# Reproduction of Adult dataset experiments

In this notebook we reproduce the results from Table 2 of the DECAF paper. We compare various methods for generating debiased data using the DECAF model against synthetic data generated using benchmark models GAN, WGAN-GP and FairGAN. As described in the paper we run all experiments (as implemented in this notebook) 10 times and avarage the results.

In [1]:
with open('repNum.txt',"r") as f:
    repNum = f.read().strip()
    repNum = float(repNum)

In [2]:
repNum

9.0

In [3]:
from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.metrics import confusion_matrix


from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

from data import load_adult, preprocess_adult
from metrics import DP, FTU
from train import train_decaf, train_fairgan, train_vanilla_gan, train_wgan_gp

## Loading data

In [4]:
dataset = load_adult()
dataset.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516.0,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174.0,0.0,40.0,United-States,<=50K
1,50,Self-emp-not-inc,83311.0,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.0,0.0,13.0,United-States,<=50K
2,38,Private,215646.0,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.0,0.0,40.0,United-States,<=50K
3,53,Private,234721.0,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.0,0.0,40.0,United-States,<=50K
4,28,Private,338409.0,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.0,0.0,40.0,Cuba,<=50K

Preprocess the data next in order to make it suitable for training models on.

In [5]:
dataset = preprocess_adult(dataset)
dataset.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,0.301370,0.833333,0.043350,0.000000,0.800000,0.333333,0.615385,0.6,0.0,1.0,0.02174,0.0,0.397959,0.0,1.0
1,0.452055,0.166667,0.047274,0.000000,0.800000,0.000000,0.307692,0.4,0.0,1.0,0.00000,0.0,0.122449,0.0,1.0
2,0.287671,0.000000,0.136877,0.200000,0.533333,0.166667,0.461538,0.6,0.0,1.0,0.00000,0.0,0.397959,0.0,1.0
3,0.493151,0.000000,0.149792,0.133333,0.400000,0.000000,0.461538,0.4,1.0,1.0,0.00000,0.0,0.397959,0.0,1.0
4,0.150685,0.000000,0.219998,0.000000,0.800000,0.000000,0.384615,0.0,1.0,0.0,0.00000,0.0,0.397959,0.3,1.0

Split the dataset into train and test folds. Test fold size is 2000.

In [6]:
# Split data into train and testing sets
dataset_train, dataset_test = train_test_split(dataset, test_size=2000,
                                               stratify=dataset['income'])

print('Size of train set:', len(dataset_train))
print('Size of test set:', len(dataset_test))

Size of train set: 43222
Size of test set: 2000

### Defining the DAG

We need to define a DAG which captures the biases of the dataset. As described in the DECAF paper normally a causal discovery algorithm is used. In this notebook we simply copy the DAG which as described in the Zhang et al. paper which is the one also used in the DECAF paper.

In [ ]:
# Define DAG for Adult dataset
dag = [
    # Edges from race
    ['race', 'occupation'],
    ['race', 'income'],
    ['race', 'hours-per-week'],
    ['race', 'education'],
    ['race', 'marital-status'],

    # Edges from age
    ['age', 'occupation'],
    ['age', 'hours-per-week'],
    ['age', 'income'],
    ['age', 'workclass'],
    ['age', 'marital-status'],
    ['age', 'education'],
    ['age', 'relationship'],
    
    # Edges from sex
    ['sex', 'occupation'],
    ['sex', 'marital-status'],
    ['sex', 'income'],
    ['sex', 'workclass'],
    ['sex', 'education'],
    ['sex', 'relationship'],
    
    # Edges from native country
    ['native-country', 'marital-status'],
    ['native-country', 'hours-per-week'],
    ['native-country', 'education'],
    ['native-country', 'workclass'],
    ['native-country', 'income'],
    ['native-country', 'relationship'],
    
    # Edges from marital status
    ['marital-status', 'occupation'],
    ['marital-status', 'hours-per-week'],
    ['marital-status', 'income'],
    ['marital-status', 'workclass'],
    ['marital-status', 'relationship'],
    ['marital-status', 'education'],
    
    # Edges from education
    ['education', 'occupation'],
    ['education', 'hours-per-week'],
    ['education', 'income'],
    ['education', 'workclass'],
    ['education', 'relationship'],
    
    # All remaining edges
    ['occupation', 'income'],
    ['hours-per-week', 'income'],
    ['workclass', 'income'],
    ['relationship', 'income'],
]

def dag_to_idx(df, dag):
    """Convert columns in a DAG to the corresponding indices."""

    dag_idx = []
    for edge in dag:
        dag_idx.append([df.columns.get_loc(edge[0]), df.columns.get_loc(edge[1])])

    return dag_idx

# Convert the DAG to one that can be provided to the DECAF model
dag_seed = dag_to_idx(dataset, dag)
print(dag_seed)

It's also necessary to define edges we want to remove from the DAG in order to meet the various fairness criteria described in the paper.

In [ ]:
def create_bias_dict(df, edge_map):
    """
    Convert the given edge tuples to a bias dict used for generating
    debiased synthetic data.
    """
    bias_dict = {}
    for key, val in edge_map.items():
        bias_dict[df.columns.get_loc(key)] = [df.columns.get_loc(f) for f in val]
    
    return bias_dict

# Bias dictionary to satisfy FTU
bias_dict_ftu = create_bias_dict(dataset, {'income': ['sex']})
print('Bias dict FTU:', bias_dict_ftu)

# Bias dictionary to satisfy DP
bias_dict_dp = create_bias_dict(dataset, {'income': [
    'occupation', 'hours-per-week', 'marital-status', 'education', 'sex',
    'workclass', 'relationship']})
print('Bias dict DP:', bias_dict_dp)

# Bias dictionary to satisfy CF
bias_dict_cf = create_bias_dict(dataset, {'income': [
    'marital-status', 'sex']})
print('Bias dict CF:', bias_dict_cf)

## Experiments

We have loaded and preprocessed the data and we are ready to run the experiments. For each experiment we train a generative model, sample synthetic data from the trained model and then obtain metrics by training and evaluating a downstream multi-layer perceptron using the test fold we generated in the previous section. We use the MLP model from `sklearn` with default parameters which matches the settings described in Appendix D of the paper.

In [21]:
def eval_model(dataset_train, dataset_test):
    """Helper function that prints evaluation metrics."""

    X_train, y_train = dataset_train.drop(columns=['income']), dataset_train['income']
    X_test, y_test = dataset_test.drop(columns=['income']), dataset_test['income']

    clf = MLPClassifier(max_iter=1000)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    auroc = roc_auc_score(y_test, y_pred)
    dp = DP(clf, X_test)
    ftu = FTU(clf, X_test)
    conf = confusion_matrix(y_test, y_pred)

    return {'precision': precision, 'recall': recall, 'auroc': auroc,
            'dp': dp, 'ftu': ftu, "confMatrix":conf}

Make the result dict:

In [ ]:
results = {}

### Original dataset

As a benchmark we want to first train the downstream model on the original dataset.

In [ ]:
res = eval_model(dataset_train, dataset_test)
print(res)

In [ ]:
results['original'] = res

In the following sections we train various models in order to reproduce the results from Table 2 of the DECAF paper.

### GAN

In [ ]:
synth_data = train_vanilla_gan(dataset_train)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['GAN'] = res

### WGAN-GP

In [ ]:
synth_data = train_wgan_gp(dataset_train)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['WGAN-GP'] = res

### FairGAN

In [ ]:
synth_data = train_fairgan(dataset_train)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['FairGAN'] = res

### DECAF

#### DECAF-ND

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['DECAF-ND'] = res

#### DECAF-FTU

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_ftu)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['DECAF-FTU'] = res

#### DECAF-CF

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_cf)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)
print(res)

In [ ]:
results['DECAF-CF'] = res

#### DECAF-DP

In [ ]:
synth_data = train_decaf(dataset_train, dag_seed, biased_edges=bias_dict_dp)
synth_data.head()

In [ ]:
res = eval_model(synth_data, dataset_test)

In [ ]:
results['DECAF-DP'] = res

#### SpGan

In [ ]:
from spgan import spgan

In [ ]:
from importlib import reload

In [ ]:
reload(spgan)

In [7]:
class optC:
    pass

In [8]:
opt = optC()
opt.latent_dim = 40
opt.batch_size = 64
opt.lr = 0.0005
opt.n_epochs = 500
opt.n_critic = 20
opt.clip_value = 0.01

In [ ]:
import pandas as pd
def helper(lam):
    opt.lam = lam
    res = spgan.train_spgan(dataset_train.to_numpy(),opt)
    q1 = pd.DataFrame(res)
    q1.columns = dataset_train.columns
    q1['income'] = q1['income']>0.5
    res = eval_model(q1, dataset_test)
    print(res)
    return res

### Run at multiple lambdas

In [ ]:
results["spgan-0.0"] = helper(0.0)
results["spgan-0.001"] = helper(0.001)
results["spgan-0.01"] = helper(0.01)
results["spgan-0.025"] = helper(0.025)
results["spgan-0.05"] = helper(0.05)
results["spgan-0.075"] = helper(0.075)
results["spgan-0.1"] = helper(0.1)
results["spgan-1"] = helper(1.0)

In [14]:
from ifgan import ifgan
from importlib import reload
reload(ifgan)

In [17]:
opt.lam = 0.1
opt.clip_value = 0.05
q1 = ifgan.train_ifgan(dataset_train.to_numpy(),opt)

[Epoch 0/500] [Batch 0/676] [D loss: -0.049243] [G loss: 0.026962] [d1 loss: 0.747151] [d2 loss: 0.704183]  [sq d1 d2: 0.001846]  [num0: 22.000000] [num1 42.000000]
[Epoch 0/500] [Batch 20/676] [D loss: -0.193285] [G loss: 0.183723] [d1 loss: 0.700489] [d2 loss: 0.664577]  [sq d1 d2: 0.001290]  [num0: 20.000000] [num1 44.000000]
[Epoch 0/500] [Batch 40/676] [D loss: -0.396805] [G loss: 0.341277] [d1 loss: 0.643700] [d2 loss: 0.608600]  [sq d1 d2: 0.001232]  [num0: 15.000000] [num1 49.000000]
[Epoch 0/500] [Batch 60/676] [D loss: -0.684105] [G loss: 0.530043] [d1 loss: 0.596816] [d2 loss: 0.577702]  [sq d1 d2: 0.000365]  [num0: 16.000000] [num1 48.000000]
[Epoch 0/500] [Batch 80/676] [D loss: -1.064522] [G loss: 0.738464] [d1 loss: 0.542895] [d2 loss: 0.531623]  [sq d1 d2: 0.000127]  [num0: 14.000000] [num1 50.000000]
[Epoch 0/500] [Batch 100/676] [D loss: -1.227604] [G loss: 0.944726] [d1 loss: 0.507724] [d2 loss: 0.503691]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 0/500] [Batch 120/676] [D loss: -1.598571] [G loss: 1.131425] [d1 loss: 0.460045] [d2 loss: 0.459416]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 0/500] [Batch 140/676] [D loss: -1.745429] [G loss: 1.231982] [d1 loss: 0.352929] [d2 loss: 0.348035]  [sq d1 d2: 0.000024]  [num0: 7.000000] [num1 57.000000]
[Epoch 0/500] [Batch 160/676] [D loss: -1.816933] [G loss: 1.288434] [d1 loss: 0.313265] [d2 loss: 0.312111]  [sq d1 d2: 0.000001]  [num0: 6.000000] [num1 58.000000]
[Epoch 0/500] [Batch 180/676] [D loss: -1.975892] [G loss: 1.324928] [d1 loss: 0.201920] [d2 loss: 0.196710]  [sq d1 d2: 0.000027]  [num0: 3.000000] [num1 61.000000]
[Epoch 0/500] [Batch 200/676] [D loss: -2.037886] [G loss: 1.339800] [d1 loss: 0.153613] [d2 loss: 0.150384]  [sq d1 d2: 0.000010]  [num0: 2.000000] [num1 62.000000]
[Epoch 0/500] [Batch 220/676] [D loss: -1.949785] [G loss: 1.334706] [d1 loss: 0.059544] [d2 loss: 0.053606]  [sq d1 d2: 0.000035]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 240/676] [D loss: -2.112572] [G loss: 1.328501] [d1 loss: 0.142780] [d2 loss: 0.141883]  [sq d1 d2: 0.000001]  [num0: 2.000000] [num1 62.000000]
[Epoch 0/500] [Batch 260/676] [D loss: -2.185220] [G loss: 1.313946] [d1 loss: 0.039192] [d2 loss: 0.035139]  [sq d1 d2: 0.000016]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 280/676] [D loss: -2.108726] [G loss: 1.294924] [d1 loss: 0.029822] [d2 loss: 0.026321]  [sq d1 d2: 0.000012]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 300/676] [D loss: -1.929230] [G loss: 1.283903] [d1 loss: 0.024141] [d2 loss: 0.021269]  [sq d1 d2: 0.000008]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 320/676] [D loss: -1.902560] [G loss: 1.257972] [d1 loss: 0.019816] [d2 loss: 0.017478]  [sq d1 d2: 0.000005]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 340/676] [D loss: -1.971339] [G loss: 1.242487] [d1 loss: 0.016101] [d2 loss: 0.014161]  [sq d1 d2: 0.000004]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 360/676] [D loss: -1.833522] [G loss: 1.198329] [d1 loss: 0.013870] [d2 loss: 0.012308]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 380/676] [D loss: -1.829741] [G loss: 1.150855] [d1 loss: 0.082479] [d2 loss: 0.084452]  [sq d1 d2: 0.000004]  [num0: 1.000000] [num1 63.000000]
[Epoch 0/500] [Batch 400/676] [D loss: -1.816112] [G loss: 1.145787] [d1 loss: 0.009893] [d2 loss: 0.008811]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 420/676] [D loss: -1.687642] [G loss: 1.115902] [d1 loss: 0.008421] [d2 loss: 0.007506]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 440/676] [D loss: -1.672042] [G loss: 1.084289] [d1 loss: 0.007147] [d2 loss: 0.006356]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 460/676] [D loss: -1.596488] [G loss: 1.059997] [d1 loss: 0.006348] [d2 loss: 0.005704]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 480/676] [D loss: -1.510954] [G loss: 1.016480] [d1 loss: 0.005658] [d2 loss: 0.005132]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 500/676] [D loss: -1.467748] [G loss: 0.995278] [d1 loss: 0.005058] [d2 loss: 0.004619]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 520/676] [D loss: -1.377182] [G loss: 0.919280] [d1 loss: 0.004664] [d2 loss: 0.004310]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 540/676] [D loss: -1.521470] [G loss: 0.931631] [d1 loss: 0.004242] [d2 loss: 0.003948]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 560/676] [D loss: -1.490096] [G loss: 0.890887] [d1 loss: 0.003848] [d2 loss: 0.003577]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 580/676] [D loss: -1.291313] [G loss: 0.873549] [d1 loss: 0.003577] [d2 loss: 0.003406]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 600/676] [D loss: -1.258521] [G loss: 0.870963] [d1 loss: 0.003316] [d2 loss: 0.003157]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 620/676] [D loss: -1.226667] [G loss: 0.848040] [d1 loss: 0.003148] [d2 loss: 0.003072]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 640/676] [D loss: -1.175900] [G loss: 0.911418] [d1 loss: 0.003010] [d2 loss: 0.002989]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 0/500] [Batch 660/676] [D loss: -1.105566] [G loss: 0.880504] [d1 loss: 0.002859] [d2 loss: 0.002881]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 0/676] [D loss: -1.054275] [G loss: 0.900831] [d1 loss: 0.002846] [d2 loss: 0.002979]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 20/676] [D loss: -0.979595] [G loss: 0.897779] [d1 loss: 0.002648] [d2 loss: 0.002695]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 40/676] [D loss: -1.081024] [G loss: 0.903223] [d1 loss: 0.002543] [d2 loss: 0.002621]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 60/676] [D loss: -0.976434] [G loss: 0.933864] [d1 loss: 0.002485] [d2 loss: 0.002635]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 80/676] [D loss: -0.981542] [G loss: 0.863275] [d1 loss: 0.002340] [d2 loss: 0.002488]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 100/676] [D loss: -0.752220] [G loss: 0.855875] [d1 loss: 0.002325] [d2 loss: 0.002602]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 120/676] [D loss: -0.820165] [G loss: 0.830046] [d1 loss: 0.002083] [d2 loss: 0.002273]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 140/676] [D loss: -0.742868] [G loss: 0.813649] [d1 loss: 0.001985] [d2 loss: 0.002156]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 160/676] [D loss: -0.773724] [G loss: 0.861078] [d1 loss: 0.001784] [d2 loss: 0.001918]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 180/676] [D loss: -0.858812] [G loss: 0.870032] [d1 loss: 0.001703] [d2 loss: 0.001838]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 200/676] [D loss: -0.739216] [G loss: 0.942861] [d1 loss: 0.001688] [d2 loss: 0.001862]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 220/676] [D loss: -0.804624] [G loss: 0.970457] [d1 loss: 0.001578] [d2 loss: 0.001725]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 240/676] [D loss: -0.636189] [G loss: 1.095883] [d1 loss: 0.001520] [d2 loss: 0.001637]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 260/676] [D loss: -0.722586] [G loss: 1.174893] [d1 loss: 0.001575] [d2 loss: 0.001754]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 280/676] [D loss: -0.612216] [G loss: 1.192080] [d1 loss: 0.001516] [d2 loss: 0.001668]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 300/676] [D loss: -0.662100] [G loss: 1.192348] [d1 loss: 0.001446] [d2 loss: 0.001575]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 320/676] [D loss: -0.639405] [G loss: 1.276087] [d1 loss: 0.001505] [d2 loss: 0.001679]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]

[Epoch 1/500] [Batch 340/676] [D loss: -0.636954] [G loss: 1.250431] [d1 loss: 0.001568] [d2 loss: 0.001720]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 360/676] [D loss: -0.476983] [G loss: 1.241270] [d1 loss: 0.001565] [d2 loss: 0.001755]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 380/676] [D loss: -0.445795] [G loss: 1.220881] [d1 loss: 0.001451] [d2 loss: 0.001550]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 400/676] [D loss: -0.444247] [G loss: 1.211636] [d1 loss: 0.001437] [d2 loss: 0.001554]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 420/676] [D loss: -0.478622] [G loss: 1.175015] [d1 loss: 0.001450] [d2 loss: 0.001540]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 440/676] [D loss: -0.422531] [G loss: 1.165490] [d1 loss: 0.001430] [d2 loss: 0.001510]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 460/676] [D loss: -0.390878] [G loss: 1.135453] [d1 loss: 0.001473] [d2 loss: 0.001628]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 480/676] [D loss: -0.407044] [G loss: 1.105566] [d1 loss: 0.001382] [d2 loss: 0.001475]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 500/676] [D loss: -0.382153] [G loss: 1.093693] [d1 loss: 0.001333] [d2 loss: 0.001372]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 520/676] [D loss: -0.410353] [G loss: 1.128711] [d1 loss: 0.001239] [d2 loss: 0.001239]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 540/676] [D loss: -0.286777] [G loss: 1.096027] [d1 loss: 0.001245] [d2 loss: 0.001303]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 560/676] [D loss: -0.239680] [G loss: 1.034384] [d1 loss: 0.001195] [d2 loss: 0.001188]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 580/676] [D loss: -0.256514] [G loss: 0.977653] [d1 loss: 0.001210] [d2 loss: 0.001225]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 600/676] [D loss: -0.241623] [G loss: 0.926930] [d1 loss: 0.001082] [d2 loss: 0.001008]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 620/676] [D loss: -0.170307] [G loss: 0.898268] [d1 loss: 0.001087] [d2 loss: 0.001035]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 640/676] [D loss: -0.340318] [G loss: 0.877663] [d1 loss: 0.001112] [d2 loss: 0.001046]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 1/500] [Batch 660/676] [D loss: -0.250288] [G loss: 0.858002] [d1 loss: 0.001012] [d2 loss: 0.000888]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 0/676] [D loss: -0.204693] [G loss: 0.843278] [d1 loss: 0.001020] [d2 loss: 0.000904]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 20/676] [D loss: -0.199969] [G loss: 0.868306] [d1 loss: 0.001004] [d2 loss: 0.000855]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 40/676] [D loss: -0.324547] [G loss: 0.865821] [d1 loss: 0.000903] [d2 loss: 0.000750]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 60/676] [D loss: -0.233703] [G loss: 0.802484] [d1 loss: 0.000818] [d2 loss: 0.000678]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 80/676] [D loss: -0.316536] [G loss: 0.734944] [d1 loss: 0.000881] [d2 loss: 0.000781]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 100/676] [D loss: -0.289172] [G loss: 0.673311] [d1 loss: 0.000848] [d2 loss: 0.000751]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 120/676] [D loss: -0.213261] [G loss: 0.629297] [d1 loss: 0.000890] [d2 loss: 0.000801]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 140/676] [D loss: -0.161099] [G loss: 0.603696] [d1 loss: 0.000796] [d2 loss: 0.000679]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 160/676] [D loss: -0.186302] [G loss: 0.590701] [d1 loss: 0.000721] [d2 loss: 0.000620]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 180/676] [D loss: -0.234524] [G loss: 0.559319] [d1 loss: 0.000695] [d2 loss: 0.000623]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 200/676] [D loss: -0.134217] [G loss: 0.558238] [d1 loss: 0.000714] [d2 loss: 0.000643]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 220/676] [D loss: -0.231374] [G loss: 0.581184] [d1 loss: 0.000624] [d2 loss: 0.000590]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 240/676] [D loss: -0.199866] [G loss: 0.566766] [d1 loss: 0.000610] [d2 loss: 0.000589]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 260/676] [D loss: -0.265906] [G loss: 0.571120] [d1 loss: 0.000633] [d2 loss: 0.000643]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 280/676] [D loss: -0.193965] [G loss: 0.595368] [d1 loss: 0.000604] [d2 loss: 0.000613]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 300/676] [D loss: -0.301025] [G loss: 0.598677] [d1 loss: 0.000524] [d2 loss: 0.000530]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 320/676] [D loss: -0.218780] [G loss: 0.612430] [d1 loss: 0.000547] [d2 loss: 0.000577]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 340/676] [D loss: -0.126671] [G loss: 0.608880] [d1 loss: 0.000449] [d2 loss: 0.000468]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 360/676] [D loss: -0.263015] [G loss: 0.627998] [d1 loss: 0.000465] [d2 loss: 0.000496]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 380/676] [D loss: -0.215558] [G loss: 0.617267] [d1 loss: 0.000428] [d2 loss: 0.000451]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 400/676] [D loss: -0.170515] [G loss: 0.598668] [d1 loss: 0.000448] [d2 loss: 0.000511]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 420/676] [D loss: -0.117292] [G loss: 0.567259] [d1 loss: 0.000398] [d2 loss: 0.000438]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 440/676] [D loss: -0.070433] [G loss: 0.568665] [d1 loss: 0.000357] [d2 loss: 0.000387]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 460/676] [D loss: -0.128196] [G loss: 0.556669] [d1 loss: 0.000372] [d2 loss: 0.000421]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 480/676] [D loss: -0.134293] [G loss: 0.546104] [d1 loss: 0.000350] [d2 loss: 0.000407]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 500/676] [D loss: -0.144552] [G loss: 0.518902] [d1 loss: 0.000352] [d2 loss: 0.000420]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 520/676] [D loss: -0.107410] [G loss: 0.476376] [d1 loss: 0.000325] [d2 loss: 0.000390]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 540/676] [D loss: -0.180010] [G loss: 0.445939] [d1 loss: 0.000328] [d2 loss: 0.000412]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 560/676] [D loss: -0.150059] [G loss: 0.401006] [d1 loss: 0.000348] [d2 loss: 0.000414]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 580/676] [D loss: -0.088355] [G loss: 0.333032] [d1 loss: 0.000377] [d2 loss: 0.000479]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 600/676] [D loss: -0.195466] [G loss: 0.266988] [d1 loss: 0.000393] [d2 loss: 0.000514]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 620/676] [D loss: -0.108310] [G loss: 0.242353] [d1 loss: 0.000516] [d2 loss: 0.000640]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 640/676] [D loss: -0.197733] [G loss: 0.205364] [d1 loss: 0.000646] [d2 loss: 0.000787]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 2/500] [Batch 660/676] [D loss: -0.146569] [G loss: 0.170410] [d1 loss: 0.000943] [d2 loss: 0.001254]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 0/676] [D loss: -0.157660] [G loss: 0.165204] [d1 loss: 0.001742] [d2 loss: 0.002308]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]

[Epoch 3/500] [Batch 20/676] [D loss: -0.143947] [G loss: 0.164688] [d1 loss: 0.103544] [d2 loss: 0.105862]  [sq d1 d2: 0.000005]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 40/676] [D loss: -0.138425] [G loss: 0.151547] [d1 loss: 0.003228] [d2 loss: 0.004146]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 60/676] [D loss: -0.183289] [G loss: 0.171339] [d1 loss: 0.176501] [d2 loss: 0.176190]  [sq d1 d2: 0.000000]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 80/676] [D loss: -0.132885] [G loss: 0.181400] [d1 loss: 0.009071] [d2 loss: 0.011227]  [sq d1 d2: 0.000005]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 100/676] [D loss: -0.175970] [G loss: 0.219149] [d1 loss: 0.011522] [d2 loss: 0.013540]  [sq d1 d2: 0.000004]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 120/676] [D loss: -0.134821] [G loss: 0.242897] [d1 loss: 0.156925] [d2 loss: 0.155993]  [sq d1 d2: 0.000001]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 140/676] [D loss: -0.210012] [G loss: 0.265927] [d1 loss: 0.015169] [d2 loss: 0.016669]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 160/676] [D loss: -0.216942] [G loss: 0.311633] [d1 loss: 0.074408] [d2 loss: 0.076501]  [sq d1 d2: 0.000004]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 180/676] [D loss: -0.143778] [G loss: 0.320592] [d1 loss: 0.144685] [d2 loss: 0.145575]  [sq d1 d2: 0.000001]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 200/676] [D loss: -0.181405] [G loss: 0.331586] [d1 loss: 0.137051] [d2 loss: 0.136212]  [sq d1 d2: 0.000001]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 220/676] [D loss: -0.201957] [G loss: 0.340660] [d1 loss: 0.254606] [d2 loss: 0.261125]  [sq d1 d2: 0.000042]  [num0: 4.000000] [num1 60.000000]
[Epoch 3/500] [Batch 240/676] [D loss: -0.175891] [G loss: 0.367079] [d1 loss: 0.200141] [d2 loss: 0.204865]  [sq d1 d2: 0.000022]  [num0: 3.000000] [num1 61.000000]
[Epoch 3/500] [Batch 260/676] [D loss: -0.228024] [G loss: 0.361490] [d1 loss: 0.083460] [d2 loss: 0.086243]  [sq d1 d2: 0.000008]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 280/676] [D loss: -0.167271] [G loss: 0.388698] [d1 loss: 0.023167] [d2 loss: 0.023897]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 300/676] [D loss: -0.124697] [G loss: 0.380198] [d1 loss: 0.137640] [d2 loss: 0.140170]  [sq d1 d2: 0.000006]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 320/676] [D loss: -0.125204] [G loss: 0.384340] [d1 loss: 0.078632] [d2 loss: 0.080312]  [sq d1 d2: 0.000003]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 340/676] [D loss: -0.137669] [G loss: 0.349404] [d1 loss: 0.021138] [d2 loss: 0.022153]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 360/676] [D loss: -0.084220] [G loss: 0.337049] [d1 loss: 0.198524] [d2 loss: 0.203085]  [sq d1 d2: 0.000021]  [num0: 3.000000] [num1 61.000000]
[Epoch 3/500] [Batch 380/676] [D loss: -0.094466] [G loss: 0.303623] [d1 loss: 0.199347] [d2 loss: 0.202543]  [sq d1 d2: 0.000010]  [num0: 3.000000] [num1 61.000000]
[Epoch 3/500] [Batch 400/676] [D loss: -0.120467] [G loss: 0.276059] [d1 loss: 0.205440] [d2 loss: 0.208968]  [sq d1 d2: 0.000012]  [num0: 3.000000] [num1 61.000000]
[Epoch 3/500] [Batch 420/676] [D loss: -0.163537] [G loss: 0.256375] [d1 loss: 0.082263] [d2 loss: 0.085021]  [sq d1 d2: 0.000008]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 440/676] [D loss: -0.167507] [G loss: 0.236277] [d1 loss: 0.158568] [d2 loss: 0.165231]  [sq d1 d2: 0.000044]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 460/676] [D loss: -0.176419] [G loss: 0.248814] [d1 loss: 0.152753] [d2 loss: 0.156150]  [sq d1 d2: 0.000012]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 480/676] [D loss: -0.119248] [G loss: 0.269244] [d1 loss: 0.014375] [d2 loss: 0.014904]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 500/676] [D loss: -0.157151] [G loss: 0.264753] [d1 loss: 0.013358] [d2 loss: 0.013674]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 520/676] [D loss: -0.129179] [G loss: 0.256922] [d1 loss: 0.087038] [d2 loss: 0.093197]  [sq d1 d2: 0.000038]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 540/676] [D loss: -0.160601] [G loss: 0.266646] [d1 loss: 0.012487] [d2 loss: 0.013077]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 560/676] [D loss: -0.209432] [G loss: 0.281738] [d1 loss: 0.134551] [d2 loss: 0.139915]  [sq d1 d2: 0.000029]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 580/676] [D loss: -0.175855] [G loss: 0.286110] [d1 loss: 0.155681] [d2 loss: 0.160858]  [sq d1 d2: 0.000027]  [num0: 2.000000] [num1 62.000000]
[Epoch 3/500] [Batch 600/676] [D loss: -0.111133] [G loss: 0.254535] [d1 loss: 0.071400] [d2 loss: 0.077441]  [sq d1 d2: 0.000036]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 620/676] [D loss: -0.145649] [G loss: 0.252634] [d1 loss: 0.074269] [d2 loss: 0.079868]  [sq d1 d2: 0.000031]  [num0: 1.000000] [num1 63.000000]
[Epoch 3/500] [Batch 640/676] [D loss: -0.081777] [G loss: 0.248513] [d1 loss: 0.015342] [d2 loss: 0.016582]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 3/500] [Batch 660/676] [D loss: -0.153138] [G loss: 0.255038] [d1 loss: 0.083123] [d2 loss: 0.086779]  [sq d1 d2: 0.000013]  [num0: 1.000000] [num1 63.000000]
[Epoch 4/500] [Batch 0/676] [D loss: -0.094325] [G loss: 0.255734] [d1 loss: 0.152024] [d2 loss: 0.158395]  [sq d1 d2: 0.000041]  [num0: 2.000000] [num1 62.000000]
[Epoch 4/500] [Batch 20/676] [D loss: -0.129478] [G loss: 0.259451] [d1 loss: 0.079830] [d2 loss: 0.084493]  [sq d1 d2: 0.000022]  [num0: 1.000000] [num1 63.000000]
[Epoch 4/500] [Batch 40/676] [D loss: -0.129712] [G loss: 0.261333] [d1 loss: 0.138558] [d2 loss: 0.147856]  [sq d1 d2: 0.000086]  [num0: 2.000000] [num1 62.000000]
[Epoch 4/500] [Batch 60/676] [D loss: -0.131303] [G loss: 0.251624] [d1 loss: 0.133996] [d2 loss: 0.144873]  [sq d1 d2: 0.000118]  [num0: 2.000000] [num1 62.000000]
[Epoch 4/500] [Batch 80/676] [D loss: -0.143799] [G loss: 0.245842] [d1 loss: 0.199051] [d2 loss: 0.211835]  [sq d1 d2: 0.000163]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 100/676] [D loss: -0.100993] [G loss: 0.240973] [d1 loss: 0.027330] [d2 loss: 0.030705]  [sq d1 d2: 0.000011]  [num0: 0.000000] [num1 64.000000]
[Epoch 4/500] [Batch 120/676] [D loss: -0.123679] [G loss: 0.226561] [d1 loss: 0.084305] [d2 loss: 0.091433]  [sq d1 d2: 0.000051]  [num0: 1.000000] [num1 63.000000]
[Epoch 4/500] [Batch 140/676] [D loss: -0.173110] [G loss: 0.208541] [d1 loss: 0.138562] [d2 loss: 0.149065]  [sq d1 d2: 0.000110]  [num0: 2.000000] [num1 62.000000]
[Epoch 4/500] [Batch 160/676] [D loss: -0.105722] [G loss: 0.201456] [d1 loss: 0.184430] [d2 loss: 0.202770]  [sq d1 d2: 0.000336]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 180/676] [D loss: -0.116647] [G loss: 0.191758] [d1 loss: 0.274715] [d2 loss: 0.299648]  [sq d1 d2: 0.000622]  [num0: 5.000000] [num1 59.000000]
[Epoch 4/500] [Batch 200/676] [D loss: -0.101589] [G loss: 0.176171] [d1 loss: 0.220137] [d2 loss: 0.247925]  [sq d1 d2: 0.000772]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 220/676] [D loss: -0.092858] [G loss: 0.180477] [d1 loss: 0.095415] [d2 loss: 0.101336]  [sq d1 d2: 0.000035]  [num0: 1.000000] [num1 63.000000]
[Epoch 4/500] [Batch 240/676] [D loss: -0.168301] [G loss: 0.185228] [d1 loss: 0.134680] [d2 loss: 0.153626]  [sq d1 d2: 0.000359]  [num0: 2.000000] [num1 62.000000]
[Epoch 4/500] [Batch 260/676] [D loss: -0.122733] [G loss: 0.188787] [d1 loss: 0.183106] [d2 loss: 0.193869]  [sq d1 d2: 0.000116]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 280/676] [D loss: -0.158809] [G loss: 0.196725] [d1 loss: 0.175064] [d2 loss: 0.192891]  [sq d1 d2: 0.000318]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 300/676] [D loss: -0.089621] [G loss: 0.205483] [d1 loss: 0.275976] [d2 loss: 0.304074]  [sq d1 d2: 0.000789]  [num0: 6.000000] [num1 58.000000]
[Epoch 4/500] [Batch 320/676] [D loss: -0.073954] [G loss: 0.208186] [d1 loss: 0.161318] [d2 loss: 0.190526]  [sq d1 d2: 0.000853]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 340/676] [D loss: -0.081919] [G loss: 0.217324] [d1 loss: 0.236275] [d2 loss: 0.264115]  [sq d1 d2: 0.000775]  [num0: 5.000000] [num1 59.000000]
[Epoch 4/500] [Batch 360/676] [D loss: -0.098059] [G loss: 0.207769] [d1 loss: 0.296706] [d2 loss: 0.333186]  [sq d1 d2: 0.001331]  [num0: 7.000000] [num1 57.000000]

[Epoch 4/500] [Batch 380/676] [D loss: -0.101742] [G loss: 0.214328] [d1 loss: 0.249015] [d2 loss: 0.294918]  [sq d1 d2: 0.002107]  [num0: 6.000000] [num1 58.000000]
[Epoch 4/500] [Batch 400/676] [D loss: -0.110314] [G loss: 0.196634] [d1 loss: 0.263813] [d2 loss: 0.315481]  [sq d1 d2: 0.002670]  [num0: 7.000000] [num1 57.000000]
[Epoch 4/500] [Batch 420/676] [D loss: -0.084561] [G loss: 0.185766] [d1 loss: 0.201610] [d2 loss: 0.225696]  [sq d1 d2: 0.000580]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 440/676] [D loss: -0.106705] [G loss: 0.187556] [d1 loss: 0.234751] [d2 loss: 0.286618]  [sq d1 d2: 0.002690]  [num0: 6.000000] [num1 58.000000]
[Epoch 4/500] [Batch 460/676] [D loss: -0.111224] [G loss: 0.214834] [d1 loss: 0.228673] [d2 loss: 0.278829]  [sq d1 d2: 0.002516]  [num0: 6.000000] [num1 58.000000]
[Epoch 4/500] [Batch 480/676] [D loss: -0.165818] [G loss: 0.192678] [d1 loss: 0.202169] [d2 loss: 0.264260]  [sq d1 d2: 0.003855]  [num0: 6.000000] [num1 58.000000]
[Epoch 4/500] [Batch 500/676] [D loss: -0.140518] [G loss: 0.203908] [d1 loss: 0.241972] [d2 loss: 0.288474]  [sq d1 d2: 0.002162]  [num0: 7.000000] [num1 57.000000]
[Epoch 4/500] [Batch 520/676] [D loss: -0.119144] [G loss: 0.215293] [d1 loss: 0.144168] [d2 loss: 0.167506]  [sq d1 d2: 0.000545]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 540/676] [D loss: -0.158776] [G loss: 0.186195] [d1 loss: 0.165805] [d2 loss: 0.213173]  [sq d1 d2: 0.002244]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 560/676] [D loss: -0.118226] [G loss: 0.186996] [d1 loss: 0.246939] [d2 loss: 0.337497]  [sq d1 d2: 0.008201]  [num0: 9.000000] [num1 55.000000]
[Epoch 4/500] [Batch 580/676] [D loss: -0.133372] [G loss: 0.183724] [d1 loss: 0.129286] [d2 loss: 0.186871]  [sq d1 d2: 0.003316]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 600/676] [D loss: -0.119351] [G loss: 0.204064] [d1 loss: 0.143003] [d2 loss: 0.195789]  [sq d1 d2: 0.002786]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 620/676] [D loss: -0.134713] [G loss: 0.200576] [d1 loss: 0.139876] [d2 loss: 0.199598]  [sq d1 d2: 0.003567]  [num0: 4.000000] [num1 60.000000]
[Epoch 4/500] [Batch 640/676] [D loss: -0.117683] [G loss: 0.198226] [d1 loss: 0.152208] [d2 loss: 0.158934]  [sq d1 d2: 0.000045]  [num0: 3.000000] [num1 61.000000]
[Epoch 4/500] [Batch 660/676] [D loss: -0.107880] [G loss: 0.203009] [d1 loss: 0.081142] [d2 loss: 0.085434]  [sq d1 d2: 0.000018]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 0/676] [D loss: -0.155405] [G loss: 0.190834] [d1 loss: 0.103859] [d2 loss: 0.134487]  [sq d1 d2: 0.000938]  [num0: 2.000000] [num1 62.000000]
[Epoch 5/500] [Batch 20/676] [D loss: -0.132424] [G loss: 0.193407] [d1 loss: 0.098130] [d2 loss: 0.125119]  [sq d1 d2: 0.000728]  [num0: 2.000000] [num1 62.000000]
[Epoch 5/500] [Batch 40/676] [D loss: -0.110136] [G loss: 0.194218] [d1 loss: 0.067678] [d2 loss: 0.082265]  [sq d1 d2: 0.000213]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 60/676] [D loss: -0.092529] [G loss: 0.204363] [d1 loss: 0.016305] [d2 loss: 0.019512]  [sq d1 d2: 0.000010]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 80/676] [D loss: -0.120885] [G loss: 0.207224] [d1 loss: 0.075208] [d2 loss: 0.071392]  [sq d1 d2: 0.000015]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 100/676] [D loss: -0.091326] [G loss: 0.200472] [d1 loss: 0.013323] [d2 loss: 0.017512]  [sq d1 d2: 0.000018]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 120/676] [D loss: -0.092891] [G loss: 0.208465] [d1 loss: 0.015241] [d2 loss: 0.017382]  [sq d1 d2: 0.000005]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 140/676] [D loss: -0.107689] [G loss: 0.201973] [d1 loss: 0.086243] [d2 loss: 0.070204]  [sq d1 d2: 0.000257]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 160/676] [D loss: -0.079240] [G loss: 0.209859] [d1 loss: 0.016315] [d2 loss: 0.015871]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 180/676] [D loss: -0.094586] [G loss: 0.212057] [d1 loss: 0.058694] [d2 loss: 0.072608]  [sq d1 d2: 0.000194]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 200/676] [D loss: -0.094403] [G loss: 0.207774] [d1 loss: 0.010443] [d2 loss: 0.012280]  [sq d1 d2: 0.000003]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 220/676] [D loss: -0.071772] [G loss: 0.232430] [d1 loss: 0.047072] [d2 loss: 0.067571]  [sq d1 d2: 0.000420]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 240/676] [D loss: -0.096612] [G loss: 0.199773] [d1 loss: 0.009184] [d2 loss: 0.011191]  [sq d1 d2: 0.000004]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 260/676] [D loss: -0.062784] [G loss: 0.207097] [d1 loss: 0.010856] [d2 loss: 0.013145]  [sq d1 d2: 0.000005]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 280/676] [D loss: -0.103015] [G loss: 0.196108] [d1 loss: 0.104671] [d2 loss: 0.132160]  [sq d1 d2: 0.000756]  [num0: 2.000000] [num1 62.000000]
[Epoch 5/500] [Batch 300/676] [D loss: -0.066065] [G loss: 0.192784] [d1 loss: 0.056445] [d2 loss: 0.075109]  [sq d1 d2: 0.000348]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 320/676] [D loss: -0.088919] [G loss: 0.205613] [d1 loss: 0.010116] [d2 loss: 0.011512]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 340/676] [D loss: -0.117475] [G loss: 0.214078] [d1 loss: 0.047741] [d2 loss: 0.059251]  [sq d1 d2: 0.000132]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 360/676] [D loss: -0.113541] [G loss: 0.230637] [d1 loss: 0.012077] [d2 loss: 0.012691]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 380/676] [D loss: -0.128877] [G loss: 0.235651] [d1 loss: 0.059518] [d2 loss: 0.069241]  [sq d1 d2: 0.000095]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 400/676] [D loss: -0.140148] [G loss: 0.261886] [d1 loss: 0.131987] [d2 loss: 0.144102]  [sq d1 d2: 0.000147]  [num0: 2.000000] [num1 62.000000]
[Epoch 5/500] [Batch 420/676] [D loss: -0.107853] [G loss: 0.240582] [d1 loss: 0.045257] [d2 loss: 0.066195]  [sq d1 d2: 0.000438]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 440/676] [D loss: -0.075055] [G loss: 0.256822] [d1 loss: 0.009985] [d2 loss: 0.012969]  [sq d1 d2: 0.000009]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 460/676] [D loss: -0.122890] [G loss: 0.266563] [d1 loss: 0.093810] [d2 loss: 0.108604]  [sq d1 d2: 0.000219]  [num0: 2.000000] [num1 62.000000]
[Epoch 5/500] [Batch 480/676] [D loss: -0.113128] [G loss: 0.275056] [d1 loss: 0.014087] [d2 loss: 0.016480]  [sq d1 d2: 0.000006]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 500/676] [D loss: -0.100822] [G loss: 0.262584] [d1 loss: 0.013997] [d2 loss: 0.014650]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 520/676] [D loss: -0.129765] [G loss: 0.275268] [d1 loss: 0.054514] [d2 loss: 0.060458]  [sq d1 d2: 0.000035]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 540/676] [D loss: -0.146917] [G loss: 0.256146] [d1 loss: 0.049135] [d2 loss: 0.062768]  [sq d1 d2: 0.000186]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 560/676] [D loss: -0.136015] [G loss: 0.259413] [d1 loss: 0.066605] [d2 loss: 0.061960]  [sq d1 d2: 0.000022]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 580/676] [D loss: -0.098540] [G loss: 0.255718] [d1 loss: 0.064253] [d2 loss: 0.075103]  [sq d1 d2: 0.000118]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 600/676] [D loss: -0.118001] [G loss: 0.228638] [d1 loss: 0.026959] [d2 loss: 0.025941]  [sq d1 d2: 0.000001]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 620/676] [D loss: -0.100295] [G loss: 0.258304] [d1 loss: 0.053482] [d2 loss: 0.062651]  [sq d1 d2: 0.000084]  [num0: 1.000000] [num1 63.000000]
[Epoch 5/500] [Batch 640/676] [D loss: -0.150482] [G loss: 0.239710] [d1 loss: 0.019563] [d2 loss: 0.019417]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 5/500] [Batch 660/676] [D loss: -0.066305] [G loss: 0.226664] [d1 loss: 0.083354] [d2 loss: 0.071022]  [sq d1 d2: 0.000152]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 0/676] [D loss: -0.121429] [G loss: 0.210847] [d1 loss: 0.050700] [d2 loss: 0.053452]  [sq d1 d2: 0.000008]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 20/676] [D loss: -0.093777] [G loss: 0.230493] [d1 loss: 0.199579] [d2 loss: 0.169432]  [sq d1 d2: 0.000909]  [num0: 4.000000] [num1 60.000000]
[Epoch 6/500] [Batch 40/676] [D loss: -0.044844] [G loss: 0.263514] [d1 loss: 0.068611] [d2 loss: 0.060355]  [sq d1 d2: 0.000068]  [num0: 1.000000] [num1 63.000000]

[Epoch 6/500] [Batch 60/676] [D loss: -0.091254] [G loss: 0.243146] [d1 loss: 0.028931] [d2 loss: 0.029386]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 80/676] [D loss: -0.060869] [G loss: 0.222619] [d1 loss: 0.053783] [d2 loss: 0.064552]  [sq d1 d2: 0.000116]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 100/676] [D loss: -0.115902] [G loss: 0.259873] [d1 loss: 0.104900] [d2 loss: 0.095408]  [sq d1 d2: 0.000090]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 120/676] [D loss: -0.110989] [G loss: 0.279974] [d1 loss: 0.065119] [d2 loss: 0.073562]  [sq d1 d2: 0.000071]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 140/676] [D loss: -0.118016] [G loss: 0.295837] [d1 loss: 0.015050] [d2 loss: 0.014433]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 160/676] [D loss: -0.102624] [G loss: 0.322686] [d1 loss: 0.145113] [d2 loss: 0.133079]  [sq d1 d2: 0.000145]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 180/676] [D loss: -0.148457] [G loss: 0.297983] [d1 loss: 0.112718] [d2 loss: 0.103678]  [sq d1 d2: 0.000082]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 200/676] [D loss: -0.085508] [G loss: 0.276192] [d1 loss: 0.014936] [d2 loss: 0.015362]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 220/676] [D loss: -0.106736] [G loss: 0.298158] [d1 loss: 0.109491] [d2 loss: 0.106429]  [sq d1 d2: 0.000009]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 240/676] [D loss: -0.082586] [G loss: 0.286555] [d1 loss: 0.133771] [d2 loss: 0.120047]  [sq d1 d2: 0.000188]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 260/676] [D loss: -0.112892] [G loss: 0.269690] [d1 loss: 0.070627] [d2 loss: 0.064931]  [sq d1 d2: 0.000032]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 280/676] [D loss: -0.065507] [G loss: 0.277370] [d1 loss: 0.021010] [d2 loss: 0.019678]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 300/676] [D loss: -0.088785] [G loss: 0.295099] [d1 loss: 0.017297] [d2 loss: 0.019086]  [sq d1 d2: 0.000003]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 320/676] [D loss: -0.059975] [G loss: 0.305865] [d1 loss: 0.132176] [d2 loss: 0.095165]  [sq d1 d2: 0.001370]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 340/676] [D loss: -0.102010] [G loss: 0.285604] [d1 loss: 0.059472] [d2 loss: 0.051254]  [sq d1 d2: 0.000068]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 360/676] [D loss: -0.058255] [G loss: 0.300405] [d1 loss: 0.012257] [d2 loss: 0.012910]  [sq d1 d2: 0.000000]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 380/676] [D loss: -0.108502] [G loss: 0.321411] [d1 loss: 0.011767] [d2 loss: 0.013082]  [sq d1 d2: 0.000002]  [num0: 0.000000] [num1 64.000000]
[Epoch 6/500] [Batch 400/676] [D loss: -0.092495] [G loss: 0.319466] [d1 loss: 0.066684] [d2 loss: 0.070126]  [sq d1 d2: 0.000012]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 420/676] [D loss: -0.056174] [G loss: 0.324262] [d1 loss: 0.337417] [d2 loss: 0.296709]  [sq d1 d2: 0.001657]  [num0: 5.000000] [num1 59.000000]
[Epoch 6/500] [Batch 440/676] [D loss: -0.128150] [G loss: 0.283432] [d1 loss: 0.089438] [d2 loss: 0.069757]  [sq d1 d2: 0.000387]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 460/676] [D loss: -0.030811] [G loss: 0.279749] [d1 loss: 0.108558] [d2 loss: 0.085418]  [sq d1 d2: 0.000535]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 480/676] [D loss: -0.079733] [G loss: 0.306386] [d1 loss: 0.055885] [d2 loss: 0.049293]  [sq d1 d2: 0.000043]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 500/676] [D loss: -0.099282] [G loss: 0.309255] [d1 loss: 0.083151] [d2 loss: 0.072794]  [sq d1 d2: 0.000107]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 520/676] [D loss: -0.094694] [G loss: 0.344574] [d1 loss: 0.052367] [d2 loss: 0.047561]  [sq d1 d2: 0.000023]  [num0: 1.000000] [num1 63.000000]
[Epoch 6/500] [Batch 540/676] [D loss: -0.053138] [G loss: 0.401197] [d1 loss: 0.113895] [d2 loss: 0.092626]  [sq d1 d2: 0.000452]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 560/676] [D loss: -0.085261] [G loss: 0.386829] [d1 loss: 0.178602] [d2 loss: 0.146930]  [sq d1 d2: 0.001003]  [num0: 4.000000] [num1 60.000000]
[Epoch 6/500] [Batch 580/676] [D loss: -0.079126] [G loss: 0.407181] [d1 loss: 0.083789] [d2 loss: 0.075000]  [sq d1 d2: 0.000077]  [num0: 2.000000] [num1 62.000000]
[Epoch 6/500] [Batch 600/676] [D loss: -0.072820] [G loss: 0.405327] [d1 loss: 0.112697] [d2 loss: 0.100925]  [sq d1 d2: 0.000139]  [num0: 3.000000] [num1 61.000000]
[Epoch 6/500] [Batch 620/676] [D loss: -0.050452] [G loss: 0.425892] [d1 loss: 0.127351] [d2 loss: 0.111746]  [sq d1 d2: 0.000244]  [num0: 3.000000] [num1 61.000000]
[Epoch 6/500] [Batch 640/676] [D loss: -0.058089] [G loss: 0.404563] [d1 loss: 0.140652] [d2 loss: 0.133324]  [sq d1 d2: 0.000054]  [num0: 4.000000] [num1 60.000000]
[Epoch 6/500] [Batch 660/676] [D loss: -0.071181] [G loss: 0.430929] [d1 loss: 0.140769] [d2 loss: 0.130390]  [sq d1 d2: 0.000108]  [num0: 3.000000] [num1 61.000000]
[Epoch 7/500] [Batch 0/676] [D loss: -0.083491] [G loss: 0.425582] [d1 loss: 0.126004] [d2 loss: 0.112862]  [sq d1 d2: 0.000173]  [num0: 3.000000] [num1 61.000000]
[Epoch 7/500] [Batch 20/676] [D loss: -0.051143] [G loss: 0.402150] [d1 loss: 0.188147] [d2 loss: 0.170344]  [sq d1 d2: 0.000317]  [num0: 5.000000] [num1 59.000000]
[Epoch 7/500] [Batch 40/676] [D loss: -0.095143] [G loss: 0.369151] [d1 loss: 0.179925] [d2 loss: 0.164091]  [sq d1 d2: 0.000251]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 60/676] [D loss: -0.145710] [G loss: 0.304705] [d1 loss: 0.243476] [d2 loss: 0.209929]  [sq d1 d2: 0.001125]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 80/676] [D loss: -0.117251] [G loss: 0.253970] [d1 loss: 0.175123] [d2 loss: 0.164463]  [sq d1 d2: 0.000114]  [num0: 5.000000] [num1 59.000000]
[Epoch 7/500] [Batch 100/676] [D loss: -0.124335] [G loss: 0.228991] [d1 loss: 0.181871] [d2 loss: 0.173006]  [sq d1 d2: 0.000079]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 120/676] [D loss: -0.072747] [G loss: 0.237234] [d1 loss: 0.187478] [d2 loss: 0.170218]  [sq d1 d2: 0.000298]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 140/676] [D loss: -0.137578] [G loss: 0.235662] [d1 loss: 0.135747] [d2 loss: 0.127370]  [sq d1 d2: 0.000070]  [num0: 3.000000] [num1 61.000000]
[Epoch 7/500] [Batch 160/676] [D loss: -0.119340] [G loss: 0.224323] [d1 loss: 0.131952] [d2 loss: 0.128639]  [sq d1 d2: 0.000011]  [num0: 5.000000] [num1 59.000000]
[Epoch 7/500] [Batch 180/676] [D loss: -0.046213] [G loss: 0.214018] [d1 loss: 0.133069] [d2 loss: 0.120739]  [sq d1 d2: 0.000152]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 200/676] [D loss: -0.028115] [G loss: 0.215581] [d1 loss: 0.137502] [d2 loss: 0.128254]  [sq d1 d2: 0.000086]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 220/676] [D loss: -0.046525] [G loss: 0.199550] [d1 loss: 0.140967] [d2 loss: 0.127905]  [sq d1 d2: 0.000171]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 240/676] [D loss: -0.055956] [G loss: 0.215526] [d1 loss: 0.149183] [d2 loss: 0.141111]  [sq d1 d2: 0.000065]  [num0: 4.000000] [num1 60.000000]
[Epoch 7/500] [Batch 260/676] [D loss: -0.056235] [G loss: 0.230627] [d1 loss: 0.183802] [d2 loss: 0.175394]  [sq d1 d2: 0.000071]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 280/676] [D loss: -0.081251] [G loss: 0.265037] [d1 loss: 0.254281] [d2 loss: 0.222164]  [sq d1 d2: 0.001031]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 300/676] [D loss: -0.131923] [G loss: 0.274540] [d1 loss: 0.201837] [d2 loss: 0.182371]  [sq d1 d2: 0.000379]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 320/676] [D loss: -0.099310] [G loss: 0.289842] [d1 loss: 0.154844] [d2 loss: 0.137814]  [sq d1 d2: 0.000290]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 340/676] [D loss: -0.120304] [G loss: 0.333568] [d1 loss: 0.206043] [d2 loss: 0.205605]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 7/500] [Batch 360/676] [D loss: -0.099346] [G loss: 0.364588] [d1 loss: 0.220819] [d2 loss: 0.195903]  [sq d1 d2: 0.000621]  [num0: 11.000000] [num1 53.000000]
[Epoch 7/500] [Batch 380/676] [D loss: -0.126405] [G loss: 0.291349] [d1 loss: 0.130755] [d2 loss: 0.122445]  [sq d1 d2: 0.000069]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 400/676] [D loss: -0.149611] [G loss: 0.287254] [d1 loss: 0.110810] [d2 loss: 0.112586]  [sq d1 d2: 0.000003]  [num0: 8.000000] [num1 56.000000]

[Epoch 7/500] [Batch 420/676] [D loss: -0.089367] [G loss: 0.249519] [d1 loss: 0.172776] [d2 loss: 0.165485]  [sq d1 d2: 0.000053]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 440/676] [D loss: -0.044177] [G loss: 0.253833] [d1 loss: 0.142273] [d2 loss: 0.127570]  [sq d1 d2: 0.000216]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 460/676] [D loss: -0.044650] [G loss: 0.187214] [d1 loss: 0.168014] [d2 loss: 0.148950]  [sq d1 d2: 0.000363]  [num0: 7.000000] [num1 57.000000]
[Epoch 7/500] [Batch 480/676] [D loss: -0.048171] [G loss: 0.165998] [d1 loss: 0.091181] [d2 loss: 0.089652]  [sq d1 d2: 0.000002]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 500/676] [D loss: -0.034053] [G loss: 0.139050] [d1 loss: 0.246213] [d2 loss: 0.225966]  [sq d1 d2: 0.000410]  [num0: 13.000000] [num1 51.000000]
[Epoch 7/500] [Batch 520/676] [D loss: -0.035859] [G loss: 0.111318] [d1 loss: 0.117591] [d2 loss: 0.106777]  [sq d1 d2: 0.000117]  [num0: 5.000000] [num1 59.000000]
[Epoch 7/500] [Batch 540/676] [D loss: -0.025522] [G loss: 0.093407] [d1 loss: 0.129245] [d2 loss: 0.112990]  [sq d1 d2: 0.000264]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 560/676] [D loss: -0.045364] [G loss: 0.109661] [d1 loss: 0.091585] [d2 loss: 0.091639]  [sq d1 d2: 0.000000]  [num0: 4.000000] [num1 60.000000]
[Epoch 7/500] [Batch 580/676] [D loss: -0.084442] [G loss: 0.111170] [d1 loss: 0.192821] [d2 loss: 0.177889]  [sq d1 d2: 0.000223]  [num0: 4.000000] [num1 60.000000]
[Epoch 7/500] [Batch 600/676] [D loss: -0.054523] [G loss: 0.141380] [d1 loss: 0.167140] [d2 loss: 0.149816]  [sq d1 d2: 0.000300]  [num0: 8.000000] [num1 56.000000]
[Epoch 7/500] [Batch 620/676] [D loss: -0.094335] [G loss: 0.164200] [d1 loss: 0.071139] [d2 loss: 0.073770]  [sq d1 d2: 0.000007]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 640/676] [D loss: -0.111043] [G loss: 0.162789] [d1 loss: 0.117525] [d2 loss: 0.112723]  [sq d1 d2: 0.000023]  [num0: 6.000000] [num1 58.000000]
[Epoch 7/500] [Batch 660/676] [D loss: -0.118504] [G loss: 0.203871] [d1 loss: 0.144366] [d2 loss: 0.140863]  [sq d1 d2: 0.000012]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 0/676] [D loss: -0.098528] [G loss: 0.187512] [d1 loss: 0.142673] [d2 loss: 0.139734]  [sq d1 d2: 0.000009]  [num0: 5.000000] [num1 59.000000]
[Epoch 8/500] [Batch 20/676] [D loss: -0.115232] [G loss: 0.205057] [d1 loss: 0.110776] [d2 loss: 0.103912]  [sq d1 d2: 0.000047]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 40/676] [D loss: -0.070077] [G loss: 0.219293] [d1 loss: 0.152022] [d2 loss: 0.141512]  [sq d1 d2: 0.000110]  [num0: 6.000000] [num1 58.000000]
[Epoch 8/500] [Batch 60/676] [D loss: -0.086490] [G loss: 0.208097] [d1 loss: 0.107088] [d2 loss: 0.095129]  [sq d1 d2: 0.000143]  [num0: 4.000000] [num1 60.000000]
[Epoch 8/500] [Batch 80/676] [D loss: -0.093921] [G loss: 0.220367] [d1 loss: 0.193636] [d2 loss: 0.181069]  [sq d1 d2: 0.000158]  [num0: 6.000000] [num1 58.000000]
[Epoch 8/500] [Batch 100/676] [D loss: -0.023349] [G loss: 0.225035] [d1 loss: 0.127382] [d2 loss: 0.121818]  [sq d1 d2: 0.000031]  [num0: 6.000000] [num1 58.000000]
[Epoch 8/500] [Batch 120/676] [D loss: -0.071515] [G loss: 0.246879] [d1 loss: 0.074310] [d2 loss: 0.079202]  [sq d1 d2: 0.000024]  [num0: 5.000000] [num1 59.000000]
[Epoch 8/500] [Batch 140/676] [D loss: -0.078784] [G loss: 0.239640] [d1 loss: 0.163637] [d2 loss: 0.160028]  [sq d1 d2: 0.000013]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 160/676] [D loss: -0.008911] [G loss: 0.250350] [d1 loss: 0.113296] [d2 loss: 0.119989]  [sq d1 d2: 0.000045]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 180/676] [D loss: -0.018029] [G loss: 0.214820] [d1 loss: 0.167361] [d2 loss: 0.155783]  [sq d1 d2: 0.000134]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 200/676] [D loss: -0.017406] [G loss: 0.221091] [d1 loss: 0.178929] [d2 loss: 0.184610]  [sq d1 d2: 0.000032]  [num0: 10.000000] [num1 54.000000]
[Epoch 8/500] [Batch 220/676] [D loss: -0.055275] [G loss: 0.233219] [d1 loss: 0.166671] [d2 loss: 0.172817]  [sq d1 d2: 0.000038]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 240/676] [D loss: -0.050480] [G loss: 0.242850] [d1 loss: 0.141450] [d2 loss: 0.145590]  [sq d1 d2: 0.000017]  [num0: 9.000000] [num1 55.000000]
[Epoch 8/500] [Batch 260/676] [D loss: -0.080413] [G loss: 0.265280] [d1 loss: 0.135266] [d2 loss: 0.139456]  [sq d1 d2: 0.000018]  [num0: 10.000000] [num1 54.000000]
[Epoch 8/500] [Batch 280/676] [D loss: -0.103157] [G loss: 0.276547] [d1 loss: 0.141911] [d2 loss: 0.152949]  [sq d1 d2: 0.000122]  [num0: 13.000000] [num1 51.000000]
[Epoch 8/500] [Batch 300/676] [D loss: -0.099403] [G loss: 0.263122] [d1 loss: 0.166914] [d2 loss: 0.177177]  [sq d1 d2: 0.000105]  [num0: 11.000000] [num1 53.000000]
[Epoch 8/500] [Batch 320/676] [D loss: -0.116354] [G loss: 0.251497] [d1 loss: 0.157315] [d2 loss: 0.153284]  [sq d1 d2: 0.000016]  [num0: 11.000000] [num1 53.000000]
[Epoch 8/500] [Batch 340/676] [D loss: -0.091593] [G loss: 0.239932] [d1 loss: 0.165087] [d2 loss: 0.155581]  [sq d1 d2: 0.000090]  [num0: 9.000000] [num1 55.000000]
[Epoch 8/500] [Batch 360/676] [D loss: -0.089279] [G loss: 0.264854] [d1 loss: 0.126358] [d2 loss: 0.121881]  [sq d1 d2: 0.000020]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 380/676] [D loss: -0.116596] [G loss: 0.250978] [d1 loss: 0.117469] [d2 loss: 0.113450]  [sq d1 d2: 0.000016]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 400/676] [D loss: -0.063034] [G loss: 0.283606] [d1 loss: 0.170048] [d2 loss: 0.172279]  [sq d1 d2: 0.000005]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 420/676] [D loss: -0.076284] [G loss: 0.292135] [d1 loss: 0.109710] [d2 loss: 0.107082]  [sq d1 d2: 0.000007]  [num0: 10.000000] [num1 54.000000]
[Epoch 8/500] [Batch 440/676] [D loss: -0.096893] [G loss: 0.288216] [d1 loss: 0.084034] [d2 loss: 0.078175]  [sq d1 d2: 0.000034]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 460/676] [D loss: -0.076463] [G loss: 0.258401] [d1 loss: 0.110936] [d2 loss: 0.100463]  [sq d1 d2: 0.000110]  [num0: 7.000000] [num1 57.000000]
[Epoch 8/500] [Batch 480/676] [D loss: -0.049657] [G loss: 0.263267] [d1 loss: 0.136125] [d2 loss: 0.121226]  [sq d1 d2: 0.000222]  [num0: 6.000000] [num1 58.000000]
[Epoch 8/500] [Batch 500/676] [D loss: -0.041733] [G loss: 0.233433] [d1 loss: 0.201871] [d2 loss: 0.202839]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 8/500] [Batch 520/676] [D loss: -0.033437] [G loss: 0.222930] [d1 loss: 0.118347] [d2 loss: 0.110581]  [sq d1 d2: 0.000060]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 540/676] [D loss: -0.019059] [G loss: 0.191239] [d1 loss: 0.164146] [d2 loss: 0.161036]  [sq d1 d2: 0.000010]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 560/676] [D loss: -0.059522] [G loss: 0.171602] [d1 loss: 0.163586] [d2 loss: 0.159625]  [sq d1 d2: 0.000016]  [num0: 11.000000] [num1 53.000000]
[Epoch 8/500] [Batch 580/676] [D loss: -0.057588] [G loss: 0.155278] [d1 loss: 0.167449] [d2 loss: 0.158156]  [sq d1 d2: 0.000086]  [num0: 10.000000] [num1 54.000000]
[Epoch 8/500] [Batch 600/676] [D loss: -0.048005] [G loss: 0.116477] [d1 loss: 0.145134] [d2 loss: 0.135537]  [sq d1 d2: 0.000092]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 620/676] [D loss: -0.104349] [G loss: 0.115797] [d1 loss: 0.137300] [d2 loss: 0.146458]  [sq d1 d2: 0.000084]  [num0: 8.000000] [num1 56.000000]
[Epoch 8/500] [Batch 640/676] [D loss: -0.039107] [G loss: 0.124021] [d1 loss: 0.098118] [d2 loss: 0.098368]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 8/500] [Batch 660/676] [D loss: -0.050688] [G loss: 0.129253] [d1 loss: 0.161832] [d2 loss: 0.167260]  [sq d1 d2: 0.000029]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 0/676] [D loss: -0.077525] [G loss: 0.109925] [d1 loss: 0.136074] [d2 loss: 0.135772]  [sq d1 d2: 0.000000]  [num0: 6.000000] [num1 58.000000]
[Epoch 9/500] [Batch 20/676] [D loss: -0.041961] [G loss: 0.090106] [d1 loss: 0.095814] [d2 loss: 0.094431]  [sq d1 d2: 0.000002]  [num0: 9.000000] [num1 55.000000]
[Epoch 9/500] [Batch 40/676] [D loss: -0.074569] [G loss: 0.070917] [d1 loss: 0.172949] [d2 loss: 0.162836]  [sq d1 d2: 0.000102]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 60/676] [D loss: -0.033400] [G loss: 0.096612] [d1 loss: 0.107175] [d2 loss: 0.110367]  [sq d1 d2: 0.000010]  [num0: 7.000000] [num1 57.000000]
[Epoch 9/500] [Batch 80/676] [D loss: -0.029411] [G loss: 0.086658] [d1 loss: 0.192312] [d2 loss: 0.200150]  [sq d1 d2: 0.000061]  [num0: 5.000000] [num1 59.000000]

[Epoch 9/500] [Batch 100/676] [D loss: -0.053384] [G loss: 0.113457] [d1 loss: 0.163908] [d2 loss: 0.164987]  [sq d1 d2: 0.000001]  [num0: 7.000000] [num1 57.000000]
[Epoch 9/500] [Batch 120/676] [D loss: -0.067147] [G loss: 0.164512] [d1 loss: 0.175519] [d2 loss: 0.172756]  [sq d1 d2: 0.000008]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 140/676] [D loss: -0.065613] [G loss: 0.181061] [d1 loss: 0.094868] [d2 loss: 0.094611]  [sq d1 d2: 0.000000]  [num0: 5.000000] [num1 59.000000]
[Epoch 9/500] [Batch 160/676] [D loss: -0.069475] [G loss: 0.203601] [d1 loss: 0.124483] [d2 loss: 0.129661]  [sq d1 d2: 0.000027]  [num0: 9.000000] [num1 55.000000]
[Epoch 9/500] [Batch 180/676] [D loss: -0.056057] [G loss: 0.246515] [d1 loss: 0.128428] [d2 loss: 0.128752]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 200/676] [D loss: -0.061798] [G loss: 0.277768] [d1 loss: 0.188103] [d2 loss: 0.184168]  [sq d1 d2: 0.000015]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 220/676] [D loss: -0.063868] [G loss: 0.270119] [d1 loss: 0.212920] [d2 loss: 0.216770]  [sq d1 d2: 0.000015]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 240/676] [D loss: -0.095549] [G loss: 0.356821] [d1 loss: 0.149783] [d2 loss: 0.141988]  [sq d1 d2: 0.000061]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 260/676] [D loss: -0.073099] [G loss: 0.392259] [d1 loss: 0.186907] [d2 loss: 0.195189]  [sq d1 d2: 0.000069]  [num0: 12.000000] [num1 52.000000]
[Epoch 9/500] [Batch 280/676] [D loss: -0.073130] [G loss: 0.425789] [d1 loss: 0.155140] [d2 loss: 0.164810]  [sq d1 d2: 0.000094]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 300/676] [D loss: -0.101059] [G loss: 0.449393] [d1 loss: 0.212299] [d2 loss: 0.213582]  [sq d1 d2: 0.000002]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 320/676] [D loss: -0.135668] [G loss: 0.508616] [d1 loss: 0.116365] [d2 loss: 0.120843]  [sq d1 d2: 0.000020]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 340/676] [D loss: -0.096279] [G loss: 0.540082] [d1 loss: 0.153988] [d2 loss: 0.147427]  [sq d1 d2: 0.000043]  [num0: 7.000000] [num1 57.000000]
[Epoch 9/500] [Batch 360/676] [D loss: -0.164099] [G loss: 0.569975] [d1 loss: 0.141892] [d2 loss: 0.141215]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 380/676] [D loss: -0.099385] [G loss: 0.511149] [d1 loss: 0.148445] [d2 loss: 0.144280]  [sq d1 d2: 0.000017]  [num0: 7.000000] [num1 57.000000]
[Epoch 9/500] [Batch 400/676] [D loss: -0.126838] [G loss: 0.435274] [d1 loss: 0.105351] [d2 loss: 0.105435]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 420/676] [D loss: -0.138949] [G loss: 0.371302] [d1 loss: 0.190507] [d2 loss: 0.187763]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 9/500] [Batch 440/676] [D loss: -0.094177] [G loss: 0.327962] [d1 loss: 0.075682] [d2 loss: 0.072301]  [sq d1 d2: 0.000011]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 460/676] [D loss: -0.090773] [G loss: 0.287437] [d1 loss: 0.168656] [d2 loss: 0.167075]  [sq d1 d2: 0.000002]  [num0: 9.000000] [num1 55.000000]
[Epoch 9/500] [Batch 480/676] [D loss: -0.053729] [G loss: 0.261225] [d1 loss: 0.105516] [d2 loss: 0.105313]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 9/500] [Batch 500/676] [D loss: -0.024607] [G loss: 0.243620] [d1 loss: 0.253245] [d2 loss: 0.250851]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 9/500] [Batch 520/676] [D loss: -0.044756] [G loss: 0.232249] [d1 loss: 0.156475] [d2 loss: 0.154798]  [sq d1 d2: 0.000003]  [num0: 10.000000] [num1 54.000000]
[Epoch 9/500] [Batch 540/676] [D loss: -0.046765] [G loss: 0.253185] [d1 loss: 0.136644] [d2 loss: 0.131343]  [sq d1 d2: 0.000028]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 560/676] [D loss: -0.072929] [G loss: 0.275382] [d1 loss: 0.109777] [d2 loss: 0.107674]  [sq d1 d2: 0.000004]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 580/676] [D loss: -0.079853] [G loss: 0.265642] [d1 loss: 0.177925] [d2 loss: 0.175805]  [sq d1 d2: 0.000004]  [num0: 8.000000] [num1 56.000000]
[Epoch 9/500] [Batch 600/676] [D loss: -0.107084] [G loss: 0.302721] [d1 loss: 0.201925] [d2 loss: 0.204872]  [sq d1 d2: 0.000009]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 620/676] [D loss: -0.121249] [G loss: 0.322199] [d1 loss: 0.183571] [d2 loss: 0.182819]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 9/500] [Batch 640/676] [D loss: -0.123152] [G loss: 0.367942] [d1 loss: 0.166007] [d2 loss: 0.173450]  [sq d1 d2: 0.000055]  [num0: 7.000000] [num1 57.000000]
[Epoch 9/500] [Batch 660/676] [D loss: -0.068910] [G loss: 0.419399] [d1 loss: 0.203971] [d2 loss: 0.205216]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 10/500] [Batch 0/676] [D loss: -0.116590] [G loss: 0.461020] [d1 loss: 0.149110] [d2 loss: 0.149439]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 10/500] [Batch 20/676] [D loss: -0.079801] [G loss: 0.468780] [d1 loss: 0.224791] [d2 loss: 0.220160]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 10/500] [Batch 40/676] [D loss: -0.088475] [G loss: 0.487777] [d1 loss: 0.159770] [d2 loss: 0.157511]  [sq d1 d2: 0.000005]  [num0: 9.000000] [num1 55.000000]
[Epoch 10/500] [Batch 60/676] [D loss: -0.071325] [G loss: 0.484369] [d1 loss: 0.160989] [d2 loss: 0.161282]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 10/500] [Batch 80/676] [D loss: -0.030191] [G loss: 0.443442] [d1 loss: 0.071445] [d2 loss: 0.068964]  [sq d1 d2: 0.000006]  [num0: 9.000000] [num1 55.000000]
[Epoch 10/500] [Batch 100/676] [D loss: -0.032745] [G loss: 0.409887] [d1 loss: 0.153651] [d2 loss: 0.143189]  [sq d1 d2: 0.000109]  [num0: 11.000000] [num1 53.000000]
[Epoch 10/500] [Batch 120/676] [D loss: -0.054521] [G loss: 0.344429] [d1 loss: 0.088364] [d2 loss: 0.089283]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 10/500] [Batch 140/676] [D loss: -0.065708] [G loss: 0.292097] [d1 loss: 0.245205] [d2 loss: 0.250067]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 10/500] [Batch 160/676] [D loss: -0.044138] [G loss: 0.224293] [d1 loss: 0.126070] [d2 loss: 0.124700]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 10/500] [Batch 180/676] [D loss: -0.050907] [G loss: 0.165140] [d1 loss: 0.168542] [d2 loss: 0.169264]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 10/500] [Batch 200/676] [D loss: -0.057178] [G loss: 0.110720] [d1 loss: 0.150315] [d2 loss: 0.154323]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 10/500] [Batch 220/676] [D loss: -0.077195] [G loss: 0.057562] [d1 loss: 0.126747] [d2 loss: 0.125132]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 10/500] [Batch 240/676] [D loss: -0.098005] [G loss: -0.007003] [d1 loss: 0.123066] [d2 loss: 0.120145]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 10/500] [Batch 260/676] [D loss: -0.078191] [G loss: -0.042953] [d1 loss: 0.142550] [d2 loss: 0.143554]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 10/500] [Batch 280/676] [D loss: -0.125641] [G loss: -0.076865] [d1 loss: 0.100290] [d2 loss: 0.100069]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 10/500] [Batch 300/676] [D loss: -0.041015] [G loss: -0.085458] [d1 loss: 0.149587] [d2 loss: 0.149590]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 10/500] [Batch 320/676] [D loss: -0.080919] [G loss: -0.096561] [d1 loss: 0.104482] [d2 loss: 0.107335]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 10/500] [Batch 340/676] [D loss: -0.102261] [G loss: -0.111592] [d1 loss: 0.101698] [d2 loss: 0.102844]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 10/500] [Batch 360/676] [D loss: -0.068654] [G loss: -0.094158] [d1 loss: 0.376072] [d2 loss: 0.390001]  [sq d1 d2: 0.000194]  [num0: 11.000000] [num1 53.000000]
[Epoch 10/500] [Batch 380/676] [D loss: -0.064732] [G loss: -0.089167] [d1 loss: 0.196031] [d2 loss: 0.195436]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 10/500] [Batch 400/676] [D loss: -0.077981] [G loss: -0.079886] [d1 loss: 0.134188] [d2 loss: 0.138685]  [sq d1 d2: 0.000020]  [num0: 8.000000] [num1 56.000000]
[Epoch 10/500] [Batch 420/676] [D loss: -0.049213] [G loss: -0.045263] [d1 loss: 0.131165] [d2 loss: 0.128363]  [sq d1 d2: 0.000008]  [num0: 7.000000] [num1 57.000000]
[Epoch 10/500] [Batch 440/676] [D loss: -0.050583] [G loss: -0.094041] [d1 loss: 0.104270] [d2 loss: 0.105257]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]

[Epoch 10/500] [Batch 460/676] [D loss: -0.028172] [G loss: -0.027179] [d1 loss: 0.145550] [d2 loss: 0.145060]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 10/500] [Batch 480/676] [D loss: -0.034388] [G loss: -0.013353] [d1 loss: 0.116883] [d2 loss: 0.118735]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 10/500] [Batch 500/676] [D loss: -0.025101] [G loss: 0.035446] [d1 loss: 0.109436] [d2 loss: 0.106842]  [sq d1 d2: 0.000007]  [num0: 6.000000] [num1 58.000000]
[Epoch 10/500] [Batch 520/676] [D loss: -0.053226] [G loss: 0.056451] [d1 loss: 0.162348] [d2 loss: 0.161475]  [sq d1 d2: 0.000001]  [num0: 9.000000] [num1 55.000000]
[Epoch 10/500] [Batch 540/676] [D loss: -0.022875] [G loss: 0.104953] [d1 loss: 0.161203] [d2 loss: 0.160167]  [sq d1 d2: 0.000001]  [num0: 7.000000] [num1 57.000000]
[Epoch 10/500] [Batch 560/676] [D loss: -0.042787] [G loss: 0.154353] [d1 loss: 0.160286] [d2 loss: 0.158635]  [sq d1 d2: 0.000003]  [num0: 10.000000] [num1 54.000000]
[Epoch 10/500] [Batch 580/676] [D loss: -0.048071] [G loss: 0.241989] [d1 loss: 0.147933] [d2 loss: 0.148354]  [sq d1 d2: 0.000000]  [num0: 7.000000] [num1 57.000000]
[Epoch 10/500] [Batch 600/676] [D loss: -0.057887] [G loss: 0.361344] [d1 loss: 0.108373] [d2 loss: 0.106528]  [sq d1 d2: 0.000003]  [num0: 8.000000] [num1 56.000000]
[Epoch 10/500] [Batch 620/676] [D loss: -0.113624] [G loss: 0.454159] [d1 loss: 0.136755] [d2 loss: 0.138793]  [sq d1 d2: 0.000004]  [num0: 10.000000] [num1 54.000000]
[Epoch 10/500] [Batch 640/676] [D loss: -0.075918] [G loss: 0.538091] [d1 loss: 0.098451] [d2 loss: 0.099979]  [sq d1 d2: 0.000002]  [num0: 5.000000] [num1 59.000000]
[Epoch 10/500] [Batch 660/676] [D loss: -0.105208] [G loss: 0.567779] [d1 loss: 0.154527] [d2 loss: 0.159782]  [sq d1 d2: 0.000028]  [num0: 6.000000] [num1 58.000000]
[Epoch 11/500] [Batch 0/676] [D loss: -0.097693] [G loss: 0.576791] [d1 loss: 0.160997] [d2 loss: 0.158015]  [sq d1 d2: 0.000009]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 20/676] [D loss: -0.075372] [G loss: 0.556958] [d1 loss: 0.110068] [d2 loss: 0.110383]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 40/676] [D loss: -0.112496] [G loss: 0.551524] [d1 loss: 0.170089] [d2 loss: 0.170427]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 11/500] [Batch 60/676] [D loss: -0.041717] [G loss: 0.484618] [d1 loss: 0.181239] [d2 loss: 0.181184]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 11/500] [Batch 80/676] [D loss: -0.074524] [G loss: 0.486462] [d1 loss: 0.159382] [d2 loss: 0.160797]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 100/676] [D loss: -0.042748] [G loss: 0.436547] [d1 loss: 0.182182] [d2 loss: 0.180022]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 120/676] [D loss: -0.062502] [G loss: 0.389831] [d1 loss: 0.170947] [d2 loss: 0.171605]  [sq d1 d2: 0.000000]  [num0: 8.000000] [num1 56.000000]
[Epoch 11/500] [Batch 140/676] [D loss: -0.064492] [G loss: 0.310639] [d1 loss: 0.232022] [d2 loss: 0.236784]  [sq d1 d2: 0.000023]  [num0: 8.000000] [num1 56.000000]
[Epoch 11/500] [Batch 160/676] [D loss: -0.045429] [G loss: 0.253241] [d1 loss: 0.163023] [d2 loss: 0.157193]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 180/676] [D loss: -0.051622] [G loss: 0.211572] [d1 loss: 0.262909] [d2 loss: 0.273097]  [sq d1 d2: 0.000104]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 200/676] [D loss: -0.058287] [G loss: 0.146804] [d1 loss: 0.193527] [d2 loss: 0.189749]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 11/500] [Batch 220/676] [D loss: -0.042855] [G loss: 0.080584] [d1 loss: 0.146552] [d2 loss: 0.143214]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 11/500] [Batch 240/676] [D loss: -0.063414] [G loss: 0.038837] [d1 loss: 0.179276] [d2 loss: 0.179393]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 260/676] [D loss: -0.032663] [G loss: 0.006646] [d1 loss: 0.166220] [d2 loss: 0.162016]  [sq d1 d2: 0.000018]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 280/676] [D loss: -0.058057] [G loss: -0.029206] [d1 loss: 0.117993] [d2 loss: 0.113255]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 300/676] [D loss: -0.063787] [G loss: -0.061790] [d1 loss: 0.225751] [d2 loss: 0.219750]  [sq d1 d2: 0.000036]  [num0: 11.000000] [num1 53.000000]
[Epoch 11/500] [Batch 320/676] [D loss: -0.050403] [G loss: -0.082297] [d1 loss: 0.175567] [d2 loss: 0.181542]  [sq d1 d2: 0.000036]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 340/676] [D loss: -0.065480] [G loss: -0.099884] [d1 loss: 0.079137] [d2 loss: 0.074582]  [sq d1 d2: 0.000021]  [num0: 11.000000] [num1 53.000000]
[Epoch 11/500] [Batch 360/676] [D loss: -0.038091] [G loss: -0.108193] [d1 loss: 0.161342] [d2 loss: 0.160637]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 11/500] [Batch 380/676] [D loss: -0.053681] [G loss: -0.129843] [d1 loss: 0.189622] [d2 loss: 0.187063]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 400/676] [D loss: -0.052871] [G loss: -0.134414] [d1 loss: 0.167661] [d2 loss: 0.167584]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 11/500] [Batch 420/676] [D loss: -0.056751] [G loss: -0.146664] [d1 loss: 0.128072] [d2 loss: 0.127803]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 11/500] [Batch 440/676] [D loss: -0.086304] [G loss: -0.171752] [d1 loss: 0.140045] [d2 loss: 0.134467]  [sq d1 d2: 0.000031]  [num0: 11.000000] [num1 53.000000]
[Epoch 11/500] [Batch 460/676] [D loss: -0.042997] [G loss: -0.181242] [d1 loss: 0.188204] [d2 loss: 0.187988]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 480/676] [D loss: -0.034947] [G loss: -0.202470] [d1 loss: 0.158120] [d2 loss: 0.149353]  [sq d1 d2: 0.000077]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 500/676] [D loss: -0.068368] [G loss: -0.192522] [d1 loss: 0.115406] [d2 loss: 0.111228]  [sq d1 d2: 0.000017]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 520/676] [D loss: -0.046133] [G loss: -0.187702] [d1 loss: 0.163887] [d2 loss: 0.163735]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 540/676] [D loss: -0.066218] [G loss: -0.180169] [d1 loss: 0.107194] [d2 loss: 0.109212]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 11/500] [Batch 560/676] [D loss: -0.049111] [G loss: -0.138476] [d1 loss: 0.182797] [d2 loss: 0.185632]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 580/676] [D loss: -0.048719] [G loss: -0.135164] [d1 loss: 0.157375] [d2 loss: 0.152614]  [sq d1 d2: 0.000023]  [num0: 10.000000] [num1 54.000000]
[Epoch 11/500] [Batch 600/676] [D loss: -0.034647] [G loss: -0.102829] [d1 loss: 0.172312] [d2 loss: 0.172519]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 620/676] [D loss: -0.049221] [G loss: -0.071391] [d1 loss: 0.110750] [d2 loss: 0.103772]  [sq d1 d2: 0.000049]  [num0: 12.000000] [num1 52.000000]
[Epoch 11/500] [Batch 640/676] [D loss: -0.041106] [G loss: -0.020545] [d1 loss: 0.201808] [d2 loss: 0.194733]  [sq d1 d2: 0.000050]  [num0: 8.000000] [num1 56.000000]
[Epoch 11/500] [Batch 660/676] [D loss: -0.026036] [G loss: 0.035383] [d1 loss: 0.187144] [d2 loss: 0.182557]  [sq d1 d2: 0.000021]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 0/676] [D loss: -0.050253] [G loss: 0.112735] [d1 loss: 0.147983] [d2 loss: 0.142458]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 12/500] [Batch 20/676] [D loss: -0.048131] [G loss: 0.196516] [d1 loss: 0.115860] [d2 loss: 0.114602]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 40/676] [D loss: -0.062283] [G loss: 0.292532] [d1 loss: 0.145581] [d2 loss: 0.142481]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 12/500] [Batch 60/676] [D loss: -0.060284] [G loss: 0.413731] [d1 loss: 0.131500] [d2 loss: 0.130920]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 80/676] [D loss: -0.053155] [G loss: 0.496108] [d1 loss: 0.141452] [d2 loss: 0.140043]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 12/500] [Batch 100/676] [D loss: -0.043573] [G loss: 0.526249] [d1 loss: 0.200343] [d2 loss: 0.199429]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 120/676] [D loss: -0.032990] [G loss: 0.566708] [d1 loss: 0.212751] [d2 loss: 0.205480]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]

[Epoch 12/500] [Batch 140/676] [D loss: -0.073499] [G loss: 0.554506] [d1 loss: 0.220662] [d2 loss: 0.219949]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 12/500] [Batch 160/676] [D loss: -0.067965] [G loss: 0.528535] [d1 loss: 0.167729] [d2 loss: 0.165821]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 12/500] [Batch 180/676] [D loss: -0.039710] [G loss: 0.474550] [d1 loss: 0.161741] [d2 loss: 0.155278]  [sq d1 d2: 0.000042]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 200/676] [D loss: -0.062090] [G loss: 0.465017] [d1 loss: 0.177768] [d2 loss: 0.173406]  [sq d1 d2: 0.000019]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 220/676] [D loss: -0.034838] [G loss: 0.433108] [d1 loss: 0.253361] [d2 loss: 0.249067]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 12/500] [Batch 240/676] [D loss: -0.043189] [G loss: 0.443537] [d1 loss: 0.170914] [d2 loss: 0.158941]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 12/500] [Batch 260/676] [D loss: -0.066039] [G loss: 0.421792] [d1 loss: 0.094734] [d2 loss: 0.087646]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 12/500] [Batch 280/676] [D loss: -0.052694] [G loss: 0.377135] [d1 loss: 0.152469] [d2 loss: 0.139928]  [sq d1 d2: 0.000157]  [num0: 15.000000] [num1 49.000000]
[Epoch 12/500] [Batch 300/676] [D loss: -0.091240] [G loss: 0.312474] [d1 loss: 0.104678] [d2 loss: 0.097502]  [sq d1 d2: 0.000051]  [num0: 12.000000] [num1 52.000000]
[Epoch 12/500] [Batch 320/676] [D loss: -0.050776] [G loss: 0.275311] [d1 loss: 0.126096] [d2 loss: 0.125440]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 12/500] [Batch 340/676] [D loss: -0.047240] [G loss: 0.256098] [d1 loss: 0.075275] [d2 loss: 0.076592]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 12/500] [Batch 360/676] [D loss: -0.034487] [G loss: 0.232993] [d1 loss: 0.112104] [d2 loss: 0.107103]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 12/500] [Batch 380/676] [D loss: -0.058598] [G loss: 0.187077] [d1 loss: 0.191195] [d2 loss: 0.188437]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 12/500] [Batch 400/676] [D loss: -0.075658] [G loss: 0.162579] [d1 loss: 0.135411] [d2 loss: 0.127578]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 12/500] [Batch 420/676] [D loss: -0.016738] [G loss: 0.191972] [d1 loss: 0.136622] [d2 loss: 0.131614]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 12/500] [Batch 440/676] [D loss: -0.060170] [G loss: 0.193176] [d1 loss: 0.145030] [d2 loss: 0.135050]  [sq d1 d2: 0.000100]  [num0: 12.000000] [num1 52.000000]
[Epoch 12/500] [Batch 460/676] [D loss: -0.082542] [G loss: 0.204558] [d1 loss: 0.116148] [d2 loss: 0.111233]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 12/500] [Batch 480/676] [D loss: -0.048569] [G loss: 0.264970] [d1 loss: 0.123329] [d2 loss: 0.117525]  [sq d1 d2: 0.000034]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 500/676] [D loss: -0.043427] [G loss: 0.271919] [d1 loss: 0.115769] [d2 loss: 0.110390]  [sq d1 d2: 0.000029]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 520/676] [D loss: -0.079363] [G loss: 0.260552] [d1 loss: 0.136661] [d2 loss: 0.130353]  [sq d1 d2: 0.000040]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 540/676] [D loss: -0.095795] [G loss: 0.231586] [d1 loss: 0.211783] [d2 loss: 0.208357]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 560/676] [D loss: -0.017212] [G loss: 0.226887] [d1 loss: 0.171834] [d2 loss: 0.166612]  [sq d1 d2: 0.000027]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 580/676] [D loss: -0.051194] [G loss: 0.164698] [d1 loss: 0.048358] [d2 loss: 0.045276]  [sq d1 d2: 0.000010]  [num0: 6.000000] [num1 58.000000]
[Epoch 12/500] [Batch 600/676] [D loss: -0.037070] [G loss: 0.154689] [d1 loss: 0.124490] [d2 loss: 0.115524]  [sq d1 d2: 0.000080]  [num0: 9.000000] [num1 55.000000]
[Epoch 12/500] [Batch 620/676] [D loss: -0.057800] [G loss: 0.121526] [d1 loss: 0.055182] [d2 loss: 0.052609]  [sq d1 d2: 0.000007]  [num0: 10.000000] [num1 54.000000]
[Epoch 12/500] [Batch 640/676] [D loss: -0.047030] [G loss: 0.126384] [d1 loss: 0.106084] [d2 loss: 0.097475]  [sq d1 d2: 0.000074]  [num0: 11.000000] [num1 53.000000]
[Epoch 12/500] [Batch 660/676] [D loss: -0.043429] [G loss: 0.105152] [d1 loss: 0.069828] [d2 loss: 0.065763]  [sq d1 d2: 0.000017]  [num0: 8.000000] [num1 56.000000]
[Epoch 13/500] [Batch 0/676] [D loss: -0.039595] [G loss: 0.105163] [d1 loss: 0.145925] [d2 loss: 0.141883]  [sq d1 d2: 0.000016]  [num0: 8.000000] [num1 56.000000]
[Epoch 13/500] [Batch 20/676] [D loss: -0.078616] [G loss: 0.085532] [d1 loss: 0.114866] [d2 loss: 0.121686]  [sq d1 d2: 0.000047]  [num0: 8.000000] [num1 56.000000]
[Epoch 13/500] [Batch 40/676] [D loss: -0.060943] [G loss: 0.095352] [d1 loss: 0.173853] [d2 loss: 0.172668]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 60/676] [D loss: -0.082742] [G loss: 0.116323] [d1 loss: 0.098442] [d2 loss: 0.089522]  [sq d1 d2: 0.000080]  [num0: 10.000000] [num1 54.000000]
[Epoch 13/500] [Batch 80/676] [D loss: -0.084165] [G loss: 0.142443] [d1 loss: 0.108170] [d2 loss: 0.102551]  [sq d1 d2: 0.000032]  [num0: 10.000000] [num1 54.000000]
[Epoch 13/500] [Batch 100/676] [D loss: -0.066500] [G loss: 0.170306] [d1 loss: 0.158731] [d2 loss: 0.153564]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 120/676] [D loss: -0.071151] [G loss: 0.208271] [d1 loss: 0.141827] [d2 loss: 0.133132]  [sq d1 d2: 0.000076]  [num0: 11.000000] [num1 53.000000]
[Epoch 13/500] [Batch 140/676] [D loss: -0.098735] [G loss: 0.228205] [d1 loss: 0.079142] [d2 loss: 0.072612]  [sq d1 d2: 0.000043]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 160/676] [D loss: -0.066998] [G loss: 0.267021] [d1 loss: 0.130873] [d2 loss: 0.129309]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 13/500] [Batch 180/676] [D loss: -0.056234] [G loss: 0.278821] [d1 loss: 0.090833] [d2 loss: 0.091368]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 13/500] [Batch 200/676] [D loss: -0.031110] [G loss: 0.318838] [d1 loss: 0.079742] [d2 loss: 0.076301]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 220/676] [D loss: -0.028860] [G loss: 0.345143] [d1 loss: 0.146395] [d2 loss: 0.150634]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 240/676] [D loss: -0.069376] [G loss: 0.354450] [d1 loss: 0.102284] [d2 loss: 0.098298]  [sq d1 d2: 0.000016]  [num0: 9.000000] [num1 55.000000]
[Epoch 13/500] [Batch 260/676] [D loss: -0.042096] [G loss: 0.403856] [d1 loss: 0.103186] [d2 loss: 0.095789]  [sq d1 d2: 0.000055]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 280/676] [D loss: -0.054007] [G loss: 0.444527] [d1 loss: 0.107473] [d2 loss: 0.106128]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 13/500] [Batch 300/676] [D loss: -0.067133] [G loss: 0.490822] [d1 loss: 0.161608] [d2 loss: 0.154775]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 13/500] [Batch 320/676] [D loss: -0.065657] [G loss: 0.536331] [d1 loss: 0.157455] [d2 loss: 0.147775]  [sq d1 d2: 0.000094]  [num0: 9.000000] [num1 55.000000]
[Epoch 13/500] [Batch 340/676] [D loss: -0.073818] [G loss: 0.583875] [d1 loss: 0.071217] [d2 loss: 0.063567]  [sq d1 d2: 0.000059]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 360/676] [D loss: -0.077659] [G loss: 0.590959] [d1 loss: 0.145405] [d2 loss: 0.138616]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 13/500] [Batch 380/676] [D loss: -0.109405] [G loss: 0.570828] [d1 loss: 0.103000] [d2 loss: 0.104022]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 13/500] [Batch 400/676] [D loss: -0.074607] [G loss: 0.545840] [d1 loss: 0.166038] [d2 loss: 0.161912]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 420/676] [D loss: -0.063858] [G loss: 0.529661] [d1 loss: 0.152803] [d2 loss: 0.161139]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 13/500] [Batch 440/676] [D loss: -0.063755] [G loss: 0.494722] [d1 loss: 0.107940] [d2 loss: 0.102193]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 13/500] [Batch 460/676] [D loss: -0.059928] [G loss: 0.441653] [d1 loss: 0.140400] [d2 loss: 0.145118]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 13/500] [Batch 480/676] [D loss: -0.073298] [G loss: 0.394608] [d1 loss: 0.173083] [d2 loss: 0.164850]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]

[Epoch 13/500] [Batch 500/676] [D loss: -0.045396] [G loss: 0.320573] [d1 loss: 0.068385] [d2 loss: 0.066577]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 520/676] [D loss: -0.069582] [G loss: 0.240402] [d1 loss: 0.149278] [d2 loss: 0.141398]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 13/500] [Batch 540/676] [D loss: -0.056073] [G loss: 0.177518] [d1 loss: 0.183492] [d2 loss: 0.180721]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 560/676] [D loss: -0.086455] [G loss: 0.092125] [d1 loss: 0.206298] [d2 loss: 0.195611]  [sq d1 d2: 0.000114]  [num0: 14.000000] [num1 50.000000]
[Epoch 13/500] [Batch 580/676] [D loss: -0.060203] [G loss: 0.032124] [d1 loss: 0.057916] [d2 loss: 0.054362]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 13/500] [Batch 600/676] [D loss: -0.066081] [G loss: -0.000048] [d1 loss: 0.139633] [d2 loss: 0.136557]  [sq d1 d2: 0.000009]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 620/676] [D loss: -0.067130] [G loss: -0.009343] [d1 loss: 0.103511] [d2 loss: 0.103443]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 640/676] [D loss: -0.061102] [G loss: -0.008370] [d1 loss: 0.112163] [d2 loss: 0.106821]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 13/500] [Batch 660/676] [D loss: -0.064448] [G loss: -0.016163] [d1 loss: 0.096664] [d2 loss: 0.089235]  [sq d1 d2: 0.000055]  [num0: 11.000000] [num1 53.000000]
[Epoch 14/500] [Batch 0/676] [D loss: -0.084661] [G loss: -0.012024] [d1 loss: 0.121036] [d2 loss: 0.120290]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 20/676] [D loss: -0.075940] [G loss: -0.006258] [d1 loss: 0.193519] [d2 loss: 0.201146]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 40/676] [D loss: -0.069535] [G loss: -0.001667] [d1 loss: 0.096855] [d2 loss: 0.093649]  [sq d1 d2: 0.000010]  [num0: 10.000000] [num1 54.000000]
[Epoch 14/500] [Batch 60/676] [D loss: -0.042199] [G loss: 0.006603] [d1 loss: 0.124939] [d2 loss: 0.127599]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 14/500] [Batch 80/676] [D loss: -0.062892] [G loss: 0.016766] [d1 loss: 0.115543] [d2 loss: 0.109635]  [sq d1 d2: 0.000035]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 100/676] [D loss: -0.038784] [G loss: 0.055112] [d1 loss: 0.161285] [d2 loss: 0.162484]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 14/500] [Batch 120/676] [D loss: -0.052070] [G loss: 0.091999] [d1 loss: 0.178740] [d2 loss: 0.170088]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 140/676] [D loss: -0.053223] [G loss: 0.165988] [d1 loss: 0.165410] [d2 loss: 0.162082]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 160/676] [D loss: -0.065247] [G loss: 0.204756] [d1 loss: 0.170469] [d2 loss: 0.169684]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 14/500] [Batch 180/676] [D loss: -0.083315] [G loss: 0.282731] [d1 loss: 0.098325] [d2 loss: 0.104175]  [sq d1 d2: 0.000034]  [num0: 8.000000] [num1 56.000000]
[Epoch 14/500] [Batch 200/676] [D loss: -0.064224] [G loss: 0.321683] [d1 loss: 0.124721] [d2 loss: 0.117943]  [sq d1 d2: 0.000046]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 220/676] [D loss: -0.051642] [G loss: 0.384395] [d1 loss: 0.186270] [d2 loss: 0.180602]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 14/500] [Batch 240/676] [D loss: -0.053430] [G loss: 0.399105] [d1 loss: 0.107621] [d2 loss: 0.102899]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 14/500] [Batch 260/676] [D loss: -0.058773] [G loss: 0.407252] [d1 loss: 0.179810] [d2 loss: 0.176677]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 280/676] [D loss: -0.075793] [G loss: 0.430428] [d1 loss: 0.116816] [d2 loss: 0.116019]  [sq d1 d2: 0.000001]  [num0: 8.000000] [num1 56.000000]
[Epoch 14/500] [Batch 300/676] [D loss: -0.069073] [G loss: 0.436803] [d1 loss: 0.071492] [d2 loss: 0.070871]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 14/500] [Batch 320/676] [D loss: -0.047332] [G loss: 0.432584] [d1 loss: 0.094139] [d2 loss: 0.093062]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 14/500] [Batch 340/676] [D loss: -0.059055] [G loss: 0.393522] [d1 loss: 0.126380] [d2 loss: 0.114229]  [sq d1 d2: 0.000148]  [num0: 11.000000] [num1 53.000000]
[Epoch 14/500] [Batch 360/676] [D loss: -0.058903] [G loss: 0.382238] [d1 loss: 0.105687] [d2 loss: 0.098717]  [sq d1 d2: 0.000049]  [num0: 11.000000] [num1 53.000000]
[Epoch 14/500] [Batch 380/676] [D loss: -0.058368] [G loss: 0.388148] [d1 loss: 0.057903] [d2 loss: 0.057525]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 14/500] [Batch 400/676] [D loss: -0.056878] [G loss: 0.347721] [d1 loss: 0.105029] [d2 loss: 0.097160]  [sq d1 d2: 0.000062]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 420/676] [D loss: -0.054096] [G loss: 0.296571] [d1 loss: 0.076255] [d2 loss: 0.073776]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 14/500] [Batch 440/676] [D loss: -0.052910] [G loss: 0.273947] [d1 loss: 0.104059] [d2 loss: 0.100618]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 14/500] [Batch 460/676] [D loss: -0.062258] [G loss: 0.257992] [d1 loss: 0.089477] [d2 loss: 0.084643]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 480/676] [D loss: -0.069945] [G loss: 0.245674] [d1 loss: 0.211819] [d2 loss: 0.220050]  [sq d1 d2: 0.000068]  [num0: 17.000000] [num1 47.000000]
[Epoch 14/500] [Batch 500/676] [D loss: -0.069093] [G loss: 0.247320] [d1 loss: 0.151519] [d2 loss: 0.140452]  [sq d1 d2: 0.000122]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 520/676] [D loss: -0.067128] [G loss: 0.237438] [d1 loss: 0.156136] [d2 loss: 0.155647]  [sq d1 d2: 0.000000]  [num0: 8.000000] [num1 56.000000]
[Epoch 14/500] [Batch 540/676] [D loss: -0.077226] [G loss: 0.237859] [d1 loss: 0.178558] [d2 loss: 0.158766]  [sq d1 d2: 0.000392]  [num0: 16.000000] [num1 48.000000]
[Epoch 14/500] [Batch 560/676] [D loss: -0.056120] [G loss: 0.246915] [d1 loss: 0.183361] [d2 loss: 0.183974]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 14/500] [Batch 580/676] [D loss: -0.046164] [G loss: 0.252428] [d1 loss: 0.163856] [d2 loss: 0.152855]  [sq d1 d2: 0.000121]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 600/676] [D loss: -0.053905] [G loss: 0.227520] [d1 loss: 0.158131] [d2 loss: 0.160571]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 14/500] [Batch 620/676] [D loss: -0.049440] [G loss: 0.211910] [d1 loss: 0.075856] [d2 loss: 0.071604]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 14/500] [Batch 640/676] [D loss: -0.042561] [G loss: 0.220651] [d1 loss: 0.035154] [d2 loss: 0.038828]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 14/500] [Batch 660/676] [D loss: -0.037152] [G loss: 0.208705] [d1 loss: 0.139503] [d2 loss: 0.158708]  [sq d1 d2: 0.000369]  [num0: 14.000000] [num1 50.000000]
[Epoch 15/500] [Batch 0/676] [D loss: -0.038272] [G loss: 0.232483] [d1 loss: 0.198868] [d2 loss: 0.230612]  [sq d1 d2: 0.001008]  [num0: 15.000000] [num1 49.000000]
[Epoch 15/500] [Batch 20/676] [D loss: -0.047893] [G loss: 0.257165] [d1 loss: 0.104436] [d2 loss: 0.098617]  [sq d1 d2: 0.000034]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 40/676] [D loss: -0.049194] [G loss: 0.268163] [d1 loss: 0.141002] [d2 loss: 0.147305]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 15/500] [Batch 60/676] [D loss: -0.055396] [G loss: 0.288548] [d1 loss: 0.166589] [d2 loss: 0.187013]  [sq d1 d2: 0.000417]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 80/676] [D loss: -0.070787] [G loss: 0.270584] [d1 loss: 0.166486] [d2 loss: 0.172887]  [sq d1 d2: 0.000041]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 100/676] [D loss: -0.081337] [G loss: 0.273910] [d1 loss: 0.170081] [d2 loss: 0.184952]  [sq d1 d2: 0.000221]  [num0: 7.000000] [num1 57.000000]
[Epoch 15/500] [Batch 120/676] [D loss: -0.062475] [G loss: 0.265268] [d1 loss: 0.139923] [d2 loss: 0.156807]  [sq d1 d2: 0.000285]  [num0: 10.000000] [num1 54.000000]
[Epoch 15/500] [Batch 140/676] [D loss: -0.066647] [G loss: 0.276365] [d1 loss: 0.107335] [d2 loss: 0.121579]  [sq d1 d2: 0.000203]  [num0: 11.000000] [num1 53.000000]
[Epoch 15/500] [Batch 160/676] [D loss: -0.044472] [G loss: 0.229599] [d1 loss: 0.095949] [d2 loss: 0.097778]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]

[Epoch 15/500] [Batch 180/676] [D loss: -0.049466] [G loss: 0.183123] [d1 loss: 0.118204] [d2 loss: 0.133156]  [sq d1 d2: 0.000224]  [num0: 10.000000] [num1 54.000000]
[Epoch 15/500] [Batch 200/676] [D loss: -0.056635] [G loss: 0.164112] [d1 loss: 0.164248] [d2 loss: 0.160426]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 15/500] [Batch 220/676] [D loss: -0.050592] [G loss: 0.152756] [d1 loss: 0.100942] [d2 loss: 0.103961]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 15/500] [Batch 240/676] [D loss: -0.036879] [G loss: 0.143009] [d1 loss: 0.143119] [d2 loss: 0.149155]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 15/500] [Batch 260/676] [D loss: -0.061675] [G loss: 0.113022] [d1 loss: 0.071316] [d2 loss: 0.083557]  [sq d1 d2: 0.000150]  [num0: 11.000000] [num1 53.000000]
[Epoch 15/500] [Batch 280/676] [D loss: -0.041575] [G loss: 0.090606] [d1 loss: 0.157310] [d2 loss: 0.164044]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 15/500] [Batch 300/676] [D loss: -0.062549] [G loss: 0.068587] [d1 loss: 0.132026] [d2 loss: 0.133971]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 320/676] [D loss: -0.054972] [G loss: 0.067897] [d1 loss: 0.034962] [d2 loss: 0.030225]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 340/676] [D loss: -0.060670] [G loss: 0.082452] [d1 loss: 0.105967] [d2 loss: 0.107654]  [sq d1 d2: 0.000003]  [num0: 9.000000] [num1 55.000000]
[Epoch 15/500] [Batch 360/676] [D loss: -0.048104] [G loss: 0.109901] [d1 loss: 0.189555] [d2 loss: 0.221885]  [sq d1 d2: 0.001045]  [num0: 13.000000] [num1 51.000000]
[Epoch 15/500] [Batch 380/676] [D loss: -0.066267] [G loss: 0.109577] [d1 loss: 0.114522] [d2 loss: 0.119942]  [sq d1 d2: 0.000029]  [num0: 6.000000] [num1 58.000000]
[Epoch 15/500] [Batch 400/676] [D loss: -0.042446] [G loss: 0.122261] [d1 loss: 0.106639] [d2 loss: 0.113023]  [sq d1 d2: 0.000041]  [num0: 13.000000] [num1 51.000000]
[Epoch 15/500] [Batch 420/676] [D loss: -0.043733] [G loss: 0.157269] [d1 loss: 0.133422] [d2 loss: 0.149768]  [sq d1 d2: 0.000267]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 440/676] [D loss: -0.052843] [G loss: 0.144648] [d1 loss: 0.107535] [d2 loss: 0.107098]  [sq d1 d2: 0.000000]  [num0: 9.000000] [num1 55.000000]
[Epoch 15/500] [Batch 460/676] [D loss: -0.040205] [G loss: 0.149226] [d1 loss: 0.151442] [d2 loss: 0.173308]  [sq d1 d2: 0.000478]  [num0: 10.000000] [num1 54.000000]
[Epoch 15/500] [Batch 480/676] [D loss: -0.024981] [G loss: 0.170589] [d1 loss: 0.152524] [d2 loss: 0.172814]  [sq d1 d2: 0.000412]  [num0: 10.000000] [num1 54.000000]
[Epoch 15/500] [Batch 500/676] [D loss: -0.062568] [G loss: 0.202803] [d1 loss: 0.082308] [d2 loss: 0.077814]  [sq d1 d2: 0.000020]  [num0: 10.000000] [num1 54.000000]
[Epoch 15/500] [Batch 520/676] [D loss: -0.051108] [G loss: 0.239497] [d1 loss: 0.125928] [d2 loss: 0.136901]  [sq d1 d2: 0.000120]  [num0: 11.000000] [num1 53.000000]
[Epoch 15/500] [Batch 540/676] [D loss: -0.057573] [G loss: 0.292106] [d1 loss: 0.110466] [d2 loss: 0.112700]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 15/500] [Batch 560/676] [D loss: -0.052118] [G loss: 0.329267] [d1 loss: 0.096120] [d2 loss: 0.109907]  [sq d1 d2: 0.000190]  [num0: 12.000000] [num1 52.000000]
[Epoch 15/500] [Batch 580/676] [D loss: -0.064595] [G loss: 0.393439] [d1 loss: 0.144929] [d2 loss: 0.165581]  [sq d1 d2: 0.000427]  [num0: 13.000000] [num1 51.000000]
[Epoch 15/500] [Batch 600/676] [D loss: -0.053493] [G loss: 0.436708] [d1 loss: 0.188605] [d2 loss: 0.217893]  [sq d1 d2: 0.000858]  [num0: 14.000000] [num1 50.000000]
[Epoch 15/500] [Batch 620/676] [D loss: -0.073477] [G loss: 0.463050] [d1 loss: 0.165224] [d2 loss: 0.203440]  [sq d1 d2: 0.001460]  [num0: 15.000000] [num1 49.000000]
[Epoch 15/500] [Batch 640/676] [D loss: -0.053500] [G loss: 0.467286] [d1 loss: 0.109279] [d2 loss: 0.096437]  [sq d1 d2: 0.000165]  [num0: 9.000000] [num1 55.000000]
[Epoch 15/500] [Batch 660/676] [D loss: -0.090775] [G loss: 0.485516] [d1 loss: 0.160791] [d2 loss: 0.177297]  [sq d1 d2: 0.000272]  [num0: 13.000000] [num1 51.000000]
[Epoch 16/500] [Batch 0/676] [D loss: -0.049319] [G loss: 0.481701] [d1 loss: 0.118783] [d2 loss: 0.143524]  [sq d1 d2: 0.000612]  [num0: 10.000000] [num1 54.000000]
[Epoch 16/500] [Batch 20/676] [D loss: -0.063350] [G loss: 0.482335] [d1 loss: 0.216353] [d2 loss: 0.220051]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 16/500] [Batch 40/676] [D loss: -0.046012] [G loss: 0.452020] [d1 loss: 0.136483] [d2 loss: 0.193533]  [sq d1 d2: 0.003255]  [num0: 13.000000] [num1 51.000000]
[Epoch 16/500] [Batch 60/676] [D loss: -0.043268] [G loss: 0.367554] [d1 loss: 0.087803] [d2 loss: 0.101808]  [sq d1 d2: 0.000196]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 80/676] [D loss: -0.074292] [G loss: 0.351371] [d1 loss: 0.185967] [d2 loss: 0.217209]  [sq d1 d2: 0.000976]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 100/676] [D loss: -0.060211] [G loss: 0.323118] [d1 loss: 0.217450] [d2 loss: 0.289951]  [sq d1 d2: 0.005256]  [num0: 17.000000] [num1 47.000000]
[Epoch 16/500] [Batch 120/676] [D loss: -0.066933] [G loss: 0.324858] [d1 loss: 0.201383] [d2 loss: 0.267452]  [sq d1 d2: 0.004365]  [num0: 17.000000] [num1 47.000000]
[Epoch 16/500] [Batch 140/676] [D loss: -0.090021] [G loss: 0.347581] [d1 loss: 0.131223] [d2 loss: 0.154167]  [sq d1 d2: 0.000526]  [num0: 15.000000] [num1 49.000000]
[Epoch 16/500] [Batch 160/676] [D loss: -0.020462] [G loss: 0.335292] [d1 loss: 0.210471] [d2 loss: 0.277759]  [sq d1 d2: 0.004528]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 180/676] [D loss: -0.061285] [G loss: 0.328162] [d1 loss: 0.131995] [d2 loss: 0.148123]  [sq d1 d2: 0.000260]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 200/676] [D loss: -0.069395] [G loss: 0.307779] [d1 loss: 0.211259] [d2 loss: 0.246071]  [sq d1 d2: 0.001212]  [num0: 20.000000] [num1 44.000000]
[Epoch 16/500] [Batch 220/676] [D loss: -0.043379] [G loss: 0.233116] [d1 loss: 0.243419] [d2 loss: 0.271381]  [sq d1 d2: 0.000782]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 240/676] [D loss: -0.051237] [G loss: 0.217915] [d1 loss: 0.197396] [d2 loss: 0.293378]  [sq d1 d2: 0.009213]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 260/676] [D loss: -0.045233] [G loss: 0.174194] [d1 loss: 0.238473] [d2 loss: 0.310134]  [sq d1 d2: 0.005135]  [num0: 15.000000] [num1 49.000000]
[Epoch 16/500] [Batch 280/676] [D loss: -0.055352] [G loss: 0.147461] [d1 loss: 0.178170] [d2 loss: 0.221383]  [sq d1 d2: 0.001867]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 300/676] [D loss: -0.041275] [G loss: 0.073485] [d1 loss: 0.288751] [d2 loss: 0.302633]  [sq d1 d2: 0.000193]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 320/676] [D loss: -0.062442] [G loss: 0.015932] [d1 loss: 0.102349] [d2 loss: 0.152175]  [sq d1 d2: 0.002483]  [num0: 13.000000] [num1 51.000000]
[Epoch 16/500] [Batch 340/676] [D loss: -0.049760] [G loss: 0.033424] [d1 loss: 0.167539] [d2 loss: 0.243045]  [sq d1 d2: 0.005701]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 360/676] [D loss: -0.057164] [G loss: 0.005361] [d1 loss: 0.061857] [d2 loss: 0.091745]  [sq d1 d2: 0.000893]  [num0: 12.000000] [num1 52.000000]
[Epoch 16/500] [Batch 380/676] [D loss: -0.056204] [G loss: -0.051638] [d1 loss: 0.125330] [d2 loss: 0.146903]  [sq d1 d2: 0.000465]  [num0: 15.000000] [num1 49.000000]
[Epoch 16/500] [Batch 400/676] [D loss: -0.058241] [G loss: -0.044336] [d1 loss: 0.123305] [d2 loss: 0.144778]  [sq d1 d2: 0.000461]  [num0: 11.000000] [num1 53.000000]
[Epoch 16/500] [Batch 420/676] [D loss: -0.084178] [G loss: -0.071903] [d1 loss: 0.100156] [d2 loss: 0.137494]  [sq d1 d2: 0.001394]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 440/676] [D loss: -0.061102] [G loss: -0.075525] [d1 loss: 0.167309] [d2 loss: 0.216565]  [sq d1 d2: 0.002426]  [num0: 15.000000] [num1 49.000000]
[Epoch 16/500] [Batch 460/676] [D loss: -0.076662] [G loss: -0.079924] [d1 loss: 0.259570] [d2 loss: 0.292207]  [sq d1 d2: 0.001065]  [num0: 16.000000] [num1 48.000000]
[Epoch 16/500] [Batch 480/676] [D loss: -0.079070] [G loss: -0.066819] [d1 loss: 0.096417] [d2 loss: 0.119586]  [sq d1 d2: 0.000537]  [num0: 13.000000] [num1 51.000000]
[Epoch 16/500] [Batch 500/676] [D loss: -0.021859] [G loss: -0.045225] [d1 loss: 0.133202] [d2 loss: 0.155866]  [sq d1 d2: 0.000514]  [num0: 9.000000] [num1 55.000000]
[Epoch 16/500] [Batch 520/676] [D loss: -0.051212] [G loss: 0.007557] [d1 loss: 0.171838] [d2 loss: 0.200872]  [sq d1 d2: 0.000843]  [num0: 14.000000] [num1 50.000000]

[Epoch 16/500] [Batch 540/676] [D loss: -0.044097] [G loss: 0.019596] [d1 loss: 0.075328] [d2 loss: 0.094361]  [sq d1 d2: 0.000362]  [num0: 12.000000] [num1 52.000000]
[Epoch 16/500] [Batch 560/676] [D loss: -0.040983] [G loss: 0.038469] [d1 loss: 0.084509] [d2 loss: 0.087583]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 16/500] [Batch 580/676] [D loss: -0.042493] [G loss: 0.045469] [d1 loss: 0.091432] [d2 loss: 0.085909]  [sq d1 d2: 0.000031]  [num0: 9.000000] [num1 55.000000]
[Epoch 16/500] [Batch 600/676] [D loss: -0.037106] [G loss: 0.050957] [d1 loss: 0.213072] [d2 loss: 0.213437]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 16/500] [Batch 620/676] [D loss: -0.071654] [G loss: 0.074786] [d1 loss: 0.063507] [d2 loss: 0.084305]  [sq d1 d2: 0.000433]  [num0: 12.000000] [num1 52.000000]
[Epoch 16/500] [Batch 640/676] [D loss: -0.065191] [G loss: 0.081489] [d1 loss: 0.199917] [d2 loss: 0.182230]  [sq d1 d2: 0.000313]  [num0: 12.000000] [num1 52.000000]
[Epoch 16/500] [Batch 660/676] [D loss: -0.077359] [G loss: 0.104061] [d1 loss: 0.120921] [d2 loss: 0.128091]  [sq d1 d2: 0.000051]  [num0: 10.000000] [num1 54.000000]
[Epoch 17/500] [Batch 0/676] [D loss: -0.079634] [G loss: 0.133584] [d1 loss: 0.239085] [d2 loss: 0.296246]  [sq d1 d2: 0.003267]  [num0: 8.000000] [num1 56.000000]
[Epoch 17/500] [Batch 20/676] [D loss: -0.075058] [G loss: 0.143212] [d1 loss: 0.101419] [d2 loss: 0.114773]  [sq d1 d2: 0.000178]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 40/676] [D loss: -0.054152] [G loss: 0.191879] [d1 loss: 0.101401] [d2 loss: 0.127988]  [sq d1 d2: 0.000707]  [num0: 10.000000] [num1 54.000000]
[Epoch 17/500] [Batch 60/676] [D loss: -0.048898] [G loss: 0.216900] [d1 loss: 0.086928] [d2 loss: 0.132452]  [sq d1 d2: 0.002073]  [num0: 8.000000] [num1 56.000000]
[Epoch 17/500] [Batch 80/676] [D loss: -0.031087] [G loss: 0.216220] [d1 loss: 0.179214] [d2 loss: 0.202082]  [sq d1 d2: 0.000523]  [num0: 13.000000] [num1 51.000000]
[Epoch 17/500] [Batch 100/676] [D loss: -0.032267] [G loss: 0.255957] [d1 loss: 0.100958] [d2 loss: 0.120453]  [sq d1 d2: 0.000380]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 120/676] [D loss: -0.031626] [G loss: 0.250893] [d1 loss: 0.217560] [d2 loss: 0.229275]  [sq d1 d2: 0.000137]  [num0: 10.000000] [num1 54.000000]
[Epoch 17/500] [Batch 140/676] [D loss: -0.035849] [G loss: 0.262934] [d1 loss: 0.123243] [d2 loss: 0.153808]  [sq d1 d2: 0.000934]  [num0: 13.000000] [num1 51.000000]
[Epoch 17/500] [Batch 160/676] [D loss: -0.034444] [G loss: 0.236919] [d1 loss: 0.132062] [d2 loss: 0.158794]  [sq d1 d2: 0.000715]  [num0: 12.000000] [num1 52.000000]
[Epoch 17/500] [Batch 180/676] [D loss: -0.049543] [G loss: 0.259832] [d1 loss: 0.097399] [d2 loss: 0.116583]  [sq d1 d2: 0.000368]  [num0: 12.000000] [num1 52.000000]
[Epoch 17/500] [Batch 200/676] [D loss: -0.054431] [G loss: 0.261446] [d1 loss: 0.126410] [d2 loss: 0.149905]  [sq d1 d2: 0.000552]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 220/676] [D loss: -0.087552] [G loss: 0.311911] [d1 loss: 0.204296] [d2 loss: 0.218450]  [sq d1 d2: 0.000200]  [num0: 13.000000] [num1 51.000000]
[Epoch 17/500] [Batch 240/676] [D loss: -0.043397] [G loss: 0.305483] [d1 loss: 0.133276] [d2 loss: 0.156828]  [sq d1 d2: 0.000555]  [num0: 11.000000] [num1 53.000000]
[Epoch 17/500] [Batch 260/676] [D loss: -0.070001] [G loss: 0.326483] [d1 loss: 0.152190] [d2 loss: 0.171154]  [sq d1 d2: 0.000360]  [num0: 12.000000] [num1 52.000000]
[Epoch 17/500] [Batch 280/676] [D loss: -0.059555] [G loss: 0.321940] [d1 loss: 0.127383] [d2 loss: 0.146125]  [sq d1 d2: 0.000351]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 300/676] [D loss: -0.057938] [G loss: 0.340628] [d1 loss: 0.173017] [d2 loss: 0.198121]  [sq d1 d2: 0.000630]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 320/676] [D loss: -0.065503] [G loss: 0.357155] [d1 loss: 0.175169] [d2 loss: 0.170471]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 17/500] [Batch 340/676] [D loss: -0.052331] [G loss: 0.350778] [d1 loss: 0.301724] [d2 loss: 0.295332]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 360/676] [D loss: -0.054308] [G loss: 0.322791] [d1 loss: 0.176122] [d2 loss: 0.193467]  [sq d1 d2: 0.000301]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 380/676] [D loss: -0.046525] [G loss: 0.284986] [d1 loss: 0.114904] [d2 loss: 0.142136]  [sq d1 d2: 0.000742]  [num0: 16.000000] [num1 48.000000]
[Epoch 17/500] [Batch 400/676] [D loss: -0.042480] [G loss: 0.222691] [d1 loss: 0.106760] [d2 loss: 0.114136]  [sq d1 d2: 0.000054]  [num0: 11.000000] [num1 53.000000]
[Epoch 17/500] [Batch 420/676] [D loss: -0.038595] [G loss: 0.166415] [d1 loss: 0.085359] [d2 loss: 0.107741]  [sq d1 d2: 0.000501]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 440/676] [D loss: -0.057165] [G loss: 0.151401] [d1 loss: 0.151919] [d2 loss: 0.162192]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 17/500] [Batch 460/676] [D loss: -0.054615] [G loss: 0.111326] [d1 loss: 0.091582] [d2 loss: 0.112808]  [sq d1 d2: 0.000451]  [num0: 9.000000] [num1 55.000000]
[Epoch 17/500] [Batch 480/676] [D loss: -0.069071] [G loss: 0.077909] [d1 loss: 0.091580] [d2 loss: 0.102747]  [sq d1 d2: 0.000125]  [num0: 12.000000] [num1 52.000000]
[Epoch 17/500] [Batch 500/676] [D loss: -0.044547] [G loss: 0.057620] [d1 loss: 0.086528] [d2 loss: 0.120031]  [sq d1 d2: 0.001122]  [num0: 18.000000] [num1 46.000000]
[Epoch 17/500] [Batch 520/676] [D loss: -0.056679] [G loss: 0.064516] [d1 loss: 0.090779] [d2 loss: 0.113424]  [sq d1 d2: 0.000513]  [num0: 15.000000] [num1 49.000000]
[Epoch 17/500] [Batch 540/676] [D loss: -0.056116] [G loss: 0.085840] [d1 loss: 0.129015] [d2 loss: 0.173279]  [sq d1 d2: 0.001959]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 560/676] [D loss: -0.068230] [G loss: 0.049899] [d1 loss: 0.114592] [d2 loss: 0.136353]  [sq d1 d2: 0.000474]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 580/676] [D loss: -0.056810] [G loss: 0.064151] [d1 loss: 0.112701] [d2 loss: 0.144278]  [sq d1 d2: 0.000997]  [num0: 17.000000] [num1 47.000000]
[Epoch 17/500] [Batch 600/676] [D loss: -0.064634] [G loss: 0.082910] [d1 loss: 0.141100] [d2 loss: 0.133534]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 620/676] [D loss: -0.038871] [G loss: 0.089253] [d1 loss: 0.223962] [d2 loss: 0.216416]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 17/500] [Batch 640/676] [D loss: -0.070311] [G loss: 0.096794] [d1 loss: 0.091147] [d2 loss: 0.097859]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 17/500] [Batch 660/676] [D loss: -0.050443] [G loss: 0.112408] [d1 loss: 0.118057] [d2 loss: 0.128570]  [sq d1 d2: 0.000111]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 0/676] [D loss: -0.030401] [G loss: 0.100286] [d1 loss: 0.111062] [d2 loss: 0.116350]  [sq d1 d2: 0.000028]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 20/676] [D loss: -0.049782] [G loss: 0.128887] [d1 loss: 0.101732] [d2 loss: 0.118426]  [sq d1 d2: 0.000279]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 40/676] [D loss: -0.048345] [G loss: 0.150077] [d1 loss: 0.115208] [d2 loss: 0.108070]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 60/676] [D loss: -0.053847] [G loss: 0.149482] [d1 loss: 0.166483] [d2 loss: 0.133135]  [sq d1 d2: 0.001112]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 80/676] [D loss: -0.056343] [G loss: 0.186775] [d1 loss: 0.087826] [d2 loss: 0.078416]  [sq d1 d2: 0.000089]  [num0: 10.000000] [num1 54.000000]
[Epoch 18/500] [Batch 100/676] [D loss: -0.063055] [G loss: 0.217987] [d1 loss: 0.117765] [d2 loss: 0.121194]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 120/676] [D loss: -0.049749] [G loss: 0.203799] [d1 loss: 0.115870] [d2 loss: 0.143819]  [sq d1 d2: 0.000781]  [num0: 16.000000] [num1 48.000000]
[Epoch 18/500] [Batch 140/676] [D loss: -0.080164] [G loss: 0.180102] [d1 loss: 0.199929] [d2 loss: 0.194176]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]

[Epoch 18/500] [Batch 160/676] [D loss: -0.059567] [G loss: 0.171997] [d1 loss: 0.193952] [d2 loss: 0.184421]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 18/500] [Batch 180/676] [D loss: -0.077252] [G loss: 0.167704] [d1 loss: 0.120589] [d2 loss: 0.144447]  [sq d1 d2: 0.000569]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 200/676] [D loss: -0.046875] [G loss: 0.149503] [d1 loss: 0.131703] [d2 loss: 0.192796]  [sq d1 d2: 0.003732]  [num0: 10.000000] [num1 54.000000]
[Epoch 18/500] [Batch 220/676] [D loss: -0.030480] [G loss: 0.125221] [d1 loss: 0.119367] [d2 loss: 0.119068]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 240/676] [D loss: -0.062059] [G loss: 0.112873] [d1 loss: 0.130519] [d2 loss: 0.126998]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 260/676] [D loss: -0.055031] [G loss: 0.106137] [d1 loss: 0.180871] [d2 loss: 0.198301]  [sq d1 d2: 0.000304]  [num0: 16.000000] [num1 48.000000]
[Epoch 18/500] [Batch 280/676] [D loss: -0.028955] [G loss: 0.085372] [d1 loss: 0.073867] [d2 loss: 0.091692]  [sq d1 d2: 0.000318]  [num0: 17.000000] [num1 47.000000]
[Epoch 18/500] [Batch 300/676] [D loss: -0.045647] [G loss: 0.106813] [d1 loss: 0.107979] [d2 loss: 0.108938]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 320/676] [D loss: -0.050633] [G loss: 0.117914] [d1 loss: 0.128028] [d2 loss: 0.148286]  [sq d1 d2: 0.000410]  [num0: 16.000000] [num1 48.000000]
[Epoch 18/500] [Batch 340/676] [D loss: -0.058221] [G loss: 0.150274] [d1 loss: 0.153686] [d2 loss: 0.151799]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 18/500] [Batch 360/676] [D loss: -0.067308] [G loss: 0.153934] [d1 loss: 0.133389] [d2 loss: 0.130946]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 18/500] [Batch 380/676] [D loss: -0.068690] [G loss: 0.200594] [d1 loss: 0.157128] [d2 loss: 0.148933]  [sq d1 d2: 0.000067]  [num0: 12.000000] [num1 52.000000]
[Epoch 18/500] [Batch 400/676] [D loss: -0.076497] [G loss: 0.229926] [d1 loss: 0.199302] [d2 loss: 0.196004]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 18/500] [Batch 420/676] [D loss: -0.037665] [G loss: 0.227987] [d1 loss: 0.124079] [d2 loss: 0.111740]  [sq d1 d2: 0.000152]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 440/676] [D loss: -0.068398] [G loss: 0.236233] [d1 loss: 0.144284] [d2 loss: 0.162309]  [sq d1 d2: 0.000325]  [num0: 15.000000] [num1 49.000000]
[Epoch 18/500] [Batch 460/676] [D loss: -0.058777] [G loss: 0.268575] [d1 loss: 0.104727] [d2 loss: 0.093357]  [sq d1 d2: 0.000129]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 480/676] [D loss: -0.043453] [G loss: 0.281618] [d1 loss: 0.072421] [d2 loss: 0.092656]  [sq d1 d2: 0.000409]  [num0: 12.000000] [num1 52.000000]
[Epoch 18/500] [Batch 500/676] [D loss: -0.019515] [G loss: 0.258843] [d1 loss: 0.186069] [d2 loss: 0.199660]  [sq d1 d2: 0.000185]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 520/676] [D loss: -0.057466] [G loss: 0.255090] [d1 loss: 0.132894] [d2 loss: 0.128226]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 540/676] [D loss: -0.029656] [G loss: 0.245623] [d1 loss: 0.081731] [d2 loss: 0.081107]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 18/500] [Batch 560/676] [D loss: -0.049317] [G loss: 0.234828] [d1 loss: 0.136655] [d2 loss: 0.152157]  [sq d1 d2: 0.000240]  [num0: 12.000000] [num1 52.000000]
[Epoch 18/500] [Batch 580/676] [D loss: -0.048357] [G loss: 0.251902] [d1 loss: 0.109865] [d2 loss: 0.127833]  [sq d1 d2: 0.000323]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 600/676] [D loss: -0.068354] [G loss: 0.236018] [d1 loss: 0.108074] [d2 loss: 0.122755]  [sq d1 d2: 0.000216]  [num0: 14.000000] [num1 50.000000]
[Epoch 18/500] [Batch 620/676] [D loss: -0.065004] [G loss: 0.279673] [d1 loss: 0.067622] [d2 loss: 0.070217]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 18/500] [Batch 640/676] [D loss: -0.066074] [G loss: 0.308347] [d1 loss: 0.128778] [d2 loss: 0.147363]  [sq d1 d2: 0.000345]  [num0: 15.000000] [num1 49.000000]
[Epoch 18/500] [Batch 660/676] [D loss: -0.054425] [G loss: 0.314025] [d1 loss: 0.164117] [d2 loss: 0.177088]  [sq d1 d2: 0.000168]  [num0: 16.000000] [num1 48.000000]
[Epoch 19/500] [Batch 0/676] [D loss: -0.068068] [G loss: 0.277176] [d1 loss: 0.121080] [d2 loss: 0.129810]  [sq d1 d2: 0.000076]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 20/676] [D loss: -0.034219] [G loss: 0.292375] [d1 loss: 0.115329] [d2 loss: 0.138365]  [sq d1 d2: 0.000531]  [num0: 10.000000] [num1 54.000000]
[Epoch 19/500] [Batch 40/676] [D loss: -0.056131] [G loss: 0.250230] [d1 loss: 0.063074] [d2 loss: 0.060348]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 19/500] [Batch 60/676] [D loss: -0.047138] [G loss: 0.229799] [d1 loss: 0.100922] [d2 loss: 0.114598]  [sq d1 d2: 0.000187]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 80/676] [D loss: -0.040838] [G loss: 0.185644] [d1 loss: 0.187109] [d2 loss: 0.189734]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 100/676] [D loss: -0.065186] [G loss: 0.128137] [d1 loss: 0.144783] [d2 loss: 0.128162]  [sq d1 d2: 0.000276]  [num0: 12.000000] [num1 52.000000]
[Epoch 19/500] [Batch 120/676] [D loss: -0.042349] [G loss: 0.083619] [d1 loss: 0.127342] [d2 loss: 0.118026]  [sq d1 d2: 0.000087]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 140/676] [D loss: -0.055250] [G loss: 0.064729] [d1 loss: 0.110315] [d2 loss: 0.107615]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 19/500] [Batch 160/676] [D loss: -0.060567] [G loss: 0.030124] [d1 loss: 0.123573] [d2 loss: 0.125166]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 19/500] [Batch 180/676] [D loss: -0.053041] [G loss: 0.001549] [d1 loss: 0.161752] [d2 loss: 0.179623]  [sq d1 d2: 0.000319]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 200/676] [D loss: -0.042492] [G loss: 0.014359] [d1 loss: 0.100767] [d2 loss: 0.120335]  [sq d1 d2: 0.000383]  [num0: 17.000000] [num1 47.000000]
[Epoch 19/500] [Batch 220/676] [D loss: -0.061277] [G loss: 0.017160] [d1 loss: 0.069170] [d2 loss: 0.077211]  [sq d1 d2: 0.000065]  [num0: 10.000000] [num1 54.000000]
[Epoch 19/500] [Batch 240/676] [D loss: -0.047518] [G loss: -0.009463] [d1 loss: 0.130426] [d2 loss: 0.132412]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 260/676] [D loss: -0.040158] [G loss: 0.010729] [d1 loss: 0.172757] [d2 loss: 0.156213]  [sq d1 d2: 0.000274]  [num0: 12.000000] [num1 52.000000]
[Epoch 19/500] [Batch 280/676] [D loss: -0.057592] [G loss: 0.004872] [d1 loss: 0.098841] [d2 loss: 0.090850]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 300/676] [D loss: -0.056037] [G loss: -0.024838] [d1 loss: 0.141310] [d2 loss: 0.142600]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 320/676] [D loss: -0.051103] [G loss: -0.009225] [d1 loss: 0.161465] [d2 loss: 0.190870]  [sq d1 d2: 0.000865]  [num0: 19.000000] [num1 45.000000]
[Epoch 19/500] [Batch 340/676] [D loss: -0.048120] [G loss: -0.001849] [d1 loss: 0.090060] [d2 loss: 0.110770]  [sq d1 d2: 0.000429]  [num0: 12.000000] [num1 52.000000]
[Epoch 19/500] [Batch 360/676] [D loss: -0.054045] [G loss: -0.011131] [d1 loss: 0.092854] [d2 loss: 0.092342]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 380/676] [D loss: -0.057863] [G loss: -0.005091] [d1 loss: 0.088739] [d2 loss: 0.100747]  [sq d1 d2: 0.000144]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 400/676] [D loss: -0.044061] [G loss: 0.017719] [d1 loss: 0.114710] [d2 loss: 0.095148]  [sq d1 d2: 0.000383]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 420/676] [D loss: -0.050655] [G loss: 0.040120] [d1 loss: 0.085023] [d2 loss: 0.077373]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 440/676] [D loss: -0.056857] [G loss: 0.081894] [d1 loss: 0.110929] [d2 loss: 0.129803]  [sq d1 d2: 0.000356]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 460/676] [D loss: -0.052662] [G loss: 0.117415] [d1 loss: 0.099071] [d2 loss: 0.104924]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]

[Epoch 19/500] [Batch 480/676] [D loss: -0.061400] [G loss: 0.148976] [d1 loss: 0.114650] [d2 loss: 0.111024]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 500/676] [D loss: -0.074951] [G loss: 0.168777] [d1 loss: 0.116373] [d2 loss: 0.141731]  [sq d1 d2: 0.000643]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 520/676] [D loss: -0.056544] [G loss: 0.169752] [d1 loss: 0.139177] [d2 loss: 0.134506]  [sq d1 d2: 0.000022]  [num0: 10.000000] [num1 54.000000]
[Epoch 19/500] [Batch 540/676] [D loss: -0.053074] [G loss: 0.194646] [d1 loss: 0.088829] [d2 loss: 0.100691]  [sq d1 d2: 0.000141]  [num0: 13.000000] [num1 51.000000]
[Epoch 19/500] [Batch 560/676] [D loss: -0.056425] [G loss: 0.216199] [d1 loss: 0.125502] [d2 loss: 0.146048]  [sq d1 d2: 0.000422]  [num0: 11.000000] [num1 53.000000]
[Epoch 19/500] [Batch 580/676] [D loss: -0.056365] [G loss: 0.232420] [d1 loss: 0.122709] [d2 loss: 0.138839]  [sq d1 d2: 0.000260]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 600/676] [D loss: -0.050710] [G loss: 0.229358] [d1 loss: 0.117274] [d2 loss: 0.132353]  [sq d1 d2: 0.000227]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 620/676] [D loss: -0.064512] [G loss: 0.262075] [d1 loss: 0.173702] [d2 loss: 0.156405]  [sq d1 d2: 0.000299]  [num0: 15.000000] [num1 49.000000]
[Epoch 19/500] [Batch 640/676] [D loss: -0.056316] [G loss: 0.278690] [d1 loss: 0.087611] [d2 loss: 0.089647]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 19/500] [Batch 660/676] [D loss: -0.059122] [G loss: 0.295153] [d1 loss: 0.112848] [d2 loss: 0.136256]  [sq d1 d2: 0.000548]  [num0: 12.000000] [num1 52.000000]
[Epoch 20/500] [Batch 0/676] [D loss: -0.067556] [G loss: 0.269702] [d1 loss: 0.111374] [d2 loss: 0.127665]  [sq d1 d2: 0.000265]  [num0: 13.000000] [num1 51.000000]
[Epoch 20/500] [Batch 20/676] [D loss: -0.063432] [G loss: 0.262125] [d1 loss: 0.175144] [d2 loss: 0.173735]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 40/676] [D loss: -0.070277] [G loss: 0.240383] [d1 loss: 0.168150] [d2 loss: 0.184957]  [sq d1 d2: 0.000282]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 60/676] [D loss: -0.060473] [G loss: 0.232358] [d1 loss: 0.085948] [d2 loss: 0.084592]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 80/676] [D loss: -0.066590] [G loss: 0.208152] [d1 loss: 0.136742] [d2 loss: 0.106136]  [sq d1 d2: 0.000937]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 100/676] [D loss: -0.052802] [G loss: 0.212677] [d1 loss: 0.119796] [d2 loss: 0.158957]  [sq d1 d2: 0.001534]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 120/676] [D loss: -0.042409] [G loss: 0.181408] [d1 loss: 0.156327] [d2 loss: 0.204678]  [sq d1 d2: 0.002338]  [num0: 17.000000] [num1 47.000000]
[Epoch 20/500] [Batch 140/676] [D loss: -0.062917] [G loss: 0.170630] [d1 loss: 0.111927] [d2 loss: 0.109650]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 20/500] [Batch 160/676] [D loss: -0.058513] [G loss: 0.165489] [d1 loss: 0.082787] [d2 loss: 0.100154]  [sq d1 d2: 0.000302]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 180/676] [D loss: -0.042852] [G loss: 0.135592] [d1 loss: 0.122141] [d2 loss: 0.142583]  [sq d1 d2: 0.000418]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 200/676] [D loss: -0.048265] [G loss: 0.146626] [d1 loss: 0.138971] [d2 loss: 0.121628]  [sq d1 d2: 0.000301]  [num0: 14.000000] [num1 50.000000]
[Epoch 20/500] [Batch 220/676] [D loss: -0.056819] [G loss: 0.125741] [d1 loss: 0.101603] [d2 loss: 0.134881]  [sq d1 d2: 0.001107]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 240/676] [D loss: -0.055949] [G loss: 0.141635] [d1 loss: 0.173806] [d2 loss: 0.159726]  [sq d1 d2: 0.000198]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 260/676] [D loss: -0.057618] [G loss: 0.143674] [d1 loss: 0.112789] [d2 loss: 0.115446]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 20/500] [Batch 280/676] [D loss: -0.058756] [G loss: 0.136086] [d1 loss: 0.144106] [d2 loss: 0.178966]  [sq d1 d2: 0.001215]  [num0: 17.000000] [num1 47.000000]
[Epoch 20/500] [Batch 300/676] [D loss: -0.056252] [G loss: 0.163242] [d1 loss: 0.117751] [d2 loss: 0.127998]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]
[Epoch 20/500] [Batch 320/676] [D loss: -0.067294] [G loss: 0.166410] [d1 loss: 0.121873] [d2 loss: 0.155318]  [sq d1 d2: 0.001119]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 340/676] [D loss: -0.050713] [G loss: 0.177430] [d1 loss: 0.216664] [d2 loss: 0.252898]  [sq d1 d2: 0.001313]  [num0: 14.000000] [num1 50.000000]
[Epoch 20/500] [Batch 360/676] [D loss: -0.051756] [G loss: 0.198557] [d1 loss: 0.180458] [d2 loss: 0.192718]  [sq d1 d2: 0.000150]  [num0: 14.000000] [num1 50.000000]
[Epoch 20/500] [Batch 380/676] [D loss: -0.047810] [G loss: 0.169104] [d1 loss: 0.151082] [d2 loss: 0.198045]  [sq d1 d2: 0.002206]  [num0: 11.000000] [num1 53.000000]
[Epoch 20/500] [Batch 400/676] [D loss: -0.064612] [G loss: 0.175872] [d1 loss: 0.200076] [d2 loss: 0.168646]  [sq d1 d2: 0.000988]  [num0: 21.000000] [num1 43.000000]
[Epoch 20/500] [Batch 420/676] [D loss: -0.035700] [G loss: 0.160643] [d1 loss: 0.070160] [d2 loss: 0.097770]  [sq d1 d2: 0.000762]  [num0: 14.000000] [num1 50.000000]
[Epoch 20/500] [Batch 440/676] [D loss: -0.060282] [G loss: 0.141605] [d1 loss: 0.118994] [d2 loss: 0.154802]  [sq d1 d2: 0.001282]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 460/676] [D loss: -0.074032] [G loss: 0.136881] [d1 loss: 0.065061] [d2 loss: 0.075019]  [sq d1 d2: 0.000099]  [num0: 17.000000] [num1 47.000000]
[Epoch 20/500] [Batch 480/676] [D loss: -0.065316] [G loss: 0.139519] [d1 loss: 0.176317] [d2 loss: 0.219844]  [sq d1 d2: 0.001895]  [num0: 18.000000] [num1 46.000000]
[Epoch 20/500] [Batch 500/676] [D loss: -0.062374] [G loss: 0.121913] [d1 loss: 0.117625] [d2 loss: 0.129428]  [sq d1 d2: 0.000139]  [num0: 12.000000] [num1 52.000000]
[Epoch 20/500] [Batch 520/676] [D loss: -0.047500] [G loss: 0.149082] [d1 loss: 0.109848] [d2 loss: 0.122909]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 540/676] [D loss: -0.055253] [G loss: 0.142454] [d1 loss: 0.101628] [d2 loss: 0.133222]  [sq d1 d2: 0.000998]  [num0: 10.000000] [num1 54.000000]
[Epoch 20/500] [Batch 560/676] [D loss: -0.054740] [G loss: 0.131969] [d1 loss: 0.104969] [d2 loss: 0.162646]  [sq d1 d2: 0.003327]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 580/676] [D loss: -0.062807] [G loss: 0.115813] [d1 loss: 0.162560] [d2 loss: 0.164364]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 20/500] [Batch 600/676] [D loss: -0.060718] [G loss: 0.089735] [d1 loss: 0.111689] [d2 loss: 0.135071]  [sq d1 d2: 0.000547]  [num0: 20.000000] [num1 44.000000]
[Epoch 20/500] [Batch 620/676] [D loss: -0.057201] [G loss: 0.046866] [d1 loss: 0.083599] [d2 loss: 0.112545]  [sq d1 d2: 0.000838]  [num0: 16.000000] [num1 48.000000]
[Epoch 20/500] [Batch 640/676] [D loss: -0.054771] [G loss: 0.044659] [d1 loss: 0.044488] [d2 loss: 0.057516]  [sq d1 d2: 0.000170]  [num0: 17.000000] [num1 47.000000]
[Epoch 20/500] [Batch 660/676] [D loss: -0.052209] [G loss: 0.047305] [d1 loss: 0.124730] [d2 loss: 0.149667]  [sq d1 d2: 0.000622]  [num0: 16.000000] [num1 48.000000]
[Epoch 21/500] [Batch 0/676] [D loss: -0.061564] [G loss: 0.052745] [d1 loss: 0.143773] [d2 loss: 0.147954]  [sq d1 d2: 0.000017]  [num0: 12.000000] [num1 52.000000]
[Epoch 21/500] [Batch 20/676] [D loss: -0.068306] [G loss: 0.031927] [d1 loss: 0.142035] [d2 loss: 0.154558]  [sq d1 d2: 0.000157]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 40/676] [D loss: -0.085071] [G loss: 0.026709] [d1 loss: 0.081614] [d2 loss: 0.093948]  [sq d1 d2: 0.000152]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 60/676] [D loss: -0.069556] [G loss: 0.063507] [d1 loss: 0.086428] [d2 loss: 0.084548]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 80/676] [D loss: -0.049961] [G loss: 0.086533] [d1 loss: 0.194748] [d2 loss: 0.202863]  [sq d1 d2: 0.000066]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 100/676] [D loss: -0.052718] [G loss: 0.098591] [d1 loss: 0.103823] [d2 loss: 0.112277]  [sq d1 d2: 0.000071]  [num0: 12.000000] [num1 52.000000]

[Epoch 21/500] [Batch 120/676] [D loss: -0.066866] [G loss: 0.128210] [d1 loss: 0.119482] [d2 loss: 0.111510]  [sq d1 d2: 0.000064]  [num0: 11.000000] [num1 53.000000]
[Epoch 21/500] [Batch 140/676] [D loss: -0.051812] [G loss: 0.143448] [d1 loss: 0.066700] [d2 loss: 0.069111]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 21/500] [Batch 160/676] [D loss: -0.058214] [G loss: 0.167268] [d1 loss: 0.090263] [d2 loss: 0.121915]  [sq d1 d2: 0.001002]  [num0: 15.000000] [num1 49.000000]
[Epoch 21/500] [Batch 180/676] [D loss: -0.051778] [G loss: 0.175301] [d1 loss: 0.083401] [d2 loss: 0.119733]  [sq d1 d2: 0.001320]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 200/676] [D loss: -0.051535] [G loss: 0.195684] [d1 loss: 0.169974] [d2 loss: 0.200055]  [sq d1 d2: 0.000905]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 220/676] [D loss: -0.049437] [G loss: 0.178054] [d1 loss: 0.100052] [d2 loss: 0.099941]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 21/500] [Batch 240/676] [D loss: -0.050034] [G loss: 0.204655] [d1 loss: 0.098935] [d2 loss: 0.084654]  [sq d1 d2: 0.000204]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 260/676] [D loss: -0.044628] [G loss: 0.225099] [d1 loss: 0.084272] [d2 loss: 0.098630]  [sq d1 d2: 0.000206]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 280/676] [D loss: -0.056144] [G loss: 0.231431] [d1 loss: 0.121768] [d2 loss: 0.141660]  [sq d1 d2: 0.000396]  [num0: 15.000000] [num1 49.000000]
[Epoch 21/500] [Batch 300/676] [D loss: -0.062789] [G loss: 0.240350] [d1 loss: 0.147696] [d2 loss: 0.155306]  [sq d1 d2: 0.000058]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 320/676] [D loss: -0.069805] [G loss: 0.262384] [d1 loss: 0.070420] [d2 loss: 0.081286]  [sq d1 d2: 0.000118]  [num0: 11.000000] [num1 53.000000]
[Epoch 21/500] [Batch 340/676] [D loss: -0.065866] [G loss: 0.244456] [d1 loss: 0.121079] [d2 loss: 0.155336]  [sq d1 d2: 0.001173]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 360/676] [D loss: -0.064354] [G loss: 0.246799] [d1 loss: 0.110082] [d2 loss: 0.131358]  [sq d1 d2: 0.000453]  [num0: 18.000000] [num1 46.000000]
[Epoch 21/500] [Batch 380/676] [D loss: -0.056611] [G loss: 0.228477] [d1 loss: 0.174446] [d2 loss: 0.157320]  [sq d1 d2: 0.000293]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 400/676] [D loss: -0.054850] [G loss: 0.219180] [d1 loss: 0.100251] [d2 loss: 0.123501]  [sq d1 d2: 0.000541]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 420/676] [D loss: -0.051560] [G loss: 0.198952] [d1 loss: 0.098861] [d2 loss: 0.140678]  [sq d1 d2: 0.001749]  [num0: 15.000000] [num1 49.000000]
[Epoch 21/500] [Batch 440/676] [D loss: -0.063576] [G loss: 0.158818] [d1 loss: 0.146730] [d2 loss: 0.145659]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 21/500] [Batch 460/676] [D loss: -0.054008] [G loss: 0.152080] [d1 loss: 0.105399] [d2 loss: 0.127347]  [sq d1 d2: 0.000482]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 480/676] [D loss: -0.057074] [G loss: 0.125571] [d1 loss: 0.154028] [d2 loss: 0.141387]  [sq d1 d2: 0.000160]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 500/676] [D loss: -0.048976] [G loss: 0.148922] [d1 loss: 0.080597] [d2 loss: 0.094351]  [sq d1 d2: 0.000189]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 520/676] [D loss: -0.057763] [G loss: 0.139042] [d1 loss: 0.082663] [d2 loss: 0.075533]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 540/676] [D loss: -0.069617] [G loss: 0.133581] [d1 loss: 0.105401] [d2 loss: 0.147102]  [sq d1 d2: 0.001739]  [num0: 13.000000] [num1 51.000000]
[Epoch 21/500] [Batch 560/676] [D loss: -0.083252] [G loss: 0.129324] [d1 loss: 0.063360] [d2 loss: 0.071568]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 21/500] [Batch 580/676] [D loss: -0.063182] [G loss: 0.133457] [d1 loss: 0.103380] [d2 loss: 0.108849]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 21/500] [Batch 600/676] [D loss: -0.066792] [G loss: 0.121356] [d1 loss: 0.089082] [d2 loss: 0.111541]  [sq d1 d2: 0.000504]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 620/676] [D loss: -0.058758] [G loss: 0.128016] [d1 loss: 0.051584] [d2 loss: 0.062951]  [sq d1 d2: 0.000129]  [num0: 17.000000] [num1 47.000000]
[Epoch 21/500] [Batch 640/676] [D loss: -0.053213] [G loss: 0.134125] [d1 loss: 0.111091] [d2 loss: 0.116598]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 21/500] [Batch 660/676] [D loss: -0.066172] [G loss: 0.134949] [d1 loss: 0.084394] [d2 loss: 0.104094]  [sq d1 d2: 0.000388]  [num0: 16.000000] [num1 48.000000]
[Epoch 22/500] [Batch 0/676] [D loss: -0.050765] [G loss: 0.125498] [d1 loss: 0.075295] [d2 loss: 0.085384]  [sq d1 d2: 0.000102]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 20/676] [D loss: -0.051860] [G loss: 0.090017] [d1 loss: 0.101379] [d2 loss: 0.120264]  [sq d1 d2: 0.000357]  [num0: 20.000000] [num1 44.000000]
[Epoch 22/500] [Batch 40/676] [D loss: -0.067122] [G loss: 0.082162] [d1 loss: 0.127956] [d2 loss: 0.103705]  [sq d1 d2: 0.000588]  [num0: 18.000000] [num1 46.000000]
[Epoch 22/500] [Batch 60/676] [D loss: -0.043638] [G loss: 0.059216] [d1 loss: 0.144558] [d2 loss: 0.164689]  [sq d1 d2: 0.000405]  [num0: 17.000000] [num1 47.000000]
[Epoch 22/500] [Batch 80/676] [D loss: -0.053214] [G loss: 0.056357] [d1 loss: 0.095314] [d2 loss: 0.117647]  [sq d1 d2: 0.000499]  [num0: 16.000000] [num1 48.000000]
[Epoch 22/500] [Batch 100/676] [D loss: -0.063130] [G loss: 0.034488] [d1 loss: 0.102015] [d2 loss: 0.135594]  [sq d1 d2: 0.001128]  [num0: 10.000000] [num1 54.000000]
[Epoch 22/500] [Batch 120/676] [D loss: -0.050007] [G loss: 0.024411] [d1 loss: 0.081706] [d2 loss: 0.091442]  [sq d1 d2: 0.000095]  [num0: 20.000000] [num1 44.000000]
[Epoch 22/500] [Batch 140/676] [D loss: -0.050018] [G loss: 0.060108] [d1 loss: 0.104600] [d2 loss: 0.123396]  [sq d1 d2: 0.000353]  [num0: 18.000000] [num1 46.000000]
[Epoch 22/500] [Batch 160/676] [D loss: -0.065994] [G loss: 0.054027] [d1 loss: 0.123583] [d2 loss: 0.142216]  [sq d1 d2: 0.000347]  [num0: 16.000000] [num1 48.000000]
[Epoch 22/500] [Batch 180/676] [D loss: -0.060440] [G loss: 0.076362] [d1 loss: 0.090518] [d2 loss: 0.101398]  [sq d1 d2: 0.000118]  [num0: 12.000000] [num1 52.000000]
[Epoch 22/500] [Batch 200/676] [D loss: -0.064893] [G loss: 0.087179] [d1 loss: 0.127639] [d2 loss: 0.120854]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 22/500] [Batch 220/676] [D loss: -0.049914] [G loss: 0.093595] [d1 loss: 0.117260] [d2 loss: 0.141916]  [sq d1 d2: 0.000608]  [num0: 14.000000] [num1 50.000000]
[Epoch 22/500] [Batch 240/676] [D loss: -0.048362] [G loss: 0.115948] [d1 loss: 0.085172] [d2 loss: 0.114429]  [sq d1 d2: 0.000856]  [num0: 14.000000] [num1 50.000000]
[Epoch 22/500] [Batch 260/676] [D loss: -0.050618] [G loss: 0.127439] [d1 loss: 0.078536] [d2 loss: 0.100577]  [sq d1 d2: 0.000486]  [num0: 13.000000] [num1 51.000000]
[Epoch 22/500] [Batch 280/676] [D loss: -0.061984] [G loss: 0.141684] [d1 loss: 0.067674] [d2 loss: 0.064490]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 22/500] [Batch 300/676] [D loss: -0.051045] [G loss: 0.166237] [d1 loss: 0.093114] [d2 loss: 0.099683]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 22/500] [Batch 320/676] [D loss: -0.061780] [G loss: 0.164653] [d1 loss: 0.113691] [d2 loss: 0.155037]  [sq d1 d2: 0.001709]  [num0: 13.000000] [num1 51.000000]
[Epoch 22/500] [Batch 340/676] [D loss: -0.054303] [G loss: 0.179555] [d1 loss: 0.115070] [d2 loss: 0.137046]  [sq d1 d2: 0.000483]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 360/676] [D loss: -0.056088] [G loss: 0.164503] [d1 loss: 0.150696] [d2 loss: 0.152815]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 22/500] [Batch 380/676] [D loss: -0.067620] [G loss: 0.144077] [d1 loss: 0.223308] [d2 loss: 0.228136]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 22/500] [Batch 400/676] [D loss: -0.067519] [G loss: 0.152375] [d1 loss: 0.136365] [d2 loss: 0.142970]  [sq d1 d2: 0.000044]  [num0: 9.000000] [num1 55.000000]
[Epoch 22/500] [Batch 420/676] [D loss: -0.070837] [G loss: 0.106264] [d1 loss: 0.098860] [d2 loss: 0.102598]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 22/500] [Batch 440/676] [D loss: -0.080235] [G loss: 0.087610] [d1 loss: 0.114378] [d2 loss: 0.151373]  [sq d1 d2: 0.001369]  [num0: 13.000000] [num1 51.000000]

[Epoch 22/500] [Batch 460/676] [D loss: -0.033885] [G loss: 0.075923] [d1 loss: 0.114791] [d2 loss: 0.112769]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 480/676] [D loss: -0.044500] [G loss: 0.052201] [d1 loss: 0.072662] [d2 loss: 0.102679]  [sq d1 d2: 0.000901]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 500/676] [D loss: -0.046876] [G loss: 0.053515] [d1 loss: 0.123294] [d2 loss: 0.127589]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 22/500] [Batch 520/676] [D loss: -0.063065] [G loss: 0.055097] [d1 loss: 0.118895] [d2 loss: 0.124553]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 22/500] [Batch 540/676] [D loss: -0.051036] [G loss: 0.036537] [d1 loss: 0.129022] [d2 loss: 0.185420]  [sq d1 d2: 0.003181]  [num0: 12.000000] [num1 52.000000]
[Epoch 22/500] [Batch 560/676] [D loss: -0.057180] [G loss: 0.041542] [d1 loss: 0.068130] [d2 loss: 0.126857]  [sq d1 d2: 0.003449]  [num0: 14.000000] [num1 50.000000]
[Epoch 22/500] [Batch 580/676] [D loss: -0.052642] [G loss: 0.049195] [d1 loss: 0.087874] [d2 loss: 0.106464]  [sq d1 d2: 0.000346]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 600/676] [D loss: -0.070670] [G loss: 0.084465] [d1 loss: 0.101088] [d2 loss: 0.137586]  [sq d1 d2: 0.001332]  [num0: 11.000000] [num1 53.000000]
[Epoch 22/500] [Batch 620/676] [D loss: -0.063093] [G loss: 0.082135] [d1 loss: 0.092839] [d2 loss: 0.101895]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 22/500] [Batch 640/676] [D loss: -0.058529] [G loss: 0.114074] [d1 loss: 0.128456] [d2 loss: 0.230056]  [sq d1 d2: 0.010323]  [num0: 17.000000] [num1 47.000000]
[Epoch 22/500] [Batch 660/676] [D loss: -0.051952] [G loss: 0.130008] [d1 loss: 0.048592] [d2 loss: 0.078312]  [sq d1 d2: 0.000883]  [num0: 14.000000] [num1 50.000000]
[Epoch 23/500] [Batch 0/676] [D loss: -0.058860] [G loss: 0.149161] [d1 loss: 0.173416] [d2 loss: 0.191108]  [sq d1 d2: 0.000313]  [num0: 17.000000] [num1 47.000000]
[Epoch 23/500] [Batch 20/676] [D loss: -0.045955] [G loss: 0.184802] [d1 loss: 0.100483] [d2 loss: 0.139192]  [sq d1 d2: 0.001498]  [num0: 18.000000] [num1 46.000000]
[Epoch 23/500] [Batch 40/676] [D loss: -0.043434] [G loss: 0.212027] [d1 loss: 0.053637] [d2 loss: 0.075047]  [sq d1 d2: 0.000458]  [num0: 13.000000] [num1 51.000000]
[Epoch 23/500] [Batch 60/676] [D loss: -0.072609] [G loss: 0.259918] [d1 loss: 0.081741] [d2 loss: 0.151020]  [sq d1 d2: 0.004800]  [num0: 12.000000] [num1 52.000000]
[Epoch 23/500] [Batch 80/676] [D loss: -0.065323] [G loss: 0.286210] [d1 loss: 0.122251] [d2 loss: 0.167531]  [sq d1 d2: 0.002050]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 100/676] [D loss: -0.058332] [G loss: 0.311978] [d1 loss: 0.145300] [d2 loss: 0.177311]  [sq d1 d2: 0.001025]  [num0: 14.000000] [num1 50.000000]
[Epoch 23/500] [Batch 120/676] [D loss: -0.061158] [G loss: 0.321538] [d1 loss: 0.049645] [d2 loss: 0.085232]  [sq d1 d2: 0.001266]  [num0: 18.000000] [num1 46.000000]
[Epoch 23/500] [Batch 140/676] [D loss: -0.068641] [G loss: 0.280278] [d1 loss: 0.071687] [d2 loss: 0.101443]  [sq d1 d2: 0.000885]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 160/676] [D loss: -0.047091] [G loss: 0.289907] [d1 loss: 0.147631] [d2 loss: 0.167668]  [sq d1 d2: 0.000401]  [num0: 10.000000] [num1 54.000000]
[Epoch 23/500] [Batch 180/676] [D loss: -0.057680] [G loss: 0.259761] [d1 loss: 0.089735] [d2 loss: 0.112081]  [sq d1 d2: 0.000499]  [num0: 13.000000] [num1 51.000000]
[Epoch 23/500] [Batch 200/676] [D loss: -0.051451] [G loss: 0.210564] [d1 loss: 0.088949] [d2 loss: 0.103453]  [sq d1 d2: 0.000210]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 220/676] [D loss: -0.074007] [G loss: 0.174241] [d1 loss: 0.060299] [d2 loss: 0.051378]  [sq d1 d2: 0.000080]  [num0: 13.000000] [num1 51.000000]
[Epoch 23/500] [Batch 240/676] [D loss: -0.036998] [G loss: 0.181427] [d1 loss: 0.104454] [d2 loss: 0.116660]  [sq d1 d2: 0.000149]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 260/676] [D loss: -0.046866] [G loss: 0.162185] [d1 loss: 0.132681] [d2 loss: 0.149265]  [sq d1 d2: 0.000275]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 280/676] [D loss: -0.061386] [G loss: 0.135651] [d1 loss: 0.179900] [d2 loss: 0.221615]  [sq d1 d2: 0.001740]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 300/676] [D loss: -0.067827] [G loss: 0.135372] [d1 loss: 0.136070] [d2 loss: 0.126539]  [sq d1 d2: 0.000091]  [num0: 10.000000] [num1 54.000000]
[Epoch 23/500] [Batch 320/676] [D loss: -0.075732] [G loss: 0.131075] [d1 loss: 0.132228] [d2 loss: 0.135046]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 23/500] [Batch 340/676] [D loss: -0.051308] [G loss: 0.117750] [d1 loss: 0.152918] [d2 loss: 0.183506]  [sq d1 d2: 0.000936]  [num0: 17.000000] [num1 47.000000]
[Epoch 23/500] [Batch 360/676] [D loss: -0.046683] [G loss: 0.113043] [d1 loss: 0.210817] [d2 loss: 0.187902]  [sq d1 d2: 0.000525]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 380/676] [D loss: -0.071234] [G loss: 0.100800] [d1 loss: 0.089794] [d2 loss: 0.109705]  [sq d1 d2: 0.000396]  [num0: 11.000000] [num1 53.000000]
[Epoch 23/500] [Batch 400/676] [D loss: -0.071043] [G loss: 0.091460] [d1 loss: 0.044739] [d2 loss: 0.059573]  [sq d1 d2: 0.000220]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 420/676] [D loss: -0.056271] [G loss: 0.088655] [d1 loss: 0.127431] [d2 loss: 0.159010]  [sq d1 d2: 0.000997]  [num0: 17.000000] [num1 47.000000]
[Epoch 23/500] [Batch 440/676] [D loss: -0.073262] [G loss: 0.106909] [d1 loss: 0.189875] [d2 loss: 0.226244]  [sq d1 d2: 0.001323]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 460/676] [D loss: -0.050895] [G loss: 0.109866] [d1 loss: 0.102229] [d2 loss: 0.113569]  [sq d1 d2: 0.000129]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 480/676] [D loss: -0.058069] [G loss: 0.110421] [d1 loss: 0.141254] [d2 loss: 0.117252]  [sq d1 d2: 0.000576]  [num0: 13.000000] [num1 51.000000]
[Epoch 23/500] [Batch 500/676] [D loss: -0.059220] [G loss: 0.090658] [d1 loss: 0.201898] [d2 loss: 0.191618]  [sq d1 d2: 0.000106]  [num0: 10.000000] [num1 54.000000]
[Epoch 23/500] [Batch 520/676] [D loss: -0.059727] [G loss: 0.092928] [d1 loss: 0.088648] [d2 loss: 0.079907]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 540/676] [D loss: -0.070190] [G loss: 0.087167] [d1 loss: 0.151195] [d2 loss: 0.160773]  [sq d1 d2: 0.000092]  [num0: 12.000000] [num1 52.000000]
[Epoch 23/500] [Batch 560/676] [D loss: -0.066436] [G loss: 0.090997] [d1 loss: 0.104533] [d2 loss: 0.117601]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 580/676] [D loss: -0.061884] [G loss: 0.093665] [d1 loss: 0.168093] [d2 loss: 0.222714]  [sq d1 d2: 0.002983]  [num0: 17.000000] [num1 47.000000]
[Epoch 23/500] [Batch 600/676] [D loss: -0.051870] [G loss: 0.098180] [d1 loss: 0.049796] [d2 loss: 0.078671]  [sq d1 d2: 0.000834]  [num0: 14.000000] [num1 50.000000]
[Epoch 23/500] [Batch 620/676] [D loss: -0.051858] [G loss: 0.102843] [d1 loss: 0.134747] [d2 loss: 0.128948]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 23/500] [Batch 640/676] [D loss: -0.072345] [G loss: 0.079279] [d1 loss: 0.081327] [d2 loss: 0.120967]  [sq d1 d2: 0.001571]  [num0: 16.000000] [num1 48.000000]
[Epoch 23/500] [Batch 660/676] [D loss: -0.060697] [G loss: 0.078278] [d1 loss: 0.178026] [d2 loss: 0.188500]  [sq d1 d2: 0.000110]  [num0: 19.000000] [num1 45.000000]
[Epoch 24/500] [Batch 0/676] [D loss: -0.068227] [G loss: 0.076302] [d1 loss: 0.116138] [d2 loss: 0.139147]  [sq d1 d2: 0.000529]  [num0: 15.000000] [num1 49.000000]
[Epoch 24/500] [Batch 20/676] [D loss: -0.067022] [G loss: 0.067945] [d1 loss: 0.077212] [d2 loss: 0.137416]  [sq d1 d2: 0.003625]  [num0: 15.000000] [num1 49.000000]
[Epoch 24/500] [Batch 40/676] [D loss: -0.063821] [G loss: 0.048340] [d1 loss: 0.091427] [d2 loss: 0.095329]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 24/500] [Batch 60/676] [D loss: -0.066160] [G loss: 0.043884] [d1 loss: 0.102568] [d2 loss: 0.139609]  [sq d1 d2: 0.001372]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 80/676] [D loss: -0.049647] [G loss: 0.025167] [d1 loss: 0.136259] [d2 loss: 0.157616]  [sq d1 d2: 0.000456]  [num0: 14.000000] [num1 50.000000]

[Epoch 24/500] [Batch 100/676] [D loss: -0.041583] [G loss: 0.044883] [d1 loss: 0.111301] [d2 loss: 0.178049]  [sq d1 d2: 0.004455]  [num0: 13.000000] [num1 51.000000]
[Epoch 24/500] [Batch 120/676] [D loss: -0.037742] [G loss: 0.025495] [d1 loss: 0.123442] [d2 loss: 0.159335]  [sq d1 d2: 0.001288]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 140/676] [D loss: -0.049248] [G loss: 0.008154] [d1 loss: 0.228804] [d2 loss: 0.216291]  [sq d1 d2: 0.000157]  [num0: 17.000000] [num1 47.000000]
[Epoch 24/500] [Batch 160/676] [D loss: -0.063445] [G loss: 0.017034] [d1 loss: 0.062271] [d2 loss: 0.096791]  [sq d1 d2: 0.001192]  [num0: 17.000000] [num1 47.000000]
[Epoch 24/500] [Batch 180/676] [D loss: -0.070328] [G loss: 0.018347] [d1 loss: 0.143600] [d2 loss: 0.173061]  [sq d1 d2: 0.000868]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 200/676] [D loss: -0.034177] [G loss: 0.000389] [d1 loss: 0.079033] [d2 loss: 0.072683]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 220/676] [D loss: -0.053840] [G loss: 0.017479] [d1 loss: 0.057734] [d2 loss: 0.082574]  [sq d1 d2: 0.000617]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 240/676] [D loss: -0.058110] [G loss: -0.000014] [d1 loss: 0.065359] [d2 loss: 0.109885]  [sq d1 d2: 0.001983]  [num0: 17.000000] [num1 47.000000]
[Epoch 24/500] [Batch 260/676] [D loss: -0.047686] [G loss: 0.034030] [d1 loss: 0.098198] [d2 loss: 0.095559]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 280/676] [D loss: -0.058479] [G loss: 0.028487] [d1 loss: 0.079083] [d2 loss: 0.099517]  [sq d1 d2: 0.000418]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 300/676] [D loss: -0.054636] [G loss: 0.043545] [d1 loss: 0.114533] [d2 loss: 0.122384]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 320/676] [D loss: -0.045340] [G loss: 0.050975] [d1 loss: 0.066663] [d2 loss: 0.086598]  [sq d1 d2: 0.000397]  [num0: 10.000000] [num1 54.000000]
[Epoch 24/500] [Batch 340/676] [D loss: -0.062292] [G loss: 0.066740] [d1 loss: 0.112756] [d2 loss: 0.129962]  [sq d1 d2: 0.000296]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 360/676] [D loss: -0.071341] [G loss: 0.080385] [d1 loss: 0.242141] [d2 loss: 0.254726]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 380/676] [D loss: -0.053646] [G loss: 0.095276] [d1 loss: 0.091722] [d2 loss: 0.093380]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 400/676] [D loss: -0.058787] [G loss: 0.104728] [d1 loss: 0.108698] [d2 loss: 0.108659]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 420/676] [D loss: -0.068468] [G loss: 0.124596] [d1 loss: 0.076969] [d2 loss: 0.098518]  [sq d1 d2: 0.000464]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 440/676] [D loss: -0.064200] [G loss: 0.090998] [d1 loss: 0.196447] [d2 loss: 0.207901]  [sq d1 d2: 0.000131]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 460/676] [D loss: -0.064875] [G loss: 0.100703] [d1 loss: 0.089187] [d2 loss: 0.087616]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 24/500] [Batch 480/676] [D loss: -0.064231] [G loss: 0.084804] [d1 loss: 0.115615] [d2 loss: 0.125192]  [sq d1 d2: 0.000092]  [num0: 13.000000] [num1 51.000000]
[Epoch 24/500] [Batch 500/676] [D loss: -0.064298] [G loss: 0.070133] [d1 loss: 0.090016] [d2 loss: 0.146144]  [sq d1 d2: 0.003150]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 520/676] [D loss: -0.064271] [G loss: 0.077760] [d1 loss: 0.184222] [d2 loss: 0.184512]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 24/500] [Batch 540/676] [D loss: -0.058402] [G loss: 0.087230] [d1 loss: 0.118077] [d2 loss: 0.169045]  [sq d1 d2: 0.002598]  [num0: 16.000000] [num1 48.000000]
[Epoch 24/500] [Batch 560/676] [D loss: -0.055195] [G loss: 0.065570] [d1 loss: 0.081072] [d2 loss: 0.099697]  [sq d1 d2: 0.000347]  [num0: 13.000000] [num1 51.000000]
[Epoch 24/500] [Batch 580/676] [D loss: -0.066744] [G loss: 0.060155] [d1 loss: 0.163805] [d2 loss: 0.213049]  [sq d1 d2: 0.002425]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 600/676] [D loss: -0.038083] [G loss: 0.056526] [d1 loss: 0.097036] [d2 loss: 0.134850]  [sq d1 d2: 0.001430]  [num0: 15.000000] [num1 49.000000]
[Epoch 24/500] [Batch 620/676] [D loss: -0.057471] [G loss: 0.041796] [d1 loss: 0.083957] [d2 loss: 0.124947]  [sq d1 d2: 0.001680]  [num0: 17.000000] [num1 47.000000]
[Epoch 24/500] [Batch 640/676] [D loss: -0.054988] [G loss: 0.040125] [d1 loss: 0.166383] [d2 loss: 0.221419]  [sq d1 d2: 0.003029]  [num0: 12.000000] [num1 52.000000]
[Epoch 24/500] [Batch 660/676] [D loss: -0.044502] [G loss: 0.021507] [d1 loss: 0.064709] [d2 loss: 0.075489]  [sq d1 d2: 0.000116]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 0/676] [D loss: -0.048031] [G loss: 0.025761] [d1 loss: 0.227763] [d2 loss: 0.206619]  [sq d1 d2: 0.000447]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 20/676] [D loss: -0.042339] [G loss: 0.024100] [d1 loss: 0.102142] [d2 loss: 0.116845]  [sq d1 d2: 0.000216]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 40/676] [D loss: -0.056832] [G loss: 0.008624] [d1 loss: 0.132263] [d2 loss: 0.129065]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 60/676] [D loss: -0.055058] [G loss: 0.010627] [d1 loss: 0.078842] [d2 loss: 0.122863]  [sq d1 d2: 0.001938]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 80/676] [D loss: -0.061109] [G loss: 0.004656] [d1 loss: 0.068010] [d2 loss: 0.091100]  [sq d1 d2: 0.000533]  [num0: 15.000000] [num1 49.000000]
[Epoch 25/500] [Batch 100/676] [D loss: -0.077910] [G loss: 0.003136] [d1 loss: 0.161718] [d2 loss: 0.206882]  [sq d1 d2: 0.002040]  [num0: 20.000000] [num1 44.000000]
[Epoch 25/500] [Batch 120/676] [D loss: -0.060369] [G loss: 0.002818] [d1 loss: 0.132134] [d2 loss: 0.190010]  [sq d1 d2: 0.003350]  [num0: 13.000000] [num1 51.000000]
[Epoch 25/500] [Batch 140/676] [D loss: -0.049746] [G loss: -0.004519] [d1 loss: 0.058981] [d2 loss: 0.079765]  [sq d1 d2: 0.000432]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 160/676] [D loss: -0.064973] [G loss: -0.006317] [d1 loss: 0.078139] [d2 loss: 0.081396]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 25/500] [Batch 180/676] [D loss: -0.059368] [G loss: -0.005622] [d1 loss: 0.186545] [d2 loss: 0.214399]  [sq d1 d2: 0.000776]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 200/676] [D loss: -0.064045] [G loss: 0.010066] [d1 loss: 0.066370] [d2 loss: 0.075181]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 25/500] [Batch 220/676] [D loss: -0.062523] [G loss: 0.008327] [d1 loss: 0.131689] [d2 loss: 0.146318]  [sq d1 d2: 0.000214]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 240/676] [D loss: -0.056147] [G loss: 0.007014] [d1 loss: 0.089118] [d2 loss: 0.124546]  [sq d1 d2: 0.001255]  [num0: 12.000000] [num1 52.000000]
[Epoch 25/500] [Batch 260/676] [D loss: -0.043834] [G loss: 0.029847] [d1 loss: 0.085285] [d2 loss: 0.071617]  [sq d1 d2: 0.000187]  [num0: 13.000000] [num1 51.000000]
[Epoch 25/500] [Batch 280/676] [D loss: -0.056814] [G loss: 0.034840] [d1 loss: 0.161201] [d2 loss: 0.151259]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 300/676] [D loss: -0.023563] [G loss: 0.057348] [d1 loss: 0.146918] [d2 loss: 0.135243]  [sq d1 d2: 0.000136]  [num0: 18.000000] [num1 46.000000]
[Epoch 25/500] [Batch 320/676] [D loss: -0.057966] [G loss: 0.068890] [d1 loss: 0.168014] [d2 loss: 0.150341]  [sq d1 d2: 0.000312]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 340/676] [D loss: -0.062822] [G loss: 0.085120] [d1 loss: 0.177560] [d2 loss: 0.192088]  [sq d1 d2: 0.000211]  [num0: 17.000000] [num1 47.000000]
[Epoch 25/500] [Batch 360/676] [D loss: -0.049258] [G loss: 0.101234] [d1 loss: 0.121923] [d2 loss: 0.109712]  [sq d1 d2: 0.000149]  [num0: 13.000000] [num1 51.000000]
[Epoch 25/500] [Batch 380/676] [D loss: -0.049923] [G loss: 0.101153] [d1 loss: 0.073210] [d2 loss: 0.080265]  [sq d1 d2: 0.000050]  [num0: 12.000000] [num1 52.000000]

[Epoch 25/500] [Batch 400/676] [D loss: -0.047535] [G loss: 0.114262] [d1 loss: 0.212898] [d2 loss: 0.215978]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 25/500] [Batch 420/676] [D loss: -0.063384] [G loss: 0.115682] [d1 loss: 0.067199] [d2 loss: 0.078291]  [sq d1 d2: 0.000123]  [num0: 17.000000] [num1 47.000000]
[Epoch 25/500] [Batch 440/676] [D loss: -0.061911] [G loss: 0.114121] [d1 loss: 0.143995] [d2 loss: 0.127402]  [sq d1 d2: 0.000275]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 460/676] [D loss: -0.051479] [G loss: 0.105694] [d1 loss: 0.228323] [d2 loss: 0.204638]  [sq d1 d2: 0.000561]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 480/676] [D loss: -0.066341] [G loss: 0.117606] [d1 loss: 0.117370] [d2 loss: 0.114634]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 25/500] [Batch 500/676] [D loss: -0.053381] [G loss: 0.104094] [d1 loss: 0.132782] [d2 loss: 0.131470]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 520/676] [D loss: -0.046668] [G loss: 0.097070] [d1 loss: 0.133933] [d2 loss: 0.105775]  [sq d1 d2: 0.000793]  [num0: 17.000000] [num1 47.000000]
[Epoch 25/500] [Batch 540/676] [D loss: -0.043457] [G loss: 0.070838] [d1 loss: 0.247254] [d2 loss: 0.213991]  [sq d1 d2: 0.001106]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 560/676] [D loss: -0.060778] [G loss: 0.036583] [d1 loss: 0.163186] [d2 loss: 0.143125]  [sq d1 d2: 0.000402]  [num0: 15.000000] [num1 49.000000]
[Epoch 25/500] [Batch 580/676] [D loss: -0.059013] [G loss: 0.005189] [d1 loss: 0.119539] [d2 loss: 0.121237]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 25/500] [Batch 600/676] [D loss: -0.051989] [G loss: -0.012160] [d1 loss: 0.076430] [d2 loss: 0.094956]  [sq d1 d2: 0.000343]  [num0: 13.000000] [num1 51.000000]
[Epoch 25/500] [Batch 620/676] [D loss: -0.056179] [G loss: -0.021156] [d1 loss: 0.161602] [d2 loss: 0.235920]  [sq d1 d2: 0.005523]  [num0: 14.000000] [num1 50.000000]
[Epoch 25/500] [Batch 640/676] [D loss: -0.057967] [G loss: -0.048848] [d1 loss: 0.114594] [d2 loss: 0.187455]  [sq d1 d2: 0.005309]  [num0: 16.000000] [num1 48.000000]
[Epoch 25/500] [Batch 660/676] [D loss: -0.050837] [G loss: -0.062576] [d1 loss: 0.091894] [d2 loss: 0.097379]  [sq d1 d2: 0.000030]  [num0: 19.000000] [num1 45.000000]
[Epoch 26/500] [Batch 0/676] [D loss: -0.058154] [G loss: -0.066215] [d1 loss: 0.090949] [d2 loss: 0.105918]  [sq d1 d2: 0.000224]  [num0: 16.000000] [num1 48.000000]
[Epoch 26/500] [Batch 20/676] [D loss: -0.054052] [G loss: -0.068888] [d1 loss: 0.115489] [d2 loss: 0.097251]  [sq d1 d2: 0.000333]  [num0: 19.000000] [num1 45.000000]
[Epoch 26/500] [Batch 40/676] [D loss: -0.054363] [G loss: -0.071139] [d1 loss: 0.241638] [d2 loss: 0.173149]  [sq d1 d2: 0.004691]  [num0: 20.000000] [num1 44.000000]
[Epoch 26/500] [Batch 60/676] [D loss: -0.063134] [G loss: -0.064050] [d1 loss: 0.166584] [d2 loss: 0.188363]  [sq d1 d2: 0.000474]  [num0: 16.000000] [num1 48.000000]
[Epoch 26/500] [Batch 80/676] [D loss: -0.054349] [G loss: -0.061371] [d1 loss: 0.190420] [d2 loss: 0.168640]  [sq d1 d2: 0.000474]  [num0: 11.000000] [num1 53.000000]
[Epoch 26/500] [Batch 100/676] [D loss: -0.039679] [G loss: -0.058673] [d1 loss: 0.081072] [d2 loss: 0.074686]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 26/500] [Batch 120/676] [D loss: -0.054641] [G loss: -0.063126] [d1 loss: 0.212207] [d2 loss: 0.228573]  [sq d1 d2: 0.000268]  [num0: 16.000000] [num1 48.000000]
[Epoch 26/500] [Batch 140/676] [D loss: -0.045209] [G loss: -0.057372] [d1 loss: 0.171510] [d2 loss: 0.185325]  [sq d1 d2: 0.000191]  [num0: 10.000000] [num1 54.000000]
[Epoch 26/500] [Batch 160/676] [D loss: -0.042567] [G loss: -0.039492] [d1 loss: 0.092571] [d2 loss: 0.143217]  [sq d1 d2: 0.002565]  [num0: 18.000000] [num1 46.000000]
[Epoch 26/500] [Batch 180/676] [D loss: -0.046448] [G loss: -0.029522] [d1 loss: 0.098829] [d2 loss: 0.118638]  [sq d1 d2: 0.000392]  [num0: 14.000000] [num1 50.000000]
[Epoch 26/500] [Batch 200/676] [D loss: -0.052104] [G loss: -0.017569] [d1 loss: 0.255926] [d2 loss: 0.184234]  [sq d1 d2: 0.005140]  [num0: 17.000000] [num1 47.000000]
[Epoch 26/500] [Batch 220/676] [D loss: -0.053583] [G loss: -0.022462] [d1 loss: 0.128675] [d2 loss: 0.149544]  [sq d1 d2: 0.000435]  [num0: 12.000000] [num1 52.000000]
[Epoch 26/500] [Batch 240/676] [D loss: -0.048574] [G loss: 0.003844] [d1 loss: 0.110189] [d2 loss: 0.119297]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 26/500] [Batch 260/676] [D loss: -0.071662] [G loss: 0.005785] [d1 loss: 0.141496] [d2 loss: 0.134542]  [sq d1 d2: 0.000048]  [num0: 12.000000] [num1 52.000000]
[Epoch 26/500] [Batch 280/676] [D loss: -0.056197] [G loss: 0.042885] [d1 loss: 0.180141] [d2 loss: 0.184002]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 26/500] [Batch 300/676] [D loss: -0.061696] [G loss: 0.089812] [d1 loss: 0.104237] [d2 loss: 0.130769]  [sq d1 d2: 0.000704]  [num0: 11.000000] [num1 53.000000]
[Epoch 26/500] [Batch 320/676] [D loss: -0.061019] [G loss: 0.133085] [d1 loss: 0.153481] [d2 loss: 0.128805]  [sq d1 d2: 0.000609]  [num0: 15.000000] [num1 49.000000]
[Epoch 26/500] [Batch 340/676] [D loss: -0.047509] [G loss: 0.134755] [d1 loss: 0.158771] [d2 loss: 0.116945]  [sq d1 d2: 0.001749]  [num0: 14.000000] [num1 50.000000]
[Epoch 26/500] [Batch 360/676] [D loss: -0.054186] [G loss: 0.146450] [d1 loss: 0.080096] [d2 loss: 0.079424]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 26/500] [Batch 380/676] [D loss: -0.053574] [G loss: 0.169191] [d1 loss: 0.116403] [d2 loss: 0.091373]  [sq d1 d2: 0.000627]  [num0: 11.000000] [num1 53.000000]
[Epoch 26/500] [Batch 400/676] [D loss: -0.036915] [G loss: 0.173749] [d1 loss: 0.215082] [d2 loss: 0.200864]  [sq d1 d2: 0.000202]  [num0: 19.000000] [num1 45.000000]
[Epoch 26/500] [Batch 420/676] [D loss: -0.043835] [G loss: 0.169472] [d1 loss: 0.128378] [d2 loss: 0.140870]  [sq d1 d2: 0.000156]  [num0: 17.000000] [num1 47.000000]
[Epoch 26/500] [Batch 440/676] [D loss: -0.042765] [G loss: 0.152659] [d1 loss: 0.161156] [d2 loss: 0.110931]  [sq d1 d2: 0.002523]  [num0: 15.000000] [num1 49.000000]
[Epoch 26/500] [Batch 460/676] [D loss: -0.043452] [G loss: 0.135394] [d1 loss: 0.191662] [d2 loss: 0.154041]  [sq d1 d2: 0.001415]  [num0: 17.000000] [num1 47.000000]
[Epoch 26/500] [Batch 480/676] [D loss: -0.048055] [G loss: 0.088547] [d1 loss: 0.166608] [d2 loss: 0.225961]  [sq d1 d2: 0.003523]  [num0: 20.000000] [num1 44.000000]
[Epoch 26/500] [Batch 500/676] [D loss: -0.045920] [G loss: 0.059034] [d1 loss: 0.079770] [d2 loss: 0.114842]  [sq d1 d2: 0.001230]  [num0: 18.000000] [num1 46.000000]
[Epoch 26/500] [Batch 520/676] [D loss: -0.040634] [G loss: 0.014117] [d1 loss: 0.092374] [d2 loss: 0.098629]  [sq d1 d2: 0.000039]  [num0: 16.000000] [num1 48.000000]
[Epoch 26/500] [Batch 540/676] [D loss: -0.043471] [G loss: -0.014755] [d1 loss: 0.136492] [d2 loss: 0.136375]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 26/500] [Batch 560/676] [D loss: -0.062521] [G loss: -0.026104] [d1 loss: 0.161084] [d2 loss: 0.173464]  [sq d1 d2: 0.000153]  [num0: 12.000000] [num1 52.000000]
[Epoch 26/500] [Batch 580/676] [D loss: -0.059300] [G loss: -0.050179] [d1 loss: 0.128103] [d2 loss: 0.121354]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 26/500] [Batch 600/676] [D loss: -0.057908] [G loss: -0.063532] [d1 loss: 0.180561] [d2 loss: 0.168253]  [sq d1 d2: 0.000151]  [num0: 18.000000] [num1 46.000000]
[Epoch 26/500] [Batch 620/676] [D loss: -0.069077] [G loss: -0.077146] [d1 loss: 0.194569] [d2 loss: 0.181294]  [sq d1 d2: 0.000176]  [num0: 17.000000] [num1 47.000000]
[Epoch 26/500] [Batch 640/676] [D loss: -0.051013] [G loss: -0.076021] [d1 loss: 0.123765] [d2 loss: 0.133010]  [sq d1 d2: 0.000085]  [num0: 11.000000] [num1 53.000000]
[Epoch 26/500] [Batch 660/676] [D loss: -0.061718] [G loss: -0.102479] [d1 loss: 0.131682] [d2 loss: 0.129324]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 0/676] [D loss: -0.065126] [G loss: -0.103160] [d1 loss: 0.118538] [d2 loss: 0.112434]  [sq d1 d2: 0.000037]  [num0: 9.000000] [num1 55.000000]

[Epoch 27/500] [Batch 20/676] [D loss: -0.050400] [G loss: -0.129608] [d1 loss: 0.126802] [d2 loss: 0.131032]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 40/676] [D loss: -0.031310] [G loss: -0.131044] [d1 loss: 0.200611] [d2 loss: 0.142571]  [sq d1 d2: 0.003369]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 60/676] [D loss: -0.039592] [G loss: -0.103404] [d1 loss: 0.100593] [d2 loss: 0.087068]  [sq d1 d2: 0.000183]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 80/676] [D loss: -0.039497] [G loss: -0.083460] [d1 loss: 0.089287] [d2 loss: 0.106747]  [sq d1 d2: 0.000305]  [num0: 18.000000] [num1 46.000000]
[Epoch 27/500] [Batch 100/676] [D loss: -0.036472] [G loss: -0.083414] [d1 loss: 0.178412] [d2 loss: 0.129998]  [sq d1 d2: 0.002344]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 120/676] [D loss: -0.050549] [G loss: -0.060498] [d1 loss: 0.190049] [d2 loss: 0.245156]  [sq d1 d2: 0.003037]  [num0: 17.000000] [num1 47.000000]
[Epoch 27/500] [Batch 140/676] [D loss: -0.046833] [G loss: -0.026804] [d1 loss: 0.166998] [d2 loss: 0.223131]  [sq d1 d2: 0.003151]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 160/676] [D loss: -0.040733] [G loss: -0.017464] [d1 loss: 0.233632] [d2 loss: 0.200041]  [sq d1 d2: 0.001128]  [num0: 16.000000] [num1 48.000000]
[Epoch 27/500] [Batch 180/676] [D loss: -0.067407] [G loss: 0.003720] [d1 loss: 0.185744] [d2 loss: 0.135326]  [sq d1 d2: 0.002542]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 200/676] [D loss: -0.048850] [G loss: 0.034708] [d1 loss: 0.078947] [d2 loss: 0.085639]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 27/500] [Batch 220/676] [D loss: -0.052837] [G loss: 0.060267] [d1 loss: 0.196159] [d2 loss: 0.221645]  [sq d1 d2: 0.000650]  [num0: 19.000000] [num1 45.000000]
[Epoch 27/500] [Batch 240/676] [D loss: -0.070317] [G loss: 0.068177] [d1 loss: 0.221066] [d2 loss: 0.170626]  [sq d1 d2: 0.002544]  [num0: 17.000000] [num1 47.000000]
[Epoch 27/500] [Batch 260/676] [D loss: -0.067739] [G loss: 0.101267] [d1 loss: 0.116432] [d2 loss: 0.115913]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 27/500] [Batch 280/676] [D loss: -0.055267] [G loss: 0.107833] [d1 loss: 0.167951] [d2 loss: 0.108943]  [sq d1 d2: 0.003482]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 300/676] [D loss: -0.060160] [G loss: 0.125405] [d1 loss: 0.194747] [d2 loss: 0.179654]  [sq d1 d2: 0.000228]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 320/676] [D loss: -0.044267] [G loss: 0.132498] [d1 loss: 0.222082] [d2 loss: 0.246471]  [sq d1 d2: 0.000595]  [num0: 13.000000] [num1 51.000000]
[Epoch 27/500] [Batch 340/676] [D loss: -0.047892] [G loss: 0.126435] [d1 loss: 0.139830] [d2 loss: 0.138302]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 27/500] [Batch 360/676] [D loss: -0.063099] [G loss: 0.116293] [d1 loss: 0.168534] [d2 loss: 0.183661]  [sq d1 d2: 0.000229]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 380/676] [D loss: -0.043864] [G loss: 0.123595] [d1 loss: 0.122315] [d2 loss: 0.118185]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 27/500] [Batch 400/676] [D loss: -0.044398] [G loss: 0.096483] [d1 loss: 0.118571] [d2 loss: 0.146430]  [sq d1 d2: 0.000776]  [num0: 12.000000] [num1 52.000000]
[Epoch 27/500] [Batch 420/676] [D loss: -0.051127] [G loss: 0.060582] [d1 loss: 0.197151] [d2 loss: 0.166820]  [sq d1 d2: 0.000920]  [num0: 11.000000] [num1 53.000000]
[Epoch 27/500] [Batch 440/676] [D loss: -0.033920] [G loss: 0.035240] [d1 loss: 0.168662] [d2 loss: 0.149632]  [sq d1 d2: 0.000362]  [num0: 13.000000] [num1 51.000000]
[Epoch 27/500] [Batch 460/676] [D loss: -0.043909] [G loss: -0.006335] [d1 loss: 0.122728] [d2 loss: 0.128923]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 27/500] [Batch 480/676] [D loss: -0.051823] [G loss: -0.031407] [d1 loss: 0.182698] [d2 loss: 0.172371]  [sq d1 d2: 0.000107]  [num0: 17.000000] [num1 47.000000]
[Epoch 27/500] [Batch 500/676] [D loss: -0.047116] [G loss: -0.032227] [d1 loss: 0.207437] [d2 loss: 0.173012]  [sq d1 d2: 0.001185]  [num0: 16.000000] [num1 48.000000]
[Epoch 27/500] [Batch 520/676] [D loss: -0.064123] [G loss: -0.042751] [d1 loss: 0.188422] [d2 loss: 0.218297]  [sq d1 d2: 0.000892]  [num0: 18.000000] [num1 46.000000]
[Epoch 27/500] [Batch 540/676] [D loss: -0.068290] [G loss: -0.082781] [d1 loss: 0.110235] [d2 loss: 0.126831]  [sq d1 d2: 0.000275]  [num0: 12.000000] [num1 52.000000]
[Epoch 27/500] [Batch 560/676] [D loss: -0.047476] [G loss: -0.080764] [d1 loss: 0.235477] [d2 loss: 0.240747]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 27/500] [Batch 580/676] [D loss: -0.064401] [G loss: -0.097473] [d1 loss: 0.175543] [d2 loss: 0.147570]  [sq d1 d2: 0.000782]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 600/676] [D loss: -0.045688] [G loss: -0.083241] [d1 loss: 0.103323] [d2 loss: 0.088007]  [sq d1 d2: 0.000235]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 620/676] [D loss: -0.053701] [G loss: -0.090829] [d1 loss: 0.169225] [d2 loss: 0.165206]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 27/500] [Batch 640/676] [D loss: -0.053456] [G loss: -0.065835] [d1 loss: 0.160485] [d2 loss: 0.141735]  [sq d1 d2: 0.000352]  [num0: 14.000000] [num1 50.000000]
[Epoch 27/500] [Batch 660/676] [D loss: -0.053912] [G loss: -0.057806] [d1 loss: 0.106096] [d2 loss: 0.145828]  [sq d1 d2: 0.001579]  [num0: 14.000000] [num1 50.000000]
[Epoch 28/500] [Batch 0/676] [D loss: -0.054142] [G loss: -0.043757] [d1 loss: 0.283464] [d2 loss: 0.190215]  [sq d1 d2: 0.008695]  [num0: 13.000000] [num1 51.000000]
[Epoch 28/500] [Batch 20/676] [D loss: -0.043020] [G loss: -0.015480] [d1 loss: 0.164768] [d2 loss: 0.154462]  [sq d1 d2: 0.000106]  [num0: 14.000000] [num1 50.000000]
[Epoch 28/500] [Batch 40/676] [D loss: -0.052907] [G loss: -0.009275] [d1 loss: 0.086806] [d2 loss: 0.109501]  [sq d1 d2: 0.000515]  [num0: 17.000000] [num1 47.000000]
[Epoch 28/500] [Batch 60/676] [D loss: -0.034895] [G loss: 0.008624] [d1 loss: 0.172313] [d2 loss: 0.182834]  [sq d1 d2: 0.000111]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 80/676] [D loss: -0.045183] [G loss: 0.013147] [d1 loss: 0.117017] [d2 loss: 0.160735]  [sq d1 d2: 0.001911]  [num0: 17.000000] [num1 47.000000]
[Epoch 28/500] [Batch 100/676] [D loss: -0.065386] [G loss: 0.037772] [d1 loss: 0.180994] [d2 loss: 0.139281]  [sq d1 d2: 0.001740]  [num0: 16.000000] [num1 48.000000]
[Epoch 28/500] [Batch 120/676] [D loss: -0.043127] [G loss: 0.072056] [d1 loss: 0.181037] [d2 loss: 0.191098]  [sq d1 d2: 0.000101]  [num0: 13.000000] [num1 51.000000]
[Epoch 28/500] [Batch 140/676] [D loss: -0.064589] [G loss: 0.088216] [d1 loss: 0.186345] [d2 loss: 0.156894]  [sq d1 d2: 0.000867]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 160/676] [D loss: -0.063966] [G loss: 0.106188] [d1 loss: 0.247575] [d2 loss: 0.255828]  [sq d1 d2: 0.000068]  [num0: 18.000000] [num1 46.000000]
[Epoch 28/500] [Batch 180/676] [D loss: -0.066240] [G loss: 0.120167] [d1 loss: 0.311967] [d2 loss: 0.276725]  [sq d1 d2: 0.001242]  [num0: 12.000000] [num1 52.000000]
[Epoch 28/500] [Batch 200/676] [D loss: -0.056653] [G loss: 0.114728] [d1 loss: 0.145752] [d2 loss: 0.170814]  [sq d1 d2: 0.000628]  [num0: 16.000000] [num1 48.000000]
[Epoch 28/500] [Batch 220/676] [D loss: -0.060374] [G loss: 0.116706] [d1 loss: 0.174092] [d2 loss: 0.128279]  [sq d1 d2: 0.002099]  [num0: 14.000000] [num1 50.000000]
[Epoch 28/500] [Batch 240/676] [D loss: -0.050995] [G loss: 0.115305] [d1 loss: 0.223356] [d2 loss: 0.209590]  [sq d1 d2: 0.000190]  [num0: 18.000000] [num1 46.000000]
[Epoch 28/500] [Batch 260/676] [D loss: -0.055040] [G loss: 0.102623] [d1 loss: 0.134835] [d2 loss: 0.155539]  [sq d1 d2: 0.000429]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 280/676] [D loss: -0.052369] [G loss: 0.092320] [d1 loss: 0.134791] [d2 loss: 0.146549]  [sq d1 d2: 0.000138]  [num0: 12.000000] [num1 52.000000]
[Epoch 28/500] [Batch 300/676] [D loss: -0.032890] [G loss: 0.078864] [d1 loss: 0.139944] [d2 loss: 0.138273]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 28/500] [Batch 320/676] [D loss: -0.045336] [G loss: 0.065898] [d1 loss: 0.142316] [d2 loss: 0.160631]  [sq d1 d2: 0.000335]  [num0: 11.000000] [num1 53.000000]

[Epoch 28/500] [Batch 340/676] [D loss: -0.041054] [G loss: 0.030742] [d1 loss: 0.131654] [d2 loss: 0.111019]  [sq d1 d2: 0.000426]  [num0: 12.000000] [num1 52.000000]
[Epoch 28/500] [Batch 360/676] [D loss: -0.039310] [G loss: -0.008640] [d1 loss: 0.136003] [d2 loss: 0.117194]  [sq d1 d2: 0.000354]  [num0: 12.000000] [num1 52.000000]
[Epoch 28/500] [Batch 380/676] [D loss: -0.048635] [G loss: -0.023297] [d1 loss: 0.162032] [d2 loss: 0.161070]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 400/676] [D loss: -0.053888] [G loss: -0.026720] [d1 loss: 0.157723] [d2 loss: 0.170744]  [sq d1 d2: 0.000170]  [num0: 14.000000] [num1 50.000000]
[Epoch 28/500] [Batch 420/676] [D loss: -0.050623] [G loss: -0.046730] [d1 loss: 0.094862] [d2 loss: 0.096257]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 28/500] [Batch 440/676] [D loss: -0.049800] [G loss: -0.057272] [d1 loss: 0.125597] [d2 loss: 0.181355]  [sq d1 d2: 0.003109]  [num0: 20.000000] [num1 44.000000]
[Epoch 28/500] [Batch 460/676] [D loss: -0.050969] [G loss: -0.047369] [d1 loss: 0.201264] [d2 loss: 0.152562]  [sq d1 d2: 0.002372]  [num0: 12.000000] [num1 52.000000]
[Epoch 28/500] [Batch 480/676] [D loss: -0.061827] [G loss: -0.071392] [d1 loss: 0.183326] [d2 loss: 0.198127]  [sq d1 d2: 0.000219]  [num0: 16.000000] [num1 48.000000]
[Epoch 28/500] [Batch 500/676] [D loss: -0.059700] [G loss: -0.077070] [d1 loss: 0.215917] [d2 loss: 0.191439]  [sq d1 d2: 0.000599]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 520/676] [D loss: -0.030763] [G loss: -0.063582] [d1 loss: 0.237138] [d2 loss: 0.200974]  [sq d1 d2: 0.001308]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 540/676] [D loss: -0.054919] [G loss: -0.043517] [d1 loss: 0.123189] [d2 loss: 0.125862]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 28/500] [Batch 560/676] [D loss: -0.067529] [G loss: -0.044620] [d1 loss: 0.176623] [d2 loss: 0.236495]  [sq d1 d2: 0.003585]  [num0: 13.000000] [num1 51.000000]
[Epoch 28/500] [Batch 580/676] [D loss: -0.030037] [G loss: -0.044111] [d1 loss: 0.092489] [d2 loss: 0.099391]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 28/500] [Batch 600/676] [D loss: -0.058860] [G loss: -0.023785] [d1 loss: 0.164315] [d2 loss: 0.151120]  [sq d1 d2: 0.000174]  [num0: 18.000000] [num1 46.000000]
[Epoch 28/500] [Batch 620/676] [D loss: -0.045276] [G loss: -0.015016] [d1 loss: 0.087641] [d2 loss: 0.104789]  [sq d1 d2: 0.000294]  [num0: 9.000000] [num1 55.000000]
[Epoch 28/500] [Batch 640/676] [D loss: -0.040151] [G loss: -0.013640] [d1 loss: 0.197044] [d2 loss: 0.188391]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 28/500] [Batch 660/676] [D loss: -0.027978] [G loss: 0.013758] [d1 loss: 0.144535] [d2 loss: 0.144580]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 0/676] [D loss: -0.041484] [G loss: 0.010296] [d1 loss: 0.200638] [d2 loss: 0.158121]  [sq d1 d2: 0.001808]  [num0: 14.000000] [num1 50.000000]
[Epoch 29/500] [Batch 20/676] [D loss: -0.053135] [G loss: 0.010786] [d1 loss: 0.286615] [d2 loss: 0.196445]  [sq d1 d2: 0.008131]  [num0: 19.000000] [num1 45.000000]
[Epoch 29/500] [Batch 40/676] [D loss: -0.044775] [G loss: 0.032234] [d1 loss: 0.188146] [d2 loss: 0.188885]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 29/500] [Batch 60/676] [D loss: -0.058569] [G loss: 0.027103] [d1 loss: 0.313693] [d2 loss: 0.243356]  [sq d1 d2: 0.004947]  [num0: 20.000000] [num1 44.000000]
[Epoch 29/500] [Batch 80/676] [D loss: -0.056173] [G loss: 0.023437] [d1 loss: 0.148487] [d2 loss: 0.109280]  [sq d1 d2: 0.001537]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 100/676] [D loss: -0.068682] [G loss: 0.034147] [d1 loss: 0.090901] [d2 loss: 0.109773]  [sq d1 d2: 0.000356]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 120/676] [D loss: -0.068191] [G loss: 0.030300] [d1 loss: 0.184475] [d2 loss: 0.183655]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 140/676] [D loss: -0.071565] [G loss: 0.014167] [d1 loss: 0.261773] [d2 loss: 0.326669]  [sq d1 d2: 0.004212]  [num0: 18.000000] [num1 46.000000]
[Epoch 29/500] [Batch 160/676] [D loss: -0.064902] [G loss: 0.020400] [d1 loss: 0.167741] [d2 loss: 0.182676]  [sq d1 d2: 0.000223]  [num0: 19.000000] [num1 45.000000]
[Epoch 29/500] [Batch 180/676] [D loss: -0.073998] [G loss: -0.010546] [d1 loss: 0.205506] [d2 loss: 0.214484]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 200/676] [D loss: -0.043182] [G loss: -0.023397] [d1 loss: 0.295379] [d2 loss: 0.288450]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 29/500] [Batch 220/676] [D loss: -0.021842] [G loss: -0.030507] [d1 loss: 0.232944] [d2 loss: 0.207234]  [sq d1 d2: 0.000661]  [num0: 13.000000] [num1 51.000000]
[Epoch 29/500] [Batch 240/676] [D loss: -0.030156] [G loss: -0.038204] [d1 loss: 0.207418] [d2 loss: 0.218276]  [sq d1 d2: 0.000118]  [num0: 13.000000] [num1 51.000000]
[Epoch 29/500] [Batch 260/676] [D loss: -0.041104] [G loss: -0.034967] [d1 loss: 0.160112] [d2 loss: 0.182082]  [sq d1 d2: 0.000483]  [num0: 18.000000] [num1 46.000000]
[Epoch 29/500] [Batch 280/676] [D loss: -0.046555] [G loss: -0.048786] [d1 loss: 0.230016] [d2 loss: 0.292277]  [sq d1 d2: 0.003876]  [num0: 16.000000] [num1 48.000000]
[Epoch 29/500] [Batch 300/676] [D loss: -0.044573] [G loss: -0.057615] [d1 loss: 0.168477] [d2 loss: 0.170897]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 29/500] [Batch 320/676] [D loss: -0.047403] [G loss: -0.060273] [d1 loss: 0.091616] [d2 loss: 0.090923]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 340/676] [D loss: -0.048171] [G loss: -0.062803] [d1 loss: 0.146266] [d2 loss: 0.157188]  [sq d1 d2: 0.000119]  [num0: 12.000000] [num1 52.000000]
[Epoch 29/500] [Batch 360/676] [D loss: -0.058435] [G loss: -0.071941] [d1 loss: 0.159742] [d2 loss: 0.141717]  [sq d1 d2: 0.000325]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 380/676] [D loss: -0.044327] [G loss: -0.069563] [d1 loss: 0.138905] [d2 loss: 0.170500]  [sq d1 d2: 0.000998]  [num0: 14.000000] [num1 50.000000]
[Epoch 29/500] [Batch 400/676] [D loss: -0.051970] [G loss: -0.072094] [d1 loss: 0.148176] [d2 loss: 0.142402]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 420/676] [D loss: -0.055934] [G loss: -0.058363] [d1 loss: 0.148068] [d2 loss: 0.145237]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 29/500] [Batch 440/676] [D loss: -0.054628] [G loss: -0.064756] [d1 loss: 0.199829] [d2 loss: 0.193936]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 29/500] [Batch 460/676] [D loss: -0.063253] [G loss: -0.052803] [d1 loss: 0.200279] [d2 loss: 0.170222]  [sq d1 d2: 0.000903]  [num0: 17.000000] [num1 47.000000]
[Epoch 29/500] [Batch 480/676] [D loss: -0.038158] [G loss: -0.042688] [d1 loss: 0.177036] [d2 loss: 0.138565]  [sq d1 d2: 0.001480]  [num0: 13.000000] [num1 51.000000]
[Epoch 29/500] [Batch 500/676] [D loss: -0.038738] [G loss: -0.035562] [d1 loss: 0.079948] [d2 loss: 0.093542]  [sq d1 d2: 0.000185]  [num0: 16.000000] [num1 48.000000]
[Epoch 29/500] [Batch 520/676] [D loss: -0.030117] [G loss: -0.019831] [d1 loss: 0.210312] [d2 loss: 0.203929]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 29/500] [Batch 540/676] [D loss: -0.034815] [G loss: -0.001912] [d1 loss: 0.201710] [d2 loss: 0.168893]  [sq d1 d2: 0.001077]  [num0: 13.000000] [num1 51.000000]
[Epoch 29/500] [Batch 560/676] [D loss: -0.037805] [G loss: 0.000760] [d1 loss: 0.105287] [d2 loss: 0.092219]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 29/500] [Batch 580/676] [D loss: -0.045048] [G loss: -0.002650] [d1 loss: 0.190871] [d2 loss: 0.212455]  [sq d1 d2: 0.000466]  [num0: 16.000000] [num1 48.000000]
[Epoch 29/500] [Batch 600/676] [D loss: -0.051074] [G loss: 0.006747] [d1 loss: 0.115764] [d2 loss: 0.135333]  [sq d1 d2: 0.000383]  [num0: 17.000000] [num1 47.000000]
[Epoch 29/500] [Batch 620/676] [D loss: -0.052615] [G loss: 0.019759] [d1 loss: 0.264786] [d2 loss: 0.271195]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 29/500] [Batch 640/676] [D loss: -0.052444] [G loss: 0.039198] [d1 loss: 0.213849] [d2 loss: 0.342983]  [sq d1 d2: 0.016676]  [num0: 19.000000] [num1 45.000000]

[Epoch 29/500] [Batch 660/676] [D loss: -0.045865] [G loss: 0.034757] [d1 loss: 0.158503] [d2 loss: 0.166717]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 0/676] [D loss: -0.044443] [G loss: 0.046490] [d1 loss: 0.180946] [d2 loss: 0.197858]  [sq d1 d2: 0.000286]  [num0: 11.000000] [num1 53.000000]
[Epoch 30/500] [Batch 20/676] [D loss: -0.049074] [G loss: 0.055561] [d1 loss: 0.194434] [d2 loss: 0.183836]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 30/500] [Batch 40/676] [D loss: -0.057005] [G loss: 0.044095] [d1 loss: 0.138563] [d2 loss: 0.133593]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 60/676] [D loss: -0.049391] [G loss: 0.040469] [d1 loss: 0.172548] [d2 loss: 0.175288]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 30/500] [Batch 80/676] [D loss: -0.059874] [G loss: 0.049688] [d1 loss: 0.135085] [d2 loss: 0.125638]  [sq d1 d2: 0.000089]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 100/676] [D loss: -0.041463] [G loss: 0.048881] [d1 loss: 0.195421] [d2 loss: 0.199910]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 120/676] [D loss: -0.040346] [G loss: 0.024160] [d1 loss: 0.205922] [d2 loss: 0.189890]  [sq d1 d2: 0.000257]  [num0: 17.000000] [num1 47.000000]
[Epoch 30/500] [Batch 140/676] [D loss: -0.045988] [G loss: 0.009036] [d1 loss: 0.219464] [d2 loss: 0.270660]  [sq d1 d2: 0.002621]  [num0: 17.000000] [num1 47.000000]
[Epoch 30/500] [Batch 160/676] [D loss: -0.050587] [G loss: 0.006104] [d1 loss: 0.313742] [d2 loss: 0.353570]  [sq d1 d2: 0.001586]  [num0: 19.000000] [num1 45.000000]
[Epoch 30/500] [Batch 180/676] [D loss: -0.044535] [G loss: -0.005784] [d1 loss: 0.154709] [d2 loss: 0.178027]  [sq d1 d2: 0.000544]  [num0: 16.000000] [num1 48.000000]
[Epoch 30/500] [Batch 200/676] [D loss: -0.036805] [G loss: -0.013689] [d1 loss: 0.160366] [d2 loss: 0.156208]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 220/676] [D loss: -0.019758] [G loss: -0.042672] [d1 loss: 0.147451] [d2 loss: 0.136516]  [sq d1 d2: 0.000120]  [num0: 18.000000] [num1 46.000000]
[Epoch 30/500] [Batch 240/676] [D loss: -0.044834] [G loss: -0.040543] [d1 loss: 0.194947] [d2 loss: 0.182347]  [sq d1 d2: 0.000159]  [num0: 18.000000] [num1 46.000000]
[Epoch 30/500] [Batch 260/676] [D loss: -0.053518] [G loss: -0.051284] [d1 loss: 0.189643] [d2 loss: 0.178371]  [sq d1 d2: 0.000127]  [num0: 18.000000] [num1 46.000000]
[Epoch 30/500] [Batch 280/676] [D loss: -0.037494] [G loss: -0.048431] [d1 loss: 0.130690] [d2 loss: 0.133587]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 300/676] [D loss: -0.067782] [G loss: -0.053447] [d1 loss: 0.169219] [d2 loss: 0.137371]  [sq d1 d2: 0.001014]  [num0: 17.000000] [num1 47.000000]
[Epoch 30/500] [Batch 320/676] [D loss: -0.063861] [G loss: -0.042504] [d1 loss: 0.216667] [d2 loss: 0.216200]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 340/676] [D loss: -0.060166] [G loss: -0.047764] [d1 loss: 0.171634] [d2 loss: 0.165712]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 30/500] [Batch 360/676] [D loss: -0.061568] [G loss: -0.046818] [d1 loss: 0.194913] [d2 loss: 0.146069]  [sq d1 d2: 0.002386]  [num0: 17.000000] [num1 47.000000]
[Epoch 30/500] [Batch 380/676] [D loss: -0.054463] [G loss: -0.056962] [d1 loss: 0.169622] [d2 loss: 0.154528]  [sq d1 d2: 0.000228]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 400/676] [D loss: -0.041792] [G loss: -0.062620] [d1 loss: 0.179360] [d2 loss: 0.171594]  [sq d1 d2: 0.000060]  [num0: 12.000000] [num1 52.000000]
[Epoch 30/500] [Batch 420/676] [D loss: -0.037196] [G loss: -0.021013] [d1 loss: 0.183093] [d2 loss: 0.177901]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 440/676] [D loss: -0.040380] [G loss: -0.020303] [d1 loss: 0.202470] [d2 loss: 0.188700]  [sq d1 d2: 0.000190]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 460/676] [D loss: -0.032174] [G loss: -0.004593] [d1 loss: 0.219327] [d2 loss: 0.198117]  [sq d1 d2: 0.000450]  [num0: 14.000000] [num1 50.000000]
[Epoch 30/500] [Batch 480/676] [D loss: -0.039774] [G loss: 0.011738] [d1 loss: 0.225421] [d2 loss: 0.232596]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 30/500] [Batch 500/676] [D loss: -0.037268] [G loss: 0.030964] [d1 loss: 0.187842] [d2 loss: 0.254700]  [sq d1 d2: 0.004470]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 520/676] [D loss: -0.042880] [G loss: 0.035054] [d1 loss: 0.152800] [d2 loss: 0.168382]  [sq d1 d2: 0.000243]  [num0: 11.000000] [num1 53.000000]
[Epoch 30/500] [Batch 540/676] [D loss: -0.047711] [G loss: 0.048895] [d1 loss: 0.283670] [d2 loss: 0.299658]  [sq d1 d2: 0.000256]  [num0: 16.000000] [num1 48.000000]
[Epoch 30/500] [Batch 560/676] [D loss: -0.047963] [G loss: 0.056474] [d1 loss: 0.212542] [d2 loss: 0.223796]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]
[Epoch 30/500] [Batch 580/676] [D loss: -0.045477] [G loss: 0.062338] [d1 loss: 0.172789] [d2 loss: 0.165047]  [sq d1 d2: 0.000060]  [num0: 13.000000] [num1 51.000000]
[Epoch 30/500] [Batch 600/676] [D loss: -0.052970] [G loss: 0.046558] [d1 loss: 0.150786] [d2 loss: 0.163473]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 30/500] [Batch 620/676] [D loss: -0.066635] [G loss: 0.043994] [d1 loss: 0.201392] [d2 loss: 0.188316]  [sq d1 d2: 0.000171]  [num0: 18.000000] [num1 46.000000]
[Epoch 30/500] [Batch 640/676] [D loss: -0.052140] [G loss: 0.048466] [d1 loss: 0.212613] [d2 loss: 0.176952]  [sq d1 d2: 0.001272]  [num0: 19.000000] [num1 45.000000]
[Epoch 30/500] [Batch 660/676] [D loss: -0.046037] [G loss: 0.063012] [d1 loss: 0.289690] [d2 loss: 0.281495]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 31/500] [Batch 0/676] [D loss: -0.048457] [G loss: 0.052789] [d1 loss: 0.328641] [d2 loss: 0.338797]  [sq d1 d2: 0.000103]  [num0: 18.000000] [num1 46.000000]
[Epoch 31/500] [Batch 20/676] [D loss: -0.046337] [G loss: 0.052530] [d1 loss: 0.141920] [d2 loss: 0.149933]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 40/676] [D loss: -0.044540] [G loss: 0.033920] [d1 loss: 0.210346] [d2 loss: 0.181815]  [sq d1 d2: 0.000814]  [num0: 15.000000] [num1 49.000000]
[Epoch 31/500] [Batch 60/676] [D loss: -0.036379] [G loss: 0.014552] [d1 loss: 0.255779] [d2 loss: 0.245663]  [sq d1 d2: 0.000102]  [num0: 15.000000] [num1 49.000000]
[Epoch 31/500] [Batch 80/676] [D loss: -0.038737] [G loss: -0.002059] [d1 loss: 0.185789] [d2 loss: 0.157414]  [sq d1 d2: 0.000805]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 100/676] [D loss: -0.046065] [G loss: -0.022307] [d1 loss: 0.148638] [d2 loss: 0.124344]  [sq d1 d2: 0.000590]  [num0: 18.000000] [num1 46.000000]
[Epoch 31/500] [Batch 120/676] [D loss: -0.037995] [G loss: -0.023012] [d1 loss: 0.124168] [d2 loss: 0.113667]  [sq d1 d2: 0.000110]  [num0: 19.000000] [num1 45.000000]
[Epoch 31/500] [Batch 140/676] [D loss: -0.054354] [G loss: -0.045452] [d1 loss: 0.277618] [d2 loss: 0.332659]  [sq d1 d2: 0.003030]  [num0: 20.000000] [num1 44.000000]
[Epoch 31/500] [Batch 160/676] [D loss: -0.044497] [G loss: -0.044095] [d1 loss: 0.189221] [d2 loss: 0.198509]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 180/676] [D loss: -0.056049] [G loss: -0.105793] [d1 loss: 0.250072] [d2 loss: 0.235498]  [sq d1 d2: 0.000212]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 200/676] [D loss: -0.048199] [G loss: -0.095424] [d1 loss: 0.115551] [d2 loss: 0.135805]  [sq d1 d2: 0.000410]  [num0: 18.000000] [num1 46.000000]
[Epoch 31/500] [Batch 220/676] [D loss: -0.042150] [G loss: -0.074490] [d1 loss: 0.147027] [d2 loss: 0.148126]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 31/500] [Batch 240/676] [D loss: -0.024192] [G loss: -0.086658] [d1 loss: 0.146516] [d2 loss: 0.142293]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 31/500] [Batch 260/676] [D loss: -0.060289] [G loss: -0.090052] [d1 loss: 0.142202] [d2 loss: 0.158108]  [sq d1 d2: 0.000253]  [num0: 15.000000] [num1 49.000000]
[Epoch 31/500] [Batch 280/676] [D loss: -0.041050] [G loss: -0.061100] [d1 loss: 0.244890] [d2 loss: 0.239132]  [sq d1 d2: 0.000033]  [num0: 19.000000] [num1 45.000000]
[Epoch 31/500] [Batch 300/676] [D loss: -0.042474] [G loss: -0.056037] [d1 loss: 0.118047] [d2 loss: 0.098768]  [sq d1 d2: 0.000372]  [num0: 10.000000] [num1 54.000000]

[Epoch 31/500] [Batch 320/676] [D loss: -0.048500] [G loss: -0.044959] [d1 loss: 0.268807] [d2 loss: 0.281174]  [sq d1 d2: 0.000153]  [num0: 19.000000] [num1 45.000000]
[Epoch 31/500] [Batch 340/676] [D loss: -0.044669] [G loss: -0.062938] [d1 loss: 0.247024] [d2 loss: 0.252309]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 31/500] [Batch 360/676] [D loss: -0.062575] [G loss: -0.044882] [d1 loss: 0.198823] [d2 loss: 0.239690]  [sq d1 d2: 0.001670]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 380/676] [D loss: -0.035251] [G loss: -0.043186] [d1 loss: 0.207823] [d2 loss: 0.203740]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 400/676] [D loss: -0.049759] [G loss: -0.031431] [d1 loss: 0.285627] [d2 loss: 0.264446]  [sq d1 d2: 0.000449]  [num0: 18.000000] [num1 46.000000]
[Epoch 31/500] [Batch 420/676] [D loss: -0.051828] [G loss: -0.015975] [d1 loss: 0.150203] [d2 loss: 0.159806]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 440/676] [D loss: -0.040690] [G loss: 0.000143] [d1 loss: 0.251314] [d2 loss: 0.293124]  [sq d1 d2: 0.001748]  [num0: 13.000000] [num1 51.000000]
[Epoch 31/500] [Batch 460/676] [D loss: -0.032252] [G loss: 0.008420] [d1 loss: 0.227554] [d2 loss: 0.255798]  [sq d1 d2: 0.000798]  [num0: 15.000000] [num1 49.000000]
[Epoch 31/500] [Batch 480/676] [D loss: -0.041582] [G loss: -0.003978] [d1 loss: 0.280621] [d2 loss: 0.300437]  [sq d1 d2: 0.000393]  [num0: 19.000000] [num1 45.000000]
[Epoch 31/500] [Batch 500/676] [D loss: -0.036320] [G loss: 0.009604] [d1 loss: 0.148522] [d2 loss: 0.159606]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 31/500] [Batch 520/676] [D loss: -0.033867] [G loss: 0.005323] [d1 loss: 0.264628] [d2 loss: 0.300514]  [sq d1 d2: 0.001288]  [num0: 16.000000] [num1 48.000000]
[Epoch 31/500] [Batch 540/676] [D loss: -0.040678] [G loss: 0.025341] [d1 loss: 0.399494] [d2 loss: 0.400258]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 31/500] [Batch 560/676] [D loss: -0.040127] [G loss: -0.000828] [d1 loss: 0.148722] [d2 loss: 0.128691]  [sq d1 d2: 0.000401]  [num0: 11.000000] [num1 53.000000]
[Epoch 31/500] [Batch 580/676] [D loss: -0.052989] [G loss: -0.004788] [d1 loss: 0.186006] [d2 loss: 0.178363]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 31/500] [Batch 600/676] [D loss: -0.035038] [G loss: -0.010131] [d1 loss: 0.184389] [d2 loss: 0.191168]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 31/500] [Batch 620/676] [D loss: -0.048708] [G loss: -0.008549] [d1 loss: 0.385730] [d2 loss: 0.410093]  [sq d1 d2: 0.000594]  [num0: 16.000000] [num1 48.000000]
[Epoch 31/500] [Batch 640/676] [D loss: -0.048327] [G loss: -0.036488] [d1 loss: 0.172363] [d2 loss: 0.142173]  [sq d1 d2: 0.000911]  [num0: 16.000000] [num1 48.000000]
[Epoch 31/500] [Batch 660/676] [D loss: -0.048669] [G loss: -0.052122] [d1 loss: 0.152551] [d2 loss: 0.146470]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 32/500] [Batch 0/676] [D loss: -0.026116] [G loss: -0.056482] [d1 loss: 0.176752] [d2 loss: 0.177829]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 32/500] [Batch 20/676] [D loss: -0.046570] [G loss: -0.067268] [d1 loss: 0.209516] [d2 loss: 0.216565]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 40/676] [D loss: -0.028413] [G loss: -0.071781] [d1 loss: 0.143271] [d2 loss: 0.133099]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 32/500] [Batch 60/676] [D loss: -0.027680] [G loss: -0.072549] [d1 loss: 0.221447] [d2 loss: 0.237962]  [sq d1 d2: 0.000273]  [num0: 14.000000] [num1 50.000000]
[Epoch 32/500] [Batch 80/676] [D loss: -0.040253] [G loss: -0.062589] [d1 loss: 0.118749] [d2 loss: 0.105167]  [sq d1 d2: 0.000184]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 100/676] [D loss: -0.022046] [G loss: -0.056853] [d1 loss: 0.152661] [d2 loss: 0.136470]  [sq d1 d2: 0.000262]  [num0: 11.000000] [num1 53.000000]
[Epoch 32/500] [Batch 120/676] [D loss: -0.023807] [G loss: -0.049095] [d1 loss: 0.268776] [d2 loss: 0.301507]  [sq d1 d2: 0.001071]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 140/676] [D loss: -0.048324] [G loss: -0.060097] [d1 loss: 0.179370] [d2 loss: 0.171683]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 160/676] [D loss: -0.042531] [G loss: -0.046509] [d1 loss: 0.136947] [d2 loss: 0.117627]  [sq d1 d2: 0.000373]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 180/676] [D loss: -0.045645] [G loss: -0.075788] [d1 loss: 0.297563] [d2 loss: 0.310914]  [sq d1 d2: 0.000178]  [num0: 12.000000] [num1 52.000000]
[Epoch 32/500] [Batch 200/676] [D loss: -0.064587] [G loss: -0.070554] [d1 loss: 0.139456] [d2 loss: 0.156944]  [sq d1 d2: 0.000306]  [num0: 11.000000] [num1 53.000000]
[Epoch 32/500] [Batch 220/676] [D loss: -0.042591] [G loss: -0.083378] [d1 loss: 0.124489] [d2 loss: 0.121455]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 32/500] [Batch 240/676] [D loss: -0.079695] [G loss: -0.096515] [d1 loss: 0.279558] [d2 loss: 0.257722]  [sq d1 d2: 0.000477]  [num0: 12.000000] [num1 52.000000]
[Epoch 32/500] [Batch 260/676] [D loss: -0.050150] [G loss: -0.090333] [d1 loss: 0.144986] [d2 loss: 0.152073]  [sq d1 d2: 0.000050]  [num0: 19.000000] [num1 45.000000]
[Epoch 32/500] [Batch 280/676] [D loss: -0.041680] [G loss: -0.066594] [d1 loss: 0.178678] [d2 loss: 0.153453]  [sq d1 d2: 0.000636]  [num0: 13.000000] [num1 51.000000]
[Epoch 32/500] [Batch 300/676] [D loss: -0.039522] [G loss: -0.069804] [d1 loss: 0.102690] [d2 loss: 0.103964]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 320/676] [D loss: -0.030510] [G loss: -0.043410] [d1 loss: 0.189648] [d2 loss: 0.163920]  [sq d1 d2: 0.000662]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 340/676] [D loss: -0.027241] [G loss: -0.045797] [d1 loss: 0.140880] [d2 loss: 0.138422]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 32/500] [Batch 360/676] [D loss: -0.057229] [G loss: -0.063480] [d1 loss: 0.223749] [d2 loss: 0.261858]  [sq d1 d2: 0.001452]  [num0: 20.000000] [num1 44.000000]
[Epoch 32/500] [Batch 380/676] [D loss: -0.038228] [G loss: -0.052705] [d1 loss: 0.261895] [d2 loss: 0.282511]  [sq d1 d2: 0.000425]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 400/676] [D loss: -0.043635] [G loss: -0.054753] [d1 loss: 0.268755] [d2 loss: 0.250511]  [sq d1 d2: 0.000333]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 420/676] [D loss: -0.040606] [G loss: -0.051797] [d1 loss: 0.221967] [d2 loss: 0.216649]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 440/676] [D loss: -0.028749] [G loss: -0.055897] [d1 loss: 0.186676] [d2 loss: 0.168687]  [sq d1 d2: 0.000324]  [num0: 16.000000] [num1 48.000000]
[Epoch 32/500] [Batch 460/676] [D loss: -0.048875] [G loss: -0.052889] [d1 loss: 0.270855] [d2 loss: 0.251129]  [sq d1 d2: 0.000389]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 480/676] [D loss: -0.039756] [G loss: -0.048457] [d1 loss: 0.143567] [d2 loss: 0.171250]  [sq d1 d2: 0.000766]  [num0: 17.000000] [num1 47.000000]
[Epoch 32/500] [Batch 500/676] [D loss: -0.053430] [G loss: -0.037222] [d1 loss: 0.294567] [d2 loss: 0.277620]  [sq d1 d2: 0.000287]  [num0: 17.000000] [num1 47.000000]
[Epoch 32/500] [Batch 520/676] [D loss: -0.035317] [G loss: -0.036286] [d1 loss: 0.165561] [d2 loss: 0.175557]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 540/676] [D loss: -0.045477] [G loss: -0.036612] [d1 loss: 0.174127] [d2 loss: 0.159914]  [sq d1 d2: 0.000202]  [num0: 13.000000] [num1 51.000000]
[Epoch 32/500] [Batch 560/676] [D loss: -0.039794] [G loss: -0.027121] [d1 loss: 0.290206] [d2 loss: 0.349096]  [sq d1 d2: 0.003468]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 580/676] [D loss: -0.039769] [G loss: -0.019012] [d1 loss: 0.192241] [d2 loss: 0.164468]  [sq d1 d2: 0.000771]  [num0: 15.000000] [num1 49.000000]
[Epoch 32/500] [Batch 600/676] [D loss: -0.042425] [G loss: -0.027728] [d1 loss: 0.258968] [d2 loss: 0.279312]  [sq d1 d2: 0.000414]  [num0: 17.000000] [num1 47.000000]
[Epoch 32/500] [Batch 620/676] [D loss: -0.038053] [G loss: -0.016891] [d1 loss: 0.158301] [d2 loss: 0.156202]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 32/500] [Batch 640/676] [D loss: -0.042935] [G loss: -0.020954] [d1 loss: 0.253687] [d2 loss: 0.264971]  [sq d1 d2: 0.000127]  [num0: 17.000000] [num1 47.000000]
[Epoch 32/500] [Batch 660/676] [D loss: -0.031411] [G loss: -0.023697] [d1 loss: 0.345060] [d2 loss: 0.337876]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]

[Epoch 33/500] [Batch 0/676] [D loss: -0.027719] [G loss: -0.019515] [d1 loss: 0.187336] [d2 loss: 0.185947]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 33/500] [Batch 20/676] [D loss: -0.040030] [G loss: -0.027369] [d1 loss: 0.289432] [d2 loss: 0.282889]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 40/676] [D loss: -0.030542] [G loss: -0.047943] [d1 loss: 0.336924] [d2 loss: 0.339023]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 60/676] [D loss: -0.046965] [G loss: -0.059822] [d1 loss: 0.260757] [d2 loss: 0.266527]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 80/676] [D loss: -0.044727] [G loss: -0.065553] [d1 loss: 0.176816] [d2 loss: 0.148641]  [sq d1 d2: 0.000794]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 100/676] [D loss: -0.042240] [G loss: -0.089873] [d1 loss: 0.100214] [d2 loss: 0.088964]  [sq d1 d2: 0.000127]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 120/676] [D loss: -0.044341] [G loss: -0.082947] [d1 loss: 0.134521] [d2 loss: 0.132032]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 140/676] [D loss: -0.057163] [G loss: -0.094399] [d1 loss: 0.312066] [d2 loss: 0.348990]  [sq d1 d2: 0.001363]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 160/676] [D loss: -0.053594] [G loss: -0.103625] [d1 loss: 0.222133] [d2 loss: 0.240533]  [sq d1 d2: 0.000339]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 180/676] [D loss: -0.047388] [G loss: -0.094123] [d1 loss: 0.228976] [d2 loss: 0.194016]  [sq d1 d2: 0.001222]  [num0: 10.000000] [num1 54.000000]
[Epoch 33/500] [Batch 200/676] [D loss: -0.042236] [G loss: -0.092262] [d1 loss: 0.113160] [d2 loss: 0.132587]  [sq d1 d2: 0.000377]  [num0: 13.000000] [num1 51.000000]
[Epoch 33/500] [Batch 220/676] [D loss: -0.050101] [G loss: -0.078447] [d1 loss: 0.152835] [d2 loss: 0.146052]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 33/500] [Batch 240/676] [D loss: -0.029232] [G loss: -0.068428] [d1 loss: 0.153488] [d2 loss: 0.139053]  [sq d1 d2: 0.000208]  [num0: 13.000000] [num1 51.000000]
[Epoch 33/500] [Batch 260/676] [D loss: -0.030148] [G loss: -0.070423] [d1 loss: 0.170030] [d2 loss: 0.185235]  [sq d1 d2: 0.000231]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 280/676] [D loss: -0.035424] [G loss: -0.059972] [d1 loss: 0.179217] [d2 loss: 0.163265]  [sq d1 d2: 0.000254]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 300/676] [D loss: -0.036420] [G loss: -0.053651] [d1 loss: 0.247724] [d2 loss: 0.245023]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 33/500] [Batch 320/676] [D loss: -0.034610] [G loss: -0.051204] [d1 loss: 0.203410] [d2 loss: 0.197776]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 340/676] [D loss: -0.038357] [G loss: -0.072124] [d1 loss: 0.131451] [d2 loss: 0.111971]  [sq d1 d2: 0.000379]  [num0: 11.000000] [num1 53.000000]
[Epoch 33/500] [Batch 360/676] [D loss: -0.054983] [G loss: -0.047158] [d1 loss: 0.160861] [d2 loss: 0.156474]  [sq d1 d2: 0.000019]  [num0: 11.000000] [num1 53.000000]
[Epoch 33/500] [Batch 380/676] [D loss: -0.036102] [G loss: -0.042602] [d1 loss: 0.187568] [d2 loss: 0.187513]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 400/676] [D loss: -0.040674] [G loss: -0.054770] [d1 loss: 0.105997] [d2 loss: 0.106254]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 420/676] [D loss: -0.029649] [G loss: -0.055165] [d1 loss: 0.298030] [d2 loss: 0.305813]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 33/500] [Batch 440/676] [D loss: -0.033535] [G loss: -0.049420] [d1 loss: 0.125785] [d2 loss: 0.123733]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 460/676] [D loss: -0.052805] [G loss: -0.056669] [d1 loss: 0.151552] [d2 loss: 0.148373]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 33/500] [Batch 480/676] [D loss: -0.031532] [G loss: -0.066234] [d1 loss: 0.237550] [d2 loss: 0.233595]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 500/676] [D loss: -0.032497] [G loss: -0.071865] [d1 loss: 0.168866] [d2 loss: 0.158857]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 520/676] [D loss: -0.045602] [G loss: -0.084187] [d1 loss: 0.198339] [d2 loss: 0.218659]  [sq d1 d2: 0.000413]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 540/676] [D loss: -0.020300] [G loss: -0.098397] [d1 loss: 0.162201] [d2 loss: 0.155367]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 33/500] [Batch 560/676] [D loss: -0.050413] [G loss: -0.104228] [d1 loss: 0.143374] [d2 loss: 0.131096]  [sq d1 d2: 0.000151]  [num0: 18.000000] [num1 46.000000]
[Epoch 33/500] [Batch 580/676] [D loss: -0.037537] [G loss: -0.113167] [d1 loss: 0.096888] [d2 loss: 0.075611]  [sq d1 d2: 0.000453]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 600/676] [D loss: -0.034471] [G loss: -0.109158] [d1 loss: 0.278423] [d2 loss: 0.280551]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 620/676] [D loss: -0.035846] [G loss: -0.106004] [d1 loss: 0.234938] [d2 loss: 0.225905]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 33/500] [Batch 640/676] [D loss: -0.051227] [G loss: -0.100232] [d1 loss: 0.230190] [d2 loss: 0.204719]  [sq d1 d2: 0.000649]  [num0: 15.000000] [num1 49.000000]
[Epoch 33/500] [Batch 660/676] [D loss: -0.054113] [G loss: -0.113644] [d1 loss: 0.155757] [d2 loss: 0.149585]  [sq d1 d2: 0.000038]  [num0: 20.000000] [num1 44.000000]
[Epoch 34/500] [Batch 0/676] [D loss: -0.037628] [G loss: -0.120012] [d1 loss: 0.233192] [d2 loss: 0.234139]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 34/500] [Batch 20/676] [D loss: -0.047275] [G loss: -0.123322] [d1 loss: 0.260386] [d2 loss: 0.250544]  [sq d1 d2: 0.000097]  [num0: 14.000000] [num1 50.000000]
[Epoch 34/500] [Batch 40/676] [D loss: -0.044515] [G loss: -0.107341] [d1 loss: 0.129991] [d2 loss: 0.115017]  [sq d1 d2: 0.000224]  [num0: 16.000000] [num1 48.000000]
[Epoch 34/500] [Batch 60/676] [D loss: -0.039350] [G loss: -0.112807] [d1 loss: 0.207188] [d2 loss: 0.183760]  [sq d1 d2: 0.000549]  [num0: 11.000000] [num1 53.000000]
[Epoch 34/500] [Batch 80/676] [D loss: -0.047309] [G loss: -0.115359] [d1 loss: 0.162222] [d2 loss: 0.149477]  [sq d1 d2: 0.000162]  [num0: 15.000000] [num1 49.000000]
[Epoch 34/500] [Batch 100/676] [D loss: -0.044993] [G loss: -0.127402] [d1 loss: 0.167164] [d2 loss: 0.156101]  [sq d1 d2: 0.000122]  [num0: 18.000000] [num1 46.000000]
[Epoch 34/500] [Batch 120/676] [D loss: -0.044036] [G loss: -0.107793] [d1 loss: 0.123455] [d2 loss: 0.122332]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 34/500] [Batch 140/676] [D loss: -0.025790] [G loss: -0.082307] [d1 loss: 0.181884] [d2 loss: 0.171576]  [sq d1 d2: 0.000106]  [num0: 19.000000] [num1 45.000000]
[Epoch 34/500] [Batch 160/676] [D loss: -0.033472] [G loss: -0.092609] [d1 loss: 0.402555] [d2 loss: 0.445864]  [sq d1 d2: 0.001876]  [num0: 17.000000] [num1 47.000000]
[Epoch 34/500] [Batch 180/676] [D loss: -0.034151] [G loss: -0.102213] [d1 loss: 0.282498] [d2 loss: 0.301712]  [sq d1 d2: 0.000369]  [num0: 15.000000] [num1 49.000000]
[Epoch 34/500] [Batch 200/676] [D loss: -0.028943] [G loss: -0.084597] [d1 loss: 0.172844] [d2 loss: 0.189638]  [sq d1 d2: 0.000282]  [num0: 16.000000] [num1 48.000000]
[Epoch 34/500] [Batch 220/676] [D loss: -0.054863] [G loss: -0.080214] [d1 loss: 0.265184] [d2 loss: 0.250819]  [sq d1 d2: 0.000206]  [num0: 23.000000] [num1 41.000000]
[Epoch 34/500] [Batch 240/676] [D loss: -0.038785] [G loss: -0.089066] [d1 loss: 0.210619] [d2 loss: 0.226324]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 34/500] [Batch 260/676] [D loss: -0.045592] [G loss: -0.085408] [d1 loss: 0.286730] [d2 loss: 0.299512]  [sq d1 d2: 0.000163]  [num0: 19.000000] [num1 45.000000]
[Epoch 34/500] [Batch 280/676] [D loss: -0.036721] [G loss: -0.091577] [d1 loss: 0.122509] [d2 loss: 0.155338]  [sq d1 d2: 0.001078]  [num0: 14.000000] [num1 50.000000]
[Epoch 34/500] [Batch 300/676] [D loss: -0.052936] [G loss: -0.082606] [d1 loss: 0.144029] [d2 loss: 0.141622]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 34/500] [Batch 320/676] [D loss: -0.046839] [G loss: -0.082488] [d1 loss: 0.445285] [d2 loss: 0.460362]  [sq d1 d2: 0.000227]  [num0: 16.000000] [num1 48.000000]
[Epoch 34/500] [Batch 340/676] [D loss: -0.044022] [G loss: -0.075138] [d1 loss: 0.095566] [d2 loss: 0.092336]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]

[Epoch 34/500] [Batch 360/676] [D loss: -0.040573] [G loss: -0.094023] [d1 loss: 0.265672] [d2 loss: 0.249025]  [sq d1 d2: 0.000277]  [num0: 14.000000] [num1 50.000000]
[Epoch 34/500] [Batch 380/676] [D loss: -0.051922] [G loss: -0.120706] [d1 loss: 0.317145] [d2 loss: 0.318833]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 34/500] [Batch 400/676] [D loss: -0.037447] [G loss: -0.109134] [d1 loss: 0.237904] [d2 loss: 0.228042]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 34/500] [Batch 420/676] [D loss: -0.017263] [G loss: -0.081615] [d1 loss: 0.212222] [d2 loss: 0.226130]  [sq d1 d2: 0.000193]  [num0: 19.000000] [num1 45.000000]
[Epoch 34/500] [Batch 440/676] [D loss: -0.034389] [G loss: -0.096696] [d1 loss: 0.279315] [d2 loss: 0.291243]  [sq d1 d2: 0.000142]  [num0: 17.000000] [num1 47.000000]
[Epoch 34/500] [Batch 460/676] [D loss: -0.046645] [G loss: -0.099528] [d1 loss: 0.164535] [d2 loss: 0.162914]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 34/500] [Batch 480/676] [D loss: -0.024673] [G loss: -0.085543] [d1 loss: 0.141290] [d2 loss: 0.143845]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 34/500] [Batch 500/676] [D loss: -0.030521] [G loss: -0.087974] [d1 loss: 0.164463] [d2 loss: 0.158626]  [sq d1 d2: 0.000034]  [num0: 12.000000] [num1 52.000000]
[Epoch 34/500] [Batch 520/676] [D loss: -0.040427] [G loss: -0.106718] [d1 loss: 0.178666] [d2 loss: 0.152026]  [sq d1 d2: 0.000710]  [num0: 17.000000] [num1 47.000000]
[Epoch 34/500] [Batch 540/676] [D loss: -0.078683] [G loss: -0.098728] [d1 loss: 0.178293] [d2 loss: 0.186018]  [sq d1 d2: 0.000060]  [num0: 11.000000] [num1 53.000000]
[Epoch 34/500] [Batch 560/676] [D loss: -0.057514] [G loss: -0.120779] [d1 loss: 0.302632] [d2 loss: 0.308670]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 34/500] [Batch 580/676] [D loss: -0.055500] [G loss: -0.137262] [d1 loss: 0.185930] [d2 loss: 0.176250]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 34/500] [Batch 600/676] [D loss: -0.043401] [G loss: -0.110519] [d1 loss: 0.141867] [d2 loss: 0.141878]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 34/500] [Batch 620/676] [D loss: -0.031715] [G loss: -0.100581] [d1 loss: 0.148174] [d2 loss: 0.159642]  [sq d1 d2: 0.000132]  [num0: 14.000000] [num1 50.000000]
[Epoch 34/500] [Batch 640/676] [D loss: -0.023828] [G loss: -0.111747] [d1 loss: 0.222307] [d2 loss: 0.220204]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 34/500] [Batch 660/676] [D loss: -0.040977] [G loss: -0.108193] [d1 loss: 0.163702] [d2 loss: 0.156832]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 35/500] [Batch 0/676] [D loss: -0.027521] [G loss: -0.109782] [d1 loss: 0.199987] [d2 loss: 0.187253]  [sq d1 d2: 0.000162]  [num0: 17.000000] [num1 47.000000]
[Epoch 35/500] [Batch 20/676] [D loss: -0.023748] [G loss: -0.103186] [d1 loss: 0.211324] [d2 loss: 0.222609]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 40/676] [D loss: -0.046613] [G loss: -0.089819] [d1 loss: 0.247711] [d2 loss: 0.241861]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 35/500] [Batch 60/676] [D loss: -0.046002] [G loss: -0.104794] [d1 loss: 0.175611] [d2 loss: 0.197313]  [sq d1 d2: 0.000471]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 80/676] [D loss: -0.045124] [G loss: -0.093663] [d1 loss: 0.135674] [d2 loss: 0.137502]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 100/676] [D loss: -0.057702] [G loss: -0.118477] [d1 loss: 0.162511] [d2 loss: 0.157638]  [sq d1 d2: 0.000024]  [num0: 20.000000] [num1 44.000000]
[Epoch 35/500] [Batch 120/676] [D loss: -0.040955] [G loss: -0.121288] [d1 loss: 0.184979] [d2 loss: 0.177507]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 35/500] [Batch 140/676] [D loss: -0.047361] [G loss: -0.119204] [d1 loss: 0.187023] [d2 loss: 0.188100]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 35/500] [Batch 160/676] [D loss: -0.006139] [G loss: -0.101734] [d1 loss: 0.160177] [d2 loss: 0.151242]  [sq d1 d2: 0.000080]  [num0: 18.000000] [num1 46.000000]
[Epoch 35/500] [Batch 180/676] [D loss: -0.040237] [G loss: -0.093314] [d1 loss: 0.326093] [d2 loss: 0.366550]  [sq d1 d2: 0.001637]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 200/676] [D loss: -0.044279] [G loss: -0.099889] [d1 loss: 0.122148] [d2 loss: 0.105874]  [sq d1 d2: 0.000265]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 220/676] [D loss: -0.050114] [G loss: -0.099421] [d1 loss: 0.317988] [d2 loss: 0.315495]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 35/500] [Batch 240/676] [D loss: -0.041375] [G loss: -0.101451] [d1 loss: 0.168725] [d2 loss: 0.166171]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 260/676] [D loss: -0.050115] [G loss: -0.098578] [d1 loss: 0.186969] [d2 loss: 0.167501]  [sq d1 d2: 0.000379]  [num0: 17.000000] [num1 47.000000]
[Epoch 35/500] [Batch 280/676] [D loss: -0.044727] [G loss: -0.124087] [d1 loss: 0.140912] [d2 loss: 0.122434]  [sq d1 d2: 0.000341]  [num0: 22.000000] [num1 42.000000]
[Epoch 35/500] [Batch 300/676] [D loss: -0.060484] [G loss: -0.116667] [d1 loss: 0.148232] [d2 loss: 0.131765]  [sq d1 d2: 0.000271]  [num0: 17.000000] [num1 47.000000]
[Epoch 35/500] [Batch 320/676] [D loss: -0.044521] [G loss: -0.131087] [d1 loss: 0.144800] [d2 loss: 0.132534]  [sq d1 d2: 0.000150]  [num0: 17.000000] [num1 47.000000]
[Epoch 35/500] [Batch 340/676] [D loss: -0.043066] [G loss: -0.117678] [d1 loss: 0.331169] [d2 loss: 0.328333]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 35/500] [Batch 360/676] [D loss: -0.036645] [G loss: -0.103318] [d1 loss: 0.256179] [d2 loss: 0.253708]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 380/676] [D loss: -0.056893] [G loss: -0.105145] [d1 loss: 0.184321] [d2 loss: 0.159051]  [sq d1 d2: 0.000639]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 400/676] [D loss: -0.022257] [G loss: -0.081203] [d1 loss: 0.109745] [d2 loss: 0.108829]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 35/500] [Batch 420/676] [D loss: -0.044935] [G loss: -0.077845] [d1 loss: 0.212987] [d2 loss: 0.230726]  [sq d1 d2: 0.000315]  [num0: 11.000000] [num1 53.000000]
[Epoch 35/500] [Batch 440/676] [D loss: -0.032167] [G loss: -0.084429] [d1 loss: 0.136655] [d2 loss: 0.146201]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 35/500] [Batch 460/676] [D loss: -0.061508] [G loss: -0.069786] [d1 loss: 0.200816] [d2 loss: 0.171536]  [sq d1 d2: 0.000857]  [num0: 18.000000] [num1 46.000000]
[Epoch 35/500] [Batch 480/676] [D loss: -0.033532] [G loss: -0.092129] [d1 loss: 0.110352] [d2 loss: 0.101292]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 35/500] [Batch 500/676] [D loss: -0.027020] [G loss: -0.091946] [d1 loss: 0.169884] [d2 loss: 0.194459]  [sq d1 d2: 0.000604]  [num0: 17.000000] [num1 47.000000]
[Epoch 35/500] [Batch 520/676] [D loss: -0.068494] [G loss: -0.109744] [d1 loss: 0.169309] [d2 loss: 0.162296]  [sq d1 d2: 0.000049]  [num0: 14.000000] [num1 50.000000]
[Epoch 35/500] [Batch 540/676] [D loss: -0.048737] [G loss: -0.084979] [d1 loss: 0.159948] [d2 loss: 0.136977]  [sq d1 d2: 0.000528]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 560/676] [D loss: -0.048787] [G loss: -0.121563] [d1 loss: 0.233241] [d2 loss: 0.258948]  [sq d1 d2: 0.000661]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 580/676] [D loss: -0.045500] [G loss: -0.116310] [d1 loss: 0.125630] [d2 loss: 0.125143]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 600/676] [D loss: -0.032344] [G loss: -0.104168] [d1 loss: 0.370197] [d2 loss: 0.367519]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 35/500] [Batch 620/676] [D loss: -0.033913] [G loss: -0.106776] [d1 loss: 0.279252] [d2 loss: 0.315776]  [sq d1 d2: 0.001334]  [num0: 13.000000] [num1 51.000000]
[Epoch 35/500] [Batch 640/676] [D loss: -0.037534] [G loss: -0.113303] [d1 loss: 0.192650] [d2 loss: 0.199577]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 35/500] [Batch 660/676] [D loss: -0.049749] [G loss: -0.117536] [d1 loss: 0.296796] [d2 loss: 0.291559]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 0/676] [D loss: -0.046347] [G loss: -0.113728] [d1 loss: 0.136854] [d2 loss: 0.114374]  [sq d1 d2: 0.000505]  [num0: 18.000000] [num1 46.000000]
[Epoch 36/500] [Batch 20/676] [D loss: -0.049698] [G loss: -0.102440] [d1 loss: 0.158253] [d2 loss: 0.201992]  [sq d1 d2: 0.001913]  [num0: 15.000000] [num1 49.000000]

[Epoch 36/500] [Batch 40/676] [D loss: -0.038997] [G loss: -0.110419] [d1 loss: 0.255067] [d2 loss: 0.260306]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 60/676] [D loss: -0.052028] [G loss: -0.092591] [d1 loss: 0.178122] [d2 loss: 0.174205]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 36/500] [Batch 80/676] [D loss: -0.024073] [G loss: -0.094827] [d1 loss: 0.350527] [d2 loss: 0.329510]  [sq d1 d2: 0.000442]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 100/676] [D loss: -0.068334] [G loss: -0.088384] [d1 loss: 0.387563] [d2 loss: 0.400268]  [sq d1 d2: 0.000161]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 120/676] [D loss: -0.071610] [G loss: -0.085580] [d1 loss: 0.108002] [d2 loss: 0.124574]  [sq d1 d2: 0.000275]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 140/676] [D loss: -0.048266] [G loss: -0.096239] [d1 loss: 0.213418] [d2 loss: 0.216137]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 36/500] [Batch 160/676] [D loss: -0.086870] [G loss: -0.082404] [d1 loss: 0.096338] [d2 loss: 0.076382]  [sq d1 d2: 0.000398]  [num0: 12.000000] [num1 52.000000]
[Epoch 36/500] [Batch 180/676] [D loss: -0.056148] [G loss: -0.088547] [d1 loss: 0.133656] [d2 loss: 0.127957]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 200/676] [D loss: -0.035426] [G loss: -0.096380] [d1 loss: 0.178288] [d2 loss: 0.175121]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 220/676] [D loss: -0.008401] [G loss: -0.068952] [d1 loss: 0.120101] [d2 loss: 0.117935]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 240/676] [D loss: -0.011745] [G loss: -0.034604] [d1 loss: 0.172213] [d2 loss: 0.164167]  [sq d1 d2: 0.000065]  [num0: 18.000000] [num1 46.000000]
[Epoch 36/500] [Batch 260/676] [D loss: -0.023878] [G loss: -0.035486] [d1 loss: 0.232409] [d2 loss: 0.224836]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 280/676] [D loss: -0.026220] [G loss: -0.014076] [d1 loss: 0.222663] [d2 loss: 0.217683]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 36/500] [Batch 300/676] [D loss: -0.034236] [G loss: -0.022020] [d1 loss: 0.130166] [d2 loss: 0.131649]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 36/500] [Batch 320/676] [D loss: -0.045368] [G loss: -0.068098] [d1 loss: 0.198746] [d2 loss: 0.220614]  [sq d1 d2: 0.000478]  [num0: 12.000000] [num1 52.000000]
[Epoch 36/500] [Batch 340/676] [D loss: -0.075089] [G loss: -0.088337] [d1 loss: 0.190951] [d2 loss: 0.204353]  [sq d1 d2: 0.000180]  [num0: 12.000000] [num1 52.000000]
[Epoch 36/500] [Batch 360/676] [D loss: -0.077864] [G loss: -0.137213] [d1 loss: 0.229866] [d2 loss: 0.245680]  [sq d1 d2: 0.000250]  [num0: 13.000000] [num1 51.000000]
[Epoch 36/500] [Batch 380/676] [D loss: -0.075920] [G loss: -0.169996] [d1 loss: 0.262252] [d2 loss: 0.226552]  [sq d1 d2: 0.001274]  [num0: 19.000000] [num1 45.000000]
[Epoch 36/500] [Batch 400/676] [D loss: -0.078549] [G loss: -0.187565] [d1 loss: 0.197718] [d2 loss: 0.206473]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 420/676] [D loss: -0.069690] [G loss: -0.212524] [d1 loss: 0.282610] [d2 loss: 0.291709]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 440/676] [D loss: -0.036416] [G loss: -0.186088] [d1 loss: 0.184734] [d2 loss: 0.197495]  [sq d1 d2: 0.000163]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 460/676] [D loss: -0.048903] [G loss: -0.157587] [d1 loss: 0.181798] [d2 loss: 0.196805]  [sq d1 d2: 0.000225]  [num0: 18.000000] [num1 46.000000]
[Epoch 36/500] [Batch 480/676] [D loss: -0.004822] [G loss: -0.133007] [d1 loss: 0.111656] [d2 loss: 0.092989]  [sq d1 d2: 0.000348]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 500/676] [D loss: -0.002246] [G loss: -0.116528] [d1 loss: 0.128942] [d2 loss: 0.121530]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 520/676] [D loss: 0.003103] [G loss: -0.103655] [d1 loss: 0.295368] [d2 loss: 0.275792]  [sq d1 d2: 0.000383]  [num0: 9.000000] [num1 55.000000]
[Epoch 36/500] [Batch 540/676] [D loss: -0.035685] [G loss: -0.118908] [d1 loss: 0.108780] [d2 loss: 0.108436]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 36/500] [Batch 560/676] [D loss: -0.053386] [G loss: -0.142271] [d1 loss: 0.143376] [d2 loss: 0.151533]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 580/676] [D loss: -0.054605] [G loss: -0.161489] [d1 loss: 0.359531] [d2 loss: 0.377541]  [sq d1 d2: 0.000324]  [num0: 15.000000] [num1 49.000000]
[Epoch 36/500] [Batch 600/676] [D loss: -0.066306] [G loss: -0.177294] [d1 loss: 0.219838] [d2 loss: 0.203170]  [sq d1 d2: 0.000278]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 620/676] [D loss: -0.069933] [G loss: -0.175159] [d1 loss: 0.224056] [d2 loss: 0.211410]  [sq d1 d2: 0.000160]  [num0: 14.000000] [num1 50.000000]
[Epoch 36/500] [Batch 640/676] [D loss: -0.080990] [G loss: -0.171000] [d1 loss: 0.116875] [d2 loss: 0.096906]  [sq d1 d2: 0.000399]  [num0: 16.000000] [num1 48.000000]
[Epoch 36/500] [Batch 660/676] [D loss: -0.079762] [G loss: -0.172087] [d1 loss: 0.119969] [d2 loss: 0.113843]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 37/500] [Batch 0/676] [D loss: -0.044724] [G loss: -0.168776] [d1 loss: 0.248925] [d2 loss: 0.266005]  [sq d1 d2: 0.000292]  [num0: 19.000000] [num1 45.000000]
[Epoch 37/500] [Batch 20/676] [D loss: -0.053123] [G loss: -0.128474] [d1 loss: 0.201389] [d2 loss: 0.167636]  [sq d1 d2: 0.001139]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 40/676] [D loss: -0.013800] [G loss: -0.090223] [d1 loss: 0.143712] [d2 loss: 0.146377]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 37/500] [Batch 60/676] [D loss: -0.005740] [G loss: -0.054062] [d1 loss: 0.149678] [d2 loss: 0.170341]  [sq d1 d2: 0.000427]  [num0: 12.000000] [num1 52.000000]
[Epoch 37/500] [Batch 80/676] [D loss: -0.035261] [G loss: -0.043969] [d1 loss: 0.129754] [d2 loss: 0.120557]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 100/676] [D loss: -0.035530] [G loss: -0.061852] [d1 loss: 0.140028] [d2 loss: 0.132090]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 120/676] [D loss: -0.039029] [G loss: -0.109869] [d1 loss: 0.105934] [d2 loss: 0.133670]  [sq d1 d2: 0.000769]  [num0: 17.000000] [num1 47.000000]
[Epoch 37/500] [Batch 140/676] [D loss: -0.053225] [G loss: -0.108601] [d1 loss: 0.174174] [d2 loss: 0.184107]  [sq d1 d2: 0.000099]  [num0: 20.000000] [num1 44.000000]
[Epoch 37/500] [Batch 160/676] [D loss: -0.062100] [G loss: -0.117578] [d1 loss: 0.175897] [d2 loss: 0.177980]  [sq d1 d2: 0.000004]  [num0: 10.000000] [num1 54.000000]
[Epoch 37/500] [Batch 180/676] [D loss: -0.043325] [G loss: -0.142028] [d1 loss: 0.248861] [d2 loss: 0.246893]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 37/500] [Batch 200/676] [D loss: -0.053932] [G loss: -0.146589] [d1 loss: 0.116047] [d2 loss: 0.127635]  [sq d1 d2: 0.000134]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 220/676] [D loss: -0.048662] [G loss: -0.141193] [d1 loss: 0.191677] [d2 loss: 0.202035]  [sq d1 d2: 0.000107]  [num0: 15.000000] [num1 49.000000]
[Epoch 37/500] [Batch 240/676] [D loss: -0.042307] [G loss: -0.154125] [d1 loss: 0.226560] [d2 loss: 0.241071]  [sq d1 d2: 0.000211]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 260/676] [D loss: -0.079212] [G loss: -0.137582] [d1 loss: 0.282197] [d2 loss: 0.262636]  [sq d1 d2: 0.000383]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 280/676] [D loss: -0.025842] [G loss: -0.141883] [d1 loss: 0.153279] [d2 loss: 0.146518]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 37/500] [Batch 300/676] [D loss: -0.004694] [G loss: -0.110994] [d1 loss: 0.125064] [d2 loss: 0.116703]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 320/676] [D loss: -0.057162] [G loss: -0.107278] [d1 loss: 0.152728] [d2 loss: 0.151036]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 37/500] [Batch 340/676] [D loss: -0.031096] [G loss: -0.084860] [d1 loss: 0.177281] [d2 loss: 0.203768]  [sq d1 d2: 0.000702]  [num0: 15.000000] [num1 49.000000]
[Epoch 37/500] [Batch 360/676] [D loss: -0.017188] [G loss: -0.127982] [d1 loss: 0.134258] [d2 loss: 0.161232]  [sq d1 d2: 0.000728]  [num0: 16.000000] [num1 48.000000]

[Epoch 37/500] [Batch 380/676] [D loss: -0.054801] [G loss: -0.123478] [d1 loss: 0.178855] [d2 loss: 0.193976]  [sq d1 d2: 0.000229]  [num0: 15.000000] [num1 49.000000]
[Epoch 37/500] [Batch 400/676] [D loss: -0.032283] [G loss: -0.116561] [d1 loss: 0.228256] [d2 loss: 0.213078]  [sq d1 d2: 0.000230]  [num0: 13.000000] [num1 51.000000]
[Epoch 37/500] [Batch 420/676] [D loss: -0.101022] [G loss: -0.138981] [d1 loss: 0.164337] [d2 loss: 0.153330]  [sq d1 d2: 0.000121]  [num0: 18.000000] [num1 46.000000]
[Epoch 37/500] [Batch 440/676] [D loss: -0.041890] [G loss: -0.144559] [d1 loss: 0.179803] [d2 loss: 0.207917]  [sq d1 d2: 0.000790]  [num0: 17.000000] [num1 47.000000]
[Epoch 37/500] [Batch 460/676] [D loss: -0.063506] [G loss: -0.167352] [d1 loss: 0.163615] [d2 loss: 0.166056]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 480/676] [D loss: -0.055566] [G loss: -0.195827] [d1 loss: 0.127654] [d2 loss: 0.114026]  [sq d1 d2: 0.000186]  [num0: 19.000000] [num1 45.000000]
[Epoch 37/500] [Batch 500/676] [D loss: -0.050393] [G loss: -0.211229] [d1 loss: 0.190724] [d2 loss: 0.175096]  [sq d1 d2: 0.000244]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 520/676] [D loss: -0.041142] [G loss: -0.202748] [d1 loss: 0.198887] [d2 loss: 0.185882]  [sq d1 d2: 0.000169]  [num0: 18.000000] [num1 46.000000]
[Epoch 37/500] [Batch 540/676] [D loss: -0.034830] [G loss: -0.152082] [d1 loss: 0.176042] [d2 loss: 0.178997]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 560/676] [D loss: -0.005035] [G loss: -0.164722] [d1 loss: 0.109874] [d2 loss: 0.102229]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 37/500] [Batch 580/676] [D loss: -0.013739] [G loss: -0.123599] [d1 loss: 0.194882] [d2 loss: 0.181442]  [sq d1 d2: 0.000181]  [num0: 18.000000] [num1 46.000000]
[Epoch 37/500] [Batch 600/676] [D loss: -0.061745] [G loss: -0.132998] [d1 loss: 0.161084] [d2 loss: 0.144450]  [sq d1 d2: 0.000277]  [num0: 15.000000] [num1 49.000000]
[Epoch 37/500] [Batch 620/676] [D loss: -0.030481] [G loss: -0.119654] [d1 loss: 0.152658] [d2 loss: 0.152004]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 37/500] [Batch 640/676] [D loss: -0.031034] [G loss: -0.160001] [d1 loss: 0.131642] [d2 loss: 0.137359]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 37/500] [Batch 660/676] [D loss: -0.013797] [G loss: -0.131176] [d1 loss: 0.201936] [d2 loss: 0.181703]  [sq d1 d2: 0.000409]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 0/676] [D loss: -0.052579] [G loss: -0.148594] [d1 loss: 0.187395] [d2 loss: 0.186738]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 38/500] [Batch 20/676] [D loss: -0.058361] [G loss: -0.138931] [d1 loss: 0.135762] [d2 loss: 0.151625]  [sq d1 d2: 0.000252]  [num0: 18.000000] [num1 46.000000]
[Epoch 38/500] [Batch 40/676] [D loss: -0.037499] [G loss: -0.134058] [d1 loss: 0.119386] [d2 loss: 0.119701]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 60/676] [D loss: -0.066637] [G loss: -0.129974] [d1 loss: 0.241754] [d2 loss: 0.257056]  [sq d1 d2: 0.000234]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 80/676] [D loss: -0.054157] [G loss: -0.130530] [d1 loss: 0.144584] [d2 loss: 0.135957]  [sq d1 d2: 0.000074]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 100/676] [D loss: -0.048809] [G loss: -0.128244] [d1 loss: 0.224730] [d2 loss: 0.213276]  [sq d1 d2: 0.000131]  [num0: 14.000000] [num1 50.000000]
[Epoch 38/500] [Batch 120/676] [D loss: -0.040301] [G loss: -0.129834] [d1 loss: 0.093143] [d2 loss: 0.097926]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 38/500] [Batch 140/676] [D loss: -0.061376] [G loss: -0.110453] [d1 loss: 0.156816] [d2 loss: 0.160412]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 38/500] [Batch 160/676] [D loss: -0.056827] [G loss: -0.126548] [d1 loss: 0.133130] [d2 loss: 0.146527]  [sq d1 d2: 0.000179]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 180/676] [D loss: -0.045500] [G loss: -0.139200] [d1 loss: 0.154893] [d2 loss: 0.173179]  [sq d1 d2: 0.000334]  [num0: 18.000000] [num1 46.000000]
[Epoch 38/500] [Batch 200/676] [D loss: -0.019034] [G loss: -0.115507] [d1 loss: 0.141368] [d2 loss: 0.136224]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 220/676] [D loss: -0.024853] [G loss: -0.142098] [d1 loss: 0.207004] [d2 loss: 0.210268]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 38/500] [Batch 240/676] [D loss: -0.072610] [G loss: -0.162215] [d1 loss: 0.146770] [d2 loss: 0.143296]  [sq d1 d2: 0.000012]  [num0: 10.000000] [num1 54.000000]
[Epoch 38/500] [Batch 260/676] [D loss: -0.046378] [G loss: -0.136138] [d1 loss: 0.174285] [d2 loss: 0.177111]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 38/500] [Batch 280/676] [D loss: -0.037600] [G loss: -0.154814] [d1 loss: 0.146810] [d2 loss: 0.161433]  [sq d1 d2: 0.000214]  [num0: 12.000000] [num1 52.000000]
[Epoch 38/500] [Batch 300/676] [D loss: -0.041631] [G loss: -0.172869] [d1 loss: 0.159768] [d2 loss: 0.176074]  [sq d1 d2: 0.000266]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 320/676] [D loss: -0.066311] [G loss: -0.172911] [d1 loss: 0.201175] [d2 loss: 0.207808]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 38/500] [Batch 340/676] [D loss: -0.062211] [G loss: -0.199357] [d1 loss: 0.133126] [d2 loss: 0.118561]  [sq d1 d2: 0.000212]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 360/676] [D loss: -0.048986] [G loss: -0.194050] [d1 loss: 0.087876] [d2 loss: 0.105186]  [sq d1 d2: 0.000300]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 380/676] [D loss: -0.052227] [G loss: -0.163885] [d1 loss: 0.169643] [d2 loss: 0.181275]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 400/676] [D loss: -0.044120] [G loss: -0.144347] [d1 loss: 0.175014] [d2 loss: 0.152486]  [sq d1 d2: 0.000508]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 420/676] [D loss: -0.025253] [G loss: -0.098875] [d1 loss: 0.126709] [d2 loss: 0.115633]  [sq d1 d2: 0.000123]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 440/676] [D loss: -0.007490] [G loss: -0.117633] [d1 loss: 0.112872] [d2 loss: 0.119159]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 38/500] [Batch 460/676] [D loss: -0.069184] [G loss: -0.104117] [d1 loss: 0.160347] [d2 loss: 0.176790]  [sq d1 d2: 0.000270]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 480/676] [D loss: -0.052094] [G loss: -0.117651] [d1 loss: 0.167750] [d2 loss: 0.174156]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 38/500] [Batch 500/676] [D loss: -0.051509] [G loss: -0.116958] [d1 loss: 0.238295] [d2 loss: 0.257729]  [sq d1 d2: 0.000378]  [num0: 17.000000] [num1 47.000000]
[Epoch 38/500] [Batch 520/676] [D loss: -0.030984] [G loss: -0.099853] [d1 loss: 0.144208] [d2 loss: 0.144935]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 38/500] [Batch 540/676] [D loss: -0.033786] [G loss: -0.109817] [d1 loss: 0.112875] [d2 loss: 0.119209]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 560/676] [D loss: -0.047209] [G loss: -0.133891] [d1 loss: 0.064828] [d2 loss: 0.055821]  [sq d1 d2: 0.000081]  [num0: 13.000000] [num1 51.000000]
[Epoch 38/500] [Batch 580/676] [D loss: -0.032012] [G loss: -0.103415] [d1 loss: 0.258677] [d2 loss: 0.255542]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 38/500] [Batch 600/676] [D loss: -0.035453] [G loss: -0.117833] [d1 loss: 0.176512] [d2 loss: 0.182028]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 38/500] [Batch 620/676] [D loss: -0.047923] [G loss: -0.128803] [d1 loss: 0.189906] [d2 loss: 0.174957]  [sq d1 d2: 0.000223]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 640/676] [D loss: -0.027222] [G loss: -0.125897] [d1 loss: 0.161153] [d2 loss: 0.163631]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 38/500] [Batch 660/676] [D loss: -0.045959] [G loss: -0.137766] [d1 loss: 0.224059] [d2 loss: 0.220606]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 39/500] [Batch 0/676] [D loss: -0.021979] [G loss: -0.161155] [d1 loss: 0.103081] [d2 loss: 0.107453]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 39/500] [Batch 20/676] [D loss: -0.051421] [G loss: -0.168856] [d1 loss: 0.096276] [d2 loss: 0.119674]  [sq d1 d2: 0.000547]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 40/676] [D loss: -0.031608] [G loss: -0.176963] [d1 loss: 0.217543] [d2 loss: 0.197213]  [sq d1 d2: 0.000413]  [num0: 15.000000] [num1 49.000000]

[Epoch 39/500] [Batch 60/676] [D loss: -0.050184] [G loss: -0.196662] [d1 loss: 0.169793] [d2 loss: 0.183162]  [sq d1 d2: 0.000179]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 80/676] [D loss: -0.023297] [G loss: -0.172635] [d1 loss: 0.070186] [d2 loss: 0.080732]  [sq d1 d2: 0.000111]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 100/676] [D loss: -0.052375] [G loss: -0.184973] [d1 loss: 0.126724] [d2 loss: 0.134426]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 120/676] [D loss: -0.030059] [G loss: -0.174726] [d1 loss: 0.111553] [d2 loss: 0.117875]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 140/676] [D loss: -0.015007] [G loss: -0.170758] [d1 loss: 0.154599] [d2 loss: 0.129053]  [sq d1 d2: 0.000653]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 160/676] [D loss: -0.033785] [G loss: -0.162744] [d1 loss: 0.249942] [d2 loss: 0.258489]  [sq d1 d2: 0.000073]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 180/676] [D loss: -0.024155] [G loss: -0.151574] [d1 loss: 0.142241] [d2 loss: 0.149205]  [sq d1 d2: 0.000049]  [num0: 14.000000] [num1 50.000000]
[Epoch 39/500] [Batch 200/676] [D loss: -0.043151] [G loss: -0.121058] [d1 loss: 0.140485] [d2 loss: 0.138853]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 39/500] [Batch 220/676] [D loss: -0.024967] [G loss: -0.112602] [d1 loss: 0.145258] [d2 loss: 0.125969]  [sq d1 d2: 0.000372]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 240/676] [D loss: -0.039764] [G loss: -0.079806] [d1 loss: 0.258158] [d2 loss: 0.274756]  [sq d1 d2: 0.000276]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 260/676] [D loss: -0.037851] [G loss: -0.067935] [d1 loss: 0.173198] [d2 loss: 0.160557]  [sq d1 d2: 0.000160]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 280/676] [D loss: -0.045899] [G loss: -0.055570] [d1 loss: 0.165526] [d2 loss: 0.186370]  [sq d1 d2: 0.000434]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 300/676] [D loss: -0.041798] [G loss: -0.072362] [d1 loss: 0.118468] [d2 loss: 0.114349]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 320/676] [D loss: -0.034130] [G loss: -0.085445] [d1 loss: 0.165815] [d2 loss: 0.164599]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 340/676] [D loss: -0.049232] [G loss: -0.105335] [d1 loss: 0.156643] [d2 loss: 0.145457]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 39/500] [Batch 360/676] [D loss: -0.050378] [G loss: -0.099532] [d1 loss: 0.163330] [d2 loss: 0.165295]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 380/676] [D loss: -0.086461] [G loss: -0.122232] [d1 loss: 0.273329] [d2 loss: 0.242351]  [sq d1 d2: 0.000960]  [num0: 17.000000] [num1 47.000000]
[Epoch 39/500] [Batch 400/676] [D loss: -0.044574] [G loss: -0.117287] [d1 loss: 0.122413] [d2 loss: 0.130673]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 39/500] [Batch 420/676] [D loss: -0.048440] [G loss: -0.119684] [d1 loss: 0.221610] [d2 loss: 0.218102]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 39/500] [Batch 440/676] [D loss: -0.045579] [G loss: -0.120200] [d1 loss: 0.146304] [d2 loss: 0.143799]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 39/500] [Batch 460/676] [D loss: -0.020324] [G loss: -0.132794] [d1 loss: 0.114772] [d2 loss: 0.097621]  [sq d1 d2: 0.000294]  [num0: 17.000000] [num1 47.000000]
[Epoch 39/500] [Batch 480/676] [D loss: -0.022509] [G loss: -0.155204] [d1 loss: 0.118594] [d2 loss: 0.111787]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 500/676] [D loss: -0.023666] [G loss: -0.151055] [d1 loss: 0.228777] [d2 loss: 0.233916]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 520/676] [D loss: -0.043456] [G loss: -0.184588] [d1 loss: 0.269892] [d2 loss: 0.267918]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 39/500] [Batch 540/676] [D loss: -0.059279] [G loss: -0.175284] [d1 loss: 0.069072] [d2 loss: 0.071285]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 560/676] [D loss: -0.050055] [G loss: -0.167322] [d1 loss: 0.243283] [d2 loss: 0.252312]  [sq d1 d2: 0.000082]  [num0: 13.000000] [num1 51.000000]
[Epoch 39/500] [Batch 580/676] [D loss: -0.069364] [G loss: -0.188440] [d1 loss: 0.178744] [d2 loss: 0.172352]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 39/500] [Batch 600/676] [D loss: -0.043726] [G loss: -0.225205] [d1 loss: 0.120288] [d2 loss: 0.106284]  [sq d1 d2: 0.000196]  [num0: 12.000000] [num1 52.000000]
[Epoch 39/500] [Batch 620/676] [D loss: -0.038485] [G loss: -0.230324] [d1 loss: 0.142457] [d2 loss: 0.142534]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 39/500] [Batch 640/676] [D loss: -0.053551] [G loss: -0.214349] [d1 loss: 0.123748] [d2 loss: 0.141830]  [sq d1 d2: 0.000327]  [num0: 13.000000] [num1 51.000000]
[Epoch 39/500] [Batch 660/676] [D loss: -0.004574] [G loss: -0.190467] [d1 loss: 0.133407] [d2 loss: 0.130832]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 0/676] [D loss: -0.008728] [G loss: -0.149751] [d1 loss: 0.164849] [d2 loss: 0.145971]  [sq d1 d2: 0.000356]  [num0: 11.000000] [num1 53.000000]
[Epoch 40/500] [Batch 20/676] [D loss: -0.030537] [G loss: -0.124537] [d1 loss: 0.124070] [d2 loss: 0.116806]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 40/676] [D loss: -0.016849] [G loss: -0.106282] [d1 loss: 0.063540] [d2 loss: 0.056319]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 60/676] [D loss: -0.042856] [G loss: -0.098854] [d1 loss: 0.245926] [d2 loss: 0.248141]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 40/500] [Batch 80/676] [D loss: -0.033784] [G loss: -0.091263] [d1 loss: 0.165370] [d2 loss: 0.148397]  [sq d1 d2: 0.000288]  [num0: 16.000000] [num1 48.000000]
[Epoch 40/500] [Batch 100/676] [D loss: -0.043417] [G loss: -0.084478] [d1 loss: 0.099443] [d2 loss: 0.089769]  [sq d1 d2: 0.000094]  [num0: 18.000000] [num1 46.000000]
[Epoch 40/500] [Batch 120/676] [D loss: -0.047627] [G loss: -0.085484] [d1 loss: 0.125602] [d2 loss: 0.130989]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 40/500] [Batch 140/676] [D loss: -0.035086] [G loss: -0.100110] [d1 loss: 0.150755] [d2 loss: 0.138791]  [sq d1 d2: 0.000143]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 160/676] [D loss: -0.066266] [G loss: -0.101864] [d1 loss: 0.192738] [d2 loss: 0.183906]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 180/676] [D loss: -0.056009] [G loss: -0.138866] [d1 loss: 0.112019] [d2 loss: 0.126953]  [sq d1 d2: 0.000223]  [num0: 13.000000] [num1 51.000000]
[Epoch 40/500] [Batch 200/676] [D loss: -0.034227] [G loss: -0.112061] [d1 loss: 0.226010] [d2 loss: 0.200342]  [sq d1 d2: 0.000659]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 220/676] [D loss: -0.061259] [G loss: -0.168534] [d1 loss: 0.177761] [d2 loss: 0.167105]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 240/676] [D loss: -0.038500] [G loss: -0.159892] [d1 loss: 0.119238] [d2 loss: 0.156189]  [sq d1 d2: 0.001365]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 260/676] [D loss: -0.022563] [G loss: -0.153328] [d1 loss: 0.125064] [d2 loss: 0.123196]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 40/500] [Batch 280/676] [D loss: -0.011537] [G loss: -0.167756] [d1 loss: 0.166229] [d2 loss: 0.172670]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 300/676] [D loss: -0.023191] [G loss: -0.151158] [d1 loss: 0.109525] [d2 loss: 0.111774]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 320/676] [D loss: -0.034339] [G loss: -0.191392] [d1 loss: 0.123915] [d2 loss: 0.128163]  [sq d1 d2: 0.000018]  [num0: 11.000000] [num1 53.000000]
[Epoch 40/500] [Batch 340/676] [D loss: -0.022469] [G loss: -0.196248] [d1 loss: 0.127847] [d2 loss: 0.128365]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 360/676] [D loss: -0.038161] [G loss: -0.239286] [d1 loss: 0.185938] [d2 loss: 0.187497]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 40/500] [Batch 380/676] [D loss: -0.012510] [G loss: -0.250419] [d1 loss: 0.164070] [d2 loss: 0.173228]  [sq d1 d2: 0.000084]  [num0: 13.000000] [num1 51.000000]
[Epoch 40/500] [Batch 400/676] [D loss: -0.043713] [G loss: -0.249850] [d1 loss: 0.182256] [d2 loss: 0.175125]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]

[Epoch 40/500] [Batch 420/676] [D loss: -0.030690] [G loss: -0.261229] [d1 loss: 0.173220] [d2 loss: 0.233439]  [sq d1 d2: 0.003626]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 440/676] [D loss: -0.046634] [G loss: -0.262919] [d1 loss: 0.203449] [d2 loss: 0.213059]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 460/676] [D loss: -0.035663] [G loss: -0.250575] [d1 loss: 0.187003] [d2 loss: 0.174804]  [sq d1 d2: 0.000149]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 480/676] [D loss: -0.040688] [G loss: -0.260643] [d1 loss: 0.181075] [d2 loss: 0.185574]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 40/500] [Batch 500/676] [D loss: -0.033718] [G loss: -0.223885] [d1 loss: 0.206163] [d2 loss: 0.236959]  [sq d1 d2: 0.000948]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 520/676] [D loss: -0.046502] [G loss: -0.222686] [d1 loss: 0.127725] [d2 loss: 0.144503]  [sq d1 d2: 0.000282]  [num0: 18.000000] [num1 46.000000]
[Epoch 40/500] [Batch 540/676] [D loss: -0.021016] [G loss: -0.190687] [d1 loss: 0.153308] [d2 loss: 0.178459]  [sq d1 d2: 0.000633]  [num0: 14.000000] [num1 50.000000]
[Epoch 40/500] [Batch 560/676] [D loss: -0.042026] [G loss: -0.143253] [d1 loss: 0.171296] [d2 loss: 0.196100]  [sq d1 d2: 0.000615]  [num0: 15.000000] [num1 49.000000]
[Epoch 40/500] [Batch 580/676] [D loss: -0.033339] [G loss: -0.129238] [d1 loss: 0.159128] [d2 loss: 0.157233]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 40/500] [Batch 600/676] [D loss: -0.032277] [G loss: -0.126554] [d1 loss: 0.259239] [d2 loss: 0.281277]  [sq d1 d2: 0.000486]  [num0: 12.000000] [num1 52.000000]
[Epoch 40/500] [Batch 620/676] [D loss: -0.048466] [G loss: -0.142019] [d1 loss: 0.102195] [d2 loss: 0.096303]  [sq d1 d2: 0.000035]  [num0: 12.000000] [num1 52.000000]
[Epoch 40/500] [Batch 640/676] [D loss: -0.055297] [G loss: -0.150103] [d1 loss: 0.206412] [d2 loss: 0.246424]  [sq d1 d2: 0.001601]  [num0: 12.000000] [num1 52.000000]
[Epoch 40/500] [Batch 660/676] [D loss: -0.076456] [G loss: -0.155016] [d1 loss: 0.106800] [d2 loss: 0.104236]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 41/500] [Batch 0/676] [D loss: 0.000649] [G loss: -0.173622] [d1 loss: 0.062049] [d2 loss: 0.067783]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 41/500] [Batch 20/676] [D loss: -0.013121] [G loss: -0.128534] [d1 loss: 0.124143] [d2 loss: 0.103899]  [sq d1 d2: 0.000410]  [num0: 12.000000] [num1 52.000000]
[Epoch 41/500] [Batch 40/676] [D loss: -0.059744] [G loss: -0.124068] [d1 loss: 0.125907] [d2 loss: 0.126538]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 60/676] [D loss: -0.031093] [G loss: -0.132710] [d1 loss: 0.206565] [d2 loss: 0.223625]  [sq d1 d2: 0.000291]  [num0: 16.000000] [num1 48.000000]
[Epoch 41/500] [Batch 80/676] [D loss: -0.014130] [G loss: -0.141559] [d1 loss: 0.168878] [d2 loss: 0.151930]  [sq d1 d2: 0.000287]  [num0: 16.000000] [num1 48.000000]
[Epoch 41/500] [Batch 100/676] [D loss: -0.014148] [G loss: -0.109278] [d1 loss: 0.128698] [d2 loss: 0.138628]  [sq d1 d2: 0.000099]  [num0: 17.000000] [num1 47.000000]
[Epoch 41/500] [Batch 120/676] [D loss: -0.021895] [G loss: -0.091900] [d1 loss: 0.195502] [d2 loss: 0.210944]  [sq d1 d2: 0.000238]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 140/676] [D loss: -0.033661] [G loss: -0.081880] [d1 loss: 0.128770] [d2 loss: 0.121900]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 41/500] [Batch 160/676] [D loss: -0.049161] [G loss: -0.106431] [d1 loss: 0.104048] [d2 loss: 0.110363]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 180/676] [D loss: -0.029643] [G loss: -0.137055] [d1 loss: 0.127180] [d2 loss: 0.134000]  [sq d1 d2: 0.000047]  [num0: 12.000000] [num1 52.000000]
[Epoch 41/500] [Batch 200/676] [D loss: -0.053955] [G loss: -0.178544] [d1 loss: 0.188865] [d2 loss: 0.187874]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 41/500] [Batch 220/676] [D loss: -0.047016] [G loss: -0.215483] [d1 loss: 0.145253] [d2 loss: 0.165123]  [sq d1 d2: 0.000395]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 240/676] [D loss: -0.080404] [G loss: -0.248077] [d1 loss: 0.070397] [d2 loss: 0.073773]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 41/500] [Batch 260/676] [D loss: -0.048007] [G loss: -0.270935] [d1 loss: 0.096202] [d2 loss: 0.083301]  [sq d1 d2: 0.000166]  [num0: 14.000000] [num1 50.000000]
[Epoch 41/500] [Batch 280/676] [D loss: -0.040496] [G loss: -0.241074] [d1 loss: 0.151976] [d2 loss: 0.145087]  [sq d1 d2: 0.000047]  [num0: 20.000000] [num1 44.000000]
[Epoch 41/500] [Batch 300/676] [D loss: 0.016696] [G loss: -0.211861] [d1 loss: 0.083454] [d2 loss: 0.088158]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 41/500] [Batch 320/676] [D loss: -0.023674] [G loss: -0.171807] [d1 loss: 0.083757] [d2 loss: 0.082181]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 41/500] [Batch 340/676] [D loss: -0.032812] [G loss: -0.171165] [d1 loss: 0.175239] [d2 loss: 0.179681]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 360/676] [D loss: -0.010165] [G loss: -0.156492] [d1 loss: 0.193478] [d2 loss: 0.178435]  [sq d1 d2: 0.000226]  [num0: 12.000000] [num1 52.000000]
[Epoch 41/500] [Batch 380/676] [D loss: -0.015206] [G loss: -0.129538] [d1 loss: 0.093862] [d2 loss: 0.105447]  [sq d1 d2: 0.000134]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 400/676] [D loss: -0.030616] [G loss: -0.110847] [d1 loss: 0.159325] [d2 loss: 0.164865]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 41/500] [Batch 420/676] [D loss: -0.040085] [G loss: -0.110319] [d1 loss: 0.129118] [d2 loss: 0.126049]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 440/676] [D loss: -0.028813] [G loss: -0.109332] [d1 loss: 0.258156] [d2 loss: 0.263878]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 41/500] [Batch 460/676] [D loss: -0.062687] [G loss: -0.125764] [d1 loss: 0.218625] [d2 loss: 0.209016]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 41/500] [Batch 480/676] [D loss: -0.041593] [G loss: -0.133095] [d1 loss: 0.085885] [d2 loss: 0.097317]  [sq d1 d2: 0.000131]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 500/676] [D loss: -0.061187] [G loss: -0.137866] [d1 loss: 0.143949] [d2 loss: 0.145207]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 41/500] [Batch 520/676] [D loss: -0.039001] [G loss: -0.138624] [d1 loss: 0.135810] [d2 loss: 0.132337]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 41/500] [Batch 540/676] [D loss: -0.034916] [G loss: -0.146443] [d1 loss: 0.147777] [d2 loss: 0.163855]  [sq d1 d2: 0.000259]  [num0: 13.000000] [num1 51.000000]
[Epoch 41/500] [Batch 560/676] [D loss: -0.028872] [G loss: -0.132283] [d1 loss: 0.186642] [d2 loss: 0.196274]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 580/676] [D loss: -0.025229] [G loss: -0.112512] [d1 loss: 0.096426] [d2 loss: 0.098336]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 600/676] [D loss: -0.022601] [G loss: -0.117746] [d1 loss: 0.201049] [d2 loss: 0.193843]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 620/676] [D loss: -0.025560] [G loss: -0.142879] [d1 loss: 0.153634] [d2 loss: 0.147646]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 640/676] [D loss: -0.020115] [G loss: -0.130105] [d1 loss: 0.257899] [d2 loss: 0.270304]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 41/500] [Batch 660/676] [D loss: -0.030844] [G loss: -0.111513] [d1 loss: 0.114683] [d2 loss: 0.114099]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 42/500] [Batch 0/676] [D loss: -0.012295] [G loss: -0.114899] [d1 loss: 0.195463] [d2 loss: 0.191697]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 20/676] [D loss: -0.028895] [G loss: -0.131709] [d1 loss: 0.154314] [d2 loss: 0.165825]  [sq d1 d2: 0.000132]  [num0: 17.000000] [num1 47.000000]

[Epoch 42/500] [Batch 40/676] [D loss: -0.039950] [G loss: -0.135875] [d1 loss: 0.094587] [d2 loss: 0.092271]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 42/500] [Batch 60/676] [D loss: -0.020186] [G loss: -0.127113] [d1 loss: 0.204559] [d2 loss: 0.203125]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 42/500] [Batch 80/676] [D loss: -0.038413] [G loss: -0.144491] [d1 loss: 0.136386] [d2 loss: 0.147808]  [sq d1 d2: 0.000130]  [num0: 14.000000] [num1 50.000000]
[Epoch 42/500] [Batch 100/676] [D loss: -0.031255] [G loss: -0.169026] [d1 loss: 0.066018] [d2 loss: 0.066111]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 42/500] [Batch 120/676] [D loss: -0.057356] [G loss: -0.168028] [d1 loss: 0.150427] [d2 loss: 0.143446]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 42/500] [Batch 140/676] [D loss: -0.039678] [G loss: -0.175698] [d1 loss: 0.182732] [d2 loss: 0.183089]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 160/676] [D loss: -0.042006] [G loss: -0.180506] [d1 loss: 0.137771] [d2 loss: 0.165318]  [sq d1 d2: 0.000759]  [num0: 14.000000] [num1 50.000000]
[Epoch 42/500] [Batch 180/676] [D loss: -0.022364] [G loss: -0.216505] [d1 loss: 0.154125] [d2 loss: 0.172677]  [sq d1 d2: 0.000344]  [num0: 18.000000] [num1 46.000000]
[Epoch 42/500] [Batch 200/676] [D loss: -0.010254] [G loss: -0.176021] [d1 loss: 0.088690] [d2 loss: 0.101527]  [sq d1 d2: 0.000165]  [num0: 13.000000] [num1 51.000000]
[Epoch 42/500] [Batch 220/676] [D loss: -0.022095] [G loss: -0.186889] [d1 loss: 0.173366] [d2 loss: 0.165479]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 42/500] [Batch 240/676] [D loss: -0.029741] [G loss: -0.155094] [d1 loss: 0.132603] [d2 loss: 0.173010]  [sq d1 d2: 0.001633]  [num0: 16.000000] [num1 48.000000]
[Epoch 42/500] [Batch 260/676] [D loss: -0.027252] [G loss: -0.139910] [d1 loss: 0.131351] [d2 loss: 0.129485]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 280/676] [D loss: -0.041740] [G loss: -0.150391] [d1 loss: 0.115729] [d2 loss: 0.122850]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 300/676] [D loss: -0.046601] [G loss: -0.144888] [d1 loss: 0.105432] [d2 loss: 0.109405]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 42/500] [Batch 320/676] [D loss: -0.037876] [G loss: -0.139645] [d1 loss: 0.113175] [d2 loss: 0.110890]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 42/500] [Batch 340/676] [D loss: -0.039207] [G loss: -0.137933] [d1 loss: 0.210088] [d2 loss: 0.205903]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 42/500] [Batch 360/676] [D loss: -0.024998] [G loss: -0.133101] [d1 loss: 0.152870] [d2 loss: 0.140963]  [sq d1 d2: 0.000142]  [num0: 19.000000] [num1 45.000000]
[Epoch 42/500] [Batch 380/676] [D loss: -0.025601] [G loss: -0.114076] [d1 loss: 0.070820] [d2 loss: 0.075673]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 42/500] [Batch 400/676] [D loss: -0.023581] [G loss: -0.149076] [d1 loss: 0.135557] [d2 loss: 0.142386]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 42/500] [Batch 420/676] [D loss: -0.028323] [G loss: -0.129420] [d1 loss: 0.174730] [d2 loss: 0.192989]  [sq d1 d2: 0.000333]  [num0: 18.000000] [num1 46.000000]
[Epoch 42/500] [Batch 440/676] [D loss: -0.039840] [G loss: -0.148967] [d1 loss: 0.110548] [d2 loss: 0.122319]  [sq d1 d2: 0.000139]  [num0: 15.000000] [num1 49.000000]
[Epoch 42/500] [Batch 460/676] [D loss: -0.031790] [G loss: -0.131858] [d1 loss: 0.123520] [d2 loss: 0.106036]  [sq d1 d2: 0.000306]  [num0: 14.000000] [num1 50.000000]
[Epoch 42/500] [Batch 480/676] [D loss: -0.029670] [G loss: -0.127280] [d1 loss: 0.116042] [d2 loss: 0.114261]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 42/500] [Batch 500/676] [D loss: -0.031474] [G loss: -0.133421] [d1 loss: 0.254779] [d2 loss: 0.230645]  [sq d1 d2: 0.000582]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 520/676] [D loss: -0.011463] [G loss: -0.129355] [d1 loss: 0.254403] [d2 loss: 0.287338]  [sq d1 d2: 0.001085]  [num0: 19.000000] [num1 45.000000]
[Epoch 42/500] [Batch 540/676] [D loss: -0.040998] [G loss: -0.145112] [d1 loss: 0.130669] [d2 loss: 0.104936]  [sq d1 d2: 0.000662]  [num0: 18.000000] [num1 46.000000]
[Epoch 42/500] [Batch 560/676] [D loss: -0.033749] [G loss: -0.131291] [d1 loss: 0.171701] [d2 loss: 0.151387]  [sq d1 d2: 0.000413]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 580/676] [D loss: -0.021934] [G loss: -0.136226] [d1 loss: 0.117846] [d2 loss: 0.113456]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 42/500] [Batch 600/676] [D loss: -0.018449] [G loss: -0.140879] [d1 loss: 0.210596] [d2 loss: 0.235315]  [sq d1 d2: 0.000611]  [num0: 18.000000] [num1 46.000000]
[Epoch 42/500] [Batch 620/676] [D loss: -0.017151] [G loss: -0.118830] [d1 loss: 0.178204] [d2 loss: 0.153021]  [sq d1 d2: 0.000634]  [num0: 17.000000] [num1 47.000000]
[Epoch 42/500] [Batch 640/676] [D loss: -0.022837] [G loss: -0.133981] [d1 loss: 0.223098] [d2 loss: 0.222703]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 42/500] [Batch 660/676] [D loss: -0.040534] [G loss: -0.137012] [d1 loss: 0.209793] [d2 loss: 0.217291]  [sq d1 d2: 0.000056]  [num0: 13.000000] [num1 51.000000]
[Epoch 43/500] [Batch 0/676] [D loss: -0.037544] [G loss: -0.135245] [d1 loss: 0.138535] [d2 loss: 0.168692]  [sq d1 d2: 0.000909]  [num0: 18.000000] [num1 46.000000]
[Epoch 43/500] [Batch 20/676] [D loss: -0.020551] [G loss: -0.139958] [d1 loss: 0.074052] [d2 loss: 0.073008]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 43/500] [Batch 40/676] [D loss: -0.039877] [G loss: -0.126989] [d1 loss: 0.102451] [d2 loss: 0.096029]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 60/676] [D loss: -0.032703] [G loss: -0.139543] [d1 loss: 0.116279] [d2 loss: 0.161342]  [sq d1 d2: 0.002031]  [num0: 20.000000] [num1 44.000000]
[Epoch 43/500] [Batch 80/676] [D loss: -0.032693] [G loss: -0.137006] [d1 loss: 0.140283] [d2 loss: 0.141227]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 100/676] [D loss: -0.017966] [G loss: -0.153395] [d1 loss: 0.102781] [d2 loss: 0.097182]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 120/676] [D loss: -0.045575] [G loss: -0.130788] [d1 loss: 0.136740] [d2 loss: 0.136429]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 140/676] [D loss: -0.017575] [G loss: -0.146478] [d1 loss: 0.133879] [d2 loss: 0.140218]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 43/500] [Batch 160/676] [D loss: -0.036636] [G loss: -0.147144] [d1 loss: 0.118367] [d2 loss: 0.109814]  [sq d1 d2: 0.000073]  [num0: 19.000000] [num1 45.000000]
[Epoch 43/500] [Batch 180/676] [D loss: -0.038070] [G loss: -0.137646] [d1 loss: 0.081071] [d2 loss: 0.078242]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 43/500] [Batch 200/676] [D loss: -0.038573] [G loss: -0.151402] [d1 loss: 0.188008] [d2 loss: 0.210510]  [sq d1 d2: 0.000506]  [num0: 21.000000] [num1 43.000000]
[Epoch 43/500] [Batch 220/676] [D loss: -0.035274] [G loss: -0.146363] [d1 loss: 0.115082] [d2 loss: 0.118296]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 43/500] [Batch 240/676] [D loss: -0.036380] [G loss: -0.139632] [d1 loss: 0.175223] [d2 loss: 0.169427]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 43/500] [Batch 260/676] [D loss: -0.037723] [G loss: -0.141254] [d1 loss: 0.075328] [d2 loss: 0.073871]  [sq d1 d2: 0.000002]  [num0: 22.000000] [num1 42.000000]
[Epoch 43/500] [Batch 280/676] [D loss: -0.041317] [G loss: -0.163914] [d1 loss: 0.112195] [d2 loss: 0.108630]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 300/676] [D loss: -0.034451] [G loss: -0.133493] [d1 loss: 0.266689] [d2 loss: 0.254386]  [sq d1 d2: 0.000151]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 320/676] [D loss: -0.026732] [G loss: -0.124046] [d1 loss: 0.074945] [d2 loss: 0.077392]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 340/676] [D loss: -0.017509] [G loss: -0.107379] [d1 loss: 0.171729] [d2 loss: 0.158478]  [sq d1 d2: 0.000176]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 360/676] [D loss: -0.036781] [G loss: -0.137883] [d1 loss: 0.131605] [d2 loss: 0.121539]  [sq d1 d2: 0.000101]  [num0: 15.000000] [num1 49.000000]

[Epoch 43/500] [Batch 380/676] [D loss: -0.016569] [G loss: -0.113235] [d1 loss: 0.186702] [d2 loss: 0.185489]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 43/500] [Batch 400/676] [D loss: -0.034058] [G loss: -0.125212] [d1 loss: 0.190171] [d2 loss: 0.203541]  [sq d1 d2: 0.000179]  [num0: 12.000000] [num1 52.000000]
[Epoch 43/500] [Batch 420/676] [D loss: -0.024801] [G loss: -0.132176] [d1 loss: 0.189142] [d2 loss: 0.197252]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 440/676] [D loss: -0.047741] [G loss: -0.126006] [d1 loss: 0.228319] [d2 loss: 0.210103]  [sq d1 d2: 0.000332]  [num0: 17.000000] [num1 47.000000]
[Epoch 43/500] [Batch 460/676] [D loss: -0.036321] [G loss: -0.127235] [d1 loss: 0.180271] [d2 loss: 0.176460]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 43/500] [Batch 480/676] [D loss: -0.026389] [G loss: -0.120512] [d1 loss: 0.250113] [d2 loss: 0.218031]  [sq d1 d2: 0.001029]  [num0: 13.000000] [num1 51.000000]
[Epoch 43/500] [Batch 500/676] [D loss: -0.017548] [G loss: -0.130564] [d1 loss: 0.154654] [d2 loss: 0.183573]  [sq d1 d2: 0.000836]  [num0: 17.000000] [num1 47.000000]
[Epoch 43/500] [Batch 520/676] [D loss: -0.033795] [G loss: -0.118079] [d1 loss: 0.107737] [d2 loss: 0.117294]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 540/676] [D loss: -0.042807] [G loss: -0.125664] [d1 loss: 0.133819] [d2 loss: 0.148909]  [sq d1 d2: 0.000228]  [num0: 13.000000] [num1 51.000000]
[Epoch 43/500] [Batch 560/676] [D loss: -0.042220] [G loss: -0.127152] [d1 loss: 0.139768] [d2 loss: 0.144573]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 580/676] [D loss: -0.037250] [G loss: -0.159228] [d1 loss: 0.207411] [d2 loss: 0.202254]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 600/676] [D loss: -0.043323] [G loss: -0.161233] [d1 loss: 0.138485] [d2 loss: 0.128488]  [sq d1 d2: 0.000100]  [num0: 13.000000] [num1 51.000000]
[Epoch 43/500] [Batch 620/676] [D loss: -0.029541] [G loss: -0.160679] [d1 loss: 0.178250] [d2 loss: 0.195996]  [sq d1 d2: 0.000315]  [num0: 15.000000] [num1 49.000000]
[Epoch 43/500] [Batch 640/676] [D loss: -0.029183] [G loss: -0.167183] [d1 loss: 0.137726] [d2 loss: 0.151241]  [sq d1 d2: 0.000183]  [num0: 16.000000] [num1 48.000000]
[Epoch 43/500] [Batch 660/676] [D loss: -0.054958] [G loss: -0.172324] [d1 loss: 0.102564] [d2 loss: 0.082773]  [sq d1 d2: 0.000392]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 0/676] [D loss: -0.009989] [G loss: -0.168253] [d1 loss: 0.115614] [d2 loss: 0.115569]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 44/500] [Batch 20/676] [D loss: -0.015317] [G loss: -0.158053] [d1 loss: 0.173198] [d2 loss: 0.190863]  [sq d1 d2: 0.000312]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 40/676] [D loss: -0.002868] [G loss: -0.154947] [d1 loss: 0.168966] [d2 loss: 0.157990]  [sq d1 d2: 0.000120]  [num0: 15.000000] [num1 49.000000]
[Epoch 44/500] [Batch 60/676] [D loss: -0.013955] [G loss: -0.140768] [d1 loss: 0.158503] [d2 loss: 0.169855]  [sq d1 d2: 0.000129]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 80/676] [D loss: -0.025903] [G loss: -0.135838] [d1 loss: 0.106699] [d2 loss: 0.115393]  [sq d1 d2: 0.000076]  [num0: 12.000000] [num1 52.000000]
[Epoch 44/500] [Batch 100/676] [D loss: -0.028990] [G loss: -0.127162] [d1 loss: 0.188479] [d2 loss: 0.215626]  [sq d1 d2: 0.000737]  [num0: 21.000000] [num1 43.000000]
[Epoch 44/500] [Batch 120/676] [D loss: -0.018716] [G loss: -0.132350] [d1 loss: 0.139242] [d2 loss: 0.133486]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 140/676] [D loss: -0.051601] [G loss: -0.126447] [d1 loss: 0.151110] [d2 loss: 0.136863]  [sq d1 d2: 0.000203]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 160/676] [D loss: -0.038024] [G loss: -0.152977] [d1 loss: 0.107401] [d2 loss: 0.116553]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 180/676] [D loss: -0.053625] [G loss: -0.163204] [d1 loss: 0.296676] [d2 loss: 0.285480]  [sq d1 d2: 0.000125]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 200/676] [D loss: -0.026032] [G loss: -0.177171] [d1 loss: 0.102875] [d2 loss: 0.093660]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 220/676] [D loss: -0.021836] [G loss: -0.156051] [d1 loss: 0.178861] [d2 loss: 0.180523]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 44/500] [Batch 240/676] [D loss: -0.004119] [G loss: -0.150137] [d1 loss: 0.196504] [d2 loss: 0.211258]  [sq d1 d2: 0.000218]  [num0: 17.000000] [num1 47.000000]
[Epoch 44/500] [Batch 260/676] [D loss: -0.005824] [G loss: -0.140305] [d1 loss: 0.093333] [d2 loss: 0.101439]  [sq d1 d2: 0.000066]  [num0: 12.000000] [num1 52.000000]
[Epoch 44/500] [Batch 280/676] [D loss: -0.031679] [G loss: -0.126912] [d1 loss: 0.133695] [d2 loss: 0.129469]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 44/500] [Batch 300/676] [D loss: -0.018822] [G loss: -0.130908] [d1 loss: 0.168298] [d2 loss: 0.162966]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 44/500] [Batch 320/676] [D loss: -0.020187] [G loss: -0.118116] [d1 loss: 0.103395] [d2 loss: 0.109409]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 340/676] [D loss: -0.026070] [G loss: -0.113797] [d1 loss: 0.244888] [d2 loss: 0.238775]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 360/676] [D loss: -0.026816] [G loss: -0.127953] [d1 loss: 0.188313] [d2 loss: 0.202301]  [sq d1 d2: 0.000196]  [num0: 20.000000] [num1 44.000000]
[Epoch 44/500] [Batch 380/676] [D loss: -0.028455] [G loss: -0.139677] [d1 loss: 0.137830] [d2 loss: 0.142352]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 44/500] [Batch 400/676] [D loss: -0.029381] [G loss: -0.121109] [d1 loss: 0.164675] [d2 loss: 0.186030]  [sq d1 d2: 0.000456]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 420/676] [D loss: -0.041462] [G loss: -0.119572] [d1 loss: 0.064428] [d2 loss: 0.070720]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 44/500] [Batch 440/676] [D loss: -0.040923] [G loss: -0.136544] [d1 loss: 0.214239] [d2 loss: 0.252042]  [sq d1 d2: 0.001429]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 460/676] [D loss: -0.067410] [G loss: -0.172191] [d1 loss: 0.136169] [d2 loss: 0.112121]  [sq d1 d2: 0.000578]  [num0: 11.000000] [num1 53.000000]
[Epoch 44/500] [Batch 480/676] [D loss: -0.047348] [G loss: -0.157095] [d1 loss: 0.158030] [d2 loss: 0.168673]  [sq d1 d2: 0.000113]  [num0: 11.000000] [num1 53.000000]
[Epoch 44/500] [Batch 500/676] [D loss: -0.004017] [G loss: -0.182156] [d1 loss: 0.127595] [d2 loss: 0.123252]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 44/500] [Batch 520/676] [D loss: -0.038100] [G loss: -0.199569] [d1 loss: 0.084624] [d2 loss: 0.081820]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 44/500] [Batch 540/676] [D loss: -0.025993] [G loss: -0.164334] [d1 loss: 0.111891] [d2 loss: 0.105375]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 44/500] [Batch 560/676] [D loss: -0.028355] [G loss: -0.109630] [d1 loss: 0.138938] [d2 loss: 0.143783]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 44/500] [Batch 580/676] [D loss: 0.002280] [G loss: -0.097003] [d1 loss: 0.134606] [d2 loss: 0.134320]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 44/500] [Batch 600/676] [D loss: -0.025128] [G loss: -0.090462] [d1 loss: 0.099444] [d2 loss: 0.101854]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 44/500] [Batch 620/676] [D loss: -0.029497] [G loss: -0.103310] [d1 loss: 0.141878] [d2 loss: 0.145658]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 44/500] [Batch 640/676] [D loss: -0.021632] [G loss: -0.073384] [d1 loss: 0.147219] [d2 loss: 0.136599]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 44/500] [Batch 660/676] [D loss: -0.040171] [G loss: -0.081977] [d1 loss: 0.195993] [d2 loss: 0.194475]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 45/500] [Batch 0/676] [D loss: -0.032602] [G loss: -0.092155] [d1 loss: 0.194365] [d2 loss: 0.173131]  [sq d1 d2: 0.000451]  [num0: 18.000000] [num1 46.000000]

[Epoch 45/500] [Batch 20/676] [D loss: -0.027830] [G loss: -0.113213] [d1 loss: 0.313738] [d2 loss: 0.290439]  [sq d1 d2: 0.000543]  [num0: 16.000000] [num1 48.000000]
[Epoch 45/500] [Batch 40/676] [D loss: -0.026118] [G loss: -0.125128] [d1 loss: 0.095242] [d2 loss: 0.102590]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 45/500] [Batch 60/676] [D loss: -0.016051] [G loss: -0.147586] [d1 loss: 0.180990] [d2 loss: 0.157282]  [sq d1 d2: 0.000562]  [num0: 13.000000] [num1 51.000000]
[Epoch 45/500] [Batch 80/676] [D loss: -0.036495] [G loss: -0.167817] [d1 loss: 0.118738] [d2 loss: 0.128162]  [sq d1 d2: 0.000089]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 100/676] [D loss: -0.017291] [G loss: -0.183293] [d1 loss: 0.169000] [d2 loss: 0.175071]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 120/676] [D loss: -0.029149] [G loss: -0.161095] [d1 loss: 0.148329] [d2 loss: 0.165346]  [sq d1 d2: 0.000290]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 140/676] [D loss: -0.040202] [G loss: -0.159679] [d1 loss: 0.067488] [d2 loss: 0.054901]  [sq d1 d2: 0.000158]  [num0: 13.000000] [num1 51.000000]
[Epoch 45/500] [Batch 160/676] [D loss: -0.035970] [G loss: -0.191336] [d1 loss: 0.133719] [d2 loss: 0.129470]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 45/500] [Batch 180/676] [D loss: -0.032170] [G loss: -0.176120] [d1 loss: 0.087993] [d2 loss: 0.080988]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 45/500] [Batch 200/676] [D loss: -0.018179] [G loss: -0.169801] [d1 loss: 0.090346] [d2 loss: 0.094731]  [sq d1 d2: 0.000019]  [num0: 13.000000] [num1 51.000000]
[Epoch 45/500] [Batch 220/676] [D loss: -0.029944] [G loss: -0.159567] [d1 loss: 0.240097] [d2 loss: 0.209009]  [sq d1 d2: 0.000967]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 240/676] [D loss: -0.026011] [G loss: -0.165756] [d1 loss: 0.113013] [d2 loss: 0.115123]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 45/500] [Batch 260/676] [D loss: -0.024910] [G loss: -0.159372] [d1 loss: 0.067203] [d2 loss: 0.066481]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 45/500] [Batch 280/676] [D loss: -0.018492] [G loss: -0.169573] [d1 loss: 0.172905] [d2 loss: 0.168898]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 45/500] [Batch 300/676] [D loss: -0.051880] [G loss: -0.162036] [d1 loss: 0.145052] [d2 loss: 0.127950]  [sq d1 d2: 0.000292]  [num0: 16.000000] [num1 48.000000]
[Epoch 45/500] [Batch 320/676] [D loss: -0.021188] [G loss: -0.142878] [d1 loss: 0.199750] [d2 loss: 0.199858]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 340/676] [D loss: -0.030896] [G loss: -0.123752] [d1 loss: 0.155127] [d2 loss: 0.160899]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 360/676] [D loss: -0.031770] [G loss: -0.099959] [d1 loss: 0.137409] [d2 loss: 0.144347]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 45/500] [Batch 380/676] [D loss: -0.037662] [G loss: -0.112866] [d1 loss: 0.192170] [d2 loss: 0.163437]  [sq d1 d2: 0.000826]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 400/676] [D loss: -0.040596] [G loss: -0.109345] [d1 loss: 0.243931] [d2 loss: 0.249273]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 45/500] [Batch 420/676] [D loss: -0.029437] [G loss: -0.091433] [d1 loss: 0.141072] [d2 loss: 0.146747]  [sq d1 d2: 0.000032]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 440/676] [D loss: -0.021115] [G loss: -0.110876] [d1 loss: 0.139857] [d2 loss: 0.143579]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]
[Epoch 45/500] [Batch 460/676] [D loss: -0.042639] [G loss: -0.105714] [d1 loss: 0.193397] [d2 loss: 0.194584]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 480/676] [D loss: -0.020782] [G loss: -0.127659] [d1 loss: 0.173138] [d2 loss: 0.166542]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 45/500] [Batch 500/676] [D loss: -0.038346] [G loss: -0.123203] [d1 loss: 0.130605] [d2 loss: 0.141464]  [sq d1 d2: 0.000118]  [num0: 12.000000] [num1 52.000000]
[Epoch 45/500] [Batch 520/676] [D loss: -0.037355] [G loss: -0.122504] [d1 loss: 0.092830] [d2 loss: 0.084878]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 540/676] [D loss: -0.025547] [G loss: -0.130483] [d1 loss: 0.159112] [d2 loss: 0.158995]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 45/500] [Batch 560/676] [D loss: -0.009118] [G loss: -0.121389] [d1 loss: 0.169960] [d2 loss: 0.183182]  [sq d1 d2: 0.000175]  [num0: 18.000000] [num1 46.000000]
[Epoch 45/500] [Batch 580/676] [D loss: -0.022510] [G loss: -0.104575] [d1 loss: 0.088345] [d2 loss: 0.089233]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 45/500] [Batch 600/676] [D loss: -0.029831] [G loss: -0.108061] [d1 loss: 0.121828] [d2 loss: 0.119745]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 620/676] [D loss: -0.015367] [G loss: -0.128924] [d1 loss: 0.176432] [d2 loss: 0.139889]  [sq d1 d2: 0.001335]  [num0: 13.000000] [num1 51.000000]
[Epoch 45/500] [Batch 640/676] [D loss: -0.028381] [G loss: -0.140627] [d1 loss: 0.138349] [d2 loss: 0.133102]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 45/500] [Batch 660/676] [D loss: -0.036907] [G loss: -0.127481] [d1 loss: 0.168154] [d2 loss: 0.146197]  [sq d1 d2: 0.000482]  [num0: 18.000000] [num1 46.000000]
[Epoch 46/500] [Batch 0/676] [D loss: -0.045319] [G loss: -0.128353] [d1 loss: 0.183859] [d2 loss: 0.159097]  [sq d1 d2: 0.000613]  [num0: 12.000000] [num1 52.000000]
[Epoch 46/500] [Batch 20/676] [D loss: -0.038436] [G loss: -0.140395] [d1 loss: 0.088163] [d2 loss: 0.076968]  [sq d1 d2: 0.000125]  [num0: 17.000000] [num1 47.000000]
[Epoch 46/500] [Batch 40/676] [D loss: -0.041368] [G loss: -0.155470] [d1 loss: 0.143787] [d2 loss: 0.129842]  [sq d1 d2: 0.000194]  [num0: 20.000000] [num1 44.000000]
[Epoch 46/500] [Batch 60/676] [D loss: -0.042429] [G loss: -0.157938] [d1 loss: 0.130172] [d2 loss: 0.110921]  [sq d1 d2: 0.000371]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 80/676] [D loss: -0.046046] [G loss: -0.144334] [d1 loss: 0.095267] [d2 loss: 0.102028]  [sq d1 d2: 0.000046]  [num0: 19.000000] [num1 45.000000]
[Epoch 46/500] [Batch 100/676] [D loss: -0.047879] [G loss: -0.141350] [d1 loss: 0.110545] [d2 loss: 0.105640]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 46/500] [Batch 120/676] [D loss: -0.038298] [G loss: -0.143128] [d1 loss: 0.236502] [d2 loss: 0.233655]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 140/676] [D loss: -0.034872] [G loss: -0.129560] [d1 loss: 0.085360] [d2 loss: 0.114776]  [sq d1 d2: 0.000865]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 160/676] [D loss: -0.008664] [G loss: -0.113565] [d1 loss: 0.095549] [d2 loss: 0.106453]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 46/500] [Batch 180/676] [D loss: -0.009382] [G loss: -0.096117] [d1 loss: 0.193993] [d2 loss: 0.180695]  [sq d1 d2: 0.000177]  [num0: 14.000000] [num1 50.000000]
[Epoch 46/500] [Batch 200/676] [D loss: -0.013461] [G loss: -0.099125] [d1 loss: 0.081861] [d2 loss: 0.074122]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 220/676] [D loss: -0.021538] [G loss: -0.099200] [d1 loss: 0.091200] [d2 loss: 0.090874]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 46/500] [Batch 240/676] [D loss: -0.026842] [G loss: -0.095164] [d1 loss: 0.128245] [d2 loss: 0.110537]  [sq d1 d2: 0.000314]  [num0: 18.000000] [num1 46.000000]
[Epoch 46/500] [Batch 260/676] [D loss: -0.018092] [G loss: -0.090902] [d1 loss: 0.153989] [d2 loss: 0.163018]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 46/500] [Batch 280/676] [D loss: -0.027108] [G loss: -0.094186] [d1 loss: 0.158734] [d2 loss: 0.156405]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 46/500] [Batch 300/676] [D loss: -0.042788] [G loss: -0.106975] [d1 loss: 0.171747] [d2 loss: 0.190576]  [sq d1 d2: 0.000355]  [num0: 20.000000] [num1 44.000000]

[Epoch 46/500] [Batch 320/676] [D loss: -0.026922] [G loss: -0.112272] [d1 loss: 0.140257] [d2 loss: 0.132228]  [sq d1 d2: 0.000064]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 340/676] [D loss: -0.046117] [G loss: -0.109886] [d1 loss: 0.093361] [d2 loss: 0.092661]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 46/500] [Batch 360/676] [D loss: -0.023760] [G loss: -0.122041] [d1 loss: 0.050282] [d2 loss: 0.063999]  [sq d1 d2: 0.000188]  [num0: 16.000000] [num1 48.000000]
[Epoch 46/500] [Batch 380/676] [D loss: -0.026574] [G loss: -0.163205] [d1 loss: 0.100649] [d2 loss: 0.115577]  [sq d1 d2: 0.000223]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 400/676] [D loss: -0.026600] [G loss: -0.159181] [d1 loss: 0.105357] [d2 loss: 0.111075]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 46/500] [Batch 420/676] [D loss: -0.033149] [G loss: -0.156260] [d1 loss: 0.064734] [d2 loss: 0.070839]  [sq d1 d2: 0.000037]  [num0: 9.000000] [num1 55.000000]
[Epoch 46/500] [Batch 440/676] [D loss: -0.009743] [G loss: -0.131730] [d1 loss: 0.075594] [d2 loss: 0.094913]  [sq d1 d2: 0.000373]  [num0: 14.000000] [num1 50.000000]
[Epoch 46/500] [Batch 460/676] [D loss: -0.028661] [G loss: -0.129296] [d1 loss: 0.151637] [d2 loss: 0.136600]  [sq d1 d2: 0.000226]  [num0: 19.000000] [num1 45.000000]
[Epoch 46/500] [Batch 480/676] [D loss: -0.009871] [G loss: -0.098275] [d1 loss: 0.121546] [d2 loss: 0.091494]  [sq d1 d2: 0.000903]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 500/676] [D loss: -0.023710] [G loss: -0.139063] [d1 loss: 0.298152] [d2 loss: 0.294051]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 46/500] [Batch 520/676] [D loss: -0.034127] [G loss: -0.136615] [d1 loss: 0.112551] [d2 loss: 0.120861]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 46/500] [Batch 540/676] [D loss: -0.041222] [G loss: -0.126598] [d1 loss: 0.247151] [d2 loss: 0.246192]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 46/500] [Batch 560/676] [D loss: -0.038485] [G loss: -0.130349] [d1 loss: 0.169423] [d2 loss: 0.182008]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 46/500] [Batch 580/676] [D loss: -0.031920] [G loss: -0.140967] [d1 loss: 0.141807] [d2 loss: 0.123666]  [sq d1 d2: 0.000329]  [num0: 18.000000] [num1 46.000000]
[Epoch 46/500] [Batch 600/676] [D loss: -0.058740] [G loss: -0.146128] [d1 loss: 0.206274] [d2 loss: 0.197435]  [sq d1 d2: 0.000078]  [num0: 15.000000] [num1 49.000000]
[Epoch 46/500] [Batch 620/676] [D loss: -0.056801] [G loss: -0.164623] [d1 loss: 0.159482] [d2 loss: 0.160603]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 46/500] [Batch 640/676] [D loss: -0.042424] [G loss: -0.156765] [d1 loss: 0.194223] [d2 loss: 0.224042]  [sq d1 d2: 0.000889]  [num0: 20.000000] [num1 44.000000]
[Epoch 46/500] [Batch 660/676] [D loss: -0.048426] [G loss: -0.155445] [d1 loss: 0.082373] [d2 loss: 0.077778]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 47/500] [Batch 0/676] [D loss: 0.000490] [G loss: -0.147200] [d1 loss: 0.057164] [d2 loss: 0.079562]  [sq d1 d2: 0.000502]  [num0: 17.000000] [num1 47.000000]
[Epoch 47/500] [Batch 20/676] [D loss: -0.018217] [G loss: -0.137682] [d1 loss: 0.128586] [d2 loss: 0.131486]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 47/500] [Batch 40/676] [D loss: -0.017187] [G loss: -0.155396] [d1 loss: 0.177160] [d2 loss: 0.175956]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 47/500] [Batch 60/676] [D loss: -0.027613] [G loss: -0.155319] [d1 loss: 0.108204] [d2 loss: 0.100658]  [sq d1 d2: 0.000057]  [num0: 12.000000] [num1 52.000000]
[Epoch 47/500] [Batch 80/676] [D loss: -0.035511] [G loss: -0.140385] [d1 loss: 0.184273] [d2 loss: 0.188205]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 47/500] [Batch 100/676] [D loss: -0.017005] [G loss: -0.171322] [d1 loss: 0.166389] [d2 loss: 0.170541]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 47/500] [Batch 120/676] [D loss: -0.022731] [G loss: -0.154712] [d1 loss: 0.106374] [d2 loss: 0.137015]  [sq d1 d2: 0.000939]  [num0: 14.000000] [num1 50.000000]
[Epoch 47/500] [Batch 140/676] [D loss: -0.045559] [G loss: -0.145494] [d1 loss: 0.070400] [d2 loss: 0.079588]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 47/500] [Batch 160/676] [D loss: -0.034732] [G loss: -0.144617] [d1 loss: 0.127523] [d2 loss: 0.125719]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 47/500] [Batch 180/676] [D loss: -0.054658] [G loss: -0.152882] [d1 loss: 0.091266] [d2 loss: 0.089718]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 47/500] [Batch 200/676] [D loss: -0.017087] [G loss: -0.145644] [d1 loss: 0.106758] [d2 loss: 0.115274]  [sq d1 d2: 0.000073]  [num0: 11.000000] [num1 53.000000]
[Epoch 47/500] [Batch 220/676] [D loss: -0.025341] [G loss: -0.130939] [d1 loss: 0.193486] [d2 loss: 0.178290]  [sq d1 d2: 0.000231]  [num0: 18.000000] [num1 46.000000]
[Epoch 47/500] [Batch 240/676] [D loss: -0.047303] [G loss: -0.118344] [d1 loss: 0.130885] [d2 loss: 0.139378]  [sq d1 d2: 0.000072]  [num0: 18.000000] [num1 46.000000]
[Epoch 47/500] [Batch 260/676] [D loss: -0.048472] [G loss: -0.140118] [d1 loss: 0.150935] [d2 loss: 0.157915]  [sq d1 d2: 0.000049]  [num0: 19.000000] [num1 45.000000]
[Epoch 47/500] [Batch 280/676] [D loss: -0.048357] [G loss: -0.149418] [d1 loss: 0.187510] [d2 loss: 0.170067]  [sq d1 d2: 0.000304]  [num0: 16.000000] [num1 48.000000]
[Epoch 47/500] [Batch 300/676] [D loss: -0.052513] [G loss: -0.170282] [d1 loss: 0.214693] [d2 loss: 0.227646]  [sq d1 d2: 0.000168]  [num0: 16.000000] [num1 48.000000]
[Epoch 47/500] [Batch 320/676] [D loss: -0.045996] [G loss: -0.184727] [d1 loss: 0.109405] [d2 loss: 0.107005]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 47/500] [Batch 340/676] [D loss: -0.036778] [G loss: -0.185917] [d1 loss: 0.242305] [d2 loss: 0.247168]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 47/500] [Batch 360/676] [D loss: -0.022421] [G loss: -0.188103] [d1 loss: 0.135589] [d2 loss: 0.140712]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 47/500] [Batch 380/676] [D loss: -0.042331] [G loss: -0.190843] [d1 loss: 0.146412] [d2 loss: 0.127678]  [sq d1 d2: 0.000351]  [num0: 17.000000] [num1 47.000000]
[Epoch 47/500] [Batch 400/676] [D loss: -0.031361] [G loss: -0.208271] [d1 loss: 0.045290] [d2 loss: 0.052506]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 47/500] [Batch 420/676] [D loss: -0.029171] [G loss: -0.181566] [d1 loss: 0.186823] [d2 loss: 0.191740]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 47/500] [Batch 440/676] [D loss: -0.037605] [G loss: -0.172815] [d1 loss: 0.108734] [d2 loss: 0.129935]  [sq d1 d2: 0.000449]  [num0: 13.000000] [num1 51.000000]
[Epoch 47/500] [Batch 460/676] [D loss: -0.017652] [G loss: -0.161339] [d1 loss: 0.120507] [d2 loss: 0.127830]  [sq d1 d2: 0.000054]  [num0: 12.000000] [num1 52.000000]
[Epoch 47/500] [Batch 480/676] [D loss: -0.015070] [G loss: -0.157654] [d1 loss: 0.141876] [d2 loss: 0.159741]  [sq d1 d2: 0.000319]  [num0: 11.000000] [num1 53.000000]
[Epoch 47/500] [Batch 500/676] [D loss: -0.068054] [G loss: -0.142946] [d1 loss: 0.117650] [d2 loss: 0.109260]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 47/500] [Batch 520/676] [D loss: -0.035840] [G loss: -0.155115] [d1 loss: 0.059491] [d2 loss: 0.054021]  [sq d1 d2: 0.000030]  [num0: 12.000000] [num1 52.000000]
[Epoch 47/500] [Batch 540/676] [D loss: -0.014236] [G loss: -0.166215] [d1 loss: 0.056685] [d2 loss: 0.057222]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 47/500] [Batch 560/676] [D loss: -0.045810] [G loss: -0.139123] [d1 loss: 0.231186] [d2 loss: 0.204826]  [sq d1 d2: 0.000695]  [num0: 18.000000] [num1 46.000000]
[Epoch 47/500] [Batch 580/676] [D loss: -0.028440] [G loss: -0.148503] [d1 loss: 0.166274] [d2 loss: 0.161364]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 47/500] [Batch 600/676] [D loss: -0.036626] [G loss: -0.170181] [d1 loss: 0.188826] [d2 loss: 0.194544]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 47/500] [Batch 620/676] [D loss: -0.059624] [G loss: -0.165027] [d1 loss: 0.104289] [d2 loss: 0.097560]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 47/500] [Batch 640/676] [D loss: -0.043282] [G loss: -0.145131] [d1 loss: 0.173574] [d2 loss: 0.166869]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 47/500] [Batch 660/676] [D loss: -0.023346] [G loss: -0.146265] [d1 loss: 0.283577] [d2 loss: 0.272470]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]

[Epoch 48/500] [Batch 0/676] [D loss: -0.038959] [G loss: -0.172244] [d1 loss: 0.160840] [d2 loss: 0.117986]  [sq d1 d2: 0.001836]  [num0: 15.000000] [num1 49.000000]
[Epoch 48/500] [Batch 20/676] [D loss: -0.046587] [G loss: -0.137128] [d1 loss: 0.153135] [d2 loss: 0.148476]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 48/500] [Batch 40/676] [D loss: 0.008493] [G loss: -0.119268] [d1 loss: 0.127860] [d2 loss: 0.129673]  [sq d1 d2: 0.000003]  [num0: 20.000000] [num1 44.000000]
[Epoch 48/500] [Batch 60/676] [D loss: -0.039104] [G loss: -0.129800] [d1 loss: 0.138180] [d2 loss: 0.140193]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 80/676] [D loss: -0.010438] [G loss: -0.130995] [d1 loss: 0.120400] [d2 loss: 0.110880]  [sq d1 d2: 0.000091]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 100/676] [D loss: -0.035093] [G loss: -0.120363] [d1 loss: 0.107479] [d2 loss: 0.087424]  [sq d1 d2: 0.000402]  [num0: 12.000000] [num1 52.000000]
[Epoch 48/500] [Batch 120/676] [D loss: -0.039064] [G loss: -0.115078] [d1 loss: 0.216282] [d2 loss: 0.210248]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 48/500] [Batch 140/676] [D loss: -0.014484] [G loss: -0.142978] [d1 loss: 0.112576] [d2 loss: 0.114015]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 48/500] [Batch 160/676] [D loss: -0.039954] [G loss: -0.140124] [d1 loss: 0.107431] [d2 loss: 0.110534]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 180/676] [D loss: -0.022313] [G loss: -0.167607] [d1 loss: 0.069916] [d2 loss: 0.090818]  [sq d1 d2: 0.000437]  [num0: 13.000000] [num1 51.000000]
[Epoch 48/500] [Batch 200/676] [D loss: -0.044772] [G loss: -0.161507] [d1 loss: 0.147114] [d2 loss: 0.152907]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 220/676] [D loss: -0.035940] [G loss: -0.186212] [d1 loss: 0.111499] [d2 loss: 0.099617]  [sq d1 d2: 0.000141]  [num0: 17.000000] [num1 47.000000]
[Epoch 48/500] [Batch 240/676] [D loss: -0.056227] [G loss: -0.216676] [d1 loss: 0.100895] [d2 loss: 0.084790]  [sq d1 d2: 0.000259]  [num0: 18.000000] [num1 46.000000]
[Epoch 48/500] [Batch 260/676] [D loss: -0.055758] [G loss: -0.212694] [d1 loss: 0.145530] [d2 loss: 0.161188]  [sq d1 d2: 0.000245]  [num0: 15.000000] [num1 49.000000]
[Epoch 48/500] [Batch 280/676] [D loss: -0.015342] [G loss: -0.263259] [d1 loss: 0.198307] [d2 loss: 0.216018]  [sq d1 d2: 0.000314]  [num0: 13.000000] [num1 51.000000]
[Epoch 48/500] [Batch 300/676] [D loss: 0.001335] [G loss: -0.289695] [d1 loss: 0.132055] [d2 loss: 0.145684]  [sq d1 d2: 0.000186]  [num0: 15.000000] [num1 49.000000]
[Epoch 48/500] [Batch 320/676] [D loss: -0.007809] [G loss: -0.309616] [d1 loss: 0.182221] [d2 loss: 0.177604]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 340/676] [D loss: -0.047067] [G loss: -0.287247] [d1 loss: 0.230230] [d2 loss: 0.234217]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 48/500] [Batch 360/676] [D loss: -0.000726] [G loss: -0.261074] [d1 loss: 0.151214] [d2 loss: 0.171003]  [sq d1 d2: 0.000392]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 380/676] [D loss: 0.001230] [G loss: -0.192709] [d1 loss: 0.198558] [d2 loss: 0.205822]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 48/500] [Batch 400/676] [D loss: -0.019267] [G loss: -0.151676] [d1 loss: 0.059713] [d2 loss: 0.056363]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 48/500] [Batch 420/676] [D loss: -0.028418] [G loss: -0.138562] [d1 loss: 0.136403] [d2 loss: 0.123832]  [sq d1 d2: 0.000158]  [num0: 19.000000] [num1 45.000000]
[Epoch 48/500] [Batch 440/676] [D loss: -0.033846] [G loss: -0.158387] [d1 loss: 0.159905] [d2 loss: 0.161757]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 48/500] [Batch 460/676] [D loss: -0.049463] [G loss: -0.152983] [d1 loss: 0.237865] [d2 loss: 0.227937]  [sq d1 d2: 0.000099]  [num0: 17.000000] [num1 47.000000]
[Epoch 48/500] [Batch 480/676] [D loss: -0.060852] [G loss: -0.161755] [d1 loss: 0.120526] [d2 loss: 0.126860]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 48/500] [Batch 500/676] [D loss: -0.023721] [G loss: -0.164613] [d1 loss: 0.161208] [d2 loss: 0.159375]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 48/500] [Batch 520/676] [D loss: -0.040168] [G loss: -0.184279] [d1 loss: 0.189538] [d2 loss: 0.201546]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 48/500] [Batch 540/676] [D loss: -0.044005] [G loss: -0.176474] [d1 loss: 0.167804] [d2 loss: 0.164558]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 48/500] [Batch 560/676] [D loss: -0.024189] [G loss: -0.175860] [d1 loss: 0.117986] [d2 loss: 0.132711]  [sq d1 d2: 0.000217]  [num0: 17.000000] [num1 47.000000]
[Epoch 48/500] [Batch 580/676] [D loss: -0.022239] [G loss: -0.161895] [d1 loss: 0.203792] [d2 loss: 0.213129]  [sq d1 d2: 0.000087]  [num0: 12.000000] [num1 52.000000]
[Epoch 48/500] [Batch 600/676] [D loss: -0.009870] [G loss: -0.132257] [d1 loss: 0.169889] [d2 loss: 0.184155]  [sq d1 d2: 0.000204]  [num0: 12.000000] [num1 52.000000]
[Epoch 48/500] [Batch 620/676] [D loss: -0.025892] [G loss: -0.093598] [d1 loss: 0.124530] [d2 loss: 0.114299]  [sq d1 d2: 0.000105]  [num0: 13.000000] [num1 51.000000]
[Epoch 48/500] [Batch 640/676] [D loss: -0.020103] [G loss: -0.114071] [d1 loss: 0.087155] [d2 loss: 0.078210]  [sq d1 d2: 0.000080]  [num0: 14.000000] [num1 50.000000]
[Epoch 48/500] [Batch 660/676] [D loss: -0.027783] [G loss: -0.142842] [d1 loss: 0.088824] [d2 loss: 0.091385]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 49/500] [Batch 0/676] [D loss: -0.056764] [G loss: -0.158298] [d1 loss: 0.129969] [d2 loss: 0.132744]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 49/500] [Batch 20/676] [D loss: -0.034755] [G loss: -0.219179] [d1 loss: 0.079114] [d2 loss: 0.089770]  [sq d1 d2: 0.000114]  [num0: 11.000000] [num1 53.000000]
[Epoch 49/500] [Batch 40/676] [D loss: -0.052294] [G loss: -0.293354] [d1 loss: 0.160547] [d2 loss: 0.166262]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 49/500] [Batch 60/676] [D loss: -0.050710] [G loss: -0.375921] [d1 loss: 0.134984] [d2 loss: 0.131611]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 49/500] [Batch 80/676] [D loss: -0.053220] [G loss: -0.475154] [d1 loss: 0.177413] [d2 loss: 0.206675]  [sq d1 d2: 0.000856]  [num0: 18.000000] [num1 46.000000]
[Epoch 49/500] [Batch 100/676] [D loss: -0.048871] [G loss: -0.542513] [d1 loss: 0.177742] [d2 loss: 0.172513]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 49/500] [Batch 120/676] [D loss: -0.020758] [G loss: -0.537488] [d1 loss: 0.088126] [d2 loss: 0.095372]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 49/500] [Batch 140/676] [D loss: 0.005216] [G loss: -0.458909] [d1 loss: 0.077528] [d2 loss: 0.085870]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 160/676] [D loss: 0.003118] [G loss: -0.348018] [d1 loss: 0.078990] [d2 loss: 0.080465]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 49/500] [Batch 180/676] [D loss: -0.018521] [G loss: -0.282930] [d1 loss: 0.154716] [d2 loss: 0.150417]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 49/500] [Batch 200/676] [D loss: -0.019543] [G loss: -0.224131] [d1 loss: 0.178683] [d2 loss: 0.166886]  [sq d1 d2: 0.000139]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 220/676] [D loss: -0.060044] [G loss: -0.198304] [d1 loss: 0.089523] [d2 loss: 0.108933]  [sq d1 d2: 0.000377]  [num0: 17.000000] [num1 47.000000]
[Epoch 49/500] [Batch 240/676] [D loss: -0.080040] [G loss: -0.157835] [d1 loss: 0.180246] [d2 loss: 0.170151]  [sq d1 d2: 0.000102]  [num0: 19.000000] [num1 45.000000]
[Epoch 49/500] [Batch 260/676] [D loss: -0.099820] [G loss: -0.116902] [d1 loss: 0.120313] [d2 loss: 0.133581]  [sq d1 d2: 0.000176]  [num0: 15.000000] [num1 49.000000]
[Epoch 49/500] [Batch 280/676] [D loss: -0.099531] [G loss: -0.102344] [d1 loss: 0.130997] [d2 loss: 0.128426]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]

[Epoch 49/500] [Batch 300/676] [D loss: -0.056986] [G loss: -0.058095] [d1 loss: 0.152154] [d2 loss: 0.157205]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 49/500] [Batch 320/676] [D loss: -0.003468] [G loss: 0.045518] [d1 loss: 0.110457] [d2 loss: 0.107565]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 340/676] [D loss: 0.008319] [G loss: 0.058831] [d1 loss: 0.216191] [d2 loss: 0.245678]  [sq d1 d2: 0.000869]  [num0: 18.000000] [num1 46.000000]
[Epoch 49/500] [Batch 360/676] [D loss: 0.002845] [G loss: 0.101083] [d1 loss: 0.138580] [d2 loss: 0.136922]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 49/500] [Batch 380/676] [D loss: -0.007262] [G loss: 0.127420] [d1 loss: 0.146923] [d2 loss: 0.156641]  [sq d1 d2: 0.000094]  [num0: 21.000000] [num1 43.000000]
[Epoch 49/500] [Batch 400/676] [D loss: -0.025307] [G loss: 0.133293] [d1 loss: 0.144327] [d2 loss: 0.164218]  [sq d1 d2: 0.000396]  [num0: 14.000000] [num1 50.000000]
[Epoch 49/500] [Batch 420/676] [D loss: -0.004400] [G loss: 0.147101] [d1 loss: 0.068742] [d2 loss: 0.058689]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 49/500] [Batch 440/676] [D loss: -0.045019] [G loss: 0.119124] [d1 loss: 0.131957] [d2 loss: 0.142967]  [sq d1 d2: 0.000121]  [num0: 19.000000] [num1 45.000000]
[Epoch 49/500] [Batch 460/676] [D loss: -0.065499] [G loss: 0.118298] [d1 loss: 0.135239] [d2 loss: 0.136062]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 480/676] [D loss: -0.056047] [G loss: 0.088712] [d1 loss: 0.056517] [d2 loss: 0.068607]  [sq d1 d2: 0.000146]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 500/676] [D loss: -0.049254] [G loss: 0.054848] [d1 loss: 0.172624] [d2 loss: 0.154920]  [sq d1 d2: 0.000313]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 520/676] [D loss: -0.063559] [G loss: 0.008297] [d1 loss: 0.161408] [d2 loss: 0.173042]  [sq d1 d2: 0.000135]  [num0: 13.000000] [num1 51.000000]
[Epoch 49/500] [Batch 540/676] [D loss: -0.038834] [G loss: -0.078466] [d1 loss: 0.158990] [d2 loss: 0.137571]  [sq d1 d2: 0.000459]  [num0: 19.000000] [num1 45.000000]
[Epoch 49/500] [Batch 560/676] [D loss: 0.011122] [G loss: -0.163205] [d1 loss: 0.123254] [d2 loss: 0.137410]  [sq d1 d2: 0.000200]  [num0: 20.000000] [num1 44.000000]
[Epoch 49/500] [Batch 580/676] [D loss: -0.021434] [G loss: -0.183412] [d1 loss: 0.075853] [d2 loss: 0.088204]  [sq d1 d2: 0.000153]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 600/676] [D loss: -0.026287] [G loss: -0.151911] [d1 loss: 0.062833] [d2 loss: 0.069061]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 49/500] [Batch 620/676] [D loss: -0.025557] [G loss: -0.179924] [d1 loss: 0.184664] [d2 loss: 0.178312]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 49/500] [Batch 640/676] [D loss: -0.064477] [G loss: -0.208830] [d1 loss: 0.103978] [d2 loss: 0.103546]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 49/500] [Batch 660/676] [D loss: -0.046581] [G loss: -0.243985] [d1 loss: 0.218471] [d2 loss: 0.203105]  [sq d1 d2: 0.000236]  [num0: 18.000000] [num1 46.000000]
[Epoch 50/500] [Batch 0/676] [D loss: -0.035683] [G loss: -0.282560] [d1 loss: 0.132522] [d2 loss: 0.123866]  [sq d1 d2: 0.000075]  [num0: 13.000000] [num1 51.000000]
[Epoch 50/500] [Batch 20/676] [D loss: -0.047595] [G loss: -0.294851] [d1 loss: 0.103791] [d2 loss: 0.100708]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 50/500] [Batch 40/676] [D loss: -0.051129] [G loss: -0.305730] [d1 loss: 0.149820] [d2 loss: 0.137168]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 50/500] [Batch 60/676] [D loss: -0.026650] [G loss: -0.322706] [d1 loss: 0.114082] [d2 loss: 0.128948]  [sq d1 d2: 0.000221]  [num0: 17.000000] [num1 47.000000]
[Epoch 50/500] [Batch 80/676] [D loss: -0.010058] [G loss: -0.314410] [d1 loss: 0.237472] [d2 loss: 0.193588]  [sq d1 d2: 0.001926]  [num0: 20.000000] [num1 44.000000]
[Epoch 50/500] [Batch 100/676] [D loss: 0.033612] [G loss: -0.262716] [d1 loss: 0.225651] [d2 loss: 0.199528]  [sq d1 d2: 0.000682]  [num0: 12.000000] [num1 52.000000]
[Epoch 50/500] [Batch 120/676] [D loss: -0.017840] [G loss: -0.179646] [d1 loss: 0.081791] [d2 loss: 0.091255]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 50/500] [Batch 140/676] [D loss: -0.020931] [G loss: -0.140973] [d1 loss: 0.088030] [d2 loss: 0.099448]  [sq d1 d2: 0.000130]  [num0: 10.000000] [num1 54.000000]
[Epoch 50/500] [Batch 160/676] [D loss: -0.045561] [G loss: -0.027506] [d1 loss: 0.087615] [d2 loss: 0.097390]  [sq d1 d2: 0.000096]  [num0: 14.000000] [num1 50.000000]
[Epoch 50/500] [Batch 180/676] [D loss: -0.043744] [G loss: -0.039779] [d1 loss: 0.093312] [d2 loss: 0.086490]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 50/500] [Batch 200/676] [D loss: -0.041348] [G loss: -0.011154] [d1 loss: 0.133779] [d2 loss: 0.131984]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 50/500] [Batch 220/676] [D loss: -0.059141] [G loss: -0.029366] [d1 loss: 0.210317] [d2 loss: 0.218818]  [sq d1 d2: 0.000072]  [num0: 15.000000] [num1 49.000000]
[Epoch 50/500] [Batch 240/676] [D loss: -0.037474] [G loss: -0.010822] [d1 loss: 0.076025] [d2 loss: 0.090469]  [sq d1 d2: 0.000209]  [num0: 11.000000] [num1 53.000000]
[Epoch 50/500] [Batch 260/676] [D loss: -0.017892] [G loss: 0.016751] [d1 loss: 0.078861] [d2 loss: 0.077674]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 50/500] [Batch 280/676] [D loss: -0.027922] [G loss: -0.018923] [d1 loss: 0.092194] [d2 loss: 0.104679]  [sq d1 d2: 0.000156]  [num0: 13.000000] [num1 51.000000]
[Epoch 50/500] [Batch 300/676] [D loss: -0.017945] [G loss: 0.012523] [d1 loss: 0.191702] [d2 loss: 0.200031]  [sq d1 d2: 0.000069]  [num0: 12.000000] [num1 52.000000]
[Epoch 50/500] [Batch 320/676] [D loss: -0.016436] [G loss: 0.039033] [d1 loss: 0.093343] [d2 loss: 0.077198]  [sq d1 d2: 0.000261]  [num0: 19.000000] [num1 45.000000]
[Epoch 50/500] [Batch 340/676] [D loss: -0.019278] [G loss: 0.020279] [d1 loss: 0.117338] [d2 loss: 0.118191]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 50/500] [Batch 360/676] [D loss: -0.005542] [G loss: 0.012793] [d1 loss: 0.096366] [d2 loss: 0.105917]  [sq d1 d2: 0.000091]  [num0: 17.000000] [num1 47.000000]
[Epoch 50/500] [Batch 380/676] [D loss: -0.008737] [G loss: -0.007688] [d1 loss: 0.386407] [d2 loss: 0.360970]  [sq d1 d2: 0.000647]  [num0: 14.000000] [num1 50.000000]
[Epoch 50/500] [Batch 400/676] [D loss: -0.010161] [G loss: -0.019217] [d1 loss: 0.087544] [d2 loss: 0.086890]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 50/500] [Batch 420/676] [D loss: -0.037588] [G loss: -0.048797] [d1 loss: 0.067186] [d2 loss: 0.065783]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 50/500] [Batch 440/676] [D loss: -0.058184] [G loss: -0.061877] [d1 loss: 0.141320] [d2 loss: 0.172366]  [sq d1 d2: 0.000964]  [num0: 16.000000] [num1 48.000000]
[Epoch 50/500] [Batch 460/676] [D loss: -0.059541] [G loss: -0.088824] [d1 loss: 0.150648] [d2 loss: 0.151167]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 50/500] [Batch 480/676] [D loss: -0.034583] [G loss: -0.125958] [d1 loss: 0.105323] [d2 loss: 0.098555]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 50/500] [Batch 500/676] [D loss: -0.036769] [G loss: -0.148973] [d1 loss: 0.117349] [d2 loss: 0.118105]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 50/500] [Batch 520/676] [D loss: -0.046264] [G loss: -0.138218] [d1 loss: 0.126295] [d2 loss: 0.114156]  [sq d1 d2: 0.000147]  [num0: 12.000000] [num1 52.000000]
[Epoch 50/500] [Batch 540/676] [D loss: -0.039464] [G loss: -0.134357] [d1 loss: 0.125996] [d2 loss: 0.120705]  [sq d1 d2: 0.000028]  [num0: 12.000000] [num1 52.000000]
[Epoch 50/500] [Batch 560/676] [D loss: -0.019483] [G loss: -0.110574] [d1 loss: 0.077691] [d2 loss: 0.083440]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 50/500] [Batch 580/676] [D loss: -0.031886] [G loss: -0.107841] [d1 loss: 0.129589] [d2 loss: 0.111425]  [sq d1 d2: 0.000330]  [num0: 13.000000] [num1 51.000000]
[Epoch 50/500] [Batch 600/676] [D loss: -0.018067] [G loss: -0.093233] [d1 loss: 0.162416] [d2 loss: 0.163203]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 50/500] [Batch 620/676] [D loss: -0.015214] [G loss: -0.080995] [d1 loss: 0.161428] [d2 loss: 0.201345]  [sq d1 d2: 0.001593]  [num0: 16.000000] [num1 48.000000]
[Epoch 50/500] [Batch 640/676] [D loss: -0.037410] [G loss: -0.066452] [d1 loss: 0.215924] [d2 loss: 0.180059]  [sq d1 d2: 0.001286]  [num0: 14.000000] [num1 50.000000]

[Epoch 50/500] [Batch 660/676] [D loss: -0.035428] [G loss: -0.023624] [d1 loss: 0.152284] [d2 loss: 0.145705]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 0/676] [D loss: -0.025952] [G loss: -0.016777] [d1 loss: 0.163121] [d2 loss: 0.157582]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 20/676] [D loss: -0.035925] [G loss: -0.010242] [d1 loss: 0.234892] [d2 loss: 0.211154]  [sq d1 d2: 0.000563]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 40/676] [D loss: -0.036905] [G loss: 0.010372] [d1 loss: 0.146680] [d2 loss: 0.139301]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 60/676] [D loss: 0.008240] [G loss: 0.005965] [d1 loss: 0.097777] [d2 loss: 0.100656]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 51/500] [Batch 80/676] [D loss: -0.025900] [G loss: -0.015940] [d1 loss: 0.098918] [d2 loss: 0.114863]  [sq d1 d2: 0.000254]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 100/676] [D loss: -0.024748] [G loss: -0.013478] [d1 loss: 0.157143] [d2 loss: 0.153470]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 51/500] [Batch 120/676] [D loss: -0.019999] [G loss: -0.019994] [d1 loss: 0.077801] [d2 loss: 0.073769]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 140/676] [D loss: -0.031063] [G loss: -0.017254] [d1 loss: 0.177977] [d2 loss: 0.161529]  [sq d1 d2: 0.000271]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 160/676] [D loss: 0.000951] [G loss: -0.011649] [d1 loss: 0.158384] [d2 loss: 0.162867]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 180/676] [D loss: -0.005690] [G loss: -0.020952] [d1 loss: 0.144957] [d2 loss: 0.148153]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 200/676] [D loss: -0.009968] [G loss: -0.021399] [d1 loss: 0.137951] [d2 loss: 0.134949]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 220/676] [D loss: -0.008221] [G loss: -0.040251] [d1 loss: 0.123716] [d2 loss: 0.143125]  [sq d1 d2: 0.000377]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 240/676] [D loss: -0.021916] [G loss: -0.036512] [d1 loss: 0.135643] [d2 loss: 0.145113]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 260/676] [D loss: -0.007335] [G loss: -0.058070] [d1 loss: 0.110117] [d2 loss: 0.109396]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 280/676] [D loss: -0.016679] [G loss: -0.059494] [d1 loss: 0.107013] [d2 loss: 0.087874]  [sq d1 d2: 0.000366]  [num0: 18.000000] [num1 46.000000]
[Epoch 51/500] [Batch 300/676] [D loss: -0.027227] [G loss: -0.078217] [d1 loss: 0.132934] [d2 loss: 0.143825]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 320/676] [D loss: -0.032603] [G loss: -0.100799] [d1 loss: 0.145537] [d2 loss: 0.139346]  [sq d1 d2: 0.000038]  [num0: 19.000000] [num1 45.000000]
[Epoch 51/500] [Batch 340/676] [D loss: -0.046508] [G loss: -0.128288] [d1 loss: 0.097793] [d2 loss: 0.116456]  [sq d1 d2: 0.000348]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 360/676] [D loss: -0.031919] [G loss: -0.105926] [d1 loss: 0.128664] [d2 loss: 0.148549]  [sq d1 d2: 0.000395]  [num0: 19.000000] [num1 45.000000]
[Epoch 51/500] [Batch 380/676] [D loss: -0.030906] [G loss: -0.090486] [d1 loss: 0.109741] [d2 loss: 0.105838]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 400/676] [D loss: -0.003954] [G loss: -0.103717] [d1 loss: 0.040651] [d2 loss: 0.047933]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 420/676] [D loss: -0.015450] [G loss: -0.097081] [d1 loss: 0.071397] [d2 loss: 0.068993]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 440/676] [D loss: -0.013025] [G loss: -0.100549] [d1 loss: 0.064243] [d2 loss: 0.073684]  [sq d1 d2: 0.000089]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 460/676] [D loss: -0.023768] [G loss: -0.089171] [d1 loss: 0.113731] [d2 loss: 0.114535]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 51/500] [Batch 480/676] [D loss: -0.033391] [G loss: -0.081854] [d1 loss: 0.164188] [d2 loss: 0.157680]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 500/676] [D loss: -0.043081] [G loss: -0.105285] [d1 loss: 0.105256] [d2 loss: 0.113545]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 520/676] [D loss: -0.014906] [G loss: -0.103746] [d1 loss: 0.105477] [d2 loss: 0.107517]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 51/500] [Batch 540/676] [D loss: -0.017452] [G loss: -0.052285] [d1 loss: 0.120457] [d2 loss: 0.088273]  [sq d1 d2: 0.001036]  [num0: 17.000000] [num1 47.000000]
[Epoch 51/500] [Batch 560/676] [D loss: -0.016565] [G loss: -0.058721] [d1 loss: 0.167463] [d2 loss: 0.178812]  [sq d1 d2: 0.000129]  [num0: 15.000000] [num1 49.000000]
[Epoch 51/500] [Batch 580/676] [D loss: -0.020090] [G loss: -0.040417] [d1 loss: 0.132825] [d2 loss: 0.128377]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 51/500] [Batch 600/676] [D loss: -0.020786] [G loss: -0.072936] [d1 loss: 0.112337] [d2 loss: 0.103120]  [sq d1 d2: 0.000085]  [num0: 18.000000] [num1 46.000000]
[Epoch 51/500] [Batch 620/676] [D loss: -0.018010] [G loss: -0.066642] [d1 loss: 0.089409] [d2 loss: 0.090214]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 51/500] [Batch 640/676] [D loss: -0.022476] [G loss: -0.080188] [d1 loss: 0.149932] [d2 loss: 0.137195]  [sq d1 d2: 0.000162]  [num0: 13.000000] [num1 51.000000]
[Epoch 51/500] [Batch 660/676] [D loss: -0.014331] [G loss: -0.086248] [d1 loss: 0.122283] [d2 loss: 0.131576]  [sq d1 d2: 0.000086]  [num0: 12.000000] [num1 52.000000]
[Epoch 52/500] [Batch 0/676] [D loss: -0.019909] [G loss: -0.073761] [d1 loss: 0.119349] [d2 loss: 0.130446]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]
[Epoch 52/500] [Batch 20/676] [D loss: -0.013289] [G loss: -0.086991] [d1 loss: 0.155571] [d2 loss: 0.169035]  [sq d1 d2: 0.000181]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 40/676] [D loss: -0.022211] [G loss: -0.103364] [d1 loss: 0.090359] [d2 loss: 0.114678]  [sq d1 d2: 0.000591]  [num0: 13.000000] [num1 51.000000]
[Epoch 52/500] [Batch 60/676] [D loss: -0.039124] [G loss: -0.111944] [d1 loss: 0.101698] [d2 loss: 0.115033]  [sq d1 d2: 0.000178]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 80/676] [D loss: -0.014950] [G loss: -0.125782] [d1 loss: 0.090150] [d2 loss: 0.092741]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 52/500] [Batch 100/676] [D loss: -0.031400] [G loss: -0.116885] [d1 loss: 0.106879] [d2 loss: 0.093584]  [sq d1 d2: 0.000177]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 120/676] [D loss: -0.021767] [G loss: -0.102278] [d1 loss: 0.161704] [d2 loss: 0.148166]  [sq d1 d2: 0.000183]  [num0: 17.000000] [num1 47.000000]
[Epoch 52/500] [Batch 140/676] [D loss: -0.013575] [G loss: -0.081785] [d1 loss: 0.155114] [d2 loss: 0.153015]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 160/676] [D loss: -0.023416] [G loss: -0.079258] [d1 loss: 0.188562] [d2 loss: 0.188749]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 52/500] [Batch 180/676] [D loss: -0.025517] [G loss: -0.079682] [d1 loss: 0.108500] [d2 loss: 0.113473]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 200/676] [D loss: -0.017221] [G loss: -0.091045] [d1 loss: 0.120372] [d2 loss: 0.130572]  [sq d1 d2: 0.000104]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 220/676] [D loss: -0.017398] [G loss: -0.056206] [d1 loss: 0.084660] [d2 loss: 0.086672]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 52/500] [Batch 240/676] [D loss: -0.029358] [G loss: -0.047465] [d1 loss: 0.175150] [d2 loss: 0.169003]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 52/500] [Batch 260/676] [D loss: -0.036043] [G loss: -0.056301] [d1 loss: 0.135451] [d2 loss: 0.140887]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 52/500] [Batch 280/676] [D loss: -0.022767] [G loss: -0.054494] [d1 loss: 0.136134] [d2 loss: 0.124080]  [sq d1 d2: 0.000145]  [num0: 17.000000] [num1 47.000000]

[Epoch 52/500] [Batch 300/676] [D loss: -0.016805] [G loss: -0.036813] [d1 loss: 0.065846] [d2 loss: 0.056768]  [sq d1 d2: 0.000082]  [num0: 21.000000] [num1 43.000000]
[Epoch 52/500] [Batch 320/676] [D loss: -0.027170] [G loss: -0.037303] [d1 loss: 0.056413] [d2 loss: 0.062361]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 340/676] [D loss: -0.015109] [G loss: -0.035119] [d1 loss: 0.067322] [d2 loss: 0.071817]  [sq d1 d2: 0.000020]  [num0: 19.000000] [num1 45.000000]
[Epoch 52/500] [Batch 360/676] [D loss: -0.034686] [G loss: -0.034171] [d1 loss: 0.155475] [d2 loss: 0.179454]  [sq d1 d2: 0.000575]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 380/676] [D loss: -0.026321] [G loss: -0.047463] [d1 loss: 0.120735] [d2 loss: 0.102856]  [sq d1 d2: 0.000320]  [num0: 11.000000] [num1 53.000000]
[Epoch 52/500] [Batch 400/676] [D loss: -0.031472] [G loss: -0.058643] [d1 loss: 0.091512] [d2 loss: 0.101973]  [sq d1 d2: 0.000109]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 420/676] [D loss: -0.018680] [G loss: -0.045084] [d1 loss: 0.158448] [d2 loss: 0.146391]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 440/676] [D loss: -0.011873] [G loss: -0.039281] [d1 loss: 0.126222] [d2 loss: 0.131533]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 52/500] [Batch 460/676] [D loss: -0.018177] [G loss: -0.048225] [d1 loss: 0.073803] [d2 loss: 0.075635]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 480/676] [D loss: -0.029783] [G loss: -0.034752] [d1 loss: 0.084799] [d2 loss: 0.078371]  [sq d1 d2: 0.000041]  [num0: 12.000000] [num1 52.000000]
[Epoch 52/500] [Batch 500/676] [D loss: -0.019978] [G loss: -0.053546] [d1 loss: 0.136682] [d2 loss: 0.149594]  [sq d1 d2: 0.000167]  [num0: 14.000000] [num1 50.000000]
[Epoch 52/500] [Batch 520/676] [D loss: -0.022751] [G loss: -0.060308] [d1 loss: 0.220759] [d2 loss: 0.194383]  [sq d1 d2: 0.000696]  [num0: 14.000000] [num1 50.000000]
[Epoch 52/500] [Batch 540/676] [D loss: -0.021679] [G loss: -0.056354] [d1 loss: 0.059995] [d2 loss: 0.056046]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 52/500] [Batch 560/676] [D loss: -0.024582] [G loss: -0.053608] [d1 loss: 0.084509] [d2 loss: 0.083419]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 580/676] [D loss: -0.019399] [G loss: -0.040690] [d1 loss: 0.063467] [d2 loss: 0.071770]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 52/500] [Batch 600/676] [D loss: -0.025734] [G loss: -0.032692] [d1 loss: 0.111459] [d2 loss: 0.116415]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 620/676] [D loss: -0.027363] [G loss: -0.039312] [d1 loss: 0.144788] [d2 loss: 0.146389]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 52/500] [Batch 640/676] [D loss: -0.016725] [G loss: -0.033898] [d1 loss: 0.108063] [d2 loss: 0.106470]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 52/500] [Batch 660/676] [D loss: -0.024719] [G loss: -0.028783] [d1 loss: 0.103772] [d2 loss: 0.099128]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 0/676] [D loss: -0.018994] [G loss: -0.044984] [d1 loss: 0.109679] [d2 loss: 0.110888]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 53/500] [Batch 20/676] [D loss: -0.008328] [G loss: -0.019303] [d1 loss: 0.089830] [d2 loss: 0.098340]  [sq d1 d2: 0.000072]  [num0: 14.000000] [num1 50.000000]
[Epoch 53/500] [Batch 40/676] [D loss: -0.014660] [G loss: -0.006163] [d1 loss: 0.053488] [d2 loss: 0.060122]  [sq d1 d2: 0.000044]  [num0: 21.000000] [num1 43.000000]
[Epoch 53/500] [Batch 60/676] [D loss: -0.013759] [G loss: -0.028782] [d1 loss: 0.081263] [d2 loss: 0.083744]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 53/500] [Batch 80/676] [D loss: -0.024763] [G loss: -0.011389] [d1 loss: 0.137761] [d2 loss: 0.157065]  [sq d1 d2: 0.000373]  [num0: 15.000000] [num1 49.000000]
[Epoch 53/500] [Batch 100/676] [D loss: -0.036334] [G loss: -0.001550] [d1 loss: 0.211859] [d2 loss: 0.190526]  [sq d1 d2: 0.000455]  [num0: 19.000000] [num1 45.000000]
[Epoch 53/500] [Batch 120/676] [D loss: -0.027405] [G loss: -0.000042] [d1 loss: 0.178287] [d2 loss: 0.185880]  [sq d1 d2: 0.000058]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 140/676] [D loss: -0.022371] [G loss: 0.001494] [d1 loss: 0.061039] [d2 loss: 0.068156]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 160/676] [D loss: -0.043348] [G loss: 0.009634] [d1 loss: 0.207753] [d2 loss: 0.203978]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 53/500] [Batch 180/676] [D loss: -0.019291] [G loss: 0.001848] [d1 loss: 0.098999] [d2 loss: 0.085891]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 200/676] [D loss: -0.025998] [G loss: -0.021222] [d1 loss: 0.117422] [d2 loss: 0.119473]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 220/676] [D loss: -0.023269] [G loss: -0.025537] [d1 loss: 0.117265] [d2 loss: 0.107472]  [sq d1 d2: 0.000096]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 240/676] [D loss: -0.024278] [G loss: -0.035200] [d1 loss: 0.114376] [d2 loss: 0.124284]  [sq d1 d2: 0.000098]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 260/676] [D loss: -0.023824] [G loss: -0.014641] [d1 loss: 0.074043] [d2 loss: 0.071629]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 53/500] [Batch 280/676] [D loss: -0.028100] [G loss: -0.031193] [d1 loss: 0.105253] [d2 loss: 0.127230]  [sq d1 d2: 0.000483]  [num0: 13.000000] [num1 51.000000]
[Epoch 53/500] [Batch 300/676] [D loss: -0.020142] [G loss: -0.035424] [d1 loss: 0.129748] [d2 loss: 0.125956]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 320/676] [D loss: -0.019838] [G loss: -0.053954] [d1 loss: 0.117689] [d2 loss: 0.106557]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 53/500] [Batch 340/676] [D loss: -0.033622] [G loss: -0.042082] [d1 loss: 0.129229] [d2 loss: 0.136529]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 53/500] [Batch 360/676] [D loss: -0.023614] [G loss: -0.062487] [d1 loss: 0.047978] [d2 loss: 0.074735]  [sq d1 d2: 0.000716]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 380/676] [D loss: -0.026086] [G loss: -0.059395] [d1 loss: 0.151363] [d2 loss: 0.144921]  [sq d1 d2: 0.000042]  [num0: 12.000000] [num1 52.000000]
[Epoch 53/500] [Batch 400/676] [D loss: -0.021309] [G loss: -0.059697] [d1 loss: 0.150417] [d2 loss: 0.163666]  [sq d1 d2: 0.000176]  [num0: 15.000000] [num1 49.000000]
[Epoch 53/500] [Batch 420/676] [D loss: -0.014558] [G loss: -0.068898] [d1 loss: 0.131097] [d2 loss: 0.147767]  [sq d1 d2: 0.000278]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 440/676] [D loss: -0.018132] [G loss: -0.047984] [d1 loss: 0.129102] [d2 loss: 0.125204]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 53/500] [Batch 460/676] [D loss: -0.027035] [G loss: -0.048900] [d1 loss: 0.142465] [d2 loss: 0.132424]  [sq d1 d2: 0.000101]  [num0: 14.000000] [num1 50.000000]
[Epoch 53/500] [Batch 480/676] [D loss: -0.014545] [G loss: -0.043465] [d1 loss: 0.155509] [d2 loss: 0.163918]  [sq d1 d2: 0.000071]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 500/676] [D loss: -0.020181] [G loss: -0.059629] [d1 loss: 0.126840] [d2 loss: 0.127122]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 520/676] [D loss: -0.025241] [G loss: -0.070041] [d1 loss: 0.224524] [d2 loss: 0.249644]  [sq d1 d2: 0.000631]  [num0: 19.000000] [num1 45.000000]
[Epoch 53/500] [Batch 540/676] [D loss: -0.029134] [G loss: -0.062124] [d1 loss: 0.068557] [d2 loss: 0.068612]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 560/676] [D loss: -0.016994] [G loss: -0.040369] [d1 loss: 0.202959] [d2 loss: 0.186800]  [sq d1 d2: 0.000261]  [num0: 14.000000] [num1 50.000000]
[Epoch 53/500] [Batch 580/676] [D loss: -0.024205] [G loss: -0.036963] [d1 loss: 0.141680] [d2 loss: 0.146018]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]

[Epoch 53/500] [Batch 600/676] [D loss: -0.016246] [G loss: -0.056198] [d1 loss: 0.085531] [d2 loss: 0.101560]  [sq d1 d2: 0.000257]  [num0: 16.000000] [num1 48.000000]
[Epoch 53/500] [Batch 620/676] [D loss: -0.018598] [G loss: -0.056394] [d1 loss: 0.129649] [d2 loss: 0.152139]  [sq d1 d2: 0.000506]  [num0: 18.000000] [num1 46.000000]
[Epoch 53/500] [Batch 640/676] [D loss: -0.023425] [G loss: -0.046700] [d1 loss: 0.091216] [d2 loss: 0.106278]  [sq d1 d2: 0.000227]  [num0: 17.000000] [num1 47.000000]
[Epoch 53/500] [Batch 660/676] [D loss: -0.017184] [G loss: -0.054942] [d1 loss: 0.081803] [d2 loss: 0.085113]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 0/676] [D loss: -0.019840] [G loss: -0.059773] [d1 loss: 0.145625] [d2 loss: 0.129131]  [sq d1 d2: 0.000272]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 20/676] [D loss: -0.018447] [G loss: -0.057083] [d1 loss: 0.090291] [d2 loss: 0.081278]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 40/676] [D loss: -0.014679] [G loss: -0.042074] [d1 loss: 0.145167] [d2 loss: 0.143567]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 54/500] [Batch 60/676] [D loss: -0.015909] [G loss: -0.059466] [d1 loss: 0.129668] [d2 loss: 0.144170]  [sq d1 d2: 0.000210]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 80/676] [D loss: -0.018187] [G loss: -0.057636] [d1 loss: 0.071458] [d2 loss: 0.079056]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 54/500] [Batch 100/676] [D loss: -0.022221] [G loss: -0.060488] [d1 loss: 0.113622] [d2 loss: 0.136051]  [sq d1 d2: 0.000503]  [num0: 15.000000] [num1 49.000000]
[Epoch 54/500] [Batch 120/676] [D loss: -0.015153] [G loss: -0.058911] [d1 loss: 0.137963] [d2 loss: 0.129039]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 54/500] [Batch 140/676] [D loss: -0.022342] [G loss: -0.043012] [d1 loss: 0.166939] [d2 loss: 0.176464]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 54/500] [Batch 160/676] [D loss: -0.018421] [G loss: -0.047503] [d1 loss: 0.217518] [d2 loss: 0.227831]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 54/500] [Batch 180/676] [D loss: -0.027098] [G loss: -0.052121] [d1 loss: 0.107646] [d2 loss: 0.132264]  [sq d1 d2: 0.000606]  [num0: 16.000000] [num1 48.000000]
[Epoch 54/500] [Batch 200/676] [D loss: -0.020149] [G loss: -0.037286] [d1 loss: 0.117504] [d2 loss: 0.113563]  [sq d1 d2: 0.000016]  [num0: 9.000000] [num1 55.000000]
[Epoch 54/500] [Batch 220/676] [D loss: -0.014706] [G loss: -0.041461] [d1 loss: 0.043351] [d2 loss: 0.055814]  [sq d1 d2: 0.000155]  [num0: 12.000000] [num1 52.000000]
[Epoch 54/500] [Batch 240/676] [D loss: -0.014590] [G loss: -0.032497] [d1 loss: 0.223621] [d2 loss: 0.237484]  [sq d1 d2: 0.000192]  [num0: 20.000000] [num1 44.000000]
[Epoch 54/500] [Batch 260/676] [D loss: -0.024693] [G loss: -0.024503] [d1 loss: 0.091916] [d2 loss: 0.108365]  [sq d1 d2: 0.000271]  [num0: 17.000000] [num1 47.000000]
[Epoch 54/500] [Batch 280/676] [D loss: -0.014341] [G loss: -0.040435] [d1 loss: 0.126656] [d2 loss: 0.141862]  [sq d1 d2: 0.000231]  [num0: 17.000000] [num1 47.000000]
[Epoch 54/500] [Batch 300/676] [D loss: -0.023295] [G loss: -0.033194] [d1 loss: 0.155438] [d2 loss: 0.176420]  [sq d1 d2: 0.000440]  [num0: 16.000000] [num1 48.000000]
[Epoch 54/500] [Batch 320/676] [D loss: -0.022685] [G loss: -0.030066] [d1 loss: 0.074782] [d2 loss: 0.098544]  [sq d1 d2: 0.000565]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 340/676] [D loss: -0.023819] [G loss: -0.039013] [d1 loss: 0.128780] [d2 loss: 0.128795]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 54/500] [Batch 360/676] [D loss: -0.023743] [G loss: -0.032577] [d1 loss: 0.054312] [d2 loss: 0.079506]  [sq d1 d2: 0.000635]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 380/676] [D loss: -0.021845] [G loss: -0.036849] [d1 loss: 0.145483] [d2 loss: 0.152365]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 54/500] [Batch 400/676] [D loss: -0.029016] [G loss: -0.012282] [d1 loss: 0.106159] [d2 loss: 0.103000]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 54/500] [Batch 420/676] [D loss: -0.015726] [G loss: -0.032280] [d1 loss: 0.056658] [d2 loss: 0.059665]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 54/500] [Batch 440/676] [D loss: -0.026206] [G loss: -0.040760] [d1 loss: 0.199428] [d2 loss: 0.196436]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 54/500] [Batch 460/676] [D loss: -0.021817] [G loss: -0.046901] [d1 loss: 0.100062] [d2 loss: 0.121831]  [sq d1 d2: 0.000474]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 480/676] [D loss: -0.024506] [G loss: -0.043739] [d1 loss: 0.131141] [d2 loss: 0.130842]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 54/500] [Batch 500/676] [D loss: -0.015083] [G loss: -0.050699] [d1 loss: 0.072188] [d2 loss: 0.079133]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 520/676] [D loss: -0.027807] [G loss: -0.048631] [d1 loss: 0.131311] [d2 loss: 0.123362]  [sq d1 d2: 0.000063]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 540/676] [D loss: -0.023315] [G loss: -0.038593] [d1 loss: 0.168910] [d2 loss: 0.161273]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 560/676] [D loss: -0.027894] [G loss: -0.039166] [d1 loss: 0.084604] [d2 loss: 0.093756]  [sq d1 d2: 0.000084]  [num0: 18.000000] [num1 46.000000]
[Epoch 54/500] [Batch 580/676] [D loss: -0.022239] [G loss: -0.040273] [d1 loss: 0.086004] [d2 loss: 0.094016]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 54/500] [Batch 600/676] [D loss: -0.024456] [G loss: -0.032552] [d1 loss: 0.103603] [d2 loss: 0.099393]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 54/500] [Batch 620/676] [D loss: -0.028361] [G loss: -0.045492] [d1 loss: 0.097258] [d2 loss: 0.110864]  [sq d1 d2: 0.000185]  [num0: 19.000000] [num1 45.000000]
[Epoch 54/500] [Batch 640/676] [D loss: -0.021008] [G loss: -0.040346] [d1 loss: 0.188293] [d2 loss: 0.161835]  [sq d1 d2: 0.000700]  [num0: 15.000000] [num1 49.000000]
[Epoch 54/500] [Batch 660/676] [D loss: -0.018838] [G loss: -0.039373] [d1 loss: 0.043565] [d2 loss: 0.052228]  [sq d1 d2: 0.000075]  [num0: 15.000000] [num1 49.000000]
[Epoch 55/500] [Batch 0/676] [D loss: -0.022078] [G loss: -0.052612] [d1 loss: 0.150579] [d2 loss: 0.152522]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 55/500] [Batch 20/676] [D loss: -0.016057] [G loss: -0.030324] [d1 loss: 0.150088] [d2 loss: 0.119422]  [sq d1 d2: 0.000940]  [num0: 16.000000] [num1 48.000000]
[Epoch 55/500] [Batch 40/676] [D loss: -0.019668] [G loss: -0.050883] [d1 loss: 0.092452] [d2 loss: 0.091349]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 60/676] [D loss: -0.022103] [G loss: -0.056361] [d1 loss: 0.229183] [d2 loss: 0.207996]  [sq d1 d2: 0.000449]  [num0: 12.000000] [num1 52.000000]
[Epoch 55/500] [Batch 80/676] [D loss: -0.032793] [G loss: -0.062231] [d1 loss: 0.222309] [d2 loss: 0.228338]  [sq d1 d2: 0.000036]  [num0: 21.000000] [num1 43.000000]
[Epoch 55/500] [Batch 100/676] [D loss: -0.019802] [G loss: -0.042220] [d1 loss: 0.066060] [d2 loss: 0.060302]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 120/676] [D loss: -0.022189] [G loss: -0.043066] [d1 loss: 0.160078] [d2 loss: 0.178418]  [sq d1 d2: 0.000336]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 140/676] [D loss: -0.018989] [G loss: -0.051099] [d1 loss: 0.219078] [d2 loss: 0.224341]  [sq d1 d2: 0.000028]  [num0: 13.000000] [num1 51.000000]
[Epoch 55/500] [Batch 160/676] [D loss: -0.020749] [G loss: -0.047710] [d1 loss: 0.144261] [d2 loss: 0.143580]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 180/676] [D loss: -0.023436] [G loss: -0.043039] [d1 loss: 0.169091] [d2 loss: 0.167789]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 200/676] [D loss: -0.017872] [G loss: -0.038190] [d1 loss: 0.089202] [d2 loss: 0.085107]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 220/676] [D loss: -0.021986] [G loss: -0.050897] [d1 loss: 0.120160] [d2 loss: 0.108653]  [sq d1 d2: 0.000132]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 240/676] [D loss: -0.024356] [G loss: -0.059837] [d1 loss: 0.134591] [d2 loss: 0.135148]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]

[Epoch 55/500] [Batch 260/676] [D loss: -0.019285] [G loss: -0.049510] [d1 loss: 0.093372] [d2 loss: 0.089939]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 280/676] [D loss: -0.027006] [G loss: -0.062914] [d1 loss: 0.079863] [d2 loss: 0.082688]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 55/500] [Batch 300/676] [D loss: -0.022680] [G loss: -0.063685] [d1 loss: 0.140146] [d2 loss: 0.107837]  [sq d1 d2: 0.001044]  [num0: 16.000000] [num1 48.000000]
[Epoch 55/500] [Batch 320/676] [D loss: -0.013385] [G loss: -0.067254] [d1 loss: 0.175055] [d2 loss: 0.152531]  [sq d1 d2: 0.000507]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 340/676] [D loss: -0.019575] [G loss: -0.061938] [d1 loss: 0.116932] [d2 loss: 0.096118]  [sq d1 d2: 0.000433]  [num0: 15.000000] [num1 49.000000]
[Epoch 55/500] [Batch 360/676] [D loss: -0.023248] [G loss: -0.040586] [d1 loss: 0.131720] [d2 loss: 0.105925]  [sq d1 d2: 0.000665]  [num0: 18.000000] [num1 46.000000]
[Epoch 55/500] [Batch 380/676] [D loss: -0.008477] [G loss: -0.039614] [d1 loss: 0.099387] [d2 loss: 0.113997]  [sq d1 d2: 0.000213]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 400/676] [D loss: -0.010237] [G loss: -0.046951] [d1 loss: 0.066573] [d2 loss: 0.062937]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 420/676] [D loss: -0.024699] [G loss: -0.036238] [d1 loss: 0.194966] [d2 loss: 0.218980]  [sq d1 d2: 0.000577]  [num0: 15.000000] [num1 49.000000]
[Epoch 55/500] [Batch 440/676] [D loss: -0.023786] [G loss: -0.039275] [d1 loss: 0.097979] [d2 loss: 0.092477]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 55/500] [Batch 460/676] [D loss: -0.011553] [G loss: -0.031020] [d1 loss: 0.138877] [d2 loss: 0.143260]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 55/500] [Batch 480/676] [D loss: -0.014623] [G loss: -0.026755] [d1 loss: 0.124573] [d2 loss: 0.134177]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 55/500] [Batch 500/676] [D loss: -0.017746] [G loss: -0.038663] [d1 loss: 0.163137] [d2 loss: 0.172014]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 55/500] [Batch 520/676] [D loss: -0.013052] [G loss: -0.035451] [d1 loss: 0.144073] [d2 loss: 0.152969]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 55/500] [Batch 540/676] [D loss: -0.020364] [G loss: -0.036392] [d1 loss: 0.163333] [d2 loss: 0.164641]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 55/500] [Batch 560/676] [D loss: -0.028591] [G loss: -0.042792] [d1 loss: 0.150230] [d2 loss: 0.156717]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 55/500] [Batch 580/676] [D loss: -0.013286] [G loss: -0.036958] [d1 loss: 0.125539] [d2 loss: 0.133398]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 55/500] [Batch 600/676] [D loss: -0.024396] [G loss: -0.058489] [d1 loss: 0.178710] [d2 loss: 0.183417]  [sq d1 d2: 0.000022]  [num0: 21.000000] [num1 43.000000]
[Epoch 55/500] [Batch 620/676] [D loss: -0.017411] [G loss: -0.052278] [d1 loss: 0.191183] [d2 loss: 0.172889]  [sq d1 d2: 0.000335]  [num0: 20.000000] [num1 44.000000]
[Epoch 55/500] [Batch 640/676] [D loss: -0.017765] [G loss: -0.054932] [d1 loss: 0.181603] [d2 loss: 0.202595]  [sq d1 d2: 0.000441]  [num0: 13.000000] [num1 51.000000]
[Epoch 55/500] [Batch 660/676] [D loss: -0.016315] [G loss: -0.029958] [d1 loss: 0.108904] [d2 loss: 0.132788]  [sq d1 d2: 0.000570]  [num0: 17.000000] [num1 47.000000]
[Epoch 56/500] [Batch 0/676] [D loss: -0.020102] [G loss: -0.044525] [d1 loss: 0.156907] [d2 loss: 0.154253]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 56/500] [Batch 20/676] [D loss: -0.018970] [G loss: -0.041566] [d1 loss: 0.071161] [d2 loss: 0.078681]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 56/500] [Batch 40/676] [D loss: -0.022475] [G loss: -0.040788] [d1 loss: 0.164463] [d2 loss: 0.169980]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 60/676] [D loss: -0.012491] [G loss: -0.040944] [d1 loss: 0.086406] [d2 loss: 0.098335]  [sq d1 d2: 0.000142]  [num0: 17.000000] [num1 47.000000]
[Epoch 56/500] [Batch 80/676] [D loss: -0.024095] [G loss: -0.038303] [d1 loss: 0.122444] [d2 loss: 0.103471]  [sq d1 d2: 0.000360]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 100/676] [D loss: -0.008641] [G loss: -0.049999] [d1 loss: 0.147422] [d2 loss: 0.132256]  [sq d1 d2: 0.000230]  [num0: 11.000000] [num1 53.000000]
[Epoch 56/500] [Batch 120/676] [D loss: -0.025106] [G loss: -0.049421] [d1 loss: 0.095909] [d2 loss: 0.087505]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 56/500] [Batch 140/676] [D loss: -0.015215] [G loss: -0.056823] [d1 loss: 0.102423] [d2 loss: 0.113791]  [sq d1 d2: 0.000129]  [num0: 20.000000] [num1 44.000000]
[Epoch 56/500] [Batch 160/676] [D loss: -0.022491] [G loss: -0.049344] [d1 loss: 0.121367] [d2 loss: 0.119382]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 56/500] [Batch 180/676] [D loss: -0.019915] [G loss: -0.044068] [d1 loss: 0.235672] [d2 loss: 0.223510]  [sq d1 d2: 0.000148]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 200/676] [D loss: -0.012661] [G loss: -0.060219] [d1 loss: 0.081971] [d2 loss: 0.079765]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 56/500] [Batch 220/676] [D loss: -0.016214] [G loss: -0.060506] [d1 loss: 0.071229] [d2 loss: 0.078341]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 56/500] [Batch 240/676] [D loss: -0.024633] [G loss: -0.047840] [d1 loss: 0.166118] [d2 loss: 0.130824]  [sq d1 d2: 0.001246]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 260/676] [D loss: -0.018140] [G loss: -0.072195] [d1 loss: 0.159765] [d2 loss: 0.191570]  [sq d1 d2: 0.001012]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 280/676] [D loss: -0.018719] [G loss: -0.060901] [d1 loss: 0.083298] [d2 loss: 0.094373]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 300/676] [D loss: -0.021193] [G loss: -0.072513] [d1 loss: 0.074687] [d2 loss: 0.061026]  [sq d1 d2: 0.000187]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 320/676] [D loss: -0.022399] [G loss: -0.051619] [d1 loss: 0.249034] [d2 loss: 0.225118]  [sq d1 d2: 0.000572]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 340/676] [D loss: -0.018956] [G loss: -0.065494] [d1 loss: 0.157934] [d2 loss: 0.160315]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 56/500] [Batch 360/676] [D loss: -0.022875] [G loss: -0.066095] [d1 loss: 0.083850] [d2 loss: 0.080110]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 56/500] [Batch 380/676] [D loss: -0.010601] [G loss: -0.056509] [d1 loss: 0.160269] [d2 loss: 0.161033]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 400/676] [D loss: -0.012733] [G loss: -0.064121] [d1 loss: 0.080138] [d2 loss: 0.103588]  [sq d1 d2: 0.000550]  [num0: 12.000000] [num1 52.000000]
[Epoch 56/500] [Batch 420/676] [D loss: -0.021936] [G loss: -0.050819] [d1 loss: 0.208065] [d2 loss: 0.217760]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 56/500] [Batch 440/676] [D loss: -0.014238] [G loss: -0.044814] [d1 loss: 0.072240] [d2 loss: 0.066200]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 460/676] [D loss: -0.011469] [G loss: -0.048638] [d1 loss: 0.109179] [d2 loss: 0.113209]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 480/676] [D loss: -0.012532] [G loss: -0.030188] [d1 loss: 0.104448] [d2 loss: 0.105280]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 500/676] [D loss: -0.021172] [G loss: -0.027876] [d1 loss: 0.081057] [d2 loss: 0.097486]  [sq d1 d2: 0.000270]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 520/676] [D loss: -0.021781] [G loss: -0.031657] [d1 loss: 0.258493] [d2 loss: 0.235989]  [sq d1 d2: 0.000506]  [num0: 18.000000] [num1 46.000000]
[Epoch 56/500] [Batch 540/676] [D loss: -0.023361] [G loss: -0.041854] [d1 loss: 0.072380] [d2 loss: 0.086078]  [sq d1 d2: 0.000188]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 560/676] [D loss: -0.016742] [G loss: -0.046021] [d1 loss: 0.120985] [d2 loss: 0.102835]  [sq d1 d2: 0.000329]  [num0: 14.000000] [num1 50.000000]
[Epoch 56/500] [Batch 580/676] [D loss: -0.020081] [G loss: -0.045167] [d1 loss: 0.085435] [d2 loss: 0.109224]  [sq d1 d2: 0.000566]  [num0: 17.000000] [num1 47.000000]
[Epoch 56/500] [Batch 600/676] [D loss: -0.016575] [G loss: -0.035755] [d1 loss: 0.165965] [d2 loss: 0.195123]  [sq d1 d2: 0.000850]  [num0: 12.000000] [num1 52.000000]

[Epoch 56/500] [Batch 620/676] [D loss: -0.024536] [G loss: -0.027091] [d1 loss: 0.218142] [d2 loss: 0.186939]  [sq d1 d2: 0.000974]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 640/676] [D loss: -0.013687] [G loss: -0.031695] [d1 loss: 0.119700] [d2 loss: 0.129673]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 56/500] [Batch 660/676] [D loss: -0.027674] [G loss: -0.038992] [d1 loss: 0.129101] [d2 loss: 0.141558]  [sq d1 d2: 0.000155]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 0/676] [D loss: -0.019780] [G loss: -0.035627] [d1 loss: 0.066528] [d2 loss: 0.066100]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 57/500] [Batch 20/676] [D loss: -0.023995] [G loss: -0.025400] [d1 loss: 0.138046] [d2 loss: 0.138696]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 57/500] [Batch 40/676] [D loss: -0.028645] [G loss: -0.035240] [d1 loss: 0.077779] [d2 loss: 0.107683]  [sq d1 d2: 0.000894]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 60/676] [D loss: -0.005287] [G loss: -0.034549] [d1 loss: 0.114365] [d2 loss: 0.156230]  [sq d1 d2: 0.001753]  [num0: 15.000000] [num1 49.000000]
[Epoch 57/500] [Batch 80/676] [D loss: -0.021168] [G loss: -0.038486] [d1 loss: 0.290406] [d2 loss: 0.276259]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 100/676] [D loss: -0.015916] [G loss: -0.033811] [d1 loss: 0.154170] [d2 loss: 0.204412]  [sq d1 d2: 0.002524]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 120/676] [D loss: -0.022623] [G loss: -0.025975] [d1 loss: 0.071292] [d2 loss: 0.068141]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 140/676] [D loss: -0.015536] [G loss: -0.040798] [d1 loss: 0.059125] [d2 loss: 0.059916]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 57/500] [Batch 160/676] [D loss: -0.016441] [G loss: -0.027828] [d1 loss: 0.152747] [d2 loss: 0.145961]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 57/500] [Batch 180/676] [D loss: -0.020427] [G loss: -0.034396] [d1 loss: 0.090446] [d2 loss: 0.095070]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 57/500] [Batch 200/676] [D loss: -0.024608] [G loss: -0.030115] [d1 loss: 0.111618] [d2 loss: 0.133376]  [sq d1 d2: 0.000473]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 220/676] [D loss: -0.031756] [G loss: -0.024264] [d1 loss: 0.159007] [d2 loss: 0.126068]  [sq d1 d2: 0.001085]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 240/676] [D loss: -0.026149] [G loss: -0.040964] [d1 loss: 0.144976] [d2 loss: 0.156056]  [sq d1 d2: 0.000123]  [num0: 12.000000] [num1 52.000000]
[Epoch 57/500] [Batch 260/676] [D loss: -0.021460] [G loss: -0.035453] [d1 loss: 0.094314] [d2 loss: 0.085952]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 280/676] [D loss: -0.023447] [G loss: -0.042463] [d1 loss: 0.090289] [d2 loss: 0.072921]  [sq d1 d2: 0.000302]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 300/676] [D loss: -0.010967] [G loss: -0.056407] [d1 loss: 0.097885] [d2 loss: 0.101125]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 320/676] [D loss: -0.022627] [G loss: -0.045019] [d1 loss: 0.114942] [d2 loss: 0.122805]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 340/676] [D loss: -0.011821] [G loss: -0.034969] [d1 loss: 0.090657] [d2 loss: 0.078020]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 57/500] [Batch 360/676] [D loss: -0.022257] [G loss: -0.043900] [d1 loss: 0.127237] [d2 loss: 0.119309]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 380/676] [D loss: -0.022619] [G loss: -0.050877] [d1 loss: 0.137970] [d2 loss: 0.136612]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 400/676] [D loss: -0.018844] [G loss: -0.061185] [d1 loss: 0.029493] [d2 loss: 0.032196]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 57/500] [Batch 420/676] [D loss: -0.027559] [G loss: -0.052571] [d1 loss: 0.064047] [d2 loss: 0.054512]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 57/500] [Batch 440/676] [D loss: -0.017399] [G loss: -0.063835] [d1 loss: 0.110532] [d2 loss: 0.092087]  [sq d1 d2: 0.000340]  [num0: 11.000000] [num1 53.000000]
[Epoch 57/500] [Batch 460/676] [D loss: -0.011266] [G loss: -0.044034] [d1 loss: 0.162029] [d2 loss: 0.167380]  [sq d1 d2: 0.000029]  [num0: 20.000000] [num1 44.000000]
[Epoch 57/500] [Batch 480/676] [D loss: -0.021540] [G loss: -0.058615] [d1 loss: 0.115418] [d2 loss: 0.131360]  [sq d1 d2: 0.000254]  [num0: 17.000000] [num1 47.000000]
[Epoch 57/500] [Batch 500/676] [D loss: -0.021095] [G loss: -0.034261] [d1 loss: 0.082252] [d2 loss: 0.094905]  [sq d1 d2: 0.000160]  [num0: 11.000000] [num1 53.000000]
[Epoch 57/500] [Batch 520/676] [D loss: -0.024113] [G loss: -0.047768] [d1 loss: 0.115293] [d2 loss: 0.104681]  [sq d1 d2: 0.000113]  [num0: 12.000000] [num1 52.000000]
[Epoch 57/500] [Batch 540/676] [D loss: -0.026000] [G loss: -0.042294] [d1 loss: 0.143251] [d2 loss: 0.154956]  [sq d1 d2: 0.000137]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 560/676] [D loss: -0.022704] [G loss: -0.037706] [d1 loss: 0.226516] [d2 loss: 0.217227]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 57/500] [Batch 580/676] [D loss: -0.014263] [G loss: -0.058911] [d1 loss: 0.127186] [d2 loss: 0.098692]  [sq d1 d2: 0.000812]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 600/676] [D loss: -0.013347] [G loss: -0.060975] [d1 loss: 0.148387] [d2 loss: 0.149743]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 620/676] [D loss: -0.033131] [G loss: -0.046204] [d1 loss: 0.153721] [d2 loss: 0.146807]  [sq d1 d2: 0.000048]  [num0: 19.000000] [num1 45.000000]
[Epoch 57/500] [Batch 640/676] [D loss: -0.015117] [G loss: -0.057635] [d1 loss: 0.158894] [d2 loss: 0.153456]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 57/500] [Batch 660/676] [D loss: -0.020068] [G loss: -0.067009] [d1 loss: 0.114836] [d2 loss: 0.124709]  [sq d1 d2: 0.000097]  [num0: 18.000000] [num1 46.000000]
[Epoch 58/500] [Batch 0/676] [D loss: -0.024067] [G loss: -0.050360] [d1 loss: 0.150204] [d2 loss: 0.146845]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 58/500] [Batch 20/676] [D loss: -0.016655] [G loss: -0.072505] [d1 loss: 0.110108] [d2 loss: 0.116157]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 40/676] [D loss: -0.019169] [G loss: -0.070735] [d1 loss: 0.236375] [d2 loss: 0.236426]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 58/500] [Batch 60/676] [D loss: -0.027994] [G loss: -0.067811] [d1 loss: 0.114272] [d2 loss: 0.117829]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 58/500] [Batch 80/676] [D loss: -0.027453] [G loss: -0.081657] [d1 loss: 0.168603] [d2 loss: 0.136740]  [sq d1 d2: 0.001015]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 100/676] [D loss: -0.027378] [G loss: -0.089475] [d1 loss: 0.217738] [d2 loss: 0.237487]  [sq d1 d2: 0.000390]  [num0: 18.000000] [num1 46.000000]
[Epoch 58/500] [Batch 120/676] [D loss: -0.021733] [G loss: -0.079285] [d1 loss: 0.080941] [d2 loss: 0.073423]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 58/500] [Batch 140/676] [D loss: -0.021446] [G loss: -0.081446] [d1 loss: 0.135468] [d2 loss: 0.106177]  [sq d1 d2: 0.000858]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 160/676] [D loss: -0.017459] [G loss: -0.079704] [d1 loss: 0.088166] [d2 loss: 0.097727]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 180/676] [D loss: -0.017916] [G loss: -0.063975] [d1 loss: 0.141116] [d2 loss: 0.140478]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 58/500] [Batch 200/676] [D loss: -0.013606] [G loss: -0.063797] [d1 loss: 0.153332] [d2 loss: 0.125689]  [sq d1 d2: 0.000764]  [num0: 14.000000] [num1 50.000000]
[Epoch 58/500] [Batch 220/676] [D loss: -0.016138] [G loss: -0.063581] [d1 loss: 0.065276] [d2 loss: 0.050675]  [sq d1 d2: 0.000213]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 240/676] [D loss: -0.012208] [G loss: -0.058827] [d1 loss: 0.169239] [d2 loss: 0.142380]  [sq d1 d2: 0.000721]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 260/676] [D loss: -0.024342] [G loss: -0.035900] [d1 loss: 0.177793] [d2 loss: 0.163626]  [sq d1 d2: 0.000201]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 280/676] [D loss: -0.021985] [G loss: -0.045900] [d1 loss: 0.150130] [d2 loss: 0.132629]  [sq d1 d2: 0.000306]  [num0: 16.000000] [num1 48.000000]

[Epoch 58/500] [Batch 300/676] [D loss: -0.021433] [G loss: -0.039089] [d1 loss: 0.136491] [d2 loss: 0.136458]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 58/500] [Batch 320/676] [D loss: -0.012674] [G loss: -0.020454] [d1 loss: 0.123460] [d2 loss: 0.109836]  [sq d1 d2: 0.000186]  [num0: 18.000000] [num1 46.000000]
[Epoch 58/500] [Batch 340/676] [D loss: -0.025659] [G loss: -0.032649] [d1 loss: 0.088161] [d2 loss: 0.108765]  [sq d1 d2: 0.000425]  [num0: 19.000000] [num1 45.000000]
[Epoch 58/500] [Batch 360/676] [D loss: -0.015726] [G loss: -0.018146] [d1 loss: 0.268560] [d2 loss: 0.240180]  [sq d1 d2: 0.000805]  [num0: 17.000000] [num1 47.000000]
[Epoch 58/500] [Batch 380/676] [D loss: -0.010601] [G loss: -0.007516] [d1 loss: 0.144875] [d2 loss: 0.149688]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 58/500] [Batch 400/676] [D loss: -0.022264] [G loss: -0.013869] [d1 loss: 0.141024] [d2 loss: 0.118787]  [sq d1 d2: 0.000494]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 420/676] [D loss: -0.023043] [G loss: -0.020595] [d1 loss: 0.121320] [d2 loss: 0.113873]  [sq d1 d2: 0.000055]  [num0: 13.000000] [num1 51.000000]
[Epoch 58/500] [Batch 440/676] [D loss: -0.037978] [G loss: -0.022964] [d1 loss: 0.128272] [d2 loss: 0.119630]  [sq d1 d2: 0.000075]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 460/676] [D loss: -0.022859] [G loss: -0.028676] [d1 loss: 0.080674] [d2 loss: 0.080964]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 480/676] [D loss: -0.036315] [G loss: -0.027870] [d1 loss: 0.215450] [d2 loss: 0.221231]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 500/676] [D loss: -0.014478] [G loss: -0.049524] [d1 loss: 0.114972] [d2 loss: 0.114125]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 58/500] [Batch 520/676] [D loss: -0.023724] [G loss: -0.065229] [d1 loss: 0.140774] [d2 loss: 0.139072]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 540/676] [D loss: -0.017176] [G loss: -0.067362] [d1 loss: 0.049408] [d2 loss: 0.052642]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 58/500] [Batch 560/676] [D loss: -0.008375] [G loss: -0.058062] [d1 loss: 0.128182] [d2 loss: 0.134757]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 580/676] [D loss: -0.012177] [G loss: -0.074007] [d1 loss: 0.133476] [d2 loss: 0.129708]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 58/500] [Batch 600/676] [D loss: -0.025801] [G loss: -0.086048] [d1 loss: 0.146043] [d2 loss: 0.174996]  [sq d1 d2: 0.000838]  [num0: 18.000000] [num1 46.000000]
[Epoch 58/500] [Batch 620/676] [D loss: -0.049698] [G loss: -0.074650] [d1 loss: 0.168053] [d2 loss: 0.191197]  [sq d1 d2: 0.000536]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 640/676] [D loss: -0.024796] [G loss: -0.079896] [d1 loss: 0.191011] [d2 loss: 0.209187]  [sq d1 d2: 0.000330]  [num0: 16.000000] [num1 48.000000]
[Epoch 58/500] [Batch 660/676] [D loss: -0.041911] [G loss: -0.097464] [d1 loss: 0.118667] [d2 loss: 0.123960]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 0/676] [D loss: -0.034928] [G loss: -0.087578] [d1 loss: 0.201674] [d2 loss: 0.175571]  [sq d1 d2: 0.000681]  [num0: 19.000000] [num1 45.000000]
[Epoch 59/500] [Batch 20/676] [D loss: -0.016447] [G loss: -0.047968] [d1 loss: 0.145181] [d2 loss: 0.167635]  [sq d1 d2: 0.000504]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 40/676] [D loss: -0.003177] [G loss: -0.040059] [d1 loss: 0.112497] [d2 loss: 0.125958]  [sq d1 d2: 0.000181]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 60/676] [D loss: -0.010021] [G loss: -0.010044] [d1 loss: 0.117463] [d2 loss: 0.119080]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 80/676] [D loss: 0.001604] [G loss: 0.032469] [d1 loss: 0.157678] [d2 loss: 0.143622]  [sq d1 d2: 0.000198]  [num0: 14.000000] [num1 50.000000]
[Epoch 59/500] [Batch 100/676] [D loss: -0.009663] [G loss: 0.062513] [d1 loss: 0.119096] [d2 loss: 0.128990]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 120/676] [D loss: -0.024346] [G loss: 0.091005] [d1 loss: 0.091826] [d2 loss: 0.092525]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 59/500] [Batch 140/676] [D loss: -0.028284] [G loss: 0.106067] [d1 loss: 0.358074] [d2 loss: 0.336994]  [sq d1 d2: 0.000444]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 160/676] [D loss: -0.034200] [G loss: 0.085198] [d1 loss: 0.099855] [d2 loss: 0.109364]  [sq d1 d2: 0.000090]  [num0: 10.000000] [num1 54.000000]
[Epoch 59/500] [Batch 180/676] [D loss: -0.029972] [G loss: 0.069067] [d1 loss: 0.147032] [d2 loss: 0.162006]  [sq d1 d2: 0.000224]  [num0: 14.000000] [num1 50.000000]
[Epoch 59/500] [Batch 200/676] [D loss: -0.034729] [G loss: 0.055629] [d1 loss: 0.075983] [d2 loss: 0.079332]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 220/676] [D loss: -0.025118] [G loss: 0.012184] [d1 loss: 0.134683] [d2 loss: 0.137716]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 240/676] [D loss: -0.027876] [G loss: -0.016517] [d1 loss: 0.149715] [d2 loss: 0.146455]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 260/676] [D loss: -0.030118] [G loss: -0.085226] [d1 loss: 0.125779] [d2 loss: 0.123419]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 280/676] [D loss: -0.010486] [G loss: -0.093585] [d1 loss: 0.083447] [d2 loss: 0.067110]  [sq d1 d2: 0.000267]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 300/676] [D loss: -0.021857] [G loss: -0.142961] [d1 loss: 0.116122] [d2 loss: 0.136994]  [sq d1 d2: 0.000436]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 320/676] [D loss: -0.018690] [G loss: -0.151735] [d1 loss: 0.151249] [d2 loss: 0.170145]  [sq d1 d2: 0.000357]  [num0: 12.000000] [num1 52.000000]
[Epoch 59/500] [Batch 340/676] [D loss: -0.022788] [G loss: -0.147241] [d1 loss: 0.109621] [d2 loss: 0.118745]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 59/500] [Batch 360/676] [D loss: -0.031778] [G loss: -0.148969] [d1 loss: 0.139037] [d2 loss: 0.140508]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 59/500] [Batch 380/676] [D loss: -0.024807] [G loss: -0.147176] [d1 loss: 0.083098] [d2 loss: 0.114533]  [sq d1 d2: 0.000988]  [num0: 16.000000] [num1 48.000000]
[Epoch 59/500] [Batch 400/676] [D loss: -0.020192] [G loss: -0.138796] [d1 loss: 0.065073] [d2 loss: 0.085213]  [sq d1 d2: 0.000406]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 420/676] [D loss: -0.020608] [G loss: -0.135822] [d1 loss: 0.101937] [d2 loss: 0.108711]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 440/676] [D loss: -0.009912] [G loss: -0.137583] [d1 loss: 0.092434] [d2 loss: 0.117589]  [sq d1 d2: 0.000633]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 460/676] [D loss: -0.008925] [G loss: -0.101998] [d1 loss: 0.069397] [d2 loss: 0.074719]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 480/676] [D loss: -0.018558] [G loss: -0.101777] [d1 loss: 0.095827] [d2 loss: 0.104908]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 500/676] [D loss: -0.047673] [G loss: -0.121161] [d1 loss: 0.057281] [d2 loss: 0.058088]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 59/500] [Batch 520/676] [D loss: -0.018134] [G loss: -0.106055] [d1 loss: 0.049910] [d2 loss: 0.044368]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 540/676] [D loss: -0.013315] [G loss: -0.114971] [d1 loss: 0.130333] [d2 loss: 0.126684]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 59/500] [Batch 560/676] [D loss: -0.031644] [G loss: -0.112103] [d1 loss: 0.147906] [d2 loss: 0.150016]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 59/500] [Batch 580/676] [D loss: -0.026322] [G loss: -0.128506] [d1 loss: 0.167662] [d2 loss: 0.113081]  [sq d1 d2: 0.002979]  [num0: 14.000000] [num1 50.000000]
[Epoch 59/500] [Batch 600/676] [D loss: -0.025923] [G loss: -0.120699] [d1 loss: 0.213236] [d2 loss: 0.183901]  [sq d1 d2: 0.000861]  [num0: 18.000000] [num1 46.000000]
[Epoch 59/500] [Batch 620/676] [D loss: -0.030265] [G loss: -0.121556] [d1 loss: 0.337742] [d2 loss: 0.319473]  [sq d1 d2: 0.000334]  [num0: 17.000000] [num1 47.000000]
[Epoch 59/500] [Batch 640/676] [D loss: -0.020852] [G loss: -0.144987] [d1 loss: 0.072553] [d2 loss: 0.073467]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]

[Epoch 59/500] [Batch 660/676] [D loss: -0.012528] [G loss: -0.167696] [d1 loss: 0.055227] [d2 loss: 0.038243]  [sq d1 d2: 0.000288]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 0/676] [D loss: -0.031824] [G loss: -0.167244] [d1 loss: 0.140630] [d2 loss: 0.116906]  [sq d1 d2: 0.000563]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 20/676] [D loss: -0.024447] [G loss: -0.144649] [d1 loss: 0.069850] [d2 loss: 0.067865]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 60/500] [Batch 40/676] [D loss: -0.013053] [G loss: -0.163697] [d1 loss: 0.138557] [d2 loss: 0.147768]  [sq d1 d2: 0.000085]  [num0: 19.000000] [num1 45.000000]
[Epoch 60/500] [Batch 60/676] [D loss: -0.022638] [G loss: -0.179199] [d1 loss: 0.090462] [d2 loss: 0.093094]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 60/500] [Batch 80/676] [D loss: -0.033225] [G loss: -0.178882] [d1 loss: 0.181915] [d2 loss: 0.183743]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 60/500] [Batch 100/676] [D loss: -0.021538] [G loss: -0.151262] [d1 loss: 0.091240] [d2 loss: 0.084472]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 120/676] [D loss: -0.021448] [G loss: -0.130124] [d1 loss: 0.061573] [d2 loss: 0.058939]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 60/500] [Batch 140/676] [D loss: -0.017806] [G loss: -0.111039] [d1 loss: 0.106962] [d2 loss: 0.110413]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 60/500] [Batch 160/676] [D loss: -0.008375] [G loss: -0.092205] [d1 loss: 0.178542] [d2 loss: 0.183945]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 60/500] [Batch 180/676] [D loss: -0.019357] [G loss: -0.073102] [d1 loss: 0.071794] [d2 loss: 0.085479]  [sq d1 d2: 0.000187]  [num0: 22.000000] [num1 42.000000]
[Epoch 60/500] [Batch 200/676] [D loss: -0.019348] [G loss: -0.077994] [d1 loss: 0.092197] [d2 loss: 0.102344]  [sq d1 d2: 0.000103]  [num0: 19.000000] [num1 45.000000]
[Epoch 60/500] [Batch 220/676] [D loss: -0.003419] [G loss: -0.039039] [d1 loss: 0.134801] [d2 loss: 0.140447]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 60/500] [Batch 240/676] [D loss: -0.016585] [G loss: -0.019527] [d1 loss: 0.175325] [d2 loss: 0.164659]  [sq d1 d2: 0.000114]  [num0: 13.000000] [num1 51.000000]
[Epoch 60/500] [Batch 260/676] [D loss: -0.009211] [G loss: -0.038231] [d1 loss: 0.127573] [d2 loss: 0.128384]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 60/500] [Batch 280/676] [D loss: -0.035205] [G loss: -0.041682] [d1 loss: 0.247292] [d2 loss: 0.236970]  [sq d1 d2: 0.000107]  [num0: 13.000000] [num1 51.000000]
[Epoch 60/500] [Batch 300/676] [D loss: -0.014155] [G loss: -0.043890] [d1 loss: 0.101319] [d2 loss: 0.108126]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 320/676] [D loss: -0.039138] [G loss: -0.067254] [d1 loss: 0.159936] [d2 loss: 0.162685]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 340/676] [D loss: -0.025991] [G loss: -0.074226] [d1 loss: 0.085096] [d2 loss: 0.084621]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 60/500] [Batch 360/676] [D loss: -0.008184] [G loss: -0.105519] [d1 loss: 0.136713] [d2 loss: 0.129629]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 60/500] [Batch 380/676] [D loss: -0.005876] [G loss: -0.086322] [d1 loss: 0.097261] [d2 loss: 0.100135]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 60/500] [Batch 400/676] [D loss: 0.013809] [G loss: -0.079625] [d1 loss: 0.094809] [d2 loss: 0.095534]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 60/500] [Batch 420/676] [D loss: -0.016799] [G loss: -0.069910] [d1 loss: 0.138562] [d2 loss: 0.143042]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 60/500] [Batch 440/676] [D loss: -0.014403] [G loss: -0.068748] [d1 loss: 0.117415] [d2 loss: 0.134832]  [sq d1 d2: 0.000303]  [num0: 15.000000] [num1 49.000000]
[Epoch 60/500] [Batch 460/676] [D loss: -0.034247] [G loss: -0.071898] [d1 loss: 0.163176] [d2 loss: 0.159777]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 60/500] [Batch 480/676] [D loss: -0.049629] [G loss: -0.093501] [d1 loss: 0.195255] [d2 loss: 0.183045]  [sq d1 d2: 0.000149]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 500/676] [D loss: -0.052869] [G loss: -0.093464] [d1 loss: 0.122024] [d2 loss: 0.110719]  [sq d1 d2: 0.000128]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 520/676] [D loss: -0.015132] [G loss: -0.043750] [d1 loss: 0.179378] [d2 loss: 0.190365]  [sq d1 d2: 0.000121]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 540/676] [D loss: -0.010557] [G loss: 0.000543] [d1 loss: 0.097998] [d2 loss: 0.098992]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 60/500] [Batch 560/676] [D loss: -0.001027] [G loss: 0.008203] [d1 loss: 0.185602] [d2 loss: 0.185332]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 60/500] [Batch 580/676] [D loss: -0.015523] [G loss: 0.044245] [d1 loss: 0.126188] [d2 loss: 0.115218]  [sq d1 d2: 0.000120]  [num0: 12.000000] [num1 52.000000]
[Epoch 60/500] [Batch 600/676] [D loss: -0.003795] [G loss: 0.085667] [d1 loss: 0.071891] [d2 loss: 0.081061]  [sq d1 d2: 0.000084]  [num0: 21.000000] [num1 43.000000]
[Epoch 60/500] [Batch 620/676] [D loss: -0.001285] [G loss: 0.065674] [d1 loss: 0.082644] [d2 loss: 0.087609]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 60/500] [Batch 640/676] [D loss: -0.012531] [G loss: 0.066759] [d1 loss: 0.097559] [d2 loss: 0.112333]  [sq d1 d2: 0.000218]  [num0: 15.000000] [num1 49.000000]
[Epoch 60/500] [Batch 660/676] [D loss: -0.022680] [G loss: 0.063397] [d1 loss: 0.123985] [d2 loss: 0.129368]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 0/676] [D loss: -0.027453] [G loss: 0.061168] [d1 loss: 0.115496] [d2 loss: 0.114250]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 20/676] [D loss: -0.037509] [G loss: 0.056598] [d1 loss: 0.089341] [d2 loss: 0.083348]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 61/500] [Batch 40/676] [D loss: -0.057027] [G loss: -0.015924] [d1 loss: 0.195196] [d2 loss: 0.203105]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 60/676] [D loss: -0.036121] [G loss: -0.071924] [d1 loss: 0.119216] [d2 loss: 0.113818]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 80/676] [D loss: 0.011372] [G loss: -0.081463] [d1 loss: 0.128458] [d2 loss: 0.116918]  [sq d1 d2: 0.000133]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 100/676] [D loss: 0.025615] [G loss: -0.066688] [d1 loss: 0.089184] [d2 loss: 0.103022]  [sq d1 d2: 0.000191]  [num0: 14.000000] [num1 50.000000]
[Epoch 61/500] [Batch 120/676] [D loss: -0.012604] [G loss: -0.083307] [d1 loss: 0.056800] [d2 loss: 0.059807]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 140/676] [D loss: -0.002589] [G loss: -0.104120] [d1 loss: 0.151073] [d2 loss: 0.158635]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 61/500] [Batch 160/676] [D loss: -0.008981] [G loss: -0.115077] [d1 loss: 0.113332] [d2 loss: 0.123577]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]
[Epoch 61/500] [Batch 180/676] [D loss: -0.013059] [G loss: -0.166361] [d1 loss: 0.099178] [d2 loss: 0.104499]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 61/500] [Batch 200/676] [D loss: -0.036848] [G loss: -0.182826] [d1 loss: 0.082171] [d2 loss: 0.081077]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 61/500] [Batch 220/676] [D loss: -0.062688] [G loss: -0.172034] [d1 loss: 0.120025] [d2 loss: 0.141763]  [sq d1 d2: 0.000473]  [num0: 20.000000] [num1 44.000000]
[Epoch 61/500] [Batch 240/676] [D loss: -0.041307] [G loss: -0.232346] [d1 loss: 0.060653] [d2 loss: 0.068639]  [sq d1 d2: 0.000064]  [num0: 19.000000] [num1 45.000000]
[Epoch 61/500] [Batch 260/676] [D loss: 0.006430] [G loss: -0.224415] [d1 loss: 0.106814] [d2 loss: 0.119065]  [sq d1 d2: 0.000150]  [num0: 19.000000] [num1 45.000000]
[Epoch 61/500] [Batch 280/676] [D loss: 0.012918] [G loss: -0.229781] [d1 loss: 0.099107] [d2 loss: 0.093886]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 61/500] [Batch 300/676] [D loss: -0.011948] [G loss: -0.144461] [d1 loss: 0.060841] [d2 loss: 0.067124]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 61/500] [Batch 320/676] [D loss: 0.026297] [G loss: -0.115291] [d1 loss: 0.150661] [d2 loss: 0.143521]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]

[Epoch 61/500] [Batch 340/676] [D loss: -0.001746] [G loss: -0.086437] [d1 loss: 0.184374] [d2 loss: 0.160893]  [sq d1 d2: 0.000551]  [num0: 13.000000] [num1 51.000000]
[Epoch 61/500] [Batch 360/676] [D loss: -0.017102] [G loss: -0.052743] [d1 loss: 0.114093] [d2 loss: 0.112216]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 61/500] [Batch 380/676] [D loss: -0.047373] [G loss: -0.046112] [d1 loss: 0.149145] [d2 loss: 0.147557]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 61/500] [Batch 400/676] [D loss: -0.016245] [G loss: -0.049480] [d1 loss: 0.171181] [d2 loss: 0.172459]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 61/500] [Batch 420/676] [D loss: -0.022475] [G loss: -0.060139] [d1 loss: 0.143375] [d2 loss: 0.117194]  [sq d1 d2: 0.000685]  [num0: 15.000000] [num1 49.000000]
[Epoch 61/500] [Batch 440/676] [D loss: -0.042432] [G loss: -0.065018] [d1 loss: 0.090524] [d2 loss: 0.088810]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 61/500] [Batch 460/676] [D loss: -0.068745] [G loss: -0.054262] [d1 loss: 0.073697] [d2 loss: 0.073412]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 61/500] [Batch 480/676] [D loss: -0.045554] [G loss: -0.043461] [d1 loss: 0.099002] [d2 loss: 0.111363]  [sq d1 d2: 0.000153]  [num0: 15.000000] [num1 49.000000]
[Epoch 61/500] [Batch 500/676] [D loss: -0.004957] [G loss: -0.076410] [d1 loss: 0.106906] [d2 loss: 0.106160]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 61/500] [Batch 520/676] [D loss: -0.026460] [G loss: -0.070758] [d1 loss: 0.081598] [d2 loss: 0.075071]  [sq d1 d2: 0.000043]  [num0: 13.000000] [num1 51.000000]
[Epoch 61/500] [Batch 540/676] [D loss: 0.002551] [G loss: -0.044258] [d1 loss: 0.091935] [d2 loss: 0.085647]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 560/676] [D loss: -0.006701] [G loss: -0.022382] [d1 loss: 0.110650] [d2 loss: 0.119790]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 580/676] [D loss: -0.010443] [G loss: -0.006319] [d1 loss: 0.259791] [d2 loss: 0.252330]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 600/676] [D loss: -0.017730] [G loss: -0.011281] [d1 loss: 0.093534] [d2 loss: 0.081923]  [sq d1 d2: 0.000135]  [num0: 14.000000] [num1 50.000000]
[Epoch 61/500] [Batch 620/676] [D loss: -0.046244] [G loss: -0.025491] [d1 loss: 0.073466] [d2 loss: 0.080052]  [sq d1 d2: 0.000043]  [num0: 19.000000] [num1 45.000000]
[Epoch 61/500] [Batch 640/676] [D loss: -0.055810] [G loss: -0.051300] [d1 loss: 0.163522] [d2 loss: 0.163781]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 61/500] [Batch 660/676] [D loss: -0.062281] [G loss: -0.076965] [d1 loss: 0.117928] [d2 loss: 0.096632]  [sq d1 d2: 0.000454]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 0/676] [D loss: -0.061648] [G loss: -0.106422] [d1 loss: 0.172425] [d2 loss: 0.156718]  [sq d1 d2: 0.000247]  [num0: 14.000000] [num1 50.000000]
[Epoch 62/500] [Batch 20/676] [D loss: -0.016618] [G loss: -0.075080] [d1 loss: 0.074863] [d2 loss: 0.088366]  [sq d1 d2: 0.000182]  [num0: 13.000000] [num1 51.000000]
[Epoch 62/500] [Batch 40/676] [D loss: -0.000050] [G loss: -0.077005] [d1 loss: 0.019577] [d2 loss: 0.031329]  [sq d1 d2: 0.000138]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 60/676] [D loss: 0.001735] [G loss: -0.056307] [d1 loss: 0.194481] [d2 loss: 0.180609]  [sq d1 d2: 0.000192]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 80/676] [D loss: 0.011351] [G loss: -0.029108] [d1 loss: 0.141225] [d2 loss: 0.138360]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 62/500] [Batch 100/676] [D loss: -0.004810] [G loss: -0.032593] [d1 loss: 0.132354] [d2 loss: 0.126298]  [sq d1 d2: 0.000037]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 120/676] [D loss: -0.017980] [G loss: -0.008413] [d1 loss: 0.132551] [d2 loss: 0.158280]  [sq d1 d2: 0.000662]  [num0: 11.000000] [num1 53.000000]
[Epoch 62/500] [Batch 140/676] [D loss: -0.024612] [G loss: -0.028130] [d1 loss: 0.117403] [d2 loss: 0.133411]  [sq d1 d2: 0.000256]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 160/676] [D loss: -0.059272] [G loss: -0.036000] [d1 loss: 0.047447] [d2 loss: 0.053706]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 62/500] [Batch 180/676] [D loss: -0.034774] [G loss: -0.049994] [d1 loss: 0.184627] [d2 loss: 0.156426]  [sq d1 d2: 0.000795]  [num0: 18.000000] [num1 46.000000]
[Epoch 62/500] [Batch 200/676] [D loss: -0.047965] [G loss: -0.099562] [d1 loss: 0.103478] [d2 loss: 0.113528]  [sq d1 d2: 0.000101]  [num0: 13.000000] [num1 51.000000]
[Epoch 62/500] [Batch 220/676] [D loss: -0.069609] [G loss: -0.105295] [d1 loss: 0.066574] [d2 loss: 0.074029]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 240/676] [D loss: -0.033275] [G loss: -0.107397] [d1 loss: 0.067305] [d2 loss: 0.077864]  [sq d1 d2: 0.000111]  [num0: 13.000000] [num1 51.000000]
[Epoch 62/500] [Batch 260/676] [D loss: -0.001357] [G loss: -0.115755] [d1 loss: 0.131616] [d2 loss: 0.132112]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 280/676] [D loss: 0.011453] [G loss: -0.100287] [d1 loss: 0.085243] [d2 loss: 0.077919]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 300/676] [D loss: 0.010748] [G loss: -0.056683] [d1 loss: 0.054698] [d2 loss: 0.060705]  [sq d1 d2: 0.000036]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 320/676] [D loss: -0.010097] [G loss: -0.041304] [d1 loss: 0.112301] [d2 loss: 0.108721]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 340/676] [D loss: -0.025515] [G loss: -0.041011] [d1 loss: 0.094124] [d2 loss: 0.106762]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 360/676] [D loss: -0.028596] [G loss: -0.048582] [d1 loss: 0.141257] [d2 loss: 0.119507]  [sq d1 d2: 0.000473]  [num0: 18.000000] [num1 46.000000]
[Epoch 62/500] [Batch 380/676] [D loss: -0.051672] [G loss: -0.047778] [d1 loss: 0.170275] [d2 loss: 0.158651]  [sq d1 d2: 0.000135]  [num0: 20.000000] [num1 44.000000]
[Epoch 62/500] [Batch 400/676] [D loss: -0.069524] [G loss: -0.068799] [d1 loss: 0.043114] [d2 loss: 0.040094]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 420/676] [D loss: -0.026502] [G loss: -0.074010] [d1 loss: 0.093239] [d2 loss: 0.092213]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 62/500] [Batch 440/676] [D loss: -0.026680] [G loss: -0.088597] [d1 loss: 0.104460] [d2 loss: 0.107614]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 62/500] [Batch 460/676] [D loss: -0.013594] [G loss: -0.072535] [d1 loss: 0.101570] [d2 loss: 0.101745]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 62/500] [Batch 480/676] [D loss: 0.009876] [G loss: -0.066886] [d1 loss: 0.104095] [d2 loss: 0.086771]  [sq d1 d2: 0.000300]  [num0: 16.000000] [num1 48.000000]
[Epoch 62/500] [Batch 500/676] [D loss: -0.005348] [G loss: -0.046211] [d1 loss: 0.186049] [d2 loss: 0.188217]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 520/676] [D loss: 0.001224] [G loss: -0.051847] [d1 loss: 0.160032] [d2 loss: 0.156705]  [sq d1 d2: 0.000011]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 540/676] [D loss: -0.019979] [G loss: -0.038065] [d1 loss: 0.078506] [d2 loss: 0.058983]  [sq d1 d2: 0.000381]  [num0: 13.000000] [num1 51.000000]
[Epoch 62/500] [Batch 560/676] [D loss: -0.060834] [G loss: -0.017189] [d1 loss: 0.106556] [d2 loss: 0.092391]  [sq d1 d2: 0.000201]  [num0: 12.000000] [num1 52.000000]
[Epoch 62/500] [Batch 580/676] [D loss: -0.099820] [G loss: 0.028100] [d1 loss: 0.122824] [d2 loss: 0.125791]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 62/500] [Batch 600/676] [D loss: -0.087238] [G loss: -0.048162] [d1 loss: 0.072926] [d2 loss: 0.066311]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 62/500] [Batch 620/676] [D loss: -0.041021] [G loss: -0.103174] [d1 loss: 0.169755] [d2 loss: 0.176400]  [sq d1 d2: 0.000044]  [num0: 19.000000] [num1 45.000000]
[Epoch 62/500] [Batch 640/676] [D loss: 0.014589] [G loss: -0.153715] [d1 loss: 0.077588] [d2 loss: 0.081047]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 62/500] [Batch 660/676] [D loss: 0.007587] [G loss: -0.176027] [d1 loss: 0.116947] [d2 loss: 0.099129]  [sq d1 d2: 0.000317]  [num0: 19.000000] [num1 45.000000]
[Epoch 63/500] [Batch 0/676] [D loss: 0.040538] [G loss: -0.143322] [d1 loss: 0.083539] [d2 loss: 0.080895]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]

[Epoch 63/500] [Batch 20/676] [D loss: 0.010815] [G loss: -0.095730] [d1 loss: 0.112162] [d2 loss: 0.110321]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 63/500] [Batch 40/676] [D loss: -0.005770] [G loss: -0.056139] [d1 loss: 0.049164] [d2 loss: 0.058182]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 60/676] [D loss: -0.020363] [G loss: -0.035565] [d1 loss: 0.174717] [d2 loss: 0.156892]  [sq d1 d2: 0.000318]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 80/676] [D loss: -0.073953] [G loss: 0.012810] [d1 loss: 0.050059] [d2 loss: 0.051203]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 100/676] [D loss: -0.095429] [G loss: 0.043339] [d1 loss: 0.056634] [d2 loss: 0.066044]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 63/500] [Batch 120/676] [D loss: -0.076929] [G loss: 0.026135] [d1 loss: 0.152087] [d2 loss: 0.141467]  [sq d1 d2: 0.000113]  [num0: 16.000000] [num1 48.000000]
[Epoch 63/500] [Batch 140/676] [D loss: -0.056423] [G loss: 0.050997] [d1 loss: 0.150592] [d2 loss: 0.147141]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 160/676] [D loss: -0.027077] [G loss: 0.032996] [d1 loss: 0.127666] [d2 loss: 0.125088]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 180/676] [D loss: 0.008868] [G loss: -0.006049] [d1 loss: 0.124005] [d2 loss: 0.121475]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 200/676] [D loss: 0.045732] [G loss: -0.021048] [d1 loss: 0.197460] [d2 loss: 0.209296]  [sq d1 d2: 0.000140]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 220/676] [D loss: 0.002354] [G loss: -0.037281] [d1 loss: 0.073765] [d2 loss: 0.082013]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 63/500] [Batch 240/676] [D loss: 0.009669] [G loss: -0.046740] [d1 loss: 0.134326] [d2 loss: 0.154745]  [sq d1 d2: 0.000417]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 260/676] [D loss: -0.023977] [G loss: -0.001604] [d1 loss: 0.127472] [d2 loss: 0.147972]  [sq d1 d2: 0.000420]  [num0: 12.000000] [num1 52.000000]
[Epoch 63/500] [Batch 280/676] [D loss: -0.067976] [G loss: 0.056827] [d1 loss: 0.180523] [d2 loss: 0.161581]  [sq d1 d2: 0.000359]  [num0: 17.000000] [num1 47.000000]
[Epoch 63/500] [Batch 300/676] [D loss: -0.107621] [G loss: 0.083726] [d1 loss: 0.170196] [d2 loss: 0.160979]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 320/676] [D loss: -0.152822] [G loss: 0.040395] [d1 loss: 0.073886] [d2 loss: 0.071808]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 340/676] [D loss: -0.022077] [G loss: -0.037999] [d1 loss: 0.044454] [d2 loss: 0.045211]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 360/676] [D loss: -0.038868] [G loss: -0.136029] [d1 loss: 0.102913] [d2 loss: 0.118064]  [sq d1 d2: 0.000230]  [num0: 13.000000] [num1 51.000000]
[Epoch 63/500] [Batch 380/676] [D loss: 0.006676] [G loss: -0.156396] [d1 loss: 0.060579] [d2 loss: 0.057785]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 400/676] [D loss: 0.029302] [G loss: -0.145581] [d1 loss: 0.145407] [d2 loss: 0.148112]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 63/500] [Batch 420/676] [D loss: 0.009364] [G loss: -0.092318] [d1 loss: 0.059657] [d2 loss: 0.051617]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 440/676] [D loss: -0.005114] [G loss: -0.045472] [d1 loss: 0.126232] [d2 loss: 0.128734]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 63/500] [Batch 460/676] [D loss: -0.034177] [G loss: 0.003502] [d1 loss: 0.111250] [d2 loss: 0.108446]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 63/500] [Batch 480/676] [D loss: -0.097403] [G loss: 0.096500] [d1 loss: 0.038154] [d2 loss: 0.032959]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 500/676] [D loss: -0.092922] [G loss: 0.148994] [d1 loss: 0.117977] [d2 loss: 0.095476]  [sq d1 d2: 0.000506]  [num0: 16.000000] [num1 48.000000]
[Epoch 63/500] [Batch 520/676] [D loss: -0.097109] [G loss: 0.148256] [d1 loss: 0.073581] [d2 loss: 0.073847]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 63/500] [Batch 540/676] [D loss: -0.042596] [G loss: 0.110297] [d1 loss: 0.133605] [d2 loss: 0.117193]  [sq d1 d2: 0.000269]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 560/676] [D loss: -0.002897] [G loss: 0.091090] [d1 loss: 0.067251] [d2 loss: 0.065843]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 63/500] [Batch 580/676] [D loss: 0.033428] [G loss: 0.070585] [d1 loss: 0.132851] [d2 loss: 0.112429]  [sq d1 d2: 0.000417]  [num0: 18.000000] [num1 46.000000]
[Epoch 63/500] [Batch 600/676] [D loss: 0.038649] [G loss: 0.054639] [d1 loss: 0.050263] [d2 loss: 0.040551]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 63/500] [Batch 620/676] [D loss: 0.016927] [G loss: 0.011191] [d1 loss: 0.084425] [d2 loss: 0.078763]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 63/500] [Batch 640/676] [D loss: 0.003098] [G loss: 0.006631] [d1 loss: 0.149738] [d2 loss: 0.130832]  [sq d1 d2: 0.000357]  [num0: 15.000000] [num1 49.000000]
[Epoch 63/500] [Batch 660/676] [D loss: -0.023098] [G loss: 0.007977] [d1 loss: 0.141777] [d2 loss: 0.153373]  [sq d1 d2: 0.000134]  [num0: 18.000000] [num1 46.000000]
[Epoch 64/500] [Batch 0/676] [D loss: -0.038302] [G loss: 0.054308] [d1 loss: 0.133101] [d2 loss: 0.124690]  [sq d1 d2: 0.000071]  [num0: 18.000000] [num1 46.000000]
[Epoch 64/500] [Batch 20/676] [D loss: -0.111242] [G loss: 0.140346] [d1 loss: 0.142414] [d2 loss: 0.105972]  [sq d1 d2: 0.001328]  [num0: 17.000000] [num1 47.000000]
[Epoch 64/500] [Batch 40/676] [D loss: -0.187348] [G loss: 0.224966] [d1 loss: 0.115759] [d2 loss: 0.101869]  [sq d1 d2: 0.000193]  [num0: 13.000000] [num1 51.000000]
[Epoch 64/500] [Batch 60/676] [D loss: -0.052378] [G loss: 0.184196] [d1 loss: 0.087203] [d2 loss: 0.113537]  [sq d1 d2: 0.000693]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 80/676] [D loss: -0.060012] [G loss: 0.110754] [d1 loss: 0.136717] [d2 loss: 0.134087]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 100/676] [D loss: 0.009918] [G loss: -0.036638] [d1 loss: 0.140072] [d2 loss: 0.122520]  [sq d1 d2: 0.000308]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 120/676] [D loss: 0.063739] [G loss: -0.096380] [d1 loss: 0.099517] [d2 loss: 0.087200]  [sq d1 d2: 0.000152]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 140/676] [D loss: 0.025216] [G loss: -0.068127] [d1 loss: 0.152388] [d2 loss: 0.167061]  [sq d1 d2: 0.000215]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 160/676] [D loss: 0.010654] [G loss: -0.051222] [d1 loss: 0.099035] [d2 loss: 0.101375]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 64/500] [Batch 180/676] [D loss: -0.009149] [G loss: -0.050894] [d1 loss: 0.149574] [d2 loss: 0.160028]  [sq d1 d2: 0.000109]  [num0: 15.000000] [num1 49.000000]
[Epoch 64/500] [Batch 200/676] [D loss: -0.042126] [G loss: -0.029641] [d1 loss: 0.084389] [d2 loss: 0.087996]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 220/676] [D loss: -0.090752] [G loss: 0.065125] [d1 loss: 0.069797] [d2 loss: 0.076325]  [sq d1 d2: 0.000043]  [num0: 22.000000] [num1 42.000000]
[Epoch 64/500] [Batch 240/676] [D loss: -0.111922] [G loss: 0.132802] [d1 loss: 0.088991] [d2 loss: 0.114470]  [sq d1 d2: 0.000649]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 260/676] [D loss: -0.096667] [G loss: 0.147968] [d1 loss: 0.062332] [d2 loss: 0.070831]  [sq d1 d2: 0.000072]  [num0: 17.000000] [num1 47.000000]
[Epoch 64/500] [Batch 280/676] [D loss: -0.116997] [G loss: 0.101039] [d1 loss: 0.111745] [d2 loss: 0.106926]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 300/676] [D loss: -0.027987] [G loss: 0.029635] [d1 loss: 0.065984] [d2 loss: 0.063459]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 320/676] [D loss: 0.034474] [G loss: -0.036178] [d1 loss: 0.070228] [d2 loss: 0.073785]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 64/500] [Batch 340/676] [D loss: 0.058880] [G loss: -0.119866] [d1 loss: 0.051437] [d2 loss: 0.060714]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 360/676] [D loss: 0.032849] [G loss: -0.116195] [d1 loss: 0.158343] [d2 loss: 0.115382]  [sq d1 d2: 0.001846]  [num0: 18.000000] [num1 46.000000]

[Epoch 64/500] [Batch 380/676] [D loss: 0.017021] [G loss: -0.113775] [d1 loss: 0.120399] [d2 loss: 0.116510]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 400/676] [D loss: -0.008045] [G loss: -0.115959] [d1 loss: 0.133218] [d2 loss: 0.115071]  [sq d1 d2: 0.000329]  [num0: 15.000000] [num1 49.000000]
[Epoch 64/500] [Batch 420/676] [D loss: -0.029572] [G loss: -0.129433] [d1 loss: 0.060165] [d2 loss: 0.070994]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 64/500] [Batch 440/676] [D loss: -0.065734] [G loss: -0.165127] [d1 loss: 0.127571] [d2 loss: 0.117321]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 460/676] [D loss: -0.076063] [G loss: -0.197447] [d1 loss: 0.078043] [d2 loss: 0.075535]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 480/676] [D loss: -0.143809] [G loss: -0.189608] [d1 loss: 0.129178] [d2 loss: 0.132906]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 64/500] [Batch 500/676] [D loss: -0.061338] [G loss: -0.088773] [d1 loss: 0.168039] [d2 loss: 0.191811]  [sq d1 d2: 0.000565]  [num0: 13.000000] [num1 51.000000]
[Epoch 64/500] [Batch 520/676] [D loss: -0.016483] [G loss: -0.109623] [d1 loss: 0.220517] [d2 loss: 0.198735]  [sq d1 d2: 0.000474]  [num0: 17.000000] [num1 47.000000]
[Epoch 64/500] [Batch 540/676] [D loss: 0.056792] [G loss: -0.158333] [d1 loss: 0.078596] [d2 loss: 0.071980]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 64/500] [Batch 560/676] [D loss: 0.042655] [G loss: -0.135506] [d1 loss: 0.049991] [d2 loss: 0.064204]  [sq d1 d2: 0.000202]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 580/676] [D loss: 0.043636] [G loss: -0.060650] [d1 loss: 0.048984] [d2 loss: 0.050513]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 64/500] [Batch 600/676] [D loss: 0.016784] [G loss: -0.040894] [d1 loss: 0.064327] [d2 loss: 0.063717]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 64/500] [Batch 620/676] [D loss: 0.002919] [G loss: -0.041609] [d1 loss: 0.077357] [d2 loss: 0.078212]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 64/500] [Batch 640/676] [D loss: -0.015538] [G loss: -0.042450] [d1 loss: 0.115176] [d2 loss: 0.104440]  [sq d1 d2: 0.000115]  [num0: 14.000000] [num1 50.000000]
[Epoch 64/500] [Batch 660/676] [D loss: -0.045097] [G loss: -0.001651] [d1 loss: 0.065141] [d2 loss: 0.065709]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 65/500] [Batch 0/676] [D loss: -0.046746] [G loss: 0.043559] [d1 loss: 0.108077] [d2 loss: 0.115516]  [sq d1 d2: 0.000055]  [num0: 19.000000] [num1 45.000000]
[Epoch 65/500] [Batch 20/676] [D loss: -0.081961] [G loss: 0.053699] [d1 loss: 0.071653] [d2 loss: 0.074617]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 65/500] [Batch 40/676] [D loss: -0.178063] [G loss: 0.083638] [d1 loss: 0.038469] [d2 loss: 0.038541]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 65/500] [Batch 60/676] [D loss: -0.075357] [G loss: 0.081195] [d1 loss: 0.056903] [d2 loss: 0.071545]  [sq d1 d2: 0.000214]  [num0: 17.000000] [num1 47.000000]
[Epoch 65/500] [Batch 80/676] [D loss: -0.094733] [G loss: 0.018997] [d1 loss: 0.099885] [d2 loss: 0.132773]  [sq d1 d2: 0.001082]  [num0: 17.000000] [num1 47.000000]
[Epoch 65/500] [Batch 100/676] [D loss: -0.050975] [G loss: 0.032353] [d1 loss: 0.050473] [d2 loss: 0.061488]  [sq d1 d2: 0.000121]  [num0: 12.000000] [num1 52.000000]
[Epoch 65/500] [Batch 120/676] [D loss: -0.005308] [G loss: 0.032613] [d1 loss: 0.097789] [d2 loss: 0.087663]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 65/500] [Batch 140/676] [D loss: 0.052798] [G loss: 0.037815] [d1 loss: 0.108832] [d2 loss: 0.129409]  [sq d1 d2: 0.000423]  [num0: 12.000000] [num1 52.000000]
[Epoch 65/500] [Batch 160/676] [D loss: 0.021583] [G loss: 0.032866] [d1 loss: 0.112578] [d2 loss: 0.096577]  [sq d1 d2: 0.000256]  [num0: 13.000000] [num1 51.000000]
[Epoch 65/500] [Batch 180/676] [D loss: 0.022516] [G loss: 0.047867] [d1 loss: 0.057408] [d2 loss: 0.047204]  [sq d1 d2: 0.000104]  [num0: 19.000000] [num1 45.000000]
[Epoch 65/500] [Batch 200/676] [D loss: 0.002429] [G loss: 0.053094] [d1 loss: 0.098810] [d2 loss: 0.079525]  [sq d1 d2: 0.000372]  [num0: 18.000000] [num1 46.000000]
[Epoch 65/500] [Batch 220/676] [D loss: -0.011923] [G loss: 0.059216] [d1 loss: 0.115714] [d2 loss: 0.141217]  [sq d1 d2: 0.000650]  [num0: 11.000000] [num1 53.000000]
[Epoch 65/500] [Batch 240/676] [D loss: -0.027566] [G loss: 0.093792] [d1 loss: 0.102943] [d2 loss: 0.089260]  [sq d1 d2: 0.000187]  [num0: 18.000000] [num1 46.000000]
[Epoch 65/500] [Batch 260/676] [D loss: -0.055757] [G loss: 0.093105] [d1 loss: 0.098153] [d2 loss: 0.132818]  [sq d1 d2: 0.001202]  [num0: 15.000000] [num1 49.000000]
[Epoch 65/500] [Batch 280/676] [D loss: -0.111201] [G loss: 0.186353] [d1 loss: 0.034662] [d2 loss: 0.036936]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 65/500] [Batch 300/676] [D loss: -0.154512] [G loss: 0.225100] [d1 loss: 0.120137] [d2 loss: 0.140730]  [sq d1 d2: 0.000424]  [num0: 19.000000] [num1 45.000000]
[Epoch 65/500] [Batch 320/676] [D loss: -0.010727] [G loss: 0.217493] [d1 loss: 0.107663] [d2 loss: 0.097869]  [sq d1 d2: 0.000096]  [num0: 18.000000] [num1 46.000000]
[Epoch 65/500] [Batch 340/676] [D loss: -0.073879] [G loss: 0.093615] [d1 loss: 0.092899] [d2 loss: 0.086943]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 65/500] [Batch 360/676] [D loss: 0.024694] [G loss: -0.001088] [d1 loss: 0.049333] [d2 loss: 0.050290]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 65/500] [Batch 380/676] [D loss: 0.018663] [G loss: -0.036924] [d1 loss: 0.079081] [d2 loss: 0.081530]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 65/500] [Batch 400/676] [D loss: 0.027406] [G loss: -0.015809] [d1 loss: 0.171374] [d2 loss: 0.164210]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 65/500] [Batch 420/676] [D loss: 0.019755] [G loss: 0.004966] [d1 loss: 0.071622] [d2 loss: 0.080711]  [sq d1 d2: 0.000083]  [num0: 13.000000] [num1 51.000000]
[Epoch 65/500] [Batch 440/676] [D loss: 0.002255] [G loss: 0.032818] [d1 loss: 0.054723] [d2 loss: 0.076789]  [sq d1 d2: 0.000487]  [num0: 11.000000] [num1 53.000000]
[Epoch 65/500] [Batch 460/676] [D loss: -0.001080] [G loss: 0.066358] [d1 loss: 0.112619] [d2 loss: 0.104432]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 65/500] [Batch 480/676] [D loss: -0.017632] [G loss: 0.123422] [d1 loss: 0.054058] [d2 loss: 0.062928]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 65/500] [Batch 500/676] [D loss: -0.047683] [G loss: 0.225528] [d1 loss: 0.071398] [d2 loss: 0.065971]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 65/500] [Batch 520/676] [D loss: -0.107790] [G loss: 0.269126] [d1 loss: 0.085229] [d2 loss: 0.083838]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 65/500] [Batch 540/676] [D loss: -0.077078] [G loss: 0.252912] [d1 loss: 0.075192] [d2 loss: 0.075881]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 65/500] [Batch 560/676] [D loss: -0.104527] [G loss: 0.164318] [d1 loss: 0.091074] [d2 loss: 0.095721]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 65/500] [Batch 580/676] [D loss: -0.027792] [G loss: 0.142129] [d1 loss: 0.078361] [d2 loss: 0.095698]  [sq d1 d2: 0.000301]  [num0: 14.000000] [num1 50.000000]
[Epoch 65/500] [Batch 600/676] [D loss: 0.023044] [G loss: 0.105043] [d1 loss: 0.038160] [d2 loss: 0.046142]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 65/500] [Batch 620/676] [D loss: 0.017323] [G loss: 0.069136] [d1 loss: 0.142748] [d2 loss: 0.135614]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 65/500] [Batch 640/676] [D loss: 0.057524] [G loss: 0.009589] [d1 loss: 0.094477] [d2 loss: 0.095974]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 65/500] [Batch 660/676] [D loss: 0.032191] [G loss: -0.054139] [d1 loss: 0.147633] [d2 loss: 0.181748]  [sq d1 d2: 0.001164]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 0/676] [D loss: 0.024396] [G loss: -0.086032] [d1 loss: 0.183037] [d2 loss: 0.154907]  [sq d1 d2: 0.000791]  [num0: 17.000000] [num1 47.000000]
[Epoch 66/500] [Batch 20/676] [D loss: 0.010103] [G loss: -0.109888] [d1 loss: 0.112650] [d2 loss: 0.104567]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 66/500] [Batch 40/676] [D loss: -0.005122] [G loss: -0.131004] [d1 loss: 0.042716] [d2 loss: 0.040067]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]

[Epoch 66/500] [Batch 60/676] [D loss: -0.017004] [G loss: -0.168796] [d1 loss: 0.112841] [d2 loss: 0.094191]  [sq d1 d2: 0.000348]  [num0: 14.000000] [num1 50.000000]
[Epoch 66/500] [Batch 80/676] [D loss: -0.052431] [G loss: -0.211876] [d1 loss: 0.105033] [d2 loss: 0.094894]  [sq d1 d2: 0.000103]  [num0: 13.000000] [num1 51.000000]
[Epoch 66/500] [Batch 100/676] [D loss: -0.076167] [G loss: -0.230541] [d1 loss: 0.077474] [d2 loss: 0.073042]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 66/500] [Batch 120/676] [D loss: -0.105621] [G loss: -0.251527] [d1 loss: 0.072222] [d2 loss: 0.061096]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 66/500] [Batch 140/676] [D loss: -0.116643] [G loss: -0.218817] [d1 loss: 0.051078] [d2 loss: 0.049203]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 66/500] [Batch 160/676] [D loss: -0.127564] [G loss: -0.212060] [d1 loss: 0.166395] [d2 loss: 0.155769]  [sq d1 d2: 0.000113]  [num0: 19.000000] [num1 45.000000]
[Epoch 66/500] [Batch 180/676] [D loss: -0.040985] [G loss: -0.300695] [d1 loss: 0.101323] [d2 loss: 0.097312]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 200/676] [D loss: 0.040021] [G loss: -0.355663] [d1 loss: 0.163470] [d2 loss: 0.172894]  [sq d1 d2: 0.000089]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 220/676] [D loss: 0.054035] [G loss: -0.283335] [d1 loss: 0.058997] [d2 loss: 0.059480]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 66/500] [Batch 240/676] [D loss: 0.013374] [G loss: -0.215011] [d1 loss: 0.127294] [d2 loss: 0.130511]  [sq d1 d2: 0.000010]  [num0: 8.000000] [num1 56.000000]
[Epoch 66/500] [Batch 260/676] [D loss: 0.025737] [G loss: -0.151076] [d1 loss: 0.090711] [d2 loss: 0.091929]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 66/500] [Batch 280/676] [D loss: 0.005494] [G loss: -0.088949] [d1 loss: 0.094529] [d2 loss: 0.102906]  [sq d1 d2: 0.000070]  [num0: 19.000000] [num1 45.000000]
[Epoch 66/500] [Batch 300/676] [D loss: -0.005750] [G loss: -0.029450] [d1 loss: 0.065498] [d2 loss: 0.081602]  [sq d1 d2: 0.000259]  [num0: 13.000000] [num1 51.000000]
[Epoch 66/500] [Batch 320/676] [D loss: -0.032207] [G loss: 0.053223] [d1 loss: 0.126523] [d2 loss: 0.126524]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 66/500] [Batch 340/676] [D loss: -0.057196] [G loss: 0.127588] [d1 loss: 0.107761] [d2 loss: 0.112988]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 66/500] [Batch 360/676] [D loss: -0.134657] [G loss: 0.290482] [d1 loss: 0.118489] [d2 loss: 0.121999]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 66/500] [Batch 380/676] [D loss: -0.126613] [G loss: 0.295092] [d1 loss: 0.126144] [d2 loss: 0.109782]  [sq d1 d2: 0.000268]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 400/676] [D loss: -0.062888] [G loss: 0.347306] [d1 loss: 0.132805] [d2 loss: 0.147279]  [sq d1 d2: 0.000209]  [num0: 14.000000] [num1 50.000000]
[Epoch 66/500] [Batch 420/676] [D loss: -0.016395] [G loss: 0.330662] [d1 loss: 0.106251] [d2 loss: 0.097265]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 66/500] [Batch 440/676] [D loss: 0.035563] [G loss: 0.295219] [d1 loss: 0.080962] [d2 loss: 0.070152]  [sq d1 d2: 0.000117]  [num0: 13.000000] [num1 51.000000]
[Epoch 66/500] [Batch 460/676] [D loss: -0.011072] [G loss: 0.275884] [d1 loss: 0.079414] [d2 loss: 0.087422]  [sq d1 d2: 0.000064]  [num0: 19.000000] [num1 45.000000]
[Epoch 66/500] [Batch 480/676] [D loss: 0.044388] [G loss: 0.267098] [d1 loss: 0.134385] [d2 loss: 0.132244]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 66/500] [Batch 500/676] [D loss: 0.029992] [G loss: 0.216619] [d1 loss: 0.012106] [d2 loss: 0.013904]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 520/676] [D loss: 0.017503] [G loss: 0.144103] [d1 loss: 0.124887] [d2 loss: 0.132503]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 66/500] [Batch 540/676] [D loss: 0.002795] [G loss: 0.103310] [d1 loss: 0.087885] [d2 loss: 0.061313]  [sq d1 d2: 0.000706]  [num0: 14.000000] [num1 50.000000]
[Epoch 66/500] [Batch 560/676] [D loss: -0.007733] [G loss: 0.093340] [d1 loss: 0.114078] [d2 loss: 0.112516]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 580/676] [D loss: -0.024024] [G loss: 0.082081] [d1 loss: 0.163370] [d2 loss: 0.168576]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 66/500] [Batch 600/676] [D loss: -0.042036] [G loss: 0.075955] [d1 loss: 0.121525] [d2 loss: 0.098869]  [sq d1 d2: 0.000513]  [num0: 14.000000] [num1 50.000000]
[Epoch 66/500] [Batch 620/676] [D loss: -0.044125] [G loss: 0.086294] [d1 loss: 0.089461] [d2 loss: 0.093227]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 66/500] [Batch 640/676] [D loss: -0.104377] [G loss: 0.196241] [d1 loss: 0.071341] [d2 loss: 0.072938]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 66/500] [Batch 660/676] [D loss: -0.149553] [G loss: 0.237397] [d1 loss: 0.047929] [d2 loss: 0.066466]  [sq d1 d2: 0.000344]  [num0: 18.000000] [num1 46.000000]
[Epoch 67/500] [Batch 0/676] [D loss: -0.077858] [G loss: 0.209277] [d1 loss: 0.070423] [d2 loss: 0.078039]  [sq d1 d2: 0.000058]  [num0: 19.000000] [num1 45.000000]
[Epoch 67/500] [Batch 20/676] [D loss: -0.084723] [G loss: 0.197835] [d1 loss: 0.110555] [d2 loss: 0.086385]  [sq d1 d2: 0.000584]  [num0: 18.000000] [num1 46.000000]
[Epoch 67/500] [Batch 40/676] [D loss: -0.059145] [G loss: 0.180819] [d1 loss: 0.076356] [d2 loss: 0.059517]  [sq d1 d2: 0.000284]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 60/676] [D loss: 0.036322] [G loss: 0.006275] [d1 loss: 0.089067] [d2 loss: 0.087936]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 80/676] [D loss: 0.030637] [G loss: -0.092384] [d1 loss: 0.074693] [d2 loss: 0.081720]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 67/500] [Batch 100/676] [D loss: 0.003132] [G loss: -0.123283] [d1 loss: 0.092380] [d2 loss: 0.095367]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 120/676] [D loss: 0.012441] [G loss: -0.113877] [d1 loss: 0.122558] [d2 loss: 0.123856]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 67/500] [Batch 140/676] [D loss: 0.001034] [G loss: -0.100872] [d1 loss: 0.063694] [d2 loss: 0.057563]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 67/500] [Batch 160/676] [D loss: -0.006781] [G loss: -0.107755] [d1 loss: 0.078766] [d2 loss: 0.075947]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 67/500] [Batch 180/676] [D loss: -0.016788] [G loss: -0.127875] [d1 loss: 0.119890] [d2 loss: 0.116308]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 67/500] [Batch 200/676] [D loss: -0.037730] [G loss: -0.133147] [d1 loss: 0.206639] [d2 loss: 0.213700]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 67/500] [Batch 220/676] [D loss: -0.023530] [G loss: -0.137818] [d1 loss: 0.091596] [d2 loss: 0.122477]  [sq d1 d2: 0.000954]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 240/676] [D loss: -0.035265] [G loss: -0.134934] [d1 loss: 0.077556] [d2 loss: 0.086737]  [sq d1 d2: 0.000084]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 260/676] [D loss: -0.037662] [G loss: -0.138677] [d1 loss: 0.120477] [d2 loss: 0.096097]  [sq d1 d2: 0.000594]  [num0: 14.000000] [num1 50.000000]
[Epoch 67/500] [Batch 280/676] [D loss: -0.042339] [G loss: -0.165831] [d1 loss: 0.106508] [d2 loss: 0.085092]  [sq d1 d2: 0.000459]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 300/676] [D loss: -0.028475] [G loss: -0.198802] [d1 loss: 0.060709] [d2 loss: 0.057502]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 67/500] [Batch 320/676] [D loss: -0.013091] [G loss: -0.211678] [d1 loss: 0.066996] [d2 loss: 0.081633]  [sq d1 d2: 0.000214]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 340/676] [D loss: -0.010306] [G loss: -0.239328] [d1 loss: 0.080045] [d2 loss: 0.070650]  [sq d1 d2: 0.000088]  [num0: 9.000000] [num1 55.000000]

[Epoch 67/500] [Batch 360/676] [D loss: 0.011290] [G loss: -0.249304] [d1 loss: 0.081480] [d2 loss: 0.077351]  [sq d1 d2: 0.000017]  [num0: 20.000000] [num1 44.000000]
[Epoch 67/500] [Batch 380/676] [D loss: 0.012681] [G loss: -0.222402] [d1 loss: 0.070859] [d2 loss: 0.060656]  [sq d1 d2: 0.000104]  [num0: 9.000000] [num1 55.000000]
[Epoch 67/500] [Batch 400/676] [D loss: 0.018860] [G loss: -0.178818] [d1 loss: 0.216200] [d2 loss: 0.194650]  [sq d1 d2: 0.000464]  [num0: 16.000000] [num1 48.000000]
[Epoch 67/500] [Batch 420/676] [D loss: 0.004197] [G loss: -0.117252] [d1 loss: 0.076660] [d2 loss: 0.072413]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 440/676] [D loss: 0.004276] [G loss: -0.070509] [d1 loss: 0.083782] [d2 loss: 0.077616]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 460/676] [D loss: -0.005468] [G loss: -0.045722] [d1 loss: 0.066236] [d2 loss: 0.068338]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 67/500] [Batch 480/676] [D loss: -0.018546] [G loss: -0.008350] [d1 loss: 0.024409] [d2 loss: 0.022799]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 500/676] [D loss: -0.012136] [G loss: 0.022639] [d1 loss: 0.120196] [d2 loss: 0.107481]  [sq d1 d2: 0.000162]  [num0: 16.000000] [num1 48.000000]
[Epoch 67/500] [Batch 520/676] [D loss: -0.024463] [G loss: 0.028577] [d1 loss: 0.087900] [d2 loss: 0.097852]  [sq d1 d2: 0.000099]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 540/676] [D loss: -0.019370] [G loss: 0.054689] [d1 loss: 0.031182] [d2 loss: 0.028913]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 67/500] [Batch 560/676] [D loss: -0.009635] [G loss: 0.029878] [d1 loss: 0.080281] [d2 loss: 0.073602]  [sq d1 d2: 0.000045]  [num0: 17.000000] [num1 47.000000]
[Epoch 67/500] [Batch 580/676] [D loss: -0.013660] [G loss: 0.078156] [d1 loss: 0.047847] [d2 loss: 0.046050]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 67/500] [Batch 600/676] [D loss: -0.014904] [G loss: 0.057218] [d1 loss: 0.126285] [d2 loss: 0.154819]  [sq d1 d2: 0.000814]  [num0: 12.000000] [num1 52.000000]
[Epoch 67/500] [Batch 620/676] [D loss: -0.012182] [G loss: 0.023332] [d1 loss: 0.126271] [d2 loss: 0.109073]  [sq d1 d2: 0.000296]  [num0: 13.000000] [num1 51.000000]
[Epoch 67/500] [Batch 640/676] [D loss: 0.010172] [G loss: 0.068294] [d1 loss: 0.087789] [d2 loss: 0.072969]  [sq d1 d2: 0.000220]  [num0: 14.000000] [num1 50.000000]
[Epoch 67/500] [Batch 660/676] [D loss: 0.017588] [G loss: 0.085274] [d1 loss: 0.096783] [d2 loss: 0.095833]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 0/676] [D loss: 0.021295] [G loss: 0.084955] [d1 loss: 0.065943] [d2 loss: 0.053755]  [sq d1 d2: 0.000149]  [num0: 15.000000] [num1 49.000000]
[Epoch 68/500] [Batch 20/676] [D loss: -0.000688] [G loss: 0.094135] [d1 loss: 0.101099] [d2 loss: 0.082236]  [sq d1 d2: 0.000356]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 40/676] [D loss: -0.003096] [G loss: 0.099573] [d1 loss: 0.109555] [d2 loss: 0.121815]  [sq d1 d2: 0.000150]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 60/676] [D loss: 0.011443] [G loss: 0.101061] [d1 loss: 0.193402] [d2 loss: 0.137151]  [sq d1 d2: 0.003164]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 80/676] [D loss: -0.008170] [G loss: 0.085737] [d1 loss: 0.122021] [d2 loss: 0.115277]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 68/500] [Batch 100/676] [D loss: -0.013045] [G loss: 0.102400] [d1 loss: 0.091087] [d2 loss: 0.096221]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 68/500] [Batch 120/676] [D loss: -0.016373] [G loss: 0.134366] [d1 loss: 0.086753] [d2 loss: 0.102605]  [sq d1 d2: 0.000251]  [num0: 17.000000] [num1 47.000000]
[Epoch 68/500] [Batch 140/676] [D loss: -0.028851] [G loss: 0.138349] [d1 loss: 0.075976] [d2 loss: 0.076265]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 68/500] [Batch 160/676] [D loss: -0.028751] [G loss: 0.176047] [d1 loss: 0.121255] [d2 loss: 0.115502]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 180/676] [D loss: -0.073592] [G loss: 0.162124] [d1 loss: 0.112235] [d2 loss: 0.084975]  [sq d1 d2: 0.000743]  [num0: 17.000000] [num1 47.000000]
[Epoch 68/500] [Batch 200/676] [D loss: -0.005098] [G loss: 0.133672] [d1 loss: 0.048333] [d2 loss: 0.049447]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 220/676] [D loss: -0.010210] [G loss: 0.129321] [d1 loss: 0.109840] [d2 loss: 0.112938]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 68/500] [Batch 240/676] [D loss: 0.008169] [G loss: 0.106739] [d1 loss: 0.094838] [d2 loss: 0.090397]  [sq d1 d2: 0.000020]  [num0: 22.000000] [num1 42.000000]
[Epoch 68/500] [Batch 260/676] [D loss: -0.007230] [G loss: 0.030592] [d1 loss: 0.121766] [d2 loss: 0.109458]  [sq d1 d2: 0.000151]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 280/676] [D loss: 0.013958] [G loss: -0.020233] [d1 loss: 0.094248] [d2 loss: 0.090081]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 300/676] [D loss: 0.002737] [G loss: -0.030607] [d1 loss: 0.132040] [d2 loss: 0.134345]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 320/676] [D loss: -0.005119] [G loss: -0.047173] [d1 loss: 0.038454] [d2 loss: 0.038685]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 68/500] [Batch 340/676] [D loss: -0.017944] [G loss: -0.083765] [d1 loss: 0.072590] [d2 loss: 0.068940]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 68/500] [Batch 360/676] [D loss: -0.017526] [G loss: -0.109086] [d1 loss: 0.094810] [d2 loss: 0.089133]  [sq d1 d2: 0.000032]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 380/676] [D loss: -0.039576] [G loss: -0.138326] [d1 loss: 0.133211] [d2 loss: 0.114155]  [sq d1 d2: 0.000363]  [num0: 15.000000] [num1 49.000000]
[Epoch 68/500] [Batch 400/676] [D loss: -0.025097] [G loss: -0.205212] [d1 loss: 0.167355] [d2 loss: 0.173367]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 420/676] [D loss: -0.049094] [G loss: -0.281515] [d1 loss: 0.097702] [d2 loss: 0.111448]  [sq d1 d2: 0.000189]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 440/676] [D loss: -0.050948] [G loss: -0.309033] [d1 loss: 0.091722] [d2 loss: 0.098520]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 460/676] [D loss: -0.012293] [G loss: -0.378089] [d1 loss: 0.085685] [d2 loss: 0.084450]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 68/500] [Batch 480/676] [D loss: 0.026658] [G loss: -0.352342] [d1 loss: 0.140233] [d2 loss: 0.123859]  [sq d1 d2: 0.000268]  [num0: 15.000000] [num1 49.000000]
[Epoch 68/500] [Batch 500/676] [D loss: 0.013089] [G loss: -0.308154] [d1 loss: 0.094225] [d2 loss: 0.071148]  [sq d1 d2: 0.000533]  [num0: 15.000000] [num1 49.000000]
[Epoch 68/500] [Batch 520/676] [D loss: 0.010952] [G loss: -0.212900] [d1 loss: 0.085492] [d2 loss: 0.090395]  [sq d1 d2: 0.000024]  [num0: 11.000000] [num1 53.000000]
[Epoch 68/500] [Batch 540/676] [D loss: 0.004824] [G loss: -0.182919] [d1 loss: 0.085863] [d2 loss: 0.073897]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 68/500] [Batch 560/676] [D loss: -0.007265] [G loss: -0.157453] [d1 loss: 0.050849] [d2 loss: 0.051563]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 580/676] [D loss: -0.015138] [G loss: -0.157164] [d1 loss: 0.218392] [d2 loss: 0.196921]  [sq d1 d2: 0.000461]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 600/676] [D loss: -0.018243] [G loss: -0.126341] [d1 loss: 0.116770] [d2 loss: 0.105762]  [sq d1 d2: 0.000121]  [num0: 18.000000] [num1 46.000000]
[Epoch 68/500] [Batch 620/676] [D loss: -0.036984] [G loss: -0.119443] [d1 loss: 0.091138] [d2 loss: 0.093461]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 68/500] [Batch 640/676] [D loss: -0.039027] [G loss: -0.080734] [d1 loss: 0.101514] [d2 loss: 0.088233]  [sq d1 d2: 0.000176]  [num0: 16.000000] [num1 48.000000]
[Epoch 68/500] [Batch 660/676] [D loss: -0.059161] [G loss: -0.021930] [d1 loss: 0.066016] [d2 loss: 0.069735]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]

[Epoch 69/500] [Batch 0/676] [D loss: -0.038248] [G loss: -0.021726] [d1 loss: 0.086593] [d2 loss: 0.075236]  [sq d1 d2: 0.000129]  [num0: 11.000000] [num1 53.000000]
[Epoch 69/500] [Batch 20/676] [D loss: -0.044894] [G loss: -0.054657] [d1 loss: 0.111108] [d2 loss: 0.109967]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 69/500] [Batch 40/676] [D loss: 0.056065] [G loss: -0.045467] [d1 loss: 0.056760] [d2 loss: 0.052349]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 69/500] [Batch 60/676] [D loss: 0.025908] [G loss: -0.029389] [d1 loss: 0.106170] [d2 loss: 0.084324]  [sq d1 d2: 0.000477]  [num0: 17.000000] [num1 47.000000]
[Epoch 69/500] [Batch 80/676] [D loss: 0.015967] [G loss: 0.053853] [d1 loss: 0.114741] [d2 loss: 0.102718]  [sq d1 d2: 0.000145]  [num0: 19.000000] [num1 45.000000]
[Epoch 69/500] [Batch 100/676] [D loss: -0.001223] [G loss: 0.148701] [d1 loss: 0.036174] [d2 loss: 0.035798]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 69/500] [Batch 120/676] [D loss: 0.006108] [G loss: 0.224294] [d1 loss: 0.087905] [d2 loss: 0.075544]  [sq d1 d2: 0.000153]  [num0: 18.000000] [num1 46.000000]
[Epoch 69/500] [Batch 140/676] [D loss: -0.039962] [G loss: 0.311588] [d1 loss: 0.130441] [d2 loss: 0.128223]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 69/500] [Batch 160/676] [D loss: -0.064811] [G loss: 0.437701] [d1 loss: 0.096666] [d2 loss: 0.123747]  [sq d1 d2: 0.000733]  [num0: 18.000000] [num1 46.000000]
[Epoch 69/500] [Batch 180/676] [D loss: -0.090015] [G loss: 0.543718] [d1 loss: 0.058063] [d2 loss: 0.052631]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 69/500] [Batch 200/676] [D loss: -0.041462] [G loss: 0.606997] [d1 loss: 0.053421] [d2 loss: 0.068244]  [sq d1 d2: 0.000220]  [num0: 17.000000] [num1 47.000000]
[Epoch 69/500] [Batch 220/676] [D loss: -0.048778] [G loss: 0.582761] [d1 loss: 0.166075] [d2 loss: 0.154939]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 69/500] [Batch 240/676] [D loss: -0.018625] [G loss: 0.505764] [d1 loss: 0.163046] [d2 loss: 0.146975]  [sq d1 d2: 0.000258]  [num0: 18.000000] [num1 46.000000]
[Epoch 69/500] [Batch 260/676] [D loss: 0.038970] [G loss: 0.356089] [d1 loss: 0.100877] [d2 loss: 0.107951]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 69/500] [Batch 280/676] [D loss: -0.003196] [G loss: 0.257896] [d1 loss: 0.133696] [d2 loss: 0.129248]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 69/500] [Batch 300/676] [D loss: 0.012345] [G loss: 0.168503] [d1 loss: 0.084621] [d2 loss: 0.093124]  [sq d1 d2: 0.000072]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 320/676] [D loss: 0.004467] [G loss: 0.119877] [d1 loss: 0.131299] [d2 loss: 0.150616]  [sq d1 d2: 0.000373]  [num0: 19.000000] [num1 45.000000]
[Epoch 69/500] [Batch 340/676] [D loss: -0.012816] [G loss: 0.084428] [d1 loss: 0.098471] [d2 loss: 0.095497]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 360/676] [D loss: -0.021084] [G loss: 0.089648] [d1 loss: 0.123054] [d2 loss: 0.108035]  [sq d1 d2: 0.000226]  [num0: 13.000000] [num1 51.000000]
[Epoch 69/500] [Batch 380/676] [D loss: -0.048449] [G loss: 0.142729] [d1 loss: 0.139680] [d2 loss: 0.137725]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 69/500] [Batch 400/676] [D loss: -0.077060] [G loss: 0.170496] [d1 loss: 0.047584] [d2 loss: 0.040995]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 420/676] [D loss: -0.057991] [G loss: 0.155164] [d1 loss: 0.168645] [d2 loss: 0.171299]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 69/500] [Batch 440/676] [D loss: -0.063398] [G loss: 0.081580] [d1 loss: 0.169351] [d2 loss: 0.168322]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 69/500] [Batch 460/676] [D loss: -0.053409] [G loss: 0.053923] [d1 loss: 0.097968] [d2 loss: 0.079935]  [sq d1 d2: 0.000325]  [num0: 15.000000] [num1 49.000000]
[Epoch 69/500] [Batch 480/676] [D loss: -0.010259] [G loss: 0.018138] [d1 loss: 0.060557] [d2 loss: 0.053233]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 500/676] [D loss: -0.006093] [G loss: -0.013491] [d1 loss: 0.033250] [d2 loss: 0.034318]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 520/676] [D loss: 0.027983] [G loss: -0.036831] [d1 loss: 0.151172] [d2 loss: 0.144586]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 69/500] [Batch 540/676] [D loss: 0.023504] [G loss: -0.075242] [d1 loss: 0.181458] [d2 loss: 0.187573]  [sq d1 d2: 0.000037]  [num0: 12.000000] [num1 52.000000]
[Epoch 69/500] [Batch 560/676] [D loss: -0.001539] [G loss: -0.103122] [d1 loss: 0.129214] [d2 loss: 0.128800]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 580/676] [D loss: -0.010306] [G loss: -0.137777] [d1 loss: 0.127847] [d2 loss: 0.140267]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]
[Epoch 69/500] [Batch 600/676] [D loss: -0.030870] [G loss: -0.195681] [d1 loss: 0.104852] [d2 loss: 0.101003]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 69/500] [Batch 620/676] [D loss: -0.036396] [G loss: -0.233632] [d1 loss: 0.169657] [d2 loss: 0.152160]  [sq d1 d2: 0.000306]  [num0: 15.000000] [num1 49.000000]
[Epoch 69/500] [Batch 640/676] [D loss: -0.043981] [G loss: -0.252463] [d1 loss: 0.086181] [d2 loss: 0.100662]  [sq d1 d2: 0.000210]  [num0: 15.000000] [num1 49.000000]
[Epoch 69/500] [Batch 660/676] [D loss: -0.029209] [G loss: -0.301851] [d1 loss: 0.071382] [d2 loss: 0.081309]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 0/676] [D loss: -0.096760] [G loss: -0.307395] [d1 loss: 0.069828] [d2 loss: 0.077250]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 20/676] [D loss: -0.035188] [G loss: -0.334418] [d1 loss: 0.061714] [d2 loss: 0.073531]  [sq d1 d2: 0.000140]  [num0: 12.000000] [num1 52.000000]
[Epoch 70/500] [Batch 40/676] [D loss: -0.000413] [G loss: -0.320457] [d1 loss: 0.064031] [d2 loss: 0.064337]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 70/500] [Batch 60/676] [D loss: 0.008649] [G loss: -0.273519] [d1 loss: 0.118945] [d2 loss: 0.102610]  [sq d1 d2: 0.000267]  [num0: 15.000000] [num1 49.000000]
[Epoch 70/500] [Batch 80/676] [D loss: 0.040536] [G loss: -0.149118] [d1 loss: 0.188216] [d2 loss: 0.175618]  [sq d1 d2: 0.000159]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 100/676] [D loss: 0.000665] [G loss: -0.086597] [d1 loss: 0.207522] [d2 loss: 0.201239]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 70/500] [Batch 120/676] [D loss: 0.014995] [G loss: -0.056239] [d1 loss: 0.078903] [d2 loss: 0.084534]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 140/676] [D loss: 0.005209] [G loss: -0.043431] [d1 loss: 0.033630] [d2 loss: 0.034219]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 70/500] [Batch 160/676] [D loss: 0.001119] [G loss: -0.042208] [d1 loss: 0.090638] [d2 loss: 0.093333]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 70/500] [Batch 180/676] [D loss: -0.004856] [G loss: -0.032771] [d1 loss: 0.074991] [d2 loss: 0.076509]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 70/500] [Batch 200/676] [D loss: -0.008842] [G loss: -0.017599] [d1 loss: 0.089770] [d2 loss: 0.098061]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 220/676] [D loss: -0.009588] [G loss: 0.010136] [d1 loss: 0.063948] [d2 loss: 0.064207]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 240/676] [D loss: -0.039197] [G loss: 0.033710] [d1 loss: 0.084119] [d2 loss: 0.086275]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 70/500] [Batch 260/676] [D loss: -0.039148] [G loss: 0.047064] [d1 loss: 0.063662] [d2 loss: 0.055470]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 280/676] [D loss: -0.036089] [G loss: 0.041194] [d1 loss: 0.095656] [d2 loss: 0.103818]  [sq d1 d2: 0.000067]  [num0: 12.000000] [num1 52.000000]

[Epoch 70/500] [Batch 300/676] [D loss: -0.043603] [G loss: 0.051607] [d1 loss: 0.121326] [d2 loss: 0.110957]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 320/676] [D loss: -0.040987] [G loss: 0.066624] [d1 loss: 0.081701] [d2 loss: 0.055704]  [sq d1 d2: 0.000676]  [num0: 13.000000] [num1 51.000000]
[Epoch 70/500] [Batch 340/676] [D loss: -0.034660] [G loss: 0.081945] [d1 loss: 0.085995] [d2 loss: 0.092271]  [sq d1 d2: 0.000039]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 360/676] [D loss: 0.005897] [G loss: 0.083496] [d1 loss: 0.082827] [d2 loss: 0.076916]  [sq d1 d2: 0.000035]  [num0: 11.000000] [num1 53.000000]
[Epoch 70/500] [Batch 380/676] [D loss: -0.012429] [G loss: 0.095188] [d1 loss: 0.141969] [d2 loss: 0.128580]  [sq d1 d2: 0.000179]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 400/676] [D loss: 0.001584] [G loss: 0.112152] [d1 loss: 0.067225] [d2 loss: 0.068764]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 70/500] [Batch 420/676] [D loss: 0.005093] [G loss: 0.085840] [d1 loss: 0.099565] [d2 loss: 0.109149]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 70/500] [Batch 440/676] [D loss: 0.015644] [G loss: 0.066998] [d1 loss: 0.121950] [d2 loss: 0.129694]  [sq d1 d2: 0.000060]  [num0: 12.000000] [num1 52.000000]
[Epoch 70/500] [Batch 460/676] [D loss: 0.010262] [G loss: 0.063899] [d1 loss: 0.107385] [d2 loss: 0.090814]  [sq d1 d2: 0.000275]  [num0: 15.000000] [num1 49.000000]
[Epoch 70/500] [Batch 480/676] [D loss: 0.000390] [G loss: 0.048876] [d1 loss: 0.054124] [d2 loss: 0.054075]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 500/676] [D loss: -0.005361] [G loss: 0.022014] [d1 loss: 0.040698] [d2 loss: 0.036459]  [sq d1 d2: 0.000018]  [num0: 10.000000] [num1 54.000000]
[Epoch 70/500] [Batch 520/676] [D loss: -0.010546] [G loss: 0.014450] [d1 loss: 0.070939] [d2 loss: 0.083032]  [sq d1 d2: 0.000146]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 540/676] [D loss: -0.007131] [G loss: 0.009677] [d1 loss: 0.079995] [d2 loss: 0.088283]  [sq d1 d2: 0.000069]  [num0: 18.000000] [num1 46.000000]
[Epoch 70/500] [Batch 560/676] [D loss: -0.011848] [G loss: -0.002105] [d1 loss: 0.140869] [d2 loss: 0.133046]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 580/676] [D loss: -0.018217] [G loss: -0.039330] [d1 loss: 0.110637] [d2 loss: 0.118801]  [sq d1 d2: 0.000067]  [num0: 21.000000] [num1 43.000000]
[Epoch 70/500] [Batch 600/676] [D loss: -0.011878] [G loss: -0.027444] [d1 loss: 0.069154] [d2 loss: 0.069562]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 70/500] [Batch 620/676] [D loss: -0.037217] [G loss: -0.046407] [d1 loss: 0.204408] [d2 loss: 0.203959]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 70/500] [Batch 640/676] [D loss: -0.027960] [G loss: -0.042529] [d1 loss: 0.063003] [d2 loss: 0.057150]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 70/500] [Batch 660/676] [D loss: 0.001099] [G loss: -0.037867] [d1 loss: 0.058166] [d2 loss: 0.045180]  [sq d1 d2: 0.000169]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 0/676] [D loss: 0.015319] [G loss: -0.045186] [d1 loss: 0.123482] [d2 loss: 0.113750]  [sq d1 d2: 0.000095]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 20/676] [D loss: -0.005392] [G loss: -0.053919] [d1 loss: 0.067851] [d2 loss: 0.085284]  [sq d1 d2: 0.000304]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 40/676] [D loss: 0.001774] [G loss: -0.059742] [d1 loss: 0.099222] [d2 loss: 0.098377]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 60/676] [D loss: 0.007607] [G loss: -0.016566] [d1 loss: 0.066328] [d2 loss: 0.076012]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 71/500] [Batch 80/676] [D loss: -0.002657] [G loss: 0.004801] [d1 loss: 0.132134] [d2 loss: 0.108055]  [sq d1 d2: 0.000580]  [num0: 13.000000] [num1 51.000000]
[Epoch 71/500] [Batch 100/676] [D loss: 0.002256] [G loss: 0.019450] [d1 loss: 0.085817] [d2 loss: 0.093273]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 71/500] [Batch 120/676] [D loss: -0.002200] [G loss: 0.020018] [d1 loss: 0.071479] [d2 loss: 0.080684]  [sq d1 d2: 0.000085]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 140/676] [D loss: -0.004905] [G loss: 0.021516] [d1 loss: 0.103365] [d2 loss: 0.101255]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 71/500] [Batch 160/676] [D loss: -0.013853] [G loss: 0.018694] [d1 loss: 0.071167] [d2 loss: 0.080758]  [sq d1 d2: 0.000092]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 180/676] [D loss: -0.015169] [G loss: 0.030646] [d1 loss: 0.037787] [d2 loss: 0.036617]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 200/676] [D loss: -0.018148] [G loss: 0.060014] [d1 loss: 0.158804] [d2 loss: 0.151996]  [sq d1 d2: 0.000046]  [num0: 19.000000] [num1 45.000000]
[Epoch 71/500] [Batch 220/676] [D loss: -0.031885] [G loss: 0.087635] [d1 loss: 0.078816] [d2 loss: 0.068813]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 71/500] [Batch 240/676] [D loss: -0.016126] [G loss: 0.108318] [d1 loss: 0.081596] [d2 loss: 0.070410]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 260/676] [D loss: 0.000991] [G loss: 0.088587] [d1 loss: 0.074549] [d2 loss: 0.099091]  [sq d1 d2: 0.000602]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 280/676] [D loss: 0.001155] [G loss: 0.100889] [d1 loss: 0.248301] [d2 loss: 0.234159]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 300/676] [D loss: 0.006524] [G loss: 0.079948] [d1 loss: 0.114436] [d2 loss: 0.097429]  [sq d1 d2: 0.000289]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 320/676] [D loss: -0.029358] [G loss: 0.050506] [d1 loss: 0.035076] [d2 loss: 0.040577]  [sq d1 d2: 0.000030]  [num0: 20.000000] [num1 44.000000]
[Epoch 71/500] [Batch 340/676] [D loss: -0.008317] [G loss: 0.065530] [d1 loss: 0.063949] [d2 loss: 0.075668]  [sq d1 d2: 0.000137]  [num0: 19.000000] [num1 45.000000]
[Epoch 71/500] [Batch 360/676] [D loss: -0.003535] [G loss: 0.040462] [d1 loss: 0.085405] [d2 loss: 0.084640]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 380/676] [D loss: -0.000700] [G loss: 0.049407] [d1 loss: 0.174881] [d2 loss: 0.189301]  [sq d1 d2: 0.000208]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 400/676] [D loss: -0.009233] [G loss: 0.021028] [d1 loss: 0.188729] [d2 loss: 0.162068]  [sq d1 d2: 0.000711]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 420/676] [D loss: -0.012533] [G loss: 0.001450] [d1 loss: 0.135894] [d2 loss: 0.145495]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 71/500] [Batch 440/676] [D loss: -0.015594] [G loss: -0.010210] [d1 loss: 0.058710] [d2 loss: 0.057648]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 71/500] [Batch 460/676] [D loss: -0.010851] [G loss: -0.039175] [d1 loss: 0.063391] [d2 loss: 0.046401]  [sq d1 d2: 0.000289]  [num0: 21.000000] [num1 43.000000]
[Epoch 71/500] [Batch 480/676] [D loss: -0.021583] [G loss: -0.026544] [d1 loss: 0.069227] [d2 loss: 0.062059]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 500/676] [D loss: -0.022114] [G loss: -0.023528] [d1 loss: 0.096966] [d2 loss: 0.084116]  [sq d1 d2: 0.000165]  [num0: 18.000000] [num1 46.000000]
[Epoch 71/500] [Batch 520/676] [D loss: -0.025730] [G loss: -0.047342] [d1 loss: 0.049303] [d2 loss: 0.042860]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 71/500] [Batch 540/676] [D loss: -0.008198] [G loss: -0.045217] [d1 loss: 0.072453] [d2 loss: 0.080341]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 560/676] [D loss: -0.002062] [G loss: -0.032026] [d1 loss: 0.102231] [d2 loss: 0.117490]  [sq d1 d2: 0.000233]  [num0: 15.000000] [num1 49.000000]
[Epoch 71/500] [Batch 580/676] [D loss: 0.003506] [G loss: -0.044670] [d1 loss: 0.059953] [d2 loss: 0.052352]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 71/500] [Batch 600/676] [D loss: 0.018346] [G loss: -0.029285] [d1 loss: 0.089591] [d2 loss: 0.071758]  [sq d1 d2: 0.000318]  [num0: 14.000000] [num1 50.000000]
[Epoch 71/500] [Batch 620/676] [D loss: 0.002740] [G loss: -0.025625] [d1 loss: 0.059179] [d2 loss: 0.053660]  [sq d1 d2: 0.000030]  [num0: 20.000000] [num1 44.000000]
[Epoch 71/500] [Batch 640/676] [D loss: -0.010906] [G loss: -0.013259] [d1 loss: 0.099624] [d2 loss: 0.103932]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]

[Epoch 71/500] [Batch 660/676] [D loss: -0.006547] [G loss: -0.019152] [d1 loss: 0.080245] [d2 loss: 0.077068]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 0/676] [D loss: -0.000251] [G loss: -0.026457] [d1 loss: 0.072347] [d2 loss: 0.070938]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 72/500] [Batch 20/676] [D loss: -0.009123] [G loss: -0.034662] [d1 loss: 0.068907] [d2 loss: 0.059520]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]
[Epoch 72/500] [Batch 40/676] [D loss: -0.011733] [G loss: -0.016758] [d1 loss: 0.074434] [d2 loss: 0.073526]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 60/676] [D loss: -0.012943] [G loss: -0.011058] [d1 loss: 0.193490] [d2 loss: 0.141461]  [sq d1 d2: 0.002707]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 80/676] [D loss: -0.004993] [G loss: -0.021297] [d1 loss: 0.098098] [d2 loss: 0.086530]  [sq d1 d2: 0.000134]  [num0: 16.000000] [num1 48.000000]
[Epoch 72/500] [Batch 100/676] [D loss: -0.010504] [G loss: -0.005622] [d1 loss: 0.115501] [d2 loss: 0.103312]  [sq d1 d2: 0.000149]  [num0: 17.000000] [num1 47.000000]
[Epoch 72/500] [Batch 120/676] [D loss: -0.032422] [G loss: 0.021633] [d1 loss: 0.072183] [d2 loss: 0.079541]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 140/676] [D loss: -0.012295] [G loss: 0.042669] [d1 loss: 0.099460] [d2 loss: 0.108133]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 72/500] [Batch 160/676] [D loss: -0.009834] [G loss: 0.078403] [d1 loss: 0.175546] [d2 loss: 0.182860]  [sq d1 d2: 0.000053]  [num0: 20.000000] [num1 44.000000]
[Epoch 72/500] [Batch 180/676] [D loss: -0.017619] [G loss: 0.073887] [d1 loss: 0.120023] [d2 loss: 0.134606]  [sq d1 d2: 0.000213]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 200/676] [D loss: -0.014753] [G loss: 0.090231] [d1 loss: 0.076375] [d2 loss: 0.070581]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 72/500] [Batch 220/676] [D loss: -0.001160] [G loss: 0.091220] [d1 loss: 0.088534] [d2 loss: 0.088896]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 240/676] [D loss: 0.000005] [G loss: 0.087772] [d1 loss: 0.067081] [d2 loss: 0.068075]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 260/676] [D loss: -0.002985] [G loss: 0.046924] [d1 loss: 0.172855] [d2 loss: 0.149403]  [sq d1 d2: 0.000550]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 280/676] [D loss: -0.003989] [G loss: 0.027171] [d1 loss: 0.178061] [d2 loss: 0.139003]  [sq d1 d2: 0.001526]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 300/676] [D loss: -0.007560] [G loss: 0.008090] [d1 loss: 0.145517] [d2 loss: 0.143524]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 320/676] [D loss: -0.012877] [G loss: -0.004899] [d1 loss: 0.074857] [d2 loss: 0.077874]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 340/676] [D loss: -0.008372] [G loss: -0.004846] [d1 loss: 0.079402] [d2 loss: 0.069832]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 72/500] [Batch 360/676] [D loss: -0.008640] [G loss: -0.023244] [d1 loss: 0.078341] [d2 loss: 0.079972]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 380/676] [D loss: -0.006878] [G loss: -0.017897] [d1 loss: 0.071051] [d2 loss: 0.060585]  [sq d1 d2: 0.000110]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 400/676] [D loss: -0.011077] [G loss: -0.037978] [d1 loss: 0.134543] [d2 loss: 0.112482]  [sq d1 d2: 0.000487]  [num0: 15.000000] [num1 49.000000]
[Epoch 72/500] [Batch 420/676] [D loss: -0.011403] [G loss: -0.032870] [d1 loss: 0.063044] [d2 loss: 0.063653]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 72/500] [Batch 440/676] [D loss: -0.010184] [G loss: -0.036964] [d1 loss: 0.035927] [d2 loss: 0.034656]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 460/676] [D loss: -0.004255] [G loss: -0.031289] [d1 loss: 0.093636] [d2 loss: 0.085514]  [sq d1 d2: 0.000066]  [num0: 10.000000] [num1 54.000000]
[Epoch 72/500] [Batch 480/676] [D loss: -0.016730] [G loss: -0.020313] [d1 loss: 0.071472] [d2 loss: 0.072876]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 72/500] [Batch 500/676] [D loss: -0.006947] [G loss: -0.013193] [d1 loss: 0.211787] [d2 loss: 0.191008]  [sq d1 d2: 0.000432]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 520/676] [D loss: -0.003227] [G loss: -0.036334] [d1 loss: 0.132523] [d2 loss: 0.136552]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 72/500] [Batch 540/676] [D loss: -0.000023] [G loss: -0.023454] [d1 loss: 0.254679] [d2 loss: 0.243919]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 560/676] [D loss: -0.008423] [G loss: -0.017110] [d1 loss: 0.117449] [d2 loss: 0.132924]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 580/676] [D loss: -0.004188] [G loss: -0.024327] [d1 loss: 0.054708] [d2 loss: 0.053759]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 72/500] [Batch 600/676] [D loss: -0.007862] [G loss: -0.009578] [d1 loss: 0.138680] [d2 loss: 0.127868]  [sq d1 d2: 0.000117]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 620/676] [D loss: -0.010285] [G loss: 0.023798] [d1 loss: 0.093193] [d2 loss: 0.087677]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 72/500] [Batch 640/676] [D loss: -0.011995] [G loss: 0.001249] [d1 loss: 0.138444] [d2 loss: 0.140708]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 72/500] [Batch 660/676] [D loss: -0.003805] [G loss: -0.005107] [d1 loss: 0.100713] [d2 loss: 0.093637]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 0/676] [D loss: -0.010202] [G loss: 0.003492] [d1 loss: 0.220853] [d2 loss: 0.172970]  [sq d1 d2: 0.002293]  [num0: 15.000000] [num1 49.000000]
[Epoch 73/500] [Batch 20/676] [D loss: -0.013944] [G loss: 0.028127] [d1 loss: 0.095685] [d2 loss: 0.105616]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 40/676] [D loss: -0.005351] [G loss: 0.039433] [d1 loss: 0.123171] [d2 loss: 0.140285]  [sq d1 d2: 0.000293]  [num0: 15.000000] [num1 49.000000]
[Epoch 73/500] [Batch 60/676] [D loss: -0.016960] [G loss: 0.094369] [d1 loss: 0.077104] [d2 loss: 0.070490]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 80/676] [D loss: -0.025115] [G loss: 0.135259] [d1 loss: 0.059685] [d2 loss: 0.070234]  [sq d1 d2: 0.000111]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 100/676] [D loss: -0.004800] [G loss: 0.152406] [d1 loss: 0.219277] [d2 loss: 0.240328]  [sq d1 d2: 0.000443]  [num0: 18.000000] [num1 46.000000]
[Epoch 73/500] [Batch 120/676] [D loss: -0.012050] [G loss: 0.173906] [d1 loss: 0.288374] [d2 loss: 0.250437]  [sq d1 d2: 0.001439]  [num0: 17.000000] [num1 47.000000]
[Epoch 73/500] [Batch 140/676] [D loss: -0.016771] [G loss: 0.158792] [d1 loss: 0.074652] [d2 loss: 0.081643]  [sq d1 d2: 0.000049]  [num0: 14.000000] [num1 50.000000]
[Epoch 73/500] [Batch 160/676] [D loss: -0.008012] [G loss: 0.143899] [d1 loss: 0.108667] [d2 loss: 0.121805]  [sq d1 d2: 0.000173]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 180/676] [D loss: -0.009487] [G loss: 0.134368] [d1 loss: 0.149136] [d2 loss: 0.152985]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 73/500] [Batch 200/676] [D loss: -0.011249] [G loss: 0.142962] [d1 loss: 0.062463] [d2 loss: 0.065042]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 220/676] [D loss: 0.000962] [G loss: 0.128485] [d1 loss: 0.165778] [d2 loss: 0.156050]  [sq d1 d2: 0.000095]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 240/676] [D loss: -0.008887] [G loss: 0.103017] [d1 loss: 0.107820] [d2 loss: 0.087541]  [sq d1 d2: 0.000411]  [num0: 17.000000] [num1 47.000000]
[Epoch 73/500] [Batch 260/676] [D loss: -0.011118] [G loss: 0.095473] [d1 loss: 0.073861] [d2 loss: 0.057085]  [sq d1 d2: 0.000281]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 280/676] [D loss: -0.021320] [G loss: 0.077363] [d1 loss: 0.097188] [d2 loss: 0.096168]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 300/676] [D loss: -0.013749] [G loss: 0.082910] [d1 loss: 0.092819] [d2 loss: 0.110624]  [sq d1 d2: 0.000317]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 320/676] [D loss: -0.009182] [G loss: 0.057847] [d1 loss: 0.095942] [d2 loss: 0.105651]  [sq d1 d2: 0.000094]  [num0: 20.000000] [num1 44.000000]

[Epoch 73/500] [Batch 340/676] [D loss: 0.002153] [G loss: 0.046013] [d1 loss: 0.154137] [d2 loss: 0.130380]  [sq d1 d2: 0.000564]  [num0: 18.000000] [num1 46.000000]
[Epoch 73/500] [Batch 360/676] [D loss: -0.015183] [G loss: 0.027110] [d1 loss: 0.070543] [d2 loss: 0.068017]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 73/500] [Batch 380/676] [D loss: -0.011410] [G loss: 0.008121] [d1 loss: 0.080764] [d2 loss: 0.096945]  [sq d1 d2: 0.000262]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 400/676] [D loss: -0.008347] [G loss: 0.027923] [d1 loss: 0.064481] [d2 loss: 0.063310]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 420/676] [D loss: -0.012653] [G loss: -0.012563] [d1 loss: 0.134975] [d2 loss: 0.126888]  [sq d1 d2: 0.000065]  [num0: 17.000000] [num1 47.000000]
[Epoch 73/500] [Batch 440/676] [D loss: -0.013256] [G loss: -0.041592] [d1 loss: 0.105177] [d2 loss: 0.117424]  [sq d1 d2: 0.000150]  [num0: 18.000000] [num1 46.000000]
[Epoch 73/500] [Batch 460/676] [D loss: 0.000823] [G loss: -0.045145] [d1 loss: 0.053325] [d2 loss: 0.063561]  [sq d1 d2: 0.000105]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 480/676] [D loss: -0.004809] [G loss: -0.059966] [d1 loss: 0.237985] [d2 loss: 0.204596]  [sq d1 d2: 0.001115]  [num0: 18.000000] [num1 46.000000]
[Epoch 73/500] [Batch 500/676] [D loss: -0.008831] [G loss: -0.038792] [d1 loss: 0.130438] [d2 loss: 0.139475]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 73/500] [Batch 520/676] [D loss: -0.014418] [G loss: -0.043216] [d1 loss: 0.115490] [d2 loss: 0.110010]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 540/676] [D loss: -0.010123] [G loss: -0.047656] [d1 loss: 0.108128] [d2 loss: 0.100057]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 560/676] [D loss: -0.014028] [G loss: -0.053623] [d1 loss: 0.135552] [d2 loss: 0.118723]  [sq d1 d2: 0.000283]  [num0: 15.000000] [num1 49.000000]
[Epoch 73/500] [Batch 580/676] [D loss: -0.005689] [G loss: -0.017601] [d1 loss: 0.099955] [d2 loss: 0.111889]  [sq d1 d2: 0.000142]  [num0: 14.000000] [num1 50.000000]
[Epoch 73/500] [Batch 600/676] [D loss: -0.013323] [G loss: -0.023658] [d1 loss: 0.171665] [d2 loss: 0.173494]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 620/676] [D loss: -0.014314] [G loss: -0.008390] [d1 loss: 0.114127] [d2 loss: 0.097924]  [sq d1 d2: 0.000263]  [num0: 13.000000] [num1 51.000000]
[Epoch 73/500] [Batch 640/676] [D loss: -0.019586] [G loss: -0.004819] [d1 loss: 0.082700] [d2 loss: 0.053071]  [sq d1 d2: 0.000878]  [num0: 16.000000] [num1 48.000000]
[Epoch 73/500] [Batch 660/676] [D loss: -0.009554] [G loss: -0.027043] [d1 loss: 0.081491] [d2 loss: 0.085136]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 74/500] [Batch 0/676] [D loss: -0.018865] [G loss: -0.016114] [d1 loss: 0.100349] [d2 loss: 0.089484]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 20/676] [D loss: -0.014831] [G loss: -0.007429] [d1 loss: 0.078809] [d2 loss: 0.076019]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 40/676] [D loss: -0.008263] [G loss: 0.007527] [d1 loss: 0.119371] [d2 loss: 0.098656]  [sq d1 d2: 0.000429]  [num0: 18.000000] [num1 46.000000]
[Epoch 74/500] [Batch 60/676] [D loss: -0.014888] [G loss: 0.037419] [d1 loss: 0.113684] [d2 loss: 0.119331]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 74/500] [Batch 80/676] [D loss: -0.011661] [G loss: 0.048879] [d1 loss: 0.118034] [d2 loss: 0.106572]  [sq d1 d2: 0.000131]  [num0: 17.000000] [num1 47.000000]
[Epoch 74/500] [Batch 100/676] [D loss: -0.010031] [G loss: 0.048516] [d1 loss: 0.148904] [d2 loss: 0.133997]  [sq d1 d2: 0.000222]  [num0: 20.000000] [num1 44.000000]
[Epoch 74/500] [Batch 120/676] [D loss: -0.008032] [G loss: 0.064758] [d1 loss: 0.116313] [d2 loss: 0.118573]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 74/500] [Batch 140/676] [D loss: -0.014470] [G loss: 0.062116] [d1 loss: 0.065221] [d2 loss: 0.055042]  [sq d1 d2: 0.000104]  [num0: 14.000000] [num1 50.000000]
[Epoch 74/500] [Batch 160/676] [D loss: -0.016434] [G loss: 0.049750] [d1 loss: 0.224753] [d2 loss: 0.200022]  [sq d1 d2: 0.000612]  [num0: 20.000000] [num1 44.000000]
[Epoch 74/500] [Batch 180/676] [D loss: -0.002514] [G loss: 0.055467] [d1 loss: 0.088958] [d2 loss: 0.092156]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 74/500] [Batch 200/676] [D loss: -0.006192] [G loss: 0.044925] [d1 loss: 0.049472] [d2 loss: 0.063876]  [sq d1 d2: 0.000207]  [num0: 10.000000] [num1 54.000000]
[Epoch 74/500] [Batch 220/676] [D loss: -0.014286] [G loss: 0.025078] [d1 loss: 0.128697] [d2 loss: 0.090229]  [sq d1 d2: 0.001480]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 240/676] [D loss: -0.011960] [G loss: 0.061933] [d1 loss: 0.117069] [d2 loss: 0.134989]  [sq d1 d2: 0.000321]  [num0: 18.000000] [num1 46.000000]
[Epoch 74/500] [Batch 260/676] [D loss: -0.017731] [G loss: 0.007430] [d1 loss: 0.165263] [d2 loss: 0.128439]  [sq d1 d2: 0.001356]  [num0: 20.000000] [num1 44.000000]
[Epoch 74/500] [Batch 280/676] [D loss: -0.012528] [G loss: -0.002929] [d1 loss: 0.120674] [d2 loss: 0.119124]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 74/500] [Batch 300/676] [D loss: -0.015963] [G loss: -0.006617] [d1 loss: 0.091090] [d2 loss: 0.094803]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 320/676] [D loss: -0.017573] [G loss: -0.005688] [d1 loss: 0.096589] [d2 loss: 0.083293]  [sq d1 d2: 0.000177]  [num0: 16.000000] [num1 48.000000]
[Epoch 74/500] [Batch 340/676] [D loss: -0.019766] [G loss: -0.001388] [d1 loss: 0.050088] [d2 loss: 0.045087]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 74/500] [Batch 360/676] [D loss: -0.016789] [G loss: 0.011383] [d1 loss: 0.111504] [d2 loss: 0.111372]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 74/500] [Batch 380/676] [D loss: -0.007690] [G loss: 0.014547] [d1 loss: 0.103529] [d2 loss: 0.085705]  [sq d1 d2: 0.000318]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 400/676] [D loss: -0.022208] [G loss: 0.028710] [d1 loss: 0.085248] [d2 loss: 0.085084]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 74/500] [Batch 420/676] [D loss: -0.023501] [G loss: 0.057196] [d1 loss: 0.105908] [d2 loss: 0.101485]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 74/500] [Batch 440/676] [D loss: -0.009394] [G loss: 0.050717] [d1 loss: 0.182071] [d2 loss: 0.136323]  [sq d1 d2: 0.002093]  [num0: 16.000000] [num1 48.000000]
[Epoch 74/500] [Batch 460/676] [D loss: -0.000597] [G loss: 0.084649] [d1 loss: 0.095115] [d2 loss: 0.118378]  [sq d1 d2: 0.000541]  [num0: 17.000000] [num1 47.000000]
[Epoch 74/500] [Batch 480/676] [D loss: -0.030037] [G loss: 0.055118] [d1 loss: 0.071212] [d2 loss: 0.070571]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 74/500] [Batch 500/676] [D loss: -0.005824] [G loss: 0.077037] [d1 loss: 0.099912] [d2 loss: 0.097722]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 74/500] [Batch 520/676] [D loss: -0.016212] [G loss: 0.124003] [d1 loss: 0.044136] [d2 loss: 0.045875]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 74/500] [Batch 540/676] [D loss: -0.025048] [G loss: 0.110219] [d1 loss: 0.127292] [d2 loss: 0.112207]  [sq d1 d2: 0.000228]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 560/676] [D loss: -0.011300] [G loss: 0.137802] [d1 loss: 0.053253] [d2 loss: 0.046376]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 580/676] [D loss: -0.008839] [G loss: 0.130195] [d1 loss: 0.161090] [d2 loss: 0.192555]  [sq d1 d2: 0.000990]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 600/676] [D loss: -0.016428] [G loss: 0.093580] [d1 loss: 0.123460] [d2 loss: 0.126086]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 620/676] [D loss: -0.024947] [G loss: 0.097811] [d1 loss: 0.110707] [d2 loss: 0.083869]  [sq d1 d2: 0.000720]  [num0: 15.000000] [num1 49.000000]
[Epoch 74/500] [Batch 640/676] [D loss: -0.012339] [G loss: 0.080381] [d1 loss: 0.131290] [d2 loss: 0.111165]  [sq d1 d2: 0.000405]  [num0: 18.000000] [num1 46.000000]
[Epoch 74/500] [Batch 660/676] [D loss: -0.010136] [G loss: 0.082872] [d1 loss: 0.094562] [d2 loss: 0.095552]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]

[Epoch 75/500] [Batch 0/676] [D loss: -0.010481] [G loss: 0.057146] [d1 loss: 0.079459] [d2 loss: 0.078103]  [sq d1 d2: 0.000002]  [num0: 9.000000] [num1 55.000000]
[Epoch 75/500] [Batch 20/676] [D loss: -0.012852] [G loss: 0.017975] [d1 loss: 0.086822] [d2 loss: 0.085867]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 40/676] [D loss: -0.007690] [G loss: 0.027008] [d1 loss: 0.096055] [d2 loss: 0.106965]  [sq d1 d2: 0.000119]  [num0: 13.000000] [num1 51.000000]
[Epoch 75/500] [Batch 60/676] [D loss: -0.011509] [G loss: 0.005607] [d1 loss: 0.045393] [d2 loss: 0.048548]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 75/500] [Batch 80/676] [D loss: -0.011377] [G loss: 0.031728] [d1 loss: 0.141563] [d2 loss: 0.128897]  [sq d1 d2: 0.000160]  [num0: 13.000000] [num1 51.000000]
[Epoch 75/500] [Batch 100/676] [D loss: -0.029817] [G loss: 0.033751] [d1 loss: 0.216654] [d2 loss: 0.210614]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 75/500] [Batch 120/676] [D loss: -0.011976] [G loss: 0.006365] [d1 loss: 0.094052] [d2 loss: 0.090103]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 75/500] [Batch 140/676] [D loss: -0.017039] [G loss: -0.001489] [d1 loss: 0.143085] [d2 loss: 0.156405]  [sq d1 d2: 0.000177]  [num0: 16.000000] [num1 48.000000]
[Epoch 75/500] [Batch 160/676] [D loss: 0.000381] [G loss: 0.021092] [d1 loss: 0.055348] [d2 loss: 0.033626]  [sq d1 d2: 0.000472]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 180/676] [D loss: -0.000760] [G loss: 0.056083] [d1 loss: 0.116066] [d2 loss: 0.117144]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 200/676] [D loss: -0.014069] [G loss: 0.079764] [d1 loss: 0.245507] [d2 loss: 0.223152]  [sq d1 d2: 0.000500]  [num0: 20.000000] [num1 44.000000]
[Epoch 75/500] [Batch 220/676] [D loss: -0.025278] [G loss: 0.096889] [d1 loss: 0.093834] [d2 loss: 0.089773]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 240/676] [D loss: -0.034274] [G loss: 0.135963] [d1 loss: 0.120761] [d2 loss: 0.134306]  [sq d1 d2: 0.000183]  [num0: 16.000000] [num1 48.000000]
[Epoch 75/500] [Batch 260/676] [D loss: -0.033440] [G loss: 0.149282] [d1 loss: 0.035792] [d2 loss: 0.037626]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 75/500] [Batch 280/676] [D loss: -0.015086] [G loss: 0.175293] [d1 loss: 0.137423] [d2 loss: 0.142169]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 300/676] [D loss: -0.031631] [G loss: 0.171888] [d1 loss: 0.178533] [d2 loss: 0.157219]  [sq d1 d2: 0.000454]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 320/676] [D loss: -0.026618] [G loss: 0.139676] [d1 loss: 0.048180] [d2 loss: 0.046202]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 75/500] [Batch 340/676] [D loss: -0.011214] [G loss: 0.112604] [d1 loss: 0.097555] [d2 loss: 0.100462]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 75/500] [Batch 360/676] [D loss: -0.014139] [G loss: 0.142322] [d1 loss: 0.112058] [d2 loss: 0.119808]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 75/500] [Batch 380/676] [D loss: -0.023373] [G loss: 0.067340] [d1 loss: 0.176258] [d2 loss: 0.164817]  [sq d1 d2: 0.000131]  [num0: 17.000000] [num1 47.000000]
[Epoch 75/500] [Batch 400/676] [D loss: -0.024487] [G loss: 0.002820] [d1 loss: 0.039375] [d2 loss: 0.035450]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 75/500] [Batch 420/676] [D loss: -0.021572] [G loss: 0.021624] [d1 loss: 0.052339] [d2 loss: 0.056297]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 75/500] [Batch 440/676] [D loss: -0.015858] [G loss: 0.007777] [d1 loss: 0.176083] [d2 loss: 0.164864]  [sq d1 d2: 0.000126]  [num0: 12.000000] [num1 52.000000]
[Epoch 75/500] [Batch 460/676] [D loss: -0.032251] [G loss: 0.031755] [d1 loss: 0.105137] [d2 loss: 0.099736]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 75/500] [Batch 480/676] [D loss: -0.037331] [G loss: 0.020770] [d1 loss: 0.151831] [d2 loss: 0.158158]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 500/676] [D loss: -0.041788] [G loss: 0.011188] [d1 loss: 0.114822] [d2 loss: 0.135789]  [sq d1 d2: 0.000440]  [num0: 17.000000] [num1 47.000000]
[Epoch 75/500] [Batch 520/676] [D loss: -0.026369] [G loss: 0.007462] [d1 loss: 0.133550] [d2 loss: 0.118002]  [sq d1 d2: 0.000242]  [num0: 16.000000] [num1 48.000000]
[Epoch 75/500] [Batch 540/676] [D loss: -0.031008] [G loss: 0.020330] [d1 loss: 0.094717] [d2 loss: 0.109816]  [sq d1 d2: 0.000228]  [num0: 18.000000] [num1 46.000000]
[Epoch 75/500] [Batch 560/676] [D loss: -0.044217] [G loss: -0.002981] [d1 loss: 0.095846] [d2 loss: 0.088758]  [sq d1 d2: 0.000050]  [num0: 20.000000] [num1 44.000000]
[Epoch 75/500] [Batch 580/676] [D loss: -0.012660] [G loss: 0.007814] [d1 loss: 0.167103] [d2 loss: 0.165767]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 600/676] [D loss: -0.030199] [G loss: -0.006051] [d1 loss: 0.106357] [d2 loss: 0.120953]  [sq d1 d2: 0.000213]  [num0: 15.000000] [num1 49.000000]
[Epoch 75/500] [Batch 620/676] [D loss: -0.022307] [G loss: -0.027497] [d1 loss: 0.140302] [d2 loss: 0.123773]  [sq d1 d2: 0.000273]  [num0: 17.000000] [num1 47.000000]
[Epoch 75/500] [Batch 640/676] [D loss: -0.007293] [G loss: 0.001116] [d1 loss: 0.227478] [d2 loss: 0.208283]  [sq d1 d2: 0.000368]  [num0: 14.000000] [num1 50.000000]
[Epoch 75/500] [Batch 660/676] [D loss: -0.022699] [G loss: 0.032512] [d1 loss: 0.168085] [d2 loss: 0.169698]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 0/676] [D loss: -0.030644] [G loss: 0.049009] [d1 loss: 0.233623] [d2 loss: 0.233079]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 76/500] [Batch 20/676] [D loss: -0.036050] [G loss: 0.029124] [d1 loss: 0.153823] [d2 loss: 0.156446]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 76/500] [Batch 40/676] [D loss: -0.024123] [G loss: -0.005734] [d1 loss: 0.110252] [d2 loss: 0.091270]  [sq d1 d2: 0.000360]  [num0: 11.000000] [num1 53.000000]
[Epoch 76/500] [Batch 60/676] [D loss: -0.037328] [G loss: -0.009990] [d1 loss: 0.079548] [d2 loss: 0.080840]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 80/676] [D loss: -0.030535] [G loss: -0.047550] [d1 loss: 0.128591] [d2 loss: 0.125922]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 76/500] [Batch 100/676] [D loss: -0.031163] [G loss: -0.052665] [d1 loss: 0.127283] [d2 loss: 0.092889]  [sq d1 d2: 0.001183]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 120/676] [D loss: -0.041135] [G loss: -0.034490] [d1 loss: 0.133502] [d2 loss: 0.115572]  [sq d1 d2: 0.000321]  [num0: 20.000000] [num1 44.000000]
[Epoch 76/500] [Batch 140/676] [D loss: -0.036395] [G loss: -0.056911] [d1 loss: 0.103191] [d2 loss: 0.078331]  [sq d1 d2: 0.000618]  [num0: 14.000000] [num1 50.000000]
[Epoch 76/500] [Batch 160/676] [D loss: -0.009181] [G loss: -0.057689] [d1 loss: 0.100423] [d2 loss: 0.098408]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 76/500] [Batch 180/676] [D loss: -0.013423] [G loss: -0.008488] [d1 loss: 0.106106] [d2 loss: 0.105051]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 76/500] [Batch 200/676] [D loss: -0.006919] [G loss: 0.027184] [d1 loss: 0.203028] [d2 loss: 0.179030]  [sq d1 d2: 0.000576]  [num0: 17.000000] [num1 47.000000]
[Epoch 76/500] [Batch 220/676] [D loss: -0.035396] [G loss: 0.050308] [d1 loss: 0.141898] [d2 loss: 0.151338]  [sq d1 d2: 0.000089]  [num0: 15.000000] [num1 49.000000]
[Epoch 76/500] [Batch 240/676] [D loss: -0.034802] [G loss: 0.063396] [d1 loss: 0.076497] [d2 loss: 0.076497]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 76/500] [Batch 260/676] [D loss: -0.043224] [G loss: 0.069750] [d1 loss: 0.153298] [d2 loss: 0.152211]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 76/500] [Batch 280/676] [D loss: -0.043095] [G loss: 0.091923] [d1 loss: 0.148462] [d2 loss: 0.129690]  [sq d1 d2: 0.000352]  [num0: 15.000000] [num1 49.000000]
[Epoch 76/500] [Batch 300/676] [D loss: -0.026501] [G loss: 0.081159] [d1 loss: 0.192178] [d2 loss: 0.162236]  [sq d1 d2: 0.000897]  [num0: 11.000000] [num1 53.000000]
[Epoch 76/500] [Batch 320/676] [D loss: -0.040494] [G loss: 0.083930] [d1 loss: 0.099236] [d2 loss: 0.100666]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]

[Epoch 76/500] [Batch 340/676] [D loss: -0.002722] [G loss: 0.060612] [d1 loss: 0.132343] [d2 loss: 0.130892]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 360/676] [D loss: 0.005718] [G loss: 0.035940] [d1 loss: 0.114932] [d2 loss: 0.109001]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 380/676] [D loss: -0.006086] [G loss: -0.021423] [d1 loss: 0.099491] [d2 loss: 0.095812]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 400/676] [D loss: -0.002016] [G loss: -0.010158] [d1 loss: 0.107195] [d2 loss: 0.113546]  [sq d1 d2: 0.000040]  [num0: 20.000000] [num1 44.000000]
[Epoch 76/500] [Batch 420/676] [D loss: -0.032987] [G loss: -0.073478] [d1 loss: 0.155807] [d2 loss: 0.170824]  [sq d1 d2: 0.000226]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 440/676] [D loss: -0.023273] [G loss: -0.114841] [d1 loss: 0.174690] [d2 loss: 0.172524]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 460/676] [D loss: -0.015078] [G loss: -0.155537] [d1 loss: 0.064086] [d2 loss: 0.044344]  [sq d1 d2: 0.000390]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 480/676] [D loss: -0.049910] [G loss: -0.169964] [d1 loss: 0.138766] [d2 loss: 0.125441]  [sq d1 d2: 0.000178]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 500/676] [D loss: -0.019955] [G loss: -0.182716] [d1 loss: 0.159817] [d2 loss: 0.132357]  [sq d1 d2: 0.000754]  [num0: 17.000000] [num1 47.000000]
[Epoch 76/500] [Batch 520/676] [D loss: -0.015097] [G loss: -0.157752] [d1 loss: 0.040103] [d2 loss: 0.045627]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 76/500] [Batch 540/676] [D loss: 0.002802] [G loss: -0.176870] [d1 loss: 0.117587] [d2 loss: 0.098670]  [sq d1 d2: 0.000358]  [num0: 15.000000] [num1 49.000000]
[Epoch 76/500] [Batch 560/676] [D loss: 0.016984] [G loss: -0.178954] [d1 loss: 0.076362] [d2 loss: 0.082090]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 76/500] [Batch 580/676] [D loss: -0.002041] [G loss: -0.172586] [d1 loss: 0.115912] [d2 loss: 0.103528]  [sq d1 d2: 0.000153]  [num0: 18.000000] [num1 46.000000]
[Epoch 76/500] [Batch 600/676] [D loss: 0.003336] [G loss: -0.083105] [d1 loss: 0.063742] [d2 loss: 0.053559]  [sq d1 d2: 0.000104]  [num0: 12.000000] [num1 52.000000]
[Epoch 76/500] [Batch 620/676] [D loss: -0.028245] [G loss: -0.015833] [d1 loss: 0.058038] [d2 loss: 0.058090]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 76/500] [Batch 640/676] [D loss: -0.032641] [G loss: 0.021043] [d1 loss: 0.120631] [d2 loss: 0.124891]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 76/500] [Batch 660/676] [D loss: -0.023972] [G loss: 0.068075] [d1 loss: 0.090279] [d2 loss: 0.089107]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 0/676] [D loss: -0.033118] [G loss: 0.075740] [d1 loss: 0.173325] [d2 loss: 0.173344]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 77/500] [Batch 20/676] [D loss: -0.022711] [G loss: 0.058165] [d1 loss: 0.059079] [d2 loss: 0.062073]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 77/500] [Batch 40/676] [D loss: -0.056831] [G loss: 0.080764] [d1 loss: 0.113814] [d2 loss: 0.115366]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 77/500] [Batch 60/676] [D loss: -0.005853] [G loss: 0.074230] [d1 loss: 0.136158] [d2 loss: 0.121732]  [sq d1 d2: 0.000208]  [num0: 18.000000] [num1 46.000000]
[Epoch 77/500] [Batch 80/676] [D loss: -0.003833] [G loss: 0.053911] [d1 loss: 0.186764] [d2 loss: 0.197520]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 100/676] [D loss: -0.026392] [G loss: 0.018780] [d1 loss: 0.087015] [d2 loss: 0.072654]  [sq d1 d2: 0.000206]  [num0: 15.000000] [num1 49.000000]
[Epoch 77/500] [Batch 120/676] [D loss: -0.029338] [G loss: 0.009008] [d1 loss: 0.105290] [d2 loss: 0.071964]  [sq d1 d2: 0.001111]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 140/676] [D loss: -0.030294] [G loss: -0.017835] [d1 loss: 0.120713] [d2 loss: 0.128866]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 160/676] [D loss: -0.039379] [G loss: -0.075091] [d1 loss: 0.077252] [d2 loss: 0.074509]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 180/676] [D loss: -0.021408] [G loss: -0.123966] [d1 loss: 0.103087] [d2 loss: 0.086595]  [sq d1 d2: 0.000272]  [num0: 15.000000] [num1 49.000000]
[Epoch 77/500] [Batch 200/676] [D loss: -0.028168] [G loss: -0.157445] [d1 loss: 0.194819] [d2 loss: 0.204809]  [sq d1 d2: 0.000100]  [num0: 19.000000] [num1 45.000000]
[Epoch 77/500] [Batch 220/676] [D loss: -0.038373] [G loss: -0.150488] [d1 loss: 0.119019] [d2 loss: 0.115954]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 240/676] [D loss: 0.006004] [G loss: -0.140811] [d1 loss: 0.066066] [d2 loss: 0.068132]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 77/500] [Batch 260/676] [D loss: -0.031943] [G loss: -0.089599] [d1 loss: 0.100893] [d2 loss: 0.096208]  [sq d1 d2: 0.000022]  [num0: 11.000000] [num1 53.000000]
[Epoch 77/500] [Batch 280/676] [D loss: -0.006217] [G loss: -0.058424] [d1 loss: 0.176687] [d2 loss: 0.168180]  [sq d1 d2: 0.000072]  [num0: 19.000000] [num1 45.000000]
[Epoch 77/500] [Batch 300/676] [D loss: 0.005911] [G loss: -0.060575] [d1 loss: 0.097815] [d2 loss: 0.097368]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 77/500] [Batch 320/676] [D loss: -0.011459] [G loss: -0.021254] [d1 loss: 0.070793] [d2 loss: 0.083284]  [sq d1 d2: 0.000156]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 340/676] [D loss: -0.020324] [G loss: -0.027266] [d1 loss: 0.081056] [d2 loss: 0.076068]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 77/500] [Batch 360/676] [D loss: -0.043480] [G loss: 0.009981] [d1 loss: 0.124892] [d2 loss: 0.107328]  [sq d1 d2: 0.000308]  [num0: 18.000000] [num1 46.000000]
[Epoch 77/500] [Batch 380/676] [D loss: -0.037981] [G loss: 0.058375] [d1 loss: 0.122190] [d2 loss: 0.113566]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 400/676] [D loss: -0.043765] [G loss: 0.058578] [d1 loss: 0.134714] [d2 loss: 0.131345]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 420/676] [D loss: -0.023364] [G loss: 0.076962] [d1 loss: 0.150350] [d2 loss: 0.148102]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 440/676] [D loss: -0.047924] [G loss: 0.085728] [d1 loss: 0.099476] [d2 loss: 0.091316]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 77/500] [Batch 460/676] [D loss: -0.015669] [G loss: 0.066549] [d1 loss: 0.065043] [d2 loss: 0.067772]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 77/500] [Batch 480/676] [D loss: 0.002520] [G loss: 0.100635] [d1 loss: 0.136045] [d2 loss: 0.151390]  [sq d1 d2: 0.000235]  [num0: 18.000000] [num1 46.000000]
[Epoch 77/500] [Batch 500/676] [D loss: 0.018772] [G loss: 0.028439] [d1 loss: 0.123463] [d2 loss: 0.097935]  [sq d1 d2: 0.000652]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 520/676] [D loss: 0.002567] [G loss: 0.015865] [d1 loss: 0.184529] [d2 loss: 0.164933]  [sq d1 d2: 0.000384]  [num0: 17.000000] [num1 47.000000]
[Epoch 77/500] [Batch 540/676] [D loss: -0.002022] [G loss: 0.022332] [d1 loss: 0.093747] [d2 loss: 0.088511]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 77/500] [Batch 560/676] [D loss: -0.009504] [G loss: 0.019511] [d1 loss: 0.055347] [d2 loss: 0.046416]  [sq d1 d2: 0.000080]  [num0: 13.000000] [num1 51.000000]
[Epoch 77/500] [Batch 580/676] [D loss: -0.025780] [G loss: 0.022432] [d1 loss: 0.094497] [d2 loss: 0.088508]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 77/500] [Batch 600/676] [D loss: -0.043426] [G loss: -0.039588] [d1 loss: 0.156097] [d2 loss: 0.145174]  [sq d1 d2: 0.000119]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 620/676] [D loss: -0.050469] [G loss: -0.038973] [d1 loss: 0.119457] [d2 loss: 0.123316]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 77/500] [Batch 640/676] [D loss: -0.046158] [G loss: -0.083390] [d1 loss: 0.093787] [d2 loss: 0.063823]  [sq d1 d2: 0.000898]  [num0: 16.000000] [num1 48.000000]
[Epoch 77/500] [Batch 660/676] [D loss: -0.056595] [G loss: -0.147264] [d1 loss: 0.088419] [d2 loss: 0.082602]  [sq d1 d2: 0.000034]  [num0: 19.000000] [num1 45.000000]
[Epoch 78/500] [Batch 0/676] [D loss: -0.013701] [G loss: -0.121249] [d1 loss: 0.194158] [d2 loss: 0.179320]  [sq d1 d2: 0.000220]  [num0: 18.000000] [num1 46.000000]

[Epoch 78/500] [Batch 20/676] [D loss: -0.003239] [G loss: -0.151606] [d1 loss: 0.040139] [d2 loss: 0.044806]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 78/500] [Batch 40/676] [D loss: 0.014935] [G loss: -0.145279] [d1 loss: 0.076767] [d2 loss: 0.069751]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 60/676] [D loss: 0.002777] [G loss: -0.131162] [d1 loss: 0.065293] [d2 loss: 0.099801]  [sq d1 d2: 0.001191]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 80/676] [D loss: 0.001566] [G loss: -0.082150] [d1 loss: 0.060193] [d2 loss: 0.057052]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 100/676] [D loss: -0.018431] [G loss: -0.072573] [d1 loss: 0.070262] [d2 loss: 0.069319]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 78/500] [Batch 120/676] [D loss: -0.016071] [G loss: -0.049157] [d1 loss: 0.193697] [d2 loss: 0.210188]  [sq d1 d2: 0.000272]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 140/676] [D loss: -0.023610] [G loss: -0.046644] [d1 loss: 0.019888] [d2 loss: 0.022201]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 78/500] [Batch 160/676] [D loss: -0.014554] [G loss: -0.047516] [d1 loss: 0.101096] [d2 loss: 0.091778]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 78/500] [Batch 180/676] [D loss: -0.041835] [G loss: -0.049512] [d1 loss: 0.044382] [d2 loss: 0.041488]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 200/676] [D loss: -0.034357] [G loss: -0.049714] [d1 loss: 0.136845] [d2 loss: 0.139270]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 220/676] [D loss: -0.015678] [G loss: -0.072055] [d1 loss: 0.070173] [d2 loss: 0.054956]  [sq d1 d2: 0.000232]  [num0: 14.000000] [num1 50.000000]
[Epoch 78/500] [Batch 240/676] [D loss: -0.026351] [G loss: -0.085843] [d1 loss: 0.114162] [d2 loss: 0.126196]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 260/676] [D loss: -0.023713] [G loss: -0.075078] [d1 loss: 0.151071] [d2 loss: 0.144302]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 78/500] [Batch 280/676] [D loss: 0.006902] [G loss: -0.040465] [d1 loss: 0.087141] [d2 loss: 0.089329]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 300/676] [D loss: 0.007139] [G loss: -0.067234] [d1 loss: 0.077393] [d2 loss: 0.072255]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 78/500] [Batch 320/676] [D loss: -0.001477] [G loss: -0.044530] [d1 loss: 0.139890] [d2 loss: 0.128543]  [sq d1 d2: 0.000129]  [num0: 14.000000] [num1 50.000000]
[Epoch 78/500] [Batch 340/676] [D loss: -0.018195] [G loss: 0.007129] [d1 loss: 0.109905] [d2 loss: 0.115789]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 78/500] [Batch 360/676] [D loss: -0.025547] [G loss: 0.001067] [d1 loss: 0.094785] [d2 loss: 0.094142]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 78/500] [Batch 380/676] [D loss: -0.021062] [G loss: 0.004230] [d1 loss: 0.055817] [d2 loss: 0.049872]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 78/500] [Batch 400/676] [D loss: -0.030762] [G loss: -0.027765] [d1 loss: 0.089840] [d2 loss: 0.075656]  [sq d1 d2: 0.000201]  [num0: 17.000000] [num1 47.000000]
[Epoch 78/500] [Batch 420/676] [D loss: -0.022810] [G loss: -0.001262] [d1 loss: 0.137249] [d2 loss: 0.139833]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 78/500] [Batch 440/676] [D loss: -0.019076] [G loss: -0.027965] [d1 loss: 0.063717] [d2 loss: 0.062219]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 460/676] [D loss: -0.029731] [G loss: -0.000617] [d1 loss: 0.031204] [d2 loss: 0.028717]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 480/676] [D loss: -0.021121] [G loss: -0.025298] [d1 loss: 0.151057] [d2 loss: 0.148771]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 500/676] [D loss: -0.015987] [G loss: -0.034772] [d1 loss: 0.090422] [d2 loss: 0.086551]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 78/500] [Batch 520/676] [D loss: -0.006112] [G loss: -0.041109] [d1 loss: 0.128504] [d2 loss: 0.138626]  [sq d1 d2: 0.000102]  [num0: 14.000000] [num1 50.000000]
[Epoch 78/500] [Batch 540/676] [D loss: -0.008672] [G loss: -0.012628] [d1 loss: 0.114108] [d2 loss: 0.119289]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 78/500] [Batch 560/676] [D loss: -0.015827] [G loss: -0.040397] [d1 loss: 0.114039] [d2 loss: 0.090564]  [sq d1 d2: 0.000551]  [num0: 17.000000] [num1 47.000000]
[Epoch 78/500] [Batch 580/676] [D loss: -0.021186] [G loss: -0.026609] [d1 loss: 0.141401] [d2 loss: 0.166762]  [sq d1 d2: 0.000643]  [num0: 15.000000] [num1 49.000000]
[Epoch 78/500] [Batch 600/676] [D loss: -0.020759] [G loss: -0.020061] [d1 loss: 0.077472] [d2 loss: 0.064342]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 78/500] [Batch 620/676] [D loss: -0.004255] [G loss: -0.010583] [d1 loss: 0.059381] [d2 loss: 0.068755]  [sq d1 d2: 0.000088]  [num0: 18.000000] [num1 46.000000]
[Epoch 78/500] [Batch 640/676] [D loss: -0.018922] [G loss: -0.002584] [d1 loss: 0.085241] [d2 loss: 0.085234]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 78/500] [Batch 660/676] [D loss: -0.027477] [G loss: -0.020529] [d1 loss: 0.084278] [d2 loss: 0.080697]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 79/500] [Batch 0/676] [D loss: -0.011789] [G loss: -0.008235] [d1 loss: 0.235267] [d2 loss: 0.245700]  [sq d1 d2: 0.000109]  [num0: 20.000000] [num1 44.000000]
[Epoch 79/500] [Batch 20/676] [D loss: -0.016405] [G loss: 0.007428] [d1 loss: 0.072937] [d2 loss: 0.063728]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 40/676] [D loss: -0.021557] [G loss: -0.029971] [d1 loss: 0.130495] [d2 loss: 0.134616]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 79/500] [Batch 60/676] [D loss: -0.016508] [G loss: -0.026780] [d1 loss: 0.097015] [d2 loss: 0.081166]  [sq d1 d2: 0.000251]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 80/676] [D loss: -0.025100] [G loss: -0.036814] [d1 loss: 0.064768] [d2 loss: 0.070977]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 79/500] [Batch 100/676] [D loss: -0.022178] [G loss: -0.002025] [d1 loss: 0.045216] [d2 loss: 0.038731]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 79/500] [Batch 120/676] [D loss: -0.026580] [G loss: -0.044268] [d1 loss: 0.121241] [d2 loss: 0.116068]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 140/676] [D loss: -0.020779] [G loss: -0.028467] [d1 loss: 0.090969] [d2 loss: 0.088708]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 79/500] [Batch 160/676] [D loss: -0.016682] [G loss: -0.020765] [d1 loss: 0.079393] [d2 loss: 0.075946]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 180/676] [D loss: -0.026154] [G loss: -0.023313] [d1 loss: 0.098309] [d2 loss: 0.089958]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 79/500] [Batch 200/676] [D loss: -0.013631] [G loss: -0.023878] [d1 loss: 0.098709] [d2 loss: 0.106550]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 220/676] [D loss: -0.032797] [G loss: -0.017856] [d1 loss: 0.076834] [d2 loss: 0.069737]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 240/676] [D loss: -0.012076] [G loss: -0.005706] [d1 loss: 0.065993] [d2 loss: 0.075669]  [sq d1 d2: 0.000094]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 260/676] [D loss: -0.016292] [G loss: -0.037897] [d1 loss: 0.069610] [d2 loss: 0.084318]  [sq d1 d2: 0.000216]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 280/676] [D loss: -0.020691] [G loss: -0.014646] [d1 loss: 0.069730] [d2 loss: 0.060050]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 300/676] [D loss: -0.024604] [G loss: -0.031801] [d1 loss: 0.058825] [d2 loss: 0.054660]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 320/676] [D loss: -0.009759] [G loss: -0.004862] [d1 loss: 0.153581] [d2 loss: 0.151108]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 79/500] [Batch 340/676] [D loss: -0.019055] [G loss: -0.015743] [d1 loss: 0.108143] [d2 loss: 0.119702]  [sq d1 d2: 0.000134]  [num0: 14.000000] [num1 50.000000]

[Epoch 79/500] [Batch 360/676] [D loss: -0.019478] [G loss: 0.010850] [d1 loss: 0.147050] [d2 loss: 0.134444]  [sq d1 d2: 0.000159]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 380/676] [D loss: -0.031744] [G loss: -0.004718] [d1 loss: 0.119276] [d2 loss: 0.113872]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 79/500] [Batch 400/676] [D loss: -0.013761] [G loss: -0.046484] [d1 loss: 0.074491] [d2 loss: 0.074131]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 79/500] [Batch 420/676] [D loss: -0.014342] [G loss: -0.032578] [d1 loss: 0.160807] [d2 loss: 0.136667]  [sq d1 d2: 0.000583]  [num0: 16.000000] [num1 48.000000]
[Epoch 79/500] [Batch 440/676] [D loss: -0.018041] [G loss: -0.075305] [d1 loss: 0.065094] [d2 loss: 0.051884]  [sq d1 d2: 0.000174]  [num0: 18.000000] [num1 46.000000]
[Epoch 79/500] [Batch 460/676] [D loss: -0.026075] [G loss: -0.126625] [d1 loss: 0.088660] [d2 loss: 0.074072]  [sq d1 d2: 0.000213]  [num0: 14.000000] [num1 50.000000]
[Epoch 79/500] [Batch 480/676] [D loss: -0.041775] [G loss: -0.152607] [d1 loss: 0.101379] [d2 loss: 0.101947]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 79/500] [Batch 500/676] [D loss: -0.023218] [G loss: -0.168609] [d1 loss: 0.105250] [d2 loss: 0.089911]  [sq d1 d2: 0.000235]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 520/676] [D loss: -0.005869] [G loss: -0.179774] [d1 loss: 0.057363] [d2 loss: 0.046753]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 540/676] [D loss: -0.019089] [G loss: -0.181184] [d1 loss: 0.106586] [d2 loss: 0.127653]  [sq d1 d2: 0.000444]  [num0: 14.000000] [num1 50.000000]
[Epoch 79/500] [Batch 560/676] [D loss: -0.012310] [G loss: -0.212231] [d1 loss: 0.165270] [d2 loss: 0.159595]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 79/500] [Batch 580/676] [D loss: -0.014175] [G loss: -0.215652] [d1 loss: 0.049893] [d2 loss: 0.042745]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 79/500] [Batch 600/676] [D loss: -0.025445] [G loss: -0.218760] [d1 loss: 0.107919] [d2 loss: 0.104094]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 79/500] [Batch 620/676] [D loss: -0.005923] [G loss: -0.207907] [d1 loss: 0.065039] [d2 loss: 0.064527]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 79/500] [Batch 640/676] [D loss: -0.031060] [G loss: -0.201352] [d1 loss: 0.066168] [d2 loss: 0.065561]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 79/500] [Batch 660/676] [D loss: -0.037866] [G loss: -0.148884] [d1 loss: 0.053621] [d2 loss: 0.051552]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 80/500] [Batch 0/676] [D loss: -0.033081] [G loss: -0.122339] [d1 loss: 0.087933] [d2 loss: 0.055499]  [sq d1 d2: 0.001052]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 20/676] [D loss: -0.041520] [G loss: -0.103490] [d1 loss: 0.052035] [d2 loss: 0.064603]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 40/676] [D loss: -0.012343] [G loss: -0.109176] [d1 loss: 0.080106] [d2 loss: 0.075793]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 60/676] [D loss: -0.036767] [G loss: -0.104225] [d1 loss: 0.116449] [d2 loss: 0.113713]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 80/500] [Batch 80/676] [D loss: -0.023196] [G loss: -0.073350] [d1 loss: 0.105216] [d2 loss: 0.089561]  [sq d1 d2: 0.000245]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 100/676] [D loss: -0.017281] [G loss: -0.034180] [d1 loss: 0.089909] [d2 loss: 0.083367]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 80/500] [Batch 120/676] [D loss: -0.016412] [G loss: -0.002477] [d1 loss: 0.077947] [d2 loss: 0.066610]  [sq d1 d2: 0.000129]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 140/676] [D loss: -0.044945] [G loss: -0.020793] [d1 loss: 0.086826] [d2 loss: 0.092181]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 80/500] [Batch 160/676] [D loss: -0.035824] [G loss: -0.013315] [d1 loss: 0.183403] [d2 loss: 0.175653]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 80/500] [Batch 180/676] [D loss: -0.039473] [G loss: -0.046719] [d1 loss: 0.080385] [d2 loss: 0.070971]  [sq d1 d2: 0.000089]  [num0: 18.000000] [num1 46.000000]
[Epoch 80/500] [Batch 200/676] [D loss: -0.036689] [G loss: -0.072810] [d1 loss: 0.085070] [d2 loss: 0.077780]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 220/676] [D loss: -0.043278] [G loss: -0.085731] [d1 loss: 0.064302] [d2 loss: 0.076722]  [sq d1 d2: 0.000154]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 240/676] [D loss: -0.023353] [G loss: -0.074703] [d1 loss: 0.084396] [d2 loss: 0.075671]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 80/500] [Batch 260/676] [D loss: 0.003555] [G loss: -0.063668] [d1 loss: 0.106510] [d2 loss: 0.100287]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 280/676] [D loss: 0.001511] [G loss: -0.053056] [d1 loss: 0.211249] [d2 loss: 0.180819]  [sq d1 d2: 0.000926]  [num0: 12.000000] [num1 52.000000]
[Epoch 80/500] [Batch 300/676] [D loss: 0.013683] [G loss: -0.063000] [d1 loss: 0.138255] [d2 loss: 0.118155]  [sq d1 d2: 0.000404]  [num0: 16.000000] [num1 48.000000]
[Epoch 80/500] [Batch 320/676] [D loss: -0.021217] [G loss: -0.052435] [d1 loss: 0.228485] [d2 loss: 0.229236]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 340/676] [D loss: -0.024973] [G loss: 0.002590] [d1 loss: 0.048354] [d2 loss: 0.047637]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 80/500] [Batch 360/676] [D loss: -0.035564] [G loss: -0.037954] [d1 loss: 0.124222] [d2 loss: 0.121312]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 380/676] [D loss: -0.066165] [G loss: -0.031776] [d1 loss: 0.074519] [d2 loss: 0.058064]  [sq d1 d2: 0.000271]  [num0: 13.000000] [num1 51.000000]
[Epoch 80/500] [Batch 400/676] [D loss: -0.067790] [G loss: -0.032306] [d1 loss: 0.054303] [d2 loss: 0.049893]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 420/676] [D loss: -0.042054] [G loss: -0.007928] [d1 loss: 0.091068] [d2 loss: 0.082821]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 80/500] [Batch 440/676] [D loss: -0.023104] [G loss: -0.004601] [d1 loss: 0.193844] [d2 loss: 0.218876]  [sq d1 d2: 0.000627]  [num0: 18.000000] [num1 46.000000]
[Epoch 80/500] [Batch 460/676] [D loss: -0.033007] [G loss: 0.015060] [d1 loss: 0.125664] [d2 loss: 0.124186]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 80/500] [Batch 480/676] [D loss: -0.011859] [G loss: 0.026471] [d1 loss: 0.128608] [d2 loss: 0.127318]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 80/500] [Batch 500/676] [D loss: 0.014506] [G loss: -0.006536] [d1 loss: 0.085162] [d2 loss: 0.086461]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 80/500] [Batch 520/676] [D loss: 0.014209] [G loss: -0.011907] [d1 loss: 0.086801] [d2 loss: 0.087199]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 80/500] [Batch 540/676] [D loss: -0.014049] [G loss: -0.059583] [d1 loss: 0.164254] [d2 loss: 0.161164]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 80/500] [Batch 560/676] [D loss: -0.031676] [G loss: -0.141645] [d1 loss: 0.176182] [d2 loss: 0.176426]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 80/500] [Batch 580/676] [D loss: -0.049861] [G loss: -0.186461] [d1 loss: 0.144940] [d2 loss: 0.123847]  [sq d1 d2: 0.000445]  [num0: 20.000000] [num1 44.000000]
[Epoch 80/500] [Batch 600/676] [D loss: -0.043273] [G loss: -0.276454] [d1 loss: 0.073298] [d2 loss: 0.072664]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 80/500] [Batch 620/676] [D loss: -0.073592] [G loss: -0.348425] [d1 loss: 0.113967] [d2 loss: 0.121625]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 80/500] [Batch 640/676] [D loss: -0.050926] [G loss: -0.417595] [d1 loss: 0.112035] [d2 loss: 0.107887]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]

[Epoch 80/500] [Batch 660/676] [D loss: -0.045926] [G loss: -0.469137] [d1 loss: 0.110645] [d2 loss: 0.097266]  [sq d1 d2: 0.000179]  [num0: 17.000000] [num1 47.000000]
[Epoch 81/500] [Batch 0/676] [D loss: 0.066072] [G loss: -0.467243] [d1 loss: 0.094047] [d2 loss: 0.099996]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 81/500] [Batch 20/676] [D loss: 0.000625] [G loss: -0.312059] [d1 loss: 0.082772] [d2 loss: 0.058807]  [sq d1 d2: 0.000574]  [num0: 12.000000] [num1 52.000000]
[Epoch 81/500] [Batch 40/676] [D loss: 0.006198] [G loss: -0.193583] [d1 loss: 0.099737] [d2 loss: 0.097153]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 81/500] [Batch 60/676] [D loss: 0.001710] [G loss: -0.115127] [d1 loss: 0.179218] [d2 loss: 0.150798]  [sq d1 d2: 0.000808]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 80/676] [D loss: -0.006691] [G loss: -0.071600] [d1 loss: 0.074854] [d2 loss: 0.058426]  [sq d1 d2: 0.000270]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 100/676] [D loss: -0.027438] [G loss: -0.069150] [d1 loss: 0.115605] [d2 loss: 0.096589]  [sq d1 d2: 0.000362]  [num0: 10.000000] [num1 54.000000]
[Epoch 81/500] [Batch 120/676] [D loss: -0.036949] [G loss: -0.029516] [d1 loss: 0.091898] [d2 loss: 0.085182]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 81/500] [Batch 140/676] [D loss: -0.036967] [G loss: -0.023555] [d1 loss: 0.123541] [d2 loss: 0.112610]  [sq d1 d2: 0.000120]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 160/676] [D loss: -0.060184] [G loss: -0.000879] [d1 loss: 0.138204] [d2 loss: 0.125641]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 180/676] [D loss: -0.050969] [G loss: 0.037994] [d1 loss: 0.126983] [d2 loss: 0.142142]  [sq d1 d2: 0.000230]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 200/676] [D loss: -0.028358] [G loss: 0.038981] [d1 loss: 0.054083] [d2 loss: 0.054768]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 220/676] [D loss: -0.061943] [G loss: 0.019504] [d1 loss: 0.069441] [d2 loss: 0.062005]  [sq d1 d2: 0.000055]  [num0: 19.000000] [num1 45.000000]
[Epoch 81/500] [Batch 240/676] [D loss: -0.009835] [G loss: 0.023697] [d1 loss: 0.036750] [d2 loss: 0.033695]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 260/676] [D loss: 0.000066] [G loss: 0.005311] [d1 loss: 0.097964] [d2 loss: 0.100402]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 280/676] [D loss: 0.015168] [G loss: -0.009115] [d1 loss: 0.050195] [d2 loss: 0.047941]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 300/676] [D loss: -0.001934] [G loss: -0.005146] [d1 loss: 0.072385] [d2 loss: 0.068647]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 320/676] [D loss: -0.009559] [G loss: 0.003957] [d1 loss: 0.067300] [d2 loss: 0.061312]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 340/676] [D loss: -0.024399] [G loss: 0.013691] [d1 loss: 0.068991] [d2 loss: 0.087195]  [sq d1 d2: 0.000331]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 360/676] [D loss: -0.040155] [G loss: -0.002553] [d1 loss: 0.046079] [d2 loss: 0.037712]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 380/676] [D loss: -0.048713] [G loss: -0.073098] [d1 loss: 0.099764] [d2 loss: 0.088710]  [sq d1 d2: 0.000122]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 400/676] [D loss: -0.050441] [G loss: -0.125945] [d1 loss: 0.107020] [d2 loss: 0.085071]  [sq d1 d2: 0.000482]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 420/676] [D loss: -0.038517] [G loss: -0.197964] [d1 loss: 0.126938] [d2 loss: 0.120759]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 440/676] [D loss: 0.007899] [G loss: -0.262955] [d1 loss: 0.090097] [d2 loss: 0.090914]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 460/676] [D loss: -0.034416] [G loss: -0.267727] [d1 loss: 0.096165] [d2 loss: 0.086551]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 81/500] [Batch 480/676] [D loss: 0.011874] [G loss: -0.231005] [d1 loss: 0.027578] [d2 loss: 0.030797]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 500/676] [D loss: 0.012269] [G loss: -0.157075] [d1 loss: 0.100867] [d2 loss: 0.110581]  [sq d1 d2: 0.000094]  [num0: 10.000000] [num1 54.000000]
[Epoch 81/500] [Batch 520/676] [D loss: -0.001238] [G loss: -0.091490] [d1 loss: 0.073633] [d2 loss: 0.065371]  [sq d1 d2: 0.000068]  [num0: 13.000000] [num1 51.000000]
[Epoch 81/500] [Batch 540/676] [D loss: -0.013016] [G loss: -0.030230] [d1 loss: 0.031380] [d2 loss: 0.030822]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 560/676] [D loss: -0.021964] [G loss: 0.037623] [d1 loss: 0.103891] [d2 loss: 0.082287]  [sq d1 d2: 0.000467]  [num0: 17.000000] [num1 47.000000]
[Epoch 81/500] [Batch 580/676] [D loss: -0.050456] [G loss: 0.148079] [d1 loss: 0.054532] [d2 loss: 0.059539]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 81/500] [Batch 600/676] [D loss: -0.064983] [G loss: 0.203878] [d1 loss: 0.041872] [d2 loss: 0.037953]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 81/500] [Batch 620/676] [D loss: -0.066446] [G loss: 0.216967] [d1 loss: 0.108492] [d2 loss: 0.091809]  [sq d1 d2: 0.000278]  [num0: 15.000000] [num1 49.000000]
[Epoch 81/500] [Batch 640/676] [D loss: -0.067798] [G loss: 0.225900] [d1 loss: 0.091261] [d2 loss: 0.089638]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 81/500] [Batch 660/676] [D loss: -0.016790] [G loss: 0.170080] [d1 loss: 0.135045] [d2 loss: 0.142441]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 0/676] [D loss: -0.013729] [G loss: 0.157141] [d1 loss: 0.103451] [d2 loss: 0.117918]  [sq d1 d2: 0.000209]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 20/676] [D loss: 0.003661] [G loss: 0.129984] [d1 loss: 0.117953] [d2 loss: 0.113847]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 82/500] [Batch 40/676] [D loss: 0.016092] [G loss: 0.076707] [d1 loss: 0.038930] [d2 loss: 0.064903]  [sq d1 d2: 0.000675]  [num0: 12.000000] [num1 52.000000]
[Epoch 82/500] [Batch 60/676] [D loss: 0.003517] [G loss: 0.084292] [d1 loss: 0.093218] [d2 loss: 0.088288]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 80/676] [D loss: -0.012646] [G loss: 0.046897] [d1 loss: 0.078657] [d2 loss: 0.075211]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 82/500] [Batch 100/676] [D loss: -0.021997] [G loss: 0.028308] [d1 loss: 0.101746] [d2 loss: 0.082059]  [sq d1 d2: 0.000388]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 120/676] [D loss: -0.039914] [G loss: -0.031754] [d1 loss: 0.145393] [d2 loss: 0.164492]  [sq d1 d2: 0.000365]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 140/676] [D loss: -0.048180] [G loss: -0.087335] [d1 loss: 0.054410] [d2 loss: 0.059497]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 160/676] [D loss: -0.054613] [G loss: -0.112074] [d1 loss: 0.164473] [d2 loss: 0.170838]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 180/676] [D loss: -0.039630] [G loss: -0.162001] [d1 loss: 0.121616] [d2 loss: 0.100500]  [sq d1 d2: 0.000446]  [num0: 13.000000] [num1 51.000000]
[Epoch 82/500] [Batch 200/676] [D loss: -0.034190] [G loss: -0.187949] [d1 loss: 0.103736] [d2 loss: 0.145603]  [sq d1 d2: 0.001753]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 220/676] [D loss: 0.003397] [G loss: -0.173740] [d1 loss: 0.120748] [d2 loss: 0.129616]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 240/676] [D loss: 0.009747] [G loss: -0.136714] [d1 loss: 0.074823] [d2 loss: 0.073832]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 82/500] [Batch 260/676] [D loss: 0.010408] [G loss: -0.090318] [d1 loss: 0.068076] [d2 loss: 0.074905]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 82/500] [Batch 280/676] [D loss: -0.006131] [G loss: -0.057244] [d1 loss: 0.121219] [d2 loss: 0.121913]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 82/500] [Batch 300/676] [D loss: -0.016898] [G loss: -0.034094] [d1 loss: 0.149650] [d2 loss: 0.135550]  [sq d1 d2: 0.000199]  [num0: 17.000000] [num1 47.000000]

[Epoch 82/500] [Batch 320/676] [D loss: -0.023218] [G loss: 0.000183] [d1 loss: 0.033565] [d2 loss: 0.034454]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 340/676] [D loss: -0.026678] [G loss: 0.033297] [d1 loss: 0.067711] [d2 loss: 0.075507]  [sq d1 d2: 0.000061]  [num0: 20.000000] [num1 44.000000]
[Epoch 82/500] [Batch 360/676] [D loss: -0.026200] [G loss: 0.061439] [d1 loss: 0.121359] [d2 loss: 0.131983]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 380/676] [D loss: -0.022519] [G loss: 0.071149] [d1 loss: 0.055667] [d2 loss: 0.056248]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 82/500] [Batch 400/676] [D loss: -0.008270] [G loss: 0.053896] [d1 loss: 0.136526] [d2 loss: 0.136583]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 82/500] [Batch 420/676] [D loss: -0.036635] [G loss: 0.076507] [d1 loss: 0.105471] [d2 loss: 0.105232]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 440/676] [D loss: -0.006384] [G loss: 0.034713] [d1 loss: 0.129443] [d2 loss: 0.132478]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 460/676] [D loss: 0.020504] [G loss: 0.022328] [d1 loss: 0.149442] [d2 loss: 0.151175]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 82/500] [Batch 480/676] [D loss: -0.023035] [G loss: 0.004182] [d1 loss: 0.178767] [d2 loss: 0.163052]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 500/676] [D loss: -0.024397] [G loss: -0.031824] [d1 loss: 0.080279] [d2 loss: 0.087794]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 520/676] [D loss: -0.023331] [G loss: -0.005422] [d1 loss: 0.131578] [d2 loss: 0.140833]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 82/500] [Batch 540/676] [D loss: -0.049550] [G loss: 0.013613] [d1 loss: 0.082989] [d2 loss: 0.074650]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 560/676] [D loss: -0.013423] [G loss: -0.027330] [d1 loss: 0.042912] [d2 loss: 0.042085]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 580/676] [D loss: -0.033278] [G loss: -0.049131] [d1 loss: 0.097222] [d2 loss: 0.089204]  [sq d1 d2: 0.000064]  [num0: 12.000000] [num1 52.000000]
[Epoch 82/500] [Batch 600/676] [D loss: -0.000036] [G loss: -0.089160] [d1 loss: 0.043414] [d2 loss: 0.043751]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 82/500] [Batch 620/676] [D loss: -0.026976] [G loss: -0.098041] [d1 loss: 0.083146] [d2 loss: 0.074479]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 82/500] [Batch 640/676] [D loss: -0.031561] [G loss: -0.122051] [d1 loss: 0.072834] [d2 loss: 0.068131]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 82/500] [Batch 660/676] [D loss: 0.001583] [G loss: -0.114777] [d1 loss: 0.154109] [d2 loss: 0.142921]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 83/500] [Batch 0/676] [D loss: -0.001615] [G loss: -0.106222] [d1 loss: 0.059484] [d2 loss: 0.049186]  [sq d1 d2: 0.000106]  [num0: 15.000000] [num1 49.000000]
[Epoch 83/500] [Batch 20/676] [D loss: -0.006805] [G loss: -0.065269] [d1 loss: 0.063291] [d2 loss: 0.066744]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 83/500] [Batch 40/676] [D loss: -0.025172] [G loss: -0.043512] [d1 loss: 0.144434] [d2 loss: 0.120652]  [sq d1 d2: 0.000566]  [num0: 15.000000] [num1 49.000000]
[Epoch 83/500] [Batch 60/676] [D loss: -0.027768] [G loss: -0.041412] [d1 loss: 0.072549] [d2 loss: 0.064755]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 80/676] [D loss: -0.044024] [G loss: -0.003245] [d1 loss: 0.124480] [d2 loss: 0.105749]  [sq d1 d2: 0.000351]  [num0: 21.000000] [num1 43.000000]
[Epoch 83/500] [Batch 100/676] [D loss: -0.037926] [G loss: 0.037906] [d1 loss: 0.038479] [d2 loss: 0.034512]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 83/500] [Batch 120/676] [D loss: -0.056107] [G loss: 0.047992] [d1 loss: 0.094140] [d2 loss: 0.079439]  [sq d1 d2: 0.000216]  [num0: 13.000000] [num1 51.000000]
[Epoch 83/500] [Batch 140/676] [D loss: -0.009712] [G loss: 0.076959] [d1 loss: 0.105285] [d2 loss: 0.114689]  [sq d1 d2: 0.000088]  [num0: 13.000000] [num1 51.000000]
[Epoch 83/500] [Batch 160/676] [D loss: -0.013576] [G loss: 0.078181] [d1 loss: 0.063006] [d2 loss: 0.057929]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 83/500] [Batch 180/676] [D loss: -0.002978] [G loss: 0.053568] [d1 loss: 0.221337] [d2 loss: 0.179023]  [sq d1 d2: 0.001790]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 200/676] [D loss: 0.022733] [G loss: 0.028140] [d1 loss: 0.081255] [d2 loss: 0.069668]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 83/500] [Batch 220/676] [D loss: 0.001149] [G loss: 0.006850] [d1 loss: 0.160415] [d2 loss: 0.147710]  [sq d1 d2: 0.000161]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 240/676] [D loss: -0.010001] [G loss: 0.021118] [d1 loss: 0.059574] [d2 loss: 0.056683]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 83/500] [Batch 260/676] [D loss: -0.035786] [G loss: 0.048029] [d1 loss: 0.119797] [d2 loss: 0.093517]  [sq d1 d2: 0.000691]  [num0: 14.000000] [num1 50.000000]
[Epoch 83/500] [Batch 280/676] [D loss: -0.002480] [G loss: 0.031644] [d1 loss: 0.095006] [d2 loss: 0.087172]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 300/676] [D loss: -0.043850] [G loss: -0.031665] [d1 loss: 0.066877] [d2 loss: 0.061372]  [sq d1 d2: 0.000030]  [num0: 19.000000] [num1 45.000000]
[Epoch 83/500] [Batch 320/676] [D loss: -0.012857] [G loss: -0.043093] [d1 loss: 0.056288] [d2 loss: 0.052070]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 83/500] [Batch 340/676] [D loss: -0.011853] [G loss: -0.026083] [d1 loss: 0.082682] [d2 loss: 0.094429]  [sq d1 d2: 0.000138]  [num0: 17.000000] [num1 47.000000]
[Epoch 83/500] [Batch 360/676] [D loss: 0.003222] [G loss: -0.085072] [d1 loss: 0.145978] [d2 loss: 0.137245]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 380/676] [D loss: 0.011442] [G loss: -0.105758] [d1 loss: 0.086767] [d2 loss: 0.075616]  [sq d1 d2: 0.000124]  [num0: 13.000000] [num1 51.000000]
[Epoch 83/500] [Batch 400/676] [D loss: -0.007238] [G loss: -0.081421] [d1 loss: 0.088585] [d2 loss: 0.077235]  [sq d1 d2: 0.000129]  [num0: 12.000000] [num1 52.000000]
[Epoch 83/500] [Batch 420/676] [D loss: -0.000636] [G loss: -0.069198] [d1 loss: 0.072050] [d2 loss: 0.061320]  [sq d1 d2: 0.000115]  [num0: 18.000000] [num1 46.000000]
[Epoch 83/500] [Batch 440/676] [D loss: -0.015108] [G loss: -0.054822] [d1 loss: 0.094606] [d2 loss: 0.097382]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 83/500] [Batch 460/676] [D loss: -0.022040] [G loss: -0.011603] [d1 loss: 0.091921] [d2 loss: 0.074367]  [sq d1 d2: 0.000308]  [num0: 14.000000] [num1 50.000000]
[Epoch 83/500] [Batch 480/676] [D loss: -0.021726] [G loss: 0.045625] [d1 loss: 0.153707] [d2 loss: 0.150091]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 83/500] [Batch 500/676] [D loss: -0.033791] [G loss: 0.044754] [d1 loss: 0.089017] [d2 loss: 0.082784]  [sq d1 d2: 0.000039]  [num0: 20.000000] [num1 44.000000]
[Epoch 83/500] [Batch 520/676] [D loss: -0.029898] [G loss: 0.050358] [d1 loss: 0.161038] [d2 loss: 0.118822]  [sq d1 d2: 0.001782]  [num0: 17.000000] [num1 47.000000]
[Epoch 83/500] [Batch 540/676] [D loss: 0.001323] [G loss: 0.061147] [d1 loss: 0.107176] [d2 loss: 0.108031]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 83/500] [Batch 560/676] [D loss: 0.012381] [G loss: 0.053118] [d1 loss: 0.114391] [d2 loss: 0.136156]  [sq d1 d2: 0.000474]  [num0: 8.000000] [num1 56.000000]
[Epoch 83/500] [Batch 580/676] [D loss: 0.006891] [G loss: 0.083612] [d1 loss: 0.089138] [d2 loss: 0.055421]  [sq d1 d2: 0.001137]  [num0: 16.000000] [num1 48.000000]
[Epoch 83/500] [Batch 600/676] [D loss: -0.000640] [G loss: 0.065070] [d1 loss: 0.104835] [d2 loss: 0.111385]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 83/500] [Batch 620/676] [D loss: -0.022528] [G loss: 0.135047] [d1 loss: 0.100176] [d2 loss: 0.100779]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 83/500] [Batch 640/676] [D loss: -0.047468] [G loss: 0.127493] [d1 loss: 0.107787] [d2 loss: 0.079750]  [sq d1 d2: 0.000786]  [num0: 13.000000] [num1 51.000000]

[Epoch 83/500] [Batch 660/676] [D loss: -0.022920] [G loss: 0.082889] [d1 loss: 0.091883] [d2 loss: 0.073259]  [sq d1 d2: 0.000347]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 0/676] [D loss: -0.023099] [G loss: 0.096755] [d1 loss: 0.114386] [d2 loss: 0.121512]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 84/500] [Batch 20/676] [D loss: -0.034141] [G loss: 0.044020] [d1 loss: 0.092610] [d2 loss: 0.096105]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 40/676] [D loss: -0.018625] [G loss: 0.020973] [d1 loss: 0.260447] [d2 loss: 0.242879]  [sq d1 d2: 0.000309]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 60/676] [D loss: -0.037285] [G loss: -0.007337] [d1 loss: 0.103759] [d2 loss: 0.090055]  [sq d1 d2: 0.000188]  [num0: 12.000000] [num1 52.000000]
[Epoch 84/500] [Batch 80/676] [D loss: 0.005786] [G loss: -0.005191] [d1 loss: 0.090664] [d2 loss: 0.089282]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 84/500] [Batch 100/676] [D loss: 0.002576] [G loss: -0.025439] [d1 loss: 0.138760] [d2 loss: 0.082298]  [sq d1 d2: 0.003188]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 120/676] [D loss: -0.008329] [G loss: -0.068113] [d1 loss: 0.119189] [d2 loss: 0.129833]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 84/500] [Batch 140/676] [D loss: -0.004279] [G loss: -0.070772] [d1 loss: 0.128544] [d2 loss: 0.112604]  [sq d1 d2: 0.000254]  [num0: 13.000000] [num1 51.000000]
[Epoch 84/500] [Batch 160/676] [D loss: -0.029142] [G loss: -0.058011] [d1 loss: 0.053630] [d2 loss: 0.052196]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 84/500] [Batch 180/676] [D loss: -0.020865] [G loss: -0.033288] [d1 loss: 0.082508] [d2 loss: 0.071381]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 84/500] [Batch 200/676] [D loss: -0.030128] [G loss: -0.028176] [d1 loss: 0.129089] [d2 loss: 0.110222]  [sq d1 d2: 0.000356]  [num0: 11.000000] [num1 53.000000]
[Epoch 84/500] [Batch 220/676] [D loss: -0.035637] [G loss: -0.042899] [d1 loss: 0.069064] [d2 loss: 0.064169]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 240/676] [D loss: -0.022026] [G loss: -0.036904] [d1 loss: 0.086293] [d2 loss: 0.088961]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 84/500] [Batch 260/676] [D loss: 0.028494] [G loss: -0.065487] [d1 loss: 0.114552] [d2 loss: 0.110078]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 84/500] [Batch 280/676] [D loss: -0.002109] [G loss: -0.074548] [d1 loss: 0.167958] [d2 loss: 0.159731]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 300/676] [D loss: 0.003134] [G loss: -0.081842] [d1 loss: 0.074877] [d2 loss: 0.084222]  [sq d1 d2: 0.000087]  [num0: 14.000000] [num1 50.000000]
[Epoch 84/500] [Batch 320/676] [D loss: -0.009864] [G loss: -0.068471] [d1 loss: 0.110641] [d2 loss: 0.088446]  [sq d1 d2: 0.000493]  [num0: 12.000000] [num1 52.000000]
[Epoch 84/500] [Batch 340/676] [D loss: -0.037741] [G loss: -0.050335] [d1 loss: 0.041879] [d2 loss: 0.030495]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 360/676] [D loss: -0.038364] [G loss: -0.031980] [d1 loss: 0.105209] [d2 loss: 0.105844]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 380/676] [D loss: -0.031070] [G loss: -0.034667] [d1 loss: 0.076056] [d2 loss: 0.071100]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 84/500] [Batch 400/676] [D loss: -0.058559] [G loss: -0.049871] [d1 loss: 0.084742] [d2 loss: 0.085853]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 420/676] [D loss: -0.020427] [G loss: -0.096722] [d1 loss: 0.093460] [d2 loss: 0.108730]  [sq d1 d2: 0.000233]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 440/676] [D loss: 0.028703] [G loss: -0.089579] [d1 loss: 0.098552] [d2 loss: 0.080711]  [sq d1 d2: 0.000318]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 460/676] [D loss: -0.001201] [G loss: -0.067934] [d1 loss: 0.096639] [d2 loss: 0.076454]  [sq d1 d2: 0.000407]  [num0: 19.000000] [num1 45.000000]
[Epoch 84/500] [Batch 480/676] [D loss: 0.010568] [G loss: -0.080859] [d1 loss: 0.087963] [d2 loss: 0.082221]  [sq d1 d2: 0.000033]  [num0: 12.000000] [num1 52.000000]
[Epoch 84/500] [Batch 500/676] [D loss: -0.003112] [G loss: -0.081032] [d1 loss: 0.050771] [d2 loss: 0.049583]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 520/676] [D loss: -0.010129] [G loss: -0.058019] [d1 loss: 0.129197] [d2 loss: 0.125964]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 84/500] [Batch 540/676] [D loss: -0.012824] [G loss: -0.023861] [d1 loss: 0.231432] [d2 loss: 0.217469]  [sq d1 d2: 0.000195]  [num0: 13.000000] [num1 51.000000]
[Epoch 84/500] [Batch 560/676] [D loss: -0.053980] [G loss: 0.045701] [d1 loss: 0.108531] [d2 loss: 0.097405]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 580/676] [D loss: -0.070173] [G loss: 0.084185] [d1 loss: 0.070837] [d2 loss: 0.072402]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 84/500] [Batch 600/676] [D loss: 0.000948] [G loss: 0.092878] [d1 loss: 0.161260] [d2 loss: 0.124755]  [sq d1 d2: 0.001333]  [num0: 15.000000] [num1 49.000000]
[Epoch 84/500] [Batch 620/676] [D loss: -0.032757] [G loss: 0.079698] [d1 loss: 0.140313] [d2 loss: 0.147442]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 84/500] [Batch 640/676] [D loss: -0.049206] [G loss: 0.062940] [d1 loss: 0.082824] [d2 loss: 0.072522]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 84/500] [Batch 660/676] [D loss: -0.018342] [G loss: 0.021947] [d1 loss: 0.078641] [d2 loss: 0.075888]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 85/500] [Batch 0/676] [D loss: 0.009465] [G loss: -0.006319] [d1 loss: 0.068993] [d2 loss: 0.063180]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 85/500] [Batch 20/676] [D loss: 0.002139] [G loss: -0.008295] [d1 loss: 0.115298] [d2 loss: 0.104563]  [sq d1 d2: 0.000115]  [num0: 16.000000] [num1 48.000000]
[Epoch 85/500] [Batch 40/676] [D loss: -0.004464] [G loss: -0.017201] [d1 loss: 0.108793] [d2 loss: 0.099007]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 85/500] [Batch 60/676] [D loss: -0.030455] [G loss: -0.019318] [d1 loss: 0.057607] [d2 loss: 0.057277]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 85/500] [Batch 80/676] [D loss: -0.061509] [G loss: 0.020179] [d1 loss: 0.095152] [d2 loss: 0.087147]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 85/500] [Batch 100/676] [D loss: -0.028558] [G loss: -0.003010] [d1 loss: 0.179446] [d2 loss: 0.182559]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 85/500] [Batch 120/676] [D loss: -0.030797] [G loss: -0.028020] [d1 loss: 0.107212] [d2 loss: 0.119689]  [sq d1 d2: 0.000156]  [num0: 12.000000] [num1 52.000000]
[Epoch 85/500] [Batch 140/676] [D loss: -0.035020] [G loss: -0.027807] [d1 loss: 0.124153] [d2 loss: 0.107417]  [sq d1 d2: 0.000280]  [num0: 21.000000] [num1 43.000000]
[Epoch 85/500] [Batch 160/676] [D loss: -0.007662] [G loss: -0.061946] [d1 loss: 0.090862] [d2 loss: 0.093842]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 85/500] [Batch 180/676] [D loss: 0.012515] [G loss: -0.090564] [d1 loss: 0.178575] [d2 loss: 0.159779]  [sq d1 d2: 0.000353]  [num0: 19.000000] [num1 45.000000]
[Epoch 85/500] [Batch 200/676] [D loss: 0.006833] [G loss: -0.098288] [d1 loss: 0.103030] [d2 loss: 0.095784]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 85/500] [Batch 220/676] [D loss: -0.000616] [G loss: -0.096523] [d1 loss: 0.129886] [d2 loss: 0.098797]  [sq d1 d2: 0.000967]  [num0: 15.000000] [num1 49.000000]
[Epoch 85/500] [Batch 240/676] [D loss: -0.006952] [G loss: -0.103019] [d1 loss: 0.174949] [d2 loss: 0.206967]  [sq d1 d2: 0.001025]  [num0: 15.000000] [num1 49.000000]
[Epoch 85/500] [Batch 260/676] [D loss: -0.021085] [G loss: -0.119668] [d1 loss: 0.080722] [d2 loss: 0.076729]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]

[Epoch 85/500] [Batch 280/676] [D loss: -0.021142] [G loss: -0.114984] [d1 loss: 0.089203] [d2 loss: 0.069300]  [sq d1 d2: 0.000396]  [num0: 19.000000] [num1 45.000000]
[Epoch 85/500] [Batch 300/676] [D loss: -0.037201] [G loss: -0.123062] [d1 loss: 0.164183] [d2 loss: 0.146111]  [sq d1 d2: 0.000327]  [num0: 19.000000] [num1 45.000000]
[Epoch 85/500] [Batch 320/676] [D loss: -0.010219] [G loss: -0.116510] [d1 loss: 0.079560] [d2 loss: 0.083265]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 85/500] [Batch 340/676] [D loss: -0.036074] [G loss: -0.086560] [d1 loss: 0.043519] [d2 loss: 0.051192]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 85/500] [Batch 360/676] [D loss: 0.005970] [G loss: -0.043399] [d1 loss: 0.113238] [d2 loss: 0.090841]  [sq d1 d2: 0.000502]  [num0: 13.000000] [num1 51.000000]
[Epoch 85/500] [Batch 380/676] [D loss: 0.004557] [G loss: -0.047727] [d1 loss: 0.214750] [d2 loss: 0.199839]  [sq d1 d2: 0.000222]  [num0: 15.000000] [num1 49.000000]
[Epoch 85/500] [Batch 400/676] [D loss: -0.017818] [G loss: -0.047623] [d1 loss: 0.116915] [d2 loss: 0.089409]  [sq d1 d2: 0.000757]  [num0: 14.000000] [num1 50.000000]
[Epoch 85/500] [Batch 420/676] [D loss: 0.006828] [G loss: -0.076573] [d1 loss: 0.087421] [d2 loss: 0.086941]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 85/500] [Batch 440/676] [D loss: -0.003882] [G loss: -0.032230] [d1 loss: 0.061527] [d2 loss: 0.062722]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 85/500] [Batch 460/676] [D loss: -0.001909] [G loss: -0.018394] [d1 loss: 0.062626] [d2 loss: 0.064881]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 85/500] [Batch 480/676] [D loss: -0.004500] [G loss: -0.004291] [d1 loss: 0.119968] [d2 loss: 0.105109]  [sq d1 d2: 0.000221]  [num0: 16.000000] [num1 48.000000]
[Epoch 85/500] [Batch 500/676] [D loss: -0.019189] [G loss: 0.011190] [d1 loss: 0.087823] [d2 loss: 0.074262]  [sq d1 d2: 0.000184]  [num0: 18.000000] [num1 46.000000]
[Epoch 85/500] [Batch 520/676] [D loss: -0.022296] [G loss: 0.040282] [d1 loss: 0.149844] [d2 loss: 0.126160]  [sq d1 d2: 0.000561]  [num0: 16.000000] [num1 48.000000]
[Epoch 85/500] [Batch 540/676] [D loss: -0.065327] [G loss: 0.034599] [d1 loss: 0.113120] [d2 loss: 0.116802]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 85/500] [Batch 560/676] [D loss: -0.026157] [G loss: 0.000646] [d1 loss: 0.081266] [d2 loss: 0.090339]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 85/500] [Batch 580/676] [D loss: 0.012016] [G loss: -0.022048] [d1 loss: 0.077916] [d2 loss: 0.069478]  [sq d1 d2: 0.000071]  [num0: 20.000000] [num1 44.000000]
[Epoch 85/500] [Batch 600/676] [D loss: -0.007502] [G loss: -0.062520] [d1 loss: 0.083781] [d2 loss: 0.080611]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 85/500] [Batch 620/676] [D loss: 0.007117] [G loss: -0.074782] [d1 loss: 0.068334] [d2 loss: 0.062961]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 85/500] [Batch 640/676] [D loss: -0.001097] [G loss: -0.065220] [d1 loss: 0.127401] [d2 loss: 0.130282]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 85/500] [Batch 660/676] [D loss: -0.000855] [G loss: -0.038745] [d1 loss: 0.062128] [d2 loss: 0.052090]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 0/676] [D loss: -0.004805] [G loss: -0.041045] [d1 loss: 0.057069] [d2 loss: 0.063752]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 86/500] [Batch 20/676] [D loss: -0.019795] [G loss: -0.033681] [d1 loss: 0.083506] [d2 loss: 0.086070]  [sq d1 d2: 0.000007]  [num0: 11.000000] [num1 53.000000]
[Epoch 86/500] [Batch 40/676] [D loss: -0.014219] [G loss: -0.023345] [d1 loss: 0.072251] [d2 loss: 0.063431]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 60/676] [D loss: -0.034777] [G loss: 0.006875] [d1 loss: 0.049163] [d2 loss: 0.046557]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 86/500] [Batch 80/676] [D loss: -0.022658] [G loss: 0.046211] [d1 loss: 0.112581] [d2 loss: 0.058857]  [sq d1 d2: 0.002886]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 100/676] [D loss: -0.029105] [G loss: 0.025080] [d1 loss: 0.130335] [d2 loss: 0.118606]  [sq d1 d2: 0.000138]  [num0: 15.000000] [num1 49.000000]
[Epoch 86/500] [Batch 120/676] [D loss: -0.024403] [G loss: 0.028649] [d1 loss: 0.106553] [d2 loss: 0.097598]  [sq d1 d2: 0.000080]  [num0: 11.000000] [num1 53.000000]
[Epoch 86/500] [Batch 140/676] [D loss: 0.003928] [G loss: 0.045769] [d1 loss: 0.178909] [d2 loss: 0.160493]  [sq d1 d2: 0.000339]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 160/676] [D loss: 0.014721] [G loss: 0.040440] [d1 loss: 0.062886] [d2 loss: 0.065869]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 180/676] [D loss: 0.000525] [G loss: 0.059159] [d1 loss: 0.138902] [d2 loss: 0.118383]  [sq d1 d2: 0.000421]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 200/676] [D loss: -0.017965] [G loss: 0.080335] [d1 loss: 0.138239] [d2 loss: 0.088001]  [sq d1 d2: 0.002524]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 220/676] [D loss: -0.012665] [G loss: 0.078776] [d1 loss: 0.079934] [d2 loss: 0.077713]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 240/676] [D loss: -0.009649] [G loss: 0.079441] [d1 loss: 0.103207] [d2 loss: 0.102306]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 86/500] [Batch 260/676] [D loss: -0.012920] [G loss: 0.054550] [d1 loss: 0.164578] [d2 loss: 0.163442]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 280/676] [D loss: -0.031711] [G loss: 0.066612] [d1 loss: 0.256303] [d2 loss: 0.233422]  [sq d1 d2: 0.000524]  [num0: 20.000000] [num1 44.000000]
[Epoch 86/500] [Batch 300/676] [D loss: -0.011659] [G loss: 0.026860] [d1 loss: 0.141591] [d2 loss: 0.108124]  [sq d1 d2: 0.001120]  [num0: 18.000000] [num1 46.000000]
[Epoch 86/500] [Batch 320/676] [D loss: -0.002872] [G loss: -0.005767] [d1 loss: 0.106119] [d2 loss: 0.102049]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 86/500] [Batch 340/676] [D loss: -0.011721] [G loss: -0.053395] [d1 loss: 0.091869] [d2 loss: 0.083554]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 360/676] [D loss: -0.008458] [G loss: -0.062983] [d1 loss: 0.079821] [d2 loss: 0.090317]  [sq d1 d2: 0.000110]  [num0: 19.000000] [num1 45.000000]
[Epoch 86/500] [Batch 380/676] [D loss: -0.010735] [G loss: -0.102157] [d1 loss: 0.104002] [d2 loss: 0.089975]  [sq d1 d2: 0.000197]  [num0: 14.000000] [num1 50.000000]
[Epoch 86/500] [Batch 400/676] [D loss: -0.011963] [G loss: -0.084290] [d1 loss: 0.124950] [d2 loss: 0.122935]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 420/676] [D loss: -0.005657] [G loss: -0.075560] [d1 loss: 0.083981] [d2 loss: 0.074421]  [sq d1 d2: 0.000091]  [num0: 18.000000] [num1 46.000000]
[Epoch 86/500] [Batch 440/676] [D loss: -0.020284] [G loss: -0.107525] [d1 loss: 0.066076] [d2 loss: 0.059179]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 460/676] [D loss: -0.019923] [G loss: -0.095133] [d1 loss: 0.089299] [d2 loss: 0.093213]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 86/500] [Batch 480/676] [D loss: -0.022848] [G loss: -0.092488] [d1 loss: 0.093451] [d2 loss: 0.075442]  [sq d1 d2: 0.000324]  [num0: 15.000000] [num1 49.000000]
[Epoch 86/500] [Batch 500/676] [D loss: -0.016456] [G loss: -0.094381] [d1 loss: 0.133838] [d2 loss: 0.133346]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 86/500] [Batch 520/676] [D loss: -0.007001] [G loss: -0.086314] [d1 loss: 0.106231] [d2 loss: 0.102067]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 86/500] [Batch 540/676] [D loss: -0.007702] [G loss: -0.098938] [d1 loss: 0.092560] [d2 loss: 0.066886]  [sq d1 d2: 0.000659]  [num0: 17.000000] [num1 47.000000]
[Epoch 86/500] [Batch 560/676] [D loss: -0.004741] [G loss: -0.104071] [d1 loss: 0.061503] [d2 loss: 0.056841]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]

[Epoch 86/500] [Batch 580/676] [D loss: -0.010716] [G loss: -0.062216] [d1 loss: 0.067664] [d2 loss: 0.069628]  [sq d1 d2: 0.000004]  [num0: 9.000000] [num1 55.000000]
[Epoch 86/500] [Batch 600/676] [D loss: -0.003887] [G loss: -0.079030] [d1 loss: 0.090346] [d2 loss: 0.087761]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 86/500] [Batch 620/676] [D loss: -0.015021] [G loss: -0.032397] [d1 loss: 0.088947] [d2 loss: 0.078131]  [sq d1 d2: 0.000117]  [num0: 14.000000] [num1 50.000000]
[Epoch 86/500] [Batch 640/676] [D loss: -0.008268] [G loss: -0.015923] [d1 loss: 0.130827] [d2 loss: 0.138248]  [sq d1 d2: 0.000055]  [num0: 19.000000] [num1 45.000000]
[Epoch 86/500] [Batch 660/676] [D loss: -0.013900] [G loss: -0.034212] [d1 loss: 0.056985] [d2 loss: 0.055657]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 0/676] [D loss: -0.015812] [G loss: -0.054873] [d1 loss: 0.211902] [d2 loss: 0.196322]  [sq d1 d2: 0.000243]  [num0: 14.000000] [num1 50.000000]
[Epoch 87/500] [Batch 20/676] [D loss: -0.008777] [G loss: -0.008254] [d1 loss: 0.052445] [d2 loss: 0.058208]  [sq d1 d2: 0.000033]  [num0: 12.000000] [num1 52.000000]
[Epoch 87/500] [Batch 40/676] [D loss: -0.003068] [G loss: -0.032664] [d1 loss: 0.084955] [d2 loss: 0.091747]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 60/676] [D loss: -0.007221] [G loss: -0.048514] [d1 loss: 0.110892] [d2 loss: 0.084446]  [sq d1 d2: 0.000699]  [num0: 19.000000] [num1 45.000000]
[Epoch 87/500] [Batch 80/676] [D loss: -0.016248] [G loss: -0.089851] [d1 loss: 0.110955] [d2 loss: 0.103658]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 87/500] [Batch 100/676] [D loss: -0.007466] [G loss: -0.079906] [d1 loss: 0.129944] [d2 loss: 0.149205]  [sq d1 d2: 0.000371]  [num0: 14.000000] [num1 50.000000]
[Epoch 87/500] [Batch 120/676] [D loss: -0.006623] [G loss: -0.082140] [d1 loss: 0.119610] [d2 loss: 0.105168]  [sq d1 d2: 0.000209]  [num0: 18.000000] [num1 46.000000]
[Epoch 87/500] [Batch 140/676] [D loss: -0.022670] [G loss: -0.069196] [d1 loss: 0.120510] [d2 loss: 0.112631]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 87/500] [Batch 160/676] [D loss: -0.020091] [G loss: -0.069672] [d1 loss: 0.094825] [d2 loss: 0.092233]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 87/500] [Batch 180/676] [D loss: -0.023638] [G loss: -0.081848] [d1 loss: 0.084983] [d2 loss: 0.087462]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 87/500] [Batch 200/676] [D loss: 0.002920] [G loss: -0.066129] [d1 loss: 0.073765] [d2 loss: 0.063272]  [sq d1 d2: 0.000110]  [num0: 13.000000] [num1 51.000000]
[Epoch 87/500] [Batch 220/676] [D loss: -0.014081] [G loss: -0.054411] [d1 loss: 0.130468] [d2 loss: 0.131511]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 87/500] [Batch 240/676] [D loss: 0.001882] [G loss: -0.043925] [d1 loss: 0.133034] [d2 loss: 0.142890]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 260/676] [D loss: -0.011064] [G loss: -0.014561] [d1 loss: 0.087383] [d2 loss: 0.073172]  [sq d1 d2: 0.000202]  [num0: 12.000000] [num1 52.000000]
[Epoch 87/500] [Batch 280/676] [D loss: -0.009784] [G loss: -0.010085] [d1 loss: 0.089516] [d2 loss: 0.083262]  [sq d1 d2: 0.000039]  [num0: 12.000000] [num1 52.000000]
[Epoch 87/500] [Batch 300/676] [D loss: -0.014632] [G loss: -0.006816] [d1 loss: 0.095397] [d2 loss: 0.127626]  [sq d1 d2: 0.001039]  [num0: 18.000000] [num1 46.000000]
[Epoch 87/500] [Batch 320/676] [D loss: -0.021697] [G loss: 0.004059] [d1 loss: 0.060945] [d2 loss: 0.066964]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 340/676] [D loss: -0.026230] [G loss: -0.008315] [d1 loss: 0.090918] [d2 loss: 0.092377]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 360/676] [D loss: -0.023294] [G loss: -0.012535] [d1 loss: 0.032216] [d2 loss: 0.028492]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 87/500] [Batch 380/676] [D loss: -0.022382] [G loss: 0.013191] [d1 loss: 0.211191] [d2 loss: 0.228624]  [sq d1 d2: 0.000304]  [num0: 19.000000] [num1 45.000000]
[Epoch 87/500] [Batch 400/676] [D loss: -0.003487] [G loss: -0.026868] [d1 loss: 0.101560] [d2 loss: 0.101870]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 87/500] [Batch 420/676] [D loss: -0.012086] [G loss: -0.066705] [d1 loss: 0.191340] [d2 loss: 0.156597]  [sq d1 d2: 0.001207]  [num0: 17.000000] [num1 47.000000]
[Epoch 87/500] [Batch 440/676] [D loss: -0.016523] [G loss: -0.047377] [d1 loss: 0.093241] [d2 loss: 0.087626]  [sq d1 d2: 0.000032]  [num0: 14.000000] [num1 50.000000]
[Epoch 87/500] [Batch 460/676] [D loss: -0.021714] [G loss: -0.067692] [d1 loss: 0.073274] [d2 loss: 0.059526]  [sq d1 d2: 0.000189]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 480/676] [D loss: -0.016614] [G loss: -0.072964] [d1 loss: 0.063660] [d2 loss: 0.063407]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 87/500] [Batch 500/676] [D loss: -0.024558] [G loss: -0.081168] [d1 loss: 0.060008] [d2 loss: 0.058354]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 87/500] [Batch 520/676] [D loss: -0.021874] [G loss: -0.092033] [d1 loss: 0.128390] [d2 loss: 0.129746]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 87/500] [Batch 540/676] [D loss: -0.019535] [G loss: -0.077439] [d1 loss: 0.086528] [d2 loss: 0.077384]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 560/676] [D loss: -0.028418] [G loss: -0.074825] [d1 loss: 0.111550] [d2 loss: 0.100770]  [sq d1 d2: 0.000116]  [num0: 16.000000] [num1 48.000000]
[Epoch 87/500] [Batch 580/676] [D loss: -0.007794] [G loss: -0.055307] [d1 loss: 0.119133] [d2 loss: 0.121748]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 87/500] [Batch 600/676] [D loss: -0.014479] [G loss: -0.008689] [d1 loss: 0.139588] [d2 loss: 0.109868]  [sq d1 d2: 0.000883]  [num0: 15.000000] [num1 49.000000]
[Epoch 87/500] [Batch 620/676] [D loss: -0.016754] [G loss: -0.027164] [d1 loss: 0.125888] [d2 loss: 0.139428]  [sq d1 d2: 0.000183]  [num0: 13.000000] [num1 51.000000]
[Epoch 87/500] [Batch 640/676] [D loss: -0.025473] [G loss: -0.029545] [d1 loss: 0.234439] [d2 loss: 0.196396]  [sq d1 d2: 0.001447]  [num0: 18.000000] [num1 46.000000]
[Epoch 87/500] [Batch 660/676] [D loss: -0.011025] [G loss: -0.035269] [d1 loss: 0.105610] [d2 loss: 0.097171]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 0/676] [D loss: -0.022151] [G loss: 0.013019] [d1 loss: 0.069023] [d2 loss: 0.061276]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 20/676] [D loss: -0.012953] [G loss: 0.044998] [d1 loss: 0.115481] [d2 loss: 0.137210]  [sq d1 d2: 0.000472]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 40/676] [D loss: -0.026143] [G loss: 0.024076] [d1 loss: 0.117392] [d2 loss: 0.123785]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 88/500] [Batch 60/676] [D loss: -0.033844] [G loss: 0.070134] [d1 loss: 0.078315] [d2 loss: 0.067824]  [sq d1 d2: 0.000110]  [num0: 17.000000] [num1 47.000000]
[Epoch 88/500] [Batch 80/676] [D loss: -0.014315] [G loss: 0.061383] [d1 loss: 0.117052] [d2 loss: 0.124103]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 100/676] [D loss: -0.019703] [G loss: 0.044811] [d1 loss: 0.132182] [d2 loss: 0.116320]  [sq d1 d2: 0.000252]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 120/676] [D loss: -0.008005] [G loss: 0.078314] [d1 loss: 0.175118] [d2 loss: 0.145036]  [sq d1 d2: 0.000905]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 140/676] [D loss: -0.038749] [G loss: 0.070387] [d1 loss: 0.128798] [d2 loss: 0.106017]  [sq d1 d2: 0.000519]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 160/676] [D loss: -0.012525] [G loss: 0.016497] [d1 loss: 0.130412] [d2 loss: 0.125125]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 88/500] [Batch 180/676] [D loss: -0.011334] [G loss: 0.021790] [d1 loss: 0.147856] [d2 loss: 0.144221]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 88/500] [Batch 200/676] [D loss: -0.019658] [G loss: 0.057391] [d1 loss: 0.118200] [d2 loss: 0.105830]  [sq d1 d2: 0.000153]  [num0: 13.000000] [num1 51.000000]
[Epoch 88/500] [Batch 220/676] [D loss: -0.014966] [G loss: 0.010847] [d1 loss: 0.134537] [d2 loss: 0.129064]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]

[Epoch 88/500] [Batch 240/676] [D loss: -0.020034] [G loss: 0.019269] [d1 loss: 0.111190] [d2 loss: 0.122662]  [sq d1 d2: 0.000132]  [num0: 18.000000] [num1 46.000000]
[Epoch 88/500] [Batch 260/676] [D loss: -0.023030] [G loss: 0.002563] [d1 loss: 0.227242] [d2 loss: 0.228083]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 88/500] [Batch 280/676] [D loss: -0.016394] [G loss: -0.007678] [d1 loss: 0.073976] [d2 loss: 0.060771]  [sq d1 d2: 0.000174]  [num0: 20.000000] [num1 44.000000]
[Epoch 88/500] [Batch 300/676] [D loss: -0.018308] [G loss: -0.033422] [d1 loss: 0.211440] [d2 loss: 0.207705]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 88/500] [Batch 320/676] [D loss: -0.011312] [G loss: -0.061784] [d1 loss: 0.089096] [d2 loss: 0.083962]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 340/676] [D loss: -0.032697] [G loss: -0.072004] [d1 loss: 0.065750] [d2 loss: 0.047097]  [sq d1 d2: 0.000348]  [num0: 18.000000] [num1 46.000000]
[Epoch 88/500] [Batch 360/676] [D loss: -0.005087] [G loss: -0.091817] [d1 loss: 0.120347] [d2 loss: 0.108596]  [sq d1 d2: 0.000138]  [num0: 17.000000] [num1 47.000000]
[Epoch 88/500] [Batch 380/676] [D loss: -0.011709] [G loss: -0.083070] [d1 loss: 0.237893] [d2 loss: 0.243467]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 88/500] [Batch 400/676] [D loss: -0.022836] [G loss: -0.068063] [d1 loss: 0.178574] [d2 loss: 0.178349]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 420/676] [D loss: -0.012097] [G loss: -0.066609] [d1 loss: 0.069067] [d2 loss: 0.071741]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 440/676] [D loss: -0.009593] [G loss: -0.094070] [d1 loss: 0.102561] [d2 loss: 0.091765]  [sq d1 d2: 0.000117]  [num0: 22.000000] [num1 42.000000]
[Epoch 88/500] [Batch 460/676] [D loss: -0.013083] [G loss: -0.078604] [d1 loss: 0.120570] [d2 loss: 0.101939]  [sq d1 d2: 0.000347]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 480/676] [D loss: -0.017962] [G loss: -0.083500] [d1 loss: 0.086988] [d2 loss: 0.086320]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 500/676] [D loss: -0.040218] [G loss: -0.126358] [d1 loss: 0.061692] [d2 loss: 0.053845]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 88/500] [Batch 520/676] [D loss: -0.024002] [G loss: -0.143313] [d1 loss: 0.055840] [d2 loss: 0.045306]  [sq d1 d2: 0.000111]  [num0: 11.000000] [num1 53.000000]
[Epoch 88/500] [Batch 540/676] [D loss: -0.042326] [G loss: -0.154038] [d1 loss: 0.051833] [d2 loss: 0.062589]  [sq d1 d2: 0.000116]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 560/676] [D loss: -0.034071] [G loss: -0.167125] [d1 loss: 0.092469] [d2 loss: 0.078434]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 580/676] [D loss: -0.019546] [G loss: -0.178047] [d1 loss: 0.104760] [d2 loss: 0.077754]  [sq d1 d2: 0.000729]  [num0: 17.000000] [num1 47.000000]
[Epoch 88/500] [Batch 600/676] [D loss: -0.012407] [G loss: -0.132692] [d1 loss: 0.098659] [d2 loss: 0.094808]  [sq d1 d2: 0.000015]  [num0: 12.000000] [num1 52.000000]
[Epoch 88/500] [Batch 620/676] [D loss: -0.016387] [G loss: -0.110476] [d1 loss: 0.077329] [d2 loss: 0.077346]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 640/676] [D loss: -0.013492] [G loss: -0.112355] [d1 loss: 0.041858] [d2 loss: 0.040022]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 88/500] [Batch 660/676] [D loss: -0.018564] [G loss: -0.116352] [d1 loss: 0.047393] [d2 loss: 0.042918]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 0/676] [D loss: -0.020650] [G loss: -0.120271] [d1 loss: 0.205221] [d2 loss: 0.182510]  [sq d1 d2: 0.000516]  [num0: 17.000000] [num1 47.000000]
[Epoch 89/500] [Batch 20/676] [D loss: -0.022030] [G loss: -0.115224] [d1 loss: 0.104032] [d2 loss: 0.115983]  [sq d1 d2: 0.000143]  [num0: 16.000000] [num1 48.000000]
[Epoch 89/500] [Batch 40/676] [D loss: -0.022355] [G loss: -0.108421] [d1 loss: 0.141378] [d2 loss: 0.138436]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 60/676] [D loss: -0.024309] [G loss: -0.087545] [d1 loss: 0.086764] [d2 loss: 0.089706]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 89/500] [Batch 80/676] [D loss: -0.022981] [G loss: -0.067062] [d1 loss: 0.125703] [d2 loss: 0.117333]  [sq d1 d2: 0.000070]  [num0: 13.000000] [num1 51.000000]
[Epoch 89/500] [Batch 100/676] [D loss: -0.016033] [G loss: -0.069441] [d1 loss: 0.123546] [d2 loss: 0.096377]  [sq d1 d2: 0.000738]  [num0: 16.000000] [num1 48.000000]
[Epoch 89/500] [Batch 120/676] [D loss: -0.024251] [G loss: -0.074075] [d1 loss: 0.150452] [d2 loss: 0.148953]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 140/676] [D loss: -0.013989] [G loss: -0.029036] [d1 loss: 0.094616] [d2 loss: 0.077799]  [sq d1 d2: 0.000283]  [num0: 12.000000] [num1 52.000000]
[Epoch 89/500] [Batch 160/676] [D loss: -0.009655] [G loss: 0.018593] [d1 loss: 0.080956] [d2 loss: 0.066245]  [sq d1 d2: 0.000216]  [num0: 12.000000] [num1 52.000000]
[Epoch 89/500] [Batch 180/676] [D loss: -0.008726] [G loss: 0.056275] [d1 loss: 0.163772] [d2 loss: 0.159718]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 89/500] [Batch 200/676] [D loss: -0.026059] [G loss: 0.041986] [d1 loss: 0.101450] [d2 loss: 0.110861]  [sq d1 d2: 0.000089]  [num0: 11.000000] [num1 53.000000]
[Epoch 89/500] [Batch 220/676] [D loss: -0.010135] [G loss: 0.102244] [d1 loss: 0.122280] [d2 loss: 0.102419]  [sq d1 d2: 0.000394]  [num0: 14.000000] [num1 50.000000]
[Epoch 89/500] [Batch 240/676] [D loss: -0.008900] [G loss: 0.113491] [d1 loss: 0.096382] [d2 loss: 0.089433]  [sq d1 d2: 0.000048]  [num0: 13.000000] [num1 51.000000]
[Epoch 89/500] [Batch 260/676] [D loss: -0.030124] [G loss: 0.134775] [d1 loss: 0.030082] [d2 loss: 0.031722]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 89/500] [Batch 280/676] [D loss: -0.032397] [G loss: 0.111377] [d1 loss: 0.145928] [d2 loss: 0.140409]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 300/676] [D loss: -0.021490] [G loss: 0.113222] [d1 loss: 0.103970] [d2 loss: 0.097305]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 320/676] [D loss: -0.030557] [G loss: 0.156210] [d1 loss: 0.061411] [d2 loss: 0.052812]  [sq d1 d2: 0.000074]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 340/676] [D loss: -0.016458] [G loss: 0.110577] [d1 loss: 0.195473] [d2 loss: 0.205352]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 89/500] [Batch 360/676] [D loss: -0.011865] [G loss: 0.125891] [d1 loss: 0.128688] [d2 loss: 0.111985]  [sq d1 d2: 0.000279]  [num0: 14.000000] [num1 50.000000]
[Epoch 89/500] [Batch 380/676] [D loss: -0.010435] [G loss: 0.127331] [d1 loss: 0.108209] [d2 loss: 0.120108]  [sq d1 d2: 0.000142]  [num0: 13.000000] [num1 51.000000]
[Epoch 89/500] [Batch 400/676] [D loss: -0.001796] [G loss: 0.087708] [d1 loss: 0.061527] [d2 loss: 0.052702]  [sq d1 d2: 0.000078]  [num0: 19.000000] [num1 45.000000]
[Epoch 89/500] [Batch 420/676] [D loss: 0.011309] [G loss: 0.065722] [d1 loss: 0.077026] [d2 loss: 0.076611]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 440/676] [D loss: -0.006163] [G loss: -0.005926] [d1 loss: 0.109829] [d2 loss: 0.107210]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 89/500] [Batch 460/676] [D loss: -0.019342] [G loss: -0.025206] [d1 loss: 0.090623] [d2 loss: 0.091315]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 89/500] [Batch 480/676] [D loss: -0.012559] [G loss: -0.061936] [d1 loss: 0.137674] [d2 loss: 0.113367]  [sq d1 d2: 0.000591]  [num0: 13.000000] [num1 51.000000]
[Epoch 89/500] [Batch 500/676] [D loss: -0.025977] [G loss: -0.094122] [d1 loss: 0.080292] [d2 loss: 0.087032]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 89/500] [Batch 520/676] [D loss: -0.026701] [G loss: -0.096017] [d1 loss: 0.155822] [d2 loss: 0.128805]  [sq d1 d2: 0.000730]  [num0: 18.000000] [num1 46.000000]
[Epoch 89/500] [Batch 540/676] [D loss: -0.007189] [G loss: -0.129502] [d1 loss: 0.137523] [d2 loss: 0.116224]  [sq d1 d2: 0.000454]  [num0: 18.000000] [num1 46.000000]
[Epoch 89/500] [Batch 560/676] [D loss: -0.036482] [G loss: -0.146546] [d1 loss: 0.045937] [d2 loss: 0.045451]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]

[Epoch 89/500] [Batch 580/676] [D loss: -0.023823] [G loss: -0.163497] [d1 loss: 0.119281] [d2 loss: 0.104339]  [sq d1 d2: 0.000223]  [num0: 16.000000] [num1 48.000000]
[Epoch 89/500] [Batch 600/676] [D loss: -0.001981] [G loss: -0.149422] [d1 loss: 0.086382] [d2 loss: 0.097225]  [sq d1 d2: 0.000118]  [num0: 17.000000] [num1 47.000000]
[Epoch 89/500] [Batch 620/676] [D loss: -0.014235] [G loss: -0.137885] [d1 loss: 0.099642] [d2 loss: 0.096743]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 89/500] [Batch 640/676] [D loss: -0.005676] [G loss: -0.128248] [d1 loss: 0.122330] [d2 loss: 0.104807]  [sq d1 d2: 0.000307]  [num0: 14.000000] [num1 50.000000]
[Epoch 89/500] [Batch 660/676] [D loss: -0.010078] [G loss: -0.139300] [d1 loss: 0.132169] [d2 loss: 0.161946]  [sq d1 d2: 0.000887]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 0/676] [D loss: -0.004168] [G loss: -0.120578] [d1 loss: 0.123907] [d2 loss: 0.105725]  [sq d1 d2: 0.000331]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 20/676] [D loss: -0.011730] [G loss: -0.128339] [d1 loss: 0.101203] [d2 loss: 0.101333]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 90/500] [Batch 40/676] [D loss: -0.011701] [G loss: -0.155444] [d1 loss: 0.123923] [d2 loss: 0.118448]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 60/676] [D loss: -0.032656] [G loss: -0.163314] [d1 loss: 0.112180] [d2 loss: 0.100652]  [sq d1 d2: 0.000133]  [num0: 18.000000] [num1 46.000000]
[Epoch 90/500] [Batch 80/676] [D loss: -0.026946] [G loss: -0.172612] [d1 loss: 0.114985] [d2 loss: 0.090505]  [sq d1 d2: 0.000599]  [num0: 13.000000] [num1 51.000000]
[Epoch 90/500] [Batch 100/676] [D loss: -0.035722] [G loss: -0.188597] [d1 loss: 0.203636] [d2 loss: 0.190804]  [sq d1 d2: 0.000165]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 120/676] [D loss: -0.045479] [G loss: -0.260016] [d1 loss: 0.056297] [d2 loss: 0.048892]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 90/500] [Batch 140/676] [D loss: -0.039966] [G loss: -0.234444] [d1 loss: 0.068923] [d2 loss: 0.059605]  [sq d1 d2: 0.000087]  [num0: 17.000000] [num1 47.000000]
[Epoch 90/500] [Batch 160/676] [D loss: -0.045806] [G loss: -0.264826] [d1 loss: 0.094547] [d2 loss: 0.091589]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 90/500] [Batch 180/676] [D loss: -0.012808] [G loss: -0.258847] [d1 loss: 0.072401] [d2 loss: 0.070359]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 200/676] [D loss: -0.014827] [G loss: -0.211906] [d1 loss: 0.063101] [d2 loss: 0.047585]  [sq d1 d2: 0.000241]  [num0: 12.000000] [num1 52.000000]
[Epoch 90/500] [Batch 220/676] [D loss: -0.002949] [G loss: -0.152610] [d1 loss: 0.090977] [d2 loss: 0.090492]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 90/500] [Batch 240/676] [D loss: -0.020249] [G loss: -0.136714] [d1 loss: 0.139795] [d2 loss: 0.132772]  [sq d1 d2: 0.000049]  [num0: 20.000000] [num1 44.000000]
[Epoch 90/500] [Batch 260/676] [D loss: -0.007187] [G loss: -0.130304] [d1 loss: 0.075580] [d2 loss: 0.080656]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 280/676] [D loss: -0.015029] [G loss: -0.127739] [d1 loss: 0.082205] [d2 loss: 0.060348]  [sq d1 d2: 0.000478]  [num0: 12.000000] [num1 52.000000]
[Epoch 90/500] [Batch 300/676] [D loss: -0.014787] [G loss: -0.099259] [d1 loss: 0.044944] [d2 loss: 0.042061]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 320/676] [D loss: -0.024244] [G loss: -0.079587] [d1 loss: 0.135087] [d2 loss: 0.133517]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 90/500] [Batch 340/676] [D loss: -0.016426] [G loss: -0.061527] [d1 loss: 0.116463] [d2 loss: 0.101024]  [sq d1 d2: 0.000238]  [num0: 17.000000] [num1 47.000000]
[Epoch 90/500] [Batch 360/676] [D loss: -0.020262] [G loss: -0.041347] [d1 loss: 0.069326] [d2 loss: 0.066658]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 380/676] [D loss: -0.017104] [G loss: -0.004738] [d1 loss: 0.082100] [d2 loss: 0.092273]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 400/676] [D loss: -0.021889] [G loss: 0.024433] [d1 loss: 0.082394] [d2 loss: 0.068516]  [sq d1 d2: 0.000193]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 420/676] [D loss: -0.028497] [G loss: 0.022043] [d1 loss: 0.094516] [d2 loss: 0.107883]  [sq d1 d2: 0.000179]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 440/676] [D loss: 0.011308] [G loss: 0.049110] [d1 loss: 0.062223] [d2 loss: 0.060958]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 460/676] [D loss: -0.011607] [G loss: 0.057411] [d1 loss: 0.145423] [d2 loss: 0.137538]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 90/500] [Batch 480/676] [D loss: -0.037707] [G loss: 0.052511] [d1 loss: 0.124499] [d2 loss: 0.142529]  [sq d1 d2: 0.000325]  [num0: 13.000000] [num1 51.000000]
[Epoch 90/500] [Batch 500/676] [D loss: -0.012819] [G loss: 0.052780] [d1 loss: 0.187638] [d2 loss: 0.195897]  [sq d1 d2: 0.000068]  [num0: 17.000000] [num1 47.000000]
[Epoch 90/500] [Batch 520/676] [D loss: -0.021750] [G loss: 0.071492] [d1 loss: 0.188612] [d2 loss: 0.166583]  [sq d1 d2: 0.000485]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 540/676] [D loss: -0.030928] [G loss: 0.049934] [d1 loss: 0.083619] [d2 loss: 0.055995]  [sq d1 d2: 0.000763]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 560/676] [D loss: -0.036474] [G loss: 0.054130] [d1 loss: 0.177226] [d2 loss: 0.171832]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 90/500] [Batch 580/676] [D loss: -0.019386] [G loss: 0.030615] [d1 loss: 0.089797] [d2 loss: 0.071063]  [sq d1 d2: 0.000351]  [num0: 15.000000] [num1 49.000000]
[Epoch 90/500] [Batch 600/676] [D loss: -0.024495] [G loss: 0.029402] [d1 loss: 0.149780] [d2 loss: 0.131619]  [sq d1 d2: 0.000330]  [num0: 14.000000] [num1 50.000000]
[Epoch 90/500] [Batch 620/676] [D loss: -0.025633] [G loss: 0.027731] [d1 loss: 0.091424] [d2 loss: 0.097387]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 90/500] [Batch 640/676] [D loss: -0.041852] [G loss: 0.078718] [d1 loss: 0.188821] [d2 loss: 0.183922]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 90/500] [Batch 660/676] [D loss: -0.019963] [G loss: 0.041487] [d1 loss: 0.094871] [d2 loss: 0.093775]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 91/500] [Batch 0/676] [D loss: -0.024559] [G loss: 0.032619] [d1 loss: 0.065110] [d2 loss: 0.063628]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 91/500] [Batch 20/676] [D loss: -0.029392] [G loss: 0.053706] [d1 loss: 0.138532] [d2 loss: 0.129818]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 40/676] [D loss: -0.026215] [G loss: 0.077705] [d1 loss: 0.055736] [d2 loss: 0.056103]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 91/500] [Batch 60/676] [D loss: -0.024080] [G loss: 0.058105] [d1 loss: 0.113830] [d2 loss: 0.111907]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 80/676] [D loss: -0.030745] [G loss: 0.048738] [d1 loss: 0.132640] [d2 loss: 0.108274]  [sq d1 d2: 0.000594]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 100/676] [D loss: -0.008832] [G loss: 0.032717] [d1 loss: 0.207767] [d2 loss: 0.196394]  [sq d1 d2: 0.000129]  [num0: 18.000000] [num1 46.000000]
[Epoch 91/500] [Batch 120/676] [D loss: 0.006336] [G loss: 0.045873] [d1 loss: 0.058766] [d2 loss: 0.052403]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 140/676] [D loss: -0.030095] [G loss: 0.012311] [d1 loss: 0.114639] [d2 loss: 0.106942]  [sq d1 d2: 0.000059]  [num0: 18.000000] [num1 46.000000]
[Epoch 91/500] [Batch 160/676] [D loss: -0.004468] [G loss: -0.057652] [d1 loss: 0.188176] [d2 loss: 0.191132]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 91/500] [Batch 180/676] [D loss: -0.023592] [G loss: -0.117640] [d1 loss: 0.215626] [d2 loss: 0.214301]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 91/500] [Batch 200/676] [D loss: -0.029848] [G loss: -0.112347] [d1 loss: 0.063379] [d2 loss: 0.080281]  [sq d1 d2: 0.000286]  [num0: 16.000000] [num1 48.000000]
[Epoch 91/500] [Batch 220/676] [D loss: 0.003664] [G loss: -0.120125] [d1 loss: 0.132373] [d2 loss: 0.116337]  [sq d1 d2: 0.000257]  [num0: 16.000000] [num1 48.000000]

[Epoch 91/500] [Batch 240/676] [D loss: -0.022600] [G loss: -0.164328] [d1 loss: 0.161058] [d2 loss: 0.164214]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 91/500] [Batch 260/676] [D loss: -0.042666] [G loss: -0.179655] [d1 loss: 0.066425] [d2 loss: 0.064512]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 91/500] [Batch 280/676] [D loss: -0.033827] [G loss: -0.178910] [d1 loss: 0.148257] [d2 loss: 0.129542]  [sq d1 d2: 0.000350]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 300/676] [D loss: -0.031021] [G loss: -0.165538] [d1 loss: 0.189699] [d2 loss: 0.195874]  [sq d1 d2: 0.000038]  [num0: 20.000000] [num1 44.000000]
[Epoch 91/500] [Batch 320/676] [D loss: -0.030881] [G loss: -0.127516] [d1 loss: 0.163520] [d2 loss: 0.128751]  [sq d1 d2: 0.001209]  [num0: 21.000000] [num1 43.000000]
[Epoch 91/500] [Batch 340/676] [D loss: -0.039627] [G loss: -0.135880] [d1 loss: 0.138083] [d2 loss: 0.137961]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 91/500] [Batch 360/676] [D loss: -0.021147] [G loss: -0.120025] [d1 loss: 0.128438] [d2 loss: 0.124110]  [sq d1 d2: 0.000019]  [num0: 13.000000] [num1 51.000000]
[Epoch 91/500] [Batch 380/676] [D loss: -0.032496] [G loss: -0.121960] [d1 loss: 0.096045] [d2 loss: 0.087207]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 400/676] [D loss: -0.004867] [G loss: -0.091494] [d1 loss: 0.170596] [d2 loss: 0.139102]  [sq d1 d2: 0.000992]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 420/676] [D loss: -0.042137] [G loss: -0.097988] [d1 loss: 0.114602] [d2 loss: 0.108720]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 440/676] [D loss: -0.030925] [G loss: -0.080164] [d1 loss: 0.138438] [d2 loss: 0.150858]  [sq d1 d2: 0.000154]  [num0: 13.000000] [num1 51.000000]
[Epoch 91/500] [Batch 460/676] [D loss: -0.019517] [G loss: -0.101352] [d1 loss: 0.047033] [d2 loss: 0.055497]  [sq d1 d2: 0.000072]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 480/676] [D loss: -0.039658] [G loss: -0.081433] [d1 loss: 0.106750] [d2 loss: 0.120669]  [sq d1 d2: 0.000194]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 500/676] [D loss: -0.035585] [G loss: -0.125786] [d1 loss: 0.073681] [d2 loss: 0.068252]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 91/500] [Batch 520/676] [D loss: 0.008398] [G loss: -0.120597] [d1 loss: 0.103197] [d2 loss: 0.105666]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 91/500] [Batch 540/676] [D loss: -0.063043] [G loss: -0.138276] [d1 loss: 0.075518] [d2 loss: 0.072638]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 560/676] [D loss: -0.027312] [G loss: -0.136274] [d1 loss: 0.115610] [d2 loss: 0.122338]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 580/676] [D loss: -0.000792] [G loss: -0.106032] [d1 loss: 0.082670] [d2 loss: 0.073442]  [sq d1 d2: 0.000085]  [num0: 12.000000] [num1 52.000000]
[Epoch 91/500] [Batch 600/676] [D loss: -0.018849] [G loss: -0.089041] [d1 loss: 0.140066] [d2 loss: 0.148816]  [sq d1 d2: 0.000077]  [num0: 11.000000] [num1 53.000000]
[Epoch 91/500] [Batch 620/676] [D loss: -0.014461] [G loss: -0.059680] [d1 loss: 0.129618] [d2 loss: 0.162265]  [sq d1 d2: 0.001066]  [num0: 17.000000] [num1 47.000000]
[Epoch 91/500] [Batch 640/676] [D loss: -0.025882] [G loss: -0.068962] [d1 loss: 0.096591] [d2 loss: 0.088178]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 91/500] [Batch 660/676] [D loss: -0.057965] [G loss: -0.055418] [d1 loss: 0.081383] [d2 loss: 0.089583]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 92/500] [Batch 0/676] [D loss: -0.027936] [G loss: -0.047674] [d1 loss: 0.058194] [d2 loss: 0.056681]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 92/500] [Batch 20/676] [D loss: -0.063389] [G loss: -0.050661] [d1 loss: 0.176486] [d2 loss: 0.162244]  [sq d1 d2: 0.000203]  [num0: 14.000000] [num1 50.000000]
[Epoch 92/500] [Batch 40/676] [D loss: -0.043949] [G loss: -0.063071] [d1 loss: 0.086394] [d2 loss: 0.076561]  [sq d1 d2: 0.000097]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 60/676] [D loss: -0.029033] [G loss: 0.009414] [d1 loss: 0.065441] [d2 loss: 0.059705]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 80/676] [D loss: -0.066705] [G loss: 0.026932] [d1 loss: 0.081437] [d2 loss: 0.096464]  [sq d1 d2: 0.000226]  [num0: 12.000000] [num1 52.000000]
[Epoch 92/500] [Batch 100/676] [D loss: -0.017939] [G loss: 0.046139] [d1 loss: 0.137312] [d2 loss: 0.139358]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 120/676] [D loss: -0.030566] [G loss: 0.095300] [d1 loss: 0.054654] [d2 loss: 0.051112]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 92/500] [Batch 140/676] [D loss: 0.002814] [G loss: 0.134868] [d1 loss: 0.078487] [d2 loss: 0.065697]  [sq d1 d2: 0.000164]  [num0: 13.000000] [num1 51.000000]
[Epoch 92/500] [Batch 160/676] [D loss: -0.041383] [G loss: 0.170005] [d1 loss: 0.047363] [d2 loss: 0.047259]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 92/500] [Batch 180/676] [D loss: -0.068985] [G loss: 0.171186] [d1 loss: 0.179182] [d2 loss: 0.175677]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 92/500] [Batch 200/676] [D loss: -0.039286] [G loss: 0.086018] [d1 loss: 0.068497] [d2 loss: 0.054207]  [sq d1 d2: 0.000204]  [num0: 12.000000] [num1 52.000000]
[Epoch 92/500] [Batch 220/676] [D loss: -0.059281] [G loss: 0.007355] [d1 loss: 0.091658] [d2 loss: 0.095047]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 92/500] [Batch 240/676] [D loss: -0.078943] [G loss: -0.045938] [d1 loss: 0.076446] [d2 loss: 0.063100]  [sq d1 d2: 0.000178]  [num0: 20.000000] [num1 44.000000]
[Epoch 92/500] [Batch 260/676] [D loss: -0.045976] [G loss: -0.127153] [d1 loss: 0.237563] [d2 loss: 0.201900]  [sq d1 d2: 0.001272]  [num0: 19.000000] [num1 45.000000]
[Epoch 92/500] [Batch 280/676] [D loss: -0.036164] [G loss: -0.181600] [d1 loss: 0.179394] [d2 loss: 0.170822]  [sq d1 d2: 0.000073]  [num0: 17.000000] [num1 47.000000]
[Epoch 92/500] [Batch 300/676] [D loss: 0.009660] [G loss: -0.270722] [d1 loss: 0.120613] [d2 loss: 0.112312]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 92/500] [Batch 320/676] [D loss: -0.033098] [G loss: -0.288904] [d1 loss: 0.085928] [d2 loss: 0.073504]  [sq d1 d2: 0.000154]  [num0: 14.000000] [num1 50.000000]
[Epoch 92/500] [Batch 340/676] [D loss: 0.010422] [G loss: -0.282313] [d1 loss: 0.195577] [d2 loss: 0.176069]  [sq d1 d2: 0.000381]  [num0: 17.000000] [num1 47.000000]
[Epoch 92/500] [Batch 360/676] [D loss: 0.014320] [G loss: -0.274664] [d1 loss: 0.162746] [d2 loss: 0.187088]  [sq d1 d2: 0.000593]  [num0: 12.000000] [num1 52.000000]
[Epoch 92/500] [Batch 380/676] [D loss: -0.046660] [G loss: -0.262481] [d1 loss: 0.110152] [d2 loss: 0.110641]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 92/500] [Batch 400/676] [D loss: -0.079216] [G loss: -0.213601] [d1 loss: 0.080229] [d2 loss: 0.079290]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 92/500] [Batch 420/676] [D loss: -0.035260] [G loss: -0.205644] [d1 loss: 0.050247] [d2 loss: 0.035964]  [sq d1 d2: 0.000204]  [num0: 16.000000] [num1 48.000000]
[Epoch 92/500] [Batch 440/676] [D loss: -0.101246] [G loss: -0.219773] [d1 loss: 0.063824] [d2 loss: 0.056381]  [sq d1 d2: 0.000055]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 460/676] [D loss: -0.070844] [G loss: -0.231324] [d1 loss: 0.095357] [d2 loss: 0.092387]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 92/500] [Batch 480/676] [D loss: -0.037678] [G loss: -0.221261] [d1 loss: 0.185218] [d2 loss: 0.183900]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 500/676] [D loss: -0.020984] [G loss: -0.155372] [d1 loss: 0.081143] [d2 loss: 0.078954]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 92/500] [Batch 520/676] [D loss: -0.011431] [G loss: -0.042538] [d1 loss: 0.271371] [d2 loss: 0.210067]  [sq d1 d2: 0.003758]  [num0: 16.000000] [num1 48.000000]
[Epoch 92/500] [Batch 540/676] [D loss: -0.011469] [G loss: 0.016890] [d1 loss: 0.096767] [d2 loss: 0.106567]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 92/500] [Batch 560/676] [D loss: -0.027789] [G loss: 0.031180] [d1 loss: 0.102556] [d2 loss: 0.087476]  [sq d1 d2: 0.000227]  [num0: 15.000000] [num1 49.000000]

[Epoch 92/500] [Batch 580/676] [D loss: -0.020598] [G loss: 0.002290] [d1 loss: 0.077174] [d2 loss: 0.063178]  [sq d1 d2: 0.000196]  [num0: 13.000000] [num1 51.000000]
[Epoch 92/500] [Batch 600/676] [D loss: -0.037983] [G loss: -0.045423] [d1 loss: 0.134226] [d2 loss: 0.119128]  [sq d1 d2: 0.000228]  [num0: 13.000000] [num1 51.000000]
[Epoch 92/500] [Batch 620/676] [D loss: -0.085491] [G loss: -0.027300] [d1 loss: 0.093403] [d2 loss: 0.072867]  [sq d1 d2: 0.000422]  [num0: 10.000000] [num1 54.000000]
[Epoch 92/500] [Batch 640/676] [D loss: -0.077494] [G loss: -0.063362] [d1 loss: 0.113430] [d2 loss: 0.106953]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 92/500] [Batch 660/676] [D loss: -0.082945] [G loss: -0.041708] [d1 loss: 0.211322] [d2 loss: 0.163039]  [sq d1 d2: 0.002331]  [num0: 13.000000] [num1 51.000000]
[Epoch 93/500] [Batch 0/676] [D loss: -0.130278] [G loss: 0.001428] [d1 loss: 0.084790] [d2 loss: 0.090435]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 20/676] [D loss: -0.051026] [G loss: -0.014828] [d1 loss: 0.124309] [d2 loss: 0.103074]  [sq d1 d2: 0.000451]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 40/676] [D loss: 0.007390] [G loss: -0.015856] [d1 loss: 0.106701] [d2 loss: 0.071594]  [sq d1 d2: 0.001233]  [num0: 16.000000] [num1 48.000000]
[Epoch 93/500] [Batch 60/676] [D loss: 0.029708] [G loss: -0.022686] [d1 loss: 0.243563] [d2 loss: 0.218853]  [sq d1 d2: 0.000611]  [num0: 13.000000] [num1 51.000000]
[Epoch 93/500] [Batch 80/676] [D loss: -0.035118] [G loss: 0.056763] [d1 loss: 0.193667] [d2 loss: 0.225764]  [sq d1 d2: 0.001030]  [num0: 18.000000] [num1 46.000000]
[Epoch 93/500] [Batch 100/676] [D loss: -0.015904] [G loss: 0.146470] [d1 loss: 0.104033] [d2 loss: 0.091966]  [sq d1 d2: 0.000146]  [num0: 17.000000] [num1 47.000000]
[Epoch 93/500] [Batch 120/676] [D loss: -0.048462] [G loss: 0.229834] [d1 loss: 0.071206] [d2 loss: 0.053274]  [sq d1 d2: 0.000322]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 140/676] [D loss: -0.029038] [G loss: 0.295918] [d1 loss: 0.123835] [d2 loss: 0.123923]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 160/676] [D loss: -0.041436] [G loss: 0.375953] [d1 loss: 0.110457] [d2 loss: 0.127559]  [sq d1 d2: 0.000292]  [num0: 18.000000] [num1 46.000000]
[Epoch 93/500] [Batch 180/676] [D loss: -0.036943] [G loss: 0.452538] [d1 loss: 0.173414] [d2 loss: 0.146669]  [sq d1 d2: 0.000715]  [num0: 19.000000] [num1 45.000000]
[Epoch 93/500] [Batch 200/676] [D loss: -0.092943] [G loss: 0.540708] [d1 loss: 0.092236] [d2 loss: 0.097388]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 93/500] [Batch 220/676] [D loss: -0.089361] [G loss: 0.479105] [d1 loss: 0.140989] [d2 loss: 0.126104]  [sq d1 d2: 0.000222]  [num0: 13.000000] [num1 51.000000]
[Epoch 93/500] [Batch 240/676] [D loss: -0.035956] [G loss: 0.405984] [d1 loss: 0.099998] [d2 loss: 0.092003]  [sq d1 d2: 0.000064]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 260/676] [D loss: 0.017195] [G loss: 0.358143] [d1 loss: 0.083821] [d2 loss: 0.087378]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 93/500] [Batch 280/676] [D loss: 0.027744] [G loss: 0.340334] [d1 loss: 0.072287] [d2 loss: 0.057217]  [sq d1 d2: 0.000227]  [num0: 12.000000] [num1 52.000000]
[Epoch 93/500] [Batch 300/676] [D loss: -0.040992] [G loss: 0.310363] [d1 loss: 0.112882] [d2 loss: 0.107428]  [sq d1 d2: 0.000030]  [num0: 18.000000] [num1 46.000000]
[Epoch 93/500] [Batch 320/676] [D loss: -0.017220] [G loss: 0.220199] [d1 loss: 0.132943] [d2 loss: 0.153002]  [sq d1 d2: 0.000402]  [num0: 14.000000] [num1 50.000000]
[Epoch 93/500] [Batch 340/676] [D loss: -0.023874] [G loss: 0.180943] [d1 loss: 0.107424] [d2 loss: 0.096352]  [sq d1 d2: 0.000123]  [num0: 18.000000] [num1 46.000000]
[Epoch 93/500] [Batch 360/676] [D loss: -0.035359] [G loss: 0.070141] [d1 loss: 0.157383] [d2 loss: 0.139488]  [sq d1 d2: 0.000320]  [num0: 14.000000] [num1 50.000000]
[Epoch 93/500] [Batch 380/676] [D loss: -0.083570] [G loss: -0.020800] [d1 loss: 0.085831] [d2 loss: 0.074197]  [sq d1 d2: 0.000135]  [num0: 20.000000] [num1 44.000000]
[Epoch 93/500] [Batch 400/676] [D loss: -0.058924] [G loss: -0.173250] [d1 loss: 0.144721] [d2 loss: 0.117939]  [sq d1 d2: 0.000717]  [num0: 17.000000] [num1 47.000000]
[Epoch 93/500] [Batch 420/676] [D loss: -0.076232] [G loss: -0.238780] [d1 loss: 0.114727] [d2 loss: 0.114712]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 93/500] [Batch 440/676] [D loss: -0.036880] [G loss: -0.350383] [d1 loss: 0.115115] [d2 loss: 0.136119]  [sq d1 d2: 0.000441]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 460/676] [D loss: -0.012462] [G loss: -0.426962] [d1 loss: 0.077806] [d2 loss: 0.076247]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 93/500] [Batch 480/676] [D loss: 0.052477] [G loss: -0.497151] [d1 loss: 0.065877] [d2 loss: 0.061869]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 500/676] [D loss: 0.016131] [G loss: -0.523258] [d1 loss: 0.102580] [d2 loss: 0.103350]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 93/500] [Batch 520/676] [D loss: 0.011717] [G loss: -0.506124] [d1 loss: 0.076480] [d2 loss: 0.068779]  [sq d1 d2: 0.000059]  [num0: 10.000000] [num1 54.000000]
[Epoch 93/500] [Batch 540/676] [D loss: -0.020485] [G loss: -0.436835] [d1 loss: 0.136838] [d2 loss: 0.133869]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 93/500] [Batch 560/676] [D loss: -0.015749] [G loss: -0.364317] [d1 loss: 0.163202] [d2 loss: 0.161971]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 580/676] [D loss: -0.036887] [G loss: -0.269155] [d1 loss: 0.083995] [d2 loss: 0.082278]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 93/500] [Batch 600/676] [D loss: -0.019225] [G loss: -0.194300] [d1 loss: 0.172229] [d2 loss: 0.159708]  [sq d1 d2: 0.000157]  [num0: 15.000000] [num1 49.000000]
[Epoch 93/500] [Batch 620/676] [D loss: -0.052045] [G loss: -0.108806] [d1 loss: 0.129838] [d2 loss: 0.138430]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 93/500] [Batch 640/676] [D loss: -0.056418] [G loss: -0.041501] [d1 loss: 0.094956] [d2 loss: 0.093485]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 93/500] [Batch 660/676] [D loss: -0.035537] [G loss: -0.017493] [d1 loss: 0.081885] [d2 loss: 0.079963]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 94/500] [Batch 0/676] [D loss: -0.012964] [G loss: -0.025823] [d1 loss: 0.156670] [d2 loss: 0.141111]  [sq d1 d2: 0.000242]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 20/676] [D loss: -0.035612] [G loss: 0.025147] [d1 loss: 0.035474] [d2 loss: 0.027358]  [sq d1 d2: 0.000066]  [num0: 12.000000] [num1 52.000000]
[Epoch 94/500] [Batch 40/676] [D loss: -0.026240] [G loss: 0.075861] [d1 loss: 0.213595] [d2 loss: 0.216099]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 60/676] [D loss: 0.016107] [G loss: 0.138387] [d1 loss: 0.068010] [d2 loss: 0.061102]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 80/676] [D loss: -0.026505] [G loss: 0.220728] [d1 loss: 0.097727] [d2 loss: 0.098829]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 94/500] [Batch 100/676] [D loss: -0.020994] [G loss: 0.262993] [d1 loss: 0.115185] [d2 loss: 0.130722]  [sq d1 d2: 0.000241]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 120/676] [D loss: -0.039607] [G loss: 0.276759] [d1 loss: 0.086630] [d2 loss: 0.075960]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 140/676] [D loss: -0.065442] [G loss: 0.325992] [d1 loss: 0.120790] [d2 loss: 0.106047]  [sq d1 d2: 0.000217]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 160/676] [D loss: -0.040430] [G loss: 0.333927] [d1 loss: 0.135093] [d2 loss: 0.156271]  [sq d1 d2: 0.000449]  [num0: 13.000000] [num1 51.000000]
[Epoch 94/500] [Batch 180/676] [D loss: -0.003688] [G loss: 0.304611] [d1 loss: 0.183633] [d2 loss: 0.158884]  [sq d1 d2: 0.000613]  [num0: 17.000000] [num1 47.000000]
[Epoch 94/500] [Batch 200/676] [D loss: -0.031836] [G loss: 0.298074] [d1 loss: 0.130074] [d2 loss: 0.124337]  [sq d1 d2: 0.000033]  [num0: 20.000000] [num1 44.000000]
[Epoch 94/500] [Batch 220/676] [D loss: -0.026867] [G loss: 0.230457] [d1 loss: 0.154600] [d2 loss: 0.141719]  [sq d1 d2: 0.000166]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 240/676] [D loss: 0.002928] [G loss: 0.190970] [d1 loss: 0.065651] [d2 loss: 0.052273]  [sq d1 d2: 0.000179]  [num0: 11.000000] [num1 53.000000]

[Epoch 94/500] [Batch 260/676] [D loss: 0.016508] [G loss: 0.087275] [d1 loss: 0.100267] [d2 loss: 0.095616]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 280/676] [D loss: 0.008538] [G loss: 0.052864] [d1 loss: 0.122832] [d2 loss: 0.121164]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 94/500] [Batch 300/676] [D loss: -0.003384] [G loss: 0.025340] [d1 loss: 0.112327] [d2 loss: 0.100689]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 320/676] [D loss: -0.004034] [G loss: 0.026191] [d1 loss: 0.101172] [d2 loss: 0.093573]  [sq d1 d2: 0.000058]  [num0: 17.000000] [num1 47.000000]
[Epoch 94/500] [Batch 340/676] [D loss: 0.004561] [G loss: -0.009077] [d1 loss: 0.095269] [d2 loss: 0.090245]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 360/676] [D loss: -0.012441] [G loss: -0.025709] [d1 loss: 0.138077] [d2 loss: 0.116060]  [sq d1 d2: 0.000485]  [num0: 17.000000] [num1 47.000000]
[Epoch 94/500] [Batch 380/676] [D loss: -0.018118] [G loss: -0.063932] [d1 loss: 0.067793] [d2 loss: 0.048284]  [sq d1 d2: 0.000381]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 400/676] [D loss: -0.045090] [G loss: -0.094190] [d1 loss: 0.094398] [d2 loss: 0.055989]  [sq d1 d2: 0.001475]  [num0: 18.000000] [num1 46.000000]
[Epoch 94/500] [Batch 420/676] [D loss: -0.040604] [G loss: -0.124049] [d1 loss: 0.094263] [d2 loss: 0.098665]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 94/500] [Batch 440/676] [D loss: -0.058286] [G loss: -0.123300] [d1 loss: 0.109040] [d2 loss: 0.102737]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 94/500] [Batch 460/676] [D loss: 0.008657] [G loss: -0.149405] [d1 loss: 0.155134] [d2 loss: 0.152205]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 480/676] [D loss: -0.034238] [G loss: -0.150855] [d1 loss: 0.079260] [d2 loss: 0.101809]  [sq d1 d2: 0.000508]  [num0: 13.000000] [num1 51.000000]
[Epoch 94/500] [Batch 500/676] [D loss: -0.009656] [G loss: -0.146536] [d1 loss: 0.061993] [d2 loss: 0.057899]  [sq d1 d2: 0.000017]  [num0: 12.000000] [num1 52.000000]
[Epoch 94/500] [Batch 520/676] [D loss: -0.013974] [G loss: -0.136721] [d1 loss: 0.072543] [d2 loss: 0.071454]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 94/500] [Batch 540/676] [D loss: 0.037223] [G loss: -0.114394] [d1 loss: 0.091054] [d2 loss: 0.087647]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 560/676] [D loss: -0.001890] [G loss: -0.074908] [d1 loss: 0.081631] [d2 loss: 0.075336]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 94/500] [Batch 580/676] [D loss: 0.003716] [G loss: -0.014513] [d1 loss: 0.043926] [d2 loss: 0.034224]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 94/500] [Batch 600/676] [D loss: -0.008316] [G loss: 0.018786] [d1 loss: 0.052689] [d2 loss: 0.057943]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 94/500] [Batch 620/676] [D loss: -0.002860] [G loss: 0.035244] [d1 loss: 0.087069] [d2 loss: 0.081910]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 94/500] [Batch 640/676] [D loss: -0.045939] [G loss: 0.019570] [d1 loss: 0.096693] [d2 loss: 0.094733]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 94/500] [Batch 660/676] [D loss: -0.028846] [G loss: 0.006164] [d1 loss: 0.110263] [d2 loss: 0.109275]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 95/500] [Batch 0/676] [D loss: -0.042903] [G loss: 0.004337] [d1 loss: 0.148758] [d2 loss: 0.131928]  [sq d1 d2: 0.000283]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 20/676] [D loss: -0.020775] [G loss: -0.001431] [d1 loss: 0.115635] [d2 loss: 0.129478]  [sq d1 d2: 0.000192]  [num0: 17.000000] [num1 47.000000]
[Epoch 95/500] [Batch 40/676] [D loss: -0.015893] [G loss: 0.033182] [d1 loss: 0.039796] [d2 loss: 0.050349]  [sq d1 d2: 0.000111]  [num0: 16.000000] [num1 48.000000]
[Epoch 95/500] [Batch 60/676] [D loss: -0.000920] [G loss: -0.041956] [d1 loss: 0.094375] [d2 loss: 0.095348]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 80/676] [D loss: -0.006667] [G loss: -0.048408] [d1 loss: 0.098766] [d2 loss: 0.083776]  [sq d1 d2: 0.000225]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 100/676] [D loss: -0.013836] [G loss: -0.064948] [d1 loss: 0.102041] [d2 loss: 0.102392]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 120/676] [D loss: -0.014975] [G loss: -0.045062] [d1 loss: 0.139247] [d2 loss: 0.118470]  [sq d1 d2: 0.000432]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 140/676] [D loss: 0.000448] [G loss: -0.042158] [d1 loss: 0.064542] [d2 loss: 0.069576]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 95/500] [Batch 160/676] [D loss: -0.006723] [G loss: -0.076698] [d1 loss: 0.069235] [d2 loss: 0.070440]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 95/500] [Batch 180/676] [D loss: -0.018496] [G loss: -0.071964] [d1 loss: 0.118665] [d2 loss: 0.111130]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 200/676] [D loss: -0.035774] [G loss: -0.075434] [d1 loss: 0.093569] [d2 loss: 0.067589]  [sq d1 d2: 0.000675]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 220/676] [D loss: -0.028347] [G loss: -0.064223] [d1 loss: 0.123989] [d2 loss: 0.121923]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 240/676] [D loss: -0.040657] [G loss: -0.040305] [d1 loss: 0.120535] [d2 loss: 0.106246]  [sq d1 d2: 0.000204]  [num0: 16.000000] [num1 48.000000]
[Epoch 95/500] [Batch 260/676] [D loss: 0.004681] [G loss: -0.066605] [d1 loss: 0.111537] [d2 loss: 0.110784]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 280/676] [D loss: 0.003156] [G loss: -0.010993] [d1 loss: 0.077203] [d2 loss: 0.082183]  [sq d1 d2: 0.000025]  [num0: 20.000000] [num1 44.000000]
[Epoch 95/500] [Batch 300/676] [D loss: 0.026386] [G loss: 0.038586] [d1 loss: 0.150936] [d2 loss: 0.114787]  [sq d1 d2: 0.001307]  [num0: 16.000000] [num1 48.000000]
[Epoch 95/500] [Batch 320/676] [D loss: -0.006298] [G loss: 0.075180] [d1 loss: 0.196106] [d2 loss: 0.223148]  [sq d1 d2: 0.000731]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 340/676] [D loss: -0.015978] [G loss: 0.129126] [d1 loss: 0.067090] [d2 loss: 0.052466]  [sq d1 d2: 0.000214]  [num0: 19.000000] [num1 45.000000]
[Epoch 95/500] [Batch 360/676] [D loss: 0.001477] [G loss: 0.144694] [d1 loss: 0.089567] [d2 loss: 0.075297]  [sq d1 d2: 0.000204]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 380/676] [D loss: -0.044121] [G loss: 0.192865] [d1 loss: 0.052943] [d2 loss: 0.054209]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 95/500] [Batch 400/676] [D loss: -0.023982] [G loss: 0.221611] [d1 loss: 0.073832] [d2 loss: 0.077110]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 95/500] [Batch 420/676] [D loss: -0.062310] [G loss: 0.247433] [d1 loss: 0.134338] [d2 loss: 0.126178]  [sq d1 d2: 0.000067]  [num0: 19.000000] [num1 45.000000]
[Epoch 95/500] [Batch 440/676] [D loss: -0.043971] [G loss: 0.239044] [d1 loss: 0.137710] [d2 loss: 0.153559]  [sq d1 d2: 0.000251]  [num0: 10.000000] [num1 54.000000]
[Epoch 95/500] [Batch 460/676] [D loss: -0.029329] [G loss: 0.271875] [d1 loss: 0.083437] [d2 loss: 0.070422]  [sq d1 d2: 0.000169]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 480/676] [D loss: -0.006060] [G loss: 0.160346] [d1 loss: 0.125785] [d2 loss: 0.111042]  [sq d1 d2: 0.000217]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 500/676] [D loss: -0.009603] [G loss: 0.104552] [d1 loss: 0.121138] [d2 loss: 0.138169]  [sq d1 d2: 0.000290]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 520/676] [D loss: -0.001846] [G loss: 0.091540] [d1 loss: 0.132345] [d2 loss: 0.103406]  [sq d1 d2: 0.000837]  [num0: 15.000000] [num1 49.000000]
[Epoch 95/500] [Batch 540/676] [D loss: 0.006963] [G loss: 0.036074] [d1 loss: 0.115905] [d2 loss: 0.090911]  [sq d1 d2: 0.000625]  [num0: 13.000000] [num1 51.000000]
[Epoch 95/500] [Batch 560/676] [D loss: -0.000397] [G loss: 0.024151] [d1 loss: 0.109343] [d2 loss: 0.093700]  [sq d1 d2: 0.000245]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 580/676] [D loss: -0.007434] [G loss: 0.012411] [d1 loss: 0.144428] [d2 loss: 0.186712]  [sq d1 d2: 0.001788]  [num0: 18.000000] [num1 46.000000]
[Epoch 95/500] [Batch 600/676] [D loss: -0.012159] [G loss: -0.011636] [d1 loss: 0.159083] [d2 loss: 0.154275]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]

[Epoch 95/500] [Batch 620/676] [D loss: -0.007576] [G loss: -0.039011] [d1 loss: 0.136985] [d2 loss: 0.128696]  [sq d1 d2: 0.000069]  [num0: 13.000000] [num1 51.000000]
[Epoch 95/500] [Batch 640/676] [D loss: -0.028133] [G loss: -0.071361] [d1 loss: 0.084985] [d2 loss: 0.084075]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 95/500] [Batch 660/676] [D loss: -0.021805] [G loss: -0.107352] [d1 loss: 0.171329] [d2 loss: 0.145006]  [sq d1 d2: 0.000693]  [num0: 16.000000] [num1 48.000000]
[Epoch 96/500] [Batch 0/676] [D loss: -0.039018] [G loss: -0.090406] [d1 loss: 0.046363] [d2 loss: 0.046560]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 96/500] [Batch 20/676] [D loss: -0.018384] [G loss: -0.069544] [d1 loss: 0.080688] [d2 loss: 0.068415]  [sq d1 d2: 0.000151]  [num0: 14.000000] [num1 50.000000]
[Epoch 96/500] [Batch 40/676] [D loss: -0.004113] [G loss: -0.069289] [d1 loss: 0.110752] [d2 loss: 0.097066]  [sq d1 d2: 0.000187]  [num0: 18.000000] [num1 46.000000]
[Epoch 96/500] [Batch 60/676] [D loss: 0.023853] [G loss: -0.088145] [d1 loss: 0.049316] [d2 loss: 0.045107]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 80/676] [D loss: 0.000536] [G loss: -0.086271] [d1 loss: 0.079862] [d2 loss: 0.090582]  [sq d1 d2: 0.000115]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 100/676] [D loss: 0.002332] [G loss: -0.062813] [d1 loss: 0.162183] [d2 loss: 0.141209]  [sq d1 d2: 0.000440]  [num0: 17.000000] [num1 47.000000]
[Epoch 96/500] [Batch 120/676] [D loss: -0.003206] [G loss: -0.039335] [d1 loss: 0.147230] [d2 loss: 0.124142]  [sq d1 d2: 0.000533]  [num0: 13.000000] [num1 51.000000]
[Epoch 96/500] [Batch 140/676] [D loss: 0.008343] [G loss: -0.004211] [d1 loss: 0.111860] [d2 loss: 0.127897]  [sq d1 d2: 0.000257]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 160/676] [D loss: -0.005489] [G loss: -0.002916] [d1 loss: 0.147609] [d2 loss: 0.162816]  [sq d1 d2: 0.000231]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 180/676] [D loss: -0.024739] [G loss: 0.011898] [d1 loss: 0.071342] [d2 loss: 0.079824]  [sq d1 d2: 0.000072]  [num0: 14.000000] [num1 50.000000]
[Epoch 96/500] [Batch 200/676] [D loss: -0.024476] [G loss: 0.039453] [d1 loss: 0.172329] [d2 loss: 0.151369]  [sq d1 d2: 0.000439]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 220/676] [D loss: -0.049890] [G loss: 0.087995] [d1 loss: 0.060228] [d2 loss: 0.052902]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 96/500] [Batch 240/676] [D loss: -0.029161] [G loss: 0.060323] [d1 loss: 0.056201] [d2 loss: 0.053806]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 96/500] [Batch 260/676] [D loss: -0.047282] [G loss: -0.017909] [d1 loss: 0.082191] [d2 loss: 0.070734]  [sq d1 d2: 0.000131]  [num0: 17.000000] [num1 47.000000]
[Epoch 96/500] [Batch 280/676] [D loss: -0.026557] [G loss: -0.078930] [d1 loss: 0.061055] [d2 loss: 0.069812]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 300/676] [D loss: 0.007559] [G loss: -0.124410] [d1 loss: 0.084426] [d2 loss: 0.065213]  [sq d1 d2: 0.000369]  [num0: 13.000000] [num1 51.000000]
[Epoch 96/500] [Batch 320/676] [D loss: 0.011926] [G loss: -0.114668] [d1 loss: 0.086595] [d2 loss: 0.058791]  [sq d1 d2: 0.000773]  [num0: 13.000000] [num1 51.000000]
[Epoch 96/500] [Batch 340/676] [D loss: 0.001912] [G loss: -0.103359] [d1 loss: 0.123508] [d2 loss: 0.129089]  [sq d1 d2: 0.000031]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 360/676] [D loss: -0.008385] [G loss: -0.113339] [d1 loss: 0.094100] [d2 loss: 0.093487]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 380/676] [D loss: -0.015131] [G loss: -0.120691] [d1 loss: 0.131226] [d2 loss: 0.139940]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 400/676] [D loss: -0.023713] [G loss: -0.130248] [d1 loss: 0.130053] [d2 loss: 0.115239]  [sq d1 d2: 0.000219]  [num0: 13.000000] [num1 51.000000]
[Epoch 96/500] [Batch 420/676] [D loss: -0.017090] [G loss: -0.143082] [d1 loss: 0.083421] [d2 loss: 0.070987]  [sq d1 d2: 0.000155]  [num0: 18.000000] [num1 46.000000]
[Epoch 96/500] [Batch 440/676] [D loss: -0.016782] [G loss: -0.146767] [d1 loss: 0.112764] [d2 loss: 0.087018]  [sq d1 d2: 0.000663]  [num0: 17.000000] [num1 47.000000]
[Epoch 96/500] [Batch 460/676] [D loss: 0.014419] [G loss: -0.141687] [d1 loss: 0.246445] [d2 loss: 0.213458]  [sq d1 d2: 0.001088]  [num0: 16.000000] [num1 48.000000]
[Epoch 96/500] [Batch 480/676] [D loss: -0.014111] [G loss: -0.128727] [d1 loss: 0.067343] [d2 loss: 0.101745]  [sq d1 d2: 0.001184]  [num0: 16.000000] [num1 48.000000]
[Epoch 96/500] [Batch 500/676] [D loss: -0.028523] [G loss: -0.153639] [d1 loss: 0.077023] [d2 loss: 0.077398]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 96/500] [Batch 520/676] [D loss: -0.006120] [G loss: -0.119129] [d1 loss: 0.087776] [d2 loss: 0.091620]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 540/676] [D loss: -0.001841] [G loss: -0.105983] [d1 loss: 0.138411] [d2 loss: 0.128415]  [sq d1 d2: 0.000100]  [num0: 19.000000] [num1 45.000000]
[Epoch 96/500] [Batch 560/676] [D loss: -0.009234] [G loss: -0.090076] [d1 loss: 0.115818] [d2 loss: 0.130884]  [sq d1 d2: 0.000227]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 580/676] [D loss: 0.007546] [G loss: -0.030084] [d1 loss: 0.170940] [d2 loss: 0.161869]  [sq d1 d2: 0.000082]  [num0: 18.000000] [num1 46.000000]
[Epoch 96/500] [Batch 600/676] [D loss: -0.003742] [G loss: 0.009769] [d1 loss: 0.103358] [d2 loss: 0.091398]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 96/500] [Batch 620/676] [D loss: -0.011356] [G loss: 0.043201] [d1 loss: 0.138304] [d2 loss: 0.125322]  [sq d1 d2: 0.000169]  [num0: 15.000000] [num1 49.000000]
[Epoch 96/500] [Batch 640/676] [D loss: -0.019348] [G loss: 0.081273] [d1 loss: 0.094356] [d2 loss: 0.100326]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 96/500] [Batch 660/676] [D loss: -0.018131] [G loss: 0.115070] [d1 loss: 0.052383] [d2 loss: 0.057805]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 97/500] [Batch 0/676] [D loss: -0.023852] [G loss: 0.187966] [d1 loss: 0.074288] [d2 loss: 0.082326]  [sq d1 d2: 0.000065]  [num0: 18.000000] [num1 46.000000]
[Epoch 97/500] [Batch 20/676] [D loss: -0.047254] [G loss: 0.219367] [d1 loss: 0.115484] [d2 loss: 0.110392]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 97/500] [Batch 40/676] [D loss: -0.014635] [G loss: 0.237378] [d1 loss: 0.058731] [d2 loss: 0.062722]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 97/500] [Batch 60/676] [D loss: 0.010992] [G loss: 0.198450] [d1 loss: 0.108226] [d2 loss: 0.069323]  [sq d1 d2: 0.001513]  [num0: 17.000000] [num1 47.000000]
[Epoch 97/500] [Batch 80/676] [D loss: 0.005690] [G loss: 0.164034] [d1 loss: 0.059689] [d2 loss: 0.050278]  [sq d1 d2: 0.000089]  [num0: 15.000000] [num1 49.000000]
[Epoch 97/500] [Batch 100/676] [D loss: -0.010057] [G loss: 0.109045] [d1 loss: 0.065045] [d2 loss: 0.058590]  [sq d1 d2: 0.000042]  [num0: 12.000000] [num1 52.000000]
[Epoch 97/500] [Batch 120/676] [D loss: 0.011323] [G loss: 0.099765] [d1 loss: 0.088739] [d2 loss: 0.089033]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 97/500] [Batch 140/676] [D loss: -0.004311] [G loss: 0.093266] [d1 loss: 0.177793] [d2 loss: 0.153336]  [sq d1 d2: 0.000598]  [num0: 18.000000] [num1 46.000000]
[Epoch 97/500] [Batch 160/676] [D loss: -0.003207] [G loss: 0.086408] [d1 loss: 0.075769] [d2 loss: 0.064395]  [sq d1 d2: 0.000129]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 180/676] [D loss: -0.017885] [G loss: 0.090186] [d1 loss: 0.111772] [d2 loss: 0.104372]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 200/676] [D loss: -0.033117] [G loss: 0.067047] [d1 loss: 0.063856] [d2 loss: 0.060404]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 220/676] [D loss: -0.032042] [G loss: 0.036949] [d1 loss: 0.124958] [d2 loss: 0.121873]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 240/676] [D loss: -0.054785] [G loss: 0.019346] [d1 loss: 0.123738] [d2 loss: 0.121072]  [sq d1 d2: 0.000007]  [num0: 11.000000] [num1 53.000000]

[Epoch 97/500] [Batch 260/676] [D loss: -0.021230] [G loss: -0.030890] [d1 loss: 0.080053] [d2 loss: 0.081606]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 97/500] [Batch 280/676] [D loss: -0.007074] [G loss: -0.024001] [d1 loss: 0.095867] [d2 loss: 0.095129]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 300/676] [D loss: -0.017591] [G loss: -0.032413] [d1 loss: 0.114676] [d2 loss: 0.096431]  [sq d1 d2: 0.000333]  [num0: 19.000000] [num1 45.000000]
[Epoch 97/500] [Batch 320/676] [D loss: 0.011632] [G loss: -0.022590] [d1 loss: 0.080765] [d2 loss: 0.091011]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 97/500] [Batch 340/676] [D loss: 0.003820] [G loss: 0.012478] [d1 loss: 0.047734] [d2 loss: 0.050950]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 360/676] [D loss: 0.000867] [G loss: 0.009699] [d1 loss: 0.171381] [d2 loss: 0.165414]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 97/500] [Batch 380/676] [D loss: 0.004528] [G loss: -0.009357] [d1 loss: 0.071891] [d2 loss: 0.084029]  [sq d1 d2: 0.000147]  [num0: 20.000000] [num1 44.000000]
[Epoch 97/500] [Batch 400/676] [D loss: -0.002888] [G loss: -0.003826] [d1 loss: 0.195357] [d2 loss: 0.187558]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 97/500] [Batch 420/676] [D loss: -0.019068] [G loss: -0.011873] [d1 loss: 0.223743] [d2 loss: 0.206390]  [sq d1 d2: 0.000301]  [num0: 13.000000] [num1 51.000000]
[Epoch 97/500] [Batch 440/676] [D loss: -0.016291] [G loss: -0.013522] [d1 loss: 0.197893] [d2 loss: 0.171884]  [sq d1 d2: 0.000676]  [num0: 18.000000] [num1 46.000000]
[Epoch 97/500] [Batch 460/676] [D loss: -0.040924] [G loss: -0.005611] [d1 loss: 0.166238] [d2 loss: 0.171986]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 97/500] [Batch 480/676] [D loss: -0.054449] [G loss: 0.008935] [d1 loss: 0.107743] [d2 loss: 0.091345]  [sq d1 d2: 0.000269]  [num0: 12.000000] [num1 52.000000]
[Epoch 97/500] [Batch 500/676] [D loss: -0.026000] [G loss: 0.086344] [d1 loss: 0.034226] [d2 loss: 0.030199]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 97/500] [Batch 520/676] [D loss: 0.002230] [G loss: 0.046995] [d1 loss: 0.074705] [d2 loss: 0.064071]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 97/500] [Batch 540/676] [D loss: 0.014385] [G loss: -0.036705] [d1 loss: 0.098027] [d2 loss: 0.093031]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 97/500] [Batch 560/676] [D loss: 0.007161] [G loss: -0.083732] [d1 loss: 0.088160] [d2 loss: 0.064488]  [sq d1 d2: 0.000560]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 580/676] [D loss: 0.014660] [G loss: -0.094147] [d1 loss: 0.060766] [d2 loss: 0.044987]  [sq d1 d2: 0.000249]  [num0: 13.000000] [num1 51.000000]
[Epoch 97/500] [Batch 600/676] [D loss: 0.005344] [G loss: -0.065319] [d1 loss: 0.119596] [d2 loss: 0.115649]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 97/500] [Batch 620/676] [D loss: 0.004308] [G loss: -0.059809] [d1 loss: 0.171397] [d2 loss: 0.160490]  [sq d1 d2: 0.000119]  [num0: 17.000000] [num1 47.000000]
[Epoch 97/500] [Batch 640/676] [D loss: -0.008898] [G loss: -0.059744] [d1 loss: 0.125827] [d2 loss: 0.101991]  [sq d1 d2: 0.000568]  [num0: 19.000000] [num1 45.000000]
[Epoch 97/500] [Batch 660/676] [D loss: -0.032448] [G loss: -0.063610] [d1 loss: 0.073303] [d2 loss: 0.073143]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 98/500] [Batch 0/676] [D loss: -0.018352] [G loss: -0.034305] [d1 loss: 0.048519] [d2 loss: 0.042688]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 98/500] [Batch 20/676] [D loss: -0.035155] [G loss: -0.001017] [d1 loss: 0.065216] [d2 loss: 0.071344]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 40/676] [D loss: -0.019226] [G loss: 0.008414] [d1 loss: 0.113526] [d2 loss: 0.137132]  [sq d1 d2: 0.000557]  [num0: 11.000000] [num1 53.000000]
[Epoch 98/500] [Batch 60/676] [D loss: -0.036524] [G loss: 0.001861] [d1 loss: 0.108358] [d2 loss: 0.100201]  [sq d1 d2: 0.000067]  [num0: 12.000000] [num1 52.000000]
[Epoch 98/500] [Batch 80/676] [D loss: 0.007676] [G loss: -0.015821] [d1 loss: 0.133446] [d2 loss: 0.131845]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 100/676] [D loss: -0.006001] [G loss: 0.007100] [d1 loss: 0.186878] [d2 loss: 0.153952]  [sq d1 d2: 0.001084]  [num0: 14.000000] [num1 50.000000]
[Epoch 98/500] [Batch 120/676] [D loss: 0.018581] [G loss: 0.016687] [d1 loss: 0.035710] [d2 loss: 0.047252]  [sq d1 d2: 0.000133]  [num0: 17.000000] [num1 47.000000]
[Epoch 98/500] [Batch 140/676] [D loss: 0.014737] [G loss: 0.066014] [d1 loss: 0.056279] [d2 loss: 0.064391]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 160/676] [D loss: 0.008492] [G loss: 0.050012] [d1 loss: 0.073632] [d2 loss: 0.095239]  [sq d1 d2: 0.000467]  [num0: 13.000000] [num1 51.000000]
[Epoch 98/500] [Batch 180/676] [D loss: -0.002994] [G loss: 0.037344] [d1 loss: 0.036952] [d2 loss: 0.048524]  [sq d1 d2: 0.000134]  [num0: 12.000000] [num1 52.000000]
[Epoch 98/500] [Batch 200/676] [D loss: -0.006356] [G loss: 0.040947] [d1 loss: 0.181259] [d2 loss: 0.169528]  [sq d1 d2: 0.000138]  [num0: 10.000000] [num1 54.000000]
[Epoch 98/500] [Batch 220/676] [D loss: -0.013171] [G loss: 0.044010] [d1 loss: 0.081269] [d2 loss: 0.067389]  [sq d1 d2: 0.000193]  [num0: 11.000000] [num1 53.000000]
[Epoch 98/500] [Batch 240/676] [D loss: -0.031689] [G loss: 0.100213] [d1 loss: 0.081116] [d2 loss: 0.076968]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 260/676] [D loss: -0.008447] [G loss: 0.167999] [d1 loss: 0.093139] [d2 loss: 0.093136]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 98/500] [Batch 280/676] [D loss: -0.067881] [G loss: 0.193292] [d1 loss: 0.098333] [d2 loss: 0.107350]  [sq d1 d2: 0.000081]  [num0: 17.000000] [num1 47.000000]
[Epoch 98/500] [Batch 300/676] [D loss: -0.038254] [G loss: 0.220582] [d1 loss: 0.053683] [d2 loss: 0.047295]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 320/676] [D loss: -0.027444] [G loss: 0.134616] [d1 loss: 0.140594] [d2 loss: 0.166785]  [sq d1 d2: 0.000686]  [num0: 14.000000] [num1 50.000000]
[Epoch 98/500] [Batch 340/676] [D loss: 0.022622] [G loss: 0.091655] [d1 loss: 0.071328] [d2 loss: 0.081169]  [sq d1 d2: 0.000097]  [num0: 19.000000] [num1 45.000000]
[Epoch 98/500] [Batch 360/676] [D loss: 0.016026] [G loss: -0.009443] [d1 loss: 0.075261] [d2 loss: 0.075623]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 98/500] [Batch 380/676] [D loss: 0.008984] [G loss: -0.023776] [d1 loss: 0.116148] [d2 loss: 0.118069]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 98/500] [Batch 400/676] [D loss: -0.000184] [G loss: -0.041726] [d1 loss: 0.091064] [d2 loss: 0.087288]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 98/500] [Batch 420/676] [D loss: -0.008201] [G loss: -0.040197] [d1 loss: 0.199061] [d2 loss: 0.178147]  [sq d1 d2: 0.000437]  [num0: 19.000000] [num1 45.000000]
[Epoch 98/500] [Batch 440/676] [D loss: -0.031696] [G loss: -0.034928] [d1 loss: 0.075355] [d2 loss: 0.076035]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 98/500] [Batch 460/676] [D loss: -0.025890] [G loss: -0.009081] [d1 loss: 0.094134] [d2 loss: 0.118594]  [sq d1 d2: 0.000598]  [num0: 14.000000] [num1 50.000000]
[Epoch 98/500] [Batch 480/676] [D loss: -0.031712] [G loss: 0.046417] [d1 loss: 0.153326] [d2 loss: 0.168822]  [sq d1 d2: 0.000240]  [num0: 13.000000] [num1 51.000000]
[Epoch 98/500] [Batch 500/676] [D loss: -0.033263] [G loss: 0.066385] [d1 loss: 0.090627] [d2 loss: 0.087217]  [sq d1 d2: 0.000012]  [num0: 20.000000] [num1 44.000000]
[Epoch 98/500] [Batch 520/676] [D loss: -0.042913] [G loss: 0.020434] [d1 loss: 0.062979] [d2 loss: 0.061185]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 540/676] [D loss: -0.036936] [G loss: -0.032613] [d1 loss: 0.108639] [d2 loss: 0.095302]  [sq d1 d2: 0.000178]  [num0: 15.000000] [num1 49.000000]

[Epoch 98/500] [Batch 560/676] [D loss: 0.009111] [G loss: -0.041772] [d1 loss: 0.086522] [d2 loss: 0.100216]  [sq d1 d2: 0.000188]  [num0: 18.000000] [num1 46.000000]
[Epoch 98/500] [Batch 580/676] [D loss: 0.014951] [G loss: -0.042941] [d1 loss: 0.099333] [d2 loss: 0.067598]  [sq d1 d2: 0.001007]  [num0: 13.000000] [num1 51.000000]
[Epoch 98/500] [Batch 600/676] [D loss: 0.004328] [G loss: -0.072056] [d1 loss: 0.077558] [d2 loss: 0.093522]  [sq d1 d2: 0.000255]  [num0: 15.000000] [num1 49.000000]
[Epoch 98/500] [Batch 620/676] [D loss: 0.016202] [G loss: -0.050538] [d1 loss: 0.078163] [d2 loss: 0.075398]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 98/500] [Batch 640/676] [D loss: 0.004490] [G loss: -0.064879] [d1 loss: 0.126656] [d2 loss: 0.158446]  [sq d1 d2: 0.001011]  [num0: 16.000000] [num1 48.000000]
[Epoch 98/500] [Batch 660/676] [D loss: -0.008971] [G loss: -0.074971] [d1 loss: 0.074144] [d2 loss: 0.086468]  [sq d1 d2: 0.000152]  [num0: 18.000000] [num1 46.000000]
[Epoch 99/500] [Batch 0/676] [D loss: -0.014183] [G loss: -0.079148] [d1 loss: 0.044126] [d2 loss: 0.080875]  [sq d1 d2: 0.001350]  [num0: 18.000000] [num1 46.000000]
[Epoch 99/500] [Batch 20/676] [D loss: -0.020977] [G loss: -0.076647] [d1 loss: 0.225030] [d2 loss: 0.244810]  [sq d1 d2: 0.000391]  [num0: 17.000000] [num1 47.000000]
[Epoch 99/500] [Batch 40/676] [D loss: -0.041122] [G loss: -0.099287] [d1 loss: 0.147367] [d2 loss: 0.136133]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 60/676] [D loss: -0.060516] [G loss: -0.085881] [d1 loss: 0.098372] [d2 loss: 0.077089]  [sq d1 d2: 0.000453]  [num0: 13.000000] [num1 51.000000]
[Epoch 99/500] [Batch 80/676] [D loss: -0.064567] [G loss: -0.102405] [d1 loss: 0.120040] [d2 loss: 0.138490]  [sq d1 d2: 0.000340]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 100/676] [D loss: -0.037773] [G loss: -0.107893] [d1 loss: 0.104112] [d2 loss: 0.093488]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 120/676] [D loss: 0.016059] [G loss: -0.127298] [d1 loss: 0.195071] [d2 loss: 0.189283]  [sq d1 d2: 0.000034]  [num0: 19.000000] [num1 45.000000]
[Epoch 99/500] [Batch 140/676] [D loss: 0.007150] [G loss: -0.096215] [d1 loss: 0.088306] [d2 loss: 0.080175]  [sq d1 d2: 0.000066]  [num0: 12.000000] [num1 52.000000]
[Epoch 99/500] [Batch 160/676] [D loss: 0.012551] [G loss: -0.074536] [d1 loss: 0.075193] [d2 loss: 0.077430]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 99/500] [Batch 180/676] [D loss: 0.007020] [G loss: -0.040513] [d1 loss: 0.084253] [d2 loss: 0.097567]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 99/500] [Batch 200/676] [D loss: 0.004237] [G loss: -0.031062] [d1 loss: 0.141954] [d2 loss: 0.137218]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 99/500] [Batch 220/676] [D loss: -0.007971] [G loss: -0.028543] [d1 loss: 0.115994] [d2 loss: 0.104708]  [sq d1 d2: 0.000127]  [num0: 12.000000] [num1 52.000000]
[Epoch 99/500] [Batch 240/676] [D loss: -0.019840] [G loss: -0.031194] [d1 loss: 0.051297] [d2 loss: 0.056988]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 99/500] [Batch 260/676] [D loss: -0.020256] [G loss: 0.002603] [d1 loss: 0.063115] [d2 loss: 0.065330]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 99/500] [Batch 280/676] [D loss: -0.031915] [G loss: 0.066308] [d1 loss: 0.111884] [d2 loss: 0.104085]  [sq d1 d2: 0.000061]  [num0: 12.000000] [num1 52.000000]
[Epoch 99/500] [Batch 300/676] [D loss: -0.029067] [G loss: 0.078516] [d1 loss: 0.057774] [d2 loss: 0.061206]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 99/500] [Batch 320/676] [D loss: -0.046977] [G loss: 0.065576] [d1 loss: 0.022991] [d2 loss: 0.019684]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 99/500] [Batch 340/676] [D loss: -0.028444] [G loss: 0.119191] [d1 loss: 0.123107] [d2 loss: 0.127369]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 99/500] [Batch 360/676] [D loss: -0.003435] [G loss: 0.051388] [d1 loss: 0.141103] [d2 loss: 0.120363]  [sq d1 d2: 0.000430]  [num0: 17.000000] [num1 47.000000]
[Epoch 99/500] [Batch 380/676] [D loss: 0.005573] [G loss: -0.002815] [d1 loss: 0.055510] [d2 loss: 0.046960]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 99/500] [Batch 400/676] [D loss: 0.012438] [G loss: -0.052919] [d1 loss: 0.094381] [d2 loss: 0.099426]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 99/500] [Batch 420/676] [D loss: 0.025314] [G loss: -0.060350] [d1 loss: 0.083591] [d2 loss: 0.094367]  [sq d1 d2: 0.000116]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 440/676] [D loss: 0.013281] [G loss: -0.045632] [d1 loss: 0.087979] [d2 loss: 0.073537]  [sq d1 d2: 0.000209]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 460/676] [D loss: -0.001436] [G loss: -0.050221] [d1 loss: 0.059743] [d2 loss: 0.068635]  [sq d1 d2: 0.000079]  [num0: 19.000000] [num1 45.000000]
[Epoch 99/500] [Batch 480/676] [D loss: -0.008409] [G loss: -0.045315] [d1 loss: 0.138093] [d2 loss: 0.138057]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 500/676] [D loss: -0.031490] [G loss: -0.030110] [d1 loss: 0.057287] [d2 loss: 0.068034]  [sq d1 d2: 0.000115]  [num0: 12.000000] [num1 52.000000]
[Epoch 99/500] [Batch 520/676] [D loss: -0.039690] [G loss: -0.026701] [d1 loss: 0.063925] [d2 loss: 0.075216]  [sq d1 d2: 0.000128]  [num0: 12.000000] [num1 52.000000]
[Epoch 99/500] [Batch 540/676] [D loss: -0.052710] [G loss: -0.022838] [d1 loss: 0.062304] [d2 loss: 0.065859]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 99/500] [Batch 560/676] [D loss: -0.032123] [G loss: -0.021632] [d1 loss: 0.036474] [d2 loss: 0.034351]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 99/500] [Batch 580/676] [D loss: -0.064370] [G loss: -0.016026] [d1 loss: 0.123176] [d2 loss: 0.129203]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 600/676] [D loss: 0.007492] [G loss: -0.085345] [d1 loss: 0.111891] [d2 loss: 0.100875]  [sq d1 d2: 0.000121]  [num0: 17.000000] [num1 47.000000]
[Epoch 99/500] [Batch 620/676] [D loss: -0.013052] [G loss: -0.109807] [d1 loss: 0.128932] [d2 loss: 0.118289]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 99/500] [Batch 640/676] [D loss: 0.042850] [G loss: -0.100455] [d1 loss: 0.116848] [d2 loss: 0.114442]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 99/500] [Batch 660/676] [D loss: 0.017984] [G loss: -0.068434] [d1 loss: 0.091634] [d2 loss: 0.083293]  [sq d1 d2: 0.000070]  [num0: 13.000000] [num1 51.000000]
[Epoch 100/500] [Batch 0/676] [D loss: 0.016004] [G loss: -0.056631] [d1 loss: 0.104392] [d2 loss: 0.099031]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 100/500] [Batch 20/676] [D loss: 0.004683] [G loss: -0.057909] [d1 loss: 0.069101] [d2 loss: 0.061535]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 40/676] [D loss: -0.000891] [G loss: -0.057032] [d1 loss: 0.070499] [d2 loss: 0.071698]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 100/500] [Batch 60/676] [D loss: -0.014867] [G loss: -0.059930] [d1 loss: 0.144387] [d2 loss: 0.110694]  [sq d1 d2: 0.001135]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 80/676] [D loss: -0.025566] [G loss: -0.059384] [d1 loss: 0.125771] [d2 loss: 0.133470]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 100/676] [D loss: -0.052359] [G loss: -0.056622] [d1 loss: 0.068581] [d2 loss: 0.070666]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 120/676] [D loss: -0.051858] [G loss: -0.044413] [d1 loss: 0.062197] [d2 loss: 0.063397]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 140/676] [D loss: -0.029792] [G loss: -0.055661] [d1 loss: 0.065559] [d2 loss: 0.080741]  [sq d1 d2: 0.000230]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 160/676] [D loss: -0.061302] [G loss: -0.078707] [d1 loss: 0.239732] [d2 loss: 0.247380]  [sq d1 d2: 0.000058]  [num0: 11.000000] [num1 53.000000]
[Epoch 100/500] [Batch 180/676] [D loss: -0.029703] [G loss: -0.079573] [d1 loss: 0.114246] [d2 loss: 0.137375]  [sq d1 d2: 0.000535]  [num0: 18.000000] [num1 46.000000]
[Epoch 100/500] [Batch 200/676] [D loss: -0.004250] [G loss: -0.083911] [d1 loss: 0.137479] [d2 loss: 0.158612]  [sq d1 d2: 0.000447]  [num0: 13.000000] [num1 51.000000]
[Epoch 100/500] [Batch 220/676] [D loss: 0.021028] [G loss: -0.034900] [d1 loss: 0.036376] [d2 loss: 0.034030]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]

[Epoch 100/500] [Batch 240/676] [D loss: 0.015878] [G loss: -0.032113] [d1 loss: 0.190783] [d2 loss: 0.173750]  [sq d1 d2: 0.000290]  [num0: 18.000000] [num1 46.000000]
[Epoch 100/500] [Batch 260/676] [D loss: -0.002873] [G loss: -0.009587] [d1 loss: 0.056204] [d2 loss: 0.073414]  [sq d1 d2: 0.000296]  [num0: 13.000000] [num1 51.000000]
[Epoch 100/500] [Batch 280/676] [D loss: 0.009706] [G loss: 0.001925] [d1 loss: 0.146360] [d2 loss: 0.130345]  [sq d1 d2: 0.000256]  [num0: 17.000000] [num1 47.000000]
[Epoch 100/500] [Batch 300/676] [D loss: -0.005092] [G loss: -0.005978] [d1 loss: 0.099410] [d2 loss: 0.116246]  [sq d1 d2: 0.000283]  [num0: 13.000000] [num1 51.000000]
[Epoch 100/500] [Batch 320/676] [D loss: -0.023527] [G loss: -0.002433] [d1 loss: 0.128605] [d2 loss: 0.152018]  [sq d1 d2: 0.000548]  [num0: 17.000000] [num1 47.000000]
[Epoch 100/500] [Batch 340/676] [D loss: -0.021301] [G loss: -0.011716] [d1 loss: 0.076819] [d2 loss: 0.098154]  [sq d1 d2: 0.000455]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 360/676] [D loss: -0.063950] [G loss: -0.031662] [d1 loss: 0.111946] [d2 loss: 0.084699]  [sq d1 d2: 0.000742]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 380/676] [D loss: -0.051141] [G loss: -0.020716] [d1 loss: 0.118575] [d2 loss: 0.110179]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 400/676] [D loss: -0.007050] [G loss: -0.043611] [d1 loss: 0.154920] [d2 loss: 0.190262]  [sq d1 d2: 0.001249]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 420/676] [D loss: -0.039374] [G loss: -0.068116] [d1 loss: 0.096673] [d2 loss: 0.122850]  [sq d1 d2: 0.000685]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 440/676] [D loss: -0.036124] [G loss: -0.083629] [d1 loss: 0.076748] [d2 loss: 0.087692]  [sq d1 d2: 0.000120]  [num0: 12.000000] [num1 52.000000]
[Epoch 100/500] [Batch 460/676] [D loss: 0.023486] [G loss: -0.089157] [d1 loss: 0.100832] [d2 loss: 0.095557]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 100/500] [Batch 480/676] [D loss: 0.041183] [G loss: -0.074340] [d1 loss: 0.055523] [d2 loss: 0.064367]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 100/500] [Batch 500/676] [D loss: 0.017266] [G loss: -0.049498] [d1 loss: 0.123812] [d2 loss: 0.128750]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 100/500] [Batch 520/676] [D loss: 0.024630] [G loss: -0.025711] [d1 loss: 0.063255] [d2 loss: 0.064582]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 100/500] [Batch 540/676] [D loss: 0.009360] [G loss: -0.010041] [d1 loss: 0.163597] [d2 loss: 0.141418]  [sq d1 d2: 0.000492]  [num0: 16.000000] [num1 48.000000]
[Epoch 100/500] [Batch 560/676] [D loss: -0.001661] [G loss: 0.002602] [d1 loss: 0.102715] [d2 loss: 0.083164]  [sq d1 d2: 0.000382]  [num0: 18.000000] [num1 46.000000]
[Epoch 100/500] [Batch 580/676] [D loss: -0.014834] [G loss: 0.008849] [d1 loss: 0.088651] [d2 loss: 0.113238]  [sq d1 d2: 0.000605]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 600/676] [D loss: -0.032361] [G loss: 0.023178] [d1 loss: 0.124107] [d2 loss: 0.099165]  [sq d1 d2: 0.000622]  [num0: 13.000000] [num1 51.000000]
[Epoch 100/500] [Batch 620/676] [D loss: -0.033938] [G loss: 0.022325] [d1 loss: 0.121539] [d2 loss: 0.125015]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 100/500] [Batch 640/676] [D loss: -0.031445] [G loss: -0.003414] [d1 loss: 0.059529] [d2 loss: 0.056005]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 100/500] [Batch 660/676] [D loss: -0.083148] [G loss: -0.001522] [d1 loss: 0.088708] [d2 loss: 0.093137]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 101/500] [Batch 0/676] [D loss: -0.031661] [G loss: -0.030193] [d1 loss: 0.108148] [d2 loss: 0.097290]  [sq d1 d2: 0.000118]  [num0: 19.000000] [num1 45.000000]
[Epoch 101/500] [Batch 20/676] [D loss: -0.011464] [G loss: -0.071135] [d1 loss: 0.102781] [d2 loss: 0.103539]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 40/676] [D loss: -0.010060] [G loss: -0.028731] [d1 loss: 0.143214] [d2 loss: 0.121235]  [sq d1 d2: 0.000483]  [num0: 20.000000] [num1 44.000000]
[Epoch 101/500] [Batch 60/676] [D loss: 0.028059] [G loss: -0.067632] [d1 loss: 0.217092] [d2 loss: 0.216118]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 80/676] [D loss: 0.016904] [G loss: -0.042660] [d1 loss: 0.115633] [d2 loss: 0.089489]  [sq d1 d2: 0.000683]  [num0: 11.000000] [num1 53.000000]
[Epoch 101/500] [Batch 100/676] [D loss: 0.015495] [G loss: -0.045952] [d1 loss: 0.089792] [d2 loss: 0.086107]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 101/500] [Batch 120/676] [D loss: 0.004425] [G loss: 0.007267] [d1 loss: 0.156904] [d2 loss: 0.117367]  [sq d1 d2: 0.001563]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 140/676] [D loss: -0.003781] [G loss: 0.045816] [d1 loss: 0.104101] [d2 loss: 0.078800]  [sq d1 d2: 0.000640]  [num0: 13.000000] [num1 51.000000]
[Epoch 101/500] [Batch 160/676] [D loss: -0.014238] [G loss: 0.069956] [d1 loss: 0.047834] [d2 loss: 0.074096]  [sq d1 d2: 0.000690]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 180/676] [D loss: -0.029486] [G loss: 0.098360] [d1 loss: 0.118093] [d2 loss: 0.120664]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 200/676] [D loss: -0.052219] [G loss: 0.113468] [d1 loss: 0.064255] [d2 loss: 0.061168]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 101/500] [Batch 220/676] [D loss: 0.008216] [G loss: 0.147512] [d1 loss: 0.069296] [d2 loss: 0.066175]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 101/500] [Batch 240/676] [D loss: -0.051575] [G loss: 0.150763] [d1 loss: 0.245537] [d2 loss: 0.201831]  [sq d1 d2: 0.001910]  [num0: 18.000000] [num1 46.000000]
[Epoch 101/500] [Batch 260/676] [D loss: -0.002972] [G loss: 0.139449] [d1 loss: 0.140934] [d2 loss: 0.117843]  [sq d1 d2: 0.000533]  [num0: 12.000000] [num1 52.000000]
[Epoch 101/500] [Batch 280/676] [D loss: 0.009730] [G loss: 0.122052] [d1 loss: 0.154034] [d2 loss: 0.167138]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 101/500] [Batch 300/676] [D loss: 0.009596] [G loss: 0.103267] [d1 loss: 0.066812] [d2 loss: 0.068287]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 320/676] [D loss: 0.007448] [G loss: 0.067975] [d1 loss: 0.173223] [d2 loss: 0.165267]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 340/676] [D loss: 0.008230] [G loss: 0.034460] [d1 loss: 0.077089] [d2 loss: 0.090308]  [sq d1 d2: 0.000175]  [num0: 16.000000] [num1 48.000000]
[Epoch 101/500] [Batch 360/676] [D loss: 0.007970] [G loss: 0.022407] [d1 loss: 0.085507] [d2 loss: 0.117568]  [sq d1 d2: 0.001028]  [num0: 20.000000] [num1 44.000000]
[Epoch 101/500] [Batch 380/676] [D loss: 0.000081] [G loss: 0.021959] [d1 loss: 0.088308] [d2 loss: 0.093006]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 400/676] [D loss: -0.005554] [G loss: 0.016562] [d1 loss: 0.072815] [d2 loss: 0.075365]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 101/500] [Batch 420/676] [D loss: -0.012123] [G loss: 0.001062] [d1 loss: 0.117229] [d2 loss: 0.107469]  [sq d1 d2: 0.000095]  [num0: 10.000000] [num1 54.000000]
[Epoch 101/500] [Batch 440/676] [D loss: 0.000693] [G loss: 0.014211] [d1 loss: 0.050577] [d2 loss: 0.049282]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 460/676] [D loss: -0.031730] [G loss: 0.037324] [d1 loss: 0.067436] [d2 loss: 0.068127]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 480/676] [D loss: -0.030709] [G loss: 0.023125] [d1 loss: 0.126844] [d2 loss: 0.131646]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 101/500] [Batch 500/676] [D loss: -0.038562] [G loss: 0.020219] [d1 loss: 0.158561] [d2 loss: 0.150236]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 101/500] [Batch 520/676] [D loss: -0.037962] [G loss: -0.000265] [d1 loss: 0.146834] [d2 loss: 0.164771]  [sq d1 d2: 0.000322]  [num0: 16.000000] [num1 48.000000]
[Epoch 101/500] [Batch 540/676] [D loss: 0.032444] [G loss: -0.052065] [d1 loss: 0.089738] [d2 loss: 0.102236]  [sq d1 d2: 0.000156]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 560/676] [D loss: 0.033021] [G loss: -0.044420] [d1 loss: 0.100713] [d2 loss: 0.088045]  [sq d1 d2: 0.000160]  [num0: 14.000000] [num1 50.000000]
[Epoch 101/500] [Batch 580/676] [D loss: 0.010054] [G loss: -0.063474] [d1 loss: 0.083528] [d2 loss: 0.077610]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]

[Epoch 101/500] [Batch 600/676] [D loss: 0.010845] [G loss: -0.031901] [d1 loss: 0.089551] [d2 loss: 0.075053]  [sq d1 d2: 0.000210]  [num0: 17.000000] [num1 47.000000]
[Epoch 101/500] [Batch 620/676] [D loss: -0.000193] [G loss: -0.039743] [d1 loss: 0.093593] [d2 loss: 0.082283]  [sq d1 d2: 0.000128]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 640/676] [D loss: -0.004085] [G loss: -0.049182] [d1 loss: 0.085564] [d2 loss: 0.082304]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 101/500] [Batch 660/676] [D loss: -0.020013] [G loss: -0.045254] [d1 loss: 0.122925] [d2 loss: 0.104189]  [sq d1 d2: 0.000351]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 0/676] [D loss: -0.023216] [G loss: -0.028862] [d1 loss: 0.109432] [d2 loss: 0.092461]  [sq d1 d2: 0.000288]  [num0: 17.000000] [num1 47.000000]
[Epoch 102/500] [Batch 20/676] [D loss: -0.027825] [G loss: -0.007366] [d1 loss: 0.062596] [d2 loss: 0.062818]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 40/676] [D loss: -0.018117] [G loss: 0.002701] [d1 loss: 0.107442] [d2 loss: 0.114033]  [sq d1 d2: 0.000043]  [num0: 11.000000] [num1 53.000000]
[Epoch 102/500] [Batch 60/676] [D loss: -0.042234] [G loss: 0.004472] [d1 loss: 0.168251] [d2 loss: 0.155557]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 102/500] [Batch 80/676] [D loss: -0.060468] [G loss: -0.023233] [d1 loss: 0.086083] [d2 loss: 0.084812]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 102/500] [Batch 100/676] [D loss: -0.040734] [G loss: -0.046288] [d1 loss: 0.214104] [d2 loss: 0.150577]  [sq d1 d2: 0.004036]  [num0: 17.000000] [num1 47.000000]
[Epoch 102/500] [Batch 120/676] [D loss: 0.035329] [G loss: -0.038631] [d1 loss: 0.124577] [d2 loss: 0.096114]  [sq d1 d2: 0.000810]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 140/676] [D loss: 0.028746] [G loss: -0.081909] [d1 loss: 0.057308] [d2 loss: 0.049171]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 160/676] [D loss: 0.007934] [G loss: -0.087039] [d1 loss: 0.061687] [d2 loss: 0.048213]  [sq d1 d2: 0.000182]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 180/676] [D loss: 0.013613] [G loss: -0.065495] [d1 loss: 0.182129] [d2 loss: 0.169733]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 200/676] [D loss: 0.005557] [G loss: -0.049702] [d1 loss: 0.149059] [d2 loss: 0.141698]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 102/500] [Batch 220/676] [D loss: -0.001747] [G loss: -0.047068] [d1 loss: 0.061081] [d2 loss: 0.057572]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 240/676] [D loss: -0.020113] [G loss: -0.042603] [d1 loss: 0.148892] [d2 loss: 0.141380]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 260/676] [D loss: -0.025519] [G loss: -0.030868] [d1 loss: 0.086632] [d2 loss: 0.097029]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 280/676] [D loss: -0.043870] [G loss: -0.009207] [d1 loss: 0.104140] [d2 loss: 0.092966]  [sq d1 d2: 0.000125]  [num0: 20.000000] [num1 44.000000]
[Epoch 102/500] [Batch 300/676] [D loss: -0.016526] [G loss: 0.017519] [d1 loss: 0.141142] [d2 loss: 0.123704]  [sq d1 d2: 0.000304]  [num0: 17.000000] [num1 47.000000]
[Epoch 102/500] [Batch 320/676] [D loss: -0.059340] [G loss: 0.016893] [d1 loss: 0.071868] [d2 loss: 0.081162]  [sq d1 d2: 0.000086]  [num0: 13.000000] [num1 51.000000]
[Epoch 102/500] [Batch 340/676] [D loss: -0.034606] [G loss: 0.037112] [d1 loss: 0.154139] [d2 loss: 0.148830]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 102/500] [Batch 360/676] [D loss: -0.000014] [G loss: 0.009899] [d1 loss: 0.143575] [d2 loss: 0.145534]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 102/500] [Batch 380/676] [D loss: -0.005120] [G loss: 0.015400] [d1 loss: 0.137538] [d2 loss: 0.153327]  [sq d1 d2: 0.000249]  [num0: 18.000000] [num1 46.000000]
[Epoch 102/500] [Batch 400/676] [D loss: 0.007873] [G loss: -0.027115] [d1 loss: 0.088580] [d2 loss: 0.093019]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 102/500] [Batch 420/676] [D loss: 0.014414] [G loss: -0.036987] [d1 loss: 0.126668] [d2 loss: 0.103296]  [sq d1 d2: 0.000546]  [num0: 12.000000] [num1 52.000000]
[Epoch 102/500] [Batch 440/676] [D loss: 0.013820] [G loss: -0.058657] [d1 loss: 0.117363] [d2 loss: 0.150868]  [sq d1 d2: 0.001123]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 460/676] [D loss: 0.005389] [G loss: -0.042780] [d1 loss: 0.174365] [d2 loss: 0.171424]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 480/676] [D loss: -0.011123] [G loss: -0.055031] [d1 loss: 0.157182] [d2 loss: 0.176554]  [sq d1 d2: 0.000375]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 500/676] [D loss: -0.016921] [G loss: -0.057773] [d1 loss: 0.076883] [d2 loss: 0.084939]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 102/500] [Batch 520/676] [D loss: -0.043966] [G loss: -0.041448] [d1 loss: 0.093485] [d2 loss: 0.063653]  [sq d1 d2: 0.000890]  [num0: 14.000000] [num1 50.000000]
[Epoch 102/500] [Batch 540/676] [D loss: -0.039982] [G loss: -0.053714] [d1 loss: 0.117752] [d2 loss: 0.121955]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 102/500] [Batch 560/676] [D loss: -0.049936] [G loss: -0.005695] [d1 loss: 0.110056] [d2 loss: 0.107685]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 102/500] [Batch 580/676] [D loss: -0.052931] [G loss: -0.020620] [d1 loss: 0.129725] [d2 loss: 0.128936]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 600/676] [D loss: -0.037084] [G loss: -0.021093] [d1 loss: 0.139310] [d2 loss: 0.156487]  [sq d1 d2: 0.000295]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 620/676] [D loss: -0.002933] [G loss: -0.022032] [d1 loss: 0.120788] [d2 loss: 0.136401]  [sq d1 d2: 0.000244]  [num0: 16.000000] [num1 48.000000]
[Epoch 102/500] [Batch 640/676] [D loss: 0.006446] [G loss: -0.049507] [d1 loss: 0.132548] [d2 loss: 0.099755]  [sq d1 d2: 0.001075]  [num0: 17.000000] [num1 47.000000]
[Epoch 102/500] [Batch 660/676] [D loss: 0.020077] [G loss: -0.040929] [d1 loss: 0.063385] [d2 loss: 0.073085]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 0/676] [D loss: 0.001186] [G loss: -0.040863] [d1 loss: 0.046701] [d2 loss: 0.041169]  [sq d1 d2: 0.000031]  [num0: 20.000000] [num1 44.000000]
[Epoch 103/500] [Batch 20/676] [D loss: 0.006872] [G loss: -0.042816] [d1 loss: 0.129043] [d2 loss: 0.142688]  [sq d1 d2: 0.000186]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 40/676] [D loss: -0.003861] [G loss: -0.048485] [d1 loss: 0.151988] [d2 loss: 0.159560]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 103/500] [Batch 60/676] [D loss: -0.016686] [G loss: -0.052091] [d1 loss: 0.081443] [d2 loss: 0.087988]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 80/676] [D loss: -0.027508] [G loss: -0.060364] [d1 loss: 0.138711] [d2 loss: 0.131891]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 100/676] [D loss: -0.034028] [G loss: -0.016741] [d1 loss: 0.128093] [d2 loss: 0.151869]  [sq d1 d2: 0.000565]  [num0: 14.000000] [num1 50.000000]
[Epoch 103/500] [Batch 120/676] [D loss: -0.057064] [G loss: 0.039035] [d1 loss: 0.080879] [d2 loss: 0.079670]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 140/676] [D loss: -0.059422] [G loss: -0.021379] [d1 loss: 0.066029] [d2 loss: 0.065542]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 160/676] [D loss: -0.042036] [G loss: -0.055939] [d1 loss: 0.069647] [d2 loss: 0.068394]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 180/676] [D loss: -0.034129] [G loss: -0.074438] [d1 loss: 0.081792] [d2 loss: 0.093483]  [sq d1 d2: 0.000137]  [num0: 14.000000] [num1 50.000000]
[Epoch 103/500] [Batch 200/676] [D loss: 0.034214] [G loss: -0.065372] [d1 loss: 0.066344] [d2 loss: 0.055321]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 220/676] [D loss: 0.032020] [G loss: -0.078721] [d1 loss: 0.197417] [d2 loss: 0.191040]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 240/676] [D loss: 0.026657] [G loss: -0.029645] [d1 loss: 0.108584] [d2 loss: 0.096636]  [sq d1 d2: 0.000143]  [num0: 20.000000] [num1 44.000000]
[Epoch 103/500] [Batch 260/676] [D loss: 0.002413] [G loss: 0.018001] [d1 loss: 0.067412] [d2 loss: 0.060905]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]

[Epoch 103/500] [Batch 280/676] [D loss: -0.018061] [G loss: 0.078912] [d1 loss: 0.055985] [d2 loss: 0.059754]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 300/676] [D loss: -0.019730] [G loss: 0.123422] [d1 loss: 0.090117] [d2 loss: 0.098105]  [sq d1 d2: 0.000064]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 320/676] [D loss: -0.035876] [G loss: 0.155706] [d1 loss: 0.151384] [d2 loss: 0.172128]  [sq d1 d2: 0.000430]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 340/676] [D loss: -0.078622] [G loss: 0.180849] [d1 loss: 0.127478] [d2 loss: 0.110724]  [sq d1 d2: 0.000281]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 360/676] [D loss: -0.020967] [G loss: 0.192315] [d1 loss: 0.066413] [d2 loss: 0.061133]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 103/500] [Batch 380/676] [D loss: -0.004434] [G loss: 0.169924] [d1 loss: 0.080083] [d2 loss: 0.086584]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 400/676] [D loss: -0.035150] [G loss: 0.087175] [d1 loss: 0.068803] [d2 loss: 0.065943]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 103/500] [Batch 420/676] [D loss: -0.009969] [G loss: 0.098036] [d1 loss: 0.089698] [d2 loss: 0.100904]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 440/676] [D loss: 0.025939] [G loss: 0.067562] [d1 loss: 0.143068] [d2 loss: 0.120642]  [sq d1 d2: 0.000503]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 460/676] [D loss: 0.022630] [G loss: 0.059053] [d1 loss: 0.084658] [d2 loss: 0.085665]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 480/676] [D loss: 0.015188] [G loss: 0.081648] [d1 loss: 0.124672] [d2 loss: 0.110967]  [sq d1 d2: 0.000188]  [num0: 19.000000] [num1 45.000000]
[Epoch 103/500] [Batch 500/676] [D loss: 0.004718] [G loss: 0.078405] [d1 loss: 0.142927] [d2 loss: 0.178830]  [sq d1 d2: 0.001289]  [num0: 13.000000] [num1 51.000000]
[Epoch 103/500] [Batch 520/676] [D loss: -0.015494] [G loss: 0.090309] [d1 loss: 0.037218] [d2 loss: 0.033403]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 103/500] [Batch 540/676] [D loss: -0.027153] [G loss: 0.145471] [d1 loss: 0.089763] [d2 loss: 0.088123]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 103/500] [Batch 560/676] [D loss: -0.051484] [G loss: 0.166914] [d1 loss: 0.102101] [d2 loss: 0.109696]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 103/500] [Batch 580/676] [D loss: -0.042135] [G loss: 0.126937] [d1 loss: 0.185045] [d2 loss: 0.161484]  [sq d1 d2: 0.000555]  [num0: 18.000000] [num1 46.000000]
[Epoch 103/500] [Batch 600/676] [D loss: -0.104633] [G loss: 0.088562] [d1 loss: 0.051568] [d2 loss: 0.053735]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 103/500] [Batch 620/676] [D loss: -0.033245] [G loss: 0.001752] [d1 loss: 0.070332] [d2 loss: 0.065724]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 103/500] [Batch 640/676] [D loss: -0.037312] [G loss: -0.065304] [d1 loss: 0.107192] [d2 loss: 0.109111]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 103/500] [Batch 660/676] [D loss: 0.036816] [G loss: -0.170377] [d1 loss: 0.135704] [d2 loss: 0.168537]  [sq d1 d2: 0.001078]  [num0: 12.000000] [num1 52.000000]
[Epoch 104/500] [Batch 0/676] [D loss: 0.035237] [G loss: -0.245600] [d1 loss: 0.130050] [d2 loss: 0.134113]  [sq d1 d2: 0.000017]  [num0: 20.000000] [num1 44.000000]
[Epoch 104/500] [Batch 20/676] [D loss: 0.005832] [G loss: -0.210741] [d1 loss: 0.175014] [d2 loss: 0.172440]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 40/676] [D loss: 0.011008] [G loss: -0.134513] [d1 loss: 0.142913] [d2 loss: 0.143828]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 60/676] [D loss: -0.007025] [G loss: -0.046864] [d1 loss: 0.219292] [d2 loss: 0.185836]  [sq d1 d2: 0.001119]  [num0: 19.000000] [num1 45.000000]
[Epoch 104/500] [Batch 80/676] [D loss: -0.013189] [G loss: 0.004479] [d1 loss: 0.089240] [d2 loss: 0.077126]  [sq d1 d2: 0.000147]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 100/676] [D loss: -0.019903] [G loss: 0.031690] [d1 loss: 0.189510] [d2 loss: 0.188154]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 120/676] [D loss: -0.037608] [G loss: 0.053265] [d1 loss: 0.098408] [d2 loss: 0.096787]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 104/500] [Batch 140/676] [D loss: -0.042101] [G loss: 0.081560] [d1 loss: 0.185965] [d2 loss: 0.189673]  [sq d1 d2: 0.000014]  [num0: 22.000000] [num1 42.000000]
[Epoch 104/500] [Batch 160/676] [D loss: -0.052758] [G loss: 0.090702] [d1 loss: 0.226020] [d2 loss: 0.227875]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 180/676] [D loss: -0.001096] [G loss: 0.089412] [d1 loss: 0.157646] [d2 loss: 0.120515]  [sq d1 d2: 0.001379]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 200/676] [D loss: -0.029451] [G loss: 0.066694] [d1 loss: 0.092655] [d2 loss: 0.106638]  [sq d1 d2: 0.000196]  [num0: 17.000000] [num1 47.000000]
[Epoch 104/500] [Batch 220/676] [D loss: -0.045175] [G loss: 0.069758] [d1 loss: 0.129929] [d2 loss: 0.145253]  [sq d1 d2: 0.000235]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 240/676] [D loss: -0.032422] [G loss: 0.013929] [d1 loss: 0.159166] [d2 loss: 0.165461]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 104/500] [Batch 260/676] [D loss: 0.001902] [G loss: -0.017277] [d1 loss: 0.147911] [d2 loss: 0.155577]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 104/500] [Batch 280/676] [D loss: 0.010318] [G loss: -0.034336] [d1 loss: 0.117729] [d2 loss: 0.120142]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 104/500] [Batch 300/676] [D loss: 0.028189] [G loss: -0.057521] [d1 loss: 0.111638] [d2 loss: 0.123373]  [sq d1 d2: 0.000138]  [num0: 17.000000] [num1 47.000000]
[Epoch 104/500] [Batch 320/676] [D loss: 0.002908] [G loss: -0.076951] [d1 loss: 0.127048] [d2 loss: 0.122003]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 340/676] [D loss: 0.000624] [G loss: -0.095113] [d1 loss: 0.125852] [d2 loss: 0.109143]  [sq d1 d2: 0.000279]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 360/676] [D loss: -0.003472] [G loss: -0.130452] [d1 loss: 0.093199] [d2 loss: 0.095553]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 380/676] [D loss: -0.024694] [G loss: -0.151300] [d1 loss: 0.121694] [d2 loss: 0.126754]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 400/676] [D loss: -0.027180] [G loss: -0.216372] [d1 loss: 0.259941] [d2 loss: 0.263420]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 104/500] [Batch 420/676] [D loss: -0.062689] [G loss: -0.218103] [d1 loss: 0.129671] [d2 loss: 0.133957]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 104/500] [Batch 440/676] [D loss: -0.061033] [G loss: -0.213255] [d1 loss: 0.077565] [d2 loss: 0.075573]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 460/676] [D loss: -0.051933] [G loss: -0.253891] [d1 loss: 0.127091] [d2 loss: 0.126248]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 480/676] [D loss: -0.044712] [G loss: -0.255778] [d1 loss: 0.095518] [d2 loss: 0.091694]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 500/676] [D loss: -0.026367] [G loss: -0.233938] [d1 loss: 0.088966] [d2 loss: 0.093381]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 520/676] [D loss: 0.015464] [G loss: -0.214748] [d1 loss: 0.087743] [d2 loss: 0.087736]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 104/500] [Batch 540/676] [D loss: 0.006018] [G loss: -0.161169] [d1 loss: 0.120165] [d2 loss: 0.125946]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 560/676] [D loss: 0.025337] [G loss: -0.121068] [d1 loss: 0.098031] [d2 loss: 0.065025]  [sq d1 d2: 0.001089]  [num0: 12.000000] [num1 52.000000]
[Epoch 104/500] [Batch 580/676] [D loss: 0.000397] [G loss: -0.088852] [d1 loss: 0.331697] [d2 loss: 0.347347]  [sq d1 d2: 0.000245]  [num0: 18.000000] [num1 46.000000]
[Epoch 104/500] [Batch 600/676] [D loss: -0.002408] [G loss: -0.099043] [d1 loss: 0.060464] [d2 loss: 0.078247]  [sq d1 d2: 0.000316]  [num0: 15.000000] [num1 49.000000]
[Epoch 104/500] [Batch 620/676] [D loss: -0.014983] [G loss: -0.110812] [d1 loss: 0.113167] [d2 loss: 0.111709]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]

[Epoch 104/500] [Batch 640/676] [D loss: -0.026512] [G loss: -0.094766] [d1 loss: 0.120352] [d2 loss: 0.118631]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 104/500] [Batch 660/676] [D loss: -0.045783] [G loss: -0.085864] [d1 loss: 0.084340] [d2 loss: 0.096188]  [sq d1 d2: 0.000140]  [num0: 14.000000] [num1 50.000000]
[Epoch 105/500] [Batch 0/676] [D loss: -0.028119] [G loss: -0.077805] [d1 loss: 0.060803] [d2 loss: 0.059254]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 20/676] [D loss: -0.029761] [G loss: -0.059476] [d1 loss: 0.146187] [d2 loss: 0.148067]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 40/676] [D loss: -0.028815] [G loss: -0.036176] [d1 loss: 0.056298] [d2 loss: 0.043026]  [sq d1 d2: 0.000176]  [num0: 14.000000] [num1 50.000000]
[Epoch 105/500] [Batch 60/676] [D loss: -0.061089] [G loss: -0.028608] [d1 loss: 0.096440] [d2 loss: 0.090404]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 80/676] [D loss: 0.012411] [G loss: 0.011809] [d1 loss: 0.197019] [d2 loss: 0.235776]  [sq d1 d2: 0.001502]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 100/676] [D loss: 0.026964] [G loss: -0.000733] [d1 loss: 0.168390] [d2 loss: 0.200452]  [sq d1 d2: 0.001028]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 120/676] [D loss: 0.013016] [G loss: 0.022243] [d1 loss: 0.118842] [d2 loss: 0.116804]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 140/676] [D loss: 0.008951] [G loss: 0.037763] [d1 loss: 0.120697] [d2 loss: 0.090494]  [sq d1 d2: 0.000912]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 160/676] [D loss: 0.010703] [G loss: 0.056471] [d1 loss: 0.130859] [d2 loss: 0.125236]  [sq d1 d2: 0.000032]  [num0: 18.000000] [num1 46.000000]
[Epoch 105/500] [Batch 180/676] [D loss: 0.000939] [G loss: 0.050994] [d1 loss: 0.096900] [d2 loss: 0.096129]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 105/500] [Batch 200/676] [D loss: -0.000699] [G loss: 0.053556] [d1 loss: 0.130159] [d2 loss: 0.137384]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 220/676] [D loss: -0.013783] [G loss: 0.091862] [d1 loss: 0.092763] [d2 loss: 0.085876]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 105/500] [Batch 240/676] [D loss: -0.022902] [G loss: 0.166886] [d1 loss: 0.114538] [d2 loss: 0.119954]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 105/500] [Batch 260/676] [D loss: -0.033925] [G loss: 0.236620] [d1 loss: 0.139532] [d2 loss: 0.122119]  [sq d1 d2: 0.000303]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 280/676] [D loss: -0.033309] [G loss: 0.253485] [d1 loss: 0.112107] [d2 loss: 0.098525]  [sq d1 d2: 0.000184]  [num0: 18.000000] [num1 46.000000]
[Epoch 105/500] [Batch 300/676] [D loss: -0.017925] [G loss: 0.229097] [d1 loss: 0.090395] [d2 loss: 0.087722]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 105/500] [Batch 320/676] [D loss: -0.016534] [G loss: 0.212173] [d1 loss: 0.098047] [d2 loss: 0.101437]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 105/500] [Batch 340/676] [D loss: 0.007566] [G loss: 0.186059] [d1 loss: 0.063594] [d2 loss: 0.064931]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 105/500] [Batch 360/676] [D loss: -0.016043] [G loss: 0.097522] [d1 loss: 0.130283] [d2 loss: 0.090246]  [sq d1 d2: 0.001603]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 380/676] [D loss: 0.007651] [G loss: 0.079275] [d1 loss: 0.086791] [d2 loss: 0.107861]  [sq d1 d2: 0.000444]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 400/676] [D loss: 0.003751] [G loss: -0.000956] [d1 loss: 0.114857] [d2 loss: 0.116325]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 105/500] [Batch 420/676] [D loss: 0.005235] [G loss: -0.038397] [d1 loss: 0.079753] [d2 loss: 0.074102]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 440/676] [D loss: -0.009682] [G loss: -0.093598] [d1 loss: 0.094820] [d2 loss: 0.081279]  [sq d1 d2: 0.000183]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 460/676] [D loss: -0.023117] [G loss: -0.139632] [d1 loss: 0.063631] [d2 loss: 0.065692]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 480/676] [D loss: -0.033764] [G loss: -0.188773] [d1 loss: 0.110992] [d2 loss: 0.112455]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 105/500] [Batch 500/676] [D loss: -0.031341] [G loss: -0.215069] [d1 loss: 0.129238] [d2 loss: 0.145547]  [sq d1 d2: 0.000266]  [num0: 18.000000] [num1 46.000000]
[Epoch 105/500] [Batch 520/676] [D loss: -0.034041] [G loss: -0.234545] [d1 loss: 0.218660] [d2 loss: 0.169016]  [sq d1 d2: 0.002465]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 540/676] [D loss: -0.028311] [G loss: -0.220107] [d1 loss: 0.083020] [d2 loss: 0.073098]  [sq d1 d2: 0.000098]  [num0: 12.000000] [num1 52.000000]
[Epoch 105/500] [Batch 560/676] [D loss: 0.011250] [G loss: -0.187589] [d1 loss: 0.131851] [d2 loss: 0.142368]  [sq d1 d2: 0.000111]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 580/676] [D loss: -0.002274] [G loss: -0.194250] [d1 loss: 0.054269] [d2 loss: 0.063307]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 105/500] [Batch 600/676] [D loss: 0.042549] [G loss: -0.199331] [d1 loss: 0.099482] [d2 loss: 0.115412]  [sq d1 d2: 0.000254]  [num0: 19.000000] [num1 45.000000]
[Epoch 105/500] [Batch 620/676] [D loss: -0.002574] [G loss: -0.159224] [d1 loss: 0.076617] [d2 loss: 0.067151]  [sq d1 d2: 0.000090]  [num0: 13.000000] [num1 51.000000]
[Epoch 105/500] [Batch 640/676] [D loss: -0.003783] [G loss: -0.106424] [d1 loss: 0.150224] [d2 loss: 0.137159]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 105/500] [Batch 660/676] [D loss: 0.003030] [G loss: -0.045339] [d1 loss: 0.078664] [d2 loss: 0.080986]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 0/676] [D loss: -0.002756] [G loss: -0.020846] [d1 loss: 0.349423] [d2 loss: 0.326590]  [sq d1 d2: 0.000521]  [num0: 14.000000] [num1 50.000000]
[Epoch 106/500] [Batch 20/676] [D loss: 0.001316] [G loss: 0.011914] [d1 loss: 0.103415] [d2 loss: 0.111424]  [sq d1 d2: 0.000064]  [num0: 20.000000] [num1 44.000000]
[Epoch 106/500] [Batch 40/676] [D loss: -0.005327] [G loss: 0.047414] [d1 loss: 0.044248] [d2 loss: 0.057823]  [sq d1 d2: 0.000184]  [num0: 16.000000] [num1 48.000000]
[Epoch 106/500] [Batch 60/676] [D loss: -0.030512] [G loss: 0.116770] [d1 loss: 0.216191] [d2 loss: 0.179973]  [sq d1 d2: 0.001312]  [num0: 16.000000] [num1 48.000000]
[Epoch 106/500] [Batch 80/676] [D loss: -0.012302] [G loss: 0.166223] [d1 loss: 0.078154] [d2 loss: 0.081640]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 106/500] [Batch 100/676] [D loss: -0.021737] [G loss: 0.225746] [d1 loss: 0.139502] [d2 loss: 0.147253]  [sq d1 d2: 0.000060]  [num0: 13.000000] [num1 51.000000]
[Epoch 106/500] [Batch 120/676] [D loss: -0.045344] [G loss: 0.277530] [d1 loss: 0.146065] [d2 loss: 0.145671]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 106/500] [Batch 140/676] [D loss: -0.030856] [G loss: 0.280030] [d1 loss: 0.181356] [d2 loss: 0.161593]  [sq d1 d2: 0.000391]  [num0: 19.000000] [num1 45.000000]
[Epoch 106/500] [Batch 160/676] [D loss: 0.008056] [G loss: 0.235896] [d1 loss: 0.115992] [d2 loss: 0.097184]  [sq d1 d2: 0.000354]  [num0: 17.000000] [num1 47.000000]
[Epoch 106/500] [Batch 180/676] [D loss: 0.008348] [G loss: 0.192768] [d1 loss: 0.106499] [d2 loss: 0.094444]  [sq d1 d2: 0.000145]  [num0: 17.000000] [num1 47.000000]
[Epoch 106/500] [Batch 200/676] [D loss: -0.021756] [G loss: 0.124734] [d1 loss: 0.037774] [d2 loss: 0.042130]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 106/500] [Batch 220/676] [D loss: 0.020676] [G loss: 0.082053] [d1 loss: 0.091883] [d2 loss: 0.076009]  [sq d1 d2: 0.000252]  [num0: 12.000000] [num1 52.000000]
[Epoch 106/500] [Batch 240/676] [D loss: 0.013971] [G loss: 0.022975] [d1 loss: 0.117967] [d2 loss: 0.122908]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 106/500] [Batch 260/676] [D loss: -0.008943] [G loss: -0.055532] [d1 loss: 0.141078] [d2 loss: 0.104886]  [sq d1 d2: 0.001310]  [num0: 18.000000] [num1 46.000000]
[Epoch 106/500] [Batch 280/676] [D loss: -0.012274] [G loss: -0.095704] [d1 loss: 0.111034] [d2 loss: 0.126693]  [sq d1 d2: 0.000245]  [num0: 19.000000] [num1 45.000000]
[Epoch 106/500] [Batch 300/676] [D loss: -0.045205] [G loss: -0.149691] [d1 loss: 0.121371] [d2 loss: 0.127504]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]

[Epoch 106/500] [Batch 320/676] [D loss: -0.040511] [G loss: -0.245088] [d1 loss: 0.166919] [d2 loss: 0.155081]  [sq d1 d2: 0.000140]  [num0: 19.000000] [num1 45.000000]
[Epoch 106/500] [Batch 340/676] [D loss: -0.043014] [G loss: -0.288676] [d1 loss: 0.105365] [d2 loss: 0.105581]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 106/500] [Batch 360/676] [D loss: -0.032966] [G loss: -0.318083] [d1 loss: 0.146126] [d2 loss: 0.148385]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 106/500] [Batch 380/676] [D loss: 0.013930] [G loss: -0.351047] [d1 loss: 0.177863] [d2 loss: 0.162442]  [sq d1 d2: 0.000238]  [num0: 19.000000] [num1 45.000000]
[Epoch 106/500] [Batch 400/676] [D loss: -0.000915] [G loss: -0.339020] [d1 loss: 0.087219] [d2 loss: 0.088929]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 420/676] [D loss: 0.009307] [G loss: -0.314887] [d1 loss: 0.150016] [d2 loss: 0.151087]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 106/500] [Batch 440/676] [D loss: 0.011644] [G loss: -0.195079] [d1 loss: 0.056991] [d2 loss: 0.056010]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 106/500] [Batch 460/676] [D loss: -0.003505] [G loss: -0.153935] [d1 loss: 0.069583] [d2 loss: 0.071611]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 106/500] [Batch 480/676] [D loss: -0.002077] [G loss: -0.096621] [d1 loss: 0.170657] [d2 loss: 0.162104]  [sq d1 d2: 0.000073]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 500/676] [D loss: -0.004408] [G loss: -0.048057] [d1 loss: 0.102585] [d2 loss: 0.097340]  [sq d1 d2: 0.000028]  [num0: 11.000000] [num1 53.000000]
[Epoch 106/500] [Batch 520/676] [D loss: -0.002902] [G loss: -0.006038] [d1 loss: 0.096672] [d2 loss: 0.106537]  [sq d1 d2: 0.000097]  [num0: 11.000000] [num1 53.000000]
[Epoch 106/500] [Batch 540/676] [D loss: -0.032726] [G loss: 0.040662] [d1 loss: 0.098159] [d2 loss: 0.100144]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 560/676] [D loss: -0.022702] [G loss: 0.103840] [d1 loss: 0.152325] [d2 loss: 0.194779]  [sq d1 d2: 0.001802]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 580/676] [D loss: -0.055368] [G loss: 0.144579] [d1 loss: 0.092929] [d2 loss: 0.122029]  [sq d1 d2: 0.000847]  [num0: 13.000000] [num1 51.000000]
[Epoch 106/500] [Batch 600/676] [D loss: -0.007037] [G loss: 0.175380] [d1 loss: 0.119835] [d2 loss: 0.122208]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 106/500] [Batch 620/676] [D loss: 0.000670] [G loss: 0.169962] [d1 loss: 0.135571] [d2 loss: 0.149219]  [sq d1 d2: 0.000186]  [num0: 20.000000] [num1 44.000000]
[Epoch 106/500] [Batch 640/676] [D loss: -0.017532] [G loss: 0.137803] [d1 loss: 0.237331] [d2 loss: 0.240875]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 106/500] [Batch 660/676] [D loss: 0.014963] [G loss: 0.102101] [d1 loss: 0.126353] [d2 loss: 0.133850]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 107/500] [Batch 0/676] [D loss: 0.005485] [G loss: 0.070794] [d1 loss: 0.095743] [d2 loss: 0.075982]  [sq d1 d2: 0.000391]  [num0: 18.000000] [num1 46.000000]
[Epoch 107/500] [Batch 20/676] [D loss: 0.000266] [G loss: 0.044696] [d1 loss: 0.069165] [d2 loss: 0.068636]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 107/500] [Batch 40/676] [D loss: -0.000535] [G loss: 0.043181] [d1 loss: 0.094421] [d2 loss: 0.062725]  [sq d1 d2: 0.001005]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 60/676] [D loss: -0.022944] [G loss: 0.018232] [d1 loss: 0.094085] [d2 loss: 0.114262]  [sq d1 d2: 0.000407]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 80/676] [D loss: -0.050407] [G loss: -0.017287] [d1 loss: 0.282936] [d2 loss: 0.298639]  [sq d1 d2: 0.000247]  [num0: 14.000000] [num1 50.000000]
[Epoch 107/500] [Batch 100/676] [D loss: -0.050937] [G loss: -0.060484] [d1 loss: 0.166431] [d2 loss: 0.177199]  [sq d1 d2: 0.000116]  [num0: 20.000000] [num1 44.000000]
[Epoch 107/500] [Batch 120/676] [D loss: 0.018576] [G loss: -0.079792] [d1 loss: 0.082767] [d2 loss: 0.083389]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 107/500] [Batch 140/676] [D loss: -0.031886] [G loss: -0.052233] [d1 loss: 0.107294] [d2 loss: 0.088760]  [sq d1 d2: 0.000344]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 160/676] [D loss: -0.038668] [G loss: -0.031657] [d1 loss: 0.106988] [d2 loss: 0.114463]  [sq d1 d2: 0.000056]  [num0: 10.000000] [num1 54.000000]
[Epoch 107/500] [Batch 180/676] [D loss: 0.013530] [G loss: -0.014118] [d1 loss: 0.140972] [d2 loss: 0.135455]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 200/676] [D loss: 0.001619] [G loss: 0.021397] [d1 loss: 0.112403] [d2 loss: 0.114555]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 107/500] [Batch 220/676] [D loss: -0.007519] [G loss: 0.087509] [d1 loss: 0.092462] [d2 loss: 0.090865]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 240/676] [D loss: -0.012441] [G loss: 0.120557] [d1 loss: 0.116269] [d2 loss: 0.098552]  [sq d1 d2: 0.000314]  [num0: 11.000000] [num1 53.000000]
[Epoch 107/500] [Batch 260/676] [D loss: -0.025564] [G loss: 0.209707] [d1 loss: 0.084644] [d2 loss: 0.085033]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 107/500] [Batch 280/676] [D loss: -0.041445] [G loss: 0.262880] [d1 loss: 0.198577] [d2 loss: 0.231643]  [sq d1 d2: 0.001093]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 300/676] [D loss: 0.006904] [G loss: 0.319122] [d1 loss: 0.099252] [d2 loss: 0.079765]  [sq d1 d2: 0.000380]  [num0: 12.000000] [num1 52.000000]
[Epoch 107/500] [Batch 320/676] [D loss: -0.104782] [G loss: 0.382847] [d1 loss: 0.099010] [d2 loss: 0.079241]  [sq d1 d2: 0.000391]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 340/676] [D loss: -0.041462] [G loss: 0.382614] [d1 loss: 0.081195] [d2 loss: 0.102868]  [sq d1 d2: 0.000470]  [num0: 18.000000] [num1 46.000000]
[Epoch 107/500] [Batch 360/676] [D loss: -0.013733] [G loss: 0.345725] [d1 loss: 0.103092] [d2 loss: 0.095786]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 380/676] [D loss: 0.037152] [G loss: 0.221488] [d1 loss: 0.115821] [d2 loss: 0.102579]  [sq d1 d2: 0.000175]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 400/676] [D loss: 0.027702] [G loss: 0.082790] [d1 loss: 0.212575] [d2 loss: 0.195538]  [sq d1 d2: 0.000290]  [num0: 18.000000] [num1 46.000000]
[Epoch 107/500] [Batch 420/676] [D loss: 0.013846] [G loss: -0.000120] [d1 loss: 0.067624] [d2 loss: 0.072560]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 440/676] [D loss: -0.000425] [G loss: -0.095808] [d1 loss: 0.127017] [d2 loss: 0.122657]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 460/676] [D loss: -0.032188] [G loss: -0.219236] [d1 loss: 0.104561] [d2 loss: 0.105952]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 480/676] [D loss: -0.057840] [G loss: -0.333582] [d1 loss: 0.183894] [d2 loss: 0.207317]  [sq d1 d2: 0.000549]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 500/676] [D loss: -0.092204] [G loss: -0.426241] [d1 loss: 0.204234] [d2 loss: 0.204244]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 107/500] [Batch 520/676] [D loss: -0.067158] [G loss: -0.501120] [d1 loss: 0.177986] [d2 loss: 0.223784]  [sq d1 d2: 0.002097]  [num0: 15.000000] [num1 49.000000]
[Epoch 107/500] [Batch 540/676] [D loss: -0.058880] [G loss: -0.573634] [d1 loss: 0.079801] [d2 loss: 0.085905]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 107/500] [Batch 560/676] [D loss: -0.020593] [G loss: -0.599557] [d1 loss: 0.136067] [d2 loss: 0.116746]  [sq d1 d2: 0.000373]  [num0: 14.000000] [num1 50.000000]
[Epoch 107/500] [Batch 580/676] [D loss: 0.031246] [G loss: -0.626526] [d1 loss: 0.111359] [d2 loss: 0.114035]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 107/500] [Batch 600/676] [D loss: 0.039845] [G loss: -0.474889] [d1 loss: 0.114378] [d2 loss: 0.114170]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 107/500] [Batch 620/676] [D loss: 0.007325] [G loss: -0.258795] [d1 loss: 0.113713] [d2 loss: 0.111417]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]

[Epoch 107/500] [Batch 640/676] [D loss: 0.019119] [G loss: -0.123255] [d1 loss: 0.220585] [d2 loss: 0.175626]  [sq d1 d2: 0.002021]  [num0: 13.000000] [num1 51.000000]
[Epoch 107/500] [Batch 660/676] [D loss: -0.006851] [G loss: -0.037200] [d1 loss: 0.103393] [d2 loss: 0.091721]  [sq d1 d2: 0.000136]  [num0: 17.000000] [num1 47.000000]
[Epoch 108/500] [Batch 0/676] [D loss: -0.016631] [G loss: 0.023468] [d1 loss: 0.103125] [d2 loss: 0.092449]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 108/500] [Batch 20/676] [D loss: -0.034532] [G loss: 0.137565] [d1 loss: 0.060935] [d2 loss: 0.063465]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 40/676] [D loss: -0.071299] [G loss: 0.338249] [d1 loss: 0.128928] [d2 loss: 0.115386]  [sq d1 d2: 0.000183]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 60/676] [D loss: -0.103245] [G loss: 0.422384] [d1 loss: 0.083944] [d2 loss: 0.085473]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 80/676] [D loss: -0.065800] [G loss: 0.537817] [d1 loss: 0.036093] [d2 loss: 0.046602]  [sq d1 d2: 0.000110]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 100/676] [D loss: -0.044638] [G loss: 0.521766] [d1 loss: 0.103736] [d2 loss: 0.103267]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 120/676] [D loss: -0.026323] [G loss: 0.498774] [d1 loss: 0.094849] [d2 loss: 0.096123]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 108/500] [Batch 140/676] [D loss: -0.011397] [G loss: 0.423876] [d1 loss: 0.065108] [d2 loss: 0.073394]  [sq d1 d2: 0.000069]  [num0: 11.000000] [num1 53.000000]
[Epoch 108/500] [Batch 160/676] [D loss: 0.016659] [G loss: 0.254668] [d1 loss: 0.051376] [d2 loss: 0.051624]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 108/500] [Batch 180/676] [D loss: 0.013201] [G loss: 0.169416] [d1 loss: 0.105472] [d2 loss: 0.082272]  [sq d1 d2: 0.000538]  [num0: 12.000000] [num1 52.000000]
[Epoch 108/500] [Batch 200/676] [D loss: -0.013348] [G loss: 0.085469] [d1 loss: 0.111888] [d2 loss: 0.123313]  [sq d1 d2: 0.000131]  [num0: 12.000000] [num1 52.000000]
[Epoch 108/500] [Batch 220/676] [D loss: -0.044694] [G loss: 0.023912] [d1 loss: 0.053668] [d2 loss: 0.055092]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 108/500] [Batch 240/676] [D loss: -0.096103] [G loss: -0.032368] [d1 loss: 0.127422] [d2 loss: 0.131697]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 260/676] [D loss: -0.073290] [G loss: -0.061695] [d1 loss: 0.136392] [d2 loss: 0.156084]  [sq d1 d2: 0.000388]  [num0: 16.000000] [num1 48.000000]
[Epoch 108/500] [Batch 280/676] [D loss: -0.080972] [G loss: -0.076587] [d1 loss: 0.046167] [d2 loss: 0.068441]  [sq d1 d2: 0.000496]  [num0: 15.000000] [num1 49.000000]
[Epoch 108/500] [Batch 300/676] [D loss: -0.051991] [G loss: -0.203858] [d1 loss: 0.288149] [d2 loss: 0.302387]  [sq d1 d2: 0.000203]  [num0: 17.000000] [num1 47.000000]
[Epoch 108/500] [Batch 320/676] [D loss: 0.028911] [G loss: -0.294650] [d1 loss: 0.112369] [d2 loss: 0.092467]  [sq d1 d2: 0.000396]  [num0: 18.000000] [num1 46.000000]
[Epoch 108/500] [Batch 340/676] [D loss: 0.079109] [G loss: -0.363470] [d1 loss: 0.045902] [d2 loss: 0.052554]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 108/500] [Batch 360/676] [D loss: 0.008217] [G loss: -0.318060] [d1 loss: 0.089611] [d2 loss: 0.066309]  [sq d1 d2: 0.000543]  [num0: 18.000000] [num1 46.000000]
[Epoch 108/500] [Batch 380/676] [D loss: 0.022939] [G loss: -0.191464] [d1 loss: 0.143430] [d2 loss: 0.089088]  [sq d1 d2: 0.002953]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 400/676] [D loss: 0.007060] [G loss: -0.078537] [d1 loss: 0.100539] [d2 loss: 0.087223]  [sq d1 d2: 0.000177]  [num0: 20.000000] [num1 44.000000]
[Epoch 108/500] [Batch 420/676] [D loss: -0.008144] [G loss: 0.044745] [d1 loss: 0.062411] [d2 loss: 0.075624]  [sq d1 d2: 0.000175]  [num0: 12.000000] [num1 52.000000]
[Epoch 108/500] [Batch 440/676] [D loss: -0.040494] [G loss: 0.225105] [d1 loss: 0.117353] [d2 loss: 0.091305]  [sq d1 d2: 0.000679]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 460/676] [D loss: -0.090302] [G loss: 0.425539] [d1 loss: 0.077174] [d2 loss: 0.063351]  [sq d1 d2: 0.000191]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 480/676] [D loss: -0.104736] [G loss: 0.659512] [d1 loss: 0.149140] [d2 loss: 0.157537]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 108/500] [Batch 500/676] [D loss: -0.119229] [G loss: 0.754817] [d1 loss: 0.159612] [d2 loss: 0.169777]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 108/500] [Batch 520/676] [D loss: -0.139018] [G loss: 0.774743] [d1 loss: 0.114023] [d2 loss: 0.122997]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 540/676] [D loss: -0.003193] [G loss: 0.729579] [d1 loss: 0.070013] [d2 loss: 0.070634]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 108/500] [Batch 560/676] [D loss: -0.039884] [G loss: 0.658400] [d1 loss: 0.227979] [d2 loss: 0.180007]  [sq d1 d2: 0.002301]  [num0: 19.000000] [num1 45.000000]
[Epoch 108/500] [Batch 580/676] [D loss: 0.022783] [G loss: 0.453664] [d1 loss: 0.164709] [d2 loss: 0.145967]  [sq d1 d2: 0.000351]  [num0: 19.000000] [num1 45.000000]
[Epoch 108/500] [Batch 600/676] [D loss: 0.008508] [G loss: 0.267221] [d1 loss: 0.068097] [d2 loss: 0.075179]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 108/500] [Batch 620/676] [D loss: 0.029396] [G loss: 0.144914] [d1 loss: 0.057006] [d2 loss: 0.070931]  [sq d1 d2: 0.000194]  [num0: 12.000000] [num1 52.000000]
[Epoch 108/500] [Batch 640/676] [D loss: 0.004104] [G loss: -0.001067] [d1 loss: 0.071306] [d2 loss: 0.082922]  [sq d1 d2: 0.000135]  [num0: 13.000000] [num1 51.000000]
[Epoch 108/500] [Batch 660/676] [D loss: -0.014884] [G loss: -0.149466] [d1 loss: 0.120755] [d2 loss: 0.121962]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 109/500] [Batch 0/676] [D loss: -0.012620] [G loss: -0.275590] [d1 loss: 0.103350] [d2 loss: 0.097811]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 109/500] [Batch 20/676] [D loss: -0.058216] [G loss: -0.464053] [d1 loss: 0.124138] [d2 loss: 0.111836]  [sq d1 d2: 0.000151]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 40/676] [D loss: -0.115384] [G loss: -0.607498] [d1 loss: 0.105277] [d2 loss: 0.084065]  [sq d1 d2: 0.000450]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 60/676] [D loss: -0.079107] [G loss: -0.732944] [d1 loss: 0.069930] [d2 loss: 0.080512]  [sq d1 d2: 0.000112]  [num0: 15.000000] [num1 49.000000]
[Epoch 109/500] [Batch 80/676] [D loss: 0.008031] [G loss: -0.759020] [d1 loss: 0.183440] [d2 loss: 0.130769]  [sq d1 d2: 0.002774]  [num0: 13.000000] [num1 51.000000]
[Epoch 109/500] [Batch 100/676] [D loss: 0.012194] [G loss: -0.834276] [d1 loss: 0.104877] [d2 loss: 0.123771]  [sq d1 d2: 0.000357]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 120/676] [D loss: 0.048502] [G loss: -0.740205] [d1 loss: 0.093562] [d2 loss: 0.093867]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 140/676] [D loss: 0.016878] [G loss: -0.520886] [d1 loss: 0.140837] [d2 loss: 0.133732]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 109/500] [Batch 160/676] [D loss: 0.024278] [G loss: -0.374553] [d1 loss: 0.049708] [d2 loss: 0.056254]  [sq d1 d2: 0.000043]  [num0: 13.000000] [num1 51.000000]
[Epoch 109/500] [Batch 180/676] [D loss: 0.012158] [G loss: -0.237480] [d1 loss: 0.092193] [d2 loss: 0.118718]  [sq d1 d2: 0.000704]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 200/676] [D loss: -0.009894] [G loss: -0.181985] [d1 loss: 0.223587] [d2 loss: 0.198279]  [sq d1 d2: 0.000640]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 220/676] [D loss: -0.014672] [G loss: -0.080280] [d1 loss: 0.140723] [d2 loss: 0.120444]  [sq d1 d2: 0.000411]  [num0: 14.000000] [num1 50.000000]
[Epoch 109/500] [Batch 240/676] [D loss: -0.030801] [G loss: 0.048653] [d1 loss: 0.131842] [d2 loss: 0.123907]  [sq d1 d2: 0.000063]  [num0: 19.000000] [num1 45.000000]
[Epoch 109/500] [Batch 260/676] [D loss: -0.021367] [G loss: 0.182609] [d1 loss: 0.096262] [d2 loss: 0.064672]  [sq d1 d2: 0.000998]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 280/676] [D loss: -0.056682] [G loss: 0.343810] [d1 loss: 0.094924] [d2 loss: 0.097168]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 109/500] [Batch 300/676] [D loss: -0.062752] [G loss: 0.520470] [d1 loss: 0.071287] [d2 loss: 0.064719]  [sq d1 d2: 0.000043]  [num0: 13.000000] [num1 51.000000]

[Epoch 109/500] [Batch 320/676] [D loss: -0.084702] [G loss: 0.648435] [d1 loss: 0.085661] [d2 loss: 0.087426]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 109/500] [Batch 340/676] [D loss: -0.084601] [G loss: 0.695495] [d1 loss: 0.127254] [d2 loss: 0.120407]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 109/500] [Batch 360/676] [D loss: -0.066905] [G loss: 0.733536] [d1 loss: 0.150406] [d2 loss: 0.159978]  [sq d1 d2: 0.000092]  [num0: 13.000000] [num1 51.000000]
[Epoch 109/500] [Batch 380/676] [D loss: -0.001720] [G loss: 0.666240] [d1 loss: 0.163996] [d2 loss: 0.140253]  [sq d1 d2: 0.000564]  [num0: 18.000000] [num1 46.000000]
[Epoch 109/500] [Batch 400/676] [D loss: 0.019268] [G loss: 0.523408] [d1 loss: 0.076281] [d2 loss: 0.110753]  [sq d1 d2: 0.001188]  [num0: 20.000000] [num1 44.000000]
[Epoch 109/500] [Batch 420/676] [D loss: 0.013066] [G loss: 0.345816] [d1 loss: 0.116150] [d2 loss: 0.123392]  [sq d1 d2: 0.000052]  [num0: 19.000000] [num1 45.000000]
[Epoch 109/500] [Batch 440/676] [D loss: 0.024201] [G loss: 0.196561] [d1 loss: 0.108462] [d2 loss: 0.109488]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 109/500] [Batch 460/676] [D loss: 0.019351] [G loss: 0.057613] [d1 loss: 0.090257] [d2 loss: 0.065368]  [sq d1 d2: 0.000619]  [num0: 19.000000] [num1 45.000000]
[Epoch 109/500] [Batch 480/676] [D loss: 0.003103] [G loss: -0.036434] [d1 loss: 0.045784] [d2 loss: 0.052417]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 500/676] [D loss: -0.014221] [G loss: -0.142248] [d1 loss: 0.045102] [d2 loss: 0.043674]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 520/676] [D loss: -0.034792] [G loss: -0.274608] [d1 loss: 0.139550] [d2 loss: 0.120602]  [sq d1 d2: 0.000359]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 540/676] [D loss: -0.093275] [G loss: -0.463904] [d1 loss: 0.077798] [d2 loss: 0.079162]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 560/676] [D loss: -0.083358] [G loss: -0.711956] [d1 loss: 0.154005] [d2 loss: 0.162736]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 109/500] [Batch 580/676] [D loss: -0.088138] [G loss: -0.729271] [d1 loss: 0.112403] [d2 loss: 0.091886]  [sq d1 d2: 0.000421]  [num0: 18.000000] [num1 46.000000]
[Epoch 109/500] [Batch 600/676] [D loss: -0.122700] [G loss: -0.751345] [d1 loss: 0.227783] [d2 loss: 0.185717]  [sq d1 d2: 0.001770]  [num0: 16.000000] [num1 48.000000]
[Epoch 109/500] [Batch 620/676] [D loss: 0.004312] [G loss: -0.784663] [d1 loss: 0.075275] [d2 loss: 0.080938]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 109/500] [Batch 640/676] [D loss: 0.066271] [G loss: -0.777093] [d1 loss: 0.171522] [d2 loss: 0.179233]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 109/500] [Batch 660/676] [D loss: 0.082626] [G loss: -0.607046] [d1 loss: 0.071177] [d2 loss: 0.099845]  [sq d1 d2: 0.000822]  [num0: 17.000000] [num1 47.000000]
[Epoch 110/500] [Batch 0/676] [D loss: 0.070185] [G loss: -0.422975] [d1 loss: 0.074118] [d2 loss: 0.072427]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 110/500] [Batch 20/676] [D loss: 0.025302] [G loss: -0.226194] [d1 loss: 0.131007] [d2 loss: 0.154628]  [sq d1 d2: 0.000558]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 40/676] [D loss: 0.004046] [G loss: -0.058252] [d1 loss: 0.050893] [d2 loss: 0.044277]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 60/676] [D loss: -0.018075] [G loss: 0.107093] [d1 loss: 0.077118] [d2 loss: 0.076867]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 110/500] [Batch 80/676] [D loss: -0.057470] [G loss: 0.310577] [d1 loss: 0.110775] [d2 loss: 0.089919]  [sq d1 d2: 0.000435]  [num0: 12.000000] [num1 52.000000]
[Epoch 110/500] [Batch 100/676] [D loss: -0.111537] [G loss: 0.670316] [d1 loss: 0.094180] [d2 loss: 0.098138]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 110/500] [Batch 120/676] [D loss: -0.123533] [G loss: 0.916680] [d1 loss: 0.139342] [d2 loss: 0.151962]  [sq d1 d2: 0.000159]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 140/676] [D loss: -0.132257] [G loss: 1.027605] [d1 loss: 0.101210] [d2 loss: 0.111128]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]
[Epoch 110/500] [Batch 160/676] [D loss: -0.062231] [G loss: 0.986736] [d1 loss: 0.070945] [d2 loss: 0.092470]  [sq d1 d2: 0.000463]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 180/676] [D loss: -0.072355] [G loss: 0.950170] [d1 loss: 0.175525] [d2 loss: 0.129386]  [sq d1 d2: 0.002129]  [num0: 17.000000] [num1 47.000000]
[Epoch 110/500] [Batch 200/676] [D loss: -0.006786] [G loss: 0.871476] [d1 loss: 0.086722] [d2 loss: 0.069480]  [sq d1 d2: 0.000297]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 220/676] [D loss: 0.048135] [G loss: 0.772343] [d1 loss: 0.088373] [d2 loss: 0.106434]  [sq d1 d2: 0.000326]  [num0: 18.000000] [num1 46.000000]
[Epoch 110/500] [Batch 240/676] [D loss: 0.056648] [G loss: 0.513052] [d1 loss: 0.037171] [d2 loss: 0.043072]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 110/500] [Batch 260/676] [D loss: 0.037689] [G loss: 0.277830] [d1 loss: 0.202302] [d2 loss: 0.267272]  [sq d1 d2: 0.004221]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 280/676] [D loss: 0.004162] [G loss: 0.150674] [d1 loss: 0.095113] [d2 loss: 0.089724]  [sq d1 d2: 0.000029]  [num0: 20.000000] [num1 44.000000]
[Epoch 110/500] [Batch 300/676] [D loss: -0.010379] [G loss: 0.031244] [d1 loss: 0.047259] [d2 loss: 0.041479]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 320/676] [D loss: -0.022905] [G loss: -0.070504] [d1 loss: 0.081698] [d2 loss: 0.080770]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 340/676] [D loss: -0.047697] [G loss: -0.194556] [d1 loss: 0.101911] [d2 loss: 0.133880]  [sq d1 d2: 0.001022]  [num0: 15.000000] [num1 49.000000]
[Epoch 110/500] [Batch 360/676] [D loss: -0.073995] [G loss: -0.321285] [d1 loss: 0.152645] [d2 loss: 0.173014]  [sq d1 d2: 0.000415]  [num0: 15.000000] [num1 49.000000]
[Epoch 110/500] [Batch 380/676] [D loss: -0.157560] [G loss: -0.516882] [d1 loss: 0.041897] [d2 loss: 0.047402]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 110/500] [Batch 400/676] [D loss: -0.207741] [G loss: -0.779076] [d1 loss: 0.161272] [d2 loss: 0.142928]  [sq d1 d2: 0.000336]  [num0: 18.000000] [num1 46.000000]
[Epoch 110/500] [Batch 420/676] [D loss: -0.124084] [G loss: -0.874075] [d1 loss: 0.077494] [d2 loss: 0.085244]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 110/500] [Batch 440/676] [D loss: -0.003376] [G loss: -0.923441] [d1 loss: 0.072604] [d2 loss: 0.078534]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 460/676] [D loss: 0.078969] [G loss: -0.933370] [d1 loss: 0.179291] [d2 loss: 0.179247]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 110/500] [Batch 480/676] [D loss: 0.070581] [G loss: -0.811431] [d1 loss: 0.095851] [d2 loss: 0.109542]  [sq d1 d2: 0.000187]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 500/676] [D loss: 0.037684] [G loss: -0.550695] [d1 loss: 0.120439] [d2 loss: 0.108914]  [sq d1 d2: 0.000133]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 520/676] [D loss: 0.031069] [G loss: -0.355114] [d1 loss: 0.100790] [d2 loss: 0.099979]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 540/676] [D loss: 0.013654] [G loss: -0.236045] [d1 loss: 0.050418] [d2 loss: 0.057298]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 110/500] [Batch 560/676] [D loss: 0.003031] [G loss: -0.103915] [d1 loss: 0.102482] [d2 loss: 0.095772]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 110/500] [Batch 580/676] [D loss: -0.008096] [G loss: 0.005624] [d1 loss: 0.169993] [d2 loss: 0.195663]  [sq d1 d2: 0.000659]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 600/676] [D loss: -0.018558] [G loss: 0.117247] [d1 loss: 0.123931] [d2 loss: 0.107573]  [sq d1 d2: 0.000268]  [num0: 13.000000] [num1 51.000000]
[Epoch 110/500] [Batch 620/676] [D loss: -0.028105] [G loss: 0.255526] [d1 loss: 0.126084] [d2 loss: 0.136615]  [sq d1 d2: 0.000111]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 640/676] [D loss: -0.058183] [G loss: 0.470160] [d1 loss: 0.087918] [d2 loss: 0.096019]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 110/500] [Batch 660/676] [D loss: -0.054810] [G loss: 0.763875] [d1 loss: 0.168646] [d2 loss: 0.200568]  [sq d1 d2: 0.001019]  [num0: 20.000000] [num1 44.000000]

[Epoch 111/500] [Batch 0/676] [D loss: -0.089074] [G loss: 0.917007] [d1 loss: 0.080777] [d2 loss: 0.089373]  [sq d1 d2: 0.000074]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 20/676] [D loss: -0.117970] [G loss: 0.912861] [d1 loss: 0.102031] [d2 loss: 0.121770]  [sq d1 d2: 0.000390]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 40/676] [D loss: -0.055347] [G loss: 0.848258] [d1 loss: 0.178673] [d2 loss: 0.203428]  [sq d1 d2: 0.000613]  [num0: 19.000000] [num1 45.000000]
[Epoch 111/500] [Batch 60/676] [D loss: -0.034623] [G loss: 0.839648] [d1 loss: 0.140689] [d2 loss: 0.136702]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 111/500] [Batch 80/676] [D loss: -0.070541] [G loss: 0.809244] [d1 loss: 0.188521] [d2 loss: 0.166288]  [sq d1 d2: 0.000494]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 100/676] [D loss: 0.026247] [G loss: 0.678318] [d1 loss: 0.108548] [d2 loss: 0.106175]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 111/500] [Batch 120/676] [D loss: 0.051246] [G loss: 0.457579] [d1 loss: 0.130282] [d2 loss: 0.147444]  [sq d1 d2: 0.000295]  [num0: 16.000000] [num1 48.000000]
[Epoch 111/500] [Batch 140/676] [D loss: 0.026681] [G loss: 0.233282] [d1 loss: 0.109311] [d2 loss: 0.150525]  [sq d1 d2: 0.001699]  [num0: 18.000000] [num1 46.000000]
[Epoch 111/500] [Batch 160/676] [D loss: 0.011301] [G loss: 0.112284] [d1 loss: 0.391837] [d2 loss: 0.349947]  [sq d1 d2: 0.001755]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 180/676] [D loss: 0.002204] [G loss: -0.030204] [d1 loss: 0.096131] [d2 loss: 0.069667]  [sq d1 d2: 0.000700]  [num0: 13.000000] [num1 51.000000]
[Epoch 111/500] [Batch 200/676] [D loss: -0.019451] [G loss: -0.163173] [d1 loss: 0.111731] [d2 loss: 0.129850]  [sq d1 d2: 0.000328]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 220/676] [D loss: -0.053967] [G loss: -0.342577] [d1 loss: 0.124177] [d2 loss: 0.136181]  [sq d1 d2: 0.000144]  [num0: 16.000000] [num1 48.000000]
[Epoch 111/500] [Batch 240/676] [D loss: -0.099099] [G loss: -0.568000] [d1 loss: 0.115986] [d2 loss: 0.085808]  [sq d1 d2: 0.000911]  [num0: 18.000000] [num1 46.000000]
[Epoch 111/500] [Batch 260/676] [D loss: -0.135120] [G loss: -0.849347] [d1 loss: 0.073822] [d2 loss: 0.076009]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 111/500] [Batch 280/676] [D loss: -0.067124] [G loss: -0.957830] [d1 loss: 0.102766] [d2 loss: 0.162531]  [sq d1 d2: 0.003572]  [num0: 16.000000] [num1 48.000000]
[Epoch 111/500] [Batch 300/676] [D loss: -0.169538] [G loss: -0.941365] [d1 loss: 0.137992] [d2 loss: 0.105687]  [sq d1 d2: 0.001044]  [num0: 19.000000] [num1 45.000000]
[Epoch 111/500] [Batch 320/676] [D loss: -0.052450] [G loss: -0.984435] [d1 loss: 0.133447] [d2 loss: 0.097337]  [sq d1 d2: 0.001304]  [num0: 12.000000] [num1 52.000000]
[Epoch 111/500] [Batch 340/676] [D loss: 0.005498] [G loss: -1.002195] [d1 loss: 0.150644] [d2 loss: 0.124973]  [sq d1 d2: 0.000659]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 360/676] [D loss: 0.069562] [G loss: -0.889005] [d1 loss: 0.062418] [d2 loss: 0.058937]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 380/676] [D loss: 0.088762] [G loss: -0.628993] [d1 loss: 0.142286] [d2 loss: 0.147834]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 400/676] [D loss: 0.011976] [G loss: -0.415560] [d1 loss: 0.117936] [d2 loss: 0.111136]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 111/500] [Batch 420/676] [D loss: 0.014583] [G loss: -0.228201] [d1 loss: 0.064388] [d2 loss: 0.064140]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 111/500] [Batch 440/676] [D loss: -0.007673] [G loss: -0.051030] [d1 loss: 0.116213] [d2 loss: 0.140906]  [sq d1 d2: 0.000610]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 460/676] [D loss: -0.044663] [G loss: 0.135167] [d1 loss: 0.138364] [d2 loss: 0.133042]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 111/500] [Batch 480/676] [D loss: -0.047636] [G loss: 0.345231] [d1 loss: 0.134582] [d2 loss: 0.163697]  [sq d1 d2: 0.000848]  [num0: 12.000000] [num1 52.000000]
[Epoch 111/500] [Batch 500/676] [D loss: -0.121784] [G loss: 0.632051] [d1 loss: 0.075511] [d2 loss: 0.072888]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 111/500] [Batch 520/676] [D loss: -0.180656] [G loss: 0.998633] [d1 loss: 0.072997] [d2 loss: 0.069103]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 111/500] [Batch 540/676] [D loss: -0.168029] [G loss: 1.189305] [d1 loss: 0.079232] [d2 loss: 0.073650]  [sq d1 d2: 0.000031]  [num0: 10.000000] [num1 54.000000]
[Epoch 111/500] [Batch 560/676] [D loss: -0.043826] [G loss: 1.063206] [d1 loss: 0.103521] [d2 loss: 0.116985]  [sq d1 d2: 0.000181]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 580/676] [D loss: -0.093790] [G loss: 0.946629] [d1 loss: 0.238464] [d2 loss: 0.212608]  [sq d1 d2: 0.000669]  [num0: 18.000000] [num1 46.000000]
[Epoch 111/500] [Batch 600/676] [D loss: -0.002614] [G loss: 0.887665] [d1 loss: 0.197394] [d2 loss: 0.184276]  [sq d1 d2: 0.000172]  [num0: 17.000000] [num1 47.000000]
[Epoch 111/500] [Batch 620/676] [D loss: -0.030757] [G loss: 0.734917] [d1 loss: 0.100211] [d2 loss: 0.089816]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 111/500] [Batch 640/676] [D loss: 0.089627] [G loss: 0.467392] [d1 loss: 0.064197] [d2 loss: 0.080894]  [sq d1 d2: 0.000279]  [num0: 18.000000] [num1 46.000000]
[Epoch 111/500] [Batch 660/676] [D loss: 0.056175] [G loss: 0.257723] [d1 loss: 0.090062] [d2 loss: 0.108106]  [sq d1 d2: 0.000326]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 0/676] [D loss: 0.039219] [G loss: 0.116547] [d1 loss: 0.108064] [d2 loss: 0.107939]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 20/676] [D loss: 0.004514] [G loss: 0.033273] [d1 loss: 0.122461] [d2 loss: 0.116016]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 40/676] [D loss: -0.006678] [G loss: -0.021149] [d1 loss: 0.120101] [d2 loss: 0.131932]  [sq d1 d2: 0.000140]  [num0: 19.000000] [num1 45.000000]
[Epoch 112/500] [Batch 60/676] [D loss: -0.019825] [G loss: -0.065536] [d1 loss: 0.121780] [d2 loss: 0.099953]  [sq d1 d2: 0.000476]  [num0: 20.000000] [num1 44.000000]
[Epoch 112/500] [Batch 80/676] [D loss: -0.074053] [G loss: -0.122432] [d1 loss: 0.046405] [d2 loss: 0.040162]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 100/676] [D loss: -0.125882] [G loss: -0.150318] [d1 loss: 0.129289] [d2 loss: 0.207440]  [sq d1 d2: 0.006108]  [num0: 19.000000] [num1 45.000000]
[Epoch 112/500] [Batch 120/676] [D loss: -0.224524] [G loss: -0.379828] [d1 loss: 0.085381] [d2 loss: 0.094109]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 140/676] [D loss: -0.164951] [G loss: -0.546730] [d1 loss: 0.200705] [d2 loss: 0.203254]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 160/676] [D loss: -0.101256] [G loss: -0.577789] [d1 loss: 0.118626] [d2 loss: 0.110384]  [sq d1 d2: 0.000068]  [num0: 18.000000] [num1 46.000000]
[Epoch 112/500] [Batch 180/676] [D loss: -0.054232] [G loss: -0.739056] [d1 loss: 0.078744] [d2 loss: 0.096173]  [sq d1 d2: 0.000304]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 200/676] [D loss: -0.023842] [G loss: -0.772116] [d1 loss: 0.237220] [d2 loss: 0.195454]  [sq d1 d2: 0.001744]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 220/676] [D loss: 0.129780] [G loss: -0.762384] [d1 loss: 0.073712] [d2 loss: 0.095936]  [sq d1 d2: 0.000494]  [num0: 17.000000] [num1 47.000000]
[Epoch 112/500] [Batch 240/676] [D loss: 0.038189] [G loss: -0.571863] [d1 loss: 0.166958] [d2 loss: 0.174376]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 260/676] [D loss: 0.024655] [G loss: -0.388392] [d1 loss: 0.079356] [d2 loss: 0.092981]  [sq d1 d2: 0.000186]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 280/676] [D loss: -0.001976] [G loss: -0.272888] [d1 loss: 0.104294] [d2 loss: 0.086061]  [sq d1 d2: 0.000332]  [num0: 11.000000] [num1 53.000000]
[Epoch 112/500] [Batch 300/676] [D loss: -0.014538] [G loss: -0.153285] [d1 loss: 0.117944] [d2 loss: 0.113924]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 112/500] [Batch 320/676] [D loss: -0.032154] [G loss: -0.042120] [d1 loss: 0.150956] [d2 loss: 0.131013]  [sq d1 d2: 0.000398]  [num0: 13.000000] [num1 51.000000]
[Epoch 112/500] [Batch 340/676] [D loss: -0.042936] [G loss: 0.016014] [d1 loss: 0.131053] [d2 loss: 0.126202]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]

[Epoch 112/500] [Batch 360/676] [D loss: -0.045301] [G loss: 0.043403] [d1 loss: 0.220575] [d2 loss: 0.193751]  [sq d1 d2: 0.000720]  [num0: 15.000000] [num1 49.000000]
[Epoch 112/500] [Batch 380/676] [D loss: -0.074683] [G loss: 0.067484] [d1 loss: 0.175653] [d2 loss: 0.156535]  [sq d1 d2: 0.000366]  [num0: 13.000000] [num1 51.000000]
[Epoch 112/500] [Batch 400/676] [D loss: -0.058775] [G loss: 0.109293] [d1 loss: 0.138367] [d2 loss: 0.139650]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 420/676] [D loss: -0.071092] [G loss: 0.135230] [d1 loss: 0.187058] [d2 loss: 0.156583]  [sq d1 d2: 0.000929]  [num0: 17.000000] [num1 47.000000]
[Epoch 112/500] [Batch 440/676] [D loss: -0.038341] [G loss: 0.154661] [d1 loss: 0.146012] [d2 loss: 0.120234]  [sq d1 d2: 0.000665]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 460/676] [D loss: -0.044967] [G loss: 0.178806] [d1 loss: 0.253580] [d2 loss: 0.221581]  [sq d1 d2: 0.001024]  [num0: 18.000000] [num1 46.000000]
[Epoch 112/500] [Batch 480/676] [D loss: -0.071076] [G loss: 0.169454] [d1 loss: 0.181821] [d2 loss: 0.084803]  [sq d1 d2: 0.009413]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 500/676] [D loss: -0.030680] [G loss: 0.199633] [d1 loss: 0.131459] [d2 loss: 0.116397]  [sq d1 d2: 0.000227]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 520/676] [D loss: -0.019111] [G loss: 0.218313] [d1 loss: 0.136996] [d2 loss: 0.121958]  [sq d1 d2: 0.000226]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 540/676] [D loss: -0.019915] [G loss: 0.259265] [d1 loss: 0.148755] [d2 loss: 0.153897]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 560/676] [D loss: 0.005459] [G loss: 0.277884] [d1 loss: 0.232225] [d2 loss: 0.249443]  [sq d1 d2: 0.000296]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 580/676] [D loss: -0.026235] [G loss: 0.300358] [d1 loss: 0.072359] [d2 loss: 0.063972]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 112/500] [Batch 600/676] [D loss: 0.034512] [G loss: 0.272862] [d1 loss: 0.133247] [d2 loss: 0.129879]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 112/500] [Batch 620/676] [D loss: -0.010205] [G loss: 0.250157] [d1 loss: 0.092609] [d2 loss: 0.081683]  [sq d1 d2: 0.000119]  [num0: 11.000000] [num1 53.000000]
[Epoch 112/500] [Batch 640/676] [D loss: 0.014932] [G loss: 0.252046] [d1 loss: 0.093620] [d2 loss: 0.059358]  [sq d1 d2: 0.001174]  [num0: 16.000000] [num1 48.000000]
[Epoch 112/500] [Batch 660/676] [D loss: 0.007998] [G loss: 0.229530] [d1 loss: 0.096011] [d2 loss: 0.095928]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 113/500] [Batch 0/676] [D loss: -0.009532] [G loss: 0.226026] [d1 loss: 0.074058] [d2 loss: 0.071545]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 113/500] [Batch 20/676] [D loss: -0.001770] [G loss: 0.254288] [d1 loss: 0.119918] [d2 loss: 0.131087]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 40/676] [D loss: -0.000455] [G loss: 0.263747] [d1 loss: 0.067341] [d2 loss: 0.056220]  [sq d1 d2: 0.000124]  [num0: 16.000000] [num1 48.000000]
[Epoch 113/500] [Batch 60/676] [D loss: -0.018573] [G loss: 0.297049] [d1 loss: 0.222354] [d2 loss: 0.193119]  [sq d1 d2: 0.000855]  [num0: 17.000000] [num1 47.000000]
[Epoch 113/500] [Batch 80/676] [D loss: -0.044540] [G loss: 0.361978] [d1 loss: 0.034925] [d2 loss: 0.041269]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 100/676] [D loss: -0.017862] [G loss: 0.449390] [d1 loss: 0.116736] [d2 loss: 0.145224]  [sq d1 d2: 0.000812]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 120/676] [D loss: -0.064847] [G loss: 0.474584] [d1 loss: 0.110362] [d2 loss: 0.137105]  [sq d1 d2: 0.000715]  [num0: 17.000000] [num1 47.000000]
[Epoch 113/500] [Batch 140/676] [D loss: -0.011606] [G loss: 0.440714] [d1 loss: 0.138145] [d2 loss: 0.121183]  [sq d1 d2: 0.000288]  [num0: 17.000000] [num1 47.000000]
[Epoch 113/500] [Batch 160/676] [D loss: -0.005646] [G loss: 0.376805] [d1 loss: 0.184998] [d2 loss: 0.189743]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 180/676] [D loss: -0.011519] [G loss: 0.330576] [d1 loss: 0.090684] [d2 loss: 0.099878]  [sq d1 d2: 0.000085]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 200/676] [D loss: 0.008642] [G loss: 0.209707] [d1 loss: 0.174391] [d2 loss: 0.142280]  [sq d1 d2: 0.001031]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 220/676] [D loss: 0.045415] [G loss: 0.034271] [d1 loss: 0.197359] [d2 loss: 0.163478]  [sq d1 d2: 0.001148]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 240/676] [D loss: 0.000939] [G loss: -0.046956] [d1 loss: 0.156719] [d2 loss: 0.167630]  [sq d1 d2: 0.000119]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 260/676] [D loss: -0.005674] [G loss: -0.066172] [d1 loss: 0.114344] [d2 loss: 0.104915]  [sq d1 d2: 0.000089]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 280/676] [D loss: 0.000663] [G loss: -0.069873] [d1 loss: 0.185782] [d2 loss: 0.196596]  [sq d1 d2: 0.000117]  [num0: 16.000000] [num1 48.000000]
[Epoch 113/500] [Batch 300/676] [D loss: -0.037678] [G loss: -0.079321] [d1 loss: 0.090597] [d2 loss: 0.083789]  [sq d1 d2: 0.000046]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 320/676] [D loss: -0.019706] [G loss: -0.073130] [d1 loss: 0.097899] [d2 loss: 0.104241]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 340/676] [D loss: -0.026016] [G loss: -0.097601] [d1 loss: 0.100143] [d2 loss: 0.100642]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 113/500] [Batch 360/676] [D loss: -0.002298] [G loss: -0.098789] [d1 loss: 0.173533] [d2 loss: 0.192024]  [sq d1 d2: 0.000342]  [num0: 15.000000] [num1 49.000000]
[Epoch 113/500] [Batch 380/676] [D loss: -0.048602] [G loss: -0.078223] [d1 loss: 0.080621] [d2 loss: 0.086336]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 113/500] [Batch 400/676] [D loss: -0.029053] [G loss: -0.108087] [d1 loss: 0.065608] [d2 loss: 0.067473]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 420/676] [D loss: -0.041034] [G loss: -0.130500] [d1 loss: 0.099720] [d2 loss: 0.111696]  [sq d1 d2: 0.000143]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 440/676] [D loss: -0.028614] [G loss: -0.124048] [d1 loss: 0.088503] [d2 loss: 0.128481]  [sq d1 d2: 0.001598]  [num0: 15.000000] [num1 49.000000]
[Epoch 113/500] [Batch 460/676] [D loss: -0.034426] [G loss: -0.166120] [d1 loss: 0.122580] [d2 loss: 0.137006]  [sq d1 d2: 0.000208]  [num0: 15.000000] [num1 49.000000]
[Epoch 113/500] [Batch 480/676] [D loss: -0.071835] [G loss: -0.178159] [d1 loss: 0.145542] [d2 loss: 0.095942]  [sq d1 d2: 0.002460]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 500/676] [D loss: -0.024158] [G loss: -0.204821] [d1 loss: 0.111177] [d2 loss: 0.112446]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 520/676] [D loss: -0.021568] [G loss: -0.256592] [d1 loss: 0.138557] [d2 loss: 0.168658]  [sq d1 d2: 0.000906]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 540/676] [D loss: -0.045552] [G loss: -0.288612] [d1 loss: 0.163605] [d2 loss: 0.143061]  [sq d1 d2: 0.000422]  [num0: 20.000000] [num1 44.000000]
[Epoch 113/500] [Batch 560/676] [D loss: 0.002407] [G loss: -0.307369] [d1 loss: 0.074213] [d2 loss: 0.091911]  [sq d1 d2: 0.000313]  [num0: 18.000000] [num1 46.000000]
[Epoch 113/500] [Batch 580/676] [D loss: -0.000455] [G loss: -0.291948] [d1 loss: 0.107051] [d2 loss: 0.119897]  [sq d1 d2: 0.000165]  [num0: 19.000000] [num1 45.000000]
[Epoch 113/500] [Batch 600/676] [D loss: 0.009769] [G loss: -0.306010] [d1 loss: 0.092006] [d2 loss: 0.133651]  [sq d1 d2: 0.001734]  [num0: 14.000000] [num1 50.000000]
[Epoch 113/500] [Batch 620/676] [D loss: -0.002120] [G loss: -0.295719] [d1 loss: 0.117793] [d2 loss: 0.140818]  [sq d1 d2: 0.000530]  [num0: 17.000000] [num1 47.000000]
[Epoch 113/500] [Batch 640/676] [D loss: -0.032346] [G loss: -0.318375] [d1 loss: 0.142213] [d2 loss: 0.154086]  [sq d1 d2: 0.000141]  [num0: 13.000000] [num1 51.000000]

[Epoch 113/500] [Batch 660/676] [D loss: -0.014851] [G loss: -0.312742] [d1 loss: 0.082508] [d2 loss: 0.109313]  [sq d1 d2: 0.000719]  [num0: 15.000000] [num1 49.000000]
[Epoch 114/500] [Batch 0/676] [D loss: -0.035545] [G loss: -0.311961] [d1 loss: 0.144723] [d2 loss: 0.179130]  [sq d1 d2: 0.001184]  [num0: 19.000000] [num1 45.000000]
[Epoch 114/500] [Batch 20/676] [D loss: -0.025777] [G loss: -0.321556] [d1 loss: 0.079160] [d2 loss: 0.085775]  [sq d1 d2: 0.000044]  [num0: 12.000000] [num1 52.000000]
[Epoch 114/500] [Batch 40/676] [D loss: -0.005887] [G loss: -0.290408] [d1 loss: 0.145910] [d2 loss: 0.151155]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 114/500] [Batch 60/676] [D loss: -0.039069] [G loss: -0.294307] [d1 loss: 0.088344] [d2 loss: 0.127494]  [sq d1 d2: 0.001533]  [num0: 17.000000] [num1 47.000000]
[Epoch 114/500] [Batch 80/676] [D loss: -0.001038] [G loss: -0.305706] [d1 loss: 0.113540] [d2 loss: 0.084833]  [sq d1 d2: 0.000824]  [num0: 18.000000] [num1 46.000000]
[Epoch 114/500] [Batch 100/676] [D loss: 0.006571] [G loss: -0.293008] [d1 loss: 0.091868] [d2 loss: 0.084645]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 120/676] [D loss: -0.006702] [G loss: -0.313043] [d1 loss: 0.123591] [d2 loss: 0.149292]  [sq d1 d2: 0.000661]  [num0: 18.000000] [num1 46.000000]
[Epoch 114/500] [Batch 140/676] [D loss: -0.020373] [G loss: -0.288346] [d1 loss: 0.039207] [d2 loss: 0.036029]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 114/500] [Batch 160/676] [D loss: 0.004188] [G loss: -0.298340] [d1 loss: 0.126767] [d2 loss: 0.125835]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 180/676] [D loss: -0.027643] [G loss: -0.302477] [d1 loss: 0.095583] [d2 loss: 0.094386]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 200/676] [D loss: -0.012263] [G loss: -0.262418] [d1 loss: 0.100087] [d2 loss: 0.071256]  [sq d1 d2: 0.000831]  [num0: 10.000000] [num1 54.000000]
[Epoch 114/500] [Batch 220/676] [D loss: -0.023555] [G loss: -0.266367] [d1 loss: 0.052822] [d2 loss: 0.053642]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 240/676] [D loss: 0.007571] [G loss: -0.241807] [d1 loss: 0.183451] [d2 loss: 0.157544]  [sq d1 d2: 0.000671]  [num0: 12.000000] [num1 52.000000]
[Epoch 114/500] [Batch 260/676] [D loss: -0.000928] [G loss: -0.233964] [d1 loss: 0.112950] [d2 loss: 0.111517]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 114/500] [Batch 280/676] [D loss: -0.024261] [G loss: -0.233759] [d1 loss: 0.118300] [d2 loss: 0.092747]  [sq d1 d2: 0.000653]  [num0: 12.000000] [num1 52.000000]
[Epoch 114/500] [Batch 300/676] [D loss: -0.019341] [G loss: -0.210523] [d1 loss: 0.179663] [d2 loss: 0.132516]  [sq d1 d2: 0.002223]  [num0: 20.000000] [num1 44.000000]
[Epoch 114/500] [Batch 320/676] [D loss: -0.013018] [G loss: -0.210167] [d1 loss: 0.153936] [d2 loss: 0.207451]  [sq d1 d2: 0.002864]  [num0: 13.000000] [num1 51.000000]
[Epoch 114/500] [Batch 340/676] [D loss: -0.007376] [G loss: -0.166944] [d1 loss: 0.073849] [d2 loss: 0.072552]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 114/500] [Batch 360/676] [D loss: 0.001302] [G loss: -0.155021] [d1 loss: 0.070698] [d2 loss: 0.078558]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 380/676] [D loss: 0.004742] [G loss: -0.102034] [d1 loss: 0.087106] [d2 loss: 0.101150]  [sq d1 d2: 0.000197]  [num0: 18.000000] [num1 46.000000]
[Epoch 114/500] [Batch 400/676] [D loss: -0.012106] [G loss: -0.061633] [d1 loss: 0.073573] [d2 loss: 0.079458]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 114/500] [Batch 420/676] [D loss: -0.020703] [G loss: -0.049246] [d1 loss: 0.059374] [d2 loss: 0.057824]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 114/500] [Batch 440/676] [D loss: -0.014341] [G loss: -0.054988] [d1 loss: 0.067754] [d2 loss: 0.083033]  [sq d1 d2: 0.000233]  [num0: 16.000000] [num1 48.000000]
[Epoch 114/500] [Batch 460/676] [D loss: 0.001832] [G loss: -0.048209] [d1 loss: 0.066263] [d2 loss: 0.070151]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 114/500] [Batch 480/676] [D loss: -0.007760] [G loss: -0.061147] [d1 loss: 0.078728] [d2 loss: 0.086227]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 114/500] [Batch 500/676] [D loss: -0.022668] [G loss: -0.062249] [d1 loss: 0.083986] [d2 loss: 0.128121]  [sq d1 d2: 0.001948]  [num0: 15.000000] [num1 49.000000]
[Epoch 114/500] [Batch 520/676] [D loss: -0.018212] [G loss: -0.061786] [d1 loss: 0.077882] [d2 loss: 0.052316]  [sq d1 d2: 0.000654]  [num0: 18.000000] [num1 46.000000]
[Epoch 114/500] [Batch 540/676] [D loss: -0.022618] [G loss: -0.069245] [d1 loss: 0.090134] [d2 loss: 0.087671]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 114/500] [Batch 560/676] [D loss: -0.023401] [G loss: -0.081598] [d1 loss: 0.047323] [d2 loss: 0.045676]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 114/500] [Batch 580/676] [D loss: -0.007179] [G loss: -0.089652] [d1 loss: 0.078840] [d2 loss: 0.078027]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 114/500] [Batch 600/676] [D loss: -0.017081] [G loss: -0.079647] [d1 loss: 0.046494] [d2 loss: 0.067868]  [sq d1 d2: 0.000457]  [num0: 14.000000] [num1 50.000000]
[Epoch 114/500] [Batch 620/676] [D loss: -0.009805] [G loss: -0.102471] [d1 loss: 0.069767] [d2 loss: 0.081144]  [sq d1 d2: 0.000129]  [num0: 18.000000] [num1 46.000000]
[Epoch 114/500] [Batch 640/676] [D loss: -0.006178] [G loss: -0.105000] [d1 loss: 0.168196] [d2 loss: 0.194905]  [sq d1 d2: 0.000713]  [num0: 12.000000] [num1 52.000000]
[Epoch 114/500] [Batch 660/676] [D loss: -0.021261] [G loss: -0.117364] [d1 loss: 0.044678] [d2 loss: 0.039797]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 0/676] [D loss: -0.018732] [G loss: -0.101366] [d1 loss: 0.046021] [d2 loss: 0.048490]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 20/676] [D loss: -0.013593] [G loss: -0.113239] [d1 loss: 0.118035] [d2 loss: 0.097231]  [sq d1 d2: 0.000433]  [num0: 17.000000] [num1 47.000000]
[Epoch 115/500] [Batch 40/676] [D loss: -0.015963] [G loss: -0.104021] [d1 loss: 0.135860] [d2 loss: 0.137072]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 60/676] [D loss: -0.000782] [G loss: -0.111540] [d1 loss: 0.157770] [d2 loss: 0.100813]  [sq d1 d2: 0.003244]  [num0: 13.000000] [num1 51.000000]
[Epoch 115/500] [Batch 80/676] [D loss: -0.010430] [G loss: -0.114922] [d1 loss: 0.078278] [d2 loss: 0.060792]  [sq d1 d2: 0.000306]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 100/676] [D loss: 0.014358] [G loss: -0.102912] [d1 loss: 0.131213] [d2 loss: 0.126225]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 120/676] [D loss: -0.019237] [G loss: -0.105775] [d1 loss: 0.051210] [d2 loss: 0.069902]  [sq d1 d2: 0.000349]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 140/676] [D loss: -0.006469] [G loss: -0.108052] [d1 loss: 0.094609] [d2 loss: 0.097710]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 160/676] [D loss: -0.014304] [G loss: -0.113222] [d1 loss: 0.078690] [d2 loss: 0.119391]  [sq d1 d2: 0.001657]  [num0: 11.000000] [num1 53.000000]
[Epoch 115/500] [Batch 180/676] [D loss: -0.014899] [G loss: -0.106126] [d1 loss: 0.099152] [d2 loss: 0.094214]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 200/676] [D loss: -0.015892] [G loss: -0.112097] [d1 loss: 0.046770] [d2 loss: 0.062681]  [sq d1 d2: 0.000253]  [num0: 10.000000] [num1 54.000000]
[Epoch 115/500] [Batch 220/676] [D loss: -0.032233] [G loss: -0.102680] [d1 loss: 0.119159] [d2 loss: 0.106927]  [sq d1 d2: 0.000150]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 240/676] [D loss: -0.027414] [G loss: -0.083816] [d1 loss: 0.077889] [d2 loss: 0.097464]  [sq d1 d2: 0.000383]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 260/676] [D loss: -0.004373] [G loss: -0.092985] [d1 loss: 0.114586] [d2 loss: 0.126980]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 280/676] [D loss: -0.012036] [G loss: -0.092426] [d1 loss: 0.101964] [d2 loss: 0.105374]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]

[Epoch 115/500] [Batch 300/676] [D loss: -0.022470] [G loss: -0.086256] [d1 loss: 0.090920] [d2 loss: 0.096510]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 320/676] [D loss: -0.015532] [G loss: -0.096088] [d1 loss: 0.099770] [d2 loss: 0.116008]  [sq d1 d2: 0.000264]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 340/676] [D loss: -0.018256] [G loss: -0.092057] [d1 loss: 0.092616] [d2 loss: 0.107704]  [sq d1 d2: 0.000228]  [num0: 12.000000] [num1 52.000000]
[Epoch 115/500] [Batch 360/676] [D loss: -0.001928] [G loss: -0.089684] [d1 loss: 0.086843] [d2 loss: 0.087124]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 380/676] [D loss: -0.019126] [G loss: -0.091996] [d1 loss: 0.046502] [d2 loss: 0.055462]  [sq d1 d2: 0.000080]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 400/676] [D loss: -0.016535] [G loss: -0.082364] [d1 loss: 0.143007] [d2 loss: 0.147631]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 420/676] [D loss: -0.011745] [G loss: -0.074467] [d1 loss: 0.150502] [d2 loss: 0.128215]  [sq d1 d2: 0.000497]  [num0: 18.000000] [num1 46.000000]
[Epoch 115/500] [Batch 440/676] [D loss: -0.024523] [G loss: -0.061817] [d1 loss: 0.120993] [d2 loss: 0.113170]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 460/676] [D loss: -0.002320] [G loss: -0.073125] [d1 loss: 0.067100] [d2 loss: 0.062772]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 480/676] [D loss: -0.015058] [G loss: -0.060728] [d1 loss: 0.064109] [d2 loss: 0.071304]  [sq d1 d2: 0.000052]  [num0: 17.000000] [num1 47.000000]
[Epoch 115/500] [Batch 500/676] [D loss: -0.006952] [G loss: -0.047097] [d1 loss: 0.070895] [d2 loss: 0.074517]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 520/676] [D loss: -0.014059] [G loss: -0.040043] [d1 loss: 0.107629] [d2 loss: 0.114358]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 540/676] [D loss: -0.013468] [G loss: -0.032823] [d1 loss: 0.075507] [d2 loss: 0.077752]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 115/500] [Batch 560/676] [D loss: -0.019086] [G loss: -0.029153] [d1 loss: 0.089286] [d2 loss: 0.091710]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 580/676] [D loss: -0.016692] [G loss: -0.033378] [d1 loss: 0.074300] [d2 loss: 0.078420]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 115/500] [Batch 600/676] [D loss: -0.020266] [G loss: -0.044689] [d1 loss: 0.084031] [d2 loss: 0.077596]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 115/500] [Batch 620/676] [D loss: -0.015830] [G loss: -0.044914] [d1 loss: 0.183598] [d2 loss: 0.207704]  [sq d1 d2: 0.000581]  [num0: 16.000000] [num1 48.000000]
[Epoch 115/500] [Batch 640/676] [D loss: -0.025186] [G loss: -0.045848] [d1 loss: 0.076597] [d2 loss: 0.067632]  [sq d1 d2: 0.000080]  [num0: 10.000000] [num1 54.000000]
[Epoch 115/500] [Batch 660/676] [D loss: -0.011022] [G loss: -0.054976] [d1 loss: 0.080644] [d2 loss: 0.097066]  [sq d1 d2: 0.000270]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 0/676] [D loss: -0.010757] [G loss: -0.080397] [d1 loss: 0.162506] [d2 loss: 0.142545]  [sq d1 d2: 0.000398]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 20/676] [D loss: -0.013185] [G loss: -0.072510] [d1 loss: 0.135219] [d2 loss: 0.141691]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 40/676] [D loss: -0.010734] [G loss: -0.103160] [d1 loss: 0.093931] [d2 loss: 0.105353]  [sq d1 d2: 0.000130]  [num0: 13.000000] [num1 51.000000]
[Epoch 116/500] [Batch 60/676] [D loss: -0.012975] [G loss: -0.087589] [d1 loss: 0.174069] [d2 loss: 0.145249]  [sq d1 d2: 0.000831]  [num0: 19.000000] [num1 45.000000]
[Epoch 116/500] [Batch 80/676] [D loss: -0.007589] [G loss: -0.103545] [d1 loss: 0.047020] [d2 loss: 0.051334]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 100/676] [D loss: -0.013226] [G loss: -0.101131] [d1 loss: 0.159034] [d2 loss: 0.161732]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 120/676] [D loss: -0.011664] [G loss: -0.109957] [d1 loss: 0.092999] [d2 loss: 0.112776]  [sq d1 d2: 0.000391]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 140/676] [D loss: -0.023912] [G loss: -0.122302] [d1 loss: 0.066924] [d2 loss: 0.079198]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 116/500] [Batch 160/676] [D loss: -0.019899] [G loss: -0.127105] [d1 loss: 0.106995] [d2 loss: 0.104538]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 116/500] [Batch 180/676] [D loss: -0.021320] [G loss: -0.131041] [d1 loss: 0.062756] [d2 loss: 0.047248]  [sq d1 d2: 0.000240]  [num0: 16.000000] [num1 48.000000]
[Epoch 116/500] [Batch 200/676] [D loss: -0.033857] [G loss: -0.128684] [d1 loss: 0.083882] [d2 loss: 0.051422]  [sq d1 d2: 0.001054]  [num0: 11.000000] [num1 53.000000]
[Epoch 116/500] [Batch 220/676] [D loss: -0.011250] [G loss: -0.133214] [d1 loss: 0.125274] [d2 loss: 0.105872]  [sq d1 d2: 0.000376]  [num0: 18.000000] [num1 46.000000]
[Epoch 116/500] [Batch 240/676] [D loss: -0.014526] [G loss: -0.144683] [d1 loss: 0.112438] [d2 loss: 0.096087]  [sq d1 d2: 0.000267]  [num0: 19.000000] [num1 45.000000]
[Epoch 116/500] [Batch 260/676] [D loss: -0.007509] [G loss: -0.141730] [d1 loss: 0.036864] [d2 loss: 0.034056]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 116/500] [Batch 280/676] [D loss: -0.007530] [G loss: -0.142333] [d1 loss: 0.061814] [d2 loss: 0.048887]  [sq d1 d2: 0.000167]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 300/676] [D loss: -0.016967] [G loss: -0.158360] [d1 loss: 0.104651] [d2 loss: 0.056806]  [sq d1 d2: 0.002289]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 320/676] [D loss: -0.017671] [G loss: -0.172812] [d1 loss: 0.182890] [d2 loss: 0.165181]  [sq d1 d2: 0.000314]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 340/676] [D loss: -0.014227] [G loss: -0.167756] [d1 loss: 0.066209] [d2 loss: 0.054694]  [sq d1 d2: 0.000133]  [num0: 18.000000] [num1 46.000000]
[Epoch 116/500] [Batch 360/676] [D loss: -0.011272] [G loss: -0.168228] [d1 loss: 0.055374] [d2 loss: 0.043814]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 116/500] [Batch 380/676] [D loss: 0.000317] [G loss: -0.166208] [d1 loss: 0.164781] [d2 loss: 0.133939]  [sq d1 d2: 0.000951]  [num0: 19.000000] [num1 45.000000]
[Epoch 116/500] [Batch 400/676] [D loss: -0.007599] [G loss: -0.150383] [d1 loss: 0.051493] [d2 loss: 0.044997]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 116/500] [Batch 420/676] [D loss: -0.009383] [G loss: -0.133938] [d1 loss: 0.041050] [d2 loss: 0.054934]  [sq d1 d2: 0.000193]  [num0: 14.000000] [num1 50.000000]
[Epoch 116/500] [Batch 440/676] [D loss: -0.015161] [G loss: -0.130701] [d1 loss: 0.093172] [d2 loss: 0.088769]  [sq d1 d2: 0.000019]  [num0: 13.000000] [num1 51.000000]
[Epoch 116/500] [Batch 460/676] [D loss: -0.021300] [G loss: -0.110996] [d1 loss: 0.074258] [d2 loss: 0.085843]  [sq d1 d2: 0.000134]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 480/676] [D loss: -0.017364] [G loss: -0.090983] [d1 loss: 0.264026] [d2 loss: 0.217859]  [sq d1 d2: 0.002131]  [num0: 20.000000] [num1 44.000000]
[Epoch 116/500] [Batch 500/676] [D loss: -0.019172] [G loss: -0.082378] [d1 loss: 0.091801] [d2 loss: 0.119687]  [sq d1 d2: 0.000778]  [num0: 19.000000] [num1 45.000000]
[Epoch 116/500] [Batch 520/676] [D loss: -0.042915] [G loss: -0.065735] [d1 loss: 0.046674] [d2 loss: 0.037041]  [sq d1 d2: 0.000093]  [num0: 12.000000] [num1 52.000000]
[Epoch 116/500] [Batch 540/676] [D loss: -0.022442] [G loss: -0.078102] [d1 loss: 0.057924] [d2 loss: 0.044404]  [sq d1 d2: 0.000183]  [num0: 16.000000] [num1 48.000000]
[Epoch 116/500] [Batch 560/676] [D loss: -0.008141] [G loss: -0.071931] [d1 loss: 0.065374] [d2 loss: 0.076988]  [sq d1 d2: 0.000135]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 580/676] [D loss: -0.022756] [G loss: -0.075152] [d1 loss: 0.057331] [d2 loss: 0.048942]  [sq d1 d2: 0.000070]  [num0: 17.000000] [num1 47.000000]

[Epoch 116/500] [Batch 600/676] [D loss: 0.006136] [G loss: -0.073166] [d1 loss: 0.052632] [d2 loss: 0.045545]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 116/500] [Batch 620/676] [D loss: -0.008546] [G loss: -0.064221] [d1 loss: 0.122895] [d2 loss: 0.096969]  [sq d1 d2: 0.000672]  [num0: 12.000000] [num1 52.000000]
[Epoch 116/500] [Batch 640/676] [D loss: -0.020617] [G loss: -0.075667] [d1 loss: 0.082455] [d2 loss: 0.077314]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 116/500] [Batch 660/676] [D loss: -0.009085] [G loss: -0.094418] [d1 loss: 0.063768] [d2 loss: 0.046975]  [sq d1 d2: 0.000282]  [num0: 20.000000] [num1 44.000000]
[Epoch 117/500] [Batch 0/676] [D loss: -0.014619] [G loss: -0.091424] [d1 loss: 0.059680] [d2 loss: 0.068797]  [sq d1 d2: 0.000083]  [num0: 21.000000] [num1 43.000000]
[Epoch 117/500] [Batch 20/676] [D loss: -0.009984] [G loss: -0.091789] [d1 loss: 0.089811] [d2 loss: 0.067492]  [sq d1 d2: 0.000498]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 40/676] [D loss: -0.010255] [G loss: -0.098507] [d1 loss: 0.058115] [d2 loss: 0.050356]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 60/676] [D loss: -0.003651] [G loss: -0.098621] [d1 loss: 0.096046] [d2 loss: 0.093154]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 117/500] [Batch 80/676] [D loss: -0.015333] [G loss: -0.103364] [d1 loss: 0.091992] [d2 loss: 0.076076]  [sq d1 d2: 0.000253]  [num0: 17.000000] [num1 47.000000]
[Epoch 117/500] [Batch 100/676] [D loss: -0.017326] [G loss: -0.118765] [d1 loss: 0.055812] [d2 loss: 0.051662]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 117/500] [Batch 120/676] [D loss: -0.015242] [G loss: -0.119764] [d1 loss: 0.109791] [d2 loss: 0.122940]  [sq d1 d2: 0.000173]  [num0: 19.000000] [num1 45.000000]
[Epoch 117/500] [Batch 140/676] [D loss: -0.020305] [G loss: -0.136745] [d1 loss: 0.149755] [d2 loss: 0.170997]  [sq d1 d2: 0.000451]  [num0: 17.000000] [num1 47.000000]
[Epoch 117/500] [Batch 160/676] [D loss: -0.026415] [G loss: -0.149514] [d1 loss: 0.063544] [d2 loss: 0.062165]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 180/676] [D loss: -0.010260] [G loss: -0.153141] [d1 loss: 0.072735] [d2 loss: 0.072581]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 200/676] [D loss: -0.010965] [G loss: -0.163717] [d1 loss: 0.204338] [d2 loss: 0.160082]  [sq d1 d2: 0.001959]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 220/676] [D loss: -0.017397] [G loss: -0.166658] [d1 loss: 0.098216] [d2 loss: 0.090469]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 240/676] [D loss: -0.011385] [G loss: -0.156935] [d1 loss: 0.108926] [d2 loss: 0.089978]  [sq d1 d2: 0.000359]  [num0: 18.000000] [num1 46.000000]
[Epoch 117/500] [Batch 260/676] [D loss: -0.001895] [G loss: -0.176400] [d1 loss: 0.075641] [d2 loss: 0.085292]  [sq d1 d2: 0.000093]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 280/676] [D loss: -0.013796] [G loss: -0.162715] [d1 loss: 0.098510] [d2 loss: 0.127795]  [sq d1 d2: 0.000858]  [num0: 18.000000] [num1 46.000000]
[Epoch 117/500] [Batch 300/676] [D loss: -0.003890] [G loss: -0.148630] [d1 loss: 0.073756] [d2 loss: 0.081826]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 320/676] [D loss: 0.001661] [G loss: -0.140176] [d1 loss: 0.139969] [d2 loss: 0.126604]  [sq d1 d2: 0.000179]  [num0: 17.000000] [num1 47.000000]
[Epoch 117/500] [Batch 340/676] [D loss: -0.013686] [G loss: -0.128062] [d1 loss: 0.055188] [d2 loss: 0.067177]  [sq d1 d2: 0.000144]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 360/676] [D loss: -0.009612] [G loss: -0.113075] [d1 loss: 0.111330] [d2 loss: 0.098333]  [sq d1 d2: 0.000169]  [num0: 18.000000] [num1 46.000000]
[Epoch 117/500] [Batch 380/676] [D loss: -0.010244] [G loss: -0.101890] [d1 loss: 0.109845] [d2 loss: 0.123327]  [sq d1 d2: 0.000182]  [num0: 18.000000] [num1 46.000000]
[Epoch 117/500] [Batch 400/676] [D loss: -0.016282] [G loss: -0.101009] [d1 loss: 0.113080] [d2 loss: 0.112754]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 117/500] [Batch 420/676] [D loss: -0.025798] [G loss: -0.107733] [d1 loss: 0.107368] [d2 loss: 0.120181]  [sq d1 d2: 0.000164]  [num0: 20.000000] [num1 44.000000]
[Epoch 117/500] [Batch 440/676] [D loss: -0.013218] [G loss: -0.096856] [d1 loss: 0.093992] [d2 loss: 0.076580]  [sq d1 d2: 0.000303]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 460/676] [D loss: -0.004801] [G loss: -0.109005] [d1 loss: 0.046557] [d2 loss: 0.054249]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 117/500] [Batch 480/676] [D loss: 0.004029] [G loss: -0.101851] [d1 loss: 0.167505] [d2 loss: 0.121832]  [sq d1 d2: 0.002086]  [num0: 12.000000] [num1 52.000000]
[Epoch 117/500] [Batch 500/676] [D loss: -0.015228] [G loss: -0.102845] [d1 loss: 0.121062] [d2 loss: 0.066708]  [sq d1 d2: 0.002954]  [num0: 18.000000] [num1 46.000000]
[Epoch 117/500] [Batch 520/676] [D loss: -0.013894] [G loss: -0.091267] [d1 loss: 0.038317] [d2 loss: 0.037835]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 117/500] [Batch 540/676] [D loss: -0.012875] [G loss: -0.095971] [d1 loss: 0.093299] [d2 loss: 0.110908]  [sq d1 d2: 0.000310]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 560/676] [D loss: -0.006574] [G loss: -0.107046] [d1 loss: 0.119767] [d2 loss: 0.103517]  [sq d1 d2: 0.000264]  [num0: 17.000000] [num1 47.000000]
[Epoch 117/500] [Batch 580/676] [D loss: -0.013275] [G loss: -0.090851] [d1 loss: 0.111686] [d2 loss: 0.127548]  [sq d1 d2: 0.000252]  [num0: 14.000000] [num1 50.000000]
[Epoch 117/500] [Batch 600/676] [D loss: -0.010040] [G loss: -0.088456] [d1 loss: 0.077616] [d2 loss: 0.064768]  [sq d1 d2: 0.000165]  [num0: 13.000000] [num1 51.000000]
[Epoch 117/500] [Batch 620/676] [D loss: -0.011436] [G loss: -0.087584] [d1 loss: 0.070733] [d2 loss: 0.068348]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 117/500] [Batch 640/676] [D loss: -0.013942] [G loss: -0.086770] [d1 loss: 0.112195] [d2 loss: 0.115910]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 117/500] [Batch 660/676] [D loss: -0.012124] [G loss: -0.076535] [d1 loss: 0.059659] [d2 loss: 0.044492]  [sq d1 d2: 0.000230]  [num0: 20.000000] [num1 44.000000]
[Epoch 118/500] [Batch 0/676] [D loss: -0.007755] [G loss: -0.066742] [d1 loss: 0.060716] [d2 loss: 0.043616]  [sq d1 d2: 0.000292]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 20/676] [D loss: -0.014595] [G loss: -0.064688] [d1 loss: 0.059418] [d2 loss: 0.055309]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 40/676] [D loss: -0.004301] [G loss: -0.063666] [d1 loss: 0.047854] [d2 loss: 0.062420]  [sq d1 d2: 0.000212]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 60/676] [D loss: -0.008984] [G loss: -0.070966] [d1 loss: 0.119261] [d2 loss: 0.119494]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 118/500] [Batch 80/676] [D loss: -0.001170] [G loss: -0.077385] [d1 loss: 0.040258] [d2 loss: 0.048078]  [sq d1 d2: 0.000061]  [num0: 13.000000] [num1 51.000000]
[Epoch 118/500] [Batch 100/676] [D loss: -0.004707] [G loss: -0.080991] [d1 loss: 0.038117] [d2 loss: 0.043750]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 120/676] [D loss: -0.006144] [G loss: -0.087384] [d1 loss: 0.062316] [d2 loss: 0.052565]  [sq d1 d2: 0.000095]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 140/676] [D loss: -0.013168] [G loss: -0.087735] [d1 loss: 0.074246] [d2 loss: 0.080451]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 160/676] [D loss: -0.004608] [G loss: -0.090865] [d1 loss: 0.038796] [d2 loss: 0.030272]  [sq d1 d2: 0.000073]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 180/676] [D loss: -0.005237] [G loss: -0.091923] [d1 loss: 0.079838] [d2 loss: 0.077296]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 200/676] [D loss: -0.018703] [G loss: -0.099123] [d1 loss: 0.114680] [d2 loss: 0.094538]  [sq d1 d2: 0.000406]  [num0: 14.000000] [num1 50.000000]

[Epoch 118/500] [Batch 220/676] [D loss: -0.006953] [G loss: -0.086260] [d1 loss: 0.063805] [d2 loss: 0.079841]  [sq d1 d2: 0.000257]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 240/676] [D loss: -0.015707] [G loss: -0.078097] [d1 loss: 0.049054] [d2 loss: 0.059262]  [sq d1 d2: 0.000104]  [num0: 18.000000] [num1 46.000000]
[Epoch 118/500] [Batch 260/676] [D loss: -0.012186] [G loss: -0.091510] [d1 loss: 0.045406] [d2 loss: 0.040200]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 280/676] [D loss: -0.011113] [G loss: -0.099479] [d1 loss: 0.040208] [d2 loss: 0.046703]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 300/676] [D loss: -0.018690] [G loss: -0.108650] [d1 loss: 0.070716] [d2 loss: 0.054168]  [sq d1 d2: 0.000274]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 320/676] [D loss: -0.015753] [G loss: -0.104557] [d1 loss: 0.078046] [d2 loss: 0.069281]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 340/676] [D loss: -0.012457] [G loss: -0.105745] [d1 loss: 0.064090] [d2 loss: 0.068907]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 360/676] [D loss: -0.015885] [G loss: -0.116072] [d1 loss: 0.063227] [d2 loss: 0.048531]  [sq d1 d2: 0.000216]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 380/676] [D loss: -0.011936] [G loss: -0.114401] [d1 loss: 0.021035] [d2 loss: 0.012031]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 400/676] [D loss: -0.004097] [G loss: -0.125094] [d1 loss: 0.099850] [d2 loss: 0.092680]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 420/676] [D loss: -0.005530] [G loss: -0.109498] [d1 loss: 0.073784] [d2 loss: 0.070377]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 440/676] [D loss: -0.008249] [G loss: -0.112764] [d1 loss: 0.078103] [d2 loss: 0.076243]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 118/500] [Batch 460/676] [D loss: -0.005867] [G loss: -0.108808] [d1 loss: 0.104082] [d2 loss: 0.097401]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 480/676] [D loss: -0.009850] [G loss: -0.109040] [d1 loss: 0.088011] [d2 loss: 0.080221]  [sq d1 d2: 0.000061]  [num0: 12.000000] [num1 52.000000]
[Epoch 118/500] [Batch 500/676] [D loss: -0.013852] [G loss: -0.105282] [d1 loss: 0.055849] [d2 loss: 0.103377]  [sq d1 d2: 0.002259]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 520/676] [D loss: -0.011704] [G loss: -0.105294] [d1 loss: 0.194732] [d2 loss: 0.168926]  [sq d1 d2: 0.000666]  [num0: 16.000000] [num1 48.000000]
[Epoch 118/500] [Batch 540/676] [D loss: -0.009855] [G loss: -0.104690] [d1 loss: 0.025756] [d2 loss: 0.037577]  [sq d1 d2: 0.000140]  [num0: 14.000000] [num1 50.000000]
[Epoch 118/500] [Batch 560/676] [D loss: -0.010980] [G loss: -0.086058] [d1 loss: 0.088303] [d2 loss: 0.081765]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 580/676] [D loss: -0.011014] [G loss: -0.091303] [d1 loss: 0.027853] [d2 loss: 0.027345]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 600/676] [D loss: -0.011118] [G loss: -0.104747] [d1 loss: 0.056373] [d2 loss: 0.053994]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 118/500] [Batch 620/676] [D loss: -0.014666] [G loss: -0.108542] [d1 loss: 0.117181] [d2 loss: 0.119292]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 118/500] [Batch 640/676] [D loss: -0.006438] [G loss: -0.111405] [d1 loss: 0.082154] [d2 loss: 0.081339]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 118/500] [Batch 660/676] [D loss: -0.011194] [G loss: -0.120085] [d1 loss: 0.074071] [d2 loss: 0.061792]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 0/676] [D loss: -0.005240] [G loss: -0.123729] [d1 loss: 0.069714] [d2 loss: 0.065936]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 119/500] [Batch 20/676] [D loss: -0.002714] [G loss: -0.121072] [d1 loss: 0.080049] [d2 loss: 0.091033]  [sq d1 d2: 0.000121]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 40/676] [D loss: -0.008170] [G loss: -0.125688] [d1 loss: 0.111228] [d2 loss: 0.120580]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 60/676] [D loss: -0.006497] [G loss: -0.122787] [d1 loss: 0.084625] [d2 loss: 0.071144]  [sq d1 d2: 0.000182]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 80/676] [D loss: -0.007160] [G loss: -0.125564] [d1 loss: 0.058611] [d2 loss: 0.069809]  [sq d1 d2: 0.000125]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 100/676] [D loss: -0.007849] [G loss: -0.123959] [d1 loss: 0.068873] [d2 loss: 0.073106]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 119/500] [Batch 120/676] [D loss: -0.006053] [G loss: -0.127172] [d1 loss: 0.043868] [d2 loss: 0.048702]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 140/676] [D loss: -0.017457] [G loss: -0.130575] [d1 loss: 0.043772] [d2 loss: 0.038629]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 119/500] [Batch 160/676] [D loss: -0.016003] [G loss: -0.116522] [d1 loss: 0.087016] [d2 loss: 0.098295]  [sq d1 d2: 0.000127]  [num0: 14.000000] [num1 50.000000]
[Epoch 119/500] [Batch 180/676] [D loss: -0.004136] [G loss: -0.113028] [d1 loss: 0.074909] [d2 loss: 0.073832]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 200/676] [D loss: -0.006085] [G loss: -0.098941] [d1 loss: 0.085479] [d2 loss: 0.073381]  [sq d1 d2: 0.000146]  [num0: 13.000000] [num1 51.000000]
[Epoch 119/500] [Batch 220/676] [D loss: -0.008777] [G loss: -0.095189] [d1 loss: 0.040144] [d2 loss: 0.063046]  [sq d1 d2: 0.000525]  [num0: 19.000000] [num1 45.000000]
[Epoch 119/500] [Batch 240/676] [D loss: -0.008704] [G loss: -0.109532] [d1 loss: 0.086092] [d2 loss: 0.094622]  [sq d1 d2: 0.000073]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 260/676] [D loss: 0.002241] [G loss: -0.105883] [d1 loss: 0.044066] [d2 loss: 0.050345]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 280/676] [D loss: -0.006344] [G loss: -0.111387] [d1 loss: 0.079169] [d2 loss: 0.074252]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 119/500] [Batch 300/676] [D loss: -0.006475] [G loss: -0.106533] [d1 loss: 0.065786] [d2 loss: 0.089890]  [sq d1 d2: 0.000581]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 320/676] [D loss: -0.014922] [G loss: -0.116608] [d1 loss: 0.031836] [d2 loss: 0.025320]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 119/500] [Batch 340/676] [D loss: -0.006099] [G loss: -0.107341] [d1 loss: 0.042702] [d2 loss: 0.033050]  [sq d1 d2: 0.000093]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 360/676] [D loss: -0.011223] [G loss: -0.114060] [d1 loss: 0.049835] [d2 loss: 0.059558]  [sq d1 d2: 0.000095]  [num0: 14.000000] [num1 50.000000]
[Epoch 119/500] [Batch 380/676] [D loss: -0.006223] [G loss: -0.119698] [d1 loss: 0.078963] [d2 loss: 0.093859]  [sq d1 d2: 0.000222]  [num0: 13.000000] [num1 51.000000]
[Epoch 119/500] [Batch 400/676] [D loss: -0.013572] [G loss: -0.129406] [d1 loss: 0.062616] [d2 loss: 0.080064]  [sq d1 d2: 0.000304]  [num0: 12.000000] [num1 52.000000]
[Epoch 119/500] [Batch 420/676] [D loss: -0.012285] [G loss: -0.110604] [d1 loss: 0.107025] [d2 loss: 0.103453]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 440/676] [D loss: -0.009669] [G loss: -0.110751] [d1 loss: 0.083633] [d2 loss: 0.076011]  [sq d1 d2: 0.000058]  [num0: 20.000000] [num1 44.000000]
[Epoch 119/500] [Batch 460/676] [D loss: 0.001672] [G loss: -0.107768] [d1 loss: 0.049414] [d2 loss: 0.039920]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 480/676] [D loss: -0.000339] [G loss: -0.105565] [d1 loss: 0.055435] [d2 loss: 0.069000]  [sq d1 d2: 0.000184]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 500/676] [D loss: -0.014896] [G loss: -0.111355] [d1 loss: 0.111918] [d2 loss: 0.116299]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 520/676] [D loss: -0.012420] [G loss: -0.114879] [d1 loss: 0.042067] [d2 loss: 0.046192]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]

[Epoch 119/500] [Batch 540/676] [D loss: -0.016201] [G loss: -0.122523] [d1 loss: 0.119353] [d2 loss: 0.099318]  [sq d1 d2: 0.000401]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 560/676] [D loss: -0.007323] [G loss: -0.122122] [d1 loss: 0.041955] [d2 loss: 0.039276]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 119/500] [Batch 580/676] [D loss: -0.006951] [G loss: -0.118262] [d1 loss: 0.107291] [d2 loss: 0.110019]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 600/676] [D loss: -0.011701] [G loss: -0.113058] [d1 loss: 0.079425] [d2 loss: 0.092940]  [sq d1 d2: 0.000183]  [num0: 18.000000] [num1 46.000000]
[Epoch 119/500] [Batch 620/676] [D loss: -0.007104] [G loss: -0.116571] [d1 loss: 0.044585] [d2 loss: 0.053954]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 640/676] [D loss: -0.006611] [G loss: -0.106884] [d1 loss: 0.086649] [d2 loss: 0.098406]  [sq d1 d2: 0.000138]  [num0: 16.000000] [num1 48.000000]
[Epoch 119/500] [Batch 660/676] [D loss: -0.006270] [G loss: -0.101457] [d1 loss: 0.076502] [d2 loss: 0.104019]  [sq d1 d2: 0.000757]  [num0: 18.000000] [num1 46.000000]
[Epoch 120/500] [Batch 0/676] [D loss: -0.006321] [G loss: -0.104336] [d1 loss: 0.062836] [d2 loss: 0.082310]  [sq d1 d2: 0.000379]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 20/676] [D loss: -0.013845] [G loss: -0.090290] [d1 loss: 0.088482] [d2 loss: 0.092059]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 40/676] [D loss: -0.008919] [G loss: -0.073532] [d1 loss: 0.048233] [d2 loss: 0.067168]  [sq d1 d2: 0.000359]  [num0: 18.000000] [num1 46.000000]
[Epoch 120/500] [Batch 60/676] [D loss: -0.009811] [G loss: -0.070617] [d1 loss: 0.097700] [d2 loss: 0.092265]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 120/500] [Batch 80/676] [D loss: -0.009008] [G loss: -0.070445] [d1 loss: 0.059001] [d2 loss: 0.072839]  [sq d1 d2: 0.000191]  [num0: 16.000000] [num1 48.000000]
[Epoch 120/500] [Batch 100/676] [D loss: -0.005334] [G loss: -0.070192] [d1 loss: 0.090410] [d2 loss: 0.067615]  [sq d1 d2: 0.000520]  [num0: 16.000000] [num1 48.000000]
[Epoch 120/500] [Batch 120/676] [D loss: -0.005930] [G loss: -0.064644] [d1 loss: 0.092443] [d2 loss: 0.077426]  [sq d1 d2: 0.000226]  [num0: 11.000000] [num1 53.000000]
[Epoch 120/500] [Batch 140/676] [D loss: -0.009640] [G loss: -0.069204] [d1 loss: 0.082218] [d2 loss: 0.065191]  [sq d1 d2: 0.000290]  [num0: 21.000000] [num1 43.000000]
[Epoch 120/500] [Batch 160/676] [D loss: -0.006070] [G loss: -0.083324] [d1 loss: 0.072677] [d2 loss: 0.061010]  [sq d1 d2: 0.000136]  [num0: 20.000000] [num1 44.000000]
[Epoch 120/500] [Batch 180/676] [D loss: -0.018439] [G loss: -0.084241] [d1 loss: 0.053738] [d2 loss: 0.043911]  [sq d1 d2: 0.000097]  [num0: 13.000000] [num1 51.000000]
[Epoch 120/500] [Batch 200/676] [D loss: -0.000260] [G loss: -0.070828] [d1 loss: 0.026159] [d2 loss: 0.028145]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 220/676] [D loss: -0.006588] [G loss: -0.076440] [d1 loss: 0.052259] [d2 loss: 0.056730]  [sq d1 d2: 0.000020]  [num0: 10.000000] [num1 54.000000]
[Epoch 120/500] [Batch 240/676] [D loss: 0.000000] [G loss: -0.087235] [d1 loss: 0.034348] [d2 loss: 0.026688]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 120/500] [Batch 260/676] [D loss: -0.001904] [G loss: -0.083281] [d1 loss: 0.030308] [d2 loss: 0.029666]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 280/676] [D loss: -0.006617] [G loss: -0.077213] [d1 loss: 0.060274] [d2 loss: 0.047560]  [sq d1 d2: 0.000162]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 300/676] [D loss: -0.010152] [G loss: -0.077572] [d1 loss: 0.055058] [d2 loss: 0.063099]  [sq d1 d2: 0.000065]  [num0: 14.000000] [num1 50.000000]
[Epoch 120/500] [Batch 320/676] [D loss: -0.009251] [G loss: -0.099453] [d1 loss: 0.068295] [d2 loss: 0.103977]  [sq d1 d2: 0.001273]  [num0: 14.000000] [num1 50.000000]
[Epoch 120/500] [Batch 340/676] [D loss: -0.004944] [G loss: -0.085595] [d1 loss: 0.102290] [d2 loss: 0.105475]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 120/500] [Batch 360/676] [D loss: -0.012264] [G loss: -0.083880] [d1 loss: 0.046624] [d2 loss: 0.051830]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 120/500] [Batch 380/676] [D loss: -0.007734] [G loss: -0.073236] [d1 loss: 0.060767] [d2 loss: 0.070864]  [sq d1 d2: 0.000102]  [num0: 19.000000] [num1 45.000000]
[Epoch 120/500] [Batch 400/676] [D loss: -0.018009] [G loss: -0.083006] [d1 loss: 0.108880] [d2 loss: 0.103547]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 120/500] [Batch 420/676] [D loss: -0.013906] [G loss: -0.087170] [d1 loss: 0.076947] [d2 loss: 0.075415]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 120/500] [Batch 440/676] [D loss: -0.010507] [G loss: -0.108667] [d1 loss: 0.038302] [d2 loss: 0.038510]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 120/500] [Batch 460/676] [D loss: -0.013730] [G loss: -0.091019] [d1 loss: 0.076163] [d2 loss: 0.073409]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 120/500] [Batch 480/676] [D loss: -0.005549] [G loss: -0.098080] [d1 loss: 0.050298] [d2 loss: 0.056579]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 120/500] [Batch 500/676] [D loss: -0.008002] [G loss: -0.098544] [d1 loss: 0.083586] [d2 loss: 0.126372]  [sq d1 d2: 0.001831]  [num0: 21.000000] [num1 43.000000]
[Epoch 120/500] [Batch 520/676] [D loss: -0.006360] [G loss: -0.098917] [d1 loss: 0.036330] [d2 loss: 0.037553]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 540/676] [D loss: -0.004750] [G loss: -0.089521] [d1 loss: 0.055673] [d2 loss: 0.056668]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 120/500] [Batch 560/676] [D loss: -0.007402] [G loss: -0.093869] [d1 loss: 0.067658] [d2 loss: 0.064678]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 120/500] [Batch 580/676] [D loss: -0.007565] [G loss: -0.094907] [d1 loss: 0.111260] [d2 loss: 0.157707]  [sq d1 d2: 0.002157]  [num0: 12.000000] [num1 52.000000]
[Epoch 120/500] [Batch 600/676] [D loss: -0.011348] [G loss: -0.076144] [d1 loss: 0.052967] [d2 loss: 0.046681]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 120/500] [Batch 620/676] [D loss: -0.007089] [G loss: -0.079245] [d1 loss: 0.077737] [d2 loss: 0.080630]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 120/500] [Batch 640/676] [D loss: -0.010624] [G loss: -0.072968] [d1 loss: 0.059092] [d2 loss: 0.064627]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 120/500] [Batch 660/676] [D loss: -0.013922] [G loss: -0.074504] [d1 loss: 0.030535] [d2 loss: 0.034995]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 121/500] [Batch 0/676] [D loss: -0.010540] [G loss: -0.083904] [d1 loss: 0.076614] [d2 loss: 0.063219]  [sq d1 d2: 0.000179]  [num0: 18.000000] [num1 46.000000]
[Epoch 121/500] [Batch 20/676] [D loss: -0.008556] [G loss: -0.092023] [d1 loss: 0.076341] [d2 loss: 0.059350]  [sq d1 d2: 0.000289]  [num0: 13.000000] [num1 51.000000]
[Epoch 121/500] [Batch 40/676] [D loss: -0.006379] [G loss: -0.096431] [d1 loss: 0.026763] [d2 loss: 0.029890]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 121/500] [Batch 60/676] [D loss: -0.016695] [G loss: -0.103647] [d1 loss: 0.074792] [d2 loss: 0.061473]  [sq d1 d2: 0.000177]  [num0: 12.000000] [num1 52.000000]
[Epoch 121/500] [Batch 80/676] [D loss: -0.007397] [G loss: -0.097702] [d1 loss: 0.097631] [d2 loss: 0.116886]  [sq d1 d2: 0.000371]  [num0: 11.000000] [num1 53.000000]
[Epoch 121/500] [Batch 100/676] [D loss: -0.013440] [G loss: -0.103377] [d1 loss: 0.078424] [d2 loss: 0.056830]  [sq d1 d2: 0.000466]  [num0: 15.000000] [num1 49.000000]
[Epoch 121/500] [Batch 120/676] [D loss: -0.006768] [G loss: -0.107368] [d1 loss: 0.172708] [d2 loss: 0.155656]  [sq d1 d2: 0.000291]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 140/676] [D loss: -0.005396] [G loss: -0.100950] [d1 loss: 0.071675] [d2 loss: 0.086158]  [sq d1 d2: 0.000210]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 160/676] [D loss: -0.007953] [G loss: -0.105648] [d1 loss: 0.071626] [d2 loss: 0.055305]  [sq d1 d2: 0.000266]  [num0: 18.000000] [num1 46.000000]

[Epoch 121/500] [Batch 180/676] [D loss: -0.009069] [G loss: -0.095909] [d1 loss: 0.066424] [d2 loss: 0.073806]  [sq d1 d2: 0.000054]  [num0: 13.000000] [num1 51.000000]
[Epoch 121/500] [Batch 200/676] [D loss: -0.005130] [G loss: -0.103548] [d1 loss: 0.074950] [d2 loss: 0.105080]  [sq d1 d2: 0.000908]  [num0: 18.000000] [num1 46.000000]
[Epoch 121/500] [Batch 220/676] [D loss: -0.014018] [G loss: -0.095363] [d1 loss: 0.043044] [d2 loss: 0.040656]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 121/500] [Batch 240/676] [D loss: -0.015218] [G loss: -0.094603] [d1 loss: 0.105328] [d2 loss: 0.114613]  [sq d1 d2: 0.000086]  [num0: 17.000000] [num1 47.000000]
[Epoch 121/500] [Batch 260/676] [D loss: -0.014672] [G loss: -0.099515] [d1 loss: 0.079825] [d2 loss: 0.077067]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 121/500] [Batch 280/676] [D loss: -0.011542] [G loss: -0.100208] [d1 loss: 0.076196] [d2 loss: 0.057180]  [sq d1 d2: 0.000362]  [num0: 17.000000] [num1 47.000000]
[Epoch 121/500] [Batch 300/676] [D loss: -0.007055] [G loss: -0.109734] [d1 loss: 0.035760] [d2 loss: 0.057264]  [sq d1 d2: 0.000462]  [num0: 17.000000] [num1 47.000000]
[Epoch 121/500] [Batch 320/676] [D loss: -0.015791] [G loss: -0.105009] [d1 loss: 0.089870] [d2 loss: 0.122152]  [sq d1 d2: 0.001042]  [num0: 19.000000] [num1 45.000000]
[Epoch 121/500] [Batch 340/676] [D loss: -0.005267] [G loss: -0.115583] [d1 loss: 0.089948] [d2 loss: 0.117835]  [sq d1 d2: 0.000778]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 360/676] [D loss: -0.001476] [G loss: -0.110330] [d1 loss: 0.041204] [d2 loss: 0.037844]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 121/500] [Batch 380/676] [D loss: 0.004677] [G loss: -0.107230] [d1 loss: 0.122379] [d2 loss: 0.122344]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 121/500] [Batch 400/676] [D loss: -0.008506] [G loss: -0.107356] [d1 loss: 0.063463] [d2 loss: 0.062005]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 420/676] [D loss: -0.010421] [G loss: -0.096598] [d1 loss: 0.121435] [d2 loss: 0.130643]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 121/500] [Batch 440/676] [D loss: -0.007164] [G loss: -0.089915] [d1 loss: 0.057284] [d2 loss: 0.058606]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 121/500] [Batch 460/676] [D loss: -0.014577] [G loss: -0.083169] [d1 loss: 0.090687] [d2 loss: 0.108040]  [sq d1 d2: 0.000301]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 480/676] [D loss: -0.013838] [G loss: -0.079066] [d1 loss: 0.032482] [d2 loss: 0.034863]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 500/676] [D loss: -0.008886] [G loss: -0.086027] [d1 loss: 0.041436] [d2 loss: 0.045125]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 121/500] [Batch 520/676] [D loss: -0.011720] [G loss: -0.085356] [d1 loss: 0.129024] [d2 loss: 0.138135]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 121/500] [Batch 540/676] [D loss: -0.011409] [G loss: -0.096570] [d1 loss: 0.082308] [d2 loss: 0.091065]  [sq d1 d2: 0.000077]  [num0: 17.000000] [num1 47.000000]
[Epoch 121/500] [Batch 560/676] [D loss: -0.011776] [G loss: -0.112542] [d1 loss: 0.056912] [d2 loss: 0.046276]  [sq d1 d2: 0.000113]  [num0: 18.000000] [num1 46.000000]
[Epoch 121/500] [Batch 580/676] [D loss: -0.015489] [G loss: -0.114935] [d1 loss: 0.066284] [d2 loss: 0.070402]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 121/500] [Batch 600/676] [D loss: 0.000911] [G loss: -0.132969] [d1 loss: 0.081196] [d2 loss: 0.078623]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 121/500] [Batch 620/676] [D loss: -0.013909] [G loss: -0.151535] [d1 loss: 0.050526] [d2 loss: 0.048904]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 121/500] [Batch 640/676] [D loss: 0.006713] [G loss: -0.149017] [d1 loss: 0.071687] [d2 loss: 0.074018]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 121/500] [Batch 660/676] [D loss: -0.007494] [G loss: -0.146208] [d1 loss: 0.041909] [d2 loss: 0.044635]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 0/676] [D loss: -0.011610] [G loss: -0.171867] [d1 loss: 0.047648] [d2 loss: 0.053406]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 20/676] [D loss: -0.026150] [G loss: -0.170212] [d1 loss: 0.062774] [d2 loss: 0.051653]  [sq d1 d2: 0.000124]  [num0: 12.000000] [num1 52.000000]
[Epoch 122/500] [Batch 40/676] [D loss: -0.005298] [G loss: -0.161681] [d1 loss: 0.039370] [d2 loss: 0.040277]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 60/676] [D loss: 0.001491] [G loss: -0.170062] [d1 loss: 0.098859] [d2 loss: 0.123489]  [sq d1 d2: 0.000607]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 80/676] [D loss: -0.003767] [G loss: -0.150967] [d1 loss: 0.066353] [d2 loss: 0.086415]  [sq d1 d2: 0.000402]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 100/676] [D loss: -0.014992] [G loss: -0.146637] [d1 loss: 0.109765] [d2 loss: 0.115685]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 120/676] [D loss: -0.015213] [G loss: -0.149723] [d1 loss: 0.026596] [d2 loss: 0.028493]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 122/500] [Batch 140/676] [D loss: -0.010393] [G loss: -0.138479] [d1 loss: 0.046059] [d2 loss: 0.043425]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 122/500] [Batch 160/676] [D loss: -0.008375] [G loss: -0.127050] [d1 loss: 0.060354] [d2 loss: 0.051389]  [sq d1 d2: 0.000080]  [num0: 20.000000] [num1 44.000000]
[Epoch 122/500] [Batch 180/676] [D loss: -0.001918] [G loss: -0.109629] [d1 loss: 0.052128] [d2 loss: 0.046620]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 200/676] [D loss: -0.007588] [G loss: -0.095581] [d1 loss: 0.068882] [d2 loss: 0.066179]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 122/500] [Batch 220/676] [D loss: -0.014599] [G loss: -0.090591] [d1 loss: 0.145103] [d2 loss: 0.154643]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 240/676] [D loss: -0.021778] [G loss: -0.083040] [d1 loss: 0.156160] [d2 loss: 0.102529]  [sq d1 d2: 0.002876]  [num0: 13.000000] [num1 51.000000]
[Epoch 122/500] [Batch 260/676] [D loss: -0.013683] [G loss: -0.079081] [d1 loss: 0.026318] [d2 loss: 0.025035]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 122/500] [Batch 280/676] [D loss: -0.002434] [G loss: -0.077923] [d1 loss: 0.072608] [d2 loss: 0.064729]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 300/676] [D loss: -0.013314] [G loss: -0.082547] [d1 loss: 0.069293] [d2 loss: 0.073002]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 122/500] [Batch 320/676] [D loss: -0.010846] [G loss: -0.085064] [d1 loss: 0.026627] [d2 loss: 0.024037]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 340/676] [D loss: -0.012991] [G loss: -0.081059] [d1 loss: 0.046350] [d2 loss: 0.025296]  [sq d1 d2: 0.000443]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 360/676] [D loss: -0.013170] [G loss: -0.075646] [d1 loss: 0.036692] [d2 loss: 0.041193]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 380/676] [D loss: -0.020298] [G loss: -0.075660] [d1 loss: 0.052628] [d2 loss: 0.047565]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 122/500] [Batch 400/676] [D loss: -0.002782] [G loss: -0.069670] [d1 loss: 0.055670] [d2 loss: 0.094980]  [sq d1 d2: 0.001545]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 420/676] [D loss: 0.003867] [G loss: -0.086522] [d1 loss: 0.072540] [d2 loss: 0.061924]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 122/500] [Batch 440/676] [D loss: -0.010409] [G loss: -0.086019] [d1 loss: 0.070201] [d2 loss: 0.066395]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 122/500] [Batch 460/676] [D loss: -0.009491] [G loss: -0.081354] [d1 loss: 0.099995] [d2 loss: 0.088200]  [sq d1 d2: 0.000139]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 480/676] [D loss: -0.010321] [G loss: -0.081862] [d1 loss: 0.080632] [d2 loss: 0.063676]  [sq d1 d2: 0.000288]  [num0: 16.000000] [num1 48.000000]

[Epoch 122/500] [Batch 500/676] [D loss: -0.012474] [G loss: -0.076413] [d1 loss: 0.057052] [d2 loss: 0.046679]  [sq d1 d2: 0.000108]  [num0: 21.000000] [num1 43.000000]
[Epoch 122/500] [Batch 520/676] [D loss: -0.021660] [G loss: -0.081274] [d1 loss: 0.063310] [d2 loss: 0.058561]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 122/500] [Batch 540/676] [D loss: -0.016908] [G loss: -0.072517] [d1 loss: 0.044451] [d2 loss: 0.045314]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 560/676] [D loss: -0.014422] [G loss: -0.080501] [d1 loss: 0.084127] [d2 loss: 0.048746]  [sq d1 d2: 0.001252]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 580/676] [D loss: -0.004311] [G loss: -0.065779] [d1 loss: 0.038540] [d2 loss: 0.037037]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 600/676] [D loss: 0.000598] [G loss: -0.064222] [d1 loss: 0.099446] [d2 loss: 0.130409]  [sq d1 d2: 0.000959]  [num0: 14.000000] [num1 50.000000]
[Epoch 122/500] [Batch 620/676] [D loss: -0.012798] [G loss: -0.036812] [d1 loss: 0.036291] [d2 loss: 0.044020]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 122/500] [Batch 640/676] [D loss: -0.012307] [G loss: -0.043245] [d1 loss: 0.044120] [d2 loss: 0.042222]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 122/500] [Batch 660/676] [D loss: -0.015922] [G loss: -0.042054] [d1 loss: 0.028704] [d2 loss: 0.044501]  [sq d1 d2: 0.000250]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 0/676] [D loss: -0.017658] [G loss: -0.030170] [d1 loss: 0.061693] [d2 loss: 0.060750]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 20/676] [D loss: 0.002874] [G loss: -0.017592] [d1 loss: 0.097861] [d2 loss: 0.111039]  [sq d1 d2: 0.000174]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 40/676] [D loss: -0.004344] [G loss: -0.010916] [d1 loss: 0.088282] [d2 loss: 0.095059]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 123/500] [Batch 60/676] [D loss: -0.034390] [G loss: -0.000148] [d1 loss: 0.086131] [d2 loss: 0.065811]  [sq d1 d2: 0.000413]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 80/676] [D loss: 0.006278] [G loss: -0.010621] [d1 loss: 0.082600] [d2 loss: 0.077760]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 123/500] [Batch 100/676] [D loss: -0.016942] [G loss: -0.024086] [d1 loss: 0.044754] [d2 loss: 0.036376]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 123/500] [Batch 120/676] [D loss: -0.014132] [G loss: -0.043769] [d1 loss: 0.074484] [d2 loss: 0.078636]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 123/500] [Batch 140/676] [D loss: -0.003527] [G loss: -0.042380] [d1 loss: 0.100356] [d2 loss: 0.138134]  [sq d1 d2: 0.001427]  [num0: 12.000000] [num1 52.000000]
[Epoch 123/500] [Batch 160/676] [D loss: -0.003328] [G loss: -0.054370] [d1 loss: 0.055111] [d2 loss: 0.037996]  [sq d1 d2: 0.000293]  [num0: 15.000000] [num1 49.000000]
[Epoch 123/500] [Batch 180/676] [D loss: -0.013108] [G loss: -0.050159] [d1 loss: 0.033541] [d2 loss: 0.034287]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 123/500] [Batch 200/676] [D loss: -0.009047] [G loss: -0.054200] [d1 loss: 0.053361] [d2 loss: 0.055523]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 220/676] [D loss: -0.014291] [G loss: -0.063796] [d1 loss: 0.043378] [d2 loss: 0.060908]  [sq d1 d2: 0.000307]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 240/676] [D loss: -0.016443] [G loss: -0.089943] [d1 loss: 0.070097] [d2 loss: 0.075464]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 260/676] [D loss: -0.012993] [G loss: -0.118831] [d1 loss: 0.029179] [d2 loss: 0.034395]  [sq d1 d2: 0.000027]  [num0: 22.000000] [num1 42.000000]
[Epoch 123/500] [Batch 280/676] [D loss: -0.015049] [G loss: -0.153063] [d1 loss: 0.043458] [d2 loss: 0.062049]  [sq d1 d2: 0.000346]  [num0: 17.000000] [num1 47.000000]
[Epoch 123/500] [Batch 300/676] [D loss: -0.022236] [G loss: -0.167030] [d1 loss: 0.020945] [d2 loss: 0.020096]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 320/676] [D loss: -0.011432] [G loss: -0.171536] [d1 loss: 0.110064] [d2 loss: 0.110776]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 123/500] [Batch 340/676] [D loss: -0.015721] [G loss: -0.141935] [d1 loss: 0.103652] [d2 loss: 0.102150]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 360/676] [D loss: -0.002203] [G loss: -0.171058] [d1 loss: 0.037768] [d2 loss: 0.054197]  [sq d1 d2: 0.000270]  [num0: 13.000000] [num1 51.000000]
[Epoch 123/500] [Batch 380/676] [D loss: -0.018942] [G loss: -0.153332] [d1 loss: 0.113695] [d2 loss: 0.120668]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 400/676] [D loss: -0.017365] [G loss: -0.164912] [d1 loss: 0.076321] [d2 loss: 0.099469]  [sq d1 d2: 0.000536]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 420/676] [D loss: -0.011158] [G loss: -0.114422] [d1 loss: 0.107204] [d2 loss: 0.122463]  [sq d1 d2: 0.000233]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 440/676] [D loss: -0.010266] [G loss: -0.128050] [d1 loss: 0.066121] [d2 loss: 0.071185]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 460/676] [D loss: -0.012305] [G loss: -0.093712] [d1 loss: 0.068115] [d2 loss: 0.073918]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 123/500] [Batch 480/676] [D loss: -0.038559] [G loss: -0.124592] [d1 loss: 0.058155] [d2 loss: 0.067734]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 500/676] [D loss: -0.025318] [G loss: -0.121556] [d1 loss: 0.049953] [d2 loss: 0.081313]  [sq d1 d2: 0.000983]  [num0: 18.000000] [num1 46.000000]
[Epoch 123/500] [Batch 520/676] [D loss: -0.024248] [G loss: -0.124551] [d1 loss: 0.124575] [d2 loss: 0.127735]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 123/500] [Batch 540/676] [D loss: -0.010179] [G loss: -0.171179] [d1 loss: 0.077473] [d2 loss: 0.054809]  [sq d1 d2: 0.000514]  [num0: 18.000000] [num1 46.000000]
[Epoch 123/500] [Batch 560/676] [D loss: -0.007947] [G loss: -0.145984] [d1 loss: 0.080831] [d2 loss: 0.066026]  [sq d1 d2: 0.000219]  [num0: 14.000000] [num1 50.000000]
[Epoch 123/500] [Batch 580/676] [D loss: -0.004127] [G loss: -0.155288] [d1 loss: 0.089620] [d2 loss: 0.117250]  [sq d1 d2: 0.000763]  [num0: 17.000000] [num1 47.000000]
[Epoch 123/500] [Batch 600/676] [D loss: 0.000905] [G loss: -0.174593] [d1 loss: 0.121401] [d2 loss: 0.115451]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]
[Epoch 123/500] [Batch 620/676] [D loss: -0.004797] [G loss: -0.146644] [d1 loss: 0.189409] [d2 loss: 0.131423]  [sq d1 d2: 0.003362]  [num0: 15.000000] [num1 49.000000]
[Epoch 123/500] [Batch 640/676] [D loss: -0.017900] [G loss: -0.132382] [d1 loss: 0.130166] [d2 loss: 0.132660]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 123/500] [Batch 660/676] [D loss: -0.011439] [G loss: -0.147289] [d1 loss: 0.116205] [d2 loss: 0.135187]  [sq d1 d2: 0.000360]  [num0: 18.000000] [num1 46.000000]
[Epoch 124/500] [Batch 0/676] [D loss: -0.039981] [G loss: -0.161142] [d1 loss: 0.068564] [d2 loss: 0.074119]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 20/676] [D loss: -0.010753] [G loss: -0.149206] [d1 loss: 0.066864] [d2 loss: 0.072979]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 40/676] [D loss: -0.042420] [G loss: -0.151852] [d1 loss: 0.021896] [d2 loss: 0.019971]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 60/676] [D loss: -0.007542] [G loss: -0.135796] [d1 loss: 0.056709] [d2 loss: 0.063547]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 124/500] [Batch 80/676] [D loss: -0.007901] [G loss: -0.098566] [d1 loss: 0.037357] [d2 loss: 0.038927]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 124/500] [Batch 100/676] [D loss: -0.030605] [G loss: -0.081230] [d1 loss: 0.039815] [d2 loss: 0.055290]  [sq d1 d2: 0.000239]  [num0: 17.000000] [num1 47.000000]
[Epoch 124/500] [Batch 120/676] [D loss: -0.019505] [G loss: -0.018369] [d1 loss: 0.058716] [d2 loss: 0.066643]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]

[Epoch 124/500] [Batch 140/676] [D loss: -0.022422] [G loss: 0.014899] [d1 loss: 0.083948] [d2 loss: 0.068637]  [sq d1 d2: 0.000234]  [num0: 19.000000] [num1 45.000000]
[Epoch 124/500] [Batch 160/676] [D loss: -0.008755] [G loss: 0.014467] [d1 loss: 0.059149] [d2 loss: 0.070766]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 180/676] [D loss: -0.001414] [G loss: 0.039971] [d1 loss: 0.035957] [d2 loss: 0.033781]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 124/500] [Batch 200/676] [D loss: -0.020062] [G loss: 0.096711] [d1 loss: 0.034191] [d2 loss: 0.055097]  [sq d1 d2: 0.000437]  [num0: 18.000000] [num1 46.000000]
[Epoch 124/500] [Batch 220/676] [D loss: -0.033355] [G loss: 0.121067] [d1 loss: 0.035390] [d2 loss: 0.039193]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 240/676] [D loss: -0.020393] [G loss: 0.127945] [d1 loss: 0.108347] [d2 loss: 0.094611]  [sq d1 d2: 0.000189]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 260/676] [D loss: -0.029361] [G loss: 0.144523] [d1 loss: 0.038354] [d2 loss: 0.028870]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 280/676] [D loss: -0.029383] [G loss: 0.124107] [d1 loss: 0.051938] [d2 loss: 0.069197]  [sq d1 d2: 0.000298]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 300/676] [D loss: -0.024518] [G loss: 0.140889] [d1 loss: 0.110609] [d2 loss: 0.092523]  [sq d1 d2: 0.000327]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 320/676] [D loss: -0.022964] [G loss: 0.147058] [d1 loss: 0.047303] [d2 loss: 0.048212]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 124/500] [Batch 340/676] [D loss: -0.022448] [G loss: 0.095364] [d1 loss: 0.019142] [d2 loss: 0.020678]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 124/500] [Batch 360/676] [D loss: -0.024921] [G loss: 0.058939] [d1 loss: 0.050430] [d2 loss: 0.049371]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 380/676] [D loss: -0.021379] [G loss: 0.037032] [d1 loss: 0.083565] [d2 loss: 0.102752]  [sq d1 d2: 0.000368]  [num0: 14.000000] [num1 50.000000]
[Epoch 124/500] [Batch 400/676] [D loss: 0.006872] [G loss: 0.008440] [d1 loss: 0.126812] [d2 loss: 0.123419]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 420/676] [D loss: -0.028387] [G loss: -0.025072] [d1 loss: 0.037025] [d2 loss: 0.029375]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 124/500] [Batch 440/676] [D loss: -0.023158] [G loss: -0.039530] [d1 loss: 0.141491] [d2 loss: 0.116291]  [sq d1 d2: 0.000635]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 460/676] [D loss: -0.004055] [G loss: -0.108979] [d1 loss: 0.068143] [d2 loss: 0.082867]  [sq d1 d2: 0.000217]  [num0: 18.000000] [num1 46.000000]
[Epoch 124/500] [Batch 480/676] [D loss: -0.021724] [G loss: -0.127931] [d1 loss: 0.026368] [d2 loss: 0.033091]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 124/500] [Batch 500/676] [D loss: -0.028465] [G loss: -0.145360] [d1 loss: 0.089542] [d2 loss: 0.087443]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 124/500] [Batch 520/676] [D loss: -0.004028] [G loss: -0.138560] [d1 loss: 0.065357] [d2 loss: 0.063620]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 124/500] [Batch 540/676] [D loss: -0.005811] [G loss: -0.134250] [d1 loss: 0.079973] [d2 loss: 0.089530]  [sq d1 d2: 0.000091]  [num0: 20.000000] [num1 44.000000]
[Epoch 124/500] [Batch 560/676] [D loss: -0.004502] [G loss: -0.130676] [d1 loss: 0.057553] [d2 loss: 0.052598]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 124/500] [Batch 580/676] [D loss: -0.011455] [G loss: -0.096510] [d1 loss: 0.094529] [d2 loss: 0.103410]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 124/500] [Batch 600/676] [D loss: -0.009037] [G loss: -0.074976] [d1 loss: 0.033950] [d2 loss: 0.038557]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 124/500] [Batch 620/676] [D loss: -0.003818] [G loss: -0.074689] [d1 loss: 0.055224] [d2 loss: 0.040915]  [sq d1 d2: 0.000205]  [num0: 13.000000] [num1 51.000000]
[Epoch 124/500] [Batch 640/676] [D loss: -0.050116] [G loss: -0.078657] [d1 loss: 0.044456] [d2 loss: 0.041589]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 124/500] [Batch 660/676] [D loss: -0.045785] [G loss: -0.090576] [d1 loss: 0.113651] [d2 loss: 0.097499]  [sq d1 d2: 0.000261]  [num0: 17.000000] [num1 47.000000]
[Epoch 125/500] [Batch 0/676] [D loss: -0.049611] [G loss: -0.081528] [d1 loss: 0.035222] [d2 loss: 0.032269]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 20/676] [D loss: -0.034668] [G loss: -0.108531] [d1 loss: 0.082981] [d2 loss: 0.092252]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 40/676] [D loss: -0.038500] [G loss: -0.131346] [d1 loss: 0.111441] [d2 loss: 0.114364]  [sq d1 d2: 0.000009]  [num0: 21.000000] [num1 43.000000]
[Epoch 125/500] [Batch 60/676] [D loss: -0.001086] [G loss: -0.138024] [d1 loss: 0.084409] [d2 loss: 0.098945]  [sq d1 d2: 0.000211]  [num0: 18.000000] [num1 46.000000]
[Epoch 125/500] [Batch 80/676] [D loss: -0.020526] [G loss: -0.167066] [d1 loss: 0.104209] [d2 loss: 0.122415]  [sq d1 d2: 0.000331]  [num0: 22.000000] [num1 42.000000]
[Epoch 125/500] [Batch 100/676] [D loss: -0.017492] [G loss: -0.194205] [d1 loss: 0.099890] [d2 loss: 0.088986]  [sq d1 d2: 0.000119]  [num0: 19.000000] [num1 45.000000]
[Epoch 125/500] [Batch 120/676] [D loss: -0.019417] [G loss: -0.212699] [d1 loss: 0.046799] [d2 loss: 0.046576]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 125/500] [Batch 140/676] [D loss: -0.031820] [G loss: -0.231843] [d1 loss: 0.034972] [d2 loss: 0.039440]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 160/676] [D loss: -0.007963] [G loss: -0.245577] [d1 loss: 0.060630] [d2 loss: 0.068346]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 180/676] [D loss: -0.022344] [G loss: -0.294719] [d1 loss: 0.083590] [d2 loss: 0.080996]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 125/500] [Batch 200/676] [D loss: -0.047659] [G loss: -0.306604] [d1 loss: 0.036460] [d2 loss: 0.029109]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 125/500] [Batch 220/676] [D loss: -0.037506] [G loss: -0.269874] [d1 loss: 0.085081] [d2 loss: 0.046317]  [sq d1 d2: 0.001503]  [num0: 17.000000] [num1 47.000000]
[Epoch 125/500] [Batch 240/676] [D loss: -0.010193] [G loss: -0.301792] [d1 loss: 0.091631] [d2 loss: 0.083438]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 125/500] [Batch 260/676] [D loss: -0.052350] [G loss: -0.258933] [d1 loss: 0.032860] [d2 loss: 0.036098]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 125/500] [Batch 280/676] [D loss: -0.033293] [G loss: -0.215049] [d1 loss: 0.055693] [d2 loss: 0.050581]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 125/500] [Batch 300/676] [D loss: -0.012433] [G loss: -0.162570] [d1 loss: 0.037044] [d2 loss: 0.036455]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 125/500] [Batch 320/676] [D loss: -0.002376] [G loss: -0.101540] [d1 loss: 0.006905] [d2 loss: 0.005561]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 340/676] [D loss: -0.004225] [G loss: -0.097419] [d1 loss: 0.068979] [d2 loss: 0.061858]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 125/500] [Batch 360/676] [D loss: -0.021516] [G loss: -0.057893] [d1 loss: 0.036328] [d2 loss: 0.030717]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 380/676] [D loss: -0.007596] [G loss: -0.021242] [d1 loss: 0.061058] [d2 loss: 0.048351]  [sq d1 d2: 0.000161]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 400/676] [D loss: -0.014284] [G loss: 0.006746] [d1 loss: 0.049685] [d2 loss: 0.073664]  [sq d1 d2: 0.000575]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 420/676] [D loss: -0.029742] [G loss: 0.009187] [d1 loss: 0.055742] [d2 loss: 0.045906]  [sq d1 d2: 0.000097]  [num0: 13.000000] [num1 51.000000]
[Epoch 125/500] [Batch 440/676] [D loss: -0.049553] [G loss: 0.012752] [d1 loss: 0.135458] [d2 loss: 0.106606]  [sq d1 d2: 0.000832]  [num0: 14.000000] [num1 50.000000]
[Epoch 125/500] [Batch 460/676] [D loss: -0.021533] [G loss: 0.022167] [d1 loss: 0.031924] [d2 loss: 0.031362]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]

[Epoch 125/500] [Batch 480/676] [D loss: -0.024662] [G loss: 0.005511] [d1 loss: 0.038549] [d2 loss: 0.039440]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 500/676] [D loss: -0.019394] [G loss: 0.013147] [d1 loss: 0.094272] [d2 loss: 0.079824]  [sq d1 d2: 0.000209]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 520/676] [D loss: -0.028321] [G loss: 0.048900] [d1 loss: 0.083830] [d2 loss: 0.074358]  [sq d1 d2: 0.000090]  [num0: 13.000000] [num1 51.000000]
[Epoch 125/500] [Batch 540/676] [D loss: -0.006484] [G loss: 0.000955] [d1 loss: 0.033281] [d2 loss: 0.036967]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 560/676] [D loss: -0.004210] [G loss: 0.013487] [d1 loss: 0.106548] [d2 loss: 0.095716]  [sq d1 d2: 0.000117]  [num0: 17.000000] [num1 47.000000]
[Epoch 125/500] [Batch 580/676] [D loss: -0.021377] [G loss: -0.035731] [d1 loss: 0.119408] [d2 loss: 0.099383]  [sq d1 d2: 0.000401]  [num0: 18.000000] [num1 46.000000]
[Epoch 125/500] [Batch 600/676] [D loss: -0.004623] [G loss: -0.093000] [d1 loss: 0.030729] [d2 loss: 0.025711]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 620/676] [D loss: -0.012762] [G loss: -0.189248] [d1 loss: 0.046431] [d2 loss: 0.054149]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 640/676] [D loss: -0.037770] [G loss: -0.219051] [d1 loss: 0.060552] [d2 loss: 0.062980]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 125/500] [Batch 660/676] [D loss: -0.034336] [G loss: -0.240838] [d1 loss: 0.045880] [d2 loss: 0.102817]  [sq d1 d2: 0.003242]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 0/676] [D loss: -0.016649] [G loss: -0.291147] [d1 loss: 0.089102] [d2 loss: 0.092485]  [sq d1 d2: 0.000011]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 20/676] [D loss: -0.034980] [G loss: -0.226095] [d1 loss: 0.109190] [d2 loss: 0.089689]  [sq d1 d2: 0.000380]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 40/676] [D loss: -0.011186] [G loss: -0.177419] [d1 loss: 0.043812] [d2 loss: 0.055355]  [sq d1 d2: 0.000133]  [num0: 21.000000] [num1 43.000000]
[Epoch 126/500] [Batch 60/676] [D loss: 0.001056] [G loss: -0.147066] [d1 loss: 0.045811] [d2 loss: 0.063603]  [sq d1 d2: 0.000317]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 80/676] [D loss: -0.006847] [G loss: -0.083627] [d1 loss: 0.050889] [d2 loss: 0.041114]  [sq d1 d2: 0.000096]  [num0: 20.000000] [num1 44.000000]
[Epoch 126/500] [Batch 100/676] [D loss: -0.009854] [G loss: -0.044195] [d1 loss: 0.016239] [d2 loss: 0.017092]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 126/500] [Batch 120/676] [D loss: -0.012556] [G loss: -0.028108] [d1 loss: 0.068985] [d2 loss: 0.061709]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 140/676] [D loss: -0.028653] [G loss: 0.008427] [d1 loss: 0.042284] [d2 loss: 0.048335]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 126/500] [Batch 160/676] [D loss: -0.038895] [G loss: 0.043932] [d1 loss: 0.071372] [d2 loss: 0.069785]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 126/500] [Batch 180/676] [D loss: -0.028320] [G loss: 0.089861] [d1 loss: 0.039996] [d2 loss: 0.042271]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 126/500] [Batch 200/676] [D loss: -0.016159] [G loss: 0.083646] [d1 loss: 0.052873] [d2 loss: 0.052023]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 126/500] [Batch 220/676] [D loss: -0.013502] [G loss: 0.086488] [d1 loss: 0.047636] [d2 loss: 0.050860]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 240/676] [D loss: -0.029504] [G loss: 0.059634] [d1 loss: 0.040270] [d2 loss: 0.039372]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 126/500] [Batch 260/676] [D loss: 0.004829] [G loss: 0.023164] [d1 loss: 0.053208] [d2 loss: 0.054289]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 280/676] [D loss: 0.000346] [G loss: 0.028813] [d1 loss: 0.078456] [d2 loss: 0.079112]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 126/500] [Batch 300/676] [D loss: -0.000402] [G loss: -0.042283] [d1 loss: 0.029571] [d2 loss: 0.032372]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 126/500] [Batch 320/676] [D loss: 0.001494] [G loss: -0.092831] [d1 loss: 0.062974] [d2 loss: 0.067819]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 340/676] [D loss: -0.005420] [G loss: -0.146459] [d1 loss: 0.018091] [d2 loss: 0.020350]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 360/676] [D loss: -0.042360] [G loss: -0.223468] [d1 loss: 0.086442] [d2 loss: 0.101264]  [sq d1 d2: 0.000220]  [num0: 16.000000] [num1 48.000000]
[Epoch 126/500] [Batch 380/676] [D loss: -0.043154] [G loss: -0.251325] [d1 loss: 0.057227] [d2 loss: 0.037162]  [sq d1 d2: 0.000403]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 400/676] [D loss: -0.024263] [G loss: -0.237915] [d1 loss: 0.052111] [d2 loss: 0.053003]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 126/500] [Batch 420/676] [D loss: -0.042010] [G loss: -0.268245] [d1 loss: 0.036618] [d2 loss: 0.045314]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 440/676] [D loss: 0.006965] [G loss: -0.239961] [d1 loss: 0.111744] [d2 loss: 0.117846]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 460/676] [D loss: -0.005711] [G loss: -0.201515] [d1 loss: 0.105472] [d2 loss: 0.091244]  [sq d1 d2: 0.000202]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 480/676] [D loss: -0.008906] [G loss: -0.134370] [d1 loss: 0.036073] [d2 loss: 0.031279]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 126/500] [Batch 500/676] [D loss: -0.006718] [G loss: -0.081654] [d1 loss: 0.035542] [d2 loss: 0.048206]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 126/500] [Batch 520/676] [D loss: 0.000347] [G loss: -0.071623] [d1 loss: 0.115143] [d2 loss: 0.125304]  [sq d1 d2: 0.000103]  [num0: 11.000000] [num1 53.000000]
[Epoch 126/500] [Batch 540/676] [D loss: -0.007466] [G loss: -0.081440] [d1 loss: 0.067638] [d2 loss: 0.059726]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 126/500] [Batch 560/676] [D loss: -0.022164] [G loss: -0.055059] [d1 loss: 0.043406] [d2 loss: 0.046523]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 126/500] [Batch 580/676] [D loss: -0.025490] [G loss: -0.030205] [d1 loss: 0.048282] [d2 loss: 0.045405]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 600/676] [D loss: -0.032893] [G loss: -0.045642] [d1 loss: 0.023708] [d2 loss: 0.037054]  [sq d1 d2: 0.000178]  [num0: 12.000000] [num1 52.000000]
[Epoch 126/500] [Batch 620/676] [D loss: -0.033529] [G loss: -0.063404] [d1 loss: 0.052962] [d2 loss: 0.090084]  [sq d1 d2: 0.001378]  [num0: 17.000000] [num1 47.000000]
[Epoch 126/500] [Batch 640/676] [D loss: -0.025927] [G loss: -0.058882] [d1 loss: 0.191772] [d2 loss: 0.150046]  [sq d1 d2: 0.001741]  [num0: 14.000000] [num1 50.000000]
[Epoch 126/500] [Batch 660/676] [D loss: -0.014743] [G loss: -0.071060] [d1 loss: 0.079195] [d2 loss: 0.060469]  [sq d1 d2: 0.000351]  [num0: 12.000000] [num1 52.000000]
[Epoch 127/500] [Batch 0/676] [D loss: -0.009939] [G loss: -0.079219] [d1 loss: 0.037573] [d2 loss: 0.057400]  [sq d1 d2: 0.000393]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 20/676] [D loss: -0.020616] [G loss: -0.089944] [d1 loss: 0.040750] [d2 loss: 0.030369]  [sq d1 d2: 0.000108]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 40/676] [D loss: 0.014873] [G loss: -0.084699] [d1 loss: 0.040513] [d2 loss: 0.052140]  [sq d1 d2: 0.000135]  [num0: 20.000000] [num1 44.000000]
[Epoch 127/500] [Batch 60/676] [D loss: -0.004055] [G loss: -0.094043] [d1 loss: 0.057087] [d2 loss: 0.066563]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 80/676] [D loss: -0.005780] [G loss: -0.085406] [d1 loss: 0.067590] [d2 loss: 0.088703]  [sq d1 d2: 0.000446]  [num0: 16.000000] [num1 48.000000]
[Epoch 127/500] [Batch 100/676] [D loss: 0.004971] [G loss: -0.096960] [d1 loss: 0.093373] [d2 loss: 0.079831]  [sq d1 d2: 0.000183]  [num0: 13.000000] [num1 51.000000]
[Epoch 127/500] [Batch 120/676] [D loss: -0.015814] [G loss: -0.114398] [d1 loss: 0.033975] [d2 loss: 0.030109]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]

[Epoch 127/500] [Batch 140/676] [D loss: -0.010586] [G loss: -0.122096] [d1 loss: 0.025961] [d2 loss: 0.033057]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 127/500] [Batch 160/676] [D loss: -0.025464] [G loss: -0.132239] [d1 loss: 0.038694] [d2 loss: 0.036106]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 127/500] [Batch 180/676] [D loss: -0.024414] [G loss: -0.161690] [d1 loss: 0.049027] [d2 loss: 0.031034]  [sq d1 d2: 0.000324]  [num0: 19.000000] [num1 45.000000]
[Epoch 127/500] [Batch 200/676] [D loss: -0.035262] [G loss: -0.209704] [d1 loss: 0.079897] [d2 loss: 0.097864]  [sq d1 d2: 0.000323]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 220/676] [D loss: -0.056407] [G loss: -0.182801] [d1 loss: 0.087134] [d2 loss: 0.081836]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 240/676] [D loss: -0.012019] [G loss: -0.200240] [d1 loss: 0.052699] [d2 loss: 0.043941]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 127/500] [Batch 260/676] [D loss: -0.030741] [G loss: -0.202003] [d1 loss: 0.048525] [d2 loss: 0.038786]  [sq d1 d2: 0.000095]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 280/676] [D loss: 0.014484] [G loss: -0.202784] [d1 loss: 0.073244] [d2 loss: 0.080605]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 127/500] [Batch 300/676] [D loss: -0.005784] [G loss: -0.186986] [d1 loss: 0.024793] [d2 loss: 0.028223]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 127/500] [Batch 320/676] [D loss: 0.011990] [G loss: -0.147135] [d1 loss: 0.030458] [d2 loss: 0.034399]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 340/676] [D loss: 0.004994] [G loss: -0.114863] [d1 loss: 0.037522] [d2 loss: 0.034291]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 360/676] [D loss: -0.016362] [G loss: -0.116548] [d1 loss: 0.182079] [d2 loss: 0.128766]  [sq d1 d2: 0.002842]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 380/676] [D loss: -0.013291] [G loss: -0.101448] [d1 loss: 0.051519] [d2 loss: 0.055069]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 127/500] [Batch 400/676] [D loss: -0.023908] [G loss: -0.112544] [d1 loss: 0.034958] [d2 loss: 0.032565]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 420/676] [D loss: -0.011807] [G loss: -0.125428] [d1 loss: 0.083507] [d2 loss: 0.073969]  [sq d1 d2: 0.000091]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 440/676] [D loss: -0.024679] [G loss: -0.169192] [d1 loss: 0.078553] [d2 loss: 0.065497]  [sq d1 d2: 0.000170]  [num0: 11.000000] [num1 53.000000]
[Epoch 127/500] [Batch 460/676] [D loss: -0.029847] [G loss: -0.207295] [d1 loss: 0.055942] [d2 loss: 0.051671]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 127/500] [Batch 480/676] [D loss: -0.006469] [G loss: -0.206513] [d1 loss: 0.121981] [d2 loss: 0.125058]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 127/500] [Batch 500/676] [D loss: -0.018228] [G loss: -0.194620] [d1 loss: 0.047001] [d2 loss: 0.052759]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 127/500] [Batch 520/676] [D loss: -0.012407] [G loss: -0.216249] [d1 loss: 0.126050] [d2 loss: 0.128263]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 127/500] [Batch 540/676] [D loss: 0.014994] [G loss: -0.151636] [d1 loss: 0.041461] [d2 loss: 0.041630]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 127/500] [Batch 560/676] [D loss: -0.004065] [G loss: -0.140276] [d1 loss: 0.087169] [d2 loss: 0.068874]  [sq d1 d2: 0.000335]  [num0: 16.000000] [num1 48.000000]
[Epoch 127/500] [Batch 580/676] [D loss: 0.010044] [G loss: -0.094774] [d1 loss: 0.059502] [d2 loss: 0.062435]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 127/500] [Batch 600/676] [D loss: -0.000338] [G loss: -0.079894] [d1 loss: 0.098967] [d2 loss: 0.113298]  [sq d1 d2: 0.000205]  [num0: 13.000000] [num1 51.000000]
[Epoch 127/500] [Batch 620/676] [D loss: -0.014905] [G loss: -0.090138] [d1 loss: 0.032133] [d2 loss: 0.044189]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 127/500] [Batch 640/676] [D loss: -0.027826] [G loss: -0.093754] [d1 loss: 0.033225] [d2 loss: 0.034003]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 127/500] [Batch 660/676] [D loss: -0.043516] [G loss: -0.104061] [d1 loss: 0.068335] [d2 loss: 0.109633]  [sq d1 d2: 0.001706]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 0/676] [D loss: -0.019398] [G loss: -0.137665] [d1 loss: 0.207318] [d2 loss: 0.209208]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 128/500] [Batch 20/676] [D loss: -0.040159] [G loss: -0.102641] [d1 loss: 0.019065] [d2 loss: 0.015495]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 128/500] [Batch 40/676] [D loss: -0.039004] [G loss: -0.123444] [d1 loss: 0.124599] [d2 loss: 0.123971]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 60/676] [D loss: -0.013205] [G loss: -0.128166] [d1 loss: 0.036456] [d2 loss: 0.036314]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 128/500] [Batch 80/676] [D loss: 0.010064] [G loss: -0.156070] [d1 loss: 0.089772] [d2 loss: 0.079684]  [sq d1 d2: 0.000102]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 100/676] [D loss: 0.010407] [G loss: -0.096591] [d1 loss: 0.216976] [d2 loss: 0.194200]  [sq d1 d2: 0.000519]  [num0: 18.000000] [num1 46.000000]
[Epoch 128/500] [Batch 120/676] [D loss: 0.009877] [G loss: -0.079247] [d1 loss: 0.051805] [d2 loss: 0.050467]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 140/676] [D loss: -0.000773] [G loss: -0.068653] [d1 loss: 0.096301] [d2 loss: 0.078754]  [sq d1 d2: 0.000308]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 160/676] [D loss: -0.008262] [G loss: -0.059515] [d1 loss: 0.136526] [d2 loss: 0.115811]  [sq d1 d2: 0.000429]  [num0: 20.000000] [num1 44.000000]
[Epoch 128/500] [Batch 180/676] [D loss: -0.014067] [G loss: -0.053437] [d1 loss: 0.048378] [d2 loss: 0.054557]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 200/676] [D loss: -0.031149] [G loss: -0.073134] [d1 loss: 0.107369] [d2 loss: 0.095396]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 220/676] [D loss: -0.038827] [G loss: -0.082052] [d1 loss: 0.113751] [d2 loss: 0.114986]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 128/500] [Batch 240/676] [D loss: -0.057299] [G loss: -0.116183] [d1 loss: 0.064816] [d2 loss: 0.053621]  [sq d1 d2: 0.000125]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 260/676] [D loss: -0.015488] [G loss: -0.122024] [d1 loss: 0.049564] [d2 loss: 0.044540]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 128/500] [Batch 280/676] [D loss: -0.043510] [G loss: -0.129687] [d1 loss: 0.080799] [d2 loss: 0.082608]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 300/676] [D loss: -0.011332] [G loss: -0.133239] [d1 loss: 0.054070] [d2 loss: 0.072769]  [sq d1 d2: 0.000350]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 320/676] [D loss: -0.013360] [G loss: -0.132569] [d1 loss: 0.056025] [d2 loss: 0.075090]  [sq d1 d2: 0.000363]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 340/676] [D loss: 0.033301] [G loss: -0.076848] [d1 loss: 0.070414] [d2 loss: 0.065341]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 128/500] [Batch 360/676] [D loss: -0.008715] [G loss: -0.064689] [d1 loss: 0.030331] [d2 loss: 0.035077]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 380/676] [D loss: 0.003958] [G loss: -0.046490] [d1 loss: 0.040415] [d2 loss: 0.044697]  [sq d1 d2: 0.000018]  [num0: 11.000000] [num1 53.000000]
[Epoch 128/500] [Batch 400/676] [D loss: -0.005700] [G loss: -0.022927] [d1 loss: 0.124224] [d2 loss: 0.100417]  [sq d1 d2: 0.000567]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 420/676] [D loss: -0.023928] [G loss: -0.005236] [d1 loss: 0.043800] [d2 loss: 0.043012]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 128/500] [Batch 440/676] [D loss: -0.025899] [G loss: 0.007713] [d1 loss: 0.138532] [d2 loss: 0.141712]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 128/500] [Batch 460/676] [D loss: -0.028019] [G loss: 0.020934] [d1 loss: 0.096037] [d2 loss: 0.096207]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 480/676] [D loss: -0.043759] [G loss: -0.000076] [d1 loss: 0.032028] [d2 loss: 0.030225]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]

[Epoch 128/500] [Batch 500/676] [D loss: -0.051029] [G loss: -0.029651] [d1 loss: 0.082300] [d2 loss: 0.089186]  [sq d1 d2: 0.000047]  [num0: 12.000000] [num1 52.000000]
[Epoch 128/500] [Batch 520/676] [D loss: -0.029092] [G loss: -0.035440] [d1 loss: 0.074464] [d2 loss: 0.067702]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 128/500] [Batch 540/676] [D loss: -0.006766] [G loss: -0.086112] [d1 loss: 0.081589] [d2 loss: 0.086999]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 128/500] [Batch 560/676] [D loss: 0.009086] [G loss: -0.084655] [d1 loss: 0.131235] [d2 loss: 0.102455]  [sq d1 d2: 0.000828]  [num0: 17.000000] [num1 47.000000]
[Epoch 128/500] [Batch 580/676] [D loss: 0.000105] [G loss: -0.051962] [d1 loss: 0.104312] [d2 loss: 0.115494]  [sq d1 d2: 0.000125]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 600/676] [D loss: -0.005460] [G loss: -0.081873] [d1 loss: 0.090024] [d2 loss: 0.084695]  [sq d1 d2: 0.000028]  [num0: 12.000000] [num1 52.000000]
[Epoch 128/500] [Batch 620/676] [D loss: -0.009466] [G loss: -0.069146] [d1 loss: 0.027434] [d2 loss: 0.025866]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 128/500] [Batch 640/676] [D loss: -0.016550] [G loss: -0.100028] [d1 loss: 0.086815] [d2 loss: 0.085430]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 128/500] [Batch 660/676] [D loss: -0.024282] [G loss: -0.125807] [d1 loss: 0.021724] [d2 loss: 0.018513]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 0/676] [D loss: -0.026145] [G loss: -0.138157] [d1 loss: 0.054083] [d2 loss: 0.051732]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 20/676] [D loss: -0.020409] [G loss: -0.182520] [d1 loss: 0.112106] [d2 loss: 0.136128]  [sq d1 d2: 0.000577]  [num0: 13.000000] [num1 51.000000]
[Epoch 129/500] [Batch 40/676] [D loss: -0.031779] [G loss: -0.190582] [d1 loss: 0.067059] [d2 loss: 0.066558]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 129/500] [Batch 60/676] [D loss: -0.028087] [G loss: -0.181645] [d1 loss: 0.106836] [d2 loss: 0.091438]  [sq d1 d2: 0.000237]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 80/676] [D loss: 0.024985] [G loss: -0.195440] [d1 loss: 0.170740] [d2 loss: 0.153009]  [sq d1 d2: 0.000314]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 100/676] [D loss: 0.007550] [G loss: -0.145958] [d1 loss: 0.055995] [d2 loss: 0.046749]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 120/676] [D loss: -0.000051] [G loss: -0.117014] [d1 loss: 0.098136] [d2 loss: 0.085549]  [sq d1 d2: 0.000158]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 140/676] [D loss: 0.017968] [G loss: -0.073810] [d1 loss: 0.037387] [d2 loss: 0.046003]  [sq d1 d2: 0.000074]  [num0: 9.000000] [num1 55.000000]
[Epoch 129/500] [Batch 160/676] [D loss: -0.003431] [G loss: -0.063929] [d1 loss: 0.093318] [d2 loss: 0.094318]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 180/676] [D loss: -0.013467] [G loss: -0.064858] [d1 loss: 0.051927] [d2 loss: 0.051168]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 129/500] [Batch 200/676] [D loss: -0.016553] [G loss: -0.062459] [d1 loss: 0.063546] [d2 loss: 0.064516]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 129/500] [Batch 220/676] [D loss: -0.031801] [G loss: -0.015756] [d1 loss: 0.051956] [d2 loss: 0.071687]  [sq d1 d2: 0.000389]  [num0: 17.000000] [num1 47.000000]
[Epoch 129/500] [Batch 240/676] [D loss: -0.037526] [G loss: -0.010538] [d1 loss: 0.060772] [d2 loss: 0.053748]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 129/500] [Batch 260/676] [D loss: -0.043761] [G loss: 0.024260] [d1 loss: 0.039814] [d2 loss: 0.037016]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 280/676] [D loss: -0.015663] [G loss: 0.005600] [d1 loss: 0.115453] [d2 loss: 0.099021]  [sq d1 d2: 0.000270]  [num0: 14.000000] [num1 50.000000]
[Epoch 129/500] [Batch 300/676] [D loss: -0.015496] [G loss: 0.003335] [d1 loss: 0.039796] [d2 loss: 0.049170]  [sq d1 d2: 0.000088]  [num0: 13.000000] [num1 51.000000]
[Epoch 129/500] [Batch 320/676] [D loss: 0.019985] [G loss: -0.001319] [d1 loss: 0.116219] [d2 loss: 0.121914]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 340/676] [D loss: 0.010421] [G loss: -0.000033] [d1 loss: 0.068299] [d2 loss: 0.058818]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 360/676] [D loss: 0.008877] [G loss: -0.008131] [d1 loss: 0.101033] [d2 loss: 0.094150]  [sq d1 d2: 0.000047]  [num0: 21.000000] [num1 43.000000]
[Epoch 129/500] [Batch 380/676] [D loss: -0.006508] [G loss: -0.016158] [d1 loss: 0.047292] [d2 loss: 0.037656]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 400/676] [D loss: -0.016278] [G loss: -0.034839] [d1 loss: 0.091504] [d2 loss: 0.113321]  [sq d1 d2: 0.000476]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 420/676] [D loss: -0.027729] [G loss: -0.060547] [d1 loss: 0.024962] [d2 loss: 0.031342]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 129/500] [Batch 440/676] [D loss: -0.041000] [G loss: -0.068501] [d1 loss: 0.139374] [d2 loss: 0.162779]  [sq d1 d2: 0.000548]  [num0: 17.000000] [num1 47.000000]
[Epoch 129/500] [Batch 460/676] [D loss: -0.042374] [G loss: -0.085145] [d1 loss: 0.046374] [d2 loss: 0.053337]  [sq d1 d2: 0.000048]  [num0: 20.000000] [num1 44.000000]
[Epoch 129/500] [Batch 480/676] [D loss: -0.029998] [G loss: -0.123936] [d1 loss: 0.091338] [d2 loss: 0.073920]  [sq d1 d2: 0.000303]  [num0: 13.000000] [num1 51.000000]
[Epoch 129/500] [Batch 500/676] [D loss: 0.008631] [G loss: -0.145389] [d1 loss: 0.168810] [d2 loss: 0.157234]  [sq d1 d2: 0.000134]  [num0: 17.000000] [num1 47.000000]
[Epoch 129/500] [Batch 520/676] [D loss: 0.014877] [G loss: -0.165732] [d1 loss: 0.160639] [d2 loss: 0.138942]  [sq d1 d2: 0.000471]  [num0: 15.000000] [num1 49.000000]
[Epoch 129/500] [Batch 540/676] [D loss: 0.015636] [G loss: -0.135753] [d1 loss: 0.031989] [d2 loss: 0.029592]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 129/500] [Batch 560/676] [D loss: 0.000005] [G loss: -0.100727] [d1 loss: 0.077515] [d2 loss: 0.069491]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 129/500] [Batch 580/676] [D loss: 0.006562] [G loss: -0.040162] [d1 loss: 0.189618] [d2 loss: 0.161332]  [sq d1 d2: 0.000800]  [num0: 17.000000] [num1 47.000000]
[Epoch 129/500] [Batch 600/676] [D loss: -0.007079] [G loss: -0.008793] [d1 loss: 0.030508] [d2 loss: 0.031469]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 129/500] [Batch 620/676] [D loss: -0.017612] [G loss: 0.013736] [d1 loss: 0.144768] [d2 loss: 0.123935]  [sq d1 d2: 0.000434]  [num0: 14.000000] [num1 50.000000]
[Epoch 129/500] [Batch 640/676] [D loss: -0.025370] [G loss: 0.010386] [d1 loss: 0.046388] [d2 loss: 0.056665]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 129/500] [Batch 660/676] [D loss: -0.048789] [G loss: 0.007453] [d1 loss: 0.046041] [d2 loss: 0.051291]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 130/500] [Batch 0/676] [D loss: -0.028057] [G loss: -0.016999] [d1 loss: 0.093510] [d2 loss: 0.082477]  [sq d1 d2: 0.000122]  [num0: 12.000000] [num1 52.000000]
[Epoch 130/500] [Batch 20/676] [D loss: -0.029995] [G loss: -0.045954] [d1 loss: 0.029784] [d2 loss: 0.030393]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 40/676] [D loss: -0.026437] [G loss: -0.052614] [d1 loss: 0.064583] [d2 loss: 0.077172]  [sq d1 d2: 0.000158]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 60/676] [D loss: -0.018153] [G loss: -0.088441] [d1 loss: 0.057716] [d2 loss: 0.039509]  [sq d1 d2: 0.000331]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 80/676] [D loss: -0.000621] [G loss: -0.125403] [d1 loss: 0.100286] [d2 loss: 0.117907]  [sq d1 d2: 0.000311]  [num0: 11.000000] [num1 53.000000]
[Epoch 130/500] [Batch 100/676] [D loss: 0.005990] [G loss: -0.126457] [d1 loss: 0.129998] [d2 loss: 0.133024]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]

[Epoch 130/500] [Batch 120/676] [D loss: 0.004081] [G loss: -0.105722] [d1 loss: 0.105646] [d2 loss: 0.080864]  [sq d1 d2: 0.000614]  [num0: 13.000000] [num1 51.000000]
[Epoch 130/500] [Batch 140/676] [D loss: -0.002829] [G loss: -0.085614] [d1 loss: 0.047531] [d2 loss: 0.074062]  [sq d1 d2: 0.000704]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 160/676] [D loss: -0.009579] [G loss: -0.087520] [d1 loss: 0.124584] [d2 loss: 0.139265]  [sq d1 d2: 0.000216]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 180/676] [D loss: -0.029215] [G loss: -0.110383] [d1 loss: 0.061772] [d2 loss: 0.046975]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 200/676] [D loss: -0.039071] [G loss: -0.130173] [d1 loss: 0.068738] [d2 loss: 0.062444]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 220/676] [D loss: -0.042153] [G loss: -0.128656] [d1 loss: 0.059550] [d2 loss: 0.065033]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 240/676] [D loss: -0.036726] [G loss: -0.156122] [d1 loss: 0.025131] [d2 loss: 0.023470]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 260/676] [D loss: -0.009411] [G loss: -0.137642] [d1 loss: 0.041483] [d2 loss: 0.041098]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 280/676] [D loss: -0.001789] [G loss: -0.155532] [d1 loss: 0.143006] [d2 loss: 0.144602]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 130/500] [Batch 300/676] [D loss: 0.020561] [G loss: -0.117272] [d1 loss: 0.160354] [d2 loss: 0.115808]  [sq d1 d2: 0.001984]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 320/676] [D loss: 0.013279] [G loss: -0.055521] [d1 loss: 0.148511] [d2 loss: 0.144300]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 340/676] [D loss: -0.001621] [G loss: -0.018853] [d1 loss: 0.118594] [d2 loss: 0.108547]  [sq d1 d2: 0.000101]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 360/676] [D loss: -0.012774] [G loss: 0.016410] [d1 loss: 0.032601] [d2 loss: 0.038560]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 380/676] [D loss: -0.040871] [G loss: 0.030970] [d1 loss: 0.038807] [d2 loss: 0.033913]  [sq d1 d2: 0.000024]  [num0: 11.000000] [num1 53.000000]
[Epoch 130/500] [Batch 400/676] [D loss: -0.051093] [G loss: 0.052246] [d1 loss: 0.059491] [d2 loss: 0.071871]  [sq d1 d2: 0.000153]  [num0: 16.000000] [num1 48.000000]
[Epoch 130/500] [Batch 420/676] [D loss: -0.039630] [G loss: 0.098570] [d1 loss: 0.055524] [d2 loss: 0.039744]  [sq d1 d2: 0.000249]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 440/676] [D loss: -0.025065] [G loss: 0.107367] [d1 loss: 0.104599] [d2 loss: 0.130026]  [sq d1 d2: 0.000647]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 460/676] [D loss: -0.015431] [G loss: 0.071029] [d1 loss: 0.074984] [d2 loss: 0.083351]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 480/676] [D loss: 0.027817] [G loss: 0.060707] [d1 loss: 0.126134] [d2 loss: 0.135503]  [sq d1 d2: 0.000088]  [num0: 22.000000] [num1 42.000000]
[Epoch 130/500] [Batch 500/676] [D loss: -0.011610] [G loss: 0.045792] [d1 loss: 0.069872] [d2 loss: 0.056742]  [sq d1 d2: 0.000172]  [num0: 18.000000] [num1 46.000000]
[Epoch 130/500] [Batch 520/676] [D loss: -0.002760] [G loss: 0.033481] [d1 loss: 0.042966] [d2 loss: 0.044572]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 130/500] [Batch 540/676] [D loss: -0.008743] [G loss: 0.037802] [d1 loss: 0.058463] [d2 loss: 0.053861]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 560/676] [D loss: -0.001119] [G loss: -0.001620] [d1 loss: 0.056163] [d2 loss: 0.072319]  [sq d1 d2: 0.000261]  [num0: 17.000000] [num1 47.000000]
[Epoch 130/500] [Batch 580/676] [D loss: -0.036983] [G loss: -0.029628] [d1 loss: 0.049065] [d2 loss: 0.040003]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 600/676] [D loss: -0.061612] [G loss: -0.049008] [d1 loss: 0.046248] [d2 loss: 0.045499]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 130/500] [Batch 620/676] [D loss: -0.024527] [G loss: -0.083705] [d1 loss: 0.047398] [d2 loss: 0.056441]  [sq d1 d2: 0.000082]  [num0: 11.000000] [num1 53.000000]
[Epoch 130/500] [Batch 640/676] [D loss: -0.010439] [G loss: -0.124022] [d1 loss: 0.112436] [d2 loss: 0.135555]  [sq d1 d2: 0.000534]  [num0: 14.000000] [num1 50.000000]
[Epoch 130/500] [Batch 660/676] [D loss: 0.011157] [G loss: -0.123223] [d1 loss: 0.080329] [d2 loss: 0.085206]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 0/676] [D loss: 0.004493] [G loss: -0.157882] [d1 loss: 0.091040] [d2 loss: 0.098477]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 20/676] [D loss: -0.009564] [G loss: -0.157087] [d1 loss: 0.016486] [d2 loss: 0.016441]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 40/676] [D loss: 0.022555] [G loss: -0.120091] [d1 loss: 0.045963] [d2 loss: 0.035713]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 60/676] [D loss: -0.011746] [G loss: -0.078733] [d1 loss: 0.065095] [d2 loss: 0.058530]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 131/500] [Batch 80/676] [D loss: -0.022250] [G loss: -0.071098] [d1 loss: 0.070120] [d2 loss: 0.064534]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 100/676] [D loss: -0.021942] [G loss: -0.067719] [d1 loss: 0.033287] [d2 loss: 0.027355]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 120/676] [D loss: -0.042648] [G loss: -0.104349] [d1 loss: 0.127283] [d2 loss: 0.117785]  [sq d1 d2: 0.000090]  [num0: 17.000000] [num1 47.000000]
[Epoch 131/500] [Batch 140/676] [D loss: -0.046222] [G loss: -0.132179] [d1 loss: 0.049754] [d2 loss: 0.065796]  [sq d1 d2: 0.000257]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 160/676] [D loss: -0.049867] [G loss: -0.122418] [d1 loss: 0.163265] [d2 loss: 0.149656]  [sq d1 d2: 0.000185]  [num0: 20.000000] [num1 44.000000]
[Epoch 131/500] [Batch 180/676] [D loss: -0.010368] [G loss: -0.159823] [d1 loss: 0.028688] [d2 loss: 0.033803]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 131/500] [Batch 200/676] [D loss: -0.018073] [G loss: -0.210198] [d1 loss: 0.062397] [d2 loss: 0.067938]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 131/500] [Batch 220/676] [D loss: 0.007943] [G loss: -0.223498] [d1 loss: 0.060437] [d2 loss: 0.076480]  [sq d1 d2: 0.000257]  [num0: 18.000000] [num1 46.000000]
[Epoch 131/500] [Batch 240/676] [D loss: 0.014406] [G loss: -0.174559] [d1 loss: 0.055501] [d2 loss: 0.055466]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 131/500] [Batch 260/676] [D loss: -0.002176] [G loss: -0.142828] [d1 loss: 0.056521] [d2 loss: 0.047371]  [sq d1 d2: 0.000084]  [num0: 20.000000] [num1 44.000000]
[Epoch 131/500] [Batch 280/676] [D loss: -0.003174] [G loss: -0.110548] [d1 loss: 0.036818] [d2 loss: 0.039890]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 300/676] [D loss: -0.010538] [G loss: -0.094963] [d1 loss: 0.094856] [d2 loss: 0.100962]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 320/676] [D loss: -0.018834] [G loss: -0.089090] [d1 loss: 0.103569] [d2 loss: 0.102547]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 131/500] [Batch 340/676] [D loss: -0.031069] [G loss: -0.086846] [d1 loss: 0.085268] [d2 loss: 0.101938]  [sq d1 d2: 0.000278]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 360/676] [D loss: -0.040822] [G loss: -0.078502] [d1 loss: 0.119751] [d2 loss: 0.099219]  [sq d1 d2: 0.000422]  [num0: 17.000000] [num1 47.000000]
[Epoch 131/500] [Batch 380/676] [D loss: -0.030744] [G loss: -0.078689] [d1 loss: 0.088157] [d2 loss: 0.069336]  [sq d1 d2: 0.000354]  [num0: 17.000000] [num1 47.000000]
[Epoch 131/500] [Batch 400/676] [D loss: -0.046883] [G loss: -0.063451] [d1 loss: 0.057974] [d2 loss: 0.052002]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]

[Epoch 131/500] [Batch 420/676] [D loss: -0.013997] [G loss: -0.042295] [d1 loss: 0.061401] [d2 loss: 0.058316]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 440/676] [D loss: 0.004975] [G loss: -0.070266] [d1 loss: 0.063323] [d2 loss: 0.072230]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 460/676] [D loss: -0.003325] [G loss: -0.025987] [d1 loss: 0.179687] [d2 loss: 0.175616]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 480/676] [D loss: 0.022793] [G loss: 0.040679] [d1 loss: 0.058076] [d2 loss: 0.056079]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 500/676] [D loss: -0.007137] [G loss: 0.079608] [d1 loss: 0.046867] [d2 loss: 0.042773]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 520/676] [D loss: -0.021459] [G loss: 0.109772] [d1 loss: 0.103058] [d2 loss: 0.097262]  [sq d1 d2: 0.000034]  [num0: 11.000000] [num1 53.000000]
[Epoch 131/500] [Batch 540/676] [D loss: -0.023453] [G loss: 0.095788] [d1 loss: 0.075566] [d2 loss: 0.076582]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 560/676] [D loss: -0.033720] [G loss: 0.119538] [d1 loss: 0.047507] [d2 loss: 0.044007]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 131/500] [Batch 580/676] [D loss: -0.022635] [G loss: 0.094975] [d1 loss: 0.060642] [d2 loss: 0.083170]  [sq d1 d2: 0.000508]  [num0: 20.000000] [num1 44.000000]
[Epoch 131/500] [Batch 600/676] [D loss: -0.018827] [G loss: 0.096237] [d1 loss: 0.061373] [d2 loss: 0.076128]  [sq d1 d2: 0.000218]  [num0: 15.000000] [num1 49.000000]
[Epoch 131/500] [Batch 620/676] [D loss: -0.005797] [G loss: 0.091501] [d1 loss: 0.112994] [d2 loss: 0.135679]  [sq d1 d2: 0.000515]  [num0: 14.000000] [num1 50.000000]
[Epoch 131/500] [Batch 640/676] [D loss: 0.002794] [G loss: 0.059649] [d1 loss: 0.042480] [d2 loss: 0.034492]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 131/500] [Batch 660/676] [D loss: -0.003566] [G loss: 0.041637] [d1 loss: 0.104458] [d2 loss: 0.072707]  [sq d1 d2: 0.001008]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 0/676] [D loss: 0.011961] [G loss: 0.015508] [d1 loss: 0.024152] [d2 loss: 0.021840]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 132/500] [Batch 20/676] [D loss: -0.003742] [G loss: 0.013899] [d1 loss: 0.071399] [d2 loss: 0.101588]  [sq d1 d2: 0.000911]  [num0: 14.000000] [num1 50.000000]
[Epoch 132/500] [Batch 40/676] [D loss: -0.006126] [G loss: -0.002582] [d1 loss: 0.081972] [d2 loss: 0.077901]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 132/500] [Batch 60/676] [D loss: -0.013842] [G loss: -0.015631] [d1 loss: 0.028995] [d2 loss: 0.027028]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 132/500] [Batch 80/676] [D loss: -0.021605] [G loss: -0.018410] [d1 loss: 0.123151] [d2 loss: 0.108653]  [sq d1 d2: 0.000210]  [num0: 12.000000] [num1 52.000000]
[Epoch 132/500] [Batch 100/676] [D loss: -0.033516] [G loss: -0.030583] [d1 loss: 0.030254] [d2 loss: 0.025972]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 132/500] [Batch 120/676] [D loss: -0.047446] [G loss: -0.068910] [d1 loss: 0.093944] [d2 loss: 0.103202]  [sq d1 d2: 0.000086]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 140/676] [D loss: -0.009609] [G loss: -0.038792] [d1 loss: 0.034729] [d2 loss: 0.033052]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 160/676] [D loss: -0.026431] [G loss: -0.051281] [d1 loss: 0.121315] [d2 loss: 0.091310]  [sq d1 d2: 0.000900]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 180/676] [D loss: 0.012102] [G loss: -0.012272] [d1 loss: 0.050887] [d2 loss: 0.047345]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 132/500] [Batch 200/676] [D loss: 0.018720] [G loss: 0.011963] [d1 loss: 0.139466] [d2 loss: 0.120802]  [sq d1 d2: 0.000348]  [num0: 17.000000] [num1 47.000000]
[Epoch 132/500] [Batch 220/676] [D loss: -0.009232] [G loss: 0.052848] [d1 loss: 0.045209] [d2 loss: 0.046565]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 132/500] [Batch 240/676] [D loss: -0.013297] [G loss: 0.051733] [d1 loss: 0.071874] [d2 loss: 0.074859]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 260/676] [D loss: -0.013164] [G loss: 0.042028] [d1 loss: 0.111503] [d2 loss: 0.105340]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 280/676] [D loss: -0.003613] [G loss: 0.040603] [d1 loss: 0.064375] [d2 loss: 0.077055]  [sq d1 d2: 0.000161]  [num0: 16.000000] [num1 48.000000]
[Epoch 132/500] [Batch 300/676] [D loss: -0.020456] [G loss: 0.039064] [d1 loss: 0.087519] [d2 loss: 0.105928]  [sq d1 d2: 0.000339]  [num0: 17.000000] [num1 47.000000]
[Epoch 132/500] [Batch 320/676] [D loss: -0.023117] [G loss: 0.046972] [d1 loss: 0.127886] [d2 loss: 0.127524]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 132/500] [Batch 340/676] [D loss: -0.013994] [G loss: 0.044369] [d1 loss: 0.060801] [d2 loss: 0.062878]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 132/500] [Batch 360/676] [D loss: -0.030288] [G loss: -0.008037] [d1 loss: 0.090934] [d2 loss: 0.093702]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 132/500] [Batch 380/676] [D loss: 0.000498] [G loss: -0.031441] [d1 loss: 0.082522] [d2 loss: 0.084900]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 132/500] [Batch 400/676] [D loss: 0.000837] [G loss: -0.029638] [d1 loss: 0.049464] [d2 loss: 0.053774]  [sq d1 d2: 0.000019]  [num0: 9.000000] [num1 55.000000]
[Epoch 132/500] [Batch 420/676] [D loss: 0.006072] [G loss: -0.056448] [d1 loss: 0.192193] [d2 loss: 0.216676]  [sq d1 d2: 0.000599]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 440/676] [D loss: -0.004364] [G loss: -0.087632] [d1 loss: 0.046979] [d2 loss: 0.056512]  [sq d1 d2: 0.000091]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 460/676] [D loss: -0.008108] [G loss: -0.125188] [d1 loss: 0.055337] [d2 loss: 0.046518]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 132/500] [Batch 480/676] [D loss: -0.011327] [G loss: -0.110552] [d1 loss: 0.131377] [d2 loss: 0.098427]  [sq d1 d2: 0.001086]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 500/676] [D loss: -0.037701] [G loss: -0.123563] [d1 loss: 0.078538] [d2 loss: 0.050465]  [sq d1 d2: 0.000788]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 520/676] [D loss: -0.010989] [G loss: -0.154209] [d1 loss: 0.105729] [d2 loss: 0.100817]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 132/500] [Batch 540/676] [D loss: 0.008802] [G loss: -0.133533] [d1 loss: 0.052638] [d2 loss: 0.061406]  [sq d1 d2: 0.000077]  [num0: 13.000000] [num1 51.000000]
[Epoch 132/500] [Batch 560/676] [D loss: -0.032803] [G loss: -0.169138] [d1 loss: 0.077552] [d2 loss: 0.068800]  [sq d1 d2: 0.000077]  [num0: 11.000000] [num1 53.000000]
[Epoch 132/500] [Batch 580/676] [D loss: -0.018875] [G loss: -0.210155] [d1 loss: 0.088878] [d2 loss: 0.081998]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 132/500] [Batch 600/676] [D loss: 0.003157] [G loss: -0.208029] [d1 loss: 0.088405] [d2 loss: 0.086127]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 620/676] [D loss: -0.013429] [G loss: -0.148782] [d1 loss: 0.055588] [d2 loss: 0.058060]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 132/500] [Batch 640/676] [D loss: -0.006962] [G loss: -0.126853] [d1 loss: 0.038761] [d2 loss: 0.057032]  [sq d1 d2: 0.000334]  [num0: 18.000000] [num1 46.000000]
[Epoch 132/500] [Batch 660/676] [D loss: -0.013822] [G loss: -0.082135] [d1 loss: 0.060935] [d2 loss: 0.062843]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 0/676] [D loss: -0.017416] [G loss: -0.068859] [d1 loss: 0.043742] [d2 loss: 0.040040]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 20/676] [D loss: -0.018472] [G loss: -0.085438] [d1 loss: 0.061023] [d2 loss: 0.061225]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 40/676] [D loss: -0.032078] [G loss: -0.063473] [d1 loss: 0.028563] [d2 loss: 0.030855]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 60/676] [D loss: -0.037205] [G loss: -0.093204] [d1 loss: 0.099867] [d2 loss: 0.099537]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]

[Epoch 133/500] [Batch 80/676] [D loss: -0.010218] [G loss: -0.087893] [d1 loss: 0.084093] [d2 loss: 0.068267]  [sq d1 d2: 0.000250]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 100/676] [D loss: -0.016228] [G loss: -0.096508] [d1 loss: 0.077291] [d2 loss: 0.046182]  [sq d1 d2: 0.000968]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 120/676] [D loss: 0.007849] [G loss: -0.112075] [d1 loss: 0.021924] [d2 loss: 0.018788]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 133/500] [Batch 140/676] [D loss: -0.001724] [G loss: -0.086799] [d1 loss: 0.072879] [d2 loss: 0.066919]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 160/676] [D loss: 0.002706] [G loss: -0.083690] [d1 loss: 0.065422] [d2 loss: 0.066234]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 180/676] [D loss: -0.004401] [G loss: -0.084963] [d1 loss: 0.090193] [d2 loss: 0.094410]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 200/676] [D loss: -0.011276] [G loss: -0.097227] [d1 loss: 0.109369] [d2 loss: 0.118572]  [sq d1 d2: 0.000085]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 220/676] [D loss: -0.020115] [G loss: -0.101072] [d1 loss: 0.030402] [d2 loss: 0.033230]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 133/500] [Batch 240/676] [D loss: -0.027486] [G loss: -0.141700] [d1 loss: 0.090221] [d2 loss: 0.092928]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 260/676] [D loss: -0.035162] [G loss: -0.143999] [d1 loss: 0.032162] [d2 loss: 0.032323]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 280/676] [D loss: -0.020179] [G loss: -0.137387] [d1 loss: 0.081623] [d2 loss: 0.069986]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 300/676] [D loss: -0.005076] [G loss: -0.181753] [d1 loss: 0.056134] [d2 loss: 0.052064]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 320/676] [D loss: -0.014821] [G loss: -0.192396] [d1 loss: 0.135812] [d2 loss: 0.140989]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 133/500] [Batch 340/676] [D loss: 0.006978] [G loss: -0.171823] [d1 loss: 0.066955] [d2 loss: 0.055583]  [sq d1 d2: 0.000129]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 360/676] [D loss: 0.004583] [G loss: -0.118795] [d1 loss: 0.051088] [d2 loss: 0.052232]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 133/500] [Batch 380/676] [D loss: -0.001194] [G loss: -0.075059] [d1 loss: 0.122661] [d2 loss: 0.100856]  [sq d1 d2: 0.000475]  [num0: 16.000000] [num1 48.000000]
[Epoch 133/500] [Batch 400/676] [D loss: -0.008847] [G loss: -0.065038] [d1 loss: 0.067700] [d2 loss: 0.053890]  [sq d1 d2: 0.000191]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 420/676] [D loss: -0.009918] [G loss: -0.017310] [d1 loss: 0.069806] [d2 loss: 0.074714]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 133/500] [Batch 440/676] [D loss: -0.038989] [G loss: 0.032139] [d1 loss: 0.127934] [d2 loss: 0.085688]  [sq d1 d2: 0.001785]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 460/676] [D loss: -0.014652] [G loss: 0.047552] [d1 loss: 0.047973] [d2 loss: 0.035581]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 480/676] [D loss: -0.047684] [G loss: 0.053520] [d1 loss: 0.096431] [d2 loss: 0.096993]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 500/676] [D loss: -0.020219] [G loss: 0.064125] [d1 loss: 0.057288] [d2 loss: 0.046394]  [sq d1 d2: 0.000119]  [num0: 13.000000] [num1 51.000000]
[Epoch 133/500] [Batch 520/676] [D loss: -0.012587] [G loss: 0.037069] [d1 loss: 0.106865] [d2 loss: 0.114596]  [sq d1 d2: 0.000060]  [num0: 19.000000] [num1 45.000000]
[Epoch 133/500] [Batch 540/676] [D loss: -0.006133] [G loss: 0.001736] [d1 loss: 0.069990] [d2 loss: 0.064327]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 133/500] [Batch 560/676] [D loss: -0.003167] [G loss: -0.008950] [d1 loss: 0.053651] [d2 loss: 0.049863]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 580/676] [D loss: -0.004884] [G loss: -0.007070] [d1 loss: 0.106156] [d2 loss: 0.108890]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 133/500] [Batch 600/676] [D loss: -0.012623] [G loss: 0.020343] [d1 loss: 0.065373] [d2 loss: 0.051755]  [sq d1 d2: 0.000185]  [num0: 18.000000] [num1 46.000000]
[Epoch 133/500] [Batch 620/676] [D loss: -0.009132] [G loss: 0.022409] [d1 loss: 0.184327] [d2 loss: 0.149159]  [sq d1 d2: 0.001237]  [num0: 20.000000] [num1 44.000000]
[Epoch 133/500] [Batch 640/676] [D loss: -0.007244] [G loss: 0.043542] [d1 loss: 0.048963] [d2 loss: 0.054625]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 133/500] [Batch 660/676] [D loss: -0.044267] [G loss: 0.051737] [d1 loss: 0.071668] [d2 loss: 0.068682]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 0/676] [D loss: -0.029061] [G loss: 0.066833] [d1 loss: 0.084489] [d2 loss: 0.053932]  [sq d1 d2: 0.000934]  [num0: 15.000000] [num1 49.000000]
[Epoch 134/500] [Batch 20/676] [D loss: -0.020541] [G loss: 0.066803] [d1 loss: 0.069526] [d2 loss: 0.063816]  [sq d1 d2: 0.000033]  [num0: 12.000000] [num1 52.000000]
[Epoch 134/500] [Batch 40/676] [D loss: 0.020552] [G loss: 0.071613] [d1 loss: 0.092400] [d2 loss: 0.086797]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 60/676] [D loss: 0.008020] [G loss: 0.088780] [d1 loss: 0.102864] [d2 loss: 0.081479]  [sq d1 d2: 0.000457]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 80/676] [D loss: 0.033089] [G loss: 0.104501] [d1 loss: 0.084282] [d2 loss: 0.085526]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 134/500] [Batch 100/676] [D loss: 0.001247] [G loss: 0.101633] [d1 loss: 0.042853] [d2 loss: 0.041934]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 134/500] [Batch 120/676] [D loss: -0.006457] [G loss: 0.104574] [d1 loss: 0.170073] [d2 loss: 0.122573]  [sq d1 d2: 0.002256]  [num0: 18.000000] [num1 46.000000]
[Epoch 134/500] [Batch 140/676] [D loss: -0.024919] [G loss: 0.133791] [d1 loss: 0.095976] [d2 loss: 0.102108]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 160/676] [D loss: -0.032145] [G loss: 0.108676] [d1 loss: 0.029724] [d2 loss: 0.028047]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 180/676] [D loss: -0.036317] [G loss: 0.088019] [d1 loss: 0.122801] [d2 loss: 0.111614]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 134/500] [Batch 200/676] [D loss: -0.024061] [G loss: 0.068107] [d1 loss: 0.110265] [d2 loss: 0.095291]  [sq d1 d2: 0.000224]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 220/676] [D loss: 0.009662] [G loss: 0.056432] [d1 loss: 0.111549] [d2 loss: 0.100370]  [sq d1 d2: 0.000125]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 240/676] [D loss: 0.015350] [G loss: -0.011599] [d1 loss: 0.044911] [d2 loss: 0.038021]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 134/500] [Batch 260/676] [D loss: 0.001458] [G loss: -0.034463] [d1 loss: 0.077294] [d2 loss: 0.084450]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 280/676] [D loss: -0.022197] [G loss: -0.046573] [d1 loss: 0.073154] [d2 loss: 0.068453]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 300/676] [D loss: -0.003808] [G loss: -0.052523] [d1 loss: 0.059994] [d2 loss: 0.051096]  [sq d1 d2: 0.000079]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 320/676] [D loss: -0.011181] [G loss: -0.075510] [d1 loss: 0.088565] [d2 loss: 0.097216]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 340/676] [D loss: -0.004216] [G loss: -0.074213] [d1 loss: 0.136177] [d2 loss: 0.130210]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 360/676] [D loss: -0.021063] [G loss: -0.066220] [d1 loss: 0.048199] [d2 loss: 0.056331]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 380/676] [D loss: -0.038790] [G loss: -0.095924] [d1 loss: 0.095136] [d2 loss: 0.083727]  [sq d1 d2: 0.000130]  [num0: 13.000000] [num1 51.000000]
[Epoch 134/500] [Batch 400/676] [D loss: -0.008940] [G loss: -0.095685] [d1 loss: 0.195421] [d2 loss: 0.160866]  [sq d1 d2: 0.001194]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 420/676] [D loss: -0.011618] [G loss: -0.093188] [d1 loss: 0.109203] [d2 loss: 0.137651]  [sq d1 d2: 0.000809]  [num0: 14.000000] [num1 50.000000]

[Epoch 134/500] [Batch 440/676] [D loss: 0.001257] [G loss: -0.066442] [d1 loss: 0.016485] [d2 loss: 0.015638]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 460/676] [D loss: 0.009132] [G loss: -0.122465] [d1 loss: 0.057239] [d2 loss: 0.045380]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 134/500] [Batch 480/676] [D loss: -0.006406] [G loss: -0.086560] [d1 loss: 0.072485] [d2 loss: 0.097856]  [sq d1 d2: 0.000644]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 500/676] [D loss: -0.015827] [G loss: -0.065684] [d1 loss: 0.111970] [d2 loss: 0.134035]  [sq d1 d2: 0.000487]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 520/676] [D loss: -0.015572] [G loss: -0.088509] [d1 loss: 0.069443] [d2 loss: 0.072422]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 540/676] [D loss: -0.005615] [G loss: -0.138352] [d1 loss: 0.056522] [d2 loss: 0.050911]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 560/676] [D loss: -0.008712] [G loss: -0.190963] [d1 loss: 0.032356] [d2 loss: 0.029731]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 134/500] [Batch 580/676] [D loss: -0.008360] [G loss: -0.179797] [d1 loss: 0.103217] [d2 loss: 0.110558]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 134/500] [Batch 600/676] [D loss: -0.030249] [G loss: -0.176181] [d1 loss: 0.062842] [d2 loss: 0.065359]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 620/676] [D loss: -0.005820] [G loss: -0.218279] [d1 loss: 0.103512] [d2 loss: 0.119986]  [sq d1 d2: 0.000271]  [num0: 16.000000] [num1 48.000000]
[Epoch 134/500] [Batch 640/676] [D loss: 0.003279] [G loss: -0.228878] [d1 loss: 0.066990] [d2 loss: 0.052979]  [sq d1 d2: 0.000196]  [num0: 17.000000] [num1 47.000000]
[Epoch 134/500] [Batch 660/676] [D loss: -0.005745] [G loss: -0.225234] [d1 loss: 0.063337] [d2 loss: 0.046792]  [sq d1 d2: 0.000274]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 0/676] [D loss: -0.014751] [G loss: -0.200976] [d1 loss: 0.074672] [d2 loss: 0.075988]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 135/500] [Batch 20/676] [D loss: -0.010760] [G loss: -0.195168] [d1 loss: 0.054635] [d2 loss: 0.061457]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 135/500] [Batch 40/676] [D loss: -0.015433] [G loss: -0.160914] [d1 loss: 0.029648] [d2 loss: 0.024910]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 135/500] [Batch 60/676] [D loss: -0.028530] [G loss: -0.145667] [d1 loss: 0.044899] [d2 loss: 0.059506]  [sq d1 d2: 0.000213]  [num0: 19.000000] [num1 45.000000]
[Epoch 135/500] [Batch 80/676] [D loss: -0.029824] [G loss: -0.173092] [d1 loss: 0.069724] [d2 loss: 0.080513]  [sq d1 d2: 0.000116]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 100/676] [D loss: -0.021564] [G loss: -0.189299] [d1 loss: 0.031662] [d2 loss: 0.029505]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 120/676] [D loss: -0.011530] [G loss: -0.173489] [d1 loss: 0.039330] [d2 loss: 0.029641]  [sq d1 d2: 0.000094]  [num0: 10.000000] [num1 54.000000]
[Epoch 135/500] [Batch 140/676] [D loss: -0.012439] [G loss: -0.123003] [d1 loss: 0.079724] [d2 loss: 0.080661]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 160/676] [D loss: 0.018119] [G loss: -0.126177] [d1 loss: 0.042801] [d2 loss: 0.035151]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 180/676] [D loss: 0.011575] [G loss: -0.087704] [d1 loss: 0.047399] [d2 loss: 0.049195]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 200/676] [D loss: -0.003699] [G loss: -0.044334] [d1 loss: 0.048010] [d2 loss: 0.047794]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 135/500] [Batch 220/676] [D loss: -0.014680] [G loss: -0.017274] [d1 loss: 0.055890] [d2 loss: 0.038116]  [sq d1 d2: 0.000316]  [num0: 13.000000] [num1 51.000000]
[Epoch 135/500] [Batch 240/676] [D loss: -0.028966] [G loss: 0.036246] [d1 loss: 0.037094] [d2 loss: 0.039261]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 135/500] [Batch 260/676] [D loss: -0.035184] [G loss: 0.096074] [d1 loss: 0.060257] [d2 loss: 0.048692]  [sq d1 d2: 0.000134]  [num0: 19.000000] [num1 45.000000]
[Epoch 135/500] [Batch 280/676] [D loss: -0.045988] [G loss: 0.095878] [d1 loss: 0.025802] [d2 loss: 0.028385]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 135/500] [Batch 300/676] [D loss: -0.008347] [G loss: 0.103628] [d1 loss: 0.053898] [d2 loss: 0.051017]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 320/676] [D loss: -0.041321] [G loss: 0.134018] [d1 loss: 0.084627] [d2 loss: 0.079456]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 135/500] [Batch 340/676] [D loss: -0.032151] [G loss: 0.094343] [d1 loss: 0.039344] [d2 loss: 0.034516]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 135/500] [Batch 360/676] [D loss: -0.016955] [G loss: 0.057409] [d1 loss: 0.038256] [d2 loss: 0.035463]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 380/676] [D loss: -0.010912] [G loss: 0.031042] [d1 loss: 0.134213] [d2 loss: 0.139237]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 135/500] [Batch 400/676] [D loss: -0.017523] [G loss: 0.058105] [d1 loss: 0.152053] [d2 loss: 0.182697]  [sq d1 d2: 0.000939]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 420/676] [D loss: 0.002964] [G loss: 0.056274] [d1 loss: 0.198275] [d2 loss: 0.192716]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 135/500] [Batch 440/676] [D loss: -0.028549] [G loss: 0.056597] [d1 loss: 0.043028] [d2 loss: 0.041104]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 135/500] [Batch 460/676] [D loss: -0.029653] [G loss: 0.081069] [d1 loss: 0.022520] [d2 loss: 0.042582]  [sq d1 d2: 0.000402]  [num0: 13.000000] [num1 51.000000]
[Epoch 135/500] [Batch 480/676] [D loss: -0.054209] [G loss: 0.131849] [d1 loss: 0.035358] [d2 loss: 0.052180]  [sq d1 d2: 0.000283]  [num0: 13.000000] [num1 51.000000]
[Epoch 135/500] [Batch 500/676] [D loss: -0.060127] [G loss: 0.126657] [d1 loss: 0.057279] [d2 loss: 0.060175]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 520/676] [D loss: -0.062937] [G loss: 0.107883] [d1 loss: 0.069761] [d2 loss: 0.062928]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 135/500] [Batch 540/676] [D loss: -0.025385] [G loss: 0.070081] [d1 loss: 0.059995] [d2 loss: 0.067667]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 135/500] [Batch 560/676] [D loss: -0.027597] [G loss: 0.059095] [d1 loss: 0.153728] [d2 loss: 0.160474]  [sq d1 d2: 0.000046]  [num0: 12.000000] [num1 52.000000]
[Epoch 135/500] [Batch 580/676] [D loss: -0.006830] [G loss: 0.021804] [d1 loss: 0.058389] [d2 loss: 0.071306]  [sq d1 d2: 0.000167]  [num0: 17.000000] [num1 47.000000]
[Epoch 135/500] [Batch 600/676] [D loss: -0.002874] [G loss: 0.020675] [d1 loss: 0.163155] [d2 loss: 0.157485]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 620/676] [D loss: -0.003775] [G loss: 0.027250] [d1 loss: 0.060236] [d2 loss: 0.047194]  [sq d1 d2: 0.000170]  [num0: 15.000000] [num1 49.000000]
[Epoch 135/500] [Batch 640/676] [D loss: -0.022415] [G loss: 0.009031] [d1 loss: 0.073068] [d2 loss: 0.072303]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 135/500] [Batch 660/676] [D loss: -0.025152] [G loss: 0.007226] [d1 loss: 0.051822] [d2 loss: 0.048681]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 136/500] [Batch 0/676] [D loss: -0.003679] [G loss: -0.012445] [d1 loss: 0.101762] [d2 loss: 0.095636]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 136/500] [Batch 20/676] [D loss: -0.030074] [G loss: -0.036758] [d1 loss: 0.209858] [d2 loss: 0.157065]  [sq d1 d2: 0.002787]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 40/676] [D loss: -0.027600] [G loss: -0.045331] [d1 loss: 0.098326] [d2 loss: 0.098629]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 136/500] [Batch 60/676] [D loss: -0.018029] [G loss: -0.088423] [d1 loss: 0.106425] [d2 loss: 0.116672]  [sq d1 d2: 0.000105]  [num0: 18.000000] [num1 46.000000]
[Epoch 136/500] [Batch 80/676] [D loss: 0.018623] [G loss: -0.081010] [d1 loss: 0.115391] [d2 loss: 0.080695]  [sq d1 d2: 0.001204]  [num0: 14.000000] [num1 50.000000]
[Epoch 136/500] [Batch 100/676] [D loss: -0.020295] [G loss: -0.130215] [d1 loss: 0.068912] [d2 loss: 0.063832]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]

[Epoch 136/500] [Batch 120/676] [D loss: 0.005298] [G loss: -0.130697] [d1 loss: 0.044923] [d2 loss: 0.044838]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 136/500] [Batch 140/676] [D loss: -0.009596] [G loss: -0.136851] [d1 loss: 0.091157] [d2 loss: 0.090953]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 136/500] [Batch 160/676] [D loss: -0.000624] [G loss: -0.137747] [d1 loss: 0.087462] [d2 loss: 0.085740]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 136/500] [Batch 180/676] [D loss: -0.007632] [G loss: -0.168221] [d1 loss: 0.038428] [d2 loss: 0.038729]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 136/500] [Batch 200/676] [D loss: -0.003723] [G loss: -0.154005] [d1 loss: 0.058332] [d2 loss: 0.053939]  [sq d1 d2: 0.000019]  [num0: 19.000000] [num1 45.000000]
[Epoch 136/500] [Batch 220/676] [D loss: -0.024215] [G loss: -0.187769] [d1 loss: 0.057276] [d2 loss: 0.053038]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 136/500] [Batch 240/676] [D loss: -0.054116] [G loss: -0.250199] [d1 loss: 0.061958] [d2 loss: 0.053509]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 260/676] [D loss: -0.009564] [G loss: -0.268168] [d1 loss: 0.093559] [d2 loss: 0.085778]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 280/676] [D loss: -0.009471] [G loss: -0.292978] [d1 loss: 0.071669] [d2 loss: 0.069000]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 136/500] [Batch 300/676] [D loss: -0.009259] [G loss: -0.303514] [d1 loss: 0.036480] [d2 loss: 0.043665]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 320/676] [D loss: -0.017375] [G loss: -0.295823] [d1 loss: 0.029830] [d2 loss: 0.032223]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 136/500] [Batch 340/676] [D loss: -0.014383] [G loss: -0.252866] [d1 loss: 0.035315] [d2 loss: 0.047601]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 360/676] [D loss: 0.007698] [G loss: -0.242749] [d1 loss: 0.073069] [d2 loss: 0.072561]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 380/676] [D loss: 0.001714] [G loss: -0.190225] [d1 loss: 0.087479] [d2 loss: 0.075097]  [sq d1 d2: 0.000153]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 400/676] [D loss: -0.010883] [G loss: -0.115960] [d1 loss: 0.030472] [d2 loss: 0.035670]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 136/500] [Batch 420/676] [D loss: -0.016370] [G loss: -0.068091] [d1 loss: 0.049071] [d2 loss: 0.046193]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 136/500] [Batch 440/676] [D loss: -0.013634] [G loss: -0.061482] [d1 loss: 0.036759] [d2 loss: 0.036883]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 136/500] [Batch 460/676] [D loss: -0.007524] [G loss: -0.073830] [d1 loss: 0.007865] [d2 loss: 0.008139]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 136/500] [Batch 480/676] [D loss: -0.032774] [G loss: -0.079870] [d1 loss: 0.053263] [d2 loss: 0.056364]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 136/500] [Batch 500/676] [D loss: 0.002344] [G loss: -0.055262] [d1 loss: 0.010577] [d2 loss: 0.008280]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 136/500] [Batch 520/676] [D loss: -0.005980] [G loss: -0.066694] [d1 loss: 0.037040] [d2 loss: 0.044982]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 540/676] [D loss: -0.025943] [G loss: -0.089625] [d1 loss: 0.090804] [d2 loss: 0.066728]  [sq d1 d2: 0.000580]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 560/676] [D loss: -0.008275] [G loss: -0.013945] [d1 loss: 0.047676] [d2 loss: 0.051927]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 136/500] [Batch 580/676] [D loss: -0.006645] [G loss: 0.028174] [d1 loss: 0.079203] [d2 loss: 0.106662]  [sq d1 d2: 0.000754]  [num0: 20.000000] [num1 44.000000]
[Epoch 136/500] [Batch 600/676] [D loss: -0.023837] [G loss: 0.071863] [d1 loss: 0.069032] [d2 loss: 0.069634]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 136/500] [Batch 620/676] [D loss: -0.000189] [G loss: 0.101521] [d1 loss: 0.079775] [d2 loss: 0.048671]  [sq d1 d2: 0.000967]  [num0: 16.000000] [num1 48.000000]
[Epoch 136/500] [Batch 640/676] [D loss: -0.013066] [G loss: 0.121616] [d1 loss: 0.046468] [d2 loss: 0.042807]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 136/500] [Batch 660/676] [D loss: 0.002075] [G loss: 0.173315] [d1 loss: 0.047797] [d2 loss: 0.043220]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 137/500] [Batch 0/676] [D loss: -0.015253] [G loss: 0.151975] [d1 loss: 0.082215] [d2 loss: 0.076854]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 137/500] [Batch 20/676] [D loss: -0.015933] [G loss: 0.138195] [d1 loss: 0.037135] [d2 loss: 0.029697]  [sq d1 d2: 0.000055]  [num0: 18.000000] [num1 46.000000]
[Epoch 137/500] [Batch 40/676] [D loss: 0.001375] [G loss: 0.103062] [d1 loss: 0.128322] [d2 loss: 0.142451]  [sq d1 d2: 0.000200]  [num0: 13.000000] [num1 51.000000]
[Epoch 137/500] [Batch 60/676] [D loss: -0.031249] [G loss: 0.118237] [d1 loss: 0.039485] [d2 loss: 0.045776]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 80/676] [D loss: -0.011698] [G loss: 0.128441] [d1 loss: 0.029592] [d2 loss: 0.028729]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 137/500] [Batch 100/676] [D loss: -0.000589] [G loss: 0.117303] [d1 loss: 0.081599] [d2 loss: 0.088438]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 137/500] [Batch 120/676] [D loss: 0.003467] [G loss: 0.082316] [d1 loss: 0.050464] [d2 loss: 0.060624]  [sq d1 d2: 0.000103]  [num0: 13.000000] [num1 51.000000]
[Epoch 137/500] [Batch 140/676] [D loss: -0.010680] [G loss: 0.077308] [d1 loss: 0.059346] [d2 loss: 0.059025]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 137/500] [Batch 160/676] [D loss: -0.028881] [G loss: 0.075333] [d1 loss: 0.051218] [d2 loss: 0.049619]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 137/500] [Batch 180/676] [D loss: -0.026534] [G loss: 0.061405] [d1 loss: 0.092758] [d2 loss: 0.085415]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 137/500] [Batch 200/676] [D loss: -0.043848] [G loss: 0.024221] [d1 loss: 0.056662] [d2 loss: 0.057334]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 137/500] [Batch 220/676] [D loss: -0.048932] [G loss: -0.025594] [d1 loss: 0.067147] [d2 loss: 0.064955]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]
[Epoch 137/500] [Batch 240/676] [D loss: -0.016230] [G loss: -0.025024] [d1 loss: 0.058327] [d2 loss: 0.040539]  [sq d1 d2: 0.000316]  [num0: 12.000000] [num1 52.000000]
[Epoch 137/500] [Batch 260/676] [D loss: -0.016727] [G loss: -0.057625] [d1 loss: 0.038343] [d2 loss: 0.035437]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 280/676] [D loss: -0.012519] [G loss: -0.078031] [d1 loss: 0.086585] [d2 loss: 0.085834]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 137/500] [Batch 300/676] [D loss: -0.014707] [G loss: -0.094347] [d1 loss: 0.068448] [d2 loss: 0.075334]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 137/500] [Batch 320/676] [D loss: -0.006859] [G loss: -0.103339] [d1 loss: 0.087850] [d2 loss: 0.082202]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 340/676] [D loss: -0.020645] [G loss: -0.110584] [d1 loss: 0.079101] [d2 loss: 0.068783]  [sq d1 d2: 0.000106]  [num0: 18.000000] [num1 46.000000]
[Epoch 137/500] [Batch 360/676] [D loss: -0.013376] [G loss: -0.122188] [d1 loss: 0.133676] [d2 loss: 0.133901]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 137/500] [Batch 380/676] [D loss: -0.016435] [G loss: -0.152478] [d1 loss: 0.027896] [d2 loss: 0.023059]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 137/500] [Batch 400/676] [D loss: -0.022210] [G loss: -0.153785] [d1 loss: 0.076484] [d2 loss: 0.065712]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 137/500] [Batch 420/676] [D loss: -0.038711] [G loss: -0.195119] [d1 loss: 0.090475] [d2 loss: 0.080798]  [sq d1 d2: 0.000094]  [num0: 11.000000] [num1 53.000000]

[Epoch 137/500] [Batch 440/676] [D loss: -0.032659] [G loss: -0.243604] [d1 loss: 0.070703] [d2 loss: 0.061748]  [sq d1 d2: 0.000080]  [num0: 18.000000] [num1 46.000000]
[Epoch 137/500] [Batch 460/676] [D loss: -0.039854] [G loss: -0.268291] [d1 loss: 0.029357] [d2 loss: 0.032894]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 480/676] [D loss: -0.001577] [G loss: -0.283899] [d1 loss: 0.129766] [d2 loss: 0.138606]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 500/676] [D loss: -0.025123] [G loss: -0.256997] [d1 loss: 0.096122] [d2 loss: 0.106547]  [sq d1 d2: 0.000109]  [num0: 14.000000] [num1 50.000000]
[Epoch 137/500] [Batch 520/676] [D loss: 0.001404] [G loss: -0.230553] [d1 loss: 0.052499] [d2 loss: 0.042904]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 540/676] [D loss: 0.018266] [G loss: -0.167195] [d1 loss: 0.072056] [d2 loss: 0.089706]  [sq d1 d2: 0.000312]  [num0: 15.000000] [num1 49.000000]
[Epoch 137/500] [Batch 560/676] [D loss: -0.015465] [G loss: -0.100354] [d1 loss: 0.110566] [d2 loss: 0.096646]  [sq d1 d2: 0.000194]  [num0: 17.000000] [num1 47.000000]
[Epoch 137/500] [Batch 580/676] [D loss: -0.021656] [G loss: -0.023908] [d1 loss: 0.052566] [d2 loss: 0.053461]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 137/500] [Batch 600/676] [D loss: -0.022101] [G loss: -0.004919] [d1 loss: 0.055314] [d2 loss: 0.054740]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 137/500] [Batch 620/676] [D loss: -0.020735] [G loss: -0.008422] [d1 loss: 0.078805] [d2 loss: 0.092100]  [sq d1 d2: 0.000177]  [num0: 16.000000] [num1 48.000000]
[Epoch 137/500] [Batch 640/676] [D loss: -0.025918] [G loss: 0.001549] [d1 loss: 0.081070] [d2 loss: 0.080319]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 137/500] [Batch 660/676] [D loss: -0.023179] [G loss: 0.010475] [d1 loss: 0.134831] [d2 loss: 0.147334]  [sq d1 d2: 0.000156]  [num0: 13.000000] [num1 51.000000]
[Epoch 138/500] [Batch 0/676] [D loss: -0.014314] [G loss: 0.036830] [d1 loss: 0.046401] [d2 loss: 0.045233]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 138/500] [Batch 20/676] [D loss: 0.006640] [G loss: 0.029758] [d1 loss: 0.104628] [d2 loss: 0.104117]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 40/676] [D loss: -0.004139] [G loss: 0.062044] [d1 loss: 0.030229] [d2 loss: 0.035716]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 60/676] [D loss: -0.000799] [G loss: 0.019167] [d1 loss: 0.053392] [d2 loss: 0.046889]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 80/676] [D loss: -0.013152] [G loss: -0.008540] [d1 loss: 0.115740] [d2 loss: 0.141842]  [sq d1 d2: 0.000681]  [num0: 14.000000] [num1 50.000000]
[Epoch 138/500] [Batch 100/676] [D loss: -0.004222] [G loss: -0.001932] [d1 loss: 0.135390] [d2 loss: 0.124780]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 120/676] [D loss: -0.013502] [G loss: -0.010735] [d1 loss: 0.069891] [d2 loss: 0.084410]  [sq d1 d2: 0.000211]  [num0: 14.000000] [num1 50.000000]
[Epoch 138/500] [Batch 140/676] [D loss: -0.022856] [G loss: -0.014091] [d1 loss: 0.071123] [d2 loss: 0.088070]  [sq d1 d2: 0.000287]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 160/676] [D loss: -0.021539] [G loss: 0.003338] [d1 loss: 0.064082] [d2 loss: 0.060469]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 138/500] [Batch 180/676] [D loss: -0.020585] [G loss: -0.053283] [d1 loss: 0.022514] [d2 loss: 0.020096]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 200/676] [D loss: -0.003539] [G loss: -0.057227] [d1 loss: 0.035873] [d2 loss: 0.039805]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 220/676] [D loss: -0.007242] [G loss: -0.049109] [d1 loss: 0.087081] [d2 loss: 0.102066]  [sq d1 d2: 0.000225]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 240/676] [D loss: -0.001231] [G loss: -0.044297] [d1 loss: 0.055841] [d2 loss: 0.052471]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 138/500] [Batch 260/676] [D loss: -0.005151] [G loss: -0.054383] [d1 loss: 0.171540] [d2 loss: 0.098237]  [sq d1 d2: 0.005373]  [num0: 15.000000] [num1 49.000000]
[Epoch 138/500] [Batch 280/676] [D loss: 0.006035] [G loss: -0.038753] [d1 loss: 0.092902] [d2 loss: 0.097455]  [sq d1 d2: 0.000021]  [num0: 20.000000] [num1 44.000000]
[Epoch 138/500] [Batch 300/676] [D loss: -0.006354] [G loss: -0.024403] [d1 loss: 0.029117] [d2 loss: 0.033695]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 320/676] [D loss: -0.015151] [G loss: 0.007638] [d1 loss: 0.082961] [d2 loss: 0.071065]  [sq d1 d2: 0.000142]  [num0: 10.000000] [num1 54.000000]
[Epoch 138/500] [Batch 340/676] [D loss: -0.006648] [G loss: 0.008873] [d1 loss: 0.020339] [d2 loss: 0.014219]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 360/676] [D loss: -0.025458] [G loss: 0.032374] [d1 loss: 0.079070] [d2 loss: 0.066366]  [sq d1 d2: 0.000161]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 380/676] [D loss: -0.012312] [G loss: 0.058182] [d1 loss: 0.081091] [d2 loss: 0.067872]  [sq d1 d2: 0.000175]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 400/676] [D loss: -0.023607] [G loss: 0.054957] [d1 loss: 0.110914] [d2 loss: 0.101502]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 420/676] [D loss: -0.011901] [G loss: 0.035646] [d1 loss: 0.055891] [d2 loss: 0.050795]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 440/676] [D loss: 0.007636] [G loss: -0.007823] [d1 loss: 0.084363] [d2 loss: 0.088368]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 460/676] [D loss: -0.011063] [G loss: -0.038529] [d1 loss: 0.052483] [d2 loss: 0.045166]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 138/500] [Batch 480/676] [D loss: -0.008948] [G loss: -0.053594] [d1 loss: 0.043338] [d2 loss: 0.037530]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 138/500] [Batch 500/676] [D loss: -0.009125] [G loss: -0.079888] [d1 loss: 0.061840] [d2 loss: 0.063403]  [sq d1 d2: 0.000002]  [num0: 21.000000] [num1 43.000000]
[Epoch 138/500] [Batch 520/676] [D loss: -0.002720] [G loss: -0.095380] [d1 loss: 0.064598] [d2 loss: 0.061840]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 138/500] [Batch 540/676] [D loss: -0.014582] [G loss: -0.105716] [d1 loss: 0.092054] [d2 loss: 0.110732]  [sq d1 d2: 0.000349]  [num0: 16.000000] [num1 48.000000]
[Epoch 138/500] [Batch 560/676] [D loss: -0.013156] [G loss: -0.134246] [d1 loss: 0.094011] [d2 loss: 0.106927]  [sq d1 d2: 0.000167]  [num0: 14.000000] [num1 50.000000]
[Epoch 138/500] [Batch 580/676] [D loss: -0.027492] [G loss: -0.138217] [d1 loss: 0.159673] [d2 loss: 0.141162]  [sq d1 d2: 0.000343]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 600/676] [D loss: -0.017003] [G loss: -0.144210] [d1 loss: 0.066136] [d2 loss: 0.066392]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 138/500] [Batch 620/676] [D loss: -0.026553] [G loss: -0.169250] [d1 loss: 0.042175] [d2 loss: 0.039662]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 138/500] [Batch 640/676] [D loss: -0.019499] [G loss: -0.192102] [d1 loss: 0.102637] [d2 loss: 0.118220]  [sq d1 d2: 0.000243]  [num0: 19.000000] [num1 45.000000]
[Epoch 138/500] [Batch 660/676] [D loss: -0.014050] [G loss: -0.189831] [d1 loss: 0.056772] [d2 loss: 0.059393]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 0/676] [D loss: -0.015311] [G loss: -0.177061] [d1 loss: 0.061723] [d2 loss: 0.052568]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 20/676] [D loss: -0.018313] [G loss: -0.163978] [d1 loss: 0.089863] [d2 loss: 0.084520]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 139/500] [Batch 40/676] [D loss: -0.009159] [G loss: -0.140767] [d1 loss: 0.057941] [d2 loss: 0.065837]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 139/500] [Batch 60/676] [D loss: -0.017199] [G loss: -0.098333] [d1 loss: 0.088076] [d2 loss: 0.080464]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 139/500] [Batch 80/676] [D loss: -0.008969] [G loss: -0.107622] [d1 loss: 0.137725] [d2 loss: 0.115311]  [sq d1 d2: 0.000502]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 100/676] [D loss: -0.005778] [G loss: -0.104375] [d1 loss: 0.052458] [d2 loss: 0.053223]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]

[Epoch 139/500] [Batch 120/676] [D loss: -0.007660] [G loss: -0.136994] [d1 loss: 0.130382] [d2 loss: 0.112471]  [sq d1 d2: 0.000321]  [num0: 12.000000] [num1 52.000000]
[Epoch 139/500] [Batch 140/676] [D loss: -0.008156] [G loss: -0.107904] [d1 loss: 0.119263] [d2 loss: 0.109933]  [sq d1 d2: 0.000087]  [num0: 13.000000] [num1 51.000000]
[Epoch 139/500] [Batch 160/676] [D loss: -0.017861] [G loss: -0.098251] [d1 loss: 0.060564] [d2 loss: 0.044946]  [sq d1 d2: 0.000244]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 180/676] [D loss: -0.026674] [G loss: -0.138200] [d1 loss: 0.022733] [d2 loss: 0.019490]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 139/500] [Batch 200/676] [D loss: -0.015582] [G loss: -0.127094] [d1 loss: 0.070325] [d2 loss: 0.074009]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 220/676] [D loss: -0.003947] [G loss: -0.136195] [d1 loss: 0.029888] [d2 loss: 0.025354]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 139/500] [Batch 240/676] [D loss: -0.019276] [G loss: -0.109317] [d1 loss: 0.061256] [d2 loss: 0.067520]  [sq d1 d2: 0.000039]  [num0: 11.000000] [num1 53.000000]
[Epoch 139/500] [Batch 260/676] [D loss: -0.024362] [G loss: -0.139324] [d1 loss: 0.096268] [d2 loss: 0.086864]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 139/500] [Batch 280/676] [D loss: -0.013428] [G loss: -0.138934] [d1 loss: 0.039323] [d2 loss: 0.050108]  [sq d1 d2: 0.000116]  [num0: 18.000000] [num1 46.000000]
[Epoch 139/500] [Batch 300/676] [D loss: -0.022187] [G loss: -0.137087] [d1 loss: 0.057557] [d2 loss: 0.059800]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 139/500] [Batch 320/676] [D loss: -0.006121] [G loss: -0.124400] [d1 loss: 0.070138] [d2 loss: 0.069648]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 340/676] [D loss: -0.029562] [G loss: -0.139347] [d1 loss: 0.086866] [d2 loss: 0.079328]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 360/676] [D loss: -0.029650] [G loss: -0.136752] [d1 loss: 0.032017] [d2 loss: 0.024182]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 139/500] [Batch 380/676] [D loss: -0.018217] [G loss: -0.131051] [d1 loss: 0.051464] [d2 loss: 0.060084]  [sq d1 d2: 0.000074]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 400/676] [D loss: -0.016515] [G loss: -0.107823] [d1 loss: 0.054393] [d2 loss: 0.064795]  [sq d1 d2: 0.000108]  [num0: 19.000000] [num1 45.000000]
[Epoch 139/500] [Batch 420/676] [D loss: 0.001975] [G loss: -0.137018] [d1 loss: 0.055890] [d2 loss: 0.055338]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 139/500] [Batch 440/676] [D loss: -0.012347] [G loss: -0.100996] [d1 loss: 0.026080] [d2 loss: 0.024213]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 460/676] [D loss: -0.030012] [G loss: -0.067969] [d1 loss: 0.084075] [d2 loss: 0.073589]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 480/676] [D loss: -0.030301] [G loss: -0.059917] [d1 loss: 0.033398] [d2 loss: 0.043919]  [sq d1 d2: 0.000111]  [num0: 10.000000] [num1 54.000000]
[Epoch 139/500] [Batch 500/676] [D loss: -0.031242] [G loss: -0.042384] [d1 loss: 0.069263] [d2 loss: 0.069457]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 139/500] [Batch 520/676] [D loss: -0.022507] [G loss: -0.061466] [d1 loss: 0.053802] [d2 loss: 0.046491]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 139/500] [Batch 540/676] [D loss: -0.032515] [G loss: -0.016521] [d1 loss: 0.047228] [d2 loss: 0.044684]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 139/500] [Batch 560/676] [D loss: -0.018420] [G loss: -0.030903] [d1 loss: 0.112929] [d2 loss: 0.092775]  [sq d1 d2: 0.000406]  [num0: 18.000000] [num1 46.000000]
[Epoch 139/500] [Batch 580/676] [D loss: -0.010623] [G loss: 0.004926] [d1 loss: 0.079746] [d2 loss: 0.103570]  [sq d1 d2: 0.000568]  [num0: 17.000000] [num1 47.000000]
[Epoch 139/500] [Batch 600/676] [D loss: -0.024411] [G loss: 0.009276] [d1 loss: 0.199495] [d2 loss: 0.173231]  [sq d1 d2: 0.000690]  [num0: 18.000000] [num1 46.000000]
[Epoch 139/500] [Batch 620/676] [D loss: -0.020469] [G loss: 0.023439] [d1 loss: 0.107739] [d2 loss: 0.092194]  [sq d1 d2: 0.000242]  [num0: 19.000000] [num1 45.000000]
[Epoch 139/500] [Batch 640/676] [D loss: -0.008276] [G loss: 0.024608] [d1 loss: 0.049750] [d2 loss: 0.030198]  [sq d1 d2: 0.000382]  [num0: 13.000000] [num1 51.000000]
[Epoch 139/500] [Batch 660/676] [D loss: -0.013618] [G loss: 0.017421] [d1 loss: 0.036531] [d2 loss: 0.026042]  [sq d1 d2: 0.000110]  [num0: 19.000000] [num1 45.000000]
[Epoch 140/500] [Batch 0/676] [D loss: -0.021841] [G loss: 0.035723] [d1 loss: 0.161271] [d2 loss: 0.162381]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 20/676] [D loss: -0.012617] [G loss: 0.000245] [d1 loss: 0.077869] [d2 loss: 0.090878]  [sq d1 d2: 0.000169]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 40/676] [D loss: -0.006759] [G loss: 0.001919] [d1 loss: 0.118972] [d2 loss: 0.119158]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 140/500] [Batch 60/676] [D loss: -0.042630] [G loss: -0.000127] [d1 loss: 0.094031] [d2 loss: 0.080751]  [sq d1 d2: 0.000176]  [num0: 19.000000] [num1 45.000000]
[Epoch 140/500] [Batch 80/676] [D loss: -0.012617] [G loss: -0.009750] [d1 loss: 0.096317] [d2 loss: 0.122117]  [sq d1 d2: 0.000666]  [num0: 13.000000] [num1 51.000000]
[Epoch 140/500] [Batch 100/676] [D loss: -0.004704] [G loss: -0.042544] [d1 loss: 0.032645] [d2 loss: 0.037342]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 140/500] [Batch 120/676] [D loss: -0.027175] [G loss: -0.065381] [d1 loss: 0.080975] [d2 loss: 0.069782]  [sq d1 d2: 0.000125]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 140/676] [D loss: -0.006334] [G loss: -0.090677] [d1 loss: 0.107392] [d2 loss: 0.101413]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 140/500] [Batch 160/676] [D loss: -0.022117] [G loss: -0.082959] [d1 loss: 0.038626] [d2 loss: 0.030762]  [sq d1 d2: 0.000062]  [num0: 12.000000] [num1 52.000000]
[Epoch 140/500] [Batch 180/676] [D loss: -0.008464] [G loss: -0.100068] [d1 loss: 0.109121] [d2 loss: 0.116495]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 200/676] [D loss: -0.007080] [G loss: -0.144145] [d1 loss: 0.124809] [d2 loss: 0.133234]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 220/676] [D loss: -0.045047] [G loss: -0.174818] [d1 loss: 0.167485] [d2 loss: 0.145851]  [sq d1 d2: 0.000468]  [num0: 16.000000] [num1 48.000000]
[Epoch 140/500] [Batch 240/676] [D loss: -0.059855] [G loss: -0.209616] [d1 loss: 0.065737] [d2 loss: 0.049475]  [sq d1 d2: 0.000264]  [num0: 18.000000] [num1 46.000000]
[Epoch 140/500] [Batch 260/676] [D loss: -0.042765] [G loss: -0.244413] [d1 loss: 0.070945] [d2 loss: 0.084431]  [sq d1 d2: 0.000182]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 280/676] [D loss: -0.033351] [G loss: -0.251185] [d1 loss: 0.138883] [d2 loss: 0.146477]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 300/676] [D loss: -0.034529] [G loss: -0.209439] [d1 loss: 0.053075] [d2 loss: 0.053331]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 140/500] [Batch 320/676] [D loss: -0.021011] [G loss: -0.211548] [d1 loss: 0.087577] [d2 loss: 0.082741]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 140/500] [Batch 340/676] [D loss: -0.007340] [G loss: -0.143248] [d1 loss: 0.115674] [d2 loss: 0.123959]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 360/676] [D loss: -0.009981] [G loss: -0.096749] [d1 loss: 0.078563] [d2 loss: 0.096967]  [sq d1 d2: 0.000339]  [num0: 21.000000] [num1 43.000000]
[Epoch 140/500] [Batch 380/676] [D loss: -0.006488] [G loss: -0.059070] [d1 loss: 0.101856] [d2 loss: 0.093250]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 400/676] [D loss: -0.000964] [G loss: -0.045489] [d1 loss: 0.097208] [d2 loss: 0.081749]  [sq d1 d2: 0.000239]  [num0: 18.000000] [num1 46.000000]

[Epoch 140/500] [Batch 420/676] [D loss: -0.021977] [G loss: -0.052124] [d1 loss: 0.099659] [d2 loss: 0.119584]  [sq d1 d2: 0.000397]  [num0: 17.000000] [num1 47.000000]
[Epoch 140/500] [Batch 440/676] [D loss: -0.034353] [G loss: -0.017466] [d1 loss: 0.073778] [d2 loss: 0.049447]  [sq d1 d2: 0.000592]  [num0: 13.000000] [num1 51.000000]
[Epoch 140/500] [Batch 460/676] [D loss: -0.030807] [G loss: -0.016065] [d1 loss: 0.068431] [d2 loss: 0.079398]  [sq d1 d2: 0.000120]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 480/676] [D loss: -0.037375] [G loss: -0.023823] [d1 loss: 0.110257] [d2 loss: 0.130929]  [sq d1 d2: 0.000427]  [num0: 18.000000] [num1 46.000000]
[Epoch 140/500] [Batch 500/676] [D loss: -0.016627] [G loss: -0.047103] [d1 loss: 0.105026] [d2 loss: 0.115330]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 140/500] [Batch 520/676] [D loss: -0.051006] [G loss: -0.048557] [d1 loss: 0.033740] [d2 loss: 0.046799]  [sq d1 d2: 0.000171]  [num0: 16.000000] [num1 48.000000]
[Epoch 140/500] [Batch 540/676] [D loss: -0.035525] [G loss: -0.082091] [d1 loss: 0.092726] [d2 loss: 0.087533]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 560/676] [D loss: 0.016692] [G loss: -0.093263] [d1 loss: 0.069771] [d2 loss: 0.083005]  [sq d1 d2: 0.000175]  [num0: 18.000000] [num1 46.000000]
[Epoch 140/500] [Batch 580/676] [D loss: -0.019199] [G loss: -0.120740] [d1 loss: 0.075393] [d2 loss: 0.079162]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 140/500] [Batch 600/676] [D loss: -0.005717] [G loss: -0.098659] [d1 loss: 0.058566] [d2 loss: 0.077506]  [sq d1 d2: 0.000359]  [num0: 15.000000] [num1 49.000000]
[Epoch 140/500] [Batch 620/676] [D loss: -0.003366] [G loss: -0.099646] [d1 loss: 0.130749] [d2 loss: 0.135131]  [sq d1 d2: 0.000019]  [num0: 19.000000] [num1 45.000000]
[Epoch 140/500] [Batch 640/676] [D loss: -0.004356] [G loss: -0.081093] [d1 loss: 0.055438] [d2 loss: 0.047502]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 140/500] [Batch 660/676] [D loss: -0.009832] [G loss: -0.092256] [d1 loss: 0.062942] [d2 loss: 0.074184]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 141/500] [Batch 0/676] [D loss: -0.024057] [G loss: -0.104691] [d1 loss: 0.115316] [d2 loss: 0.104449]  [sq d1 d2: 0.000118]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 20/676] [D loss: -0.041677] [G loss: -0.128667] [d1 loss: 0.043771] [d2 loss: 0.042130]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 141/500] [Batch 40/676] [D loss: -0.024790] [G loss: -0.177963] [d1 loss: 0.053328] [d2 loss: 0.050102]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 60/676] [D loss: -0.046788] [G loss: -0.170210] [d1 loss: 0.080065] [d2 loss: 0.074015]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 80/676] [D loss: -0.040537] [G loss: -0.195469] [d1 loss: 0.058088] [d2 loss: 0.065615]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 100/676] [D loss: -0.039921] [G loss: -0.138941] [d1 loss: 0.177878] [d2 loss: 0.161116]  [sq d1 d2: 0.000281]  [num0: 19.000000] [num1 45.000000]
[Epoch 141/500] [Batch 120/676] [D loss: 0.018377] [G loss: -0.152925] [d1 loss: 0.035332] [d2 loss: 0.037637]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 140/676] [D loss: 0.011963] [G loss: -0.101273] [d1 loss: 0.110334] [d2 loss: 0.111740]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 160/676] [D loss: -0.002184] [G loss: -0.066327] [d1 loss: 0.129087] [d2 loss: 0.153909]  [sq d1 d2: 0.000616]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 180/676] [D loss: -0.007831] [G loss: -0.015297] [d1 loss: 0.120371] [d2 loss: 0.101758]  [sq d1 d2: 0.000346]  [num0: 12.000000] [num1 52.000000]
[Epoch 141/500] [Batch 200/676] [D loss: -0.001402] [G loss: -0.000205] [d1 loss: 0.113768] [d2 loss: 0.083492]  [sq d1 d2: 0.000917]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 220/676] [D loss: -0.013321] [G loss: 0.016872] [d1 loss: 0.075478] [d2 loss: 0.065673]  [sq d1 d2: 0.000096]  [num0: 17.000000] [num1 47.000000]
[Epoch 141/500] [Batch 240/676] [D loss: -0.002380] [G loss: 0.034437] [d1 loss: 0.038140] [d2 loss: 0.040936]  [sq d1 d2: 0.000008]  [num0: 20.000000] [num1 44.000000]
[Epoch 141/500] [Batch 260/676] [D loss: -0.022156] [G loss: 0.045855] [d1 loss: 0.123600] [d2 loss: 0.114929]  [sq d1 d2: 0.000075]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 280/676] [D loss: -0.034032] [G loss: 0.053380] [d1 loss: 0.088855] [d2 loss: 0.081158]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 300/676] [D loss: -0.042966] [G loss: 0.039434] [d1 loss: 0.082814] [d2 loss: 0.095899]  [sq d1 d2: 0.000171]  [num0: 12.000000] [num1 52.000000]
[Epoch 141/500] [Batch 320/676] [D loss: -0.041453] [G loss: 0.017680] [d1 loss: 0.089692] [d2 loss: 0.088196]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 340/676] [D loss: -0.000271] [G loss: 0.009431] [d1 loss: 0.043161] [d2 loss: 0.041018]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 360/676] [D loss: 0.004975] [G loss: -0.045445] [d1 loss: 0.040472] [d2 loss: 0.043472]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 380/676] [D loss: -0.000898] [G loss: -0.002425] [d1 loss: 0.101541] [d2 loss: 0.097593]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 400/676] [D loss: -0.000320] [G loss: -0.029257] [d1 loss: 0.094598] [d2 loss: 0.092631]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 141/500] [Batch 420/676] [D loss: 0.009456] [G loss: -0.037000] [d1 loss: 0.059503] [d2 loss: 0.057420]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 141/500] [Batch 440/676] [D loss: -0.002122] [G loss: -0.037539] [d1 loss: 0.056865] [d2 loss: 0.078889]  [sq d1 d2: 0.000485]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 460/676] [D loss: -0.006512] [G loss: -0.047803] [d1 loss: 0.059881] [d2 loss: 0.067453]  [sq d1 d2: 0.000057]  [num0: 19.000000] [num1 45.000000]
[Epoch 141/500] [Batch 480/676] [D loss: -0.012258] [G loss: -0.063831] [d1 loss: 0.025307] [d2 loss: 0.044241]  [sq d1 d2: 0.000359]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 500/676] [D loss: -0.016124] [G loss: -0.097699] [d1 loss: 0.036299] [d2 loss: 0.039783]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 141/500] [Batch 520/676] [D loss: -0.029979] [G loss: -0.138910] [d1 loss: 0.059728] [d2 loss: 0.052914]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 141/500] [Batch 540/676] [D loss: -0.050965] [G loss: -0.205182] [d1 loss: 0.033179] [d2 loss: 0.039567]  [sq d1 d2: 0.000041]  [num0: 19.000000] [num1 45.000000]
[Epoch 141/500] [Batch 560/676] [D loss: -0.024606] [G loss: -0.205565] [d1 loss: 0.095933] [d2 loss: 0.097223]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 141/500] [Batch 580/676] [D loss: -0.040294] [G loss: -0.255645] [d1 loss: 0.024994] [d2 loss: 0.022078]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 600/676] [D loss: -0.004529] [G loss: -0.251772] [d1 loss: 0.054087] [d2 loss: 0.065919]  [sq d1 d2: 0.000140]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 620/676] [D loss: 0.009376] [G loss: -0.201561] [d1 loss: 0.078793] [d2 loss: 0.076687]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 141/500] [Batch 640/676] [D loss: 0.022356] [G loss: -0.164996] [d1 loss: 0.166476] [d2 loss: 0.164523]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 141/500] [Batch 660/676] [D loss: 0.008740] [G loss: -0.080047] [d1 loss: 0.099853] [d2 loss: 0.112627]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 142/500] [Batch 0/676] [D loss: -0.004418] [G loss: -0.029888] [d1 loss: 0.089804] [d2 loss: 0.076018]  [sq d1 d2: 0.000190]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 20/676] [D loss: -0.020072] [G loss: 0.007122] [d1 loss: 0.106054] [d2 loss: 0.100656]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]

[Epoch 142/500] [Batch 40/676] [D loss: -0.026005] [G loss: 0.033998] [d1 loss: 0.057342] [d2 loss: 0.057580]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 60/676] [D loss: -0.027152] [G loss: 0.065252] [d1 loss: 0.129627] [d2 loss: 0.131664]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 80/676] [D loss: -0.038890] [G loss: 0.081433] [d1 loss: 0.060327] [d2 loss: 0.051678]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 142/500] [Batch 100/676] [D loss: -0.043377] [G loss: 0.109915] [d1 loss: 0.040460] [d2 loss: 0.041252]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 142/500] [Batch 120/676] [D loss: -0.020933] [G loss: 0.095489] [d1 loss: 0.102473] [d2 loss: 0.143283]  [sq d1 d2: 0.001666]  [num0: 11.000000] [num1 53.000000]
[Epoch 142/500] [Batch 140/676] [D loss: -0.024733] [G loss: 0.097601] [d1 loss: 0.054913] [d2 loss: 0.057934]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 160/676] [D loss: 0.015655] [G loss: 0.066123] [d1 loss: 0.035867] [d2 loss: 0.031541]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 142/500] [Batch 180/676] [D loss: 0.032919] [G loss: 0.052934] [d1 loss: 0.085240] [d2 loss: 0.069253]  [sq d1 d2: 0.000256]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 200/676] [D loss: -0.010966] [G loss: 0.038227] [d1 loss: 0.099909] [d2 loss: 0.085285]  [sq d1 d2: 0.000214]  [num0: 17.000000] [num1 47.000000]
[Epoch 142/500] [Batch 220/676] [D loss: -0.005714] [G loss: 0.009648] [d1 loss: 0.070068] [d2 loss: 0.060159]  [sq d1 d2: 0.000098]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 240/676] [D loss: 0.000693] [G loss: -0.009392] [d1 loss: 0.106383] [d2 loss: 0.122041]  [sq d1 d2: 0.000245]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 260/676] [D loss: -0.025579] [G loss: -0.040930] [d1 loss: 0.081887] [d2 loss: 0.061439]  [sq d1 d2: 0.000418]  [num0: 17.000000] [num1 47.000000]
[Epoch 142/500] [Batch 280/676] [D loss: -0.017742] [G loss: -0.093650] [d1 loss: 0.068506] [d2 loss: 0.081935]  [sq d1 d2: 0.000180]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 300/676] [D loss: -0.035477] [G loss: -0.106109] [d1 loss: 0.124275] [d2 loss: 0.111375]  [sq d1 d2: 0.000166]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 320/676] [D loss: -0.027419] [G loss: -0.140603] [d1 loss: 0.114104] [d2 loss: 0.086939]  [sq d1 d2: 0.000738]  [num0: 15.000000] [num1 49.000000]
[Epoch 142/500] [Batch 340/676] [D loss: -0.015431] [G loss: -0.155361] [d1 loss: 0.049586] [d2 loss: 0.037045]  [sq d1 d2: 0.000157]  [num0: 15.000000] [num1 49.000000]
[Epoch 142/500] [Batch 360/676] [D loss: 0.011826] [G loss: -0.175175] [d1 loss: 0.095962] [d2 loss: 0.100953]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 380/676] [D loss: -0.007505] [G loss: -0.133516] [d1 loss: 0.037420] [d2 loss: 0.029392]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 400/676] [D loss: -0.005581] [G loss: -0.122042] [d1 loss: 0.051613] [d2 loss: 0.055030]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 420/676] [D loss: 0.002044] [G loss: -0.070703] [d1 loss: 0.195318] [d2 loss: 0.190579]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 440/676] [D loss: -0.007639] [G loss: -0.035813] [d1 loss: 0.070441] [d2 loss: 0.081552]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 460/676] [D loss: -0.023488] [G loss: 0.017124] [d1 loss: 0.075598] [d2 loss: 0.086919]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 480/676] [D loss: -0.033259] [G loss: 0.007875] [d1 loss: 0.133666] [d2 loss: 0.097693]  [sq d1 d2: 0.001294]  [num0: 18.000000] [num1 46.000000]
[Epoch 142/500] [Batch 500/676] [D loss: -0.036299] [G loss: 0.016154] [d1 loss: 0.079761] [d2 loss: 0.091833]  [sq d1 d2: 0.000146]  [num0: 15.000000] [num1 49.000000]
[Epoch 142/500] [Batch 520/676] [D loss: -0.034058] [G loss: 0.052363] [d1 loss: 0.063375] [d2 loss: 0.048881]  [sq d1 d2: 0.000210]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 540/676] [D loss: -0.023100] [G loss: 0.045986] [d1 loss: 0.050918] [d2 loss: 0.049820]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 560/676] [D loss: -0.031037] [G loss: 0.028168] [d1 loss: 0.103044] [d2 loss: 0.137318]  [sq d1 d2: 0.001175]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 580/676] [D loss: 0.017115] [G loss: -0.015167] [d1 loss: 0.041074] [d2 loss: 0.052201]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 142/500] [Batch 600/676] [D loss: 0.007972] [G loss: -0.029219] [d1 loss: 0.034376] [d2 loss: 0.048985]  [sq d1 d2: 0.000213]  [num0: 17.000000] [num1 47.000000]
[Epoch 142/500] [Batch 620/676] [D loss: -0.000955] [G loss: -0.074794] [d1 loss: 0.064512] [d2 loss: 0.060345]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 142/500] [Batch 640/676] [D loss: -0.007068] [G loss: -0.099755] [d1 loss: 0.075159] [d2 loss: 0.064405]  [sq d1 d2: 0.000116]  [num0: 16.000000] [num1 48.000000]
[Epoch 142/500] [Batch 660/676] [D loss: -0.008917] [G loss: -0.119683] [d1 loss: 0.088118] [d2 loss: 0.096941]  [sq d1 d2: 0.000078]  [num0: 13.000000] [num1 51.000000]
[Epoch 143/500] [Batch 0/676] [D loss: -0.019390] [G loss: -0.123478] [d1 loss: 0.056397] [d2 loss: 0.063416]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 143/500] [Batch 20/676] [D loss: -0.006958] [G loss: -0.163360] [d1 loss: 0.099068] [d2 loss: 0.112215]  [sq d1 d2: 0.000173]  [num0: 11.000000] [num1 53.000000]
[Epoch 143/500] [Batch 40/676] [D loss: -0.043510] [G loss: -0.188612] [d1 loss: 0.096927] [d2 loss: 0.092596]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 143/500] [Batch 60/676] [D loss: -0.016113] [G loss: -0.155727] [d1 loss: 0.155218] [d2 loss: 0.142538]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 143/500] [Batch 80/676] [D loss: -0.007360] [G loss: -0.193594] [d1 loss: 0.030219] [d2 loss: 0.040371]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 100/676] [D loss: -0.008501] [G loss: -0.218062] [d1 loss: 0.111921] [d2 loss: 0.122837]  [sq d1 d2: 0.000119]  [num0: 16.000000] [num1 48.000000]
[Epoch 143/500] [Batch 120/676] [D loss: 0.016789] [G loss: -0.233330] [d1 loss: 0.143818] [d2 loss: 0.150785]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 140/676] [D loss: -0.006735] [G loss: -0.216422] [d1 loss: 0.059549] [d2 loss: 0.069485]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 160/676] [D loss: -0.014204] [G loss: -0.168986] [d1 loss: 0.063277] [d2 loss: 0.090217]  [sq d1 d2: 0.000726]  [num0: 16.000000] [num1 48.000000]
[Epoch 143/500] [Batch 180/676] [D loss: -0.003736] [G loss: -0.132613] [d1 loss: 0.072281] [d2 loss: 0.068094]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 143/500] [Batch 200/676] [D loss: -0.012871] [G loss: -0.108473] [d1 loss: 0.052113] [d2 loss: 0.052949]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 220/676] [D loss: -0.004297] [G loss: -0.088602] [d1 loss: 0.024415] [d2 loss: 0.024353]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 240/676] [D loss: -0.017550] [G loss: -0.092716] [d1 loss: 0.095035] [d2 loss: 0.081621]  [sq d1 d2: 0.000180]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 260/676] [D loss: -0.011981] [G loss: -0.082407] [d1 loss: 0.024730] [d2 loss: 0.025659]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 143/500] [Batch 280/676] [D loss: -0.005652] [G loss: -0.089191] [d1 loss: 0.056531] [d2 loss: 0.057538]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 143/500] [Batch 300/676] [D loss: -0.013923] [G loss: -0.086668] [d1 loss: 0.039670] [d2 loss: 0.033635]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 320/676] [D loss: -0.012753] [G loss: -0.112535] [d1 loss: 0.047890] [d2 loss: 0.053066]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 143/500] [Batch 340/676] [D loss: -0.002088] [G loss: -0.093822] [d1 loss: 0.041037] [d2 loss: 0.029105]  [sq d1 d2: 0.000142]  [num0: 20.000000] [num1 44.000000]

[Epoch 143/500] [Batch 360/676] [D loss: -0.005320] [G loss: -0.074950] [d1 loss: 0.119384] [d2 loss: 0.107015]  [sq d1 d2: 0.000153]  [num0: 13.000000] [num1 51.000000]
[Epoch 143/500] [Batch 380/676] [D loss: -0.000768] [G loss: -0.045082] [d1 loss: 0.057886] [d2 loss: 0.038793]  [sq d1 d2: 0.000365]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 400/676] [D loss: -0.009043] [G loss: -0.050984] [d1 loss: 0.033377] [d2 loss: 0.025977]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 143/500] [Batch 420/676] [D loss: -0.028495] [G loss: -0.023715] [d1 loss: 0.075731] [d2 loss: 0.074074]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 440/676] [D loss: -0.013844] [G loss: -0.026968] [d1 loss: 0.032093] [d2 loss: 0.041592]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 460/676] [D loss: -0.014663] [G loss: -0.036123] [d1 loss: 0.041411] [d2 loss: 0.048843]  [sq d1 d2: 0.000055]  [num0: 11.000000] [num1 53.000000]
[Epoch 143/500] [Batch 480/676] [D loss: -0.029495] [G loss: -0.028822] [d1 loss: 0.037463] [d2 loss: 0.023548]  [sq d1 d2: 0.000194]  [num0: 19.000000] [num1 45.000000]
[Epoch 143/500] [Batch 500/676] [D loss: -0.026594] [G loss: -0.005834] [d1 loss: 0.058231] [d2 loss: 0.061256]  [sq d1 d2: 0.000009]  [num0: 20.000000] [num1 44.000000]
[Epoch 143/500] [Batch 520/676] [D loss: -0.000753] [G loss: 0.015081] [d1 loss: 0.087647] [d2 loss: 0.089302]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 143/500] [Batch 540/676] [D loss: -0.011509] [G loss: 0.032990] [d1 loss: 0.031079] [d2 loss: 0.029405]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 143/500] [Batch 560/676] [D loss: -0.010248] [G loss: 0.076092] [d1 loss: 0.111433] [d2 loss: 0.107323]  [sq d1 d2: 0.000017]  [num0: 20.000000] [num1 44.000000]
[Epoch 143/500] [Batch 580/676] [D loss: -0.005540] [G loss: 0.095942] [d1 loss: 0.085047] [d2 loss: 0.090583]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 143/500] [Batch 600/676] [D loss: -0.010802] [G loss: 0.086127] [d1 loss: 0.025604] [d2 loss: 0.017273]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 620/676] [D loss: 0.004420] [G loss: 0.093775] [d1 loss: 0.096165] [d2 loss: 0.093463]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 143/500] [Batch 640/676] [D loss: -0.015689] [G loss: 0.148474] [d1 loss: 0.104293] [d2 loss: 0.092813]  [sq d1 d2: 0.000132]  [num0: 16.000000] [num1 48.000000]
[Epoch 143/500] [Batch 660/676] [D loss: -0.013877] [G loss: 0.128826] [d1 loss: 0.088506] [d2 loss: 0.111686]  [sq d1 d2: 0.000537]  [num0: 19.000000] [num1 45.000000]
[Epoch 144/500] [Batch 0/676] [D loss: -0.024019] [G loss: 0.116589] [d1 loss: 0.066955] [d2 loss: 0.056009]  [sq d1 d2: 0.000120]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 20/676] [D loss: 0.006829] [G loss: 0.044909] [d1 loss: 0.089374] [d2 loss: 0.093725]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 144/500] [Batch 40/676] [D loss: 0.005442] [G loss: 0.032887] [d1 loss: 0.067335] [d2 loss: 0.040186]  [sq d1 d2: 0.000737]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 60/676] [D loss: -0.019062] [G loss: 0.007542] [d1 loss: 0.079024] [d2 loss: 0.073405]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 80/676] [D loss: -0.014246] [G loss: -0.011091] [d1 loss: 0.123086] [d2 loss: 0.116961]  [sq d1 d2: 0.000038]  [num0: 12.000000] [num1 52.000000]
[Epoch 144/500] [Batch 100/676] [D loss: -0.012895] [G loss: -0.030973] [d1 loss: 0.059451] [d2 loss: 0.052949]  [sq d1 d2: 0.000042]  [num0: 20.000000] [num1 44.000000]
[Epoch 144/500] [Batch 120/676] [D loss: -0.009728] [G loss: -0.049775] [d1 loss: 0.170017] [d2 loss: 0.145943]  [sq d1 d2: 0.000580]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 140/676] [D loss: -0.006688] [G loss: -0.058103] [d1 loss: 0.031629] [d2 loss: 0.031249]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 160/676] [D loss: -0.008265] [G loss: -0.068188] [d1 loss: 0.109520] [d2 loss: 0.096092]  [sq d1 d2: 0.000180]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 180/676] [D loss: -0.012459] [G loss: -0.058170] [d1 loss: 0.161877] [d2 loss: 0.154679]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 144/500] [Batch 200/676] [D loss: -0.008536] [G loss: -0.054772] [d1 loss: 0.097741] [d2 loss: 0.085834]  [sq d1 d2: 0.000142]  [num0: 14.000000] [num1 50.000000]
[Epoch 144/500] [Batch 220/676] [D loss: -0.025298] [G loss: -0.053681] [d1 loss: 0.155346] [d2 loss: 0.123190]  [sq d1 d2: 0.001034]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 240/676] [D loss: -0.016501] [G loss: -0.029970] [d1 loss: 0.158958] [d2 loss: 0.118467]  [sq d1 d2: 0.001640]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 260/676] [D loss: 0.010790] [G loss: -0.030583] [d1 loss: 0.204666] [d2 loss: 0.161080]  [sq d1 d2: 0.001900]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 280/676] [D loss: -0.006137] [G loss: -0.072190] [d1 loss: 0.052992] [d2 loss: 0.056996]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 300/676] [D loss: -0.002975] [G loss: -0.053390] [d1 loss: 0.035288] [d2 loss: 0.037504]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 144/500] [Batch 320/676] [D loss: -0.005272] [G loss: -0.012814] [d1 loss: 0.044426] [d2 loss: 0.039328]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 340/676] [D loss: -0.023693] [G loss: -0.049074] [d1 loss: 0.088932] [d2 loss: 0.075030]  [sq d1 d2: 0.000193]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 360/676] [D loss: -0.013008] [G loss: -0.033212] [d1 loss: 0.051313] [d2 loss: 0.051945]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 380/676] [D loss: -0.025111] [G loss: -0.053234] [d1 loss: 0.049012] [d2 loss: 0.060454]  [sq d1 d2: 0.000131]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 400/676] [D loss: -0.016767] [G loss: -0.063104] [d1 loss: 0.026984] [d2 loss: 0.024285]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 144/500] [Batch 420/676] [D loss: -0.022125] [G loss: -0.133466] [d1 loss: 0.083514] [d2 loss: 0.053906]  [sq d1 d2: 0.000877]  [num0: 19.000000] [num1 45.000000]
[Epoch 144/500] [Batch 440/676] [D loss: -0.012985] [G loss: -0.162459] [d1 loss: 0.066745] [d2 loss: 0.080949]  [sq d1 d2: 0.000202]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 460/676] [D loss: -0.035497] [G loss: -0.142886] [d1 loss: 0.067346] [d2 loss: 0.058993]  [sq d1 d2: 0.000070]  [num0: 19.000000] [num1 45.000000]
[Epoch 144/500] [Batch 480/676] [D loss: -0.013302] [G loss: -0.172434] [d1 loss: 0.093477] [d2 loss: 0.085104]  [sq d1 d2: 0.000070]  [num0: 19.000000] [num1 45.000000]
[Epoch 144/500] [Batch 500/676] [D loss: -0.024355] [G loss: -0.136079] [d1 loss: 0.061567] [d2 loss: 0.088657]  [sq d1 d2: 0.000734]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 520/676] [D loss: -0.020425] [G loss: -0.158302] [d1 loss: 0.092199] [d2 loss: 0.118543]  [sq d1 d2: 0.000694]  [num0: 16.000000] [num1 48.000000]
[Epoch 144/500] [Batch 540/676] [D loss: -0.040480] [G loss: -0.144512] [d1 loss: 0.055133] [d2 loss: 0.059999]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 144/500] [Batch 560/676] [D loss: -0.024385] [G loss: -0.165988] [d1 loss: 0.042915] [d2 loss: 0.041051]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 144/500] [Batch 580/676] [D loss: -0.012665] [G loss: -0.225170] [d1 loss: 0.071490] [d2 loss: 0.074209]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 144/500] [Batch 600/676] [D loss: -0.019373] [G loss: -0.176076] [d1 loss: 0.263052] [d2 loss: 0.198607]  [sq d1 d2: 0.004153]  [num0: 12.000000] [num1 52.000000]
[Epoch 144/500] [Batch 620/676] [D loss: 0.002693] [G loss: -0.143481] [d1 loss: 0.086291] [d2 loss: 0.073069]  [sq d1 d2: 0.000175]  [num0: 14.000000] [num1 50.000000]
[Epoch 144/500] [Batch 640/676] [D loss: -0.012739] [G loss: -0.073808] [d1 loss: 0.066980] [d2 loss: 0.058414]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]

[Epoch 144/500] [Batch 660/676] [D loss: 0.015008] [G loss: -0.021194] [d1 loss: 0.139718] [d2 loss: 0.150524]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 145/500] [Batch 0/676] [D loss: -0.001778] [G loss: 0.000626] [d1 loss: 0.015962] [d2 loss: 0.014390]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 145/500] [Batch 20/676] [D loss: -0.020613] [G loss: 0.008695] [d1 loss: 0.070194] [d2 loss: 0.064051]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 40/676] [D loss: -0.015965] [G loss: 0.029504] [d1 loss: 0.043114] [d2 loss: 0.055723]  [sq d1 d2: 0.000159]  [num0: 12.000000] [num1 52.000000]
[Epoch 145/500] [Batch 60/676] [D loss: -0.011164] [G loss: 0.072631] [d1 loss: 0.082363] [d2 loss: 0.078949]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 145/500] [Batch 80/676] [D loss: -0.017198] [G loss: 0.094589] [d1 loss: 0.067208] [d2 loss: 0.059352]  [sq d1 d2: 0.000062]  [num0: 13.000000] [num1 51.000000]
[Epoch 145/500] [Batch 100/676] [D loss: -0.026413] [G loss: 0.111089] [d1 loss: 0.050980] [d2 loss: 0.044318]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 145/500] [Batch 120/676] [D loss: -0.026121] [G loss: 0.101034] [d1 loss: 0.056203] [d2 loss: 0.058320]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 145/500] [Batch 140/676] [D loss: -0.006463] [G loss: 0.049208] [d1 loss: 0.075202] [d2 loss: 0.066027]  [sq d1 d2: 0.000084]  [num0: 12.000000] [num1 52.000000]
[Epoch 145/500] [Batch 160/676] [D loss: -0.018264] [G loss: 0.050650] [d1 loss: 0.032228] [d2 loss: 0.025643]  [sq d1 d2: 0.000043]  [num0: 19.000000] [num1 45.000000]
[Epoch 145/500] [Batch 180/676] [D loss: -0.002706] [G loss: 0.011240] [d1 loss: 0.102153] [d2 loss: 0.073982]  [sq d1 d2: 0.000794]  [num0: 18.000000] [num1 46.000000]
[Epoch 145/500] [Batch 200/676] [D loss: 0.015020] [G loss: -0.006561] [d1 loss: 0.109753] [d2 loss: 0.111585]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 145/500] [Batch 220/676] [D loss: -0.001267] [G loss: -0.048546] [d1 loss: 0.137195] [d2 loss: 0.137428]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 145/500] [Batch 240/676] [D loss: -0.006609] [G loss: -0.077600] [d1 loss: 0.033104] [d2 loss: 0.041536]  [sq d1 d2: 0.000071]  [num0: 19.000000] [num1 45.000000]
[Epoch 145/500] [Batch 260/676] [D loss: -0.025613] [G loss: -0.074809] [d1 loss: 0.097484] [d2 loss: 0.100598]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 145/500] [Batch 280/676] [D loss: -0.017985] [G loss: -0.078577] [d1 loss: 0.055709] [d2 loss: 0.054356]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 145/500] [Batch 300/676] [D loss: -0.025950] [G loss: -0.120577] [d1 loss: 0.063388] [d2 loss: 0.051710]  [sq d1 d2: 0.000136]  [num0: 15.000000] [num1 49.000000]
[Epoch 145/500] [Batch 320/676] [D loss: -0.022443] [G loss: -0.117860] [d1 loss: 0.268958] [d2 loss: 0.199891]  [sq d1 d2: 0.004770]  [num0: 18.000000] [num1 46.000000]
[Epoch 145/500] [Batch 340/676] [D loss: -0.034296] [G loss: -0.129009] [d1 loss: 0.082858] [d2 loss: 0.060091]  [sq d1 d2: 0.000518]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 360/676] [D loss: -0.006162] [G loss: -0.111200] [d1 loss: 0.028202] [d2 loss: 0.025921]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 145/500] [Batch 380/676] [D loss: -0.020445] [G loss: -0.129666] [d1 loss: 0.036975] [d2 loss: 0.038158]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 400/676] [D loss: 0.003462] [G loss: -0.130918] [d1 loss: 0.104908] [d2 loss: 0.128634]  [sq d1 d2: 0.000563]  [num0: 19.000000] [num1 45.000000]
[Epoch 145/500] [Batch 420/676] [D loss: -0.002124] [G loss: -0.092679] [d1 loss: 0.040382] [d2 loss: 0.037091]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 440/676] [D loss: 0.001239] [G loss: -0.054561] [d1 loss: 0.103106] [d2 loss: 0.119084]  [sq d1 d2: 0.000255]  [num0: 14.000000] [num1 50.000000]
[Epoch 145/500] [Batch 460/676] [D loss: -0.025621] [G loss: -0.024552] [d1 loss: 0.220190] [d2 loss: 0.157336]  [sq d1 d2: 0.003951]  [num0: 14.000000] [num1 50.000000]
[Epoch 145/500] [Batch 480/676] [D loss: -0.014608] [G loss: -0.006911] [d1 loss: 0.078313] [d2 loss: 0.064349]  [sq d1 d2: 0.000195]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 500/676] [D loss: -0.043397] [G loss: 0.015125] [d1 loss: 0.063879] [d2 loss: 0.072034]  [sq d1 d2: 0.000066]  [num0: 13.000000] [num1 51.000000]
[Epoch 145/500] [Batch 520/676] [D loss: -0.010499] [G loss: 0.047946] [d1 loss: 0.091856] [d2 loss: 0.094980]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 540/676] [D loss: -0.016824] [G loss: 0.039574] [d1 loss: 0.142686] [d2 loss: 0.151974]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 145/500] [Batch 560/676] [D loss: -0.015393] [G loss: 0.015377] [d1 loss: 0.078268] [d2 loss: 0.064793]  [sq d1 d2: 0.000182]  [num0: 18.000000] [num1 46.000000]
[Epoch 145/500] [Batch 580/676] [D loss: -0.016532] [G loss: -0.024416] [d1 loss: 0.145562] [d2 loss: 0.113567]  [sq d1 d2: 0.001024]  [num0: 13.000000] [num1 51.000000]
[Epoch 145/500] [Batch 600/676] [D loss: -0.008824] [G loss: -0.037604] [d1 loss: 0.142564] [d2 loss: 0.111725]  [sq d1 d2: 0.000951]  [num0: 17.000000] [num1 47.000000]
[Epoch 145/500] [Batch 620/676] [D loss: -0.007047] [G loss: -0.060142] [d1 loss: 0.108675] [d2 loss: 0.117569]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 145/500] [Batch 640/676] [D loss: -0.014558] [G loss: -0.070282] [d1 loss: 0.069654] [d2 loss: 0.073262]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 145/500] [Batch 660/676] [D loss: -0.008688] [G loss: -0.065757] [d1 loss: 0.030625] [d2 loss: 0.026007]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 146/500] [Batch 0/676] [D loss: -0.000149] [G loss: -0.046293] [d1 loss: 0.100961] [d2 loss: 0.107909]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 20/676] [D loss: -0.013564] [G loss: -0.074701] [d1 loss: 0.100233] [d2 loss: 0.115435]  [sq d1 d2: 0.000231]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 40/676] [D loss: -0.009100] [G loss: -0.080411] [d1 loss: 0.079424] [d2 loss: 0.068615]  [sq d1 d2: 0.000117]  [num0: 12.000000] [num1 52.000000]
[Epoch 146/500] [Batch 60/676] [D loss: -0.024761] [G loss: -0.085115] [d1 loss: 0.067158] [d2 loss: 0.068656]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 146/500] [Batch 80/676] [D loss: -0.019427] [G loss: -0.124396] [d1 loss: 0.061613] [d2 loss: 0.059916]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 146/500] [Batch 100/676] [D loss: -0.020866] [G loss: -0.127832] [d1 loss: 0.095216] [d2 loss: 0.117585]  [sq d1 d2: 0.000500]  [num0: 18.000000] [num1 46.000000]
[Epoch 146/500] [Batch 120/676] [D loss: -0.000196] [G loss: -0.135396] [d1 loss: 0.102954] [d2 loss: 0.093471]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 146/500] [Batch 140/676] [D loss: -0.006608] [G loss: -0.102069] [d1 loss: 0.087927] [d2 loss: 0.112133]  [sq d1 d2: 0.000586]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 160/676] [D loss: -0.026941] [G loss: -0.121621] [d1 loss: 0.057810] [d2 loss: 0.056911]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 180/676] [D loss: -0.022124] [G loss: -0.123661] [d1 loss: 0.090619] [d2 loss: 0.079105]  [sq d1 d2: 0.000133]  [num0: 12.000000] [num1 52.000000]
[Epoch 146/500] [Batch 200/676] [D loss: -0.015845] [G loss: -0.091802] [d1 loss: 0.041832] [d2 loss: 0.051274]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 146/500] [Batch 220/676] [D loss: -0.013817] [G loss: -0.078133] [d1 loss: 0.049619] [d2 loss: 0.033763]  [sq d1 d2: 0.000251]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 240/676] [D loss: -0.021502] [G loss: -0.094393] [d1 loss: 0.067185] [d2 loss: 0.070986]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 260/676] [D loss: -0.003506] [G loss: -0.127192] [d1 loss: 0.042728] [d2 loss: 0.053961]  [sq d1 d2: 0.000126]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 280/676] [D loss: -0.004439] [G loss: -0.076218] [d1 loss: 0.153522] [d2 loss: 0.170607]  [sq d1 d2: 0.000292]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 300/676] [D loss: -0.002663] [G loss: -0.068845] [d1 loss: 0.036414] [d2 loss: 0.047078]  [sq d1 d2: 0.000114]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 320/676] [D loss: -0.009670] [G loss: -0.084999] [d1 loss: 0.056847] [d2 loss: 0.049425]  [sq d1 d2: 0.000055]  [num0: 13.000000] [num1 51.000000]

[Epoch 146/500] [Batch 340/676] [D loss: -0.012026] [G loss: -0.100559] [d1 loss: 0.115860] [d2 loss: 0.104303]  [sq d1 d2: 0.000134]  [num0: 19.000000] [num1 45.000000]
[Epoch 146/500] [Batch 360/676] [D loss: -0.010748] [G loss: -0.109744] [d1 loss: 0.044222] [d2 loss: 0.042498]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 380/676] [D loss: -0.005559] [G loss: -0.124432] [d1 loss: 0.060350] [d2 loss: 0.054726]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 146/500] [Batch 400/676] [D loss: -0.025853] [G loss: -0.110881] [d1 loss: 0.065858] [d2 loss: 0.074128]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 420/676] [D loss: -0.005500] [G loss: -0.113072] [d1 loss: 0.035284] [d2 loss: 0.032611]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 146/500] [Batch 440/676] [D loss: -0.031181] [G loss: -0.123123] [d1 loss: 0.063806] [d2 loss: 0.067525]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 146/500] [Batch 460/676] [D loss: -0.017259] [G loss: -0.134249] [d1 loss: 0.029760] [d2 loss: 0.031891]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 146/500] [Batch 480/676] [D loss: -0.011799] [G loss: -0.154844] [d1 loss: 0.093030] [d2 loss: 0.091571]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 146/500] [Batch 500/676] [D loss: -0.000140] [G loss: -0.179664] [d1 loss: 0.082660] [d2 loss: 0.077220]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 146/500] [Batch 520/676] [D loss: -0.035716] [G loss: -0.169562] [d1 loss: 0.109832] [d2 loss: 0.103660]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]
[Epoch 146/500] [Batch 540/676] [D loss: -0.010189] [G loss: -0.150188] [d1 loss: 0.092605] [d2 loss: 0.101937]  [sq d1 d2: 0.000087]  [num0: 14.000000] [num1 50.000000]
[Epoch 146/500] [Batch 560/676] [D loss: -0.045106] [G loss: -0.182125] [d1 loss: 0.047094] [d2 loss: 0.045778]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 146/500] [Batch 580/676] [D loss: -0.057617] [G loss: -0.160103] [d1 loss: 0.070737] [d2 loss: 0.058192]  [sq d1 d2: 0.000157]  [num0: 13.000000] [num1 51.000000]
[Epoch 146/500] [Batch 600/676] [D loss: -0.029837] [G loss: -0.152013] [d1 loss: 0.077776] [d2 loss: 0.077301]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 146/500] [Batch 620/676] [D loss: -0.024937] [G loss: -0.162890] [d1 loss: 0.029305] [d2 loss: 0.022841]  [sq d1 d2: 0.000042]  [num0: 12.000000] [num1 52.000000]
[Epoch 146/500] [Batch 640/676] [D loss: -0.010406] [G loss: -0.202564] [d1 loss: 0.060700] [d2 loss: 0.065807]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 146/500] [Batch 660/676] [D loss: -0.014539] [G loss: -0.201240] [d1 loss: 0.189439] [d2 loss: 0.169786]  [sq d1 d2: 0.000386]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 0/676] [D loss: -0.006309] [G loss: -0.186338] [d1 loss: 0.072953] [d2 loss: 0.082225]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 20/676] [D loss: -0.012306] [G loss: -0.139451] [d1 loss: 0.177790] [d2 loss: 0.166403]  [sq d1 d2: 0.000130]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 40/676] [D loss: -0.026776] [G loss: -0.117713] [d1 loss: 0.066564] [d2 loss: 0.091339]  [sq d1 d2: 0.000614]  [num0: 12.000000] [num1 52.000000]
[Epoch 147/500] [Batch 60/676] [D loss: -0.018269] [G loss: -0.102586] [d1 loss: 0.074002] [d2 loss: 0.081282]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 80/676] [D loss: -0.039909] [G loss: -0.086231] [d1 loss: 0.063695] [d2 loss: 0.060620]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 100/676] [D loss: -0.046654] [G loss: -0.100261] [d1 loss: 0.094970] [d2 loss: 0.088528]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 120/676] [D loss: -0.045463] [G loss: -0.156807] [d1 loss: 0.162682] [d2 loss: 0.101102]  [sq d1 d2: 0.003792]  [num0: 18.000000] [num1 46.000000]
[Epoch 147/500] [Batch 140/676] [D loss: -0.031003] [G loss: -0.144454] [d1 loss: 0.186175] [d2 loss: 0.154034]  [sq d1 d2: 0.001033]  [num0: 17.000000] [num1 47.000000]
[Epoch 147/500] [Batch 160/676] [D loss: -0.011578] [G loss: -0.151420] [d1 loss: 0.138947] [d2 loss: 0.166972]  [sq d1 d2: 0.000785]  [num0: 14.000000] [num1 50.000000]
[Epoch 147/500] [Batch 180/676] [D loss: 0.007332] [G loss: -0.084720] [d1 loss: 0.115929] [d2 loss: 0.096013]  [sq d1 d2: 0.000397]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 200/676] [D loss: 0.003749] [G loss: -0.060586] [d1 loss: 0.086087] [d2 loss: 0.092388]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 147/500] [Batch 220/676] [D loss: 0.008197] [G loss: -0.038705] [d1 loss: 0.136335] [d2 loss: 0.123785]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 240/676] [D loss: -0.024273] [G loss: -0.014420] [d1 loss: 0.092734] [d2 loss: 0.080725]  [sq d1 d2: 0.000144]  [num0: 13.000000] [num1 51.000000]
[Epoch 147/500] [Batch 260/676] [D loss: -0.019478] [G loss: 0.006897] [d1 loss: 0.072883] [d2 loss: 0.067681]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 280/676] [D loss: -0.032169] [G loss: 0.011603] [d1 loss: 0.100313] [d2 loss: 0.085216]  [sq d1 d2: 0.000228]  [num0: 18.000000] [num1 46.000000]
[Epoch 147/500] [Batch 300/676] [D loss: -0.062604] [G loss: 0.022591] [d1 loss: 0.121158] [d2 loss: 0.087487]  [sq d1 d2: 0.001134]  [num0: 13.000000] [num1 51.000000]
[Epoch 147/500] [Batch 320/676] [D loss: -0.037429] [G loss: 0.014439] [d1 loss: 0.080935] [d2 loss: 0.088128]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 340/676] [D loss: -0.056408] [G loss: -0.001021] [d1 loss: 0.103273] [d2 loss: 0.087225]  [sq d1 d2: 0.000258]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 360/676] [D loss: -0.038148] [G loss: 0.025398] [d1 loss: 0.057750] [d2 loss: 0.068799]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 380/676] [D loss: -0.013709] [G loss: 0.027078] [d1 loss: 0.090782] [d2 loss: 0.123901]  [sq d1 d2: 0.001097]  [num0: 19.000000] [num1 45.000000]
[Epoch 147/500] [Batch 400/676] [D loss: 0.027531] [G loss: 0.056086] [d1 loss: 0.117714] [d2 loss: 0.115572]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 420/676] [D loss: 0.007240] [G loss: 0.093573] [d1 loss: 0.073470] [d2 loss: 0.089779]  [sq d1 d2: 0.000266]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 440/676] [D loss: -0.010965] [G loss: 0.069351] [d1 loss: 0.065697] [d2 loss: 0.102460]  [sq d1 d2: 0.001352]  [num0: 15.000000] [num1 49.000000]
[Epoch 147/500] [Batch 460/676] [D loss: 0.009228] [G loss: 0.038191] [d1 loss: 0.083824] [d2 loss: 0.069192]  [sq d1 d2: 0.000214]  [num0: 17.000000] [num1 47.000000]
[Epoch 147/500] [Batch 480/676] [D loss: -0.010294] [G loss: -0.023812] [d1 loss: 0.044563] [d2 loss: 0.037654]  [sq d1 d2: 0.000048]  [num0: 13.000000] [num1 51.000000]
[Epoch 147/500] [Batch 500/676] [D loss: -0.037748] [G loss: -0.070114] [d1 loss: 0.064931] [d2 loss: 0.061030]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 147/500] [Batch 520/676] [D loss: -0.058069] [G loss: -0.154868] [d1 loss: 0.150678] [d2 loss: 0.120590]  [sq d1 d2: 0.000905]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 540/676] [D loss: -0.069500] [G loss: -0.164960] [d1 loss: 0.078548] [d2 loss: 0.075311]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 560/676] [D loss: -0.072832] [G loss: -0.165208] [d1 loss: 0.065240] [d2 loss: 0.071809]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 147/500] [Batch 580/676] [D loss: -0.024440] [G loss: -0.208631] [d1 loss: 0.054498] [d2 loss: 0.056458]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 600/676] [D loss: 0.021345] [G loss: -0.161178] [d1 loss: 0.049634] [d2 loss: 0.044032]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 147/500] [Batch 620/676] [D loss: 0.016670] [G loss: -0.143956] [d1 loss: 0.048638] [d2 loss: 0.047681]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 147/500] [Batch 640/676] [D loss: 0.004225] [G loss: -0.080520] [d1 loss: 0.091833] [d2 loss: 0.089898]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]

[Epoch 147/500] [Batch 660/676] [D loss: -0.002288] [G loss: -0.007528] [d1 loss: 0.051861] [d2 loss: 0.061433]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 148/500] [Batch 0/676] [D loss: -0.010292] [G loss: 0.018239] [d1 loss: 0.120145] [d2 loss: 0.125189]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 148/500] [Batch 20/676] [D loss: -0.019852] [G loss: 0.060682] [d1 loss: 0.044988] [d2 loss: 0.041192]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 148/500] [Batch 40/676] [D loss: -0.044491] [G loss: 0.152016] [d1 loss: 0.075046] [d2 loss: 0.081740]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 60/676] [D loss: -0.028424] [G loss: 0.219443] [d1 loss: 0.138009] [d2 loss: 0.133942]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 148/500] [Batch 80/676] [D loss: -0.050844] [G loss: 0.221503] [d1 loss: 0.078437] [d2 loss: 0.090710]  [sq d1 d2: 0.000151]  [num0: 15.000000] [num1 49.000000]
[Epoch 148/500] [Batch 100/676] [D loss: -0.081241] [G loss: 0.175604] [d1 loss: 0.038186] [d2 loss: 0.040754]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 120/676] [D loss: -0.043046] [G loss: 0.116255] [d1 loss: 0.039778] [d2 loss: 0.041079]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 148/500] [Batch 140/676] [D loss: 0.003003] [G loss: 0.064228] [d1 loss: 0.034925] [d2 loss: 0.046097]  [sq d1 d2: 0.000125]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 160/676] [D loss: 0.010076] [G loss: 0.031972] [d1 loss: 0.024374] [d2 loss: 0.035169]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 148/500] [Batch 180/676] [D loss: -0.001511] [G loss: 0.013969] [d1 loss: 0.069512] [d2 loss: 0.065065]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 200/676] [D loss: -0.004585] [G loss: 0.008024] [d1 loss: 0.079955] [d2 loss: 0.057988]  [sq d1 d2: 0.000483]  [num0: 21.000000] [num1 43.000000]
[Epoch 148/500] [Batch 220/676] [D loss: -0.021158] [G loss: -0.011654] [d1 loss: 0.056396] [d2 loss: 0.096445]  [sq d1 d2: 0.001604]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 240/676] [D loss: -0.035251] [G loss: -0.035568] [d1 loss: 0.071409] [d2 loss: 0.071049]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 148/500] [Batch 260/676] [D loss: -0.064579] [G loss: -0.103023] [d1 loss: 0.157948] [d2 loss: 0.147659]  [sq d1 d2: 0.000106]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 280/676] [D loss: -0.056541] [G loss: -0.191807] [d1 loss: 0.133811] [d2 loss: 0.131198]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 300/676] [D loss: -0.057144] [G loss: -0.233197] [d1 loss: 0.082965] [d2 loss: 0.109267]  [sq d1 d2: 0.000692]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 320/676] [D loss: -0.037052] [G loss: -0.279440] [d1 loss: 0.092182] [d2 loss: 0.086957]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 340/676] [D loss: -0.000134] [G loss: -0.324207] [d1 loss: 0.173556] [d2 loss: 0.146683]  [sq d1 d2: 0.000722]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 360/676] [D loss: -0.003598] [G loss: -0.307940] [d1 loss: 0.078600] [d2 loss: 0.100851]  [sq d1 d2: 0.000495]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 380/676] [D loss: 0.013293] [G loss: -0.249941] [d1 loss: 0.146016] [d2 loss: 0.149636]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 148/500] [Batch 400/676] [D loss: 0.017737] [G loss: -0.172006] [d1 loss: 0.088236] [d2 loss: 0.076165]  [sq d1 d2: 0.000146]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 420/676] [D loss: -0.002552] [G loss: -0.089523] [d1 loss: 0.060161] [d2 loss: 0.069401]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 440/676] [D loss: -0.017209] [G loss: -0.027723] [d1 loss: 0.130143] [d2 loss: 0.129583]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 148/500] [Batch 460/676] [D loss: -0.029362] [G loss: 0.070262] [d1 loss: 0.110515] [d2 loss: 0.109861]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 480/676] [D loss: -0.038739] [G loss: 0.098657] [d1 loss: 0.070653] [d2 loss: 0.072924]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 148/500] [Batch 500/676] [D loss: -0.078192] [G loss: 0.119913] [d1 loss: 0.059035] [d2 loss: 0.060353]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 520/676] [D loss: -0.044865] [G loss: 0.174737] [d1 loss: 0.120102] [d2 loss: 0.129174]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 540/676] [D loss: -0.000908] [G loss: 0.163236] [d1 loss: 0.092385] [d2 loss: 0.085944]  [sq d1 d2: 0.000041]  [num0: 13.000000] [num1 51.000000]
[Epoch 148/500] [Batch 560/676] [D loss: -0.010911] [G loss: 0.078837] [d1 loss: 0.091571] [d2 loss: 0.084582]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 580/676] [D loss: -0.000206] [G loss: 0.015206] [d1 loss: 0.056274] [d2 loss: 0.072428]  [sq d1 d2: 0.000261]  [num0: 16.000000] [num1 48.000000]
[Epoch 148/500] [Batch 600/676] [D loss: 0.001330] [G loss: -0.019075] [d1 loss: 0.124304] [d2 loss: 0.152872]  [sq d1 d2: 0.000816]  [num0: 15.000000] [num1 49.000000]
[Epoch 148/500] [Batch 620/676] [D loss: -0.006928] [G loss: -0.007260] [d1 loss: 0.090171] [d2 loss: 0.101946]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 148/500] [Batch 640/676] [D loss: -0.021292] [G loss: -0.030718] [d1 loss: 0.059401] [d2 loss: 0.061652]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 148/500] [Batch 660/676] [D loss: -0.037755] [G loss: -0.038039] [d1 loss: 0.114211] [d2 loss: 0.146650]  [sq d1 d2: 0.001052]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 0/676] [D loss: -0.028318] [G loss: -0.066003] [d1 loss: 0.095448] [d2 loss: 0.113279]  [sq d1 d2: 0.000318]  [num0: 13.000000] [num1 51.000000]
[Epoch 149/500] [Batch 20/676] [D loss: -0.023991] [G loss: -0.127264] [d1 loss: 0.150849] [d2 loss: 0.134592]  [sq d1 d2: 0.000264]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 40/676] [D loss: -0.002106] [G loss: -0.173391] [d1 loss: 0.036581] [d2 loss: 0.035932]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 60/676] [D loss: -0.027626] [G loss: -0.234079] [d1 loss: 0.136811] [d2 loss: 0.156855]  [sq d1 d2: 0.000402]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 80/676] [D loss: -0.000601] [G loss: -0.250145] [d1 loss: 0.129827] [d2 loss: 0.127396]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 100/676] [D loss: 0.013051] [G loss: -0.293901] [d1 loss: 0.088897] [d2 loss: 0.086115]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 120/676] [D loss: 0.013319] [G loss: -0.233032] [d1 loss: 0.060411] [d2 loss: 0.044040]  [sq d1 d2: 0.000268]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 140/676] [D loss: 0.005798] [G loss: -0.182611] [d1 loss: 0.028949] [d2 loss: 0.026850]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 149/500] [Batch 160/676] [D loss: -0.003702] [G loss: -0.151672] [d1 loss: 0.092530] [d2 loss: 0.119035]  [sq d1 d2: 0.000703]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 180/676] [D loss: -0.006264] [G loss: -0.136788] [d1 loss: 0.060726] [d2 loss: 0.059777]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 200/676] [D loss: -0.021236] [G loss: -0.121308] [d1 loss: 0.030921] [d2 loss: 0.027218]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 220/676] [D loss: -0.021158] [G loss: -0.084463] [d1 loss: 0.065855] [d2 loss: 0.059082]  [sq d1 d2: 0.000046]  [num0: 12.000000] [num1 52.000000]
[Epoch 149/500] [Batch 240/676] [D loss: -0.058743] [G loss: -0.018645] [d1 loss: 0.134068] [d2 loss: 0.088657]  [sq d1 d2: 0.002062]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 260/676] [D loss: -0.032057] [G loss: 0.022013] [d1 loss: 0.037693] [d2 loss: 0.036864]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 280/676] [D loss: -0.041233] [G loss: 0.017296] [d1 loss: 0.072295] [d2 loss: 0.067079]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 300/676] [D loss: -0.006273] [G loss: -0.051615] [d1 loss: 0.185249] [d2 loss: 0.147182]  [sq d1 d2: 0.001449]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 320/676] [D loss: -0.002581] [G loss: -0.083117] [d1 loss: 0.186671] [d2 loss: 0.191567]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]

[Epoch 149/500] [Batch 340/676] [D loss: 0.003427] [G loss: -0.060208] [d1 loss: 0.087378] [d2 loss: 0.073912]  [sq d1 d2: 0.000181]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 360/676] [D loss: -0.003913] [G loss: -0.023453] [d1 loss: 0.180378] [d2 loss: 0.130781]  [sq d1 d2: 0.002460]  [num0: 12.000000] [num1 52.000000]
[Epoch 149/500] [Batch 380/676] [D loss: -0.017493] [G loss: -0.027768] [d1 loss: 0.044165] [d2 loss: 0.051104]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 400/676] [D loss: -0.023736] [G loss: -0.054713] [d1 loss: 0.138243] [d2 loss: 0.138758]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 420/676] [D loss: -0.024648] [G loss: -0.098434] [d1 loss: 0.061208] [d2 loss: 0.045337]  [sq d1 d2: 0.000252]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 440/676] [D loss: -0.045954] [G loss: -0.131894] [d1 loss: 0.059456] [d2 loss: 0.062265]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 460/676] [D loss: -0.030724] [G loss: -0.176909] [d1 loss: 0.098320] [d2 loss: 0.088009]  [sq d1 d2: 0.000106]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 480/676] [D loss: -0.014388] [G loss: -0.195848] [d1 loss: 0.103457] [d2 loss: 0.098057]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 500/676] [D loss: -0.022086] [G loss: -0.191691] [d1 loss: 0.113875] [d2 loss: 0.124717]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 520/676] [D loss: -0.008966] [G loss: -0.134315] [d1 loss: 0.058554] [d2 loss: 0.043882]  [sq d1 d2: 0.000215]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 540/676] [D loss: -0.000701] [G loss: -0.100223] [d1 loss: 0.122036] [d2 loss: 0.117146]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 149/500] [Batch 560/676] [D loss: 0.006025] [G loss: -0.072264] [d1 loss: 0.055208] [d2 loss: 0.054288]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 580/676] [D loss: 0.003403] [G loss: -0.060001] [d1 loss: 0.071529] [d2 loss: 0.084454]  [sq d1 d2: 0.000167]  [num0: 13.000000] [num1 51.000000]
[Epoch 149/500] [Batch 600/676] [D loss: -0.009714] [G loss: -0.036286] [d1 loss: 0.081103] [d2 loss: 0.087445]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 149/500] [Batch 620/676] [D loss: -0.015967] [G loss: -0.008293] [d1 loss: 0.095344] [d2 loss: 0.065333]  [sq d1 d2: 0.000901]  [num0: 16.000000] [num1 48.000000]
[Epoch 149/500] [Batch 640/676] [D loss: -0.016363] [G loss: 0.007646] [d1 loss: 0.029730] [d2 loss: 0.032557]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 149/500] [Batch 660/676] [D loss: -0.025179] [G loss: 0.019544] [d1 loss: 0.080603] [d2 loss: 0.094906]  [sq d1 d2: 0.000205]  [num0: 12.000000] [num1 52.000000]
[Epoch 150/500] [Batch 0/676] [D loss: 0.024641] [G loss: 0.029521] [d1 loss: 0.115150] [d2 loss: 0.111260]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 150/500] [Batch 20/676] [D loss: 0.003181] [G loss: 0.000670] [d1 loss: 0.139161] [d2 loss: 0.152269]  [sq d1 d2: 0.000172]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 40/676] [D loss: 0.013314] [G loss: -0.038947] [d1 loss: 0.120920] [d2 loss: 0.126955]  [sq d1 d2: 0.000036]  [num0: 19.000000] [num1 45.000000]
[Epoch 150/500] [Batch 60/676] [D loss: 0.011518] [G loss: -0.011171] [d1 loss: 0.053604] [d2 loss: 0.067832]  [sq d1 d2: 0.000202]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 80/676] [D loss: 0.001155] [G loss: -0.006536] [d1 loss: 0.135908] [d2 loss: 0.116421]  [sq d1 d2: 0.000380]  [num0: 18.000000] [num1 46.000000]
[Epoch 150/500] [Batch 100/676] [D loss: -0.005935] [G loss: 0.012415] [d1 loss: 0.084325] [d2 loss: 0.079513]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 150/500] [Batch 120/676] [D loss: -0.017104] [G loss: 0.027055] [d1 loss: 0.096910] [d2 loss: 0.102951]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 150/500] [Batch 140/676] [D loss: -0.024227] [G loss: 0.039642] [d1 loss: 0.105205] [d2 loss: 0.093904]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 150/500] [Batch 160/676] [D loss: -0.046427] [G loss: -0.025079] [d1 loss: 0.159006] [d2 loss: 0.157227]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 150/500] [Batch 180/676] [D loss: -0.028027] [G loss: -0.035818] [d1 loss: 0.037510] [d2 loss: 0.038688]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 200/676] [D loss: -0.022068] [G loss: -0.048024] [d1 loss: 0.045097] [d2 loss: 0.070849]  [sq d1 d2: 0.000663]  [num0: 16.000000] [num1 48.000000]
[Epoch 150/500] [Batch 220/676] [D loss: -0.017492] [G loss: -0.073723] [d1 loss: 0.073646] [d2 loss: 0.066447]  [sq d1 d2: 0.000052]  [num0: 20.000000] [num1 44.000000]
[Epoch 150/500] [Batch 240/676] [D loss: 0.016472] [G loss: -0.093240] [d1 loss: 0.052674] [d2 loss: 0.061401]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 260/676] [D loss: 0.015996] [G loss: -0.078401] [d1 loss: 0.100147] [d2 loss: 0.078940]  [sq d1 d2: 0.000450]  [num0: 13.000000] [num1 51.000000]
[Epoch 150/500] [Batch 280/676] [D loss: 0.009391] [G loss: -0.054145] [d1 loss: 0.129737] [d2 loss: 0.141525]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 300/676] [D loss: -0.003929] [G loss: -0.045541] [d1 loss: 0.081823] [d2 loss: 0.082780]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 150/500] [Batch 320/676] [D loss: -0.018112] [G loss: -0.087683] [d1 loss: 0.130550] [d2 loss: 0.126683]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 340/676] [D loss: -0.042621] [G loss: -0.100033] [d1 loss: 0.079562] [d2 loss: 0.069971]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 360/676] [D loss: -0.063183] [G loss: -0.035097] [d1 loss: 0.099851] [d2 loss: 0.090031]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 380/676] [D loss: -0.039863] [G loss: -0.025451] [d1 loss: 0.040555] [d2 loss: 0.047534]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 400/676] [D loss: 0.005821] [G loss: -0.062403] [d1 loss: 0.172021] [d2 loss: 0.152719]  [sq d1 d2: 0.000373]  [num0: 19.000000] [num1 45.000000]
[Epoch 150/500] [Batch 420/676] [D loss: -0.002708] [G loss: -0.081617] [d1 loss: 0.056939] [d2 loss: 0.053601]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 150/500] [Batch 440/676] [D loss: 0.010100] [G loss: -0.135261] [d1 loss: 0.046948] [d2 loss: 0.032958]  [sq d1 d2: 0.000196]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 460/676] [D loss: 0.001374] [G loss: -0.094021] [d1 loss: 0.092427] [d2 loss: 0.093901]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 150/500] [Batch 480/676] [D loss: 0.004366] [G loss: -0.087592] [d1 loss: 0.107807] [d2 loss: 0.110836]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 500/676] [D loss: -0.014492] [G loss: -0.086306] [d1 loss: 0.078056] [d2 loss: 0.041757]  [sq d1 d2: 0.001318]  [num0: 16.000000] [num1 48.000000]
[Epoch 150/500] [Batch 520/676] [D loss: -0.022984] [G loss: -0.095923] [d1 loss: 0.075589] [d2 loss: 0.083218]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 150/500] [Batch 540/676] [D loss: -0.056559] [G loss: -0.098843] [d1 loss: 0.067915] [d2 loss: 0.070256]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 560/676] [D loss: -0.031607] [G loss: -0.065148] [d1 loss: 0.076237] [d2 loss: 0.078777]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 150/500] [Batch 580/676] [D loss: -0.031726] [G loss: -0.068345] [d1 loss: 0.144892] [d2 loss: 0.148044]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 150/500] [Batch 600/676] [D loss: -0.027433] [G loss: -0.101852] [d1 loss: 0.042457] [d2 loss: 0.040671]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 150/500] [Batch 620/676] [D loss: 0.014441] [G loss: -0.137743] [d1 loss: 0.070249] [d2 loss: 0.086981]  [sq d1 d2: 0.000280]  [num0: 17.000000] [num1 47.000000]

[Epoch 150/500] [Batch 640/676] [D loss: 0.034196] [G loss: -0.099567] [d1 loss: 0.111436] [d2 loss: 0.087737]  [sq d1 d2: 0.000562]  [num0: 17.000000] [num1 47.000000]
[Epoch 150/500] [Batch 660/676] [D loss: 0.009220] [G loss: -0.087751] [d1 loss: 0.128237] [d2 loss: 0.119436]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 151/500] [Batch 0/676] [D loss: 0.019331] [G loss: -0.027938] [d1 loss: 0.055164] [d2 loss: 0.046637]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 151/500] [Batch 20/676] [D loss: -0.014527] [G loss: 0.050676] [d1 loss: 0.071111] [d2 loss: 0.066428]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 40/676] [D loss: -0.023646] [G loss: 0.089152] [d1 loss: 0.040539] [d2 loss: 0.042685]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 151/500] [Batch 60/676] [D loss: -0.049674] [G loss: 0.081845] [d1 loss: 0.198029] [d2 loss: 0.223751]  [sq d1 d2: 0.000662]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 80/676] [D loss: -0.055243] [G loss: 0.089552] [d1 loss: 0.047056] [d2 loss: 0.052785]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 100/676] [D loss: -0.030216] [G loss: 0.045514] [d1 loss: 0.065850] [d2 loss: 0.079876]  [sq d1 d2: 0.000197]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 120/676] [D loss: -0.018958] [G loss: -0.016307] [d1 loss: 0.105360] [d2 loss: 0.101762]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 140/676] [D loss: 0.008828] [G loss: -0.039435] [d1 loss: 0.078293] [d2 loss: 0.086980]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 151/500] [Batch 160/676] [D loss: 0.000041] [G loss: -0.111620] [d1 loss: 0.102724] [d2 loss: 0.101835]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 180/676] [D loss: 0.010134] [G loss: -0.117118] [d1 loss: 0.102231] [d2 loss: 0.109885]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 200/676] [D loss: 0.006244] [G loss: -0.076442] [d1 loss: 0.048481] [d2 loss: 0.066216]  [sq d1 d2: 0.000315]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 220/676] [D loss: -0.004855] [G loss: -0.043160] [d1 loss: 0.069955] [d2 loss: 0.079275]  [sq d1 d2: 0.000087]  [num0: 18.000000] [num1 46.000000]
[Epoch 151/500] [Batch 240/676] [D loss: -0.019171] [G loss: -0.041881] [d1 loss: 0.103050] [d2 loss: 0.132531]  [sq d1 d2: 0.000869]  [num0: 13.000000] [num1 51.000000]
[Epoch 151/500] [Batch 260/676] [D loss: -0.030788] [G loss: -0.035464] [d1 loss: 0.037378] [d2 loss: 0.036782]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 151/500] [Batch 280/676] [D loss: -0.040015] [G loss: -0.081997] [d1 loss: 0.085550] [d2 loss: 0.092403]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 300/676] [D loss: -0.015937] [G loss: -0.065211] [d1 loss: 0.139182] [d2 loss: 0.141015]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 151/500] [Batch 320/676] [D loss: -0.051294] [G loss: -0.097413] [d1 loss: 0.191613] [d2 loss: 0.205817]  [sq d1 d2: 0.000202]  [num0: 19.000000] [num1 45.000000]
[Epoch 151/500] [Batch 340/676] [D loss: -0.026557] [G loss: -0.099909] [d1 loss: 0.029503] [d2 loss: 0.028772]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 360/676] [D loss: -0.009203] [G loss: -0.085793] [d1 loss: 0.130129] [d2 loss: 0.126328]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 151/500] [Batch 380/676] [D loss: 0.013662] [G loss: -0.078213] [d1 loss: 0.074423] [d2 loss: 0.107009]  [sq d1 d2: 0.001062]  [num0: 13.000000] [num1 51.000000]
[Epoch 151/500] [Batch 400/676] [D loss: 0.015019] [G loss: -0.069819] [d1 loss: 0.133423] [d2 loss: 0.133841]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 151/500] [Batch 420/676] [D loss: 0.007322] [G loss: -0.063689] [d1 loss: 0.082413] [d2 loss: 0.075143]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 440/676] [D loss: -0.009052] [G loss: -0.059176] [d1 loss: 0.100489] [d2 loss: 0.117073]  [sq d1 d2: 0.000275]  [num0: 13.000000] [num1 51.000000]
[Epoch 151/500] [Batch 460/676] [D loss: -0.033824] [G loss: -0.055619] [d1 loss: 0.078791] [d2 loss: 0.077875]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 480/676] [D loss: -0.034273] [G loss: -0.039396] [d1 loss: 0.065725] [d2 loss: 0.069154]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 151/500] [Batch 500/676] [D loss: -0.047131] [G loss: 0.019047] [d1 loss: 0.139885] [d2 loss: 0.149311]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 151/500] [Batch 520/676] [D loss: -0.009380] [G loss: 0.104879] [d1 loss: 0.090310] [d2 loss: 0.109408]  [sq d1 d2: 0.000365]  [num0: 15.000000] [num1 49.000000]
[Epoch 151/500] [Batch 540/676] [D loss: -0.021205] [G loss: 0.111395] [d1 loss: 0.057430] [d2 loss: 0.087887]  [sq d1 d2: 0.000928]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 560/676] [D loss: 0.006903] [G loss: 0.010735] [d1 loss: 0.060205] [d2 loss: 0.053121]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 151/500] [Batch 580/676] [D loss: 0.001430] [G loss: -0.086268] [d1 loss: 0.079540] [d2 loss: 0.103245]  [sq d1 d2: 0.000562]  [num0: 14.000000] [num1 50.000000]
[Epoch 151/500] [Batch 600/676] [D loss: 0.023046] [G loss: -0.096649] [d1 loss: 0.113371] [d2 loss: 0.099674]  [sq d1 d2: 0.000188]  [num0: 21.000000] [num1 43.000000]
[Epoch 151/500] [Batch 620/676] [D loss: 0.011102] [G loss: -0.060608] [d1 loss: 0.049047] [d2 loss: 0.050877]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 151/500] [Batch 640/676] [D loss: 0.004203] [G loss: -0.041335] [d1 loss: 0.042929] [d2 loss: 0.047813]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 151/500] [Batch 660/676] [D loss: -0.017449] [G loss: -0.017936] [d1 loss: 0.052545] [d2 loss: 0.062693]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 152/500] [Batch 0/676] [D loss: -0.030167] [G loss: 0.003842] [d1 loss: 0.090470] [d2 loss: 0.102122]  [sq d1 d2: 0.000136]  [num0: 19.000000] [num1 45.000000]
[Epoch 152/500] [Batch 20/676] [D loss: -0.082474] [G loss: 0.061179] [d1 loss: 0.036041] [d2 loss: 0.040725]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 40/676] [D loss: -0.081960] [G loss: 0.097755] [d1 loss: 0.094020] [d2 loss: 0.100157]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 152/500] [Batch 60/676] [D loss: -0.062751] [G loss: 0.063915] [d1 loss: 0.065929] [d2 loss: 0.049398]  [sq d1 d2: 0.000273]  [num0: 18.000000] [num1 46.000000]
[Epoch 152/500] [Batch 80/676] [D loss: -0.042337] [G loss: 0.073310] [d1 loss: 0.136658] [d2 loss: 0.140010]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 100/676] [D loss: -0.039196] [G loss: 0.071338] [d1 loss: 0.064448] [d2 loss: 0.079804]  [sq d1 d2: 0.000236]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 120/676] [D loss: -0.001689] [G loss: 0.061841] [d1 loss: 0.051211] [d2 loss: 0.045619]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 152/500] [Batch 140/676] [D loss: 0.007120] [G loss: 0.064033] [d1 loss: 0.090712] [d2 loss: 0.088475]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 152/500] [Batch 160/676] [D loss: 0.024058] [G loss: 0.040966] [d1 loss: 0.046227] [d2 loss: 0.064650]  [sq d1 d2: 0.000339]  [num0: 17.000000] [num1 47.000000]
[Epoch 152/500] [Batch 180/676] [D loss: 0.002660] [G loss: -0.009821] [d1 loss: 0.058254] [d2 loss: 0.059063]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 152/500] [Batch 200/676] [D loss: -0.007798] [G loss: -0.065170] [d1 loss: 0.031614] [d2 loss: 0.021696]  [sq d1 d2: 0.000098]  [num0: 19.000000] [num1 45.000000]
[Epoch 152/500] [Batch 220/676] [D loss: -0.022103] [G loss: -0.110082] [d1 loss: 0.126549] [d2 loss: 0.112208]  [sq d1 d2: 0.000206]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 240/676] [D loss: -0.083029] [G loss: -0.105871] [d1 loss: 0.082266] [d2 loss: 0.140140]  [sq d1 d2: 0.003349]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 260/676] [D loss: -0.093319] [G loss: 0.040236] [d1 loss: 0.121032] [d2 loss: 0.116798]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 280/676] [D loss: -0.103682] [G loss: 0.096945] [d1 loss: 0.086020] [d2 loss: 0.093497]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]

[Epoch 152/500] [Batch 300/676] [D loss: -0.009265] [G loss: 0.054055] [d1 loss: 0.060076] [d2 loss: 0.042161]  [sq d1 d2: 0.000321]  [num0: 18.000000] [num1 46.000000]
[Epoch 152/500] [Batch 320/676] [D loss: 0.018793] [G loss: -0.085699] [d1 loss: 0.073819] [d2 loss: 0.065891]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 340/676] [D loss: 0.042102] [G loss: -0.122591] [d1 loss: 0.068322] [d2 loss: 0.086405]  [sq d1 d2: 0.000327]  [num0: 17.000000] [num1 47.000000]
[Epoch 152/500] [Batch 360/676] [D loss: 0.013886] [G loss: -0.103780] [d1 loss: 0.178943] [d2 loss: 0.164039]  [sq d1 d2: 0.000222]  [num0: 13.000000] [num1 51.000000]
[Epoch 152/500] [Batch 380/676] [D loss: 0.015718] [G loss: -0.077724] [d1 loss: 0.097280] [d2 loss: 0.092630]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 400/676] [D loss: -0.002296] [G loss: -0.034692] [d1 loss: 0.134232] [d2 loss: 0.126196]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 420/676] [D loss: -0.023709] [G loss: -0.002350] [d1 loss: 0.089503] [d2 loss: 0.067512]  [sq d1 d2: 0.000484]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 440/676] [D loss: -0.051712] [G loss: 0.076530] [d1 loss: 0.087493] [d2 loss: 0.062913]  [sq d1 d2: 0.000604]  [num0: 18.000000] [num1 46.000000]
[Epoch 152/500] [Batch 460/676] [D loss: -0.065692] [G loss: 0.185456] [d1 loss: 0.061108] [d2 loss: 0.076704]  [sq d1 d2: 0.000243]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 480/676] [D loss: -0.135802] [G loss: 0.169778] [d1 loss: 0.065265] [d2 loss: 0.075704]  [sq d1 d2: 0.000109]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 500/676] [D loss: -0.069580] [G loss: 0.145610] [d1 loss: 0.071047] [d2 loss: 0.069445]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 152/500] [Batch 520/676] [D loss: -0.017453] [G loss: 0.089105] [d1 loss: 0.132520] [d2 loss: 0.181586]  [sq d1 d2: 0.002407]  [num0: 17.000000] [num1 47.000000]
[Epoch 152/500] [Batch 540/676] [D loss: -0.024320] [G loss: 0.061913] [d1 loss: 0.063994] [d2 loss: 0.091807]  [sq d1 d2: 0.000774]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 560/676] [D loss: 0.018098] [G loss: 0.026092] [d1 loss: 0.133544] [d2 loss: 0.137115]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 152/500] [Batch 580/676] [D loss: 0.021858] [G loss: -0.014382] [d1 loss: 0.064805] [d2 loss: 0.079663]  [sq d1 d2: 0.000221]  [num0: 15.000000] [num1 49.000000]
[Epoch 152/500] [Batch 600/676] [D loss: 0.023263] [G loss: -0.009942] [d1 loss: 0.089981] [d2 loss: 0.094226]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 152/500] [Batch 620/676] [D loss: 0.009343] [G loss: 0.001489] [d1 loss: 0.087159] [d2 loss: 0.087522]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 152/500] [Batch 640/676] [D loss: 0.004010] [G loss: 0.004176] [d1 loss: 0.090730] [d2 loss: 0.102658]  [sq d1 d2: 0.000142]  [num0: 18.000000] [num1 46.000000]
[Epoch 152/500] [Batch 660/676] [D loss: -0.013420] [G loss: -0.016259] [d1 loss: 0.157683] [d2 loss: 0.135149]  [sq d1 d2: 0.000508]  [num0: 20.000000] [num1 44.000000]
[Epoch 153/500] [Batch 0/676] [D loss: -0.019264] [G loss: -0.032711] [d1 loss: 0.061729] [d2 loss: 0.068824]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 20/676] [D loss: -0.038699] [G loss: -0.044012] [d1 loss: 0.102867] [d2 loss: 0.104510]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 153/500] [Batch 40/676] [D loss: -0.061927] [G loss: -0.016398] [d1 loss: 0.057422] [d2 loss: 0.052317]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 60/676] [D loss: -0.088735] [G loss: 0.096829] [d1 loss: 0.113657] [d2 loss: 0.119126]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 80/676] [D loss: -0.089901] [G loss: 0.114510] [d1 loss: 0.058552] [d2 loss: 0.085707]  [sq d1 d2: 0.000737]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 100/676] [D loss: -0.002036] [G loss: 0.133930] [d1 loss: 0.186951] [d2 loss: 0.136910]  [sq d1 d2: 0.002504]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 120/676] [D loss: 0.050279] [G loss: 0.125842] [d1 loss: 0.042133] [d2 loss: 0.082905]  [sq d1 d2: 0.001662]  [num0: 9.000000] [num1 55.000000]
[Epoch 153/500] [Batch 140/676] [D loss: 0.061801] [G loss: -0.055408] [d1 loss: 0.034695] [d2 loss: 0.045946]  [sq d1 d2: 0.000127]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 160/676] [D loss: 0.024293] [G loss: -0.083465] [d1 loss: 0.113655] [d2 loss: 0.118293]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 180/676] [D loss: 0.019389] [G loss: -0.079055] [d1 loss: 0.056627] [d2 loss: 0.049703]  [sq d1 d2: 0.000048]  [num0: 13.000000] [num1 51.000000]
[Epoch 153/500] [Batch 200/676] [D loss: 0.004269] [G loss: -0.068619] [d1 loss: 0.092850] [d2 loss: 0.106913]  [sq d1 d2: 0.000198]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 220/676] [D loss: -0.011020] [G loss: -0.070049] [d1 loss: 0.054718] [d2 loss: 0.050395]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 240/676] [D loss: -0.025559] [G loss: -0.041968] [d1 loss: 0.226488] [d2 loss: 0.139090]  [sq d1 d2: 0.007638]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 260/676] [D loss: -0.051329] [G loss: -0.060036] [d1 loss: 0.026509] [d2 loss: 0.029529]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 280/676] [D loss: -0.079766] [G loss: 0.006873] [d1 loss: 0.106452] [d2 loss: 0.128545]  [sq d1 d2: 0.000488]  [num0: 18.000000] [num1 46.000000]
[Epoch 153/500] [Batch 300/676] [D loss: -0.096365] [G loss: 0.056032] [d1 loss: 0.098693] [d2 loss: 0.100700]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 153/500] [Batch 320/676] [D loss: -0.057529] [G loss: 0.057699] [d1 loss: 0.049815] [d2 loss: 0.065283]  [sq d1 d2: 0.000239]  [num0: 18.000000] [num1 46.000000]
[Epoch 153/500] [Batch 340/676] [D loss: -0.039152] [G loss: 0.010328] [d1 loss: 0.036792] [d2 loss: 0.038570]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 360/676] [D loss: -0.013897] [G loss: -0.011194] [d1 loss: 0.057648] [d2 loss: 0.112599]  [sq d1 d2: 0.003020]  [num0: 12.000000] [num1 52.000000]
[Epoch 153/500] [Batch 380/676] [D loss: -0.002610] [G loss: -0.061413] [d1 loss: 0.077384] [d2 loss: 0.093106]  [sq d1 d2: 0.000247]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 400/676] [D loss: 0.047368] [G loss: -0.060492] [d1 loss: 0.194424] [d2 loss: 0.203275]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 420/676] [D loss: 0.026192] [G loss: -0.043027] [d1 loss: 0.045684] [d2 loss: 0.059582]  [sq d1 d2: 0.000193]  [num0: 13.000000] [num1 51.000000]
[Epoch 153/500] [Batch 440/676] [D loss: 0.016100] [G loss: -0.054800] [d1 loss: 0.076767] [d2 loss: 0.072961]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 153/500] [Batch 460/676] [D loss: 0.013916] [G loss: -0.050396] [d1 loss: 0.141934] [d2 loss: 0.124302]  [sq d1 d2: 0.000311]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 480/676] [D loss: 0.001456] [G loss: -0.063083] [d1 loss: 0.183824] [d2 loss: 0.193263]  [sq d1 d2: 0.000089]  [num0: 15.000000] [num1 49.000000]
[Epoch 153/500] [Batch 500/676] [D loss: -0.006773] [G loss: -0.081302] [d1 loss: 0.067244] [d2 loss: 0.103226]  [sq d1 d2: 0.001295]  [num0: 14.000000] [num1 50.000000]
[Epoch 153/500] [Batch 520/676] [D loss: -0.020335] [G loss: -0.102474] [d1 loss: 0.212965] [d2 loss: 0.203319]  [sq d1 d2: 0.000093]  [num0: 18.000000] [num1 46.000000]
[Epoch 153/500] [Batch 540/676] [D loss: -0.041080] [G loss: -0.124068] [d1 loss: 0.051712] [d2 loss: 0.049113]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 153/500] [Batch 560/676] [D loss: -0.044563] [G loss: -0.065759] [d1 loss: 0.155824] [d2 loss: 0.121091]  [sq d1 d2: 0.001206]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 580/676] [D loss: -0.089108] [G loss: 0.028983] [d1 loss: 0.057272] [d2 loss: 0.059656]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 153/500] [Batch 600/676] [D loss: -0.105409] [G loss: 0.105338] [d1 loss: 0.186598] [d2 loss: 0.160128]  [sq d1 d2: 0.000701]  [num0: 17.000000] [num1 47.000000]
[Epoch 153/500] [Batch 620/676] [D loss: -0.034979] [G loss: 0.050278] [d1 loss: 0.132047] [d2 loss: 0.136600]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]

[Epoch 153/500] [Batch 640/676] [D loss: -0.047894] [G loss: 0.004030] [d1 loss: 0.062935] [d2 loss: 0.063599]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 153/500] [Batch 660/676] [D loss: 0.034435] [G loss: -0.130444] [d1 loss: 0.112822] [d2 loss: 0.128074]  [sq d1 d2: 0.000233]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 0/676] [D loss: 0.030958] [G loss: -0.121483] [d1 loss: 0.095334] [d2 loss: 0.084762]  [sq d1 d2: 0.000112]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 20/676] [D loss: 0.028021] [G loss: -0.084702] [d1 loss: 0.082619] [d2 loss: 0.072162]  [sq d1 d2: 0.000109]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 40/676] [D loss: 0.008634] [G loss: -0.053048] [d1 loss: 0.081397] [d2 loss: 0.100741]  [sq d1 d2: 0.000374]  [num0: 12.000000] [num1 52.000000]
[Epoch 154/500] [Batch 60/676] [D loss: -0.004784] [G loss: -0.021606] [d1 loss: 0.080034] [d2 loss: 0.089000]  [sq d1 d2: 0.000080]  [num0: 16.000000] [num1 48.000000]
[Epoch 154/500] [Batch 80/676] [D loss: -0.023184] [G loss: 0.001647] [d1 loss: 0.138072] [d2 loss: 0.171049]  [sq d1 d2: 0.001087]  [num0: 20.000000] [num1 44.000000]
[Epoch 154/500] [Batch 100/676] [D loss: -0.046450] [G loss: 0.049122] [d1 loss: 0.052967] [d2 loss: 0.037734]  [sq d1 d2: 0.000232]  [num0: 14.000000] [num1 50.000000]
[Epoch 154/500] [Batch 120/676] [D loss: -0.059101] [G loss: 0.106890] [d1 loss: 0.123663] [d2 loss: 0.106072]  [sq d1 d2: 0.000309]  [num0: 13.000000] [num1 51.000000]
[Epoch 154/500] [Batch 140/676] [D loss: -0.140384] [G loss: 0.087242] [d1 loss: 0.178376] [d2 loss: 0.190078]  [sq d1 d2: 0.000137]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 160/676] [D loss: -0.091864] [G loss: 0.107687] [d1 loss: 0.072389] [d2 loss: 0.058701]  [sq d1 d2: 0.000187]  [num0: 13.000000] [num1 51.000000]
[Epoch 154/500] [Batch 180/676] [D loss: 0.014476] [G loss: 0.056945] [d1 loss: 0.084644] [d2 loss: 0.072084]  [sq d1 d2: 0.000158]  [num0: 13.000000] [num1 51.000000]
[Epoch 154/500] [Batch 200/676] [D loss: -0.046464] [G loss: -0.001438] [d1 loss: 0.172776] [d2 loss: 0.202128]  [sq d1 d2: 0.000861]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 220/676] [D loss: -0.019043] [G loss: -0.096701] [d1 loss: 0.121213] [d2 loss: 0.102629]  [sq d1 d2: 0.000345]  [num0: 19.000000] [num1 45.000000]
[Epoch 154/500] [Batch 240/676] [D loss: 0.007398] [G loss: -0.144270] [d1 loss: 0.256812] [d2 loss: 0.230781]  [sq d1 d2: 0.000678]  [num0: 19.000000] [num1 45.000000]
[Epoch 154/500] [Batch 260/676] [D loss: 0.041500] [G loss: -0.160989] [d1 loss: 0.054032] [d2 loss: 0.045427]  [sq d1 d2: 0.000074]  [num0: 15.000000] [num1 49.000000]
[Epoch 154/500] [Batch 280/676] [D loss: 0.019537] [G loss: -0.137894] [d1 loss: 0.083170] [d2 loss: 0.077538]  [sq d1 d2: 0.000032]  [num0: 20.000000] [num1 44.000000]
[Epoch 154/500] [Batch 300/676] [D loss: 0.008452] [G loss: -0.098360] [d1 loss: 0.070157] [d2 loss: 0.067160]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 154/500] [Batch 320/676] [D loss: 0.001032] [G loss: -0.051520] [d1 loss: 0.095693] [d2 loss: 0.088672]  [sq d1 d2: 0.000049]  [num0: 12.000000] [num1 52.000000]
[Epoch 154/500] [Batch 340/676] [D loss: -0.012246] [G loss: -0.010017] [d1 loss: 0.121151] [d2 loss: 0.126511]  [sq d1 d2: 0.000029]  [num0: 11.000000] [num1 53.000000]
[Epoch 154/500] [Batch 360/676] [D loss: -0.018364] [G loss: 0.031580] [d1 loss: 0.030628] [d2 loss: 0.043213]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 380/676] [D loss: -0.034072] [G loss: 0.117940] [d1 loss: 0.034492] [d2 loss: 0.027968]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 400/676] [D loss: -0.053004] [G loss: 0.172038] [d1 loss: 0.077930] [d2 loss: 0.087438]  [sq d1 d2: 0.000090]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 420/676] [D loss: -0.075875] [G loss: 0.272082] [d1 loss: 0.135704] [d2 loss: 0.135497]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 440/676] [D loss: -0.043236] [G loss: 0.335566] [d1 loss: 0.098275] [d2 loss: 0.092696]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 154/500] [Batch 460/676] [D loss: 0.011913] [G loss: 0.327251] [d1 loss: 0.094614] [d2 loss: 0.086024]  [sq d1 d2: 0.000074]  [num0: 15.000000] [num1 49.000000]
[Epoch 154/500] [Batch 480/676] [D loss: 0.008933] [G loss: 0.315453] [d1 loss: 0.148848] [d2 loss: 0.132345]  [sq d1 d2: 0.000272]  [num0: 15.000000] [num1 49.000000]
[Epoch 154/500] [Batch 500/676] [D loss: -0.009181] [G loss: 0.119044] [d1 loss: 0.188734] [d2 loss: 0.178233]  [sq d1 d2: 0.000110]  [num0: 18.000000] [num1 46.000000]
[Epoch 154/500] [Batch 520/676] [D loss: 0.033194] [G loss: 0.030279] [d1 loss: 0.060720] [d2 loss: 0.091628]  [sq d1 d2: 0.000955]  [num0: 15.000000] [num1 49.000000]
[Epoch 154/500] [Batch 540/676] [D loss: 0.029232] [G loss: -0.040486] [d1 loss: 0.607269] [d2 loss: 0.507551]  [sq d1 d2: 0.009944]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 560/676] [D loss: 0.011031] [G loss: -0.050193] [d1 loss: 0.102786] [d2 loss: 0.092690]  [sq d1 d2: 0.000102]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 580/676] [D loss: -0.005628] [G loss: 0.009009] [d1 loss: 0.117020] [d2 loss: 0.142359]  [sq d1 d2: 0.000642]  [num0: 17.000000] [num1 47.000000]
[Epoch 154/500] [Batch 600/676] [D loss: -0.023373] [G loss: 0.062050] [d1 loss: 0.115928] [d2 loss: 0.126497]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 154/500] [Batch 620/676] [D loss: -0.047447] [G loss: 0.074234] [d1 loss: 0.071040] [d2 loss: 0.078775]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 154/500] [Batch 640/676] [D loss: -0.038978] [G loss: 0.053737] [d1 loss: 0.071580] [d2 loss: 0.069586]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 154/500] [Batch 660/676] [D loss: -0.033727] [G loss: 0.062165] [d1 loss: 0.066600] [d2 loss: 0.073566]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 0/676] [D loss: -0.060391] [G loss: 0.008707] [d1 loss: 0.038614] [d2 loss: 0.052182]  [sq d1 d2: 0.000184]  [num0: 18.000000] [num1 46.000000]
[Epoch 155/500] [Batch 20/676] [D loss: -0.009880] [G loss: -0.004210] [d1 loss: 0.186424] [d2 loss: 0.165460]  [sq d1 d2: 0.000439]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 40/676] [D loss: 0.014522] [G loss: -0.020177] [d1 loss: 0.061123] [d2 loss: 0.071980]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 60/676] [D loss: 0.008012] [G loss: -0.012077] [d1 loss: 0.069391] [d2 loss: 0.074276]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 80/676] [D loss: 0.006346] [G loss: -0.051565] [d1 loss: 0.044486] [d2 loss: 0.030927]  [sq d1 d2: 0.000184]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 100/676] [D loss: 0.012000] [G loss: -0.058320] [d1 loss: 0.041674] [d2 loss: 0.039666]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 120/676] [D loss: 0.008707] [G loss: -0.074800] [d1 loss: 0.075946] [d2 loss: 0.061471]  [sq d1 d2: 0.000210]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 140/676] [D loss: 0.016095] [G loss: -0.074572] [d1 loss: 0.073874] [d2 loss: 0.109653]  [sq d1 d2: 0.001280]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 160/676] [D loss: -0.002863] [G loss: -0.098930] [d1 loss: 0.109711] [d2 loss: 0.105249]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 155/500] [Batch 180/676] [D loss: -0.004959] [G loss: -0.115626] [d1 loss: 0.070276] [d2 loss: 0.057768]  [sq d1 d2: 0.000156]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 200/676] [D loss: -0.004242] [G loss: -0.133659] [d1 loss: 0.115278] [d2 loss: 0.125674]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 220/676] [D loss: -0.023497] [G loss: -0.186235] [d1 loss: 0.030089] [d2 loss: 0.034950]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 155/500] [Batch 240/676] [D loss: -0.047031] [G loss: -0.199709] [d1 loss: 0.125407] [d2 loss: 0.129643]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]

[Epoch 155/500] [Batch 260/676] [D loss: -0.046613] [G loss: -0.231781] [d1 loss: 0.146008] [d2 loss: 0.222924]  [sq d1 d2: 0.005916]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 280/676] [D loss: -0.038012] [G loss: -0.227754] [d1 loss: 0.121742] [d2 loss: 0.110855]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 300/676] [D loss: -0.053208] [G loss: -0.235009] [d1 loss: 0.100594] [d2 loss: 0.094244]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 155/500] [Batch 320/676] [D loss: 0.002256] [G loss: -0.149496] [d1 loss: 0.138977] [d2 loss: 0.105622]  [sq d1 d2: 0.001113]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 340/676] [D loss: -0.005625] [G loss: -0.124491] [d1 loss: 0.104131] [d2 loss: 0.120459]  [sq d1 d2: 0.000267]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 360/676] [D loss: -0.012176] [G loss: -0.048105] [d1 loss: 0.066921] [d2 loss: 0.069685]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 380/676] [D loss: 0.012341] [G loss: -0.030224] [d1 loss: 0.150562] [d2 loss: 0.119619]  [sq d1 d2: 0.000957]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 400/676] [D loss: 0.007906] [G loss: 0.007044] [d1 loss: 0.089535] [d2 loss: 0.109294]  [sq d1 d2: 0.000390]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 420/676] [D loss: 0.001887] [G loss: -0.013584] [d1 loss: 0.159563] [d2 loss: 0.108925]  [sq d1 d2: 0.002564]  [num0: 18.000000] [num1 46.000000]
[Epoch 155/500] [Batch 440/676] [D loss: 0.002556] [G loss: -0.019699] [d1 loss: 0.096574] [d2 loss: 0.119270]  [sq d1 d2: 0.000515]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 460/676] [D loss: -0.000367] [G loss: -0.041016] [d1 loss: 0.213883] [d2 loss: 0.184554]  [sq d1 d2: 0.000860]  [num0: 18.000000] [num1 46.000000]
[Epoch 155/500] [Batch 480/676] [D loss: -0.006862] [G loss: -0.057272] [d1 loss: 0.098230] [d2 loss: 0.118797]  [sq d1 d2: 0.000423]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 500/676] [D loss: -0.009931] [G loss: -0.071680] [d1 loss: 0.075713] [d2 loss: 0.074211]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 155/500] [Batch 520/676] [D loss: -0.004229] [G loss: -0.078264] [d1 loss: 0.075287] [d2 loss: 0.068173]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 155/500] [Batch 540/676] [D loss: -0.015838] [G loss: -0.097175] [d1 loss: 0.080336] [d2 loss: 0.057842]  [sq d1 d2: 0.000506]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 560/676] [D loss: -0.016471] [G loss: -0.108828] [d1 loss: 0.095775] [d2 loss: 0.097322]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 580/676] [D loss: -0.012115] [G loss: -0.113293] [d1 loss: 0.067670] [d2 loss: 0.117757]  [sq d1 d2: 0.002509]  [num0: 14.000000] [num1 50.000000]
[Epoch 155/500] [Batch 600/676] [D loss: -0.028059] [G loss: -0.146084] [d1 loss: 0.142000] [d2 loss: 0.173249]  [sq d1 d2: 0.000977]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 620/676] [D loss: -0.016296] [G loss: -0.165796] [d1 loss: 0.109931] [d2 loss: 0.096473]  [sq d1 d2: 0.000181]  [num0: 16.000000] [num1 48.000000]
[Epoch 155/500] [Batch 640/676] [D loss: -0.022525] [G loss: -0.175627] [d1 loss: 0.031310] [d2 loss: 0.037108]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 155/500] [Batch 660/676] [D loss: -0.035432] [G loss: -0.172586] [d1 loss: 0.066335] [d2 loss: 0.064885]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 0/676] [D loss: -0.002847] [G loss: -0.163999] [d1 loss: 0.085608] [d2 loss: 0.078998]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 20/676] [D loss: -0.004350] [G loss: -0.165008] [d1 loss: 0.128997] [d2 loss: 0.103509]  [sq d1 d2: 0.000650]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 40/676] [D loss: -0.001040] [G loss: -0.145505] [d1 loss: 0.066697] [d2 loss: 0.056224]  [sq d1 d2: 0.000110]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 60/676] [D loss: -0.006374] [G loss: -0.108425] [d1 loss: 0.160791] [d2 loss: 0.106172]  [sq d1 d2: 0.002983]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 80/676] [D loss: -0.015516] [G loss: -0.092918] [d1 loss: 0.061057] [d2 loss: 0.065967]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 100/676] [D loss: 0.015147] [G loss: -0.036173] [d1 loss: 0.040002] [d2 loss: 0.045774]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 120/676] [D loss: 0.006562] [G loss: -0.012521] [d1 loss: 0.074256] [d2 loss: 0.070707]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 156/500] [Batch 140/676] [D loss: 0.002452] [G loss: 0.010748] [d1 loss: 0.071861] [d2 loss: 0.094882]  [sq d1 d2: 0.000530]  [num0: 12.000000] [num1 52.000000]
[Epoch 156/500] [Batch 160/676] [D loss: 0.001150] [G loss: 0.035073] [d1 loss: 0.097251] [d2 loss: 0.090162]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 180/676] [D loss: -0.004611] [G loss: 0.052591] [d1 loss: 0.166786] [d2 loss: 0.162413]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 200/676] [D loss: -0.006551] [G loss: 0.071155] [d1 loss: 0.071638] [d2 loss: 0.064643]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 156/500] [Batch 220/676] [D loss: -0.005480] [G loss: 0.102401] [d1 loss: 0.078542] [d2 loss: 0.049930]  [sq d1 d2: 0.000819]  [num0: 17.000000] [num1 47.000000]
[Epoch 156/500] [Batch 240/676] [D loss: -0.001583] [G loss: 0.138216] [d1 loss: 0.131098] [d2 loss: 0.093610]  [sq d1 d2: 0.001405]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 260/676] [D loss: -0.031401] [G loss: 0.175199] [d1 loss: 0.071020] [d2 loss: 0.075994]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 156/500] [Batch 280/676] [D loss: -0.020590] [G loss: 0.183200] [d1 loss: 0.059660] [d2 loss: 0.059406]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 300/676] [D loss: -0.008653] [G loss: 0.191074] [d1 loss: 0.104513] [d2 loss: 0.122580]  [sq d1 d2: 0.000326]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 320/676] [D loss: -0.016484] [G loss: 0.183960] [d1 loss: 0.121774] [d2 loss: 0.126811]  [sq d1 d2: 0.000025]  [num0: 10.000000] [num1 54.000000]
[Epoch 156/500] [Batch 340/676] [D loss: 0.014369] [G loss: 0.191993] [d1 loss: 0.085379] [d2 loss: 0.103401]  [sq d1 d2: 0.000325]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 360/676] [D loss: 0.001446] [G loss: 0.167869] [d1 loss: 0.071513] [d2 loss: 0.056660]  [sq d1 d2: 0.000221]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 380/676] [D loss: 0.000127] [G loss: 0.175480] [d1 loss: 0.062613] [d2 loss: 0.059664]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 400/676] [D loss: 0.005386] [G loss: 0.138978] [d1 loss: 0.119860] [d2 loss: 0.113686]  [sq d1 d2: 0.000038]  [num0: 17.000000] [num1 47.000000]
[Epoch 156/500] [Batch 420/676] [D loss: 0.004588] [G loss: 0.079027] [d1 loss: 0.078944] [d2 loss: 0.096920]  [sq d1 d2: 0.000323]  [num0: 18.000000] [num1 46.000000]
[Epoch 156/500] [Batch 440/676] [D loss: -0.001082] [G loss: 0.049591] [d1 loss: 0.065222] [d2 loss: 0.070595]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 156/500] [Batch 460/676] [D loss: 0.003596] [G loss: 0.018955] [d1 loss: 0.130486] [d2 loss: 0.142866]  [sq d1 d2: 0.000153]  [num0: 17.000000] [num1 47.000000]
[Epoch 156/500] [Batch 480/676] [D loss: -0.003832] [G loss: 0.000786] [d1 loss: 0.059278] [d2 loss: 0.079637]  [sq d1 d2: 0.000415]  [num0: 11.000000] [num1 53.000000]
[Epoch 156/500] [Batch 500/676] [D loss: -0.004137] [G loss: -0.031632] [d1 loss: 0.111615] [d2 loss: 0.133374]  [sq d1 d2: 0.000473]  [num0: 17.000000] [num1 47.000000]
[Epoch 156/500] [Batch 520/676] [D loss: -0.005687] [G loss: -0.039756] [d1 loss: 0.036962] [d2 loss: 0.049263]  [sq d1 d2: 0.000151]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 540/676] [D loss: -0.007909] [G loss: -0.039549] [d1 loss: 0.054286] [d2 loss: 0.054105]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 156/500] [Batch 560/676] [D loss: -0.004521] [G loss: -0.050623] [d1 loss: 0.140815] [d2 loss: 0.139303]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 156/500] [Batch 580/676] [D loss: 0.002348] [G loss: -0.065928] [d1 loss: 0.040281] [d2 loss: 0.038323]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 600/676] [D loss: -0.012209] [G loss: -0.074570] [d1 loss: 0.118198] [d2 loss: 0.102283]  [sq d1 d2: 0.000253]  [num0: 14.000000] [num1 50.000000]

[Epoch 156/500] [Batch 620/676] [D loss: -0.003896] [G loss: -0.076276] [d1 loss: 0.040873] [d2 loss: 0.051492]  [sq d1 d2: 0.000113]  [num0: 16.000000] [num1 48.000000]
[Epoch 156/500] [Batch 640/676] [D loss: -0.004562] [G loss: -0.085173] [d1 loss: 0.075748] [d2 loss: 0.096536]  [sq d1 d2: 0.000432]  [num0: 12.000000] [num1 52.000000]
[Epoch 156/500] [Batch 660/676] [D loss: -0.001997] [G loss: -0.094057] [d1 loss: 0.091074] [d2 loss: 0.101233]  [sq d1 d2: 0.000103]  [num0: 17.000000] [num1 47.000000]
[Epoch 157/500] [Batch 0/676] [D loss: -0.015947] [G loss: -0.090356] [d1 loss: 0.051294] [d2 loss: 0.051087]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 157/500] [Batch 20/676] [D loss: -0.004014] [G loss: -0.101454] [d1 loss: 0.072005] [d2 loss: 0.073762]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 40/676] [D loss: -0.005308] [G loss: -0.085671] [d1 loss: 0.076487] [d2 loss: 0.069892]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 157/500] [Batch 60/676] [D loss: 0.000242] [G loss: -0.078518] [d1 loss: 0.104208] [d2 loss: 0.082485]  [sq d1 d2: 0.000472]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 80/676] [D loss: -0.002970] [G loss: -0.055033] [d1 loss: 0.074953] [d2 loss: 0.077188]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 157/500] [Batch 100/676] [D loss: 0.002599] [G loss: -0.052435] [d1 loss: 0.061302] [d2 loss: 0.056372]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 157/500] [Batch 120/676] [D loss: -0.001850] [G loss: -0.029070] [d1 loss: 0.048944] [d2 loss: 0.048646]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 157/500] [Batch 140/676] [D loss: -0.001148] [G loss: -0.015465] [d1 loss: 0.081542] [d2 loss: 0.086192]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 157/500] [Batch 160/676] [D loss: -0.002207] [G loss: -0.002135] [d1 loss: 0.052725] [d2 loss: 0.061371]  [sq d1 d2: 0.000075]  [num0: 13.000000] [num1 51.000000]
[Epoch 157/500] [Batch 180/676] [D loss: -0.004435] [G loss: 0.011381] [d1 loss: 0.054968] [d2 loss: 0.107811]  [sq d1 d2: 0.002792]  [num0: 14.000000] [num1 50.000000]
[Epoch 157/500] [Batch 200/676] [D loss: -0.002097] [G loss: 0.019076] [d1 loss: 0.092335] [d2 loss: 0.121061]  [sq d1 d2: 0.000825]  [num0: 17.000000] [num1 47.000000]
[Epoch 157/500] [Batch 220/676] [D loss: -0.005939] [G loss: 0.034834] [d1 loss: 0.054239] [d2 loss: 0.057173]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 157/500] [Batch 240/676] [D loss: -0.011346] [G loss: 0.034479] [d1 loss: 0.168528] [d2 loss: 0.169678]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 260/676] [D loss: -0.009257] [G loss: 0.033555] [d1 loss: 0.104440] [d2 loss: 0.078750]  [sq d1 d2: 0.000660]  [num0: 13.000000] [num1 51.000000]
[Epoch 157/500] [Batch 280/676] [D loss: -0.008335] [G loss: 0.038422] [d1 loss: 0.049786] [d2 loss: 0.063090]  [sq d1 d2: 0.000177]  [num0: 14.000000] [num1 50.000000]
[Epoch 157/500] [Batch 300/676] [D loss: -0.015851] [G loss: 0.034398] [d1 loss: 0.079329] [d2 loss: 0.083244]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 320/676] [D loss: 0.006418] [G loss: 0.041839] [d1 loss: 0.019550] [d2 loss: 0.021896]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 157/500] [Batch 340/676] [D loss: -0.004182] [G loss: 0.044321] [d1 loss: 0.086993] [d2 loss: 0.070461]  [sq d1 d2: 0.000273]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 360/676] [D loss: -0.005867] [G loss: 0.039703] [d1 loss: 0.155800] [d2 loss: 0.170646]  [sq d1 d2: 0.000220]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 380/676] [D loss: -0.003061] [G loss: 0.022313] [d1 loss: 0.073416] [d2 loss: 0.066956]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 157/500] [Batch 400/676] [D loss: 0.001029] [G loss: 0.025572] [d1 loss: 0.041610] [d2 loss: 0.037134]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 157/500] [Batch 420/676] [D loss: -0.002191] [G loss: 0.010947] [d1 loss: 0.174956] [d2 loss: 0.187198]  [sq d1 d2: 0.000150]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 440/676] [D loss: 0.001064] [G loss: 0.009888] [d1 loss: 0.075134] [d2 loss: 0.122701]  [sq d1 d2: 0.002263]  [num0: 20.000000] [num1 44.000000]
[Epoch 157/500] [Batch 460/676] [D loss: -0.001170] [G loss: 0.011537] [d1 loss: 0.062535] [d2 loss: 0.064799]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 157/500] [Batch 480/676] [D loss: -0.001162] [G loss: 0.001079] [d1 loss: 0.035983] [d2 loss: 0.038168]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 157/500] [Batch 500/676] [D loss: -0.001259] [G loss: -0.012997] [d1 loss: 0.072701] [d2 loss: 0.057594]  [sq d1 d2: 0.000228]  [num0: 17.000000] [num1 47.000000]
[Epoch 157/500] [Batch 520/676] [D loss: -0.003728] [G loss: -0.020314] [d1 loss: 0.105116] [d2 loss: 0.113477]  [sq d1 d2: 0.000070]  [num0: 10.000000] [num1 54.000000]
[Epoch 157/500] [Batch 540/676] [D loss: -0.007370] [G loss: -0.036219] [d1 loss: 0.196261] [d2 loss: 0.187459]  [sq d1 d2: 0.000077]  [num0: 19.000000] [num1 45.000000]
[Epoch 157/500] [Batch 560/676] [D loss: -0.013215] [G loss: -0.074627] [d1 loss: 0.058766] [d2 loss: 0.064518]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 157/500] [Batch 580/676] [D loss: -0.005086] [G loss: -0.108128] [d1 loss: 0.049212] [d2 loss: 0.064992]  [sq d1 d2: 0.000249]  [num0: 12.000000] [num1 52.000000]
[Epoch 157/500] [Batch 600/676] [D loss: -0.017064] [G loss: -0.121665] [d1 loss: 0.100527] [d2 loss: 0.120558]  [sq d1 d2: 0.000401]  [num0: 16.000000] [num1 48.000000]
[Epoch 157/500] [Batch 620/676] [D loss: -0.036835] [G loss: -0.144048] [d1 loss: 0.162670] [d2 loss: 0.150310]  [sq d1 d2: 0.000153]  [num0: 20.000000] [num1 44.000000]
[Epoch 157/500] [Batch 640/676] [D loss: -0.004427] [G loss: -0.153539] [d1 loss: 0.086192] [d2 loss: 0.106531]  [sq d1 d2: 0.000414]  [num0: 15.000000] [num1 49.000000]
[Epoch 157/500] [Batch 660/676] [D loss: 0.002281] [G loss: -0.144198] [d1 loss: 0.044363] [d2 loss: 0.050680]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 158/500] [Batch 0/676] [D loss: -0.004317] [G loss: -0.154826] [d1 loss: 0.159894] [d2 loss: 0.152072]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 20/676] [D loss: 0.005134] [G loss: -0.146323] [d1 loss: 0.058464] [d2 loss: 0.054590]  [sq d1 d2: 0.000015]  [num0: 20.000000] [num1 44.000000]
[Epoch 158/500] [Batch 40/676] [D loss: -0.001066] [G loss: -0.123685] [d1 loss: 0.143919] [d2 loss: 0.149795]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 158/500] [Batch 60/676] [D loss: -0.002542] [G loss: -0.082394] [d1 loss: 0.111860] [d2 loss: 0.073477]  [sq d1 d2: 0.001473]  [num0: 16.000000] [num1 48.000000]
[Epoch 158/500] [Batch 80/676] [D loss: -0.000366] [G loss: -0.081080] [d1 loss: 0.052740] [d2 loss: 0.042282]  [sq d1 d2: 0.000109]  [num0: 14.000000] [num1 50.000000]
[Epoch 158/500] [Batch 100/676] [D loss: -0.009264] [G loss: -0.069783] [d1 loss: 0.043701] [d2 loss: 0.056524]  [sq d1 d2: 0.000164]  [num0: 16.000000] [num1 48.000000]
[Epoch 158/500] [Batch 120/676] [D loss: 0.001955] [G loss: -0.040369] [d1 loss: 0.082121] [d2 loss: 0.075794]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 140/676] [D loss: -0.002913] [G loss: -0.035605] [d1 loss: 0.091913] [d2 loss: 0.081525]  [sq d1 d2: 0.000108]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 160/676] [D loss: -0.004822] [G loss: -0.036320] [d1 loss: 0.096209] [d2 loss: 0.133543]  [sq d1 d2: 0.001394]  [num0: 12.000000] [num1 52.000000]
[Epoch 158/500] [Batch 180/676] [D loss: -0.002176] [G loss: -0.035399] [d1 loss: 0.053643] [d2 loss: 0.052282]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 200/676] [D loss: -0.009479] [G loss: -0.034449] [d1 loss: 0.047164] [d2 loss: 0.052582]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 158/500] [Batch 220/676] [D loss: -0.010532] [G loss: -0.038759] [d1 loss: 0.054802] [d2 loss: 0.031681]  [sq d1 d2: 0.000535]  [num0: 18.000000] [num1 46.000000]

[Epoch 158/500] [Batch 240/676] [D loss: -0.002840] [G loss: -0.030619] [d1 loss: 0.111906] [d2 loss: 0.080538]  [sq d1 d2: 0.000984]  [num0: 14.000000] [num1 50.000000]
[Epoch 158/500] [Batch 260/676] [D loss: -0.006266] [G loss: -0.022088] [d1 loss: 0.082590] [d2 loss: 0.070373]  [sq d1 d2: 0.000149]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 280/676] [D loss: -0.012751] [G loss: -0.043311] [d1 loss: 0.082410] [d2 loss: 0.089320]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 158/500] [Batch 300/676] [D loss: -0.002068] [G loss: -0.045652] [d1 loss: 0.118677] [d2 loss: 0.081423]  [sq d1 d2: 0.001388]  [num0: 20.000000] [num1 44.000000]
[Epoch 158/500] [Batch 320/676] [D loss: -0.007460] [G loss: -0.049170] [d1 loss: 0.058340] [d2 loss: 0.059931]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 158/500] [Batch 340/676] [D loss: 0.007944] [G loss: -0.055718] [d1 loss: 0.046813] [d2 loss: 0.052317]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 360/676] [D loss: -0.006133] [G loss: -0.058708] [d1 loss: 0.071335] [d2 loss: 0.064155]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 158/500] [Batch 380/676] [D loss: -0.013045] [G loss: -0.070693] [d1 loss: 0.140513] [d2 loss: 0.152066]  [sq d1 d2: 0.000133]  [num0: 15.000000] [num1 49.000000]
[Epoch 158/500] [Batch 400/676] [D loss: -0.004939] [G loss: -0.072524] [d1 loss: 0.115661] [d2 loss: 0.124933]  [sq d1 d2: 0.000086]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 420/676] [D loss: -0.006887] [G loss: -0.077098] [d1 loss: 0.079133] [d2 loss: 0.131375]  [sq d1 d2: 0.002729]  [num0: 19.000000] [num1 45.000000]
[Epoch 158/500] [Batch 440/676] [D loss: -0.003831] [G loss: -0.084243] [d1 loss: 0.049398] [d2 loss: 0.031929]  [sq d1 d2: 0.000305]  [num0: 15.000000] [num1 49.000000]
[Epoch 158/500] [Batch 460/676] [D loss: -0.015412] [G loss: -0.089293] [d1 loss: 0.054862] [d2 loss: 0.059348]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 480/676] [D loss: 0.000893] [G loss: -0.105447] [d1 loss: 0.112638] [d2 loss: 0.124480]  [sq d1 d2: 0.000140]  [num0: 14.000000] [num1 50.000000]
[Epoch 158/500] [Batch 500/676] [D loss: -0.002892] [G loss: -0.114993] [d1 loss: 0.046901] [d2 loss: 0.066464]  [sq d1 d2: 0.000383]  [num0: 13.000000] [num1 51.000000]
[Epoch 158/500] [Batch 520/676] [D loss: -0.000697] [G loss: -0.121590] [d1 loss: 0.158496] [d2 loss: 0.163533]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 540/676] [D loss: -0.000169] [G loss: -0.107079] [d1 loss: 0.097715] [d2 loss: 0.088328]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]
[Epoch 158/500] [Batch 560/676] [D loss: -0.000165] [G loss: -0.107618] [d1 loss: 0.081060] [d2 loss: 0.069088]  [sq d1 d2: 0.000143]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 580/676] [D loss: 0.003311] [G loss: -0.099359] [d1 loss: 0.094590] [d2 loss: 0.102077]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 158/500] [Batch 600/676] [D loss: -0.010189] [G loss: -0.100090] [d1 loss: 0.044711] [d2 loss: 0.038293]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 158/500] [Batch 620/676] [D loss: -0.006568] [G loss: -0.079987] [d1 loss: 0.053640] [d2 loss: 0.055356]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 158/500] [Batch 640/676] [D loss: -0.008189] [G loss: -0.083716] [d1 loss: 0.033138] [d2 loss: 0.038520]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 158/500] [Batch 660/676] [D loss: -0.003821] [G loss: -0.072954] [d1 loss: 0.077776] [d2 loss: 0.062482]  [sq d1 d2: 0.000234]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 0/676] [D loss: -0.005841] [G loss: -0.066544] [d1 loss: 0.061462] [d2 loss: 0.046178]  [sq d1 d2: 0.000234]  [num0: 17.000000] [num1 47.000000]
[Epoch 159/500] [Batch 20/676] [D loss: -0.003153] [G loss: -0.044905] [d1 loss: 0.075806] [d2 loss: 0.068784]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 40/676] [D loss: -0.008336] [G loss: -0.027087] [d1 loss: 0.091727] [d2 loss: 0.089044]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 60/676] [D loss: -0.003535] [G loss: -0.037097] [d1 loss: 0.034897] [d2 loss: 0.044496]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 80/676] [D loss: -0.012984] [G loss: -0.029448] [d1 loss: 0.049275] [d2 loss: 0.055324]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 100/676] [D loss: -0.014352] [G loss: -0.012375] [d1 loss: 0.030957] [d2 loss: 0.027655]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 120/676] [D loss: -0.028009] [G loss: -0.011306] [d1 loss: 0.068827] [d2 loss: 0.062204]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 159/500] [Batch 140/676] [D loss: -0.008965] [G loss: -0.018263] [d1 loss: 0.159769] [d2 loss: 0.139042]  [sq d1 d2: 0.000430]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 160/676] [D loss: -0.000187] [G loss: -0.012399] [d1 loss: 0.160503] [d2 loss: 0.130693]  [sq d1 d2: 0.000889]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 180/676] [D loss: -0.012318] [G loss: -0.001551] [d1 loss: 0.207364] [d2 loss: 0.187103]  [sq d1 d2: 0.000410]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 200/676] [D loss: -0.008918] [G loss: -0.009696] [d1 loss: 0.086879] [d2 loss: 0.076445]  [sq d1 d2: 0.000109]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 220/676] [D loss: -0.004554] [G loss: -0.038872] [d1 loss: 0.073832] [d2 loss: 0.067951]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 240/676] [D loss: 0.000513] [G loss: -0.019893] [d1 loss: 0.045586] [d2 loss: 0.046128]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 260/676] [D loss: -0.003340] [G loss: -0.024590] [d1 loss: 0.029342] [d2 loss: 0.032637]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 159/500] [Batch 280/676] [D loss: -0.006918] [G loss: -0.024680] [d1 loss: 0.080189] [d2 loss: 0.103115]  [sq d1 d2: 0.000526]  [num0: 17.000000] [num1 47.000000]
[Epoch 159/500] [Batch 300/676] [D loss: -0.001070] [G loss: -0.036062] [d1 loss: 0.113930] [d2 loss: 0.107360]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 159/500] [Batch 320/676] [D loss: -0.003708] [G loss: -0.045976] [d1 loss: 0.069573] [d2 loss: 0.068842]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 340/676] [D loss: -0.010225] [G loss: -0.046939] [d1 loss: 0.071779] [d2 loss: 0.076000]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 360/676] [D loss: -0.010026] [G loss: -0.050384] [d1 loss: 0.073995] [d2 loss: 0.082617]  [sq d1 d2: 0.000074]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 380/676] [D loss: -0.011467] [G loss: -0.053201] [d1 loss: 0.124476] [d2 loss: 0.081020]  [sq d1 d2: 0.001888]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 400/676] [D loss: -0.017265] [G loss: -0.056311] [d1 loss: 0.057988] [d2 loss: 0.056272]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 420/676] [D loss: -0.003841] [G loss: -0.076226] [d1 loss: 0.121373] [d2 loss: 0.124498]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 159/500] [Batch 440/676] [D loss: -0.015659] [G loss: -0.085483] [d1 loss: 0.056105] [d2 loss: 0.050168]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 460/676] [D loss: -0.013213] [G loss: -0.089755] [d1 loss: 0.071759] [d2 loss: 0.071413]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 480/676] [D loss: -0.002878] [G loss: -0.098603] [d1 loss: 0.043143] [d2 loss: 0.060379]  [sq d1 d2: 0.000297]  [num0: 17.000000] [num1 47.000000]
[Epoch 159/500] [Batch 500/676] [D loss: -0.012629] [G loss: -0.069476] [d1 loss: 0.109307] [d2 loss: 0.132151]  [sq d1 d2: 0.000522]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 520/676] [D loss: 0.017529] [G loss: -0.055248] [d1 loss: 0.049387] [d2 loss: 0.060065]  [sq d1 d2: 0.000114]  [num0: 16.000000] [num1 48.000000]

[Epoch 159/500] [Batch 540/676] [D loss: -0.006092] [G loss: -0.072910] [d1 loss: 0.031679] [d2 loss: 0.035324]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 560/676] [D loss: -0.009140] [G loss: -0.050965] [d1 loss: 0.072926] [d2 loss: 0.059356]  [sq d1 d2: 0.000184]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 580/676] [D loss: -0.001585] [G loss: -0.051482] [d1 loss: 0.059147] [d2 loss: 0.060430]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 159/500] [Batch 600/676] [D loss: -0.008145] [G loss: -0.054316] [d1 loss: 0.082739] [d2 loss: 0.086689]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 159/500] [Batch 620/676] [D loss: -0.020244] [G loss: -0.062841] [d1 loss: 0.044920] [d2 loss: 0.045858]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 159/500] [Batch 640/676] [D loss: -0.017775] [G loss: -0.060062] [d1 loss: 0.057378] [d2 loss: 0.055657]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 159/500] [Batch 660/676] [D loss: -0.003383] [G loss: -0.086597] [d1 loss: 0.113916] [d2 loss: 0.112602]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 160/500] [Batch 0/676] [D loss: -0.014490] [G loss: -0.097630] [d1 loss: 0.096100] [d2 loss: 0.083039]  [sq d1 d2: 0.000171]  [num0: 13.000000] [num1 51.000000]
[Epoch 160/500] [Batch 20/676] [D loss: -0.014247] [G loss: -0.074201] [d1 loss: 0.051722] [d2 loss: 0.059866]  [sq d1 d2: 0.000066]  [num0: 14.000000] [num1 50.000000]
[Epoch 160/500] [Batch 40/676] [D loss: -0.012198] [G loss: -0.077918] [d1 loss: 0.192344] [d2 loss: 0.166963]  [sq d1 d2: 0.000644]  [num0: 17.000000] [num1 47.000000]
[Epoch 160/500] [Batch 60/676] [D loss: 0.002646] [G loss: -0.068245] [d1 loss: 0.058321] [d2 loss: 0.068902]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 160/500] [Batch 80/676] [D loss: -0.007408] [G loss: -0.065123] [d1 loss: 0.014877] [d2 loss: 0.011323]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 160/500] [Batch 100/676] [D loss: -0.012027] [G loss: -0.077067] [d1 loss: 0.048184] [d2 loss: 0.047665]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 120/676] [D loss: -0.007549] [G loss: -0.076363] [d1 loss: 0.078803] [d2 loss: 0.089840]  [sq d1 d2: 0.000122]  [num0: 18.000000] [num1 46.000000]
[Epoch 160/500] [Batch 140/676] [D loss: -0.002601] [G loss: -0.078332] [d1 loss: 0.177647] [d2 loss: 0.162129]  [sq d1 d2: 0.000241]  [num0: 20.000000] [num1 44.000000]
[Epoch 160/500] [Batch 160/676] [D loss: -0.007258] [G loss: -0.100330] [d1 loss: 0.087793] [d2 loss: 0.097097]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 180/676] [D loss: -0.022867] [G loss: -0.108927] [d1 loss: 0.094488] [d2 loss: 0.112590]  [sq d1 d2: 0.000328]  [num0: 17.000000] [num1 47.000000]
[Epoch 160/500] [Batch 200/676] [D loss: -0.007055] [G loss: -0.099148] [d1 loss: 0.100803] [d2 loss: 0.100745]  [sq d1 d2: 0.000000]  [num0: 22.000000] [num1 42.000000]
[Epoch 160/500] [Batch 220/676] [D loss: -0.015767] [G loss: -0.114290] [d1 loss: 0.086877] [d2 loss: 0.063613]  [sq d1 d2: 0.000541]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 240/676] [D loss: -0.017194] [G loss: -0.131408] [d1 loss: 0.060951] [d2 loss: 0.056725]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 260/676] [D loss: -0.010973] [G loss: -0.122600] [d1 loss: 0.056020] [d2 loss: 0.047339]  [sq d1 d2: 0.000075]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 280/676] [D loss: -0.017656] [G loss: -0.114170] [d1 loss: 0.142419] [d2 loss: 0.126289]  [sq d1 d2: 0.000260]  [num0: 18.000000] [num1 46.000000]
[Epoch 160/500] [Batch 300/676] [D loss: -0.005400] [G loss: -0.124060] [d1 loss: 0.042843] [d2 loss: 0.042062]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 320/676] [D loss: -0.005700] [G loss: -0.121968] [d1 loss: 0.064016] [d2 loss: 0.050442]  [sq d1 d2: 0.000184]  [num0: 16.000000] [num1 48.000000]
[Epoch 160/500] [Batch 340/676] [D loss: -0.015062] [G loss: -0.129169] [d1 loss: 0.068601] [d2 loss: 0.075301]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 360/676] [D loss: -0.004023] [G loss: -0.125889] [d1 loss: 0.071802] [d2 loss: 0.076792]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 160/500] [Batch 380/676] [D loss: -0.001155] [G loss: -0.122178] [d1 loss: 0.065078] [d2 loss: 0.053031]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 160/500] [Batch 400/676] [D loss: -0.008110] [G loss: -0.135405] [d1 loss: 0.075641] [d2 loss: 0.078323]  [sq d1 d2: 0.000007]  [num0: 20.000000] [num1 44.000000]
[Epoch 160/500] [Batch 420/676] [D loss: -0.010459] [G loss: -0.110751] [d1 loss: 0.080117] [d2 loss: 0.064332]  [sq d1 d2: 0.000249]  [num0: 20.000000] [num1 44.000000]
[Epoch 160/500] [Batch 440/676] [D loss: -0.012082] [G loss: -0.105777] [d1 loss: 0.084700] [d2 loss: 0.095806]  [sq d1 d2: 0.000123]  [num0: 18.000000] [num1 46.000000]
[Epoch 160/500] [Batch 460/676] [D loss: -0.001670] [G loss: -0.114901] [d1 loss: 0.043816] [d2 loss: 0.053181]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 160/500] [Batch 480/676] [D loss: -0.014676] [G loss: -0.125626] [d1 loss: 0.089997] [d2 loss: 0.096090]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 500/676] [D loss: -0.014375] [G loss: -0.154593] [d1 loss: 0.071126] [d2 loss: 0.107487]  [sq d1 d2: 0.001322]  [num0: 17.000000] [num1 47.000000]
[Epoch 160/500] [Batch 520/676] [D loss: -0.015102] [G loss: -0.163862] [d1 loss: 0.025979] [d2 loss: 0.023973]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 160/500] [Batch 540/676] [D loss: -0.005563] [G loss: -0.153734] [d1 loss: 0.028487] [d2 loss: 0.044535]  [sq d1 d2: 0.000258]  [num0: 17.000000] [num1 47.000000]
[Epoch 160/500] [Batch 560/676] [D loss: -0.018480] [G loss: -0.138655] [d1 loss: 0.072723] [d2 loss: 0.062666]  [sq d1 d2: 0.000101]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 580/676] [D loss: -0.019666] [G loss: -0.155484] [d1 loss: 0.077195] [d2 loss: 0.066174]  [sq d1 d2: 0.000121]  [num0: 20.000000] [num1 44.000000]
[Epoch 160/500] [Batch 600/676] [D loss: -0.003684] [G loss: -0.140471] [d1 loss: 0.075767] [d2 loss: 0.081606]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 160/500] [Batch 620/676] [D loss: -0.014778] [G loss: -0.146284] [d1 loss: 0.049278] [d2 loss: 0.058428]  [sq d1 d2: 0.000084]  [num0: 19.000000] [num1 45.000000]
[Epoch 160/500] [Batch 640/676] [D loss: -0.009760] [G loss: -0.119595] [d1 loss: 0.076867] [d2 loss: 0.089417]  [sq d1 d2: 0.000157]  [num0: 11.000000] [num1 53.000000]
[Epoch 160/500] [Batch 660/676] [D loss: -0.013768] [G loss: -0.120439] [d1 loss: 0.038550] [d2 loss: 0.035508]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 0/676] [D loss: -0.012489] [G loss: -0.131711] [d1 loss: 0.028535] [d2 loss: 0.021430]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 161/500] [Batch 20/676] [D loss: -0.003587] [G loss: -0.114152] [d1 loss: 0.050450] [d2 loss: 0.046276]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 40/676] [D loss: -0.019543] [G loss: -0.109028] [d1 loss: 0.125729] [d2 loss: 0.109921]  [sq d1 d2: 0.000250]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 60/676] [D loss: -0.012780] [G loss: -0.095147] [d1 loss: 0.038039] [d2 loss: 0.031921]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 80/676] [D loss: -0.023112] [G loss: -0.099885] [d1 loss: 0.050562] [d2 loss: 0.071542]  [sq d1 d2: 0.000440]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 100/676] [D loss: -0.007740] [G loss: -0.073316] [d1 loss: 0.067604] [d2 loss: 0.063115]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 120/676] [D loss: -0.006085] [G loss: -0.059738] [d1 loss: 0.053800] [d2 loss: 0.034945]  [sq d1 d2: 0.000355]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 140/676] [D loss: -0.009128] [G loss: -0.058160] [d1 loss: 0.082055] [d2 loss: 0.072509]  [sq d1 d2: 0.000091]  [num0: 13.000000] [num1 51.000000]
[Epoch 161/500] [Batch 160/676] [D loss: -0.012187] [G loss: -0.068724] [d1 loss: 0.082753] [d2 loss: 0.069341]  [sq d1 d2: 0.000180]  [num0: 13.000000] [num1 51.000000]
[Epoch 161/500] [Batch 180/676] [D loss: -0.009128] [G loss: -0.070460] [d1 loss: 0.032514] [d2 loss: 0.033652]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 200/676] [D loss: -0.008024] [G loss: -0.052509] [d1 loss: 0.056477] [d2 loss: 0.052751]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]

[Epoch 161/500] [Batch 220/676] [D loss: -0.007483] [G loss: -0.020259] [d1 loss: 0.096283] [d2 loss: 0.094651]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 161/500] [Batch 240/676] [D loss: -0.006685] [G loss: -0.022878] [d1 loss: 0.119820] [d2 loss: 0.094731]  [sq d1 d2: 0.000629]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 260/676] [D loss: -0.008233] [G loss: -0.015144] [d1 loss: 0.083547] [d2 loss: 0.086626]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 161/500] [Batch 280/676] [D loss: -0.010861] [G loss: -0.005910] [d1 loss: 0.090789] [d2 loss: 0.101833]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 300/676] [D loss: -0.006646] [G loss: -0.019142] [d1 loss: 0.073555] [d2 loss: 0.065797]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 320/676] [D loss: -0.015455] [G loss: -0.033344] [d1 loss: 0.152165] [d2 loss: 0.148220]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 161/500] [Batch 340/676] [D loss: -0.014064] [G loss: -0.040963] [d1 loss: 0.073096] [d2 loss: 0.056531]  [sq d1 d2: 0.000274]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 360/676] [D loss: -0.011882] [G loss: -0.083658] [d1 loss: 0.089371] [d2 loss: 0.075917]  [sq d1 d2: 0.000181]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 380/676] [D loss: -0.001499] [G loss: -0.098106] [d1 loss: 0.117257] [d2 loss: 0.122355]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 161/500] [Batch 400/676] [D loss: -0.017393] [G loss: -0.125457] [d1 loss: 0.092725] [d2 loss: 0.083197]  [sq d1 d2: 0.000091]  [num0: 20.000000] [num1 44.000000]
[Epoch 161/500] [Batch 420/676] [D loss: -0.013837] [G loss: -0.121796] [d1 loss: 0.060189] [d2 loss: 0.094438]  [sq d1 d2: 0.001173]  [num0: 14.000000] [num1 50.000000]
[Epoch 161/500] [Batch 440/676] [D loss: -0.016083] [G loss: -0.174527] [d1 loss: 0.089172] [d2 loss: 0.061907]  [sq d1 d2: 0.000743]  [num0: 14.000000] [num1 50.000000]
[Epoch 161/500] [Batch 460/676] [D loss: -0.008346] [G loss: -0.155555] [d1 loss: 0.039237] [d2 loss: 0.042875]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 161/500] [Batch 480/676] [D loss: -0.011848] [G loss: -0.148692] [d1 loss: 0.031017] [d2 loss: 0.035557]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 500/676] [D loss: -0.012689] [G loss: -0.167694] [d1 loss: 0.033283] [d2 loss: 0.037400]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 520/676] [D loss: -0.030892] [G loss: -0.180192] [d1 loss: 0.055910] [d2 loss: 0.048331]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 161/500] [Batch 540/676] [D loss: -0.007770] [G loss: -0.178360] [d1 loss: 0.197901] [d2 loss: 0.150343]  [sq d1 d2: 0.002262]  [num0: 13.000000] [num1 51.000000]
[Epoch 161/500] [Batch 560/676] [D loss: -0.026391] [G loss: -0.168951] [d1 loss: 0.096557] [d2 loss: 0.109146]  [sq d1 d2: 0.000158]  [num0: 21.000000] [num1 43.000000]
[Epoch 161/500] [Batch 580/676] [D loss: -0.029241] [G loss: -0.154133] [d1 loss: 0.076634] [d2 loss: 0.063554]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 600/676] [D loss: -0.018008] [G loss: -0.123191] [d1 loss: 0.128293] [d2 loss: 0.148705]  [sq d1 d2: 0.000417]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 620/676] [D loss: 0.007968] [G loss: -0.141687] [d1 loss: 0.078406] [d2 loss: 0.077050]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 161/500] [Batch 640/676] [D loss: -0.013079] [G loss: -0.120359] [d1 loss: 0.121152] [d2 loss: 0.125333]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 161/500] [Batch 660/676] [D loss: -0.007426] [G loss: -0.068724] [d1 loss: 0.071648] [d2 loss: 0.062444]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 0/676] [D loss: -0.008968] [G loss: -0.064711] [d1 loss: 0.063794] [d2 loss: 0.047837]  [sq d1 d2: 0.000255]  [num0: 17.000000] [num1 47.000000]
[Epoch 162/500] [Batch 20/676] [D loss: -0.017377] [G loss: -0.056253] [d1 loss: 0.036245] [d2 loss: 0.033444]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 162/500] [Batch 40/676] [D loss: -0.023094] [G loss: -0.026830] [d1 loss: 0.065989] [d2 loss: 0.078644]  [sq d1 d2: 0.000160]  [num0: 17.000000] [num1 47.000000]
[Epoch 162/500] [Batch 60/676] [D loss: -0.009352] [G loss: -0.025722] [d1 loss: 0.065920] [d2 loss: 0.057595]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 162/500] [Batch 80/676] [D loss: -0.022680] [G loss: -0.033011] [d1 loss: 0.075369] [d2 loss: 0.067657]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 100/676] [D loss: -0.021813] [G loss: -0.032663] [d1 loss: 0.089981] [d2 loss: 0.111723]  [sq d1 d2: 0.000473]  [num0: 17.000000] [num1 47.000000]
[Epoch 162/500] [Batch 120/676] [D loss: -0.016212] [G loss: -0.034339] [d1 loss: 0.094029] [d2 loss: 0.078834]  [sq d1 d2: 0.000231]  [num0: 17.000000] [num1 47.000000]
[Epoch 162/500] [Batch 140/676] [D loss: -0.014566] [G loss: -0.041563] [d1 loss: 0.096179] [d2 loss: 0.076164]  [sq d1 d2: 0.000401]  [num0: 14.000000] [num1 50.000000]
[Epoch 162/500] [Batch 160/676] [D loss: -0.013306] [G loss: -0.037247] [d1 loss: 0.054435] [d2 loss: 0.044937]  [sq d1 d2: 0.000090]  [num0: 18.000000] [num1 46.000000]
[Epoch 162/500] [Batch 180/676] [D loss: -0.018903] [G loss: -0.028761] [d1 loss: 0.056594] [d2 loss: 0.028440]  [sq d1 d2: 0.000793]  [num0: 14.000000] [num1 50.000000]
[Epoch 162/500] [Batch 200/676] [D loss: -0.010609] [G loss: -0.057968] [d1 loss: 0.050341] [d2 loss: 0.049510]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 162/500] [Batch 220/676] [D loss: -0.015500] [G loss: -0.052017] [d1 loss: 0.033110] [d2 loss: 0.034387]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 162/500] [Batch 240/676] [D loss: -0.004414] [G loss: -0.053641] [d1 loss: 0.063935] [d2 loss: 0.076482]  [sq d1 d2: 0.000157]  [num0: 19.000000] [num1 45.000000]
[Epoch 162/500] [Batch 260/676] [D loss: -0.017272] [G loss: -0.046194] [d1 loss: 0.073500] [d2 loss: 0.074856]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 280/676] [D loss: -0.007860] [G loss: -0.045119] [d1 loss: 0.039416] [d2 loss: 0.033666]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 162/500] [Batch 300/676] [D loss: -0.005580] [G loss: -0.036353] [d1 loss: 0.078039] [d2 loss: 0.067862]  [sq d1 d2: 0.000104]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 320/676] [D loss: -0.007788] [G loss: -0.052267] [d1 loss: 0.061328] [d2 loss: 0.060735]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 340/676] [D loss: -0.023435] [G loss: -0.064475] [d1 loss: 0.078156] [d2 loss: 0.115929]  [sq d1 d2: 0.001427]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 360/676] [D loss: -0.014423] [G loss: -0.080396] [d1 loss: 0.044580] [d2 loss: 0.041953]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 162/500] [Batch 380/676] [D loss: -0.016710] [G loss: -0.061380] [d1 loss: 0.067749] [d2 loss: 0.059801]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 400/676] [D loss: -0.026185] [G loss: -0.065239] [d1 loss: 0.037047] [d2 loss: 0.040321]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 420/676] [D loss: -0.014617] [G loss: -0.087490] [d1 loss: 0.041212] [d2 loss: 0.053481]  [sq d1 d2: 0.000151]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 440/676] [D loss: -0.013043] [G loss: -0.106215] [d1 loss: 0.060073] [d2 loss: 0.071789]  [sq d1 d2: 0.000137]  [num0: 14.000000] [num1 50.000000]
[Epoch 162/500] [Batch 460/676] [D loss: -0.009192] [G loss: -0.100453] [d1 loss: 0.079935] [d2 loss: 0.065824]  [sq d1 d2: 0.000199]  [num0: 14.000000] [num1 50.000000]
[Epoch 162/500] [Batch 480/676] [D loss: -0.007322] [G loss: -0.093368] [d1 loss: 0.041813] [d2 loss: 0.031853]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 162/500] [Batch 500/676] [D loss: -0.017381] [G loss: -0.101894] [d1 loss: 0.092229] [d2 loss: 0.070433]  [sq d1 d2: 0.000475]  [num0: 18.000000] [num1 46.000000]

[Epoch 162/500] [Batch 520/676] [D loss: 0.002887] [G loss: -0.079948] [d1 loss: 0.049918] [d2 loss: 0.036220]  [sq d1 d2: 0.000188]  [num0: 13.000000] [num1 51.000000]
[Epoch 162/500] [Batch 540/676] [D loss: -0.009906] [G loss: -0.090704] [d1 loss: 0.082802] [d2 loss: 0.088877]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 560/676] [D loss: -0.008287] [G loss: -0.115032] [d1 loss: 0.039113] [d2 loss: 0.057678]  [sq d1 d2: 0.000345]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 580/676] [D loss: -0.008543] [G loss: -0.125961] [d1 loss: 0.093575] [d2 loss: 0.096368]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 162/500] [Batch 600/676] [D loss: -0.017222] [G loss: -0.150228] [d1 loss: 0.031913] [d2 loss: 0.031697]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 162/500] [Batch 620/676] [D loss: -0.011588] [G loss: -0.169151] [d1 loss: 0.072468] [d2 loss: 0.066156]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 162/500] [Batch 640/676] [D loss: -0.020533] [G loss: -0.170259] [d1 loss: 0.069201] [d2 loss: 0.047404]  [sq d1 d2: 0.000475]  [num0: 19.000000] [num1 45.000000]
[Epoch 162/500] [Batch 660/676] [D loss: -0.018574] [G loss: -0.166266] [d1 loss: 0.028872] [d2 loss: 0.032380]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 0/676] [D loss: -0.028911] [G loss: -0.164035] [d1 loss: 0.046182] [d2 loss: 0.046700]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 20/676] [D loss: -0.007582] [G loss: -0.162702] [d1 loss: 0.080397] [d2 loss: 0.061926]  [sq d1 d2: 0.000341]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 40/676] [D loss: 0.000779] [G loss: -0.125715] [d1 loss: 0.036584] [d2 loss: 0.034668]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 163/500] [Batch 60/676] [D loss: -0.011291] [G loss: -0.137565] [d1 loss: 0.055563] [d2 loss: 0.051878]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 80/676] [D loss: -0.003667] [G loss: -0.128219] [d1 loss: 0.028136] [d2 loss: 0.028992]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 100/676] [D loss: -0.010695] [G loss: -0.142779] [d1 loss: 0.235510] [d2 loss: 0.263138]  [sq d1 d2: 0.000763]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 120/676] [D loss: -0.022024] [G loss: -0.127850] [d1 loss: 0.046160] [d2 loss: 0.036426]  [sq d1 d2: 0.000095]  [num0: 12.000000] [num1 52.000000]
[Epoch 163/500] [Batch 140/676] [D loss: -0.008226] [G loss: -0.145731] [d1 loss: 0.054959] [d2 loss: 0.033270]  [sq d1 d2: 0.000470]  [num0: 12.000000] [num1 52.000000]
[Epoch 163/500] [Batch 160/676] [D loss: -0.014385] [G loss: -0.162554] [d1 loss: 0.028314] [d2 loss: 0.055833]  [sq d1 d2: 0.000757]  [num0: 19.000000] [num1 45.000000]
[Epoch 163/500] [Batch 180/676] [D loss: -0.009776] [G loss: -0.168190] [d1 loss: 0.058331] [d2 loss: 0.046525]  [sq d1 d2: 0.000139]  [num0: 19.000000] [num1 45.000000]
[Epoch 163/500] [Batch 200/676] [D loss: -0.018289] [G loss: -0.165615] [d1 loss: 0.112088] [d2 loss: 0.088150]  [sq d1 d2: 0.000573]  [num0: 17.000000] [num1 47.000000]
[Epoch 163/500] [Batch 220/676] [D loss: -0.018873] [G loss: -0.147331] [d1 loss: 0.025774] [d2 loss: 0.027269]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 240/676] [D loss: -0.009338] [G loss: -0.131301] [d1 loss: 0.067220] [d2 loss: 0.057281]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 260/676] [D loss: -0.000757] [G loss: -0.130575] [d1 loss: 0.102389] [d2 loss: 0.070069]  [sq d1 d2: 0.001045]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 280/676] [D loss: -0.002215] [G loss: -0.128686] [d1 loss: 0.073112] [d2 loss: 0.043946]  [sq d1 d2: 0.000851]  [num0: 19.000000] [num1 45.000000]
[Epoch 163/500] [Batch 300/676] [D loss: -0.009786] [G loss: -0.115311] [d1 loss: 0.097850] [d2 loss: 0.108207]  [sq d1 d2: 0.000107]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 320/676] [D loss: -0.022643] [G loss: -0.086897] [d1 loss: 0.029951] [d2 loss: 0.032002]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 163/500] [Batch 340/676] [D loss: -0.023311] [G loss: -0.073450] [d1 loss: 0.072058] [d2 loss: 0.072765]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 360/676] [D loss: -0.019553] [G loss: -0.083281] [d1 loss: 0.074754] [d2 loss: 0.070822]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 380/676] [D loss: -0.023736] [G loss: -0.070882] [d1 loss: 0.058546] [d2 loss: 0.068015]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 400/676] [D loss: -0.027875] [G loss: -0.074645] [d1 loss: 0.048268] [d2 loss: 0.056026]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 420/676] [D loss: -0.015166] [G loss: -0.088739] [d1 loss: 0.040738] [d2 loss: 0.024713]  [sq d1 d2: 0.000257]  [num0: 17.000000] [num1 47.000000]
[Epoch 163/500] [Batch 440/676] [D loss: -0.010977] [G loss: -0.104662] [d1 loss: 0.049886] [d2 loss: 0.053746]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 163/500] [Batch 460/676] [D loss: -0.023965] [G loss: -0.085671] [d1 loss: 0.098410] [d2 loss: 0.079222]  [sq d1 d2: 0.000368]  [num0: 14.000000] [num1 50.000000]
[Epoch 163/500] [Batch 480/676] [D loss: -0.002552] [G loss: -0.084271] [d1 loss: 0.104264] [d2 loss: 0.091570]  [sq d1 d2: 0.000161]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 500/676] [D loss: 0.002679] [G loss: -0.065988] [d1 loss: 0.095957] [d2 loss: 0.099352]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 163/500] [Batch 520/676] [D loss: -0.005669] [G loss: -0.070316] [d1 loss: 0.108242] [d2 loss: 0.138521]  [sq d1 d2: 0.000917]  [num0: 21.000000] [num1 43.000000]
[Epoch 163/500] [Batch 540/676] [D loss: -0.010243] [G loss: -0.078236] [d1 loss: 0.052777] [d2 loss: 0.058778]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 560/676] [D loss: -0.022707] [G loss: -0.085511] [d1 loss: 0.062037] [d2 loss: 0.071717]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 163/500] [Batch 580/676] [D loss: -0.015126] [G loss: -0.090213] [d1 loss: 0.063711] [d2 loss: 0.057572]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 600/676] [D loss: -0.019400] [G loss: -0.104000] [d1 loss: 0.053879] [d2 loss: 0.047423]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 163/500] [Batch 620/676] [D loss: -0.023598] [G loss: -0.117460] [d1 loss: 0.044153] [d2 loss: 0.030401]  [sq d1 d2: 0.000189]  [num0: 13.000000] [num1 51.000000]
[Epoch 163/500] [Batch 640/676] [D loss: -0.016598] [G loss: -0.127179] [d1 loss: 0.056652] [d2 loss: 0.066023]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 163/500] [Batch 660/676] [D loss: -0.006668] [G loss: -0.125524] [d1 loss: 0.046169] [d2 loss: 0.036212]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 164/500] [Batch 0/676] [D loss: 0.000474] [G loss: -0.088542] [d1 loss: 0.030961] [d2 loss: 0.030132]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 20/676] [D loss: -0.023121] [G loss: -0.087323] [d1 loss: 0.071245] [d2 loss: 0.072893]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 40/676] [D loss: -0.027491] [G loss: -0.098744] [d1 loss: 0.156655] [d2 loss: 0.134334]  [sq d1 d2: 0.000498]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 60/676] [D loss: 0.000804] [G loss: -0.101646] [d1 loss: 0.062029] [d2 loss: 0.073403]  [sq d1 d2: 0.000129]  [num0: 9.000000] [num1 55.000000]
[Epoch 164/500] [Batch 80/676] [D loss: -0.006863] [G loss: -0.108315] [d1 loss: 0.026376] [d2 loss: 0.023770]  [sq d1 d2: 0.000007]  [num0: 11.000000] [num1 53.000000]
[Epoch 164/500] [Batch 100/676] [D loss: -0.035394] [G loss: -0.116325] [d1 loss: 0.023734] [d2 loss: 0.026858]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 164/500] [Batch 120/676] [D loss: -0.014882] [G loss: -0.073336] [d1 loss: 0.035780] [d2 loss: 0.045304]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 140/676] [D loss: 0.000495] [G loss: -0.080903] [d1 loss: 0.054668] [d2 loss: 0.046205]  [sq d1 d2: 0.000072]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 160/676] [D loss: -0.022068] [G loss: -0.072301] [d1 loss: 0.119903] [d2 loss: 0.093397]  [sq d1 d2: 0.000703]  [num0: 16.000000] [num1 48.000000]

[Epoch 164/500] [Batch 180/676] [D loss: -0.023343] [G loss: -0.049670] [d1 loss: 0.071234] [d2 loss: 0.060027]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 200/676] [D loss: -0.031623] [G loss: -0.045825] [d1 loss: 0.040536] [d2 loss: 0.049024]  [sq d1 d2: 0.000072]  [num0: 18.000000] [num1 46.000000]
[Epoch 164/500] [Batch 220/676] [D loss: -0.021554] [G loss: -0.040905] [d1 loss: 0.055399] [d2 loss: 0.055575]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 164/500] [Batch 240/676] [D loss: -0.039179] [G loss: -0.029246] [d1 loss: 0.120538] [d2 loss: 0.097261]  [sq d1 d2: 0.000542]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 260/676] [D loss: -0.039286] [G loss: -0.031645] [d1 loss: 0.051019] [d2 loss: 0.047159]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 280/676] [D loss: -0.002945] [G loss: -0.050216] [d1 loss: 0.099948] [d2 loss: 0.074800]  [sq d1 d2: 0.000632]  [num0: 19.000000] [num1 45.000000]
[Epoch 164/500] [Batch 300/676] [D loss: -0.017051] [G loss: -0.032658] [d1 loss: 0.108329] [d2 loss: 0.134315]  [sq d1 d2: 0.000675]  [num0: 14.000000] [num1 50.000000]
[Epoch 164/500] [Batch 320/676] [D loss: -0.023695] [G loss: -0.123775] [d1 loss: 0.042697] [d2 loss: 0.056117]  [sq d1 d2: 0.000180]  [num0: 13.000000] [num1 51.000000]
[Epoch 164/500] [Batch 340/676] [D loss: 0.006602] [G loss: -0.158438] [d1 loss: 0.039837] [d2 loss: 0.039576]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 164/500] [Batch 360/676] [D loss: 0.006224] [G loss: -0.176773] [d1 loss: 0.085731] [d2 loss: 0.064321]  [sq d1 d2: 0.000458]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 380/676] [D loss: -0.001697] [G loss: -0.168500] [d1 loss: 0.042796] [d2 loss: 0.036331]  [sq d1 d2: 0.000042]  [num0: 19.000000] [num1 45.000000]
[Epoch 164/500] [Batch 400/676] [D loss: -0.020135] [G loss: -0.179249] [d1 loss: 0.077655] [d2 loss: 0.063075]  [sq d1 d2: 0.000213]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 420/676] [D loss: -0.012452] [G loss: -0.185252] [d1 loss: 0.093790] [d2 loss: 0.070658]  [sq d1 d2: 0.000535]  [num0: 17.000000] [num1 47.000000]
[Epoch 164/500] [Batch 440/676] [D loss: -0.032314] [G loss: -0.154300] [d1 loss: 0.030160] [d2 loss: 0.047277]  [sq d1 d2: 0.000293]  [num0: 12.000000] [num1 52.000000]
[Epoch 164/500] [Batch 460/676] [D loss: -0.017941] [G loss: -0.155205] [d1 loss: 0.036137] [d2 loss: 0.028696]  [sq d1 d2: 0.000055]  [num0: 18.000000] [num1 46.000000]
[Epoch 164/500] [Batch 480/676] [D loss: -0.014339] [G loss: -0.160981] [d1 loss: 0.031687] [d2 loss: 0.033926]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 164/500] [Batch 500/676] [D loss: -0.002408] [G loss: -0.132675] [d1 loss: 0.132877] [d2 loss: 0.127948]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 164/500] [Batch 520/676] [D loss: -0.034139] [G loss: -0.125000] [d1 loss: 0.050102] [d2 loss: 0.042797]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 164/500] [Batch 540/676] [D loss: -0.023292] [G loss: -0.119187] [d1 loss: 0.050254] [d2 loss: 0.043455]  [sq d1 d2: 0.000046]  [num0: 20.000000] [num1 44.000000]
[Epoch 164/500] [Batch 560/676] [D loss: -0.003532] [G loss: -0.103049] [d1 loss: 0.028531] [d2 loss: 0.031189]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 164/500] [Batch 580/676] [D loss: -0.008778] [G loss: -0.084164] [d1 loss: 0.103309] [d2 loss: 0.090523]  [sq d1 d2: 0.000163]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 600/676] [D loss: 0.003775] [G loss: -0.083879] [d1 loss: 0.044730] [d2 loss: 0.041629]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 164/500] [Batch 620/676] [D loss: -0.013568] [G loss: -0.064170] [d1 loss: 0.269898] [d2 loss: 0.200264]  [sq d1 d2: 0.004849]  [num0: 16.000000] [num1 48.000000]
[Epoch 164/500] [Batch 640/676] [D loss: 0.014061] [G loss: -0.043495] [d1 loss: 0.059744] [d2 loss: 0.059008]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 164/500] [Batch 660/676] [D loss: -0.026282] [G loss: -0.047316] [d1 loss: 0.035808] [d2 loss: 0.033723]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 165/500] [Batch 0/676] [D loss: -0.020852] [G loss: -0.054093] [d1 loss: 0.088562] [d2 loss: 0.069679]  [sq d1 d2: 0.000357]  [num0: 13.000000] [num1 51.000000]
[Epoch 165/500] [Batch 20/676] [D loss: -0.028649] [G loss: -0.055354] [d1 loss: 0.059556] [d2 loss: 0.054499]  [sq d1 d2: 0.000026]  [num0: 12.000000] [num1 52.000000]
[Epoch 165/500] [Batch 40/676] [D loss: -0.037613] [G loss: -0.072207] [d1 loss: 0.060853] [d2 loss: 0.055999]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 165/500] [Batch 60/676] [D loss: -0.044582] [G loss: -0.077842] [d1 loss: 0.018890] [d2 loss: 0.020704]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 80/676] [D loss: -0.036251] [G loss: -0.135126] [d1 loss: 0.097189] [d2 loss: 0.113961]  [sq d1 d2: 0.000281]  [num0: 12.000000] [num1 52.000000]
[Epoch 165/500] [Batch 100/676] [D loss: -0.044449] [G loss: -0.133381] [d1 loss: 0.059879] [d2 loss: 0.105072]  [sq d1 d2: 0.002042]  [num0: 20.000000] [num1 44.000000]
[Epoch 165/500] [Batch 120/676] [D loss: 0.018932] [G loss: -0.139241] [d1 loss: 0.062914] [d2 loss: 0.066472]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 165/500] [Batch 140/676] [D loss: -0.004916] [G loss: -0.135949] [d1 loss: 0.110219] [d2 loss: 0.101502]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 160/676] [D loss: -0.015078] [G loss: -0.140456] [d1 loss: 0.028941] [d2 loss: 0.028381]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 180/676] [D loss: -0.020214] [G loss: -0.112178] [d1 loss: 0.115946] [d2 loss: 0.114969]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 165/500] [Batch 200/676] [D loss: -0.024167] [G loss: -0.134232] [d1 loss: 0.109414] [d2 loss: 0.095584]  [sq d1 d2: 0.000191]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 220/676] [D loss: -0.030535] [G loss: -0.148101] [d1 loss: 0.110298] [d2 loss: 0.104737]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 165/500] [Batch 240/676] [D loss: -0.022189] [G loss: -0.142613] [d1 loss: 0.061381] [d2 loss: 0.064357]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 165/500] [Batch 260/676] [D loss: -0.029611] [G loss: -0.139103] [d1 loss: 0.035652] [d2 loss: 0.032369]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 280/676] [D loss: -0.042608] [G loss: -0.135633] [d1 loss: 0.108501] [d2 loss: 0.113907]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 300/676] [D loss: -0.047605] [G loss: -0.155973] [d1 loss: 0.050447] [d2 loss: 0.056090]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 320/676] [D loss: -0.002958] [G loss: -0.163957] [d1 loss: 0.052342] [d2 loss: 0.047052]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 340/676] [D loss: 0.002028] [G loss: -0.149342] [d1 loss: 0.098269] [d2 loss: 0.099005]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 165/500] [Batch 360/676] [D loss: -0.035876] [G loss: -0.173655] [d1 loss: 0.037509] [d2 loss: 0.042145]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 165/500] [Batch 380/676] [D loss: -0.034017] [G loss: -0.143137] [d1 loss: 0.060060] [d2 loss: 0.059943]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 165/500] [Batch 400/676] [D loss: -0.007906] [G loss: -0.114635] [d1 loss: 0.101890] [d2 loss: 0.074130]  [sq d1 d2: 0.000771]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 420/676] [D loss: -0.001296] [G loss: -0.110822] [d1 loss: 0.092549] [d2 loss: 0.071613]  [sq d1 d2: 0.000438]  [num0: 17.000000] [num1 47.000000]
[Epoch 165/500] [Batch 440/676] [D loss: -0.016772] [G loss: -0.104607] [d1 loss: 0.101173] [d2 loss: 0.116369]  [sq d1 d2: 0.000231]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 460/676] [D loss: -0.023886] [G loss: -0.042767] [d1 loss: 0.057575] [d2 loss: 0.055152]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 165/500] [Batch 480/676] [D loss: -0.034964] [G loss: -0.041271] [d1 loss: 0.089525] [d2 loss: 0.091918]  [sq d1 d2: 0.000006]  [num0: 20.000000] [num1 44.000000]
[Epoch 165/500] [Batch 500/676] [D loss: -0.028477] [G loss: -0.011462] [d1 loss: 0.016319] [d2 loss: 0.014418]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 520/676] [D loss: -0.052822] [G loss: -0.031075] [d1 loss: 0.129173] [d2 loss: 0.119871]  [sq d1 d2: 0.000087]  [num0: 18.000000] [num1 46.000000]

[Epoch 165/500] [Batch 540/676] [D loss: -0.041607] [G loss: 0.009894] [d1 loss: 0.089734] [d2 loss: 0.094390]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 560/676] [D loss: -0.007706] [G loss: 0.020819] [d1 loss: 0.099222] [d2 loss: 0.079734]  [sq d1 d2: 0.000380]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 580/676] [D loss: -0.043095] [G loss: 0.018576] [d1 loss: 0.040494] [d2 loss: 0.036221]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 165/500] [Batch 600/676] [D loss: -0.010236] [G loss: -0.004019] [d1 loss: 0.031392] [d2 loss: 0.029314]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 165/500] [Batch 620/676] [D loss: -0.007929] [G loss: 0.032239] [d1 loss: 0.043304] [d2 loss: 0.045716]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 165/500] [Batch 640/676] [D loss: -0.003431] [G loss: 0.011278] [d1 loss: 0.077558] [d2 loss: 0.091401]  [sq d1 d2: 0.000192]  [num0: 15.000000] [num1 49.000000]
[Epoch 165/500] [Batch 660/676] [D loss: -0.013916] [G loss: -0.044876] [d1 loss: 0.048377] [d2 loss: 0.051653]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 0/676] [D loss: -0.022206] [G loss: -0.074034] [d1 loss: 0.060796] [d2 loss: 0.060971]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 20/676] [D loss: -0.045752] [G loss: -0.105959] [d1 loss: 0.095067] [d2 loss: 0.091887]  [sq d1 d2: 0.000010]  [num0: 21.000000] [num1 43.000000]
[Epoch 166/500] [Batch 40/676] [D loss: -0.053119] [G loss: -0.165240] [d1 loss: 0.024765] [d2 loss: 0.017253]  [sq d1 d2: 0.000056]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 60/676] [D loss: -0.003245] [G loss: -0.199154] [d1 loss: 0.066250] [d2 loss: 0.073506]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 166/500] [Batch 80/676] [D loss: -0.053063] [G loss: -0.252885] [d1 loss: 0.079367] [d2 loss: 0.090835]  [sq d1 d2: 0.000132]  [num0: 17.000000] [num1 47.000000]
[Epoch 166/500] [Batch 100/676] [D loss: -0.022447] [G loss: -0.298342] [d1 loss: 0.115490] [d2 loss: 0.071148]  [sq d1 d2: 0.001966]  [num0: 15.000000] [num1 49.000000]
[Epoch 166/500] [Batch 120/676] [D loss: -0.040126] [G loss: -0.318868] [d1 loss: 0.025252] [d2 loss: 0.020914]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 166/500] [Batch 140/676] [D loss: 0.003512] [G loss: -0.349153] [d1 loss: 0.097690] [d2 loss: 0.085427]  [sq d1 d2: 0.000150]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 160/676] [D loss: -0.010500] [G loss: -0.356781] [d1 loss: 0.080458] [d2 loss: 0.083714]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 166/500] [Batch 180/676] [D loss: 0.002774] [G loss: -0.307852] [d1 loss: 0.080412] [d2 loss: 0.073261]  [sq d1 d2: 0.000051]  [num0: 12.000000] [num1 52.000000]
[Epoch 166/500] [Batch 200/676] [D loss: 0.010294] [G loss: -0.254430] [d1 loss: 0.084086] [d2 loss: 0.076444]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 166/500] [Batch 220/676] [D loss: -0.011772] [G loss: -0.172156] [d1 loss: 0.124738] [d2 loss: 0.106756]  [sq d1 d2: 0.000323]  [num0: 12.000000] [num1 52.000000]
[Epoch 166/500] [Batch 240/676] [D loss: -0.011201] [G loss: -0.146270] [d1 loss: 0.056471] [d2 loss: 0.054694]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 166/500] [Batch 260/676] [D loss: -0.015553] [G loss: -0.091803] [d1 loss: 0.060928] [d2 loss: 0.050080]  [sq d1 d2: 0.000118]  [num0: 14.000000] [num1 50.000000]
[Epoch 166/500] [Batch 280/676] [D loss: -0.018783] [G loss: -0.048878] [d1 loss: 0.065340] [d2 loss: 0.063970]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 166/500] [Batch 300/676] [D loss: -0.096630] [G loss: -0.003635] [d1 loss: 0.075425] [d2 loss: 0.063205]  [sq d1 d2: 0.000149]  [num0: 14.000000] [num1 50.000000]
[Epoch 166/500] [Batch 320/676] [D loss: -0.038723] [G loss: 0.011260] [d1 loss: 0.039700] [d2 loss: 0.038145]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 166/500] [Batch 340/676] [D loss: -0.008698] [G loss: 0.040004] [d1 loss: 0.080867] [d2 loss: 0.084882]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 166/500] [Batch 360/676] [D loss: -0.015100] [G loss: 0.058720] [d1 loss: 0.073080] [d2 loss: 0.049362]  [sq d1 d2: 0.000563]  [num0: 12.000000] [num1 52.000000]
[Epoch 166/500] [Batch 380/676] [D loss: -0.005907] [G loss: 0.037227] [d1 loss: 0.075340] [d2 loss: 0.076581]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 400/676] [D loss: -0.017397] [G loss: 0.034155] [d1 loss: 0.030796] [d2 loss: 0.036357]  [sq d1 d2: 0.000031]  [num0: 12.000000] [num1 52.000000]
[Epoch 166/500] [Batch 420/676] [D loss: 0.010380] [G loss: 0.017757] [d1 loss: 0.062663] [d2 loss: 0.071014]  [sq d1 d2: 0.000070]  [num0: 18.000000] [num1 46.000000]
[Epoch 166/500] [Batch 440/676] [D loss: 0.012302] [G loss: 0.010340] [d1 loss: 0.038830] [d2 loss: 0.052911]  [sq d1 d2: 0.000198]  [num0: 17.000000] [num1 47.000000]
[Epoch 166/500] [Batch 460/676] [D loss: -0.005554] [G loss: -0.012841] [d1 loss: 0.068287] [d2 loss: 0.067702]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 166/500] [Batch 480/676] [D loss: -0.030945] [G loss: -0.069068] [d1 loss: 0.034060] [d2 loss: 0.033467]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 500/676] [D loss: -0.045459] [G loss: -0.107033] [d1 loss: 0.109699] [d2 loss: 0.083787]  [sq d1 d2: 0.000671]  [num0: 15.000000] [num1 49.000000]
[Epoch 166/500] [Batch 520/676] [D loss: -0.051310] [G loss: -0.157764] [d1 loss: 0.050549] [d2 loss: 0.031387]  [sq d1 d2: 0.000367]  [num0: 16.000000] [num1 48.000000]
[Epoch 166/500] [Batch 540/676] [D loss: -0.047642] [G loss: -0.227032] [d1 loss: 0.055155] [d2 loss: 0.051480]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 166/500] [Batch 560/676] [D loss: -0.045203] [G loss: -0.226416] [d1 loss: 0.102518] [d2 loss: 0.075589]  [sq d1 d2: 0.000725]  [num0: 19.000000] [num1 45.000000]
[Epoch 166/500] [Batch 580/676] [D loss: -0.005369] [G loss: -0.286481] [d1 loss: 0.052253] [d2 loss: 0.056049]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 166/500] [Batch 600/676] [D loss: -0.003312] [G loss: -0.308921] [d1 loss: 0.045118] [d2 loss: 0.030946]  [sq d1 d2: 0.000201]  [num0: 17.000000] [num1 47.000000]
[Epoch 166/500] [Batch 620/676] [D loss: 0.050687] [G loss: -0.288911] [d1 loss: 0.111197] [d2 loss: 0.105390]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 166/500] [Batch 640/676] [D loss: 0.033533] [G loss: -0.223333] [d1 loss: 0.118387] [d2 loss: 0.114987]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 166/500] [Batch 660/676] [D loss: 0.006220] [G loss: -0.145467] [d1 loss: 0.145130] [d2 loss: 0.129565]  [sq d1 d2: 0.000242]  [num0: 13.000000] [num1 51.000000]
[Epoch 167/500] [Batch 0/676] [D loss: -0.014782] [G loss: -0.089383] [d1 loss: 0.045619] [d2 loss: 0.052772]  [sq d1 d2: 0.000051]  [num0: 12.000000] [num1 52.000000]
[Epoch 167/500] [Batch 20/676] [D loss: -0.031855] [G loss: -0.021478] [d1 loss: 0.107463] [d2 loss: 0.115176]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 167/500] [Batch 40/676] [D loss: -0.050806] [G loss: 0.055600] [d1 loss: 0.093647] [d2 loss: 0.084900]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 60/676] [D loss: -0.076306] [G loss: 0.081781] [d1 loss: 0.166620] [d2 loss: 0.146314]  [sq d1 d2: 0.000412]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 80/676] [D loss: -0.082049] [G loss: 0.100345] [d1 loss: 0.146423] [d2 loss: 0.129520]  [sq d1 d2: 0.000286]  [num0: 14.000000] [num1 50.000000]
[Epoch 167/500] [Batch 100/676] [D loss: -0.089768] [G loss: 0.093686] [d1 loss: 0.092828] [d2 loss: 0.085501]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 167/500] [Batch 120/676] [D loss: -0.036942] [G loss: 0.093137] [d1 loss: 0.092441] [d2 loss: 0.091448]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 167/500] [Batch 140/676] [D loss: -0.011310] [G loss: 0.076778] [d1 loss: 0.077725] [d2 loss: 0.088152]  [sq d1 d2: 0.000109]  [num0: 13.000000] [num1 51.000000]

[Epoch 167/500] [Batch 160/676] [D loss: 0.034658] [G loss: 0.073810] [d1 loss: 0.040271] [d2 loss: 0.047546]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 167/500] [Batch 180/676] [D loss: 0.005071] [G loss: 0.051334] [d1 loss: 0.067361] [d2 loss: 0.065713]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 167/500] [Batch 200/676] [D loss: -0.001776] [G loss: 0.041848] [d1 loss: 0.058641] [d2 loss: 0.061158]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 220/676] [D loss: -0.014500] [G loss: 0.018945] [d1 loss: 0.189563] [d2 loss: 0.152421]  [sq d1 d2: 0.001380]  [num0: 17.000000] [num1 47.000000]
[Epoch 167/500] [Batch 240/676] [D loss: -0.022513] [G loss: -0.022766] [d1 loss: 0.057742] [d2 loss: 0.061143]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 167/500] [Batch 260/676] [D loss: -0.055998] [G loss: -0.081660] [d1 loss: 0.050509] [d2 loss: 0.059326]  [sq d1 d2: 0.000078]  [num0: 17.000000] [num1 47.000000]
[Epoch 167/500] [Batch 280/676] [D loss: -0.058845] [G loss: -0.127848] [d1 loss: 0.078585] [d2 loss: 0.063190]  [sq d1 d2: 0.000237]  [num0: 12.000000] [num1 52.000000]
[Epoch 167/500] [Batch 300/676] [D loss: -0.066241] [G loss: -0.167144] [d1 loss: 0.063104] [d2 loss: 0.047666]  [sq d1 d2: 0.000238]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 320/676] [D loss: -0.051285] [G loss: -0.204422] [d1 loss: 0.071878] [d2 loss: 0.077047]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 167/500] [Batch 340/676] [D loss: -0.006930] [G loss: -0.229885] [d1 loss: 0.066292] [d2 loss: 0.068062]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 167/500] [Batch 360/676] [D loss: 0.030341] [G loss: -0.259651] [d1 loss: 0.112925] [d2 loss: 0.108758]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 380/676] [D loss: 0.017885] [G loss: -0.234834] [d1 loss: 0.064666] [d2 loss: 0.061375]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 167/500] [Batch 400/676] [D loss: 0.004293] [G loss: -0.156401] [d1 loss: 0.116531] [d2 loss: 0.136049]  [sq d1 d2: 0.000381]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 420/676] [D loss: 0.006539] [G loss: -0.094118] [d1 loss: 0.130483] [d2 loss: 0.117769]  [sq d1 d2: 0.000162]  [num0: 17.000000] [num1 47.000000]
[Epoch 167/500] [Batch 440/676] [D loss: -0.010017] [G loss: -0.013360] [d1 loss: 0.073815] [d2 loss: 0.066518]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 167/500] [Batch 460/676] [D loss: -0.019041] [G loss: 0.054780] [d1 loss: 0.077216] [d2 loss: 0.074341]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 167/500] [Batch 480/676] [D loss: -0.028187] [G loss: 0.146004] [d1 loss: 0.119383] [d2 loss: 0.109441]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 500/676] [D loss: -0.053072] [G loss: 0.221820] [d1 loss: 0.038417] [d2 loss: 0.037807]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 167/500] [Batch 520/676] [D loss: -0.094316] [G loss: 0.272330] [d1 loss: 0.098171] [d2 loss: 0.086002]  [sq d1 d2: 0.000148]  [num0: 20.000000] [num1 44.000000]
[Epoch 167/500] [Batch 540/676] [D loss: -0.046625] [G loss: 0.243946] [d1 loss: 0.054639] [d2 loss: 0.048008]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 167/500] [Batch 560/676] [D loss: -0.049884] [G loss: 0.212860] [d1 loss: 0.020531] [d2 loss: 0.027262]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 167/500] [Batch 580/676] [D loss: 0.004496] [G loss: 0.213256] [d1 loss: 0.088207] [d2 loss: 0.098918]  [sq d1 d2: 0.000115]  [num0: 18.000000] [num1 46.000000]
[Epoch 167/500] [Batch 600/676] [D loss: 0.011385] [G loss: 0.116366] [d1 loss: 0.036383] [d2 loss: 0.042449]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 167/500] [Batch 620/676] [D loss: 0.024340] [G loss: 0.054405] [d1 loss: 0.074686] [d2 loss: 0.079004]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 167/500] [Batch 640/676] [D loss: 0.003319] [G loss: 0.009384] [d1 loss: 0.069007] [d2 loss: 0.060732]  [sq d1 d2: 0.000068]  [num0: 13.000000] [num1 51.000000]
[Epoch 167/500] [Batch 660/676] [D loss: -0.012740] [G loss: 0.011968] [d1 loss: 0.104530] [d2 loss: 0.089584]  [sq d1 d2: 0.000223]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 0/676] [D loss: -0.030902] [G loss: -0.028419] [d1 loss: 0.023181] [d2 loss: 0.018173]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 20/676] [D loss: -0.040782] [G loss: -0.074902] [d1 loss: 0.068660] [d2 loss: 0.058305]  [sq d1 d2: 0.000107]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 40/676] [D loss: -0.051226] [G loss: -0.156614] [d1 loss: 0.065577] [d2 loss: 0.061030]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 168/500] [Batch 60/676] [D loss: -0.094643] [G loss: -0.223359] [d1 loss: 0.078638] [d2 loss: 0.075097]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 80/676] [D loss: -0.075813] [G loss: -0.285550] [d1 loss: 0.095666] [d2 loss: 0.088479]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 168/500] [Batch 100/676] [D loss: -0.013973] [G loss: -0.318972] [d1 loss: 0.048176] [d2 loss: 0.033824]  [sq d1 d2: 0.000206]  [num0: 19.000000] [num1 45.000000]
[Epoch 168/500] [Batch 120/676] [D loss: -0.029009] [G loss: -0.368267] [d1 loss: 0.061182] [d2 loss: 0.060171]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 140/676] [D loss: 0.018927] [G loss: -0.429189] [d1 loss: 0.056440] [d2 loss: 0.052462]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 160/676] [D loss: 0.040276] [G loss: -0.314509] [d1 loss: 0.098881] [d2 loss: 0.099026]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 168/500] [Batch 180/676] [D loss: 0.000978] [G loss: -0.234703] [d1 loss: 0.045780] [d2 loss: 0.044383]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 168/500] [Batch 200/676] [D loss: -0.004464] [G loss: -0.179013] [d1 loss: 0.030184] [d2 loss: 0.032487]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 168/500] [Batch 220/676] [D loss: -0.020772] [G loss: -0.120786] [d1 loss: 0.098965] [d2 loss: 0.117073]  [sq d1 d2: 0.000328]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 240/676] [D loss: -0.021017] [G loss: -0.052499] [d1 loss: 0.085066] [d2 loss: 0.075774]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 260/676] [D loss: -0.049348] [G loss: -0.018964] [d1 loss: 0.045218] [d2 loss: 0.052193]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 280/676] [D loss: -0.063119] [G loss: 0.057717] [d1 loss: 0.031785] [d2 loss: 0.031431]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 300/676] [D loss: -0.005614] [G loss: 0.112866] [d1 loss: 0.052199] [d2 loss: 0.045363]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 168/500] [Batch 320/676] [D loss: -0.022936] [G loss: 0.124130] [d1 loss: 0.019751] [d2 loss: 0.019622]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 340/676] [D loss: -0.010116] [G loss: 0.109038] [d1 loss: 0.036015] [d2 loss: 0.020051]  [sq d1 d2: 0.000255]  [num0: 14.000000] [num1 50.000000]
[Epoch 168/500] [Batch 360/676] [D loss: 0.015077] [G loss: 0.104243] [d1 loss: 0.078688] [d2 loss: 0.089963]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 380/676] [D loss: 0.056092] [G loss: 0.068745] [d1 loss: 0.039128] [d2 loss: 0.036054]  [sq d1 d2: 0.000009]  [num0: 12.000000] [num1 52.000000]
[Epoch 168/500] [Batch 400/676] [D loss: 0.015733] [G loss: 0.054475] [d1 loss: 0.060647] [d2 loss: 0.062473]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 420/676] [D loss: 0.002408] [G loss: 0.057108] [d1 loss: 0.165259] [d2 loss: 0.166819]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 168/500] [Batch 440/676] [D loss: -0.003974] [G loss: 0.063787] [d1 loss: 0.100948] [d2 loss: 0.081687]  [sq d1 d2: 0.000371]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 460/676] [D loss: -0.024099] [G loss: 0.058267] [d1 loss: 0.045076] [d2 loss: 0.054230]  [sq d1 d2: 0.000084]  [num0: 11.000000] [num1 53.000000]
[Epoch 168/500] [Batch 480/676] [D loss: -0.028703] [G loss: 0.054141] [d1 loss: 0.093228] [d2 loss: 0.095936]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]

[Epoch 168/500] [Batch 500/676] [D loss: -0.034356] [G loss: -0.000547] [d1 loss: 0.101249] [d2 loss: 0.087197]  [sq d1 d2: 0.000197]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 520/676] [D loss: -0.032473] [G loss: -0.012412] [d1 loss: 0.043294] [d2 loss: 0.043647]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 540/676] [D loss: -0.022622] [G loss: -0.071357] [d1 loss: 0.102287] [d2 loss: 0.096650]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 168/500] [Batch 560/676] [D loss: -0.012035] [G loss: -0.106189] [d1 loss: 0.078546] [d2 loss: 0.074383]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 168/500] [Batch 580/676] [D loss: -0.015741] [G loss: -0.135875] [d1 loss: 0.073997] [d2 loss: 0.074732]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 168/500] [Batch 600/676] [D loss: 0.033037] [G loss: -0.109053] [d1 loss: 0.107747] [d2 loss: 0.098850]  [sq d1 d2: 0.000079]  [num0: 19.000000] [num1 45.000000]
[Epoch 168/500] [Batch 620/676] [D loss: 0.010921] [G loss: -0.096810] [d1 loss: 0.047433] [d2 loss: 0.048533]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 168/500] [Batch 640/676] [D loss: 0.004829] [G loss: -0.071209] [d1 loss: 0.092645] [d2 loss: 0.095656]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 168/500] [Batch 660/676] [D loss: 0.012679] [G loss: -0.043047] [d1 loss: 0.068029] [d2 loss: 0.088760]  [sq d1 d2: 0.000430]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 0/676] [D loss: 0.000589] [G loss: -0.017660] [d1 loss: 0.076606] [d2 loss: 0.070159]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 169/500] [Batch 20/676] [D loss: -0.008305] [G loss: 0.012753] [d1 loss: 0.100559] [d2 loss: 0.090511]  [sq d1 d2: 0.000101]  [num0: 14.000000] [num1 50.000000]
[Epoch 169/500] [Batch 40/676] [D loss: -0.018515] [G loss: 0.067944] [d1 loss: 0.057364] [d2 loss: 0.062888]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 169/500] [Batch 60/676] [D loss: -0.032442] [G loss: 0.129787] [d1 loss: 0.069515] [d2 loss: 0.053313]  [sq d1 d2: 0.000262]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 80/676] [D loss: -0.058360] [G loss: 0.203410] [d1 loss: 0.053256] [d2 loss: 0.064470]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 100/676] [D loss: -0.055563] [G loss: 0.193426] [d1 loss: 0.081611] [d2 loss: 0.094481]  [sq d1 d2: 0.000166]  [num0: 19.000000] [num1 45.000000]
[Epoch 169/500] [Batch 120/676] [D loss: -0.069064] [G loss: 0.190318] [d1 loss: 0.071336] [d2 loss: 0.073849]  [sq d1 d2: 0.000006]  [num0: 23.000000] [num1 41.000000]
[Epoch 169/500] [Batch 140/676] [D loss: -0.000509] [G loss: 0.144438] [d1 loss: 0.155391] [d2 loss: 0.117776]  [sq d1 d2: 0.001415]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 160/676] [D loss: 0.017429] [G loss: 0.112868] [d1 loss: 0.064120] [d2 loss: 0.070843]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 180/676] [D loss: 0.009230] [G loss: 0.136257] [d1 loss: 0.075068] [d2 loss: 0.079127]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 169/500] [Batch 200/676] [D loss: 0.017764] [G loss: 0.099409] [d1 loss: 0.141669] [d2 loss: 0.151537]  [sq d1 d2: 0.000097]  [num0: 19.000000] [num1 45.000000]
[Epoch 169/500] [Batch 220/676] [D loss: 0.006511] [G loss: 0.070762] [d1 loss: 0.052329] [d2 loss: 0.047382]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 240/676] [D loss: -0.005062] [G loss: 0.046960] [d1 loss: 0.036169] [d2 loss: 0.044994]  [sq d1 d2: 0.000078]  [num0: 13.000000] [num1 51.000000]
[Epoch 169/500] [Batch 260/676] [D loss: -0.018209] [G loss: 0.029776] [d1 loss: 0.030553] [d2 loss: 0.034966]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 280/676] [D loss: -0.032654] [G loss: 0.015534] [d1 loss: 0.104792] [d2 loss: 0.120611]  [sq d1 d2: 0.000250]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 300/676] [D loss: -0.050023] [G loss: 0.038248] [d1 loss: 0.055600] [d2 loss: 0.054439]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 320/676] [D loss: -0.044799] [G loss: 0.050101] [d1 loss: 0.063325] [d2 loss: 0.048043]  [sq d1 d2: 0.000234]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 340/676] [D loss: -0.054863] [G loss: 0.131874] [d1 loss: 0.089851] [d2 loss: 0.081660]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 169/500] [Batch 360/676] [D loss: 0.006124] [G loss: 0.134388] [d1 loss: 0.055900] [d2 loss: 0.059027]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 380/676] [D loss: 0.007408] [G loss: 0.090419] [d1 loss: 0.099292] [d2 loss: 0.083655]  [sq d1 d2: 0.000245]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 400/676] [D loss: -0.006491] [G loss: 0.096943] [d1 loss: 0.087014] [d2 loss: 0.100952]  [sq d1 d2: 0.000194]  [num0: 19.000000] [num1 45.000000]
[Epoch 169/500] [Batch 420/676] [D loss: 0.025618] [G loss: 0.058268] [d1 loss: 0.148687] [d2 loss: 0.127674]  [sq d1 d2: 0.000442]  [num0: 17.000000] [num1 47.000000]
[Epoch 169/500] [Batch 440/676] [D loss: 0.011745] [G loss: 0.032185] [d1 loss: 0.025308] [d2 loss: 0.025276]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 460/676] [D loss: -0.003360] [G loss: 0.005339] [d1 loss: 0.106061] [d2 loss: 0.121387]  [sq d1 d2: 0.000235]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 480/676] [D loss: -0.024986] [G loss: -0.011512] [d1 loss: 0.066058] [d2 loss: 0.057792]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 500/676] [D loss: -0.034490] [G loss: -0.040847] [d1 loss: 0.049265] [d2 loss: 0.064784]  [sq d1 d2: 0.000241]  [num0: 18.000000] [num1 46.000000]
[Epoch 169/500] [Batch 520/676] [D loss: -0.081739] [G loss: 0.021215] [d1 loss: 0.147288] [d2 loss: 0.123165]  [sq d1 d2: 0.000582]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 540/676] [D loss: -0.093985] [G loss: 0.051271] [d1 loss: 0.131057] [d2 loss: 0.116634]  [sq d1 d2: 0.000208]  [num0: 13.000000] [num1 51.000000]
[Epoch 169/500] [Batch 560/676] [D loss: -0.058980] [G loss: 0.077424] [d1 loss: 0.043574] [d2 loss: 0.046945]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 169/500] [Batch 580/676] [D loss: 0.036546] [G loss: 0.064641] [d1 loss: 0.065814] [d2 loss: 0.064954]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 169/500] [Batch 600/676] [D loss: 0.009975] [G loss: 0.035417] [d1 loss: 0.087665] [d2 loss: 0.085976]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 169/500] [Batch 620/676] [D loss: 0.041056] [G loss: 0.012209] [d1 loss: 0.171330] [d2 loss: 0.144189]  [sq d1 d2: 0.000737]  [num0: 21.000000] [num1 43.000000]
[Epoch 169/500] [Batch 640/676] [D loss: 0.026243] [G loss: 0.022760] [d1 loss: 0.057504] [d2 loss: 0.055638]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 169/500] [Batch 660/676] [D loss: 0.003501] [G loss: 0.007258] [d1 loss: 0.148452] [d2 loss: 0.125930]  [sq d1 d2: 0.000507]  [num0: 12.000000] [num1 52.000000]
[Epoch 170/500] [Batch 0/676] [D loss: -0.013813] [G loss: 0.004895] [d1 loss: 0.072266] [d2 loss: 0.071575]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 20/676] [D loss: -0.040610] [G loss: 0.008997] [d1 loss: 0.075619] [d2 loss: 0.052447]  [sq d1 d2: 0.000537]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 40/676] [D loss: -0.083290] [G loss: -0.000753] [d1 loss: 0.027582] [d2 loss: 0.025731]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 170/500] [Batch 60/676] [D loss: -0.087540] [G loss: 0.021576] [d1 loss: 0.052819] [d2 loss: 0.047390]  [sq d1 d2: 0.000029]  [num0: 21.000000] [num1 43.000000]
[Epoch 170/500] [Batch 80/676] [D loss: -0.082598] [G loss: -0.016217] [d1 loss: 0.164366] [d2 loss: 0.156024]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 100/676] [D loss: -0.012798] [G loss: 0.008282] [d1 loss: 0.097695] [d2 loss: 0.106561]  [sq d1 d2: 0.000079]  [num0: 17.000000] [num1 47.000000]
[Epoch 170/500] [Batch 120/676] [D loss: -0.017287] [G loss: -0.061352] [d1 loss: 0.162372] [d2 loss: 0.158069]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 140/676] [D loss: 0.046459] [G loss: -0.042677] [d1 loss: 0.141361] [d2 loss: 0.138560]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]

[Epoch 170/500] [Batch 160/676] [D loss: 0.030528] [G loss: 0.001544] [d1 loss: 0.088281] [d2 loss: 0.082866]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 170/500] [Batch 180/676] [D loss: 0.006638] [G loss: 0.008898] [d1 loss: 0.057658] [d2 loss: 0.044778]  [sq d1 d2: 0.000166]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 200/676] [D loss: -0.002920] [G loss: 0.000298] [d1 loss: 0.105082] [d2 loss: 0.083549]  [sq d1 d2: 0.000464]  [num0: 19.000000] [num1 45.000000]
[Epoch 170/500] [Batch 220/676] [D loss: -0.029938] [G loss: 0.000931] [d1 loss: 0.043647] [d2 loss: 0.032710]  [sq d1 d2: 0.000120]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 240/676] [D loss: -0.059961] [G loss: 0.028915] [d1 loss: 0.098524] [d2 loss: 0.088758]  [sq d1 d2: 0.000095]  [num0: 15.000000] [num1 49.000000]
[Epoch 170/500] [Batch 260/676] [D loss: -0.088765] [G loss: 0.085138] [d1 loss: 0.128071] [d2 loss: 0.126218]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 170/500] [Batch 280/676] [D loss: -0.109465] [G loss: 0.083214] [d1 loss: 0.094612] [d2 loss: 0.103220]  [sq d1 d2: 0.000074]  [num0: 13.000000] [num1 51.000000]
[Epoch 170/500] [Batch 300/676] [D loss: -0.100010] [G loss: 0.019197] [d1 loss: 0.114878] [d2 loss: 0.114183]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 170/500] [Batch 320/676] [D loss: 0.008385] [G loss: -0.018487] [d1 loss: 0.103597] [d2 loss: 0.107027]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 340/676] [D loss: -0.042400] [G loss: -0.052418] [d1 loss: 0.101003] [d2 loss: 0.094590]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 360/676] [D loss: 0.070911] [G loss: -0.099776] [d1 loss: 0.072005] [d2 loss: 0.056284]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 170/500] [Batch 380/676] [D loss: 0.016180] [G loss: -0.054663] [d1 loss: 0.040822] [d2 loss: 0.041610]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 400/676] [D loss: 0.024410] [G loss: -0.026231] [d1 loss: 0.029086] [d2 loss: 0.028250]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 170/500] [Batch 420/676] [D loss: -0.002905] [G loss: 0.039979] [d1 loss: 0.040468] [d2 loss: 0.053425]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 440/676] [D loss: -0.008066] [G loss: 0.122412] [d1 loss: 0.081370] [d2 loss: 0.085905]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 460/676] [D loss: -0.041051] [G loss: 0.207482] [d1 loss: 0.065176] [d2 loss: 0.064685]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 170/500] [Batch 480/676] [D loss: -0.092106] [G loss: 0.268374] [d1 loss: 0.035545] [d2 loss: 0.027896]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 500/676] [D loss: -0.119080] [G loss: 0.316005] [d1 loss: 0.076147] [d2 loss: 0.085263]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 520/676] [D loss: -0.012440] [G loss: 0.301751] [d1 loss: 0.084331] [d2 loss: 0.091194]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 170/500] [Batch 540/676] [D loss: -0.053782] [G loss: 0.213123] [d1 loss: 0.073396] [d2 loss: 0.048020]  [sq d1 d2: 0.000644]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 560/676] [D loss: -0.000513] [G loss: 0.123814] [d1 loss: 0.074581] [d2 loss: 0.066510]  [sq d1 d2: 0.000065]  [num0: 19.000000] [num1 45.000000]
[Epoch 170/500] [Batch 580/676] [D loss: 0.001879] [G loss: 0.007740] [d1 loss: 0.129108] [d2 loss: 0.112901]  [sq d1 d2: 0.000263]  [num0: 13.000000] [num1 51.000000]
[Epoch 170/500] [Batch 600/676] [D loss: 0.039282] [G loss: -0.148264] [d1 loss: 0.075889] [d2 loss: 0.069020]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 170/500] [Batch 620/676] [D loss: 0.017834] [G loss: -0.143117] [d1 loss: 0.124543] [d2 loss: 0.110101]  [sq d1 d2: 0.000209]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 640/676] [D loss: 0.011942] [G loss: -0.114746] [d1 loss: 0.046944] [d2 loss: 0.051162]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 170/500] [Batch 660/676] [D loss: 0.014347] [G loss: -0.099097] [d1 loss: 0.197140] [d2 loss: 0.222102]  [sq d1 d2: 0.000623]  [num0: 20.000000] [num1 44.000000]
[Epoch 171/500] [Batch 0/676] [D loss: 0.004990] [G loss: -0.089685] [d1 loss: 0.108918] [d2 loss: 0.090474]  [sq d1 d2: 0.000340]  [num0: 20.000000] [num1 44.000000]
[Epoch 171/500] [Batch 20/676] [D loss: 0.002106] [G loss: -0.074414] [d1 loss: 0.064431] [d2 loss: 0.051143]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 40/676] [D loss: -0.006043] [G loss: -0.059922] [d1 loss: 0.111650] [d2 loss: 0.121971]  [sq d1 d2: 0.000107]  [num0: 21.000000] [num1 43.000000]
[Epoch 171/500] [Batch 60/676] [D loss: -0.018865] [G loss: -0.017444] [d1 loss: 0.141610] [d2 loss: 0.130755]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 80/676] [D loss: -0.035178] [G loss: 0.049256] [d1 loss: 0.185985] [d2 loss: 0.182013]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 171/500] [Batch 100/676] [D loss: -0.043104] [G loss: 0.085945] [d1 loss: 0.058382] [d2 loss: 0.057596]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 120/676] [D loss: -0.045804] [G loss: 0.122259] [d1 loss: 0.053927] [d2 loss: 0.047597]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 140/676] [D loss: -0.059377] [G loss: 0.120785] [d1 loss: 0.069261] [d2 loss: 0.054376]  [sq d1 d2: 0.000222]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 160/676] [D loss: -0.059898] [G loss: 0.091837] [d1 loss: 0.065883] [d2 loss: 0.085063]  [sq d1 d2: 0.000368]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 180/676] [D loss: -0.013343] [G loss: 0.117539] [d1 loss: 0.081197] [d2 loss: 0.051870]  [sq d1 d2: 0.000860]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 200/676] [D loss: -0.013691] [G loss: 0.089471] [d1 loss: 0.069975] [d2 loss: 0.080790]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 171/500] [Batch 220/676] [D loss: -0.006935] [G loss: 0.064393] [d1 loss: 0.055539] [d2 loss: 0.067983]  [sq d1 d2: 0.000155]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 240/676] [D loss: 0.001503] [G loss: 0.071497] [d1 loss: 0.131634] [d2 loss: 0.133786]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 171/500] [Batch 260/676] [D loss: -0.003348] [G loss: 0.057252] [d1 loss: 0.093389] [d2 loss: 0.092316]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 280/676] [D loss: 0.013758] [G loss: 0.008713] [d1 loss: 0.075393] [d2 loss: 0.065960]  [sq d1 d2: 0.000089]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 300/676] [D loss: 0.010372] [G loss: 0.010087] [d1 loss: 0.069793] [d2 loss: 0.050791]  [sq d1 d2: 0.000361]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 320/676] [D loss: 0.005648] [G loss: -0.003850] [d1 loss: 0.064424] [d2 loss: 0.070627]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]
[Epoch 171/500] [Batch 340/676] [D loss: 0.000712] [G loss: 0.001256] [d1 loss: 0.058055] [d2 loss: 0.055433]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 360/676] [D loss: -0.019639] [G loss: 0.049791] [d1 loss: 0.140878] [d2 loss: 0.129988]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 380/676] [D loss: -0.034514] [G loss: 0.055485] [d1 loss: 0.049009] [d2 loss: 0.037617]  [sq d1 d2: 0.000130]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 400/676] [D loss: -0.050506] [G loss: 0.085743] [d1 loss: 0.076811] [d2 loss: 0.079315]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 171/500] [Batch 420/676] [D loss: -0.038582] [G loss: 0.139940] [d1 loss: 0.171366] [d2 loss: 0.169744]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 171/500] [Batch 440/676] [D loss: -0.031815] [G loss: 0.150219] [d1 loss: 0.073248] [d2 loss: 0.060999]  [sq d1 d2: 0.000150]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 460/676] [D loss: -0.031931] [G loss: 0.120021] [d1 loss: 0.086978] [d2 loss: 0.100297]  [sq d1 d2: 0.000177]  [num0: 15.000000] [num1 49.000000]
[Epoch 171/500] [Batch 480/676] [D loss: -0.012925] [G loss: 0.145705] [d1 loss: 0.135033] [d2 loss: 0.136808]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 171/500] [Batch 500/676] [D loss: 0.018040] [G loss: 0.130233] [d1 loss: 0.133896] [d2 loss: 0.117241]  [sq d1 d2: 0.000277]  [num0: 17.000000] [num1 47.000000]

[Epoch 171/500] [Batch 520/676] [D loss: 0.035341] [G loss: 0.090410] [d1 loss: 0.070790] [d2 loss: 0.084863]  [sq d1 d2: 0.000198]  [num0: 20.000000] [num1 44.000000]
[Epoch 171/500] [Batch 540/676] [D loss: 0.016395] [G loss: 0.039214] [d1 loss: 0.054026] [d2 loss: 0.068517]  [sq d1 d2: 0.000210]  [num0: 16.000000] [num1 48.000000]
[Epoch 171/500] [Batch 560/676] [D loss: 0.008753] [G loss: 0.020204] [d1 loss: 0.073725] [d2 loss: 0.072615]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 171/500] [Batch 580/676] [D loss: -0.001441] [G loss: -0.021323] [d1 loss: 0.057435] [d2 loss: 0.051425]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 600/676] [D loss: -0.010815] [G loss: -0.076778] [d1 loss: 0.077306] [d2 loss: 0.081947]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 171/500] [Batch 620/676] [D loss: -0.029568] [G loss: -0.123072] [d1 loss: 0.063494] [d2 loss: 0.074907]  [sq d1 d2: 0.000130]  [num0: 20.000000] [num1 44.000000]
[Epoch 171/500] [Batch 640/676] [D loss: -0.015749] [G loss: -0.150734] [d1 loss: 0.098249] [d2 loss: 0.116797]  [sq d1 d2: 0.000344]  [num0: 20.000000] [num1 44.000000]
[Epoch 171/500] [Batch 660/676] [D loss: -0.058812] [G loss: -0.177184] [d1 loss: 0.146907] [d2 loss: 0.140265]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 0/676] [D loss: -0.054623] [G loss: -0.230223] [d1 loss: 0.098606] [d2 loss: 0.112390]  [sq d1 d2: 0.000190]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 20/676] [D loss: -0.004456] [G loss: -0.210355] [d1 loss: 0.040368] [d2 loss: 0.043908]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 172/500] [Batch 40/676] [D loss: 0.020972] [G loss: -0.241304] [d1 loss: 0.069757] [d2 loss: 0.049318]  [sq d1 d2: 0.000418]  [num0: 17.000000] [num1 47.000000]
[Epoch 172/500] [Batch 60/676] [D loss: -0.003266] [G loss: -0.286943] [d1 loss: 0.317205] [d2 loss: 0.233766]  [sq d1 d2: 0.006962]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 80/676] [D loss: 0.000553] [G loss: -0.202379] [d1 loss: 0.056451] [d2 loss: 0.059779]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 100/676] [D loss: 0.010434] [G loss: -0.161251] [d1 loss: 0.050924] [d2 loss: 0.053263]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 120/676] [D loss: 0.000926] [G loss: -0.096316] [d1 loss: 0.133097] [d2 loss: 0.127589]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 172/500] [Batch 140/676] [D loss: -0.005222] [G loss: -0.021388] [d1 loss: 0.079538] [d2 loss: 0.067483]  [sq d1 d2: 0.000145]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 160/676] [D loss: -0.009557] [G loss: 0.061067] [d1 loss: 0.107591] [d2 loss: 0.106403]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 172/500] [Batch 180/676] [D loss: -0.042063] [G loss: 0.108725] [d1 loss: 0.081864] [d2 loss: 0.057584]  [sq d1 d2: 0.000590]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 200/676] [D loss: -0.056475] [G loss: 0.150089] [d1 loss: 0.035432] [d2 loss: 0.038273]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 220/676] [D loss: 0.023013] [G loss: 0.166638] [d1 loss: 0.062109] [d2 loss: 0.080422]  [sq d1 d2: 0.000335]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 240/676] [D loss: 0.008047] [G loss: 0.227834] [d1 loss: 0.057060] [d2 loss: 0.064308]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 260/676] [D loss: -0.010187] [G loss: 0.196640] [d1 loss: 0.084755] [d2 loss: 0.073124]  [sq d1 d2: 0.000135]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 280/676] [D loss: 0.007054] [G loss: 0.201894] [d1 loss: 0.046410] [d2 loss: 0.044665]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 300/676] [D loss: 0.021778] [G loss: 0.206599] [d1 loss: 0.032659] [d2 loss: 0.032389]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 320/676] [D loss: 0.011344] [G loss: 0.157473] [d1 loss: 0.051735] [d2 loss: 0.045262]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 340/676] [D loss: 0.008010] [G loss: 0.080785] [d1 loss: 0.035331] [d2 loss: 0.041959]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 172/500] [Batch 360/676] [D loss: 0.000533] [G loss: 0.025610] [d1 loss: 0.072264] [d2 loss: 0.054100]  [sq d1 d2: 0.000330]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 380/676] [D loss: -0.011921] [G loss: -0.068144] [d1 loss: 0.094888] [d2 loss: 0.088083]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 400/676] [D loss: -0.028004] [G loss: -0.130015] [d1 loss: 0.142500] [d2 loss: 0.188683]  [sq d1 d2: 0.002133]  [num0: 12.000000] [num1 52.000000]
[Epoch 172/500] [Batch 420/676] [D loss: -0.022808] [G loss: -0.150880] [d1 loss: 0.085668] [d2 loss: 0.064650]  [sq d1 d2: 0.000442]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 440/676] [D loss: -0.078093] [G loss: -0.190123] [d1 loss: 0.054556] [d2 loss: 0.062689]  [sq d1 d2: 0.000066]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 460/676] [D loss: -0.070161] [G loss: -0.200873] [d1 loss: 0.058357] [d2 loss: 0.048704]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 480/676] [D loss: -0.073868] [G loss: -0.243372] [d1 loss: 0.115942] [d2 loss: 0.096473]  [sq d1 d2: 0.000379]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 500/676] [D loss: 0.002872] [G loss: -0.221592] [d1 loss: 0.055163] [d2 loss: 0.049119]  [sq d1 d2: 0.000037]  [num0: 18.000000] [num1 46.000000]
[Epoch 172/500] [Batch 520/676] [D loss: 0.002764] [G loss: -0.191145] [d1 loss: 0.095710] [d2 loss: 0.109048]  [sq d1 d2: 0.000178]  [num0: 16.000000] [num1 48.000000]
[Epoch 172/500] [Batch 540/676] [D loss: 0.019564] [G loss: -0.180058] [d1 loss: 0.101279] [d2 loss: 0.096703]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 560/676] [D loss: 0.035776] [G loss: -0.108763] [d1 loss: 0.048099] [d2 loss: 0.052890]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 580/676] [D loss: 0.014348] [G loss: -0.050626] [d1 loss: 0.104661] [d2 loss: 0.116405]  [sq d1 d2: 0.000138]  [num0: 13.000000] [num1 51.000000]
[Epoch 172/500] [Batch 600/676] [D loss: -0.006459] [G loss: 0.004356] [d1 loss: 0.045985] [d2 loss: 0.056297]  [sq d1 d2: 0.000106]  [num0: 14.000000] [num1 50.000000]
[Epoch 172/500] [Batch 620/676] [D loss: -0.020223] [G loss: 0.059989] [d1 loss: 0.101317] [d2 loss: 0.107722]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 640/676] [D loss: -0.044548] [G loss: 0.086988] [d1 loss: 0.061356] [d2 loss: 0.057091]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 172/500] [Batch 660/676] [D loss: -0.062228] [G loss: 0.226060] [d1 loss: 0.135415] [d2 loss: 0.081277]  [sq d1 d2: 0.002931]  [num0: 18.000000] [num1 46.000000]
[Epoch 173/500] [Batch 0/676] [D loss: -0.057539] [G loss: 0.242643] [d1 loss: 0.099428] [d2 loss: 0.092028]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 20/676] [D loss: -0.047521] [G loss: 0.269129] [d1 loss: 0.076525] [d2 loss: 0.078553]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 40/676] [D loss: -0.117886] [G loss: 0.278847] [d1 loss: 0.053222] [d2 loss: 0.059768]  [sq d1 d2: 0.000043]  [num0: 12.000000] [num1 52.000000]
[Epoch 173/500] [Batch 60/676] [D loss: 0.012221] [G loss: 0.264993] [d1 loss: 0.051676] [d2 loss: 0.058993]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 80/676] [D loss: 0.029171] [G loss: 0.294891] [d1 loss: 0.063000] [d2 loss: 0.063277]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 173/500] [Batch 100/676] [D loss: 0.028435] [G loss: 0.281174] [d1 loss: 0.041367] [d2 loss: 0.032952]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 120/676] [D loss: 0.002634] [G loss: 0.176121] [d1 loss: 0.042347] [d2 loss: 0.042032]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 140/676] [D loss: 0.010471] [G loss: 0.103728] [d1 loss: 0.034936] [d2 loss: 0.031366]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 160/676] [D loss: 0.001270] [G loss: 0.030742] [d1 loss: 0.077774] [d2 loss: 0.086027]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 173/500] [Batch 180/676] [D loss: -0.013144] [G loss: -0.040677] [d1 loss: 0.059745] [d2 loss: 0.066119]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]

[Epoch 173/500] [Batch 200/676] [D loss: -0.031233] [G loss: -0.092531] [d1 loss: 0.098614] [d2 loss: 0.094936]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 173/500] [Batch 220/676] [D loss: -0.054586] [G loss: -0.092834] [d1 loss: 0.093029] [d2 loss: 0.074033]  [sq d1 d2: 0.000361]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 240/676] [D loss: -0.060474] [G loss: -0.098967] [d1 loss: 0.027802] [d2 loss: 0.026298]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 173/500] [Batch 260/676] [D loss: -0.062570] [G loss: -0.125210] [d1 loss: 0.124615] [d2 loss: 0.110742]  [sq d1 d2: 0.000192]  [num0: 19.000000] [num1 45.000000]
[Epoch 173/500] [Batch 280/676] [D loss: -0.036513] [G loss: -0.100300] [d1 loss: 0.043846] [d2 loss: 0.047481]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 300/676] [D loss: -0.017754] [G loss: -0.153431] [d1 loss: 0.057283] [d2 loss: 0.054214]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 320/676] [D loss: 0.061886] [G loss: -0.125785] [d1 loss: 0.062369] [d2 loss: 0.050624]  [sq d1 d2: 0.000138]  [num0: 18.000000] [num1 46.000000]
[Epoch 173/500] [Batch 340/676] [D loss: 0.035531] [G loss: -0.185520] [d1 loss: 0.073578] [d2 loss: 0.061003]  [sq d1 d2: 0.000158]  [num0: 15.000000] [num1 49.000000]
[Epoch 173/500] [Batch 360/676] [D loss: 0.010184] [G loss: -0.207812] [d1 loss: 0.112271] [d2 loss: 0.123514]  [sq d1 d2: 0.000126]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 380/676] [D loss: 0.027490] [G loss: -0.150141] [d1 loss: 0.046062] [d2 loss: 0.047158]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 400/676] [D loss: -0.005523] [G loss: -0.054239] [d1 loss: 0.116250] [d2 loss: 0.115698]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 420/676] [D loss: -0.008315] [G loss: -0.007676] [d1 loss: 0.116392] [d2 loss: 0.117105]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 440/676] [D loss: -0.047510] [G loss: 0.079980] [d1 loss: 0.145485] [d2 loss: 0.133170]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 173/500] [Batch 460/676] [D loss: -0.035697] [G loss: 0.144958] [d1 loss: 0.066977] [d2 loss: 0.065167]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 173/500] [Batch 480/676] [D loss: -0.071842] [G loss: 0.185395] [d1 loss: 0.110123] [d2 loss: 0.127475]  [sq d1 d2: 0.000301]  [num0: 19.000000] [num1 45.000000]
[Epoch 173/500] [Batch 500/676] [D loss: -0.088124] [G loss: 0.223982] [d1 loss: 0.136190] [d2 loss: 0.161935]  [sq d1 d2: 0.000663]  [num0: 15.000000] [num1 49.000000]
[Epoch 173/500] [Batch 520/676] [D loss: -0.040028] [G loss: 0.136964] [d1 loss: 0.045844] [d2 loss: 0.045418]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 540/676] [D loss: -0.009160] [G loss: 0.186144] [d1 loss: 0.059325] [d2 loss: 0.067019]  [sq d1 d2: 0.000059]  [num0: 11.000000] [num1 53.000000]
[Epoch 173/500] [Batch 560/676] [D loss: -0.004708] [G loss: 0.121026] [d1 loss: 0.127909] [d2 loss: 0.135166]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 580/676] [D loss: 0.014373] [G loss: 0.049692] [d1 loss: 0.045648] [d2 loss: 0.046089]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 600/676] [D loss: 0.013368] [G loss: 0.011595] [d1 loss: 0.060556] [d2 loss: 0.051970]  [sq d1 d2: 0.000074]  [num0: 13.000000] [num1 51.000000]
[Epoch 173/500] [Batch 620/676] [D loss: 0.003674] [G loss: -0.018305] [d1 loss: 0.091896] [d2 loss: 0.067804]  [sq d1 d2: 0.000580]  [num0: 16.000000] [num1 48.000000]
[Epoch 173/500] [Batch 640/676] [D loss: 0.002539] [G loss: -0.023897] [d1 loss: 0.066067] [d2 loss: 0.068596]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 173/500] [Batch 660/676] [D loss: -0.004648] [G loss: -0.041973] [d1 loss: 0.154168] [d2 loss: 0.158915]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 0/676] [D loss: -0.005836] [G loss: -0.045606] [d1 loss: 0.061232] [d2 loss: 0.061619]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 20/676] [D loss: -0.022750] [G loss: -0.053426] [d1 loss: 0.180606] [d2 loss: 0.173864]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 40/676] [D loss: -0.034376] [G loss: -0.046243] [d1 loss: 0.071185] [d2 loss: 0.068930]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 174/500] [Batch 60/676] [D loss: -0.066043] [G loss: 0.001065] [d1 loss: 0.073933] [d2 loss: 0.066928]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 80/676] [D loss: -0.053717] [G loss: 0.020530] [d1 loss: 0.058185] [d2 loss: 0.054837]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 174/500] [Batch 100/676] [D loss: -0.019564] [G loss: 0.006306] [d1 loss: 0.089873] [d2 loss: 0.089677]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 174/500] [Batch 120/676] [D loss: 0.002667] [G loss: -0.056942] [d1 loss: 0.067128] [d2 loss: 0.070713]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 140/676] [D loss: 0.036607] [G loss: -0.042139] [d1 loss: 0.054719] [d2 loss: 0.061137]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 174/500] [Batch 160/676] [D loss: 0.011872] [G loss: -0.058723] [d1 loss: 0.116007] [d2 loss: 0.113717]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 180/676] [D loss: 0.018110] [G loss: -0.041391] [d1 loss: 0.064832] [d2 loss: 0.075939]  [sq d1 d2: 0.000123]  [num0: 13.000000] [num1 51.000000]
[Epoch 174/500] [Batch 200/676] [D loss: 0.003103] [G loss: -0.019784] [d1 loss: 0.028019] [d2 loss: 0.031847]  [sq d1 d2: 0.000015]  [num0: 20.000000] [num1 44.000000]
[Epoch 174/500] [Batch 220/676] [D loss: -0.001145] [G loss: -0.006710] [d1 loss: 0.130531] [d2 loss: 0.117252]  [sq d1 d2: 0.000176]  [num0: 15.000000] [num1 49.000000]
[Epoch 174/500] [Batch 240/676] [D loss: -0.005874] [G loss: 0.034963] [d1 loss: 0.096647] [d2 loss: 0.095923]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 174/500] [Batch 260/676] [D loss: -0.042826] [G loss: 0.091326] [d1 loss: 0.117529] [d2 loss: 0.103737]  [sq d1 d2: 0.000190]  [num0: 12.000000] [num1 52.000000]
[Epoch 174/500] [Batch 280/676] [D loss: -0.027458] [G loss: 0.155984] [d1 loss: 0.204674] [d2 loss: 0.214778]  [sq d1 d2: 0.000102]  [num0: 17.000000] [num1 47.000000]
[Epoch 174/500] [Batch 300/676] [D loss: -0.054547] [G loss: 0.202657] [d1 loss: 0.083729] [d2 loss: 0.074802]  [sq d1 d2: 0.000080]  [num0: 14.000000] [num1 50.000000]
[Epoch 174/500] [Batch 320/676] [D loss: -0.012129] [G loss: 0.211968] [d1 loss: 0.059226] [d2 loss: 0.068043]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 340/676] [D loss: -0.019637] [G loss: 0.184054] [d1 loss: 0.084051] [d2 loss: 0.089715]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 360/676] [D loss: -0.010547] [G loss: 0.239077] [d1 loss: 0.124801] [d2 loss: 0.112820]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 380/676] [D loss: -0.000841] [G loss: 0.197596] [d1 loss: 0.138846] [d2 loss: 0.149770]  [sq d1 d2: 0.000119]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 400/676] [D loss: 0.023935] [G loss: 0.155272] [d1 loss: 0.035862] [d2 loss: 0.036388]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 420/676] [D loss: 0.003771] [G loss: 0.106649] [d1 loss: 0.036646] [d2 loss: 0.038818]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 174/500] [Batch 440/676] [D loss: 0.002638] [G loss: 0.065959] [d1 loss: 0.065645] [d2 loss: 0.076403]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 174/500] [Batch 460/676] [D loss: -0.002078] [G loss: 0.036167] [d1 loss: 0.100120] [d2 loss: 0.090651]  [sq d1 d2: 0.000090]  [num0: 17.000000] [num1 47.000000]
[Epoch 174/500] [Batch 480/676] [D loss: -0.020409] [G loss: -0.023611] [d1 loss: 0.127564] [d2 loss: 0.139083]  [sq d1 d2: 0.000133]  [num0: 17.000000] [num1 47.000000]
[Epoch 174/500] [Batch 500/676] [D loss: -0.036669] [G loss: -0.100343] [d1 loss: 0.096552] [d2 loss: 0.104919]  [sq d1 d2: 0.000070]  [num0: 19.000000] [num1 45.000000]
[Epoch 174/500] [Batch 520/676] [D loss: -0.047057] [G loss: -0.140099] [d1 loss: 0.074418] [d2 loss: 0.062270]  [sq d1 d2: 0.000148]  [num0: 14.000000] [num1 50.000000]
[Epoch 174/500] [Batch 540/676] [D loss: -0.081777] [G loss: -0.214502] [d1 loss: 0.054279] [d2 loss: 0.046138]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]

[Epoch 174/500] [Batch 560/676] [D loss: -0.033728] [G loss: -0.197555] [d1 loss: 0.126528] [d2 loss: 0.108662]  [sq d1 d2: 0.000319]  [num0: 18.000000] [num1 46.000000]
[Epoch 174/500] [Batch 580/676] [D loss: -0.022222] [G loss: -0.190939] [d1 loss: 0.137412] [d2 loss: 0.142414]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 600/676] [D loss: 0.000893] [G loss: -0.252106] [d1 loss: 0.138194] [d2 loss: 0.137089]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 174/500] [Batch 620/676] [D loss: 0.041837] [G loss: -0.251950] [d1 loss: 0.045000] [d2 loss: 0.050364]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 174/500] [Batch 640/676] [D loss: 0.007388] [G loss: -0.191567] [d1 loss: 0.089133] [d2 loss: 0.071256]  [sq d1 d2: 0.000320]  [num0: 16.000000] [num1 48.000000]
[Epoch 174/500] [Batch 660/676] [D loss: 0.000566] [G loss: -0.133057] [d1 loss: 0.140678] [d2 loss: 0.142840]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 175/500] [Batch 0/676] [D loss: -0.014671] [G loss: -0.059169] [d1 loss: 0.068413] [d2 loss: 0.075839]  [sq d1 d2: 0.000055]  [num0: 10.000000] [num1 54.000000]
[Epoch 175/500] [Batch 20/676] [D loss: -0.020211] [G loss: -0.006585] [d1 loss: 0.024439] [d2 loss: 0.029511]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 175/500] [Batch 40/676] [D loss: -0.058272] [G loss: 0.031733] [d1 loss: 0.138164] [d2 loss: 0.118097]  [sq d1 d2: 0.000403]  [num0: 13.000000] [num1 51.000000]
[Epoch 175/500] [Batch 60/676] [D loss: -0.091281] [G loss: 0.073371] [d1 loss: 0.066988] [d2 loss: 0.070868]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 175/500] [Batch 80/676] [D loss: -0.031174] [G loss: 0.064435] [d1 loss: 0.084797] [d2 loss: 0.097838]  [sq d1 d2: 0.000170]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 100/676] [D loss: 0.004757] [G loss: 0.085419] [d1 loss: 0.098933] [d2 loss: 0.106865]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 175/500] [Batch 120/676] [D loss: 0.071673] [G loss: 0.097804] [d1 loss: 0.062131] [d2 loss: 0.069658]  [sq d1 d2: 0.000057]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 140/676] [D loss: 0.057452] [G loss: 0.080720] [d1 loss: 0.106258] [d2 loss: 0.092162]  [sq d1 d2: 0.000199]  [num0: 17.000000] [num1 47.000000]
[Epoch 175/500] [Batch 160/676] [D loss: 0.025269] [G loss: 0.054820] [d1 loss: 0.143932] [d2 loss: 0.119168]  [sq d1 d2: 0.000613]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 180/676] [D loss: 0.015592] [G loss: 0.066236] [d1 loss: 0.043175] [d2 loss: 0.041161]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 175/500] [Batch 200/676] [D loss: 0.002012] [G loss: 0.018742] [d1 loss: 0.028494] [d2 loss: 0.021729]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 175/500] [Batch 220/676] [D loss: -0.003164] [G loss: -0.024796] [d1 loss: 0.055915] [d2 loss: 0.055073]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 175/500] [Batch 240/676] [D loss: -0.019026] [G loss: -0.065024] [d1 loss: 0.109261] [d2 loss: 0.104615]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 260/676] [D loss: -0.049174] [G loss: -0.083358] [d1 loss: 0.022102] [d2 loss: 0.022987]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 175/500] [Batch 280/676] [D loss: -0.058634] [G loss: -0.111218] [d1 loss: 0.059795] [d2 loss: 0.049688]  [sq d1 d2: 0.000102]  [num0: 19.000000] [num1 45.000000]
[Epoch 175/500] [Batch 300/676] [D loss: -0.018236] [G loss: -0.152392] [d1 loss: 0.058836] [d2 loss: 0.059440]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 320/676] [D loss: -0.012384] [G loss: -0.160763] [d1 loss: 0.079851] [d2 loss: 0.073229]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 340/676] [D loss: -0.030349] [G loss: -0.186359] [d1 loss: 0.059440] [d2 loss: 0.058131]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 360/676] [D loss: -0.024266] [G loss: -0.222058] [d1 loss: 0.099858] [d2 loss: 0.085173]  [sq d1 d2: 0.000216]  [num0: 19.000000] [num1 45.000000]
[Epoch 175/500] [Batch 380/676] [D loss: -0.010649] [G loss: -0.246412] [d1 loss: 0.151897] [d2 loss: 0.117614]  [sq d1 d2: 0.001175]  [num0: 17.000000] [num1 47.000000]
[Epoch 175/500] [Batch 400/676] [D loss: 0.029580] [G loss: -0.189783] [d1 loss: 0.084862] [d2 loss: 0.085753]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 420/676] [D loss: 0.014544] [G loss: -0.113971] [d1 loss: 0.051701] [d2 loss: 0.051667]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 175/500] [Batch 440/676] [D loss: 0.023576] [G loss: -0.062040] [d1 loss: 0.192266] [d2 loss: 0.162883]  [sq d1 d2: 0.000863]  [num0: 13.000000] [num1 51.000000]
[Epoch 175/500] [Batch 460/676] [D loss: -0.000368] [G loss: -0.032777] [d1 loss: 0.079993] [d2 loss: 0.073336]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 480/676] [D loss: -0.017309] [G loss: -0.003281] [d1 loss: 0.093668] [d2 loss: 0.109098]  [sq d1 d2: 0.000238]  [num0: 12.000000] [num1 52.000000]
[Epoch 175/500] [Batch 500/676] [D loss: -0.039131] [G loss: 0.029027] [d1 loss: 0.058012] [d2 loss: 0.062873]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 175/500] [Batch 520/676] [D loss: -0.051249] [G loss: 0.068356] [d1 loss: 0.022692] [d2 loss: 0.022465]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 175/500] [Batch 540/676] [D loss: -0.072413] [G loss: 0.087707] [d1 loss: 0.095610] [d2 loss: 0.104146]  [sq d1 d2: 0.000073]  [num0: 14.000000] [num1 50.000000]
[Epoch 175/500] [Batch 560/676] [D loss: -0.114918] [G loss: 0.081096] [d1 loss: 0.119799] [d2 loss: 0.143239]  [sq d1 d2: 0.000549]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 580/676] [D loss: -0.076510] [G loss: 0.064432] [d1 loss: 0.205071] [d2 loss: 0.181130]  [sq d1 d2: 0.000573]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 600/676] [D loss: -0.042680] [G loss: 0.009777] [d1 loss: 0.069799] [d2 loss: 0.070051]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 175/500] [Batch 620/676] [D loss: 0.000259] [G loss: -0.002417] [d1 loss: 0.065406] [d2 loss: 0.063914]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 175/500] [Batch 640/676] [D loss: -0.002337] [G loss: 0.037505] [d1 loss: 0.126728] [d2 loss: 0.153656]  [sq d1 d2: 0.000725]  [num0: 16.000000] [num1 48.000000]
[Epoch 175/500] [Batch 660/676] [D loss: 0.022960] [G loss: 0.046203] [d1 loss: 0.083341] [d2 loss: 0.088215]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 176/500] [Batch 0/676] [D loss: 0.005439] [G loss: 0.040973] [d1 loss: 0.132904] [d2 loss: 0.119570]  [sq d1 d2: 0.000178]  [num0: 13.000000] [num1 51.000000]
[Epoch 176/500] [Batch 20/676] [D loss: 0.009514] [G loss: 0.004025] [d1 loss: 0.072351] [d2 loss: 0.076175]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 40/676] [D loss: -0.000500] [G loss: -0.029641] [d1 loss: 0.093887] [d2 loss: 0.093205]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 176/500] [Batch 60/676] [D loss: -0.010739] [G loss: -0.071966] [d1 loss: 0.063837] [d2 loss: 0.061446]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 80/676] [D loss: -0.041609] [G loss: -0.089027] [d1 loss: 0.055743] [d2 loss: 0.057229]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 176/500] [Batch 100/676] [D loss: -0.051344] [G loss: -0.123277] [d1 loss: 0.207495] [d2 loss: 0.188374]  [sq d1 d2: 0.000366]  [num0: 15.000000] [num1 49.000000]
[Epoch 176/500] [Batch 120/676] [D loss: -0.071364] [G loss: -0.156728] [d1 loss: 0.102641] [d2 loss: 0.086469]  [sq d1 d2: 0.000262]  [num0: 21.000000] [num1 43.000000]
[Epoch 176/500] [Batch 140/676] [D loss: -0.039839] [G loss: -0.164266] [d1 loss: 0.186835] [d2 loss: 0.180829]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 176/500] [Batch 160/676] [D loss: -0.047823] [G loss: -0.206079] [d1 loss: 0.045865] [d2 loss: 0.041804]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 180/676] [D loss: -0.014409] [G loss: -0.204061] [d1 loss: 0.115578] [d2 loss: 0.133187]  [sq d1 d2: 0.000310]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 200/676] [D loss: 0.019452] [G loss: -0.293298] [d1 loss: 0.159921] [d2 loss: 0.116830]  [sq d1 d2: 0.001857]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 220/676] [D loss: -0.025416] [G loss: -0.300867] [d1 loss: 0.140336] [d2 loss: 0.163042]  [sq d1 d2: 0.000516]  [num0: 15.000000] [num1 49.000000]

[Epoch 176/500] [Batch 240/676] [D loss: 0.035758] [G loss: -0.255975] [d1 loss: 0.098761] [d2 loss: 0.104742]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 260/676] [D loss: 0.034415] [G loss: -0.204660] [d1 loss: 0.097810] [d2 loss: 0.095824]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 280/676] [D loss: 0.005377] [G loss: -0.140950] [d1 loss: 0.035647] [d2 loss: 0.033338]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 176/500] [Batch 300/676] [D loss: 0.004021] [G loss: -0.083238] [d1 loss: 0.112099] [d2 loss: 0.119977]  [sq d1 d2: 0.000062]  [num0: 12.000000] [num1 52.000000]
[Epoch 176/500] [Batch 320/676] [D loss: -0.012792] [G loss: -0.040396] [d1 loss: 0.118198] [d2 loss: 0.128360]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 340/676] [D loss: -0.049247] [G loss: -0.036972] [d1 loss: 0.049390] [d2 loss: 0.054769]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 176/500] [Batch 360/676] [D loss: -0.076824] [G loss: -0.053002] [d1 loss: 0.070859] [d2 loss: 0.072387]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 380/676] [D loss: -0.094322] [G loss: -0.068939] [d1 loss: 0.185468] [d2 loss: 0.182059]  [sq d1 d2: 0.000012]  [num0: 20.000000] [num1 44.000000]
[Epoch 176/500] [Batch 400/676] [D loss: -0.063962] [G loss: -0.039891] [d1 loss: 0.128495] [d2 loss: 0.130831]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 176/500] [Batch 420/676] [D loss: -0.093230] [G loss: 0.050385] [d1 loss: 0.085173] [d2 loss: 0.108806]  [sq d1 d2: 0.000559]  [num0: 14.000000] [num1 50.000000]
[Epoch 176/500] [Batch 440/676] [D loss: -0.028089] [G loss: -0.022369] [d1 loss: 0.112843] [d2 loss: 0.106304]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 460/676] [D loss: 0.085927] [G loss: -0.096201] [d1 loss: 0.116518] [d2 loss: 0.097470]  [sq d1 d2: 0.000363]  [num0: 18.000000] [num1 46.000000]
[Epoch 176/500] [Batch 480/676] [D loss: 0.032320] [G loss: -0.133013] [d1 loss: 0.051528] [d2 loss: 0.043788]  [sq d1 d2: 0.000060]  [num0: 18.000000] [num1 46.000000]
[Epoch 176/500] [Batch 500/676] [D loss: 0.026762] [G loss: -0.101864] [d1 loss: 0.055347] [d2 loss: 0.051108]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 176/500] [Batch 520/676] [D loss: 0.005971] [G loss: -0.063325] [d1 loss: 0.023904] [d2 loss: 0.030261]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 540/676] [D loss: 0.004639] [G loss: -0.051860] [d1 loss: 0.140240] [d2 loss: 0.123463]  [sq d1 d2: 0.000281]  [num0: 20.000000] [num1 44.000000]
[Epoch 176/500] [Batch 560/676] [D loss: -0.000301] [G loss: -0.036454] [d1 loss: 0.231731] [d2 loss: 0.157445]  [sq d1 d2: 0.005518]  [num0: 16.000000] [num1 48.000000]
[Epoch 176/500] [Batch 580/676] [D loss: -0.006537] [G loss: -0.014991] [d1 loss: 0.172124] [d2 loss: 0.158776]  [sq d1 d2: 0.000178]  [num0: 19.000000] [num1 45.000000]
[Epoch 176/500] [Batch 600/676] [D loss: -0.028723] [G loss: 0.031827] [d1 loss: 0.160904] [d2 loss: 0.140550]  [sq d1 d2: 0.000414]  [num0: 17.000000] [num1 47.000000]
[Epoch 176/500] [Batch 620/676] [D loss: -0.105786] [G loss: 0.098510] [d1 loss: 0.065916] [d2 loss: 0.054765]  [sq d1 d2: 0.000124]  [num0: 22.000000] [num1 42.000000]
[Epoch 176/500] [Batch 640/676] [D loss: -0.103550] [G loss: 0.094796] [d1 loss: 0.108865] [d2 loss: 0.088494]  [sq d1 d2: 0.000415]  [num0: 20.000000] [num1 44.000000]
[Epoch 176/500] [Batch 660/676] [D loss: -0.060528] [G loss: 0.107870] [d1 loss: 0.033084] [d2 loss: 0.032256]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 177/500] [Batch 0/676] [D loss: -0.081881] [G loss: 0.073155] [d1 loss: 0.015551] [d2 loss: 0.016644]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 177/500] [Batch 20/676] [D loss: -0.035978] [G loss: 0.085282] [d1 loss: 0.040703] [d2 loss: 0.052912]  [sq d1 d2: 0.000149]  [num0: 17.000000] [num1 47.000000]
[Epoch 177/500] [Batch 40/676] [D loss: -0.005793] [G loss: 0.091208] [d1 loss: 0.059570] [d2 loss: 0.042323]  [sq d1 d2: 0.000297]  [num0: 15.000000] [num1 49.000000]
[Epoch 177/500] [Batch 60/676] [D loss: 0.035899] [G loss: 0.088855] [d1 loss: 0.020981] [d2 loss: 0.018861]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 177/500] [Batch 80/676] [D loss: 0.026880] [G loss: 0.084226] [d1 loss: 0.107182] [d2 loss: 0.106342]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 177/500] [Batch 100/676] [D loss: 0.041234] [G loss: 0.073970] [d1 loss: 0.075877] [d2 loss: 0.063941]  [sq d1 d2: 0.000142]  [num0: 12.000000] [num1 52.000000]
[Epoch 177/500] [Batch 120/676] [D loss: 0.014526] [G loss: 0.071376] [d1 loss: 0.062953] [d2 loss: 0.065032]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 177/500] [Batch 140/676] [D loss: -0.003876] [G loss: 0.047454] [d1 loss: 0.115013] [d2 loss: 0.139492]  [sq d1 d2: 0.000599]  [num0: 14.000000] [num1 50.000000]
[Epoch 177/500] [Batch 160/676] [D loss: -0.016462] [G loss: 0.045654] [d1 loss: 0.144649] [d2 loss: 0.148084]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 177/500] [Batch 180/676] [D loss: 0.001967] [G loss: 0.094210] [d1 loss: 0.092298] [d2 loss: 0.095244]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 177/500] [Batch 200/676] [D loss: -0.051024] [G loss: 0.126326] [d1 loss: 0.078498] [d2 loss: 0.077168]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 177/500] [Batch 220/676] [D loss: -0.016934] [G loss: 0.080936] [d1 loss: 0.072673] [d2 loss: 0.073609]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 177/500] [Batch 240/676] [D loss: -0.027978] [G loss: 0.078237] [d1 loss: 0.115742] [d2 loss: 0.093079]  [sq d1 d2: 0.000514]  [num0: 11.000000] [num1 53.000000]
[Epoch 177/500] [Batch 260/676] [D loss: -0.033073] [G loss: 0.050954] [d1 loss: 0.106667] [d2 loss: 0.111728]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 177/500] [Batch 280/676] [D loss: 0.033663] [G loss: 0.037218] [d1 loss: 0.146780] [d2 loss: 0.152112]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 177/500] [Batch 300/676] [D loss: -0.008344] [G loss: -0.002713] [d1 loss: 0.056627] [d2 loss: 0.050594]  [sq d1 d2: 0.000036]  [num0: 12.000000] [num1 52.000000]
[Epoch 177/500] [Batch 320/676] [D loss: 0.020138] [G loss: -0.007265] [d1 loss: 0.088673] [d2 loss: 0.097481]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 177/500] [Batch 340/676] [D loss: 0.014288] [G loss: -0.053314] [d1 loss: 0.033730] [d2 loss: 0.031382]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 177/500] [Batch 360/676] [D loss: 0.021028] [G loss: -0.072861] [d1 loss: 0.097557] [d2 loss: 0.108491]  [sq d1 d2: 0.000120]  [num0: 21.000000] [num1 43.000000]
[Epoch 177/500] [Batch 380/676] [D loss: 0.004199] [G loss: -0.066615] [d1 loss: 0.065100] [d2 loss: 0.064268]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 177/500] [Batch 400/676] [D loss: 0.006289] [G loss: -0.042013] [d1 loss: 0.135060] [d2 loss: 0.142602]  [sq d1 d2: 0.000057]  [num0: 20.000000] [num1 44.000000]
[Epoch 177/500] [Batch 420/676] [D loss: -0.004071] [G loss: -0.021239] [d1 loss: 0.065731] [d2 loss: 0.063878]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 177/500] [Batch 440/676] [D loss: -0.009239] [G loss: 0.015751] [d1 loss: 0.047105] [d2 loss: 0.066576]  [sq d1 d2: 0.000379]  [num0: 16.000000] [num1 48.000000]
[Epoch 177/500] [Batch 460/676] [D loss: -0.027213] [G loss: 0.051964] [d1 loss: 0.046522] [d2 loss: 0.045992]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 177/500] [Batch 480/676] [D loss: -0.029073] [G loss: 0.081189] [d1 loss: 0.040330] [d2 loss: 0.043123]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 177/500] [Batch 500/676] [D loss: -0.036544] [G loss: 0.109944] [d1 loss: 0.042793] [d2 loss: 0.044621]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 177/500] [Batch 520/676] [D loss: -0.023268] [G loss: 0.112165] [d1 loss: 0.047738] [d2 loss: 0.051694]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 177/500] [Batch 540/676] [D loss: -0.048681] [G loss: 0.121583] [d1 loss: 0.061754] [d2 loss: 0.058754]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 177/500] [Batch 560/676] [D loss: -0.036364] [G loss: 0.090144] [d1 loss: 0.191095] [d2 loss: 0.128458]  [sq d1 d2: 0.003923]  [num0: 18.000000] [num1 46.000000]
[Epoch 177/500] [Batch 580/676] [D loss: 0.013806] [G loss: 0.024552] [d1 loss: 0.076472] [d2 loss: 0.071752]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]

[Epoch 177/500] [Batch 600/676] [D loss: 0.022677] [G loss: -0.001951] [d1 loss: 0.161054] [d2 loss: 0.169806]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 177/500] [Batch 620/676] [D loss: -0.014131] [G loss: -0.031364] [d1 loss: 0.073795] [d2 loss: 0.092556]  [sq d1 d2: 0.000352]  [num0: 17.000000] [num1 47.000000]
[Epoch 177/500] [Batch 640/676] [D loss: 0.010011] [G loss: -0.049398] [d1 loss: 0.094738] [d2 loss: 0.091199]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 177/500] [Batch 660/676] [D loss: 0.002145] [G loss: -0.052859] [d1 loss: 0.083092] [d2 loss: 0.069500]  [sq d1 d2: 0.000185]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 0/676] [D loss: -0.008741] [G loss: -0.038201] [d1 loss: 0.152172] [d2 loss: 0.133517]  [sq d1 d2: 0.000348]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 20/676] [D loss: -0.030204] [G loss: -0.009165] [d1 loss: 0.112398] [d2 loss: 0.074794]  [sq d1 d2: 0.001414]  [num0: 18.000000] [num1 46.000000]
[Epoch 178/500] [Batch 40/676] [D loss: -0.045176] [G loss: 0.031403] [d1 loss: 0.102913] [d2 loss: 0.090918]  [sq d1 d2: 0.000144]  [num0: 13.000000] [num1 51.000000]
[Epoch 178/500] [Batch 60/676] [D loss: -0.084903] [G loss: 0.084126] [d1 loss: 0.126094] [d2 loss: 0.140725]  [sq d1 d2: 0.000214]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 80/676] [D loss: -0.096255] [G loss: 0.137545] [d1 loss: 0.101939] [d2 loss: 0.132500]  [sq d1 d2: 0.000934]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 100/676] [D loss: -0.022444] [G loss: 0.113063] [d1 loss: 0.090423] [d2 loss: 0.086921]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 178/500] [Batch 120/676] [D loss: 0.033668] [G loss: 0.087821] [d1 loss: 0.095800] [d2 loss: 0.101611]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 140/676] [D loss: -0.010958] [G loss: 0.041843] [d1 loss: 0.126881] [d2 loss: 0.081804]  [sq d1 d2: 0.002032]  [num0: 13.000000] [num1 51.000000]
[Epoch 178/500] [Batch 160/676] [D loss: -0.005612] [G loss: -0.075134] [d1 loss: 0.128134] [d2 loss: 0.118527]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 178/500] [Batch 180/676] [D loss: -0.003390] [G loss: -0.105677] [d1 loss: 0.108514] [d2 loss: 0.077274]  [sq d1 d2: 0.000976]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 200/676] [D loss: -0.000442] [G loss: -0.121755] [d1 loss: 0.112788] [d2 loss: 0.108643]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 220/676] [D loss: -0.003749] [G loss: -0.131958] [d1 loss: 0.144271] [d2 loss: 0.138402]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 240/676] [D loss: -0.006531] [G loss: -0.145283] [d1 loss: 0.056721] [d2 loss: 0.046970]  [sq d1 d2: 0.000095]  [num0: 12.000000] [num1 52.000000]
[Epoch 178/500] [Batch 260/676] [D loss: -0.014623] [G loss: -0.157100] [d1 loss: 0.053742] [d2 loss: 0.059824]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 178/500] [Batch 280/676] [D loss: -0.027541] [G loss: -0.162341] [d1 loss: 0.050029] [d2 loss: 0.056587]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 300/676] [D loss: -0.011650] [G loss: -0.154649] [d1 loss: 0.029146] [d2 loss: 0.030474]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 320/676] [D loss: -0.002353] [G loss: -0.113249] [d1 loss: 0.096315] [d2 loss: 0.089056]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 340/676] [D loss: -0.012655] [G loss: -0.101623] [d1 loss: 0.091433] [d2 loss: 0.102017]  [sq d1 d2: 0.000112]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 360/676] [D loss: -0.030679] [G loss: -0.117783] [d1 loss: 0.102470] [d2 loss: 0.124717]  [sq d1 d2: 0.000495]  [num0: 20.000000] [num1 44.000000]
[Epoch 178/500] [Batch 380/676] [D loss: -0.045969] [G loss: -0.105344] [d1 loss: 0.814915] [d2 loss: 0.706866]  [sq d1 d2: 0.011674]  [num0: 20.000000] [num1 44.000000]
[Epoch 178/500] [Batch 400/676] [D loss: -0.005600] [G loss: -0.025089] [d1 loss: 0.092171] [d2 loss: 0.088562]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 420/676] [D loss: 0.020956] [G loss: -0.036942] [d1 loss: 0.146586] [d2 loss: 0.102890]  [sq d1 d2: 0.001909]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 440/676] [D loss: 0.018395] [G loss: -0.025883] [d1 loss: 0.053838] [d2 loss: 0.055179]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 460/676] [D loss: 0.000031] [G loss: 0.046004] [d1 loss: 0.069731] [d2 loss: 0.079455]  [sq d1 d2: 0.000095]  [num0: 20.000000] [num1 44.000000]
[Epoch 178/500] [Batch 480/676] [D loss: -0.017830] [G loss: 0.046465] [d1 loss: 0.154462] [d2 loss: 0.126890]  [sq d1 d2: 0.000760]  [num0: 18.000000] [num1 46.000000]
[Epoch 178/500] [Batch 500/676] [D loss: -0.013214] [G loss: 0.098961] [d1 loss: 0.113074] [d2 loss: 0.118513]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 178/500] [Batch 520/676] [D loss: -0.031287] [G loss: 0.153712] [d1 loss: 0.103389] [d2 loss: 0.087845]  [sq d1 d2: 0.000242]  [num0: 19.000000] [num1 45.000000]
[Epoch 178/500] [Batch 540/676] [D loss: -0.004791] [G loss: 0.171185] [d1 loss: 0.029143] [d2 loss: 0.026627]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 560/676] [D loss: -0.015624] [G loss: 0.132786] [d1 loss: 0.050590] [d2 loss: 0.042215]  [sq d1 d2: 0.000070]  [num0: 13.000000] [num1 51.000000]
[Epoch 178/500] [Batch 580/676] [D loss: -0.024312] [G loss: 0.178125] [d1 loss: 0.158307] [d2 loss: 0.060832]  [sq d1 d2: 0.009501]  [num0: 14.000000] [num1 50.000000]
[Epoch 178/500] [Batch 600/676] [D loss: -0.018411] [G loss: 0.150155] [d1 loss: 0.068898] [d2 loss: 0.066031]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 178/500] [Batch 620/676] [D loss: 0.014280] [G loss: 0.139061] [d1 loss: 0.103409] [d2 loss: 0.130700]  [sq d1 d2: 0.000745]  [num0: 17.000000] [num1 47.000000]
[Epoch 178/500] [Batch 640/676] [D loss: 0.012370] [G loss: 0.089311] [d1 loss: 0.099618] [d2 loss: 0.110468]  [sq d1 d2: 0.000118]  [num0: 20.000000] [num1 44.000000]
[Epoch 178/500] [Batch 660/676] [D loss: -0.003884] [G loss: 0.096978] [d1 loss: 0.024914] [d2 loss: 0.020792]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 179/500] [Batch 0/676] [D loss: -0.013790] [G loss: 0.062602] [d1 loss: 0.072807] [d2 loss: 0.067064]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 20/676] [D loss: -0.033024] [G loss: 0.005956] [d1 loss: 0.049768] [d2 loss: 0.051539]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 40/676] [D loss: -0.005771] [G loss: 0.035626] [d1 loss: 0.038924] [d2 loss: 0.033857]  [sq d1 d2: 0.000026]  [num0: 11.000000] [num1 53.000000]
[Epoch 179/500] [Batch 60/676] [D loss: -0.032056] [G loss: 0.016354] [d1 loss: 0.014066] [d2 loss: 0.013594]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 179/500] [Batch 80/676] [D loss: -0.006184] [G loss: 0.049531] [d1 loss: 0.069988] [d2 loss: 0.065221]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 100/676] [D loss: -0.014351] [G loss: 0.055905] [d1 loss: 0.073022] [d2 loss: 0.082426]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 120/676] [D loss: -0.003280] [G loss: 0.043219] [d1 loss: 0.134305] [d2 loss: 0.111441]  [sq d1 d2: 0.000523]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 140/676] [D loss: 0.000643] [G loss: 0.067517] [d1 loss: 0.053079] [d2 loss: 0.049507]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 179/500] [Batch 160/676] [D loss: -0.009880] [G loss: 0.058915] [d1 loss: 0.046028] [d2 loss: 0.047775]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 179/500] [Batch 180/676] [D loss: -0.006063] [G loss: 0.061577] [d1 loss: 0.124603] [d2 loss: 0.089826]  [sq d1 d2: 0.001209]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 200/676] [D loss: 0.003060] [G loss: 0.133748] [d1 loss: 0.041283] [d2 loss: 0.038971]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 220/676] [D loss: -0.003862] [G loss: 0.218843] [d1 loss: 0.047606] [d2 loss: 0.049795]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 179/500] [Batch 240/676] [D loss: -0.011521] [G loss: 0.240358] [d1 loss: 0.048181] [d2 loss: 0.049434]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 260/676] [D loss: -0.045008] [G loss: 0.274957] [d1 loss: 0.064032] [d2 loss: 0.088601]  [sq d1 d2: 0.000604]  [num0: 17.000000] [num1 47.000000]

[Epoch 179/500] [Batch 280/676] [D loss: -0.015788] [G loss: 0.233261] [d1 loss: 0.030244] [d2 loss: 0.023180]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 300/676] [D loss: -0.047934] [G loss: 0.210418] [d1 loss: 0.160696] [d2 loss: 0.159928]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 179/500] [Batch 320/676] [D loss: -0.023160] [G loss: 0.230238] [d1 loss: 0.043894] [d2 loss: 0.041787]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 179/500] [Batch 340/676] [D loss: -0.009610] [G loss: 0.202741] [d1 loss: 0.075620] [d2 loss: 0.094388]  [sq d1 d2: 0.000352]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 360/676] [D loss: 0.001403] [G loss: 0.198633] [d1 loss: 0.047373] [d2 loss: 0.047435]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 179/500] [Batch 380/676] [D loss: 0.005935] [G loss: 0.098587] [d1 loss: 0.071457] [d2 loss: 0.090403]  [sq d1 d2: 0.000359]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 400/676] [D loss: 0.008755] [G loss: 0.092294] [d1 loss: 0.059610] [d2 loss: 0.090231]  [sq d1 d2: 0.000938]  [num0: 12.000000] [num1 52.000000]
[Epoch 179/500] [Batch 420/676] [D loss: -0.024944] [G loss: 0.034951] [d1 loss: 0.116431] [d2 loss: 0.113921]  [sq d1 d2: 0.000006]  [num0: 20.000000] [num1 44.000000]
[Epoch 179/500] [Batch 440/676] [D loss: -0.024786] [G loss: -0.006622] [d1 loss: 0.043296] [d2 loss: 0.051587]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 460/676] [D loss: -0.036160] [G loss: -0.037967] [d1 loss: 0.084444] [d2 loss: 0.063854]  [sq d1 d2: 0.000424]  [num0: 21.000000] [num1 43.000000]
[Epoch 179/500] [Batch 480/676] [D loss: -0.015131] [G loss: -0.020381] [d1 loss: 0.136334] [d2 loss: 0.128180]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 179/500] [Batch 500/676] [D loss: -0.021133] [G loss: -0.020678] [d1 loss: 0.031082] [d2 loss: 0.033849]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 520/676] [D loss: -0.037863] [G loss: -0.060622] [d1 loss: 0.074352] [d2 loss: 0.060606]  [sq d1 d2: 0.000189]  [num0: 13.000000] [num1 51.000000]
[Epoch 179/500] [Batch 540/676] [D loss: -0.032145] [G loss: -0.110655] [d1 loss: 0.056007] [d2 loss: 0.064458]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 179/500] [Batch 560/676] [D loss: 0.062622] [G loss: -0.111257] [d1 loss: 0.061957] [d2 loss: 0.047482]  [sq d1 d2: 0.000210]  [num0: 12.000000] [num1 52.000000]
[Epoch 179/500] [Batch 580/676] [D loss: 0.006627] [G loss: -0.082336] [d1 loss: 0.113394] [d2 loss: 0.105351]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 179/500] [Batch 600/676] [D loss: 0.008151] [G loss: -0.076991] [d1 loss: 0.151982] [d2 loss: 0.137846]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 179/500] [Batch 620/676] [D loss: -0.013698] [G loss: -0.108949] [d1 loss: 0.099652] [d2 loss: 0.098887]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 179/500] [Batch 640/676] [D loss: -0.011706] [G loss: -0.148729] [d1 loss: 0.084778] [d2 loss: 0.070971]  [sq d1 d2: 0.000191]  [num0: 18.000000] [num1 46.000000]
[Epoch 179/500] [Batch 660/676] [D loss: -0.007582] [G loss: -0.095422] [d1 loss: 0.088534] [d2 loss: 0.108131]  [sq d1 d2: 0.000384]  [num0: 14.000000] [num1 50.000000]
[Epoch 180/500] [Batch 0/676] [D loss: -0.023543] [G loss: -0.090590] [d1 loss: 0.044936] [d2 loss: 0.049769]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 180/500] [Batch 20/676] [D loss: -0.018825] [G loss: -0.071657] [d1 loss: 0.056811] [d2 loss: 0.045939]  [sq d1 d2: 0.000118]  [num0: 20.000000] [num1 44.000000]
[Epoch 180/500] [Batch 40/676] [D loss: -0.017327] [G loss: -0.054610] [d1 loss: 0.031508] [d2 loss: 0.034703]  [sq d1 d2: 0.000010]  [num0: 10.000000] [num1 54.000000]
[Epoch 180/500] [Batch 60/676] [D loss: -0.013608] [G loss: -0.037392] [d1 loss: 0.045374] [d2 loss: 0.052767]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 80/676] [D loss: -0.018575] [G loss: -0.033833] [d1 loss: 0.076292] [d2 loss: 0.063030]  [sq d1 d2: 0.000176]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 100/676] [D loss: -0.015390] [G loss: -0.033835] [d1 loss: 0.042771] [d2 loss: 0.044640]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 120/676] [D loss: -0.026848] [G loss: -0.034918] [d1 loss: 0.036231] [d2 loss: 0.035908]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 180/500] [Batch 140/676] [D loss: -0.012505] [G loss: -0.032439] [d1 loss: 0.086737] [d2 loss: 0.083932]  [sq d1 d2: 0.000008]  [num0: 10.000000] [num1 54.000000]
[Epoch 180/500] [Batch 160/676] [D loss: -0.007951] [G loss: 0.012106] [d1 loss: 0.072684] [d2 loss: 0.128648]  [sq d1 d2: 0.003132]  [num0: 13.000000] [num1 51.000000]
[Epoch 180/500] [Batch 180/676] [D loss: -0.002133] [G loss: 0.038604] [d1 loss: 0.091771] [d2 loss: 0.076350]  [sq d1 d2: 0.000238]  [num0: 16.000000] [num1 48.000000]
[Epoch 180/500] [Batch 200/676] [D loss: 0.018573] [G loss: 0.087798] [d1 loss: 0.088741] [d2 loss: 0.084735]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 180/500] [Batch 220/676] [D loss: -0.001349] [G loss: 0.124781] [d1 loss: 0.086953] [d2 loss: 0.102399]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 180/500] [Batch 240/676] [D loss: -0.018819] [G loss: 0.182769] [d1 loss: 0.190571] [d2 loss: 0.136891]  [sq d1 d2: 0.002882]  [num0: 13.000000] [num1 51.000000]
[Epoch 180/500] [Batch 260/676] [D loss: -0.011186] [G loss: 0.182332] [d1 loss: 0.027535] [d2 loss: 0.022771]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 180/500] [Batch 280/676] [D loss: -0.012262] [G loss: 0.205036] [d1 loss: 0.029772] [d2 loss: 0.035356]  [sq d1 d2: 0.000031]  [num0: 19.000000] [num1 45.000000]
[Epoch 180/500] [Batch 300/676] [D loss: -0.021268] [G loss: 0.223441] [d1 loss: 0.033100] [d2 loss: 0.028288]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 180/500] [Batch 320/676] [D loss: -0.016624] [G loss: 0.228437] [d1 loss: 0.089576] [d2 loss: 0.083738]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 340/676] [D loss: -0.038649] [G loss: 0.236944] [d1 loss: 0.051242] [d2 loss: 0.047598]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 180/500] [Batch 360/676] [D loss: -0.011433] [G loss: 0.236369] [d1 loss: 0.076719] [d2 loss: 0.085434]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 380/676] [D loss: -0.018930] [G loss: 0.186399] [d1 loss: 0.024285] [d2 loss: 0.028409]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 180/500] [Batch 400/676] [D loss: -0.021880] [G loss: 0.159138] [d1 loss: 0.120870] [d2 loss: 0.133590]  [sq d1 d2: 0.000162]  [num0: 18.000000] [num1 46.000000]
[Epoch 180/500] [Batch 420/676] [D loss: 0.009512] [G loss: 0.123295] [d1 loss: 0.061857] [d2 loss: 0.028916]  [sq d1 d2: 0.001085]  [num0: 13.000000] [num1 51.000000]
[Epoch 180/500] [Batch 440/676] [D loss: -0.023877] [G loss: 0.074824] [d1 loss: 0.048505] [d2 loss: 0.038565]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 180/500] [Batch 460/676] [D loss: 0.006323] [G loss: 0.038775] [d1 loss: 0.078108] [d2 loss: 0.071796]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 180/500] [Batch 480/676] [D loss: -0.003616] [G loss: -0.004737] [d1 loss: 0.033252] [d2 loss: 0.034862]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 500/676] [D loss: -0.003384] [G loss: -0.029424] [d1 loss: 0.078370] [d2 loss: 0.081706]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 180/500] [Batch 520/676] [D loss: -0.012904] [G loss: -0.057247] [d1 loss: 0.073067] [d2 loss: 0.076702]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 180/500] [Batch 540/676] [D loss: -0.010558] [G loss: -0.123660] [d1 loss: 0.106305] [d2 loss: 0.104351]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 180/500] [Batch 560/676] [D loss: -0.012708] [G loss: -0.159860] [d1 loss: 0.025221] [d2 loss: 0.023088]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 180/500] [Batch 580/676] [D loss: -0.032452] [G loss: -0.175330] [d1 loss: 0.085143] [d2 loss: 0.071110]  [sq d1 d2: 0.000197]  [num0: 19.000000] [num1 45.000000]
[Epoch 180/500] [Batch 600/676] [D loss: -0.007561] [G loss: -0.208446] [d1 loss: 0.062312] [d2 loss: 0.073324]  [sq d1 d2: 0.000121]  [num0: 15.000000] [num1 49.000000]
[Epoch 180/500] [Batch 620/676] [D loss: -0.026550] [G loss: -0.256671] [d1 loss: 0.084161] [d2 loss: 0.086206]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]

[Epoch 180/500] [Batch 640/676] [D loss: -0.018523] [G loss: -0.216500] [d1 loss: 0.072166] [d2 loss: 0.063050]  [sq d1 d2: 0.000083]  [num0: 12.000000] [num1 52.000000]
[Epoch 180/500] [Batch 660/676] [D loss: -0.027555] [G loss: -0.235403] [d1 loss: 0.063160] [d2 loss: 0.080589]  [sq d1 d2: 0.000304]  [num0: 15.000000] [num1 49.000000]
[Epoch 181/500] [Batch 0/676] [D loss: -0.022569] [G loss: -0.240020] [d1 loss: 0.079052] [d2 loss: 0.077696]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 181/500] [Batch 20/676] [D loss: -0.012161] [G loss: -0.223637] [d1 loss: 0.047492] [d2 loss: 0.046669]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 181/500] [Batch 40/676] [D loss: -0.013860] [G loss: -0.186600] [d1 loss: 0.090073] [d2 loss: 0.084626]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 60/676] [D loss: -0.029405] [G loss: -0.131766] [d1 loss: 0.083925] [d2 loss: 0.088919]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 181/500] [Batch 80/676] [D loss: -0.006301] [G loss: -0.083196] [d1 loss: 0.040003] [d2 loss: 0.034174]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 100/676] [D loss: -0.016182] [G loss: -0.052500] [d1 loss: 0.039841] [d2 loss: 0.043258]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 120/676] [D loss: -0.026229] [G loss: -0.022332] [d1 loss: 0.059107] [d2 loss: 0.061825]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 181/500] [Batch 140/676] [D loss: 0.003082] [G loss: 0.012659] [d1 loss: 0.036411] [d2 loss: 0.028510]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 181/500] [Batch 160/676] [D loss: -0.019283] [G loss: 0.029762] [d1 loss: 0.110085] [d2 loss: 0.087767]  [sq d1 d2: 0.000498]  [num0: 15.000000] [num1 49.000000]
[Epoch 181/500] [Batch 180/676] [D loss: -0.013871] [G loss: 0.061575] [d1 loss: 0.049498] [d2 loss: 0.051983]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 181/500] [Batch 200/676] [D loss: -0.012310] [G loss: 0.070467] [d1 loss: 0.069271] [d2 loss: 0.073651]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 181/500] [Batch 220/676] [D loss: -0.019405] [G loss: 0.099039] [d1 loss: 0.114121] [d2 loss: 0.116599]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 240/676] [D loss: -0.009866] [G loss: 0.129759] [d1 loss: 0.076988] [d2 loss: 0.081300]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 181/500] [Batch 260/676] [D loss: -0.016672] [G loss: 0.156810] [d1 loss: 0.055720] [d2 loss: 0.063245]  [sq d1 d2: 0.000057]  [num0: 19.000000] [num1 45.000000]
[Epoch 181/500] [Batch 280/676] [D loss: -0.013510] [G loss: 0.115837] [d1 loss: 0.039775] [d2 loss: 0.034699]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 300/676] [D loss: 0.008271] [G loss: 0.160335] [d1 loss: 0.046025] [d2 loss: 0.043405]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 181/500] [Batch 320/676] [D loss: -0.024116] [G loss: 0.186983] [d1 loss: 0.030290] [d2 loss: 0.027914]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 181/500] [Batch 340/676] [D loss: -0.014102] [G loss: 0.185135] [d1 loss: 0.054243] [d2 loss: 0.059758]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 181/500] [Batch 360/676] [D loss: -0.031689] [G loss: 0.133863] [d1 loss: 0.040839] [d2 loss: 0.039779]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 181/500] [Batch 380/676] [D loss: -0.033448] [G loss: 0.164709] [d1 loss: 0.044113] [d2 loss: 0.055617]  [sq d1 d2: 0.000132]  [num0: 12.000000] [num1 52.000000]
[Epoch 181/500] [Batch 400/676] [D loss: -0.025212] [G loss: 0.160815] [d1 loss: 0.180094] [d2 loss: 0.195533]  [sq d1 d2: 0.000238]  [num0: 14.000000] [num1 50.000000]
[Epoch 181/500] [Batch 420/676] [D loss: -0.010563] [G loss: 0.099153] [d1 loss: 0.026346] [d2 loss: 0.035974]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 181/500] [Batch 440/676] [D loss: 0.004849] [G loss: 0.091567] [d1 loss: 0.081669] [d2 loss: 0.088470]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 460/676] [D loss: -0.005382] [G loss: 0.098401] [d1 loss: 0.028904] [d2 loss: 0.033527]  [sq d1 d2: 0.000021]  [num0: 23.000000] [num1 41.000000]
[Epoch 181/500] [Batch 480/676] [D loss: -0.005878] [G loss: 0.085220] [d1 loss: 0.027966] [d2 loss: 0.024528]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 500/676] [D loss: -0.015782] [G loss: 0.009859] [d1 loss: 0.022707] [d2 loss: 0.026006]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 181/500] [Batch 520/676] [D loss: -0.012164] [G loss: -0.005871] [d1 loss: 0.146660] [d2 loss: 0.166546]  [sq d1 d2: 0.000395]  [num0: 15.000000] [num1 49.000000]
[Epoch 181/500] [Batch 540/676] [D loss: -0.009218] [G loss: 0.002032] [d1 loss: 0.045933] [d2 loss: 0.049892]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 181/500] [Batch 560/676] [D loss: -0.021470] [G loss: 0.001420] [d1 loss: 0.090295] [d2 loss: 0.068139]  [sq d1 d2: 0.000491]  [num0: 18.000000] [num1 46.000000]
[Epoch 181/500] [Batch 580/676] [D loss: 0.006512] [G loss: 0.014211] [d1 loss: 0.072690] [d2 loss: 0.073435]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 181/500] [Batch 600/676] [D loss: -0.033572] [G loss: -0.018578] [d1 loss: 0.048102] [d2 loss: 0.045576]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 181/500] [Batch 620/676] [D loss: -0.008143] [G loss: -0.016868] [d1 loss: 0.026825] [d2 loss: 0.028141]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 181/500] [Batch 640/676] [D loss: -0.025206] [G loss: -0.041820] [d1 loss: 0.061331] [d2 loss: 0.062243]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 181/500] [Batch 660/676] [D loss: -0.018398] [G loss: -0.047009] [d1 loss: 0.100721] [d2 loss: 0.105913]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 182/500] [Batch 0/676] [D loss: 0.018667] [G loss: -0.019884] [d1 loss: 0.062485] [d2 loss: 0.059877]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 182/500] [Batch 20/676] [D loss: -0.006879] [G loss: -0.005615] [d1 loss: 0.059920] [d2 loss: 0.055316]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 182/500] [Batch 40/676] [D loss: 0.000548] [G loss: -0.010182] [d1 loss: 0.052594] [d2 loss: 0.043620]  [sq d1 d2: 0.000081]  [num0: 18.000000] [num1 46.000000]
[Epoch 182/500] [Batch 60/676] [D loss: -0.015623] [G loss: -0.002027] [d1 loss: 0.056077] [d2 loss: 0.046391]  [sq d1 d2: 0.000094]  [num0: 18.000000] [num1 46.000000]
[Epoch 182/500] [Batch 80/676] [D loss: -0.026784] [G loss: -0.054798] [d1 loss: 0.051902] [d2 loss: 0.064067]  [sq d1 d2: 0.000148]  [num0: 14.000000] [num1 50.000000]
[Epoch 182/500] [Batch 100/676] [D loss: -0.004560] [G loss: -0.070494] [d1 loss: 0.053969] [d2 loss: 0.060198]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 120/676] [D loss: -0.048635] [G loss: -0.069412] [d1 loss: 0.010672] [d2 loss: 0.017853]  [sq d1 d2: 0.000052]  [num0: 11.000000] [num1 53.000000]
[Epoch 182/500] [Batch 140/676] [D loss: -0.043451] [G loss: -0.091567] [d1 loss: 0.032869] [d2 loss: 0.035419]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 182/500] [Batch 160/676] [D loss: -0.023971] [G loss: -0.093835] [d1 loss: 0.124029] [d2 loss: 0.116738]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 182/500] [Batch 180/676] [D loss: 0.004210] [G loss: -0.081536] [d1 loss: 0.047213] [d2 loss: 0.032264]  [sq d1 d2: 0.000223]  [num0: 14.000000] [num1 50.000000]
[Epoch 182/500] [Batch 200/676] [D loss: -0.005095] [G loss: -0.115404] [d1 loss: 0.046112] [d2 loss: 0.041327]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 220/676] [D loss: -0.009071] [G loss: -0.076665] [d1 loss: 0.027785] [d2 loss: 0.024970]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 182/500] [Batch 240/676] [D loss: -0.020746] [G loss: -0.059137] [d1 loss: 0.041303] [d2 loss: 0.047847]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 182/500] [Batch 260/676] [D loss: 0.001713] [G loss: -0.057965] [d1 loss: 0.108488] [d2 loss: 0.101973]  [sq d1 d2: 0.000042]  [num0: 12.000000] [num1 52.000000]
[Epoch 182/500] [Batch 280/676] [D loss: -0.006295] [G loss: -0.001951] [d1 loss: 0.051429] [d2 loss: 0.051515]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 300/676] [D loss: -0.017200] [G loss: 0.031374] [d1 loss: 0.012583] [d2 loss: 0.014612]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]

[Epoch 182/500] [Batch 320/676] [D loss: -0.026489] [G loss: 0.021103] [d1 loss: 0.113941] [d2 loss: 0.095735]  [sq d1 d2: 0.000331]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 340/676] [D loss: -0.004840] [G loss: 0.056528] [d1 loss: 0.062609] [d2 loss: 0.069165]  [sq d1 d2: 0.000043]  [num0: 20.000000] [num1 44.000000]
[Epoch 182/500] [Batch 360/676] [D loss: -0.036320] [G loss: 0.025926] [d1 loss: 0.074441] [d2 loss: 0.075833]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 380/676] [D loss: -0.011457] [G loss: 0.061595] [d1 loss: 0.092190] [d2 loss: 0.122048]  [sq d1 d2: 0.000891]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 400/676] [D loss: -0.051736] [G loss: 0.046214] [d1 loss: 0.029447] [d2 loss: 0.023737]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 182/500] [Batch 420/676] [D loss: -0.027298] [G loss: 0.063321] [d1 loss: 0.088430] [d2 loss: 0.081445]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 440/676] [D loss: 0.006847] [G loss: 0.102184] [d1 loss: 0.055895] [d2 loss: 0.061032]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 460/676] [D loss: -0.004618] [G loss: 0.107476] [d1 loss: 0.063644] [d2 loss: 0.082408]  [sq d1 d2: 0.000352]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 480/676] [D loss: -0.003047] [G loss: 0.095742] [d1 loss: 0.090951] [d2 loss: 0.080160]  [sq d1 d2: 0.000116]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 500/676] [D loss: -0.003310] [G loss: 0.077563] [d1 loss: 0.079446] [d2 loss: 0.054068]  [sq d1 d2: 0.000644]  [num0: 14.000000] [num1 50.000000]
[Epoch 182/500] [Batch 520/676] [D loss: -0.013368] [G loss: 0.083567] [d1 loss: 0.046544] [d2 loss: 0.044807]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 182/500] [Batch 540/676] [D loss: -0.007171] [G loss: 0.059949] [d1 loss: 0.007838] [d2 loss: 0.009530]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 560/676] [D loss: 0.006454] [G loss: 0.037319] [d1 loss: 0.038276] [d2 loss: 0.030896]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 182/500] [Batch 580/676] [D loss: -0.034638] [G loss: 0.027092] [d1 loss: 0.105390] [d2 loss: 0.106711]  [sq d1 d2: 0.000002]  [num0: 21.000000] [num1 43.000000]
[Epoch 182/500] [Batch 600/676] [D loss: -0.031936] [G loss: 0.045352] [d1 loss: 0.025603] [d2 loss: 0.018814]  [sq d1 d2: 0.000046]  [num0: 13.000000] [num1 51.000000]
[Epoch 182/500] [Batch 620/676] [D loss: -0.027173] [G loss: 0.010333] [d1 loss: 0.041913] [d2 loss: 0.035632]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 182/500] [Batch 640/676] [D loss: -0.014272] [G loss: -0.031257] [d1 loss: 0.059219] [d2 loss: 0.045997]  [sq d1 d2: 0.000175]  [num0: 17.000000] [num1 47.000000]
[Epoch 182/500] [Batch 660/676] [D loss: 0.016398] [G loss: -0.080667] [d1 loss: 0.058044] [d2 loss: 0.056611]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 183/500] [Batch 0/676] [D loss: 0.001399] [G loss: -0.086985] [d1 loss: 0.048142] [d2 loss: 0.048837]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 20/676] [D loss: 0.007104] [G loss: -0.045929] [d1 loss: 0.102773] [d2 loss: 0.105120]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 183/500] [Batch 40/676] [D loss: -0.000396] [G loss: -0.072352] [d1 loss: 0.035118] [d2 loss: 0.036701]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 60/676] [D loss: -0.008181] [G loss: -0.062064] [d1 loss: 0.038948] [d2 loss: 0.036196]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 183/500] [Batch 80/676] [D loss: -0.005311] [G loss: -0.059321] [d1 loss: 0.036859] [d2 loss: 0.053553]  [sq d1 d2: 0.000279]  [num0: 12.000000] [num1 52.000000]
[Epoch 183/500] [Batch 100/676] [D loss: -0.010867] [G loss: -0.102730] [d1 loss: 0.046956] [d2 loss: 0.053030]  [sq d1 d2: 0.000037]  [num0: 13.000000] [num1 51.000000]
[Epoch 183/500] [Batch 120/676] [D loss: -0.033381] [G loss: -0.068255] [d1 loss: 0.068052] [d2 loss: 0.076895]  [sq d1 d2: 0.000078]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 140/676] [D loss: -0.034094] [G loss: -0.034169] [d1 loss: 0.070056] [d2 loss: 0.060568]  [sq d1 d2: 0.000090]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 160/676] [D loss: -0.002321] [G loss: -0.023439] [d1 loss: 0.025991] [d2 loss: 0.020558]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 183/500] [Batch 180/676] [D loss: -0.031829] [G loss: 0.003716] [d1 loss: 0.023086] [d2 loss: 0.022226]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 200/676] [D loss: -0.028602] [G loss: 0.046135] [d1 loss: 0.043744] [d2 loss: 0.041373]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 183/500] [Batch 220/676] [D loss: 0.000158] [G loss: 0.090456] [d1 loss: 0.101953] [d2 loss: 0.102156]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 240/676] [D loss: 0.008591] [G loss: 0.109062] [d1 loss: 0.074170] [d2 loss: 0.074574]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 260/676] [D loss: 0.016575] [G loss: 0.135321] [d1 loss: 0.084039] [d2 loss: 0.083937]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 183/500] [Batch 280/676] [D loss: 0.001435] [G loss: 0.119453] [d1 loss: 0.074684] [d2 loss: 0.087094]  [sq d1 d2: 0.000154]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 300/676] [D loss: -0.006545] [G loss: 0.146832] [d1 loss: 0.036750] [d2 loss: 0.049714]  [sq d1 d2: 0.000168]  [num0: 13.000000] [num1 51.000000]
[Epoch 183/500] [Batch 320/676] [D loss: -0.001162] [G loss: 0.179255] [d1 loss: 0.107516] [d2 loss: 0.103503]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 183/500] [Batch 340/676] [D loss: -0.023482] [G loss: 0.208773] [d1 loss: 0.098360] [d2 loss: 0.096308]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 183/500] [Batch 360/676] [D loss: -0.019968] [G loss: 0.227348] [d1 loss: 0.116131] [d2 loss: 0.114936]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 380/676] [D loss: -0.008859] [G loss: 0.203227] [d1 loss: 0.114665] [d2 loss: 0.095498]  [sq d1 d2: 0.000367]  [num0: 18.000000] [num1 46.000000]
[Epoch 183/500] [Batch 400/676] [D loss: -0.009834] [G loss: 0.157855] [d1 loss: 0.061240] [d2 loss: 0.055509]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 420/676] [D loss: -0.017064] [G loss: 0.154474] [d1 loss: 0.162400] [d2 loss: 0.194018]  [sq d1 d2: 0.001000]  [num0: 15.000000] [num1 49.000000]
[Epoch 183/500] [Batch 440/676] [D loss: 0.015387] [G loss: 0.187250] [d1 loss: 0.046327] [d2 loss: 0.031448]  [sq d1 d2: 0.000221]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 460/676] [D loss: -0.002141] [G loss: 0.151497] [d1 loss: 0.043803] [d2 loss: 0.049249]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 480/676] [D loss: -0.026494] [G loss: 0.146383] [d1 loss: 0.129179] [d2 loss: 0.107156]  [sq d1 d2: 0.000485]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 500/676] [D loss: -0.002069] [G loss: 0.134476] [d1 loss: 0.061601] [d2 loss: 0.063435]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 183/500] [Batch 520/676] [D loss: -0.012471] [G loss: 0.076901] [d1 loss: 0.073316] [d2 loss: 0.068963]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 540/676] [D loss: 0.002909] [G loss: 0.055077] [d1 loss: 0.166627] [d2 loss: 0.162482]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 183/500] [Batch 560/676] [D loss: -0.023527] [G loss: -0.006092] [d1 loss: 0.095235] [d2 loss: 0.110044]  [sq d1 d2: 0.000219]  [num0: 19.000000] [num1 45.000000]
[Epoch 183/500] [Batch 580/676] [D loss: -0.021186] [G loss: -0.047706] [d1 loss: 0.070803] [d2 loss: 0.049158]  [sq d1 d2: 0.000469]  [num0: 17.000000] [num1 47.000000]
[Epoch 183/500] [Batch 600/676] [D loss: -0.012726] [G loss: -0.053575] [d1 loss: 0.033774] [d2 loss: 0.027555]  [sq d1 d2: 0.000039]  [num0: 12.000000] [num1 52.000000]
[Epoch 183/500] [Batch 620/676] [D loss: -0.020122] [G loss: -0.086684] [d1 loss: 0.040796] [d2 loss: 0.035028]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 640/676] [D loss: -0.012953] [G loss: -0.114419] [d1 loss: 0.083356] [d2 loss: 0.078781]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 183/500] [Batch 660/676] [D loss: -0.022541] [G loss: -0.177333] [d1 loss: 0.078284] [d2 loss: 0.093077]  [sq d1 d2: 0.000219]  [num0: 18.000000] [num1 46.000000]

[Epoch 184/500] [Batch 0/676] [D loss: -0.003828] [G loss: -0.195601] [d1 loss: 0.035283] [d2 loss: 0.030151]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 20/676] [D loss: 0.017862] [G loss: -0.223589] [d1 loss: 0.062559] [d2 loss: 0.057167]  [sq d1 d2: 0.000029]  [num0: 20.000000] [num1 44.000000]
[Epoch 184/500] [Batch 40/676] [D loss: -0.011812] [G loss: -0.239485] [d1 loss: 0.061593] [d2 loss: 0.053558]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 60/676] [D loss: -0.009317] [G loss: -0.233408] [d1 loss: 0.032154] [d2 loss: 0.052432]  [sq d1 d2: 0.000411]  [num0: 17.000000] [num1 47.000000]
[Epoch 184/500] [Batch 80/676] [D loss: -0.000424] [G loss: -0.204828] [d1 loss: 0.066863] [d2 loss: 0.062663]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 100/676] [D loss: -0.005075] [G loss: -0.165044] [d1 loss: 0.011766] [d2 loss: 0.007852]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 120/676] [D loss: -0.007337] [G loss: -0.129702] [d1 loss: 0.032947] [d2 loss: 0.032963]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 184/500] [Batch 140/676] [D loss: -0.021897] [G loss: -0.131177] [d1 loss: 0.084891] [d2 loss: 0.077236]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 184/500] [Batch 160/676] [D loss: -0.015787] [G loss: -0.139478] [d1 loss: 0.061726] [d2 loss: 0.062452]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 184/500] [Batch 180/676] [D loss: -0.027678] [G loss: -0.109421] [d1 loss: 0.067767] [d2 loss: 0.067782]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 184/500] [Batch 200/676] [D loss: -0.025096] [G loss: -0.133355] [d1 loss: 0.118612] [d2 loss: 0.117372]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 220/676] [D loss: -0.017086] [G loss: -0.179358] [d1 loss: 0.038101] [d2 loss: 0.034439]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 184/500] [Batch 240/676] [D loss: -0.007885] [G loss: -0.169258] [d1 loss: 0.022873] [d2 loss: 0.017377]  [sq d1 d2: 0.000030]  [num0: 11.000000] [num1 53.000000]
[Epoch 184/500] [Batch 260/676] [D loss: -0.006507] [G loss: -0.154569] [d1 loss: 0.130843] [d2 loss: 0.141372]  [sq d1 d2: 0.000111]  [num0: 18.000000] [num1 46.000000]
[Epoch 184/500] [Batch 280/676] [D loss: -0.001754] [G loss: -0.101461] [d1 loss: 0.052509] [d2 loss: 0.052887]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 184/500] [Batch 300/676] [D loss: 0.015211] [G loss: -0.092647] [d1 loss: 0.020046] [d2 loss: 0.017288]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 320/676] [D loss: -0.002957] [G loss: -0.058148] [d1 loss: 0.067520] [d2 loss: 0.074451]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 340/676] [D loss: -0.004799] [G loss: -0.017129] [d1 loss: 0.022106] [d2 loss: 0.020673]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 360/676] [D loss: -0.009650] [G loss: 0.027713] [d1 loss: 0.080941] [d2 loss: 0.080606]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 380/676] [D loss: -0.003925] [G loss: 0.047462] [d1 loss: 0.035119] [d2 loss: 0.021484]  [sq d1 d2: 0.000186]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 400/676] [D loss: -0.008368] [G loss: 0.083149] [d1 loss: 0.058713] [d2 loss: 0.055154]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 184/500] [Batch 420/676] [D loss: -0.025163] [G loss: 0.099759] [d1 loss: 0.065207] [d2 loss: 0.054925]  [sq d1 d2: 0.000106]  [num0: 14.000000] [num1 50.000000]
[Epoch 184/500] [Batch 440/676] [D loss: -0.023658] [G loss: 0.078061] [d1 loss: 0.099662] [d2 loss: 0.116806]  [sq d1 d2: 0.000294]  [num0: 13.000000] [num1 51.000000]
[Epoch 184/500] [Batch 460/676] [D loss: -0.024352] [G loss: 0.091685] [d1 loss: 0.110093] [d2 loss: 0.087373]  [sq d1 d2: 0.000516]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 480/676] [D loss: 0.002175] [G loss: 0.074519] [d1 loss: 0.042234] [d2 loss: 0.032800]  [sq d1 d2: 0.000089]  [num0: 18.000000] [num1 46.000000]
[Epoch 184/500] [Batch 500/676] [D loss: -0.023334] [G loss: 0.108490] [d1 loss: 0.035057] [d2 loss: 0.024649]  [sq d1 d2: 0.000108]  [num0: 18.000000] [num1 46.000000]
[Epoch 184/500] [Batch 520/676] [D loss: 0.000792] [G loss: 0.109847] [d1 loss: 0.059516] [d2 loss: 0.097133]  [sq d1 d2: 0.001415]  [num0: 11.000000] [num1 53.000000]
[Epoch 184/500] [Batch 540/676] [D loss: -0.013418] [G loss: 0.116949] [d1 loss: 0.139105] [d2 loss: 0.108773]  [sq d1 d2: 0.000920]  [num0: 17.000000] [num1 47.000000]
[Epoch 184/500] [Batch 560/676] [D loss: 0.005998] [G loss: 0.124833] [d1 loss: 0.043331] [d2 loss: 0.026947]  [sq d1 d2: 0.000268]  [num0: 16.000000] [num1 48.000000]
[Epoch 184/500] [Batch 580/676] [D loss: -0.004039] [G loss: 0.119277] [d1 loss: 0.082328] [d2 loss: 0.089038]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 184/500] [Batch 600/676] [D loss: -0.002721] [G loss: 0.105179] [d1 loss: 0.019959] [d2 loss: 0.014530]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 184/500] [Batch 620/676] [D loss: -0.035197] [G loss: 0.146286] [d1 loss: 0.082004] [d2 loss: 0.092040]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 184/500] [Batch 640/676] [D loss: -0.027538] [G loss: 0.173024] [d1 loss: 0.047918] [d2 loss: 0.057749]  [sq d1 d2: 0.000097]  [num0: 11.000000] [num1 53.000000]
[Epoch 184/500] [Batch 660/676] [D loss: -0.029771] [G loss: 0.155838] [d1 loss: 0.074947] [d2 loss: 0.086900]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 0/676] [D loss: 0.000833] [G loss: 0.188962] [d1 loss: 0.048428] [d2 loss: 0.044255]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 185/500] [Batch 20/676] [D loss: -0.004784] [G loss: 0.169056] [d1 loss: 0.035189] [d2 loss: 0.033076]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 40/676] [D loss: -0.013015] [G loss: 0.139661] [d1 loss: 0.058461] [d2 loss: 0.049765]  [sq d1 d2: 0.000076]  [num0: 20.000000] [num1 44.000000]
[Epoch 185/500] [Batch 60/676] [D loss: -0.005887] [G loss: 0.150051] [d1 loss: 0.047275] [d2 loss: 0.041279]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 185/500] [Batch 80/676] [D loss: -0.007400] [G loss: 0.087501] [d1 loss: 0.044313] [d2 loss: 0.044937]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 185/500] [Batch 100/676] [D loss: -0.001913] [G loss: 0.064083] [d1 loss: 0.112333] [d2 loss: 0.111611]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 120/676] [D loss: -0.002844] [G loss: 0.006158] [d1 loss: 0.057590] [d2 loss: 0.064223]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 140/676] [D loss: -0.012612] [G loss: -0.003199] [d1 loss: 0.026767] [d2 loss: 0.025901]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 185/500] [Batch 160/676] [D loss: -0.008747] [G loss: -0.004310] [d1 loss: 0.048728] [d2 loss: 0.038976]  [sq d1 d2: 0.000095]  [num0: 15.000000] [num1 49.000000]
[Epoch 185/500] [Batch 180/676] [D loss: -0.016306] [G loss: -0.024162] [d1 loss: 0.039140] [d2 loss: 0.040853]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 200/676] [D loss: -0.027073] [G loss: -0.031734] [d1 loss: 0.031470] [d2 loss: 0.025192]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 220/676] [D loss: -0.028512] [G loss: -0.042595] [d1 loss: 0.077876] [d2 loss: 0.096279]  [sq d1 d2: 0.000339]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 240/676] [D loss: -0.030481] [G loss: -0.055215] [d1 loss: 0.089735] [d2 loss: 0.081244]  [sq d1 d2: 0.000072]  [num0: 18.000000] [num1 46.000000]
[Epoch 185/500] [Batch 260/676] [D loss: -0.020735] [G loss: -0.043781] [d1 loss: 0.034988] [d2 loss: 0.033261]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 185/500] [Batch 280/676] [D loss: -0.021861] [G loss: -0.022783] [d1 loss: 0.128464] [d2 loss: 0.144461]  [sq d1 d2: 0.000256]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 300/676] [D loss: -0.002548] [G loss: -0.022166] [d1 loss: 0.043134] [d2 loss: 0.056230]  [sq d1 d2: 0.000172]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 320/676] [D loss: -0.001969] [G loss: -0.036788] [d1 loss: 0.049058] [d2 loss: 0.048632]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 185/500] [Batch 340/676] [D loss: 0.010956] [G loss: -0.039570] [d1 loss: 0.095076] [d2 loss: 0.089018]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]

[Epoch 185/500] [Batch 360/676] [D loss: -0.003734] [G loss: -0.076734] [d1 loss: 0.037641] [d2 loss: 0.037049]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 380/676] [D loss: -0.006055] [G loss: -0.083485] [d1 loss: 0.027868] [d2 loss: 0.025219]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 185/500] [Batch 400/676] [D loss: -0.015002] [G loss: -0.061533] [d1 loss: 0.083339] [d2 loss: 0.094541]  [sq d1 d2: 0.000125]  [num0: 13.000000] [num1 51.000000]
[Epoch 185/500] [Batch 420/676] [D loss: -0.019789] [G loss: -0.087476] [d1 loss: 0.052685] [d2 loss: 0.054487]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 185/500] [Batch 440/676] [D loss: -0.015536] [G loss: -0.076848] [d1 loss: 0.083307] [d2 loss: 0.086297]  [sq d1 d2: 0.000009]  [num0: 11.000000] [num1 53.000000]
[Epoch 185/500] [Batch 460/676] [D loss: -0.013708] [G loss: -0.074555] [d1 loss: 0.052145] [d2 loss: 0.036884]  [sq d1 d2: 0.000233]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 480/676] [D loss: -0.018463] [G loss: -0.048525] [d1 loss: 0.063578] [d2 loss: 0.064989]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 185/500] [Batch 500/676] [D loss: -0.029350] [G loss: -0.097700] [d1 loss: 0.026526] [d2 loss: 0.024439]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 185/500] [Batch 520/676] [D loss: -0.021980] [G loss: -0.055093] [d1 loss: 0.045538] [d2 loss: 0.034981]  [sq d1 d2: 0.000111]  [num0: 16.000000] [num1 48.000000]
[Epoch 185/500] [Batch 540/676] [D loss: -0.013271] [G loss: -0.085363] [d1 loss: 0.165127] [d2 loss: 0.155258]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 185/500] [Batch 560/676] [D loss: 0.018470] [G loss: -0.064993] [d1 loss: 0.059646] [d2 loss: 0.069900]  [sq d1 d2: 0.000105]  [num0: 17.000000] [num1 47.000000]
[Epoch 185/500] [Batch 580/676] [D loss: -0.000709] [G loss: -0.046193] [d1 loss: 0.046866] [d2 loss: 0.032233]  [sq d1 d2: 0.000214]  [num0: 12.000000] [num1 52.000000]
[Epoch 185/500] [Batch 600/676] [D loss: 0.000326] [G loss: -0.020413] [d1 loss: 0.019169] [d2 loss: 0.018972]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 185/500] [Batch 620/676] [D loss: -0.002623] [G loss: 0.037526] [d1 loss: 0.026871] [d2 loss: 0.027743]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 185/500] [Batch 640/676] [D loss: -0.013220] [G loss: 0.121957] [d1 loss: 0.059333] [d2 loss: 0.042043]  [sq d1 d2: 0.000299]  [num0: 15.000000] [num1 49.000000]
[Epoch 185/500] [Batch 660/676] [D loss: -0.016842] [G loss: 0.135014] [d1 loss: 0.021826] [d2 loss: 0.033778]  [sq d1 d2: 0.000143]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 0/676] [D loss: -0.012552] [G loss: 0.170623] [d1 loss: 0.029525] [d2 loss: 0.032935]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 20/676] [D loss: -0.025099] [G loss: 0.176138] [d1 loss: 0.011264] [d2 loss: 0.010463]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 40/676] [D loss: -0.013953] [G loss: 0.128784] [d1 loss: 0.039551] [d2 loss: 0.038218]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 60/676] [D loss: -0.000063] [G loss: 0.153765] [d1 loss: 0.056857] [d2 loss: 0.051672]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 80/676] [D loss: -0.020901] [G loss: 0.168165] [d1 loss: 0.066374] [d2 loss: 0.072807]  [sq d1 d2: 0.000041]  [num0: 12.000000] [num1 52.000000]
[Epoch 186/500] [Batch 100/676] [D loss: -0.017056] [G loss: 0.179551] [d1 loss: 0.057062] [d2 loss: 0.050926]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 120/676] [D loss: -0.013016] [G loss: 0.190286] [d1 loss: 0.050339] [d2 loss: 0.047457]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 140/676] [D loss: -0.001109] [G loss: 0.159688] [d1 loss: 0.020721] [d2 loss: 0.018448]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 160/676] [D loss: -0.006633] [G loss: 0.151770] [d1 loss: 0.022152] [d2 loss: 0.023979]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 180/676] [D loss: -0.008670] [G loss: 0.146542] [d1 loss: 0.060305] [d2 loss: 0.050455]  [sq d1 d2: 0.000097]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 200/676] [D loss: -0.019361] [G loss: 0.122957] [d1 loss: 0.182703] [d2 loss: 0.166051]  [sq d1 d2: 0.000277]  [num0: 17.000000] [num1 47.000000]
[Epoch 186/500] [Batch 220/676] [D loss: -0.013637] [G loss: 0.130910] [d1 loss: 0.058035] [d2 loss: 0.049521]  [sq d1 d2: 0.000072]  [num0: 16.000000] [num1 48.000000]
[Epoch 186/500] [Batch 240/676] [D loss: -0.038686] [G loss: 0.122712] [d1 loss: 0.055286] [d2 loss: 0.048607]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 260/676] [D loss: -0.047644] [G loss: 0.103520] [d1 loss: 0.050091] [d2 loss: 0.049343]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 280/676] [D loss: -0.029732] [G loss: 0.087293] [d1 loss: 0.026138] [d2 loss: 0.030023]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 300/676] [D loss: -0.038984] [G loss: 0.049461] [d1 loss: 0.137020] [d2 loss: 0.109712]  [sq d1 d2: 0.000746]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 320/676] [D loss: 0.016362] [G loss: 0.013954] [d1 loss: 0.061639] [d2 loss: 0.064379]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 340/676] [D loss: 0.004459] [G loss: -0.001818] [d1 loss: 0.047292] [d2 loss: 0.049698]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 186/500] [Batch 360/676] [D loss: -0.000231] [G loss: -0.011015] [d1 loss: 0.058142] [d2 loss: 0.060270]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 186/500] [Batch 380/676] [D loss: -0.003356] [G loss: -0.044715] [d1 loss: 0.021475] [d2 loss: 0.016314]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 186/500] [Batch 400/676] [D loss: -0.015840] [G loss: -0.032160] [d1 loss: 0.086746] [d2 loss: 0.097837]  [sq d1 d2: 0.000123]  [num0: 17.000000] [num1 47.000000]
[Epoch 186/500] [Batch 420/676] [D loss: -0.010271] [G loss: -0.044760] [d1 loss: 0.036350] [d2 loss: 0.046732]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 440/676] [D loss: -0.020221] [G loss: -0.061427] [d1 loss: 0.058174] [d2 loss: 0.057117]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 460/676] [D loss: -0.044041] [G loss: -0.086643] [d1 loss: 0.174820] [d2 loss: 0.205459]  [sq d1 d2: 0.000939]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 480/676] [D loss: -0.019778] [G loss: -0.146542] [d1 loss: 0.076338] [d2 loss: 0.065138]  [sq d1 d2: 0.000125]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 500/676] [D loss: -0.020503] [G loss: -0.161142] [d1 loss: 0.067116] [d2 loss: 0.065535]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 520/676] [D loss: -0.006254] [G loss: -0.158414] [d1 loss: 0.071340] [d2 loss: 0.070106]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 540/676] [D loss: 0.008706] [G loss: -0.176401] [d1 loss: 0.076308] [d2 loss: 0.080419]  [sq d1 d2: 0.000017]  [num0: 11.000000] [num1 53.000000]
[Epoch 186/500] [Batch 560/676] [D loss: -0.008570] [G loss: -0.160807] [d1 loss: 0.124266] [d2 loss: 0.110424]  [sq d1 d2: 0.000192]  [num0: 18.000000] [num1 46.000000]
[Epoch 186/500] [Batch 580/676] [D loss: 0.001875] [G loss: -0.171786] [d1 loss: 0.083468] [d2 loss: 0.074331]  [sq d1 d2: 0.000083]  [num0: 22.000000] [num1 42.000000]
[Epoch 186/500] [Batch 600/676] [D loss: -0.000824] [G loss: -0.184968] [d1 loss: 0.056985] [d2 loss: 0.060047]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 186/500] [Batch 620/676] [D loss: -0.015702] [G loss: -0.196226] [d1 loss: 0.028645] [d2 loss: 0.033914]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 186/500] [Batch 640/676] [D loss: -0.005382] [G loss: -0.180478] [d1 loss: 0.071859] [d2 loss: 0.067306]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 186/500] [Batch 660/676] [D loss: -0.001288] [G loss: -0.182557] [d1 loss: 0.064584] [d2 loss: 0.074322]  [sq d1 d2: 0.000095]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 0/676] [D loss: -0.042348] [G loss: -0.198677] [d1 loss: 0.038366] [d2 loss: 0.040222]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 187/500] [Batch 20/676] [D loss: -0.049479] [G loss: -0.171805] [d1 loss: 0.044575] [d2 loss: 0.039154]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]

[Epoch 187/500] [Batch 40/676] [D loss: -0.010378] [G loss: -0.194573] [d1 loss: 0.089015] [d2 loss: 0.083870]  [sq d1 d2: 0.000026]  [num0: 12.000000] [num1 52.000000]
[Epoch 187/500] [Batch 60/676] [D loss: -0.036769] [G loss: -0.112655] [d1 loss: 0.076695] [d2 loss: 0.096742]  [sq d1 d2: 0.000402]  [num0: 12.000000] [num1 52.000000]
[Epoch 187/500] [Batch 80/676] [D loss: -0.016891] [G loss: -0.112607] [d1 loss: 0.057186] [d2 loss: 0.050698]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 100/676] [D loss: -0.000247] [G loss: -0.060767] [d1 loss: 0.023051] [d2 loss: 0.029912]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 120/676] [D loss: 0.002808] [G loss: -0.057959] [d1 loss: 0.075642] [d2 loss: 0.075531]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 187/500] [Batch 140/676] [D loss: -0.029747] [G loss: -0.001974] [d1 loss: 0.058552] [d2 loss: 0.048796]  [sq d1 d2: 0.000095]  [num0: 15.000000] [num1 49.000000]
[Epoch 187/500] [Batch 160/676] [D loss: 0.015854] [G loss: 0.019691] [d1 loss: 0.095638] [d2 loss: 0.079246]  [sq d1 d2: 0.000269]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 180/676] [D loss: -0.022596] [G loss: 0.065792] [d1 loss: 0.056741] [d2 loss: 0.052652]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 187/500] [Batch 200/676] [D loss: -0.015366] [G loss: 0.085331] [d1 loss: 0.117910] [d2 loss: 0.090711]  [sq d1 d2: 0.000740]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 220/676] [D loss: -0.004329] [G loss: 0.069817] [d1 loss: 0.060705] [d2 loss: 0.075171]  [sq d1 d2: 0.000209]  [num0: 13.000000] [num1 51.000000]
[Epoch 187/500] [Batch 240/676] [D loss: -0.046285] [G loss: 0.096547] [d1 loss: 0.092313] [d2 loss: 0.106647]  [sq d1 d2: 0.000205]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 260/676] [D loss: -0.033742] [G loss: 0.117229] [d1 loss: 0.034434] [d2 loss: 0.030150]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 187/500] [Batch 280/676] [D loss: -0.029580] [G loss: 0.096436] [d1 loss: 0.081126] [d2 loss: 0.074575]  [sq d1 d2: 0.000043]  [num0: 12.000000] [num1 52.000000]
[Epoch 187/500] [Batch 300/676] [D loss: -0.012201] [G loss: 0.084743] [d1 loss: 0.095683] [d2 loss: 0.121582]  [sq d1 d2: 0.000671]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 320/676] [D loss: -0.027026] [G loss: 0.083256] [d1 loss: 0.145187] [d2 loss: 0.135344]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 340/676] [D loss: 0.011026] [G loss: 0.120061] [d1 loss: 0.027420] [d2 loss: 0.023861]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 360/676] [D loss: -0.005160] [G loss: 0.091781] [d1 loss: 0.103950] [d2 loss: 0.127419]  [sq d1 d2: 0.000551]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 380/676] [D loss: -0.006355] [G loss: 0.096182] [d1 loss: 0.041900] [d2 loss: 0.053132]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 400/676] [D loss: -0.013725] [G loss: 0.105734] [d1 loss: 0.031983] [d2 loss: 0.026584]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 187/500] [Batch 420/676] [D loss: 0.009176] [G loss: 0.097373] [d1 loss: 0.039983] [d2 loss: 0.039759]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 187/500] [Batch 440/676] [D loss: -0.023430] [G loss: 0.061212] [d1 loss: 0.184266] [d2 loss: 0.143312]  [sq d1 d2: 0.001677]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 460/676] [D loss: -0.010055] [G loss: -0.001294] [d1 loss: 0.059072] [d2 loss: 0.082062]  [sq d1 d2: 0.000529]  [num0: 17.000000] [num1 47.000000]
[Epoch 187/500] [Batch 480/676] [D loss: -0.028427] [G loss: -0.014622] [d1 loss: 0.066993] [d2 loss: 0.046433]  [sq d1 d2: 0.000423]  [num0: 13.000000] [num1 51.000000]
[Epoch 187/500] [Batch 500/676] [D loss: -0.019632] [G loss: -0.022934] [d1 loss: 0.047701] [d2 loss: 0.073050]  [sq d1 d2: 0.000643]  [num0: 19.000000] [num1 45.000000]
[Epoch 187/500] [Batch 520/676] [D loss: -0.023997] [G loss: -0.028976] [d1 loss: 0.105629] [d2 loss: 0.107946]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 187/500] [Batch 540/676] [D loss: -0.006117] [G loss: -0.059963] [d1 loss: 0.056440] [d2 loss: 0.057573]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 187/500] [Batch 560/676] [D loss: -0.008919] [G loss: -0.045190] [d1 loss: 0.077059] [d2 loss: 0.076465]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 580/676] [D loss: 0.007765] [G loss: -0.070479] [d1 loss: 0.155999] [d2 loss: 0.132043]  [sq d1 d2: 0.000574]  [num0: 11.000000] [num1 53.000000]
[Epoch 187/500] [Batch 600/676] [D loss: -0.019181] [G loss: -0.072719] [d1 loss: 0.131294] [d2 loss: 0.139952]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 187/500] [Batch 620/676] [D loss: -0.002946] [G loss: -0.086592] [d1 loss: 0.147854] [d2 loss: 0.122805]  [sq d1 d2: 0.000627]  [num0: 15.000000] [num1 49.000000]
[Epoch 187/500] [Batch 640/676] [D loss: -0.003397] [G loss: -0.109165] [d1 loss: 0.043239] [d2 loss: 0.054207]  [sq d1 d2: 0.000120]  [num0: 14.000000] [num1 50.000000]
[Epoch 187/500] [Batch 660/676] [D loss: -0.011229] [G loss: -0.066886] [d1 loss: 0.072825] [d2 loss: 0.069984]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 0/676] [D loss: -0.002974] [G loss: -0.081599] [d1 loss: 0.058721] [d2 loss: 0.033965]  [sq d1 d2: 0.000613]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 20/676] [D loss: -0.028101] [G loss: -0.116900] [d1 loss: 0.044259] [d2 loss: 0.040356]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 188/500] [Batch 40/676] [D loss: -0.020500] [G loss: -0.126512] [d1 loss: 0.117522] [d2 loss: 0.128079]  [sq d1 d2: 0.000111]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 60/676] [D loss: -0.016828] [G loss: -0.140993] [d1 loss: 0.041708] [d2 loss: 0.037895]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 80/676] [D loss: -0.028901] [G loss: -0.175427] [d1 loss: 0.170195] [d2 loss: 0.135428]  [sq d1 d2: 0.001209]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 100/676] [D loss: -0.018805] [G loss: -0.217494] [d1 loss: 0.188386] [d2 loss: 0.158463]  [sq d1 d2: 0.000895]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 120/676] [D loss: -0.020640] [G loss: -0.195700] [d1 loss: 0.089575] [d2 loss: 0.091451]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 188/500] [Batch 140/676] [D loss: 0.022054] [G loss: -0.280050] [d1 loss: 0.048845] [d2 loss: 0.040326]  [sq d1 d2: 0.000073]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 160/676] [D loss: -0.021294] [G loss: -0.290669] [d1 loss: 0.053399] [d2 loss: 0.059797]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 180/676] [D loss: -0.010766] [G loss: -0.256700] [d1 loss: 0.068563] [d2 loss: 0.061853]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 200/676] [D loss: 0.013266] [G loss: -0.183574] [d1 loss: 0.036776] [d2 loss: 0.044299]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 220/676] [D loss: -0.002012] [G loss: -0.175090] [d1 loss: 0.112666] [d2 loss: 0.098969]  [sq d1 d2: 0.000188]  [num0: 18.000000] [num1 46.000000]
[Epoch 188/500] [Batch 240/676] [D loss: -0.014892] [G loss: -0.127631] [d1 loss: 0.087199] [d2 loss: 0.087079]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 260/676] [D loss: -0.020541] [G loss: -0.128983] [d1 loss: 0.074819] [d2 loss: 0.062419]  [sq d1 d2: 0.000154]  [num0: 13.000000] [num1 51.000000]
[Epoch 188/500] [Batch 280/676] [D loss: -0.024784] [G loss: -0.135385] [d1 loss: 0.035927] [d2 loss: 0.031464]  [sq d1 d2: 0.000020]  [num0: 12.000000] [num1 52.000000]
[Epoch 188/500] [Batch 300/676] [D loss: -0.011843] [G loss: -0.157414] [d1 loss: 0.055396] [d2 loss: 0.054758]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 188/500] [Batch 320/676] [D loss: -0.023648] [G loss: -0.155573] [d1 loss: 0.026727] [d2 loss: 0.023793]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 340/676] [D loss: -0.026848] [G loss: -0.146045] [d1 loss: 0.045732] [d2 loss: 0.041620]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]

[Epoch 188/500] [Batch 360/676] [D loss: -0.028484] [G loss: -0.118107] [d1 loss: 0.044599] [d2 loss: 0.038630]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 380/676] [D loss: -0.007014] [G loss: -0.068063] [d1 loss: 0.098380] [d2 loss: 0.099434]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 188/500] [Batch 400/676] [D loss: -0.004216] [G loss: -0.003479] [d1 loss: 0.028665] [d2 loss: 0.031824]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 188/500] [Batch 420/676] [D loss: -0.000777] [G loss: 0.021236] [d1 loss: 0.032268] [d2 loss: 0.020456]  [sq d1 d2: 0.000140]  [num0: 14.000000] [num1 50.000000]
[Epoch 188/500] [Batch 440/676] [D loss: -0.000908] [G loss: 0.045386] [d1 loss: 0.043892] [d2 loss: 0.042293]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 460/676] [D loss: -0.016423] [G loss: 0.118353] [d1 loss: 0.034906] [d2 loss: 0.033057]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 188/500] [Batch 480/676] [D loss: -0.032158] [G loss: 0.141852] [d1 loss: 0.092574] [d2 loss: 0.095294]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 188/500] [Batch 500/676] [D loss: -0.040020] [G loss: 0.146928] [d1 loss: 0.038231] [d2 loss: 0.054911]  [sq d1 d2: 0.000278]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 520/676] [D loss: -0.028945] [G loss: 0.148366] [d1 loss: 0.050105] [d2 loss: 0.046653]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 540/676] [D loss: -0.036814] [G loss: 0.156116] [d1 loss: 0.016442] [d2 loss: 0.019293]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 188/500] [Batch 560/676] [D loss: -0.029037] [G loss: 0.168045] [d1 loss: 0.085082] [d2 loss: 0.087609]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 188/500] [Batch 580/676] [D loss: -0.020149] [G loss: 0.185766] [d1 loss: 0.045775] [d2 loss: 0.039343]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 600/676] [D loss: -0.024022] [G loss: 0.134669] [d1 loss: 0.042405] [d2 loss: 0.029064]  [sq d1 d2: 0.000178]  [num0: 13.000000] [num1 51.000000]
[Epoch 188/500] [Batch 620/676] [D loss: -0.018164] [G loss: 0.088769] [d1 loss: 0.052417] [d2 loss: 0.033613]  [sq d1 d2: 0.000354]  [num0: 15.000000] [num1 49.000000]
[Epoch 188/500] [Batch 640/676] [D loss: -0.016572] [G loss: 0.031573] [d1 loss: 0.095787] [d2 loss: 0.116095]  [sq d1 d2: 0.000412]  [num0: 16.000000] [num1 48.000000]
[Epoch 188/500] [Batch 660/676] [D loss: 0.017448] [G loss: 0.010213] [d1 loss: 0.051080] [d2 loss: 0.044076]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 189/500] [Batch 0/676] [D loss: -0.009944] [G loss: -0.010295] [d1 loss: 0.074816] [d2 loss: 0.077692]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 189/500] [Batch 20/676] [D loss: -0.007101] [G loss: -0.039803] [d1 loss: 0.088601] [d2 loss: 0.060793]  [sq d1 d2: 0.000773]  [num0: 12.000000] [num1 52.000000]
[Epoch 189/500] [Batch 40/676] [D loss: -0.018689] [G loss: -0.124861] [d1 loss: 0.180400] [d2 loss: 0.187084]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 189/500] [Batch 60/676] [D loss: -0.026262] [G loss: -0.237557] [d1 loss: 0.067384] [d2 loss: 0.057944]  [sq d1 d2: 0.000089]  [num0: 14.000000] [num1 50.000000]
[Epoch 189/500] [Batch 80/676] [D loss: -0.010861] [G loss: -0.276171] [d1 loss: 0.087935] [d2 loss: 0.081708]  [sq d1 d2: 0.000039]  [num0: 12.000000] [num1 52.000000]
[Epoch 189/500] [Batch 100/676] [D loss: -0.017955] [G loss: -0.324838] [d1 loss: 0.072410] [d2 loss: 0.092159]  [sq d1 d2: 0.000390]  [num0: 18.000000] [num1 46.000000]
[Epoch 189/500] [Batch 120/676] [D loss: -0.013716] [G loss: -0.329428] [d1 loss: 0.059160] [d2 loss: 0.058823]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 140/676] [D loss: 0.015573] [G loss: -0.331244] [d1 loss: 0.113684] [d2 loss: 0.115007]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 189/500] [Batch 160/676] [D loss: -0.011142] [G loss: -0.276281] [d1 loss: 0.137150] [d2 loss: 0.105226]  [sq d1 d2: 0.001019]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 180/676] [D loss: 0.013665] [G loss: -0.235196] [d1 loss: 0.059556] [d2 loss: 0.051189]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 189/500] [Batch 200/676] [D loss: -0.010130] [G loss: -0.161390] [d1 loss: 0.017991] [d2 loss: 0.027396]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 189/500] [Batch 220/676] [D loss: -0.004679] [G loss: -0.208548] [d1 loss: 0.156674] [d2 loss: 0.125556]  [sq d1 d2: 0.000968]  [num0: 17.000000] [num1 47.000000]
[Epoch 189/500] [Batch 240/676] [D loss: -0.002775] [G loss: -0.161539] [d1 loss: 0.033596] [d2 loss: 0.038447]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 189/500] [Batch 260/676] [D loss: -0.002230] [G loss: -0.177733] [d1 loss: 0.206608] [d2 loss: 0.198479]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 189/500] [Batch 280/676] [D loss: -0.007168] [G loss: -0.123500] [d1 loss: 0.123634] [d2 loss: 0.123875]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 189/500] [Batch 300/676] [D loss: -0.012350] [G loss: -0.063591] [d1 loss: 0.142948] [d2 loss: 0.145134]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 189/500] [Batch 320/676] [D loss: -0.029231] [G loss: -0.079270] [d1 loss: 0.033111] [d2 loss: 0.029413]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]
[Epoch 189/500] [Batch 340/676] [D loss: -0.007762] [G loss: -0.086510] [d1 loss: 0.096771] [d2 loss: 0.109013]  [sq d1 d2: 0.000150]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 360/676] [D loss: -0.023237] [G loss: -0.065192] [d1 loss: 0.261787] [d2 loss: 0.355615]  [sq d1 d2: 0.008804]  [num0: 19.000000] [num1 45.000000]
[Epoch 189/500] [Batch 380/676] [D loss: -0.023304] [G loss: -0.062539] [d1 loss: 0.010681] [d2 loss: 0.012011]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 189/500] [Batch 400/676] [D loss: -0.007184] [G loss: -0.092352] [d1 loss: 0.059410] [d2 loss: 0.038603]  [sq d1 d2: 0.000433]  [num0: 15.000000] [num1 49.000000]
[Epoch 189/500] [Batch 420/676] [D loss: -0.019660] [G loss: -0.077777] [d1 loss: 0.037374] [d2 loss: 0.031770]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 440/676] [D loss: -0.018881] [G loss: -0.025230] [d1 loss: 0.019541] [d2 loss: 0.025165]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 189/500] [Batch 460/676] [D loss: -0.007065] [G loss: -0.021009] [d1 loss: 0.037342] [d2 loss: 0.033337]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 480/676] [D loss: 0.028642] [G loss: -0.015415] [d1 loss: 0.043147] [d2 loss: 0.044635]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 189/500] [Batch 500/676] [D loss: -0.022285] [G loss: 0.027506] [d1 loss: 0.040701] [d2 loss: 0.046540]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 189/500] [Batch 520/676] [D loss: 0.035477] [G loss: 0.013390] [d1 loss: 0.054402] [d2 loss: 0.073294]  [sq d1 d2: 0.000357]  [num0: 14.000000] [num1 50.000000]
[Epoch 189/500] [Batch 540/676] [D loss: -0.023012] [G loss: 0.043491] [d1 loss: 0.125817] [d2 loss: 0.114247]  [sq d1 d2: 0.000134]  [num0: 13.000000] [num1 51.000000]
[Epoch 189/500] [Batch 560/676] [D loss: -0.027579] [G loss: 0.080412] [d1 loss: 0.065368] [d2 loss: 0.059173]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 189/500] [Batch 580/676] [D loss: 0.012022] [G loss: 0.090873] [d1 loss: 0.084083] [d2 loss: 0.056757]  [sq d1 d2: 0.000747]  [num0: 16.000000] [num1 48.000000]
[Epoch 189/500] [Batch 600/676] [D loss: -0.035077] [G loss: 0.111676] [d1 loss: 0.159593] [d2 loss: 0.145865]  [sq d1 d2: 0.000188]  [num0: 15.000000] [num1 49.000000]
[Epoch 189/500] [Batch 620/676] [D loss: -0.046943] [G loss: 0.139958] [d1 loss: 0.081189] [d2 loss: 0.098675]  [sq d1 d2: 0.000306]  [num0: 18.000000] [num1 46.000000]
[Epoch 189/500] [Batch 640/676] [D loss: -0.025695] [G loss: 0.158257] [d1 loss: 0.048354] [d2 loss: 0.054106]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 189/500] [Batch 660/676] [D loss: -0.043079] [G loss: 0.160240] [d1 loss: 0.120696] [d2 loss: 0.104282]  [sq d1 d2: 0.000269]  [num0: 12.000000] [num1 52.000000]
[Epoch 190/500] [Batch 0/676] [D loss: -0.016378] [G loss: 0.159322] [d1 loss: 0.128901] [d2 loss: 0.136115]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 190/500] [Batch 20/676] [D loss: 0.002513] [G loss: 0.157683] [d1 loss: 0.037957] [d2 loss: 0.031631]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]

[Epoch 190/500] [Batch 40/676] [D loss: -0.001596] [G loss: 0.208517] [d1 loss: 0.089705] [d2 loss: 0.120909]  [sq d1 d2: 0.000974]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 60/676] [D loss: -0.008775] [G loss: 0.224332] [d1 loss: 0.165338] [d2 loss: 0.098682]  [sq d1 d2: 0.004443]  [num0: 14.000000] [num1 50.000000]
[Epoch 190/500] [Batch 80/676] [D loss: -0.007949] [G loss: 0.177968] [d1 loss: 0.061881] [d2 loss: 0.064442]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 100/676] [D loss: -0.006063] [G loss: 0.162910] [d1 loss: 0.104659] [d2 loss: 0.114749]  [sq d1 d2: 0.000102]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 120/676] [D loss: -0.017164] [G loss: 0.153817] [d1 loss: 0.061860] [d2 loss: 0.063512]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 140/676] [D loss: -0.003913] [G loss: 0.148400] [d1 loss: 0.063554] [d2 loss: 0.053823]  [sq d1 d2: 0.000095]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 160/676] [D loss: -0.018182] [G loss: 0.055543] [d1 loss: 0.062529] [d2 loss: 0.062835]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 190/500] [Batch 180/676] [D loss: -0.035432] [G loss: 0.093453] [d1 loss: 0.104672] [d2 loss: 0.121764]  [sq d1 d2: 0.000292]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 200/676] [D loss: 0.001230] [G loss: 0.088255] [d1 loss: 0.241192] [d2 loss: 0.214610]  [sq d1 d2: 0.000707]  [num0: 15.000000] [num1 49.000000]
[Epoch 190/500] [Batch 220/676] [D loss: -0.027789] [G loss: -0.018204] [d1 loss: 0.084472] [d2 loss: 0.105662]  [sq d1 d2: 0.000449]  [num0: 12.000000] [num1 52.000000]
[Epoch 190/500] [Batch 240/676] [D loss: -0.040725] [G loss: -0.082148] [d1 loss: 0.054138] [d2 loss: 0.058836]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 190/500] [Batch 260/676] [D loss: -0.040354] [G loss: -0.164863] [d1 loss: 0.044822] [d2 loss: 0.039451]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 280/676] [D loss: -0.017033] [G loss: -0.245371] [d1 loss: 0.072144] [d2 loss: 0.085682]  [sq d1 d2: 0.000183]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 300/676] [D loss: -0.036645] [G loss: -0.307347] [d1 loss: 0.069085] [d2 loss: 0.067581]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 190/500] [Batch 320/676] [D loss: 0.011175] [G loss: -0.367140] [d1 loss: 0.047084] [d2 loss: 0.053102]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 190/500] [Batch 340/676] [D loss: -0.012063] [G loss: -0.348788] [d1 loss: 0.069176] [d2 loss: 0.068458]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 190/500] [Batch 360/676] [D loss: -0.015248] [G loss: -0.374680] [d1 loss: 0.111125] [d2 loss: 0.105061]  [sq d1 d2: 0.000037]  [num0: 18.000000] [num1 46.000000]
[Epoch 190/500] [Batch 380/676] [D loss: -0.023806] [G loss: -0.373176] [d1 loss: 0.096544] [d2 loss: 0.101839]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 400/676] [D loss: -0.006462] [G loss: -0.345145] [d1 loss: 0.034242] [d2 loss: 0.036062]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 190/500] [Batch 420/676] [D loss: -0.001662] [G loss: -0.323796] [d1 loss: 0.111170] [d2 loss: 0.113627]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 440/676] [D loss: -0.009427] [G loss: -0.327546] [d1 loss: 0.070428] [d2 loss: 0.087378]  [sq d1 d2: 0.000287]  [num0: 14.000000] [num1 50.000000]
[Epoch 190/500] [Batch 460/676] [D loss: -0.044632] [G loss: -0.319358] [d1 loss: 0.085355] [d2 loss: 0.087229]  [sq d1 d2: 0.000004]  [num0: 9.000000] [num1 55.000000]
[Epoch 190/500] [Batch 480/676] [D loss: 0.008966] [G loss: -0.307375] [d1 loss: 0.110831] [d2 loss: 0.133454]  [sq d1 d2: 0.000512]  [num0: 11.000000] [num1 53.000000]
[Epoch 190/500] [Batch 500/676] [D loss: -0.027957] [G loss: -0.251041] [d1 loss: 0.106736] [d2 loss: 0.095881]  [sq d1 d2: 0.000118]  [num0: 19.000000] [num1 45.000000]
[Epoch 190/500] [Batch 520/676] [D loss: -0.005781] [G loss: -0.200121] [d1 loss: 0.059396] [d2 loss: 0.063495]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 190/500] [Batch 540/676] [D loss: -0.058934] [G loss: -0.208762] [d1 loss: 0.123123] [d2 loss: 0.107297]  [sq d1 d2: 0.000250]  [num0: 12.000000] [num1 52.000000]
[Epoch 190/500] [Batch 560/676] [D loss: -0.021757] [G loss: -0.158596] [d1 loss: 0.126843] [d2 loss: 0.139486]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 190/500] [Batch 580/676] [D loss: 0.011859] [G loss: -0.158096] [d1 loss: 0.037505] [d2 loss: 0.030384]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 600/676] [D loss: -0.017821] [G loss: -0.124046] [d1 loss: 0.085086] [d2 loss: 0.085352]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 190/500] [Batch 620/676] [D loss: -0.009898] [G loss: -0.075718] [d1 loss: 0.119146] [d2 loss: 0.115698]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 190/500] [Batch 640/676] [D loss: -0.041380] [G loss: -0.018047] [d1 loss: 0.124835] [d2 loss: 0.167568]  [sq d1 d2: 0.001826]  [num0: 15.000000] [num1 49.000000]
[Epoch 190/500] [Batch 660/676] [D loss: -0.011497] [G loss: 0.041267] [d1 loss: 0.067414] [d2 loss: 0.060939]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 0/676] [D loss: -0.022033] [G loss: 0.043640] [d1 loss: 0.115931] [d2 loss: 0.126040]  [sq d1 d2: 0.000102]  [num0: 13.000000] [num1 51.000000]
[Epoch 191/500] [Batch 20/676] [D loss: -0.034031] [G loss: 0.077960] [d1 loss: 0.180144] [d2 loss: 0.140448]  [sq d1 d2: 0.001576]  [num0: 13.000000] [num1 51.000000]
[Epoch 191/500] [Batch 40/676] [D loss: -0.025279] [G loss: 0.097579] [d1 loss: 0.067154] [d2 loss: 0.052688]  [sq d1 d2: 0.000209]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 60/676] [D loss: -0.049724] [G loss: 0.129901] [d1 loss: 0.097033] [d2 loss: 0.094379]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 80/676] [D loss: -0.032579] [G loss: 0.128135] [d1 loss: 0.058242] [d2 loss: 0.061791]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 100/676] [D loss: 0.010974] [G loss: 0.101614] [d1 loss: 0.050233] [d2 loss: 0.043758]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 120/676] [D loss: -0.027949] [G loss: 0.085685] [d1 loss: 0.047671] [d2 loss: 0.038963]  [sq d1 d2: 0.000076]  [num0: 12.000000] [num1 52.000000]
[Epoch 191/500] [Batch 140/676] [D loss: -0.010854] [G loss: 0.052133] [d1 loss: 0.038840] [d2 loss: 0.036629]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 191/500] [Batch 160/676] [D loss: -0.037461] [G loss: 0.044410] [d1 loss: 0.016425] [d2 loss: 0.018484]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 180/676] [D loss: -0.018621] [G loss: 0.104152] [d1 loss: 0.012608] [d2 loss: 0.010143]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 200/676] [D loss: -0.054682] [G loss: 0.052608] [d1 loss: 0.214202] [d2 loss: 0.176483]  [sq d1 d2: 0.001423]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 220/676] [D loss: -0.013071] [G loss: 0.054623] [d1 loss: 0.080014] [d2 loss: 0.069412]  [sq d1 d2: 0.000112]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 240/676] [D loss: -0.025758] [G loss: 0.015973] [d1 loss: 0.059871] [d2 loss: 0.046475]  [sq d1 d2: 0.000179]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 260/676] [D loss: -0.044019] [G loss: 0.040004] [d1 loss: 0.040360] [d2 loss: 0.041756]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 280/676] [D loss: -0.012852] [G loss: 0.021075] [d1 loss: 0.065236] [d2 loss: 0.063080]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 300/676] [D loss: -0.008407] [G loss: 0.017296] [d1 loss: 0.033850] [d2 loss: 0.034396]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 320/676] [D loss: 0.004225] [G loss: 0.025300] [d1 loss: 0.112433] [d2 loss: 0.082681]  [sq d1 d2: 0.000885]  [num0: 14.000000] [num1 50.000000]
[Epoch 191/500] [Batch 340/676] [D loss: -0.005428] [G loss: 0.019671] [d1 loss: 0.040546] [d2 loss: 0.040739]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 191/500] [Batch 360/676] [D loss: -0.032915] [G loss: 0.033889] [d1 loss: 0.137815] [d2 loss: 0.163056]  [sq d1 d2: 0.000637]  [num0: 18.000000] [num1 46.000000]
[Epoch 191/500] [Batch 380/676] [D loss: -0.032541] [G loss: 0.069294] [d1 loss: 0.105214] [d2 loss: 0.092837]  [sq d1 d2: 0.000153]  [num0: 15.000000] [num1 49.000000]

[Epoch 191/500] [Batch 400/676] [D loss: 0.012316] [G loss: 0.085184] [d1 loss: 0.079246] [d2 loss: 0.065416]  [sq d1 d2: 0.000191]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 420/676] [D loss: -0.013905] [G loss: 0.076731] [d1 loss: 0.052778] [d2 loss: 0.050204]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 191/500] [Batch 440/676] [D loss: -0.033737] [G loss: 0.103088] [d1 loss: 0.086454] [d2 loss: 0.082238]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 460/676] [D loss: -0.045408] [G loss: 0.121329] [d1 loss: 0.043500] [d2 loss: 0.045709]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 480/676] [D loss: -0.005183] [G loss: 0.120951] [d1 loss: 0.062661] [d2 loss: 0.062441]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 500/676] [D loss: -0.037709] [G loss: 0.120673] [d1 loss: 0.110633] [d2 loss: 0.111022]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 520/676] [D loss: -0.010160] [G loss: 0.089686] [d1 loss: 0.117097] [d2 loss: 0.112046]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 191/500] [Batch 540/676] [D loss: -0.015203] [G loss: 0.065479] [d1 loss: 0.103961] [d2 loss: 0.111216]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 191/500] [Batch 560/676] [D loss: -0.021824] [G loss: -0.012516] [d1 loss: 0.057204] [d2 loss: 0.055045]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 580/676] [D loss: -0.018820] [G loss: -0.084076] [d1 loss: 0.054260] [d2 loss: 0.046468]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 191/500] [Batch 600/676] [D loss: -0.010904] [G loss: -0.115131] [d1 loss: 0.050615] [d2 loss: 0.056268]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 191/500] [Batch 620/676] [D loss: -0.001079] [G loss: -0.209048] [d1 loss: 0.120264] [d2 loss: 0.138342]  [sq d1 d2: 0.000327]  [num0: 18.000000] [num1 46.000000]
[Epoch 191/500] [Batch 640/676] [D loss: -0.013494] [G loss: -0.216413] [d1 loss: 0.110616] [d2 loss: 0.093284]  [sq d1 d2: 0.000300]  [num0: 16.000000] [num1 48.000000]
[Epoch 191/500] [Batch 660/676] [D loss: -0.036403] [G loss: -0.246953] [d1 loss: 0.181378] [d2 loss: 0.163519]  [sq d1 d2: 0.000319]  [num0: 12.000000] [num1 52.000000]
[Epoch 192/500] [Batch 0/676] [D loss: -0.033296] [G loss: -0.246232] [d1 loss: 0.048659] [d2 loss: 0.050523]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 20/676] [D loss: 0.003416] [G loss: -0.297618] [d1 loss: 0.077561] [d2 loss: 0.057516]  [sq d1 d2: 0.000402]  [num0: 13.000000] [num1 51.000000]
[Epoch 192/500] [Batch 40/676] [D loss: -0.014243] [G loss: -0.298565] [d1 loss: 0.090514] [d2 loss: 0.082081]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 60/676] [D loss: -0.017871] [G loss: -0.318121] [d1 loss: 0.060183] [d2 loss: 0.075225]  [sq d1 d2: 0.000226]  [num0: 12.000000] [num1 52.000000]
[Epoch 192/500] [Batch 80/676] [D loss: -0.041128] [G loss: -0.311567] [d1 loss: 0.011230] [d2 loss: 0.011526]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 192/500] [Batch 100/676] [D loss: 0.020313] [G loss: -0.294861] [d1 loss: 0.112832] [d2 loss: 0.125510]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 192/500] [Batch 120/676] [D loss: -0.031340] [G loss: -0.270320] [d1 loss: 0.061767] [d2 loss: 0.075971]  [sq d1 d2: 0.000202]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 140/676] [D loss: -0.017598] [G loss: -0.197083] [d1 loss: 0.066537] [d2 loss: 0.058256]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 160/676] [D loss: -0.004805] [G loss: -0.093492] [d1 loss: 0.067651] [d2 loss: 0.064957]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 180/676] [D loss: -0.006185] [G loss: -0.066548] [d1 loss: 0.050639] [d2 loss: 0.055647]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 192/500] [Batch 200/676] [D loss: -0.015335] [G loss: -0.042254] [d1 loss: 0.049257] [d2 loss: 0.058835]  [sq d1 d2: 0.000092]  [num0: 12.000000] [num1 52.000000]
[Epoch 192/500] [Batch 220/676] [D loss: -0.015664] [G loss: -0.008865] [d1 loss: 0.092063] [d2 loss: 0.093859]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 192/500] [Batch 240/676] [D loss: -0.025836] [G loss: 0.005065] [d1 loss: 0.034365] [d2 loss: 0.055909]  [sq d1 d2: 0.000464]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 260/676] [D loss: -0.028079] [G loss: 0.025634] [d1 loss: 0.135215] [d2 loss: 0.136934]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 192/500] [Batch 280/676] [D loss: -0.036716] [G loss: 0.027106] [d1 loss: 0.092003] [d2 loss: 0.079795]  [sq d1 d2: 0.000149]  [num0: 20.000000] [num1 44.000000]
[Epoch 192/500] [Batch 300/676] [D loss: -0.045044] [G loss: 0.045102] [d1 loss: 0.102684] [d2 loss: 0.102339]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 192/500] [Batch 320/676] [D loss: 0.007978] [G loss: 0.044476] [d1 loss: 0.054088] [d2 loss: 0.030484]  [sq d1 d2: 0.000557]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 340/676] [D loss: -0.009941] [G loss: 0.036211] [d1 loss: 0.046495] [d2 loss: 0.049205]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 192/500] [Batch 360/676] [D loss: 0.003168] [G loss: 0.034313] [d1 loss: 0.099178] [d2 loss: 0.132673]  [sq d1 d2: 0.001122]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 380/676] [D loss: 0.025365] [G loss: 0.005853] [d1 loss: 0.084536] [d2 loss: 0.083010]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 192/500] [Batch 400/676] [D loss: -0.007584] [G loss: -0.004332] [d1 loss: 0.052834] [d2 loss: 0.047959]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 420/676] [D loss: 0.001488] [G loss: -0.010715] [d1 loss: 0.041084] [d2 loss: 0.044467]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 440/676] [D loss: -0.019829] [G loss: -0.005561] [d1 loss: 0.082109] [d2 loss: 0.074636]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 460/676] [D loss: -0.007706] [G loss: -0.022022] [d1 loss: 0.097858] [d2 loss: 0.076986]  [sq d1 d2: 0.000436]  [num0: 18.000000] [num1 46.000000]
[Epoch 192/500] [Batch 480/676] [D loss: -0.012590] [G loss: -0.031815] [d1 loss: 0.081265] [d2 loss: 0.059374]  [sq d1 d2: 0.000479]  [num0: 14.000000] [num1 50.000000]
[Epoch 192/500] [Batch 500/676] [D loss: -0.019831] [G loss: -0.024501] [d1 loss: 0.060047] [d2 loss: 0.057362]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 520/676] [D loss: -0.029083] [G loss: -0.064893] [d1 loss: 0.059123] [d2 loss: 0.053173]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 192/500] [Batch 540/676] [D loss: -0.025063] [G loss: -0.100624] [d1 loss: 0.090617] [d2 loss: 0.091135]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 192/500] [Batch 560/676] [D loss: -0.019580] [G loss: -0.084436] [d1 loss: 0.086843] [d2 loss: 0.072190]  [sq d1 d2: 0.000215]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 580/676] [D loss: -0.011396] [G loss: -0.095808] [d1 loss: 0.055582] [d2 loss: 0.048266]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 600/676] [D loss: -0.008567] [G loss: -0.075055] [d1 loss: 0.081833] [d2 loss: 0.091881]  [sq d1 d2: 0.000101]  [num0: 15.000000] [num1 49.000000]
[Epoch 192/500] [Batch 620/676] [D loss: 0.008986] [G loss: -0.076167] [d1 loss: 0.087702] [d2 loss: 0.087734]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 192/500] [Batch 640/676] [D loss: 0.011066] [G loss: -0.038724] [d1 loss: 0.110330] [d2 loss: 0.118645]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 192/500] [Batch 660/676] [D loss: -0.000252] [G loss: 0.002261] [d1 loss: 0.092511] [d2 loss: 0.081751]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 193/500] [Batch 0/676] [D loss: -0.011178] [G loss: 0.011145] [d1 loss: 0.064807] [d2 loss: 0.090019]  [sq d1 d2: 0.000636]  [num0: 13.000000] [num1 51.000000]
[Epoch 193/500] [Batch 20/676] [D loss: -0.009299] [G loss: 0.020841] [d1 loss: 0.058676] [d2 loss: 0.058111]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 193/500] [Batch 40/676] [D loss: -0.007241] [G loss: 0.027024] [d1 loss: 0.022476] [d2 loss: 0.035237]  [sq d1 d2: 0.000163]  [num0: 13.000000] [num1 51.000000]
[Epoch 193/500] [Batch 60/676] [D loss: -0.015543] [G loss: 0.056312] [d1 loss: 0.123168] [d2 loss: 0.131062]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]

[Epoch 193/500] [Batch 80/676] [D loss: -0.019202] [G loss: 0.096212] [d1 loss: 0.055934] [d2 loss: 0.056456]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 193/500] [Batch 100/676] [D loss: -0.013403] [G loss: 0.096606] [d1 loss: 0.040304] [d2 loss: 0.030812]  [sq d1 d2: 0.000090]  [num0: 19.000000] [num1 45.000000]
[Epoch 193/500] [Batch 120/676] [D loss: -0.020839] [G loss: 0.088125] [d1 loss: 0.118568] [d2 loss: 0.084233]  [sq d1 d2: 0.001179]  [num0: 20.000000] [num1 44.000000]
[Epoch 193/500] [Batch 140/676] [D loss: -0.001257] [G loss: 0.075073] [d1 loss: 0.122729] [d2 loss: 0.132964]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 160/676] [D loss: -0.023571] [G loss: 0.061283] [d1 loss: 0.073101] [d2 loss: 0.074249]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 193/500] [Batch 180/676] [D loss: 0.001780] [G loss: 0.029329] [d1 loss: 0.083470] [d2 loss: 0.074127]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 200/676] [D loss: 0.000768] [G loss: -0.021321] [d1 loss: 0.115232] [d2 loss: 0.116203]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 220/676] [D loss: 0.015932] [G loss: -0.063829] [d1 loss: 0.039539] [d2 loss: 0.035584]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 240/676] [D loss: -0.007217] [G loss: -0.058368] [d1 loss: 0.071855] [d2 loss: 0.055759]  [sq d1 d2: 0.000259]  [num0: 15.000000] [num1 49.000000]
[Epoch 193/500] [Batch 260/676] [D loss: 0.005164] [G loss: -0.081700] [d1 loss: 0.059911] [d2 loss: 0.064379]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 280/676] [D loss: -0.007454] [G loss: -0.121268] [d1 loss: 0.114429] [d2 loss: 0.105982]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 193/500] [Batch 300/676] [D loss: -0.014034] [G loss: -0.147603] [d1 loss: 0.063881] [d2 loss: 0.073832]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 193/500] [Batch 320/676] [D loss: -0.013476] [G loss: -0.141847] [d1 loss: 0.051516] [d2 loss: 0.055267]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 193/500] [Batch 340/676] [D loss: -0.014389] [G loss: -0.161817] [d1 loss: 0.066441] [d2 loss: 0.062613]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 193/500] [Batch 360/676] [D loss: -0.010255] [G loss: -0.238541] [d1 loss: 0.059134] [d2 loss: 0.053416]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 380/676] [D loss: -0.022020] [G loss: -0.271797] [d1 loss: 0.058783] [d2 loss: 0.059552]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 400/676] [D loss: 0.000607] [G loss: -0.232188] [d1 loss: 0.133850] [d2 loss: 0.123352]  [sq d1 d2: 0.000110]  [num0: 12.000000] [num1 52.000000]
[Epoch 193/500] [Batch 420/676] [D loss: -0.007140] [G loss: -0.183834] [d1 loss: 0.043492] [d2 loss: 0.036983]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 193/500] [Batch 440/676] [D loss: -0.013585] [G loss: -0.196131] [d1 loss: 0.145809] [d2 loss: 0.122231]  [sq d1 d2: 0.000556]  [num0: 19.000000] [num1 45.000000]
[Epoch 193/500] [Batch 460/676] [D loss: 0.004228] [G loss: -0.174485] [d1 loss: 0.129049] [d2 loss: 0.160123]  [sq d1 d2: 0.000966]  [num0: 17.000000] [num1 47.000000]
[Epoch 193/500] [Batch 480/676] [D loss: 0.002012] [G loss: -0.134120] [d1 loss: 0.085077] [d2 loss: 0.081570]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 193/500] [Batch 500/676] [D loss: 0.001626] [G loss: -0.122413] [d1 loss: 0.107846] [d2 loss: 0.100134]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 520/676] [D loss: -0.004316] [G loss: -0.094302] [d1 loss: 0.052594] [d2 loss: 0.054511]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 193/500] [Batch 540/676] [D loss: -0.030785] [G loss: -0.075346] [d1 loss: 0.083808] [d2 loss: 0.086582]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 193/500] [Batch 560/676] [D loss: -0.020603] [G loss: -0.061477] [d1 loss: 0.053742] [d2 loss: 0.042250]  [sq d1 d2: 0.000132]  [num0: 14.000000] [num1 50.000000]
[Epoch 193/500] [Batch 580/676] [D loss: -0.020294] [G loss: -0.006261] [d1 loss: 0.024869] [d2 loss: 0.020004]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 193/500] [Batch 600/676] [D loss: -0.013873] [G loss: 0.013103] [d1 loss: 0.118315] [d2 loss: 0.125866]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 193/500] [Batch 620/676] [D loss: -0.027278] [G loss: 0.036556] [d1 loss: 0.070333] [d2 loss: 0.065369]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 193/500] [Batch 640/676] [D loss: -0.030634] [G loss: 0.032391] [d1 loss: 0.045862] [d2 loss: 0.035802]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 193/500] [Batch 660/676] [D loss: -0.003410] [G loss: 0.060823] [d1 loss: 0.191037] [d2 loss: 0.189799]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 194/500] [Batch 0/676] [D loss: -0.008136] [G loss: 0.061387] [d1 loss: 0.062511] [d2 loss: 0.065173]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 20/676] [D loss: -0.005982] [G loss: 0.081300] [d1 loss: 0.036969] [d2 loss: 0.034119]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 194/500] [Batch 40/676] [D loss: -0.008251] [G loss: 0.053278] [d1 loss: 0.078555] [d2 loss: 0.087920]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 194/500] [Batch 60/676] [D loss: 0.000106] [G loss: 0.038882] [d1 loss: 0.071223] [d2 loss: 0.062875]  [sq d1 d2: 0.000070]  [num0: 21.000000] [num1 43.000000]
[Epoch 194/500] [Batch 80/676] [D loss: -0.015279] [G loss: 0.054864] [d1 loss: 0.133257] [d2 loss: 0.121077]  [sq d1 d2: 0.000148]  [num0: 18.000000] [num1 46.000000]
[Epoch 194/500] [Batch 100/676] [D loss: -0.003303] [G loss: 0.076192] [d1 loss: 0.075208] [d2 loss: 0.064656]  [sq d1 d2: 0.000111]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 120/676] [D loss: -0.016101] [G loss: 0.030084] [d1 loss: 0.098333] [d2 loss: 0.087745]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 140/676] [D loss: -0.023911] [G loss: 0.009821] [d1 loss: 0.061282] [d2 loss: 0.071194]  [sq d1 d2: 0.000098]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 160/676] [D loss: -0.012728] [G loss: -0.061306] [d1 loss: 0.081047] [d2 loss: 0.078131]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 194/500] [Batch 180/676] [D loss: -0.029849] [G loss: -0.084951] [d1 loss: 0.057425] [d2 loss: 0.061846]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 194/500] [Batch 200/676] [D loss: 0.006222] [G loss: -0.113316] [d1 loss: 0.056213] [d2 loss: 0.047288]  [sq d1 d2: 0.000080]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 220/676] [D loss: -0.020864] [G loss: -0.116678] [d1 loss: 0.039598] [d2 loss: 0.041667]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 194/500] [Batch 240/676] [D loss: -0.003481] [G loss: -0.138798] [d1 loss: 0.078686] [d2 loss: 0.071387]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 194/500] [Batch 260/676] [D loss: -0.005687] [G loss: -0.105176] [d1 loss: 0.073370] [d2 loss: 0.077779]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 280/676] [D loss: -0.012041] [G loss: -0.098501] [d1 loss: 0.113307] [d2 loss: 0.096917]  [sq d1 d2: 0.000269]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 300/676] [D loss: 0.000128] [G loss: -0.082163] [d1 loss: 0.103696] [d2 loss: 0.122004]  [sq d1 d2: 0.000335]  [num0: 19.000000] [num1 45.000000]
[Epoch 194/500] [Batch 320/676] [D loss: -0.006635] [G loss: -0.064085] [d1 loss: 0.081891] [d2 loss: 0.054595]  [sq d1 d2: 0.000745]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 340/676] [D loss: 0.004310] [G loss: -0.058007] [d1 loss: 0.019950] [d2 loss: 0.021473]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 360/676] [D loss: -0.014672] [G loss: -0.013381] [d1 loss: 0.052960] [d2 loss: 0.086886]  [sq d1 d2: 0.001151]  [num0: 19.000000] [num1 45.000000]
[Epoch 194/500] [Batch 380/676] [D loss: 0.000183] [G loss: 0.010023] [d1 loss: 0.116206] [d2 loss: 0.106628]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 400/676] [D loss: -0.027747] [G loss: 0.019961] [d1 loss: 0.088318] [d2 loss: 0.095715]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 420/676] [D loss: -0.005787] [G loss: 0.043072] [d1 loss: 0.105088] [d2 loss: 0.100695]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]

[Epoch 194/500] [Batch 440/676] [D loss: -0.018452] [G loss: 0.031463] [d1 loss: 0.107146] [d2 loss: 0.094498]  [sq d1 d2: 0.000160]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 460/676] [D loss: -0.017455] [G loss: 0.001051] [d1 loss: 0.052735] [d2 loss: 0.052939]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 480/676] [D loss: -0.036125] [G loss: 0.000645] [d1 loss: 0.062402] [d2 loss: 0.067075]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 500/676] [D loss: -0.010213] [G loss: 0.054727] [d1 loss: 0.072386] [d2 loss: 0.075627]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 194/500] [Batch 520/676] [D loss: -0.001064] [G loss: 0.024275] [d1 loss: 0.071512] [d2 loss: 0.069527]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 194/500] [Batch 540/676] [D loss: -0.015644] [G loss: 0.025886] [d1 loss: 0.032483] [d2 loss: 0.038267]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 194/500] [Batch 560/676] [D loss: -0.001107] [G loss: 0.026446] [d1 loss: 0.084592] [d2 loss: 0.062485]  [sq d1 d2: 0.000489]  [num0: 19.000000] [num1 45.000000]
[Epoch 194/500] [Batch 580/676] [D loss: 0.020896] [G loss: -0.000032] [d1 loss: 0.055681] [d2 loss: 0.068802]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 600/676] [D loss: -0.035211] [G loss: -0.011113] [d1 loss: 0.088752] [d2 loss: 0.075881]  [sq d1 d2: 0.000166]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 620/676] [D loss: -0.012912] [G loss: 0.009821] [d1 loss: 0.089541] [d2 loss: 0.083808]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 194/500] [Batch 640/676] [D loss: -0.008456] [G loss: 0.039767] [d1 loss: 0.068108] [d2 loss: 0.047243]  [sq d1 d2: 0.000435]  [num0: 16.000000] [num1 48.000000]
[Epoch 194/500] [Batch 660/676] [D loss: -0.016918] [G loss: 0.023996] [d1 loss: 0.057132] [d2 loss: 0.063417]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 195/500] [Batch 0/676] [D loss: 0.001847] [G loss: 0.015244] [d1 loss: 0.099052] [d2 loss: 0.104382]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 20/676] [D loss: -0.029867] [G loss: 0.043379] [d1 loss: 0.056731] [d2 loss: 0.050220]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 195/500] [Batch 40/676] [D loss: 0.000537] [G loss: 0.016082] [d1 loss: 0.071247] [d2 loss: 0.073092]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 195/500] [Batch 60/676] [D loss: -0.008931] [G loss: -0.001462] [d1 loss: 0.087731] [d2 loss: 0.073086]  [sq d1 d2: 0.000214]  [num0: 18.000000] [num1 46.000000]
[Epoch 195/500] [Batch 80/676] [D loss: 0.001836] [G loss: -0.001299] [d1 loss: 0.153738] [d2 loss: 0.155141]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 195/500] [Batch 100/676] [D loss: -0.015224] [G loss: 0.017731] [d1 loss: 0.037976] [d2 loss: 0.032628]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 195/500] [Batch 120/676] [D loss: -0.021223] [G loss: 0.033819] [d1 loss: 0.042872] [d2 loss: 0.042428]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 140/676] [D loss: -0.029729] [G loss: 0.048213] [d1 loss: 0.119632] [d2 loss: 0.138519]  [sq d1 d2: 0.000357]  [num0: 12.000000] [num1 52.000000]
[Epoch 195/500] [Batch 160/676] [D loss: -0.030199] [G loss: 0.035356] [d1 loss: 0.119326] [d2 loss: 0.119690]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 180/676] [D loss: -0.011162] [G loss: 0.000736] [d1 loss: 0.124117] [d2 loss: 0.091829]  [sq d1 d2: 0.001043]  [num0: 20.000000] [num1 44.000000]
[Epoch 195/500] [Batch 200/676] [D loss: -0.007204] [G loss: -0.016980] [d1 loss: 0.155149] [d2 loss: 0.163404]  [sq d1 d2: 0.000068]  [num0: 21.000000] [num1 43.000000]
[Epoch 195/500] [Batch 220/676] [D loss: -0.024493] [G loss: -0.057107] [d1 loss: 0.057741] [d2 loss: 0.059011]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 240/676] [D loss: -0.004098] [G loss: -0.075395] [d1 loss: 0.116279] [d2 loss: 0.099691]  [sq d1 d2: 0.000275]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 260/676] [D loss: -0.008688] [G loss: -0.074665] [d1 loss: 0.103248] [d2 loss: 0.120701]  [sq d1 d2: 0.000305]  [num0: 14.000000] [num1 50.000000]
[Epoch 195/500] [Batch 280/676] [D loss: -0.018178] [G loss: -0.088347] [d1 loss: 0.032850] [d2 loss: 0.029410]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 195/500] [Batch 300/676] [D loss: 0.005093] [G loss: -0.078871] [d1 loss: 0.042234] [d2 loss: 0.047339]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 195/500] [Batch 320/676] [D loss: -0.010583] [G loss: -0.107051] [d1 loss: 0.103122] [d2 loss: 0.057449]  [sq d1 d2: 0.002086]  [num0: 14.000000] [num1 50.000000]
[Epoch 195/500] [Batch 340/676] [D loss: -0.019879] [G loss: -0.092388] [d1 loss: 0.056567] [d2 loss: 0.072591]  [sq d1 d2: 0.000257]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 360/676] [D loss: -0.009174] [G loss: -0.123887] [d1 loss: 0.090233] [d2 loss: 0.098546]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 195/500] [Batch 380/676] [D loss: -0.022306] [G loss: -0.152802] [d1 loss: 0.057524] [d2 loss: 0.071691]  [sq d1 d2: 0.000201]  [num0: 13.000000] [num1 51.000000]
[Epoch 195/500] [Batch 400/676] [D loss: -0.024660] [G loss: -0.149982] [d1 loss: 0.112031] [d2 loss: 0.093264]  [sq d1 d2: 0.000352]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 420/676] [D loss: -0.011850] [G loss: -0.154129] [d1 loss: 0.038048] [d2 loss: 0.030560]  [sq d1 d2: 0.000056]  [num0: 13.000000] [num1 51.000000]
[Epoch 195/500] [Batch 440/676] [D loss: 0.001628] [G loss: -0.101612] [d1 loss: 0.101635] [d2 loss: 0.094626]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 460/676] [D loss: 0.003083] [G loss: -0.110173] [d1 loss: 0.084112] [d2 loss: 0.076942]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 195/500] [Batch 480/676] [D loss: -0.001004] [G loss: -0.079591] [d1 loss: 0.050235] [d2 loss: 0.049392]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 195/500] [Batch 500/676] [D loss: 0.002162] [G loss: -0.025804] [d1 loss: 0.049745] [d2 loss: 0.048062]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 195/500] [Batch 520/676] [D loss: -0.015746] [G loss: -0.009982] [d1 loss: 0.115328] [d2 loss: 0.100819]  [sq d1 d2: 0.000211]  [num0: 18.000000] [num1 46.000000]
[Epoch 195/500] [Batch 540/676] [D loss: -0.008720] [G loss: -0.015303] [d1 loss: 0.069423] [d2 loss: 0.065562]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 195/500] [Batch 560/676] [D loss: -0.022680] [G loss: 0.038863] [d1 loss: 0.055070] [d2 loss: 0.061229]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 195/500] [Batch 580/676] [D loss: -0.010821] [G loss: 0.044750] [d1 loss: 0.073283] [d2 loss: 0.062540]  [sq d1 d2: 0.000115]  [num0: 15.000000] [num1 49.000000]
[Epoch 195/500] [Batch 600/676] [D loss: -0.025162] [G loss: 0.058627] [d1 loss: 0.051954] [d2 loss: 0.048744]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 195/500] [Batch 620/676] [D loss: -0.032080] [G loss: 0.046093] [d1 loss: 0.145976] [d2 loss: 0.120346]  [sq d1 d2: 0.000657]  [num0: 10.000000] [num1 54.000000]
[Epoch 195/500] [Batch 640/676] [D loss: -0.021854] [G loss: 0.030312] [d1 loss: 0.115216] [d2 loss: 0.111508]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 195/500] [Batch 660/676] [D loss: -0.013567] [G loss: 0.021049] [d1 loss: 0.089738] [d2 loss: 0.111444]  [sq d1 d2: 0.000471]  [num0: 23.000000] [num1 41.000000]
[Epoch 196/500] [Batch 0/676] [D loss: -0.038412] [G loss: 0.005366] [d1 loss: 0.019051] [d2 loss: 0.018919]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 20/676] [D loss: -0.026744] [G loss: 0.040359] [d1 loss: 0.107030] [d2 loss: 0.116604]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 40/676] [D loss: 0.005143] [G loss: 0.004139] [d1 loss: 0.073269] [d2 loss: 0.061498]  [sq d1 d2: 0.000139]  [num0: 11.000000] [num1 53.000000]
[Epoch 196/500] [Batch 60/676] [D loss: 0.006864] [G loss: -0.048747] [d1 loss: 0.038938] [d2 loss: 0.033507]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 196/500] [Batch 80/676] [D loss: -0.013827] [G loss: -0.068516] [d1 loss: 0.056390] [d2 loss: 0.052400]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 100/676] [D loss: -0.020506] [G loss: -0.067724] [d1 loss: 0.106848] [d2 loss: 0.086476]  [sq d1 d2: 0.000415]  [num0: 18.000000] [num1 46.000000]

[Epoch 196/500] [Batch 120/676] [D loss: -0.023148] [G loss: -0.092953] [d1 loss: 0.066064] [d2 loss: 0.077350]  [sq d1 d2: 0.000127]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 140/676] [D loss: -0.020277] [G loss: -0.144917] [d1 loss: 0.053702] [d2 loss: 0.040901]  [sq d1 d2: 0.000164]  [num0: 16.000000] [num1 48.000000]
[Epoch 196/500] [Batch 160/676] [D loss: -0.022668] [G loss: -0.191653] [d1 loss: 0.039895] [d2 loss: 0.043788]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 180/676] [D loss: -0.008680] [G loss: -0.181990] [d1 loss: 0.048080] [d2 loss: 0.053301]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 196/500] [Batch 200/676] [D loss: -0.019501] [G loss: -0.154470] [d1 loss: 0.062443] [d2 loss: 0.067281]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 196/500] [Batch 220/676] [D loss: -0.009338] [G loss: -0.162757] [d1 loss: 0.091132] [d2 loss: 0.096394]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 196/500] [Batch 240/676] [D loss: -0.027873] [G loss: -0.143778] [d1 loss: 0.109188] [d2 loss: 0.092882]  [sq d1 d2: 0.000266]  [num0: 16.000000] [num1 48.000000]
[Epoch 196/500] [Batch 260/676] [D loss: -0.002422] [G loss: -0.122242] [d1 loss: 0.053179] [d2 loss: 0.047295]  [sq d1 d2: 0.000035]  [num0: 11.000000] [num1 53.000000]
[Epoch 196/500] [Batch 280/676] [D loss: 0.012914] [G loss: -0.065279] [d1 loss: 0.078371] [d2 loss: 0.066346]  [sq d1 d2: 0.000145]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 300/676] [D loss: -0.021172] [G loss: -0.061248] [d1 loss: 0.106831] [d2 loss: 0.092924]  [sq d1 d2: 0.000193]  [num0: 15.000000] [num1 49.000000]
[Epoch 196/500] [Batch 320/676] [D loss: -0.020251] [G loss: -0.013239] [d1 loss: 0.074144] [d2 loss: 0.080219]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 196/500] [Batch 340/676] [D loss: -0.023938] [G loss: -0.022102] [d1 loss: 0.108905] [d2 loss: 0.128868]  [sq d1 d2: 0.000399]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 360/676] [D loss: -0.017684] [G loss: 0.012599] [d1 loss: 0.068702] [d2 loss: 0.075747]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 196/500] [Batch 380/676] [D loss: -0.046433] [G loss: 0.049210] [d1 loss: 0.098735] [d2 loss: 0.107978]  [sq d1 d2: 0.000085]  [num0: 10.000000] [num1 54.000000]
[Epoch 196/500] [Batch 400/676] [D loss: -0.011501] [G loss: 0.063457] [d1 loss: 0.039564] [d2 loss: 0.045904]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 196/500] [Batch 420/676] [D loss: -0.009515] [G loss: 0.052967] [d1 loss: 0.122525] [d2 loss: 0.098852]  [sq d1 d2: 0.000560]  [num0: 12.000000] [num1 52.000000]
[Epoch 196/500] [Batch 440/676] [D loss: -0.017642] [G loss: 0.042111] [d1 loss: 0.111282] [d2 loss: 0.122205]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 460/676] [D loss: -0.028370] [G loss: 0.067229] [d1 loss: 0.028791] [d2 loss: 0.035552]  [sq d1 d2: 0.000046]  [num0: 13.000000] [num1 51.000000]
[Epoch 196/500] [Batch 480/676] [D loss: -0.012273] [G loss: 0.075900] [d1 loss: 0.056200] [d2 loss: 0.042976]  [sq d1 d2: 0.000175]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 500/676] [D loss: -0.003999] [G loss: -0.007078] [d1 loss: 0.075561] [d2 loss: 0.075577]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 196/500] [Batch 520/676] [D loss: -0.005938] [G loss: -0.034111] [d1 loss: 0.168004] [d2 loss: 0.143108]  [sq d1 d2: 0.000620]  [num0: 20.000000] [num1 44.000000]
[Epoch 196/500] [Batch 540/676] [D loss: -0.015952] [G loss: -0.093957] [d1 loss: 0.148106] [d2 loss: 0.124433]  [sq d1 d2: 0.000560]  [num0: 16.000000] [num1 48.000000]
[Epoch 196/500] [Batch 560/676] [D loss: -0.019073] [G loss: -0.114864] [d1 loss: 0.056208] [d2 loss: 0.058987]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 196/500] [Batch 580/676] [D loss: -0.023474] [G loss: -0.177478] [d1 loss: 0.065096] [d2 loss: 0.070499]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 600/676] [D loss: -0.014837] [G loss: -0.183863] [d1 loss: 0.142417] [d2 loss: 0.129220]  [sq d1 d2: 0.000174]  [num0: 16.000000] [num1 48.000000]
[Epoch 196/500] [Batch 620/676] [D loss: -0.030407] [G loss: -0.174427] [d1 loss: 0.059371] [d2 loss: 0.061225]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 196/500] [Batch 640/676] [D loss: -0.008258] [G loss: -0.220537] [d1 loss: 0.132708] [d2 loss: 0.095503]  [sq d1 d2: 0.001384]  [num0: 17.000000] [num1 47.000000]
[Epoch 196/500] [Batch 660/676] [D loss: -0.014619] [G loss: -0.232593] [d1 loss: 0.236262] [d2 loss: 0.214105]  [sq d1 d2: 0.000491]  [num0: 18.000000] [num1 46.000000]
[Epoch 197/500] [Batch 0/676] [D loss: -0.014801] [G loss: -0.217305] [d1 loss: 0.064336] [d2 loss: 0.061913]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 20/676] [D loss: -0.021027] [G loss: -0.238589] [d1 loss: 0.073971] [d2 loss: 0.056176]  [sq d1 d2: 0.000317]  [num0: 18.000000] [num1 46.000000]
[Epoch 197/500] [Batch 40/676] [D loss: -0.031669] [G loss: -0.221705] [d1 loss: 0.006830] [d2 loss: 0.005277]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 60/676] [D loss: -0.003249] [G loss: -0.187342] [d1 loss: 0.055053] [d2 loss: 0.045011]  [sq d1 d2: 0.000101]  [num0: 20.000000] [num1 44.000000]
[Epoch 197/500] [Batch 80/676] [D loss: -0.005467] [G loss: -0.147401] [d1 loss: 0.055775] [d2 loss: 0.058498]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 197/500] [Batch 100/676] [D loss: -0.005010] [G loss: -0.125540] [d1 loss: 0.029209] [d2 loss: 0.027671]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 197/500] [Batch 120/676] [D loss: -0.009740] [G loss: -0.131210] [d1 loss: 0.082593] [d2 loss: 0.075753]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 197/500] [Batch 140/676] [D loss: -0.008603] [G loss: -0.100145] [d1 loss: 0.033956] [d2 loss: 0.034764]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 197/500] [Batch 160/676] [D loss: -0.022618] [G loss: -0.048821] [d1 loss: 0.084576] [d2 loss: 0.081508]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 197/500] [Batch 180/676] [D loss: -0.023083] [G loss: 0.009005] [d1 loss: 0.058922] [d2 loss: 0.067805]  [sq d1 d2: 0.000079]  [num0: 19.000000] [num1 45.000000]
[Epoch 197/500] [Batch 200/676] [D loss: -0.030932] [G loss: 0.026107] [d1 loss: 0.052586] [d2 loss: 0.064233]  [sq d1 d2: 0.000136]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 220/676] [D loss: -0.043178] [G loss: 0.022097] [d1 loss: 0.035384] [d2 loss: 0.030271]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 197/500] [Batch 240/676] [D loss: -0.023586] [G loss: 0.006644] [d1 loss: 0.115288] [d2 loss: 0.104769]  [sq d1 d2: 0.000111]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 260/676] [D loss: -0.016926] [G loss: 0.010284] [d1 loss: 0.100326] [d2 loss: 0.075312]  [sq d1 d2: 0.000626]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 280/676] [D loss: -0.004365] [G loss: -0.004075] [d1 loss: 0.104044] [d2 loss: 0.098015]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 197/500] [Batch 300/676] [D loss: -0.012910] [G loss: 0.006168] [d1 loss: 0.167002] [d2 loss: 0.155918]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 320/676] [D loss: -0.002611] [G loss: -0.034875] [d1 loss: 0.027725] [d2 loss: 0.024534]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 340/676] [D loss: -0.010534] [G loss: -0.025975] [d1 loss: 0.123538] [d2 loss: 0.116780]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 360/676] [D loss: -0.004383] [G loss: -0.044634] [d1 loss: 0.103537] [d2 loss: 0.096711]  [sq d1 d2: 0.000047]  [num0: 19.000000] [num1 45.000000]
[Epoch 197/500] [Batch 380/676] [D loss: -0.022559] [G loss: -0.044528] [d1 loss: 0.102314] [d2 loss: 0.093010]  [sq d1 d2: 0.000087]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 400/676] [D loss: -0.003274] [G loss: -0.117816] [d1 loss: 0.067817] [d2 loss: 0.064991]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 420/676] [D loss: -0.015441] [G loss: -0.113394] [d1 loss: 0.018099] [d2 loss: 0.014946]  [sq d1 d2: 0.000010]  [num0: 21.000000] [num1 43.000000]
[Epoch 197/500] [Batch 440/676] [D loss: -0.000329] [G loss: -0.124171] [d1 loss: 0.096243] [d2 loss: 0.082747]  [sq d1 d2: 0.000182]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 460/676] [D loss: -0.035030] [G loss: -0.144541] [d1 loss: 0.034613] [d2 loss: 0.058305]  [sq d1 d2: 0.000561]  [num0: 18.000000] [num1 46.000000]

[Epoch 197/500] [Batch 480/676] [D loss: -0.009418] [G loss: -0.159982] [d1 loss: 0.128606] [d2 loss: 0.138628]  [sq d1 d2: 0.000100]  [num0: 17.000000] [num1 47.000000]
[Epoch 197/500] [Batch 500/676] [D loss: 0.014636] [G loss: -0.140298] [d1 loss: 0.085422] [d2 loss: 0.078463]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 520/676] [D loss: 0.004314] [G loss: -0.170192] [d1 loss: 0.066191] [d2 loss: 0.065186]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 197/500] [Batch 540/676] [D loss: 0.004038] [G loss: -0.158514] [d1 loss: 0.087132] [d2 loss: 0.069247]  [sq d1 d2: 0.000320]  [num0: 15.000000] [num1 49.000000]
[Epoch 197/500] [Batch 560/676] [D loss: 0.010530] [G loss: -0.178580] [d1 loss: 0.103124] [d2 loss: 0.095489]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 197/500] [Batch 580/676] [D loss: -0.007692] [G loss: -0.157896] [d1 loss: 0.090630] [d2 loss: 0.074357]  [sq d1 d2: 0.000265]  [num0: 19.000000] [num1 45.000000]
[Epoch 197/500] [Batch 600/676] [D loss: 0.000280] [G loss: -0.129176] [d1 loss: 0.101111] [d2 loss: 0.110369]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 197/500] [Batch 620/676] [D loss: -0.024572] [G loss: -0.100448] [d1 loss: 0.129947] [d2 loss: 0.136563]  [sq d1 d2: 0.000044]  [num0: 13.000000] [num1 51.000000]
[Epoch 197/500] [Batch 640/676] [D loss: -0.026253] [G loss: -0.105600] [d1 loss: 0.049995] [d2 loss: 0.043721]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 197/500] [Batch 660/676] [D loss: -0.031440] [G loss: -0.093101] [d1 loss: 0.121050] [d2 loss: 0.112249]  [sq d1 d2: 0.000077]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 0/676] [D loss: 0.002036] [G loss: -0.097770] [d1 loss: 0.025774] [d2 loss: 0.029021]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 20/676] [D loss: -0.040397] [G loss: -0.110110] [d1 loss: 0.114745] [d2 loss: 0.105750]  [sq d1 d2: 0.000081]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 40/676] [D loss: -0.022384] [G loss: -0.109081] [d1 loss: 0.107623] [d2 loss: 0.091562]  [sq d1 d2: 0.000258]  [num0: 16.000000] [num1 48.000000]
[Epoch 198/500] [Batch 60/676] [D loss: -0.016327] [G loss: -0.127377] [d1 loss: 0.024525] [d2 loss: 0.024552]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 198/500] [Batch 80/676] [D loss: -0.012480] [G loss: -0.102722] [d1 loss: 0.063126] [d2 loss: 0.065136]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 100/676] [D loss: -0.017890] [G loss: -0.116310] [d1 loss: 0.064151] [d2 loss: 0.068249]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 120/676] [D loss: -0.004874] [G loss: -0.079971] [d1 loss: 0.062035] [d2 loss: 0.060403]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 198/500] [Batch 140/676] [D loss: 0.017180] [G loss: -0.074140] [d1 loss: 0.086822] [d2 loss: 0.090695]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 160/676] [D loss: -0.005200] [G loss: -0.089860] [d1 loss: 0.070312] [d2 loss: 0.075443]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 198/500] [Batch 180/676] [D loss: -0.031864] [G loss: -0.112774] [d1 loss: 0.032937] [d2 loss: 0.034097]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 198/500] [Batch 200/676] [D loss: -0.005832] [G loss: -0.120938] [d1 loss: 0.086225] [d2 loss: 0.065741]  [sq d1 d2: 0.000420]  [num0: 20.000000] [num1 44.000000]
[Epoch 198/500] [Batch 220/676] [D loss: -0.029885] [G loss: -0.099804] [d1 loss: 0.051643] [d2 loss: 0.046685]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 198/500] [Batch 240/676] [D loss: -0.026844] [G loss: -0.169422] [d1 loss: 0.092523] [d2 loss: 0.081780]  [sq d1 d2: 0.000115]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 260/676] [D loss: -0.043312] [G loss: -0.178882] [d1 loss: 0.054690] [d2 loss: 0.048108]  [sq d1 d2: 0.000043]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 280/676] [D loss: 0.001277] [G loss: -0.262584] [d1 loss: 0.084163] [d2 loss: 0.085393]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 198/500] [Batch 300/676] [D loss: -0.020885] [G loss: -0.255320] [d1 loss: 0.052111] [d2 loss: 0.059530]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 198/500] [Batch 320/676] [D loss: 0.007402] [G loss: -0.254056] [d1 loss: 0.038329] [d2 loss: 0.037342]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 198/500] [Batch 340/676] [D loss: 0.009484] [G loss: -0.243203] [d1 loss: 0.063335] [d2 loss: 0.050048]  [sq d1 d2: 0.000177]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 360/676] [D loss: 0.003551] [G loss: -0.182523] [d1 loss: 0.085167] [d2 loss: 0.084761]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 380/676] [D loss: -0.000377] [G loss: -0.175723] [d1 loss: 0.059140] [d2 loss: 0.083661]  [sq d1 d2: 0.000601]  [num0: 18.000000] [num1 46.000000]
[Epoch 198/500] [Batch 400/676] [D loss: -0.001623] [G loss: -0.160506] [d1 loss: 0.068707] [d2 loss: 0.074128]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 420/676] [D loss: -0.007820] [G loss: -0.155275] [d1 loss: 0.091036] [d2 loss: 0.109336]  [sq d1 d2: 0.000335]  [num0: 19.000000] [num1 45.000000]
[Epoch 198/500] [Batch 440/676] [D loss: -0.017996] [G loss: -0.155223] [d1 loss: 0.122864] [d2 loss: 0.124964]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 198/500] [Batch 460/676] [D loss: -0.020462] [G loss: -0.133854] [d1 loss: 0.048434] [d2 loss: 0.045039]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 480/676] [D loss: -0.017940] [G loss: -0.104919] [d1 loss: 0.138877] [d2 loss: 0.148790]  [sq d1 d2: 0.000098]  [num0: 19.000000] [num1 45.000000]
[Epoch 198/500] [Batch 500/676] [D loss: -0.039510] [G loss: -0.072599] [d1 loss: 0.064338] [d2 loss: 0.050877]  [sq d1 d2: 0.000181]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 520/676] [D loss: -0.013807] [G loss: -0.093551] [d1 loss: 0.064169] [d2 loss: 0.079907]  [sq d1 d2: 0.000248]  [num0: 18.000000] [num1 46.000000]
[Epoch 198/500] [Batch 540/676] [D loss: -0.002318] [G loss: -0.041577] [d1 loss: 0.076225] [d2 loss: 0.095321]  [sq d1 d2: 0.000365]  [num0: 15.000000] [num1 49.000000]
[Epoch 198/500] [Batch 560/676] [D loss: -0.020181] [G loss: -0.019574] [d1 loss: 0.083592] [d2 loss: 0.097468]  [sq d1 d2: 0.000193]  [num0: 19.000000] [num1 45.000000]
[Epoch 198/500] [Batch 580/676] [D loss: -0.014594] [G loss: 0.060778] [d1 loss: 0.082322] [d2 loss: 0.076368]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 198/500] [Batch 600/676] [D loss: 0.002812] [G loss: 0.057829] [d1 loss: 0.155179] [d2 loss: 0.145917]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 198/500] [Batch 620/676] [D loss: 0.000526] [G loss: 0.081717] [d1 loss: 0.036777] [d2 loss: 0.037788]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 198/500] [Batch 640/676] [D loss: -0.009706] [G loss: 0.097141] [d1 loss: 0.169439] [d2 loss: 0.141489]  [sq d1 d2: 0.000781]  [num0: 12.000000] [num1 52.000000]
[Epoch 198/500] [Batch 660/676] [D loss: -0.016276] [G loss: 0.117238] [d1 loss: 0.115535] [d2 loss: 0.103209]  [sq d1 d2: 0.000152]  [num0: 11.000000] [num1 53.000000]
[Epoch 199/500] [Batch 0/676] [D loss: -0.012621] [G loss: 0.129745] [d1 loss: 0.038712] [d2 loss: 0.051154]  [sq d1 d2: 0.000155]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 20/676] [D loss: -0.026321] [G loss: 0.104431] [d1 loss: 0.135728] [d2 loss: 0.130439]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 40/676] [D loss: -0.026144] [G loss: 0.106230] [d1 loss: 0.031245] [d2 loss: 0.046255]  [sq d1 d2: 0.000225]  [num0: 13.000000] [num1 51.000000]
[Epoch 199/500] [Batch 60/676] [D loss: -0.016498] [G loss: 0.073897] [d1 loss: 0.037292] [d2 loss: 0.029711]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 199/500] [Batch 80/676] [D loss: -0.029274] [G loss: 0.056983] [d1 loss: 0.065174] [d2 loss: 0.066977]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 199/500] [Batch 100/676] [D loss: -0.014485] [G loss: 0.041357] [d1 loss: 0.062575] [d2 loss: 0.069711]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 199/500] [Batch 120/676] [D loss: -0.027167] [G loss: 0.016472] [d1 loss: 0.158166] [d2 loss: 0.128116]  [sq d1 d2: 0.000903]  [num0: 15.000000] [num1 49.000000]
[Epoch 199/500] [Batch 140/676] [D loss: 0.035424] [G loss: -0.019751] [d1 loss: 0.142281] [d2 loss: 0.148567]  [sq d1 d2: 0.000040]  [num0: 21.000000] [num1 43.000000]

[Epoch 199/500] [Batch 160/676] [D loss: 0.007911] [G loss: -0.033912] [d1 loss: 0.090176] [d2 loss: 0.078125]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 180/676] [D loss: -0.008690] [G loss: -0.048614] [d1 loss: 0.074781] [d2 loss: 0.072542]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 200/676] [D loss: -0.005913] [G loss: -0.089366] [d1 loss: 0.075230] [d2 loss: 0.074297]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 199/500] [Batch 220/676] [D loss: -0.010726] [G loss: -0.106555] [d1 loss: 0.040203] [d2 loss: 0.036493]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 199/500] [Batch 240/676] [D loss: -0.004322] [G loss: -0.098207] [d1 loss: 0.027826] [d2 loss: 0.041207]  [sq d1 d2: 0.000179]  [num0: 15.000000] [num1 49.000000]
[Epoch 199/500] [Batch 260/676] [D loss: -0.015226] [G loss: -0.133232] [d1 loss: 0.035527] [d2 loss: 0.033541]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 280/676] [D loss: -0.025785] [G loss: -0.136133] [d1 loss: 0.076015] [d2 loss: 0.070354]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 300/676] [D loss: -0.010178] [G loss: -0.140995] [d1 loss: 0.061749] [d2 loss: 0.056425]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 199/500] [Batch 320/676] [D loss: -0.016495] [G loss: -0.149226] [d1 loss: 0.110254] [d2 loss: 0.162712]  [sq d1 d2: 0.002752]  [num0: 15.000000] [num1 49.000000]
[Epoch 199/500] [Batch 340/676] [D loss: -0.031422] [G loss: -0.163267] [d1 loss: 0.050061] [d2 loss: 0.046237]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 199/500] [Batch 360/676] [D loss: -0.012461] [G loss: -0.143310] [d1 loss: 0.095107] [d2 loss: 0.099970]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 380/676] [D loss: -0.010103] [G loss: -0.118322] [d1 loss: 0.119150] [d2 loss: 0.138764]  [sq d1 d2: 0.000385]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 400/676] [D loss: -0.003983] [G loss: -0.087580] [d1 loss: 0.065623] [d2 loss: 0.050832]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 420/676] [D loss: -0.006063] [G loss: -0.082428] [d1 loss: 0.082524] [d2 loss: 0.089385]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 440/676] [D loss: -0.003630] [G loss: -0.067954] [d1 loss: 0.142274] [d2 loss: 0.135293]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 199/500] [Batch 460/676] [D loss: -0.008922] [G loss: -0.041251] [d1 loss: 0.061249] [d2 loss: 0.047393]  [sq d1 d2: 0.000192]  [num0: 14.000000] [num1 50.000000]
[Epoch 199/500] [Batch 480/676] [D loss: -0.009433] [G loss: 0.006955] [d1 loss: 0.088080] [d2 loss: 0.113748]  [sq d1 d2: 0.000659]  [num0: 18.000000] [num1 46.000000]
[Epoch 199/500] [Batch 500/676] [D loss: -0.014936] [G loss: -0.004956] [d1 loss: 0.048422] [d2 loss: 0.086542]  [sq d1 d2: 0.001453]  [num0: 13.000000] [num1 51.000000]
[Epoch 199/500] [Batch 520/676] [D loss: -0.026072] [G loss: -0.007331] [d1 loss: 0.087525] [d2 loss: 0.084435]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 540/676] [D loss: -0.012665] [G loss: -0.022370] [d1 loss: 0.101364] [d2 loss: 0.078184]  [sq d1 d2: 0.000537]  [num0: 14.000000] [num1 50.000000]
[Epoch 199/500] [Batch 560/676] [D loss: -0.025325] [G loss: -0.059721] [d1 loss: 0.107545] [d2 loss: 0.102874]  [sq d1 d2: 0.000022]  [num0: 21.000000] [num1 43.000000]
[Epoch 199/500] [Batch 580/676] [D loss: -0.017035] [G loss: -0.118239] [d1 loss: 0.067415] [d2 loss: 0.080857]  [sq d1 d2: 0.000181]  [num0: 16.000000] [num1 48.000000]
[Epoch 199/500] [Batch 600/676] [D loss: 0.012399] [G loss: -0.116295] [d1 loss: 0.093126] [d2 loss: 0.116545]  [sq d1 d2: 0.000548]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 620/676] [D loss: -0.008621] [G loss: -0.173519] [d1 loss: 0.070327] [d2 loss: 0.056393]  [sq d1 d2: 0.000194]  [num0: 12.000000] [num1 52.000000]
[Epoch 199/500] [Batch 640/676] [D loss: 0.012535] [G loss: -0.161855] [d1 loss: 0.107810] [d2 loss: 0.116630]  [sq d1 d2: 0.000078]  [num0: 17.000000] [num1 47.000000]
[Epoch 199/500] [Batch 660/676] [D loss: -0.008361] [G loss: -0.158693] [d1 loss: 0.100499] [d2 loss: 0.135848]  [sq d1 d2: 0.001250]  [num0: 16.000000] [num1 48.000000]
[Epoch 200/500] [Batch 0/676] [D loss: -0.015012] [G loss: -0.139263] [d1 loss: 0.175795] [d2 loss: 0.180073]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 20/676] [D loss: -0.017252] [G loss: -0.146337] [d1 loss: 0.073356] [d2 loss: 0.062344]  [sq d1 d2: 0.000121]  [num0: 13.000000] [num1 51.000000]
[Epoch 200/500] [Batch 40/676] [D loss: -0.015466] [G loss: -0.142184] [d1 loss: 0.081107] [d2 loss: 0.086556]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 60/676] [D loss: -0.013618] [G loss: -0.151293] [d1 loss: 0.103517] [d2 loss: 0.101555]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 80/676] [D loss: -0.028362] [G loss: -0.177828] [d1 loss: 0.035768] [d2 loss: 0.033898]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 200/500] [Batch 100/676] [D loss: -0.024859] [G loss: -0.179486] [d1 loss: 0.044981] [d2 loss: 0.043744]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 200/500] [Batch 120/676] [D loss: -0.026643] [G loss: -0.186281] [d1 loss: 0.043759] [d2 loss: 0.041086]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 200/500] [Batch 140/676] [D loss: -0.009945] [G loss: -0.224479] [d1 loss: 0.062972] [d2 loss: 0.055728]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 200/500] [Batch 160/676] [D loss: -0.006428] [G loss: -0.191564] [d1 loss: 0.039199] [d2 loss: 0.040430]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 200/500] [Batch 180/676] [D loss: -0.003962] [G loss: -0.179445] [d1 loss: 0.110754] [d2 loss: 0.107047]  [sq d1 d2: 0.000014]  [num0: 21.000000] [num1 43.000000]
[Epoch 200/500] [Batch 200/676] [D loss: -0.005338] [G loss: -0.138212] [d1 loss: 0.088212] [d2 loss: 0.064966]  [sq d1 d2: 0.000540]  [num0: 20.000000] [num1 44.000000]
[Epoch 200/500] [Batch 220/676] [D loss: -0.000222] [G loss: -0.040822] [d1 loss: 0.103348] [d2 loss: 0.105666]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 240/676] [D loss: -0.015194] [G loss: 0.000542] [d1 loss: 0.090565] [d2 loss: 0.087436]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 200/500] [Batch 260/676] [D loss: -0.014741] [G loss: 0.049906] [d1 loss: 0.055355] [d2 loss: 0.051919]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 200/500] [Batch 280/676] [D loss: -0.013474] [G loss: 0.056135] [d1 loss: 0.076061] [d2 loss: 0.079999]  [sq d1 d2: 0.000016]  [num0: 22.000000] [num1 42.000000]
[Epoch 200/500] [Batch 300/676] [D loss: -0.005515] [G loss: 0.080061] [d1 loss: 0.032922] [d2 loss: 0.032258]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 200/500] [Batch 320/676] [D loss: -0.024036] [G loss: 0.078634] [d1 loss: 0.097536] [d2 loss: 0.068845]  [sq d1 d2: 0.000823]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 340/676] [D loss: -0.039671] [G loss: 0.084360] [d1 loss: 0.043591] [d2 loss: 0.038075]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 200/500] [Batch 360/676] [D loss: -0.021226] [G loss: 0.081373] [d1 loss: 0.103374] [d2 loss: 0.108209]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 380/676] [D loss: -0.012771] [G loss: 0.058384] [d1 loss: 0.077415] [d2 loss: 0.068277]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 400/676] [D loss: -0.003615] [G loss: 0.031941] [d1 loss: 0.065109] [d2 loss: 0.047450]  [sq d1 d2: 0.000312]  [num0: 14.000000] [num1 50.000000]
[Epoch 200/500] [Batch 420/676] [D loss: -0.003599] [G loss: 0.029235] [d1 loss: 0.056516] [d2 loss: 0.053192]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 200/500] [Batch 440/676] [D loss: -0.004539] [G loss: 0.000264] [d1 loss: 0.034408] [d2 loss: 0.030908]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 460/676] [D loss: -0.007392] [G loss: -0.000774] [d1 loss: 0.124701] [d2 loss: 0.107392]  [sq d1 d2: 0.000300]  [num0: 12.000000] [num1 52.000000]
[Epoch 200/500] [Batch 480/676] [D loss: 0.001730] [G loss: -0.028397] [d1 loss: 0.074100] [d2 loss: 0.079662]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 200/500] [Batch 500/676] [D loss: -0.009808] [G loss: -0.036427] [d1 loss: 0.086687] [d2 loss: 0.077430]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]

[Epoch 200/500] [Batch 520/676] [D loss: -0.007199] [G loss: -0.053069] [d1 loss: 0.111291] [d2 loss: 0.090961]  [sq d1 d2: 0.000413]  [num0: 13.000000] [num1 51.000000]
[Epoch 200/500] [Batch 540/676] [D loss: -0.019414] [G loss: -0.034414] [d1 loss: 0.099200] [d2 loss: 0.092161]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 560/676] [D loss: -0.007017] [G loss: -0.051282] [d1 loss: 0.088645] [d2 loss: 0.102988]  [sq d1 d2: 0.000206]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 580/676] [D loss: -0.016160] [G loss: -0.073647] [d1 loss: 0.096370] [d2 loss: 0.055263]  [sq d1 d2: 0.001690]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 600/676] [D loss: -0.011039] [G loss: -0.082787] [d1 loss: 0.054389] [d2 loss: 0.042081]  [sq d1 d2: 0.000151]  [num0: 13.000000] [num1 51.000000]
[Epoch 200/500] [Batch 620/676] [D loss: -0.015569] [G loss: -0.085843] [d1 loss: 0.088501] [d2 loss: 0.129688]  [sq d1 d2: 0.001696]  [num0: 17.000000] [num1 47.000000]
[Epoch 200/500] [Batch 640/676] [D loss: -0.016296] [G loss: -0.067375] [d1 loss: 0.051625] [d2 loss: 0.041135]  [sq d1 d2: 0.000110]  [num0: 15.000000] [num1 49.000000]
[Epoch 200/500] [Batch 660/676] [D loss: -0.007259] [G loss: -0.096974] [d1 loss: 0.058052] [d2 loss: 0.041196]  [sq d1 d2: 0.000284]  [num0: 14.000000] [num1 50.000000]
[Epoch 201/500] [Batch 0/676] [D loss: -0.004023] [G loss: -0.087833] [d1 loss: 0.087805] [d2 loss: 0.074500]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 201/500] [Batch 20/676] [D loss: -0.008044] [G loss: -0.099166] [d1 loss: 0.082272] [d2 loss: 0.060868]  [sq d1 d2: 0.000458]  [num0: 15.000000] [num1 49.000000]
[Epoch 201/500] [Batch 40/676] [D loss: -0.004181] [G loss: -0.067538] [d1 loss: 0.058567] [d2 loss: 0.044037]  [sq d1 d2: 0.000211]  [num0: 13.000000] [num1 51.000000]
[Epoch 201/500] [Batch 60/676] [D loss: -0.006647] [G loss: -0.034297] [d1 loss: 0.044430] [d2 loss: 0.048123]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 201/500] [Batch 80/676] [D loss: -0.015067] [G loss: -0.069073] [d1 loss: 0.054188] [d2 loss: 0.047175]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 201/500] [Batch 100/676] [D loss: -0.009996] [G loss: -0.062818] [d1 loss: 0.006443] [d2 loss: 0.004573]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 201/500] [Batch 120/676] [D loss: -0.015960] [G loss: -0.035862] [d1 loss: 0.087738] [d2 loss: 0.081959]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 201/500] [Batch 140/676] [D loss: -0.017576] [G loss: -0.086588] [d1 loss: 0.035667] [d2 loss: 0.023159]  [sq d1 d2: 0.000156]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 160/676] [D loss: -0.015521] [G loss: -0.057002] [d1 loss: 0.059779] [d2 loss: 0.064715]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 180/676] [D loss: -0.016302] [G loss: -0.083819] [d1 loss: 0.062373] [d2 loss: 0.080372]  [sq d1 d2: 0.000324]  [num0: 15.000000] [num1 49.000000]
[Epoch 201/500] [Batch 200/676] [D loss: -0.014412] [G loss: -0.080648] [d1 loss: 0.041218] [d2 loss: 0.040341]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 201/500] [Batch 220/676] [D loss: -0.003147] [G loss: -0.075765] [d1 loss: 0.125172] [d2 loss: 0.096935]  [sq d1 d2: 0.000797]  [num0: 14.000000] [num1 50.000000]
[Epoch 201/500] [Batch 240/676] [D loss: -0.009379] [G loss: -0.093077] [d1 loss: 0.019245] [d2 loss: 0.014427]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 201/500] [Batch 260/676] [D loss: -0.008259] [G loss: -0.105823] [d1 loss: 0.026874] [d2 loss: 0.032575]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 201/500] [Batch 280/676] [D loss: -0.007175] [G loss: -0.071720] [d1 loss: 0.106700] [d2 loss: 0.082719]  [sq d1 d2: 0.000575]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 300/676] [D loss: -0.007775] [G loss: -0.087586] [d1 loss: 0.099053] [d2 loss: 0.100544]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 201/500] [Batch 320/676] [D loss: -0.009234] [G loss: -0.072100] [d1 loss: 0.084214] [d2 loss: 0.080058]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 201/500] [Batch 340/676] [D loss: -0.012786] [G loss: -0.070097] [d1 loss: 0.098887] [d2 loss: 0.118957]  [sq d1 d2: 0.000403]  [num0: 13.000000] [num1 51.000000]
[Epoch 201/500] [Batch 360/676] [D loss: -0.011487] [G loss: -0.067736] [d1 loss: 0.046285] [d2 loss: 0.042554]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]
[Epoch 201/500] [Batch 380/676] [D loss: -0.019425] [G loss: -0.038817] [d1 loss: 0.074144] [d2 loss: 0.080918]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 201/500] [Batch 400/676] [D loss: -0.018880] [G loss: -0.039562] [d1 loss: 0.085135] [d2 loss: 0.088942]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 420/676] [D loss: -0.022322] [G loss: -0.014081] [d1 loss: 0.143292] [d2 loss: 0.140760]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 201/500] [Batch 440/676] [D loss: 0.005652] [G loss: -0.036273] [d1 loss: 0.039361] [d2 loss: 0.047363]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 460/676] [D loss: -0.020919] [G loss: -0.016213] [d1 loss: 0.118156] [d2 loss: 0.095116]  [sq d1 d2: 0.000531]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 480/676] [D loss: -0.009965] [G loss: 0.007611] [d1 loss: 0.018217] [d2 loss: 0.022461]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 500/676] [D loss: -0.022781] [G loss: 0.016740] [d1 loss: 0.075548] [d2 loss: 0.088058]  [sq d1 d2: 0.000156]  [num0: 17.000000] [num1 47.000000]
[Epoch 201/500] [Batch 520/676] [D loss: -0.009990] [G loss: 0.061664] [d1 loss: 0.103981] [d2 loss: 0.111072]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 201/500] [Batch 540/676] [D loss: -0.004870] [G loss: 0.059268] [d1 loss: 0.085225] [d2 loss: 0.091336]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 560/676] [D loss: -0.012914] [G loss: 0.066283] [d1 loss: 0.132108] [d2 loss: 0.154339]  [sq d1 d2: 0.000494]  [num0: 16.000000] [num1 48.000000]
[Epoch 201/500] [Batch 580/676] [D loss: -0.013852] [G loss: 0.078459] [d1 loss: 0.021653] [d2 loss: 0.026366]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 201/500] [Batch 600/676] [D loss: -0.013448] [G loss: 0.064733] [d1 loss: 0.094890] [d2 loss: 0.105720]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 201/500] [Batch 620/676] [D loss: -0.018225] [G loss: 0.027763] [d1 loss: 0.118888] [d2 loss: 0.125427]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 201/500] [Batch 640/676] [D loss: -0.038880] [G loss: 0.023183] [d1 loss: 0.048558] [d2 loss: 0.050444]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 201/500] [Batch 660/676] [D loss: -0.012119] [G loss: -0.014911] [d1 loss: 0.057464] [d2 loss: 0.049590]  [sq d1 d2: 0.000062]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 0/676] [D loss: -0.021924] [G loss: -0.036126] [d1 loss: 0.072162] [d2 loss: 0.061060]  [sq d1 d2: 0.000123]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 20/676] [D loss: -0.036224] [G loss: -0.060100] [d1 loss: 0.083733] [d2 loss: 0.084470]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 202/500] [Batch 40/676] [D loss: -0.006947] [G loss: -0.090180] [d1 loss: 0.054755] [d2 loss: 0.055167]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 202/500] [Batch 60/676] [D loss: -0.010343] [G loss: -0.095561] [d1 loss: 0.043323] [d2 loss: 0.041949]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 80/676] [D loss: -0.008286] [G loss: -0.119265] [d1 loss: 0.027629] [d2 loss: 0.036928]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 100/676] [D loss: -0.001564] [G loss: -0.102994] [d1 loss: 0.022525] [d2 loss: 0.021231]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 202/500] [Batch 120/676] [D loss: -0.007994] [G loss: -0.132370] [d1 loss: 0.016436] [d2 loss: 0.016564]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 140/676] [D loss: -0.019276] [G loss: -0.107632] [d1 loss: 0.087121] [d2 loss: 0.070586]  [sq d1 d2: 0.000273]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 160/676] [D loss: -0.005602] [G loss: -0.095076] [d1 loss: 0.090728] [d2 loss: 0.101181]  [sq d1 d2: 0.000109]  [num0: 14.000000] [num1 50.000000]

[Epoch 202/500] [Batch 180/676] [D loss: -0.014987] [G loss: -0.068610] [d1 loss: 0.126427] [d2 loss: 0.133197]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 202/500] [Batch 200/676] [D loss: -0.023000] [G loss: -0.055968] [d1 loss: 0.084251] [d2 loss: 0.098435]  [sq d1 d2: 0.000201]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 220/676] [D loss: -0.012658] [G loss: -0.015356] [d1 loss: 0.040720] [d2 loss: 0.037777]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 240/676] [D loss: -0.022093] [G loss: -0.046287] [d1 loss: 0.052937] [d2 loss: 0.048158]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 260/676] [D loss: -0.007633] [G loss: -0.016045] [d1 loss: 0.074055] [d2 loss: 0.062847]  [sq d1 d2: 0.000126]  [num0: 11.000000] [num1 53.000000]
[Epoch 202/500] [Batch 280/676] [D loss: -0.017062] [G loss: 0.014332] [d1 loss: 0.033866] [d2 loss: 0.032877]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 300/676] [D loss: -0.012113] [G loss: 0.059590] [d1 loss: 0.029949] [d2 loss: 0.029172]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 202/500] [Batch 320/676] [D loss: -0.009275] [G loss: 0.075690] [d1 loss: 0.063906] [d2 loss: 0.066186]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 340/676] [D loss: -0.026287] [G loss: 0.105735] [d1 loss: 0.023585] [d2 loss: 0.039156]  [sq d1 d2: 0.000242]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 360/676] [D loss: -0.027774] [G loss: 0.079073] [d1 loss: 0.048829] [d2 loss: 0.047807]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 202/500] [Batch 380/676] [D loss: -0.038736] [G loss: 0.103668] [d1 loss: 0.133344] [d2 loss: 0.113131]  [sq d1 d2: 0.000409]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 400/676] [D loss: -0.034056] [G loss: 0.085976] [d1 loss: 0.025972] [d2 loss: 0.023063]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 420/676] [D loss: -0.016013] [G loss: 0.047015] [d1 loss: 0.086568] [d2 loss: 0.086471]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 202/500] [Batch 440/676] [D loss: -0.008355] [G loss: 0.041783] [d1 loss: 0.041530] [d2 loss: 0.041084]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 460/676] [D loss: -0.001221] [G loss: 0.015519] [d1 loss: 0.025502] [d2 loss: 0.025498]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 202/500] [Batch 480/676] [D loss: -0.031830] [G loss: -0.006269] [d1 loss: 0.107788] [d2 loss: 0.097363]  [sq d1 d2: 0.000109]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 500/676] [D loss: -0.006297] [G loss: -0.039975] [d1 loss: 0.066397] [d2 loss: 0.056380]  [sq d1 d2: 0.000100]  [num0: 17.000000] [num1 47.000000]
[Epoch 202/500] [Batch 520/676] [D loss: -0.012378] [G loss: -0.040278] [d1 loss: 0.020842] [d2 loss: 0.022934]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 540/676] [D loss: -0.012168] [G loss: -0.047239] [d1 loss: 0.050412] [d2 loss: 0.052094]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 202/500] [Batch 560/676] [D loss: -0.021662] [G loss: -0.053183] [d1 loss: 0.042951] [d2 loss: 0.041122]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 580/676] [D loss: -0.026771] [G loss: -0.073352] [d1 loss: 0.026167] [d2 loss: 0.017532]  [sq d1 d2: 0.000075]  [num0: 15.000000] [num1 49.000000]
[Epoch 202/500] [Batch 600/676] [D loss: -0.019015] [G loss: -0.090693] [d1 loss: 0.058606] [d2 loss: 0.068821]  [sq d1 d2: 0.000104]  [num0: 13.000000] [num1 51.000000]
[Epoch 202/500] [Batch 620/676] [D loss: -0.029722] [G loss: -0.097417] [d1 loss: 0.024864] [d2 loss: 0.023421]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 202/500] [Batch 640/676] [D loss: 0.012482] [G loss: -0.126092] [d1 loss: 0.090966] [d2 loss: 0.091625]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 202/500] [Batch 660/676] [D loss: -0.016726] [G loss: -0.164966] [d1 loss: 0.070510] [d2 loss: 0.085912]  [sq d1 d2: 0.000237]  [num0: 20.000000] [num1 44.000000]
[Epoch 203/500] [Batch 0/676] [D loss: -0.008395] [G loss: -0.150419] [d1 loss: 0.054003] [d2 loss: 0.069830]  [sq d1 d2: 0.000250]  [num0: 19.000000] [num1 45.000000]
[Epoch 203/500] [Batch 20/676] [D loss: 0.000659] [G loss: -0.092341] [d1 loss: 0.047061] [d2 loss: 0.044395]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 203/500] [Batch 40/676] [D loss: -0.008443] [G loss: -0.097423] [d1 loss: 0.028839] [d2 loss: 0.025342]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 203/500] [Batch 60/676] [D loss: -0.019385] [G loss: -0.060344] [d1 loss: 0.063824] [d2 loss: 0.060905]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 80/676] [D loss: -0.022569] [G loss: -0.034059] [d1 loss: 0.055527] [d2 loss: 0.047344]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 100/676] [D loss: -0.041817] [G loss: -0.067953] [d1 loss: 0.085064] [d2 loss: 0.110381]  [sq d1 d2: 0.000641]  [num0: 12.000000] [num1 52.000000]
[Epoch 203/500] [Batch 120/676] [D loss: -0.021218] [G loss: -0.059255] [d1 loss: 0.161601] [d2 loss: 0.168293]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 203/500] [Batch 140/676] [D loss: -0.030436] [G loss: -0.100709] [d1 loss: 0.070708] [d2 loss: 0.057986]  [sq d1 d2: 0.000162]  [num0: 16.000000] [num1 48.000000]
[Epoch 203/500] [Batch 160/676] [D loss: 0.002783] [G loss: -0.041501] [d1 loss: 0.084776] [d2 loss: 0.105015]  [sq d1 d2: 0.000410]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 180/676] [D loss: -0.001275] [G loss: 0.001980] [d1 loss: 0.055320] [d2 loss: 0.060179]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 203/500] [Batch 200/676] [D loss: -0.022569] [G loss: -0.005032] [d1 loss: 0.068941] [d2 loss: 0.062998]  [sq d1 d2: 0.000035]  [num0: 19.000000] [num1 45.000000]
[Epoch 203/500] [Batch 220/676] [D loss: -0.018821] [G loss: -0.003544] [d1 loss: 0.032960] [d2 loss: 0.034779]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 203/500] [Batch 240/676] [D loss: -0.038394] [G loss: 0.001598] [d1 loss: 0.068945] [d2 loss: 0.068219]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 203/500] [Batch 260/676] [D loss: -0.048196] [G loss: -0.009620] [d1 loss: 0.102784] [d2 loss: 0.104218]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 203/500] [Batch 280/676] [D loss: -0.022643] [G loss: -0.011114] [d1 loss: 0.151523] [d2 loss: 0.087523]  [sq d1 d2: 0.004096]  [num0: 19.000000] [num1 45.000000]
[Epoch 203/500] [Batch 300/676] [D loss: -0.032806] [G loss: -0.050978] [d1 loss: 0.022145] [d2 loss: 0.020128]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 203/500] [Batch 320/676] [D loss: -0.019896] [G loss: -0.080597] [d1 loss: 0.067159] [d2 loss: 0.063657]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 203/500] [Batch 340/676] [D loss: 0.003764] [G loss: -0.065407] [d1 loss: 0.100343] [d2 loss: 0.099333]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 360/676] [D loss: -0.008623] [G loss: -0.132031] [d1 loss: 0.133596] [d2 loss: 0.135313]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 203/500] [Batch 380/676] [D loss: 0.003259] [G loss: -0.082032] [d1 loss: 0.223241] [d2 loss: 0.165723]  [sq d1 d2: 0.003308]  [num0: 14.000000] [num1 50.000000]
[Epoch 203/500] [Batch 400/676] [D loss: 0.004325] [G loss: -0.110381] [d1 loss: 0.082624] [d2 loss: 0.093854]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 420/676] [D loss: -0.017810] [G loss: -0.094744] [d1 loss: 0.067680] [d2 loss: 0.068632]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 203/500] [Batch 440/676] [D loss: -0.031941] [G loss: -0.073567] [d1 loss: 0.039916] [d2 loss: 0.028404]  [sq d1 d2: 0.000133]  [num0: 17.000000] [num1 47.000000]
[Epoch 203/500] [Batch 460/676] [D loss: -0.003499] [G loss: -0.064742] [d1 loss: 0.048032] [d2 loss: 0.044781]  [sq d1 d2: 0.000011]  [num0: 21.000000] [num1 43.000000]
[Epoch 203/500] [Batch 480/676] [D loss: -0.038114] [G loss: -0.083964] [d1 loss: 0.075939] [d2 loss: 0.081766]  [sq d1 d2: 0.000034]  [num0: 20.000000] [num1 44.000000]
[Epoch 203/500] [Batch 500/676] [D loss: -0.037728] [G loss: -0.095515] [d1 loss: 0.074256] [d2 loss: 0.069153]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 203/500] [Batch 520/676] [D loss: -0.032481] [G loss: -0.142986] [d1 loss: 0.065750] [d2 loss: 0.068059]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]

[Epoch 203/500] [Batch 540/676] [D loss: -0.026665] [G loss: -0.159172] [d1 loss: 0.063650] [d2 loss: 0.074994]  [sq d1 d2: 0.000129]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 560/676] [D loss: -0.033022] [G loss: -0.156001] [d1 loss: 0.108007] [d2 loss: 0.101413]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 203/500] [Batch 580/676] [D loss: -0.008000] [G loss: -0.125147] [d1 loss: 0.064545] [d2 loss: 0.051367]  [sq d1 d2: 0.000174]  [num0: 17.000000] [num1 47.000000]
[Epoch 203/500] [Batch 600/676] [D loss: 0.024701] [G loss: -0.119657] [d1 loss: 0.088036] [d2 loss: 0.075929]  [sq d1 d2: 0.000147]  [num0: 13.000000] [num1 51.000000]
[Epoch 203/500] [Batch 620/676] [D loss: -0.014371] [G loss: -0.057593] [d1 loss: 0.092407] [d2 loss: 0.100597]  [sq d1 d2: 0.000067]  [num0: 18.000000] [num1 46.000000]
[Epoch 203/500] [Batch 640/676] [D loss: -0.007878] [G loss: -0.045844] [d1 loss: 0.028723] [d2 loss: 0.025072]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 203/500] [Batch 660/676] [D loss: -0.024774] [G loss: -0.044970] [d1 loss: 0.072371] [d2 loss: 0.064154]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 204/500] [Batch 0/676] [D loss: -0.026878] [G loss: 0.001740] [d1 loss: 0.077062] [d2 loss: 0.100037]  [sq d1 d2: 0.000528]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 20/676] [D loss: -0.030200] [G loss: 0.016334] [d1 loss: 0.081079] [d2 loss: 0.073694]  [sq d1 d2: 0.000055]  [num0: 12.000000] [num1 52.000000]
[Epoch 204/500] [Batch 40/676] [D loss: -0.031493] [G loss: 0.001764] [d1 loss: 0.043521] [d2 loss: 0.046969]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 204/500] [Batch 60/676] [D loss: -0.045303] [G loss: -0.004439] [d1 loss: 0.059786] [d2 loss: 0.054533]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 80/676] [D loss: -0.016522] [G loss: -0.015171] [d1 loss: 0.285380] [d2 loss: 0.238739]  [sq d1 d2: 0.002175]  [num0: 12.000000] [num1 52.000000]
[Epoch 204/500] [Batch 100/676] [D loss: 0.003069] [G loss: -0.032069] [d1 loss: 0.054266] [d2 loss: 0.042487]  [sq d1 d2: 0.000139]  [num0: 14.000000] [num1 50.000000]
[Epoch 204/500] [Batch 120/676] [D loss: -0.004963] [G loss: -0.015645] [d1 loss: 0.079674] [d2 loss: 0.062602]  [sq d1 d2: 0.000291]  [num0: 10.000000] [num1 54.000000]
[Epoch 204/500] [Batch 140/676] [D loss: -0.013984] [G loss: -0.022634] [d1 loss: 0.083754] [d2 loss: 0.067351]  [sq d1 d2: 0.000269]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 160/676] [D loss: 0.009210] [G loss: -0.024191] [d1 loss: 0.038829] [d2 loss: 0.033780]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 204/500] [Batch 180/676] [D loss: 0.005133] [G loss: -0.021202] [d1 loss: 0.050771] [d2 loss: 0.061051]  [sq d1 d2: 0.000106]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 200/676] [D loss: -0.002672] [G loss: -0.006704] [d1 loss: 0.127100] [d2 loss: 0.100310]  [sq d1 d2: 0.000718]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 220/676] [D loss: -0.002332] [G loss: 0.005725] [d1 loss: 0.145297] [d2 loss: 0.133879]  [sq d1 d2: 0.000130]  [num0: 17.000000] [num1 47.000000]
[Epoch 204/500] [Batch 240/676] [D loss: -0.035336] [G loss: 0.016892] [d1 loss: 0.052299] [d2 loss: 0.050309]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 204/500] [Batch 260/676] [D loss: -0.047631] [G loss: 0.005964] [d1 loss: 0.091138] [d2 loss: 0.093735]  [sq d1 d2: 0.000007]  [num0: 11.000000] [num1 53.000000]
[Epoch 204/500] [Batch 280/676] [D loss: -0.073760] [G loss: 0.009383] [d1 loss: 0.128109] [d2 loss: 0.119067]  [sq d1 d2: 0.000082]  [num0: 19.000000] [num1 45.000000]
[Epoch 204/500] [Batch 300/676] [D loss: -0.063285] [G loss: -0.046680] [d1 loss: 0.032572] [d2 loss: 0.041328]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 204/500] [Batch 320/676] [D loss: -0.018063] [G loss: -0.091360] [d1 loss: 0.103162] [d2 loss: 0.077407]  [sq d1 d2: 0.000663]  [num0: 18.000000] [num1 46.000000]
[Epoch 204/500] [Batch 340/676] [D loss: -0.022373] [G loss: -0.140809] [d1 loss: 0.113042] [d2 loss: 0.093990]  [sq d1 d2: 0.000363]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 360/676] [D loss: -0.025908] [G loss: -0.133579] [d1 loss: 0.081232] [d2 loss: 0.075777]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 380/676] [D loss: 0.023223] [G loss: -0.163923] [d1 loss: 0.138585] [d2 loss: 0.119423]  [sq d1 d2: 0.000367]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 400/676] [D loss: 0.018383] [G loss: -0.150878] [d1 loss: 0.041982] [d2 loss: 0.045039]  [sq d1 d2: 0.000009]  [num0: 21.000000] [num1 43.000000]
[Epoch 204/500] [Batch 420/676] [D loss: 0.001257] [G loss: -0.125957] [d1 loss: 0.078959] [d2 loss: 0.062276]  [sq d1 d2: 0.000278]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 440/676] [D loss: -0.010344] [G loss: -0.122878] [d1 loss: 0.052485] [d2 loss: 0.063593]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]
[Epoch 204/500] [Batch 460/676] [D loss: -0.007663] [G loss: -0.110302] [d1 loss: 0.073522] [d2 loss: 0.082722]  [sq d1 d2: 0.000085]  [num0: 19.000000] [num1 45.000000]
[Epoch 204/500] [Batch 480/676] [D loss: -0.027518] [G loss: -0.127085] [d1 loss: 0.228067] [d2 loss: 0.161531]  [sq d1 d2: 0.004427]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 500/676] [D loss: -0.032475] [G loss: -0.138629] [d1 loss: 0.032632] [d2 loss: 0.021890]  [sq d1 d2: 0.000115]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 520/676] [D loss: -0.045525] [G loss: -0.163110] [d1 loss: 0.054239] [d2 loss: 0.049997]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 540/676] [D loss: -0.031154] [G loss: -0.164291] [d1 loss: 0.025486] [d2 loss: 0.028581]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 204/500] [Batch 560/676] [D loss: 0.007978] [G loss: -0.166268] [d1 loss: 0.091766] [d2 loss: 0.094505]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 204/500] [Batch 580/676] [D loss: -0.034418] [G loss: -0.186499] [d1 loss: 0.102275] [d2 loss: 0.103091]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 600/676] [D loss: 0.011596] [G loss: -0.166237] [d1 loss: 0.059565] [d2 loss: 0.054677]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 204/500] [Batch 620/676] [D loss: 0.010932] [G loss: -0.191298] [d1 loss: 0.121109] [d2 loss: 0.160253]  [sq d1 d2: 0.001532]  [num0: 16.000000] [num1 48.000000]
[Epoch 204/500] [Batch 640/676] [D loss: 0.014196] [G loss: -0.149087] [d1 loss: 0.067744] [d2 loss: 0.096654]  [sq d1 d2: 0.000836]  [num0: 14.000000] [num1 50.000000]
[Epoch 204/500] [Batch 660/676] [D loss: 0.006099] [G loss: -0.118581] [d1 loss: 0.071225] [d2 loss: 0.060628]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 0/676] [D loss: 0.003790] [G loss: -0.076157] [d1 loss: 0.075369] [d2 loss: 0.057277]  [sq d1 d2: 0.000327]  [num0: 16.000000] [num1 48.000000]
[Epoch 205/500] [Batch 20/676] [D loss: -0.000304] [G loss: -0.033336] [d1 loss: 0.173975] [d2 loss: 0.178958]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 40/676] [D loss: -0.007834] [G loss: -0.001722] [d1 loss: 0.081059] [d2 loss: 0.077379]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 60/676] [D loss: -0.035461] [G loss: 0.022379] [d1 loss: 0.018375] [d2 loss: 0.017063]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 205/500] [Batch 80/676] [D loss: -0.041694] [G loss: 0.063530] [d1 loss: 0.071206] [d2 loss: 0.081802]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 100/676] [D loss: -0.060086] [G loss: 0.074980] [d1 loss: 0.033028] [d2 loss: 0.030973]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 120/676] [D loss: -0.040346] [G loss: 0.072936] [d1 loss: 0.034142] [d2 loss: 0.021030]  [sq d1 d2: 0.000172]  [num0: 11.000000] [num1 53.000000]
[Epoch 205/500] [Batch 140/676] [D loss: -0.050722] [G loss: 0.018308] [d1 loss: 0.073053] [d2 loss: 0.101613]  [sq d1 d2: 0.000816]  [num0: 13.000000] [num1 51.000000]
[Epoch 205/500] [Batch 160/676] [D loss: -0.009146] [G loss: -0.002492] [d1 loss: 0.052023] [d2 loss: 0.052719]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 205/500] [Batch 180/676] [D loss: -0.009888] [G loss: 0.007208] [d1 loss: 0.062878] [d2 loss: 0.048044]  [sq d1 d2: 0.000220]  [num0: 12.000000] [num1 52.000000]
[Epoch 205/500] [Batch 200/676] [D loss: 0.025752] [G loss: -0.072097] [d1 loss: 0.107586] [d2 loss: 0.121397]  [sq d1 d2: 0.000191]  [num0: 14.000000] [num1 50.000000]

[Epoch 205/500] [Batch 220/676] [D loss: 0.002464] [G loss: -0.044960] [d1 loss: 0.063121] [d2 loss: 0.058082]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 240/676] [D loss: 0.009568] [G loss: -0.000093] [d1 loss: 0.086292] [d2 loss: 0.092184]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 205/500] [Batch 260/676] [D loss: -0.019632] [G loss: 0.050174] [d1 loss: 0.068582] [d2 loss: 0.053372]  [sq d1 d2: 0.000231]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 280/676] [D loss: -0.013329] [G loss: 0.087560] [d1 loss: 0.077750] [d2 loss: 0.094081]  [sq d1 d2: 0.000267]  [num0: 13.000000] [num1 51.000000]
[Epoch 205/500] [Batch 300/676] [D loss: -0.071717] [G loss: 0.077839] [d1 loss: 0.053409] [d2 loss: 0.063552]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 320/676] [D loss: -0.069151] [G loss: 0.071244] [d1 loss: 0.047276] [d2 loss: 0.043534]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 340/676] [D loss: -0.098189] [G loss: 0.052945] [d1 loss: 0.085026] [d2 loss: 0.083083]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 360/676] [D loss: -0.070595] [G loss: -0.015446] [d1 loss: 0.085499] [d2 loss: 0.075624]  [sq d1 d2: 0.000098]  [num0: 18.000000] [num1 46.000000]
[Epoch 205/500] [Batch 380/676] [D loss: -0.081809] [G loss: -0.008187] [d1 loss: 0.107031] [d2 loss: 0.062084]  [sq d1 d2: 0.002020]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 400/676] [D loss: 0.049442] [G loss: -0.073549] [d1 loss: 0.042569] [d2 loss: 0.033546]  [sq d1 d2: 0.000081]  [num0: 12.000000] [num1 52.000000]
[Epoch 205/500] [Batch 420/676] [D loss: 0.030034] [G loss: -0.076639] [d1 loss: 0.086682] [d2 loss: 0.084896]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 440/676] [D loss: -0.002032] [G loss: -0.095999] [d1 loss: 0.115254] [d2 loss: 0.098737]  [sq d1 d2: 0.000273]  [num0: 18.000000] [num1 46.000000]
[Epoch 205/500] [Batch 460/676] [D loss: 0.002428] [G loss: -0.089496] [d1 loss: 0.029336] [d2 loss: 0.022495]  [sq d1 d2: 0.000047]  [num0: 10.000000] [num1 54.000000]
[Epoch 205/500] [Batch 480/676] [D loss: -0.007012] [G loss: -0.106737] [d1 loss: 0.123425] [d2 loss: 0.139730]  [sq d1 d2: 0.000266]  [num0: 16.000000] [num1 48.000000]
[Epoch 205/500] [Batch 500/676] [D loss: -0.023543] [G loss: -0.083982] [d1 loss: 0.084248] [d2 loss: 0.084001]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 205/500] [Batch 520/676] [D loss: -0.066705] [G loss: -0.048024] [d1 loss: 0.078899] [d2 loss: 0.079184]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 205/500] [Batch 540/676] [D loss: -0.047087] [G loss: -0.016769] [d1 loss: 0.053688] [d2 loss: 0.052737]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 205/500] [Batch 560/676] [D loss: -0.047159] [G loss: 0.002694] [d1 loss: 0.119888] [d2 loss: 0.137839]  [sq d1 d2: 0.000322]  [num0: 18.000000] [num1 46.000000]
[Epoch 205/500] [Batch 580/676] [D loss: -0.059043] [G loss: -0.035735] [d1 loss: 0.085050] [d2 loss: 0.083604]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 205/500] [Batch 600/676] [D loss: -0.060030] [G loss: -0.116120] [d1 loss: 0.077808] [d2 loss: 0.081734]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 205/500] [Batch 620/676] [D loss: 0.025112] [G loss: -0.145080] [d1 loss: 0.076497] [d2 loss: 0.062651]  [sq d1 d2: 0.000192]  [num0: 13.000000] [num1 51.000000]
[Epoch 205/500] [Batch 640/676] [D loss: 0.018397] [G loss: -0.178589] [d1 loss: 0.061817] [d2 loss: 0.040726]  [sq d1 d2: 0.000445]  [num0: 15.000000] [num1 49.000000]
[Epoch 205/500] [Batch 660/676] [D loss: 0.022597] [G loss: -0.122120] [d1 loss: 0.055907] [d2 loss: 0.065885]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 206/500] [Batch 0/676] [D loss: 0.017093] [G loss: -0.076942] [d1 loss: 0.085614] [d2 loss: 0.059229]  [sq d1 d2: 0.000696]  [num0: 20.000000] [num1 44.000000]
[Epoch 206/500] [Batch 20/676] [D loss: 0.000513] [G loss: -0.012911] [d1 loss: 0.080789] [d2 loss: 0.086555]  [sq d1 d2: 0.000033]  [num0: 20.000000] [num1 44.000000]
[Epoch 206/500] [Batch 40/676] [D loss: -0.018518] [G loss: 0.038122] [d1 loss: 0.042041] [d2 loss: 0.054721]  [sq d1 d2: 0.000161]  [num0: 15.000000] [num1 49.000000]
[Epoch 206/500] [Batch 60/676] [D loss: -0.039587] [G loss: 0.115472] [d1 loss: 0.118296] [d2 loss: 0.091215]  [sq d1 d2: 0.000733]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 80/676] [D loss: -0.046987] [G loss: 0.202764] [d1 loss: 0.097043] [d2 loss: 0.099964]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 100/676] [D loss: -0.095152] [G loss: 0.243973] [d1 loss: 0.083370] [d2 loss: 0.084965]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 206/500] [Batch 120/676] [D loss: -0.068964] [G loss: 0.229620] [d1 loss: 0.028199] [d2 loss: 0.030363]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 140/676] [D loss: 0.019010] [G loss: 0.220652] [d1 loss: 0.165365] [d2 loss: 0.138870]  [sq d1 d2: 0.000702]  [num0: 19.000000] [num1 45.000000]
[Epoch 206/500] [Batch 160/676] [D loss: -0.007361] [G loss: 0.186252] [d1 loss: 0.026375] [d2 loss: 0.025957]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 206/500] [Batch 180/676] [D loss: 0.037324] [G loss: 0.134721] [d1 loss: 0.103482] [d2 loss: 0.090963]  [sq d1 d2: 0.000157]  [num0: 13.000000] [num1 51.000000]
[Epoch 206/500] [Batch 200/676] [D loss: 0.048306] [G loss: 0.088759] [d1 loss: 0.045367] [d2 loss: 0.055531]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 220/676] [D loss: 0.032329] [G loss: 0.030033] [d1 loss: 0.080940] [d2 loss: 0.097840]  [sq d1 d2: 0.000286]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 240/676] [D loss: 0.012624] [G loss: 0.006385] [d1 loss: 0.207568] [d2 loss: 0.215167]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 206/500] [Batch 260/676] [D loss: 0.006033] [G loss: -0.017041] [d1 loss: 0.149885] [d2 loss: 0.136913]  [sq d1 d2: 0.000168]  [num0: 12.000000] [num1 52.000000]
[Epoch 206/500] [Batch 280/676] [D loss: -0.005790] [G loss: -0.048828] [d1 loss: 0.051008] [d2 loss: 0.064194]  [sq d1 d2: 0.000174]  [num0: 18.000000] [num1 46.000000]
[Epoch 206/500] [Batch 300/676] [D loss: -0.015317] [G loss: -0.065910] [d1 loss: 0.072002] [d2 loss: 0.073379]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 320/676] [D loss: -0.047412] [G loss: -0.105370] [d1 loss: 0.070352] [d2 loss: 0.059688]  [sq d1 d2: 0.000114]  [num0: 13.000000] [num1 51.000000]
[Epoch 206/500] [Batch 340/676] [D loss: -0.062137] [G loss: -0.083646] [d1 loss: 0.047716] [d2 loss: 0.046984]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 360/676] [D loss: -0.092570] [G loss: -0.053243] [d1 loss: 0.182937] [d2 loss: 0.150908]  [sq d1 d2: 0.001026]  [num0: 19.000000] [num1 45.000000]
[Epoch 206/500] [Batch 380/676] [D loss: -0.011592] [G loss: -0.065200] [d1 loss: 0.102723] [d2 loss: 0.108417]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 206/500] [Batch 400/676] [D loss: -0.044141] [G loss: -0.168907] [d1 loss: 0.090238] [d2 loss: 0.090858]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 420/676] [D loss: -0.013254] [G loss: -0.186776] [d1 loss: 0.098323] [d2 loss: 0.112053]  [sq d1 d2: 0.000188]  [num0: 12.000000] [num1 52.000000]
[Epoch 206/500] [Batch 440/676] [D loss: 0.035997] [G loss: -0.199075] [d1 loss: 0.085277] [d2 loss: 0.087993]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 460/676] [D loss: 0.029946] [G loss: -0.133393] [d1 loss: 0.125454] [d2 loss: 0.081763]  [sq d1 d2: 0.001909]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 480/676] [D loss: 0.001809] [G loss: -0.068871] [d1 loss: 0.162935] [d2 loss: 0.153540]  [sq d1 d2: 0.000088]  [num0: 18.000000] [num1 46.000000]
[Epoch 206/500] [Batch 500/676] [D loss: -0.004364] [G loss: -0.023323] [d1 loss: 0.091576] [d2 loss: 0.082013]  [sq d1 d2: 0.000091]  [num0: 20.000000] [num1 44.000000]
[Epoch 206/500] [Batch 520/676] [D loss: -0.029659] [G loss: 0.027966] [d1 loss: 0.047777] [d2 loss: 0.044986]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 206/500] [Batch 540/676] [D loss: -0.034466] [G loss: 0.090677] [d1 loss: 0.126552] [d2 loss: 0.087868]  [sq d1 d2: 0.001496]  [num0: 14.000000] [num1 50.000000]
[Epoch 206/500] [Batch 560/676] [D loss: -0.072352] [G loss: 0.141778] [d1 loss: 0.143973] [d2 loss: 0.156934]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]

[Epoch 206/500] [Batch 580/676] [D loss: -0.119858] [G loss: 0.197188] [d1 loss: 0.055678] [d2 loss: 0.042651]  [sq d1 d2: 0.000170]  [num0: 20.000000] [num1 44.000000]
[Epoch 206/500] [Batch 600/676] [D loss: -0.080009] [G loss: 0.215296] [d1 loss: 0.078974] [d2 loss: 0.044862]  [sq d1 d2: 0.001164]  [num0: 16.000000] [num1 48.000000]
[Epoch 206/500] [Batch 620/676] [D loss: -0.068891] [G loss: 0.198264] [d1 loss: 0.041690] [d2 loss: 0.051481]  [sq d1 d2: 0.000096]  [num0: 18.000000] [num1 46.000000]
[Epoch 206/500] [Batch 640/676] [D loss: -0.018003] [G loss: 0.225261] [d1 loss: 0.114829] [d2 loss: 0.105999]  [sq d1 d2: 0.000078]  [num0: 17.000000] [num1 47.000000]
[Epoch 206/500] [Batch 660/676] [D loss: -0.022114] [G loss: 0.201444] [d1 loss: 0.066260] [d2 loss: 0.058060]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 0/676] [D loss: 0.067470] [G loss: 0.208955] [d1 loss: 0.097733] [d2 loss: 0.083557]  [sq d1 d2: 0.000201]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 20/676] [D loss: 0.029136] [G loss: 0.189913] [d1 loss: 0.039566] [d2 loss: 0.046702]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 207/500] [Batch 40/676] [D loss: 0.020428] [G loss: 0.129411] [d1 loss: 0.083243] [d2 loss: 0.080348]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 207/500] [Batch 60/676] [D loss: 0.007189] [G loss: 0.054719] [d1 loss: 0.053710] [d2 loss: 0.072726]  [sq d1 d2: 0.000362]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 80/676] [D loss: -0.002961] [G loss: -0.004181] [d1 loss: 0.118880] [d2 loss: 0.084343]  [sq d1 d2: 0.001193]  [num0: 16.000000] [num1 48.000000]
[Epoch 207/500] [Batch 100/676] [D loss: -0.005566] [G loss: -0.058534] [d1 loss: 0.060953] [d2 loss: 0.051033]  [sq d1 d2: 0.000098]  [num0: 13.000000] [num1 51.000000]
[Epoch 207/500] [Batch 120/676] [D loss: -0.040616] [G loss: -0.077311] [d1 loss: 0.117543] [d2 loss: 0.123057]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 140/676] [D loss: -0.057366] [G loss: -0.005473] [d1 loss: 0.122990] [d2 loss: 0.112428]  [sq d1 d2: 0.000112]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 160/676] [D loss: -0.107083] [G loss: 0.022332] [d1 loss: 0.144187] [d2 loss: 0.125684]  [sq d1 d2: 0.000342]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 180/676] [D loss: -0.080445] [G loss: -0.011779] [d1 loss: 0.025477] [d2 loss: 0.023556]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 207/500] [Batch 200/676] [D loss: -0.052577] [G loss: -0.099850] [d1 loss: 0.042803] [d2 loss: 0.036378]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 220/676] [D loss: 0.074014] [G loss: -0.157097] [d1 loss: 0.084573] [d2 loss: 0.101690]  [sq d1 d2: 0.000293]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 240/676] [D loss: 0.030777] [G loss: -0.183186] [d1 loss: 0.056481] [d2 loss: 0.063754]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 207/500] [Batch 260/676] [D loss: 0.036214] [G loss: -0.177459] [d1 loss: 0.102572] [d2 loss: 0.111781]  [sq d1 d2: 0.000085]  [num0: 18.000000] [num1 46.000000]
[Epoch 207/500] [Batch 280/676] [D loss: 0.038250] [G loss: -0.109110] [d1 loss: 0.046534] [d2 loss: 0.031825]  [sq d1 d2: 0.000216]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 300/676] [D loss: 0.010171] [G loss: -0.058530] [d1 loss: 0.046540] [d2 loss: 0.048193]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 320/676] [D loss: -0.002361] [G loss: -0.017010] [d1 loss: 0.039201] [d2 loss: 0.042220]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 340/676] [D loss: -0.013850] [G loss: 0.009575] [d1 loss: 0.077472] [d2 loss: 0.074023]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 360/676] [D loss: -0.058478] [G loss: 0.039705] [d1 loss: 0.047556] [d2 loss: 0.040261]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 207/500] [Batch 380/676] [D loss: -0.063409] [G loss: 0.099877] [d1 loss: 0.058043] [d2 loss: 0.056843]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 400/676] [D loss: -0.108754] [G loss: 0.094331] [d1 loss: 0.025081] [d2 loss: 0.023171]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 420/676] [D loss: -0.053267] [G loss: 0.107071] [d1 loss: 0.057042] [d2 loss: 0.055206]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 440/676] [D loss: 0.028047] [G loss: 0.096065] [d1 loss: 0.051220] [d2 loss: 0.064706]  [sq d1 d2: 0.000182]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 460/676] [D loss: -0.032059] [G loss: 0.084058] [d1 loss: 0.158442] [d2 loss: 0.165266]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 480/676] [D loss: 0.012164] [G loss: 0.037886] [d1 loss: 0.056536] [d2 loss: 0.079411]  [sq d1 d2: 0.000523]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 500/676] [D loss: 0.030440] [G loss: 0.047137] [d1 loss: 0.105000] [d2 loss: 0.100087]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 207/500] [Batch 520/676] [D loss: 0.023935] [G loss: 0.000816] [d1 loss: 0.059610] [d2 loss: 0.051576]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 207/500] [Batch 540/676] [D loss: 0.012461] [G loss: -0.011651] [d1 loss: 0.052435] [d2 loss: 0.034966]  [sq d1 d2: 0.000305]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 560/676] [D loss: 0.007133] [G loss: -0.017939] [d1 loss: 0.079263] [d2 loss: 0.075841]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 207/500] [Batch 580/676] [D loss: -0.005548] [G loss: -0.019207] [d1 loss: 0.041346] [d2 loss: 0.073648]  [sq d1 d2: 0.001043]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 600/676] [D loss: -0.024298] [G loss: -0.018487] [d1 loss: 0.111396] [d2 loss: 0.118601]  [sq d1 d2: 0.000052]  [num0: 17.000000] [num1 47.000000]
[Epoch 207/500] [Batch 620/676] [D loss: -0.038533] [G loss: -0.011587] [d1 loss: 0.082957] [d2 loss: 0.098137]  [sq d1 d2: 0.000230]  [num0: 15.000000] [num1 49.000000]
[Epoch 207/500] [Batch 640/676] [D loss: -0.104005] [G loss: 0.034028] [d1 loss: 0.036711] [d2 loss: 0.056064]  [sq d1 d2: 0.000375]  [num0: 16.000000] [num1 48.000000]
[Epoch 207/500] [Batch 660/676] [D loss: -0.078101] [G loss: 0.002076] [d1 loss: 0.042364] [d2 loss: 0.050588]  [sq d1 d2: 0.000068]  [num0: 13.000000] [num1 51.000000]
[Epoch 208/500] [Batch 0/676] [D loss: -0.072596] [G loss: 0.008062] [d1 loss: 0.045208] [d2 loss: 0.056780]  [sq d1 d2: 0.000134]  [num0: 10.000000] [num1 54.000000]
[Epoch 208/500] [Batch 20/676] [D loss: -0.059306] [G loss: 0.006162] [d1 loss: 0.079163] [d2 loss: 0.084307]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 40/676] [D loss: 0.018154] [G loss: -0.041704] [d1 loss: 0.084294] [d2 loss: 0.081695]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 60/676] [D loss: 0.038987] [G loss: -0.156610] [d1 loss: 0.052164] [d2 loss: 0.053525]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 208/500] [Batch 80/676] [D loss: 0.020840] [G loss: -0.195200] [d1 loss: 0.087488] [d2 loss: 0.068932]  [sq d1 d2: 0.000344]  [num0: 15.000000] [num1 49.000000]
[Epoch 208/500] [Batch 100/676] [D loss: 0.021195] [G loss: -0.166314] [d1 loss: 0.054019] [d2 loss: 0.081703]  [sq d1 d2: 0.000766]  [num0: 13.000000] [num1 51.000000]
[Epoch 208/500] [Batch 120/676] [D loss: 0.009947] [G loss: -0.120552] [d1 loss: 0.112637] [d2 loss: 0.099679]  [sq d1 d2: 0.000168]  [num0: 18.000000] [num1 46.000000]
[Epoch 208/500] [Batch 140/676] [D loss: -0.002843] [G loss: -0.069900] [d1 loss: 0.059537] [d2 loss: 0.057076]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 208/500] [Batch 160/676] [D loss: -0.026468] [G loss: -0.041663] [d1 loss: 0.151652] [d2 loss: 0.090452]  [sq d1 d2: 0.003745]  [num0: 20.000000] [num1 44.000000]
[Epoch 208/500] [Batch 180/676] [D loss: -0.031787] [G loss: 0.007230] [d1 loss: 0.171680] [d2 loss: 0.175918]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 208/500] [Batch 200/676] [D loss: -0.052160] [G loss: 0.044941] [d1 loss: 0.072583] [d2 loss: 0.083846]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]

[Epoch 208/500] [Batch 220/676] [D loss: -0.094546] [G loss: 0.073889] [d1 loss: 0.137471] [d2 loss: 0.135321]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 208/500] [Batch 240/676] [D loss: -0.041493] [G loss: 0.140216] [d1 loss: 0.032579] [d2 loss: 0.065703]  [sq d1 d2: 0.001097]  [num0: 16.000000] [num1 48.000000]
[Epoch 208/500] [Batch 260/676] [D loss: -0.068972] [G loss: 0.122134] [d1 loss: 0.058254] [d2 loss: 0.065473]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 208/500] [Batch 280/676] [D loss: -0.032072] [G loss: 0.110180] [d1 loss: 0.031036] [d2 loss: 0.027376]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 208/500] [Batch 300/676] [D loss: -0.003786] [G loss: 0.055633] [d1 loss: 0.068756] [d2 loss: 0.071711]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 320/676] [D loss: -0.010788] [G loss: -0.009389] [d1 loss: 0.039307] [d2 loss: 0.029656]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 208/500] [Batch 340/676] [D loss: 0.029256] [G loss: -0.062260] [d1 loss: 0.083925] [d2 loss: 0.072505]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 208/500] [Batch 360/676] [D loss: 0.002664] [G loss: -0.043322] [d1 loss: 0.057760] [d2 loss: 0.067379]  [sq d1 d2: 0.000093]  [num0: 13.000000] [num1 51.000000]
[Epoch 208/500] [Batch 380/676] [D loss: 0.015468] [G loss: -0.065838] [d1 loss: 0.075550] [d2 loss: 0.072113]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 208/500] [Batch 400/676] [D loss: 0.010755] [G loss: -0.060388] [d1 loss: 0.089793] [d2 loss: 0.070982]  [sq d1 d2: 0.000354]  [num0: 21.000000] [num1 43.000000]
[Epoch 208/500] [Batch 420/676] [D loss: 0.000725] [G loss: -0.028657] [d1 loss: 0.144785] [d2 loss: 0.158962]  [sq d1 d2: 0.000201]  [num0: 22.000000] [num1 42.000000]
[Epoch 208/500] [Batch 440/676] [D loss: -0.007964] [G loss: -0.020926] [d1 loss: 0.097502] [d2 loss: 0.089688]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 460/676] [D loss: -0.016163] [G loss: -0.011896] [d1 loss: 0.056411] [d2 loss: 0.052848]  [sq d1 d2: 0.000013]  [num0: 22.000000] [num1 42.000000]
[Epoch 208/500] [Batch 480/676] [D loss: -0.037197] [G loss: -0.046656] [d1 loss: 0.059877] [d2 loss: 0.083169]  [sq d1 d2: 0.000543]  [num0: 17.000000] [num1 47.000000]
[Epoch 208/500] [Batch 500/676] [D loss: -0.075935] [G loss: -0.013967] [d1 loss: 0.080899] [d2 loss: 0.076129]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 520/676] [D loss: -0.107294] [G loss: 0.028642] [d1 loss: 0.063222] [d2 loss: 0.074352]  [sq d1 d2: 0.000124]  [num0: 11.000000] [num1 53.000000]
[Epoch 208/500] [Batch 540/676] [D loss: -0.040597] [G loss: 0.029717] [d1 loss: 0.086160] [d2 loss: 0.082114]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 208/500] [Batch 560/676] [D loss: -0.055439] [G loss: -0.004020] [d1 loss: 0.210304] [d2 loss: 0.194788]  [sq d1 d2: 0.000241]  [num0: 16.000000] [num1 48.000000]
[Epoch 208/500] [Batch 580/676] [D loss: 0.012660] [G loss: -0.119020] [d1 loss: 0.121447] [d2 loss: 0.121957]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 208/500] [Batch 600/676] [D loss: 0.077046] [G loss: -0.227518] [d1 loss: 0.071092] [d2 loss: 0.067963]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 208/500] [Batch 620/676] [D loss: 0.029990] [G loss: -0.210795] [d1 loss: 0.112663] [d2 loss: 0.094939]  [sq d1 d2: 0.000314]  [num0: 16.000000] [num1 48.000000]
[Epoch 208/500] [Batch 640/676] [D loss: 0.037143] [G loss: -0.191428] [d1 loss: 0.136202] [d2 loss: 0.129326]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 208/500] [Batch 660/676] [D loss: 0.012631] [G loss: -0.140120] [d1 loss: 0.081528] [d2 loss: 0.092820]  [sq d1 d2: 0.000128]  [num0: 13.000000] [num1 51.000000]
[Epoch 209/500] [Batch 0/676] [D loss: 0.008922] [G loss: -0.115588] [d1 loss: 0.043986] [d2 loss: 0.034301]  [sq d1 d2: 0.000094]  [num0: 19.000000] [num1 45.000000]
[Epoch 209/500] [Batch 20/676] [D loss: -0.000988] [G loss: -0.085806] [d1 loss: 0.052952] [d2 loss: 0.050253]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 40/676] [D loss: -0.010929] [G loss: -0.041855] [d1 loss: 0.121590] [d2 loss: 0.129174]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 60/676] [D loss: -0.029548] [G loss: 0.009062] [d1 loss: 0.031301] [d2 loss: 0.026814]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 80/676] [D loss: -0.067583] [G loss: 0.105269] [d1 loss: 0.074587] [d2 loss: 0.095603]  [sq d1 d2: 0.000442]  [num0: 17.000000] [num1 47.000000]
[Epoch 209/500] [Batch 100/676] [D loss: -0.055405] [G loss: 0.165249] [d1 loss: 0.143574] [d2 loss: 0.111372]  [sq d1 d2: 0.001037]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 120/676] [D loss: -0.108803] [G loss: 0.171450] [d1 loss: 0.054156] [d2 loss: 0.061540]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 140/676] [D loss: -0.103733] [G loss: 0.199697] [d1 loss: 0.080263] [d2 loss: 0.081021]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 209/500] [Batch 160/676] [D loss: -0.059974] [G loss: 0.161875] [d1 loss: 0.130343] [d2 loss: 0.126745]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 209/500] [Batch 180/676] [D loss: -0.037473] [G loss: 0.171241] [d1 loss: 0.110419] [d2 loss: 0.102839]  [sq d1 d2: 0.000057]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 200/676] [D loss: -0.026288] [G loss: 0.122273] [d1 loss: 0.094881] [d2 loss: 0.083904]  [sq d1 d2: 0.000120]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 220/676] [D loss: -0.001698] [G loss: 0.101037] [d1 loss: 0.169096] [d2 loss: 0.136120]  [sq d1 d2: 0.001087]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 240/676] [D loss: 0.013068] [G loss: 0.049487] [d1 loss: 0.051314] [d2 loss: 0.041578]  [sq d1 d2: 0.000095]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 260/676] [D loss: 0.022890] [G loss: 0.021938] [d1 loss: 0.116329] [d2 loss: 0.113872]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 280/676] [D loss: 0.015020] [G loss: 0.031907] [d1 loss: 0.091505] [d2 loss: 0.096014]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 300/676] [D loss: -0.001905] [G loss: 0.040043] [d1 loss: 0.109272] [d2 loss: 0.108090]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 209/500] [Batch 320/676] [D loss: -0.019244] [G loss: 0.066323] [d1 loss: 0.089213] [d2 loss: 0.083602]  [sq d1 d2: 0.000031]  [num0: 12.000000] [num1 52.000000]
[Epoch 209/500] [Batch 340/676] [D loss: -0.036408] [G loss: 0.044113] [d1 loss: 0.037980] [d2 loss: 0.049088]  [sq d1 d2: 0.000123]  [num0: 13.000000] [num1 51.000000]
[Epoch 209/500] [Batch 360/676] [D loss: -0.030848] [G loss: 0.011608] [d1 loss: 0.048863] [d2 loss: 0.043325]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 380/676] [D loss: -0.046824] [G loss: 0.010370] [d1 loss: 0.081574] [d2 loss: 0.098603]  [sq d1 d2: 0.000290]  [num0: 17.000000] [num1 47.000000]
[Epoch 209/500] [Batch 400/676] [D loss: -0.000353] [G loss: 0.057622] [d1 loss: 0.067515] [d2 loss: 0.066569]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 209/500] [Batch 420/676] [D loss: -0.035050] [G loss: 0.024620] [d1 loss: 0.113490] [d2 loss: 0.129120]  [sq d1 d2: 0.000244]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 440/676] [D loss: -0.014226] [G loss: 0.008806] [d1 loss: 0.050777] [d2 loss: 0.073093]  [sq d1 d2: 0.000498]  [num0: 18.000000] [num1 46.000000]
[Epoch 209/500] [Batch 460/676] [D loss: -0.017835] [G loss: -0.114860] [d1 loss: 0.075085] [d2 loss: 0.068734]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 209/500] [Batch 480/676] [D loss: 0.038836] [G loss: -0.167758] [d1 loss: 0.140361] [d2 loss: 0.117187]  [sq d1 d2: 0.000537]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 500/676] [D loss: 0.013898] [G loss: -0.259198] [d1 loss: 0.085726] [d2 loss: 0.100698]  [sq d1 d2: 0.000224]  [num0: 20.000000] [num1 44.000000]
[Epoch 209/500] [Batch 520/676] [D loss: 0.016840] [G loss: -0.227723] [d1 loss: 0.078875] [d2 loss: 0.087224]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 540/676] [D loss: 0.014377] [G loss: -0.184393] [d1 loss: 0.123109] [d2 loss: 0.098703]  [sq d1 d2: 0.000596]  [num0: 19.000000] [num1 45.000000]
[Epoch 209/500] [Batch 560/676] [D loss: 0.011282] [G loss: -0.140121] [d1 loss: 0.079028] [d2 loss: 0.077707]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]

[Epoch 209/500] [Batch 580/676] [D loss: 0.006688] [G loss: -0.092302] [d1 loss: 0.116121] [d2 loss: 0.146490]  [sq d1 d2: 0.000922]  [num0: 15.000000] [num1 49.000000]
[Epoch 209/500] [Batch 600/676] [D loss: 0.000438] [G loss: -0.052912] [d1 loss: 0.044894] [d2 loss: 0.045297]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 209/500] [Batch 620/676] [D loss: -0.007532] [G loss: -0.028448] [d1 loss: 0.040254] [d2 loss: 0.051495]  [sq d1 d2: 0.000126]  [num0: 14.000000] [num1 50.000000]
[Epoch 209/500] [Batch 640/676] [D loss: -0.019032] [G loss: -0.005578] [d1 loss: 0.061869] [d2 loss: 0.057656]  [sq d1 d2: 0.000018]  [num0: 20.000000] [num1 44.000000]
[Epoch 209/500] [Batch 660/676] [D loss: -0.026750] [G loss: 0.046587] [d1 loss: 0.265793] [d2 loss: 0.164773]  [sq d1 d2: 0.010205]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 0/676] [D loss: -0.027058] [G loss: 0.118232] [d1 loss: 0.200775] [d2 loss: 0.192831]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 20/676] [D loss: -0.049648] [G loss: 0.165011] [d1 loss: 0.071800] [d2 loss: 0.072951]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 40/676] [D loss: -0.051453] [G loss: 0.200099] [d1 loss: 0.119562] [d2 loss: 0.098664]  [sq d1 d2: 0.000437]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 60/676] [D loss: -0.046945] [G loss: 0.199378] [d1 loss: 0.063081] [d2 loss: 0.069804]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 80/676] [D loss: -0.049124] [G loss: 0.227239] [d1 loss: 0.074334] [d2 loss: 0.079363]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 100/676] [D loss: -0.005635] [G loss: 0.249532] [d1 loss: 0.108990] [d2 loss: 0.087551]  [sq d1 d2: 0.000460]  [num0: 13.000000] [num1 51.000000]
[Epoch 210/500] [Batch 120/676] [D loss: -0.022685] [G loss: 0.226078] [d1 loss: 0.064512] [d2 loss: 0.092446]  [sq d1 d2: 0.000780]  [num0: 19.000000] [num1 45.000000]
[Epoch 210/500] [Batch 140/676] [D loss: 0.013440] [G loss: 0.238704] [d1 loss: 0.052778] [d2 loss: 0.049833]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 210/500] [Batch 160/676] [D loss: 0.009514] [G loss: 0.161753] [d1 loss: 0.063776] [d2 loss: 0.053413]  [sq d1 d2: 0.000107]  [num0: 19.000000] [num1 45.000000]
[Epoch 210/500] [Batch 180/676] [D loss: 0.023178] [G loss: 0.089659] [d1 loss: 0.085465] [d2 loss: 0.051700]  [sq d1 d2: 0.001140]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 200/676] [D loss: 0.004250] [G loss: 0.050705] [d1 loss: 0.164305] [d2 loss: 0.152598]  [sq d1 d2: 0.000137]  [num0: 19.000000] [num1 45.000000]
[Epoch 210/500] [Batch 220/676] [D loss: 0.001616] [G loss: -0.018925] [d1 loss: 0.065699] [d2 loss: 0.062334]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 240/676] [D loss: -0.007051] [G loss: -0.087381] [d1 loss: 0.089221] [d2 loss: 0.092787]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 260/676] [D loss: -0.015142] [G loss: -0.123450] [d1 loss: 0.058951] [d2 loss: 0.067917]  [sq d1 d2: 0.000080]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 280/676] [D loss: -0.009790] [G loss: -0.160654] [d1 loss: 0.061122] [d2 loss: 0.078049]  [sq d1 d2: 0.000287]  [num0: 17.000000] [num1 47.000000]
[Epoch 210/500] [Batch 300/676] [D loss: -0.018446] [G loss: -0.216087] [d1 loss: 0.153468] [d2 loss: 0.153719]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 320/676] [D loss: -0.042835] [G loss: -0.290156] [d1 loss: 0.172296] [d2 loss: 0.166982]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 340/676] [D loss: -0.062215] [G loss: -0.295348] [d1 loss: 0.139526] [d2 loss: 0.117971]  [sq d1 d2: 0.000465]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 360/676] [D loss: -0.041128] [G loss: -0.329252] [d1 loss: 0.105270] [d2 loss: 0.092990]  [sq d1 d2: 0.000151]  [num0: 17.000000] [num1 47.000000]
[Epoch 210/500] [Batch 380/676] [D loss: -0.053840] [G loss: -0.383180] [d1 loss: 0.063792] [d2 loss: 0.052733]  [sq d1 d2: 0.000122]  [num0: 14.000000] [num1 50.000000]
[Epoch 210/500] [Batch 400/676] [D loss: 0.003179] [G loss: -0.375743] [d1 loss: 0.115563] [d2 loss: 0.101268]  [sq d1 d2: 0.000204]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 420/676] [D loss: 0.003546] [G loss: -0.348617] [d1 loss: 0.046611] [d2 loss: 0.051074]  [sq d1 d2: 0.000020]  [num0: 9.000000] [num1 55.000000]
[Epoch 210/500] [Batch 440/676] [D loss: -0.003165] [G loss: -0.292011] [d1 loss: 0.099759] [d2 loss: 0.133510]  [sq d1 d2: 0.001139]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 460/676] [D loss: 0.000114] [G loss: -0.212210] [d1 loss: 0.339653] [d2 loss: 0.257637]  [sq d1 d2: 0.006727]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 480/676] [D loss: 0.022392] [G loss: -0.146003] [d1 loss: 0.058791] [d2 loss: 0.054777]  [sq d1 d2: 0.000016]  [num0: 20.000000] [num1 44.000000]
[Epoch 210/500] [Batch 500/676] [D loss: 0.007126] [G loss: -0.105330] [d1 loss: 0.071425] [d2 loss: 0.068696]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 520/676] [D loss: 0.001381] [G loss: -0.076995] [d1 loss: 0.108099] [d2 loss: 0.115803]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 210/500] [Batch 540/676] [D loss: -0.002835] [G loss: -0.061767] [d1 loss: 0.073935] [d2 loss: 0.072195]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 210/500] [Batch 560/676] [D loss: -0.003950] [G loss: -0.044672] [d1 loss: 0.099890] [d2 loss: 0.093332]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 580/676] [D loss: -0.021863] [G loss: -0.029734] [d1 loss: 0.089655] [d2 loss: 0.100332]  [sq d1 d2: 0.000114]  [num0: 17.000000] [num1 47.000000]
[Epoch 210/500] [Batch 600/676] [D loss: -0.016425] [G loss: 0.012664] [d1 loss: 0.169062] [d2 loss: 0.168771]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 210/500] [Batch 620/676] [D loss: -0.029593] [G loss: 0.056870] [d1 loss: 0.098633] [d2 loss: 0.077477]  [sq d1 d2: 0.000448]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 640/676] [D loss: -0.026464] [G loss: 0.122479] [d1 loss: 0.191851] [d2 loss: 0.137187]  [sq d1 d2: 0.002988]  [num0: 15.000000] [num1 49.000000]
[Epoch 210/500] [Batch 660/676] [D loss: -0.066453] [G loss: 0.179772] [d1 loss: 0.142461] [d2 loss: 0.129537]  [sq d1 d2: 0.000167]  [num0: 18.000000] [num1 46.000000]
[Epoch 211/500] [Batch 0/676] [D loss: -0.038482] [G loss: 0.184456] [d1 loss: 0.115206] [d2 loss: 0.117862]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 211/500] [Batch 20/676] [D loss: -0.040581] [G loss: 0.175154] [d1 loss: 0.078272] [d2 loss: 0.093519]  [sq d1 d2: 0.000232]  [num0: 20.000000] [num1 44.000000]
[Epoch 211/500] [Batch 40/676] [D loss: -0.014837] [G loss: 0.163256] [d1 loss: 0.050446] [d2 loss: 0.066355]  [sq d1 d2: 0.000253]  [num0: 15.000000] [num1 49.000000]
[Epoch 211/500] [Batch 60/676] [D loss: 0.038646] [G loss: 0.159226] [d1 loss: 0.094353] [d2 loss: 0.110165]  [sq d1 d2: 0.000250]  [num0: 17.000000] [num1 47.000000]
[Epoch 211/500] [Batch 80/676] [D loss: 0.035289] [G loss: 0.144571] [d1 loss: 0.063584] [d2 loss: 0.074982]  [sq d1 d2: 0.000130]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 100/676] [D loss: 0.011400] [G loss: 0.121097] [d1 loss: 0.129230] [d2 loss: 0.115267]  [sq d1 d2: 0.000195]  [num0: 14.000000] [num1 50.000000]
[Epoch 211/500] [Batch 120/676] [D loss: 0.009769] [G loss: 0.059609] [d1 loss: 0.069925] [d2 loss: 0.087683]  [sq d1 d2: 0.000315]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 140/676] [D loss: 0.002495] [G loss: 0.028821] [d1 loss: 0.067361] [d2 loss: 0.067142]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 211/500] [Batch 160/676] [D loss: -0.001925] [G loss: 0.019153] [d1 loss: 0.069405] [d2 loss: 0.102092]  [sq d1 d2: 0.001068]  [num0: 12.000000] [num1 52.000000]
[Epoch 211/500] [Batch 180/676] [D loss: -0.007493] [G loss: -0.023019] [d1 loss: 0.079452] [d2 loss: 0.091025]  [sq d1 d2: 0.000134]  [num0: 18.000000] [num1 46.000000]
[Epoch 211/500] [Batch 200/676] [D loss: -0.020727] [G loss: -0.039408] [d1 loss: 0.075854] [d2 loss: 0.075248]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 211/500] [Batch 220/676] [D loss: -0.039218] [G loss: -0.050233] [d1 loss: 0.081358] [d2 loss: 0.077177]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 211/500] [Batch 240/676] [D loss: -0.034440] [G loss: -0.060339] [d1 loss: 0.350413] [d2 loss: 0.273641]  [sq d1 d2: 0.005894]  [num0: 15.000000] [num1 49.000000]

[Epoch 211/500] [Batch 260/676] [D loss: -0.032684] [G loss: -0.122042] [d1 loss: 0.144919] [d2 loss: 0.144991]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 211/500] [Batch 280/676] [D loss: -0.022096] [G loss: -0.100051] [d1 loss: 0.104669] [d2 loss: 0.121741]  [sq d1 d2: 0.000291]  [num0: 14.000000] [num1 50.000000]
[Epoch 211/500] [Batch 300/676] [D loss: -0.038694] [G loss: -0.175537] [d1 loss: 0.090001] [d2 loss: 0.086733]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 211/500] [Batch 320/676] [D loss: -0.002466] [G loss: -0.161271] [d1 loss: 0.065800] [d2 loss: 0.049380]  [sq d1 d2: 0.000270]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 340/676] [D loss: 0.006783] [G loss: -0.224116] [d1 loss: 0.097528] [d2 loss: 0.102424]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 211/500] [Batch 360/676] [D loss: 0.011923] [G loss: -0.275792] [d1 loss: 0.061656] [d2 loss: 0.058704]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 211/500] [Batch 380/676] [D loss: 0.020338] [G loss: -0.254003] [d1 loss: 0.088362] [d2 loss: 0.091198]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 211/500] [Batch 400/676] [D loss: 0.006151] [G loss: -0.183557] [d1 loss: 0.066561] [d2 loss: 0.078129]  [sq d1 d2: 0.000134]  [num0: 14.000000] [num1 50.000000]
[Epoch 211/500] [Batch 420/676] [D loss: 0.005209] [G loss: -0.140069] [d1 loss: 0.075879] [d2 loss: 0.083742]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 440/676] [D loss: 0.003788] [G loss: -0.112703] [d1 loss: 0.066970] [d2 loss: 0.073454]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 211/500] [Batch 460/676] [D loss: -0.004461] [G loss: -0.078661] [d1 loss: 0.029017] [d2 loss: 0.031442]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 211/500] [Batch 480/676] [D loss: -0.004237] [G loss: -0.058324] [d1 loss: 0.169908] [d2 loss: 0.191846]  [sq d1 d2: 0.000481]  [num0: 20.000000] [num1 44.000000]
[Epoch 211/500] [Batch 500/676] [D loss: -0.012942] [G loss: -0.009943] [d1 loss: 0.076318] [d2 loss: 0.088012]  [sq d1 d2: 0.000137]  [num0: 19.000000] [num1 45.000000]
[Epoch 211/500] [Batch 520/676] [D loss: -0.013805] [G loss: 0.012291] [d1 loss: 0.052298] [d2 loss: 0.031795]  [sq d1 d2: 0.000420]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 540/676] [D loss: -0.017422] [G loss: 0.044699] [d1 loss: 0.199201] [d2 loss: 0.226516]  [sq d1 d2: 0.000746]  [num0: 15.000000] [num1 49.000000]
[Epoch 211/500] [Batch 560/676] [D loss: -0.015500] [G loss: 0.082561] [d1 loss: 0.093384] [d2 loss: 0.092623]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 211/500] [Batch 580/676] [D loss: -0.028126] [G loss: 0.121680] [d1 loss: 0.101811] [d2 loss: 0.134165]  [sq d1 d2: 0.001047]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 600/676] [D loss: -0.023920] [G loss: 0.139793] [d1 loss: 0.032662] [d2 loss: 0.026503]  [sq d1 d2: 0.000038]  [num0: 11.000000] [num1 53.000000]
[Epoch 211/500] [Batch 620/676] [D loss: -0.036289] [G loss: 0.176016] [d1 loss: 0.046821] [d2 loss: 0.047008]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 211/500] [Batch 640/676] [D loss: -0.025504] [G loss: 0.177092] [d1 loss: 0.085972] [d2 loss: 0.068280]  [sq d1 d2: 0.000313]  [num0: 16.000000] [num1 48.000000]
[Epoch 211/500] [Batch 660/676] [D loss: 0.006504] [G loss: 0.157369] [d1 loss: 0.094235] [d2 loss: 0.094378]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 0/676] [D loss: 0.029568] [G loss: 0.152281] [d1 loss: 0.098877] [d2 loss: 0.146884]  [sq d1 d2: 0.002305]  [num0: 13.000000] [num1 51.000000]
[Epoch 212/500] [Batch 20/676] [D loss: 0.014988] [G loss: 0.127916] [d1 loss: 0.034766] [d2 loss: 0.043043]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 40/676] [D loss: 0.007171] [G loss: 0.074729] [d1 loss: 0.135423] [d2 loss: 0.130038]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 60/676] [D loss: 0.006925] [G loss: 0.024372] [d1 loss: 0.072626] [d2 loss: 0.077546]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 80/676] [D loss: -0.000422] [G loss: -0.020760] [d1 loss: 0.107210] [d2 loss: 0.080465]  [sq d1 d2: 0.000715]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 100/676] [D loss: -0.006090] [G loss: -0.078669] [d1 loss: 0.112333] [d2 loss: 0.109054]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 212/500] [Batch 120/676] [D loss: -0.010822] [G loss: -0.126190] [d1 loss: 0.129319] [d2 loss: 0.146572]  [sq d1 d2: 0.000298]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 140/676] [D loss: -0.011252] [G loss: -0.148523] [d1 loss: 0.075488] [d2 loss: 0.077726]  [sq d1 d2: 0.000005]  [num0: 11.000000] [num1 53.000000]
[Epoch 212/500] [Batch 160/676] [D loss: -0.020760] [G loss: -0.170750] [d1 loss: 0.137059] [d2 loss: 0.139886]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 212/500] [Batch 180/676] [D loss: -0.020410] [G loss: -0.225159] [d1 loss: 0.083213] [d2 loss: 0.089391]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 212/500] [Batch 200/676] [D loss: -0.012938] [G loss: -0.233828] [d1 loss: 0.223385] [d2 loss: 0.147692]  [sq d1 d2: 0.005729]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 220/676] [D loss: -0.012978] [G loss: -0.254900] [d1 loss: 0.073775] [d2 loss: 0.066111]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 212/500] [Batch 240/676] [D loss: -0.013766] [G loss: -0.282876] [d1 loss: 0.119417] [d2 loss: 0.121633]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 212/500] [Batch 260/676] [D loss: -0.022274] [G loss: -0.263990] [d1 loss: 0.120723] [d2 loss: 0.116620]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 280/676] [D loss: -0.008842] [G loss: -0.253286] [d1 loss: 0.110099] [d2 loss: 0.123299]  [sq d1 d2: 0.000174]  [num0: 13.000000] [num1 51.000000]
[Epoch 212/500] [Batch 300/676] [D loss: -0.003683] [G loss: -0.257323] [d1 loss: 0.064368] [d2 loss: 0.064500]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 320/676] [D loss: 0.012166] [G loss: -0.232814] [d1 loss: 0.135630] [d2 loss: 0.107015]  [sq d1 d2: 0.000819]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 340/676] [D loss: 0.009794] [G loss: -0.164441] [d1 loss: 0.049381] [d2 loss: 0.049836]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 360/676] [D loss: -0.001583] [G loss: -0.132712] [d1 loss: 0.065587] [d2 loss: 0.032213]  [sq d1 d2: 0.001114]  [num0: 12.000000] [num1 52.000000]
[Epoch 212/500] [Batch 380/676] [D loss: -0.002683] [G loss: -0.104563] [d1 loss: 0.156001] [d2 loss: 0.150769]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 400/676] [D loss: -0.001566] [G loss: -0.070072] [d1 loss: 0.124121] [d2 loss: 0.085611]  [sq d1 d2: 0.001483]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 420/676] [D loss: -0.008632] [G loss: -0.058100] [d1 loss: 0.049175] [d2 loss: 0.048689]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 440/676] [D loss: -0.012599] [G loss: -0.042509] [d1 loss: 0.079207] [d2 loss: 0.061409]  [sq d1 d2: 0.000317]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 460/676] [D loss: -0.012538] [G loss: -0.019114] [d1 loss: 0.068783] [d2 loss: 0.062265]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 480/676] [D loss: 0.004743] [G loss: 0.018597] [d1 loss: 0.137531] [d2 loss: 0.112533]  [sq d1 d2: 0.000625]  [num0: 19.000000] [num1 45.000000]
[Epoch 212/500] [Batch 500/676] [D loss: -0.011480] [G loss: 0.060840] [d1 loss: 0.106588] [d2 loss: 0.098956]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 212/500] [Batch 520/676] [D loss: -0.012009] [G loss: 0.121796] [d1 loss: 0.149130] [d2 loss: 0.122047]  [sq d1 d2: 0.000733]  [num0: 16.000000] [num1 48.000000]
[Epoch 212/500] [Batch 540/676] [D loss: -0.011860] [G loss: 0.138657] [d1 loss: 0.133873] [d2 loss: 0.122742]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 560/676] [D loss: -0.008213] [G loss: 0.163087] [d1 loss: 0.089698] [d2 loss: 0.096574]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 580/676] [D loss: -0.020955] [G loss: 0.186395] [d1 loss: 0.078583] [d2 loss: 0.086649]  [sq d1 d2: 0.000065]  [num0: 20.000000] [num1 44.000000]
[Epoch 212/500] [Batch 600/676] [D loss: 0.014818] [G loss: 0.177011] [d1 loss: 0.046612] [d2 loss: 0.056350]  [sq d1 d2: 0.000095]  [num0: 16.000000] [num1 48.000000]

[Epoch 212/500] [Batch 620/676] [D loss: 0.001304] [G loss: 0.186406] [d1 loss: 0.133825] [d2 loss: 0.108510]  [sq d1 d2: 0.000641]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 640/676] [D loss: 0.004454] [G loss: 0.195842] [d1 loss: 0.116638] [d2 loss: 0.133743]  [sq d1 d2: 0.000293]  [num0: 15.000000] [num1 49.000000]
[Epoch 212/500] [Batch 660/676] [D loss: 0.004130] [G loss: 0.163525] [d1 loss: 0.099778] [d2 loss: 0.106727]  [sq d1 d2: 0.000048]  [num0: 19.000000] [num1 45.000000]
[Epoch 213/500] [Batch 0/676] [D loss: -0.002039] [G loss: 0.130640] [d1 loss: 0.099667] [d2 loss: 0.148903]  [sq d1 d2: 0.002424]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 20/676] [D loss: -0.001158] [G loss: 0.107546] [d1 loss: 0.070002] [d2 loss: 0.070959]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 213/500] [Batch 40/676] [D loss: -0.033905] [G loss: 0.075469] [d1 loss: 0.098946] [d2 loss: 0.107267]  [sq d1 d2: 0.000069]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 60/676] [D loss: -0.006796] [G loss: 0.066022] [d1 loss: 0.142838] [d2 loss: 0.134029]  [sq d1 d2: 0.000078]  [num0: 15.000000] [num1 49.000000]
[Epoch 213/500] [Batch 80/676] [D loss: -0.007780] [G loss: 0.025863] [d1 loss: 0.071798] [d2 loss: 0.074813]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 100/676] [D loss: -0.039449] [G loss: 0.009375] [d1 loss: 0.085701] [d2 loss: 0.094689]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 213/500] [Batch 120/676] [D loss: -0.013606] [G loss: 0.049347] [d1 loss: 0.125815] [d2 loss: 0.124201]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 140/676] [D loss: -0.038425] [G loss: -0.001943] [d1 loss: 0.189786] [d2 loss: 0.113288]  [sq d1 d2: 0.005852]  [num0: 12.000000] [num1 52.000000]
[Epoch 213/500] [Batch 160/676] [D loss: -0.012583] [G loss: -0.003539] [d1 loss: 0.040237] [d2 loss: 0.032446]  [sq d1 d2: 0.000061]  [num0: 11.000000] [num1 53.000000]
[Epoch 213/500] [Batch 180/676] [D loss: 0.011981] [G loss: -0.003901] [d1 loss: 0.193081] [d2 loss: 0.170708]  [sq d1 d2: 0.000501]  [num0: 19.000000] [num1 45.000000]
[Epoch 213/500] [Batch 200/676] [D loss: 0.017616] [G loss: 0.005079] [d1 loss: 0.131014] [d2 loss: 0.070528]  [sq d1 d2: 0.003659]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 220/676] [D loss: -0.011772] [G loss: 0.019693] [d1 loss: 0.067851] [d2 loss: 0.066156]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 213/500] [Batch 240/676] [D loss: 0.006095] [G loss: 0.027901] [d1 loss: 0.027084] [d2 loss: 0.040109]  [sq d1 d2: 0.000170]  [num0: 21.000000] [num1 43.000000]
[Epoch 213/500] [Batch 260/676] [D loss: 0.005799] [G loss: 0.027349] [d1 loss: 0.119692] [d2 loss: 0.096047]  [sq d1 d2: 0.000559]  [num0: 15.000000] [num1 49.000000]
[Epoch 213/500] [Batch 280/676] [D loss: -0.002231] [G loss: 0.037563] [d1 loss: 0.052150] [d2 loss: 0.040306]  [sq d1 d2: 0.000140]  [num0: 12.000000] [num1 52.000000]
[Epoch 213/500] [Batch 300/676] [D loss: 0.000433] [G loss: 0.065310] [d1 loss: 0.072163] [d2 loss: 0.068323]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 213/500] [Batch 320/676] [D loss: -0.002674] [G loss: 0.080885] [d1 loss: 0.051316] [d2 loss: 0.035604]  [sq d1 d2: 0.000247]  [num0: 17.000000] [num1 47.000000]
[Epoch 213/500] [Batch 340/676] [D loss: -0.012931] [G loss: 0.116246] [d1 loss: 0.059489] [d2 loss: 0.055994]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 213/500] [Batch 360/676] [D loss: -0.016593] [G loss: 0.170075] [d1 loss: 0.059885] [d2 loss: 0.070132]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 380/676] [D loss: -0.020537] [G loss: 0.188156] [d1 loss: 0.091995] [d2 loss: 0.105588]  [sq d1 d2: 0.000185]  [num0: 17.000000] [num1 47.000000]
[Epoch 213/500] [Batch 400/676] [D loss: -0.024154] [G loss: 0.201631] [d1 loss: 0.056004] [d2 loss: 0.074361]  [sq d1 d2: 0.000337]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 420/676] [D loss: 0.028433] [G loss: 0.177885] [d1 loss: 0.049428] [d2 loss: 0.041164]  [sq d1 d2: 0.000068]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 440/676] [D loss: 0.014483] [G loss: 0.123700] [d1 loss: 0.058065] [d2 loss: 0.052916]  [sq d1 d2: 0.000027]  [num0: 11.000000] [num1 53.000000]
[Epoch 213/500] [Batch 460/676] [D loss: 0.006585] [G loss: 0.109090] [d1 loss: 0.092781] [d2 loss: 0.081690]  [sq d1 d2: 0.000123]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 480/676] [D loss: 0.000416] [G loss: 0.071335] [d1 loss: 0.060925] [d2 loss: 0.057707]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 500/676] [D loss: -0.000738] [G loss: 0.069611] [d1 loss: 0.142532] [d2 loss: 0.123324]  [sq d1 d2: 0.000369]  [num0: 18.000000] [num1 46.000000]
[Epoch 213/500] [Batch 520/676] [D loss: 0.014009] [G loss: 0.033829] [d1 loss: 0.080175] [d2 loss: 0.077059]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 540/676] [D loss: -0.004467] [G loss: -0.009674] [d1 loss: 0.087341] [d2 loss: 0.076482]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 560/676] [D loss: -0.006609] [G loss: -0.044935] [d1 loss: 0.134087] [d2 loss: 0.121405]  [sq d1 d2: 0.000161]  [num0: 15.000000] [num1 49.000000]
[Epoch 213/500] [Batch 580/676] [D loss: -0.003854] [G loss: -0.071881] [d1 loss: 0.054912] [d2 loss: 0.051285]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 600/676] [D loss: -0.004634] [G loss: -0.124752] [d1 loss: 0.066700] [d2 loss: 0.067695]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 213/500] [Batch 620/676] [D loss: -0.010455] [G loss: -0.183258] [d1 loss: 0.120804] [d2 loss: 0.083870]  [sq d1 d2: 0.001364]  [num0: 13.000000] [num1 51.000000]
[Epoch 213/500] [Batch 640/676] [D loss: -0.027985] [G loss: -0.273909] [d1 loss: 0.079212] [d2 loss: 0.077299]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 213/500] [Batch 660/676] [D loss: -0.006467] [G loss: -0.365924] [d1 loss: 0.114594] [d2 loss: 0.122160]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 214/500] [Batch 0/676] [D loss: -0.033962] [G loss: -0.396485] [d1 loss: 0.134082] [d2 loss: 0.117073]  [sq d1 d2: 0.000289]  [num0: 16.000000] [num1 48.000000]
[Epoch 214/500] [Batch 20/676] [D loss: 0.011814] [G loss: -0.460555] [d1 loss: 0.099323] [d2 loss: 0.103074]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 214/500] [Batch 40/676] [D loss: -0.006299] [G loss: -0.460437] [d1 loss: 0.065037] [d2 loss: 0.064283]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 214/500] [Batch 60/676] [D loss: 0.004186] [G loss: -0.433041] [d1 loss: 0.170674] [d2 loss: 0.172766]  [sq d1 d2: 0.000004]  [num0: 21.000000] [num1 43.000000]
[Epoch 214/500] [Batch 80/676] [D loss: -0.014269] [G loss: -0.374239] [d1 loss: 0.270647] [d2 loss: 0.232698]  [sq d1 d2: 0.001440]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 100/676] [D loss: 0.007999] [G loss: -0.326658] [d1 loss: 0.047400] [d2 loss: 0.045433]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 120/676] [D loss: -0.004936] [G loss: -0.267685] [d1 loss: 0.062100] [d2 loss: 0.077513]  [sq d1 d2: 0.000238]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 140/676] [D loss: -0.002935] [G loss: -0.187330] [d1 loss: 0.148942] [d2 loss: 0.130597]  [sq d1 d2: 0.000337]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 160/676] [D loss: -0.017297] [G loss: -0.170559] [d1 loss: 0.085805] [d2 loss: 0.087639]  [sq d1 d2: 0.000003]  [num0: 21.000000] [num1 43.000000]
[Epoch 214/500] [Batch 180/676] [D loss: -0.003044] [G loss: -0.147713] [d1 loss: 0.054341] [d2 loss: 0.051747]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 200/676] [D loss: -0.019476] [G loss: -0.123787] [d1 loss: 0.049839] [d2 loss: 0.057755]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 214/500] [Batch 220/676] [D loss: -0.020148] [G loss: -0.084812] [d1 loss: 0.122218] [d2 loss: 0.111090]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 240/676] [D loss: -0.035130] [G loss: -0.067640] [d1 loss: 0.083254] [d2 loss: 0.100117]  [sq d1 d2: 0.000284]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 260/676] [D loss: -0.028258] [G loss: -0.054308] [d1 loss: 0.088273] [d2 loss: 0.093196]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 280/676] [D loss: -0.030000] [G loss: -0.057359] [d1 loss: 0.061156] [d2 loss: 0.059619]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]

[Epoch 214/500] [Batch 300/676] [D loss: 0.010489] [G loss: -0.017673] [d1 loss: 0.160479] [d2 loss: 0.128011]  [sq d1 d2: 0.001054]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 320/676] [D loss: 0.004499] [G loss: 0.036399] [d1 loss: 0.088079] [d2 loss: 0.086078]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 340/676] [D loss: 0.002777] [G loss: 0.028522] [d1 loss: 0.061071] [d2 loss: 0.066772]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 214/500] [Batch 360/676] [D loss: -0.000856] [G loss: 0.041857] [d1 loss: 0.071855] [d2 loss: 0.063491]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 380/676] [D loss: -0.005923] [G loss: 0.024747] [d1 loss: 0.063386] [d2 loss: 0.064447]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 214/500] [Batch 400/676] [D loss: -0.011495] [G loss: 0.022616] [d1 loss: 0.059755] [d2 loss: 0.067431]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 420/676] [D loss: -0.005900] [G loss: 0.050710] [d1 loss: 0.050035] [d2 loss: 0.054130]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 440/676] [D loss: -0.029179] [G loss: 0.025568] [d1 loss: 0.108066] [d2 loss: 0.092933]  [sq d1 d2: 0.000229]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 460/676] [D loss: -0.017139] [G loss: 0.007491] [d1 loss: 0.042453] [d2 loss: 0.052697]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 480/676] [D loss: -0.006005] [G loss: -0.012690] [d1 loss: 0.065943] [d2 loss: 0.062361]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 500/676] [D loss: 0.000347] [G loss: -0.030389] [d1 loss: 0.089302] [d2 loss: 0.070744]  [sq d1 d2: 0.000344]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 520/676] [D loss: -0.012738] [G loss: -0.042485] [d1 loss: 0.151426] [d2 loss: 0.128397]  [sq d1 d2: 0.000530]  [num0: 13.000000] [num1 51.000000]
[Epoch 214/500] [Batch 540/676] [D loss: -0.010216] [G loss: -0.046826] [d1 loss: 0.085008] [d2 loss: 0.079148]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 214/500] [Batch 560/676] [D loss: -0.006976] [G loss: -0.041760] [d1 loss: 0.048772] [d2 loss: 0.053425]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 214/500] [Batch 580/676] [D loss: 0.007999] [G loss: -0.049981] [d1 loss: 0.129724] [d2 loss: 0.086305]  [sq d1 d2: 0.001885]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 600/676] [D loss: -0.002449] [G loss: -0.010818] [d1 loss: 0.105733] [d2 loss: 0.076552]  [sq d1 d2: 0.000852]  [num0: 15.000000] [num1 49.000000]
[Epoch 214/500] [Batch 620/676] [D loss: 0.003849] [G loss: -0.014754] [d1 loss: 0.033999] [d2 loss: 0.037355]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 214/500] [Batch 640/676] [D loss: -0.001502] [G loss: 0.002592] [d1 loss: 0.067793] [d2 loss: 0.077657]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 214/500] [Batch 660/676] [D loss: -0.002492] [G loss: 0.026903] [d1 loss: 0.065136] [d2 loss: 0.082570]  [sq d1 d2: 0.000304]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 0/676] [D loss: 0.004733] [G loss: 0.058088] [d1 loss: 0.095937] [d2 loss: 0.113865]  [sq d1 d2: 0.000321]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 20/676] [D loss: -0.009655] [G loss: 0.087555] [d1 loss: 0.099632] [d2 loss: 0.088028]  [sq d1 d2: 0.000135]  [num0: 13.000000] [num1 51.000000]
[Epoch 215/500] [Batch 40/676] [D loss: -0.012841] [G loss: 0.139902] [d1 loss: 0.036708] [d2 loss: 0.038516]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 215/500] [Batch 60/676] [D loss: -0.019145] [G loss: 0.175116] [d1 loss: 0.052520] [d2 loss: 0.055852]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 80/676] [D loss: -0.020131] [G loss: 0.149635] [d1 loss: 0.092517] [d2 loss: 0.098489]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 215/500] [Batch 100/676] [D loss: -0.011903] [G loss: 0.181706] [d1 loss: 0.210683] [d2 loss: 0.232212]  [sq d1 d2: 0.000463]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 120/676] [D loss: -0.009584] [G loss: 0.207619] [d1 loss: 0.083893] [d2 loss: 0.071698]  [sq d1 d2: 0.000149]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 140/676] [D loss: 0.017662] [G loss: 0.217998] [d1 loss: 0.052218] [d2 loss: 0.057323]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 160/676] [D loss: -0.000097] [G loss: 0.186092] [d1 loss: 0.040679] [d2 loss: 0.036743]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 215/500] [Batch 180/676] [D loss: -0.000276] [G loss: 0.149520] [d1 loss: 0.036122] [d2 loss: 0.025440]  [sq d1 d2: 0.000114]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 200/676] [D loss: -0.003241] [G loss: 0.109417] [d1 loss: 0.028325] [d2 loss: 0.033638]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 220/676] [D loss: -0.008463] [G loss: 0.105603] [d1 loss: 0.052389] [d2 loss: 0.046025]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 240/676] [D loss: -0.036492] [G loss: 0.112368] [d1 loss: 0.275184] [d2 loss: 0.199788]  [sq d1 d2: 0.005685]  [num0: 20.000000] [num1 44.000000]
[Epoch 215/500] [Batch 260/676] [D loss: -0.032122] [G loss: 0.105364] [d1 loss: 0.119371] [d2 loss: 0.114800]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 215/500] [Batch 280/676] [D loss: -0.022674] [G loss: 0.069470] [d1 loss: 0.134672] [d2 loss: 0.080415]  [sq d1 d2: 0.002944]  [num0: 18.000000] [num1 46.000000]
[Epoch 215/500] [Batch 300/676] [D loss: -0.032910] [G loss: 0.019130] [d1 loss: 0.156244] [d2 loss: 0.148459]  [sq d1 d2: 0.000061]  [num0: 13.000000] [num1 51.000000]
[Epoch 215/500] [Batch 320/676] [D loss: -0.018394] [G loss: -0.005896] [d1 loss: 0.086542] [d2 loss: 0.076381]  [sq d1 d2: 0.000103]  [num0: 17.000000] [num1 47.000000]
[Epoch 215/500] [Batch 340/676] [D loss: -0.001116] [G loss: -0.041077] [d1 loss: 0.099349] [d2 loss: 0.105183]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 215/500] [Batch 360/676] [D loss: -0.009867] [G loss: -0.070767] [d1 loss: 0.180637] [d2 loss: 0.152047]  [sq d1 d2: 0.000817]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 380/676] [D loss: 0.002692] [G loss: -0.085993] [d1 loss: 0.041908] [d2 loss: 0.040026]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 215/500] [Batch 400/676] [D loss: -0.001991] [G loss: -0.095903] [d1 loss: 0.108076] [d2 loss: 0.102360]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 420/676] [D loss: -0.009887] [G loss: -0.097009] [d1 loss: 0.044512] [d2 loss: 0.044527]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 215/500] [Batch 440/676] [D loss: -0.008561] [G loss: -0.088233] [d1 loss: 0.051383] [d2 loss: 0.062643]  [sq d1 d2: 0.000127]  [num0: 19.000000] [num1 45.000000]
[Epoch 215/500] [Batch 460/676] [D loss: -0.011066] [G loss: -0.075625] [d1 loss: 0.075833] [d2 loss: 0.067908]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 215/500] [Batch 480/676] [D loss: -0.011632] [G loss: -0.071332] [d1 loss: 0.059623] [d2 loss: 0.055343]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 500/676] [D loss: -0.018454] [G loss: -0.075769] [d1 loss: 0.063715] [d2 loss: 0.072921]  [sq d1 d2: 0.000085]  [num0: 18.000000] [num1 46.000000]
[Epoch 215/500] [Batch 520/676] [D loss: -0.024818] [G loss: -0.068966] [d1 loss: 0.026917] [d2 loss: 0.038750]  [sq d1 d2: 0.000140]  [num0: 19.000000] [num1 45.000000]
[Epoch 215/500] [Batch 540/676] [D loss: -0.004242] [G loss: -0.103783] [d1 loss: 0.049592] [d2 loss: 0.046259]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 215/500] [Batch 560/676] [D loss: -0.007600] [G loss: -0.089544] [d1 loss: 0.078174] [d2 loss: 0.073326]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 215/500] [Batch 580/676] [D loss: 0.006680] [G loss: -0.062775] [d1 loss: 0.064322] [d2 loss: 0.054430]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]

[Epoch 215/500] [Batch 600/676] [D loss: -0.000769] [G loss: -0.051841] [d1 loss: 0.035385] [d2 loss: 0.040329]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 215/500] [Batch 620/676] [D loss: -0.006605] [G loss: -0.068041] [d1 loss: 0.079132] [d2 loss: 0.081648]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 215/500] [Batch 640/676] [D loss: 0.003438] [G loss: -0.060316] [d1 loss: 0.125249] [d2 loss: 0.104222]  [sq d1 d2: 0.000442]  [num0: 19.000000] [num1 45.000000]
[Epoch 215/500] [Batch 660/676] [D loss: -0.007713] [G loss: -0.052407] [d1 loss: 0.086511] [d2 loss: 0.071316]  [sq d1 d2: 0.000231]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 0/676] [D loss: -0.001508] [G loss: -0.059238] [d1 loss: 0.065746] [d2 loss: 0.052932]  [sq d1 d2: 0.000164]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 20/676] [D loss: -0.006735] [G loss: -0.053972] [d1 loss: 0.093694] [d2 loss: 0.075117]  [sq d1 d2: 0.000345]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 40/676] [D loss: -0.004500] [G loss: -0.063767] [d1 loss: 0.054657] [d2 loss: 0.059080]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 216/500] [Batch 60/676] [D loss: -0.011284] [G loss: -0.083243] [d1 loss: 0.067642] [d2 loss: 0.067270]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 80/676] [D loss: -0.009133] [G loss: -0.115541] [d1 loss: 0.117627] [d2 loss: 0.108448]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 100/676] [D loss: -0.002011] [G loss: -0.151938] [d1 loss: 0.086404] [d2 loss: 0.085688]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 216/500] [Batch 120/676] [D loss: -0.023867] [G loss: -0.209447] [d1 loss: 0.068832] [d2 loss: 0.066672]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 140/676] [D loss: -0.024093] [G loss: -0.234465] [d1 loss: 0.098796] [d2 loss: 0.085348]  [sq d1 d2: 0.000181]  [num0: 17.000000] [num1 47.000000]
[Epoch 216/500] [Batch 160/676] [D loss: 0.015650] [G loss: -0.209308] [d1 loss: 0.091756] [d2 loss: 0.075810]  [sq d1 d2: 0.000254]  [num0: 17.000000] [num1 47.000000]
[Epoch 216/500] [Batch 180/676] [D loss: -0.027503] [G loss: -0.237265] [d1 loss: 0.052967] [d2 loss: 0.055581]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 216/500] [Batch 200/676] [D loss: 0.004907] [G loss: -0.224296] [d1 loss: 0.100878] [d2 loss: 0.104156]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 216/500] [Batch 220/676] [D loss: 0.005623] [G loss: -0.277017] [d1 loss: 0.100544] [d2 loss: 0.105718]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 216/500] [Batch 240/676] [D loss: -0.008147] [G loss: -0.234123] [d1 loss: 0.079704] [d2 loss: 0.082193]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 260/676] [D loss: -0.001189] [G loss: -0.247886] [d1 loss: 0.041703] [d2 loss: 0.040479]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 280/676] [D loss: -0.002603] [G loss: -0.153732] [d1 loss: 0.047182] [d2 loss: 0.046960]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 300/676] [D loss: -0.004848] [G loss: -0.138248] [d1 loss: 0.051612] [d2 loss: 0.038153]  [sq d1 d2: 0.000181]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 320/676] [D loss: -0.000106] [G loss: -0.128635] [d1 loss: 0.079321] [d2 loss: 0.088391]  [sq d1 d2: 0.000082]  [num0: 12.000000] [num1 52.000000]
[Epoch 216/500] [Batch 340/676] [D loss: -0.010541] [G loss: -0.111029] [d1 loss: 0.068138] [d2 loss: 0.071329]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 360/676] [D loss: -0.004991] [G loss: -0.082965] [d1 loss: 0.086568] [d2 loss: 0.110260]  [sq d1 d2: 0.000561]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 380/676] [D loss: -0.010418] [G loss: -0.070504] [d1 loss: 0.052262] [d2 loss: 0.048270]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 216/500] [Batch 400/676] [D loss: -0.009255] [G loss: -0.054443] [d1 loss: 0.083379] [d2 loss: 0.089994]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 420/676] [D loss: -0.011137] [G loss: -0.045732] [d1 loss: 0.049890] [d2 loss: 0.048870]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 440/676] [D loss: -0.015286] [G loss: -0.049292] [d1 loss: 0.032720] [d2 loss: 0.029395]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 216/500] [Batch 460/676] [D loss: -0.007748] [G loss: 0.017390] [d1 loss: 0.109116] [d2 loss: 0.119069]  [sq d1 d2: 0.000099]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 480/676] [D loss: -0.007312] [G loss: 0.059286] [d1 loss: 0.059351] [d2 loss: 0.057173]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 216/500] [Batch 500/676] [D loss: -0.022206] [G loss: 0.088087] [d1 loss: 0.072799] [d2 loss: 0.064359]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 216/500] [Batch 520/676] [D loss: -0.004990] [G loss: 0.107067] [d1 loss: 0.139227] [d2 loss: 0.187342]  [sq d1 d2: 0.002315]  [num0: 16.000000] [num1 48.000000]
[Epoch 216/500] [Batch 540/676] [D loss: -0.010070] [G loss: 0.134528] [d1 loss: 0.065136] [d2 loss: 0.063315]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 216/500] [Batch 560/676] [D loss: -0.002324] [G loss: 0.149218] [d1 loss: 0.071995] [d2 loss: 0.062378]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 216/500] [Batch 580/676] [D loss: -0.013377] [G loss: 0.194150] [d1 loss: 0.089486] [d2 loss: 0.076949]  [sq d1 d2: 0.000157]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 600/676] [D loss: -0.012536] [G loss: 0.182056] [d1 loss: 0.088721] [d2 loss: 0.089275]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 216/500] [Batch 620/676] [D loss: 0.022427] [G loss: 0.194834] [d1 loss: 0.138611] [d2 loss: 0.131055]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 216/500] [Batch 640/676] [D loss: -0.016042] [G loss: 0.189224] [d1 loss: 0.048603] [d2 loss: 0.052311]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 216/500] [Batch 660/676] [D loss: 0.001477] [G loss: 0.145401] [d1 loss: 0.072926] [d2 loss: 0.067693]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 217/500] [Batch 0/676] [D loss: -0.017261] [G loss: 0.140608] [d1 loss: 0.126776] [d2 loss: 0.090746]  [sq d1 d2: 0.001298]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 20/676] [D loss: 0.006841] [G loss: 0.138336] [d1 loss: 0.064017] [d2 loss: 0.076986]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]
[Epoch 217/500] [Batch 40/676] [D loss: -0.016380] [G loss: 0.092102] [d1 loss: 0.078704] [d2 loss: 0.097689]  [sq d1 d2: 0.000360]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 60/676] [D loss: -0.003401] [G loss: 0.062631] [d1 loss: 0.112967] [d2 loss: 0.128687]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 80/676] [D loss: 0.007837] [G loss: 0.027723] [d1 loss: 0.154482] [d2 loss: 0.137370]  [sq d1 d2: 0.000293]  [num0: 21.000000] [num1 43.000000]
[Epoch 217/500] [Batch 100/676] [D loss: -0.010978] [G loss: 0.009587] [d1 loss: 0.116310] [d2 loss: 0.097850]  [sq d1 d2: 0.000341]  [num0: 19.000000] [num1 45.000000]
[Epoch 217/500] [Batch 120/676] [D loss: -0.025081] [G loss: -0.012985] [d1 loss: 0.056027] [d2 loss: 0.036102]  [sq d1 d2: 0.000397]  [num0: 14.000000] [num1 50.000000]
[Epoch 217/500] [Batch 140/676] [D loss: -0.027235] [G loss: 0.028495] [d1 loss: 0.068511] [d2 loss: 0.064214]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 217/500] [Batch 160/676] [D loss: 0.008817] [G loss: 0.015048] [d1 loss: 0.063413] [d2 loss: 0.055090]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 180/676] [D loss: -0.014884] [G loss: -0.018203] [d1 loss: 0.131818] [d2 loss: 0.119888]  [sq d1 d2: 0.000142]  [num0: 12.000000] [num1 52.000000]
[Epoch 217/500] [Batch 200/676] [D loss: -0.004593] [G loss: -0.013622] [d1 loss: 0.036030] [d2 loss: 0.030985]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 217/500] [Batch 220/676] [D loss: -0.014487] [G loss: 0.018337] [d1 loss: 0.017110] [d2 loss: 0.019266]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 240/676] [D loss: -0.006112] [G loss: 0.018117] [d1 loss: 0.066997] [d2 loss: 0.062438]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 217/500] [Batch 260/676] [D loss: -0.012863] [G loss: 0.041654] [d1 loss: 0.048521] [d2 loss: 0.043514]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]

[Epoch 217/500] [Batch 280/676] [D loss: 0.001915] [G loss: 0.023320] [d1 loss: 0.098199] [d2 loss: 0.087804]  [sq d1 d2: 0.000108]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 300/676] [D loss: -0.006593] [G loss: 0.033205] [d1 loss: 0.041532] [d2 loss: 0.035117]  [sq d1 d2: 0.000041]  [num0: 13.000000] [num1 51.000000]
[Epoch 217/500] [Batch 320/676] [D loss: -0.016616] [G loss: 0.047282] [d1 loss: 0.084852] [d2 loss: 0.083359]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 340/676] [D loss: -0.023764] [G loss: 0.058275] [d1 loss: 0.186060] [d2 loss: 0.163244]  [sq d1 d2: 0.000521]  [num0: 21.000000] [num1 43.000000]
[Epoch 217/500] [Batch 360/676] [D loss: -0.008818] [G loss: 0.077855] [d1 loss: 0.070845] [d2 loss: 0.052157]  [sq d1 d2: 0.000349]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 380/676] [D loss: -0.006335] [G loss: 0.072485] [d1 loss: 0.083083] [d2 loss: 0.062838]  [sq d1 d2: 0.000410]  [num0: 18.000000] [num1 46.000000]
[Epoch 217/500] [Batch 400/676] [D loss: -0.018624] [G loss: 0.048472] [d1 loss: 0.085803] [d2 loss: 0.068061]  [sq d1 d2: 0.000315]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 420/676] [D loss: 0.018685] [G loss: 0.057817] [d1 loss: 0.121731] [d2 loss: 0.110596]  [sq d1 d2: 0.000124]  [num0: 16.000000] [num1 48.000000]
[Epoch 217/500] [Batch 440/676] [D loss: -0.011061] [G loss: 0.045524] [d1 loss: 0.040913] [d2 loss: 0.039266]  [sq d1 d2: 0.000003]  [num0: 21.000000] [num1 43.000000]
[Epoch 217/500] [Batch 460/676] [D loss: -0.009915] [G loss: 0.038976] [d1 loss: 0.105125] [d2 loss: 0.076967]  [sq d1 d2: 0.000793]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 480/676] [D loss: 0.004697] [G loss: 0.034079] [d1 loss: 0.063875] [d2 loss: 0.078293]  [sq d1 d2: 0.000208]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 500/676] [D loss: -0.007491] [G loss: -0.001510] [d1 loss: 0.055591] [d2 loss: 0.035851]  [sq d1 d2: 0.000390]  [num0: 14.000000] [num1 50.000000]
[Epoch 217/500] [Batch 520/676] [D loss: -0.007173] [G loss: -0.033045] [d1 loss: 0.074768] [d2 loss: 0.075507]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 540/676] [D loss: 0.002659] [G loss: -0.046354] [d1 loss: 0.019435] [d2 loss: 0.017805]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 217/500] [Batch 560/676] [D loss: -0.017476] [G loss: -0.106107] [d1 loss: 0.057837] [d2 loss: 0.056761]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 217/500] [Batch 580/676] [D loss: -0.020351] [G loss: -0.103165] [d1 loss: 0.101716] [d2 loss: 0.101919]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 600/676] [D loss: -0.012326] [G loss: -0.137388] [d1 loss: 0.075652] [d2 loss: 0.057390]  [sq d1 d2: 0.000333]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 620/676] [D loss: -0.012964] [G loss: -0.195934] [d1 loss: 0.161355] [d2 loss: 0.142053]  [sq d1 d2: 0.000373]  [num0: 15.000000] [num1 49.000000]
[Epoch 217/500] [Batch 640/676] [D loss: -0.013629] [G loss: -0.249170] [d1 loss: 0.021237] [d2 loss: 0.019048]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 217/500] [Batch 660/676] [D loss: -0.007430] [G loss: -0.278380] [d1 loss: 0.081819] [d2 loss: 0.072495]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 0/676] [D loss: 0.009795] [G loss: -0.275230] [d1 loss: 0.088565] [d2 loss: 0.107122]  [sq d1 d2: 0.000344]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 20/676] [D loss: -0.019305] [G loss: -0.284400] [d1 loss: 0.111816] [d2 loss: 0.118830]  [sq d1 d2: 0.000049]  [num0: 19.000000] [num1 45.000000]
[Epoch 218/500] [Batch 40/676] [D loss: -0.026238] [G loss: -0.286978] [d1 loss: 0.067245] [d2 loss: 0.055469]  [sq d1 d2: 0.000139]  [num0: 18.000000] [num1 46.000000]
[Epoch 218/500] [Batch 60/676] [D loss: -0.013748] [G loss: -0.244143] [d1 loss: 0.092397] [d2 loss: 0.063534]  [sq d1 d2: 0.000833]  [num0: 20.000000] [num1 44.000000]
[Epoch 218/500] [Batch 80/676] [D loss: 0.000533] [G loss: -0.195445] [d1 loss: 0.043994] [d2 loss: 0.036326]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 100/676] [D loss: -0.005356] [G loss: -0.149820] [d1 loss: 0.034961] [d2 loss: 0.040403]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 120/676] [D loss: -0.007328] [G loss: -0.135870] [d1 loss: 0.089700] [d2 loss: 0.092460]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 140/676] [D loss: -0.015238] [G loss: -0.130938] [d1 loss: 0.162201] [d2 loss: 0.122870]  [sq d1 d2: 0.001547]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 160/676] [D loss: -0.020366] [G loss: -0.115646] [d1 loss: 0.041553] [d2 loss: 0.038061]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 180/676] [D loss: -0.023460] [G loss: -0.128545] [d1 loss: 0.116712] [d2 loss: 0.097631]  [sq d1 d2: 0.000364]  [num0: 13.000000] [num1 51.000000]
[Epoch 218/500] [Batch 200/676] [D loss: -0.006078] [G loss: -0.112300] [d1 loss: 0.041937] [d2 loss: 0.059960]  [sq d1 d2: 0.000325]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 220/676] [D loss: -0.006238] [G loss: -0.074652] [d1 loss: 0.130350] [d2 loss: 0.100394]  [sq d1 d2: 0.000897]  [num0: 12.000000] [num1 52.000000]
[Epoch 218/500] [Batch 240/676] [D loss: -0.008267] [G loss: -0.066769] [d1 loss: 0.102060] [d2 loss: 0.093321]  [sq d1 d2: 0.000076]  [num0: 11.000000] [num1 53.000000]
[Epoch 218/500] [Batch 260/676] [D loss: -0.026111] [G loss: -0.065309] [d1 loss: 0.053400] [d2 loss: 0.053720]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 218/500] [Batch 280/676] [D loss: -0.010726] [G loss: -0.076353] [d1 loss: 0.135355] [d2 loss: 0.130529]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 300/676] [D loss: -0.028803] [G loss: -0.085321] [d1 loss: 0.052876] [d2 loss: 0.059401]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 320/676] [D loss: -0.009710] [G loss: -0.061983] [d1 loss: 0.031286] [d2 loss: 0.031956]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 340/676] [D loss: -0.018031] [G loss: -0.052000] [d1 loss: 0.072611] [d2 loss: 0.058189]  [sq d1 d2: 0.000208]  [num0: 20.000000] [num1 44.000000]
[Epoch 218/500] [Batch 360/676] [D loss: -0.003102] [G loss: -0.068191] [d1 loss: 0.120401] [d2 loss: 0.071126]  [sq d1 d2: 0.002428]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 380/676] [D loss: -0.002714] [G loss: -0.044586] [d1 loss: 0.038268] [d2 loss: 0.056868]  [sq d1 d2: 0.000346]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 400/676] [D loss: -0.003655] [G loss: -0.027983] [d1 loss: 0.061450] [d2 loss: 0.056132]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 420/676] [D loss: -0.002309] [G loss: -0.020768] [d1 loss: 0.051468] [d2 loss: 0.055298]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 218/500] [Batch 440/676] [D loss: -0.007235] [G loss: -0.029683] [d1 loss: 0.043894] [d2 loss: 0.044376]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 460/676] [D loss: -0.005711] [G loss: -0.010948] [d1 loss: 0.077389] [d2 loss: 0.078420]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 480/676] [D loss: -0.025086] [G loss: -0.009477] [d1 loss: 0.039209] [d2 loss: 0.031241]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 500/676] [D loss: -0.013783] [G loss: -0.020940] [d1 loss: 0.155323] [d2 loss: 0.141780]  [sq d1 d2: 0.000183]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 520/676] [D loss: -0.033580] [G loss: -0.021552] [d1 loss: 0.052096] [d2 loss: 0.055370]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 218/500] [Batch 540/676] [D loss: 0.004142] [G loss: -0.055725] [d1 loss: 0.064518] [d2 loss: 0.088804]  [sq d1 d2: 0.000590]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 560/676] [D loss: 0.005082] [G loss: -0.054137] [d1 loss: 0.053384] [d2 loss: 0.046722]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 218/500] [Batch 580/676] [D loss: -0.010716] [G loss: -0.042925] [d1 loss: 0.041069] [d2 loss: 0.046009]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 218/500] [Batch 600/676] [D loss: 0.004449] [G loss: -0.066626] [d1 loss: 0.022944] [d2 loss: 0.022956]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 218/500] [Batch 620/676] [D loss: -0.007467] [G loss: -0.055878] [d1 loss: 0.118201] [d2 loss: 0.097672]  [sq d1 d2: 0.000421]  [num0: 16.000000] [num1 48.000000]

[Epoch 218/500] [Batch 640/676] [D loss: 0.001281] [G loss: -0.050597] [d1 loss: 0.061448] [d2 loss: 0.073137]  [sq d1 d2: 0.000137]  [num0: 17.000000] [num1 47.000000]
[Epoch 218/500] [Batch 660/676] [D loss: -0.013547] [G loss: -0.051355] [d1 loss: 0.079355] [d2 loss: 0.070255]  [sq d1 d2: 0.000083]  [num0: 19.000000] [num1 45.000000]
[Epoch 219/500] [Batch 0/676] [D loss: -0.028759] [G loss: -0.037188] [d1 loss: 0.043295] [d2 loss: 0.039895]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 20/676] [D loss: -0.006123] [G loss: -0.024225] [d1 loss: 0.061804] [d2 loss: 0.081695]  [sq d1 d2: 0.000396]  [num0: 14.000000] [num1 50.000000]
[Epoch 219/500] [Batch 40/676] [D loss: -0.028545] [G loss: 0.006151] [d1 loss: 0.118391] [d2 loss: 0.122117]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 60/676] [D loss: -0.002518] [G loss: -0.009089] [d1 loss: 0.069940] [d2 loss: 0.077795]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 219/500] [Batch 80/676] [D loss: -0.026362] [G loss: 0.002702] [d1 loss: 0.115649] [d2 loss: 0.115612]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 219/500] [Batch 100/676] [D loss: -0.012040] [G loss: 0.001669] [d1 loss: 0.080516] [d2 loss: 0.078828]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 219/500] [Batch 120/676] [D loss: -0.004565] [G loss: 0.031112] [d1 loss: 0.075019] [d2 loss: 0.116480]  [sq d1 d2: 0.001719]  [num0: 19.000000] [num1 45.000000]
[Epoch 219/500] [Batch 140/676] [D loss: -0.005245] [G loss: 0.037033] [d1 loss: 0.043240] [d2 loss: 0.035699]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 219/500] [Batch 160/676] [D loss: -0.021580] [G loss: 0.029822] [d1 loss: 0.046942] [d2 loss: 0.046141]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 219/500] [Batch 180/676] [D loss: -0.001598] [G loss: 0.024141] [d1 loss: 0.081272] [d2 loss: 0.069922]  [sq d1 d2: 0.000129]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 200/676] [D loss: 0.002278] [G loss: 0.034318] [d1 loss: 0.039935] [d2 loss: 0.046391]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 219/500] [Batch 220/676] [D loss: -0.006085] [G loss: 0.039300] [d1 loss: 0.042191] [d2 loss: 0.049583]  [sq d1 d2: 0.000055]  [num0: 20.000000] [num1 44.000000]
[Epoch 219/500] [Batch 240/676] [D loss: 0.006353] [G loss: 0.011870] [d1 loss: 0.100393] [d2 loss: 0.076564]  [sq d1 d2: 0.000568]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 260/676] [D loss: -0.016179] [G loss: -0.010761] [d1 loss: 0.045601] [d2 loss: 0.047124]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 280/676] [D loss: -0.011453] [G loss: -0.025475] [d1 loss: 0.050633] [d2 loss: 0.037936]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 300/676] [D loss: -0.028973] [G loss: -0.011680] [d1 loss: 0.029534] [d2 loss: 0.030215]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 219/500] [Batch 320/676] [D loss: -0.011597] [G loss: -0.042153] [d1 loss: 0.151435] [d2 loss: 0.130610]  [sq d1 d2: 0.000434]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 340/676] [D loss: 0.005094] [G loss: -0.047059] [d1 loss: 0.099461] [d2 loss: 0.089862]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 219/500] [Batch 360/676] [D loss: -0.014362] [G loss: -0.050394] [d1 loss: 0.104693] [d2 loss: 0.111961]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 219/500] [Batch 380/676] [D loss: -0.009722] [G loss: -0.085708] [d1 loss: 0.085595] [d2 loss: 0.089727]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 219/500] [Batch 400/676] [D loss: -0.001985] [G loss: -0.090260] [d1 loss: 0.052338] [d2 loss: 0.039388]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]
[Epoch 219/500] [Batch 420/676] [D loss: -0.011671] [G loss: -0.119225] [d1 loss: 0.048542] [d2 loss: 0.062659]  [sq d1 d2: 0.000199]  [num0: 14.000000] [num1 50.000000]
[Epoch 219/500] [Batch 440/676] [D loss: -0.006465] [G loss: -0.146908] [d1 loss: 0.059692] [d2 loss: 0.089414]  [sq d1 d2: 0.000883]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 460/676] [D loss: -0.006545] [G loss: -0.114422] [d1 loss: 0.017983] [d2 loss: 0.020870]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 219/500] [Batch 480/676] [D loss: -0.021835] [G loss: -0.140541] [d1 loss: 0.046529] [d2 loss: 0.040192]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 500/676] [D loss: -0.018182] [G loss: -0.165684] [d1 loss: 0.051433] [d2 loss: 0.037990]  [sq d1 d2: 0.000181]  [num0: 18.000000] [num1 46.000000]
[Epoch 219/500] [Batch 520/676] [D loss: -0.016979] [G loss: -0.159916] [d1 loss: 0.064979] [d2 loss: 0.073582]  [sq d1 d2: 0.000074]  [num0: 13.000000] [num1 51.000000]
[Epoch 219/500] [Batch 540/676] [D loss: -0.028258] [G loss: -0.154195] [d1 loss: 0.021828] [d2 loss: 0.018416]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 560/676] [D loss: -0.019493] [G loss: -0.153255] [d1 loss: 0.048320] [d2 loss: 0.039970]  [sq d1 d2: 0.000070]  [num0: 10.000000] [num1 54.000000]
[Epoch 219/500] [Batch 580/676] [D loss: -0.017521] [G loss: -0.138887] [d1 loss: 0.141343] [d2 loss: 0.104479]  [sq d1 d2: 0.001359]  [num0: 16.000000] [num1 48.000000]
[Epoch 219/500] [Batch 600/676] [D loss: -0.004585] [G loss: -0.150414] [d1 loss: 0.123796] [d2 loss: 0.142299]  [sq d1 d2: 0.000342]  [num0: 13.000000] [num1 51.000000]
[Epoch 219/500] [Batch 620/676] [D loss: -0.007943] [G loss: -0.116585] [d1 loss: 0.021272] [d2 loss: 0.040105]  [sq d1 d2: 0.000355]  [num0: 15.000000] [num1 49.000000]
[Epoch 219/500] [Batch 640/676] [D loss: -0.012370] [G loss: -0.091170] [d1 loss: 0.033377] [d2 loss: 0.031743]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 219/500] [Batch 660/676] [D loss: 0.003522] [G loss: -0.066800] [d1 loss: 0.059616] [d2 loss: 0.058682]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 220/500] [Batch 0/676] [D loss: -0.010980] [G loss: -0.056037] [d1 loss: 0.065167] [d2 loss: 0.066295]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 220/500] [Batch 20/676] [D loss: -0.020739] [G loss: -0.015326] [d1 loss: 0.066240] [d2 loss: 0.058312]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 220/500] [Batch 40/676] [D loss: 0.006621] [G loss: 0.009234] [d1 loss: 0.025115] [d2 loss: 0.023975]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 220/500] [Batch 60/676] [D loss: -0.009268] [G loss: 0.005812] [d1 loss: 0.064729] [d2 loss: 0.079238]  [sq d1 d2: 0.000211]  [num0: 12.000000] [num1 52.000000]
[Epoch 220/500] [Batch 80/676] [D loss: -0.021013] [G loss: 0.037341] [d1 loss: 0.049862] [d2 loss: 0.046358]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 220/500] [Batch 100/676] [D loss: -0.029874] [G loss: 0.033776] [d1 loss: 0.079011] [d2 loss: 0.076358]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 220/500] [Batch 120/676] [D loss: -0.002784] [G loss: 0.044959] [d1 loss: 0.095384] [d2 loss: 0.102430]  [sq d1 d2: 0.000050]  [num0: 19.000000] [num1 45.000000]
[Epoch 220/500] [Batch 140/676] [D loss: -0.016000] [G loss: 0.075724] [d1 loss: 0.072625] [d2 loss: 0.069021]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 220/500] [Batch 160/676] [D loss: -0.010927] [G loss: 0.066071] [d1 loss: 0.046417] [d2 loss: 0.030050]  [sq d1 d2: 0.000268]  [num0: 16.000000] [num1 48.000000]
[Epoch 220/500] [Batch 180/676] [D loss: -0.012989] [G loss: 0.062897] [d1 loss: 0.036051] [d2 loss: 0.031029]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 220/500] [Batch 200/676] [D loss: -0.010104] [G loss: 0.063253] [d1 loss: 0.115727] [d2 loss: 0.124237]  [sq d1 d2: 0.000072]  [num0: 15.000000] [num1 49.000000]
[Epoch 220/500] [Batch 220/676] [D loss: -0.013384] [G loss: 0.043192] [d1 loss: 0.065172] [d2 loss: 0.064364]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 220/500] [Batch 240/676] [D loss: -0.003359] [G loss: 0.006902] [d1 loss: 0.124429] [d2 loss: 0.137456]  [sq d1 d2: 0.000170]  [num0: 14.000000] [num1 50.000000]
[Epoch 220/500] [Batch 260/676] [D loss: -0.011873] [G loss: 0.000873] [d1 loss: 0.046405] [d2 loss: 0.047787]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 220/500] [Batch 280/676] [D loss: -0.016310] [G loss: 0.012592] [d1 loss: 0.079332] [d2 loss: 0.082286]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 220/500] [Batch 300/676] [D loss: -0.014576] [G loss: -0.014164] [d1 loss: 0.057372] [d2 loss: 0.089563]  [sq d1 d2: 0.001036]  [num0: 14.000000] [num1 50.000000]

[Epoch 220/500] [Batch 320/676] [D loss: -0.013476] [G loss: 0.021492] [d1 loss: 0.056689] [d2 loss: 0.051861]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 220/500] [Batch 340/676] [D loss: -0.023446] [G loss: 0.008106] [d1 loss: 0.157669] [d2 loss: 0.116393]  [sq d1 d2: 0.001704]  [num0: 19.000000] [num1 45.000000]
[Epoch 220/500] [Batch 360/676] [D loss: -0.023334] [G loss: 0.021231] [d1 loss: 0.031988] [d2 loss: 0.035574]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 220/500] [Batch 380/676] [D loss: -0.014849] [G loss: -0.014655] [d1 loss: 0.093849] [d2 loss: 0.088588]  [sq d1 d2: 0.000028]  [num0: 12.000000] [num1 52.000000]
[Epoch 220/500] [Batch 400/676] [D loss: -0.020660] [G loss: -0.049029] [d1 loss: 0.088106] [d2 loss: 0.080408]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 220/500] [Batch 420/676] [D loss: -0.008322] [G loss: -0.045625] [d1 loss: 0.056880] [d2 loss: 0.066974]  [sq d1 d2: 0.000102]  [num0: 17.000000] [num1 47.000000]
[Epoch 220/500] [Batch 440/676] [D loss: -0.010388] [G loss: -0.034384] [d1 loss: 0.054993] [d2 loss: 0.063565]  [sq d1 d2: 0.000073]  [num0: 17.000000] [num1 47.000000]
[Epoch 220/500] [Batch 460/676] [D loss: -0.004516] [G loss: -0.048677] [d1 loss: 0.023028] [d2 loss: 0.021475]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 220/500] [Batch 480/676] [D loss: -0.006866] [G loss: -0.056586] [d1 loss: 0.055385] [d2 loss: 0.072089]  [sq d1 d2: 0.000279]  [num0: 15.000000] [num1 49.000000]
[Epoch 220/500] [Batch 500/676] [D loss: -0.012131] [G loss: -0.052065] [d1 loss: 0.087050] [d2 loss: 0.080833]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 220/500] [Batch 520/676] [D loss: -0.019698] [G loss: -0.049607] [d1 loss: 0.012844] [d2 loss: 0.014673]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 220/500] [Batch 540/676] [D loss: -0.018250] [G loss: -0.068355] [d1 loss: 0.078449] [d2 loss: 0.095101]  [sq d1 d2: 0.000277]  [num0: 15.000000] [num1 49.000000]
[Epoch 220/500] [Batch 560/676] [D loss: -0.013119] [G loss: -0.071133] [d1 loss: 0.057658] [d2 loss: 0.046902]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 220/500] [Batch 580/676] [D loss: -0.031427] [G loss: -0.093810] [d1 loss: 0.031375] [d2 loss: 0.030626]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 220/500] [Batch 600/676] [D loss: -0.008700] [G loss: -0.124227] [d1 loss: 0.066274] [d2 loss: 0.062404]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 220/500] [Batch 620/676] [D loss: -0.011250] [G loss: -0.128776] [d1 loss: 0.076396] [d2 loss: 0.087223]  [sq d1 d2: 0.000117]  [num0: 9.000000] [num1 55.000000]
[Epoch 220/500] [Batch 640/676] [D loss: -0.015937] [G loss: -0.138693] [d1 loss: 0.029714] [d2 loss: 0.027566]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 220/500] [Batch 660/676] [D loss: -0.005491] [G loss: -0.128158] [d1 loss: 0.031301] [d2 loss: 0.026626]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 0/676] [D loss: 0.012090] [G loss: -0.117128] [d1 loss: 0.012241] [d2 loss: 0.008145]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 20/676] [D loss: 0.001048] [G loss: -0.085098] [d1 loss: 0.050310] [d2 loss: 0.044619]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 40/676] [D loss: -0.011704] [G loss: -0.084231] [d1 loss: 0.104546] [d2 loss: 0.148973]  [sq d1 d2: 0.001974]  [num0: 14.000000] [num1 50.000000]
[Epoch 221/500] [Batch 60/676] [D loss: -0.005727] [G loss: -0.071234] [d1 loss: 0.068503] [d2 loss: 0.076291]  [sq d1 d2: 0.000061]  [num0: 11.000000] [num1 53.000000]
[Epoch 221/500] [Batch 80/676] [D loss: -0.026631] [G loss: -0.078177] [d1 loss: 0.080053] [d2 loss: 0.105240]  [sq d1 d2: 0.000634]  [num0: 18.000000] [num1 46.000000]
[Epoch 221/500] [Batch 100/676] [D loss: -0.021784] [G loss: -0.068373] [d1 loss: 0.084120] [d2 loss: 0.090053]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 221/500] [Batch 120/676] [D loss: -0.026707] [G loss: -0.086738] [d1 loss: 0.074433] [d2 loss: 0.050956]  [sq d1 d2: 0.000551]  [num0: 14.000000] [num1 50.000000]
[Epoch 221/500] [Batch 140/676] [D loss: -0.023669] [G loss: -0.065814] [d1 loss: 0.085481] [d2 loss: 0.086934]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 221/500] [Batch 160/676] [D loss: -0.026110] [G loss: -0.065578] [d1 loss: 0.091545] [d2 loss: 0.093619]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 221/500] [Batch 180/676] [D loss: -0.016024] [G loss: -0.079832] [d1 loss: 0.199835] [d2 loss: 0.188200]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 200/676] [D loss: -0.017530] [G loss: -0.078232] [d1 loss: 0.035132] [d2 loss: 0.035062]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 220/676] [D loss: -0.005816] [G loss: -0.036233] [d1 loss: 0.090507] [d2 loss: 0.089203]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 240/676] [D loss: 0.003696] [G loss: -0.064103] [d1 loss: 0.046222] [d2 loss: 0.036031]  [sq d1 d2: 0.000104]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 260/676] [D loss: -0.005881] [G loss: -0.046421] [d1 loss: 0.092568] [d2 loss: 0.089417]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 280/676] [D loss: -0.001744] [G loss: -0.063880] [d1 loss: 0.041815] [d2 loss: 0.045169]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 300/676] [D loss: -0.014035] [G loss: -0.063242] [d1 loss: 0.094378] [d2 loss: 0.094558]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 221/500] [Batch 320/676] [D loss: -0.007022] [G loss: -0.052707] [d1 loss: 0.090409] [d2 loss: 0.109351]  [sq d1 d2: 0.000359]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 340/676] [D loss: -0.024031] [G loss: -0.064932] [d1 loss: 0.071961] [d2 loss: 0.083150]  [sq d1 d2: 0.000125]  [num0: 21.000000] [num1 43.000000]
[Epoch 221/500] [Batch 360/676] [D loss: -0.006336] [G loss: -0.076542] [d1 loss: 0.090917] [d2 loss: 0.076084]  [sq d1 d2: 0.000220]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 380/676] [D loss: -0.007365] [G loss: -0.060021] [d1 loss: 0.057506] [d2 loss: 0.046561]  [sq d1 d2: 0.000120]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 400/676] [D loss: -0.020751] [G loss: -0.096166] [d1 loss: 0.050729] [d2 loss: 0.058259]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 221/500] [Batch 420/676] [D loss: -0.012558] [G loss: -0.124506] [d1 loss: 0.099366] [d2 loss: 0.100274]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 440/676] [D loss: -0.008322] [G loss: -0.101864] [d1 loss: 0.046828] [d2 loss: 0.053183]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 460/676] [D loss: -0.016884] [G loss: -0.120655] [d1 loss: 0.084593] [d2 loss: 0.087059]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 480/676] [D loss: -0.020463] [G loss: -0.119916] [d1 loss: 0.063651] [d2 loss: 0.063987]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 500/676] [D loss: -0.004535] [G loss: -0.108870] [d1 loss: 0.033931] [d2 loss: 0.037997]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 221/500] [Batch 520/676] [D loss: -0.016885] [G loss: -0.092066] [d1 loss: 0.154653] [d2 loss: 0.122330]  [sq d1 d2: 0.001045]  [num0: 12.000000] [num1 52.000000]
[Epoch 221/500] [Batch 540/676] [D loss: -0.002755] [G loss: -0.055258] [d1 loss: 0.058620] [d2 loss: 0.056529]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 221/500] [Batch 560/676] [D loss: -0.017331] [G loss: -0.046902] [d1 loss: 0.047002] [d2 loss: 0.050780]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 580/676] [D loss: -0.020910] [G loss: -0.049952] [d1 loss: 0.040499] [d2 loss: 0.032987]  [sq d1 d2: 0.000056]  [num0: 11.000000] [num1 53.000000]
[Epoch 221/500] [Batch 600/676] [D loss: -0.017049] [G loss: -0.014110] [d1 loss: 0.049245] [d2 loss: 0.052273]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 221/500] [Batch 620/676] [D loss: 0.004858] [G loss: -0.042510] [d1 loss: 0.042400] [d2 loss: 0.050344]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 221/500] [Batch 640/676] [D loss: -0.020464] [G loss: -0.001545] [d1 loss: 0.050984] [d2 loss: 0.061478]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]

[Epoch 221/500] [Batch 660/676] [D loss: -0.015955] [G loss: 0.001030] [d1 loss: 0.064226] [d2 loss: 0.062850]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 0/676] [D loss: -0.006600] [G loss: 0.018259] [d1 loss: 0.056852] [d2 loss: 0.052181]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 222/500] [Batch 20/676] [D loss: -0.011359] [G loss: 0.001528] [d1 loss: 0.124839] [d2 loss: 0.125738]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 222/500] [Batch 40/676] [D loss: -0.013067] [G loss: 0.025109] [d1 loss: 0.045463] [d2 loss: 0.045566]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 222/500] [Batch 60/676] [D loss: -0.012590] [G loss: 0.020146] [d1 loss: 0.025412] [d2 loss: 0.028014]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 222/500] [Batch 80/676] [D loss: -0.031929] [G loss: 0.020969] [d1 loss: 0.086269] [d2 loss: 0.108867]  [sq d1 d2: 0.000511]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 100/676] [D loss: -0.016915] [G loss: 0.006086] [d1 loss: 0.051465] [d2 loss: 0.054083]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 222/500] [Batch 120/676] [D loss: -0.050557] [G loss: 0.004894] [d1 loss: 0.087494] [d2 loss: 0.084119]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 222/500] [Batch 140/676] [D loss: -0.004935] [G loss: -0.023925] [d1 loss: 0.044886] [d2 loss: 0.054560]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 160/676] [D loss: -0.001050] [G loss: -0.017398] [d1 loss: 0.128245] [d2 loss: 0.128738]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 222/500] [Batch 180/676] [D loss: -0.003429] [G loss: -0.028406] [d1 loss: 0.042194] [d2 loss: 0.057772]  [sq d1 d2: 0.000243]  [num0: 19.000000] [num1 45.000000]
[Epoch 222/500] [Batch 200/676] [D loss: 0.011611] [G loss: -0.067525] [d1 loss: 0.088898] [d2 loss: 0.080434]  [sq d1 d2: 0.000072]  [num0: 13.000000] [num1 51.000000]
[Epoch 222/500] [Batch 220/676] [D loss: -0.016110] [G loss: -0.069845] [d1 loss: 0.087832] [d2 loss: 0.083554]  [sq d1 d2: 0.000018]  [num0: 11.000000] [num1 53.000000]
[Epoch 222/500] [Batch 240/676] [D loss: -0.009126] [G loss: -0.090301] [d1 loss: 0.069839] [d2 loss: 0.062765]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 222/500] [Batch 260/676] [D loss: -0.012798] [G loss: -0.076519] [d1 loss: 0.127539] [d2 loss: 0.108150]  [sq d1 d2: 0.000376]  [num0: 17.000000] [num1 47.000000]
[Epoch 222/500] [Batch 280/676] [D loss: -0.004455] [G loss: -0.086071] [d1 loss: 0.073324] [d2 loss: 0.097177]  [sq d1 d2: 0.000569]  [num0: 14.000000] [num1 50.000000]
[Epoch 222/500] [Batch 300/676] [D loss: -0.005375] [G loss: -0.083029] [d1 loss: 0.059230] [d2 loss: 0.050646]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 222/500] [Batch 320/676] [D loss: -0.015614] [G loss: -0.112408] [d1 loss: 0.013758] [d2 loss: 0.012963]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 222/500] [Batch 340/676] [D loss: -0.007253] [G loss: -0.098612] [d1 loss: 0.020462] [d2 loss: 0.033233]  [sq d1 d2: 0.000163]  [num0: 13.000000] [num1 51.000000]
[Epoch 222/500] [Batch 360/676] [D loss: -0.023204] [G loss: -0.095012] [d1 loss: 0.028442] [d2 loss: 0.026116]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 380/676] [D loss: -0.019981] [G loss: -0.111798] [d1 loss: 0.103153] [d2 loss: 0.069388]  [sq d1 d2: 0.001140]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 400/676] [D loss: -0.034001] [G loss: -0.085672] [d1 loss: 0.072772] [d2 loss: 0.068062]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 222/500] [Batch 420/676] [D loss: -0.025502] [G loss: -0.082367] [d1 loss: 0.031588] [d2 loss: 0.032872]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 222/500] [Batch 440/676] [D loss: -0.011354] [G loss: -0.075690] [d1 loss: 0.047186] [d2 loss: 0.055868]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 222/500] [Batch 460/676] [D loss: -0.002899] [G loss: -0.054068] [d1 loss: 0.098556] [d2 loss: 0.093943]  [sq d1 d2: 0.000021]  [num0: 12.000000] [num1 52.000000]
[Epoch 222/500] [Batch 480/676] [D loss: -0.017156] [G loss: -0.058943] [d1 loss: 0.037056] [d2 loss: 0.043672]  [sq d1 d2: 0.000044]  [num0: 11.000000] [num1 53.000000]
[Epoch 222/500] [Batch 500/676] [D loss: -0.015297] [G loss: -0.054630] [d1 loss: 0.095013] [d2 loss: 0.140252]  [sq d1 d2: 0.002047]  [num0: 21.000000] [num1 43.000000]
[Epoch 222/500] [Batch 520/676] [D loss: -0.009127] [G loss: -0.070348] [d1 loss: 0.027584] [d2 loss: 0.026952]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 222/500] [Batch 540/676] [D loss: -0.012283] [G loss: -0.052815] [d1 loss: 0.048343] [d2 loss: 0.045285]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 222/500] [Batch 560/676] [D loss: -0.016143] [G loss: -0.044090] [d1 loss: 0.137112] [d2 loss: 0.104577]  [sq d1 d2: 0.001059]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 580/676] [D loss: -0.013110] [G loss: -0.046254] [d1 loss: 0.063124] [d2 loss: 0.063133]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 600/676] [D loss: -0.023095] [G loss: -0.071137] [d1 loss: 0.071822] [d2 loss: 0.067275]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 620/676] [D loss: -0.025272] [G loss: -0.072882] [d1 loss: 0.100079] [d2 loss: 0.086084]  [sq d1 d2: 0.000196]  [num0: 16.000000] [num1 48.000000]
[Epoch 222/500] [Batch 640/676] [D loss: -0.001661] [G loss: -0.036423] [d1 loss: 0.045222] [d2 loss: 0.065398]  [sq d1 d2: 0.000407]  [num0: 15.000000] [num1 49.000000]
[Epoch 222/500] [Batch 660/676] [D loss: -0.019848] [G loss: -0.039167] [d1 loss: 0.072893] [d2 loss: 0.072622]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 0/676] [D loss: -0.024308] [G loss: -0.054435] [d1 loss: 0.048938] [d2 loss: 0.050527]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 20/676] [D loss: -0.020808] [G loss: -0.049843] [d1 loss: 0.097655] [d2 loss: 0.082600]  [sq d1 d2: 0.000227]  [num0: 14.000000] [num1 50.000000]
[Epoch 223/500] [Batch 40/676] [D loss: 0.006175] [G loss: -0.067206] [d1 loss: 0.021380] [d2 loss: 0.023755]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 60/676] [D loss: -0.021177] [G loss: -0.119928] [d1 loss: 0.129402] [d2 loss: 0.114262]  [sq d1 d2: 0.000229]  [num0: 15.000000] [num1 49.000000]
[Epoch 223/500] [Batch 80/676] [D loss: -0.015614] [G loss: -0.091833] [d1 loss: 0.039632] [d2 loss: 0.039466]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 223/500] [Batch 100/676] [D loss: 0.011159] [G loss: -0.079249] [d1 loss: 0.121714] [d2 loss: 0.150182]  [sq d1 d2: 0.000810]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 120/676] [D loss: -0.020164] [G loss: -0.058072] [d1 loss: 0.019366] [d2 loss: 0.019928]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 223/500] [Batch 140/676] [D loss: -0.002425] [G loss: -0.046117] [d1 loss: 0.104560] [d2 loss: 0.104523]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 223/500] [Batch 160/676] [D loss: -0.018959] [G loss: -0.054728] [d1 loss: 0.147989] [d2 loss: 0.141433]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 180/676] [D loss: -0.017388] [G loss: -0.047902] [d1 loss: 0.039733] [d2 loss: 0.063007]  [sq d1 d2: 0.000542]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 200/676] [D loss: -0.002195] [G loss: -0.039387] [d1 loss: 0.114884] [d2 loss: 0.100456]  [sq d1 d2: 0.000208]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 220/676] [D loss: -0.016937] [G loss: -0.074839] [d1 loss: 0.082480] [d2 loss: 0.086213]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 240/676] [D loss: -0.007233] [G loss: -0.074990] [d1 loss: 0.071918] [d2 loss: 0.061823]  [sq d1 d2: 0.000102]  [num0: 16.000000] [num1 48.000000]
[Epoch 223/500] [Batch 260/676] [D loss: -0.031403] [G loss: -0.033137] [d1 loss: 0.052756] [d2 loss: 0.042623]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 223/500] [Batch 280/676] [D loss: 0.001747] [G loss: -0.043596] [d1 loss: 0.016075] [d2 loss: 0.028293]  [sq d1 d2: 0.000149]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 300/676] [D loss: -0.014702] [G loss: -0.030467] [d1 loss: 0.121128] [d2 loss: 0.118824]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]

[Epoch 223/500] [Batch 320/676] [D loss: -0.017082] [G loss: -0.043363] [d1 loss: 0.051094] [d2 loss: 0.054434]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 340/676] [D loss: 0.000310] [G loss: -0.071740] [d1 loss: 0.052033] [d2 loss: 0.052434]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 223/500] [Batch 360/676] [D loss: -0.002133] [G loss: -0.084064] [d1 loss: 0.067987] [d2 loss: 0.070697]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 223/500] [Batch 380/676] [D loss: -0.004920] [G loss: -0.064514] [d1 loss: 0.084117] [d2 loss: 0.066262]  [sq d1 d2: 0.000319]  [num0: 17.000000] [num1 47.000000]
[Epoch 223/500] [Batch 400/676] [D loss: 0.003003] [G loss: -0.090926] [d1 loss: 0.066020] [d2 loss: 0.049702]  [sq d1 d2: 0.000266]  [num0: 16.000000] [num1 48.000000]
[Epoch 223/500] [Batch 420/676] [D loss: 0.003696] [G loss: -0.095835] [d1 loss: 0.060074] [d2 loss: 0.061165]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 223/500] [Batch 440/676] [D loss: -0.019934] [G loss: -0.115356] [d1 loss: 0.069524] [d2 loss: 0.091539]  [sq d1 d2: 0.000485]  [num0: 16.000000] [num1 48.000000]
[Epoch 223/500] [Batch 460/676] [D loss: -0.019602] [G loss: -0.117576] [d1 loss: 0.119782] [d2 loss: 0.099292]  [sq d1 d2: 0.000420]  [num0: 19.000000] [num1 45.000000]
[Epoch 223/500] [Batch 480/676] [D loss: -0.005643] [G loss: -0.106332] [d1 loss: 0.060242] [d2 loss: 0.065075]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 500/676] [D loss: -0.024633] [G loss: -0.088002] [d1 loss: 0.032436] [d2 loss: 0.029843]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 223/500] [Batch 520/676] [D loss: -0.026709] [G loss: -0.103640] [d1 loss: 0.049087] [d2 loss: 0.056548]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 223/500] [Batch 540/676] [D loss: -0.002283] [G loss: -0.095037] [d1 loss: 0.043157] [d2 loss: 0.030729]  [sq d1 d2: 0.000154]  [num0: 14.000000] [num1 50.000000]
[Epoch 223/500] [Batch 560/676] [D loss: -0.037630] [G loss: -0.095459] [d1 loss: 0.122466] [d2 loss: 0.085540]  [sq d1 d2: 0.001364]  [num0: 14.000000] [num1 50.000000]
[Epoch 223/500] [Batch 580/676] [D loss: -0.005373] [G loss: -0.078319] [d1 loss: 0.041122] [d2 loss: 0.066745]  [sq d1 d2: 0.000657]  [num0: 18.000000] [num1 46.000000]
[Epoch 223/500] [Batch 600/676] [D loss: -0.005523] [G loss: -0.082579] [d1 loss: 0.064146] [d2 loss: 0.074090]  [sq d1 d2: 0.000099]  [num0: 12.000000] [num1 52.000000]
[Epoch 223/500] [Batch 620/676] [D loss: 0.004363] [G loss: -0.042606] [d1 loss: 0.044510] [d2 loss: 0.048291]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 223/500] [Batch 640/676] [D loss: 0.002677] [G loss: -0.039456] [d1 loss: 0.203661] [d2 loss: 0.200018]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 223/500] [Batch 660/676] [D loss: 0.005348] [G loss: -0.061257] [d1 loss: 0.075978] [d2 loss: 0.102659]  [sq d1 d2: 0.000712]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 0/676] [D loss: -0.005543] [G loss: -0.030031] [d1 loss: 0.106493] [d2 loss: 0.102876]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 224/500] [Batch 20/676] [D loss: -0.007584] [G loss: -0.090575] [d1 loss: 0.095390] [d2 loss: 0.106314]  [sq d1 d2: 0.000119]  [num0: 12.000000] [num1 52.000000]
[Epoch 224/500] [Batch 40/676] [D loss: 0.002717] [G loss: -0.079269] [d1 loss: 0.135253] [d2 loss: 0.098151]  [sq d1 d2: 0.001377]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 60/676] [D loss: -0.012904] [G loss: -0.101680] [d1 loss: 0.078117] [d2 loss: 0.091092]  [sq d1 d2: 0.000168]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 80/676] [D loss: -0.006085] [G loss: -0.121763] [d1 loss: 0.114373] [d2 loss: 0.103578]  [sq d1 d2: 0.000117]  [num0: 20.000000] [num1 44.000000]
[Epoch 224/500] [Batch 100/676] [D loss: -0.021451] [G loss: -0.140939] [d1 loss: 0.085495] [d2 loss: 0.083756]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 224/500] [Batch 120/676] [D loss: -0.000063] [G loss: -0.166466] [d1 loss: 0.128167] [d2 loss: 0.184264]  [sq d1 d2: 0.003147]  [num0: 19.000000] [num1 45.000000]
[Epoch 224/500] [Batch 140/676] [D loss: 0.000335] [G loss: -0.205324] [d1 loss: 0.101631] [d2 loss: 0.143391]  [sq d1 d2: 0.001744]  [num0: 20.000000] [num1 44.000000]
[Epoch 224/500] [Batch 160/676] [D loss: 0.004307] [G loss: -0.183249] [d1 loss: 0.077980] [d2 loss: 0.091839]  [sq d1 d2: 0.000192]  [num0: 13.000000] [num1 51.000000]
[Epoch 224/500] [Batch 180/676] [D loss: 0.005652] [G loss: -0.167513] [d1 loss: 0.056050] [d2 loss: 0.050922]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 200/676] [D loss: -0.002157] [G loss: -0.131684] [d1 loss: 0.055573] [d2 loss: 0.051637]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 224/500] [Batch 220/676] [D loss: 0.007014] [G loss: -0.116721] [d1 loss: 0.098441] [d2 loss: 0.091654]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 224/500] [Batch 240/676] [D loss: -0.000091] [G loss: -0.104017] [d1 loss: 0.118386] [d2 loss: 0.152032]  [sq d1 d2: 0.001132]  [num0: 18.000000] [num1 46.000000]
[Epoch 224/500] [Batch 260/676] [D loss: 0.001142] [G loss: -0.099623] [d1 loss: 0.118359] [d2 loss: 0.112036]  [sq d1 d2: 0.000040]  [num0: 20.000000] [num1 44.000000]
[Epoch 224/500] [Batch 280/676] [D loss: -0.014000] [G loss: -0.122653] [d1 loss: 0.116892] [d2 loss: 0.114830]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 224/500] [Batch 300/676] [D loss: -0.021540] [G loss: -0.122098] [d1 loss: 0.056155] [d2 loss: 0.056805]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 320/676] [D loss: -0.019310] [G loss: -0.138181] [d1 loss: 0.086774] [d2 loss: 0.068346]  [sq d1 d2: 0.000340]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 340/676] [D loss: -0.046063] [G loss: -0.145901] [d1 loss: 0.088258] [d2 loss: 0.088268]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 224/500] [Batch 360/676] [D loss: -0.020028] [G loss: -0.127255] [d1 loss: 0.107482] [d2 loss: 0.125500]  [sq d1 d2: 0.000325]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 380/676] [D loss: -0.008236] [G loss: -0.147637] [d1 loss: 0.079336] [d2 loss: 0.080427]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 400/676] [D loss: -0.018395] [G loss: -0.156122] [d1 loss: 0.052426] [d2 loss: 0.042738]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 420/676] [D loss: -0.004008] [G loss: -0.132443] [d1 loss: 0.185595] [d2 loss: 0.164289]  [sq d1 d2: 0.000454]  [num0: 16.000000] [num1 48.000000]
[Epoch 224/500] [Batch 440/676] [D loss: 0.011605] [G loss: -0.113876] [d1 loss: 0.065990] [d2 loss: 0.043169]  [sq d1 d2: 0.000521]  [num0: 17.000000] [num1 47.000000]
[Epoch 224/500] [Batch 460/676] [D loss: 0.002780] [G loss: -0.095783] [d1 loss: 0.082493] [d2 loss: 0.066085]  [sq d1 d2: 0.000269]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 480/676] [D loss: 0.015060] [G loss: -0.097687] [d1 loss: 0.094288] [d2 loss: 0.081552]  [sq d1 d2: 0.000162]  [num0: 14.000000] [num1 50.000000]
[Epoch 224/500] [Batch 500/676] [D loss: -0.005282] [G loss: -0.101600] [d1 loss: 0.098487] [d2 loss: 0.085208]  [sq d1 d2: 0.000176]  [num0: 18.000000] [num1 46.000000]
[Epoch 224/500] [Batch 520/676] [D loss: -0.014457] [G loss: -0.087393] [d1 loss: 0.042845] [d2 loss: 0.059853]  [sq d1 d2: 0.000289]  [num0: 18.000000] [num1 46.000000]
[Epoch 224/500] [Batch 540/676] [D loss: -0.019754] [G loss: -0.088299] [d1 loss: 0.055250] [d2 loss: 0.063140]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 224/500] [Batch 560/676] [D loss: -0.020076] [G loss: -0.111736] [d1 loss: 0.101924] [d2 loss: 0.088947]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]
[Epoch 224/500] [Batch 580/676] [D loss: -0.002984] [G loss: -0.119880] [d1 loss: 0.133202] [d2 loss: 0.148009]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 224/500] [Batch 600/676] [D loss: -0.038939] [G loss: -0.134587] [d1 loss: 0.060853] [d2 loss: 0.055770]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 224/500] [Batch 620/676] [D loss: -0.014332] [G loss: -0.120927] [d1 loss: 0.068318] [d2 loss: 0.056347]  [sq d1 d2: 0.000143]  [num0: 12.000000] [num1 52.000000]
[Epoch 224/500] [Batch 640/676] [D loss: -0.002813] [G loss: -0.131176] [d1 loss: 0.093030] [d2 loss: 0.093668]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 224/500] [Batch 660/676] [D loss: 0.014398] [G loss: -0.061097] [d1 loss: 0.082530] [d2 loss: 0.095613]  [sq d1 d2: 0.000171]  [num0: 12.000000] [num1 52.000000]

[Epoch 225/500] [Batch 0/676] [D loss: -0.004256] [G loss: -0.050683] [d1 loss: 0.080420] [d2 loss: 0.063364]  [sq d1 d2: 0.000291]  [num0: 13.000000] [num1 51.000000]
[Epoch 225/500] [Batch 20/676] [D loss: 0.007552] [G loss: -0.016397] [d1 loss: 0.157262] [d2 loss: 0.144091]  [sq d1 d2: 0.000173]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 40/676] [D loss: 0.003129] [G loss: 0.001482] [d1 loss: 0.070554] [d2 loss: 0.063791]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 60/676] [D loss: -0.000837] [G loss: -0.006728] [d1 loss: 0.024162] [d2 loss: 0.023622]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 225/500] [Batch 80/676] [D loss: -0.007267] [G loss: -0.020655] [d1 loss: 0.066649] [d2 loss: 0.070293]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 100/676] [D loss: -0.027619] [G loss: -0.030063] [d1 loss: 0.079253] [d2 loss: 0.096983]  [sq d1 d2: 0.000314]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 120/676] [D loss: -0.028083] [G loss: -0.048491] [d1 loss: 0.081823] [d2 loss: 0.083624]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 140/676] [D loss: -0.013294] [G loss: -0.060886] [d1 loss: 0.064356] [d2 loss: 0.077828]  [sq d1 d2: 0.000181]  [num0: 12.000000] [num1 52.000000]
[Epoch 225/500] [Batch 160/676] [D loss: -0.004391] [G loss: -0.085872] [d1 loss: 0.067826] [d2 loss: 0.072232]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 180/676] [D loss: -0.027517] [G loss: -0.091615] [d1 loss: 0.013236] [d2 loss: 0.012831]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 200/676] [D loss: 0.012345] [G loss: -0.098473] [d1 loss: 0.049572] [d2 loss: 0.054661]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 225/500] [Batch 220/676] [D loss: -0.008845] [G loss: -0.113326] [d1 loss: 0.052232] [d2 loss: 0.054187]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 225/500] [Batch 240/676] [D loss: 0.014641] [G loss: -0.095861] [d1 loss: 0.032795] [d2 loss: 0.028446]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 225/500] [Batch 260/676] [D loss: 0.007455] [G loss: -0.091472] [d1 loss: 0.038789] [d2 loss: 0.041218]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 225/500] [Batch 280/676] [D loss: 0.001367] [G loss: -0.096759] [d1 loss: 0.077506] [d2 loss: 0.065313]  [sq d1 d2: 0.000149]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 300/676] [D loss: -0.002763] [G loss: -0.083867] [d1 loss: 0.121291] [d2 loss: 0.135395]  [sq d1 d2: 0.000199]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 320/676] [D loss: -0.011144] [G loss: -0.100401] [d1 loss: 0.103751] [d2 loss: 0.088534]  [sq d1 d2: 0.000232]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 340/676] [D loss: -0.024721] [G loss: -0.110115] [d1 loss: 0.037237] [d2 loss: 0.044069]  [sq d1 d2: 0.000047]  [num0: 19.000000] [num1 45.000000]
[Epoch 225/500] [Batch 360/676] [D loss: -0.030862] [G loss: -0.100537] [d1 loss: 0.095076] [d2 loss: 0.076080]  [sq d1 d2: 0.000361]  [num0: 17.000000] [num1 47.000000]
[Epoch 225/500] [Batch 380/676] [D loss: -0.033478] [G loss: -0.127709] [d1 loss: 0.100599] [d2 loss: 0.115441]  [sq d1 d2: 0.000220]  [num0: 19.000000] [num1 45.000000]
[Epoch 225/500] [Batch 400/676] [D loss: -0.008869] [G loss: -0.131136] [d1 loss: 0.144166] [d2 loss: 0.141996]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 225/500] [Batch 420/676] [D loss: 0.002040] [G loss: -0.133439] [d1 loss: 0.133417] [d2 loss: 0.120881]  [sq d1 d2: 0.000157]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 440/676] [D loss: 0.011426] [G loss: -0.141024] [d1 loss: 0.158818] [d2 loss: 0.151137]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 460/676] [D loss: 0.004902] [G loss: -0.134557] [d1 loss: 0.072580] [d2 loss: 0.095670]  [sq d1 d2: 0.000533]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 480/676] [D loss: -0.012348] [G loss: -0.095247] [d1 loss: 0.036778] [d2 loss: 0.052273]  [sq d1 d2: 0.000240]  [num0: 17.000000] [num1 47.000000]
[Epoch 225/500] [Batch 500/676] [D loss: 0.005832] [G loss: -0.097944] [d1 loss: 0.048565] [d2 loss: 0.048377]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 225/500] [Batch 520/676] [D loss: -0.004810] [G loss: -0.073165] [d1 loss: 0.033162] [d2 loss: 0.036990]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 540/676] [D loss: -0.001743] [G loss: -0.053715] [d1 loss: 0.056863] [d2 loss: 0.051642]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 225/500] [Batch 560/676] [D loss: -0.007644] [G loss: -0.062942] [d1 loss: 0.066456] [d2 loss: 0.048805]  [sq d1 d2: 0.000312]  [num0: 15.000000] [num1 49.000000]
[Epoch 225/500] [Batch 580/676] [D loss: -0.019144] [G loss: -0.064772] [d1 loss: 0.080080] [d2 loss: 0.077091]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 600/676] [D loss: -0.030396] [G loss: -0.070584] [d1 loss: 0.089360] [d2 loss: 0.091924]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 620/676] [D loss: -0.027864] [G loss: -0.071275] [d1 loss: 0.082162] [d2 loss: 0.079820]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 225/500] [Batch 640/676] [D loss: -0.046290] [G loss: -0.061931] [d1 loss: 0.066135] [d2 loss: 0.044679]  [sq d1 d2: 0.000460]  [num0: 14.000000] [num1 50.000000]
[Epoch 225/500] [Batch 660/676] [D loss: -0.033541] [G loss: -0.096036] [d1 loss: 0.059858] [d2 loss: 0.048997]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 0/676] [D loss: 0.012256] [G loss: -0.093766] [d1 loss: 0.098409] [d2 loss: 0.065404]  [sq d1 d2: 0.001089]  [num0: 17.000000] [num1 47.000000]
[Epoch 226/500] [Batch 20/676] [D loss: 0.014114] [G loss: -0.111892] [d1 loss: 0.115456] [d2 loss: 0.103579]  [sq d1 d2: 0.000141]  [num0: 13.000000] [num1 51.000000]
[Epoch 226/500] [Batch 40/676] [D loss: 0.000406] [G loss: -0.091431] [d1 loss: 0.038942] [d2 loss: 0.032597]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 226/500] [Batch 60/676] [D loss: 0.008284] [G loss: -0.061553] [d1 loss: 0.059024] [d2 loss: 0.061472]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 80/676] [D loss: -0.007581] [G loss: -0.018253] [d1 loss: 0.159676] [d2 loss: 0.163122]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 226/500] [Batch 100/676] [D loss: -0.024465] [G loss: -0.001043] [d1 loss: 0.043376] [d2 loss: 0.040581]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 226/500] [Batch 120/676] [D loss: -0.021119] [G loss: -0.025553] [d1 loss: 0.060322] [d2 loss: 0.061091]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 226/500] [Batch 140/676] [D loss: -0.016434] [G loss: -0.008236] [d1 loss: 0.043355] [d2 loss: 0.055051]  [sq d1 d2: 0.000137]  [num0: 18.000000] [num1 46.000000]
[Epoch 226/500] [Batch 160/676] [D loss: -0.018535] [G loss: -0.022617] [d1 loss: 0.053901] [d2 loss: 0.053178]  [sq d1 d2: 0.000001]  [num0: 8.000000] [num1 56.000000]
[Epoch 226/500] [Batch 180/676] [D loss: -0.026277] [G loss: -0.048627] [d1 loss: 0.047977] [d2 loss: 0.043978]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 200/676] [D loss: -0.002335] [G loss: -0.105096] [d1 loss: 0.086959] [d2 loss: 0.112189]  [sq d1 d2: 0.000637]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 220/676] [D loss: -0.003734] [G loss: -0.067358] [d1 loss: 0.037628] [d2 loss: 0.042965]  [sq d1 d2: 0.000028]  [num0: 12.000000] [num1 52.000000]
[Epoch 226/500] [Batch 240/676] [D loss: 0.021854] [G loss: -0.068890] [d1 loss: 0.061353] [d2 loss: 0.052906]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 260/676] [D loss: -0.000299] [G loss: -0.047515] [d1 loss: 0.088265] [d2 loss: 0.053222]  [sq d1 d2: 0.001228]  [num0: 17.000000] [num1 47.000000]
[Epoch 226/500] [Batch 280/676] [D loss: -0.002103] [G loss: -0.048372] [d1 loss: 0.034435] [d2 loss: 0.036180]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 300/676] [D loss: -0.014742] [G loss: -0.038924] [d1 loss: 0.038908] [d2 loss: 0.044161]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 320/676] [D loss: -0.012334] [G loss: -0.052267] [d1 loss: 0.022578] [d2 loss: 0.021447]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 226/500] [Batch 340/676] [D loss: -0.032122] [G loss: -0.055147] [d1 loss: 0.069550] [d2 loss: 0.079436]  [sq d1 d2: 0.000098]  [num0: 13.000000] [num1 51.000000]

[Epoch 226/500] [Batch 360/676] [D loss: -0.061378] [G loss: -0.053128] [d1 loss: 0.038996] [d2 loss: 0.044221]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 380/676] [D loss: -0.044598] [G loss: -0.088160] [d1 loss: 0.030045] [d2 loss: 0.025419]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 400/676] [D loss: -0.022103] [G loss: -0.090963] [d1 loss: 0.116830] [d2 loss: 0.120554]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 226/500] [Batch 420/676] [D loss: -0.006496] [G loss: -0.126277] [d1 loss: 0.068591] [d2 loss: 0.051962]  [sq d1 d2: 0.000277]  [num0: 14.000000] [num1 50.000000]
[Epoch 226/500] [Batch 440/676] [D loss: 0.018376] [G loss: -0.156765] [d1 loss: 0.160778] [d2 loss: 0.156025]  [sq d1 d2: 0.000023]  [num0: 20.000000] [num1 44.000000]
[Epoch 226/500] [Batch 460/676] [D loss: 0.013262] [G loss: -0.145444] [d1 loss: 0.098083] [d2 loss: 0.103395]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 226/500] [Batch 480/676] [D loss: 0.006420] [G loss: -0.110145] [d1 loss: 0.092746] [d2 loss: 0.094629]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 500/676] [D loss: -0.007625] [G loss: -0.095883] [d1 loss: 0.058581] [d2 loss: 0.069614]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 520/676] [D loss: -0.010627] [G loss: -0.092568] [d1 loss: 0.109279] [d2 loss: 0.090615]  [sq d1 d2: 0.000348]  [num0: 19.000000] [num1 45.000000]
[Epoch 226/500] [Batch 540/676] [D loss: -0.047156] [G loss: -0.081704] [d1 loss: 0.021778] [d2 loss: 0.021644]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 560/676] [D loss: -0.042076] [G loss: -0.081105] [d1 loss: 0.068302] [d2 loss: 0.081449]  [sq d1 d2: 0.000173]  [num0: 20.000000] [num1 44.000000]
[Epoch 226/500] [Batch 580/676] [D loss: -0.019012] [G loss: -0.039043] [d1 loss: 0.074630] [d2 loss: 0.093334]  [sq d1 d2: 0.000350]  [num0: 16.000000] [num1 48.000000]
[Epoch 226/500] [Batch 600/676] [D loss: -0.038417] [G loss: -0.059904] [d1 loss: 0.057032] [d2 loss: 0.049321]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 226/500] [Batch 620/676] [D loss: 0.018089] [G loss: -0.058445] [d1 loss: 0.047173] [d2 loss: 0.067278]  [sq d1 d2: 0.000404]  [num0: 17.000000] [num1 47.000000]
[Epoch 226/500] [Batch 640/676] [D loss: 0.010890] [G loss: -0.065240] [d1 loss: 0.092191] [d2 loss: 0.099598]  [sq d1 d2: 0.000055]  [num0: 18.000000] [num1 46.000000]
[Epoch 226/500] [Batch 660/676] [D loss: 0.023264] [G loss: -0.095624] [d1 loss: 0.058072] [d2 loss: 0.049256]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 227/500] [Batch 0/676] [D loss: -0.006740] [G loss: -0.079725] [d1 loss: 0.042946] [d2 loss: 0.031772]  [sq d1 d2: 0.000125]  [num0: 14.000000] [num1 50.000000]
[Epoch 227/500] [Batch 20/676] [D loss: 0.010311] [G loss: -0.046863] [d1 loss: 0.026749] [d2 loss: 0.024958]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 40/676] [D loss: -0.005714] [G loss: -0.029412] [d1 loss: 0.039340] [d2 loss: 0.036558]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 227/500] [Batch 60/676] [D loss: -0.018966] [G loss: -0.018180] [d1 loss: 0.099521] [d2 loss: 0.108176]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 227/500] [Batch 80/676] [D loss: -0.029708] [G loss: -0.000236] [d1 loss: 0.142353] [d2 loss: 0.204367]  [sq d1 d2: 0.003846]  [num0: 18.000000] [num1 46.000000]
[Epoch 227/500] [Batch 100/676] [D loss: -0.037583] [G loss: 0.004824] [d1 loss: 0.043549] [d2 loss: 0.043188]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 227/500] [Batch 120/676] [D loss: -0.044902] [G loss: 0.004653] [d1 loss: 0.063327] [d2 loss: 0.069034]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 227/500] [Batch 140/676] [D loss: 0.026922] [G loss: -0.051561] [d1 loss: 0.074247] [d2 loss: 0.062274]  [sq d1 d2: 0.000143]  [num0: 15.000000] [num1 49.000000]
[Epoch 227/500] [Batch 160/676] [D loss: 0.007297] [G loss: -0.083766] [d1 loss: 0.071184] [d2 loss: 0.079297]  [sq d1 d2: 0.000066]  [num0: 20.000000] [num1 44.000000]
[Epoch 227/500] [Batch 180/676] [D loss: 0.031573] [G loss: -0.089897] [d1 loss: 0.084123] [d2 loss: 0.077392]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 227/500] [Batch 200/676] [D loss: 0.008174] [G loss: -0.083548] [d1 loss: 0.044109] [d2 loss: 0.049163]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 227/500] [Batch 220/676] [D loss: 0.007702] [G loss: -0.079705] [d1 loss: 0.076053] [d2 loss: 0.070375]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 240/676] [D loss: -0.005050] [G loss: -0.068494] [d1 loss: 0.063073] [d2 loss: 0.063195]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 227/500] [Batch 260/676] [D loss: -0.020254] [G loss: -0.051642] [d1 loss: 0.062256] [d2 loss: 0.055724]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 280/676] [D loss: -0.037266] [G loss: -0.091277] [d1 loss: 0.088464] [d2 loss: 0.062719]  [sq d1 d2: 0.000663]  [num0: 15.000000] [num1 49.000000]
[Epoch 227/500] [Batch 300/676] [D loss: -0.037515] [G loss: -0.088486] [d1 loss: 0.040840] [d2 loss: 0.042334]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 227/500] [Batch 320/676] [D loss: -0.033494] [G loss: -0.071792] [d1 loss: 0.153732] [d2 loss: 0.169273]  [sq d1 d2: 0.000242]  [num0: 13.000000] [num1 51.000000]
[Epoch 227/500] [Batch 340/676] [D loss: -0.018340] [G loss: -0.112749] [d1 loss: 0.099954] [d2 loss: 0.107484]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 227/500] [Batch 360/676] [D loss: -0.013081] [G loss: -0.129326] [d1 loss: 0.062177] [d2 loss: 0.074312]  [sq d1 d2: 0.000147]  [num0: 14.000000] [num1 50.000000]
[Epoch 227/500] [Batch 380/676] [D loss: 0.011463] [G loss: -0.142805] [d1 loss: 0.128397] [d2 loss: 0.125883]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 400/676] [D loss: 0.016738] [G loss: -0.106335] [d1 loss: 0.065612] [d2 loss: 0.068433]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 227/500] [Batch 420/676] [D loss: 0.004145] [G loss: -0.089540] [d1 loss: 0.105376] [d2 loss: 0.103228]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 440/676] [D loss: -0.004736] [G loss: -0.071373] [d1 loss: 0.069418] [d2 loss: 0.070205]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 227/500] [Batch 460/676] [D loss: -0.022606] [G loss: -0.067073] [d1 loss: 0.093595] [d2 loss: 0.082006]  [sq d1 d2: 0.000134]  [num0: 20.000000] [num1 44.000000]
[Epoch 227/500] [Batch 480/676] [D loss: -0.036068] [G loss: -0.044349] [d1 loss: 0.052908] [d2 loss: 0.056709]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 227/500] [Batch 500/676] [D loss: -0.049832] [G loss: -0.058810] [d1 loss: 0.071105] [d2 loss: 0.078131]  [sq d1 d2: 0.000049]  [num0: 12.000000] [num1 52.000000]
[Epoch 227/500] [Batch 520/676] [D loss: -0.056847] [G loss: -0.087827] [d1 loss: 0.115027] [d2 loss: 0.111943]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 227/500] [Batch 540/676] [D loss: -0.032190] [G loss: -0.111957] [d1 loss: 0.086920] [d2 loss: 0.090461]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 227/500] [Batch 560/676] [D loss: -0.023913] [G loss: -0.152121] [d1 loss: 0.035976] [d2 loss: 0.055587]  [sq d1 d2: 0.000385]  [num0: 13.000000] [num1 51.000000]
[Epoch 227/500] [Batch 580/676] [D loss: 0.018932] [G loss: -0.146171] [d1 loss: 0.176296] [d2 loss: 0.153978]  [sq d1 d2: 0.000498]  [num0: 17.000000] [num1 47.000000]
[Epoch 227/500] [Batch 600/676] [D loss: 0.007348] [G loss: -0.148700] [d1 loss: 0.079510] [d2 loss: 0.085757]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 227/500] [Batch 620/676] [D loss: 0.004288] [G loss: -0.123500] [d1 loss: 0.087053] [d2 loss: 0.078206]  [sq d1 d2: 0.000078]  [num0: 21.000000] [num1 43.000000]
[Epoch 227/500] [Batch 640/676] [D loss: 0.004757] [G loss: -0.079874] [d1 loss: 0.054111] [d2 loss: 0.058873]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 227/500] [Batch 660/676] [D loss: -0.012066] [G loss: -0.053629] [d1 loss: 0.064086] [d2 loss: 0.066337]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 228/500] [Batch 0/676] [D loss: -0.033482] [G loss: -0.025310] [d1 loss: 0.123185] [d2 loss: 0.139701]  [sq d1 d2: 0.000273]  [num0: 18.000000] [num1 46.000000]
[Epoch 228/500] [Batch 20/676] [D loss: -0.029210] [G loss: -0.001789] [d1 loss: 0.043332] [d2 loss: 0.049606]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]

[Epoch 228/500] [Batch 40/676] [D loss: -0.052055] [G loss: 0.045025] [d1 loss: 0.036984] [d2 loss: 0.047110]  [sq d1 d2: 0.000103]  [num0: 17.000000] [num1 47.000000]
[Epoch 228/500] [Batch 60/676] [D loss: -0.048852] [G loss: 0.032041] [d1 loss: 0.043747] [d2 loss: 0.050415]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 228/500] [Batch 80/676] [D loss: -0.081643] [G loss: 0.076791] [d1 loss: 0.124522] [d2 loss: 0.129337]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 228/500] [Batch 100/676] [D loss: 0.023181] [G loss: 0.064784] [d1 loss: 0.074967] [d2 loss: 0.080266]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 228/500] [Batch 120/676] [D loss: 0.037191] [G loss: 0.041727] [d1 loss: 0.067829] [d2 loss: 0.058296]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 228/500] [Batch 140/676] [D loss: 0.025086] [G loss: 0.045377] [d1 loss: 0.103705] [d2 loss: 0.090382]  [sq d1 d2: 0.000178]  [num0: 14.000000] [num1 50.000000]
[Epoch 228/500] [Batch 160/676] [D loss: 0.012240] [G loss: 0.021046] [d1 loss: 0.031369] [d2 loss: 0.030901]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 180/676] [D loss: -0.001419] [G loss: 0.001887] [d1 loss: 0.124624] [d2 loss: 0.105964]  [sq d1 d2: 0.000348]  [num0: 19.000000] [num1 45.000000]
[Epoch 228/500] [Batch 200/676] [D loss: -0.008969] [G loss: -0.002373] [d1 loss: 0.136879] [d2 loss: 0.139627]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 228/500] [Batch 220/676] [D loss: -0.038965] [G loss: 0.027137] [d1 loss: 0.072254] [d2 loss: 0.074004]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 228/500] [Batch 240/676] [D loss: -0.050897] [G loss: 0.035586] [d1 loss: 0.103915] [d2 loss: 0.095263]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 228/500] [Batch 260/676] [D loss: -0.044831] [G loss: -0.002654] [d1 loss: 0.087937] [d2 loss: 0.071640]  [sq d1 d2: 0.000266]  [num0: 18.000000] [num1 46.000000]
[Epoch 228/500] [Batch 280/676] [D loss: -0.038484] [G loss: -0.021150] [d1 loss: 0.092587] [d2 loss: 0.079104]  [sq d1 d2: 0.000182]  [num0: 19.000000] [num1 45.000000]
[Epoch 228/500] [Batch 300/676] [D loss: -0.039051] [G loss: -0.080016] [d1 loss: 0.042012] [d2 loss: 0.052417]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 228/500] [Batch 320/676] [D loss: -0.018669] [G loss: -0.156125] [d1 loss: 0.064243] [d2 loss: 0.075842]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 340/676] [D loss: 0.017499] [G loss: -0.125568] [d1 loss: 0.054256] [d2 loss: 0.051334]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 360/676] [D loss: 0.015571] [G loss: -0.089564] [d1 loss: 0.040367] [d2 loss: 0.037769]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 228/500] [Batch 380/676] [D loss: 0.003453] [G loss: -0.044876] [d1 loss: 0.053581] [d2 loss: 0.057687]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 400/676] [D loss: -0.007438] [G loss: 0.003282] [d1 loss: 0.056248] [d2 loss: 0.056363]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 228/500] [Batch 420/676] [D loss: -0.036950] [G loss: 0.061851] [d1 loss: 0.098126] [d2 loss: 0.114083]  [sq d1 d2: 0.000255]  [num0: 14.000000] [num1 50.000000]
[Epoch 228/500] [Batch 440/676] [D loss: -0.036628] [G loss: 0.127360] [d1 loss: 0.063241] [d2 loss: 0.052551]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 460/676] [D loss: -0.034931] [G loss: 0.162490] [d1 loss: 0.024104] [d2 loss: 0.027839]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 480/676] [D loss: -0.062730] [G loss: 0.160351] [d1 loss: 0.022985] [d2 loss: 0.024462]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 228/500] [Batch 500/676] [D loss: -0.059964] [G loss: 0.124848] [d1 loss: 0.065409] [d2 loss: 0.041502]  [sq d1 d2: 0.000572]  [num0: 14.000000] [num1 50.000000]
[Epoch 228/500] [Batch 520/676] [D loss: 0.031072] [G loss: 0.078516] [d1 loss: 0.065496] [d2 loss: 0.071221]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 540/676] [D loss: 0.041015] [G loss: 0.032332] [d1 loss: 0.050404] [d2 loss: 0.058118]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 560/676] [D loss: 0.011956] [G loss: 0.045211] [d1 loss: 0.051155] [d2 loss: 0.047307]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 228/500] [Batch 580/676] [D loss: 0.006809] [G loss: 0.052572] [d1 loss: 0.019769] [d2 loss: 0.020818]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 228/500] [Batch 600/676] [D loss: -0.015132] [G loss: 0.050278] [d1 loss: 0.041421] [d2 loss: 0.073373]  [sq d1 d2: 0.001021]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 620/676] [D loss: -0.056284] [G loss: -0.004796] [d1 loss: 0.220042] [d2 loss: 0.164557]  [sq d1 d2: 0.003079]  [num0: 15.000000] [num1 49.000000]
[Epoch 228/500] [Batch 640/676] [D loss: -0.047942] [G loss: -0.027050] [d1 loss: 0.050735] [d2 loss: 0.055216]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 228/500] [Batch 660/676] [D loss: -0.069184] [G loss: -0.055944] [d1 loss: 0.099619] [d2 loss: 0.079901]  [sq d1 d2: 0.000389]  [num0: 14.000000] [num1 50.000000]
[Epoch 229/500] [Batch 0/676] [D loss: -0.077140] [G loss: -0.080950] [d1 loss: 0.034214] [d2 loss: 0.033144]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 229/500] [Batch 20/676] [D loss: -0.029774] [G loss: -0.106743] [d1 loss: 0.043072] [d2 loss: 0.041708]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 40/676] [D loss: 0.056041] [G loss: -0.140514] [d1 loss: 0.063639] [d2 loss: 0.074266]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 60/676] [D loss: 0.025151] [G loss: -0.160256] [d1 loss: 0.080908] [d2 loss: 0.067607]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 80/676] [D loss: 0.029162] [G loss: -0.116926] [d1 loss: 0.062100] [d2 loss: 0.059755]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 100/676] [D loss: 0.008681] [G loss: -0.073012] [d1 loss: 0.048314] [d2 loss: 0.049323]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 229/500] [Batch 120/676] [D loss: -0.007405] [G loss: -0.033067] [d1 loss: 0.100550] [d2 loss: 0.079147]  [sq d1 d2: 0.000458]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 140/676] [D loss: -0.023916] [G loss: 0.012630] [d1 loss: 0.126819] [d2 loss: 0.103591]  [sq d1 d2: 0.000540]  [num0: 13.000000] [num1 51.000000]
[Epoch 229/500] [Batch 160/676] [D loss: -0.054229] [G loss: 0.095900] [d1 loss: 0.086967] [d2 loss: 0.076106]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 180/676] [D loss: -0.077780] [G loss: 0.120454] [d1 loss: 0.055319] [d2 loss: 0.043192]  [sq d1 d2: 0.000147]  [num0: 19.000000] [num1 45.000000]
[Epoch 229/500] [Batch 200/676] [D loss: -0.086959] [G loss: 0.143314] [d1 loss: 0.074448] [d2 loss: 0.080170]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 220/676] [D loss: -0.050723] [G loss: 0.086516] [d1 loss: 0.110201] [d2 loss: 0.102267]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 240/676] [D loss: 0.017384] [G loss: 0.098869] [d1 loss: 0.092831] [d2 loss: 0.119591]  [sq d1 d2: 0.000716]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 260/676] [D loss: 0.028235] [G loss: 0.074638] [d1 loss: 0.033591] [d2 loss: 0.032226]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 280/676] [D loss: 0.044250] [G loss: 0.039180] [d1 loss: 0.091676] [d2 loss: 0.070429]  [sq d1 d2: 0.000451]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 300/676] [D loss: 0.016700] [G loss: 0.019018] [d1 loss: 0.060538] [d2 loss: 0.065617]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 229/500] [Batch 320/676] [D loss: -0.000711] [G loss: 0.013519] [d1 loss: 0.046053] [d2 loss: 0.075229]  [sq d1 d2: 0.000851]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 340/676] [D loss: -0.034537] [G loss: 0.050392] [d1 loss: 0.116848] [d2 loss: 0.106352]  [sq d1 d2: 0.000110]  [num0: 13.000000] [num1 51.000000]
[Epoch 229/500] [Batch 360/676] [D loss: -0.037273] [G loss: 0.126814] [d1 loss: 0.067564] [d2 loss: 0.087586]  [sq d1 d2: 0.000401]  [num0: 16.000000] [num1 48.000000]
[Epoch 229/500] [Batch 380/676] [D loss: -0.101702] [G loss: 0.167476] [d1 loss: 0.109553] [d2 loss: 0.109782]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]

[Epoch 229/500] [Batch 400/676] [D loss: -0.074616] [G loss: 0.132567] [d1 loss: 0.159006] [d2 loss: 0.119269]  [sq d1 d2: 0.001579]  [num0: 21.000000] [num1 43.000000]
[Epoch 229/500] [Batch 420/676] [D loss: -0.062488] [G loss: 0.077246] [d1 loss: 0.114127] [d2 loss: 0.098529]  [sq d1 d2: 0.000243]  [num0: 13.000000] [num1 51.000000]
[Epoch 229/500] [Batch 440/676] [D loss: -0.052151] [G loss: 0.097394] [d1 loss: 0.116320] [d2 loss: 0.163391]  [sq d1 d2: 0.002216]  [num0: 13.000000] [num1 51.000000]
[Epoch 229/500] [Batch 460/676] [D loss: 0.024088] [G loss: 0.099057] [d1 loss: 0.054080] [d2 loss: 0.059077]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 229/500] [Batch 480/676] [D loss: 0.031289] [G loss: 0.035145] [d1 loss: 0.107362] [d2 loss: 0.134861]  [sq d1 d2: 0.000756]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 500/676] [D loss: 0.026817] [G loss: 0.021459] [d1 loss: 0.066284] [d2 loss: 0.059495]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 229/500] [Batch 520/676] [D loss: 0.006875] [G loss: -0.026240] [d1 loss: 0.089800] [d2 loss: 0.092951]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 229/500] [Batch 540/676] [D loss: -0.013835] [G loss: -0.076688] [d1 loss: 0.086147] [d2 loss: 0.070629]  [sq d1 d2: 0.000241]  [num0: 15.000000] [num1 49.000000]
[Epoch 229/500] [Batch 560/676] [D loss: -0.045505] [G loss: -0.105755] [d1 loss: 0.090416] [d2 loss: 0.083963]  [sq d1 d2: 0.000042]  [num0: 20.000000] [num1 44.000000]
[Epoch 229/500] [Batch 580/676] [D loss: -0.096963] [G loss: -0.121953] [d1 loss: 0.026436] [d2 loss: 0.042266]  [sq d1 d2: 0.000251]  [num0: 16.000000] [num1 48.000000]
[Epoch 229/500] [Batch 600/676] [D loss: -0.074327] [G loss: -0.083584] [d1 loss: 0.115673] [d2 loss: 0.120828]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 229/500] [Batch 620/676] [D loss: -0.046092] [G loss: -0.115880] [d1 loss: 0.079664] [d2 loss: 0.072092]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 229/500] [Batch 640/676] [D loss: 0.003495] [G loss: -0.075171] [d1 loss: 0.043412] [d2 loss: 0.059321]  [sq d1 d2: 0.000253]  [num0: 18.000000] [num1 46.000000]
[Epoch 229/500] [Batch 660/676] [D loss: -0.009645] [G loss: -0.127257] [d1 loss: 0.085569] [d2 loss: 0.097589]  [sq d1 d2: 0.000144]  [num0: 22.000000] [num1 42.000000]
[Epoch 230/500] [Batch 0/676] [D loss: 0.001934] [G loss: -0.164105] [d1 loss: 0.169278] [d2 loss: 0.198707]  [sq d1 d2: 0.000866]  [num0: 20.000000] [num1 44.000000]
[Epoch 230/500] [Batch 20/676] [D loss: 0.038605] [G loss: -0.153792] [d1 loss: 0.150423] [d2 loss: 0.139593]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 230/500] [Batch 40/676] [D loss: 0.022782] [G loss: -0.107813] [d1 loss: 0.075822] [d2 loss: 0.091951]  [sq d1 d2: 0.000260]  [num0: 18.000000] [num1 46.000000]
[Epoch 230/500] [Batch 60/676] [D loss: 0.004754] [G loss: -0.060511] [d1 loss: 0.087155] [d2 loss: 0.081780]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 230/500] [Batch 80/676] [D loss: -0.015425] [G loss: -0.013634] [d1 loss: 0.232033] [d2 loss: 0.202915]  [sq d1 d2: 0.000848]  [num0: 15.000000] [num1 49.000000]
[Epoch 230/500] [Batch 100/676] [D loss: -0.041513] [G loss: 0.027566] [d1 loss: 0.031199] [d2 loss: 0.045495]  [sq d1 d2: 0.000204]  [num0: 15.000000] [num1 49.000000]
[Epoch 230/500] [Batch 120/676] [D loss: -0.091628] [G loss: 0.123586] [d1 loss: 0.051457] [d2 loss: 0.063099]  [sq d1 d2: 0.000136]  [num0: 17.000000] [num1 47.000000]
[Epoch 230/500] [Batch 140/676] [D loss: -0.145726] [G loss: 0.258320] [d1 loss: 0.056708] [d2 loss: 0.047188]  [sq d1 d2: 0.000091]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 160/676] [D loss: -0.093743] [G loss: 0.199005] [d1 loss: 0.060694] [d2 loss: 0.061046]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 230/500] [Batch 180/676] [D loss: -0.071883] [G loss: 0.147860] [d1 loss: 0.101803] [d2 loss: 0.099617]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 200/676] [D loss: -0.029310] [G loss: 0.056539] [d1 loss: 0.104035] [d2 loss: 0.101635]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 220/676] [D loss: 0.076630] [G loss: 0.017192] [d1 loss: 0.129921] [d2 loss: 0.093040]  [sq d1 d2: 0.001360]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 240/676] [D loss: 0.010912] [G loss: -0.072412] [d1 loss: 0.144283] [d2 loss: 0.145277]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 260/676] [D loss: 0.015153] [G loss: -0.071416] [d1 loss: 0.086605] [d2 loss: 0.088344]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 230/500] [Batch 280/676] [D loss: 0.020511] [G loss: -0.060959] [d1 loss: 0.057012] [d2 loss: 0.059401]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 230/500] [Batch 300/676] [D loss: -0.004014] [G loss: -0.054448] [d1 loss: 0.134670] [d2 loss: 0.129559]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 230/500] [Batch 320/676] [D loss: -0.021610] [G loss: -0.029411] [d1 loss: 0.147389] [d2 loss: 0.135378]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 230/500] [Batch 340/676] [D loss: -0.073960] [G loss: -0.005321] [d1 loss: 0.034779] [d2 loss: 0.039949]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 360/676] [D loss: -0.117619] [G loss: -0.002481] [d1 loss: 0.037221] [d2 loss: 0.028334]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 380/676] [D loss: -0.159142] [G loss: 0.068129] [d1 loss: 0.076915] [d2 loss: 0.057017]  [sq d1 d2: 0.000396]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 400/676] [D loss: -0.176446] [G loss: 0.053328] [d1 loss: 0.155390] [d2 loss: 0.133149]  [sq d1 d2: 0.000495]  [num0: 17.000000] [num1 47.000000]
[Epoch 230/500] [Batch 420/676] [D loss: -0.062032] [G loss: 0.044794] [d1 loss: 0.056220] [d2 loss: 0.048705]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 230/500] [Batch 440/676] [D loss: 0.011600] [G loss: -0.019243] [d1 loss: 0.119122] [d2 loss: 0.105939]  [sq d1 d2: 0.000174]  [num0: 19.000000] [num1 45.000000]
[Epoch 230/500] [Batch 460/676] [D loss: 0.029854] [G loss: -0.161859] [d1 loss: 0.062236] [d2 loss: 0.062717]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 480/676] [D loss: -0.007801] [G loss: -0.185658] [d1 loss: 0.050651] [d2 loss: 0.065219]  [sq d1 d2: 0.000212]  [num0: 12.000000] [num1 52.000000]
[Epoch 230/500] [Batch 500/676] [D loss: 0.044685] [G loss: -0.179004] [d1 loss: 0.051025] [d2 loss: 0.041657]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 520/676] [D loss: 0.012607] [G loss: -0.118983] [d1 loss: 0.110034] [d2 loss: 0.134712]  [sq d1 d2: 0.000609]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 540/676] [D loss: -0.003891] [G loss: -0.052782] [d1 loss: 0.041310] [d2 loss: 0.040329]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 230/500] [Batch 560/676] [D loss: -0.041576] [G loss: 0.017661] [d1 loss: 0.070819] [d2 loss: 0.053548]  [sq d1 d2: 0.000298]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 580/676] [D loss: -0.055779] [G loss: 0.057489] [d1 loss: 0.088726] [d2 loss: 0.067658]  [sq d1 d2: 0.000444]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 600/676] [D loss: -0.069909] [G loss: 0.145404] [d1 loss: 0.109176] [d2 loss: 0.119770]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 230/500] [Batch 620/676] [D loss: -0.131590] [G loss: 0.199892] [d1 loss: 0.093769] [d2 loss: 0.068661]  [sq d1 d2: 0.000630]  [num0: 12.000000] [num1 52.000000]
[Epoch 230/500] [Batch 640/676] [D loss: -0.114363] [G loss: 0.220407] [d1 loss: 0.061929] [d2 loss: 0.051519]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 230/500] [Batch 660/676] [D loss: -0.050406] [G loss: 0.087910] [d1 loss: 0.063488] [d2 loss: 0.061984]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 231/500] [Batch 0/676] [D loss: -0.014578] [G loss: 0.069161] [d1 loss: 0.200427] [d2 loss: 0.215576]  [sq d1 d2: 0.000229]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 20/676] [D loss: 0.021660] [G loss: -0.045517] [d1 loss: 0.126337] [d2 loss: 0.112187]  [sq d1 d2: 0.000200]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 40/676] [D loss: 0.087900] [G loss: -0.175562] [d1 loss: 0.233804] [d2 loss: 0.225062]  [sq d1 d2: 0.000076]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 60/676] [D loss: 0.033134] [G loss: -0.245026] [d1 loss: 0.089751] [d2 loss: 0.074328]  [sq d1 d2: 0.000238]  [num0: 16.000000] [num1 48.000000]

[Epoch 231/500] [Batch 80/676] [D loss: 0.017951] [G loss: -0.206049] [d1 loss: 0.066874] [d2 loss: 0.062013]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 231/500] [Batch 100/676] [D loss: 0.007194] [G loss: -0.128382] [d1 loss: 0.085289] [d2 loss: 0.085044]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 231/500] [Batch 120/676] [D loss: -0.003612] [G loss: -0.032589] [d1 loss: 0.067113] [d2 loss: 0.069919]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 231/500] [Batch 140/676] [D loss: -0.022933] [G loss: 0.031413] [d1 loss: 0.115450] [d2 loss: 0.108065]  [sq d1 d2: 0.000055]  [num0: 12.000000] [num1 52.000000]
[Epoch 231/500] [Batch 160/676] [D loss: -0.042282] [G loss: 0.100506] [d1 loss: 0.087094] [d2 loss: 0.107561]  [sq d1 d2: 0.000419]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 180/676] [D loss: -0.074582] [G loss: 0.210931] [d1 loss: 0.167821] [d2 loss: 0.130855]  [sq d1 d2: 0.001367]  [num0: 19.000000] [num1 45.000000]
[Epoch 231/500] [Batch 200/676] [D loss: -0.072746] [G loss: 0.279866] [d1 loss: 0.118301] [d2 loss: 0.111668]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 231/500] [Batch 220/676] [D loss: -0.054387] [G loss: 0.338364] [d1 loss: 0.037461] [d2 loss: 0.038245]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 240/676] [D loss: -0.045547] [G loss: 0.358801] [d1 loss: 0.083183] [d2 loss: 0.078265]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 231/500] [Batch 260/676] [D loss: -0.030663] [G loss: 0.372104] [d1 loss: 0.109185] [d2 loss: 0.058530]  [sq d1 d2: 0.002566]  [num0: 17.000000] [num1 47.000000]
[Epoch 231/500] [Batch 280/676] [D loss: -0.043025] [G loss: 0.339823] [d1 loss: 0.049094] [d2 loss: 0.045468]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 231/500] [Batch 300/676] [D loss: 0.015133] [G loss: 0.321223] [d1 loss: 0.093723] [d2 loss: 0.092850]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 231/500] [Batch 320/676] [D loss: 0.029177] [G loss: 0.270454] [d1 loss: 0.084227] [d2 loss: 0.070078]  [sq d1 d2: 0.000200]  [num0: 13.000000] [num1 51.000000]
[Epoch 231/500] [Batch 340/676] [D loss: 0.013397] [G loss: 0.204123] [d1 loss: 0.171039] [d2 loss: 0.191156]  [sq d1 d2: 0.000405]  [num0: 15.000000] [num1 49.000000]
[Epoch 231/500] [Batch 360/676] [D loss: 0.005869] [G loss: 0.152954] [d1 loss: 0.085135] [d2 loss: 0.066666]  [sq d1 d2: 0.000341]  [num0: 17.000000] [num1 47.000000]
[Epoch 231/500] [Batch 380/676] [D loss: 0.001589] [G loss: 0.146345] [d1 loss: 0.062413] [d2 loss: 0.058387]  [sq d1 d2: 0.000016]  [num0: 10.000000] [num1 54.000000]
[Epoch 231/500] [Batch 400/676] [D loss: 0.010896] [G loss: 0.147148] [d1 loss: 0.079109] [d2 loss: 0.078117]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 420/676] [D loss: -0.021270] [G loss: 0.184765] [d1 loss: 0.117781] [d2 loss: 0.118448]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 231/500] [Batch 440/676] [D loss: -0.058257] [G loss: 0.243856] [d1 loss: 0.051746] [d2 loss: 0.064151]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 460/676] [D loss: -0.038647] [G loss: 0.272659] [d1 loss: 0.089086] [d2 loss: 0.078563]  [sq d1 d2: 0.000111]  [num0: 19.000000] [num1 45.000000]
[Epoch 231/500] [Batch 480/676] [D loss: -0.063900] [G loss: 0.244046] [d1 loss: 0.102869] [d2 loss: 0.079915]  [sq d1 d2: 0.000527]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 500/676] [D loss: -0.054439] [G loss: 0.203920] [d1 loss: 0.038923] [d2 loss: 0.041469]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 520/676] [D loss: -0.027765] [G loss: 0.131948] [d1 loss: 0.097532] [d2 loss: 0.098181]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 540/676] [D loss: -0.041754] [G loss: 0.085977] [d1 loss: 0.139534] [d2 loss: 0.160651]  [sq d1 d2: 0.000446]  [num0: 17.000000] [num1 47.000000]
[Epoch 231/500] [Batch 560/676] [D loss: 0.012881] [G loss: 0.059100] [d1 loss: 0.042634] [d2 loss: 0.037925]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 231/500] [Batch 580/676] [D loss: 0.033316] [G loss: 0.038563] [d1 loss: 0.044322] [d2 loss: 0.062866]  [sq d1 d2: 0.000344]  [num0: 18.000000] [num1 46.000000]
[Epoch 231/500] [Batch 600/676] [D loss: 0.020369] [G loss: -0.008722] [d1 loss: 0.074551] [d2 loss: 0.089091]  [sq d1 d2: 0.000211]  [num0: 20.000000] [num1 44.000000]
[Epoch 231/500] [Batch 620/676] [D loss: 0.012800] [G loss: -0.012126] [d1 loss: 0.259053] [d2 loss: 0.214292]  [sq d1 d2: 0.002004]  [num0: 16.000000] [num1 48.000000]
[Epoch 231/500] [Batch 640/676] [D loss: 0.011585] [G loss: -0.025534] [d1 loss: 0.081231] [d2 loss: 0.077147]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 231/500] [Batch 660/676] [D loss: 0.002346] [G loss: -0.034313] [d1 loss: 0.047981] [d2 loss: 0.053499]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 232/500] [Batch 0/676] [D loss: 0.000002] [G loss: -0.058805] [d1 loss: 0.061513] [d2 loss: 0.069535]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 232/500] [Batch 20/676] [D loss: -0.013145] [G loss: -0.098883] [d1 loss: 0.044965] [d2 loss: 0.036294]  [sq d1 d2: 0.000075]  [num0: 19.000000] [num1 45.000000]
[Epoch 232/500] [Batch 40/676] [D loss: -0.036948] [G loss: -0.138423] [d1 loss: 0.101655] [d2 loss: 0.112610]  [sq d1 d2: 0.000120]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 60/676] [D loss: -0.040288] [G loss: -0.180041] [d1 loss: 0.193248] [d2 loss: 0.192066]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 80/676] [D loss: -0.043746] [G loss: -0.195156] [d1 loss: 0.085594] [d2 loss: 0.089791]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 100/676] [D loss: -0.067458] [G loss: -0.207511] [d1 loss: 0.064485] [d2 loss: 0.076747]  [sq d1 d2: 0.000150]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 120/676] [D loss: -0.037233] [G loss: -0.296055] [d1 loss: 0.036623] [d2 loss: 0.035418]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 140/676] [D loss: -0.042582] [G loss: -0.322985] [d1 loss: 0.119762] [d2 loss: 0.102049]  [sq d1 d2: 0.000314]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 160/676] [D loss: 0.009128] [G loss: -0.329176] [d1 loss: 0.138246] [d2 loss: 0.138563]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 180/676] [D loss: 0.031750] [G loss: -0.305231] [d1 loss: 0.053794] [d2 loss: 0.053432]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 200/676] [D loss: 0.009417] [G loss: -0.207542] [d1 loss: 0.083438] [d2 loss: 0.064263]  [sq d1 d2: 0.000368]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 220/676] [D loss: 0.022668] [G loss: -0.148224] [d1 loss: 0.080172] [d2 loss: 0.111076]  [sq d1 d2: 0.000955]  [num0: 18.000000] [num1 46.000000]
[Epoch 232/500] [Batch 240/676] [D loss: 0.009010] [G loss: -0.121592] [d1 loss: 0.124819] [d2 loss: 0.129823]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 260/676] [D loss: -0.011308] [G loss: -0.083158] [d1 loss: 0.088950] [d2 loss: 0.097749]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 280/676] [D loss: -0.017993] [G loss: -0.029265] [d1 loss: 0.053019] [d2 loss: 0.054456]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 300/676] [D loss: -0.054771] [G loss: -0.015409] [d1 loss: 0.084165] [d2 loss: 0.096790]  [sq d1 d2: 0.000159]  [num0: 17.000000] [num1 47.000000]
[Epoch 232/500] [Batch 320/676] [D loss: -0.093758] [G loss: 0.020327] [d1 loss: 0.059131] [d2 loss: 0.062403]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 232/500] [Batch 340/676] [D loss: -0.061005] [G loss: 0.067892] [d1 loss: 0.107505] [d2 loss: 0.120571]  [sq d1 d2: 0.000171]  [num0: 18.000000] [num1 46.000000]
[Epoch 232/500] [Batch 360/676] [D loss: -0.033540] [G loss: 0.066943] [d1 loss: 0.099827] [d2 loss: 0.074519]  [sq d1 d2: 0.000641]  [num0: 17.000000] [num1 47.000000]
[Epoch 232/500] [Batch 380/676] [D loss: 0.030362] [G loss: 0.069058] [d1 loss: 0.052727] [d2 loss: 0.052443]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 232/500] [Batch 400/676] [D loss: -0.004768] [G loss: 0.030658] [d1 loss: 0.170940] [d2 loss: 0.156993]  [sq d1 d2: 0.000195]  [num0: 17.000000] [num1 47.000000]
[Epoch 232/500] [Batch 420/676] [D loss: 0.064628] [G loss: 0.105908] [d1 loss: 0.050542] [d2 loss: 0.055566]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]

[Epoch 232/500] [Batch 440/676] [D loss: 0.021972] [G loss: 0.144374] [d1 loss: 0.143143] [d2 loss: 0.149512]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 232/500] [Batch 460/676] [D loss: 0.002941] [G loss: 0.130478] [d1 loss: 0.064316] [d2 loss: 0.098772]  [sq d1 d2: 0.001187]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 480/676] [D loss: 0.011438] [G loss: 0.063003] [d1 loss: 0.063457] [d2 loss: 0.068409]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 500/676] [D loss: -0.000666] [G loss: 0.020570] [d1 loss: 0.091948] [d2 loss: 0.100985]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 520/676] [D loss: -0.010315] [G loss: -0.035727] [d1 loss: 0.032223] [d2 loss: 0.034087]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 540/676] [D loss: -0.037679] [G loss: -0.118051] [d1 loss: 0.163557] [d2 loss: 0.176763]  [sq d1 d2: 0.000174]  [num0: 18.000000] [num1 46.000000]
[Epoch 232/500] [Batch 560/676] [D loss: -0.046205] [G loss: -0.193095] [d1 loss: 0.109402] [d2 loss: 0.114789]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 232/500] [Batch 580/676] [D loss: -0.058444] [G loss: -0.284026] [d1 loss: 0.092570] [d2 loss: 0.065379]  [sq d1 d2: 0.000739]  [num0: 18.000000] [num1 46.000000]
[Epoch 232/500] [Batch 600/676] [D loss: -0.050206] [G loss: -0.366633] [d1 loss: 0.095164] [d2 loss: 0.099768]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 232/500] [Batch 620/676] [D loss: -0.069550] [G loss: -0.337777] [d1 loss: 0.192166] [d2 loss: 0.151434]  [sq d1 d2: 0.001659]  [num0: 16.000000] [num1 48.000000]
[Epoch 232/500] [Batch 640/676] [D loss: -0.040959] [G loss: -0.398901] [d1 loss: 0.076851] [d2 loss: 0.075423]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 232/500] [Batch 660/676] [D loss: 0.044619] [G loss: -0.433694] [d1 loss: 0.033904] [d2 loss: 0.038517]  [sq d1 d2: 0.000021]  [num0: 12.000000] [num1 52.000000]
[Epoch 233/500] [Batch 0/676] [D loss: 0.030853] [G loss: -0.392407] [d1 loss: 0.080307] [d2 loss: 0.072952]  [sq d1 d2: 0.000054]  [num0: 13.000000] [num1 51.000000]
[Epoch 233/500] [Batch 20/676] [D loss: 0.045635] [G loss: -0.328844] [d1 loss: 0.068705] [d2 loss: 0.070477]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 40/676] [D loss: 0.019403] [G loss: -0.194290] [d1 loss: 0.057511] [d2 loss: 0.053534]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 233/500] [Batch 60/676] [D loss: 0.005404] [G loss: -0.061931] [d1 loss: 0.164343] [d2 loss: 0.136854]  [sq d1 d2: 0.000756]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 80/676] [D loss: -0.006703] [G loss: 0.044499] [d1 loss: 0.081446] [d2 loss: 0.077900]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 233/500] [Batch 100/676] [D loss: -0.025825] [G loss: 0.183261] [d1 loss: 0.092949] [d2 loss: 0.091025]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 233/500] [Batch 120/676] [D loss: -0.043410] [G loss: 0.304402] [d1 loss: 0.066510] [d2 loss: 0.065846]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 233/500] [Batch 140/676] [D loss: -0.061905] [G loss: 0.471845] [d1 loss: 0.077216] [d2 loss: 0.084964]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 233/500] [Batch 160/676] [D loss: -0.066451] [G loss: 0.588039] [d1 loss: 0.154635] [d2 loss: 0.134218]  [sq d1 d2: 0.000417]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 180/676] [D loss: -0.072812] [G loss: 0.596914] [d1 loss: 0.162493] [d2 loss: 0.171469]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 233/500] [Batch 200/676] [D loss: -0.018219] [G loss: 0.510793] [d1 loss: 0.056803] [d2 loss: 0.055316]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 220/676] [D loss: -0.015638] [G loss: 0.494660] [d1 loss: 0.139421] [d2 loss: 0.138058]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 240/676] [D loss: 0.029703] [G loss: 0.382553] [d1 loss: 0.077293] [d2 loss: 0.071880]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 233/500] [Batch 260/676] [D loss: 0.018854] [G loss: 0.184361] [d1 loss: 0.070561] [d2 loss: 0.067826]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 280/676] [D loss: 0.027222] [G loss: 0.064946] [d1 loss: 0.137468] [d2 loss: 0.149512]  [sq d1 d2: 0.000145]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 300/676] [D loss: 0.001869] [G loss: 0.036216] [d1 loss: 0.049502] [d2 loss: 0.036873]  [sq d1 d2: 0.000159]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 320/676] [D loss: 0.007265] [G loss: 0.007754] [d1 loss: 0.046692] [d2 loss: 0.047930]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 233/500] [Batch 340/676] [D loss: -0.000892] [G loss: 0.005436] [d1 loss: 0.071958] [d2 loss: 0.065622]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 233/500] [Batch 360/676] [D loss: -0.007075] [G loss: 0.015721] [d1 loss: 0.065543] [d2 loss: 0.074556]  [sq d1 d2: 0.000081]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 380/676] [D loss: -0.009789] [G loss: 0.046608] [d1 loss: 0.050365] [d2 loss: 0.054504]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 400/676] [D loss: -0.026201] [G loss: 0.086303] [d1 loss: 0.091720] [d2 loss: 0.074333]  [sq d1 d2: 0.000302]  [num0: 14.000000] [num1 50.000000]
[Epoch 233/500] [Batch 420/676] [D loss: -0.052929] [G loss: 0.095720] [d1 loss: 0.025585] [d2 loss: 0.022087]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 233/500] [Batch 440/676] [D loss: -0.050174] [G loss: 0.072734] [d1 loss: 0.033979] [d2 loss: 0.031035]  [sq d1 d2: 0.000009]  [num0: 22.000000] [num1 42.000000]
[Epoch 233/500] [Batch 460/676] [D loss: -0.048413] [G loss: 0.082135] [d1 loss: 0.030011] [d2 loss: 0.040919]  [sq d1 d2: 0.000119]  [num0: 17.000000] [num1 47.000000]
[Epoch 233/500] [Batch 480/676] [D loss: -0.025293] [G loss: 0.081451] [d1 loss: 0.150555] [d2 loss: 0.152576]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 233/500] [Batch 500/676] [D loss: -0.058931] [G loss: 0.090611] [d1 loss: 0.084267] [d2 loss: 0.082224]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 233/500] [Batch 520/676] [D loss: 0.001020] [G loss: 0.084649] [d1 loss: 0.158099] [d2 loss: 0.161488]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 540/676] [D loss: 0.005488] [G loss: 0.055357] [d1 loss: 0.036037] [d2 loss: 0.037065]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 560/676] [D loss: 0.002574] [G loss: 0.035563] [d1 loss: 0.080507] [d2 loss: 0.067381]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 580/676] [D loss: 0.020446] [G loss: 0.002246] [d1 loss: 0.090079] [d2 loss: 0.089363]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 233/500] [Batch 600/676] [D loss: 0.002785] [G loss: -0.012830] [d1 loss: 0.088234] [d2 loss: 0.101282]  [sq d1 d2: 0.000170]  [num0: 16.000000] [num1 48.000000]
[Epoch 233/500] [Batch 620/676] [D loss: 0.005353] [G loss: -0.023706] [d1 loss: 0.032697] [d2 loss: 0.033331]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 233/500] [Batch 640/676] [D loss: 0.004838] [G loss: -0.032833] [d1 loss: 0.056441] [d2 loss: 0.049151]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 233/500] [Batch 660/676] [D loss: -0.016537] [G loss: -0.042572] [d1 loss: 0.057532] [d2 loss: 0.070380]  [sq d1 d2: 0.000165]  [num0: 18.000000] [num1 46.000000]
[Epoch 234/500] [Batch 0/676] [D loss: -0.012740] [G loss: -0.046818] [d1 loss: 0.105460] [d2 loss: 0.097497]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 20/676] [D loss: -0.028691] [G loss: -0.029800] [d1 loss: 0.054040] [d2 loss: 0.062009]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 40/676] [D loss: -0.036639] [G loss: -0.035267] [d1 loss: 0.079351] [d2 loss: 0.101636]  [sq d1 d2: 0.000497]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 60/676] [D loss: -0.040638] [G loss: -0.080073] [d1 loss: 0.222454] [d2 loss: 0.186460]  [sq d1 d2: 0.001296]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 80/676] [D loss: -0.023956] [G loss: -0.068457] [d1 loss: 0.074422] [d2 loss: 0.059119]  [sq d1 d2: 0.000234]  [num0: 14.000000] [num1 50.000000]

[Epoch 234/500] [Batch 100/676] [D loss: -0.033591] [G loss: -0.097281] [d1 loss: 0.113292] [d2 loss: 0.124791]  [sq d1 d2: 0.000132]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 120/676] [D loss: 0.024404] [G loss: -0.119378] [d1 loss: 0.065402] [d2 loss: 0.069885]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 140/676] [D loss: 0.002332] [G loss: -0.123078] [d1 loss: 0.025531] [d2 loss: 0.027101]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 234/500] [Batch 160/676] [D loss: 0.003337] [G loss: -0.091948] [d1 loss: 0.027201] [d2 loss: 0.030539]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 180/676] [D loss: 0.006514] [G loss: -0.026184] [d1 loss: 0.096211] [d2 loss: 0.098825]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 200/676] [D loss: 0.001554] [G loss: -0.024674] [d1 loss: 0.089177] [d2 loss: 0.088587]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 220/676] [D loss: 0.008678] [G loss: -0.035313] [d1 loss: 0.059063] [d2 loss: 0.061039]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 240/676] [D loss: 0.005352] [G loss: -0.039574] [d1 loss: 0.104329] [d2 loss: 0.088462]  [sq d1 d2: 0.000252]  [num0: 14.000000] [num1 50.000000]
[Epoch 234/500] [Batch 260/676] [D loss: -0.001418] [G loss: -0.069698] [d1 loss: 0.055097] [d2 loss: 0.046737]  [sq d1 d2: 0.000070]  [num0: 12.000000] [num1 52.000000]
[Epoch 234/500] [Batch 280/676] [D loss: -0.016274] [G loss: -0.093089] [d1 loss: 0.065629] [d2 loss: 0.057752]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 234/500] [Batch 300/676] [D loss: -0.023779] [G loss: -0.124992] [d1 loss: 0.041743] [d2 loss: 0.049715]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 234/500] [Batch 320/676] [D loss: -0.035433] [G loss: -0.175367] [d1 loss: 0.051347] [d2 loss: 0.048778]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 340/676] [D loss: -0.026854] [G loss: -0.166481] [d1 loss: 0.081371] [d2 loss: 0.100208]  [sq d1 d2: 0.000355]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 360/676] [D loss: -0.061602] [G loss: -0.188173] [d1 loss: 0.053787] [d2 loss: 0.059228]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 234/500] [Batch 380/676] [D loss: -0.014269] [G loss: -0.188940] [d1 loss: 0.126293] [d2 loss: 0.135566]  [sq d1 d2: 0.000086]  [num0: 12.000000] [num1 52.000000]
[Epoch 234/500] [Batch 400/676] [D loss: -0.003892] [G loss: -0.140099] [d1 loss: 0.090375] [d2 loss: 0.072313]  [sq d1 d2: 0.000326]  [num0: 13.000000] [num1 51.000000]
[Epoch 234/500] [Batch 420/676] [D loss: -0.005186] [G loss: -0.141881] [d1 loss: 0.063996] [d2 loss: 0.070608]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 440/676] [D loss: 0.011856] [G loss: -0.076219] [d1 loss: 0.075918] [d2 loss: 0.063242]  [sq d1 d2: 0.000161]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 460/676] [D loss: 0.020912] [G loss: -0.012804] [d1 loss: 0.094384] [d2 loss: 0.092606]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 234/500] [Batch 480/676] [D loss: 0.008133] [G loss: 0.019489] [d1 loss: 0.230898] [d2 loss: 0.215818]  [sq d1 d2: 0.000227]  [num0: 17.000000] [num1 47.000000]
[Epoch 234/500] [Batch 500/676] [D loss: 0.003431] [G loss: 0.054492] [d1 loss: 0.073609] [d2 loss: 0.068642]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 520/676] [D loss: 0.005929] [G loss: 0.060950] [d1 loss: 0.080895] [d2 loss: 0.078238]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 540/676] [D loss: -0.002565] [G loss: 0.063964] [d1 loss: 0.121241] [d2 loss: 0.104047]  [sq d1 d2: 0.000296]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 560/676] [D loss: -0.004667] [G loss: 0.054858] [d1 loss: 0.131510] [d2 loss: 0.108500]  [sq d1 d2: 0.000529]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 580/676] [D loss: -0.006324] [G loss: 0.050441] [d1 loss: 0.129237] [d2 loss: 0.129401]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 234/500] [Batch 600/676] [D loss: -0.022767] [G loss: 0.064965] [d1 loss: 0.164878] [d2 loss: 0.155450]  [sq d1 d2: 0.000089]  [num0: 15.000000] [num1 49.000000]
[Epoch 234/500] [Batch 620/676] [D loss: -0.016423] [G loss: 0.079119] [d1 loss: 0.066198] [d2 loss: 0.076959]  [sq d1 d2: 0.000116]  [num0: 20.000000] [num1 44.000000]
[Epoch 234/500] [Batch 640/676] [D loss: -0.008041] [G loss: 0.137107] [d1 loss: 0.094484] [d2 loss: 0.092448]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 234/500] [Batch 660/676] [D loss: -0.004574] [G loss: 0.136916] [d1 loss: 0.014551] [d2 loss: 0.022516]  [sq d1 d2: 0.000063]  [num0: 21.000000] [num1 43.000000]
[Epoch 235/500] [Batch 0/676] [D loss: 0.014574] [G loss: 0.156793] [d1 loss: 0.042032] [d2 loss: 0.056067]  [sq d1 d2: 0.000197]  [num0: 8.000000] [num1 56.000000]
[Epoch 235/500] [Batch 20/676] [D loss: -0.015449] [G loss: 0.201238] [d1 loss: 0.096916] [d2 loss: 0.084533]  [sq d1 d2: 0.000153]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 40/676] [D loss: -0.008978] [G loss: 0.222767] [d1 loss: 0.042131] [d2 loss: 0.047824]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 60/676] [D loss: 0.021191] [G loss: 0.193975] [d1 loss: 0.022995] [d2 loss: 0.019649]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 80/676] [D loss: 0.018881] [G loss: 0.149395] [d1 loss: 0.109832] [d2 loss: 0.130194]  [sq d1 d2: 0.000415]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 100/676] [D loss: 0.017925] [G loss: 0.125850] [d1 loss: 0.018613] [d2 loss: 0.034194]  [sq d1 d2: 0.000243]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 120/676] [D loss: 0.006378] [G loss: 0.110589] [d1 loss: 0.131356] [d2 loss: 0.139680]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 140/676] [D loss: 0.002917] [G loss: 0.098302] [d1 loss: 0.104727] [d2 loss: 0.132363]  [sq d1 d2: 0.000764]  [num0: 17.000000] [num1 47.000000]
[Epoch 235/500] [Batch 160/676] [D loss: -0.005364] [G loss: 0.096290] [d1 loss: 0.020641] [d2 loss: 0.018421]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 180/676] [D loss: -0.002426] [G loss: 0.103626] [d1 loss: 0.048521] [d2 loss: 0.064066]  [sq d1 d2: 0.000242]  [num0: 18.000000] [num1 46.000000]
[Epoch 235/500] [Batch 200/676] [D loss: -0.003749] [G loss: 0.090018] [d1 loss: 0.155227] [d2 loss: 0.164100]  [sq d1 d2: 0.000079]  [num0: 10.000000] [num1 54.000000]
[Epoch 235/500] [Batch 220/676] [D loss: -0.036923] [G loss: 0.093589] [d1 loss: 0.220838] [d2 loss: 0.183233]  [sq d1 d2: 0.001414]  [num0: 20.000000] [num1 44.000000]
[Epoch 235/500] [Batch 240/676] [D loss: -0.032199] [G loss: 0.092033] [d1 loss: 0.083635] [d2 loss: 0.082759]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 235/500] [Batch 260/676] [D loss: -0.021741] [G loss: 0.071500] [d1 loss: 0.044949] [d2 loss: 0.045523]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 280/676] [D loss: -0.020822] [G loss: 0.033708] [d1 loss: 0.066586] [d2 loss: 0.062261]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 235/500] [Batch 300/676] [D loss: -0.017561] [G loss: 0.008875] [d1 loss: 0.068371] [d2 loss: 0.087992]  [sq d1 d2: 0.000385]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 320/676] [D loss: -0.010511] [G loss: -0.036297] [d1 loss: 0.115110] [d2 loss: 0.097001]  [sq d1 d2: 0.000328]  [num0: 20.000000] [num1 44.000000]
[Epoch 235/500] [Batch 340/676] [D loss: -0.020094] [G loss: -0.047095] [d1 loss: 0.091866] [d2 loss: 0.078765]  [sq d1 d2: 0.000172]  [num0: 13.000000] [num1 51.000000]
[Epoch 235/500] [Batch 360/676] [D loss: 0.012829] [G loss: -0.048760] [d1 loss: 0.077973] [d2 loss: 0.064100]  [sq d1 d2: 0.000192]  [num0: 19.000000] [num1 45.000000]
[Epoch 235/500] [Batch 380/676] [D loss: 0.024522] [G loss: -0.044462] [d1 loss: 0.030235] [d2 loss: 0.043934]  [sq d1 d2: 0.000188]  [num0: 16.000000] [num1 48.000000]

[Epoch 235/500] [Batch 400/676] [D loss: 0.011399] [G loss: -0.037790] [d1 loss: 0.050614] [d2 loss: 0.036341]  [sq d1 d2: 0.000204]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 420/676] [D loss: -0.004610] [G loss: -0.032937] [d1 loss: 0.045775] [d2 loss: 0.058785]  [sq d1 d2: 0.000169]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 440/676] [D loss: -0.003890] [G loss: -0.003087] [d1 loss: 0.095084] [d2 loss: 0.097348]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 460/676] [D loss: -0.021315] [G loss: 0.004435] [d1 loss: 0.083925] [d2 loss: 0.095076]  [sq d1 d2: 0.000124]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 480/676] [D loss: -0.013375] [G loss: -0.002220] [d1 loss: 0.046486] [d2 loss: 0.051855]  [sq d1 d2: 0.000029]  [num0: 20.000000] [num1 44.000000]
[Epoch 235/500] [Batch 500/676] [D loss: -0.014242] [G loss: 0.026805] [d1 loss: 0.105064] [d2 loss: 0.088952]  [sq d1 d2: 0.000260]  [num0: 16.000000] [num1 48.000000]
[Epoch 235/500] [Batch 520/676] [D loss: -0.032566] [G loss: 0.000249] [d1 loss: 0.059336] [d2 loss: 0.057126]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 235/500] [Batch 540/676] [D loss: -0.002665] [G loss: 0.010010] [d1 loss: 0.057289] [d2 loss: 0.050316]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 235/500] [Batch 560/676] [D loss: -0.014690] [G loss: 0.018852] [d1 loss: 0.159042] [d2 loss: 0.124896]  [sq d1 d2: 0.001166]  [num0: 14.000000] [num1 50.000000]
[Epoch 235/500] [Batch 580/676] [D loss: -0.001626] [G loss: 0.044195] [d1 loss: 0.038832] [d2 loss: 0.044246]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 235/500] [Batch 600/676] [D loss: -0.022096] [G loss: -0.026451] [d1 loss: 0.062067] [d2 loss: 0.059028]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 235/500] [Batch 620/676] [D loss: 0.003232] [G loss: -0.025076] [d1 loss: 0.209032] [d2 loss: 0.163613]  [sq d1 d2: 0.002063]  [num0: 18.000000] [num1 46.000000]
[Epoch 235/500] [Batch 640/676] [D loss: 0.004658] [G loss: 0.010275] [d1 loss: 0.046341] [d2 loss: 0.043420]  [sq d1 d2: 0.000009]  [num0: 20.000000] [num1 44.000000]
[Epoch 235/500] [Batch 660/676] [D loss: 0.011832] [G loss: -0.009643] [d1 loss: 0.065818] [d2 loss: 0.066110]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 236/500] [Batch 0/676] [D loss: 0.005872] [G loss: -0.044541] [d1 loss: 0.045717] [d2 loss: 0.044530]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 236/500] [Batch 20/676] [D loss: -0.002753] [G loss: -0.068170] [d1 loss: 0.083270] [d2 loss: 0.091276]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 236/500] [Batch 40/676] [D loss: -0.014688] [G loss: -0.089342] [d1 loss: 0.126177] [d2 loss: 0.116371]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 236/500] [Batch 60/676] [D loss: -0.020713] [G loss: -0.107456] [d1 loss: 0.093667] [d2 loss: 0.072118]  [sq d1 d2: 0.000464]  [num0: 15.000000] [num1 49.000000]
[Epoch 236/500] [Batch 80/676] [D loss: -0.014829] [G loss: -0.164020] [d1 loss: 0.054346] [d2 loss: 0.064366]  [sq d1 d2: 0.000100]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 100/676] [D loss: -0.037946] [G loss: -0.167837] [d1 loss: 0.035847] [d2 loss: 0.034961]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 120/676] [D loss: -0.007839] [G loss: -0.205351] [d1 loss: 0.064036] [d2 loss: 0.081498]  [sq d1 d2: 0.000305]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 140/676] [D loss: -0.043389] [G loss: -0.188046] [d1 loss: 0.094589] [d2 loss: 0.113839]  [sq d1 d2: 0.000371]  [num0: 16.000000] [num1 48.000000]
[Epoch 236/500] [Batch 160/676] [D loss: -0.008710] [G loss: -0.184819] [d1 loss: 0.040540] [d2 loss: 0.041836]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 180/676] [D loss: -0.005309] [G loss: -0.145838] [d1 loss: 0.047032] [d2 loss: 0.051009]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 200/676] [D loss: -0.003370] [G loss: -0.139279] [d1 loss: 0.085521] [d2 loss: 0.058215]  [sq d1 d2: 0.000746]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 220/676] [D loss: 0.015720] [G loss: -0.089247] [d1 loss: 0.058370] [d2 loss: 0.044583]  [sq d1 d2: 0.000190]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 240/676] [D loss: 0.006276] [G loss: -0.039200] [d1 loss: 0.126300] [d2 loss: 0.120201]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 260/676] [D loss: 0.002302] [G loss: 0.008491] [d1 loss: 0.194428] [d2 loss: 0.133602]  [sq d1 d2: 0.003700]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 280/676] [D loss: -0.005984] [G loss: 0.019767] [d1 loss: 0.072140] [d2 loss: 0.056342]  [sq d1 d2: 0.000250]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 300/676] [D loss: -0.008325] [G loss: -0.003849] [d1 loss: 0.131854] [d2 loss: 0.150695]  [sq d1 d2: 0.000355]  [num0: 16.000000] [num1 48.000000]
[Epoch 236/500] [Batch 320/676] [D loss: -0.021712] [G loss: 0.015460] [d1 loss: 0.046469] [d2 loss: 0.062297]  [sq d1 d2: 0.000250]  [num0: 13.000000] [num1 51.000000]
[Epoch 236/500] [Batch 340/676] [D loss: -0.045839] [G loss: 0.041448] [d1 loss: 0.074691] [d2 loss: 0.084378]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 236/500] [Batch 360/676] [D loss: -0.043002] [G loss: 0.041665] [d1 loss: 0.035895] [d2 loss: 0.063207]  [sq d1 d2: 0.000746]  [num0: 18.000000] [num1 46.000000]
[Epoch 236/500] [Batch 380/676] [D loss: -0.025250] [G loss: 0.018477] [d1 loss: 0.053574] [d2 loss: 0.045983]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 400/676] [D loss: -0.025061] [G loss: 0.040535] [d1 loss: 0.072345] [d2 loss: 0.077732]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 420/676] [D loss: 0.007175] [G loss: -0.006452] [d1 loss: 0.071632] [d2 loss: 0.066222]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 440/676] [D loss: 0.035649] [G loss: 0.042528] [d1 loss: 0.128312] [d2 loss: 0.157183]  [sq d1 d2: 0.000834]  [num0: 13.000000] [num1 51.000000]
[Epoch 236/500] [Batch 460/676] [D loss: 0.024721] [G loss: 0.056634] [d1 loss: 0.108849] [d2 loss: 0.114440]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 480/676] [D loss: 0.001244] [G loss: 0.072163] [d1 loss: 0.056590] [d2 loss: 0.066927]  [sq d1 d2: 0.000107]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 500/676] [D loss: -0.002621] [G loss: 0.063217] [d1 loss: 0.160229] [d2 loss: 0.169633]  [sq d1 d2: 0.000088]  [num0: 19.000000] [num1 45.000000]
[Epoch 236/500] [Batch 520/676] [D loss: -0.007598] [G loss: 0.082962] [d1 loss: 0.053753] [d2 loss: 0.052024]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 540/676] [D loss: -0.036136] [G loss: 0.100392] [d1 loss: 0.070249] [d2 loss: 0.053267]  [sq d1 d2: 0.000288]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 560/676] [D loss: -0.023234] [G loss: 0.090902] [d1 loss: 0.065455] [d2 loss: 0.060999]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 236/500] [Batch 580/676] [D loss: -0.045402] [G loss: 0.090648] [d1 loss: 0.028210] [d2 loss: 0.023137]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 236/500] [Batch 600/676] [D loss: -0.064938] [G loss: 0.042794] [d1 loss: 0.090238] [d2 loss: 0.096231]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 236/500] [Batch 620/676] [D loss: -0.001110] [G loss: 0.070247] [d1 loss: 0.094417] [d2 loss: 0.088818]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 640/676] [D loss: -0.015714] [G loss: 0.100555] [d1 loss: 0.088631] [d2 loss: 0.103520]  [sq d1 d2: 0.000222]  [num0: 17.000000] [num1 47.000000]
[Epoch 236/500] [Batch 660/676] [D loss: 0.019494] [G loss: 0.122073] [d1 loss: 0.052507] [d2 loss: 0.041790]  [sq d1 d2: 0.000115]  [num0: 13.000000] [num1 51.000000]
[Epoch 237/500] [Batch 0/676] [D loss: 0.020197] [G loss: 0.163086] [d1 loss: 0.117084] [d2 loss: 0.131750]  [sq d1 d2: 0.000215]  [num0: 20.000000] [num1 44.000000]
[Epoch 237/500] [Batch 20/676] [D loss: 0.020512] [G loss: 0.175816] [d1 loss: 0.031292] [d2 loss: 0.035696]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 237/500] [Batch 40/676] [D loss: 0.000962] [G loss: 0.174444] [d1 loss: 0.070808] [d2 loss: 0.074021]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 237/500] [Batch 60/676] [D loss: -0.002173] [G loss: 0.192053] [d1 loss: 0.104077] [d2 loss: 0.068198]  [sq d1 d2: 0.001287]  [num0: 18.000000] [num1 46.000000]

[Epoch 237/500] [Batch 80/676] [D loss: -0.016600] [G loss: 0.244088] [d1 loss: 0.087675] [d2 loss: 0.088703]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 237/500] [Batch 100/676] [D loss: -0.059326] [G loss: 0.339546] [d1 loss: 0.123105] [d2 loss: 0.136327]  [sq d1 d2: 0.000175]  [num0: 13.000000] [num1 51.000000]
[Epoch 237/500] [Batch 120/676] [D loss: -0.051604] [G loss: 0.352163] [d1 loss: 0.094168] [d2 loss: 0.097655]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 140/676] [D loss: -0.044514] [G loss: 0.351824] [d1 loss: 0.097295] [d2 loss: 0.090453]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 237/500] [Batch 160/676] [D loss: -0.006063] [G loss: 0.354407] [d1 loss: 0.018184] [d2 loss: 0.020211]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 237/500] [Batch 180/676] [D loss: -0.026959] [G loss: 0.288356] [d1 loss: 0.039299] [d2 loss: 0.038281]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 200/676] [D loss: 0.017920] [G loss: 0.207107] [d1 loss: 0.075798] [d2 loss: 0.086635]  [sq d1 d2: 0.000117]  [num0: 17.000000] [num1 47.000000]
[Epoch 237/500] [Batch 220/676] [D loss: 0.007871] [G loss: 0.098311] [d1 loss: 0.102812] [d2 loss: 0.093130]  [sq d1 d2: 0.000094]  [num0: 19.000000] [num1 45.000000]
[Epoch 237/500] [Batch 240/676] [D loss: 0.008033] [G loss: 0.063045] [d1 loss: 0.056608] [d2 loss: 0.056983]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 237/500] [Batch 260/676] [D loss: 0.003920] [G loss: 0.016450] [d1 loss: 0.030698] [d2 loss: 0.018792]  [sq d1 d2: 0.000142]  [num0: 14.000000] [num1 50.000000]
[Epoch 237/500] [Batch 280/676] [D loss: -0.011120] [G loss: -0.060027] [d1 loss: 0.039345] [d2 loss: 0.045172]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 237/500] [Batch 300/676] [D loss: -0.033170] [G loss: -0.126713] [d1 loss: 0.036365] [d2 loss: 0.050732]  [sq d1 d2: 0.000206]  [num0: 19.000000] [num1 45.000000]
[Epoch 237/500] [Batch 320/676] [D loss: -0.025525] [G loss: -0.176709] [d1 loss: 0.126558] [d2 loss: 0.102610]  [sq d1 d2: 0.000574]  [num0: 17.000000] [num1 47.000000]
[Epoch 237/500] [Batch 340/676] [D loss: -0.052328] [G loss: -0.206333] [d1 loss: 0.084275] [d2 loss: 0.084735]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 360/676] [D loss: -0.066023] [G loss: -0.247602] [d1 loss: 0.077465] [d2 loss: 0.055017]  [sq d1 d2: 0.000504]  [num0: 21.000000] [num1 43.000000]
[Epoch 237/500] [Batch 380/676] [D loss: -0.009311] [G loss: -0.263005] [d1 loss: 0.094671] [d2 loss: 0.094335]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 237/500] [Batch 400/676] [D loss: -0.008980] [G loss: -0.320132] [d1 loss: 0.118821] [d2 loss: 0.106750]  [sq d1 d2: 0.000146]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 420/676] [D loss: 0.006099] [G loss: -0.329570] [d1 loss: 0.055972] [d2 loss: 0.048012]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 237/500] [Batch 440/676] [D loss: 0.000872] [G loss: -0.290616] [d1 loss: 0.039080] [d2 loss: 0.060431]  [sq d1 d2: 0.000456]  [num0: 13.000000] [num1 51.000000]
[Epoch 237/500] [Batch 460/676] [D loss: 0.026101] [G loss: -0.280932] [d1 loss: 0.038221] [d2 loss: 0.038767]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 237/500] [Batch 480/676] [D loss: 0.011252] [G loss: -0.210392] [d1 loss: 0.026713] [d2 loss: 0.030252]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 237/500] [Batch 500/676] [D loss: -0.008277] [G loss: -0.146001] [d1 loss: 0.094233] [d2 loss: 0.119494]  [sq d1 d2: 0.000638]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 520/676] [D loss: -0.028378] [G loss: -0.083276] [d1 loss: 0.063748] [d2 loss: 0.071387]  [sq d1 d2: 0.000058]  [num0: 13.000000] [num1 51.000000]
[Epoch 237/500] [Batch 540/676] [D loss: -0.032400] [G loss: -0.062791] [d1 loss: 0.097612] [d2 loss: 0.078240]  [sq d1 d2: 0.000375]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 560/676] [D loss: -0.023483] [G loss: 0.039780] [d1 loss: 0.061953] [d2 loss: 0.064417]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 580/676] [D loss: -0.056981] [G loss: 0.052073] [d1 loss: 0.072231] [d2 loss: 0.071155]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 237/500] [Batch 600/676] [D loss: -0.036304] [G loss: 0.082471] [d1 loss: 0.029676] [d2 loss: 0.025339]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 237/500] [Batch 620/676] [D loss: -0.044547] [G loss: 0.049681] [d1 loss: 0.133618] [d2 loss: 0.152089]  [sq d1 d2: 0.000341]  [num0: 19.000000] [num1 45.000000]
[Epoch 237/500] [Batch 640/676] [D loss: -0.013368] [G loss: 0.083081] [d1 loss: 0.132333] [d2 loss: 0.140695]  [sq d1 d2: 0.000070]  [num0: 18.000000] [num1 46.000000]
[Epoch 237/500] [Batch 660/676] [D loss: 0.014369] [G loss: 0.032580] [d1 loss: 0.038819] [d2 loss: 0.034146]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 238/500] [Batch 0/676] [D loss: 0.003707] [G loss: 0.034585] [d1 loss: 0.217271] [d2 loss: 0.208285]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 238/500] [Batch 20/676] [D loss: 0.003125] [G loss: 0.021678] [d1 loss: 0.106548] [d2 loss: 0.115998]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 238/500] [Batch 40/676] [D loss: -0.009508] [G loss: -0.025299] [d1 loss: 0.063935] [d2 loss: 0.069761]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 238/500] [Batch 60/676] [D loss: -0.019896] [G loss: -0.035321] [d1 loss: 0.079527] [d2 loss: 0.087328]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 238/500] [Batch 80/676] [D loss: -0.017764] [G loss: -0.037273] [d1 loss: 0.065669] [d2 loss: 0.086396]  [sq d1 d2: 0.000430]  [num0: 14.000000] [num1 50.000000]
[Epoch 238/500] [Batch 100/676] [D loss: -0.024911] [G loss: -0.080963] [d1 loss: 0.065447] [d2 loss: 0.050627]  [sq d1 d2: 0.000220]  [num0: 16.000000] [num1 48.000000]
[Epoch 238/500] [Batch 120/676] [D loss: -0.077357] [G loss: -0.068986] [d1 loss: 0.080645] [d2 loss: 0.080979]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 238/500] [Batch 140/676] [D loss: -0.118441] [G loss: -0.080265] [d1 loss: 0.026773] [d2 loss: 0.031820]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 238/500] [Batch 160/676] [D loss: 0.018888] [G loss: -0.093909] [d1 loss: 0.069229] [d2 loss: 0.062033]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 238/500] [Batch 180/676] [D loss: 0.022569] [G loss: 0.004452] [d1 loss: 0.057160] [d2 loss: 0.058887]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 238/500] [Batch 200/676] [D loss: 0.012072] [G loss: 0.071960] [d1 loss: 0.059736] [d2 loss: 0.045628]  [sq d1 d2: 0.000199]  [num0: 15.000000] [num1 49.000000]
[Epoch 238/500] [Batch 220/676] [D loss: 0.011251] [G loss: 0.106705] [d1 loss: 0.079025] [d2 loss: 0.088857]  [sq d1 d2: 0.000097]  [num0: 18.000000] [num1 46.000000]
[Epoch 238/500] [Batch 240/676] [D loss: -0.017089] [G loss: 0.148019] [d1 loss: 0.096917] [d2 loss: 0.100377]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 238/500] [Batch 260/676] [D loss: -0.040769] [G loss: 0.204032] [d1 loss: 0.083147] [d2 loss: 0.095413]  [sq d1 d2: 0.000150]  [num0: 14.000000] [num1 50.000000]
[Epoch 238/500] [Batch 280/676] [D loss: -0.039773] [G loss: 0.240985] [d1 loss: 0.229731] [d2 loss: 0.221126]  [sq d1 d2: 0.000074]  [num0: 17.000000] [num1 47.000000]
[Epoch 238/500] [Batch 300/676] [D loss: -0.057133] [G loss: 0.349516] [d1 loss: 0.103873] [d2 loss: 0.099899]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 238/500] [Batch 320/676] [D loss: -0.092441] [G loss: 0.421455] [d1 loss: 0.146457] [d2 loss: 0.115177]  [sq d1 d2: 0.000978]  [num0: 12.000000] [num1 52.000000]
[Epoch 238/500] [Batch 340/676] [D loss: -0.099296] [G loss: 0.465458] [d1 loss: 0.028010] [d2 loss: 0.034972]  [sq d1 d2: 0.000048]  [num0: 10.000000] [num1 54.000000]
[Epoch 238/500] [Batch 360/676] [D loss: -0.089301] [G loss: 0.479617] [d1 loss: 0.085754] [d2 loss: 0.076144]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 238/500] [Batch 380/676] [D loss: -0.016369] [G loss: 0.386254] [d1 loss: 0.108631] [d2 loss: 0.070801]  [sq d1 d2: 0.001431]  [num0: 15.000000] [num1 49.000000]
[Epoch 238/500] [Batch 400/676] [D loss: 0.012651] [G loss: 0.306748] [d1 loss: 0.101130] [d2 loss: 0.101686]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 238/500] [Batch 420/676] [D loss: 0.036568] [G loss: 0.210176] [d1 loss: 0.133833] [d2 loss: 0.080227]  [sq d1 d2: 0.002874]  [num0: 19.000000] [num1 45.000000]

[Epoch 238/500] [Batch 440/676] [D loss: 0.017057] [G loss: 0.130031] [d1 loss: 0.024839] [d2 loss: 0.056642]  [sq d1 d2: 0.001011]  [num0: 19.000000] [num1 45.000000]
[Epoch 238/500] [Batch 460/676] [D loss: -0.001182] [G loss: 0.010731] [d1 loss: 0.052942] [d2 loss: 0.053908]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 238/500] [Batch 480/676] [D loss: -0.017311] [G loss: -0.065908] [d1 loss: 0.073392] [d2 loss: 0.078523]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 238/500] [Batch 500/676] [D loss: -0.039367] [G loss: -0.180109] [d1 loss: 0.048916] [d2 loss: 0.060350]  [sq d1 d2: 0.000131]  [num0: 17.000000] [num1 47.000000]
[Epoch 238/500] [Batch 520/676] [D loss: -0.055367] [G loss: -0.294375] [d1 loss: 0.117070] [d2 loss: 0.113349]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]
[Epoch 238/500] [Batch 540/676] [D loss: -0.068374] [G loss: -0.295782] [d1 loss: 0.056731] [d2 loss: 0.068035]  [sq d1 d2: 0.000128]  [num0: 19.000000] [num1 45.000000]
[Epoch 238/500] [Batch 560/676] [D loss: -0.035742] [G loss: -0.379197] [d1 loss: 0.069320] [d2 loss: 0.072724]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 238/500] [Batch 580/676] [D loss: -0.040909] [G loss: -0.389130] [d1 loss: 0.089060] [d2 loss: 0.107571]  [sq d1 d2: 0.000343]  [num0: 13.000000] [num1 51.000000]
[Epoch 238/500] [Batch 600/676] [D loss: -0.016353] [G loss: -0.428646] [d1 loss: 0.077477] [d2 loss: 0.061259]  [sq d1 d2: 0.000263]  [num0: 13.000000] [num1 51.000000]
[Epoch 238/500] [Batch 620/676] [D loss: 0.006860] [G loss: -0.562640] [d1 loss: 0.052508] [d2 loss: 0.055208]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 238/500] [Batch 640/676] [D loss: 0.045310] [G loss: -0.597887] [d1 loss: 0.080080] [d2 loss: 0.053322]  [sq d1 d2: 0.000716]  [num0: 17.000000] [num1 47.000000]
[Epoch 238/500] [Batch 660/676] [D loss: 0.018583] [G loss: -0.494540] [d1 loss: 0.074859] [d2 loss: 0.100019]  [sq d1 d2: 0.000633]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 0/676] [D loss: 0.002042] [G loss: -0.423082] [d1 loss: 0.059344] [d2 loss: 0.075737]  [sq d1 d2: 0.000269]  [num0: 11.000000] [num1 53.000000]
[Epoch 239/500] [Batch 20/676] [D loss: -0.003520] [G loss: -0.356032] [d1 loss: 0.117497] [d2 loss: 0.095206]  [sq d1 d2: 0.000497]  [num0: 17.000000] [num1 47.000000]
[Epoch 239/500] [Batch 40/676] [D loss: -0.051836] [G loss: -0.239581] [d1 loss: 0.090938] [d2 loss: 0.109214]  [sq d1 d2: 0.000334]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 60/676] [D loss: -0.027092] [G loss: -0.100114] [d1 loss: 0.114150] [d2 loss: 0.091968]  [sq d1 d2: 0.000492]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 80/676] [D loss: -0.062881] [G loss: -0.056331] [d1 loss: 0.059150] [d2 loss: 0.053787]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 100/676] [D loss: -0.050179] [G loss: 0.099924] [d1 loss: 0.040389] [d2 loss: 0.041103]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 120/676] [D loss: -0.056317] [G loss: 0.104394] [d1 loss: 0.067027] [d2 loss: 0.062646]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 239/500] [Batch 140/676] [D loss: -0.032563] [G loss: 0.212807] [d1 loss: 0.062607] [d2 loss: 0.076763]  [sq d1 d2: 0.000200]  [num0: 14.000000] [num1 50.000000]
[Epoch 239/500] [Batch 160/676] [D loss: -0.001431] [G loss: 0.110829] [d1 loss: 0.069047] [d2 loss: 0.055534]  [sq d1 d2: 0.000183]  [num0: 16.000000] [num1 48.000000]
[Epoch 239/500] [Batch 180/676] [D loss: 0.032355] [G loss: 0.067069] [d1 loss: 0.056824] [d2 loss: 0.070064]  [sq d1 d2: 0.000175]  [num0: 14.000000] [num1 50.000000]
[Epoch 239/500] [Batch 200/676] [D loss: 0.032673] [G loss: 0.093053] [d1 loss: 0.073789] [d2 loss: 0.090525]  [sq d1 d2: 0.000280]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 220/676] [D loss: -0.001451] [G loss: 0.086947] [d1 loss: 0.075407] [d2 loss: 0.066367]  [sq d1 d2: 0.000082]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 240/676] [D loss: 0.001989] [G loss: 0.105059] [d1 loss: 0.103240] [d2 loss: 0.111379]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 239/500] [Batch 260/676] [D loss: -0.010623] [G loss: 0.104659] [d1 loss: 0.054334] [d2 loss: 0.045481]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 239/500] [Batch 280/676] [D loss: -0.029776] [G loss: 0.130480] [d1 loss: 0.098951] [d2 loss: 0.086230]  [sq d1 d2: 0.000162]  [num0: 20.000000] [num1 44.000000]
[Epoch 239/500] [Batch 300/676] [D loss: -0.026763] [G loss: 0.144462] [d1 loss: 0.097677] [d2 loss: 0.110514]  [sq d1 d2: 0.000165]  [num0: 21.000000] [num1 43.000000]
[Epoch 239/500] [Batch 320/676] [D loss: -0.064301] [G loss: 0.184584] [d1 loss: 0.143836] [d2 loss: 0.134007]  [sq d1 d2: 0.000097]  [num0: 12.000000] [num1 52.000000]
[Epoch 239/500] [Batch 340/676] [D loss: -0.050996] [G loss: 0.225845] [d1 loss: 0.091216] [d2 loss: 0.076867]  [sq d1 d2: 0.000206]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 360/676] [D loss: -0.030425] [G loss: 0.203774] [d1 loss: 0.039325] [d2 loss: 0.037987]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 239/500] [Batch 380/676] [D loss: -0.002678] [G loss: 0.171128] [d1 loss: 0.052786] [d2 loss: 0.067132]  [sq d1 d2: 0.000206]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 400/676] [D loss: 0.021024] [G loss: 0.159984] [d1 loss: 0.069959] [d2 loss: 0.078332]  [sq d1 d2: 0.000070]  [num0: 12.000000] [num1 52.000000]
[Epoch 239/500] [Batch 420/676] [D loss: 0.000604] [G loss: 0.022376] [d1 loss: 0.044656] [d2 loss: 0.041811]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 239/500] [Batch 440/676] [D loss: 0.013578] [G loss: -0.017433] [d1 loss: 0.112866] [d2 loss: 0.119822]  [sq d1 d2: 0.000048]  [num0: 13.000000] [num1 51.000000]
[Epoch 239/500] [Batch 460/676] [D loss: 0.014778] [G loss: -0.064883] [d1 loss: 0.077818] [d2 loss: 0.088089]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 480/676] [D loss: 0.005185] [G loss: -0.119637] [d1 loss: 0.094003] [d2 loss: 0.104701]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 500/676] [D loss: -0.003432] [G loss: -0.113762] [d1 loss: 0.073840] [d2 loss: 0.095229]  [sq d1 d2: 0.000457]  [num0: 19.000000] [num1 45.000000]
[Epoch 239/500] [Batch 520/676] [D loss: -0.005309] [G loss: -0.105701] [d1 loss: 0.126077] [d2 loss: 0.132324]  [sq d1 d2: 0.000039]  [num0: 16.000000] [num1 48.000000]
[Epoch 239/500] [Batch 540/676] [D loss: -0.012064] [G loss: -0.112567] [d1 loss: 0.053676] [d2 loss: 0.052465]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 239/500] [Batch 560/676] [D loss: -0.025124] [G loss: -0.138708] [d1 loss: 0.057530] [d2 loss: 0.062714]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 239/500] [Batch 580/676] [D loss: -0.008948] [G loss: -0.212083] [d1 loss: 0.077985] [d2 loss: 0.057539]  [sq d1 d2: 0.000418]  [num0: 14.000000] [num1 50.000000]
[Epoch 239/500] [Batch 600/676] [D loss: -0.055374] [G loss: -0.286320] [d1 loss: 0.084814] [d2 loss: 0.089335]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 239/500] [Batch 620/676] [D loss: -0.056252] [G loss: -0.360646] [d1 loss: 0.113198] [d2 loss: 0.090808]  [sq d1 d2: 0.000501]  [num0: 15.000000] [num1 49.000000]
[Epoch 239/500] [Batch 640/676] [D loss: -0.081727] [G loss: -0.352531] [d1 loss: 0.047927] [d2 loss: 0.038724]  [sq d1 d2: 0.000085]  [num0: 14.000000] [num1 50.000000]
[Epoch 239/500] [Batch 660/676] [D loss: -0.005751] [G loss: -0.299267] [d1 loss: 0.075619] [d2 loss: 0.108811]  [sq d1 d2: 0.001102]  [num0: 10.000000] [num1 54.000000]
[Epoch 240/500] [Batch 0/676] [D loss: -0.035462] [G loss: -0.274593] [d1 loss: 0.067273] [d2 loss: 0.083761]  [sq d1 d2: 0.000272]  [num0: 14.000000] [num1 50.000000]
[Epoch 240/500] [Batch 20/676] [D loss: -0.018439] [G loss: -0.167078] [d1 loss: 0.109458] [d2 loss: 0.095740]  [sq d1 d2: 0.000188]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 40/676] [D loss: 0.022428] [G loss: -0.007900] [d1 loss: 0.118124] [d2 loss: 0.160554]  [sq d1 d2: 0.001800]  [num0: 17.000000] [num1 47.000000]
[Epoch 240/500] [Batch 60/676] [D loss: 0.028340] [G loss: 0.075036] [d1 loss: 0.091830] [d2 loss: 0.127723]  [sq d1 d2: 0.001288]  [num0: 17.000000] [num1 47.000000]
[Epoch 240/500] [Batch 80/676] [D loss: 0.015356] [G loss: 0.132536] [d1 loss: 0.122918] [d2 loss: 0.110519]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]
[Epoch 240/500] [Batch 100/676] [D loss: 0.008126] [G loss: 0.186605] [d1 loss: 0.052317] [d2 loss: 0.062580]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]

[Epoch 240/500] [Batch 120/676] [D loss: 0.022830] [G loss: 0.253799] [d1 loss: 0.117212] [d2 loss: 0.140197]  [sq d1 d2: 0.000528]  [num0: 20.000000] [num1 44.000000]
[Epoch 240/500] [Batch 140/676] [D loss: -0.005606] [G loss: 0.296657] [d1 loss: 0.053105] [d2 loss: 0.059804]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 240/500] [Batch 160/676] [D loss: -0.033853] [G loss: 0.372021] [d1 loss: 0.146005] [d2 loss: 0.170598]  [sq d1 d2: 0.000605]  [num0: 15.000000] [num1 49.000000]
[Epoch 240/500] [Batch 180/676] [D loss: -0.045353] [G loss: 0.420584] [d1 loss: 0.081533] [d2 loss: 0.094989]  [sq d1 d2: 0.000181]  [num0: 12.000000] [num1 52.000000]
[Epoch 240/500] [Batch 200/676] [D loss: -0.048195] [G loss: 0.428240] [d1 loss: 0.064516] [d2 loss: 0.053330]  [sq d1 d2: 0.000125]  [num0: 16.000000] [num1 48.000000]
[Epoch 240/500] [Batch 220/676] [D loss: -0.031233] [G loss: 0.427382] [d1 loss: 0.073214] [d2 loss: 0.059707]  [sq d1 d2: 0.000182]  [num0: 17.000000] [num1 47.000000]
[Epoch 240/500] [Batch 240/676] [D loss: -0.010890] [G loss: 0.442230] [d1 loss: 0.123025] [d2 loss: 0.142529]  [sq d1 d2: 0.000380]  [num0: 15.000000] [num1 49.000000]
[Epoch 240/500] [Batch 260/676] [D loss: 0.013785] [G loss: 0.357566] [d1 loss: 0.033042] [d2 loss: 0.024867]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 240/500] [Batch 280/676] [D loss: -0.031447] [G loss: 0.270425] [d1 loss: 0.089650] [d2 loss: 0.119269]  [sq d1 d2: 0.000877]  [num0: 16.000000] [num1 48.000000]
[Epoch 240/500] [Batch 300/676] [D loss: -0.005219] [G loss: 0.264054] [d1 loss: 0.100951] [d2 loss: 0.097680]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 240/500] [Batch 320/676] [D loss: -0.020547] [G loss: 0.160256] [d1 loss: 0.123471] [d2 loss: 0.121513]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 240/500] [Batch 340/676] [D loss: 0.020515] [G loss: 0.125295] [d1 loss: 0.141865] [d2 loss: 0.077920]  [sq d1 d2: 0.004089]  [num0: 16.000000] [num1 48.000000]
[Epoch 240/500] [Batch 360/676] [D loss: -0.028285] [G loss: 0.074952] [d1 loss: 0.066031] [d2 loss: 0.073234]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 240/500] [Batch 380/676] [D loss: -0.008307] [G loss: 0.019351] [d1 loss: 0.079296] [d2 loss: 0.074097]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 400/676] [D loss: -0.006546] [G loss: -0.009169] [d1 loss: 0.061695] [d2 loss: 0.054069]  [sq d1 d2: 0.000058]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 420/676] [D loss: 0.000820] [G loss: -0.035815] [d1 loss: 0.114892] [d2 loss: 0.102302]  [sq d1 d2: 0.000159]  [num0: 19.000000] [num1 45.000000]
[Epoch 240/500] [Batch 440/676] [D loss: -0.018981] [G loss: -0.081183] [d1 loss: 0.036751] [d2 loss: 0.033965]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 460/676] [D loss: -0.013874] [G loss: -0.102857] [d1 loss: 0.063058] [d2 loss: 0.057952]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 240/500] [Batch 480/676] [D loss: -0.019867] [G loss: -0.149281] [d1 loss: 0.122247] [d2 loss: 0.107532]  [sq d1 d2: 0.000217]  [num0: 18.000000] [num1 46.000000]
[Epoch 240/500] [Batch 500/676] [D loss: -0.004031] [G loss: -0.176666] [d1 loss: 0.105361] [d2 loss: 0.107537]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 240/500] [Batch 520/676] [D loss: -0.027884] [G loss: -0.175569] [d1 loss: 0.035989] [d2 loss: 0.037056]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 240/500] [Batch 540/676] [D loss: -0.028903] [G loss: -0.170050] [d1 loss: 0.073833] [d2 loss: 0.067606]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 560/676] [D loss: -0.004006] [G loss: -0.164883] [d1 loss: 0.055922] [d2 loss: 0.061754]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 240/500] [Batch 580/676] [D loss: 0.007724] [G loss: -0.171024] [d1 loss: 0.078633] [d2 loss: 0.090518]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 240/500] [Batch 600/676] [D loss: 0.029023] [G loss: -0.209969] [d1 loss: 0.038359] [d2 loss: 0.031578]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 240/500] [Batch 620/676] [D loss: 0.016574] [G loss: -0.152411] [d1 loss: 0.034717] [d2 loss: 0.031579]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 240/500] [Batch 640/676] [D loss: -0.010973] [G loss: -0.161055] [d1 loss: 0.060212] [d2 loss: 0.057575]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 240/500] [Batch 660/676] [D loss: 0.010159] [G loss: -0.153521] [d1 loss: 0.091595] [d2 loss: 0.114177]  [sq d1 d2: 0.000510]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 0/676] [D loss: 0.010583] [G loss: -0.105993] [d1 loss: 0.106338] [d2 loss: 0.091030]  [sq d1 d2: 0.000234]  [num0: 15.000000] [num1 49.000000]
[Epoch 241/500] [Batch 20/676] [D loss: -0.013344] [G loss: -0.117904] [d1 loss: 0.103045] [d2 loss: 0.114926]  [sq d1 d2: 0.000141]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 40/676] [D loss: -0.012916] [G loss: -0.122660] [d1 loss: 0.058083] [d2 loss: 0.068448]  [sq d1 d2: 0.000107]  [num0: 14.000000] [num1 50.000000]
[Epoch 241/500] [Batch 60/676] [D loss: -0.009265] [G loss: -0.100098] [d1 loss: 0.078559] [d2 loss: 0.071568]  [sq d1 d2: 0.000049]  [num0: 14.000000] [num1 50.000000]
[Epoch 241/500] [Batch 80/676] [D loss: -0.022941] [G loss: -0.133878] [d1 loss: 0.032830] [d2 loss: 0.047136]  [sq d1 d2: 0.000205]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 100/676] [D loss: -0.014418] [G loss: -0.085112] [d1 loss: 0.079751] [d2 loss: 0.056127]  [sq d1 d2: 0.000558]  [num0: 12.000000] [num1 52.000000]
[Epoch 241/500] [Batch 120/676] [D loss: -0.026679] [G loss: -0.094093] [d1 loss: 0.089706] [d2 loss: 0.088912]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 241/500] [Batch 140/676] [D loss: 0.010432] [G loss: -0.060316] [d1 loss: 0.110044] [d2 loss: 0.141810]  [sq d1 d2: 0.001009]  [num0: 15.000000] [num1 49.000000]
[Epoch 241/500] [Batch 160/676] [D loss: 0.006474] [G loss: -0.056403] [d1 loss: 0.074912] [d2 loss: 0.077211]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 180/676] [D loss: 0.002513] [G loss: -0.056779] [d1 loss: 0.121148] [d2 loss: 0.111791]  [sq d1 d2: 0.000088]  [num0: 20.000000] [num1 44.000000]
[Epoch 241/500] [Batch 200/676] [D loss: -0.021566] [G loss: -0.026342] [d1 loss: 0.018639] [d2 loss: 0.022709]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 220/676] [D loss: 0.009820] [G loss: 0.003526] [d1 loss: 0.098961] [d2 loss: 0.108853]  [sq d1 d2: 0.000098]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 240/676] [D loss: -0.001338] [G loss: 0.039563] [d1 loss: 0.087831] [d2 loss: 0.093513]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 241/500] [Batch 260/676] [D loss: -0.012614] [G loss: 0.126353] [d1 loss: 0.070794] [d2 loss: 0.074980]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 280/676] [D loss: -0.013460] [G loss: 0.162667] [d1 loss: 0.060922] [d2 loss: 0.067610]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 300/676] [D loss: -0.019400] [G loss: 0.176248] [d1 loss: 0.080229] [d2 loss: 0.103290]  [sq d1 d2: 0.000532]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 320/676] [D loss: -0.039300] [G loss: 0.209608] [d1 loss: 0.131537] [d2 loss: 0.122434]  [sq d1 d2: 0.000083]  [num0: 18.000000] [num1 46.000000]
[Epoch 241/500] [Batch 340/676] [D loss: -0.033273] [G loss: 0.237260] [d1 loss: 0.039485] [d2 loss: 0.047121]  [sq d1 d2: 0.000058]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 360/676] [D loss: -0.017613] [G loss: 0.202570] [d1 loss: 0.089560] [d2 loss: 0.104214]  [sq d1 d2: 0.000215]  [num0: 19.000000] [num1 45.000000]
[Epoch 241/500] [Batch 380/676] [D loss: -0.015302] [G loss: 0.236980] [d1 loss: 0.250206] [d2 loss: 0.308775]  [sq d1 d2: 0.003430]  [num0: 18.000000] [num1 46.000000]
[Epoch 241/500] [Batch 400/676] [D loss: -0.018861] [G loss: 0.222425] [d1 loss: 0.053213] [d2 loss: 0.061047]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 420/676] [D loss: -0.009655] [G loss: 0.248984] [d1 loss: 0.056539] [d2 loss: 0.063644]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 241/500] [Batch 440/676] [D loss: 0.009168] [G loss: 0.225736] [d1 loss: 0.046359] [d2 loss: 0.042261]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 241/500] [Batch 460/676] [D loss: -0.013155] [G loss: 0.181354] [d1 loss: 0.032403] [d2 loss: 0.031742]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]

[Epoch 241/500] [Batch 480/676] [D loss: 0.005478] [G loss: 0.112410] [d1 loss: 0.056533] [d2 loss: 0.067133]  [sq d1 d2: 0.000112]  [num0: 18.000000] [num1 46.000000]
[Epoch 241/500] [Batch 500/676] [D loss: 0.000693] [G loss: 0.066645] [d1 loss: 0.081524] [d2 loss: 0.065360]  [sq d1 d2: 0.000261]  [num0: 18.000000] [num1 46.000000]
[Epoch 241/500] [Batch 520/676] [D loss: -0.018356] [G loss: 0.028306] [d1 loss: 0.044887] [d2 loss: 0.047445]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 540/676] [D loss: -0.021910] [G loss: -0.039635] [d1 loss: 0.082213] [d2 loss: 0.060616]  [sq d1 d2: 0.000466]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 560/676] [D loss: -0.019505] [G loss: -0.039237] [d1 loss: 0.056147] [d2 loss: 0.061423]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 241/500] [Batch 580/676] [D loss: -0.010037] [G loss: -0.069064] [d1 loss: 0.084054] [d2 loss: 0.083115]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 600/676] [D loss: -0.008804] [G loss: -0.121282] [d1 loss: 0.053089] [d2 loss: 0.046956]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 241/500] [Batch 620/676] [D loss: -0.017647] [G loss: -0.131630] [d1 loss: 0.093863] [d2 loss: 0.105557]  [sq d1 d2: 0.000137]  [num0: 17.000000] [num1 47.000000]
[Epoch 241/500] [Batch 640/676] [D loss: -0.005411] [G loss: -0.131606] [d1 loss: 0.089704] [d2 loss: 0.099149]  [sq d1 d2: 0.000089]  [num0: 16.000000] [num1 48.000000]
[Epoch 241/500] [Batch 660/676] [D loss: -0.019112] [G loss: -0.155606] [d1 loss: 0.076582] [d2 loss: 0.079073]  [sq d1 d2: 0.000006]  [num0: 21.000000] [num1 43.000000]
[Epoch 242/500] [Batch 0/676] [D loss: 0.003355] [G loss: -0.165412] [d1 loss: 0.101019] [d2 loss: 0.138368]  [sq d1 d2: 0.001395]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 20/676] [D loss: 0.000712] [G loss: -0.154266] [d1 loss: 0.035568] [d2 loss: 0.036390]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 40/676] [D loss: -0.006621] [G loss: -0.141258] [d1 loss: 0.058877] [d2 loss: 0.062377]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 60/676] [D loss: -0.025822] [G loss: -0.136108] [d1 loss: 0.118685] [d2 loss: 0.105403]  [sq d1 d2: 0.000176]  [num0: 23.000000] [num1 41.000000]
[Epoch 242/500] [Batch 80/676] [D loss: 0.010314] [G loss: -0.129092] [d1 loss: 0.058098] [d2 loss: 0.046315]  [sq d1 d2: 0.000139]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 100/676] [D loss: -0.009605] [G loss: -0.142710] [d1 loss: 0.083664] [d2 loss: 0.054000]  [sq d1 d2: 0.000880]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 120/676] [D loss: -0.028009] [G loss: -0.095944] [d1 loss: 0.064913] [d2 loss: 0.072282]  [sq d1 d2: 0.000054]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 140/676] [D loss: -0.016533] [G loss: -0.110570] [d1 loss: 0.090051] [d2 loss: 0.074805]  [sq d1 d2: 0.000232]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 160/676] [D loss: -0.021724] [G loss: -0.125504] [d1 loss: 0.125052] [d2 loss: 0.144042]  [sq d1 d2: 0.000361]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 180/676] [D loss: -0.018110] [G loss: -0.131788] [d1 loss: 0.059201] [d2 loss: 0.062110]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 200/676] [D loss: -0.012360] [G loss: -0.120107] [d1 loss: 0.036079] [d2 loss: 0.051988]  [sq d1 d2: 0.000253]  [num0: 15.000000] [num1 49.000000]
[Epoch 242/500] [Batch 220/676] [D loss: -0.011678] [G loss: -0.111165] [d1 loss: 0.085776] [d2 loss: 0.076843]  [sq d1 d2: 0.000080]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 240/676] [D loss: 0.002124] [G loss: -0.121475] [d1 loss: 0.078518] [d2 loss: 0.070181]  [sq d1 d2: 0.000070]  [num0: 11.000000] [num1 53.000000]
[Epoch 242/500] [Batch 260/676] [D loss: 0.000206] [G loss: -0.114332] [d1 loss: 0.040717] [d2 loss: 0.037837]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 280/676] [D loss: -0.015941] [G loss: -0.103918] [d1 loss: 0.039128] [d2 loss: 0.046291]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 300/676] [D loss: 0.009581] [G loss: -0.069465] [d1 loss: 0.035224] [d2 loss: 0.035756]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 320/676] [D loss: -0.008977] [G loss: -0.047427] [d1 loss: 0.052368] [d2 loss: 0.041559]  [sq d1 d2: 0.000117]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 340/676] [D loss: -0.000310] [G loss: -0.034286] [d1 loss: 0.058288] [d2 loss: 0.071466]  [sq d1 d2: 0.000174]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 360/676] [D loss: -0.010601] [G loss: -0.014887] [d1 loss: 0.093017] [d2 loss: 0.085981]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 242/500] [Batch 380/676] [D loss: -0.018938] [G loss: -0.003413] [d1 loss: 0.019680] [d2 loss: 0.035374]  [sq d1 d2: 0.000246]  [num0: 14.000000] [num1 50.000000]
[Epoch 242/500] [Batch 400/676] [D loss: -0.044566] [G loss: 0.004299] [d1 loss: 0.064206] [d2 loss: 0.062283]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 242/500] [Batch 420/676] [D loss: -0.029088] [G loss: 0.021227] [d1 loss: 0.104048] [d2 loss: 0.099575]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 440/676] [D loss: -0.011255] [G loss: 0.043700] [d1 loss: 0.077116] [d2 loss: 0.054039]  [sq d1 d2: 0.000533]  [num0: 14.000000] [num1 50.000000]
[Epoch 242/500] [Batch 460/676] [D loss: 0.010481] [G loss: 0.091690] [d1 loss: 0.153175] [d2 loss: 0.174784]  [sq d1 d2: 0.000467]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 480/676] [D loss: -0.011692] [G loss: 0.110427] [d1 loss: 0.031176] [d2 loss: 0.034510]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 242/500] [Batch 500/676] [D loss: -0.006678] [G loss: 0.130824] [d1 loss: 0.084388] [d2 loss: 0.084469]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 242/500] [Batch 520/676] [D loss: 0.001837] [G loss: 0.127300] [d1 loss: 0.053030] [d2 loss: 0.056338]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 242/500] [Batch 540/676] [D loss: 0.011255] [G loss: 0.152925] [d1 loss: 0.036438] [d2 loss: 0.032675]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 242/500] [Batch 560/676] [D loss: 0.003607] [G loss: 0.215579] [d1 loss: 0.089272] [d2 loss: 0.095220]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 242/500] [Batch 580/676] [D loss: -0.002154] [G loss: 0.218510] [d1 loss: 0.023951] [d2 loss: 0.028680]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 242/500] [Batch 600/676] [D loss: -0.014977] [G loss: 0.252059] [d1 loss: 0.041807] [d2 loss: 0.049534]  [sq d1 d2: 0.000060]  [num0: 19.000000] [num1 45.000000]
[Epoch 242/500] [Batch 620/676] [D loss: -0.020884] [G loss: 0.294929] [d1 loss: 0.027112] [d2 loss: 0.039519]  [sq d1 d2: 0.000154]  [num0: 14.000000] [num1 50.000000]
[Epoch 242/500] [Batch 640/676] [D loss: -0.005020] [G loss: 0.337805] [d1 loss: 0.055034] [d2 loss: 0.050224]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 242/500] [Batch 660/676] [D loss: -0.016380] [G loss: 0.352102] [d1 loss: 0.105195] [d2 loss: 0.094201]  [sq d1 d2: 0.000121]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 0/676] [D loss: -0.023287] [G loss: 0.348132] [d1 loss: 0.033258] [d2 loss: 0.034291]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 20/676] [D loss: -0.022219] [G loss: 0.363080] [d1 loss: 0.073883] [d2 loss: 0.100347]  [sq d1 d2: 0.000700]  [num0: 16.000000] [num1 48.000000]
[Epoch 243/500] [Batch 40/676] [D loss: 0.001408] [G loss: 0.348413] [d1 loss: 0.081528] [d2 loss: 0.089649]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 243/500] [Batch 60/676] [D loss: -0.020502] [G loss: 0.333806] [d1 loss: 0.040610] [d2 loss: 0.039861]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 243/500] [Batch 80/676] [D loss: -0.016312] [G loss: 0.245786] [d1 loss: 0.021184] [d2 loss: 0.017311]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]

[Epoch 243/500] [Batch 100/676] [D loss: 0.007002] [G loss: 0.184316] [d1 loss: 0.087488] [d2 loss: 0.082885]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 243/500] [Batch 120/676] [D loss: 0.007696] [G loss: 0.154935] [d1 loss: 0.051091] [d2 loss: 0.055957]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 140/676] [D loss: -0.004569] [G loss: 0.111842] [d1 loss: 0.052203] [d2 loss: 0.041969]  [sq d1 d2: 0.000105]  [num0: 12.000000] [num1 52.000000]
[Epoch 243/500] [Batch 160/676] [D loss: -0.019878] [G loss: 0.057858] [d1 loss: 0.036902] [d2 loss: 0.051124]  [sq d1 d2: 0.000202]  [num0: 11.000000] [num1 53.000000]
[Epoch 243/500] [Batch 180/676] [D loss: -0.026480] [G loss: 0.022318] [d1 loss: 0.017483] [d2 loss: 0.019089]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 200/676] [D loss: -0.036707] [G loss: -0.003420] [d1 loss: 0.056024] [d2 loss: 0.058509]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 243/500] [Batch 220/676] [D loss: -0.021471] [G loss: -0.030552] [d1 loss: 0.069198] [d2 loss: 0.118920]  [sq d1 d2: 0.002472]  [num0: 14.000000] [num1 50.000000]
[Epoch 243/500] [Batch 240/676] [D loss: -0.026740] [G loss: -0.096365] [d1 loss: 0.077698] [d2 loss: 0.086509]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 243/500] [Batch 260/676] [D loss: -0.026558] [G loss: -0.158357] [d1 loss: 0.058510] [d2 loss: 0.068953]  [sq d1 d2: 0.000109]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 280/676] [D loss: -0.025907] [G loss: -0.191970] [d1 loss: 0.040529] [d2 loss: 0.051838]  [sq d1 d2: 0.000128]  [num0: 13.000000] [num1 51.000000]
[Epoch 243/500] [Batch 300/676] [D loss: -0.020764] [G loss: -0.183456] [d1 loss: 0.032036] [d2 loss: 0.021195]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 320/676] [D loss: -0.008279] [G loss: -0.204486] [d1 loss: 0.086565] [d2 loss: 0.070931]  [sq d1 d2: 0.000244]  [num0: 17.000000] [num1 47.000000]
[Epoch 243/500] [Batch 340/676] [D loss: -0.001303] [G loss: -0.176815] [d1 loss: 0.065774] [d2 loss: 0.057578]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 243/500] [Batch 360/676] [D loss: 0.001817] [G loss: -0.163147] [d1 loss: 0.113594] [d2 loss: 0.112209]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 243/500] [Batch 380/676] [D loss: -0.006607] [G loss: -0.162721] [d1 loss: 0.047283] [d2 loss: 0.047051]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 243/500] [Batch 400/676] [D loss: -0.004271] [G loss: -0.191126] [d1 loss: 0.044560] [d2 loss: 0.044326]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 243/500] [Batch 420/676] [D loss: -0.018912] [G loss: -0.208225] [d1 loss: 0.057340] [d2 loss: 0.049124]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 440/676] [D loss: 0.001958] [G loss: -0.225660] [d1 loss: 0.111682] [d2 loss: 0.087802]  [sq d1 d2: 0.000570]  [num0: 18.000000] [num1 46.000000]
[Epoch 243/500] [Batch 460/676] [D loss: -0.030108] [G loss: -0.236549] [d1 loss: 0.130768] [d2 loss: 0.104205]  [sq d1 d2: 0.000706]  [num0: 18.000000] [num1 46.000000]
[Epoch 243/500] [Batch 480/676] [D loss: -0.012406] [G loss: -0.227479] [d1 loss: 0.057397] [d2 loss: 0.038582]  [sq d1 d2: 0.000354]  [num0: 16.000000] [num1 48.000000]
[Epoch 243/500] [Batch 500/676] [D loss: -0.040471] [G loss: -0.228886] [d1 loss: 0.059231] [d2 loss: 0.066062]  [sq d1 d2: 0.000047]  [num0: 20.000000] [num1 44.000000]
[Epoch 243/500] [Batch 520/676] [D loss: 0.013321] [G loss: -0.224741] [d1 loss: 0.083188] [d2 loss: 0.077391]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 243/500] [Batch 540/676] [D loss: -0.015832] [G loss: -0.196212] [d1 loss: 0.051512] [d2 loss: 0.071239]  [sq d1 d2: 0.000389]  [num0: 17.000000] [num1 47.000000]
[Epoch 243/500] [Batch 560/676] [D loss: 0.024235] [G loss: -0.200677] [d1 loss: 0.087413] [d2 loss: 0.062488]  [sq d1 d2: 0.000621]  [num0: 13.000000] [num1 51.000000]
[Epoch 243/500] [Batch 580/676] [D loss: 0.002538] [G loss: -0.221753] [d1 loss: 0.074406] [d2 loss: 0.074695]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 243/500] [Batch 600/676] [D loss: 0.007978] [G loss: -0.117120] [d1 loss: 0.047541] [d2 loss: 0.050136]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 243/500] [Batch 620/676] [D loss: -0.007899] [G loss: -0.111170] [d1 loss: 0.068540] [d2 loss: 0.073103]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 243/500] [Batch 640/676] [D loss: 0.002020] [G loss: -0.086759] [d1 loss: 0.072787] [d2 loss: 0.088229]  [sq d1 d2: 0.000238]  [num0: 17.000000] [num1 47.000000]
[Epoch 243/500] [Batch 660/676] [D loss: 0.002045] [G loss: -0.066730] [d1 loss: 0.030071] [d2 loss: 0.024629]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 244/500] [Batch 0/676] [D loss: -0.012977] [G loss: -0.045496] [d1 loss: 0.025937] [d2 loss: 0.039230]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 244/500] [Batch 20/676] [D loss: -0.015726] [G loss: -0.055913] [d1 loss: 0.076709] [d2 loss: 0.072975]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 244/500] [Batch 40/676] [D loss: -0.014994] [G loss: -0.053702] [d1 loss: 0.020015] [d2 loss: 0.025740]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 244/500] [Batch 60/676] [D loss: -0.006110] [G loss: -0.070903] [d1 loss: 0.034019] [d2 loss: 0.045136]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 80/676] [D loss: -0.011615] [G loss: -0.093225] [d1 loss: 0.068535] [d2 loss: 0.062931]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 100/676] [D loss: -0.011172] [G loss: -0.068651] [d1 loss: 0.034906] [d2 loss: 0.045923]  [sq d1 d2: 0.000121]  [num0: 16.000000] [num1 48.000000]
[Epoch 244/500] [Batch 120/676] [D loss: -0.015331] [G loss: -0.083088] [d1 loss: 0.028081] [d2 loss: 0.029267]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 244/500] [Batch 140/676] [D loss: 0.000173] [G loss: -0.057630] [d1 loss: 0.081697] [d2 loss: 0.060254]  [sq d1 d2: 0.000460]  [num0: 14.000000] [num1 50.000000]
[Epoch 244/500] [Batch 160/676] [D loss: -0.008164] [G loss: -0.050039] [d1 loss: 0.054911] [d2 loss: 0.041907]  [sq d1 d2: 0.000169]  [num0: 14.000000] [num1 50.000000]
[Epoch 244/500] [Batch 180/676] [D loss: 0.002702] [G loss: -0.070645] [d1 loss: 0.020951] [d2 loss: 0.022006]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 244/500] [Batch 200/676] [D loss: -0.011126] [G loss: -0.028198] [d1 loss: 0.047692] [d2 loss: 0.055701]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 244/500] [Batch 220/676] [D loss: 0.001870] [G loss: -0.016600] [d1 loss: 0.072022] [d2 loss: 0.056301]  [sq d1 d2: 0.000247]  [num0: 16.000000] [num1 48.000000]
[Epoch 244/500] [Batch 240/676] [D loss: 0.000077] [G loss: 0.014976] [d1 loss: 0.050996] [d2 loss: 0.087466]  [sq d1 d2: 0.001330]  [num0: 19.000000] [num1 45.000000]
[Epoch 244/500] [Batch 260/676] [D loss: -0.009491] [G loss: 0.013051] [d1 loss: 0.043474] [d2 loss: 0.044921]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 244/500] [Batch 280/676] [D loss: -0.011331] [G loss: 0.033175] [d1 loss: 0.060419] [d2 loss: 0.075351]  [sq d1 d2: 0.000223]  [num0: 20.000000] [num1 44.000000]
[Epoch 244/500] [Batch 300/676] [D loss: -0.011865] [G loss: 0.041819] [d1 loss: 0.066410] [d2 loss: 0.043077]  [sq d1 d2: 0.000544]  [num0: 16.000000] [num1 48.000000]
[Epoch 244/500] [Batch 320/676] [D loss: -0.018293] [G loss: 0.032657] [d1 loss: 0.037418] [d2 loss: 0.034395]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 244/500] [Batch 340/676] [D loss: -0.021142] [G loss: 0.013097] [d1 loss: 0.105644] [d2 loss: 0.075139]  [sq d1 d2: 0.000931]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 360/676] [D loss: -0.015816] [G loss: 0.003056] [d1 loss: 0.034291] [d2 loss: 0.034294]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 244/500] [Batch 380/676] [D loss: -0.023615] [G loss: -0.013765] [d1 loss: 0.052856] [d2 loss: 0.043855]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 400/676] [D loss: -0.013837] [G loss: 0.012757] [d1 loss: 0.044870] [d2 loss: 0.062011]  [sq d1 d2: 0.000294]  [num0: 16.000000] [num1 48.000000]
[Epoch 244/500] [Batch 420/676] [D loss: -0.007023] [G loss: 0.012200] [d1 loss: 0.050649] [d2 loss: 0.055086]  [sq d1 d2: 0.000020]  [num0: 19.000000] [num1 45.000000]
[Epoch 244/500] [Batch 440/676] [D loss: -0.003453] [G loss: 0.015164] [d1 loss: 0.037586] [d2 loss: 0.033689]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]

[Epoch 244/500] [Batch 460/676] [D loss: 0.012274] [G loss: 0.038420] [d1 loss: 0.042722] [d2 loss: 0.038312]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 244/500] [Batch 480/676] [D loss: -0.005076] [G loss: 0.013983] [d1 loss: 0.049063] [d2 loss: 0.041054]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 244/500] [Batch 500/676] [D loss: -0.009219] [G loss: 0.010714] [d1 loss: 0.064098] [d2 loss: 0.066494]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 520/676] [D loss: -0.013327] [G loss: 0.054196] [d1 loss: 0.075752] [d2 loss: 0.098028]  [sq d1 d2: 0.000496]  [num0: 13.000000] [num1 51.000000]
[Epoch 244/500] [Batch 540/676] [D loss: -0.017131] [G loss: 0.080625] [d1 loss: 0.083244] [d2 loss: 0.081321]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 244/500] [Batch 560/676] [D loss: -0.032474] [G loss: 0.109480] [d1 loss: 0.067993] [d2 loss: 0.066670]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 244/500] [Batch 580/676] [D loss: -0.021149] [G loss: 0.085864] [d1 loss: 0.014451] [d2 loss: 0.015814]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 244/500] [Batch 600/676] [D loss: -0.013010] [G loss: 0.036744] [d1 loss: 0.054102] [d2 loss: 0.060402]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 244/500] [Batch 620/676] [D loss: -0.002351] [G loss: 0.031978] [d1 loss: 0.070305] [d2 loss: 0.071385]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 244/500] [Batch 640/676] [D loss: -0.027724] [G loss: 0.051144] [d1 loss: 0.123990] [d2 loss: 0.083168]  [sq d1 d2: 0.001666]  [num0: 17.000000] [num1 47.000000]
[Epoch 244/500] [Batch 660/676] [D loss: 0.009354] [G loss: 0.085632] [d1 loss: 0.133172] [d2 loss: 0.122128]  [sq d1 d2: 0.000122]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 0/676] [D loss: -0.007860] [G loss: 0.055810] [d1 loss: 0.045857] [d2 loss: 0.041216]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 20/676] [D loss: 0.000717] [G loss: 0.031268] [d1 loss: 0.096213] [d2 loss: 0.115236]  [sq d1 d2: 0.000362]  [num0: 16.000000] [num1 48.000000]
[Epoch 245/500] [Batch 40/676] [D loss: 0.003247] [G loss: 0.047011] [d1 loss: 0.038378] [d2 loss: 0.036080]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 245/500] [Batch 60/676] [D loss: -0.015345] [G loss: 0.037400] [d1 loss: 0.072997] [d2 loss: 0.064954]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 80/676] [D loss: -0.003868] [G loss: 0.085343] [d1 loss: 0.117589] [d2 loss: 0.111129]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 245/500] [Batch 100/676] [D loss: -0.013609] [G loss: 0.087498] [d1 loss: 0.047681] [d2 loss: 0.040634]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 245/500] [Batch 120/676] [D loss: -0.034065] [G loss: 0.099137] [d1 loss: 0.028062] [d2 loss: 0.030745]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 245/500] [Batch 140/676] [D loss: -0.002262] [G loss: 0.112975] [d1 loss: 0.065279] [d2 loss: 0.077487]  [sq d1 d2: 0.000149]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 160/676] [D loss: -0.021970] [G loss: 0.115000] [d1 loss: 0.070831] [d2 loss: 0.078112]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 245/500] [Batch 180/676] [D loss: -0.010225] [G loss: 0.114019] [d1 loss: 0.058106] [d2 loss: 0.060788]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 245/500] [Batch 200/676] [D loss: -0.016119] [G loss: 0.084087] [d1 loss: 0.054957] [d2 loss: 0.076304]  [sq d1 d2: 0.000456]  [num0: 17.000000] [num1 47.000000]
[Epoch 245/500] [Batch 220/676] [D loss: 0.006122] [G loss: 0.084368] [d1 loss: 0.081522] [d2 loss: 0.095555]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 240/676] [D loss: -0.010092] [G loss: 0.065921] [d1 loss: 0.078700] [d2 loss: 0.133046]  [sq d1 d2: 0.002953]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 260/676] [D loss: -0.016099] [G loss: 0.052628] [d1 loss: 0.063941] [d2 loss: 0.060123]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 280/676] [D loss: -0.034891] [G loss: -0.003816] [d1 loss: 0.088800] [d2 loss: 0.086690]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 300/676] [D loss: -0.010422] [G loss: -0.076194] [d1 loss: 0.052317] [d2 loss: 0.047325]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 320/676] [D loss: -0.019512] [G loss: -0.092663] [d1 loss: 0.120675] [d2 loss: 0.106623]  [sq d1 d2: 0.000197]  [num0: 17.000000] [num1 47.000000]
[Epoch 245/500] [Batch 340/676] [D loss: -0.006460] [G loss: -0.109403] [d1 loss: 0.061531] [d2 loss: 0.052623]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 360/676] [D loss: -0.007622] [G loss: -0.110214] [d1 loss: 0.046592] [d2 loss: 0.044831]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 245/500] [Batch 380/676] [D loss: 0.002407] [G loss: -0.098499] [d1 loss: 0.030183] [d2 loss: 0.028582]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 245/500] [Batch 400/676] [D loss: -0.004331] [G loss: -0.130895] [d1 loss: 0.114070] [d2 loss: 0.093183]  [sq d1 d2: 0.000436]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 420/676] [D loss: 0.001844] [G loss: -0.115932] [d1 loss: 0.087321] [d2 loss: 0.087697]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 245/500] [Batch 440/676] [D loss: -0.018994] [G loss: -0.131957] [d1 loss: 0.075428] [d2 loss: 0.081909]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 460/676] [D loss: -0.001080] [G loss: -0.176746] [d1 loss: 0.049800] [d2 loss: 0.051131]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 245/500] [Batch 480/676] [D loss: -0.005586] [G loss: -0.161488] [d1 loss: 0.037417] [d2 loss: 0.062864]  [sq d1 d2: 0.000648]  [num0: 14.000000] [num1 50.000000]
[Epoch 245/500] [Batch 500/676] [D loss: -0.005340] [G loss: -0.146254] [d1 loss: 0.049193] [d2 loss: 0.082888]  [sq d1 d2: 0.001135]  [num0: 10.000000] [num1 54.000000]
[Epoch 245/500] [Batch 520/676] [D loss: -0.029778] [G loss: -0.176963] [d1 loss: 0.055547] [d2 loss: 0.054486]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 245/500] [Batch 540/676] [D loss: -0.034769] [G loss: -0.170030] [d1 loss: 0.036487] [d2 loss: 0.036976]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 245/500] [Batch 560/676] [D loss: -0.032508] [G loss: -0.162576] [d1 loss: 0.019502] [d2 loss: 0.029785]  [sq d1 d2: 0.000106]  [num0: 17.000000] [num1 47.000000]
[Epoch 245/500] [Batch 580/676] [D loss: -0.004232] [G loss: -0.149026] [d1 loss: 0.008598] [d2 loss: 0.011534]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 245/500] [Batch 600/676] [D loss: -0.028482] [G loss: -0.126729] [d1 loss: 0.034172] [d2 loss: 0.052396]  [sq d1 d2: 0.000332]  [num0: 16.000000] [num1 48.000000]
[Epoch 245/500] [Batch 620/676] [D loss: -0.018955] [G loss: -0.140199] [d1 loss: 0.093248] [d2 loss: 0.100077]  [sq d1 d2: 0.000047]  [num0: 20.000000] [num1 44.000000]
[Epoch 245/500] [Batch 640/676] [D loss: -0.047828] [G loss: -0.152927] [d1 loss: 0.089982] [d2 loss: 0.187662]  [sq d1 d2: 0.009541]  [num0: 21.000000] [num1 43.000000]
[Epoch 245/500] [Batch 660/676] [D loss: -0.017291] [G loss: -0.162645] [d1 loss: 0.015361] [d2 loss: 0.018257]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 0/676] [D loss: -0.010386] [G loss: -0.147443] [d1 loss: 0.018068] [d2 loss: 0.012200]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 246/500] [Batch 20/676] [D loss: -0.005549] [G loss: -0.139339] [d1 loss: 0.029281] [d2 loss: 0.027980]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 246/500] [Batch 40/676] [D loss: 0.001170] [G loss: -0.147316] [d1 loss: 0.167438] [d2 loss: 0.195044]  [sq d1 d2: 0.000762]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 60/676] [D loss: -0.009732] [G loss: -0.158096] [d1 loss: 0.087616] [d2 loss: 0.078678]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 246/500] [Batch 80/676] [D loss: -0.003963] [G loss: -0.146009] [d1 loss: 0.059932] [d2 loss: 0.057193]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 246/500] [Batch 100/676] [D loss: -0.044893] [G loss: -0.120487] [d1 loss: 0.042967] [d2 loss: 0.061383]  [sq d1 d2: 0.000339]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 120/676] [D loss: -0.000210] [G loss: -0.140526] [d1 loss: 0.043243] [d2 loss: 0.044096]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]

[Epoch 246/500] [Batch 140/676] [D loss: -0.022364] [G loss: -0.127102] [d1 loss: 0.019088] [d2 loss: 0.019221]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 160/676] [D loss: -0.015518] [G loss: -0.089684] [d1 loss: 0.066409] [d2 loss: 0.071556]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 246/500] [Batch 180/676] [D loss: 0.011913] [G loss: -0.100097] [d1 loss: 0.039173] [d2 loss: 0.036066]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 246/500] [Batch 200/676] [D loss: -0.016671] [G loss: -0.029556] [d1 loss: 0.054157] [d2 loss: 0.063363]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 220/676] [D loss: -0.015887] [G loss: -0.002549] [d1 loss: 0.035673] [d2 loss: 0.032391]  [sq d1 d2: 0.000011]  [num0: 12.000000] [num1 52.000000]
[Epoch 246/500] [Batch 240/676] [D loss: -0.034385] [G loss: 0.018722] [d1 loss: 0.079979] [d2 loss: 0.085324]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 260/676] [D loss: -0.011486] [G loss: 0.060506] [d1 loss: 0.084990] [d2 loss: 0.118338]  [sq d1 d2: 0.001112]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 280/676] [D loss: -0.020733] [G loss: 0.107124] [d1 loss: 0.067312] [d2 loss: 0.048000]  [sq d1 d2: 0.000373]  [num0: 14.000000] [num1 50.000000]
[Epoch 246/500] [Batch 300/676] [D loss: -0.042203] [G loss: 0.127981] [d1 loss: 0.026566] [d2 loss: 0.032826]  [sq d1 d2: 0.000039]  [num0: 12.000000] [num1 52.000000]
[Epoch 246/500] [Batch 320/676] [D loss: -0.010381] [G loss: 0.125233] [d1 loss: 0.059102] [d2 loss: 0.049824]  [sq d1 d2: 0.000086]  [num0: 13.000000] [num1 51.000000]
[Epoch 246/500] [Batch 340/676] [D loss: 0.005139] [G loss: 0.148789] [d1 loss: 0.052627] [d2 loss: 0.051233]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 246/500] [Batch 360/676] [D loss: -0.018317] [G loss: 0.142276] [d1 loss: 0.111814] [d2 loss: 0.169854]  [sq d1 d2: 0.003369]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 380/676] [D loss: -0.001383] [G loss: 0.105600] [d1 loss: 0.069746] [d2 loss: 0.068516]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 246/500] [Batch 400/676] [D loss: -0.032793] [G loss: 0.150427] [d1 loss: 0.103948] [d2 loss: 0.102115]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 420/676] [D loss: -0.019451] [G loss: 0.145772] [d1 loss: 0.039638] [d2 loss: 0.075202]  [sq d1 d2: 0.001265]  [num0: 14.000000] [num1 50.000000]
[Epoch 246/500] [Batch 440/676] [D loss: -0.020451] [G loss: 0.162924] [d1 loss: 0.092057] [d2 loss: 0.081987]  [sq d1 d2: 0.000101]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 460/676] [D loss: -0.012390] [G loss: 0.139996] [d1 loss: 0.041728] [d2 loss: 0.040838]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 246/500] [Batch 480/676] [D loss: 0.002972] [G loss: 0.135266] [d1 loss: 0.031338] [d2 loss: 0.035158]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 500/676] [D loss: -0.029330] [G loss: 0.082463] [d1 loss: 0.055299] [d2 loss: 0.064839]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 520/676] [D loss: -0.032151] [G loss: 0.060336] [d1 loss: 0.053407] [d2 loss: 0.060359]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 540/676] [D loss: 0.003772] [G loss: -0.019861] [d1 loss: 0.151015] [d2 loss: 0.126226]  [sq d1 d2: 0.000614]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 560/676] [D loss: -0.007862] [G loss: -0.002493] [d1 loss: 0.054929] [d2 loss: 0.055948]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 246/500] [Batch 580/676] [D loss: -0.025034] [G loss: 0.008074] [d1 loss: 0.056470] [d2 loss: 0.057311]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 246/500] [Batch 600/676] [D loss: -0.012163] [G loss: -0.024246] [d1 loss: 0.188787] [d2 loss: 0.228750]  [sq d1 d2: 0.001597]  [num0: 18.000000] [num1 46.000000]
[Epoch 246/500] [Batch 620/676] [D loss: 0.019227] [G loss: -0.047648] [d1 loss: 0.064149] [d2 loss: 0.071019]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 246/500] [Batch 640/676] [D loss: -0.035769] [G loss: -0.054872] [d1 loss: 0.033467] [d2 loss: 0.031865]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 246/500] [Batch 660/676] [D loss: -0.048801] [G loss: -0.051625] [d1 loss: 0.032008] [d2 loss: 0.042153]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 247/500] [Batch 0/676] [D loss: -0.031652] [G loss: -0.013638] [d1 loss: 0.052053] [d2 loss: 0.069067]  [sq d1 d2: 0.000289]  [num0: 13.000000] [num1 51.000000]
[Epoch 247/500] [Batch 20/676] [D loss: -0.026067] [G loss: -0.031384] [d1 loss: 0.062003] [d2 loss: 0.071827]  [sq d1 d2: 0.000097]  [num0: 23.000000] [num1 41.000000]
[Epoch 247/500] [Batch 40/676] [D loss: -0.027932] [G loss: -0.018378] [d1 loss: 0.118880] [d2 loss: 0.109492]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 60/676] [D loss: -0.023959] [G loss: -0.003814] [d1 loss: 0.022027] [d2 loss: 0.018477]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 247/500] [Batch 80/676] [D loss: -0.021412] [G loss: -0.017229] [d1 loss: 0.061184] [d2 loss: 0.065354]  [sq d1 d2: 0.000017]  [num0: 20.000000] [num1 44.000000]
[Epoch 247/500] [Batch 100/676] [D loss: -0.017516] [G loss: -0.018600] [d1 loss: 0.132065] [d2 loss: 0.094512]  [sq d1 d2: 0.001410]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 120/676] [D loss: -0.016223] [G loss: -0.028872] [d1 loss: 0.176401] [d2 loss: 0.200715]  [sq d1 d2: 0.000591]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 140/676] [D loss: -0.015269] [G loss: -0.081014] [d1 loss: 0.069820] [d2 loss: 0.077284]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 160/676] [D loss: 0.002105] [G loss: -0.102838] [d1 loss: 0.033215] [d2 loss: 0.029995]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 247/500] [Batch 180/676] [D loss: -0.020031] [G loss: -0.125604] [d1 loss: 0.101514] [d2 loss: 0.106327]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 247/500] [Batch 200/676] [D loss: -0.036436] [G loss: -0.150925] [d1 loss: 0.047202] [d2 loss: 0.042444]  [sq d1 d2: 0.000023]  [num0: 11.000000] [num1 53.000000]
[Epoch 247/500] [Batch 220/676] [D loss: 0.000698] [G loss: -0.137073] [d1 loss: 0.159416] [d2 loss: 0.151623]  [sq d1 d2: 0.000061]  [num0: 13.000000] [num1 51.000000]
[Epoch 247/500] [Batch 240/676] [D loss: -0.066057] [G loss: -0.221466] [d1 loss: 0.045591] [d2 loss: 0.045650]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 260/676] [D loss: -0.051567] [G loss: -0.259299] [d1 loss: 0.074514] [d2 loss: 0.121487]  [sq d1 d2: 0.002207]  [num0: 19.000000] [num1 45.000000]
[Epoch 247/500] [Batch 280/676] [D loss: 0.014329] [G loss: -0.290441] [d1 loss: 0.083115] [d2 loss: 0.053231]  [sq d1 d2: 0.000893]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 300/676] [D loss: -0.017521] [G loss: -0.362960] [d1 loss: 0.080137] [d2 loss: 0.079702]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 320/676] [D loss: -0.010421] [G loss: -0.308263] [d1 loss: 0.178373] [d2 loss: 0.166249]  [sq d1 d2: 0.000147]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 340/676] [D loss: -0.006707] [G loss: -0.303439] [d1 loss: 0.033450] [d2 loss: 0.045900]  [sq d1 d2: 0.000155]  [num0: 18.000000] [num1 46.000000]
[Epoch 247/500] [Batch 360/676] [D loss: -0.000347] [G loss: -0.248589] [d1 loss: 0.133474] [d2 loss: 0.129152]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 247/500] [Batch 380/676] [D loss: 0.001135] [G loss: -0.237210] [d1 loss: 0.042399] [d2 loss: 0.043607]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 400/676] [D loss: 0.003241] [G loss: -0.222101] [d1 loss: 0.080965] [d2 loss: 0.104342]  [sq d1 d2: 0.000546]  [num0: 16.000000] [num1 48.000000]
[Epoch 247/500] [Batch 420/676] [D loss: -0.027933] [G loss: -0.196555] [d1 loss: 0.040026] [d2 loss: 0.024982]  [sq d1 d2: 0.000226]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 440/676] [D loss: -0.008433] [G loss: -0.160732] [d1 loss: 0.029633] [d2 loss: 0.033915]  [sq d1 d2: 0.000018]  [num0: 20.000000] [num1 44.000000]
[Epoch 247/500] [Batch 460/676] [D loss: -0.029646] [G loss: -0.129944] [d1 loss: 0.116781] [d2 loss: 0.095641]  [sq d1 d2: 0.000447]  [num0: 14.000000] [num1 50.000000]
[Epoch 247/500] [Batch 480/676] [D loss: -0.007606] [G loss: -0.104321] [d1 loss: 0.094280] [d2 loss: 0.095754]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]

[Epoch 247/500] [Batch 500/676] [D loss: -0.019204] [G loss: -0.077805] [d1 loss: 0.048330] [d2 loss: 0.049339]  [sq d1 d2: 0.000001]  [num0: 8.000000] [num1 56.000000]
[Epoch 247/500] [Batch 520/676] [D loss: -0.014619] [G loss: -0.097548] [d1 loss: 0.105879] [d2 loss: 0.125630]  [sq d1 d2: 0.000390]  [num0: 12.000000] [num1 52.000000]
[Epoch 247/500] [Batch 540/676] [D loss: -0.001714] [G loss: -0.048079] [d1 loss: 0.038649] [d2 loss: 0.024128]  [sq d1 d2: 0.000211]  [num0: 17.000000] [num1 47.000000]
[Epoch 247/500] [Batch 560/676] [D loss: 0.006144] [G loss: 0.001473] [d1 loss: 0.033746] [d2 loss: 0.045701]  [sq d1 d2: 0.000143]  [num0: 14.000000] [num1 50.000000]
[Epoch 247/500] [Batch 580/676] [D loss: -0.026011] [G loss: 0.013226] [d1 loss: 0.116080] [d2 loss: 0.156800]  [sq d1 d2: 0.001658]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 600/676] [D loss: -0.041578] [G loss: 0.063542] [d1 loss: 0.031387] [d2 loss: 0.016429]  [sq d1 d2: 0.000224]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 620/676] [D loss: 0.004056] [G loss: 0.075945] [d1 loss: 0.072570] [d2 loss: 0.124013]  [sq d1 d2: 0.002646]  [num0: 12.000000] [num1 52.000000]
[Epoch 247/500] [Batch 640/676] [D loss: -0.021502] [G loss: 0.056532] [d1 loss: 0.046282] [d2 loss: 0.068826]  [sq d1 d2: 0.000508]  [num0: 15.000000] [num1 49.000000]
[Epoch 247/500] [Batch 660/676] [D loss: 0.002816] [G loss: 0.044333] [d1 loss: 0.090231] [d2 loss: 0.092917]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 0/676] [D loss: -0.019756] [G loss: 0.066319] [d1 loss: 0.051313] [d2 loss: 0.046094]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 248/500] [Batch 20/676] [D loss: -0.022625] [G loss: 0.064578] [d1 loss: 0.056716] [d2 loss: 0.070287]  [sq d1 d2: 0.000184]  [num0: 11.000000] [num1 53.000000]
[Epoch 248/500] [Batch 40/676] [D loss: -0.024062] [G loss: 0.076826] [d1 loss: 0.082536] [d2 loss: 0.114979]  [sq d1 d2: 0.001053]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 60/676] [D loss: -0.024306] [G loss: 0.059035] [d1 loss: 0.068536] [d2 loss: 0.069329]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 80/676] [D loss: -0.026117] [G loss: 0.000404] [d1 loss: 0.054138] [d2 loss: 0.080748]  [sq d1 d2: 0.000708]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 100/676] [D loss: -0.024699] [G loss: -0.002215] [d1 loss: 0.046412] [d2 loss: 0.042525]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 120/676] [D loss: -0.032788] [G loss: 0.011307] [d1 loss: 0.053659] [d2 loss: 0.049348]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 140/676] [D loss: -0.026143] [G loss: -0.015988] [d1 loss: 0.149794] [d2 loss: 0.110969]  [sq d1 d2: 0.001507]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 160/676] [D loss: -0.000903] [G loss: -0.051886] [d1 loss: 0.037665] [d2 loss: 0.052184]  [sq d1 d2: 0.000211]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 180/676] [D loss: -0.011289] [G loss: -0.011517] [d1 loss: 0.025751] [d2 loss: 0.015829]  [sq d1 d2: 0.000098]  [num0: 18.000000] [num1 46.000000]
[Epoch 248/500] [Batch 200/676] [D loss: -0.002744] [G loss: -0.041657] [d1 loss: 0.129025] [d2 loss: 0.162394]  [sq d1 d2: 0.001114]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 220/676] [D loss: -0.006571] [G loss: -0.048258] [d1 loss: 0.060007] [d2 loss: 0.051724]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 240/676] [D loss: -0.007283] [G loss: -0.090955] [d1 loss: 0.162859] [d2 loss: 0.150112]  [sq d1 d2: 0.000162]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 260/676] [D loss: -0.021719] [G loss: -0.120140] [d1 loss: 0.046735] [d2 loss: 0.034209]  [sq d1 d2: 0.000157]  [num0: 20.000000] [num1 44.000000]
[Epoch 248/500] [Batch 280/676] [D loss: -0.008338] [G loss: -0.150975] [d1 loss: 0.268766] [d2 loss: 0.225243]  [sq d1 d2: 0.001894]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 300/676] [D loss: -0.038467] [G loss: -0.159303] [d1 loss: 0.052534] [d2 loss: 0.054443]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 320/676] [D loss: -0.045057] [G loss: -0.168184] [d1 loss: 0.097668] [d2 loss: 0.096177]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 340/676] [D loss: -0.042590] [G loss: -0.160128] [d1 loss: 0.029555] [d2 loss: 0.032644]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 248/500] [Batch 360/676] [D loss: -0.048667] [G loss: -0.173485] [d1 loss: 0.122210] [d2 loss: 0.102185]  [sq d1 d2: 0.000401]  [num0: 17.000000] [num1 47.000000]
[Epoch 248/500] [Batch 380/676] [D loss: -0.018938] [G loss: -0.189927] [d1 loss: 0.021700] [d2 loss: 0.041657]  [sq d1 d2: 0.000398]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 400/676] [D loss: 0.037612] [G loss: -0.156141] [d1 loss: 0.041586] [d2 loss: 0.055736]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 420/676] [D loss: -0.016531] [G loss: -0.135758] [d1 loss: 0.049399] [d2 loss: 0.046786]  [sq d1 d2: 0.000007]  [num0: 10.000000] [num1 54.000000]
[Epoch 248/500] [Batch 440/676] [D loss: -0.010801] [G loss: -0.112095] [d1 loss: 0.016660] [d2 loss: 0.022656]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 460/676] [D loss: 0.017999] [G loss: -0.104529] [d1 loss: 0.033015] [d2 loss: 0.033683]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 480/676] [D loss: -0.026962] [G loss: -0.123289] [d1 loss: 0.012013] [d2 loss: 0.013722]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 500/676] [D loss: -0.024217] [G loss: -0.102340] [d1 loss: 0.083352] [d2 loss: 0.077850]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 520/676] [D loss: -0.002162] [G loss: -0.137203] [d1 loss: 0.105343] [d2 loss: 0.113155]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 540/676] [D loss: 0.005014] [G loss: -0.157336] [d1 loss: 0.088703] [d2 loss: 0.095133]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 248/500] [Batch 560/676] [D loss: -0.003907] [G loss: -0.151264] [d1 loss: 0.037307] [d2 loss: 0.029491]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 248/500] [Batch 580/676] [D loss: -0.024191] [G loss: -0.183210] [d1 loss: 0.041947] [d2 loss: 0.054676]  [sq d1 d2: 0.000162]  [num0: 16.000000] [num1 48.000000]
[Epoch 248/500] [Batch 600/676] [D loss: -0.020992] [G loss: -0.211472] [d1 loss: 0.056188] [d2 loss: 0.036729]  [sq d1 d2: 0.000379]  [num0: 15.000000] [num1 49.000000]
[Epoch 248/500] [Batch 620/676] [D loss: -0.001002] [G loss: -0.189538] [d1 loss: 0.029527] [d2 loss: 0.026109]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 248/500] [Batch 640/676] [D loss: -0.010160] [G loss: -0.177892] [d1 loss: 0.092159] [d2 loss: 0.090577]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 248/500] [Batch 660/676] [D loss: 0.000017] [G loss: -0.163495] [d1 loss: 0.028227] [d2 loss: 0.026439]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 249/500] [Batch 0/676] [D loss: -0.008700] [G loss: -0.132076] [d1 loss: 0.063353] [d2 loss: 0.058923]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 20/676] [D loss: -0.003714] [G loss: -0.110993] [d1 loss: 0.084810] [d2 loss: 0.091757]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 249/500] [Batch 40/676] [D loss: 0.001356] [G loss: -0.082581] [d1 loss: 0.048486] [d2 loss: 0.047595]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 60/676] [D loss: -0.010895] [G loss: -0.034383] [d1 loss: 0.055075] [d2 loss: 0.056262]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 249/500] [Batch 80/676] [D loss: -0.009392] [G loss: -0.054733] [d1 loss: 0.069446] [d2 loss: 0.039856]  [sq d1 d2: 0.000876]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 100/676] [D loss: -0.028848] [G loss: -0.029422] [d1 loss: 0.088069] [d2 loss: 0.098558]  [sq d1 d2: 0.000110]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 120/676] [D loss: -0.011440] [G loss: -0.030387] [d1 loss: 0.045589] [d2 loss: 0.046241]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 249/500] [Batch 140/676] [D loss: -0.021953] [G loss: -0.054901] [d1 loss: 0.053356] [d2 loss: 0.059027]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]

[Epoch 249/500] [Batch 160/676] [D loss: -0.013911] [G loss: -0.036538] [d1 loss: 0.043900] [d2 loss: 0.051320]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 249/500] [Batch 180/676] [D loss: -0.025561] [G loss: -0.029223] [d1 loss: 0.061586] [d2 loss: 0.064655]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 200/676] [D loss: -0.024235] [G loss: -0.039081] [d1 loss: 0.024775] [d2 loss: 0.032952]  [sq d1 d2: 0.000067]  [num0: 13.000000] [num1 51.000000]
[Epoch 249/500] [Batch 220/676] [D loss: -0.003356] [G loss: -0.064307] [d1 loss: 0.080878] [d2 loss: 0.042822]  [sq d1 d2: 0.001448]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 240/676] [D loss: 0.009517] [G loss: -0.048646] [d1 loss: 0.080030] [d2 loss: 0.077151]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 260/676] [D loss: 0.003475] [G loss: -0.066994] [d1 loss: 0.043211] [d2 loss: 0.040945]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 280/676] [D loss: -0.000995] [G loss: -0.097728] [d1 loss: 0.066997] [d2 loss: 0.065917]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 300/676] [D loss: -0.004885] [G loss: -0.095267] [d1 loss: 0.086389] [d2 loss: 0.083801]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 320/676] [D loss: -0.003613] [G loss: -0.063191] [d1 loss: 0.029667] [d2 loss: 0.027448]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 340/676] [D loss: -0.004939] [G loss: -0.055329] [d1 loss: 0.114471] [d2 loss: 0.121191]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 249/500] [Batch 360/676] [D loss: -0.026000] [G loss: -0.070890] [d1 loss: 0.083999] [d2 loss: 0.077201]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 249/500] [Batch 380/676] [D loss: -0.019983] [G loss: -0.091982] [d1 loss: 0.030319] [d2 loss: 0.041049]  [sq d1 d2: 0.000115]  [num0: 14.000000] [num1 50.000000]
[Epoch 249/500] [Batch 400/676] [D loss: -0.013999] [G loss: -0.120728] [d1 loss: 0.075847] [d2 loss: 0.087495]  [sq d1 d2: 0.000136]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 420/676] [D loss: -0.011747] [G loss: -0.126291] [d1 loss: 0.111568] [d2 loss: 0.089848]  [sq d1 d2: 0.000472]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 440/676] [D loss: -0.040219] [G loss: -0.157795] [d1 loss: 0.073990] [d2 loss: 0.075060]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 460/676] [D loss: -0.006980] [G loss: -0.132430] [d1 loss: 0.064207] [d2 loss: 0.068122]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 480/676] [D loss: 0.008136] [G loss: -0.087272] [d1 loss: 0.045189] [d2 loss: 0.048283]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 249/500] [Batch 500/676] [D loss: -0.010828] [G loss: -0.101025] [d1 loss: 0.056636] [d2 loss: 0.055957]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 520/676] [D loss: -0.009764] [G loss: -0.062875] [d1 loss: 0.110363] [d2 loss: 0.093451]  [sq d1 d2: 0.000286]  [num0: 18.000000] [num1 46.000000]
[Epoch 249/500] [Batch 540/676] [D loss: -0.003435] [G loss: -0.047573] [d1 loss: 0.062153] [d2 loss: 0.069755]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 249/500] [Batch 560/676] [D loss: -0.001229] [G loss: -0.013941] [d1 loss: 0.102784] [d2 loss: 0.106970]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 580/676] [D loss: -0.005495] [G loss: -0.001980] [d1 loss: 0.039612] [d2 loss: 0.056024]  [sq d1 d2: 0.000269]  [num0: 13.000000] [num1 51.000000]
[Epoch 249/500] [Batch 600/676] [D loss: -0.012669] [G loss: -0.002631] [d1 loss: 0.039022] [d2 loss: 0.039608]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 249/500] [Batch 620/676] [D loss: -0.015086] [G loss: 0.004946] [d1 loss: 0.040535] [d2 loss: 0.042170]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 249/500] [Batch 640/676] [D loss: -0.018226] [G loss: -0.004489] [d1 loss: 0.107075] [d2 loss: 0.095775]  [sq d1 d2: 0.000128]  [num0: 17.000000] [num1 47.000000]
[Epoch 249/500] [Batch 660/676] [D loss: -0.006535] [G loss: -0.007122] [d1 loss: 0.030857] [d2 loss: 0.025992]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 0/676] [D loss: -0.015316] [G loss: -0.030988] [d1 loss: 0.065506] [d2 loss: 0.084634]  [sq d1 d2: 0.000366]  [num0: 12.000000] [num1 52.000000]
[Epoch 250/500] [Batch 20/676] [D loss: -0.014493] [G loss: -0.067032] [d1 loss: 0.050503] [d2 loss: 0.060298]  [sq d1 d2: 0.000096]  [num0: 13.000000] [num1 51.000000]
[Epoch 250/500] [Batch 40/676] [D loss: -0.016552] [G loss: -0.048063] [d1 loss: 0.044545] [d2 loss: 0.054172]  [sq d1 d2: 0.000093]  [num0: 13.000000] [num1 51.000000]
[Epoch 250/500] [Batch 60/676] [D loss: -0.001970] [G loss: -0.059505] [d1 loss: 0.050206] [d2 loss: 0.054813]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 250/500] [Batch 80/676] [D loss: 0.015472] [G loss: -0.066533] [d1 loss: 0.060846] [d2 loss: 0.059386]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 250/500] [Batch 100/676] [D loss: -0.008308] [G loss: -0.074909] [d1 loss: 0.061555] [d2 loss: 0.055075]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 250/500] [Batch 120/676] [D loss: -0.012010] [G loss: -0.085031] [d1 loss: 0.078699] [d2 loss: 0.093671]  [sq d1 d2: 0.000224]  [num0: 13.000000] [num1 51.000000]
[Epoch 250/500] [Batch 140/676] [D loss: -0.013502] [G loss: -0.077320] [d1 loss: 0.091560] [d2 loss: 0.084735]  [sq d1 d2: 0.000047]  [num0: 12.000000] [num1 52.000000]
[Epoch 250/500] [Batch 160/676] [D loss: -0.010026] [G loss: -0.080991] [d1 loss: 0.052377] [d2 loss: 0.058926]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 250/500] [Batch 180/676] [D loss: -0.005453] [G loss: -0.091432] [d1 loss: 0.046636] [d2 loss: 0.042065]  [sq d1 d2: 0.000021]  [num0: 12.000000] [num1 52.000000]
[Epoch 250/500] [Batch 200/676] [D loss: -0.017015] [G loss: -0.078823] [d1 loss: 0.049947] [d2 loss: 0.046268]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 250/500] [Batch 220/676] [D loss: -0.027644] [G loss: -0.064071] [d1 loss: 0.077500] [d2 loss: 0.065747]  [sq d1 d2: 0.000138]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 240/676] [D loss: -0.015934] [G loss: -0.096195] [d1 loss: 0.083091] [d2 loss: 0.079464]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 250/500] [Batch 260/676] [D loss: -0.020728] [G loss: -0.126313] [d1 loss: 0.185680] [d2 loss: 0.165138]  [sq d1 d2: 0.000422]  [num0: 16.000000] [num1 48.000000]
[Epoch 250/500] [Batch 280/676] [D loss: -0.010327] [G loss: -0.149619] [d1 loss: 0.012969] [d2 loss: 0.014122]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 250/500] [Batch 300/676] [D loss: 0.004268] [G loss: -0.129538] [d1 loss: 0.041875] [d2 loss: 0.034145]  [sq d1 d2: 0.000060]  [num0: 18.000000] [num1 46.000000]
[Epoch 250/500] [Batch 320/676] [D loss: -0.015043] [G loss: -0.121646] [d1 loss: 0.096111] [d2 loss: 0.104211]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 340/676] [D loss: -0.000920] [G loss: -0.090720] [d1 loss: 0.049056] [d2 loss: 0.048977]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 250/500] [Batch 360/676] [D loss: -0.007058] [G loss: -0.075256] [d1 loss: 0.026850] [d2 loss: 0.026750]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 380/676] [D loss: 0.001443] [G loss: -0.069812] [d1 loss: 0.073874] [d2 loss: 0.068393]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 250/500] [Batch 400/676] [D loss: -0.002971] [G loss: -0.050492] [d1 loss: 0.081644] [d2 loss: 0.074788]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 250/500] [Batch 420/676] [D loss: -0.010796] [G loss: -0.030866] [d1 loss: 0.042973] [d2 loss: 0.049386]  [sq d1 d2: 0.000041]  [num0: 11.000000] [num1 53.000000]
[Epoch 250/500] [Batch 440/676] [D loss: -0.020422] [G loss: -0.030397] [d1 loss: 0.073609] [d2 loss: 0.074847]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 250/500] [Batch 460/676] [D loss: -0.009380] [G loss: -0.028681] [d1 loss: 0.104778] [d2 loss: 0.080778]  [sq d1 d2: 0.000576]  [num0: 20.000000] [num1 44.000000]
[Epoch 250/500] [Batch 480/676] [D loss: -0.019438] [G loss: -0.041155] [d1 loss: 0.074698] [d2 loss: 0.084230]  [sq d1 d2: 0.000091]  [num0: 18.000000] [num1 46.000000]
[Epoch 250/500] [Batch 500/676] [D loss: -0.021545] [G loss: -0.047695] [d1 loss: 0.114662] [d2 loss: 0.089727]  [sq d1 d2: 0.000622]  [num0: 11.000000] [num1 53.000000]

[Epoch 250/500] [Batch 520/676] [D loss: -0.012914] [G loss: -0.015784] [d1 loss: 0.055412] [d2 loss: 0.069328]  [sq d1 d2: 0.000194]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 540/676] [D loss: -0.014160] [G loss: 0.026825] [d1 loss: 0.039319] [d2 loss: 0.041004]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 250/500] [Batch 560/676] [D loss: -0.000494] [G loss: 0.011928] [d1 loss: 0.027856] [d2 loss: 0.031605]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 250/500] [Batch 580/676] [D loss: -0.007944] [G loss: -0.006605] [d1 loss: 0.149342] [d2 loss: 0.137933]  [sq d1 d2: 0.000130]  [num0: 18.000000] [num1 46.000000]
[Epoch 250/500] [Batch 600/676] [D loss: -0.011249] [G loss: 0.007453] [d1 loss: 0.033195] [d2 loss: 0.046570]  [sq d1 d2: 0.000179]  [num0: 17.000000] [num1 47.000000]
[Epoch 250/500] [Batch 620/676] [D loss: -0.000594] [G loss: 0.022869] [d1 loss: 0.026799] [d2 loss: 0.029794]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 250/500] [Batch 640/676] [D loss: -0.015024] [G loss: 0.009938] [d1 loss: 0.076343] [d2 loss: 0.081950]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 250/500] [Batch 660/676] [D loss: -0.008820] [G loss: 0.036161] [d1 loss: 0.073604] [d2 loss: 0.068007]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 251/500] [Batch 0/676] [D loss: -0.010567] [G loss: 0.013145] [d1 loss: 0.051471] [d2 loss: 0.041895]  [sq d1 d2: 0.000092]  [num0: 12.000000] [num1 52.000000]
[Epoch 251/500] [Batch 20/676] [D loss: -0.017362] [G loss: 0.023780] [d1 loss: 0.055515] [d2 loss: 0.069458]  [sq d1 d2: 0.000194]  [num0: 18.000000] [num1 46.000000]
[Epoch 251/500] [Batch 40/676] [D loss: -0.019453] [G loss: 0.034526] [d1 loss: 0.061410] [d2 loss: 0.049416]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 251/500] [Batch 60/676] [D loss: -0.018356] [G loss: 0.059432] [d1 loss: 0.052482] [d2 loss: 0.048923]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 80/676] [D loss: -0.008003] [G loss: 0.045185] [d1 loss: 0.122989] [d2 loss: 0.138104]  [sq d1 d2: 0.000228]  [num0: 19.000000] [num1 45.000000]
[Epoch 251/500] [Batch 100/676] [D loss: -0.015161] [G loss: 0.016473] [d1 loss: 0.031977] [d2 loss: 0.037177]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 251/500] [Batch 120/676] [D loss: -0.006878] [G loss: 0.012321] [d1 loss: 0.041005] [d2 loss: 0.063563]  [sq d1 d2: 0.000509]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 140/676] [D loss: -0.014434] [G loss: -0.003929] [d1 loss: 0.061026] [d2 loss: 0.062354]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 251/500] [Batch 160/676] [D loss: -0.006274] [G loss: 0.003457] [d1 loss: 0.066951] [d2 loss: 0.058152]  [sq d1 d2: 0.000077]  [num0: 19.000000] [num1 45.000000]
[Epoch 251/500] [Batch 180/676] [D loss: -0.002825] [G loss: -0.002200] [d1 loss: 0.040706] [d2 loss: 0.047164]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 251/500] [Batch 200/676] [D loss: -0.002206] [G loss: -0.012492] [d1 loss: 0.054315] [d2 loss: 0.060612]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 251/500] [Batch 220/676] [D loss: -0.016222] [G loss: -0.011399] [d1 loss: 0.068745] [d2 loss: 0.082027]  [sq d1 d2: 0.000176]  [num0: 16.000000] [num1 48.000000]
[Epoch 251/500] [Batch 240/676] [D loss: -0.006959] [G loss: -0.030784] [d1 loss: 0.102192] [d2 loss: 0.130460]  [sq d1 d2: 0.000799]  [num0: 16.000000] [num1 48.000000]
[Epoch 251/500] [Batch 260/676] [D loss: -0.013807] [G loss: -0.057188] [d1 loss: 0.071853] [d2 loss: 0.073429]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 251/500] [Batch 280/676] [D loss: -0.013540] [G loss: -0.089026] [d1 loss: 0.058022] [d2 loss: 0.054657]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 251/500] [Batch 300/676] [D loss: -0.015044] [G loss: -0.125675] [d1 loss: 0.036575] [d2 loss: 0.035595]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 251/500] [Batch 320/676] [D loss: -0.025799] [G loss: -0.109231] [d1 loss: 0.046839] [d2 loss: 0.058035]  [sq d1 d2: 0.000125]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 340/676] [D loss: -0.015637] [G loss: -0.114795] [d1 loss: 0.074363] [d2 loss: 0.072017]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 360/676] [D loss: -0.014004] [G loss: -0.116892] [d1 loss: 0.017386] [d2 loss: 0.015127]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 251/500] [Batch 380/676] [D loss: -0.003970] [G loss: -0.128262] [d1 loss: 0.070849] [d2 loss: 0.064703]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 400/676] [D loss: -0.020272] [G loss: -0.112224] [d1 loss: 0.032072] [d2 loss: 0.029471]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 251/500] [Batch 420/676] [D loss: 0.000726] [G loss: -0.110135] [d1 loss: 0.086908] [d2 loss: 0.066045]  [sq d1 d2: 0.000435]  [num0: 15.000000] [num1 49.000000]
[Epoch 251/500] [Batch 440/676] [D loss: 0.008195] [G loss: -0.105283] [d1 loss: 0.055168] [d2 loss: 0.050674]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 251/500] [Batch 460/676] [D loss: -0.021531] [G loss: -0.100273] [d1 loss: 0.053277] [d2 loss: 0.069831]  [sq d1 d2: 0.000274]  [num0: 12.000000] [num1 52.000000]
[Epoch 251/500] [Batch 480/676] [D loss: -0.014871] [G loss: -0.099388] [d1 loss: 0.091939] [d2 loss: 0.091512]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 251/500] [Batch 500/676] [D loss: -0.016186] [G loss: -0.106721] [d1 loss: 0.180713] [d2 loss: 0.153195]  [sq d1 d2: 0.000757]  [num0: 19.000000] [num1 45.000000]
[Epoch 251/500] [Batch 520/676] [D loss: -0.021934] [G loss: -0.118136] [d1 loss: 0.078065] [d2 loss: 0.074146]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 251/500] [Batch 540/676] [D loss: -0.008142] [G loss: -0.127945] [d1 loss: 0.029995] [d2 loss: 0.024116]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]
[Epoch 251/500] [Batch 560/676] [D loss: -0.016733] [G loss: -0.117850] [d1 loss: 0.057478] [d2 loss: 0.061090]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 251/500] [Batch 580/676] [D loss: -0.013420] [G loss: -0.092389] [d1 loss: 0.157458] [d2 loss: 0.145031]  [sq d1 d2: 0.000154]  [num0: 14.000000] [num1 50.000000]
[Epoch 251/500] [Batch 600/676] [D loss: -0.007919] [G loss: -0.062795] [d1 loss: 0.121474] [d2 loss: 0.143762]  [sq d1 d2: 0.000497]  [num0: 16.000000] [num1 48.000000]
[Epoch 251/500] [Batch 620/676] [D loss: -0.007638] [G loss: -0.051490] [d1 loss: 0.079376] [d2 loss: 0.056621]  [sq d1 d2: 0.000518]  [num0: 19.000000] [num1 45.000000]
[Epoch 251/500] [Batch 640/676] [D loss: -0.012959] [G loss: -0.093052] [d1 loss: 0.050780] [d2 loss: 0.054569]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 251/500] [Batch 660/676] [D loss: -0.000327] [G loss: -0.091567] [d1 loss: 0.044501] [d2 loss: 0.039783]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 0/676] [D loss: -0.012117] [G loss: -0.092737] [d1 loss: 0.097139] [d2 loss: 0.118792]  [sq d1 d2: 0.000469]  [num0: 17.000000] [num1 47.000000]
[Epoch 252/500] [Batch 20/676] [D loss: -0.006081] [G loss: -0.067614] [d1 loss: 0.059981] [d2 loss: 0.061394]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 40/676] [D loss: -0.004292] [G loss: -0.088383] [d1 loss: 0.027719] [d2 loss: 0.022221]  [sq d1 d2: 0.000030]  [num0: 21.000000] [num1 43.000000]
[Epoch 252/500] [Batch 60/676] [D loss: 0.003412] [G loss: -0.068638] [d1 loss: 0.160708] [d2 loss: 0.130524]  [sq d1 d2: 0.000911]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 80/676] [D loss: -0.014563] [G loss: -0.094126] [d1 loss: 0.126624] [d2 loss: 0.084907]  [sq d1 d2: 0.001740]  [num0: 19.000000] [num1 45.000000]
[Epoch 252/500] [Batch 100/676] [D loss: -0.017146] [G loss: -0.070361] [d1 loss: 0.042535] [d2 loss: 0.039182]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 252/500] [Batch 120/676] [D loss: -0.018366] [G loss: -0.055670] [d1 loss: 0.097817] [d2 loss: 0.080353]  [sq d1 d2: 0.000305]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 140/676] [D loss: -0.011918] [G loss: -0.054877] [d1 loss: 0.118100] [d2 loss: 0.134189]  [sq d1 d2: 0.000259]  [num0: 14.000000] [num1 50.000000]
[Epoch 252/500] [Batch 160/676] [D loss: -0.015650] [G loss: -0.072450] [d1 loss: 0.113765] [d2 loss: 0.127909]  [sq d1 d2: 0.000200]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 180/676] [D loss: 0.002240] [G loss: -0.062502] [d1 loss: 0.074776] [d2 loss: 0.084172]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]

[Epoch 252/500] [Batch 200/676] [D loss: 0.000354] [G loss: -0.063582] [d1 loss: 0.105259] [d2 loss: 0.111848]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 252/500] [Batch 220/676] [D loss: -0.036333] [G loss: -0.071179] [d1 loss: 0.042765] [d2 loss: 0.040988]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 252/500] [Batch 240/676] [D loss: 0.010597] [G loss: -0.079167] [d1 loss: 0.089741] [d2 loss: 0.081971]  [sq d1 d2: 0.000060]  [num0: 19.000000] [num1 45.000000]
[Epoch 252/500] [Batch 260/676] [D loss: -0.021227] [G loss: -0.049151] [d1 loss: 0.084428] [d2 loss: 0.099173]  [sq d1 d2: 0.000217]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 280/676] [D loss: -0.011484] [G loss: -0.071858] [d1 loss: 0.075376] [d2 loss: 0.075266]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 252/500] [Batch 300/676] [D loss: 0.006738] [G loss: -0.085967] [d1 loss: 0.044312] [d2 loss: 0.046389]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 252/500] [Batch 320/676] [D loss: -0.001354] [G loss: -0.075681] [d1 loss: 0.050829] [d2 loss: 0.049740]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 252/500] [Batch 340/676] [D loss: -0.012330] [G loss: -0.073885] [d1 loss: 0.086822] [d2 loss: 0.094400]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 360/676] [D loss: -0.008176] [G loss: -0.028340] [d1 loss: 0.053166] [d2 loss: 0.044633]  [sq d1 d2: 0.000073]  [num0: 12.000000] [num1 52.000000]
[Epoch 252/500] [Batch 380/676] [D loss: -0.030790] [G loss: 0.016229] [d1 loss: 0.022425] [d2 loss: 0.030893]  [sq d1 d2: 0.000072]  [num0: 13.000000] [num1 51.000000]
[Epoch 252/500] [Batch 400/676] [D loss: -0.017805] [G loss: 0.002894] [d1 loss: 0.160077] [d2 loss: 0.175048]  [sq d1 d2: 0.000224]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 420/676] [D loss: -0.021918] [G loss: 0.021109] [d1 loss: 0.071827] [d2 loss: 0.074382]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 252/500] [Batch 440/676] [D loss: -0.007498] [G loss: 0.021442] [d1 loss: 0.118542] [d2 loss: 0.136197]  [sq d1 d2: 0.000312]  [num0: 13.000000] [num1 51.000000]
[Epoch 252/500] [Batch 460/676] [D loss: -0.015104] [G loss: 0.040105] [d1 loss: 0.023900] [d2 loss: 0.023995]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 252/500] [Batch 480/676] [D loss: -0.020551] [G loss: 0.027005] [d1 loss: 0.047298] [d2 loss: 0.049524]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 252/500] [Batch 500/676] [D loss: -0.005207] [G loss: 0.041458] [d1 loss: 0.057949] [d2 loss: 0.066987]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 252/500] [Batch 520/676] [D loss: -0.012817] [G loss: 0.047159] [d1 loss: 0.082772] [d2 loss: 0.089083]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 252/500] [Batch 540/676] [D loss: -0.022650] [G loss: 0.047045] [d1 loss: 0.072127] [d2 loss: 0.064895]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 252/500] [Batch 560/676] [D loss: 0.010933] [G loss: 0.072142] [d1 loss: 0.042247] [d2 loss: 0.027742]  [sq d1 d2: 0.000210]  [num0: 16.000000] [num1 48.000000]
[Epoch 252/500] [Batch 580/676] [D loss: -0.014171] [G loss: 0.095323] [d1 loss: 0.122146] [d2 loss: 0.133460]  [sq d1 d2: 0.000128]  [num0: 19.000000] [num1 45.000000]
[Epoch 252/500] [Batch 600/676] [D loss: -0.022561] [G loss: 0.059851] [d1 loss: 0.132772] [d2 loss: 0.119778]  [sq d1 d2: 0.000169]  [num0: 14.000000] [num1 50.000000]
[Epoch 252/500] [Batch 620/676] [D loss: -0.027611] [G loss: 0.082544] [d1 loss: 0.050220] [d2 loss: 0.044765]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 252/500] [Batch 640/676] [D loss: -0.012665] [G loss: 0.072099] [d1 loss: 0.054214] [d2 loss: 0.058452]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 252/500] [Batch 660/676] [D loss: -0.002781] [G loss: 0.014758] [d1 loss: 0.018979] [d2 loss: 0.020565]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 253/500] [Batch 0/676] [D loss: -0.000140] [G loss: -0.009414] [d1 loss: 0.084528] [d2 loss: 0.085084]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 253/500] [Batch 20/676] [D loss: -0.017167] [G loss: -0.026902] [d1 loss: 0.035276] [d2 loss: 0.028225]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 253/500] [Batch 40/676] [D loss: -0.004953] [G loss: -0.091735] [d1 loss: 0.099989] [d2 loss: 0.086642]  [sq d1 d2: 0.000178]  [num0: 17.000000] [num1 47.000000]
[Epoch 253/500] [Batch 60/676] [D loss: -0.008848] [G loss: -0.150873] [d1 loss: 0.056542] [d2 loss: 0.048193]  [sq d1 d2: 0.000070]  [num0: 11.000000] [num1 53.000000]
[Epoch 253/500] [Batch 80/676] [D loss: -0.004125] [G loss: -0.158154] [d1 loss: 0.073718] [d2 loss: 0.071200]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 100/676] [D loss: -0.024760] [G loss: -0.156747] [d1 loss: 0.143779] [d2 loss: 0.146241]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 253/500] [Batch 120/676] [D loss: -0.019578] [G loss: -0.214584] [d1 loss: 0.022349] [d2 loss: 0.029116]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 253/500] [Batch 140/676] [D loss: -0.017360] [G loss: -0.229030] [d1 loss: 0.060031] [d2 loss: 0.067075]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 160/676] [D loss: 0.011002] [G loss: -0.218314] [d1 loss: 0.041367] [d2 loss: 0.043229]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 253/500] [Batch 180/676] [D loss: 0.000444] [G loss: -0.252687] [d1 loss: 0.073015] [d2 loss: 0.066691]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 253/500] [Batch 200/676] [D loss: -0.022203] [G loss: -0.234700] [d1 loss: 0.020404] [d2 loss: 0.017375]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 253/500] [Batch 220/676] [D loss: -0.026992] [G loss: -0.174887] [d1 loss: 0.020166] [d2 loss: 0.021688]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 240/676] [D loss: -0.019010] [G loss: -0.115286] [d1 loss: 0.059339] [d2 loss: 0.073756]  [sq d1 d2: 0.000208]  [num0: 16.000000] [num1 48.000000]
[Epoch 253/500] [Batch 260/676] [D loss: -0.004221] [G loss: -0.111059] [d1 loss: 0.083265] [d2 loss: 0.102303]  [sq d1 d2: 0.000362]  [num0: 16.000000] [num1 48.000000]
[Epoch 253/500] [Batch 280/676] [D loss: -0.002979] [G loss: -0.098527] [d1 loss: 0.069613] [d2 loss: 0.062528]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 253/500] [Batch 300/676] [D loss: -0.005559] [G loss: -0.068996] [d1 loss: 0.073010] [d2 loss: 0.072695]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 253/500] [Batch 320/676] [D loss: -0.019877] [G loss: -0.069620] [d1 loss: 0.065449] [d2 loss: 0.067101]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 253/500] [Batch 340/676] [D loss: -0.021574] [G loss: -0.068211] [d1 loss: 0.137117] [d2 loss: 0.149766]  [sq d1 d2: 0.000160]  [num0: 18.000000] [num1 46.000000]
[Epoch 253/500] [Batch 360/676] [D loss: -0.022284] [G loss: -0.055892] [d1 loss: 0.142700] [d2 loss: 0.128919]  [sq d1 d2: 0.000190]  [num0: 17.000000] [num1 47.000000]
[Epoch 253/500] [Batch 380/676] [D loss: -0.018039] [G loss: -0.065880] [d1 loss: 0.078610] [d2 loss: 0.072459]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 400/676] [D loss: -0.020374] [G loss: -0.037337] [d1 loss: 0.036552] [d2 loss: 0.045232]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 253/500] [Batch 420/676] [D loss: -0.031172] [G loss: -0.077197] [d1 loss: 0.062989] [d2 loss: 0.067545]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 253/500] [Batch 440/676] [D loss: -0.034596] [G loss: -0.063975] [d1 loss: 0.148269] [d2 loss: 0.126837]  [sq d1 d2: 0.000459]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 460/676] [D loss: -0.022187] [G loss: -0.097242] [d1 loss: 0.071843] [d2 loss: 0.073355]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 253/500] [Batch 480/676] [D loss: -0.023155] [G loss: -0.053899] [d1 loss: 0.076943] [d2 loss: 0.084547]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 253/500] [Batch 500/676] [D loss: 0.010562] [G loss: -0.058263] [d1 loss: 0.068524] [d2 loss: 0.055894]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 520/676] [D loss: -0.012187] [G loss: -0.079730] [d1 loss: 0.027855] [d2 loss: 0.029967]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 253/500] [Batch 540/676] [D loss: 0.009567] [G loss: -0.084111] [d1 loss: 0.039887] [d2 loss: 0.033904]  [sq d1 d2: 0.000036]  [num0: 19.000000] [num1 45.000000]

[Epoch 253/500] [Batch 560/676] [D loss: 0.008458] [G loss: -0.112245] [d1 loss: 0.058126] [d2 loss: 0.046294]  [sq d1 d2: 0.000140]  [num0: 20.000000] [num1 44.000000]
[Epoch 253/500] [Batch 580/676] [D loss: -0.008084] [G loss: -0.112022] [d1 loss: 0.146929] [d2 loss: 0.110742]  [sq d1 d2: 0.001309]  [num0: 15.000000] [num1 49.000000]
[Epoch 253/500] [Batch 600/676] [D loss: -0.020064] [G loss: -0.117020] [d1 loss: 0.108899] [d2 loss: 0.098439]  [sq d1 d2: 0.000109]  [num0: 17.000000] [num1 47.000000]
[Epoch 253/500] [Batch 620/676] [D loss: -0.029595] [G loss: -0.123792] [d1 loss: 0.073330] [d2 loss: 0.088534]  [sq d1 d2: 0.000231]  [num0: 14.000000] [num1 50.000000]
[Epoch 253/500] [Batch 640/676] [D loss: -0.041514] [G loss: -0.128474] [d1 loss: 0.022664] [d2 loss: 0.025356]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 253/500] [Batch 660/676] [D loss: -0.014859] [G loss: -0.178079] [d1 loss: 0.054579] [d2 loss: 0.058798]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 254/500] [Batch 0/676] [D loss: -0.025103] [G loss: -0.142316] [d1 loss: 0.007727] [d2 loss: 0.007613]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 254/500] [Batch 20/676] [D loss: -0.017375] [G loss: -0.160768] [d1 loss: 0.150533] [d2 loss: 0.154268]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 254/500] [Batch 40/676] [D loss: -0.008241] [G loss: -0.104351] [d1 loss: 0.099985] [d2 loss: 0.102650]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 254/500] [Batch 60/676] [D loss: -0.003332] [G loss: -0.115924] [d1 loss: 0.089741] [d2 loss: 0.073588]  [sq d1 d2: 0.000261]  [num0: 13.000000] [num1 51.000000]
[Epoch 254/500] [Batch 80/676] [D loss: 0.004972] [G loss: -0.051488] [d1 loss: 0.056000] [d2 loss: 0.065703]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 254/500] [Batch 100/676] [D loss: -0.029860] [G loss: -0.009617] [d1 loss: 0.129787] [d2 loss: 0.106326]  [sq d1 d2: 0.000550]  [num0: 20.000000] [num1 44.000000]
[Epoch 254/500] [Batch 120/676] [D loss: -0.011270] [G loss: -0.016286] [d1 loss: 0.108896] [d2 loss: 0.115373]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 254/500] [Batch 140/676] [D loss: -0.005386] [G loss: -0.010096] [d1 loss: 0.116882] [d2 loss: 0.111845]  [sq d1 d2: 0.000025]  [num0: 21.000000] [num1 43.000000]
[Epoch 254/500] [Batch 160/676] [D loss: -0.019121] [G loss: -0.014740] [d1 loss: 0.073932] [d2 loss: 0.072466]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 180/676] [D loss: -0.029597] [G loss: -0.013406] [d1 loss: 0.074696] [d2 loss: 0.094055]  [sq d1 d2: 0.000375]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 200/676] [D loss: -0.023554] [G loss: -0.015856] [d1 loss: 0.111054] [d2 loss: 0.091002]  [sq d1 d2: 0.000402]  [num0: 10.000000] [num1 54.000000]
[Epoch 254/500] [Batch 220/676] [D loss: -0.033072] [G loss: -0.078214] [d1 loss: 0.051904] [d2 loss: 0.085705]  [sq d1 d2: 0.001142]  [num0: 18.000000] [num1 46.000000]
[Epoch 254/500] [Batch 240/676] [D loss: -0.036431] [G loss: -0.089649] [d1 loss: 0.063843] [d2 loss: 0.077999]  [sq d1 d2: 0.000200]  [num0: 10.000000] [num1 54.000000]
[Epoch 254/500] [Batch 260/676] [D loss: 0.003366] [G loss: -0.098398] [d1 loss: 0.045726] [d2 loss: 0.047944]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 254/500] [Batch 280/676] [D loss: -0.000311] [G loss: -0.062781] [d1 loss: 0.037601] [d2 loss: 0.034005]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 254/500] [Batch 300/676] [D loss: 0.010399] [G loss: -0.089688] [d1 loss: 0.112567] [d2 loss: 0.110011]  [sq d1 d2: 0.000007]  [num0: 10.000000] [num1 54.000000]
[Epoch 254/500] [Batch 320/676] [D loss: 0.020613] [G loss: -0.120122] [d1 loss: 0.096157] [d2 loss: 0.094626]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 254/500] [Batch 340/676] [D loss: -0.025857] [G loss: -0.132146] [d1 loss: 0.039526] [d2 loss: 0.044764]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 254/500] [Batch 360/676] [D loss: -0.009426] [G loss: -0.171352] [d1 loss: 0.066521] [d2 loss: 0.081747]  [sq d1 d2: 0.000232]  [num0: 11.000000] [num1 53.000000]
[Epoch 254/500] [Batch 380/676] [D loss: -0.014249] [G loss: -0.223334] [d1 loss: 0.057848] [d2 loss: 0.064435]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 400/676] [D loss: -0.039944] [G loss: -0.296416] [d1 loss: 0.019153] [d2 loss: 0.023989]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 254/500] [Batch 420/676] [D loss: -0.028190] [G loss: -0.362844] [d1 loss: 0.098264] [d2 loss: 0.081775]  [sq d1 d2: 0.000272]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 440/676] [D loss: 0.021692] [G loss: -0.402662] [d1 loss: 0.057382] [d2 loss: 0.060120]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 460/676] [D loss: -0.036311] [G loss: -0.395539] [d1 loss: 0.086961] [d2 loss: 0.083127]  [sq d1 d2: 0.000015]  [num0: 21.000000] [num1 43.000000]
[Epoch 254/500] [Batch 480/676] [D loss: -0.014293] [G loss: -0.399833] [d1 loss: 0.063924] [d2 loss: 0.067015]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 254/500] [Batch 500/676] [D loss: 0.005055] [G loss: -0.316348] [d1 loss: 0.084116] [d2 loss: 0.092913]  [sq d1 d2: 0.000077]  [num0: 22.000000] [num1 42.000000]
[Epoch 254/500] [Batch 520/676] [D loss: -0.005025] [G loss: -0.215635] [d1 loss: 0.098122] [d2 loss: 0.099961]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 254/500] [Batch 540/676] [D loss: -0.001440] [G loss: -0.131391] [d1 loss: 0.043707] [d2 loss: 0.049272]  [sq d1 d2: 0.000031]  [num0: 11.000000] [num1 53.000000]
[Epoch 254/500] [Batch 560/676] [D loss: -0.000855] [G loss: -0.097780] [d1 loss: 0.043897] [d2 loss: 0.043305]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 580/676] [D loss: -0.005775] [G loss: -0.045513] [d1 loss: 0.023776] [d2 loss: 0.028058]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 254/500] [Batch 600/676] [D loss: -0.012099] [G loss: 0.010059] [d1 loss: 0.082579] [d2 loss: 0.080442]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 254/500] [Batch 620/676] [D loss: -0.030791] [G loss: 0.056221] [d1 loss: 0.052964] [d2 loss: 0.088564]  [sq d1 d2: 0.001267]  [num0: 17.000000] [num1 47.000000]
[Epoch 254/500] [Batch 640/676] [D loss: -0.043051] [G loss: 0.094344] [d1 loss: 0.078359] [d2 loss: 0.069502]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 254/500] [Batch 660/676] [D loss: -0.045675] [G loss: 0.149064] [d1 loss: 0.017795] [d2 loss: 0.020794]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 0/676] [D loss: -0.056703] [G loss: 0.171624] [d1 loss: 0.014529] [d2 loss: 0.042682]  [sq d1 d2: 0.000793]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 20/676] [D loss: -0.070981] [G loss: 0.202662] [d1 loss: 0.048992] [d2 loss: 0.056159]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 255/500] [Batch 40/676] [D loss: 0.003833] [G loss: 0.176527] [d1 loss: 0.047704] [d2 loss: 0.048675]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 60/676] [D loss: -0.025380] [G loss: 0.177312] [d1 loss: 0.075221] [d2 loss: 0.060996]  [sq d1 d2: 0.000202]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 80/676] [D loss: -0.024064] [G loss: 0.175715] [d1 loss: 0.063053] [d2 loss: 0.056410]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 255/500] [Batch 100/676] [D loss: 0.001465] [G loss: 0.142234] [d1 loss: 0.073713] [d2 loss: 0.085594]  [sq d1 d2: 0.000141]  [num0: 14.000000] [num1 50.000000]
[Epoch 255/500] [Batch 120/676] [D loss: -0.002081] [G loss: 0.111014] [d1 loss: 0.059776] [d2 loss: 0.091798]  [sq d1 d2: 0.001025]  [num0: 14.000000] [num1 50.000000]
[Epoch 255/500] [Batch 140/676] [D loss: -0.009748] [G loss: 0.066318] [d1 loss: 0.063257] [d2 loss: 0.047816]  [sq d1 d2: 0.000238]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 160/676] [D loss: -0.010756] [G loss: 0.024603] [d1 loss: 0.103940] [d2 loss: 0.089896]  [sq d1 d2: 0.000197]  [num0: 14.000000] [num1 50.000000]
[Epoch 255/500] [Batch 180/676] [D loss: -0.033738] [G loss: -0.008998] [d1 loss: 0.070991] [d2 loss: 0.073511]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 255/500] [Batch 200/676] [D loss: -0.019413] [G loss: -0.040464] [d1 loss: 0.072485] [d2 loss: 0.079676]  [sq d1 d2: 0.000052]  [num0: 13.000000] [num1 51.000000]
[Epoch 255/500] [Batch 220/676] [D loss: -0.009438] [G loss: -0.102064] [d1 loss: 0.057382] [d2 loss: 0.054995]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]

[Epoch 255/500] [Batch 240/676] [D loss: -0.059490] [G loss: -0.145656] [d1 loss: 0.009281] [d2 loss: 0.008697]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 260/676] [D loss: -0.019898] [G loss: -0.168363] [d1 loss: 0.094340] [d2 loss: 0.087564]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 280/676] [D loss: -0.033935] [G loss: -0.215675] [d1 loss: 0.032840] [d2 loss: 0.035293]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 255/500] [Batch 300/676] [D loss: 0.000984] [G loss: -0.251762] [d1 loss: 0.084610] [d2 loss: 0.115409]  [sq d1 d2: 0.000949]  [num0: 13.000000] [num1 51.000000]
[Epoch 255/500] [Batch 320/676] [D loss: -0.003687] [G loss: -0.192418] [d1 loss: 0.057408] [d2 loss: 0.051325]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 340/676] [D loss: 0.012388] [G loss: -0.117343] [d1 loss: 0.061219] [d2 loss: 0.048726]  [sq d1 d2: 0.000156]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 360/676] [D loss: 0.000000] [G loss: -0.022536] [d1 loss: 0.052093] [d2 loss: 0.055210]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 255/500] [Batch 380/676] [D loss: -0.003106] [G loss: 0.046170] [d1 loss: 0.044289] [d2 loss: 0.055150]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 400/676] [D loss: -0.005944] [G loss: 0.111542] [d1 loss: 0.034477] [d2 loss: 0.039420]  [sq d1 d2: 0.000024]  [num0: 21.000000] [num1 43.000000]
[Epoch 255/500] [Batch 420/676] [D loss: -0.031556] [G loss: 0.190486] [d1 loss: 0.082103] [d2 loss: 0.075862]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 440/676] [D loss: 0.004000] [G loss: 0.253459] [d1 loss: 0.084024] [d2 loss: 0.074860]  [sq d1 d2: 0.000084]  [num0: 18.000000] [num1 46.000000]
[Epoch 255/500] [Batch 460/676] [D loss: -0.039468] [G loss: 0.253405] [d1 loss: 0.052350] [d2 loss: 0.060136]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 255/500] [Batch 480/676] [D loss: -0.038734] [G loss: 0.270466] [d1 loss: 0.038673] [d2 loss: 0.033918]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 255/500] [Batch 500/676] [D loss: -0.008084] [G loss: 0.253243] [d1 loss: 0.082255] [d2 loss: 0.078037]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 255/500] [Batch 520/676] [D loss: 0.001227] [G loss: 0.224883] [d1 loss: 0.122371] [d2 loss: 0.123550]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 255/500] [Batch 540/676] [D loss: 0.007586] [G loss: 0.120503] [d1 loss: 0.122654] [d2 loss: 0.094736]  [sq d1 d2: 0.000779]  [num0: 13.000000] [num1 51.000000]
[Epoch 255/500] [Batch 560/676] [D loss: 0.005673] [G loss: 0.031402] [d1 loss: 0.117030] [d2 loss: 0.172819]  [sq d1 d2: 0.003112]  [num0: 16.000000] [num1 48.000000]
[Epoch 255/500] [Batch 580/676] [D loss: -0.005940] [G loss: 0.011767] [d1 loss: 0.047951] [d2 loss: 0.054041]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 255/500] [Batch 600/676] [D loss: -0.002234] [G loss: -0.055662] [d1 loss: 0.106866] [d2 loss: 0.085555]  [sq d1 d2: 0.000454]  [num0: 17.000000] [num1 47.000000]
[Epoch 255/500] [Batch 620/676] [D loss: -0.009575] [G loss: -0.063270] [d1 loss: 0.054439] [d2 loss: 0.054580]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 255/500] [Batch 640/676] [D loss: -0.018139] [G loss: -0.126616] [d1 loss: 0.071248] [d2 loss: 0.074916]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 255/500] [Batch 660/676] [D loss: -0.026851] [G loss: -0.153430] [d1 loss: 0.058844] [d2 loss: 0.060936]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 256/500] [Batch 0/676] [D loss: -0.031426] [G loss: -0.235804] [d1 loss: 0.115910] [d2 loss: 0.095388]  [sq d1 d2: 0.000421]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 20/676] [D loss: -0.027484] [G loss: -0.239127] [d1 loss: 0.022031] [d2 loss: 0.024193]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 256/500] [Batch 40/676] [D loss: 0.008996] [G loss: -0.208708] [d1 loss: 0.046812] [d2 loss: 0.041934]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 256/500] [Batch 60/676] [D loss: 0.000192] [G loss: -0.169114] [d1 loss: 0.085859] [d2 loss: 0.085531]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 256/500] [Batch 80/676] [D loss: 0.013553] [G loss: -0.137484] [d1 loss: 0.083550] [d2 loss: 0.068219]  [sq d1 d2: 0.000235]  [num0: 19.000000] [num1 45.000000]
[Epoch 256/500] [Batch 100/676] [D loss: -0.000499] [G loss: -0.119874] [d1 loss: 0.030393] [d2 loss: 0.028760]  [sq d1 d2: 0.000003]  [num0: 20.000000] [num1 44.000000]
[Epoch 256/500] [Batch 120/676] [D loss: -0.007923] [G loss: -0.064583] [d1 loss: 0.097924] [d2 loss: 0.091629]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 256/500] [Batch 140/676] [D loss: -0.004343] [G loss: -0.025333] [d1 loss: 0.107589] [d2 loss: 0.102715]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 256/500] [Batch 160/676] [D loss: -0.023646] [G loss: 0.053952] [d1 loss: 0.046639] [d2 loss: 0.050955]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 180/676] [D loss: -0.016453] [G loss: 0.097334] [d1 loss: 0.014111] [d2 loss: 0.019893]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 256/500] [Batch 200/676] [D loss: -0.006698] [G loss: 0.162375] [d1 loss: 0.053330] [d2 loss: 0.072748]  [sq d1 d2: 0.000377]  [num0: 13.000000] [num1 51.000000]
[Epoch 256/500] [Batch 220/676] [D loss: -0.045784] [G loss: 0.214980] [d1 loss: 0.128465] [d2 loss: 0.134189]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 256/500] [Batch 240/676] [D loss: -0.020366] [G loss: 0.233551] [d1 loss: 0.046003] [d2 loss: 0.051530]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 256/500] [Batch 260/676] [D loss: -0.000115] [G loss: 0.192894] [d1 loss: 0.064949] [d2 loss: 0.059371]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 280/676] [D loss: 0.033141] [G loss: 0.125000] [d1 loss: 0.126951] [d2 loss: 0.121085]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 256/500] [Batch 300/676] [D loss: 0.007945] [G loss: 0.070731] [d1 loss: 0.064199] [d2 loss: 0.076325]  [sq d1 d2: 0.000147]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 320/676] [D loss: -0.004678] [G loss: 0.034025] [d1 loss: 0.130110] [d2 loss: 0.111800]  [sq d1 d2: 0.000335]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 340/676] [D loss: -0.006442] [G loss: 0.021405] [d1 loss: 0.043535] [d2 loss: 0.041460]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 256/500] [Batch 360/676] [D loss: -0.014620] [G loss: -0.030870] [d1 loss: 0.142529] [d2 loss: 0.173303]  [sq d1 d2: 0.000947]  [num0: 17.000000] [num1 47.000000]
[Epoch 256/500] [Batch 380/676] [D loss: -0.024199] [G loss: -0.063908] [d1 loss: 0.049481] [d2 loss: 0.058332]  [sq d1 d2: 0.000078]  [num0: 11.000000] [num1 53.000000]
[Epoch 256/500] [Batch 400/676] [D loss: -0.024949] [G loss: -0.084122] [d1 loss: 0.108760] [d2 loss: 0.125430]  [sq d1 d2: 0.000278]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 420/676] [D loss: 0.001081] [G loss: -0.054249] [d1 loss: 0.435977] [d2 loss: 0.413958]  [sq d1 d2: 0.000485]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 440/676] [D loss: -0.001399] [G loss: -0.109060] [d1 loss: 0.067238] [d2 loss: 0.062777]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 460/676] [D loss: -0.031490] [G loss: -0.126671] [d1 loss: 0.039250] [d2 loss: 0.033463]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 256/500] [Batch 480/676] [D loss: -0.002643] [G loss: -0.138747] [d1 loss: 0.087987] [d2 loss: 0.086623]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 500/676] [D loss: 0.028686] [G loss: -0.124608] [d1 loss: 0.085697] [d2 loss: 0.108701]  [sq d1 d2: 0.000529]  [num0: 16.000000] [num1 48.000000]
[Epoch 256/500] [Batch 520/676] [D loss: 0.025895] [G loss: -0.135113] [d1 loss: 0.091923] [d2 loss: 0.101601]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 540/676] [D loss: -0.002251] [G loss: -0.060324] [d1 loss: 0.124677] [d2 loss: 0.130204]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 256/500] [Batch 560/676] [D loss: -0.002360] [G loss: -0.018029] [d1 loss: 0.058054] [d2 loss: 0.061233]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 256/500] [Batch 580/676] [D loss: -0.006412] [G loss: -0.005010] [d1 loss: 0.038826] [d2 loss: 0.044856]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]

[Epoch 256/500] [Batch 600/676] [D loss: -0.015967] [G loss: -0.014741] [d1 loss: 0.093051] [d2 loss: 0.085210]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 256/500] [Batch 620/676] [D loss: -0.017689] [G loss: 0.002527] [d1 loss: 0.100169] [d2 loss: 0.094756]  [sq d1 d2: 0.000029]  [num0: 19.000000] [num1 45.000000]
[Epoch 256/500] [Batch 640/676] [D loss: -0.030104] [G loss: 0.002307] [d1 loss: 0.113443] [d2 loss: 0.087740]  [sq d1 d2: 0.000661]  [num0: 20.000000] [num1 44.000000]
[Epoch 256/500] [Batch 660/676] [D loss: -0.021480] [G loss: 0.003634] [d1 loss: 0.065233] [d2 loss: 0.055607]  [sq d1 d2: 0.000093]  [num0: 14.000000] [num1 50.000000]
[Epoch 257/500] [Batch 0/676] [D loss: -0.040868] [G loss: -0.006063] [d1 loss: 0.079769] [d2 loss: 0.103977]  [sq d1 d2: 0.000586]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 20/676] [D loss: 0.006816] [G loss: -0.018244] [d1 loss: 0.055881] [d2 loss: 0.063542]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 40/676] [D loss: 0.003192] [G loss: -0.008400] [d1 loss: 0.069958] [d2 loss: 0.060979]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 60/676] [D loss: 0.011289] [G loss: 0.055852] [d1 loss: 0.127141] [d2 loss: 0.120771]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 80/676] [D loss: 0.046012] [G loss: 0.007099] [d1 loss: 0.095568] [d2 loss: 0.097411]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 100/676] [D loss: 0.011235] [G loss: -0.019589] [d1 loss: 0.041344] [d2 loss: 0.042563]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 257/500] [Batch 120/676] [D loss: 0.001474] [G loss: -0.031559] [d1 loss: 0.159370] [d2 loss: 0.132041]  [sq d1 d2: 0.000747]  [num0: 20.000000] [num1 44.000000]
[Epoch 257/500] [Batch 140/676] [D loss: -0.002555] [G loss: -0.039725] [d1 loss: 0.065436] [d2 loss: 0.061291]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 160/676] [D loss: -0.017158] [G loss: -0.067807] [d1 loss: 0.074037] [d2 loss: 0.081944]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 180/676] [D loss: -0.022569] [G loss: -0.091305] [d1 loss: 0.102203] [d2 loss: 0.073596]  [sq d1 d2: 0.000818]  [num0: 14.000000] [num1 50.000000]
[Epoch 257/500] [Batch 200/676] [D loss: -0.046664] [G loss: -0.117947] [d1 loss: 0.110806] [d2 loss: 0.126113]  [sq d1 d2: 0.000234]  [num0: 17.000000] [num1 47.000000]
[Epoch 257/500] [Batch 220/676] [D loss: -0.046846] [G loss: -0.149125] [d1 loss: 0.051055] [d2 loss: 0.066242]  [sq d1 d2: 0.000231]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 240/676] [D loss: -0.028291] [G loss: -0.194551] [d1 loss: 0.037745] [d2 loss: 0.045118]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 260/676] [D loss: -0.052361] [G loss: -0.205182] [d1 loss: 0.031151] [d2 loss: 0.038205]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 257/500] [Batch 280/676] [D loss: -0.046863] [G loss: -0.182013] [d1 loss: 0.087218] [d2 loss: 0.091959]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 257/500] [Batch 300/676] [D loss: -0.025235] [G loss: -0.164649] [d1 loss: 0.033930] [d2 loss: 0.037570]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 257/500] [Batch 320/676] [D loss: -0.007167] [G loss: -0.080203] [d1 loss: 0.038067] [d2 loss: 0.044914]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 257/500] [Batch 340/676] [D loss: 0.012331] [G loss: -0.052085] [d1 loss: 0.126010] [d2 loss: 0.127625]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 257/500] [Batch 360/676] [D loss: 0.004858] [G loss: 0.025568] [d1 loss: 0.069755] [d2 loss: 0.085691]  [sq d1 d2: 0.000254]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 380/676] [D loss: -0.000475] [G loss: 0.069382] [d1 loss: 0.048955] [d2 loss: 0.046643]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 400/676] [D loss: -0.017262] [G loss: 0.116629] [d1 loss: 0.127550] [d2 loss: 0.116568]  [sq d1 d2: 0.000121]  [num0: 11.000000] [num1 53.000000]
[Epoch 257/500] [Batch 420/676] [D loss: -0.036832] [G loss: 0.175685] [d1 loss: 0.056038] [d2 loss: 0.055437]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 257/500] [Batch 440/676] [D loss: -0.019193] [G loss: 0.228682] [d1 loss: 0.042474] [d2 loss: 0.044051]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 257/500] [Batch 460/676] [D loss: -0.069996] [G loss: 0.275812] [d1 loss: 0.109243] [d2 loss: 0.085224]  [sq d1 d2: 0.000577]  [num0: 14.000000] [num1 50.000000]
[Epoch 257/500] [Batch 480/676] [D loss: -0.053148] [G loss: 0.285484] [d1 loss: 0.083926] [d2 loss: 0.084066]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 257/500] [Batch 500/676] [D loss: -0.018166] [G loss: 0.216839] [d1 loss: 0.061137] [d2 loss: 0.056853]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 257/500] [Batch 520/676] [D loss: -0.016894] [G loss: 0.159875] [d1 loss: 0.115642] [d2 loss: 0.115226]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 257/500] [Batch 540/676] [D loss: 0.022303] [G loss: 0.090738] [d1 loss: 0.031525] [d2 loss: 0.024968]  [sq d1 d2: 0.000043]  [num0: 18.000000] [num1 46.000000]
[Epoch 257/500] [Batch 560/676] [D loss: 0.030196] [G loss: 0.031409] [d1 loss: 0.085285] [d2 loss: 0.092027]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 580/676] [D loss: 0.008870] [G loss: -0.013383] [d1 loss: 0.144065] [d2 loss: 0.164805]  [sq d1 d2: 0.000430]  [num0: 14.000000] [num1 50.000000]
[Epoch 257/500] [Batch 600/676] [D loss: -0.000603] [G loss: -0.022403] [d1 loss: 0.122382] [d2 loss: 0.139244]  [sq d1 d2: 0.000284]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 620/676] [D loss: -0.015317] [G loss: -0.019021] [d1 loss: 0.180050] [d2 loss: 0.155885]  [sq d1 d2: 0.000584]  [num0: 16.000000] [num1 48.000000]
[Epoch 257/500] [Batch 640/676] [D loss: -0.036838] [G loss: -0.033167] [d1 loss: 0.074365] [d2 loss: 0.070357]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 257/500] [Batch 660/676] [D loss: -0.030182] [G loss: -0.099451] [d1 loss: 0.099111] [d2 loss: 0.100886]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 258/500] [Batch 0/676] [D loss: -0.054370] [G loss: -0.157969] [d1 loss: 0.083683] [d2 loss: 0.093496]  [sq d1 d2: 0.000096]  [num0: 17.000000] [num1 47.000000]
[Epoch 258/500] [Batch 20/676] [D loss: -0.068803] [G loss: -0.186635] [d1 loss: 0.024323] [d2 loss: 0.027754]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 40/676] [D loss: -0.049972] [G loss: -0.217258] [d1 loss: 0.111330] [d2 loss: 0.116654]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 258/500] [Batch 60/676] [D loss: 0.049152] [G loss: -0.227841] [d1 loss: 0.071939] [d2 loss: 0.065082]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 80/676] [D loss: 0.000284] [G loss: -0.250779] [d1 loss: 0.074795] [d2 loss: 0.066696]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 100/676] [D loss: 0.035721] [G loss: -0.240306] [d1 loss: 0.051059] [d2 loss: 0.057064]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 258/500] [Batch 120/676] [D loss: 0.011239] [G loss: -0.168646] [d1 loss: 0.069753] [d2 loss: 0.091301]  [sq d1 d2: 0.000464]  [num0: 16.000000] [num1 48.000000]
[Epoch 258/500] [Batch 140/676] [D loss: -0.000206] [G loss: -0.127069] [d1 loss: 0.085688] [d2 loss: 0.077749]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 258/500] [Batch 160/676] [D loss: 0.005833] [G loss: -0.089610] [d1 loss: 0.038145] [d2 loss: 0.029090]  [sq d1 d2: 0.000082]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 180/676] [D loss: -0.008782] [G loss: -0.078840] [d1 loss: 0.053809] [d2 loss: 0.055338]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 258/500] [Batch 200/676] [D loss: -0.003463] [G loss: -0.059442] [d1 loss: 0.085534] [d2 loss: 0.082274]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 258/500] [Batch 220/676] [D loss: -0.026991] [G loss: -0.066357] [d1 loss: 0.144358] [d2 loss: 0.136379]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 258/500] [Batch 240/676] [D loss: -0.050844] [G loss: -0.041915] [d1 loss: 0.023778] [d2 loss: 0.021932]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 260/676] [D loss: -0.015458] [G loss: 0.020051] [d1 loss: 0.125493] [d2 loss: 0.140291]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]

[Epoch 258/500] [Batch 280/676] [D loss: -0.030734] [G loss: 0.041446] [d1 loss: 0.049521] [d2 loss: 0.051056]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 300/676] [D loss: 0.000637] [G loss: 0.098137] [d1 loss: 0.024545] [d2 loss: 0.026463]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 258/500] [Batch 320/676] [D loss: 0.029258] [G loss: 0.113977] [d1 loss: 0.044145] [d2 loss: 0.041414]  [sq d1 d2: 0.000007]  [num0: 22.000000] [num1 42.000000]
[Epoch 258/500] [Batch 340/676] [D loss: -0.012609] [G loss: 0.082641] [d1 loss: 0.123592] [d2 loss: 0.103926]  [sq d1 d2: 0.000387]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 360/676] [D loss: 0.037013] [G loss: 0.064120] [d1 loss: 0.094373] [d2 loss: 0.094120]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 380/676] [D loss: 0.002027] [G loss: 0.077874] [d1 loss: 0.019698] [d2 loss: 0.022093]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 400/676] [D loss: 0.001455] [G loss: 0.040975] [d1 loss: 0.033539] [d2 loss: 0.029237]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 258/500] [Batch 420/676] [D loss: 0.014372] [G loss: 0.042057] [d1 loss: 0.089043] [d2 loss: 0.104507]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 440/676] [D loss: 0.001509] [G loss: 0.039050] [d1 loss: 0.028484] [d2 loss: 0.023006]  [sq d1 d2: 0.000030]  [num0: 18.000000] [num1 46.000000]
[Epoch 258/500] [Batch 460/676] [D loss: -0.011976] [G loss: 0.031273] [d1 loss: 0.092173] [d2 loss: 0.078598]  [sq d1 d2: 0.000184]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 480/676] [D loss: -0.033354] [G loss: 0.016180] [d1 loss: 0.031727] [d2 loss: 0.035121]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 258/500] [Batch 500/676] [D loss: -0.022501] [G loss: 0.057562] [d1 loss: 0.093716] [d2 loss: 0.104462]  [sq d1 d2: 0.000115]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 520/676] [D loss: -0.043068] [G loss: 0.092961] [d1 loss: 0.074826] [d2 loss: 0.057529]  [sq d1 d2: 0.000299]  [num0: 15.000000] [num1 49.000000]
[Epoch 258/500] [Batch 540/676] [D loss: -0.053931] [G loss: 0.131166] [d1 loss: 0.090517] [d2 loss: 0.109535]  [sq d1 d2: 0.000362]  [num0: 17.000000] [num1 47.000000]
[Epoch 258/500] [Batch 560/676] [D loss: -0.008224] [G loss: 0.109175] [d1 loss: 0.065377] [d2 loss: 0.059453]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 258/500] [Batch 580/676] [D loss: 0.013272] [G loss: 0.080289] [d1 loss: 0.062083] [d2 loss: 0.049934]  [sq d1 d2: 0.000148]  [num0: 18.000000] [num1 46.000000]
[Epoch 258/500] [Batch 600/676] [D loss: -0.009139] [G loss: 0.061865] [d1 loss: 0.099564] [d2 loss: 0.098655]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 258/500] [Batch 620/676] [D loss: 0.059439] [G loss: 0.078383] [d1 loss: 0.045440] [d2 loss: 0.036845]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 640/676] [D loss: 0.021630] [G loss: 0.082580] [d1 loss: 0.164548] [d2 loss: 0.187932]  [sq d1 d2: 0.000547]  [num0: 14.000000] [num1 50.000000]
[Epoch 258/500] [Batch 660/676] [D loss: 0.005666] [G loss: 0.055278] [d1 loss: 0.045978] [d2 loss: 0.069048]  [sq d1 d2: 0.000532]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 0/676] [D loss: 0.004765] [G loss: 0.040270] [d1 loss: 0.070777] [d2 loss: 0.064014]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 20/676] [D loss: -0.010150] [G loss: 0.003894] [d1 loss: 0.059829] [d2 loss: 0.049711]  [sq d1 d2: 0.000102]  [num0: 18.000000] [num1 46.000000]
[Epoch 259/500] [Batch 40/676] [D loss: -0.008150] [G loss: -0.021036] [d1 loss: 0.082558] [d2 loss: 0.083899]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 60/676] [D loss: -0.033895] [G loss: -0.037270] [d1 loss: 0.048261] [d2 loss: 0.051981]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 80/676] [D loss: -0.031221] [G loss: -0.010817] [d1 loss: 0.108211] [d2 loss: 0.105250]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 100/676] [D loss: -0.039435] [G loss: 0.025587] [d1 loss: 0.061834] [d2 loss: 0.082596]  [sq d1 d2: 0.000431]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 120/676] [D loss: -0.067948] [G loss: 0.041303] [d1 loss: 0.107334] [d2 loss: 0.066079]  [sq d1 d2: 0.001702]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 140/676] [D loss: -0.036536] [G loss: 0.011204] [d1 loss: 0.060691] [d2 loss: 0.060844]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 259/500] [Batch 160/676] [D loss: -0.006993] [G loss: 0.000685] [d1 loss: 0.120978] [d2 loss: 0.150958]  [sq d1 d2: 0.000899]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 180/676] [D loss: 0.003188] [G loss: -0.064943] [d1 loss: 0.111254] [d2 loss: 0.105310]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 259/500] [Batch 200/676] [D loss: 0.001792] [G loss: -0.108041] [d1 loss: 0.105705] [d2 loss: 0.125368]  [sq d1 d2: 0.000387]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 220/676] [D loss: 0.022221] [G loss: -0.118780] [d1 loss: 0.052131] [d2 loss: 0.062745]  [sq d1 d2: 0.000113]  [num0: 14.000000] [num1 50.000000]
[Epoch 259/500] [Batch 240/676] [D loss: 0.023688] [G loss: -0.086846] [d1 loss: 0.092739] [d2 loss: 0.112032]  [sq d1 d2: 0.000372]  [num0: 14.000000] [num1 50.000000]
[Epoch 259/500] [Batch 260/676] [D loss: 0.003341] [G loss: -0.075523] [d1 loss: 0.038436] [d2 loss: 0.039862]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 259/500] [Batch 280/676] [D loss: -0.017614] [G loss: -0.073209] [d1 loss: 0.093557] [d2 loss: 0.099260]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 259/500] [Batch 300/676] [D loss: -0.049022] [G loss: -0.046659] [d1 loss: 0.136949] [d2 loss: 0.133122]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 320/676] [D loss: -0.054376] [G loss: -0.029289] [d1 loss: 0.063716] [d2 loss: 0.069658]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 259/500] [Batch 340/676] [D loss: -0.096612] [G loss: -0.009249] [d1 loss: 0.123821] [d2 loss: 0.141240]  [sq d1 d2: 0.000303]  [num0: 13.000000] [num1 51.000000]
[Epoch 259/500] [Batch 360/676] [D loss: -0.098727] [G loss: 0.012548] [d1 loss: 0.095169] [d2 loss: 0.121388]  [sq d1 d2: 0.000687]  [num0: 12.000000] [num1 52.000000]
[Epoch 259/500] [Batch 380/676] [D loss: -0.069444] [G loss: 0.009333] [d1 loss: 0.068625] [d2 loss: 0.075780]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 400/676] [D loss: -0.016760] [G loss: -0.043744] [d1 loss: 0.071564] [d2 loss: 0.099407]  [sq d1 d2: 0.000775]  [num0: 13.000000] [num1 51.000000]
[Epoch 259/500] [Batch 420/676] [D loss: 0.032007] [G loss: 0.002087] [d1 loss: 0.077610] [d2 loss: 0.061947]  [sq d1 d2: 0.000245]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 440/676] [D loss: 0.026726] [G loss: 0.003852] [d1 loss: 0.094319] [d2 loss: 0.106973]  [sq d1 d2: 0.000160]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 460/676] [D loss: -0.001706] [G loss: 0.026075] [d1 loss: 0.098630] [d2 loss: 0.101493]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 480/676] [D loss: 0.014540] [G loss: 0.059557] [d1 loss: 0.060507] [d2 loss: 0.058125]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 500/676] [D loss: 0.003444] [G loss: 0.041565] [d1 loss: 0.143267] [d2 loss: 0.083412]  [sq d1 d2: 0.003583]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 520/676] [D loss: -0.004820] [G loss: 0.022108] [d1 loss: 0.172341] [d2 loss: 0.148008]  [sq d1 d2: 0.000592]  [num0: 16.000000] [num1 48.000000]
[Epoch 259/500] [Batch 540/676] [D loss: -0.026429] [G loss: 0.046698] [d1 loss: 0.071555] [d2 loss: 0.042855]  [sq d1 d2: 0.000824]  [num0: 14.000000] [num1 50.000000]
[Epoch 259/500] [Batch 560/676] [D loss: -0.034437] [G loss: 0.066422] [d1 loss: 0.107845] [d2 loss: 0.097503]  [sq d1 d2: 0.000107]  [num0: 18.000000] [num1 46.000000]
[Epoch 259/500] [Batch 580/676] [D loss: -0.039828] [G loss: 0.098109] [d1 loss: 0.089692] [d2 loss: 0.096146]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 259/500] [Batch 600/676] [D loss: -0.057110] [G loss: 0.120031] [d1 loss: 0.070103] [d2 loss: 0.059494]  [sq d1 d2: 0.000113]  [num0: 19.000000] [num1 45.000000]

[Epoch 259/500] [Batch 620/676] [D loss: -0.016627] [G loss: 0.094314] [d1 loss: 0.084058] [d2 loss: 0.073022]  [sq d1 d2: 0.000122]  [num0: 18.000000] [num1 46.000000]
[Epoch 259/500] [Batch 640/676] [D loss: -0.019477] [G loss: 0.144344] [d1 loss: 0.121563] [d2 loss: 0.132628]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 259/500] [Batch 660/676] [D loss: 0.010329] [G loss: 0.076533] [d1 loss: 0.116753] [d2 loss: 0.093114]  [sq d1 d2: 0.000559]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 0/676] [D loss: 0.041107] [G loss: -0.033794] [d1 loss: 0.082147] [d2 loss: 0.067686]  [sq d1 d2: 0.000209]  [num0: 18.000000] [num1 46.000000]
[Epoch 260/500] [Batch 20/676] [D loss: 0.050332] [G loss: -0.114337] [d1 loss: 0.044357] [d2 loss: 0.036400]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 260/500] [Batch 40/676] [D loss: 0.035022] [G loss: -0.118032] [d1 loss: 0.053531] [d2 loss: 0.058477]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 60/676] [D loss: 0.015267] [G loss: -0.103011] [d1 loss: 0.108939] [d2 loss: 0.099900]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 80/676] [D loss: 0.010635] [G loss: -0.095069] [d1 loss: 0.075031] [d2 loss: 0.089814]  [sq d1 d2: 0.000219]  [num0: 16.000000] [num1 48.000000]
[Epoch 260/500] [Batch 100/676] [D loss: -0.005782] [G loss: -0.098977] [d1 loss: 0.079324] [d2 loss: 0.071588]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 120/676] [D loss: -0.015559] [G loss: -0.120504] [d1 loss: 0.097383] [d2 loss: 0.086916]  [sq d1 d2: 0.000110]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 140/676] [D loss: -0.057753] [G loss: -0.133609] [d1 loss: 0.068812] [d2 loss: 0.069321]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 260/500] [Batch 160/676] [D loss: -0.078454] [G loss: -0.132512] [d1 loss: 0.026835] [d2 loss: 0.033492]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 180/676] [D loss: -0.057196] [G loss: -0.145697] [d1 loss: 0.114759] [d2 loss: 0.067722]  [sq d1 d2: 0.002212]  [num0: 13.000000] [num1 51.000000]
[Epoch 260/500] [Batch 200/676] [D loss: -0.066630] [G loss: -0.137549] [d1 loss: 0.031367] [d2 loss: 0.040563]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 260/500] [Batch 220/676] [D loss: -0.034675] [G loss: -0.209025] [d1 loss: 0.067407] [d2 loss: 0.065103]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 240/676] [D loss: -0.007686] [G loss: -0.202787] [d1 loss: 0.052647] [d2 loss: 0.041518]  [sq d1 d2: 0.000124]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 260/676] [D loss: 0.000866] [G loss: -0.226620] [d1 loss: 0.069208] [d2 loss: 0.058130]  [sq d1 d2: 0.000123]  [num0: 12.000000] [num1 52.000000]
[Epoch 260/500] [Batch 280/676] [D loss: -0.006698] [G loss: -0.132105] [d1 loss: 0.085183] [d2 loss: 0.088766]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 260/500] [Batch 300/676] [D loss: 0.037357] [G loss: -0.059704] [d1 loss: 0.078578] [d2 loss: 0.083958]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 320/676] [D loss: 0.014813] [G loss: -0.006344] [d1 loss: 0.049394] [d2 loss: 0.050174]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 340/676] [D loss: 0.002305] [G loss: 0.012843] [d1 loss: 0.027355] [d2 loss: 0.021252]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 360/676] [D loss: -0.000609] [G loss: 0.049267] [d1 loss: 0.120604] [d2 loss: 0.097620]  [sq d1 d2: 0.000528]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 380/676] [D loss: -0.012547] [G loss: 0.045071] [d1 loss: 0.046129] [d2 loss: 0.046495]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 260/500] [Batch 400/676] [D loss: -0.012769] [G loss: 0.070779] [d1 loss: 0.085808] [d2 loss: 0.067483]  [sq d1 d2: 0.000336]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 420/676] [D loss: -0.003935] [G loss: 0.105518] [d1 loss: 0.057149] [d2 loss: 0.068119]  [sq d1 d2: 0.000120]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 440/676] [D loss: -0.057395] [G loss: 0.143914] [d1 loss: 0.075821] [d2 loss: 0.079095]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 460/676] [D loss: -0.043679] [G loss: 0.160021] [d1 loss: 0.050023] [d2 loss: 0.059761]  [sq d1 d2: 0.000095]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 480/676] [D loss: -0.057687] [G loss: 0.180361] [d1 loss: 0.053098] [d2 loss: 0.048539]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 500/676] [D loss: -0.067280] [G loss: 0.216744] [d1 loss: 0.060901] [d2 loss: 0.066325]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 260/500] [Batch 520/676] [D loss: -0.049918] [G loss: 0.224911] [d1 loss: 0.059198] [d2 loss: 0.047047]  [sq d1 d2: 0.000148]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 540/676] [D loss: 0.038482] [G loss: 0.200969] [d1 loss: 0.039654] [d2 loss: 0.043752]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 260/500] [Batch 560/676] [D loss: 0.046120] [G loss: 0.112045] [d1 loss: 0.078522] [d2 loss: 0.067855]  [sq d1 d2: 0.000114]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 580/676] [D loss: 0.029006] [G loss: 0.100366] [d1 loss: 0.087734] [d2 loss: 0.084316]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 600/676] [D loss: 0.009424] [G loss: 0.079836] [d1 loss: 0.085495] [d2 loss: 0.064703]  [sq d1 d2: 0.000432]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 620/676] [D loss: 0.011526] [G loss: 0.043913] [d1 loss: 0.078524] [d2 loss: 0.071236]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 260/500] [Batch 640/676] [D loss: 0.001579] [G loss: 0.009017] [d1 loss: 0.082700] [d2 loss: 0.085750]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 260/500] [Batch 660/676] [D loss: -0.005565] [G loss: -0.015282] [d1 loss: 0.082285] [d2 loss: 0.069223]  [sq d1 d2: 0.000171]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 0/676] [D loss: -0.022279] [G loss: -0.035608] [d1 loss: 0.066656] [d2 loss: 0.074480]  [sq d1 d2: 0.000061]  [num0: 12.000000] [num1 52.000000]
[Epoch 261/500] [Batch 20/676] [D loss: -0.014164] [G loss: -0.076593] [d1 loss: 0.026110] [d2 loss: 0.025399]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 261/500] [Batch 40/676] [D loss: -0.059631] [G loss: -0.106584] [d1 loss: 0.096678] [d2 loss: 0.095340]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 261/500] [Batch 60/676] [D loss: -0.044037] [G loss: -0.149208] [d1 loss: 0.106338] [d2 loss: 0.086545]  [sq d1 d2: 0.000392]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 80/676] [D loss: -0.016298] [G loss: -0.224491] [d1 loss: 0.084675] [d2 loss: 0.097281]  [sq d1 d2: 0.000159]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 100/676] [D loss: -0.040372] [G loss: -0.290240] [d1 loss: 0.080224] [d2 loss: 0.066091]  [sq d1 d2: 0.000200]  [num0: 14.000000] [num1 50.000000]
[Epoch 261/500] [Batch 120/676] [D loss: 0.003806] [G loss: -0.291547] [d1 loss: 0.033871] [d2 loss: 0.035953]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 261/500] [Batch 140/676] [D loss: 0.051468] [G loss: -0.269679] [d1 loss: 0.064145] [d2 loss: 0.059579]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 160/676] [D loss: 0.029981] [G loss: -0.152132] [d1 loss: 0.065373] [d2 loss: 0.077019]  [sq d1 d2: 0.000136]  [num0: 13.000000] [num1 51.000000]
[Epoch 261/500] [Batch 180/676] [D loss: 0.029364] [G loss: -0.063488] [d1 loss: 0.101375] [d2 loss: 0.130980]  [sq d1 d2: 0.000876]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 200/676] [D loss: 0.008096] [G loss: -0.001775] [d1 loss: 0.031067] [d2 loss: 0.032934]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 220/676] [D loss: 0.007216] [G loss: 0.030344] [d1 loss: 0.081479] [d2 loss: 0.099177]  [sq d1 d2: 0.000313]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 240/676] [D loss: -0.009032] [G loss: 0.068598] [d1 loss: 0.101142] [d2 loss: 0.103522]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 261/500] [Batch 260/676] [D loss: -0.013127] [G loss: 0.137394] [d1 loss: 0.034269] [d2 loss: 0.042893]  [sq d1 d2: 0.000074]  [num0: 17.000000] [num1 47.000000]
[Epoch 261/500] [Batch 280/676] [D loss: -0.020201] [G loss: 0.208790] [d1 loss: 0.070026] [d2 loss: 0.086870]  [sq d1 d2: 0.000284]  [num0: 16.000000] [num1 48.000000]

[Epoch 261/500] [Batch 300/676] [D loss: -0.037397] [G loss: 0.290212] [d1 loss: 0.106376] [d2 loss: 0.102486]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 261/500] [Batch 320/676] [D loss: -0.063041] [G loss: 0.397889] [d1 loss: 0.121970] [d2 loss: 0.165829]  [sq d1 d2: 0.001924]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 340/676] [D loss: -0.062045] [G loss: 0.478488] [d1 loss: 0.058302] [d2 loss: 0.069937]  [sq d1 d2: 0.000135]  [num0: 20.000000] [num1 44.000000]
[Epoch 261/500] [Batch 360/676] [D loss: -0.030014] [G loss: 0.494859] [d1 loss: 0.119872] [d2 loss: 0.130085]  [sq d1 d2: 0.000104]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 380/676] [D loss: 0.016972] [G loss: 0.529646] [d1 loss: 0.107504] [d2 loss: 0.083856]  [sq d1 d2: 0.000559]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 400/676] [D loss: 0.026243] [G loss: 0.456840] [d1 loss: 0.051313] [d2 loss: 0.037939]  [sq d1 d2: 0.000179]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 420/676] [D loss: 0.015569] [G loss: 0.337628] [d1 loss: 0.088897] [d2 loss: 0.066063]  [sq d1 d2: 0.000521]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 440/676] [D loss: 0.030452] [G loss: 0.224968] [d1 loss: 0.034991] [d2 loss: 0.037218]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 460/676] [D loss: 0.028451] [G loss: 0.124987] [d1 loss: 0.076509] [d2 loss: 0.081107]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 261/500] [Batch 480/676] [D loss: -0.008166] [G loss: 0.063464] [d1 loss: 0.031643] [d2 loss: 0.029470]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 261/500] [Batch 500/676] [D loss: -0.000417] [G loss: 0.033294] [d1 loss: 0.055392] [d2 loss: 0.057206]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 261/500] [Batch 520/676] [D loss: -0.003017] [G loss: -0.036521] [d1 loss: 0.038927] [d2 loss: 0.044840]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]
[Epoch 261/500] [Batch 540/676] [D loss: -0.012089] [G loss: -0.088753] [d1 loss: 0.068909] [d2 loss: 0.058972]  [sq d1 d2: 0.000099]  [num0: 18.000000] [num1 46.000000]
[Epoch 261/500] [Batch 560/676] [D loss: -0.031215] [G loss: -0.152753] [d1 loss: 0.075658] [d2 loss: 0.090221]  [sq d1 d2: 0.000212]  [num0: 15.000000] [num1 49.000000]
[Epoch 261/500] [Batch 580/676] [D loss: -0.045354] [G loss: -0.240297] [d1 loss: 0.045231] [d2 loss: 0.039318]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 261/500] [Batch 600/676] [D loss: -0.049296] [G loss: -0.344670] [d1 loss: 0.023185] [d2 loss: 0.020104]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 261/500] [Batch 620/676] [D loss: -0.092800] [G loss: -0.412999] [d1 loss: 0.055272] [d2 loss: 0.065523]  [sq d1 d2: 0.000105]  [num0: 19.000000] [num1 45.000000]
[Epoch 261/500] [Batch 640/676] [D loss: -0.046178] [G loss: -0.466075] [d1 loss: 0.142318] [d2 loss: 0.108812]  [sq d1 d2: 0.001123]  [num0: 17.000000] [num1 47.000000]
[Epoch 261/500] [Batch 660/676] [D loss: 0.019251] [G loss: -0.535636] [d1 loss: 0.028484] [d2 loss: 0.030559]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 0/676] [D loss: 0.020415] [G loss: -0.526552] [d1 loss: 0.051565] [d2 loss: 0.058455]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 20/676] [D loss: -0.002097] [G loss: -0.426632] [d1 loss: 0.082668] [d2 loss: 0.097461]  [sq d1 d2: 0.000219]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 40/676] [D loss: 0.022842] [G loss: -0.351708] [d1 loss: 0.053945] [d2 loss: 0.049370]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 262/500] [Batch 60/676] [D loss: 0.012234] [G loss: -0.237381] [d1 loss: 0.075409] [d2 loss: 0.068951]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 80/676] [D loss: 0.007908] [G loss: -0.167107] [d1 loss: 0.044826] [d2 loss: 0.042117]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 262/500] [Batch 100/676] [D loss: -0.001345] [G loss: -0.091365] [d1 loss: 0.083138] [d2 loss: 0.096427]  [sq d1 d2: 0.000177]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 120/676] [D loss: -0.004987] [G loss: -0.047008] [d1 loss: 0.114570] [d2 loss: 0.116271]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 262/500] [Batch 140/676] [D loss: -0.025342] [G loss: -0.001990] [d1 loss: 0.031758] [d2 loss: 0.026742]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 160/676] [D loss: -0.054668] [G loss: 0.025208] [d1 loss: 0.059034] [d2 loss: 0.066239]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 180/676] [D loss: -0.070816] [G loss: 0.079870] [d1 loss: 0.060210] [d2 loss: 0.067901]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 200/676] [D loss: -0.052950] [G loss: 0.170408] [d1 loss: 0.126360] [d2 loss: 0.108044]  [sq d1 d2: 0.000335]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 220/676] [D loss: -0.062239] [G loss: 0.187750] [d1 loss: 0.101651] [d2 loss: 0.085549]  [sq d1 d2: 0.000259]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 240/676] [D loss: -0.023999] [G loss: 0.208115] [d1 loss: 0.050945] [d2 loss: 0.051413]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 260/676] [D loss: -0.076715] [G loss: 0.142412] [d1 loss: 0.101925] [d2 loss: 0.088272]  [sq d1 d2: 0.000186]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 280/676] [D loss: 0.029365] [G loss: 0.125110] [d1 loss: 0.053058] [d2 loss: 0.052682]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 262/500] [Batch 300/676] [D loss: 0.029177] [G loss: 0.096845] [d1 loss: 0.053332] [d2 loss: 0.052772]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 320/676] [D loss: 0.023439] [G loss: 0.080434] [d1 loss: 0.089705] [d2 loss: 0.089536]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 262/500] [Batch 340/676] [D loss: 0.012380] [G loss: 0.027245] [d1 loss: 0.096230] [d2 loss: 0.090728]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 360/676] [D loss: 0.003181] [G loss: -0.013247] [d1 loss: 0.096695] [d2 loss: 0.086470]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 380/676] [D loss: -0.006357] [G loss: -0.036836] [d1 loss: 0.160278] [d2 loss: 0.170007]  [sq d1 d2: 0.000095]  [num0: 18.000000] [num1 46.000000]
[Epoch 262/500] [Batch 400/676] [D loss: -0.017334] [G loss: -0.010271] [d1 loss: 0.070511] [d2 loss: 0.069951]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 420/676] [D loss: -0.039237] [G loss: -0.030714] [d1 loss: 0.074090] [d2 loss: 0.063061]  [sq d1 d2: 0.000122]  [num0: 14.000000] [num1 50.000000]
[Epoch 262/500] [Batch 440/676] [D loss: -0.057605] [G loss: -0.107213] [d1 loss: 0.065684] [d2 loss: 0.055321]  [sq d1 d2: 0.000107]  [num0: 12.000000] [num1 52.000000]
[Epoch 262/500] [Batch 460/676] [D loss: -0.076742] [G loss: -0.196659] [d1 loss: 0.071882] [d2 loss: 0.067521]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 262/500] [Batch 480/676] [D loss: -0.009716] [G loss: -0.295724] [d1 loss: 0.056313] [d2 loss: 0.053240]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 262/500] [Batch 500/676] [D loss: -0.015038] [G loss: -0.337664] [d1 loss: 0.034085] [d2 loss: 0.033130]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 262/500] [Batch 520/676] [D loss: -0.028798] [G loss: -0.361223] [d1 loss: 0.071460] [d2 loss: 0.076266]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 540/676] [D loss: -0.003724] [G loss: -0.376713] [d1 loss: 0.105155] [d2 loss: 0.080095]  [sq d1 d2: 0.000628]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 560/676] [D loss: 0.023286] [G loss: -0.303462] [d1 loss: 0.081330] [d2 loss: 0.095485]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 580/676] [D loss: 0.029555] [G loss: -0.218021] [d1 loss: 0.105961] [d2 loss: 0.102405]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 262/500] [Batch 600/676] [D loss: 0.018616] [G loss: -0.159497] [d1 loss: 0.079353] [d2 loss: 0.105619]  [sq d1 d2: 0.000690]  [num0: 19.000000] [num1 45.000000]
[Epoch 262/500] [Batch 620/676] [D loss: -0.000284] [G loss: -0.096496] [d1 loss: 0.054419] [d2 loss: 0.060202]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 262/500] [Batch 640/676] [D loss: -0.002646] [G loss: -0.044875] [d1 loss: 0.038527] [d2 loss: 0.040570]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]

[Epoch 262/500] [Batch 660/676] [D loss: -0.011754] [G loss: 0.005444] [d1 loss: 0.060985] [d2 loss: 0.059238]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 263/500] [Batch 0/676] [D loss: -0.006841] [G loss: 0.021319] [d1 loss: 0.035594] [d2 loss: 0.037818]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 20/676] [D loss: -0.025983] [G loss: 0.053894] [d1 loss: 0.137859] [d2 loss: 0.114068]  [sq d1 d2: 0.000566]  [num0: 19.000000] [num1 45.000000]
[Epoch 263/500] [Batch 40/676] [D loss: -0.037309] [G loss: 0.112705] [d1 loss: 0.071838] [d2 loss: 0.061823]  [sq d1 d2: 0.000100]  [num0: 14.000000] [num1 50.000000]
[Epoch 263/500] [Batch 60/676] [D loss: -0.028402] [G loss: 0.253563] [d1 loss: 0.076546] [d2 loss: 0.049953]  [sq d1 d2: 0.000707]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 80/676] [D loss: -0.085454] [G loss: 0.297803] [d1 loss: 0.133137] [d2 loss: 0.124070]  [sq d1 d2: 0.000082]  [num0: 19.000000] [num1 45.000000]
[Epoch 263/500] [Batch 100/676] [D loss: -0.007889] [G loss: 0.309930] [d1 loss: 0.060071] [d2 loss: 0.071768]  [sq d1 d2: 0.000137]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 120/676] [D loss: -0.037164] [G loss: 0.329357] [d1 loss: 0.140579] [d2 loss: 0.120907]  [sq d1 d2: 0.000387]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 140/676] [D loss: -0.030357] [G loss: 0.258755] [d1 loss: 0.024174] [d2 loss: 0.026314]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 160/676] [D loss: -0.010354] [G loss: 0.242282] [d1 loss: 0.050871] [d2 loss: 0.054457]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 263/500] [Batch 180/676] [D loss: -0.011628] [G loss: 0.184714] [d1 loss: 0.104430] [d2 loss: 0.088556]  [sq d1 d2: 0.000252]  [num0: 18.000000] [num1 46.000000]
[Epoch 263/500] [Batch 200/676] [D loss: 0.014427] [G loss: 0.162400] [d1 loss: 0.026237] [d2 loss: 0.045599]  [sq d1 d2: 0.000375]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 220/676] [D loss: 0.007085] [G loss: 0.126342] [d1 loss: 0.092961] [d2 loss: 0.077478]  [sq d1 d2: 0.000240]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 240/676] [D loss: 0.007627] [G loss: 0.043276] [d1 loss: 0.048144] [d2 loss: 0.053857]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 263/500] [Batch 260/676] [D loss: -0.002817] [G loss: -0.014618] [d1 loss: 0.051675] [d2 loss: 0.067773]  [sq d1 d2: 0.000259]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 280/676] [D loss: -0.014126] [G loss: -0.046417] [d1 loss: 0.083572] [d2 loss: 0.085780]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 263/500] [Batch 300/676] [D loss: -0.045842] [G loss: -0.075098] [d1 loss: 0.075279] [d2 loss: 0.073252]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 263/500] [Batch 320/676] [D loss: -0.034828] [G loss: -0.109472] [d1 loss: 0.019146] [d2 loss: 0.015868]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 263/500] [Batch 340/676] [D loss: -0.062707] [G loss: -0.189088] [d1 loss: 0.106140] [d2 loss: 0.083858]  [sq d1 d2: 0.000497]  [num0: 16.000000] [num1 48.000000]
[Epoch 263/500] [Batch 360/676] [D loss: -0.077236] [G loss: -0.246234] [d1 loss: 0.078931] [d2 loss: 0.093654]  [sq d1 d2: 0.000217]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 380/676] [D loss: -0.039037] [G loss: -0.285763] [d1 loss: 0.053027] [d2 loss: 0.045335]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 400/676] [D loss: 0.013800] [G loss: -0.359667] [d1 loss: 0.029899] [d2 loss: 0.029631]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 420/676] [D loss: 0.015644] [G loss: -0.376874] [d1 loss: 0.085906] [d2 loss: 0.081332]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 440/676] [D loss: 0.022322] [G loss: -0.301931] [d1 loss: 0.071237] [d2 loss: 0.080666]  [sq d1 d2: 0.000089]  [num0: 18.000000] [num1 46.000000]
[Epoch 263/500] [Batch 460/676] [D loss: 0.031620] [G loss: -0.256208] [d1 loss: 0.104259] [d2 loss: 0.093439]  [sq d1 d2: 0.000117]  [num0: 16.000000] [num1 48.000000]
[Epoch 263/500] [Batch 480/676] [D loss: 0.020142] [G loss: -0.136630] [d1 loss: 0.022962] [d2 loss: 0.024775]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 500/676] [D loss: 0.020231] [G loss: -0.053882] [d1 loss: 0.051994] [d2 loss: 0.052026]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 520/676] [D loss: 0.001590] [G loss: -0.000181] [d1 loss: 0.051959] [d2 loss: 0.040494]  [sq d1 d2: 0.000131]  [num0: 13.000000] [num1 51.000000]
[Epoch 263/500] [Batch 540/676] [D loss: -0.002498] [G loss: 0.059166] [d1 loss: 0.063317] [d2 loss: 0.072810]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 263/500] [Batch 560/676] [D loss: -0.007046] [G loss: 0.103802] [d1 loss: 0.147694] [d2 loss: 0.131650]  [sq d1 d2: 0.000257]  [num0: 12.000000] [num1 52.000000]
[Epoch 263/500] [Batch 580/676] [D loss: -0.028909] [G loss: 0.182901] [d1 loss: 0.018177] [d2 loss: 0.012812]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 263/500] [Batch 600/676] [D loss: -0.058624] [G loss: 0.277422] [d1 loss: 0.055744] [d2 loss: 0.085675]  [sq d1 d2: 0.000896]  [num0: 16.000000] [num1 48.000000]
[Epoch 263/500] [Batch 620/676] [D loss: -0.019131] [G loss: 0.368271] [d1 loss: 0.083761] [d2 loss: 0.096160]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 263/500] [Batch 640/676] [D loss: -0.059501] [G loss: 0.417427] [d1 loss: 0.091273] [d2 loss: 0.105257]  [sq d1 d2: 0.000196]  [num0: 11.000000] [num1 53.000000]
[Epoch 263/500] [Batch 660/676] [D loss: -0.030264] [G loss: 0.462872] [d1 loss: 0.122137] [d2 loss: 0.079347]  [sq d1 d2: 0.001831]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 0/676] [D loss: 0.013379] [G loss: 0.425364] [d1 loss: 0.111654] [d2 loss: 0.120455]  [sq d1 d2: 0.000077]  [num0: 20.000000] [num1 44.000000]
[Epoch 264/500] [Batch 20/676] [D loss: 0.029225] [G loss: 0.410890] [d1 loss: 0.069851] [d2 loss: 0.070845]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 40/676] [D loss: -0.053925] [G loss: 0.322736] [d1 loss: 0.020593] [d2 loss: 0.019068]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 264/500] [Batch 60/676] [D loss: 0.050860] [G loss: 0.244118] [d1 loss: 0.101526] [d2 loss: 0.099926]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 264/500] [Batch 80/676] [D loss: 0.016788] [G loss: 0.149700] [d1 loss: 0.114607] [d2 loss: 0.093359]  [sq d1 d2: 0.000451]  [num0: 18.000000] [num1 46.000000]
[Epoch 264/500] [Batch 100/676] [D loss: 0.009768] [G loss: 0.071463] [d1 loss: 0.058833] [d2 loss: 0.063376]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 120/676] [D loss: -0.003259] [G loss: 0.005612] [d1 loss: 0.148980] [d2 loss: 0.146429]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 264/500] [Batch 140/676] [D loss: -0.025826] [G loss: -0.045112] [d1 loss: 0.220355] [d2 loss: 0.203932]  [sq d1 d2: 0.000270]  [num0: 17.000000] [num1 47.000000]
[Epoch 264/500] [Batch 160/676] [D loss: -0.038900] [G loss: -0.113873] [d1 loss: 0.029163] [d2 loss: 0.030461]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 180/676] [D loss: -0.057528] [G loss: -0.212761] [d1 loss: 0.055031] [d2 loss: 0.047616]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 200/676] [D loss: -0.071886] [G loss: -0.279574] [d1 loss: 0.053496] [d2 loss: 0.047613]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 264/500] [Batch 220/676] [D loss: -0.037943] [G loss: -0.337149] [d1 loss: 0.072822] [d2 loss: 0.084224]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 240/676] [D loss: -0.008397] [G loss: -0.438117] [d1 loss: 0.102060] [d2 loss: 0.090495]  [sq d1 d2: 0.000134]  [num0: 20.000000] [num1 44.000000]
[Epoch 264/500] [Batch 260/676] [D loss: -0.017936] [G loss: -0.396764] [d1 loss: 0.087698] [d2 loss: 0.072579]  [sq d1 d2: 0.000229]  [num0: 17.000000] [num1 47.000000]
[Epoch 264/500] [Batch 280/676] [D loss: -0.004957] [G loss: -0.355619] [d1 loss: 0.057948] [d2 loss: 0.062742]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 264/500] [Batch 300/676] [D loss: 0.015673] [G loss: -0.307923] [d1 loss: 0.084027] [d2 loss: 0.102054]  [sq d1 d2: 0.000325]  [num0: 13.000000] [num1 51.000000]
[Epoch 264/500] [Batch 320/676] [D loss: 0.029391] [G loss: -0.153890] [d1 loss: 0.168988] [d2 loss: 0.089208]  [sq d1 d2: 0.006365]  [num0: 16.000000] [num1 48.000000]

[Epoch 264/500] [Batch 340/676] [D loss: 0.017490] [G loss: -0.057214] [d1 loss: 0.039114] [d2 loss: 0.017062]  [sq d1 d2: 0.000486]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 360/676] [D loss: 0.009143] [G loss: -0.007523] [d1 loss: 0.071321] [d2 loss: 0.065969]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 264/500] [Batch 380/676] [D loss: -0.000775] [G loss: 0.025124] [d1 loss: 0.062696] [d2 loss: 0.056265]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 400/676] [D loss: -0.009236] [G loss: 0.073364] [d1 loss: 0.062824] [d2 loss: 0.050975]  [sq d1 d2: 0.000140]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 420/676] [D loss: -0.032892] [G loss: 0.168965] [d1 loss: 0.087382] [d2 loss: 0.070639]  [sq d1 d2: 0.000280]  [num0: 19.000000] [num1 45.000000]
[Epoch 264/500] [Batch 440/676] [D loss: -0.053419] [G loss: 0.255656] [d1 loss: 0.051920] [d2 loss: 0.052300]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 264/500] [Batch 460/676] [D loss: -0.071188] [G loss: 0.291650] [d1 loss: 0.059509] [d2 loss: 0.042516]  [sq d1 d2: 0.000289]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 480/676] [D loss: -0.069569] [G loss: 0.359338] [d1 loss: 0.051135] [d2 loss: 0.041873]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 264/500] [Batch 500/676] [D loss: -0.088238] [G loss: 0.402918] [d1 loss: 0.080799] [d2 loss: 0.067746]  [sq d1 d2: 0.000170]  [num0: 17.000000] [num1 47.000000]
[Epoch 264/500] [Batch 520/676] [D loss: -0.013340] [G loss: 0.305834] [d1 loss: 0.118045] [d2 loss: 0.109093]  [sq d1 d2: 0.000080]  [num0: 14.000000] [num1 50.000000]
[Epoch 264/500] [Batch 540/676] [D loss: -0.025622] [G loss: 0.215050] [d1 loss: 0.056298] [d2 loss: 0.064171]  [sq d1 d2: 0.000062]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 560/676] [D loss: 0.044404] [G loss: 0.100316] [d1 loss: 0.084059] [d2 loss: 0.099296]  [sq d1 d2: 0.000232]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 580/676] [D loss: 0.051151] [G loss: 0.025131] [d1 loss: 0.116813] [d2 loss: 0.130435]  [sq d1 d2: 0.000186]  [num0: 15.000000] [num1 49.000000]
[Epoch 264/500] [Batch 600/676] [D loss: 0.027077] [G loss: -0.003784] [d1 loss: 0.106970] [d2 loss: 0.114195]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 620/676] [D loss: 0.006402] [G loss: -0.048511] [d1 loss: 0.104506] [d2 loss: 0.101229]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 264/500] [Batch 640/676] [D loss: -0.014784] [G loss: -0.097517] [d1 loss: 0.132681] [d2 loss: 0.109750]  [sq d1 d2: 0.000526]  [num0: 16.000000] [num1 48.000000]
[Epoch 264/500] [Batch 660/676] [D loss: -0.019059] [G loss: -0.136255] [d1 loss: 0.041778] [d2 loss: 0.047068]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 0/676] [D loss: -0.028518] [G loss: -0.167157] [d1 loss: 0.078673] [d2 loss: 0.084805]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 20/676] [D loss: -0.056190] [G loss: -0.213391] [d1 loss: 0.141062] [d2 loss: 0.101102]  [sq d1 d2: 0.001597]  [num0: 13.000000] [num1 51.000000]
[Epoch 265/500] [Batch 40/676] [D loss: -0.058675] [G loss: -0.281582] [d1 loss: 0.053405] [d2 loss: 0.054526]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 265/500] [Batch 60/676] [D loss: -0.072287] [G loss: -0.376791] [d1 loss: 0.117373] [d2 loss: 0.124904]  [sq d1 d2: 0.000057]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 80/676] [D loss: -0.020947] [G loss: -0.460608] [d1 loss: 0.043908] [d2 loss: 0.046880]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 100/676] [D loss: -0.074279] [G loss: -0.415404] [d1 loss: 0.056248] [d2 loss: 0.046671]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 120/676] [D loss: -0.069637] [G loss: -0.349305] [d1 loss: 0.059653] [d2 loss: 0.058582]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 140/676] [D loss: 0.050328] [G loss: -0.232277] [d1 loss: 0.045978] [d2 loss: 0.053166]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 160/676] [D loss: 0.022004] [G loss: -0.064122] [d1 loss: 0.066197] [d2 loss: 0.074140]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 180/676] [D loss: 0.021532] [G loss: 0.033064] [d1 loss: 0.109543] [d2 loss: 0.126284]  [sq d1 d2: 0.000280]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 200/676] [D loss: 0.002089] [G loss: 0.033265] [d1 loss: 0.071818] [d2 loss: 0.061840]  [sq d1 d2: 0.000100]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 220/676] [D loss: -0.001214] [G loss: 0.060118] [d1 loss: 0.147503] [d2 loss: 0.165153]  [sq d1 d2: 0.000312]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 240/676] [D loss: -0.006125] [G loss: 0.066732] [d1 loss: 0.110387] [d2 loss: 0.132143]  [sq d1 d2: 0.000473]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 260/676] [D loss: -0.009454] [G loss: 0.097782] [d1 loss: 0.094130] [d2 loss: 0.075449]  [sq d1 d2: 0.000349]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 280/676] [D loss: -0.037809] [G loss: 0.167147] [d1 loss: 0.062287] [d2 loss: 0.063793]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 300/676] [D loss: -0.018200] [G loss: 0.250901] [d1 loss: 0.051777] [d2 loss: 0.046278]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 320/676] [D loss: -0.045980] [G loss: 0.288524] [d1 loss: 0.082217] [d2 loss: 0.082271]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 340/676] [D loss: -0.061640] [G loss: 0.395819] [d1 loss: 0.124997] [d2 loss: 0.126902]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 265/500] [Batch 360/676] [D loss: -0.082971] [G loss: 0.422251] [d1 loss: 0.086569] [d2 loss: 0.066211]  [sq d1 d2: 0.000414]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 380/676] [D loss: -0.034565] [G loss: 0.426785] [d1 loss: 0.113781] [d2 loss: 0.121619]  [sq d1 d2: 0.000061]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 400/676] [D loss: 0.031631] [G loss: 0.414582] [d1 loss: 0.102424] [d2 loss: 0.102881]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 265/500] [Batch 420/676] [D loss: 0.020248] [G loss: 0.306322] [d1 loss: 0.014388] [d2 loss: 0.014650]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 440/676] [D loss: -0.006666] [G loss: 0.293526] [d1 loss: 0.071513] [d2 loss: 0.096504]  [sq d1 d2: 0.000625]  [num0: 14.000000] [num1 50.000000]
[Epoch 265/500] [Batch 460/676] [D loss: 0.009443] [G loss: 0.203553] [d1 loss: 0.027896] [d2 loss: 0.031887]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 265/500] [Batch 480/676] [D loss: -0.006122] [G loss: 0.112804] [d1 loss: 0.080915] [d2 loss: 0.064837]  [sq d1 d2: 0.000259]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 500/676] [D loss: 0.011978] [G loss: 0.036476] [d1 loss: 0.040193] [d2 loss: 0.041120]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 520/676] [D loss: 0.001132] [G loss: -0.009215] [d1 loss: 0.075621] [d2 loss: 0.065799]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 265/500] [Batch 540/676] [D loss: -0.001729] [G loss: -0.053177] [d1 loss: 0.131125] [d2 loss: 0.103369]  [sq d1 d2: 0.000770]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 560/676] [D loss: -0.009716] [G loss: -0.111992] [d1 loss: 0.042521] [d2 loss: 0.044981]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 580/676] [D loss: -0.012592] [G loss: -0.184098] [d1 loss: 0.313605] [d2 loss: 0.251749]  [sq d1 d2: 0.003826]  [num0: 17.000000] [num1 47.000000]
[Epoch 265/500] [Batch 600/676] [D loss: -0.035947] [G loss: -0.267736] [d1 loss: 0.070028] [d2 loss: 0.062254]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 620/676] [D loss: -0.024983] [G loss: -0.324682] [d1 loss: 0.037717] [d2 loss: 0.033883]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 265/500] [Batch 640/676] [D loss: -0.018603] [G loss: -0.334016] [d1 loss: 0.093798] [d2 loss: 0.104935]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 265/500] [Batch 660/676] [D loss: -0.034765] [G loss: -0.397457] [d1 loss: 0.035686] [d2 loss: 0.052734]  [sq d1 d2: 0.000291]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 0/676] [D loss: -0.018304] [G loss: -0.412759] [d1 loss: 0.063654] [d2 loss: 0.072081]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]

[Epoch 266/500] [Batch 20/676] [D loss: -0.021232] [G loss: -0.416794] [d1 loss: 0.017482] [d2 loss: 0.022472]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 40/676] [D loss: -0.021670] [G loss: -0.418116] [d1 loss: 0.077568] [d2 loss: 0.097393]  [sq d1 d2: 0.000393]  [num0: 12.000000] [num1 52.000000]
[Epoch 266/500] [Batch 60/676] [D loss: 0.026609] [G loss: -0.367927] [d1 loss: 0.076974] [d2 loss: 0.099568]  [sq d1 d2: 0.000510]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 80/676] [D loss: 0.037974] [G loss: -0.237102] [d1 loss: 0.072766] [d2 loss: 0.093852]  [sq d1 d2: 0.000445]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 100/676] [D loss: 0.014868] [G loss: -0.133855] [d1 loss: 0.058645] [d2 loss: 0.051211]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 120/676] [D loss: 0.006917] [G loss: -0.038775] [d1 loss: 0.035441] [d2 loss: 0.027076]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 140/676] [D loss: 0.001175] [G loss: 0.014651] [d1 loss: 0.075426] [d2 loss: 0.060217]  [sq d1 d2: 0.000231]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 160/676] [D loss: -0.006630] [G loss: 0.059329] [d1 loss: 0.142760] [d2 loss: 0.152801]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 180/676] [D loss: -0.006743] [G loss: 0.120558] [d1 loss: 0.072791] [d2 loss: 0.061757]  [sq d1 d2: 0.000122]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 200/676] [D loss: -0.009407] [G loss: 0.150906] [d1 loss: 0.082669] [d2 loss: 0.099795]  [sq d1 d2: 0.000293]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 220/676] [D loss: -0.021630] [G loss: 0.217110] [d1 loss: 0.041592] [d2 loss: 0.067228]  [sq d1 d2: 0.000657]  [num0: 12.000000] [num1 52.000000]
[Epoch 266/500] [Batch 240/676] [D loss: -0.048551] [G loss: 0.287019] [d1 loss: 0.017045] [d2 loss: 0.017638]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 260/676] [D loss: -0.025268] [G loss: 0.370414] [d1 loss: 0.068098] [d2 loss: 0.077919]  [sq d1 d2: 0.000096]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 280/676] [D loss: -0.014925] [G loss: 0.430677] [d1 loss: 0.032223] [d2 loss: 0.024928]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 266/500] [Batch 300/676] [D loss: -0.017258] [G loss: 0.412323] [d1 loss: 0.164398] [d2 loss: 0.186652]  [sq d1 d2: 0.000495]  [num0: 15.000000] [num1 49.000000]
[Epoch 266/500] [Batch 320/676] [D loss: 0.018059] [G loss: 0.418534] [d1 loss: 0.098221] [d2 loss: 0.097081]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 340/676] [D loss: 0.011681] [G loss: 0.348545] [d1 loss: 0.027621] [d2 loss: 0.027941]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 360/676] [D loss: 0.002064] [G loss: 0.269437] [d1 loss: 0.090132] [d2 loss: 0.083132]  [sq d1 d2: 0.000049]  [num0: 11.000000] [num1 53.000000]
[Epoch 266/500] [Batch 380/676] [D loss: -0.001089] [G loss: 0.186342] [d1 loss: 0.099748] [d2 loss: 0.112806]  [sq d1 d2: 0.000171]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 400/676] [D loss: 0.006174] [G loss: 0.135635] [d1 loss: 0.042552] [d2 loss: 0.041966]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 420/676] [D loss: 0.001223] [G loss: 0.087605] [d1 loss: 0.126424] [d2 loss: 0.112724]  [sq d1 d2: 0.000188]  [num0: 19.000000] [num1 45.000000]
[Epoch 266/500] [Batch 440/676] [D loss: -0.010158] [G loss: 0.038899] [d1 loss: 0.038207] [d2 loss: 0.035197]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 460/676] [D loss: -0.000927] [G loss: -0.017202] [d1 loss: 0.100906] [d2 loss: 0.121758]  [sq d1 d2: 0.000435]  [num0: 15.000000] [num1 49.000000]
[Epoch 266/500] [Batch 480/676] [D loss: -0.036604] [G loss: -0.094091] [d1 loss: 0.147920] [d2 loss: 0.123617]  [sq d1 d2: 0.000591]  [num0: 19.000000] [num1 45.000000]
[Epoch 266/500] [Batch 500/676] [D loss: -0.029578] [G loss: -0.185522] [d1 loss: 0.022521] [d2 loss: 0.022189]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 266/500] [Batch 520/676] [D loss: -0.020989] [G loss: -0.248295] [d1 loss: 0.033389] [d2 loss: 0.038340]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 266/500] [Batch 540/676] [D loss: -0.025612] [G loss: -0.329556] [d1 loss: 0.058365] [d2 loss: 0.044506]  [sq d1 d2: 0.000192]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 560/676] [D loss: -0.009808] [G loss: -0.332581] [d1 loss: 0.095667] [d2 loss: 0.099388]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 266/500] [Batch 580/676] [D loss: 0.046118] [G loss: -0.354468] [d1 loss: 0.047075] [d2 loss: 0.054518]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 266/500] [Batch 600/676] [D loss: -0.031686] [G loss: -0.316278] [d1 loss: 0.054512] [d2 loss: 0.057675]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 266/500] [Batch 620/676] [D loss: 0.012147] [G loss: -0.288161] [d1 loss: 0.067708] [d2 loss: 0.066476]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 266/500] [Batch 640/676] [D loss: 0.021431] [G loss: -0.229195] [d1 loss: 0.221761] [d2 loss: 0.209565]  [sq d1 d2: 0.000149]  [num0: 12.000000] [num1 52.000000]
[Epoch 266/500] [Batch 660/676] [D loss: 0.018302] [G loss: -0.159517] [d1 loss: 0.097086] [d2 loss: 0.096720]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 267/500] [Batch 0/676] [D loss: 0.012303] [G loss: -0.119625] [d1 loss: 0.055652] [d2 loss: 0.041418]  [sq d1 d2: 0.000203]  [num0: 15.000000] [num1 49.000000]
[Epoch 267/500] [Batch 20/676] [D loss: -0.003191] [G loss: -0.068153] [d1 loss: 0.076047] [d2 loss: 0.071924]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 267/500] [Batch 40/676] [D loss: -0.005523] [G loss: -0.041357] [d1 loss: 0.076117] [d2 loss: 0.068255]  [sq d1 d2: 0.000062]  [num0: 13.000000] [num1 51.000000]
[Epoch 267/500] [Batch 60/676] [D loss: -0.013529] [G loss: -0.067288] [d1 loss: 0.055382] [d2 loss: 0.046495]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 267/500] [Batch 80/676] [D loss: -0.008037] [G loss: -0.036700] [d1 loss: 0.079588] [d2 loss: 0.072339]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 100/676] [D loss: -0.019506] [G loss: -0.021582] [d1 loss: 0.134873] [d2 loss: 0.141497]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 120/676] [D loss: -0.027011] [G loss: -0.029951] [d1 loss: 0.057671] [d2 loss: 0.063383]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 140/676] [D loss: -0.008260] [G loss: -0.016318] [d1 loss: 0.019739] [d2 loss: 0.011607]  [sq d1 d2: 0.000066]  [num0: 19.000000] [num1 45.000000]
[Epoch 267/500] [Batch 160/676] [D loss: -0.000565] [G loss: -0.018906] [d1 loss: 0.102615] [d2 loss: 0.080024]  [sq d1 d2: 0.000510]  [num0: 19.000000] [num1 45.000000]
[Epoch 267/500] [Batch 180/676] [D loss: -0.003518] [G loss: 0.016888] [d1 loss: 0.046480] [d2 loss: 0.044661]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 267/500] [Batch 200/676] [D loss: -0.022014] [G loss: 0.004937] [d1 loss: 0.063581] [d2 loss: 0.066042]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 267/500] [Batch 220/676] [D loss: -0.018465] [G loss: -0.032302] [d1 loss: 0.071606] [d2 loss: 0.093210]  [sq d1 d2: 0.000467]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 240/676] [D loss: -0.012773] [G loss: -0.025113] [d1 loss: 0.103592] [d2 loss: 0.115866]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 267/500] [Batch 260/676] [D loss: 0.020408] [G loss: 0.023629] [d1 loss: 0.076573] [d2 loss: 0.064531]  [sq d1 d2: 0.000145]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 280/676] [D loss: 0.003795] [G loss: 0.021889] [d1 loss: 0.029596] [d2 loss: 0.038764]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 267/500] [Batch 300/676] [D loss: 0.004974] [G loss: 0.034355] [d1 loss: 0.071947] [d2 loss: 0.086056]  [sq d1 d2: 0.000199]  [num0: 14.000000] [num1 50.000000]
[Epoch 267/500] [Batch 320/676] [D loss: -0.015107] [G loss: 0.048148] [d1 loss: 0.050795] [d2 loss: 0.042275]  [sq d1 d2: 0.000073]  [num0: 17.000000] [num1 47.000000]

[Epoch 267/500] [Batch 340/676] [D loss: -0.014457] [G loss: 0.051564] [d1 loss: 0.057745] [d2 loss: 0.062893]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 360/676] [D loss: -0.013886] [G loss: 0.087518] [d1 loss: 0.040778] [d2 loss: 0.052828]  [sq d1 d2: 0.000145]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 380/676] [D loss: -0.019718] [G loss: 0.056188] [d1 loss: 0.075102] [d2 loss: 0.059272]  [sq d1 d2: 0.000251]  [num0: 22.000000] [num1 42.000000]
[Epoch 267/500] [Batch 400/676] [D loss: -0.004902] [G loss: 0.059582] [d1 loss: 0.070081] [d2 loss: 0.081878]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 420/676] [D loss: -0.022274] [G loss: 0.072565] [d1 loss: 0.048855] [d2 loss: 0.059063]  [sq d1 d2: 0.000104]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 440/676] [D loss: -0.005952] [G loss: 0.062030] [d1 loss: 0.045667] [d2 loss: 0.052110]  [sq d1 d2: 0.000042]  [num0: 19.000000] [num1 45.000000]
[Epoch 267/500] [Batch 460/676] [D loss: -0.006119] [G loss: 0.051035] [d1 loss: 0.105038] [d2 loss: 0.081285]  [sq d1 d2: 0.000564]  [num0: 12.000000] [num1 52.000000]
[Epoch 267/500] [Batch 480/676] [D loss: -0.021931] [G loss: 0.075362] [d1 loss: 0.033906] [d2 loss: 0.038119]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 267/500] [Batch 500/676] [D loss: -0.027388] [G loss: 0.057659] [d1 loss: 0.116324] [d2 loss: 0.137425]  [sq d1 d2: 0.000445]  [num0: 12.000000] [num1 52.000000]
[Epoch 267/500] [Batch 520/676] [D loss: 0.004355] [G loss: 0.109705] [d1 loss: 0.073085] [d2 loss: 0.071810]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 540/676] [D loss: -0.003973] [G loss: 0.079707] [d1 loss: 0.028337] [d2 loss: 0.024024]  [sq d1 d2: 0.000019]  [num0: 20.000000] [num1 44.000000]
[Epoch 267/500] [Batch 560/676] [D loss: 0.003555] [G loss: 0.083522] [d1 loss: 0.076431] [d2 loss: 0.087070]  [sq d1 d2: 0.000113]  [num0: 19.000000] [num1 45.000000]
[Epoch 267/500] [Batch 580/676] [D loss: -0.011008] [G loss: 0.095090] [d1 loss: 0.037039] [d2 loss: 0.035195]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 600/676] [D loss: -0.011838] [G loss: 0.116061] [d1 loss: 0.038442] [d2 loss: 0.048484]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 267/500] [Batch 620/676] [D loss: -0.014970] [G loss: 0.108202] [d1 loss: 0.035879] [d2 loss: 0.031839]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 267/500] [Batch 640/676] [D loss: -0.013133] [G loss: 0.024564] [d1 loss: 0.084460] [d2 loss: 0.055656]  [sq d1 d2: 0.000830]  [num0: 17.000000] [num1 47.000000]
[Epoch 267/500] [Batch 660/676] [D loss: -0.010020] [G loss: 0.012486] [d1 loss: 0.055064] [d2 loss: 0.055769]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 268/500] [Batch 0/676] [D loss: -0.014496] [G loss: 0.000336] [d1 loss: 0.072520] [d2 loss: 0.067377]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 20/676] [D loss: -0.024845] [G loss: -0.084969] [d1 loss: 0.017590] [d2 loss: 0.027676]  [sq d1 d2: 0.000102]  [num0: 12.000000] [num1 52.000000]
[Epoch 268/500] [Batch 40/676] [D loss: -0.033330] [G loss: -0.031808] [d1 loss: 0.046451] [d2 loss: 0.034004]  [sq d1 d2: 0.000155]  [num0: 14.000000] [num1 50.000000]
[Epoch 268/500] [Batch 60/676] [D loss: -0.047972] [G loss: -0.056939] [d1 loss: 0.086600] [d2 loss: 0.082425]  [sq d1 d2: 0.000017]  [num0: 9.000000] [num1 55.000000]
[Epoch 268/500] [Batch 80/676] [D loss: -0.028719] [G loss: -0.070521] [d1 loss: 0.033189] [d2 loss: 0.034856]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 268/500] [Batch 100/676] [D loss: -0.009217] [G loss: -0.041067] [d1 loss: 0.049406] [d2 loss: 0.064893]  [sq d1 d2: 0.000240]  [num0: 14.000000] [num1 50.000000]
[Epoch 268/500] [Batch 120/676] [D loss: -0.026685] [G loss: -0.044539] [d1 loss: 0.040172] [d2 loss: 0.054897]  [sq d1 d2: 0.000217]  [num0: 14.000000] [num1 50.000000]
[Epoch 268/500] [Batch 140/676] [D loss: 0.005120] [G loss: -0.042188] [d1 loss: 0.065788] [d2 loss: 0.046206]  [sq d1 d2: 0.000383]  [num0: 9.000000] [num1 55.000000]
[Epoch 268/500] [Batch 160/676] [D loss: -0.008745] [G loss: -0.037361] [d1 loss: 0.047064] [d2 loss: 0.035119]  [sq d1 d2: 0.000143]  [num0: 11.000000] [num1 53.000000]
[Epoch 268/500] [Batch 180/676] [D loss: -0.000303] [G loss: -0.045032] [d1 loss: 0.025099] [d2 loss: 0.033882]  [sq d1 d2: 0.000077]  [num0: 17.000000] [num1 47.000000]
[Epoch 268/500] [Batch 200/676] [D loss: -0.006001] [G loss: 0.016606] [d1 loss: 0.223189] [d2 loss: 0.232346]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 268/500] [Batch 220/676] [D loss: 0.004931] [G loss: 0.032904] [d1 loss: 0.100405] [d2 loss: 0.091587]  [sq d1 d2: 0.000078]  [num0: 19.000000] [num1 45.000000]
[Epoch 268/500] [Batch 240/676] [D loss: -0.010262] [G loss: 0.052092] [d1 loss: 0.080618] [d2 loss: 0.090638]  [sq d1 d2: 0.000100]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 260/676] [D loss: -0.047795] [G loss: 0.068620] [d1 loss: 0.061439] [d2 loss: 0.055195]  [sq d1 d2: 0.000039]  [num0: 19.000000] [num1 45.000000]
[Epoch 268/500] [Batch 280/676] [D loss: -0.010526] [G loss: 0.024484] [d1 loss: 0.076903] [d2 loss: 0.068141]  [sq d1 d2: 0.000077]  [num0: 21.000000] [num1 43.000000]
[Epoch 268/500] [Batch 300/676] [D loss: -0.016899] [G loss: 0.006521] [d1 loss: 0.069607] [d2 loss: 0.059219]  [sq d1 d2: 0.000108]  [num0: 19.000000] [num1 45.000000]
[Epoch 268/500] [Batch 320/676] [D loss: -0.021732] [G loss: 0.014177] [d1 loss: 0.049484] [d2 loss: 0.050657]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 268/500] [Batch 340/676] [D loss: -0.017882] [G loss: 0.023476] [d1 loss: 0.137112] [d2 loss: 0.096723]  [sq d1 d2: 0.001631]  [num0: 21.000000] [num1 43.000000]
[Epoch 268/500] [Batch 360/676] [D loss: -0.009457] [G loss: 0.081488] [d1 loss: 0.066977] [d2 loss: 0.071500]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 268/500] [Batch 380/676] [D loss: 0.008338] [G loss: 0.082691] [d1 loss: 0.093146] [d2 loss: 0.115176]  [sq d1 d2: 0.000485]  [num0: 13.000000] [num1 51.000000]
[Epoch 268/500] [Batch 400/676] [D loss: -0.009213] [G loss: 0.119138] [d1 loss: 0.023088] [d2 loss: 0.026060]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 420/676] [D loss: -0.026286] [G loss: 0.158371] [d1 loss: 0.057622] [d2 loss: 0.058244]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 268/500] [Batch 440/676] [D loss: 0.000924] [G loss: 0.144921] [d1 loss: 0.091789] [d2 loss: 0.079188]  [sq d1 d2: 0.000159]  [num0: 18.000000] [num1 46.000000]
[Epoch 268/500] [Batch 460/676] [D loss: -0.029411] [G loss: 0.074499] [d1 loss: 0.045278] [d2 loss: 0.054591]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 480/676] [D loss: -0.035648] [G loss: 0.025185] [d1 loss: 0.035283] [d2 loss: 0.045292]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 268/500] [Batch 500/676] [D loss: -0.027793] [G loss: -0.008194] [d1 loss: 0.071629] [d2 loss: 0.074273]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 268/500] [Batch 520/676] [D loss: -0.036943] [G loss: -0.023447] [d1 loss: 0.141435] [d2 loss: 0.109163]  [sq d1 d2: 0.001041]  [num0: 15.000000] [num1 49.000000]
[Epoch 268/500] [Batch 540/676] [D loss: -0.061441] [G loss: -0.065050] [d1 loss: 0.044408] [d2 loss: 0.040838]  [sq d1 d2: 0.000013]  [num0: 10.000000] [num1 54.000000]
[Epoch 268/500] [Batch 560/676] [D loss: -0.015444] [G loss: -0.108490] [d1 loss: 0.029153] [d2 loss: 0.019468]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 268/500] [Batch 580/676] [D loss: 0.009063] [G loss: -0.155400] [d1 loss: 0.094246] [d2 loss: 0.128544]  [sq d1 d2: 0.001176]  [num0: 17.000000] [num1 47.000000]
[Epoch 268/500] [Batch 600/676] [D loss: -0.005869] [G loss: -0.154538] [d1 loss: 0.019633] [d2 loss: 0.016432]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 268/500] [Batch 620/676] [D loss: -0.006972] [G loss: -0.140648] [d1 loss: 0.077152] [d2 loss: 0.068754]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 640/676] [D loss: 0.009261] [G loss: -0.128560] [d1 loss: 0.052852] [d2 loss: 0.059535]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 268/500] [Batch 660/676] [D loss: -0.008989] [G loss: -0.112173] [d1 loss: 0.037019] [d2 loss: 0.032268]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]

[Epoch 269/500] [Batch 0/676] [D loss: 0.001812] [G loss: -0.055131] [d1 loss: 0.068090] [d2 loss: 0.078008]  [sq d1 d2: 0.000098]  [num0: 18.000000] [num1 46.000000]
[Epoch 269/500] [Batch 20/676] [D loss: -0.008002] [G loss: 0.031914] [d1 loss: 0.106722] [d2 loss: 0.087349]  [sq d1 d2: 0.000375]  [num0: 18.000000] [num1 46.000000]
[Epoch 269/500] [Batch 40/676] [D loss: -0.032571] [G loss: 0.050627] [d1 loss: 0.069990] [d2 loss: 0.076144]  [sq d1 d2: 0.000038]  [num0: 19.000000] [num1 45.000000]
[Epoch 269/500] [Batch 60/676] [D loss: -0.024562] [G loss: 0.086763] [d1 loss: 0.128571] [d2 loss: 0.111104]  [sq d1 d2: 0.000305]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 80/676] [D loss: -0.011771] [G loss: 0.088620] [d1 loss: 0.041550] [d2 loss: 0.050182]  [sq d1 d2: 0.000075]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 100/676] [D loss: -0.045377] [G loss: 0.134346] [d1 loss: 0.063808] [d2 loss: 0.062556]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 269/500] [Batch 120/676] [D loss: -0.066989] [G loss: 0.119824] [d1 loss: 0.029396] [d2 loss: 0.027498]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 269/500] [Batch 140/676] [D loss: -0.005362] [G loss: 0.152490] [d1 loss: 0.060330] [d2 loss: 0.045956]  [sq d1 d2: 0.000207]  [num0: 13.000000] [num1 51.000000]
[Epoch 269/500] [Batch 160/676] [D loss: -0.018215] [G loss: 0.082444] [d1 loss: 0.054960] [d2 loss: 0.073282]  [sq d1 d2: 0.000336]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 180/676] [D loss: 0.017119] [G loss: 0.063487] [d1 loss: 0.085289] [d2 loss: 0.090135]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 200/676] [D loss: 0.004975] [G loss: 0.004492] [d1 loss: 0.077866] [d2 loss: 0.077844]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 220/676] [D loss: -0.000774] [G loss: -0.033206] [d1 loss: 0.064122] [d2 loss: 0.057864]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 240/676] [D loss: 0.001501] [G loss: -0.101287] [d1 loss: 0.097290] [d2 loss: 0.089214]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 260/676] [D loss: -0.017760] [G loss: -0.074066] [d1 loss: 0.079756] [d2 loss: 0.095866]  [sq d1 d2: 0.000260]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 280/676] [D loss: -0.040706] [G loss: -0.108823] [d1 loss: 0.026857] [d2 loss: 0.023828]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 300/676] [D loss: -0.040427] [G loss: -0.166445] [d1 loss: 0.024069] [d2 loss: 0.024237]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 269/500] [Batch 320/676] [D loss: -0.057970] [G loss: -0.189378] [d1 loss: 0.044917] [d2 loss: 0.046118]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 340/676] [D loss: -0.041351] [G loss: -0.184928] [d1 loss: 0.022772] [d2 loss: 0.023111]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 269/500] [Batch 360/676] [D loss: -0.028100] [G loss: -0.195941] [d1 loss: 0.021924] [d2 loss: 0.021648]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 380/676] [D loss: -0.046485] [G loss: -0.217769] [d1 loss: 0.069822] [d2 loss: 0.073712]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 269/500] [Batch 400/676] [D loss: -0.042536] [G loss: -0.181665] [d1 loss: 0.123081] [d2 loss: 0.136000]  [sq d1 d2: 0.000167]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 420/676] [D loss: 0.015974] [G loss: -0.041488] [d1 loss: 0.091141] [d2 loss: 0.090652]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 440/676] [D loss: 0.016289] [G loss: -0.037954] [d1 loss: 0.025245] [d2 loss: 0.021952]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 460/676] [D loss: 0.004641] [G loss: -0.036793] [d1 loss: 0.060009] [d2 loss: 0.052336]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 480/676] [D loss: -0.003238] [G loss: 0.010990] [d1 loss: 0.120307] [d2 loss: 0.096594]  [sq d1 d2: 0.000562]  [num0: 17.000000] [num1 47.000000]
[Epoch 269/500] [Batch 500/676] [D loss: -0.006869] [G loss: 0.042681] [d1 loss: 0.023913] [d2 loss: 0.022313]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 269/500] [Batch 520/676] [D loss: -0.024954] [G loss: 0.029825] [d1 loss: 0.100441] [d2 loss: 0.101558]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 540/676] [D loss: -0.024590] [G loss: 0.054921] [d1 loss: 0.115623] [d2 loss: 0.078643]  [sq d1 d2: 0.001367]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 560/676] [D loss: -0.013711] [G loss: 0.035464] [d1 loss: 0.102914] [d2 loss: 0.096792]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 580/676] [D loss: 0.003291] [G loss: 0.033260] [d1 loss: 0.032534] [d2 loss: 0.038736]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 269/500] [Batch 600/676] [D loss: -0.013375] [G loss: 0.017799] [d1 loss: 0.093481] [d2 loss: 0.122105]  [sq d1 d2: 0.000819]  [num0: 17.000000] [num1 47.000000]
[Epoch 269/500] [Batch 620/676] [D loss: -0.040851] [G loss: 0.004257] [d1 loss: 0.072612] [d2 loss: 0.074904]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 269/500] [Batch 640/676] [D loss: 0.005735] [G loss: -0.015571] [d1 loss: 0.034350] [d2 loss: 0.040758]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 269/500] [Batch 660/676] [D loss: 0.021158] [G loss: -0.018849] [d1 loss: 0.044949] [d2 loss: 0.036838]  [sq d1 d2: 0.000066]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 0/676] [D loss: 0.005474] [G loss: -0.035258] [d1 loss: 0.070912] [d2 loss: 0.078160]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 270/500] [Batch 20/676] [D loss: -0.000112] [G loss: -0.031890] [d1 loss: 0.031283] [d2 loss: 0.032134]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 270/500] [Batch 40/676] [D loss: -0.008901] [G loss: -0.002626] [d1 loss: 0.042246] [d2 loss: 0.033503]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 270/500] [Batch 60/676] [D loss: 0.004434] [G loss: -0.026474] [d1 loss: 0.042958] [d2 loss: 0.043242]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 270/500] [Batch 80/676] [D loss: 0.001563] [G loss: -0.041068] [d1 loss: 0.027517] [d2 loss: 0.021851]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 100/676] [D loss: -0.006535] [G loss: -0.047711] [d1 loss: 0.027767] [d2 loss: 0.025411]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 120/676] [D loss: -0.016289] [G loss: -0.034234] [d1 loss: 0.248954] [d2 loss: 0.200131]  [sq d1 d2: 0.002384]  [num0: 12.000000] [num1 52.000000]
[Epoch 270/500] [Batch 140/676] [D loss: -0.016481] [G loss: -0.021518] [d1 loss: 0.031500] [d2 loss: 0.034650]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 160/676] [D loss: -0.023002] [G loss: -0.032650] [d1 loss: 0.086725] [d2 loss: 0.096686]  [sq d1 d2: 0.000099]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 180/676] [D loss: -0.016412] [G loss: -0.026208] [d1 loss: 0.036440] [d2 loss: 0.036803]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 200/676] [D loss: -0.035890] [G loss: -0.014586] [d1 loss: 0.083184] [d2 loss: 0.087655]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 270/500] [Batch 220/676] [D loss: 0.001691] [G loss: -0.022753] [d1 loss: 0.088702] [d2 loss: 0.073605]  [sq d1 d2: 0.000228]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 240/676] [D loss: -0.004604] [G loss: -0.048462] [d1 loss: 0.089264] [d2 loss: 0.074059]  [sq d1 d2: 0.000231]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 260/676] [D loss: -0.004113] [G loss: -0.029090] [d1 loss: 0.014259] [d2 loss: 0.017342]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 280/676] [D loss: 0.001340] [G loss: -0.045591] [d1 loss: 0.079745] [d2 loss: 0.081631]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 300/676] [D loss: -0.017292] [G loss: -0.029653] [d1 loss: 0.088599] [d2 loss: 0.114223]  [sq d1 d2: 0.000657]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 320/676] [D loss: 0.002426] [G loss: 0.005698] [d1 loss: 0.009548] [d2 loss: 0.012240]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 340/676] [D loss: 0.012542] [G loss: 0.011963] [d1 loss: 0.053000] [d2 loss: 0.049527]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]

[Epoch 270/500] [Batch 360/676] [D loss: 0.003205] [G loss: 0.041289] [d1 loss: 0.060889] [d2 loss: 0.068180]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 270/500] [Batch 380/676] [D loss: -0.006988] [G loss: 0.057222] [d1 loss: 0.097485] [d2 loss: 0.084915]  [sq d1 d2: 0.000158]  [num0: 13.000000] [num1 51.000000]
[Epoch 270/500] [Batch 400/676] [D loss: -0.010360] [G loss: 0.081763] [d1 loss: 0.070215] [d2 loss: 0.052175]  [sq d1 d2: 0.000325]  [num0: 17.000000] [num1 47.000000]
[Epoch 270/500] [Batch 420/676] [D loss: -0.012384] [G loss: 0.079706] [d1 loss: 0.067678] [d2 loss: 0.075618]  [sq d1 d2: 0.000063]  [num0: 19.000000] [num1 45.000000]
[Epoch 270/500] [Batch 440/676] [D loss: -0.022461] [G loss: 0.093327] [d1 loss: 0.044897] [d2 loss: 0.055399]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 270/500] [Batch 460/676] [D loss: -0.038479] [G loss: 0.142591] [d1 loss: 0.044944] [d2 loss: 0.114220]  [sq d1 d2: 0.004799]  [num0: 18.000000] [num1 46.000000]
[Epoch 270/500] [Batch 480/676] [D loss: -0.016330] [G loss: 0.162339] [d1 loss: 0.074620] [d2 loss: 0.075363]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 270/500] [Batch 500/676] [D loss: -0.010851] [G loss: 0.183355] [d1 loss: 0.089492] [d2 loss: 0.088254]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 270/500] [Batch 520/676] [D loss: -0.005725] [G loss: 0.178865] [d1 loss: 0.063597] [d2 loss: 0.065505]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 270/500] [Batch 540/676] [D loss: 0.000350] [G loss: 0.184227] [d1 loss: 0.055274] [d2 loss: 0.057806]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 270/500] [Batch 560/676] [D loss: 0.007356] [G loss: 0.187011] [d1 loss: 0.045384] [d2 loss: 0.041784]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 270/500] [Batch 580/676] [D loss: -0.010336] [G loss: 0.170156] [d1 loss: 0.115570] [d2 loss: 0.118659]  [sq d1 d2: 0.000010]  [num0: 23.000000] [num1 41.000000]
[Epoch 270/500] [Batch 600/676] [D loss: -0.006721] [G loss: 0.156374] [d1 loss: 0.047859] [d2 loss: 0.037177]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 270/500] [Batch 620/676] [D loss: 0.001443] [G loss: 0.128097] [d1 loss: 0.082676] [d2 loss: 0.079330]  [sq d1 d2: 0.000011]  [num0: 19.000000] [num1 45.000000]
[Epoch 270/500] [Batch 640/676] [D loss: -0.004663] [G loss: 0.079160] [d1 loss: 0.035865] [d2 loss: 0.043747]  [sq d1 d2: 0.000062]  [num0: 12.000000] [num1 52.000000]
[Epoch 270/500] [Batch 660/676] [D loss: -0.008119] [G loss: 0.064257] [d1 loss: 0.066520] [d2 loss: 0.055860]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 271/500] [Batch 0/676] [D loss: -0.017848] [G loss: 0.056013] [d1 loss: 0.064480] [d2 loss: 0.060973]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 20/676] [D loss: -0.009526] [G loss: 0.045786] [d1 loss: 0.160143] [d2 loss: 0.130153]  [sq d1 d2: 0.000899]  [num0: 18.000000] [num1 46.000000]
[Epoch 271/500] [Batch 40/676] [D loss: -0.010331] [G loss: 0.032044] [d1 loss: 0.092227] [d2 loss: 0.091995]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 60/676] [D loss: -0.025516] [G loss: 0.010356] [d1 loss: 0.098569] [d2 loss: 0.094478]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 80/676] [D loss: -0.012518] [G loss: -0.049505] [d1 loss: 0.049020] [d2 loss: 0.052183]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 100/676] [D loss: -0.016049] [G loss: -0.093565] [d1 loss: 0.045747] [d2 loss: 0.045917]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 271/500] [Batch 120/676] [D loss: -0.007329] [G loss: -0.114557] [d1 loss: 0.072174] [d2 loss: 0.073028]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 140/676] [D loss: 0.001344] [G loss: -0.144636] [d1 loss: 0.078919] [d2 loss: 0.077525]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 160/676] [D loss: 0.006439] [G loss: -0.162530] [d1 loss: 0.042481] [d2 loss: 0.032592]  [sq d1 d2: 0.000098]  [num0: 13.000000] [num1 51.000000]
[Epoch 271/500] [Batch 180/676] [D loss: -0.012241] [G loss: -0.161782] [d1 loss: 0.073573] [d2 loss: 0.078067]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 200/676] [D loss: 0.002037] [G loss: -0.136632] [d1 loss: 0.077580] [d2 loss: 0.070467]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 220/676] [D loss: 0.004202] [G loss: -0.137569] [d1 loss: 0.076043] [d2 loss: 0.058895]  [sq d1 d2: 0.000294]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 240/676] [D loss: -0.004027] [G loss: -0.130454] [d1 loss: 0.075816] [d2 loss: 0.070834]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 271/500] [Batch 260/676] [D loss: -0.011764] [G loss: -0.150090] [d1 loss: 0.056571] [d2 loss: 0.049043]  [sq d1 d2: 0.000057]  [num0: 19.000000] [num1 45.000000]
[Epoch 271/500] [Batch 280/676] [D loss: -0.013969] [G loss: -0.170726] [d1 loss: 0.140784] [d2 loss: 0.088731]  [sq d1 d2: 0.002710]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 300/676] [D loss: -0.018990] [G loss: -0.220496] [d1 loss: 0.011310] [d2 loss: 0.011032]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 320/676] [D loss: -0.019928] [G loss: -0.199831] [d1 loss: 0.048150] [d2 loss: 0.071284]  [sq d1 d2: 0.000535]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 340/676] [D loss: -0.011179] [G loss: -0.228871] [d1 loss: 0.079595] [d2 loss: 0.079387]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 360/676] [D loss: -0.007981] [G loss: -0.237649] [d1 loss: 0.032552] [d2 loss: 0.032324]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 380/676] [D loss: -0.015850] [G loss: -0.288885] [d1 loss: 0.063868] [d2 loss: 0.034409]  [sq d1 d2: 0.000868]  [num0: 13.000000] [num1 51.000000]
[Epoch 271/500] [Batch 400/676] [D loss: -0.000668] [G loss: -0.218553] [d1 loss: 0.059379] [d2 loss: 0.041545]  [sq d1 d2: 0.000318]  [num0: 18.000000] [num1 46.000000]
[Epoch 271/500] [Batch 420/676] [D loss: 0.007548] [G loss: -0.232859] [d1 loss: 0.040090] [d2 loss: 0.049234]  [sq d1 d2: 0.000084]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 440/676] [D loss: 0.002667] [G loss: -0.205640] [d1 loss: 0.026047] [d2 loss: 0.026061]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 460/676] [D loss: 0.010049] [G loss: -0.165240] [d1 loss: 0.036435] [d2 loss: 0.040857]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 480/676] [D loss: -0.013871] [G loss: -0.134843] [d1 loss: 0.021572] [d2 loss: 0.021544]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 271/500] [Batch 500/676] [D loss: 0.004284] [G loss: -0.137057] [d1 loss: 0.028068] [d2 loss: 0.028002]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 271/500] [Batch 520/676] [D loss: 0.004844] [G loss: -0.074485] [d1 loss: 0.102550] [d2 loss: 0.071145]  [sq d1 d2: 0.000986]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 540/676] [D loss: -0.004194] [G loss: -0.023449] [d1 loss: 0.126495] [d2 loss: 0.114855]  [sq d1 d2: 0.000135]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 560/676] [D loss: -0.009427] [G loss: 0.013828] [d1 loss: 0.058487] [d2 loss: 0.058769]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 271/500] [Batch 580/676] [D loss: -0.015301] [G loss: 0.064490] [d1 loss: 0.055639] [d2 loss: 0.046122]  [sq d1 d2: 0.000091]  [num0: 13.000000] [num1 51.000000]
[Epoch 271/500] [Batch 600/676] [D loss: -0.001800] [G loss: 0.076703] [d1 loss: 0.065851] [d2 loss: 0.056009]  [sq d1 d2: 0.000097]  [num0: 17.000000] [num1 47.000000]
[Epoch 271/500] [Batch 620/676] [D loss: -0.010378] [G loss: 0.096358] [d1 loss: 0.082166] [d2 loss: 0.083125]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 271/500] [Batch 640/676] [D loss: -0.001181] [G loss: 0.101819] [d1 loss: 0.038836] [d2 loss: 0.032318]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 271/500] [Batch 660/676] [D loss: -0.023546] [G loss: 0.109393] [d1 loss: 0.046670] [d2 loss: 0.033071]  [sq d1 d2: 0.000185]  [num0: 16.000000] [num1 48.000000]
[Epoch 272/500] [Batch 0/676] [D loss: -0.013677] [G loss: 0.092931] [d1 loss: 0.098229] [d2 loss: 0.089872]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 20/676] [D loss: -0.022592] [G loss: 0.120082] [d1 loss: 0.074764] [d2 loss: 0.066385]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]

[Epoch 272/500] [Batch 40/676] [D loss: 0.006451] [G loss: 0.092341] [d1 loss: 0.052323] [d2 loss: 0.044023]  [sq d1 d2: 0.000069]  [num0: 20.000000] [num1 44.000000]
[Epoch 272/500] [Batch 60/676] [D loss: 0.009079] [G loss: 0.080122] [d1 loss: 0.023252] [d2 loss: 0.018003]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 80/676] [D loss: 0.002307] [G loss: 0.067738] [d1 loss: 0.089082] [d2 loss: 0.059889]  [sq d1 d2: 0.000852]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 100/676] [D loss: 0.005340] [G loss: 0.038920] [d1 loss: 0.069844] [d2 loss: 0.065182]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 272/500] [Batch 120/676] [D loss: -0.008417] [G loss: 0.059463] [d1 loss: 0.040197] [d2 loss: 0.038646]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 272/500] [Batch 140/676] [D loss: -0.007432] [G loss: 0.045364] [d1 loss: 0.042225] [d2 loss: 0.040154]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 160/676] [D loss: -0.006387] [G loss: 0.020393] [d1 loss: 0.092752] [d2 loss: 0.094176]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 272/500] [Batch 180/676] [D loss: -0.012874] [G loss: -0.001255] [d1 loss: 0.013996] [d2 loss: 0.023125]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 200/676] [D loss: -0.010861] [G loss: -0.038286] [d1 loss: 0.057893] [d2 loss: 0.050880]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 272/500] [Batch 220/676] [D loss: -0.019063] [G loss: -0.104525] [d1 loss: 0.022148] [d2 loss: 0.024798]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 272/500] [Batch 240/676] [D loss: -0.011458] [G loss: -0.094638] [d1 loss: 0.058303] [d2 loss: 0.066519]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 260/676] [D loss: -0.019336] [G loss: -0.114692] [d1 loss: 0.081426] [d2 loss: 0.094689]  [sq d1 d2: 0.000176]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 280/676] [D loss: -0.026524] [G loss: -0.146469] [d1 loss: 0.062982] [d2 loss: 0.073597]  [sq d1 d2: 0.000113]  [num0: 19.000000] [num1 45.000000]
[Epoch 272/500] [Batch 300/676] [D loss: 0.005165] [G loss: -0.101458] [d1 loss: 0.109335] [d2 loss: 0.115292]  [sq d1 d2: 0.000035]  [num0: 18.000000] [num1 46.000000]
[Epoch 272/500] [Batch 320/676] [D loss: -0.002558] [G loss: -0.079720] [d1 loss: 0.032199] [d2 loss: 0.036580]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 272/500] [Batch 340/676] [D loss: 0.009921] [G loss: -0.046000] [d1 loss: 0.037502] [d2 loss: 0.039218]  [sq d1 d2: 0.000003]  [num0: 10.000000] [num1 54.000000]
[Epoch 272/500] [Batch 360/676] [D loss: -0.000157] [G loss: -0.010030] [d1 loss: 0.066989] [d2 loss: 0.055938]  [sq d1 d2: 0.000122]  [num0: 20.000000] [num1 44.000000]
[Epoch 272/500] [Batch 380/676] [D loss: 0.001902] [G loss: 0.024522] [d1 loss: 0.124355] [d2 loss: 0.115485]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 272/500] [Batch 400/676] [D loss: -0.006246] [G loss: 0.034416] [d1 loss: 0.095440] [d2 loss: 0.100243]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]
[Epoch 272/500] [Batch 420/676] [D loss: 0.000823] [G loss: 0.035238] [d1 loss: 0.071815] [d2 loss: 0.092296]  [sq d1 d2: 0.000419]  [num0: 18.000000] [num1 46.000000]
[Epoch 272/500] [Batch 440/676] [D loss: -0.021939] [G loss: 0.086178] [d1 loss: 0.047877] [d2 loss: 0.047772]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 460/676] [D loss: -0.018245] [G loss: 0.085909] [d1 loss: 0.173237] [d2 loss: 0.191441]  [sq d1 d2: 0.000331]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 480/676] [D loss: -0.021125] [G loss: 0.102955] [d1 loss: 0.019746] [d2 loss: 0.019857]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 500/676] [D loss: -0.002234] [G loss: 0.123299] [d1 loss: 0.041638] [d2 loss: 0.052556]  [sq d1 d2: 0.000119]  [num0: 21.000000] [num1 43.000000]
[Epoch 272/500] [Batch 520/676] [D loss: 0.013760] [G loss: 0.098927] [d1 loss: 0.075699] [d2 loss: 0.067294]  [sq d1 d2: 0.000071]  [num0: 19.000000] [num1 45.000000]
[Epoch 272/500] [Batch 540/676] [D loss: -0.014781] [G loss: 0.126634] [d1 loss: 0.039612] [d2 loss: 0.050919]  [sq d1 d2: 0.000128]  [num0: 17.000000] [num1 47.000000]
[Epoch 272/500] [Batch 560/676] [D loss: -0.009562] [G loss: 0.128800] [d1 loss: 0.033254] [d2 loss: 0.053047]  [sq d1 d2: 0.000392]  [num0: 16.000000] [num1 48.000000]
[Epoch 272/500] [Batch 580/676] [D loss: -0.011939] [G loss: 0.097267] [d1 loss: 0.078978] [d2 loss: 0.071960]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 272/500] [Batch 600/676] [D loss: -0.000824] [G loss: 0.128769] [d1 loss: 0.043531] [d2 loss: 0.060684]  [sq d1 d2: 0.000294]  [num0: 16.000000] [num1 48.000000]
[Epoch 272/500] [Batch 620/676] [D loss: 0.006386] [G loss: 0.092421] [d1 loss: 0.049034] [d2 loss: 0.044826]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 272/500] [Batch 640/676] [D loss: -0.002470] [G loss: 0.015593] [d1 loss: 0.055520] [d2 loss: 0.049454]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 272/500] [Batch 660/676] [D loss: -0.005368] [G loss: -0.029220] [d1 loss: 0.073775] [d2 loss: 0.063661]  [sq d1 d2: 0.000102]  [num0: 13.000000] [num1 51.000000]
[Epoch 273/500] [Batch 0/676] [D loss: 0.001380] [G loss: -0.038172] [d1 loss: 0.087481] [d2 loss: 0.052482]  [sq d1 d2: 0.001225]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 20/676] [D loss: -0.017566] [G loss: -0.045612] [d1 loss: 0.065794] [d2 loss: 0.062130]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 273/500] [Batch 40/676] [D loss: -0.022558] [G loss: -0.095060] [d1 loss: 0.105066] [d2 loss: 0.073878]  [sq d1 d2: 0.000973]  [num0: 19.000000] [num1 45.000000]
[Epoch 273/500] [Batch 60/676] [D loss: -0.000795] [G loss: -0.128091] [d1 loss: 0.075161] [d2 loss: 0.081033]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 80/676] [D loss: -0.007334] [G loss: -0.114240] [d1 loss: 0.036820] [d2 loss: 0.045872]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 100/676] [D loss: -0.009684] [G loss: -0.152467] [d1 loss: 0.050036] [d2 loss: 0.062324]  [sq d1 d2: 0.000151]  [num0: 19.000000] [num1 45.000000]
[Epoch 273/500] [Batch 120/676] [D loss: -0.012203] [G loss: -0.166739] [d1 loss: 0.085710] [d2 loss: 0.101443]  [sq d1 d2: 0.000248]  [num0: 12.000000] [num1 52.000000]
[Epoch 273/500] [Batch 140/676] [D loss: -0.013897] [G loss: -0.160608] [d1 loss: 0.042222] [d2 loss: 0.051971]  [sq d1 d2: 0.000095]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 160/676] [D loss: 0.014769] [G loss: -0.146527] [d1 loss: 0.047816] [d2 loss: 0.043966]  [sq d1 d2: 0.000015]  [num0: 11.000000] [num1 53.000000]
[Epoch 273/500] [Batch 180/676] [D loss: 0.000206] [G loss: -0.111799] [d1 loss: 0.103235] [d2 loss: 0.072550]  [sq d1 d2: 0.000942]  [num0: 17.000000] [num1 47.000000]
[Epoch 273/500] [Batch 200/676] [D loss: 0.001593] [G loss: -0.117556] [d1 loss: 0.068685] [d2 loss: 0.072323]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 273/500] [Batch 220/676] [D loss: -0.002893] [G loss: -0.063177] [d1 loss: 0.123871] [d2 loss: 0.130608]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 240/676] [D loss: -0.001389] [G loss: -0.055126] [d1 loss: 0.040089] [d2 loss: 0.037592]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 260/676] [D loss: -0.002638] [G loss: -0.037108] [d1 loss: 0.043257] [d2 loss: 0.047418]  [sq d1 d2: 0.000017]  [num0: 12.000000] [num1 52.000000]
[Epoch 273/500] [Batch 280/676] [D loss: -0.011316] [G loss: -0.013617] [d1 loss: 0.091682] [d2 loss: 0.082653]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 300/676] [D loss: -0.012773] [G loss: 0.046527] [d1 loss: 0.089986] [d2 loss: 0.118123]  [sq d1 d2: 0.000792]  [num0: 15.000000] [num1 49.000000]
[Epoch 273/500] [Batch 320/676] [D loss: -0.019940] [G loss: 0.030309] [d1 loss: 0.089549] [d2 loss: 0.062930]  [sq d1 d2: 0.000709]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 340/676] [D loss: 0.019324] [G loss: 0.048205] [d1 loss: 0.034152] [d2 loss: 0.051081]  [sq d1 d2: 0.000287]  [num0: 18.000000] [num1 46.000000]
[Epoch 273/500] [Batch 360/676] [D loss: -0.008752] [G loss: 0.048024] [d1 loss: 0.053070] [d2 loss: 0.062057]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 273/500] [Batch 380/676] [D loss: -0.004888] [G loss: 0.017844] [d1 loss: 0.027371] [d2 loss: 0.022789]  [sq d1 d2: 0.000021]  [num0: 20.000000] [num1 44.000000]

[Epoch 273/500] [Batch 400/676] [D loss: 0.001069] [G loss: -0.011329] [d1 loss: 0.068217] [d2 loss: 0.085115]  [sq d1 d2: 0.000286]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 420/676] [D loss: -0.005780] [G loss: -0.004753] [d1 loss: 0.142907] [d2 loss: 0.135095]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 273/500] [Batch 440/676] [D loss: -0.006787] [G loss: 0.001594] [d1 loss: 0.198245] [d2 loss: 0.197999]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 273/500] [Batch 460/676] [D loss: -0.007057] [G loss: -0.036473] [d1 loss: 0.043909] [d2 loss: 0.042323]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 273/500] [Batch 480/676] [D loss: -0.000702] [G loss: -0.030777] [d1 loss: 0.007113] [d2 loss: 0.010546]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 273/500] [Batch 500/676] [D loss: -0.005795] [G loss: -0.043796] [d1 loss: 0.025625] [d2 loss: 0.030602]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 273/500] [Batch 520/676] [D loss: -0.010685] [G loss: -0.028818] [d1 loss: 0.051860] [d2 loss: 0.046386]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 273/500] [Batch 540/676] [D loss: -0.011147] [G loss: -0.058468] [d1 loss: 0.031162] [d2 loss: 0.041045]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 273/500] [Batch 560/676] [D loss: -0.015865] [G loss: -0.083273] [d1 loss: 0.037588] [d2 loss: 0.039276]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 580/676] [D loss: -0.007129] [G loss: -0.097128] [d1 loss: 0.033948] [d2 loss: 0.030507]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 273/500] [Batch 600/676] [D loss: -0.002138] [G loss: -0.089520] [d1 loss: 0.044450] [d2 loss: 0.032380]  [sq d1 d2: 0.000146]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 620/676] [D loss: -0.027319] [G loss: -0.106430] [d1 loss: 0.071305] [d2 loss: 0.077424]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 273/500] [Batch 640/676] [D loss: -0.006676] [G loss: -0.070344] [d1 loss: 0.076633] [d2 loss: 0.083406]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 273/500] [Batch 660/676] [D loss: -0.006799] [G loss: -0.045114] [d1 loss: 0.044661] [d2 loss: 0.059566]  [sq d1 d2: 0.000222]  [num0: 12.000000] [num1 52.000000]
[Epoch 274/500] [Batch 0/676] [D loss: -0.007398] [G loss: -0.026081] [d1 loss: 0.047339] [d2 loss: 0.035188]  [sq d1 d2: 0.000148]  [num0: 17.000000] [num1 47.000000]
[Epoch 274/500] [Batch 20/676] [D loss: -0.006795] [G loss: -0.015755] [d1 loss: 0.035248] [d2 loss: 0.033774]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 40/676] [D loss: 0.005139] [G loss: 0.009063] [d1 loss: 0.025684] [d2 loss: 0.024106]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 60/676] [D loss: -0.007347] [G loss: 0.060395] [d1 loss: 0.052978] [d2 loss: 0.071982]  [sq d1 d2: 0.000361]  [num0: 14.000000] [num1 50.000000]
[Epoch 274/500] [Batch 80/676] [D loss: -0.008823] [G loss: 0.104219] [d1 loss: 0.062412] [d2 loss: 0.051952]  [sq d1 d2: 0.000109]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 100/676] [D loss: -0.006142] [G loss: 0.113806] [d1 loss: 0.068511] [d2 loss: 0.071572]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 120/676] [D loss: -0.005423] [G loss: 0.140101] [d1 loss: 0.063571] [d2 loss: 0.064767]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 274/500] [Batch 140/676] [D loss: -0.004540] [G loss: 0.171644] [d1 loss: 0.138136] [d2 loss: 0.116828]  [sq d1 d2: 0.000454]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 160/676] [D loss: -0.003368] [G loss: 0.162772] [d1 loss: 0.040632] [d2 loss: 0.039057]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 274/500] [Batch 180/676] [D loss: -0.009707] [G loss: 0.090911] [d1 loss: 0.015289] [d2 loss: 0.020371]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 274/500] [Batch 200/676] [D loss: -0.002683] [G loss: 0.037448] [d1 loss: 0.049368] [d2 loss: 0.051726]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 220/676] [D loss: -0.007084] [G loss: 0.002148] [d1 loss: 0.062881] [d2 loss: 0.056185]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 240/676] [D loss: -0.010477] [G loss: 0.029986] [d1 loss: 0.063877] [d2 loss: 0.057670]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 260/676] [D loss: -0.005533] [G loss: 0.001723] [d1 loss: 0.072732] [d2 loss: 0.063993]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 280/676] [D loss: -0.011614] [G loss: 0.043835] [d1 loss: 0.054090] [d2 loss: 0.058058]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 300/676] [D loss: -0.007976] [G loss: 0.029721] [d1 loss: 0.077956] [d2 loss: 0.064540]  [sq d1 d2: 0.000180]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 320/676] [D loss: -0.010438] [G loss: -0.000836] [d1 loss: 0.107771] [d2 loss: 0.098044]  [sq d1 d2: 0.000095]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 340/676] [D loss: -0.005052] [G loss: 0.017877] [d1 loss: 0.043532] [d2 loss: 0.036794]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 274/500] [Batch 360/676] [D loss: -0.010600] [G loss: -0.011233] [d1 loss: 0.085745] [d2 loss: 0.102541]  [sq d1 d2: 0.000282]  [num0: 13.000000] [num1 51.000000]
[Epoch 274/500] [Batch 380/676] [D loss: 0.000569] [G loss: 0.019439] [d1 loss: 0.010370] [d2 loss: 0.013761]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 274/500] [Batch 400/676] [D loss: -0.007116] [G loss: -0.048666] [d1 loss: 0.076225] [d2 loss: 0.090213]  [sq d1 d2: 0.000196]  [num0: 14.000000] [num1 50.000000]
[Epoch 274/500] [Batch 420/676] [D loss: -0.012451] [G loss: -0.065675] [d1 loss: 0.035062] [d2 loss: 0.031749]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 274/500] [Batch 440/676] [D loss: -0.010750] [G loss: -0.036062] [d1 loss: 0.092498] [d2 loss: 0.084751]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 274/500] [Batch 460/676] [D loss: -0.001957] [G loss: -0.021635] [d1 loss: 0.070619] [d2 loss: 0.075911]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 480/676] [D loss: -0.015024] [G loss: -0.052161] [d1 loss: 0.107320] [d2 loss: 0.110360]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 500/676] [D loss: -0.008093] [G loss: -0.017550] [d1 loss: 0.088138] [d2 loss: 0.074255]  [sq d1 d2: 0.000193]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 520/676] [D loss: -0.010323] [G loss: -0.013606] [d1 loss: 0.105346] [d2 loss: 0.132663]  [sq d1 d2: 0.000746]  [num0: 14.000000] [num1 50.000000]
[Epoch 274/500] [Batch 540/676] [D loss: -0.001757] [G loss: -0.057502] [d1 loss: 0.069640] [d2 loss: 0.067605]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 274/500] [Batch 560/676] [D loss: -0.001323] [G loss: -0.084576] [d1 loss: 0.024046] [d2 loss: 0.018553]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 274/500] [Batch 580/676] [D loss: -0.011163] [G loss: -0.086452] [d1 loss: 0.078608] [d2 loss: 0.068038]  [sq d1 d2: 0.000112]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 600/676] [D loss: -0.008333] [G loss: -0.069948] [d1 loss: 0.031726] [d2 loss: 0.029568]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 274/500] [Batch 620/676] [D loss: -0.013050] [G loss: -0.102322] [d1 loss: 0.026947] [d2 loss: 0.028278]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 274/500] [Batch 640/676] [D loss: -0.009603] [G loss: -0.101619] [d1 loss: 0.147510] [d2 loss: 0.101593]  [sq d1 d2: 0.002108]  [num0: 17.000000] [num1 47.000000]
[Epoch 274/500] [Batch 660/676] [D loss: -0.000441] [G loss: -0.087092] [d1 loss: 0.059268] [d2 loss: 0.046781]  [sq d1 d2: 0.000156]  [num0: 18.000000] [num1 46.000000]
[Epoch 275/500] [Batch 0/676] [D loss: -0.007069] [G loss: -0.123012] [d1 loss: 0.035549] [d2 loss: 0.043961]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 20/676] [D loss: -0.005310] [G loss: -0.097959] [d1 loss: 0.047287] [d2 loss: 0.047686]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 40/676] [D loss: -0.001297] [G loss: -0.132581] [d1 loss: 0.040161] [d2 loss: 0.028492]  [sq d1 d2: 0.000136]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 60/676] [D loss: -0.014910] [G loss: -0.116849] [d1 loss: 0.027897] [d2 loss: 0.020558]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]

[Epoch 275/500] [Batch 80/676] [D loss: -0.009089] [G loss: -0.104495] [d1 loss: 0.089182] [d2 loss: 0.080177]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 275/500] [Batch 100/676] [D loss: -0.004830] [G loss: -0.104160] [d1 loss: 0.055822] [d2 loss: 0.053517]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 275/500] [Batch 120/676] [D loss: -0.014465] [G loss: -0.136053] [d1 loss: 0.081897] [d2 loss: 0.090465]  [sq d1 d2: 0.000073]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 140/676] [D loss: -0.013932] [G loss: -0.137852] [d1 loss: 0.100409] [d2 loss: 0.075424]  [sq d1 d2: 0.000624]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 160/676] [D loss: -0.006869] [G loss: -0.133504] [d1 loss: 0.111862] [d2 loss: 0.095761]  [sq d1 d2: 0.000259]  [num0: 19.000000] [num1 45.000000]
[Epoch 275/500] [Batch 180/676] [D loss: -0.006204] [G loss: -0.124630] [d1 loss: 0.061646] [d2 loss: 0.052255]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 200/676] [D loss: -0.003880] [G loss: -0.096468] [d1 loss: 0.022233] [d2 loss: 0.026837]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 220/676] [D loss: -0.006722] [G loss: -0.082023] [d1 loss: 0.056814] [d2 loss: 0.056176]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 240/676] [D loss: -0.004667] [G loss: -0.088201] [d1 loss: 0.029181] [d2 loss: 0.028315]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 260/676] [D loss: -0.003989] [G loss: -0.061053] [d1 loss: 0.056915] [d2 loss: 0.066964]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 280/676] [D loss: -0.003438] [G loss: -0.068433] [d1 loss: 0.053801] [d2 loss: 0.035019]  [sq d1 d2: 0.000353]  [num0: 14.000000] [num1 50.000000]
[Epoch 275/500] [Batch 300/676] [D loss: -0.004679] [G loss: -0.064701] [d1 loss: 0.055587] [d2 loss: 0.044871]  [sq d1 d2: 0.000115]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 320/676] [D loss: 0.001726] [G loss: -0.082583] [d1 loss: 0.062155] [d2 loss: 0.065015]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 340/676] [D loss: -0.007991] [G loss: -0.049399] [d1 loss: 0.113652] [d2 loss: 0.122617]  [sq d1 d2: 0.000080]  [num0: 10.000000] [num1 54.000000]
[Epoch 275/500] [Batch 360/676] [D loss: -0.005241] [G loss: -0.039198] [d1 loss: 0.039499] [d2 loss: 0.039505]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 275/500] [Batch 380/676] [D loss: -0.001666] [G loss: -0.044381] [d1 loss: 0.047117] [d2 loss: 0.058606]  [sq d1 d2: 0.000132]  [num0: 12.000000] [num1 52.000000]
[Epoch 275/500] [Batch 400/676] [D loss: -0.009493] [G loss: -0.027962] [d1 loss: 0.082555] [d2 loss: 0.088457]  [sq d1 d2: 0.000035]  [num0: 12.000000] [num1 52.000000]
[Epoch 275/500] [Batch 420/676] [D loss: -0.012957] [G loss: 0.007870] [d1 loss: 0.045210] [d2 loss: 0.042490]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 440/676] [D loss: -0.011753] [G loss: -0.017549] [d1 loss: 0.068591] [d2 loss: 0.071938]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 460/676] [D loss: -0.013152] [G loss: 0.013871] [d1 loss: 0.105152] [d2 loss: 0.119691]  [sq d1 d2: 0.000211]  [num0: 13.000000] [num1 51.000000]
[Epoch 275/500] [Batch 480/676] [D loss: -0.001121] [G loss: 0.044236] [d1 loss: 0.060928] [d2 loss: 0.078983]  [sq d1 d2: 0.000326]  [num0: 12.000000] [num1 52.000000]
[Epoch 275/500] [Batch 500/676] [D loss: -0.008874] [G loss: 0.046336] [d1 loss: 0.052437] [d2 loss: 0.046497]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 520/676] [D loss: -0.002623] [G loss: 0.017985] [d1 loss: 0.747951] [d2 loss: 0.610004]  [sq d1 d2: 0.019029]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 540/676] [D loss: -0.007832] [G loss: 0.041148] [d1 loss: 0.027891] [d2 loss: 0.040486]  [sq d1 d2: 0.000159]  [num0: 14.000000] [num1 50.000000]
[Epoch 275/500] [Batch 560/676] [D loss: -0.006238] [G loss: 0.014522] [d1 loss: 0.144549] [d2 loss: 0.125540]  [sq d1 d2: 0.000361]  [num0: 15.000000] [num1 49.000000]
[Epoch 275/500] [Batch 580/676] [D loss: -0.008589] [G loss: 0.032770] [d1 loss: 0.048179] [d2 loss: 0.048242]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 275/500] [Batch 600/676] [D loss: -0.007661] [G loss: 0.006272] [d1 loss: 0.029819] [d2 loss: 0.027848]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 620/676] [D loss: -0.014632] [G loss: 0.038619] [d1 loss: 0.062245] [d2 loss: 0.070969]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 275/500] [Batch 640/676] [D loss: -0.006296] [G loss: 0.044677] [d1 loss: 0.040014] [d2 loss: 0.034178]  [sq d1 d2: 0.000034]  [num0: 19.000000] [num1 45.000000]
[Epoch 275/500] [Batch 660/676] [D loss: -0.014060] [G loss: 0.080312] [d1 loss: 0.034674] [d2 loss: 0.032251]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 0/676] [D loss: 0.001373] [G loss: 0.083607] [d1 loss: 0.072410] [d2 loss: 0.082724]  [sq d1 d2: 0.000106]  [num0: 20.000000] [num1 44.000000]
[Epoch 276/500] [Batch 20/676] [D loss: -0.001410] [G loss: 0.041302] [d1 loss: 0.097695] [d2 loss: 0.132794]  [sq d1 d2: 0.001232]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 40/676] [D loss: 0.000386] [G loss: 0.033385] [d1 loss: 0.081261] [d2 loss: 0.064281]  [sq d1 d2: 0.000288]  [num0: 14.000000] [num1 50.000000]
[Epoch 276/500] [Batch 60/676] [D loss: -0.006050] [G loss: 0.009898] [d1 loss: 0.093956] [d2 loss: 0.099475]  [sq d1 d2: 0.000030]  [num0: 20.000000] [num1 44.000000]
[Epoch 276/500] [Batch 80/676] [D loss: -0.003103] [G loss: 0.032034] [d1 loss: 0.069654] [d2 loss: 0.067138]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 276/500] [Batch 100/676] [D loss: -0.009266] [G loss: 0.011398] [d1 loss: 0.016404] [d2 loss: 0.018941]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 120/676] [D loss: -0.017390] [G loss: 0.042154] [d1 loss: 0.029317] [d2 loss: 0.032850]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 276/500] [Batch 140/676] [D loss: -0.018815] [G loss: 0.062017] [d1 loss: 0.046065] [d2 loss: 0.043397]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 276/500] [Batch 160/676] [D loss: 0.002515] [G loss: 0.067259] [d1 loss: 0.045236] [d2 loss: 0.043325]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 180/676] [D loss: -0.010148] [G loss: 0.060930] [d1 loss: 0.161222] [d2 loss: 0.149310]  [sq d1 d2: 0.000142]  [num0: 15.000000] [num1 49.000000]
[Epoch 276/500] [Batch 200/676] [D loss: -0.008992] [G loss: 0.075563] [d1 loss: 0.099044] [d2 loss: 0.111459]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 276/500] [Batch 220/676] [D loss: 0.007632] [G loss: 0.115365] [d1 loss: 0.060004] [d2 loss: 0.097008]  [sq d1 d2: 0.001369]  [num0: 19.000000] [num1 45.000000]
[Epoch 276/500] [Batch 240/676] [D loss: -0.019107] [G loss: 0.136216] [d1 loss: 0.072656] [d2 loss: 0.042157]  [sq d1 d2: 0.000930]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 260/676] [D loss: -0.000184] [G loss: 0.099123] [d1 loss: 0.089913] [d2 loss: 0.072538]  [sq d1 d2: 0.000302]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 280/676] [D loss: -0.007442] [G loss: 0.143937] [d1 loss: 0.063793] [d2 loss: 0.063102]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 300/676] [D loss: 0.003132] [G loss: 0.131542] [d1 loss: 0.030934] [d2 loss: 0.030795]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 320/676] [D loss: -0.019501] [G loss: 0.072022] [d1 loss: 0.092672] [d2 loss: 0.080263]  [sq d1 d2: 0.000154]  [num0: 20.000000] [num1 44.000000]
[Epoch 276/500] [Batch 340/676] [D loss: -0.013273] [G loss: 0.093332] [d1 loss: 0.077266] [d2 loss: 0.064339]  [sq d1 d2: 0.000167]  [num0: 19.000000] [num1 45.000000]
[Epoch 276/500] [Batch 360/676] [D loss: -0.006523] [G loss: 0.077824] [d1 loss: 0.189875] [d2 loss: 0.208637]  [sq d1 d2: 0.000352]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 380/676] [D loss: -0.022799] [G loss: 0.023818] [d1 loss: 0.064793] [d2 loss: 0.061311]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 400/676] [D loss: -0.001783] [G loss: -0.023412] [d1 loss: 0.082061] [d2 loss: 0.084188]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 420/676] [D loss: 0.006063] [G loss: -0.076687] [d1 loss: 0.155623] [d2 loss: 0.110052]  [sq d1 d2: 0.002077]  [num0: 15.000000] [num1 49.000000]

[Epoch 276/500] [Batch 440/676] [D loss: -0.012750] [G loss: -0.116233] [d1 loss: 0.105622] [d2 loss: 0.092075]  [sq d1 d2: 0.000184]  [num0: 17.000000] [num1 47.000000]
[Epoch 276/500] [Batch 460/676] [D loss: -0.004054] [G loss: -0.105047] [d1 loss: 0.038250] [d2 loss: 0.035363]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 276/500] [Batch 480/676] [D loss: -0.005651] [G loss: -0.172702] [d1 loss: 0.092596] [d2 loss: 0.081980]  [sq d1 d2: 0.000113]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 500/676] [D loss: -0.013425] [G loss: -0.129959] [d1 loss: 0.058587] [d2 loss: 0.059310]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 276/500] [Batch 520/676] [D loss: -0.017470] [G loss: -0.135813] [d1 loss: 0.031291] [d2 loss: 0.039058]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 276/500] [Batch 540/676] [D loss: -0.026368] [G loss: -0.138208] [d1 loss: 0.018877] [d2 loss: 0.018121]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 276/500] [Batch 560/676] [D loss: -0.011309] [G loss: -0.151010] [d1 loss: 0.030325] [d2 loss: 0.035329]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 276/500] [Batch 580/676] [D loss: -0.006894] [G loss: -0.149623] [d1 loss: 0.085547] [d2 loss: 0.083168]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 276/500] [Batch 600/676] [D loss: -0.014571] [G loss: -0.167220] [d1 loss: 0.057753] [d2 loss: 0.060841]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 276/500] [Batch 620/676] [D loss: -0.003393] [G loss: -0.195900] [d1 loss: 0.042760] [d2 loss: 0.052718]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 276/500] [Batch 640/676] [D loss: 0.016979] [G loss: -0.191590] [d1 loss: 0.139528] [d2 loss: 0.114869]  [sq d1 d2: 0.000608]  [num0: 14.000000] [num1 50.000000]
[Epoch 276/500] [Batch 660/676] [D loss: 0.005544] [G loss: -0.151160] [d1 loss: 0.040925] [d2 loss: 0.037150]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 277/500] [Batch 0/676] [D loss: -0.003176] [G loss: -0.116561] [d1 loss: 0.026075] [d2 loss: 0.027679]  [sq d1 d2: 0.000003]  [num0: 20.000000] [num1 44.000000]
[Epoch 277/500] [Batch 20/676] [D loss: 0.001125] [G loss: -0.112199] [d1 loss: 0.044450] [d2 loss: 0.043346]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 40/676] [D loss: 0.000894] [G loss: -0.069631] [d1 loss: 0.028588] [d2 loss: 0.016768]  [sq d1 d2: 0.000140]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 60/676] [D loss: -0.006628] [G loss: -0.037176] [d1 loss: 0.036349] [d2 loss: 0.043795]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 80/676] [D loss: -0.009272] [G loss: 0.007281] [d1 loss: 0.109112] [d2 loss: 0.094347]  [sq d1 d2: 0.000218]  [num0: 13.000000] [num1 51.000000]
[Epoch 277/500] [Batch 100/676] [D loss: -0.012792] [G loss: 0.053715] [d1 loss: 0.075985] [d2 loss: 0.071991]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 277/500] [Batch 120/676] [D loss: -0.013152] [G loss: 0.085190] [d1 loss: 0.115375] [d2 loss: 0.077860]  [sq d1 d2: 0.001407]  [num0: 14.000000] [num1 50.000000]
[Epoch 277/500] [Batch 140/676] [D loss: -0.018998] [G loss: 0.129205] [d1 loss: 0.079988] [d2 loss: 0.068137]  [sq d1 d2: 0.000140]  [num0: 16.000000] [num1 48.000000]
[Epoch 277/500] [Batch 160/676] [D loss: -0.010983] [G loss: 0.155798] [d1 loss: 0.049327] [d2 loss: 0.041417]  [sq d1 d2: 0.000063]  [num0: 20.000000] [num1 44.000000]
[Epoch 277/500] [Batch 180/676] [D loss: -0.002659] [G loss: 0.132523] [d1 loss: 0.057253] [d2 loss: 0.058202]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 277/500] [Batch 200/676] [D loss: -0.012794] [G loss: 0.147308] [d1 loss: 0.188502] [d2 loss: 0.164924]  [sq d1 d2: 0.000556]  [num0: 15.000000] [num1 49.000000]
[Epoch 277/500] [Batch 220/676] [D loss: -0.006923] [G loss: 0.146414] [d1 loss: 0.025830] [d2 loss: 0.021563]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 277/500] [Batch 240/676] [D loss: -0.018571] [G loss: 0.163708] [d1 loss: 0.065583] [d2 loss: 0.054204]  [sq d1 d2: 0.000129]  [num0: 18.000000] [num1 46.000000]
[Epoch 277/500] [Batch 260/676] [D loss: -0.000537] [G loss: 0.134236] [d1 loss: 0.075242] [d2 loss: 0.067542]  [sq d1 d2: 0.000059]  [num0: 19.000000] [num1 45.000000]
[Epoch 277/500] [Batch 280/676] [D loss: 0.012731] [G loss: 0.071601] [d1 loss: 0.128329] [d2 loss: 0.147654]  [sq d1 d2: 0.000373]  [num0: 19.000000] [num1 45.000000]
[Epoch 277/500] [Batch 300/676] [D loss: -0.013119] [G loss: -0.017933] [d1 loss: 0.044817] [d2 loss: 0.044936]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 320/676] [D loss: -0.012538] [G loss: -0.053332] [d1 loss: 0.104004] [d2 loss: 0.087769]  [sq d1 d2: 0.000264]  [num0: 15.000000] [num1 49.000000]
[Epoch 277/500] [Batch 340/676] [D loss: -0.016166] [G loss: -0.083281] [d1 loss: 0.051341] [d2 loss: 0.053305]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 360/676] [D loss: -0.022303] [G loss: -0.086463] [d1 loss: 0.048581] [d2 loss: 0.059541]  [sq d1 d2: 0.000120]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 380/676] [D loss: -0.005707] [G loss: -0.114450] [d1 loss: 0.039717] [d2 loss: 0.044748]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 277/500] [Batch 400/676] [D loss: -0.005467] [G loss: -0.097984] [d1 loss: 0.040882] [d2 loss: 0.051159]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]
[Epoch 277/500] [Batch 420/676] [D loss: -0.023719] [G loss: -0.157387] [d1 loss: 0.109119] [d2 loss: 0.105459]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 440/676] [D loss: -0.021230] [G loss: -0.179861] [d1 loss: 0.066382] [d2 loss: 0.068058]  [sq d1 d2: 0.000003]  [num0: 21.000000] [num1 43.000000]
[Epoch 277/500] [Batch 460/676] [D loss: -0.005963] [G loss: -0.182277] [d1 loss: 0.098614] [d2 loss: 0.101835]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 277/500] [Batch 480/676] [D loss: 0.036906] [G loss: -0.178161] [d1 loss: 0.133952] [d2 loss: 0.135734]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 277/500] [Batch 500/676] [D loss: -0.011021] [G loss: -0.134466] [d1 loss: 0.032912] [d2 loss: 0.028697]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 277/500] [Batch 520/676] [D loss: 0.000098] [G loss: -0.150517] [d1 loss: 0.078550] [d2 loss: 0.068959]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 277/500] [Batch 540/676] [D loss: -0.012170] [G loss: -0.162279] [d1 loss: 0.128190] [d2 loss: 0.135226]  [sq d1 d2: 0.000050]  [num0: 21.000000] [num1 43.000000]
[Epoch 277/500] [Batch 560/676] [D loss: -0.015658] [G loss: -0.147687] [d1 loss: 0.057213] [d2 loss: 0.064214]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 277/500] [Batch 580/676] [D loss: -0.033004] [G loss: -0.134311] [d1 loss: 0.055998] [d2 loss: 0.055146]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 277/500] [Batch 600/676] [D loss: -0.028212] [G loss: -0.130255] [d1 loss: 0.174261] [d2 loss: 0.171025]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 277/500] [Batch 620/676] [D loss: -0.013212] [G loss: -0.144364] [d1 loss: 0.041563] [d2 loss: 0.023173]  [sq d1 d2: 0.000338]  [num0: 15.000000] [num1 49.000000]
[Epoch 277/500] [Batch 640/676] [D loss: -0.009416] [G loss: -0.143802] [d1 loss: 0.070996] [d2 loss: 0.070967]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 277/500] [Batch 660/676] [D loss: -0.009944] [G loss: -0.141922] [d1 loss: 0.053899] [d2 loss: 0.049963]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 0/676] [D loss: -0.010399] [G loss: -0.118521] [d1 loss: 0.046215] [d2 loss: 0.078601]  [sq d1 d2: 0.001049]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 20/676] [D loss: 0.006709] [G loss: -0.104608] [d1 loss: 0.038453] [d2 loss: 0.049749]  [sq d1 d2: 0.000128]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 40/676] [D loss: -0.006279] [G loss: -0.104684] [d1 loss: 0.045249] [d2 loss: 0.042210]  [sq d1 d2: 0.000009]  [num0: 12.000000] [num1 52.000000]
[Epoch 278/500] [Batch 60/676] [D loss: 0.002187] [G loss: -0.087512] [d1 loss: 0.022033] [d2 loss: 0.042157]  [sq d1 d2: 0.000405]  [num0: 19.000000] [num1 45.000000]
[Epoch 278/500] [Batch 80/676] [D loss: -0.000852] [G loss: -0.093550] [d1 loss: 0.042152] [d2 loss: 0.030021]  [sq d1 d2: 0.000147]  [num0: 17.000000] [num1 47.000000]
[Epoch 278/500] [Batch 100/676] [D loss: -0.001684] [G loss: -0.085334] [d1 loss: 0.021372] [d2 loss: 0.025333]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]

[Epoch 278/500] [Batch 120/676] [D loss: -0.007234] [G loss: -0.116077] [d1 loss: 0.010238] [d2 loss: 0.010415]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 278/500] [Batch 140/676] [D loss: -0.020910] [G loss: -0.109182] [d1 loss: 0.066278] [d2 loss: 0.084164]  [sq d1 d2: 0.000320]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 160/676] [D loss: -0.014290] [G loss: -0.114127] [d1 loss: 0.062218] [d2 loss: 0.077416]  [sq d1 d2: 0.000231]  [num0: 20.000000] [num1 44.000000]
[Epoch 278/500] [Batch 180/676] [D loss: -0.013266] [G loss: -0.119860] [d1 loss: 0.020914] [d2 loss: 0.021388]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 278/500] [Batch 200/676] [D loss: -0.005946] [G loss: -0.144035] [d1 loss: 0.023957] [d2 loss: 0.017069]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 278/500] [Batch 220/676] [D loss: -0.000974] [G loss: -0.160289] [d1 loss: 0.029219] [d2 loss: 0.037312]  [sq d1 d2: 0.000066]  [num0: 18.000000] [num1 46.000000]
[Epoch 278/500] [Batch 240/676] [D loss: -0.023731] [G loss: -0.146281] [d1 loss: 0.042767] [d2 loss: 0.042120]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 278/500] [Batch 260/676] [D loss: 0.002685] [G loss: -0.139388] [d1 loss: 0.067681] [d2 loss: 0.072847]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 280/676] [D loss: 0.010398] [G loss: -0.102240] [d1 loss: 0.062481] [d2 loss: 0.071183]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 278/500] [Batch 300/676] [D loss: 0.001795] [G loss: -0.113230] [d1 loss: 0.047362] [d2 loss: 0.054398]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 278/500] [Batch 320/676] [D loss: -0.007943] [G loss: -0.075440] [d1 loss: 0.113434] [d2 loss: 0.089096]  [sq d1 d2: 0.000592]  [num0: 17.000000] [num1 47.000000]
[Epoch 278/500] [Batch 340/676] [D loss: -0.000903] [G loss: -0.073831] [d1 loss: 0.021141] [d2 loss: 0.024311]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 278/500] [Batch 360/676] [D loss: -0.006207] [G loss: -0.070805] [d1 loss: 0.087776] [d2 loss: 0.080570]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 380/676] [D loss: -0.005645] [G loss: -0.077763] [d1 loss: 0.026665] [d2 loss: 0.020517]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 278/500] [Batch 400/676] [D loss: -0.017743] [G loss: -0.080091] [d1 loss: 0.036876] [d2 loss: 0.039585]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 420/676] [D loss: -0.010608] [G loss: -0.085891] [d1 loss: 0.046883] [d2 loss: 0.047212]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 278/500] [Batch 440/676] [D loss: -0.024095] [G loss: -0.079091] [d1 loss: 0.051369] [d2 loss: 0.055013]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 460/676] [D loss: -0.028814] [G loss: -0.057733] [d1 loss: 0.061872] [d2 loss: 0.064296]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 278/500] [Batch 480/676] [D loss: -0.005734] [G loss: -0.024945] [d1 loss: 0.047731] [d2 loss: 0.054499]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 500/676] [D loss: 0.001145] [G loss: -0.065430] [d1 loss: 0.079762] [d2 loss: 0.072032]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 278/500] [Batch 520/676] [D loss: -0.006525] [G loss: -0.036847] [d1 loss: 0.041673] [d2 loss: 0.037478]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 540/676] [D loss: -0.015183] [G loss: -0.060934] [d1 loss: 0.057850] [d2 loss: 0.068328]  [sq d1 d2: 0.000110]  [num0: 11.000000] [num1 53.000000]
[Epoch 278/500] [Batch 560/676] [D loss: -0.005553] [G loss: -0.033312] [d1 loss: 0.049244] [d2 loss: 0.054044]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 278/500] [Batch 580/676] [D loss: -0.014860] [G loss: -0.040839] [d1 loss: 0.078101] [d2 loss: 0.084320]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 278/500] [Batch 600/676] [D loss: -0.017456] [G loss: -0.076507] [d1 loss: 0.055516] [d2 loss: 0.060033]  [sq d1 d2: 0.000020]  [num0: 19.000000] [num1 45.000000]
[Epoch 278/500] [Batch 620/676] [D loss: -0.003551] [G loss: -0.094694] [d1 loss: 0.059168] [d2 loss: 0.041855]  [sq d1 d2: 0.000300]  [num0: 19.000000] [num1 45.000000]
[Epoch 278/500] [Batch 640/676] [D loss: -0.033345] [G loss: -0.141798] [d1 loss: 0.023988] [d2 loss: 0.025766]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 278/500] [Batch 660/676] [D loss: -0.040452] [G loss: -0.145447] [d1 loss: 0.107452] [d2 loss: 0.106527]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 279/500] [Batch 0/676] [D loss: 0.012164] [G loss: -0.145331] [d1 loss: 0.035271] [d2 loss: 0.058587]  [sq d1 d2: 0.000544]  [num0: 17.000000] [num1 47.000000]
[Epoch 279/500] [Batch 20/676] [D loss: 0.004560] [G loss: -0.131757] [d1 loss: 0.049852] [d2 loss: 0.070113]  [sq d1 d2: 0.000410]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 40/676] [D loss: -0.002812] [G loss: -0.152883] [d1 loss: 0.047288] [d2 loss: 0.048435]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 279/500] [Batch 60/676] [D loss: 0.006609] [G loss: -0.106125] [d1 loss: 0.139255] [d2 loss: 0.154968]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 80/676] [D loss: -0.000229] [G loss: -0.093420] [d1 loss: 0.128306] [d2 loss: 0.098258]  [sq d1 d2: 0.000903]  [num0: 18.000000] [num1 46.000000]
[Epoch 279/500] [Batch 100/676] [D loss: -0.002980] [G loss: -0.086728] [d1 loss: 0.059519] [d2 loss: 0.053529]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 279/500] [Batch 120/676] [D loss: -0.010942] [G loss: -0.069157] [d1 loss: 0.096312] [d2 loss: 0.065101]  [sq d1 d2: 0.000974]  [num0: 18.000000] [num1 46.000000]
[Epoch 279/500] [Batch 140/676] [D loss: -0.014121] [G loss: -0.065452] [d1 loss: 0.043961] [d2 loss: 0.056293]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 160/676] [D loss: -0.016927] [G loss: -0.082577] [d1 loss: 0.068120] [d2 loss: 0.083330]  [sq d1 d2: 0.000231]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 180/676] [D loss: -0.014149] [G loss: -0.116453] [d1 loss: 0.036810] [d2 loss: 0.028724]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 200/676] [D loss: -0.013822] [G loss: -0.101422] [d1 loss: 0.012906] [d2 loss: 0.011606]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 220/676] [D loss: -0.027615] [G loss: -0.086561] [d1 loss: 0.116417] [d2 loss: 0.150443]  [sq d1 d2: 0.001158]  [num0: 19.000000] [num1 45.000000]
[Epoch 279/500] [Batch 240/676] [D loss: -0.021415] [G loss: -0.118131] [d1 loss: 0.046681] [d2 loss: 0.043788]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 260/676] [D loss: -0.014929] [G loss: -0.110771] [d1 loss: 0.114355] [d2 loss: 0.103571]  [sq d1 d2: 0.000116]  [num0: 14.000000] [num1 50.000000]
[Epoch 279/500] [Batch 280/676] [D loss: -0.009684] [G loss: -0.125381] [d1 loss: 0.083350] [d2 loss: 0.083851]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 279/500] [Batch 300/676] [D loss: -0.004208] [G loss: -0.090718] [d1 loss: 0.106402] [d2 loss: 0.117253]  [sq d1 d2: 0.000118]  [num0: 19.000000] [num1 45.000000]
[Epoch 279/500] [Batch 320/676] [D loss: -0.014201] [G loss: -0.094900] [d1 loss: 0.017961] [d2 loss: 0.018605]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 340/676] [D loss: -0.000634] [G loss: -0.070500] [d1 loss: 0.047491] [d2 loss: 0.043454]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 360/676] [D loss: -0.002873] [G loss: -0.106490] [d1 loss: 0.039047] [d2 loss: 0.038292]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 380/676] [D loss: -0.016854] [G loss: -0.111622] [d1 loss: 0.078699] [d2 loss: 0.080251]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 400/676] [D loss: -0.014314] [G loss: -0.111587] [d1 loss: 0.074384] [d2 loss: 0.064807]  [sq d1 d2: 0.000092]  [num0: 13.000000] [num1 51.000000]
[Epoch 279/500] [Batch 420/676] [D loss: -0.008082] [G loss: -0.123579] [d1 loss: 0.083144] [d2 loss: 0.081588]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 279/500] [Batch 440/676] [D loss: -0.026853] [G loss: -0.117748] [d1 loss: 0.081016] [d2 loss: 0.110668]  [sq d1 d2: 0.000879]  [num0: 13.000000] [num1 51.000000]
[Epoch 279/500] [Batch 460/676] [D loss: -0.017035] [G loss: -0.125868] [d1 loss: 0.046650] [d2 loss: 0.048306]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]

[Epoch 279/500] [Batch 480/676] [D loss: -0.010022] [G loss: -0.139708] [d1 loss: 0.029536] [d2 loss: 0.036028]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 279/500] [Batch 500/676] [D loss: -0.013767] [G loss: -0.148736] [d1 loss: 0.017284] [d2 loss: 0.016000]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 279/500] [Batch 520/676] [D loss: -0.009511] [G loss: -0.116039] [d1 loss: 0.329840] [d2 loss: 0.251559]  [sq d1 d2: 0.006128]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 540/676] [D loss: -0.006491] [G loss: -0.083599] [d1 loss: 0.060678] [d2 loss: 0.044327]  [sq d1 d2: 0.000267]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 560/676] [D loss: 0.005198] [G loss: -0.066533] [d1 loss: 0.032501] [d2 loss: 0.036402]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 279/500] [Batch 580/676] [D loss: -0.018190] [G loss: -0.053082] [d1 loss: 0.027202] [d2 loss: 0.034440]  [sq d1 d2: 0.000052]  [num0: 13.000000] [num1 51.000000]
[Epoch 279/500] [Batch 600/676] [D loss: -0.007174] [G loss: -0.072894] [d1 loss: 0.056572] [d2 loss: 0.078590]  [sq d1 d2: 0.000485]  [num0: 16.000000] [num1 48.000000]
[Epoch 279/500] [Batch 620/676] [D loss: -0.012051] [G loss: -0.089422] [d1 loss: 0.045640] [d2 loss: 0.044804]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 279/500] [Batch 640/676] [D loss: -0.021607] [G loss: -0.100179] [d1 loss: 0.055241] [d2 loss: 0.049470]  [sq d1 d2: 0.000033]  [num0: 12.000000] [num1 52.000000]
[Epoch 279/500] [Batch 660/676] [D loss: -0.023628] [G loss: -0.104596] [d1 loss: 0.034986] [d2 loss: 0.040547]  [sq d1 d2: 0.000031]  [num0: 19.000000] [num1 45.000000]
[Epoch 280/500] [Batch 0/676] [D loss: -0.027809] [G loss: -0.091988] [d1 loss: 0.032901] [d2 loss: 0.035505]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 280/500] [Batch 20/676] [D loss: -0.017376] [G loss: -0.088981] [d1 loss: 0.047184] [d2 loss: 0.059399]  [sq d1 d2: 0.000149]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 40/676] [D loss: -0.022884] [G loss: -0.119063] [d1 loss: 0.039280] [d2 loss: 0.042787]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 60/676] [D loss: -0.021476] [G loss: -0.149186] [d1 loss: 0.057528] [d2 loss: 0.075927]  [sq d1 d2: 0.000339]  [num0: 13.000000] [num1 51.000000]
[Epoch 280/500] [Batch 80/676] [D loss: 0.005182] [G loss: -0.143243] [d1 loss: 0.026673] [d2 loss: 0.030424]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 280/500] [Batch 100/676] [D loss: -0.015224] [G loss: -0.148182] [d1 loss: 0.132358] [d2 loss: 0.113719]  [sq d1 d2: 0.000347]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 120/676] [D loss: -0.008894] [G loss: -0.125900] [d1 loss: 0.109144] [d2 loss: 0.074736]  [sq d1 d2: 0.001184]  [num0: 18.000000] [num1 46.000000]
[Epoch 280/500] [Batch 140/676] [D loss: -0.006296] [G loss: -0.135563] [d1 loss: 0.073426] [d2 loss: 0.065469]  [sq d1 d2: 0.000063]  [num0: 13.000000] [num1 51.000000]
[Epoch 280/500] [Batch 160/676] [D loss: -0.005985] [G loss: -0.129410] [d1 loss: 0.035232] [d2 loss: 0.034015]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 180/676] [D loss: -0.024457] [G loss: -0.171882] [d1 loss: 0.089088] [d2 loss: 0.097980]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 200/676] [D loss: -0.009391] [G loss: -0.181444] [d1 loss: 0.042900] [d2 loss: 0.050242]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 220/676] [D loss: -0.019490] [G loss: -0.184442] [d1 loss: 0.057871] [d2 loss: 0.050967]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 240/676] [D loss: -0.032534] [G loss: -0.245084] [d1 loss: 0.093941] [d2 loss: 0.056642]  [sq d1 d2: 0.001391]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 260/676] [D loss: -0.005875] [G loss: -0.222977] [d1 loss: 0.062562] [d2 loss: 0.056479]  [sq d1 d2: 0.000037]  [num0: 11.000000] [num1 53.000000]
[Epoch 280/500] [Batch 280/676] [D loss: 0.005451] [G loss: -0.212560] [d1 loss: 0.039406] [d2 loss: 0.057728]  [sq d1 d2: 0.000336]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 300/676] [D loss: -0.015111] [G loss: -0.167788] [d1 loss: 0.129970] [d2 loss: 0.127212]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 280/500] [Batch 320/676] [D loss: -0.013183] [G loss: -0.128539] [d1 loss: 0.073381] [d2 loss: 0.077610]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 340/676] [D loss: 0.012657] [G loss: -0.120983] [d1 loss: 0.076123] [d2 loss: 0.081945]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 280/500] [Batch 360/676] [D loss: 0.009780] [G loss: -0.115466] [d1 loss: 0.095642] [d2 loss: 0.097303]  [sq d1 d2: 0.000003]  [num0: 21.000000] [num1 43.000000]
[Epoch 280/500] [Batch 380/676] [D loss: -0.003979] [G loss: -0.074915] [d1 loss: 0.096110] [d2 loss: 0.092700]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 400/676] [D loss: -0.015623] [G loss: -0.078642] [d1 loss: 0.072269] [d2 loss: 0.061233]  [sq d1 d2: 0.000122]  [num0: 19.000000] [num1 45.000000]
[Epoch 280/500] [Batch 420/676] [D loss: -0.008934] [G loss: -0.069576] [d1 loss: 0.026789] [d2 loss: 0.027195]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 440/676] [D loss: -0.027394] [G loss: -0.063526] [d1 loss: 0.066034] [d2 loss: 0.066111]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 280/500] [Batch 460/676] [D loss: -0.016072] [G loss: -0.091219] [d1 loss: 0.069859] [d2 loss: 0.064332]  [sq d1 d2: 0.000031]  [num0: 19.000000] [num1 45.000000]
[Epoch 280/500] [Batch 480/676] [D loss: 0.007682] [G loss: -0.066028] [d1 loss: 0.113532] [d2 loss: 0.114403]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 500/676] [D loss: -0.016085] [G loss: -0.087869] [d1 loss: 0.118420] [d2 loss: 0.081575]  [sq d1 d2: 0.001358]  [num0: 19.000000] [num1 45.000000]
[Epoch 280/500] [Batch 520/676] [D loss: -0.013231] [G loss: -0.102397] [d1 loss: 0.078494] [d2 loss: 0.092897]  [sq d1 d2: 0.000207]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 540/676] [D loss: -0.000094] [G loss: -0.130064] [d1 loss: 0.031653] [d2 loss: 0.039013]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 560/676] [D loss: 0.022241] [G loss: -0.135458] [d1 loss: 0.012329] [d2 loss: 0.012454]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 280/500] [Batch 580/676] [D loss: -0.009605] [G loss: -0.120035] [d1 loss: 0.225553] [d2 loss: 0.166837]  [sq d1 d2: 0.003448]  [num0: 14.000000] [num1 50.000000]
[Epoch 280/500] [Batch 600/676] [D loss: -0.000488] [G loss: -0.144589] [d1 loss: 0.039449] [d2 loss: 0.043072]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 280/500] [Batch 620/676] [D loss: -0.009878] [G loss: -0.158204] [d1 loss: 0.048774] [d2 loss: 0.041717]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 280/500] [Batch 640/676] [D loss: -0.013055] [G loss: -0.190635] [d1 loss: 0.061884] [d2 loss: 0.065137]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 280/500] [Batch 660/676] [D loss: -0.011619] [G loss: -0.204682] [d1 loss: 0.020830] [d2 loss: 0.026034]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 281/500] [Batch 0/676] [D loss: -0.015636] [G loss: -0.222370] [d1 loss: 0.066448] [d2 loss: 0.081224]  [sq d1 d2: 0.000218]  [num0: 16.000000] [num1 48.000000]
[Epoch 281/500] [Batch 20/676] [D loss: -0.027270] [G loss: -0.236217] [d1 loss: 0.077056] [d2 loss: 0.082981]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]
[Epoch 281/500] [Batch 40/676] [D loss: -0.033859] [G loss: -0.254777] [d1 loss: 0.021587] [d2 loss: 0.017146]  [sq d1 d2: 0.000020]  [num0: 12.000000] [num1 52.000000]
[Epoch 281/500] [Batch 60/676] [D loss: -0.026831] [G loss: -0.242317] [d1 loss: 0.017631] [d2 loss: 0.018334]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 281/500] [Batch 80/676] [D loss: -0.025214] [G loss: -0.236371] [d1 loss: 0.036336] [d2 loss: 0.030551]  [sq d1 d2: 0.000033]  [num0: 19.000000] [num1 45.000000]
[Epoch 281/500] [Batch 100/676] [D loss: 0.025815] [G loss: -0.176831] [d1 loss: 0.086485] [d2 loss: 0.080445]  [sq d1 d2: 0.000036]  [num0: 19.000000] [num1 45.000000]

[Epoch 281/500] [Batch 120/676] [D loss: 0.004196] [G loss: -0.139380] [d1 loss: 0.065512] [d2 loss: 0.070746]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 281/500] [Batch 140/676] [D loss: -0.005582] [G loss: -0.096796] [d1 loss: 0.024703] [d2 loss: 0.021092]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 281/500] [Batch 160/676] [D loss: 0.000428] [G loss: -0.067050] [d1 loss: 0.017574] [d2 loss: 0.010871]  [sq d1 d2: 0.000045]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 180/676] [D loss: -0.014984] [G loss: -0.031713] [d1 loss: 0.064949] [d2 loss: 0.056228]  [sq d1 d2: 0.000076]  [num0: 11.000000] [num1 53.000000]
[Epoch 281/500] [Batch 200/676] [D loss: -0.020253] [G loss: -0.006822] [d1 loss: 0.074127] [d2 loss: 0.104371]  [sq d1 d2: 0.000915]  [num0: 12.000000] [num1 52.000000]
[Epoch 281/500] [Batch 220/676] [D loss: -0.039241] [G loss: 0.003353] [d1 loss: 0.034237] [d2 loss: 0.024944]  [sq d1 d2: 0.000086]  [num0: 12.000000] [num1 52.000000]
[Epoch 281/500] [Batch 240/676] [D loss: -0.021377] [G loss: -0.009700] [d1 loss: 0.032797] [d2 loss: 0.029135]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 281/500] [Batch 260/676] [D loss: -0.009985] [G loss: 0.016971] [d1 loss: 0.106983] [d2 loss: 0.107030]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 281/500] [Batch 280/676] [D loss: -0.017798] [G loss: 0.021593] [d1 loss: 0.062036] [d2 loss: 0.068924]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 300/676] [D loss: -0.018196] [G loss: -0.008663] [d1 loss: 0.034192] [d2 loss: 0.054997]  [sq d1 d2: 0.000433]  [num0: 15.000000] [num1 49.000000]
[Epoch 281/500] [Batch 320/676] [D loss: 0.003616] [G loss: -0.016156] [d1 loss: 0.017594] [d2 loss: 0.032374]  [sq d1 d2: 0.000218]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 340/676] [D loss: -0.002527] [G loss: 0.008174] [d1 loss: 0.047546] [d2 loss: 0.053223]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 281/500] [Batch 360/676] [D loss: 0.002476] [G loss: -0.021279] [d1 loss: 0.210767] [d2 loss: 0.251983]  [sq d1 d2: 0.001699]  [num0: 18.000000] [num1 46.000000]
[Epoch 281/500] [Batch 380/676] [D loss: -0.011002] [G loss: -0.051875] [d1 loss: 0.109276] [d2 loss: 0.098895]  [sq d1 d2: 0.000108]  [num0: 13.000000] [num1 51.000000]
[Epoch 281/500] [Batch 400/676] [D loss: -0.005557] [G loss: -0.078711] [d1 loss: 0.073884] [d2 loss: 0.067885]  [sq d1 d2: 0.000036]  [num0: 20.000000] [num1 44.000000]
[Epoch 281/500] [Batch 420/676] [D loss: -0.002240] [G loss: -0.083339] [d1 loss: 0.039625] [d2 loss: 0.041551]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 281/500] [Batch 440/676] [D loss: -0.024875] [G loss: -0.093979] [d1 loss: 0.064623] [d2 loss: 0.061107]  [sq d1 d2: 0.000012]  [num0: 20.000000] [num1 44.000000]
[Epoch 281/500] [Batch 460/676] [D loss: -0.004669] [G loss: -0.102285] [d1 loss: 0.067492] [d2 loss: 0.075775]  [sq d1 d2: 0.000069]  [num0: 18.000000] [num1 46.000000]
[Epoch 281/500] [Batch 480/676] [D loss: -0.018485] [G loss: -0.111565] [d1 loss: 0.037005] [d2 loss: 0.036700]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 281/500] [Batch 500/676] [D loss: -0.029045] [G loss: -0.136416] [d1 loss: 0.044173] [d2 loss: 0.054297]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 281/500] [Batch 520/676] [D loss: -0.020052] [G loss: -0.123875] [d1 loss: 0.047344] [d2 loss: 0.053466]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 540/676] [D loss: -0.012234] [G loss: -0.122047] [d1 loss: 0.153955] [d2 loss: 0.149544]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 560/676] [D loss: -0.011191] [G loss: -0.127972] [d1 loss: 0.065531] [d2 loss: 0.079485]  [sq d1 d2: 0.000195]  [num0: 19.000000] [num1 45.000000]
[Epoch 281/500] [Batch 580/676] [D loss: 0.008948] [G loss: -0.114528] [d1 loss: 0.113228] [d2 loss: 0.146164]  [sq d1 d2: 0.001085]  [num0: 17.000000] [num1 47.000000]
[Epoch 281/500] [Batch 600/676] [D loss: 0.000821] [G loss: -0.048376] [d1 loss: 0.144167] [d2 loss: 0.138783]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 281/500] [Batch 620/676] [D loss: -0.008449] [G loss: -0.043708] [d1 loss: 0.058058] [d2 loss: 0.061450]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 281/500] [Batch 640/676] [D loss: 0.002816] [G loss: -0.041738] [d1 loss: 0.060360] [d2 loss: 0.060989]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 281/500] [Batch 660/676] [D loss: -0.014733] [G loss: -0.034732] [d1 loss: 0.098469] [d2 loss: 0.099297]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 282/500] [Batch 0/676] [D loss: -0.014266] [G loss: -0.033661] [d1 loss: 0.068845] [d2 loss: 0.060613]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 20/676] [D loss: -0.026051] [G loss: -0.043756] [d1 loss: 0.073835] [d2 loss: 0.066566]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 40/676] [D loss: -0.015637] [G loss: -0.055594] [d1 loss: 0.068154] [d2 loss: 0.092571]  [sq d1 d2: 0.000596]  [num0: 12.000000] [num1 52.000000]
[Epoch 282/500] [Batch 60/676] [D loss: -0.029837] [G loss: -0.057129] [d1 loss: 0.082705] [d2 loss: 0.095116]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 80/676] [D loss: -0.019598] [G loss: -0.063690] [d1 loss: 0.044841] [d2 loss: 0.046892]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 282/500] [Batch 100/676] [D loss: -0.014352] [G loss: -0.069118] [d1 loss: 0.104066] [d2 loss: 0.077668]  [sq d1 d2: 0.000697]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 120/676] [D loss: -0.019667] [G loss: -0.095401] [d1 loss: 0.058929] [d2 loss: 0.058909]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 282/500] [Batch 140/676] [D loss: 0.008572] [G loss: -0.091052] [d1 loss: 0.078777] [d2 loss: 0.065026]  [sq d1 d2: 0.000189]  [num0: 20.000000] [num1 44.000000]
[Epoch 282/500] [Batch 160/676] [D loss: -0.001792] [G loss: -0.121817] [d1 loss: 0.070580] [d2 loss: 0.085354]  [sq d1 d2: 0.000218]  [num0: 17.000000] [num1 47.000000]
[Epoch 282/500] [Batch 180/676] [D loss: -0.004678] [G loss: -0.110870] [d1 loss: 0.030527] [d2 loss: 0.033142]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 282/500] [Batch 200/676] [D loss: -0.006068] [G loss: -0.153923] [d1 loss: 0.062376] [d2 loss: 0.062328]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 282/500] [Batch 220/676] [D loss: -0.006658] [G loss: -0.167381] [d1 loss: 0.031164] [d2 loss: 0.028635]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 240/676] [D loss: -0.014787] [G loss: -0.172872] [d1 loss: 0.050377] [d2 loss: 0.060350]  [sq d1 d2: 0.000099]  [num0: 20.000000] [num1 44.000000]
[Epoch 282/500] [Batch 260/676] [D loss: -0.025442] [G loss: -0.197951] [d1 loss: 0.020978] [d2 loss: 0.018310]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 280/676] [D loss: -0.002612] [G loss: -0.215915] [d1 loss: 0.055789] [d2 loss: 0.050768]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 282/500] [Batch 300/676] [D loss: -0.037102] [G loss: -0.258778] [d1 loss: 0.021609] [d2 loss: 0.020821]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 282/500] [Batch 320/676] [D loss: -0.021531] [G loss: -0.292196] [d1 loss: 0.062468] [d2 loss: 0.071201]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 282/500] [Batch 340/676] [D loss: -0.022923] [G loss: -0.255417] [d1 loss: 0.040038] [d2 loss: 0.040362]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 360/676] [D loss: -0.015687] [G loss: -0.239001] [d1 loss: 0.071320] [d2 loss: 0.065178]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 282/500] [Batch 380/676] [D loss: 0.004004] [G loss: -0.190997] [d1 loss: 0.101261] [d2 loss: 0.112796]  [sq d1 d2: 0.000133]  [num0: 18.000000] [num1 46.000000]
[Epoch 282/500] [Batch 400/676] [D loss: 0.005975] [G loss: -0.105627] [d1 loss: 0.051889] [d2 loss: 0.062593]  [sq d1 d2: 0.000115]  [num0: 14.000000] [num1 50.000000]
[Epoch 282/500] [Batch 420/676] [D loss: -0.002084] [G loss: -0.069475] [d1 loss: 0.123012] [d2 loss: 0.096088]  [sq d1 d2: 0.000725]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 440/676] [D loss: -0.014312] [G loss: -0.022695] [d1 loss: 0.126045] [d2 loss: 0.129269]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 282/500] [Batch 460/676] [D loss: -0.014376] [G loss: -0.002262] [d1 loss: 0.149947] [d2 loss: 0.145414]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]

[Epoch 282/500] [Batch 480/676] [D loss: -0.027862] [G loss: 0.051342] [d1 loss: 0.140487] [d2 loss: 0.130402]  [sq d1 d2: 0.000102]  [num0: 14.000000] [num1 50.000000]
[Epoch 282/500] [Batch 500/676] [D loss: -0.034383] [G loss: 0.042017] [d1 loss: 0.029098] [d2 loss: 0.028101]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 282/500] [Batch 520/676] [D loss: -0.030135] [G loss: 0.041976] [d1 loss: 0.047866] [d2 loss: 0.054563]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 282/500] [Batch 540/676] [D loss: -0.030366] [G loss: 0.050546] [d1 loss: 0.057092] [d2 loss: 0.046641]  [sq d1 d2: 0.000109]  [num0: 13.000000] [num1 51.000000]
[Epoch 282/500] [Batch 560/676] [D loss: -0.014381] [G loss: 0.008293] [d1 loss: 0.051358] [d2 loss: 0.044842]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 580/676] [D loss: -0.017502] [G loss: 0.026293] [d1 loss: 0.072898] [d2 loss: 0.065054]  [sq d1 d2: 0.000062]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 600/676] [D loss: 0.027296] [G loss: -0.015971] [d1 loss: 0.060919] [d2 loss: 0.058501]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 620/676] [D loss: 0.006843] [G loss: -0.052887] [d1 loss: 0.032034] [d2 loss: 0.023845]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 640/676] [D loss: 0.006375] [G loss: -0.057961] [d1 loss: 0.047401] [d2 loss: 0.069585]  [sq d1 d2: 0.000492]  [num0: 15.000000] [num1 49.000000]
[Epoch 282/500] [Batch 660/676] [D loss: 0.003685] [G loss: -0.088707] [d1 loss: 0.050530] [d2 loss: 0.052218]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 283/500] [Batch 0/676] [D loss: -0.005442] [G loss: -0.081461] [d1 loss: 0.045011] [d2 loss: 0.055918]  [sq d1 d2: 0.000119]  [num0: 17.000000] [num1 47.000000]
[Epoch 283/500] [Batch 20/676] [D loss: -0.002637] [G loss: -0.110379] [d1 loss: 0.093475] [d2 loss: 0.075274]  [sq d1 d2: 0.000331]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 40/676] [D loss: -0.026770] [G loss: -0.140586] [d1 loss: 0.033127] [d2 loss: 0.032036]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 283/500] [Batch 60/676] [D loss: -0.017355] [G loss: -0.176747] [d1 loss: 0.042055] [d2 loss: 0.041098]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 283/500] [Batch 80/676] [D loss: -0.027495] [G loss: -0.227690] [d1 loss: 0.020382] [d2 loss: 0.018510]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 100/676] [D loss: -0.014681] [G loss: -0.281264] [d1 loss: 0.047779] [d2 loss: 0.042567]  [sq d1 d2: 0.000027]  [num0: 20.000000] [num1 44.000000]
[Epoch 283/500] [Batch 120/676] [D loss: -0.024327] [G loss: -0.305969] [d1 loss: 0.015172] [d2 loss: 0.017672]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 140/676] [D loss: -0.013574] [G loss: -0.286744] [d1 loss: 0.096801] [d2 loss: 0.108005]  [sq d1 d2: 0.000126]  [num0: 13.000000] [num1 51.000000]
[Epoch 283/500] [Batch 160/676] [D loss: 0.006839] [G loss: -0.251339] [d1 loss: 0.115899] [d2 loss: 0.115386]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 180/676] [D loss: 0.006750] [G loss: -0.248267] [d1 loss: 0.031738] [d2 loss: 0.033664]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 200/676] [D loss: 0.019384] [G loss: -0.151209] [d1 loss: 0.042021] [d2 loss: 0.038747]  [sq d1 d2: 0.000011]  [num0: 12.000000] [num1 52.000000]
[Epoch 283/500] [Batch 220/676] [D loss: 0.001290] [G loss: -0.095178] [d1 loss: 0.041038] [d2 loss: 0.051538]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 240/676] [D loss: -0.000538] [G loss: -0.072348] [d1 loss: 0.059926] [d2 loss: 0.058240]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 283/500] [Batch 260/676] [D loss: 0.000784] [G loss: -0.045394] [d1 loss: 0.077040] [d2 loss: 0.048307]  [sq d1 d2: 0.000826]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 280/676] [D loss: -0.026120] [G loss: -0.010853] [d1 loss: 0.024715] [d2 loss: 0.036244]  [sq d1 d2: 0.000133]  [num0: 13.000000] [num1 51.000000]
[Epoch 283/500] [Batch 300/676] [D loss: -0.033930] [G loss: 0.003039] [d1 loss: 0.064571] [d2 loss: 0.103527]  [sq d1 d2: 0.001518]  [num0: 17.000000] [num1 47.000000]
[Epoch 283/500] [Batch 320/676] [D loss: -0.053577] [G loss: -0.003650] [d1 loss: 0.057981] [d2 loss: 0.068427]  [sq d1 d2: 0.000109]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 340/676] [D loss: -0.039074] [G loss: -0.006471] [d1 loss: 0.158206] [d2 loss: 0.177985]  [sq d1 d2: 0.000391]  [num0: 10.000000] [num1 54.000000]
[Epoch 283/500] [Batch 360/676] [D loss: -0.061640] [G loss: 0.008352] [d1 loss: 0.068786] [d2 loss: 0.070848]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 283/500] [Batch 380/676] [D loss: -0.029732] [G loss: 0.006871] [d1 loss: 0.079872] [d2 loss: 0.079917]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 400/676] [D loss: 0.022498] [G loss: -0.033589] [d1 loss: 0.066572] [d2 loss: 0.066293]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 420/676] [D loss: 0.005014] [G loss: -0.019873] [d1 loss: 0.020173] [d2 loss: 0.023772]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 440/676] [D loss: 0.003434] [G loss: -0.020908] [d1 loss: 0.055279] [d2 loss: 0.057342]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 460/676] [D loss: 0.008508] [G loss: -0.025750] [d1 loss: 0.081105] [d2 loss: 0.087865]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 480/676] [D loss: 0.000610] [G loss: -0.043041] [d1 loss: 0.036485] [d2 loss: 0.035671]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 500/676] [D loss: -0.011550] [G loss: -0.043467] [d1 loss: 0.064766] [d2 loss: 0.063574]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 520/676] [D loss: -0.012290] [G loss: -0.096074] [d1 loss: 0.013730] [d2 loss: 0.013174]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 540/676] [D loss: -0.015567] [G loss: -0.148210] [d1 loss: 0.071664] [d2 loss: 0.070623]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 283/500] [Batch 560/676] [D loss: -0.029943] [G loss: -0.179026] [d1 loss: 0.084562] [d2 loss: 0.065936]  [sq d1 d2: 0.000347]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 580/676] [D loss: -0.020189] [G loss: -0.195936] [d1 loss: 0.054090] [d2 loss: 0.059813]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 283/500] [Batch 600/676] [D loss: -0.035983] [G loss: -0.189200] [d1 loss: 0.014355] [d2 loss: 0.013700]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 283/500] [Batch 620/676] [D loss: -0.052777] [G loss: -0.219835] [d1 loss: 0.082726] [d2 loss: 0.061373]  [sq d1 d2: 0.000456]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 640/676] [D loss: 0.005421] [G loss: -0.219542] [d1 loss: 0.072213] [d2 loss: 0.074958]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 283/500] [Batch 660/676] [D loss: 0.027200] [G loss: -0.193085] [d1 loss: 0.051981] [d2 loss: 0.051710]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 284/500] [Batch 0/676] [D loss: 0.020867] [G loss: -0.174354] [d1 loss: 0.059221] [d2 loss: 0.057096]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 284/500] [Batch 20/676] [D loss: 0.003834] [G loss: -0.098606] [d1 loss: 0.057926] [d2 loss: 0.054741]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 284/500] [Batch 40/676] [D loss: -0.002981] [G loss: -0.054250] [d1 loss: 0.065591] [d2 loss: 0.067802]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 60/676] [D loss: -0.005887] [G loss: 0.005862] [d1 loss: 0.067090] [d2 loss: 0.042593]  [sq d1 d2: 0.000600]  [num0: 15.000000] [num1 49.000000]
[Epoch 284/500] [Batch 80/676] [D loss: -0.025019] [G loss: 0.034811] [d1 loss: 0.049208] [d2 loss: 0.040156]  [sq d1 d2: 0.000082]  [num0: 14.000000] [num1 50.000000]
[Epoch 284/500] [Batch 100/676] [D loss: -0.019506] [G loss: 0.046721] [d1 loss: 0.027806] [d2 loss: 0.025400]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 284/500] [Batch 120/676] [D loss: -0.054452] [G loss: 0.096102] [d1 loss: 0.056536] [d2 loss: 0.066816]  [sq d1 d2: 0.000106]  [num0: 13.000000] [num1 51.000000]
[Epoch 284/500] [Batch 140/676] [D loss: -0.037379] [G loss: 0.102771] [d1 loss: 0.094718] [d2 loss: 0.098663]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]

[Epoch 284/500] [Batch 160/676] [D loss: -0.008345] [G loss: 0.090148] [d1 loss: 0.084028] [d2 loss: 0.102920]  [sq d1 d2: 0.000357]  [num0: 18.000000] [num1 46.000000]
[Epoch 284/500] [Batch 180/676] [D loss: 0.012516] [G loss: 0.064454] [d1 loss: 0.086479] [d2 loss: 0.070528]  [sq d1 d2: 0.000254]  [num0: 13.000000] [num1 51.000000]
[Epoch 284/500] [Batch 200/676] [D loss: -0.016975] [G loss: 0.036999] [d1 loss: 0.091313] [d2 loss: 0.076931]  [sq d1 d2: 0.000207]  [num0: 13.000000] [num1 51.000000]
[Epoch 284/500] [Batch 220/676] [D loss: 0.011601] [G loss: -0.035713] [d1 loss: 0.048985] [d2 loss: 0.046069]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 240/676] [D loss: -0.003534] [G loss: -0.063574] [d1 loss: 0.091768] [d2 loss: 0.079199]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 260/676] [D loss: -0.000709] [G loss: -0.071417] [d1 loss: 0.105656] [d2 loss: 0.039581]  [sq d1 d2: 0.004366]  [num0: 18.000000] [num1 46.000000]
[Epoch 284/500] [Batch 280/676] [D loss: -0.010684] [G loss: -0.087523] [d1 loss: 0.107716] [d2 loss: 0.096901]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 284/500] [Batch 300/676] [D loss: -0.006448] [G loss: -0.106992] [d1 loss: 0.094125] [d2 loss: 0.083244]  [sq d1 d2: 0.000118]  [num0: 11.000000] [num1 53.000000]
[Epoch 284/500] [Batch 320/676] [D loss: -0.042213] [G loss: -0.165755] [d1 loss: 0.050745] [d2 loss: 0.058894]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 340/676] [D loss: -0.021886] [G loss: -0.206287] [d1 loss: 0.076883] [d2 loss: 0.046908]  [sq d1 d2: 0.000898]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 360/676] [D loss: -0.025089] [G loss: -0.229731] [d1 loss: 0.155218] [d2 loss: 0.099008]  [sq d1 d2: 0.003160]  [num0: 15.000000] [num1 49.000000]
[Epoch 284/500] [Batch 380/676] [D loss: -0.002288] [G loss: -0.263576] [d1 loss: 0.025153] [d2 loss: 0.032973]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 284/500] [Batch 400/676] [D loss: 0.015351] [G loss: -0.269226] [d1 loss: 0.106532] [d2 loss: 0.111591]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 420/676] [D loss: -0.020434] [G loss: -0.223006] [d1 loss: 0.033298] [d2 loss: 0.035274]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 284/500] [Batch 440/676] [D loss: 0.003491] [G loss: -0.145750] [d1 loss: 0.033069] [d2 loss: 0.031578]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 284/500] [Batch 460/676] [D loss: 0.015039] [G loss: -0.056623] [d1 loss: 0.063727] [d2 loss: 0.058151]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 480/676] [D loss: 0.002799] [G loss: -0.029061] [d1 loss: 0.077512] [d2 loss: 0.063018]  [sq d1 d2: 0.000210]  [num0: 18.000000] [num1 46.000000]
[Epoch 284/500] [Batch 500/676] [D loss: -0.008407] [G loss: 0.026559] [d1 loss: 0.149210] [d2 loss: 0.159568]  [sq d1 d2: 0.000107]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 520/676] [D loss: -0.014973] [G loss: 0.060518] [d1 loss: 0.143078] [d2 loss: 0.128503]  [sq d1 d2: 0.000212]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 540/676] [D loss: -0.014058] [G loss: 0.086286] [d1 loss: 0.100866] [d2 loss: 0.091226]  [sq d1 d2: 0.000093]  [num0: 19.000000] [num1 45.000000]
[Epoch 284/500] [Batch 560/676] [D loss: -0.010174] [G loss: 0.088169] [d1 loss: 0.056111] [d2 loss: 0.053227]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 580/676] [D loss: -0.027591] [G loss: 0.100745] [d1 loss: 0.121763] [d2 loss: 0.134971]  [sq d1 d2: 0.000174]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 600/676] [D loss: 0.004552] [G loss: 0.089740] [d1 loss: 0.090614] [d2 loss: 0.115745]  [sq d1 d2: 0.000632]  [num0: 17.000000] [num1 47.000000]
[Epoch 284/500] [Batch 620/676] [D loss: -0.005938] [G loss: 0.052886] [d1 loss: 0.074738] [d2 loss: 0.078931]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 284/500] [Batch 640/676] [D loss: 0.001845] [G loss: 0.008584] [d1 loss: 0.101005] [d2 loss: 0.070927]  [sq d1 d2: 0.000905]  [num0: 16.000000] [num1 48.000000]
[Epoch 284/500] [Batch 660/676] [D loss: 0.005739] [G loss: -0.037320] [d1 loss: 0.044532] [d2 loss: 0.069008]  [sq d1 d2: 0.000599]  [num0: 18.000000] [num1 46.000000]
[Epoch 285/500] [Batch 0/676] [D loss: 0.000800] [G loss: -0.056138] [d1 loss: 0.093098] [d2 loss: 0.096318]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 285/500] [Batch 20/676] [D loss: 0.002339] [G loss: -0.083467] [d1 loss: 0.083620] [d2 loss: 0.093651]  [sq d1 d2: 0.000101]  [num0: 18.000000] [num1 46.000000]
[Epoch 285/500] [Batch 40/676] [D loss: -0.014931] [G loss: -0.102336] [d1 loss: 0.037468] [d2 loss: 0.038551]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 285/500] [Batch 60/676] [D loss: -0.016319] [G loss: -0.132668] [d1 loss: 0.073408] [d2 loss: 0.065855]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 285/500] [Batch 80/676] [D loss: -0.029686] [G loss: -0.183424] [d1 loss: 0.028016] [d2 loss: 0.028433]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 100/676] [D loss: -0.020072] [G loss: -0.215251] [d1 loss: 0.071545] [d2 loss: 0.050958]  [sq d1 d2: 0.000424]  [num0: 19.000000] [num1 45.000000]
[Epoch 285/500] [Batch 120/676] [D loss: -0.027715] [G loss: -0.231434] [d1 loss: 0.077025] [d2 loss: 0.069948]  [sq d1 d2: 0.000050]  [num0: 10.000000] [num1 54.000000]
[Epoch 285/500] [Batch 140/676] [D loss: -0.031687] [G loss: -0.250370] [d1 loss: 0.069662] [d2 loss: 0.062285]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 285/500] [Batch 160/676] [D loss: -0.012157] [G loss: -0.266358] [d1 loss: 0.042216] [d2 loss: 0.038350]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 180/676] [D loss: 0.014891] [G loss: -0.275756] [d1 loss: 0.054048] [d2 loss: 0.062146]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 285/500] [Batch 200/676] [D loss: 0.011416] [G loss: -0.239147] [d1 loss: 0.062363] [d2 loss: 0.064883]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 285/500] [Batch 220/676] [D loss: 0.005622] [G loss: -0.200025] [d1 loss: 0.035824] [d2 loss: 0.040471]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 285/500] [Batch 240/676] [D loss: 0.006181] [G loss: -0.165834] [d1 loss: 0.134608] [d2 loss: 0.117911]  [sq d1 d2: 0.000279]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 260/676] [D loss: -0.000167] [G loss: -0.145626] [d1 loss: 0.030549] [d2 loss: 0.071364]  [sq d1 d2: 0.001666]  [num0: 16.000000] [num1 48.000000]
[Epoch 285/500] [Batch 280/676] [D loss: -0.000258] [G loss: -0.127340] [d1 loss: 0.042847] [d2 loss: 0.047520]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 285/500] [Batch 300/676] [D loss: -0.013533] [G loss: -0.121480] [d1 loss: 0.079586] [d2 loss: 0.062724]  [sq d1 d2: 0.000284]  [num0: 11.000000] [num1 53.000000]
[Epoch 285/500] [Batch 320/676] [D loss: -0.021670] [G loss: -0.087086] [d1 loss: 0.053855] [d2 loss: 0.056721]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 340/676] [D loss: -0.026923] [G loss: -0.061578] [d1 loss: 0.104436] [d2 loss: 0.078357]  [sq d1 d2: 0.000680]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 360/676] [D loss: -0.051407] [G loss: -0.052645] [d1 loss: 0.065792] [d2 loss: 0.044661]  [sq d1 d2: 0.000447]  [num0: 16.000000] [num1 48.000000]
[Epoch 285/500] [Batch 380/676] [D loss: -0.048718] [G loss: -0.027043] [d1 loss: 0.064107] [d2 loss: 0.047273]  [sq d1 d2: 0.000283]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 400/676] [D loss: -0.029492] [G loss: -0.051488] [d1 loss: 0.043297] [d2 loss: 0.038452]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 285/500] [Batch 420/676] [D loss: -0.020652] [G loss: -0.050239] [d1 loss: 0.045906] [d2 loss: 0.049419]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 440/676] [D loss: -0.011422] [G loss: -0.071421] [d1 loss: 0.113215] [d2 loss: 0.095754]  [sq d1 d2: 0.000305]  [num0: 16.000000] [num1 48.000000]
[Epoch 285/500] [Batch 460/676] [D loss: -0.016276] [G loss: -0.079005] [d1 loss: 0.088469] [d2 loss: 0.091762]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 480/676] [D loss: 0.014664] [G loss: -0.071489] [d1 loss: 0.071217] [d2 loss: 0.087136]  [sq d1 d2: 0.000253]  [num0: 17.000000] [num1 47.000000]
[Epoch 285/500] [Batch 500/676] [D loss: -0.005302] [G loss: -0.082341] [d1 loss: 0.093531] [d2 loss: 0.099563]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]

[Epoch 285/500] [Batch 520/676] [D loss: -0.013215] [G loss: -0.101136] [d1 loss: 0.056931] [d2 loss: 0.063584]  [sq d1 d2: 0.000044]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 540/676] [D loss: -0.031944] [G loss: -0.137790] [d1 loss: 0.073355] [d2 loss: 0.083434]  [sq d1 d2: 0.000102]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 560/676] [D loss: -0.040288] [G loss: -0.187546] [d1 loss: 0.052445] [d2 loss: 0.044988]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 285/500] [Batch 580/676] [D loss: -0.019118] [G loss: -0.254892] [d1 loss: 0.075472] [d2 loss: 0.069348]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 285/500] [Batch 600/676] [D loss: -0.065290] [G loss: -0.271605] [d1 loss: 0.035558] [d2 loss: 0.038532]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 285/500] [Batch 620/676] [D loss: -0.043115] [G loss: -0.327228] [d1 loss: 0.039396] [d2 loss: 0.043844]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 285/500] [Batch 640/676] [D loss: 0.035297] [G loss: -0.304293] [d1 loss: 0.029652] [d2 loss: 0.024143]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 285/500] [Batch 660/676] [D loss: 0.023058] [G loss: -0.230676] [d1 loss: 0.060703] [d2 loss: 0.068170]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 286/500] [Batch 0/676] [D loss: 0.012986] [G loss: -0.154890] [d1 loss: 0.067911] [d2 loss: 0.069003]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 286/500] [Batch 20/676] [D loss: 0.010788] [G loss: -0.099134] [d1 loss: 0.076068] [d2 loss: 0.068667]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 286/500] [Batch 40/676] [D loss: -0.005321] [G loss: -0.037632] [d1 loss: 0.098202] [d2 loss: 0.094223]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 60/676] [D loss: -0.016188] [G loss: 0.039272] [d1 loss: 0.072699] [d2 loss: 0.072954]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 80/676] [D loss: -0.048822] [G loss: 0.089328] [d1 loss: 0.063674] [d2 loss: 0.056121]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 286/500] [Batch 100/676] [D loss: -0.030498] [G loss: 0.141620] [d1 loss: 0.119451] [d2 loss: 0.093787]  [sq d1 d2: 0.000659]  [num0: 18.000000] [num1 46.000000]
[Epoch 286/500] [Batch 120/676] [D loss: -0.024402] [G loss: 0.186704] [d1 loss: 0.132997] [d2 loss: 0.132495]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 286/500] [Batch 140/676] [D loss: -0.039948] [G loss: 0.209159] [d1 loss: 0.054505] [d2 loss: 0.056142]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 286/500] [Batch 160/676] [D loss: 0.009106] [G loss: 0.214334] [d1 loss: 0.027828] [d2 loss: 0.034051]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 286/500] [Batch 180/676] [D loss: 0.024535] [G loss: 0.199063] [d1 loss: 0.122163] [d2 loss: 0.110714]  [sq d1 d2: 0.000131]  [num0: 19.000000] [num1 45.000000]
[Epoch 286/500] [Batch 200/676] [D loss: 0.057105] [G loss: 0.129111] [d1 loss: 0.123840] [d2 loss: 0.116431]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 286/500] [Batch 220/676] [D loss: -0.004027] [G loss: 0.073014] [d1 loss: 0.038043] [d2 loss: 0.052912]  [sq d1 d2: 0.000221]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 240/676] [D loss: 0.005308] [G loss: 0.024276] [d1 loss: 0.070651] [d2 loss: 0.053433]  [sq d1 d2: 0.000296]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 260/676] [D loss: -0.016059] [G loss: 0.016349] [d1 loss: 0.088597] [d2 loss: 0.058142]  [sq d1 d2: 0.000928]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 280/676] [D loss: -0.016387] [G loss: -0.020416] [d1 loss: 0.045085] [d2 loss: 0.047139]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 286/500] [Batch 300/676] [D loss: -0.045067] [G loss: -0.040924] [d1 loss: 0.076519] [d2 loss: 0.079507]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 286/500] [Batch 320/676] [D loss: -0.085526] [G loss: -0.063954] [d1 loss: 0.097345] [d2 loss: 0.081274]  [sq d1 d2: 0.000258]  [num0: 19.000000] [num1 45.000000]
[Epoch 286/500] [Batch 340/676] [D loss: -0.014051] [G loss: -0.088870] [d1 loss: 0.038318] [d2 loss: 0.041946]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 360/676] [D loss: 0.039775] [G loss: -0.111938] [d1 loss: 0.064306] [d2 loss: 0.069212]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 286/500] [Batch 380/676] [D loss: 0.014063] [G loss: -0.131217] [d1 loss: 0.073360] [d2 loss: 0.090230]  [sq d1 d2: 0.000285]  [num0: 14.000000] [num1 50.000000]
[Epoch 286/500] [Batch 400/676] [D loss: 0.031314] [G loss: -0.081790] [d1 loss: 0.074647] [d2 loss: 0.102703]  [sq d1 d2: 0.000787]  [num0: 17.000000] [num1 47.000000]
[Epoch 286/500] [Batch 420/676] [D loss: 0.023483] [G loss: -0.032991] [d1 loss: 0.047509] [d2 loss: 0.046031]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 286/500] [Batch 440/676] [D loss: 0.005596] [G loss: 0.020937] [d1 loss: 0.058313] [d2 loss: 0.038576]  [sq d1 d2: 0.000390]  [num0: 11.000000] [num1 53.000000]
[Epoch 286/500] [Batch 460/676] [D loss: 0.004361] [G loss: 0.020488] [d1 loss: 0.118834] [d2 loss: 0.129073]  [sq d1 d2: 0.000105]  [num0: 11.000000] [num1 53.000000]
[Epoch 286/500] [Batch 480/676] [D loss: -0.009372] [G loss: 0.019062] [d1 loss: 0.085386] [d2 loss: 0.082962]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 286/500] [Batch 500/676] [D loss: -0.016324] [G loss: 0.032575] [d1 loss: 0.026789] [d2 loss: 0.026260]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 286/500] [Batch 520/676] [D loss: -0.017032] [G loss: 0.081336] [d1 loss: 0.028565] [d2 loss: 0.023758]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 286/500] [Batch 540/676] [D loss: -0.059335] [G loss: 0.140709] [d1 loss: 0.052568] [d2 loss: 0.059630]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 286/500] [Batch 560/676] [D loss: -0.068746] [G loss: 0.182255] [d1 loss: 0.124490] [d2 loss: 0.088503]  [sq d1 d2: 0.001295]  [num0: 11.000000] [num1 53.000000]
[Epoch 286/500] [Batch 580/676] [D loss: -0.028413] [G loss: 0.165226] [d1 loss: 0.057541] [d2 loss: 0.068139]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 600/676] [D loss: -0.010223] [G loss: 0.127511] [d1 loss: 0.074590] [d2 loss: 0.065892]  [sq d1 d2: 0.000076]  [num0: 14.000000] [num1 50.000000]
[Epoch 286/500] [Batch 620/676] [D loss: 0.023976] [G loss: 0.101629] [d1 loss: 0.104278] [d2 loss: 0.110789]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 286/500] [Batch 640/676] [D loss: 0.021411] [G loss: 0.056244] [d1 loss: 0.036845] [d2 loss: 0.028680]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 286/500] [Batch 660/676] [D loss: 0.009586] [G loss: 0.020516] [d1 loss: 0.043540] [d2 loss: 0.039986]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 287/500] [Batch 0/676] [D loss: 0.007033] [G loss: -0.002822] [d1 loss: 0.112059] [d2 loss: 0.084691]  [sq d1 d2: 0.000749]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 20/676] [D loss: -0.016732] [G loss: -0.062793] [d1 loss: 0.130893] [d2 loss: 0.091326]  [sq d1 d2: 0.001566]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 40/676] [D loss: -0.037497] [G loss: -0.137688] [d1 loss: 0.100741] [d2 loss: 0.103393]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 287/500] [Batch 60/676] [D loss: -0.070217] [G loss: -0.201790] [d1 loss: 0.043743] [d2 loss: 0.045388]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 80/676] [D loss: -0.032261] [G loss: -0.313959] [d1 loss: 0.114747] [d2 loss: 0.087898]  [sq d1 d2: 0.000721]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 100/676] [D loss: -0.064155] [G loss: -0.433012] [d1 loss: 0.082440] [d2 loss: 0.101025]  [sq d1 d2: 0.000345]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 120/676] [D loss: -0.037854] [G loss: -0.468476] [d1 loss: 0.018858] [d2 loss: 0.017111]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 140/676] [D loss: 0.044425] [G loss: -0.442415] [d1 loss: 0.041604] [d2 loss: 0.039699]  [sq d1 d2: 0.000004]  [num0: 11.000000] [num1 53.000000]
[Epoch 287/500] [Batch 160/676] [D loss: 0.011611] [G loss: -0.323521] [d1 loss: 0.048235] [d2 loss: 0.035640]  [sq d1 d2: 0.000159]  [num0: 16.000000] [num1 48.000000]
[Epoch 287/500] [Batch 180/676] [D loss: 0.047270] [G loss: -0.186580] [d1 loss: 0.150993] [d2 loss: 0.095041]  [sq d1 d2: 0.003131]  [num0: 17.000000] [num1 47.000000]

[Epoch 287/500] [Batch 200/676] [D loss: 0.018407] [G loss: -0.093470] [d1 loss: 0.067421] [d2 loss: 0.065164]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 220/676] [D loss: 0.000609] [G loss: -0.024994] [d1 loss: 0.035764] [d2 loss: 0.032411]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 240/676] [D loss: -0.016521] [G loss: 0.022460] [d1 loss: 0.074340] [d2 loss: 0.074268]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 287/500] [Batch 260/676] [D loss: -0.041016] [G loss: 0.084445] [d1 loss: 0.103794] [d2 loss: 0.096086]  [sq d1 d2: 0.000059]  [num0: 12.000000] [num1 52.000000]
[Epoch 287/500] [Batch 280/676] [D loss: -0.067660] [G loss: 0.230623] [d1 loss: 0.020354] [d2 loss: 0.016791]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 287/500] [Batch 300/676] [D loss: -0.092398] [G loss: 0.309714] [d1 loss: 0.039401] [d2 loss: 0.030985]  [sq d1 d2: 0.000071]  [num0: 11.000000] [num1 53.000000]
[Epoch 287/500] [Batch 320/676] [D loss: -0.034653] [G loss: 0.289029] [d1 loss: 0.045816] [d2 loss: 0.048247]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 340/676] [D loss: -0.097098] [G loss: 0.221039] [d1 loss: 0.063385] [d2 loss: 0.049648]  [sq d1 d2: 0.000189]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 360/676] [D loss: -0.000760] [G loss: 0.144072] [d1 loss: 0.033410] [d2 loss: 0.044272]  [sq d1 d2: 0.000118]  [num0: 12.000000] [num1 52.000000]
[Epoch 287/500] [Batch 380/676] [D loss: -0.009688] [G loss: 0.020611] [d1 loss: 0.082434] [d2 loss: 0.073532]  [sq d1 d2: 0.000079]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 400/676] [D loss: 0.011243] [G loss: -0.051611] [d1 loss: 0.054673] [d2 loss: 0.042789]  [sq d1 d2: 0.000141]  [num0: 17.000000] [num1 47.000000]
[Epoch 287/500] [Batch 420/676] [D loss: 0.014749] [G loss: -0.071502] [d1 loss: 0.086866] [d2 loss: 0.071932]  [sq d1 d2: 0.000223]  [num0: 16.000000] [num1 48.000000]
[Epoch 287/500] [Batch 440/676] [D loss: 0.000205] [G loss: -0.087630] [d1 loss: 0.021421] [d2 loss: 0.022500]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 287/500] [Batch 460/676] [D loss: -0.002716] [G loss: -0.102051] [d1 loss: 0.116760] [d2 loss: 0.123397]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 287/500] [Batch 480/676] [D loss: -0.026926] [G loss: -0.125274] [d1 loss: 0.110496] [d2 loss: 0.087761]  [sq d1 d2: 0.000517]  [num0: 10.000000] [num1 54.000000]
[Epoch 287/500] [Batch 500/676] [D loss: -0.058115] [G loss: -0.174774] [d1 loss: 0.048280] [d2 loss: 0.043032]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 520/676] [D loss: -0.023018] [G loss: -0.225273] [d1 loss: 0.029409] [d2 loss: 0.030034]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 287/500] [Batch 540/676] [D loss: -0.074973] [G loss: -0.260109] [d1 loss: 0.103815] [d2 loss: 0.101637]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 287/500] [Batch 560/676] [D loss: -0.000061] [G loss: -0.316474] [d1 loss: 0.138347] [d2 loss: 0.112063]  [sq d1 d2: 0.000691]  [num0: 17.000000] [num1 47.000000]
[Epoch 287/500] [Batch 580/676] [D loss: -0.004438] [G loss: -0.322347] [d1 loss: 0.027222] [d2 loss: 0.027739]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 287/500] [Batch 600/676] [D loss: 0.017502] [G loss: -0.272056] [d1 loss: 0.099235] [d2 loss: 0.099423]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 287/500] [Batch 620/676] [D loss: -0.009677] [G loss: -0.148170] [d1 loss: 0.067711] [d2 loss: 0.082133]  [sq d1 d2: 0.000208]  [num0: 14.000000] [num1 50.000000]
[Epoch 287/500] [Batch 640/676] [D loss: 0.019619] [G loss: -0.076773] [d1 loss: 0.051824] [d2 loss: 0.047340]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 287/500] [Batch 660/676] [D loss: 0.014391] [G loss: -0.017852] [d1 loss: 0.064820] [d2 loss: 0.063607]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 0/676] [D loss: -0.000940] [G loss: 0.012912] [d1 loss: 0.045611] [d2 loss: 0.050836]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 288/500] [Batch 20/676] [D loss: -0.009500] [G loss: 0.059916] [d1 loss: 0.031448] [d2 loss: 0.033597]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 288/500] [Batch 40/676] [D loss: -0.031556] [G loss: 0.114134] [d1 loss: 0.068282] [d2 loss: 0.051381]  [sq d1 d2: 0.000286]  [num0: 17.000000] [num1 47.000000]
[Epoch 288/500] [Batch 60/676] [D loss: -0.067960] [G loss: 0.296964] [d1 loss: 0.090432] [d2 loss: 0.079544]  [sq d1 d2: 0.000119]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 80/676] [D loss: -0.086221] [G loss: 0.420873] [d1 loss: 0.073892] [d2 loss: 0.084715]  [sq d1 d2: 0.000117]  [num0: 12.000000] [num1 52.000000]
[Epoch 288/500] [Batch 100/676] [D loss: -0.008559] [G loss: 0.414709] [d1 loss: 0.110715] [d2 loss: 0.112719]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 120/676] [D loss: -0.071368] [G loss: 0.417072] [d1 loss: 0.112489] [d2 loss: 0.155867]  [sq d1 d2: 0.001882]  [num0: 17.000000] [num1 47.000000]
[Epoch 288/500] [Batch 140/676] [D loss: 0.034706] [G loss: 0.399333] [d1 loss: 0.067631] [d2 loss: 0.082969]  [sq d1 d2: 0.000235]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 160/676] [D loss: 0.034468] [G loss: 0.287662] [d1 loss: 0.079022] [d2 loss: 0.105361]  [sq d1 d2: 0.000694]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 180/676] [D loss: 0.024895] [G loss: 0.158835] [d1 loss: 0.033193] [d2 loss: 0.029834]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 288/500] [Batch 200/676] [D loss: 0.014434] [G loss: 0.079586] [d1 loss: 0.035218] [d2 loss: 0.040545]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 288/500] [Batch 220/676] [D loss: 0.002706] [G loss: 0.027202] [d1 loss: 0.039237] [d2 loss: 0.046540]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 288/500] [Batch 240/676] [D loss: -0.006187] [G loss: -0.012129] [d1 loss: 0.038799] [d2 loss: 0.038120]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 260/676] [D loss: -0.034536] [G loss: -0.073891] [d1 loss: 0.083166] [d2 loss: 0.053733]  [sq d1 d2: 0.000866]  [num0: 14.000000] [num1 50.000000]
[Epoch 288/500] [Batch 280/676] [D loss: -0.081164] [G loss: -0.120967] [d1 loss: 0.049426] [d2 loss: 0.033231]  [sq d1 d2: 0.000262]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 300/676] [D loss: -0.081534] [G loss: -0.214087] [d1 loss: 0.123490] [d2 loss: 0.129548]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 288/500] [Batch 320/676] [D loss: -0.089159] [G loss: -0.223302] [d1 loss: 0.018872] [d2 loss: 0.015742]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 340/676] [D loss: -0.040479] [G loss: -0.295756] [d1 loss: 0.060751] [d2 loss: 0.059387]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 288/500] [Batch 360/676] [D loss: 0.003708] [G loss: -0.367769] [d1 loss: 0.103448] [d2 loss: 0.118059]  [sq d1 d2: 0.000213]  [num0: 17.000000] [num1 47.000000]
[Epoch 288/500] [Batch 380/676] [D loss: 0.049942] [G loss: -0.395235] [d1 loss: 0.069139] [d2 loss: 0.104846]  [sq d1 d2: 0.001275]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 400/676] [D loss: 0.030172] [G loss: -0.344835] [d1 loss: 0.087562] [d2 loss: 0.070566]  [sq d1 d2: 0.000289]  [num0: 16.000000] [num1 48.000000]
[Epoch 288/500] [Batch 420/676] [D loss: 0.011076] [G loss: -0.192925] [d1 loss: 0.039789] [d2 loss: 0.038014]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 440/676] [D loss: 0.009908] [G loss: -0.115459] [d1 loss: 0.045229] [d2 loss: 0.038894]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 460/676] [D loss: 0.000915] [G loss: -0.059005] [d1 loss: 0.099516] [d2 loss: 0.106851]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 480/676] [D loss: -0.026441] [G loss: 0.003994] [d1 loss: 0.109945] [d2 loss: 0.106172]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 288/500] [Batch 500/676] [D loss: -0.030854] [G loss: 0.111575] [d1 loss: 0.051760] [d2 loss: 0.045902]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 288/500] [Batch 520/676] [D loss: -0.030706] [G loss: 0.342973] [d1 loss: 0.085111] [d2 loss: 0.083382]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 288/500] [Batch 540/676] [D loss: -0.083464] [G loss: 0.525798] [d1 loss: 0.136788] [d2 loss: 0.135963]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]

[Epoch 288/500] [Batch 560/676] [D loss: -0.063458] [G loss: 0.595366] [d1 loss: 0.100057] [d2 loss: 0.082150]  [sq d1 d2: 0.000321]  [num0: 19.000000] [num1 45.000000]
[Epoch 288/500] [Batch 580/676] [D loss: -0.011486] [G loss: 0.538334] [d1 loss: 0.072135] [d2 loss: 0.066752]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 288/500] [Batch 600/676] [D loss: 0.013176] [G loss: 0.466019] [d1 loss: 0.055689] [d2 loss: 0.057306]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 288/500] [Batch 620/676] [D loss: 0.014402] [G loss: 0.415395] [d1 loss: 0.080865] [d2 loss: 0.065932]  [sq d1 d2: 0.000223]  [num0: 18.000000] [num1 46.000000]
[Epoch 288/500] [Batch 640/676] [D loss: 0.010366] [G loss: 0.262626] [d1 loss: 0.066964] [d2 loss: 0.064078]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 288/500] [Batch 660/676] [D loss: 0.032380] [G loss: 0.129094] [d1 loss: 0.055032] [d2 loss: 0.051062]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 0/676] [D loss: 0.012260] [G loss: 0.044546] [d1 loss: 0.188526] [d2 loss: 0.208828]  [sq d1 d2: 0.000412]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 20/676] [D loss: -0.011621] [G loss: -0.018839] [d1 loss: 0.036138] [d2 loss: 0.074431]  [sq d1 d2: 0.001466]  [num0: 16.000000] [num1 48.000000]
[Epoch 289/500] [Batch 40/676] [D loss: -0.024522] [G loss: -0.055124] [d1 loss: 0.072881] [d2 loss: 0.046814]  [sq d1 d2: 0.000679]  [num0: 20.000000] [num1 44.000000]
[Epoch 289/500] [Batch 60/676] [D loss: -0.065396] [G loss: -0.096644] [d1 loss: 0.056220] [d2 loss: 0.067283]  [sq d1 d2: 0.000122]  [num0: 18.000000] [num1 46.000000]
[Epoch 289/500] [Batch 80/676] [D loss: -0.120093] [G loss: -0.196366] [d1 loss: 0.054721] [d2 loss: 0.030804]  [sq d1 d2: 0.000572]  [num0: 19.000000] [num1 45.000000]
[Epoch 289/500] [Batch 100/676] [D loss: -0.078609] [G loss: -0.290292] [d1 loss: 0.073018] [d2 loss: 0.073423]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 120/676] [D loss: -0.043847] [G loss: -0.351458] [d1 loss: 0.037238] [d2 loss: 0.054674]  [sq d1 d2: 0.000304]  [num0: 13.000000] [num1 51.000000]
[Epoch 289/500] [Batch 140/676] [D loss: -0.029763] [G loss: -0.352846] [d1 loss: 0.063568] [d2 loss: 0.057864]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 289/500] [Batch 160/676] [D loss: -0.017612] [G loss: -0.374304] [d1 loss: 0.109661] [d2 loss: 0.087205]  [sq d1 d2: 0.000504]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 180/676] [D loss: 0.032473] [G loss: -0.388243] [d1 loss: 0.099745] [d2 loss: 0.081844]  [sq d1 d2: 0.000320]  [num0: 17.000000] [num1 47.000000]
[Epoch 289/500] [Batch 200/676] [D loss: 0.043784] [G loss: -0.336055] [d1 loss: 0.062253] [d2 loss: 0.063310]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 289/500] [Batch 220/676] [D loss: 0.026723] [G loss: -0.216596] [d1 loss: 0.069870] [d2 loss: 0.053703]  [sq d1 d2: 0.000261]  [num0: 18.000000] [num1 46.000000]
[Epoch 289/500] [Batch 240/676] [D loss: 0.010255] [G loss: -0.112099] [d1 loss: 0.082709] [d2 loss: 0.079183]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 260/676] [D loss: -0.003495] [G loss: -0.049684] [d1 loss: 0.092732] [d2 loss: 0.086703]  [sq d1 d2: 0.000036]  [num0: 19.000000] [num1 45.000000]
[Epoch 289/500] [Batch 280/676] [D loss: -0.025840] [G loss: 0.029117] [d1 loss: 0.084906] [d2 loss: 0.090203]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 300/676] [D loss: -0.041697] [G loss: 0.120402] [d1 loss: 0.091023] [d2 loss: 0.072938]  [sq d1 d2: 0.000327]  [num0: 16.000000] [num1 48.000000]
[Epoch 289/500] [Batch 320/676] [D loss: -0.072439] [G loss: 0.322535] [d1 loss: 0.070971] [d2 loss: 0.070611]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 340/676] [D loss: -0.094261] [G loss: 0.379693] [d1 loss: 0.077678] [d2 loss: 0.082794]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 289/500] [Batch 360/676] [D loss: -0.072033] [G loss: 0.467983] [d1 loss: 0.052402] [d2 loss: 0.048573]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 289/500] [Batch 380/676] [D loss: -0.082420] [G loss: 0.510320] [d1 loss: 0.107835] [d2 loss: 0.112148]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 400/676] [D loss: -0.019806] [G loss: 0.378940] [d1 loss: 0.033329] [d2 loss: 0.027370]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 289/500] [Batch 420/676] [D loss: 0.030603] [G loss: 0.308798] [d1 loss: 0.196683] [d2 loss: 0.164515]  [sq d1 d2: 0.001035]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 440/676] [D loss: 0.045817] [G loss: 0.144681] [d1 loss: 0.074614] [d2 loss: 0.058681]  [sq d1 d2: 0.000254]  [num0: 17.000000] [num1 47.000000]
[Epoch 289/500] [Batch 460/676] [D loss: 0.026121] [G loss: 0.048957] [d1 loss: 0.033159] [d2 loss: 0.031507]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 480/676] [D loss: 0.002913] [G loss: -0.019984] [d1 loss: 0.108219] [d2 loss: 0.082460]  [sq d1 d2: 0.000664]  [num0: 19.000000] [num1 45.000000]
[Epoch 289/500] [Batch 500/676] [D loss: -0.016149] [G loss: -0.085387] [d1 loss: 0.078476] [d2 loss: 0.085393]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 520/676] [D loss: -0.065722] [G loss: -0.172424] [d1 loss: 0.156437] [d2 loss: 0.140729]  [sq d1 d2: 0.000247]  [num0: 16.000000] [num1 48.000000]
[Epoch 289/500] [Batch 540/676] [D loss: -0.128084] [G loss: -0.263395] [d1 loss: 0.015556] [d2 loss: 0.013639]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 560/676] [D loss: -0.116895] [G loss: -0.335031] [d1 loss: 0.223590] [d2 loss: 0.248623]  [sq d1 d2: 0.000627]  [num0: 16.000000] [num1 48.000000]
[Epoch 289/500] [Batch 580/676] [D loss: -0.105398] [G loss: -0.377420] [d1 loss: 0.287544] [d2 loss: 0.243293]  [sq d1 d2: 0.001958]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 600/676] [D loss: -0.050155] [G loss: -0.432459] [d1 loss: 0.059482] [d2 loss: 0.066453]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 289/500] [Batch 620/676] [D loss: -0.046951] [G loss: -0.495371] [d1 loss: 0.104255] [d2 loss: 0.104731]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 289/500] [Batch 640/676] [D loss: 0.051176] [G loss: -0.418423] [d1 loss: 0.054245] [d2 loss: 0.064631]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 289/500] [Batch 660/676] [D loss: 0.033959] [G loss: -0.346823] [d1 loss: 0.090750] [d2 loss: 0.065925]  [sq d1 d2: 0.000616]  [num0: 13.000000] [num1 51.000000]
[Epoch 290/500] [Batch 0/676] [D loss: 0.030614] [G loss: -0.208628] [d1 loss: 0.149509] [d2 loss: 0.126834]  [sq d1 d2: 0.000514]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 20/676] [D loss: 0.014868] [G loss: -0.084625] [d1 loss: 0.113356] [d2 loss: 0.104324]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 40/676] [D loss: 0.005013] [G loss: -0.012031] [d1 loss: 0.114933] [d2 loss: 0.108498]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 60/676] [D loss: -0.010468] [G loss: 0.027504] [d1 loss: 0.111934] [d2 loss: 0.117819]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 80/676] [D loss: -0.041683] [G loss: 0.130085] [d1 loss: 0.075387] [d2 loss: 0.077994]  [sq d1 d2: 0.000007]  [num0: 11.000000] [num1 53.000000]
[Epoch 290/500] [Batch 100/676] [D loss: -0.104841] [G loss: 0.318419] [d1 loss: 0.099310] [d2 loss: 0.095074]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 120/676] [D loss: -0.151514] [G loss: 0.586012] [d1 loss: 0.115861] [d2 loss: 0.096445]  [sq d1 d2: 0.000377]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 140/676] [D loss: -0.152260] [G loss: 0.665459] [d1 loss: 0.099550] [d2 loss: 0.082731]  [sq d1 d2: 0.000283]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 160/676] [D loss: -0.147720] [G loss: 0.692480] [d1 loss: 0.089082] [d2 loss: 0.068689]  [sq d1 d2: 0.000416]  [num0: 14.000000] [num1 50.000000]
[Epoch 290/500] [Batch 180/676] [D loss: -0.006975] [G loss: 0.666254] [d1 loss: 0.087592] [d2 loss: 0.077619]  [sq d1 d2: 0.000099]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 200/676] [D loss: 0.010789] [G loss: 0.574641] [d1 loss: 0.089518] [d2 loss: 0.094776]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 220/676] [D loss: -0.004263] [G loss: 0.432752] [d1 loss: 0.031518] [d2 loss: 0.036422]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]

[Epoch 290/500] [Batch 240/676] [D loss: 0.061907] [G loss: 0.263650] [d1 loss: 0.174596] [d2 loss: 0.119331]  [sq d1 d2: 0.003054]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 260/676] [D loss: 0.037352] [G loss: 0.138526] [d1 loss: 0.091051] [d2 loss: 0.045789]  [sq d1 d2: 0.002049]  [num0: 10.000000] [num1 54.000000]
[Epoch 290/500] [Batch 280/676] [D loss: 0.006933] [G loss: 0.047160] [d1 loss: 0.044056] [d2 loss: 0.052347]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 300/676] [D loss: -0.003138] [G loss: -0.035663] [d1 loss: 0.029365] [d2 loss: 0.033772]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 290/500] [Batch 320/676] [D loss: -0.015484] [G loss: -0.138635] [d1 loss: 0.109532] [d2 loss: 0.101573]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 340/676] [D loss: -0.039771] [G loss: -0.216041] [d1 loss: 0.031677] [d2 loss: 0.036819]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 360/676] [D loss: -0.051946] [G loss: -0.284744] [d1 loss: 0.092230] [d2 loss: 0.084391]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 380/676] [D loss: -0.100036] [G loss: -0.433443] [d1 loss: 0.039835] [d2 loss: 0.032079]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 400/676] [D loss: -0.110659] [G loss: -0.489103] [d1 loss: 0.103875] [d2 loss: 0.085971]  [sq d1 d2: 0.000321]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 420/676] [D loss: -0.048287] [G loss: -0.512013] [d1 loss: 0.067266] [d2 loss: 0.075932]  [sq d1 d2: 0.000075]  [num0: 13.000000] [num1 51.000000]
[Epoch 290/500] [Batch 440/676] [D loss: -0.126235] [G loss: -0.657385] [d1 loss: 0.153281] [d2 loss: 0.126751]  [sq d1 d2: 0.000704]  [num0: 19.000000] [num1 45.000000]
[Epoch 290/500] [Batch 460/676] [D loss: 0.035597] [G loss: -0.756107] [d1 loss: 0.055976] [d2 loss: 0.066985]  [sq d1 d2: 0.000121]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 480/676] [D loss: -0.010494] [G loss: -0.675322] [d1 loss: 0.096221] [d2 loss: 0.094243]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 290/500] [Batch 500/676] [D loss: 0.068466] [G loss: -0.547912] [d1 loss: 0.177561] [d2 loss: 0.188013]  [sq d1 d2: 0.000109]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 520/676] [D loss: 0.026803] [G loss: -0.357177] [d1 loss: 0.143665] [d2 loss: 0.157146]  [sq d1 d2: 0.000182]  [num0: 17.000000] [num1 47.000000]
[Epoch 290/500] [Batch 540/676] [D loss: 0.020620] [G loss: -0.221068] [d1 loss: 0.058453] [d2 loss: 0.047503]  [sq d1 d2: 0.000120]  [num0: 14.000000] [num1 50.000000]
[Epoch 290/500] [Batch 560/676] [D loss: 0.000895] [G loss: -0.117264] [d1 loss: 0.167639] [d2 loss: 0.198694]  [sq d1 d2: 0.000964]  [num0: 15.000000] [num1 49.000000]
[Epoch 290/500] [Batch 580/676] [D loss: -0.014417] [G loss: 0.018388] [d1 loss: 0.119366] [d2 loss: 0.116452]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 290/500] [Batch 600/676] [D loss: -0.041538] [G loss: 0.193505] [d1 loss: 0.069439] [d2 loss: 0.059280]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 290/500] [Batch 620/676] [D loss: -0.094262] [G loss: 0.397770] [d1 loss: 0.074393] [d2 loss: 0.088765]  [sq d1 d2: 0.000207]  [num0: 13.000000] [num1 51.000000]
[Epoch 290/500] [Batch 640/676] [D loss: -0.121628] [G loss: 0.662465] [d1 loss: 0.124933] [d2 loss: 0.115603]  [sq d1 d2: 0.000087]  [num0: 19.000000] [num1 45.000000]
[Epoch 290/500] [Batch 660/676] [D loss: -0.067395] [G loss: 0.885220] [d1 loss: 0.111174] [d2 loss: 0.101262]  [sq d1 d2: 0.000098]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 0/676] [D loss: -0.232666] [G loss: 0.878558] [d1 loss: 0.139612] [d2 loss: 0.148876]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 20/676] [D loss: 0.033954] [G loss: 0.838194] [d1 loss: 0.081951] [d2 loss: 0.076801]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 291/500] [Batch 40/676] [D loss: -0.034793] [G loss: 0.802806] [d1 loss: 0.091854] [d2 loss: 0.098848]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 291/500] [Batch 60/676] [D loss: 0.006633] [G loss: 0.646857] [d1 loss: 0.030527] [d2 loss: 0.039354]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 80/676] [D loss: 0.052715] [G loss: 0.450609] [d1 loss: 0.076589] [d2 loss: 0.070621]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 291/500] [Batch 100/676] [D loss: 0.042620] [G loss: 0.258271] [d1 loss: 0.094835] [d2 loss: 0.084033]  [sq d1 d2: 0.000117]  [num0: 12.000000] [num1 52.000000]
[Epoch 291/500] [Batch 120/676] [D loss: 0.021215] [G loss: 0.098840] [d1 loss: 0.069633] [d2 loss: 0.061303]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 140/676] [D loss: -0.004515] [G loss: -0.043166] [d1 loss: 0.040863] [d2 loss: 0.047987]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 291/500] [Batch 160/676] [D loss: -0.036340] [G loss: -0.167311] [d1 loss: 0.207159] [d2 loss: 0.150811]  [sq d1 d2: 0.003175]  [num0: 18.000000] [num1 46.000000]
[Epoch 291/500] [Batch 180/676] [D loss: -0.046811] [G loss: -0.295104] [d1 loss: 0.095810] [d2 loss: 0.087261]  [sq d1 d2: 0.000073]  [num0: 18.000000] [num1 46.000000]
[Epoch 291/500] [Batch 200/676] [D loss: -0.091409] [G loss: -0.448422] [d1 loss: 0.080996] [d2 loss: 0.080205]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 291/500] [Batch 220/676] [D loss: -0.081501] [G loss: -0.582270] [d1 loss: 0.069863] [d2 loss: 0.069428]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 291/500] [Batch 240/676] [D loss: -0.173577] [G loss: -0.600465] [d1 loss: 0.023174] [d2 loss: 0.020980]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 260/676] [D loss: -0.067359] [G loss: -0.638676] [d1 loss: 0.093586] [d2 loss: 0.104361]  [sq d1 d2: 0.000116]  [num0: 18.000000] [num1 46.000000]
[Epoch 291/500] [Batch 280/676] [D loss: -0.141526] [G loss: -0.705846] [d1 loss: 0.128228] [d2 loss: 0.162509]  [sq d1 d2: 0.001175]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 300/676] [D loss: 0.046332] [G loss: -0.778563] [d1 loss: 0.153169] [d2 loss: 0.152626]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 291/500] [Batch 320/676] [D loss: 0.035652] [G loss: -0.608954] [d1 loss: 0.179158] [d2 loss: 0.158942]  [sq d1 d2: 0.000409]  [num0: 17.000000] [num1 47.000000]
[Epoch 291/500] [Batch 340/676] [D loss: 0.020279] [G loss: -0.424570] [d1 loss: 0.142556] [d2 loss: 0.124755]  [sq d1 d2: 0.000317]  [num0: 10.000000] [num1 54.000000]
[Epoch 291/500] [Batch 360/676] [D loss: 0.030592] [G loss: -0.255265] [d1 loss: 0.133170] [d2 loss: 0.117545]  [sq d1 d2: 0.000244]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 380/676] [D loss: 0.011607] [G loss: -0.102396] [d1 loss: 0.155961] [d2 loss: 0.134764]  [sq d1 d2: 0.000449]  [num0: 15.000000] [num1 49.000000]
[Epoch 291/500] [Batch 400/676] [D loss: -0.008107] [G loss: 0.019992] [d1 loss: 0.164916] [d2 loss: 0.142690]  [sq d1 d2: 0.000494]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 420/676] [D loss: -0.013202] [G loss: 0.128051] [d1 loss: 0.117813] [d2 loss: 0.156740]  [sq d1 d2: 0.001515]  [num0: 14.000000] [num1 50.000000]
[Epoch 291/500] [Batch 440/676] [D loss: -0.047794] [G loss: 0.306265] [d1 loss: 0.087254] [d2 loss: 0.079475]  [sq d1 d2: 0.000061]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 460/676] [D loss: -0.073547] [G loss: 0.531414] [d1 loss: 0.105716] [d2 loss: 0.110130]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 291/500] [Batch 480/676] [D loss: -0.152368] [G loss: 0.803803] [d1 loss: 0.132491] [d2 loss: 0.144305]  [sq d1 d2: 0.000140]  [num0: 12.000000] [num1 52.000000]
[Epoch 291/500] [Batch 500/676] [D loss: -0.091399] [G loss: 0.840966] [d1 loss: 0.080266] [d2 loss: 0.091642]  [sq d1 d2: 0.000129]  [num0: 13.000000] [num1 51.000000]
[Epoch 291/500] [Batch 520/676] [D loss: -0.046799] [G loss: 0.884376] [d1 loss: 0.096838] [d2 loss: 0.084588]  [sq d1 d2: 0.000150]  [num0: 13.000000] [num1 51.000000]
[Epoch 291/500] [Batch 540/676] [D loss: -0.045537] [G loss: 0.870339] [d1 loss: 0.132473] [d2 loss: 0.134608]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 560/676] [D loss: 0.012640] [G loss: 0.865014] [d1 loss: 0.122844] [d2 loss: 0.110329]  [sq d1 d2: 0.000157]  [num0: 19.000000] [num1 45.000000]
[Epoch 291/500] [Batch 580/676] [D loss: -0.011066] [G loss: 0.741027] [d1 loss: 0.109569] [d2 loss: 0.089181]  [sq d1 d2: 0.000416]  [num0: 17.000000] [num1 47.000000]

[Epoch 291/500] [Batch 600/676] [D loss: -0.031509] [G loss: 0.615586] [d1 loss: 0.087251] [d2 loss: 0.072332]  [sq d1 d2: 0.000223]  [num0: 13.000000] [num1 51.000000]
[Epoch 291/500] [Batch 620/676] [D loss: 0.040634] [G loss: 0.431925] [d1 loss: 0.122027] [d2 loss: 0.124931]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 291/500] [Batch 640/676] [D loss: 0.016092] [G loss: 0.372968] [d1 loss: 0.212173] [d2 loss: 0.195827]  [sq d1 d2: 0.000267]  [num0: 21.000000] [num1 43.000000]
[Epoch 291/500] [Batch 660/676] [D loss: -0.009209] [G loss: 0.269953] [d1 loss: 0.118750] [d2 loss: 0.100228]  [sq d1 d2: 0.000343]  [num0: 16.000000] [num1 48.000000]
[Epoch 292/500] [Batch 0/676] [D loss: -0.007050] [G loss: 0.252145] [d1 loss: 0.094448] [d2 loss: 0.087672]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 20/676] [D loss: -0.017164] [G loss: 0.249237] [d1 loss: 0.058710] [d2 loss: 0.046539]  [sq d1 d2: 0.000148]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 40/676] [D loss: -0.026811] [G loss: 0.227589] [d1 loss: 0.084747] [d2 loss: 0.075280]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 60/676] [D loss: -0.055130] [G loss: 0.207476] [d1 loss: 0.112541] [d2 loss: 0.107927]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 292/500] [Batch 80/676] [D loss: -0.038641] [G loss: 0.220202] [d1 loss: 0.204708] [d2 loss: 0.166182]  [sq d1 d2: 0.001484]  [num0: 19.000000] [num1 45.000000]
[Epoch 292/500] [Batch 100/676] [D loss: -0.030689] [G loss: 0.237418] [d1 loss: 0.044619] [d2 loss: 0.046250]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 292/500] [Batch 120/676] [D loss: -0.028868] [G loss: 0.239305] [d1 loss: 0.100462] [d2 loss: 0.119418]  [sq d1 d2: 0.000359]  [num0: 17.000000] [num1 47.000000]
[Epoch 292/500] [Batch 140/676] [D loss: -0.049443] [G loss: 0.228470] [d1 loss: 0.094499] [d2 loss: 0.082236]  [sq d1 d2: 0.000150]  [num0: 19.000000] [num1 45.000000]
[Epoch 292/500] [Batch 160/676] [D loss: -0.027815] [G loss: 0.152266] [d1 loss: 0.072730] [d2 loss: 0.065341]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 292/500] [Batch 180/676] [D loss: -0.015838] [G loss: 0.131082] [d1 loss: 0.111674] [d2 loss: 0.113873]  [sq d1 d2: 0.000005]  [num0: 21.000000] [num1 43.000000]
[Epoch 292/500] [Batch 200/676] [D loss: 0.005323] [G loss: 0.070752] [d1 loss: 0.103015] [d2 loss: 0.069136]  [sq d1 d2: 0.001148]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 220/676] [D loss: -0.038325] [G loss: 0.007506] [d1 loss: 0.050857] [d2 loss: 0.052543]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 240/676] [D loss: 0.019831] [G loss: -0.076615] [d1 loss: 0.063263] [d2 loss: 0.064250]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 292/500] [Batch 260/676] [D loss: 0.023412] [G loss: -0.229003] [d1 loss: 0.094796] [d2 loss: 0.093657]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 292/500] [Batch 280/676] [D loss: -0.015180] [G loss: -0.265970] [d1 loss: 0.190224] [d2 loss: 0.154922]  [sq d1 d2: 0.001246]  [num0: 17.000000] [num1 47.000000]
[Epoch 292/500] [Batch 300/676] [D loss: -0.007801] [G loss: -0.278376] [d1 loss: 0.097836] [d2 loss: 0.092525]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 292/500] [Batch 320/676] [D loss: 0.012084] [G loss: -0.324978] [d1 loss: 0.065185] [d2 loss: 0.081256]  [sq d1 d2: 0.000258]  [num0: 14.000000] [num1 50.000000]
[Epoch 292/500] [Batch 340/676] [D loss: -0.017049] [G loss: -0.355820] [d1 loss: 0.109481] [d2 loss: 0.076113]  [sq d1 d2: 0.001113]  [num0: 14.000000] [num1 50.000000]
[Epoch 292/500] [Batch 360/676] [D loss: -0.012506] [G loss: -0.379571] [d1 loss: 0.144777] [d2 loss: 0.171417]  [sq d1 d2: 0.000710]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 380/676] [D loss: -0.058864] [G loss: -0.422051] [d1 loss: 0.085673] [d2 loss: 0.075414]  [sq d1 d2: 0.000105]  [num0: 17.000000] [num1 47.000000]
[Epoch 292/500] [Batch 400/676] [D loss: -0.000993] [G loss: -0.449034] [d1 loss: 0.137908] [d2 loss: 0.115394]  [sq d1 d2: 0.000507]  [num0: 17.000000] [num1 47.000000]
[Epoch 292/500] [Batch 420/676] [D loss: -0.032927] [G loss: -0.441987] [d1 loss: 0.046188] [d2 loss: 0.059036]  [sq d1 d2: 0.000165]  [num0: 20.000000] [num1 44.000000]
[Epoch 292/500] [Batch 440/676] [D loss: -0.036793] [G loss: -0.432872] [d1 loss: 0.119469] [d2 loss: 0.130857]  [sq d1 d2: 0.000130]  [num0: 20.000000] [num1 44.000000]
[Epoch 292/500] [Batch 460/676] [D loss: 0.016226] [G loss: -0.431436] [d1 loss: 0.088959] [d2 loss: 0.092121]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 480/676] [D loss: -0.034919] [G loss: -0.429911] [d1 loss: 0.070140] [d2 loss: 0.069751]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 500/676] [D loss: -0.026405] [G loss: -0.333223] [d1 loss: 0.073236] [d2 loss: 0.070099]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 520/676] [D loss: -0.000434] [G loss: -0.285191] [d1 loss: 0.184411] [d2 loss: 0.170011]  [sq d1 d2: 0.000207]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 540/676] [D loss: 0.006912] [G loss: -0.244746] [d1 loss: 0.077676] [d2 loss: 0.076823]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 292/500] [Batch 560/676] [D loss: -0.007406] [G loss: -0.182787] [d1 loss: 0.164776] [d2 loss: 0.140239]  [sq d1 d2: 0.000602]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 580/676] [D loss: -0.019650] [G loss: -0.152692] [d1 loss: 0.035186] [d2 loss: 0.039694]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 292/500] [Batch 600/676] [D loss: -0.019793] [G loss: -0.144768] [d1 loss: 0.100144] [d2 loss: 0.082700]  [sq d1 d2: 0.000304]  [num0: 15.000000] [num1 49.000000]
[Epoch 292/500] [Batch 620/676] [D loss: 0.001495] [G loss: -0.085765] [d1 loss: 0.063192] [d2 loss: 0.066114]  [sq d1 d2: 0.000009]  [num0: 12.000000] [num1 52.000000]
[Epoch 292/500] [Batch 640/676] [D loss: -0.031510] [G loss: -0.050840] [d1 loss: 0.108287] [d2 loss: 0.091512]  [sq d1 d2: 0.000281]  [num0: 18.000000] [num1 46.000000]
[Epoch 292/500] [Batch 660/676] [D loss: -0.000938] [G loss: -0.001840] [d1 loss: 0.080806] [d2 loss: 0.074801]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 293/500] [Batch 0/676] [D loss: -0.023099] [G loss: 0.000322] [d1 loss: 0.103871] [d2 loss: 0.115972]  [sq d1 d2: 0.000146]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 20/676] [D loss: -0.014439] [G loss: 0.020608] [d1 loss: 0.102940] [d2 loss: 0.086817]  [sq d1 d2: 0.000260]  [num0: 16.000000] [num1 48.000000]
[Epoch 293/500] [Batch 40/676] [D loss: -0.019321] [G loss: 0.079995] [d1 loss: 0.059647] [d2 loss: 0.058181]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 293/500] [Batch 60/676] [D loss: -0.011793] [G loss: 0.036799] [d1 loss: 0.053111] [d2 loss: 0.051438]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 293/500] [Batch 80/676] [D loss: 0.027665] [G loss: 0.065649] [d1 loss: 0.114667] [d2 loss: 0.107132]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 293/500] [Batch 100/676] [D loss: -0.007632] [G loss: 0.081968] [d1 loss: 0.178706] [d2 loss: 0.201378]  [sq d1 d2: 0.000514]  [num0: 17.000000] [num1 47.000000]
[Epoch 293/500] [Batch 120/676] [D loss: -0.010263] [G loss: 0.091580] [d1 loss: 0.063872] [d2 loss: 0.054319]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 140/676] [D loss: -0.009064] [G loss: 0.088358] [d1 loss: 0.061792] [d2 loss: 0.058083]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 293/500] [Batch 160/676] [D loss: 0.009747] [G loss: 0.106115] [d1 loss: 0.046816] [d2 loss: 0.057923]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]
[Epoch 293/500] [Batch 180/676] [D loss: 0.005953] [G loss: 0.121612] [d1 loss: 0.071333] [d2 loss: 0.080768]  [sq d1 d2: 0.000089]  [num0: 12.000000] [num1 52.000000]
[Epoch 293/500] [Batch 200/676] [D loss: -0.014390] [G loss: 0.122104] [d1 loss: 0.034437] [d2 loss: 0.037395]  [sq d1 d2: 0.000009]  [num0: 9.000000] [num1 55.000000]
[Epoch 293/500] [Batch 220/676] [D loss: -0.012223] [G loss: 0.107187] [d1 loss: 0.089235] [d2 loss: 0.069605]  [sq d1 d2: 0.000385]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 240/676] [D loss: -0.001529] [G loss: 0.076451] [d1 loss: 0.069665] [d2 loss: 0.080506]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 293/500] [Batch 260/676] [D loss: -0.016678] [G loss: 0.075426] [d1 loss: 0.152358] [d2 loss: 0.140529]  [sq d1 d2: 0.000140]  [num0: 17.000000] [num1 47.000000]

[Epoch 293/500] [Batch 280/676] [D loss: 0.015369] [G loss: 0.065423] [d1 loss: 0.042887] [d2 loss: 0.052126]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 293/500] [Batch 300/676] [D loss: -0.018480] [G loss: 0.053118] [d1 loss: 0.056251] [d2 loss: 0.068211]  [sq d1 d2: 0.000143]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 320/676] [D loss: -0.012006] [G loss: 0.057931] [d1 loss: 0.082170] [d2 loss: 0.093027]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 340/676] [D loss: -0.032008] [G loss: 0.026832] [d1 loss: 0.027926] [d2 loss: 0.047372]  [sq d1 d2: 0.000378]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 360/676] [D loss: 0.003068] [G loss: 0.057042] [d1 loss: 0.048590] [d2 loss: 0.047054]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 293/500] [Batch 380/676] [D loss: -0.017676] [G loss: 0.068741] [d1 loss: 0.132271] [d2 loss: 0.136986]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 293/500] [Batch 400/676] [D loss: -0.007496] [G loss: 0.112337] [d1 loss: 0.086713] [d2 loss: 0.110793]  [sq d1 d2: 0.000580]  [num0: 14.000000] [num1 50.000000]
[Epoch 293/500] [Batch 420/676] [D loss: -0.020620] [G loss: 0.154022] [d1 loss: 0.037877] [d2 loss: 0.039753]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 293/500] [Batch 440/676] [D loss: 0.002215] [G loss: 0.182946] [d1 loss: 0.061941] [d2 loss: 0.051018]  [sq d1 d2: 0.000119]  [num0: 12.000000] [num1 52.000000]
[Epoch 293/500] [Batch 460/676] [D loss: -0.017796] [G loss: 0.194446] [d1 loss: 0.072471] [d2 loss: 0.097196]  [sq d1 d2: 0.000611]  [num0: 17.000000] [num1 47.000000]
[Epoch 293/500] [Batch 480/676] [D loss: 0.014971] [G loss: 0.225553] [d1 loss: 0.100917] [d2 loss: 0.099958]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 293/500] [Batch 500/676] [D loss: -0.014875] [G loss: 0.237807] [d1 loss: 0.096891] [d2 loss: 0.088033]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 293/500] [Batch 520/676] [D loss: -0.030581] [G loss: 0.248112] [d1 loss: 0.065627] [d2 loss: 0.079372]  [sq d1 d2: 0.000189]  [num0: 18.000000] [num1 46.000000]
[Epoch 293/500] [Batch 540/676] [D loss: -0.015955] [G loss: 0.279810] [d1 loss: 0.128850] [d2 loss: 0.134399]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 293/500] [Batch 560/676] [D loss: -0.020714] [G loss: 0.274107] [d1 loss: 0.081302] [d2 loss: 0.099408]  [sq d1 d2: 0.000328]  [num0: 16.000000] [num1 48.000000]
[Epoch 293/500] [Batch 580/676] [D loss: -0.009346] [G loss: 0.224568] [d1 loss: 0.058649] [d2 loss: 0.061349]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 293/500] [Batch 600/676] [D loss: 0.000722] [G loss: 0.241863] [d1 loss: 0.112140] [d2 loss: 0.117990]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 293/500] [Batch 620/676] [D loss: -0.015559] [G loss: 0.212575] [d1 loss: 0.077724] [d2 loss: 0.074702]  [sq d1 d2: 0.000009]  [num0: 20.000000] [num1 44.000000]
[Epoch 293/500] [Batch 640/676] [D loss: 0.008661] [G loss: 0.203655] [d1 loss: 0.120082] [d2 loss: 0.147421]  [sq d1 d2: 0.000747]  [num0: 13.000000] [num1 51.000000]
[Epoch 293/500] [Batch 660/676] [D loss: -0.022363] [G loss: 0.211008] [d1 loss: 0.041372] [d2 loss: 0.041124]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 294/500] [Batch 0/676] [D loss: 0.000156] [G loss: 0.200896] [d1 loss: 0.173259] [d2 loss: 0.159957]  [sq d1 d2: 0.000177]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 20/676] [D loss: -0.020151] [G loss: 0.195157] [d1 loss: 0.107657] [d2 loss: 0.106502]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 294/500] [Batch 40/676] [D loss: -0.038122] [G loss: 0.169018] [d1 loss: 0.083990] [d2 loss: 0.092730]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 294/500] [Batch 60/676] [D loss: -0.021451] [G loss: 0.166682] [d1 loss: 0.103447] [d2 loss: 0.115289]  [sq d1 d2: 0.000140]  [num0: 16.000000] [num1 48.000000]
[Epoch 294/500] [Batch 80/676] [D loss: -0.012353] [G loss: 0.092701] [d1 loss: 0.105784] [d2 loss: 0.083122]  [sq d1 d2: 0.000514]  [num0: 15.000000] [num1 49.000000]
[Epoch 294/500] [Batch 100/676] [D loss: -0.011568] [G loss: 0.017416] [d1 loss: 0.060705] [d2 loss: 0.064387]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 294/500] [Batch 120/676] [D loss: 0.007137] [G loss: 0.036866] [d1 loss: 0.037212] [d2 loss: 0.046217]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 294/500] [Batch 140/676] [D loss: 0.011843] [G loss: 0.000469] [d1 loss: 0.093389] [d2 loss: 0.093229]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 294/500] [Batch 160/676] [D loss: -0.026267] [G loss: -0.004775] [d1 loss: 0.046621] [d2 loss: 0.037331]  [sq d1 d2: 0.000086]  [num0: 10.000000] [num1 54.000000]
[Epoch 294/500] [Batch 180/676] [D loss: -0.024043] [G loss: 0.024539] [d1 loss: 0.091254] [d2 loss: 0.094354]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 200/676] [D loss: 0.007465] [G loss: -0.013734] [d1 loss: 0.152084] [d2 loss: 0.130892]  [sq d1 d2: 0.000449]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 220/676] [D loss: 0.014145] [G loss: -0.007923] [d1 loss: 0.101038] [d2 loss: 0.096431]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 294/500] [Batch 240/676] [D loss: -0.014542] [G loss: -0.057383] [d1 loss: 0.146226] [d2 loss: 0.141601]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 294/500] [Batch 260/676] [D loss: -0.007056] [G loss: -0.054853] [d1 loss: 0.108472] [d2 loss: 0.114644]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 294/500] [Batch 280/676] [D loss: 0.000101] [G loss: -0.064495] [d1 loss: 0.077133] [d2 loss: 0.070918]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 300/676] [D loss: -0.010859] [G loss: -0.094287] [d1 loss: 0.131154] [d2 loss: 0.130534]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 294/500] [Batch 320/676] [D loss: 0.008018] [G loss: -0.036244] [d1 loss: 0.027242] [d2 loss: 0.027895]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 294/500] [Batch 340/676] [D loss: -0.043165] [G loss: -0.014547] [d1 loss: 0.087076] [d2 loss: 0.075007]  [sq d1 d2: 0.000146]  [num0: 14.000000] [num1 50.000000]
[Epoch 294/500] [Batch 360/676] [D loss: -0.049996] [G loss: -0.038164] [d1 loss: 0.118824] [d2 loss: 0.117832]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 380/676] [D loss: -0.022128] [G loss: -0.002614] [d1 loss: 0.074308] [d2 loss: 0.082036]  [sq d1 d2: 0.000060]  [num0: 21.000000] [num1 43.000000]
[Epoch 294/500] [Batch 400/676] [D loss: -0.004081] [G loss: 0.014611] [d1 loss: 0.051742] [d2 loss: 0.071615]  [sq d1 d2: 0.000395]  [num0: 17.000000] [num1 47.000000]
[Epoch 294/500] [Batch 420/676] [D loss: -0.000332] [G loss: 0.094348] [d1 loss: 0.092754] [d2 loss: 0.073759]  [sq d1 d2: 0.000361]  [num0: 14.000000] [num1 50.000000]
[Epoch 294/500] [Batch 440/676] [D loss: -0.009266] [G loss: 0.107234] [d1 loss: 0.123333] [d2 loss: 0.100016]  [sq d1 d2: 0.000544]  [num0: 16.000000] [num1 48.000000]
[Epoch 294/500] [Batch 460/676] [D loss: -0.032017] [G loss: 0.110084] [d1 loss: 0.061923] [d2 loss: 0.069944]  [sq d1 d2: 0.000064]  [num0: 15.000000] [num1 49.000000]
[Epoch 294/500] [Batch 480/676] [D loss: -0.023659] [G loss: 0.109639] [d1 loss: 0.116973] [d2 loss: 0.102637]  [sq d1 d2: 0.000206]  [num0: 13.000000] [num1 51.000000]
[Epoch 294/500] [Batch 500/676] [D loss: -0.027774] [G loss: 0.104151] [d1 loss: 0.122547] [d2 loss: 0.107365]  [sq d1 d2: 0.000230]  [num0: 19.000000] [num1 45.000000]
[Epoch 294/500] [Batch 520/676] [D loss: -0.035402] [G loss: 0.072149] [d1 loss: 0.063698] [d2 loss: 0.070057]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 294/500] [Batch 540/676] [D loss: -0.000770] [G loss: 0.026232] [d1 loss: 0.046551] [d2 loss: 0.038010]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 294/500] [Batch 560/676] [D loss: -0.007166] [G loss: 0.008933] [d1 loss: 0.074906] [d2 loss: 0.082874]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 294/500] [Batch 580/676] [D loss: -0.001373] [G loss: -0.039975] [d1 loss: 0.063635] [d2 loss: 0.058374]  [sq d1 d2: 0.000028]  [num0: 11.000000] [num1 53.000000]
[Epoch 294/500] [Batch 600/676] [D loss: -0.008101] [G loss: -0.014965] [d1 loss: 0.069255] [d2 loss: 0.057002]  [sq d1 d2: 0.000150]  [num0: 13.000000] [num1 51.000000]
[Epoch 294/500] [Batch 620/676] [D loss: -0.024449] [G loss: -0.046738] [d1 loss: 0.056472] [d2 loss: 0.064390]  [sq d1 d2: 0.000063]  [num0: 12.000000] [num1 52.000000]

[Epoch 294/500] [Batch 640/676] [D loss: 0.009047] [G loss: -0.103385] [d1 loss: 0.096232] [d2 loss: 0.099322]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 294/500] [Batch 660/676] [D loss: -0.023170] [G loss: -0.100162] [d1 loss: 0.181803] [d2 loss: 0.175161]  [sq d1 d2: 0.000044]  [num0: 19.000000] [num1 45.000000]
[Epoch 295/500] [Batch 0/676] [D loss: 0.003327] [G loss: -0.116647] [d1 loss: 0.058188] [d2 loss: 0.071922]  [sq d1 d2: 0.000189]  [num0: 11.000000] [num1 53.000000]
[Epoch 295/500] [Batch 20/676] [D loss: -0.019456] [G loss: -0.161119] [d1 loss: 0.154862] [d2 loss: 0.151606]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 40/676] [D loss: -0.018036] [G loss: -0.200955] [d1 loss: 0.013917] [d2 loss: 0.009119]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 60/676] [D loss: -0.014753] [G loss: -0.180026] [d1 loss: 0.235910] [d2 loss: 0.204799]  [sq d1 d2: 0.000968]  [num0: 20.000000] [num1 44.000000]
[Epoch 295/500] [Batch 80/676] [D loss: -0.002751] [G loss: -0.209189] [d1 loss: 0.090457] [d2 loss: 0.058581]  [sq d1 d2: 0.001016]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 100/676] [D loss: 0.008962] [G loss: -0.213388] [d1 loss: 0.060333] [d2 loss: 0.055321]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 120/676] [D loss: -0.042433] [G loss: -0.229884] [d1 loss: 0.126109] [d2 loss: 0.119979]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 295/500] [Batch 140/676] [D loss: -0.018499] [G loss: -0.151270] [d1 loss: 0.109222] [d2 loss: 0.106920]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 160/676] [D loss: -0.014224] [G loss: -0.109102] [d1 loss: 0.079189] [d2 loss: 0.089331]  [sq d1 d2: 0.000103]  [num0: 20.000000] [num1 44.000000]
[Epoch 295/500] [Batch 180/676] [D loss: -0.019178] [G loss: -0.117566] [d1 loss: 0.221112] [d2 loss: 0.172657]  [sq d1 d2: 0.002348]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 200/676] [D loss: -0.003160] [G loss: -0.040243] [d1 loss: 0.039542] [d2 loss: 0.041554]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 295/500] [Batch 220/676] [D loss: -0.000538] [G loss: 0.018179] [d1 loss: 0.076767] [d2 loss: 0.072041]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 295/500] [Batch 240/676] [D loss: 0.010637] [G loss: 0.063162] [d1 loss: 0.043523] [d2 loss: 0.044566]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 295/500] [Batch 260/676] [D loss: 0.004092] [G loss: 0.084363] [d1 loss: 0.034453] [d2 loss: 0.050631]  [sq d1 d2: 0.000262]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 280/676] [D loss: -0.029913] [G loss: 0.124257] [d1 loss: 0.044684] [d2 loss: 0.047105]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 295/500] [Batch 300/676] [D loss: -0.028218] [G loss: 0.141896] [d1 loss: 0.061915] [d2 loss: 0.035720]  [sq d1 d2: 0.000686]  [num0: 16.000000] [num1 48.000000]
[Epoch 295/500] [Batch 320/676] [D loss: -0.007979] [G loss: 0.173471] [d1 loss: 0.047746] [d2 loss: 0.046511]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 295/500] [Batch 340/676] [D loss: -0.015951] [G loss: 0.182384] [d1 loss: 0.066037] [d2 loss: 0.065307]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 295/500] [Batch 360/676] [D loss: 0.002585] [G loss: 0.188180] [d1 loss: 0.067784] [d2 loss: 0.090397]  [sq d1 d2: 0.000511]  [num0: 20.000000] [num1 44.000000]
[Epoch 295/500] [Batch 380/676] [D loss: -0.007695] [G loss: 0.187124] [d1 loss: 0.061773] [d2 loss: 0.065527]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 400/676] [D loss: -0.020802] [G loss: 0.205351] [d1 loss: 0.055175] [d2 loss: 0.060169]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 295/500] [Batch 420/676] [D loss: -0.017494] [G loss: 0.165294] [d1 loss: 0.032155] [d2 loss: 0.030205]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 295/500] [Batch 440/676] [D loss: -0.025054] [G loss: 0.177456] [d1 loss: 0.121913] [d2 loss: 0.077075]  [sq d1 d2: 0.002010]  [num0: 15.000000] [num1 49.000000]
[Epoch 295/500] [Batch 460/676] [D loss: -0.000728] [G loss: 0.177501] [d1 loss: 0.087761] [d2 loss: 0.067423]  [sq d1 d2: 0.000414]  [num0: 16.000000] [num1 48.000000]
[Epoch 295/500] [Batch 480/676] [D loss: -0.017454] [G loss: 0.158902] [d1 loss: 0.038032] [d2 loss: 0.057455]  [sq d1 d2: 0.000377]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 500/676] [D loss: -0.021924] [G loss: 0.178853] [d1 loss: 0.116687] [d2 loss: 0.144206]  [sq d1 d2: 0.000757]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 520/676] [D loss: -0.008330] [G loss: 0.153640] [d1 loss: 0.030422] [d2 loss: 0.025720]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 295/500] [Batch 540/676] [D loss: -0.036268] [G loss: 0.093611] [d1 loss: 0.067448] [d2 loss: 0.057473]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 295/500] [Batch 560/676] [D loss: -0.031844] [G loss: 0.098137] [d1 loss: 0.047037] [d2 loss: 0.030620]  [sq d1 d2: 0.000270]  [num0: 15.000000] [num1 49.000000]
[Epoch 295/500] [Batch 580/676] [D loss: -0.007201] [G loss: 0.061033] [d1 loss: 0.058763] [d2 loss: 0.062132]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 295/500] [Batch 600/676] [D loss: -0.018898] [G loss: 0.008484] [d1 loss: 0.126522] [d2 loss: 0.132524]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 295/500] [Batch 620/676] [D loss: -0.027287] [G loss: 0.018819] [d1 loss: 0.051253] [d2 loss: 0.049270]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 295/500] [Batch 640/676] [D loss: -0.006918] [G loss: 0.006896] [d1 loss: 0.140285] [d2 loss: 0.137837]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 295/500] [Batch 660/676] [D loss: -0.018298] [G loss: -0.028637] [d1 loss: 0.031462] [d2 loss: 0.031734]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 0/676] [D loss: -0.012125] [G loss: -0.001988] [d1 loss: 0.093272] [d2 loss: 0.090801]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 296/500] [Batch 20/676] [D loss: 0.007834] [G loss: 0.008083] [d1 loss: 0.080636] [d2 loss: 0.076404]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 296/500] [Batch 40/676] [D loss: -0.017242] [G loss: -0.001369] [d1 loss: 0.147836] [d2 loss: 0.179463]  [sq d1 d2: 0.001000]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 60/676] [D loss: 0.008421] [G loss: 0.025325] [d1 loss: 0.067523] [d2 loss: 0.060417]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 296/500] [Batch 80/676] [D loss: -0.014876] [G loss: 0.053120] [d1 loss: 0.119125] [d2 loss: 0.111495]  [sq d1 d2: 0.000058]  [num0: 18.000000] [num1 46.000000]
[Epoch 296/500] [Batch 100/676] [D loss: -0.020622] [G loss: 0.100386] [d1 loss: 0.076052] [d2 loss: 0.084851]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 120/676] [D loss: -0.001757] [G loss: 0.161796] [d1 loss: 0.074498] [d2 loss: 0.069358]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 140/676] [D loss: -0.038855] [G loss: 0.171409] [d1 loss: 0.082046] [d2 loss: 0.100450]  [sq d1 d2: 0.000339]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 160/676] [D loss: -0.013259] [G loss: 0.205882] [d1 loss: 0.047208] [d2 loss: 0.043556]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 180/676] [D loss: -0.040311] [G loss: 0.179397] [d1 loss: 0.096686] [d2 loss: 0.118115]  [sq d1 d2: 0.000459]  [num0: 12.000000] [num1 52.000000]
[Epoch 296/500] [Batch 200/676] [D loss: -0.029253] [G loss: 0.148692] [d1 loss: 0.043931] [d2 loss: 0.054061]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 220/676] [D loss: 0.003512] [G loss: 0.152323] [d1 loss: 0.033952] [d2 loss: 0.031873]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 240/676] [D loss: -0.021454] [G loss: 0.148840] [d1 loss: 0.062009] [d2 loss: 0.061614]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 260/676] [D loss: -0.012132] [G loss: 0.127674] [d1 loss: 0.103435] [d2 loss: 0.103977]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 296/500] [Batch 280/676] [D loss: -0.024497] [G loss: 0.080210] [d1 loss: 0.045936] [d2 loss: 0.039707]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 300/676] [D loss: -0.007073] [G loss: 0.079220] [d1 loss: 0.125512] [d2 loss: 0.116777]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]

[Epoch 296/500] [Batch 320/676] [D loss: 0.003741] [G loss: 0.035462] [d1 loss: 0.033230] [d2 loss: 0.025563]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 340/676] [D loss: -0.009936] [G loss: 0.021750] [d1 loss: 0.097636] [d2 loss: 0.106305]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 296/500] [Batch 360/676] [D loss: -0.015403] [G loss: -0.008000] [d1 loss: 0.066881] [d2 loss: 0.049497]  [sq d1 d2: 0.000302]  [num0: 12.000000] [num1 52.000000]
[Epoch 296/500] [Batch 380/676] [D loss: -0.011937] [G loss: -0.023997] [d1 loss: 0.022782] [d2 loss: 0.021911]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 400/676] [D loss: -0.016954] [G loss: -0.061030] [d1 loss: 0.096430] [d2 loss: 0.089542]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 296/500] [Batch 420/676] [D loss: -0.033603] [G loss: -0.058754] [d1 loss: 0.022133] [d2 loss: 0.021416]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 440/676] [D loss: -0.023440] [G loss: -0.086790] [d1 loss: 0.032961] [d2 loss: 0.035051]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 460/676] [D loss: -0.020744] [G loss: -0.110149] [d1 loss: 0.118595] [d2 loss: 0.095357]  [sq d1 d2: 0.000540]  [num0: 18.000000] [num1 46.000000]
[Epoch 296/500] [Batch 480/676] [D loss: 0.016990] [G loss: -0.159721] [d1 loss: 0.032477] [d2 loss: 0.035895]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 500/676] [D loss: -0.024618] [G loss: -0.125230] [d1 loss: 0.056539] [d2 loss: 0.056227]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 296/500] [Batch 520/676] [D loss: -0.010267] [G loss: -0.109096] [d1 loss: 0.094950] [d2 loss: 0.096404]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 540/676] [D loss: 0.008419] [G loss: -0.091835] [d1 loss: 0.198596] [d2 loss: 0.148386]  [sq d1 d2: 0.002521]  [num0: 19.000000] [num1 45.000000]
[Epoch 296/500] [Batch 560/676] [D loss: -0.005710] [G loss: -0.069332] [d1 loss: 0.054864] [d2 loss: 0.088687]  [sq d1 d2: 0.001144]  [num0: 15.000000] [num1 49.000000]
[Epoch 296/500] [Batch 580/676] [D loss: -0.005101] [G loss: -0.060778] [d1 loss: 0.130446] [d2 loss: 0.087760]  [sq d1 d2: 0.001822]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 600/676] [D loss: 0.006710] [G loss: -0.017862] [d1 loss: 0.070729] [d2 loss: 0.067706]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 620/676] [D loss: -0.028409] [G loss: -0.005432] [d1 loss: 0.078262] [d2 loss: 0.079517]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 296/500] [Batch 640/676] [D loss: -0.000802] [G loss: -0.000090] [d1 loss: 0.096183] [d2 loss: 0.097505]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 296/500] [Batch 660/676] [D loss: -0.009830] [G loss: 0.040115] [d1 loss: 0.085248] [d2 loss: 0.081103]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 297/500] [Batch 0/676] [D loss: -0.013066] [G loss: 0.026785] [d1 loss: 0.556488] [d2 loss: 0.455245]  [sq d1 d2: 0.010250]  [num0: 13.000000] [num1 51.000000]
[Epoch 297/500] [Batch 20/676] [D loss: -0.007312] [G loss: 0.084139] [d1 loss: 0.053409] [d2 loss: 0.052607]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 40/676] [D loss: -0.031004] [G loss: 0.109746] [d1 loss: 0.078218] [d2 loss: 0.083848]  [sq d1 d2: 0.000032]  [num0: 14.000000] [num1 50.000000]
[Epoch 297/500] [Batch 60/676] [D loss: 0.003372] [G loss: 0.078487] [d1 loss: 0.030319] [d2 loss: 0.030332]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 297/500] [Batch 80/676] [D loss: 0.003624] [G loss: 0.057382] [d1 loss: 0.084937] [d2 loss: 0.088201]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 297/500] [Batch 100/676] [D loss: -0.024567] [G loss: 0.070578] [d1 loss: 0.070477] [d2 loss: 0.056853]  [sq d1 d2: 0.000186]  [num0: 14.000000] [num1 50.000000]
[Epoch 297/500] [Batch 120/676] [D loss: 0.004443] [G loss: 0.083496] [d1 loss: 0.030257] [d2 loss: 0.028616]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 297/500] [Batch 140/676] [D loss: 0.003085] [G loss: 0.017112] [d1 loss: 0.112773] [d2 loss: 0.095270]  [sq d1 d2: 0.000306]  [num0: 14.000000] [num1 50.000000]
[Epoch 297/500] [Batch 160/676] [D loss: -0.019761] [G loss: -0.033326] [d1 loss: 0.089095] [d2 loss: 0.071978]  [sq d1 d2: 0.000293]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 180/676] [D loss: -0.010621] [G loss: -0.008370] [d1 loss: 0.044596] [d2 loss: 0.047611]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 297/500] [Batch 200/676] [D loss: -0.038648] [G loss: -0.028376] [d1 loss: 0.059485] [d2 loss: 0.055245]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 220/676] [D loss: -0.012538] [G loss: -0.045500] [d1 loss: 0.057745] [d2 loss: 0.062518]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 297/500] [Batch 240/676] [D loss: -0.037920] [G loss: -0.045085] [d1 loss: 0.026315] [d2 loss: 0.026787]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 260/676] [D loss: 0.005578] [G loss: -0.073925] [d1 loss: 0.217176] [d2 loss: 0.188697]  [sq d1 d2: 0.000811]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 280/676] [D loss: -0.012837] [G loss: -0.080968] [d1 loss: 0.051098] [d2 loss: 0.071826]  [sq d1 d2: 0.000430]  [num0: 12.000000] [num1 52.000000]
[Epoch 297/500] [Batch 300/676] [D loss: -0.019760] [G loss: -0.082709] [d1 loss: 0.113858] [d2 loss: 0.124198]  [sq d1 d2: 0.000107]  [num0: 18.000000] [num1 46.000000]
[Epoch 297/500] [Batch 320/676] [D loss: 0.009784] [G loss: -0.108509] [d1 loss: 0.061203] [d2 loss: 0.064825]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 297/500] [Batch 340/676] [D loss: 0.002090] [G loss: -0.083687] [d1 loss: 0.113314] [d2 loss: 0.092415]  [sq d1 d2: 0.000437]  [num0: 19.000000] [num1 45.000000]
[Epoch 297/500] [Batch 360/676] [D loss: -0.003137] [G loss: -0.076613] [d1 loss: 0.128056] [d2 loss: 0.111969]  [sq d1 d2: 0.000259]  [num0: 14.000000] [num1 50.000000]
[Epoch 297/500] [Batch 380/676] [D loss: 0.001956] [G loss: -0.063895] [d1 loss: 0.090067] [d2 loss: 0.087897]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 400/676] [D loss: -0.005555] [G loss: -0.024693] [d1 loss: 0.080672] [d2 loss: 0.088107]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 420/676] [D loss: -0.012180] [G loss: 0.006338] [d1 loss: 0.040210] [d2 loss: 0.041537]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 297/500] [Batch 440/676] [D loss: -0.020112] [G loss: 0.038211] [d1 loss: 0.046187] [d2 loss: 0.053903]  [sq d1 d2: 0.000060]  [num0: 12.000000] [num1 52.000000]
[Epoch 297/500] [Batch 460/676] [D loss: -0.001475] [G loss: 0.063154] [d1 loss: 0.035706] [d2 loss: 0.044158]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 480/676] [D loss: -0.004752] [G loss: 0.076259] [d1 loss: 0.062814] [d2 loss: 0.059256]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 297/500] [Batch 500/676] [D loss: -0.016028] [G loss: 0.095029] [d1 loss: 0.064261] [d2 loss: 0.067589]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 520/676] [D loss: -0.025160] [G loss: 0.075308] [d1 loss: 0.101729] [d2 loss: 0.099239]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 297/500] [Batch 540/676] [D loss: -0.029449] [G loss: 0.037916] [d1 loss: 0.085670] [d2 loss: 0.047367]  [sq d1 d2: 0.001467]  [num0: 15.000000] [num1 49.000000]
[Epoch 297/500] [Batch 560/676] [D loss: -0.007382] [G loss: 0.092530] [d1 loss: 0.071858] [d2 loss: 0.076863]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 297/500] [Batch 580/676] [D loss: -0.014664] [G loss: 0.134628] [d1 loss: 0.007880] [d2 loss: 0.012093]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 297/500] [Batch 600/676] [D loss: -0.016486] [G loss: 0.111278] [d1 loss: 0.024980] [d2 loss: 0.022105]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]

[Epoch 297/500] [Batch 620/676] [D loss: -0.004930] [G loss: 0.148506] [d1 loss: 0.108269] [d2 loss: 0.101700]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 297/500] [Batch 640/676] [D loss: -0.010700] [G loss: 0.143579] [d1 loss: 0.010862] [d2 loss: 0.015777]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 297/500] [Batch 660/676] [D loss: 0.013818] [G loss: 0.098553] [d1 loss: 0.098466] [d2 loss: 0.087707]  [sq d1 d2: 0.000116]  [num0: 17.000000] [num1 47.000000]
[Epoch 298/500] [Batch 0/676] [D loss: 0.000836] [G loss: 0.126730] [d1 loss: 0.085828] [d2 loss: 0.080985]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 20/676] [D loss: 0.007653] [G loss: 0.055023] [d1 loss: 0.082237] [d2 loss: 0.074679]  [sq d1 d2: 0.000057]  [num0: 19.000000] [num1 45.000000]
[Epoch 298/500] [Batch 40/676] [D loss: -0.016501] [G loss: 0.029940] [d1 loss: 0.082905] [d2 loss: 0.084699]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 298/500] [Batch 60/676] [D loss: -0.009572] [G loss: 0.026791] [d1 loss: 0.031858] [d2 loss: 0.030487]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 80/676] [D loss: -0.002621] [G loss: 0.016413] [d1 loss: 0.050328] [d2 loss: 0.045826]  [sq d1 d2: 0.000020]  [num0: 12.000000] [num1 52.000000]
[Epoch 298/500] [Batch 100/676] [D loss: 0.003954] [G loss: -0.016813] [d1 loss: 0.071428] [d2 loss: 0.069771]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 120/676] [D loss: -0.021469] [G loss: 0.009510] [d1 loss: 0.082419] [d2 loss: 0.067622]  [sq d1 d2: 0.000219]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 140/676] [D loss: -0.014594] [G loss: -0.014957] [d1 loss: 0.053945] [d2 loss: 0.050285]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 160/676] [D loss: -0.036356] [G loss: -0.041747] [d1 loss: 0.100550] [d2 loss: 0.119654]  [sq d1 d2: 0.000365]  [num0: 13.000000] [num1 51.000000]
[Epoch 298/500] [Batch 180/676] [D loss: -0.019545] [G loss: -0.081584] [d1 loss: 0.041217] [d2 loss: 0.029489]  [sq d1 d2: 0.000138]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 200/676] [D loss: -0.005848] [G loss: -0.086741] [d1 loss: 0.063461] [d2 loss: 0.058705]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 220/676] [D loss: 0.001067] [G loss: -0.125903] [d1 loss: 0.058348] [d2 loss: 0.052952]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 240/676] [D loss: -0.006775] [G loss: -0.142561] [d1 loss: 0.042652] [d2 loss: 0.047000]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 260/676] [D loss: -0.001384] [G loss: -0.099012] [d1 loss: 0.046091] [d2 loss: 0.047712]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 298/500] [Batch 280/676] [D loss: -0.019843] [G loss: -0.104019] [d1 loss: 0.112041] [d2 loss: 0.093780]  [sq d1 d2: 0.000333]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 300/676] [D loss: -0.017514] [G loss: -0.112048] [d1 loss: 0.090280] [d2 loss: 0.071405]  [sq d1 d2: 0.000356]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 320/676] [D loss: -0.010145] [G loss: -0.126366] [d1 loss: 0.077846] [d2 loss: 0.084393]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 340/676] [D loss: -0.011949] [G loss: -0.118826] [d1 loss: 0.057505] [d2 loss: 0.052447]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 298/500] [Batch 360/676] [D loss: -0.003770] [G loss: -0.116835] [d1 loss: 0.041349] [d2 loss: 0.041940]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 298/500] [Batch 380/676] [D loss: -0.027612] [G loss: -0.074477] [d1 loss: 0.023580] [d2 loss: 0.018526]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 400/676] [D loss: -0.021491] [G loss: -0.056956] [d1 loss: 0.074173] [d2 loss: 0.075973]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 420/676] [D loss: 0.017123] [G loss: -0.036922] [d1 loss: 0.056816] [d2 loss: 0.053588]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 298/500] [Batch 440/676] [D loss: 0.008022] [G loss: -0.068351] [d1 loss: 0.077576] [d2 loss: 0.079467]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 298/500] [Batch 460/676] [D loss: -0.001216] [G loss: -0.024649] [d1 loss: 0.055322] [d2 loss: 0.041825]  [sq d1 d2: 0.000182]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 480/676] [D loss: -0.016818] [G loss: -0.014818] [d1 loss: 0.030817] [d2 loss: 0.029018]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 298/500] [Batch 500/676] [D loss: -0.015579] [G loss: -0.017225] [d1 loss: 0.119243] [d2 loss: 0.105826]  [sq d1 d2: 0.000180]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 520/676] [D loss: 0.006597] [G loss: 0.014203] [d1 loss: 0.033267] [d2 loss: 0.036678]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 540/676] [D loss: -0.000693] [G loss: 0.063385] [d1 loss: 0.036062] [d2 loss: 0.027945]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 560/676] [D loss: -0.022982] [G loss: 0.077447] [d1 loss: 0.065898] [d2 loss: 0.070575]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 298/500] [Batch 580/676] [D loss: 0.003813] [G loss: 0.080596] [d1 loss: 0.068134] [d2 loss: 0.062303]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 298/500] [Batch 600/676] [D loss: -0.011663] [G loss: 0.099095] [d1 loss: 0.051702] [d2 loss: 0.050912]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 298/500] [Batch 620/676] [D loss: -0.025808] [G loss: 0.139982] [d1 loss: 0.069866] [d2 loss: 0.069650]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 298/500] [Batch 640/676] [D loss: -0.008419] [G loss: 0.095256] [d1 loss: 0.065319] [d2 loss: 0.074828]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 298/500] [Batch 660/676] [D loss: -0.012891] [G loss: 0.080376] [d1 loss: 0.057694] [d2 loss: 0.058884]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 0/676] [D loss: 0.007469] [G loss: 0.098472] [d1 loss: 0.118267] [d2 loss: 0.095073]  [sq d1 d2: 0.000538]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 20/676] [D loss: -0.011928] [G loss: 0.109459] [d1 loss: 0.026232] [d2 loss: 0.022371]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 40/676] [D loss: -0.015570] [G loss: 0.085368] [d1 loss: 0.023146] [d2 loss: 0.030254]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 60/676] [D loss: -0.028082] [G loss: 0.102720] [d1 loss: 0.070173] [d2 loss: 0.050068]  [sq d1 d2: 0.000404]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 80/676] [D loss: 0.017465] [G loss: 0.059505] [d1 loss: 0.025530] [d2 loss: 0.020953]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 100/676] [D loss: -0.019948] [G loss: 0.070636] [d1 loss: 0.122209] [d2 loss: 0.087523]  [sq d1 d2: 0.001203]  [num0: 15.000000] [num1 49.000000]
[Epoch 299/500] [Batch 120/676] [D loss: -0.004090] [G loss: 0.059814] [d1 loss: 0.044011] [d2 loss: 0.043509]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 140/676] [D loss: -0.010562] [G loss: 0.020160] [d1 loss: 0.050106] [d2 loss: 0.026179]  [sq d1 d2: 0.000573]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 160/676] [D loss: -0.009492] [G loss: 0.018900] [d1 loss: 0.070369] [d2 loss: 0.065405]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 180/676] [D loss: -0.009388] [G loss: 0.005387] [d1 loss: 0.046417] [d2 loss: 0.041592]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 299/500] [Batch 200/676] [D loss: -0.016401] [G loss: 0.016895] [d1 loss: 0.045205] [d2 loss: 0.024522]  [sq d1 d2: 0.000428]  [num0: 13.000000] [num1 51.000000]
[Epoch 299/500] [Batch 220/676] [D loss: -0.009250] [G loss: -0.041525] [d1 loss: 0.073421] [d2 loss: 0.087586]  [sq d1 d2: 0.000201]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 240/676] [D loss: -0.004169] [G loss: -0.033865] [d1 loss: 0.029860] [d2 loss: 0.034404]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 260/676] [D loss: -0.000446] [G loss: -0.012933] [d1 loss: 0.047924] [d2 loss: 0.062848]  [sq d1 d2: 0.000223]  [num0: 17.000000] [num1 47.000000]

[Epoch 299/500] [Batch 280/676] [D loss: -0.022310] [G loss: -0.036170] [d1 loss: 0.059861] [d2 loss: 0.056469]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 300/676] [D loss: -0.001422] [G loss: -0.047081] [d1 loss: 0.040660] [d2 loss: 0.047347]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 320/676] [D loss: -0.006342] [G loss: -0.074668] [d1 loss: 0.033950] [d2 loss: 0.030593]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 299/500] [Batch 340/676] [D loss: -0.005711] [G loss: -0.082199] [d1 loss: 0.059090] [d2 loss: 0.053153]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 360/676] [D loss: -0.021921] [G loss: -0.105635] [d1 loss: 0.096859] [d2 loss: 0.087645]  [sq d1 d2: 0.000085]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 380/676] [D loss: 0.004288] [G loss: -0.097068] [d1 loss: 0.113205] [d2 loss: 0.113386]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 299/500] [Batch 400/676] [D loss: -0.014968] [G loss: -0.097499] [d1 loss: 0.050184] [d2 loss: 0.054601]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 420/676] [D loss: -0.009244] [G loss: -0.121115] [d1 loss: 0.168417] [d2 loss: 0.159872]  [sq d1 d2: 0.000073]  [num0: 17.000000] [num1 47.000000]
[Epoch 299/500] [Batch 440/676] [D loss: -0.011374] [G loss: -0.131462] [d1 loss: 0.073067] [d2 loss: 0.061360]  [sq d1 d2: 0.000137]  [num0: 13.000000] [num1 51.000000]
[Epoch 299/500] [Batch 460/676] [D loss: -0.015471] [G loss: -0.109460] [d1 loss: 0.089628] [d2 loss: 0.090159]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 299/500] [Batch 480/676] [D loss: -0.001498] [G loss: -0.130837] [d1 loss: 0.051486] [d2 loss: 0.059059]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 299/500] [Batch 500/676] [D loss: -0.019205] [G loss: -0.110148] [d1 loss: 0.066508] [d2 loss: 0.077704]  [sq d1 d2: 0.000125]  [num0: 15.000000] [num1 49.000000]
[Epoch 299/500] [Batch 520/676] [D loss: -0.020514] [G loss: -0.098493] [d1 loss: 0.029900] [d2 loss: 0.028274]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 540/676] [D loss: -0.020021] [G loss: -0.084837] [d1 loss: 0.043086] [d2 loss: 0.045764]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 299/500] [Batch 560/676] [D loss: -0.004886] [G loss: -0.085888] [d1 loss: 0.060774] [d2 loss: 0.056157]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 299/500] [Batch 580/676] [D loss: -0.013494] [G loss: -0.069030] [d1 loss: 0.039238] [d2 loss: 0.035623]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 299/500] [Batch 600/676] [D loss: -0.010468] [G loss: -0.049278] [d1 loss: 0.029794] [d2 loss: 0.032787]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 299/500] [Batch 620/676] [D loss: -0.004575] [G loss: -0.001406] [d1 loss: 0.049003] [d2 loss: 0.041072]  [sq d1 d2: 0.000063]  [num0: 11.000000] [num1 53.000000]
[Epoch 299/500] [Batch 640/676] [D loss: -0.003326] [G loss: 0.010225] [d1 loss: 0.049356] [d2 loss: 0.032977]  [sq d1 d2: 0.000268]  [num0: 20.000000] [num1 44.000000]
[Epoch 299/500] [Batch 660/676] [D loss: -0.011055] [G loss: -0.004318] [d1 loss: 0.038734] [d2 loss: 0.044296]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 0/676] [D loss: -0.006183] [G loss: 0.025878] [d1 loss: 0.112391] [d2 loss: 0.101573]  [sq d1 d2: 0.000117]  [num0: 13.000000] [num1 51.000000]
[Epoch 300/500] [Batch 20/676] [D loss: -0.022256] [G loss: 0.019679] [d1 loss: 0.036184] [d2 loss: 0.041237]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 40/676] [D loss: -0.015295] [G loss: 0.034316] [d1 loss: 0.063355] [d2 loss: 0.061841]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 300/500] [Batch 60/676] [D loss: -0.026902] [G loss: 0.056319] [d1 loss: 0.068737] [d2 loss: 0.054571]  [sq d1 d2: 0.000201]  [num0: 15.000000] [num1 49.000000]
[Epoch 300/500] [Batch 80/676] [D loss: -0.003220] [G loss: 0.084843] [d1 loss: 0.059318] [d2 loss: 0.053274]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 300/500] [Batch 100/676] [D loss: -0.001182] [G loss: 0.027330] [d1 loss: 0.078898] [d2 loss: 0.053074]  [sq d1 d2: 0.000667]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 120/676] [D loss: -0.004547] [G loss: 0.024457] [d1 loss: 0.063633] [d2 loss: 0.081999]  [sq d1 d2: 0.000337]  [num0: 12.000000] [num1 52.000000]
[Epoch 300/500] [Batch 140/676] [D loss: -0.011022] [G loss: 0.065069] [d1 loss: 0.056910] [d2 loss: 0.078663]  [sq d1 d2: 0.000473]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 160/676] [D loss: 0.000980] [G loss: 0.035794] [d1 loss: 0.076613] [d2 loss: 0.058235]  [sq d1 d2: 0.000338]  [num0: 13.000000] [num1 51.000000]
[Epoch 300/500] [Batch 180/676] [D loss: -0.024124] [G loss: 0.012705] [d1 loss: 0.032001] [d2 loss: 0.033151]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 200/676] [D loss: -0.008226] [G loss: 0.023578] [d1 loss: 0.109645] [d2 loss: 0.080396]  [sq d1 d2: 0.000855]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 220/676] [D loss: -0.011893] [G loss: 0.037616] [d1 loss: 0.030179] [d2 loss: 0.022950]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 300/500] [Batch 240/676] [D loss: -0.023017] [G loss: 0.043704] [d1 loss: 0.025313] [d2 loss: 0.015554]  [sq d1 d2: 0.000095]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 260/676] [D loss: -0.010120] [G loss: 0.018028] [d1 loss: 0.027095] [d2 loss: 0.026810]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 300/500] [Batch 280/676] [D loss: -0.006732] [G loss: 0.011456] [d1 loss: 0.113350] [d2 loss: 0.070413]  [sq d1 d2: 0.001844]  [num0: 15.000000] [num1 49.000000]
[Epoch 300/500] [Batch 300/676] [D loss: -0.015862] [G loss: 0.014670] [d1 loss: 0.078295] [d2 loss: 0.075000]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 300/500] [Batch 320/676] [D loss: -0.011055] [G loss: -0.001113] [d1 loss: 0.086892] [d2 loss: 0.070515]  [sq d1 d2: 0.000268]  [num0: 12.000000] [num1 52.000000]
[Epoch 300/500] [Batch 340/676] [D loss: -0.014483] [G loss: 0.040141] [d1 loss: 0.117087] [d2 loss: 0.118014]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 360/676] [D loss: -0.015530] [G loss: 0.009579] [d1 loss: 0.043973] [d2 loss: 0.046827]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 300/500] [Batch 380/676] [D loss: -0.021306] [G loss: 0.002715] [d1 loss: 0.106069] [d2 loss: 0.115843]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 400/676] [D loss: -0.024585] [G loss: 0.025008] [d1 loss: 0.071088] [d2 loss: 0.085888]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 300/500] [Batch 420/676] [D loss: -0.006314] [G loss: 0.053740] [d1 loss: 0.041716] [d2 loss: 0.039186]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 300/500] [Batch 440/676] [D loss: -0.020991] [G loss: 0.060365] [d1 loss: 0.081148] [d2 loss: 0.075569]  [sq d1 d2: 0.000031]  [num0: 22.000000] [num1 42.000000]
[Epoch 300/500] [Batch 460/676] [D loss: -0.027321] [G loss: 0.053799] [d1 loss: 0.069077] [d2 loss: 0.063675]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 300/500] [Batch 480/676] [D loss: 0.002794] [G loss: 0.037258] [d1 loss: 0.059638] [d2 loss: 0.046786]  [sq d1 d2: 0.000165]  [num0: 18.000000] [num1 46.000000]
[Epoch 300/500] [Batch 500/676] [D loss: -0.017533] [G loss: 0.014392] [d1 loss: 0.010385] [d2 loss: 0.010335]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 300/500] [Batch 520/676] [D loss: -0.011752] [G loss: 0.020472] [d1 loss: 0.060426] [d2 loss: 0.065874]  [sq d1 d2: 0.000030]  [num0: 9.000000] [num1 55.000000]
[Epoch 300/500] [Batch 540/676] [D loss: 0.000966] [G loss: 0.036979] [d1 loss: 0.090474] [d2 loss: 0.091661]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 300/500] [Batch 560/676] [D loss: -0.019056] [G loss: 0.004436] [d1 loss: 0.026739] [d2 loss: 0.031852]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 300/500] [Batch 580/676] [D loss: -0.020848] [G loss: -0.003311] [d1 loss: 0.026907] [d2 loss: 0.020727]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 600/676] [D loss: -0.016092] [G loss: -0.014885] [d1 loss: 0.045465] [d2 loss: 0.047411]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 300/500] [Batch 620/676] [D loss: -0.004017] [G loss: -0.009624] [d1 loss: 0.057610] [d2 loss: 0.053480]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]

[Epoch 300/500] [Batch 640/676] [D loss: -0.007670] [G loss: -0.026464] [d1 loss: 0.090020] [d2 loss: 0.090852]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 300/500] [Batch 660/676] [D loss: -0.015026] [G loss: -0.065952] [d1 loss: 0.081948] [d2 loss: 0.082052]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 301/500] [Batch 0/676] [D loss: -0.017555] [G loss: -0.056821] [d1 loss: 0.033118] [d2 loss: 0.035386]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 20/676] [D loss: -0.004213] [G loss: -0.061785] [d1 loss: 0.027932] [d2 loss: 0.028885]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 301/500] [Batch 40/676] [D loss: -0.008181] [G loss: -0.087883] [d1 loss: 0.047419] [d2 loss: 0.047678]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 301/500] [Batch 60/676] [D loss: -0.017899] [G loss: -0.148499] [d1 loss: 0.068641] [d2 loss: 0.058971]  [sq d1 d2: 0.000094]  [num0: 12.000000] [num1 52.000000]
[Epoch 301/500] [Batch 80/676] [D loss: 0.009362] [G loss: -0.100966] [d1 loss: 0.085453] [d2 loss: 0.110721]  [sq d1 d2: 0.000638]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 100/676] [D loss: -0.003776] [G loss: -0.070738] [d1 loss: 0.051363] [d2 loss: 0.044240]  [sq d1 d2: 0.000051]  [num0: 19.000000] [num1 45.000000]
[Epoch 301/500] [Batch 120/676] [D loss: -0.016682] [G loss: -0.051046] [d1 loss: 0.060504] [d2 loss: 0.061194]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 301/500] [Batch 140/676] [D loss: -0.008124] [G loss: -0.028062] [d1 loss: 0.046034] [d2 loss: 0.056912]  [sq d1 d2: 0.000118]  [num0: 13.000000] [num1 51.000000]
[Epoch 301/500] [Batch 160/676] [D loss: -0.009523] [G loss: -0.018427] [d1 loss: 0.092728] [d2 loss: 0.133944]  [sq d1 d2: 0.001699]  [num0: 20.000000] [num1 44.000000]
[Epoch 301/500] [Batch 180/676] [D loss: -0.001938] [G loss: 0.016875] [d1 loss: 0.063779] [d2 loss: 0.049534]  [sq d1 d2: 0.000203]  [num0: 17.000000] [num1 47.000000]
[Epoch 301/500] [Batch 200/676] [D loss: -0.027778] [G loss: 0.022150] [d1 loss: 0.058689] [d2 loss: 0.065250]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 301/500] [Batch 220/676] [D loss: -0.015622] [G loss: 0.050768] [d1 loss: 0.065086] [d2 loss: 0.070338]  [sq d1 d2: 0.000028]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 240/676] [D loss: -0.013055] [G loss: 0.079958] [d1 loss: 0.091384] [d2 loss: 0.069964]  [sq d1 d2: 0.000459]  [num0: 15.000000] [num1 49.000000]
[Epoch 301/500] [Batch 260/676] [D loss: 0.009852] [G loss: 0.108123] [d1 loss: 0.033449] [d2 loss: 0.046388]  [sq d1 d2: 0.000167]  [num0: 19.000000] [num1 45.000000]
[Epoch 301/500] [Batch 280/676] [D loss: -0.033398] [G loss: 0.123524] [d1 loss: 0.051920] [d2 loss: 0.041952]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 301/500] [Batch 300/676] [D loss: 0.004121] [G loss: 0.115913] [d1 loss: 0.036239] [d2 loss: 0.040625]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 301/500] [Batch 320/676] [D loss: -0.011178] [G loss: 0.108448] [d1 loss: 0.186237] [d2 loss: 0.182210]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 301/500] [Batch 340/676] [D loss: -0.025610] [G loss: 0.090363] [d1 loss: 0.074876] [d2 loss: 0.080797]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 301/500] [Batch 360/676] [D loss: -0.002906] [G loss: 0.122561] [d1 loss: 0.095435] [d2 loss: 0.113133]  [sq d1 d2: 0.000313]  [num0: 17.000000] [num1 47.000000]
[Epoch 301/500] [Batch 380/676] [D loss: -0.004148] [G loss: 0.053103] [d1 loss: 0.050183] [d2 loss: 0.063290]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 301/500] [Batch 400/676] [D loss: -0.023763] [G loss: 0.047681] [d1 loss: 0.090847] [d2 loss: 0.105493]  [sq d1 d2: 0.000214]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 420/676] [D loss: -0.008930] [G loss: 0.037587] [d1 loss: 0.025592] [d2 loss: 0.027835]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 301/500] [Batch 440/676] [D loss: -0.015260] [G loss: 0.022091] [d1 loss: 0.041059] [d2 loss: 0.039529]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 301/500] [Batch 460/676] [D loss: -0.013845] [G loss: -0.005743] [d1 loss: 0.052898] [d2 loss: 0.052583]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 301/500] [Batch 480/676] [D loss: -0.012731] [G loss: -0.053313] [d1 loss: 0.056307] [d2 loss: 0.046263]  [sq d1 d2: 0.000101]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 500/676] [D loss: -0.012628] [G loss: -0.059563] [d1 loss: 0.119837] [d2 loss: 0.121795]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 301/500] [Batch 520/676] [D loss: -0.023268] [G loss: -0.125693] [d1 loss: 0.049822] [d2 loss: 0.040736]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 540/676] [D loss: -0.011305] [G loss: -0.147652] [d1 loss: 0.124221] [d2 loss: 0.120210]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 560/676] [D loss: -0.022320] [G loss: -0.146394] [d1 loss: 0.103740] [d2 loss: 0.062304]  [sq d1 d2: 0.001717]  [num0: 13.000000] [num1 51.000000]
[Epoch 301/500] [Batch 580/676] [D loss: -0.009142] [G loss: -0.167638] [d1 loss: 0.051428] [d2 loss: 0.051562]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 600/676] [D loss: -0.012199] [G loss: -0.204414] [d1 loss: 0.018286] [d2 loss: 0.018403]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 301/500] [Batch 620/676] [D loss: -0.005352] [G loss: -0.221497] [d1 loss: 0.130721] [d2 loss: 0.116014]  [sq d1 d2: 0.000216]  [num0: 17.000000] [num1 47.000000]
[Epoch 301/500] [Batch 640/676] [D loss: 0.009553] [G loss: -0.227856] [d1 loss: 0.061349] [d2 loss: 0.028159]  [sq d1 d2: 0.001102]  [num0: 16.000000] [num1 48.000000]
[Epoch 301/500] [Batch 660/676] [D loss: 0.006724] [G loss: -0.216320] [d1 loss: 0.052380] [d2 loss: 0.057082]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 302/500] [Batch 0/676] [D loss: -0.011360] [G loss: -0.178090] [d1 loss: 0.036823] [d2 loss: 0.023889]  [sq d1 d2: 0.000167]  [num0: 11.000000] [num1 53.000000]
[Epoch 302/500] [Batch 20/676] [D loss: -0.000072] [G loss: -0.119171] [d1 loss: 0.082649] [d2 loss: 0.076256]  [sq d1 d2: 0.000041]  [num0: 20.000000] [num1 44.000000]
[Epoch 302/500] [Batch 40/676] [D loss: -0.030575] [G loss: -0.080771] [d1 loss: 0.109109] [d2 loss: 0.114670]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 302/500] [Batch 60/676] [D loss: -0.009105] [G loss: -0.049625] [d1 loss: 0.026143] [d2 loss: 0.025654]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 302/500] [Batch 80/676] [D loss: -0.020199] [G loss: -0.052198] [d1 loss: 0.151062] [d2 loss: 0.138548]  [sq d1 d2: 0.000157]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 100/676] [D loss: -0.023384] [G loss: -0.030713] [d1 loss: 0.092606] [d2 loss: 0.069884]  [sq d1 d2: 0.000516]  [num0: 22.000000] [num1 42.000000]
[Epoch 302/500] [Batch 120/676] [D loss: 0.001305] [G loss: -0.042475] [d1 loss: 0.070637] [d2 loss: 0.072860]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 140/676] [D loss: -0.034080] [G loss: -0.006178] [d1 loss: 0.025574] [d2 loss: 0.020758]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 302/500] [Batch 160/676] [D loss: -0.013713] [G loss: 0.003554] [d1 loss: 0.049249] [d2 loss: 0.031453]  [sq d1 d2: 0.000317]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 180/676] [D loss: 0.010643] [G loss: 0.026814] [d1 loss: 0.035510] [d2 loss: 0.038714]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 200/676] [D loss: -0.009578] [G loss: 0.021125] [d1 loss: 0.081742] [d2 loss: 0.091855]  [sq d1 d2: 0.000102]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 220/676] [D loss: -0.005379] [G loss: 0.025681] [d1 loss: 0.024205] [d2 loss: 0.020802]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 302/500] [Batch 240/676] [D loss: -0.011195] [G loss: 0.026733] [d1 loss: 0.069639] [d2 loss: 0.075011]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 302/500] [Batch 260/676] [D loss: -0.019831] [G loss: 0.020504] [d1 loss: 0.102313] [d2 loss: 0.078082]  [sq d1 d2: 0.000587]  [num0: 13.000000] [num1 51.000000]
[Epoch 302/500] [Batch 280/676] [D loss: -0.025296] [G loss: 0.022562] [d1 loss: 0.021518] [d2 loss: 0.029969]  [sq d1 d2: 0.000071]  [num0: 20.000000] [num1 44.000000]
[Epoch 302/500] [Batch 300/676] [D loss: -0.006516] [G loss: 0.025350] [d1 loss: 0.052277] [d2 loss: 0.069424]  [sq d1 d2: 0.000294]  [num0: 17.000000] [num1 47.000000]

[Epoch 302/500] [Batch 320/676] [D loss: -0.030027] [G loss: -0.028627] [d1 loss: 0.034758] [d2 loss: 0.043895]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 340/676] [D loss: -0.018450] [G loss: -0.023079] [d1 loss: 0.102160] [d2 loss: 0.093283]  [sq d1 d2: 0.000079]  [num0: 19.000000] [num1 45.000000]
[Epoch 302/500] [Batch 360/676] [D loss: -0.034117] [G loss: -0.084631] [d1 loss: 0.049743] [d2 loss: 0.055378]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 380/676] [D loss: -0.023184] [G loss: -0.073029] [d1 loss: 0.055710] [d2 loss: 0.060756]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 400/676] [D loss: 0.000310] [G loss: -0.081611] [d1 loss: 0.053945] [d2 loss: 0.058076]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 420/676] [D loss: 0.005494] [G loss: -0.062007] [d1 loss: 0.018378] [d2 loss: 0.024370]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 302/500] [Batch 440/676] [D loss: -0.013264] [G loss: -0.059280] [d1 loss: 0.037373] [d2 loss: 0.037790]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 460/676] [D loss: -0.005806] [G loss: -0.078490] [d1 loss: 0.036981] [d2 loss: 0.047878]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 480/676] [D loss: -0.014543] [G loss: -0.047681] [d1 loss: 0.049837] [d2 loss: 0.057654]  [sq d1 d2: 0.000061]  [num0: 12.000000] [num1 52.000000]
[Epoch 302/500] [Batch 500/676] [D loss: -0.022643] [G loss: -0.006195] [d1 loss: 0.045303] [d2 loss: 0.047717]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 520/676] [D loss: -0.002779] [G loss: -0.010879] [d1 loss: 0.102268] [d2 loss: 0.103359]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 302/500] [Batch 540/676] [D loss: -0.017227] [G loss: 0.002521] [d1 loss: 0.131816] [d2 loss: 0.111007]  [sq d1 d2: 0.000433]  [num0: 10.000000] [num1 54.000000]
[Epoch 302/500] [Batch 560/676] [D loss: -0.026583] [G loss: 0.059258] [d1 loss: 0.027353] [d2 loss: 0.035744]  [sq d1 d2: 0.000070]  [num0: 17.000000] [num1 47.000000]
[Epoch 302/500] [Batch 580/676] [D loss: -0.031326] [G loss: 0.037996] [d1 loss: 0.050061] [d2 loss: 0.050884]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 302/500] [Batch 600/676] [D loss: -0.012419] [G loss: 0.089731] [d1 loss: 0.026412] [d2 loss: 0.030905]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 302/500] [Batch 620/676] [D loss: 0.010434] [G loss: 0.150427] [d1 loss: 0.040912] [d2 loss: 0.033873]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 302/500] [Batch 640/676] [D loss: -0.013380] [G loss: 0.141529] [d1 loss: 0.071361] [d2 loss: 0.054222]  [sq d1 d2: 0.000294]  [num0: 17.000000] [num1 47.000000]
[Epoch 302/500] [Batch 660/676] [D loss: -0.024580] [G loss: 0.116193] [d1 loss: 0.073749] [d2 loss: 0.065592]  [sq d1 d2: 0.000067]  [num0: 21.000000] [num1 43.000000]
[Epoch 303/500] [Batch 0/676] [D loss: 0.013936] [G loss: 0.134298] [d1 loss: 0.068691] [d2 loss: 0.070800]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 20/676] [D loss: -0.017945] [G loss: 0.105426] [d1 loss: 0.052201] [d2 loss: 0.055023]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 303/500] [Batch 40/676] [D loss: 0.000364] [G loss: 0.060376] [d1 loss: 0.069620] [d2 loss: 0.096191]  [sq d1 d2: 0.000706]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 60/676] [D loss: -0.010524] [G loss: 0.082554] [d1 loss: 0.052950] [d2 loss: 0.062052]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 80/676] [D loss: -0.005756] [G loss: -0.031922] [d1 loss: 0.042250] [d2 loss: 0.059987]  [sq d1 d2: 0.000315]  [num0: 11.000000] [num1 53.000000]
[Epoch 303/500] [Batch 100/676] [D loss: -0.000040] [G loss: -0.123957] [d1 loss: 0.026485] [d2 loss: 0.021004]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 120/676] [D loss: -0.024044] [G loss: -0.164623] [d1 loss: 0.047648] [d2 loss: 0.052280]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 140/676] [D loss: -0.008515] [G loss: -0.202541] [d1 loss: 0.068935] [d2 loss: 0.073864]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 160/676] [D loss: -0.002323] [G loss: -0.218902] [d1 loss: 0.096713] [d2 loss: 0.101182]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 303/500] [Batch 180/676] [D loss: -0.012954] [G loss: -0.286647] [d1 loss: 0.055448] [d2 loss: 0.049494]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 200/676] [D loss: -0.026636] [G loss: -0.359529] [d1 loss: 0.049917] [d2 loss: 0.056221]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 220/676] [D loss: -0.007576] [G loss: -0.352918] [d1 loss: 0.053343] [d2 loss: 0.047829]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 240/676] [D loss: -0.000016] [G loss: -0.291629] [d1 loss: 0.041359] [d2 loss: 0.035341]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 260/676] [D loss: -0.003953] [G loss: -0.330610] [d1 loss: 0.157261] [d2 loss: 0.078184]  [sq d1 d2: 0.006253]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 280/676] [D loss: 0.006865] [G loss: -0.376699] [d1 loss: 0.019389] [d2 loss: 0.024800]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 300/676] [D loss: 0.015214] [G loss: -0.319425] [d1 loss: 0.027623] [d2 loss: 0.027949]  [sq d1 d2: 0.000000]  [num0: 10.000000] [num1 54.000000]
[Epoch 303/500] [Batch 320/676] [D loss: -0.009869] [G loss: -0.278089] [d1 loss: 0.016147] [d2 loss: 0.018708]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 303/500] [Batch 340/676] [D loss: -0.009285] [G loss: -0.282130] [d1 loss: 0.070382] [d2 loss: 0.064370]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 360/676] [D loss: -0.016342] [G loss: -0.263003] [d1 loss: 0.057367] [d2 loss: 0.070136]  [sq d1 d2: 0.000163]  [num0: 18.000000] [num1 46.000000]
[Epoch 303/500] [Batch 380/676] [D loss: -0.029240] [G loss: -0.179325] [d1 loss: 0.046370] [d2 loss: 0.057877]  [sq d1 d2: 0.000132]  [num0: 20.000000] [num1 44.000000]
[Epoch 303/500] [Batch 400/676] [D loss: -0.035956] [G loss: -0.148898] [d1 loss: 0.056477] [d2 loss: 0.062833]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 420/676] [D loss: -0.010696] [G loss: -0.149713] [d1 loss: 0.205208] [d2 loss: 0.149214]  [sq d1 d2: 0.003135]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 440/676] [D loss: -0.033171] [G loss: -0.094597] [d1 loss: 0.146076] [d2 loss: 0.149284]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 303/500] [Batch 460/676] [D loss: 0.012447] [G loss: -0.055976] [d1 loss: 0.035229] [d2 loss: 0.041064]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 303/500] [Batch 480/676] [D loss: -0.018697] [G loss: -0.008900] [d1 loss: 0.053547] [d2 loss: 0.070321]  [sq d1 d2: 0.000281]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 500/676] [D loss: 0.007101] [G loss: 0.013011] [d1 loss: 0.046222] [d2 loss: 0.042535]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 303/500] [Batch 520/676] [D loss: 0.004696] [G loss: 0.050095] [d1 loss: 0.075596] [d2 loss: 0.083649]  [sq d1 d2: 0.000065]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 540/676] [D loss: -0.002244] [G loss: 0.094084] [d1 loss: 0.066182] [d2 loss: 0.059884]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 560/676] [D loss: -0.005512] [G loss: 0.100493] [d1 loss: 0.212171] [d2 loss: 0.098434]  [sq d1 d2: 0.012936]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 580/676] [D loss: 0.004613] [G loss: 0.110785] [d1 loss: 0.023271] [d2 loss: 0.023614]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 303/500] [Batch 600/676] [D loss: -0.016446] [G loss: 0.075255] [d1 loss: 0.089730] [d2 loss: 0.085374]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 620/676] [D loss: -0.026342] [G loss: 0.068335] [d1 loss: 0.051264] [d2 loss: 0.049172]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]

[Epoch 303/500] [Batch 640/676] [D loss: -0.022085] [G loss: 0.094686] [d1 loss: 0.053198] [d2 loss: 0.063371]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 303/500] [Batch 660/676] [D loss: -0.008805] [G loss: 0.071833] [d1 loss: 0.045032] [d2 loss: 0.034519]  [sq d1 d2: 0.000111]  [num0: 13.000000] [num1 51.000000]
[Epoch 304/500] [Batch 0/676] [D loss: 0.014202] [G loss: 0.044128] [d1 loss: 0.029779] [d2 loss: 0.038178]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 20/676] [D loss: -0.013180] [G loss: 0.009766] [d1 loss: 0.055688] [d2 loss: 0.060737]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 40/676] [D loss: 0.012395] [G loss: -0.009338] [d1 loss: 0.081146] [d2 loss: 0.075445]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 304/500] [Batch 60/676] [D loss: -0.024841] [G loss: -0.025576] [d1 loss: 0.054155] [d2 loss: 0.044359]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 80/676] [D loss: 0.004907] [G loss: -0.000787] [d1 loss: 0.135107] [d2 loss: 0.141627]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 100/676] [D loss: -0.002462] [G loss: 0.039685] [d1 loss: 0.054916] [d2 loss: 0.017264]  [sq d1 d2: 0.001418]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 120/676] [D loss: -0.002139] [G loss: 0.038834] [d1 loss: 0.108969] [d2 loss: 0.114182]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 140/676] [D loss: -0.012262] [G loss: 0.012221] [d1 loss: 0.065263] [d2 loss: 0.067720]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 160/676] [D loss: -0.000285] [G loss: 0.001313] [d1 loss: 0.066356] [d2 loss: 0.050495]  [sq d1 d2: 0.000252]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 180/676] [D loss: -0.003053] [G loss: -0.011637] [d1 loss: 0.052877] [d2 loss: 0.055007]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 200/676] [D loss: -0.001107] [G loss: 0.003755] [d1 loss: 0.044073] [d2 loss: 0.046559]  [sq d1 d2: 0.000006]  [num0: 20.000000] [num1 44.000000]
[Epoch 304/500] [Batch 220/676] [D loss: -0.014834] [G loss: 0.005169] [d1 loss: 0.038737] [d2 loss: 0.054155]  [sq d1 d2: 0.000238]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 240/676] [D loss: -0.010787] [G loss: 0.001080] [d1 loss: 0.113949] [d2 loss: 0.077658]  [sq d1 d2: 0.001317]  [num0: 19.000000] [num1 45.000000]
[Epoch 304/500] [Batch 260/676] [D loss: -0.025175] [G loss: 0.000201] [d1 loss: 0.033264] [d2 loss: 0.046025]  [sq d1 d2: 0.000163]  [num0: 14.000000] [num1 50.000000]
[Epoch 304/500] [Batch 280/676] [D loss: -0.022961] [G loss: -0.016458] [d1 loss: 0.052976] [d2 loss: 0.045955]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 300/676] [D loss: -0.004967] [G loss: 0.023976] [d1 loss: 0.093572] [d2 loss: 0.112660]  [sq d1 d2: 0.000364]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 320/676] [D loss: -0.014639] [G loss: -0.036070] [d1 loss: 0.041497] [d2 loss: 0.062310]  [sq d1 d2: 0.000433]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 340/676] [D loss: -0.000872] [G loss: -0.044411] [d1 loss: 0.057294] [d2 loss: 0.087121]  [sq d1 d2: 0.000890]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 360/676] [D loss: 0.002299] [G loss: -0.017878] [d1 loss: 0.120242] [d2 loss: 0.102283]  [sq d1 d2: 0.000323]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 380/676] [D loss: 0.003652] [G loss: -0.045142] [d1 loss: 0.075200] [d2 loss: 0.082479]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 400/676] [D loss: -0.004272] [G loss: -0.068043] [d1 loss: 0.059217] [d2 loss: 0.058541]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 420/676] [D loss: -0.008202] [G loss: -0.083568] [d1 loss: 0.189016] [d2 loss: 0.160402]  [sq d1 d2: 0.000819]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 440/676] [D loss: -0.008519] [G loss: -0.068133] [d1 loss: 0.113714] [d2 loss: 0.128664]  [sq d1 d2: 0.000223]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 460/676] [D loss: -0.027243] [G loss: -0.098486] [d1 loss: 0.040900] [d2 loss: 0.044077]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 480/676] [D loss: -0.019509] [G loss: -0.149058] [d1 loss: 0.042487] [d2 loss: 0.041750]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 500/676] [D loss: -0.015607] [G loss: -0.167261] [d1 loss: 0.058405] [d2 loss: 0.054093]  [sq d1 d2: 0.000019]  [num0: 21.000000] [num1 43.000000]
[Epoch 304/500] [Batch 520/676] [D loss: -0.011813] [G loss: -0.187133] [d1 loss: 0.077587] [d2 loss: 0.091364]  [sq d1 d2: 0.000190]  [num0: 12.000000] [num1 52.000000]
[Epoch 304/500] [Batch 540/676] [D loss: -0.011453] [G loss: -0.232466] [d1 loss: 0.083007] [d2 loss: 0.075239]  [sq d1 d2: 0.000060]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 560/676] [D loss: -0.018888] [G loss: -0.236153] [d1 loss: 0.058514] [d2 loss: 0.057142]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 580/676] [D loss: -0.021570] [G loss: -0.256902] [d1 loss: 0.055455] [d2 loss: 0.065475]  [sq d1 d2: 0.000100]  [num0: 18.000000] [num1 46.000000]
[Epoch 304/500] [Batch 600/676] [D loss: 0.000617] [G loss: -0.248760] [d1 loss: 0.088134] [d2 loss: 0.063740]  [sq d1 d2: 0.000595]  [num0: 17.000000] [num1 47.000000]
[Epoch 304/500] [Batch 620/676] [D loss: -0.001486] [G loss: -0.218294] [d1 loss: 0.047046] [d2 loss: 0.052057]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 304/500] [Batch 640/676] [D loss: -0.000654] [G loss: -0.229307] [d1 loss: 0.077663] [d2 loss: 0.047307]  [sq d1 d2: 0.000921]  [num0: 16.000000] [num1 48.000000]
[Epoch 304/500] [Batch 660/676] [D loss: -0.012661] [G loss: -0.192896] [d1 loss: 0.050757] [d2 loss: 0.052102]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 0/676] [D loss: -0.005553] [G loss: -0.173185] [d1 loss: 0.098140] [d2 loss: 0.102885]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 20/676] [D loss: -0.013698] [G loss: -0.143839] [d1 loss: 0.044250] [d2 loss: 0.043967]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 40/676] [D loss: -0.015694] [G loss: -0.145511] [d1 loss: 0.050536] [d2 loss: 0.043567]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 305/500] [Batch 60/676] [D loss: 0.000396] [G loss: -0.155082] [d1 loss: 0.040136] [d2 loss: 0.048932]  [sq d1 d2: 0.000077]  [num0: 11.000000] [num1 53.000000]
[Epoch 305/500] [Batch 80/676] [D loss: -0.016239] [G loss: -0.120607] [d1 loss: 0.100721] [d2 loss: 0.080247]  [sq d1 d2: 0.000419]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 100/676] [D loss: -0.003508] [G loss: -0.187864] [d1 loss: 0.043011] [d2 loss: 0.065621]  [sq d1 d2: 0.000511]  [num0: 14.000000] [num1 50.000000]
[Epoch 305/500] [Batch 120/676] [D loss: -0.011922] [G loss: -0.133636] [d1 loss: 0.088108] [d2 loss: 0.097431]  [sq d1 d2: 0.000087]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 140/676] [D loss: -0.008839] [G loss: -0.179835] [d1 loss: 0.049650] [d2 loss: 0.058955]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 305/500] [Batch 160/676] [D loss: 0.011189] [G loss: -0.084077] [d1 loss: 0.059014] [d2 loss: 0.071825]  [sq d1 d2: 0.000164]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 180/676] [D loss: -0.004253] [G loss: -0.075052] [d1 loss: 0.046970] [d2 loss: 0.053967]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 305/500] [Batch 200/676] [D loss: 0.011952] [G loss: -0.078802] [d1 loss: 0.069180] [d2 loss: 0.051529]  [sq d1 d2: 0.000312]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 220/676] [D loss: 0.000487] [G loss: -0.070282] [d1 loss: 0.066200] [d2 loss: 0.069359]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 305/500] [Batch 240/676] [D loss: -0.007586] [G loss: -0.062277] [d1 loss: 0.051889] [d2 loss: 0.031770]  [sq d1 d2: 0.000405]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 260/676] [D loss: -0.001619] [G loss: -0.043121] [d1 loss: 0.059348] [d2 loss: 0.064357]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 305/500] [Batch 280/676] [D loss: -0.011256] [G loss: -0.039057] [d1 loss: 0.112353] [d2 loss: 0.096172]  [sq d1 d2: 0.000262]  [num0: 22.000000] [num1 42.000000]

[Epoch 305/500] [Batch 300/676] [D loss: -0.008769] [G loss: -0.041700] [d1 loss: 0.024389] [d2 loss: 0.021231]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 320/676] [D loss: -0.012147] [G loss: -0.053090] [d1 loss: 0.043440] [d2 loss: 0.048800]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 305/500] [Batch 340/676] [D loss: -0.018743] [G loss: -0.046668] [d1 loss: 0.049488] [d2 loss: 0.045882]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 305/500] [Batch 360/676] [D loss: 0.003901] [G loss: -0.048783] [d1 loss: 0.049219] [d2 loss: 0.033222]  [sq d1 d2: 0.000256]  [num0: 15.000000] [num1 49.000000]
[Epoch 305/500] [Batch 380/676] [D loss: -0.014508] [G loss: -0.023125] [d1 loss: 0.063416] [d2 loss: 0.076628]  [sq d1 d2: 0.000175]  [num0: 17.000000] [num1 47.000000]
[Epoch 305/500] [Batch 400/676] [D loss: -0.011528] [G loss: -0.023288] [d1 loss: 0.079314] [d2 loss: 0.052004]  [sq d1 d2: 0.000746]  [num0: 15.000000] [num1 49.000000]
[Epoch 305/500] [Batch 420/676] [D loss: -0.016841] [G loss: -0.016341] [d1 loss: 0.058935] [d2 loss: 0.056869]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 305/500] [Batch 440/676] [D loss: -0.004339] [G loss: 0.016345] [d1 loss: 0.090489] [d2 loss: 0.081726]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 305/500] [Batch 460/676] [D loss: -0.001173] [G loss: 0.000664] [d1 loss: 0.100625] [d2 loss: 0.080010]  [sq d1 d2: 0.000425]  [num0: 14.000000] [num1 50.000000]
[Epoch 305/500] [Batch 480/676] [D loss: -0.014994] [G loss: -0.029994] [d1 loss: 0.056918] [d2 loss: 0.053127]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 305/500] [Batch 500/676] [D loss: -0.010801] [G loss: -0.021468] [d1 loss: 0.051490] [d2 loss: 0.052132]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 520/676] [D loss: -0.019677] [G loss: 0.008022] [d1 loss: 0.049109] [d2 loss: 0.050646]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 540/676] [D loss: 0.003609] [G loss: 0.007231] [d1 loss: 0.060359] [d2 loss: 0.055241]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 560/676] [D loss: -0.005362] [G loss: -0.013614] [d1 loss: 0.124921] [d2 loss: 0.089368]  [sq d1 d2: 0.001264]  [num0: 17.000000] [num1 47.000000]
[Epoch 305/500] [Batch 580/676] [D loss: 0.002054] [G loss: -0.019663] [d1 loss: 0.025868] [d2 loss: 0.022702]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 305/500] [Batch 600/676] [D loss: -0.000493] [G loss: -0.028361] [d1 loss: 0.017299] [d2 loss: 0.019462]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 305/500] [Batch 620/676] [D loss: -0.012397] [G loss: -0.022970] [d1 loss: 0.020650] [d2 loss: 0.020122]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 305/500] [Batch 640/676] [D loss: 0.011947] [G loss: -0.038598] [d1 loss: 0.107364] [d2 loss: 0.090685]  [sq d1 d2: 0.000278]  [num0: 17.000000] [num1 47.000000]
[Epoch 305/500] [Batch 660/676] [D loss: -0.011896] [G loss: -0.007067] [d1 loss: 0.100673] [d2 loss: 0.099689]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 306/500] [Batch 0/676] [D loss: -0.003313] [G loss: -0.038090] [d1 loss: 0.119604] [d2 loss: 0.129541]  [sq d1 d2: 0.000099]  [num0: 13.000000] [num1 51.000000]
[Epoch 306/500] [Batch 20/676] [D loss: 0.001811] [G loss: -0.046548] [d1 loss: 0.061160] [d2 loss: 0.048312]  [sq d1 d2: 0.000165]  [num0: 17.000000] [num1 47.000000]
[Epoch 306/500] [Batch 40/676] [D loss: -0.026752] [G loss: -0.066799] [d1 loss: 0.036638] [d2 loss: 0.041466]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 60/676] [D loss: -0.003557] [G loss: -0.080150] [d1 loss: 0.065929] [d2 loss: 0.060288]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 306/500] [Batch 80/676] [D loss: -0.028932] [G loss: -0.038703] [d1 loss: 0.099406] [d2 loss: 0.108175]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 100/676] [D loss: 0.015756] [G loss: -0.079516] [d1 loss: 0.158023] [d2 loss: 0.156302]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 120/676] [D loss: -0.034842] [G loss: -0.088942] [d1 loss: 0.049810] [d2 loss: 0.061492]  [sq d1 d2: 0.000136]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 140/676] [D loss: -0.010369] [G loss: -0.093898] [d1 loss: 0.077054] [d2 loss: 0.063020]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 306/500] [Batch 160/676] [D loss: -0.014217] [G loss: -0.093262] [d1 loss: 0.048214] [d2 loss: 0.047060]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 306/500] [Batch 180/676] [D loss: 0.000828] [G loss: -0.066802] [d1 loss: 0.041465] [d2 loss: 0.045869]  [sq d1 d2: 0.000019]  [num0: 19.000000] [num1 45.000000]
[Epoch 306/500] [Batch 200/676] [D loss: 0.001807] [G loss: -0.067354] [d1 loss: 0.051708] [d2 loss: 0.067781]  [sq d1 d2: 0.000258]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 220/676] [D loss: -0.005343] [G loss: -0.041037] [d1 loss: 0.113672] [d2 loss: 0.112431]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 240/676] [D loss: -0.003472] [G loss: -0.024385] [d1 loss: 0.091934] [d2 loss: 0.087042]  [sq d1 d2: 0.000024]  [num0: 11.000000] [num1 53.000000]
[Epoch 306/500] [Batch 260/676] [D loss: -0.004228] [G loss: -0.082553] [d1 loss: 0.059247] [d2 loss: 0.077615]  [sq d1 d2: 0.000337]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 280/676] [D loss: -0.009200] [G loss: -0.084166] [d1 loss: 0.061002] [d2 loss: 0.060066]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 306/500] [Batch 300/676] [D loss: -0.007946] [G loss: -0.137540] [d1 loss: 0.107538] [d2 loss: 0.120750]  [sq d1 d2: 0.000175]  [num0: 10.000000] [num1 54.000000]
[Epoch 306/500] [Batch 320/676] [D loss: -0.009051] [G loss: -0.085152] [d1 loss: 0.103708] [d2 loss: 0.092840]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 340/676] [D loss: -0.027759] [G loss: -0.061049] [d1 loss: 0.137263] [d2 loss: 0.104339]  [sq d1 d2: 0.001084]  [num0: 19.000000] [num1 45.000000]
[Epoch 306/500] [Batch 360/676] [D loss: -0.010614] [G loss: -0.121617] [d1 loss: 0.174329] [d2 loss: 0.165168]  [sq d1 d2: 0.000084]  [num0: 13.000000] [num1 51.000000]
[Epoch 306/500] [Batch 380/676] [D loss: -0.020139] [G loss: -0.144901] [d1 loss: 0.138797] [d2 loss: 0.159802]  [sq d1 d2: 0.000441]  [num0: 14.000000] [num1 50.000000]
[Epoch 306/500] [Batch 400/676] [D loss: -0.001475] [G loss: -0.061806] [d1 loss: 0.075805] [d2 loss: 0.072785]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 306/500] [Batch 420/676] [D loss: -0.002181] [G loss: -0.026901] [d1 loss: 0.063810] [d2 loss: 0.073861]  [sq d1 d2: 0.000101]  [num0: 13.000000] [num1 51.000000]
[Epoch 306/500] [Batch 440/676] [D loss: 0.000938] [G loss: -0.047891] [d1 loss: 0.047328] [d2 loss: 0.048202]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 460/676] [D loss: -0.013975] [G loss: -0.011070] [d1 loss: 0.084316] [d2 loss: 0.080285]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 306/500] [Batch 480/676] [D loss: -0.008756] [G loss: 0.028907] [d1 loss: 0.067024] [d2 loss: 0.072666]  [sq d1 d2: 0.000032]  [num0: 14.000000] [num1 50.000000]
[Epoch 306/500] [Batch 500/676] [D loss: -0.020354] [G loss: 0.025377] [d1 loss: 0.109276] [d2 loss: 0.108677]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 306/500] [Batch 520/676] [D loss: -0.018694] [G loss: 0.002178] [d1 loss: 0.077829] [d2 loss: 0.067749]  [sq d1 d2: 0.000102]  [num0: 19.000000] [num1 45.000000]
[Epoch 306/500] [Batch 540/676] [D loss: -0.007070] [G loss: 0.031255] [d1 loss: 0.042452] [d2 loss: 0.030456]  [sq d1 d2: 0.000144]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 560/676] [D loss: -0.037911] [G loss: 0.054992] [d1 loss: 0.103528] [d2 loss: 0.105397]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 306/500] [Batch 580/676] [D loss: -0.006532] [G loss: 0.069143] [d1 loss: 0.066266] [d2 loss: 0.087580]  [sq d1 d2: 0.000454]  [num0: 17.000000] [num1 47.000000]
[Epoch 306/500] [Batch 600/676] [D loss: -0.020326] [G loss: 0.101919] [d1 loss: 0.090693] [d2 loss: 0.101168]  [sq d1 d2: 0.000110]  [num0: 15.000000] [num1 49.000000]
[Epoch 306/500] [Batch 620/676] [D loss: -0.007480] [G loss: 0.108530] [d1 loss: 0.022569] [d2 loss: 0.020062]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 306/500] [Batch 640/676] [D loss: 0.003778] [G loss: 0.094608] [d1 loss: 0.106059] [d2 loss: 0.098104]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]

[Epoch 306/500] [Batch 660/676] [D loss: -0.001063] [G loss: 0.089027] [d1 loss: 0.078682] [d2 loss: 0.068372]  [sq d1 d2: 0.000106]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 0/676] [D loss: -0.009524] [G loss: 0.085104] [d1 loss: 0.067914] [d2 loss: 0.053795]  [sq d1 d2: 0.000199]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 20/676] [D loss: -0.000052] [G loss: 0.049530] [d1 loss: 0.129906] [d2 loss: 0.100750]  [sq d1 d2: 0.000850]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 40/676] [D loss: -0.009369] [G loss: -0.005622] [d1 loss: 0.047065] [d2 loss: 0.039203]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 60/676] [D loss: -0.035911] [G loss: -0.042361] [d1 loss: 0.112741] [d2 loss: 0.088459]  [sq d1 d2: 0.000590]  [num0: 19.000000] [num1 45.000000]
[Epoch 307/500] [Batch 80/676] [D loss: -0.012336] [G loss: -0.094130] [d1 loss: 0.038007] [d2 loss: 0.034349]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 307/500] [Batch 100/676] [D loss: -0.019218] [G loss: -0.125476] [d1 loss: 0.072389] [d2 loss: 0.072854]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 120/676] [D loss: 0.004469] [G loss: -0.185794] [d1 loss: 0.043131] [d2 loss: 0.048090]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 307/500] [Batch 140/676] [D loss: -0.026905] [G loss: -0.221378] [d1 loss: 0.098152] [d2 loss: 0.082641]  [sq d1 d2: 0.000241]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 160/676] [D loss: -0.002707] [G loss: -0.211299] [d1 loss: 0.054476] [d2 loss: 0.054436]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 180/676] [D loss: 0.013177] [G loss: -0.200189] [d1 loss: 0.074953] [d2 loss: 0.060387]  [sq d1 d2: 0.000212]  [num0: 14.000000] [num1 50.000000]
[Epoch 307/500] [Batch 200/676] [D loss: 0.008453] [G loss: -0.200995] [d1 loss: 0.088526] [d2 loss: 0.084247]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 220/676] [D loss: 0.014540] [G loss: -0.139966] [d1 loss: 0.055175] [d2 loss: 0.045101]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 240/676] [D loss: -0.005138] [G loss: -0.143781] [d1 loss: 0.045363] [d2 loss: 0.038705]  [sq d1 d2: 0.000044]  [num0: 13.000000] [num1 51.000000]
[Epoch 307/500] [Batch 260/676] [D loss: -0.001971] [G loss: -0.114199] [d1 loss: 0.090598] [d2 loss: 0.068395]  [sq d1 d2: 0.000493]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 280/676] [D loss: -0.026804] [G loss: -0.135647] [d1 loss: 0.037813] [d2 loss: 0.032930]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 300/676] [D loss: -0.007163] [G loss: -0.166326] [d1 loss: 0.051864] [d2 loss: 0.048321]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 307/500] [Batch 320/676] [D loss: -0.045680] [G loss: -0.174477] [d1 loss: 0.183984] [d2 loss: 0.182184]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 340/676] [D loss: 0.002408] [G loss: -0.183621] [d1 loss: 0.100216] [d2 loss: 0.112792]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 360/676] [D loss: -0.014885] [G loss: -0.153913] [d1 loss: 0.122495] [d2 loss: 0.107886]  [sq d1 d2: 0.000213]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 380/676] [D loss: -0.014687] [G loss: -0.094369] [d1 loss: 0.029139] [d2 loss: 0.034694]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 400/676] [D loss: 0.005371] [G loss: -0.038840] [d1 loss: 0.135027] [d2 loss: 0.131281]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 307/500] [Batch 420/676] [D loss: 0.009941] [G loss: 0.009424] [d1 loss: 0.132558] [d2 loss: 0.144030]  [sq d1 d2: 0.000132]  [num0: 18.000000] [num1 46.000000]
[Epoch 307/500] [Batch 440/676] [D loss: 0.015802] [G loss: 0.030091] [d1 loss: 0.085377] [d2 loss: 0.088450]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 307/500] [Batch 460/676] [D loss: 0.000435] [G loss: 0.085083] [d1 loss: 0.130208] [d2 loss: 0.139592]  [sq d1 d2: 0.000088]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 480/676] [D loss: 0.014866] [G loss: 0.124723] [d1 loss: 0.054009] [d2 loss: 0.063055]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 500/676] [D loss: -0.004340] [G loss: 0.106647] [d1 loss: 0.064602] [d2 loss: 0.082895]  [sq d1 d2: 0.000335]  [num0: 20.000000] [num1 44.000000]
[Epoch 307/500] [Batch 520/676] [D loss: -0.007293] [G loss: 0.135350] [d1 loss: 0.123996] [d2 loss: 0.123278]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 307/500] [Batch 540/676] [D loss: -0.002866] [G loss: 0.173886] [d1 loss: 0.033014] [d2 loss: 0.039767]  [sq d1 d2: 0.000046]  [num0: 19.000000] [num1 45.000000]
[Epoch 307/500] [Batch 560/676] [D loss: -0.036095] [G loss: 0.211651] [d1 loss: 0.045170] [d2 loss: 0.042708]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 307/500] [Batch 580/676] [D loss: -0.015342] [G loss: 0.217400] [d1 loss: 0.085801] [d2 loss: 0.079336]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 307/500] [Batch 600/676] [D loss: -0.018331] [G loss: 0.185345] [d1 loss: 0.038675] [d2 loss: 0.044153]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 620/676] [D loss: 0.010947] [G loss: 0.131634] [d1 loss: 0.061326] [d2 loss: 0.061284]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 307/500] [Batch 640/676] [D loss: -0.007362] [G loss: 0.053632] [d1 loss: 0.070948] [d2 loss: 0.062270]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 307/500] [Batch 660/676] [D loss: 0.017430] [G loss: -0.031552] [d1 loss: 0.040800] [d2 loss: 0.044734]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 308/500] [Batch 0/676] [D loss: -0.002811] [G loss: -0.069568] [d1 loss: 0.071578] [d2 loss: 0.066063]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 308/500] [Batch 20/676] [D loss: 0.009234] [G loss: -0.147866] [d1 loss: 0.125176] [d2 loss: 0.114229]  [sq d1 d2: 0.000120]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 40/676] [D loss: 0.004390] [G loss: -0.177785] [d1 loss: 0.047852] [d2 loss: 0.049080]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 308/500] [Batch 60/676] [D loss: -0.013834] [G loss: -0.248420] [d1 loss: 0.034346] [d2 loss: 0.028501]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 308/500] [Batch 80/676] [D loss: -0.010364] [G loss: -0.298306] [d1 loss: 0.056220] [d2 loss: 0.052020]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 308/500] [Batch 100/676] [D loss: -0.013545] [G loss: -0.327974] [d1 loss: 0.077758] [d2 loss: 0.096401]  [sq d1 d2: 0.000348]  [num0: 17.000000] [num1 47.000000]
[Epoch 308/500] [Batch 120/676] [D loss: -0.026147] [G loss: -0.352193] [d1 loss: 0.066263] [d2 loss: 0.052596]  [sq d1 d2: 0.000187]  [num0: 16.000000] [num1 48.000000]
[Epoch 308/500] [Batch 140/676] [D loss: 0.004961] [G loss: -0.361475] [d1 loss: 0.074477] [d2 loss: 0.068312]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 160/676] [D loss: 0.004382] [G loss: -0.404506] [d1 loss: 0.066109] [d2 loss: 0.065431]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 180/676] [D loss: -0.001031] [G loss: -0.394705] [d1 loss: 0.073735] [d2 loss: 0.094480]  [sq d1 d2: 0.000430]  [num0: 16.000000] [num1 48.000000]
[Epoch 308/500] [Batch 200/676] [D loss: -0.010716] [G loss: -0.402867] [d1 loss: 0.080395] [d2 loss: 0.073735]  [sq d1 d2: 0.000044]  [num0: 20.000000] [num1 44.000000]
[Epoch 308/500] [Batch 220/676] [D loss: 0.004950] [G loss: -0.312476] [d1 loss: 0.246244] [d2 loss: 0.203300]  [sq d1 d2: 0.001844]  [num0: 16.000000] [num1 48.000000]
[Epoch 308/500] [Batch 240/676] [D loss: 0.017709] [G loss: -0.223854] [d1 loss: 0.087082] [d2 loss: 0.082184]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 260/676] [D loss: 0.007486] [G loss: -0.139987] [d1 loss: 0.042809] [d2 loss: 0.059019]  [sq d1 d2: 0.000263]  [num0: 17.000000] [num1 47.000000]
[Epoch 308/500] [Batch 280/676] [D loss: 0.003431] [G loss: -0.093213] [d1 loss: 0.104497] [d2 loss: 0.107080]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 300/676] [D loss: -0.008036] [G loss: -0.062772] [d1 loss: 0.029706] [d2 loss: 0.023038]  [sq d1 d2: 0.000044]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 320/676] [D loss: -0.004123] [G loss: -0.034275] [d1 loss: 0.060029] [d2 loss: 0.060234]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]

[Epoch 308/500] [Batch 340/676] [D loss: -0.017760] [G loss: -0.012225] [d1 loss: 0.023943] [d2 loss: 0.019699]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 360/676] [D loss: -0.029075] [G loss: -0.027480] [d1 loss: 0.046046] [d2 loss: 0.060109]  [sq d1 d2: 0.000198]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 380/676] [D loss: -0.026994] [G loss: -0.053100] [d1 loss: 0.069084] [d2 loss: 0.068040]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 400/676] [D loss: -0.013934] [G loss: -0.065805] [d1 loss: 0.042006] [d2 loss: 0.049938]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 308/500] [Batch 420/676] [D loss: -0.037882] [G loss: -0.045565] [d1 loss: 0.104079] [d2 loss: 0.104423]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 308/500] [Batch 440/676] [D loss: -0.042451] [G loss: -0.073235] [d1 loss: 0.059719] [d2 loss: 0.058035]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 460/676] [D loss: -0.000078] [G loss: -0.069783] [d1 loss: 0.044182] [d2 loss: 0.038405]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 308/500] [Batch 480/676] [D loss: 0.013156] [G loss: -0.072425] [d1 loss: 0.068031] [d2 loss: 0.060288]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 308/500] [Batch 500/676] [D loss: 0.021119] [G loss: -0.053529] [d1 loss: 0.101393] [d2 loss: 0.102145]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 520/676] [D loss: 0.014863] [G loss: -0.081931] [d1 loss: 0.059928] [d2 loss: 0.053517]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 308/500] [Batch 540/676] [D loss: -0.008347] [G loss: -0.087125] [d1 loss: 0.093339] [d2 loss: 0.075735]  [sq d1 d2: 0.000310]  [num0: 14.000000] [num1 50.000000]
[Epoch 308/500] [Batch 560/676] [D loss: 0.003027] [G loss: -0.065930] [d1 loss: 0.061284] [d2 loss: 0.063075]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 580/676] [D loss: -0.012024] [G loss: -0.062885] [d1 loss: 0.087988] [d2 loss: 0.089132]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 308/500] [Batch 600/676] [D loss: -0.004144] [G loss: -0.080569] [d1 loss: 0.065482] [d2 loss: 0.072794]  [sq d1 d2: 0.000053]  [num0: 13.000000] [num1 51.000000]
[Epoch 308/500] [Batch 620/676] [D loss: -0.024826] [G loss: -0.093761] [d1 loss: 0.043337] [d2 loss: 0.045495]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 308/500] [Batch 640/676] [D loss: -0.019072] [G loss: -0.117719] [d1 loss: 0.019521] [d2 loss: 0.024638]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 308/500] [Batch 660/676] [D loss: -0.052423] [G loss: -0.132698] [d1 loss: 0.082052] [d2 loss: 0.077404]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 0/676] [D loss: -0.024930] [G loss: -0.143331] [d1 loss: 0.042892] [d2 loss: 0.036448]  [sq d1 d2: 0.000042]  [num0: 17.000000] [num1 47.000000]
[Epoch 309/500] [Batch 20/676] [D loss: 0.000413] [G loss: -0.171453] [d1 loss: 0.079122] [d2 loss: 0.083623]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 309/500] [Batch 40/676] [D loss: 0.002594] [G loss: -0.166537] [d1 loss: 0.153012] [d2 loss: 0.142847]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 60/676] [D loss: 0.003596] [G loss: -0.124022] [d1 loss: 0.098102] [d2 loss: 0.111700]  [sq d1 d2: 0.000185]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 80/676] [D loss: 0.003220] [G loss: -0.086228] [d1 loss: 0.080782] [d2 loss: 0.074745]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 100/676] [D loss: 0.002728] [G loss: -0.068301] [d1 loss: 0.062118] [d2 loss: 0.061277]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 120/676] [D loss: 0.004252] [G loss: -0.043276] [d1 loss: 0.058862] [d2 loss: 0.065904]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 140/676] [D loss: -0.014360] [G loss: -0.028839] [d1 loss: 0.076119] [d2 loss: 0.071753]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 160/676] [D loss: -0.017044] [G loss: -0.007579] [d1 loss: 0.133442] [d2 loss: 0.137020]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 180/676] [D loss: -0.015136] [G loss: -0.010124] [d1 loss: 0.059027] [d2 loss: 0.062019]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 200/676] [D loss: -0.021800] [G loss: -0.026667] [d1 loss: 0.031585] [d2 loss: 0.029805]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 220/676] [D loss: -0.025664] [G loss: -0.036245] [d1 loss: 0.055613] [d2 loss: 0.033023]  [sq d1 d2: 0.000510]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 240/676] [D loss: -0.032510] [G loss: -0.071617] [d1 loss: 0.095138] [d2 loss: 0.106228]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 260/676] [D loss: -0.039764] [G loss: -0.083076] [d1 loss: 0.082334] [d2 loss: 0.094672]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 280/676] [D loss: -0.012563] [G loss: -0.114302] [d1 loss: 0.059858] [d2 loss: 0.063149]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 300/676] [D loss: 0.013956] [G loss: -0.117225] [d1 loss: 0.066683] [d2 loss: 0.074057]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 320/676] [D loss: -0.007260] [G loss: -0.055165] [d1 loss: 0.105174] [d2 loss: 0.093666]  [sq d1 d2: 0.000132]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 340/676] [D loss: -0.010078] [G loss: -0.025016] [d1 loss: 0.035772] [d2 loss: 0.036252]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 360/676] [D loss: 0.009387] [G loss: -0.001308] [d1 loss: 0.024030] [d2 loss: 0.031695]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 380/676] [D loss: -0.003762] [G loss: -0.005817] [d1 loss: 0.084032] [d2 loss: 0.064562]  [sq d1 d2: 0.000379]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 400/676] [D loss: -0.014945] [G loss: 0.006040] [d1 loss: 0.038915] [d2 loss: 0.053343]  [sq d1 d2: 0.000208]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 420/676] [D loss: -0.008096] [G loss: 0.000097] [d1 loss: 0.046157] [d2 loss: 0.055878]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 440/676] [D loss: -0.025208] [G loss: 0.010302] [d1 loss: 0.044193] [d2 loss: 0.045378]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 460/676] [D loss: -0.013516] [G loss: -0.003528] [d1 loss: 0.033665] [d2 loss: 0.043895]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 480/676] [D loss: -0.014051] [G loss: -0.019136] [d1 loss: 0.102162] [d2 loss: 0.081571]  [sq d1 d2: 0.000424]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 500/676] [D loss: -0.035495] [G loss: -0.016972] [d1 loss: 0.037314] [d2 loss: 0.035221]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 520/676] [D loss: -0.020221] [G loss: -0.010194] [d1 loss: 0.122952] [d2 loss: 0.121628]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 540/676] [D loss: -0.001194] [G loss: -0.042652] [d1 loss: 0.053098] [d2 loss: 0.055406]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 309/500] [Batch 560/676] [D loss: -0.012433] [G loss: -0.049038] [d1 loss: 0.052801] [d2 loss: 0.052730]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 309/500] [Batch 580/676] [D loss: -0.012470] [G loss: -0.050765] [d1 loss: 0.111713] [d2 loss: 0.106931]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 309/500] [Batch 600/676] [D loss: -0.000737] [G loss: -0.040828] [d1 loss: 0.080033] [d2 loss: 0.070543]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 620/676] [D loss: 0.000793] [G loss: -0.049082] [d1 loss: 0.073651] [d2 loss: 0.075372]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 309/500] [Batch 640/676] [D loss: -0.010258] [G loss: -0.062132] [d1 loss: 0.043136] [d2 loss: 0.050562]  [sq d1 d2: 0.000055]  [num0: 22.000000] [num1 42.000000]
[Epoch 309/500] [Batch 660/676] [D loss: -0.008442] [G loss: -0.041431] [d1 loss: 0.026271] [d2 loss: 0.024587]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 310/500] [Batch 0/676] [D loss: -0.008359] [G loss: -0.057552] [d1 loss: 0.068307] [d2 loss: 0.077353]  [sq d1 d2: 0.000082]  [num0: 18.000000] [num1 46.000000]

[Epoch 310/500] [Batch 20/676] [D loss: -0.027844] [G loss: -0.081373] [d1 loss: 0.053117] [d2 loss: 0.056753]  [sq d1 d2: 0.000013]  [num0: 20.000000] [num1 44.000000]
[Epoch 310/500] [Batch 40/676] [D loss: -0.025393] [G loss: -0.101747] [d1 loss: 0.084356] [d2 loss: 0.079249]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 60/676] [D loss: -0.025100] [G loss: -0.115347] [d1 loss: 0.107215] [d2 loss: 0.100343]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 80/676] [D loss: -0.020072] [G loss: -0.119028] [d1 loss: 0.045542] [d2 loss: 0.050545]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 310/500] [Batch 100/676] [D loss: 0.004749] [G loss: -0.153517] [d1 loss: 0.053199] [d2 loss: 0.062597]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 120/676] [D loss: -0.010038] [G loss: -0.158924] [d1 loss: 0.045373] [d2 loss: 0.036558]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 310/500] [Batch 140/676] [D loss: 0.006016] [G loss: -0.156652] [d1 loss: 0.063398] [d2 loss: 0.066012]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 160/676] [D loss: -0.001808] [G loss: -0.117739] [d1 loss: 0.124317] [d2 loss: 0.123569]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 310/500] [Batch 180/676] [D loss: -0.000493] [G loss: -0.097753] [d1 loss: 0.136683] [d2 loss: 0.095333]  [sq d1 d2: 0.001710]  [num0: 16.000000] [num1 48.000000]
[Epoch 310/500] [Batch 200/676] [D loss: 0.007060] [G loss: -0.111937] [d1 loss: 0.081279] [d2 loss: 0.076523]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 310/500] [Batch 220/676] [D loss: 0.000857] [G loss: -0.080018] [d1 loss: 0.032533] [d2 loss: 0.032955]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 240/676] [D loss: -0.007762] [G loss: -0.078999] [d1 loss: 0.034737] [d2 loss: 0.050556]  [sq d1 d2: 0.000250]  [num0: 13.000000] [num1 51.000000]
[Epoch 310/500] [Batch 260/676] [D loss: -0.010234] [G loss: -0.061625] [d1 loss: 0.036329] [d2 loss: 0.032491]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 280/676] [D loss: -0.023467] [G loss: -0.043280] [d1 loss: 0.264103] [d2 loss: 0.232875]  [sq d1 d2: 0.000975]  [num0: 16.000000] [num1 48.000000]
[Epoch 310/500] [Batch 300/676] [D loss: -0.025163] [G loss: -0.063046] [d1 loss: 0.024055] [d2 loss: 0.023266]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 310/500] [Batch 320/676] [D loss: -0.020230] [G loss: -0.105007] [d1 loss: 0.066634] [d2 loss: 0.075529]  [sq d1 d2: 0.000079]  [num0: 17.000000] [num1 47.000000]
[Epoch 310/500] [Batch 340/676] [D loss: -0.028356] [G loss: -0.107181] [d1 loss: 0.108969] [d2 loss: 0.109639]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 310/500] [Batch 360/676] [D loss: -0.005743] [G loss: -0.064539] [d1 loss: 0.056733] [d2 loss: 0.053538]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 310/500] [Batch 380/676] [D loss: -0.018842] [G loss: -0.107293] [d1 loss: 0.030264] [d2 loss: 0.032652]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 400/676] [D loss: -0.011042] [G loss: -0.071701] [d1 loss: 0.064525] [d2 loss: 0.088189]  [sq d1 d2: 0.000560]  [num0: 17.000000] [num1 47.000000]
[Epoch 310/500] [Batch 420/676] [D loss: -0.003877] [G loss: -0.091488] [d1 loss: 0.080527] [d2 loss: 0.083317]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 310/500] [Batch 440/676] [D loss: 0.002385] [G loss: -0.062655] [d1 loss: 0.047940] [d2 loss: 0.051280]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 460/676] [D loss: -0.000263] [G loss: -0.040934] [d1 loss: 0.148236] [d2 loss: 0.132701]  [sq d1 d2: 0.000241]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 480/676] [D loss: 0.003506] [G loss: -0.036777] [d1 loss: 0.111685] [d2 loss: 0.073062]  [sq d1 d2: 0.001492]  [num0: 11.000000] [num1 53.000000]
[Epoch 310/500] [Batch 500/676] [D loss: -0.009786] [G loss: -0.076241] [d1 loss: 0.064194] [d2 loss: 0.058264]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 310/500] [Batch 520/676] [D loss: -0.025219] [G loss: -0.113755] [d1 loss: 0.030358] [d2 loss: 0.032789]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 310/500] [Batch 540/676] [D loss: -0.019132] [G loss: -0.101453] [d1 loss: 0.062535] [d2 loss: 0.059803]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 560/676] [D loss: -0.026806] [G loss: -0.133199] [d1 loss: 0.011574] [d2 loss: 0.014157]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 580/676] [D loss: -0.029444] [G loss: -0.135632] [d1 loss: 0.030646] [d2 loss: 0.034042]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 600/676] [D loss: -0.001600] [G loss: -0.075259] [d1 loss: 0.045814] [d2 loss: 0.054522]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 310/500] [Batch 620/676] [D loss: 0.006815] [G loss: -0.045297] [d1 loss: 0.090715] [d2 loss: 0.076783]  [sq d1 d2: 0.000194]  [num0: 14.000000] [num1 50.000000]
[Epoch 310/500] [Batch 640/676] [D loss: -0.009877] [G loss: -0.095089] [d1 loss: 0.153292] [d2 loss: 0.150030]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 310/500] [Batch 660/676] [D loss: 0.007387] [G loss: -0.051848] [d1 loss: 0.031927] [d2 loss: 0.032648]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 0/676] [D loss: 0.011096] [G loss: -0.047029] [d1 loss: 0.063226] [d2 loss: 0.044263]  [sq d1 d2: 0.000360]  [num0: 12.000000] [num1 52.000000]
[Epoch 311/500] [Batch 20/676] [D loss: -0.006034] [G loss: -0.051219] [d1 loss: 0.081592] [d2 loss: 0.082325]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 40/676] [D loss: -0.006877] [G loss: -0.060940] [d1 loss: 0.077013] [d2 loss: 0.076515]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 311/500] [Batch 60/676] [D loss: -0.004147] [G loss: -0.068055] [d1 loss: 0.086978] [d2 loss: 0.091602]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 80/676] [D loss: -0.020750] [G loss: -0.091190] [d1 loss: 0.086379] [d2 loss: 0.086940]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 100/676] [D loss: -0.023271] [G loss: -0.086221] [d1 loss: 0.175760] [d2 loss: 0.154268]  [sq d1 d2: 0.000462]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 120/676] [D loss: -0.019057] [G loss: -0.099185] [d1 loss: 0.075019] [d2 loss: 0.083343]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 140/676] [D loss: -0.021189] [G loss: -0.123609] [d1 loss: 0.082400] [d2 loss: 0.088848]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 160/676] [D loss: -0.023727] [G loss: -0.142285] [d1 loss: 0.052173] [d2 loss: 0.057494]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 311/500] [Batch 180/676] [D loss: -0.010427] [G loss: -0.143320] [d1 loss: 0.063937] [d2 loss: 0.053541]  [sq d1 d2: 0.000108]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 200/676] [D loss: 0.000598] [G loss: -0.118108] [d1 loss: 0.068924] [d2 loss: 0.062825]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 220/676] [D loss: 0.000775] [G loss: -0.120970] [d1 loss: 0.104439] [d2 loss: 0.099632]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 311/500] [Batch 240/676] [D loss: -0.009655] [G loss: -0.113541] [d1 loss: 0.036753] [d2 loss: 0.040465]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 260/676] [D loss: 0.003201] [G loss: -0.097848] [d1 loss: 0.043773] [d2 loss: 0.045239]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 311/500] [Batch 280/676] [D loss: 0.003800] [G loss: -0.093554] [d1 loss: 0.034895] [d2 loss: 0.062043]  [sq d1 d2: 0.000737]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 300/676] [D loss: -0.004061] [G loss: -0.080378] [d1 loss: 0.032288] [d2 loss: 0.030485]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 320/676] [D loss: -0.016033] [G loss: -0.099328] [d1 loss: 0.048653] [d2 loss: 0.043256]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 340/676] [D loss: -0.021021] [G loss: -0.078574] [d1 loss: 0.137000] [d2 loss: 0.116652]  [sq d1 d2: 0.000414]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 360/676] [D loss: -0.019546] [G loss: -0.078775] [d1 loss: 0.040088] [d2 loss: 0.056266]  [sq d1 d2: 0.000262]  [num0: 10.000000] [num1 54.000000]

[Epoch 311/500] [Batch 380/676] [D loss: -0.009575] [G loss: -0.098959] [d1 loss: 0.028472] [d2 loss: 0.040171]  [sq d1 d2: 0.000137]  [num0: 19.000000] [num1 45.000000]
[Epoch 311/500] [Batch 400/676] [D loss: -0.021208] [G loss: -0.083724] [d1 loss: 0.049685] [d2 loss: 0.045569]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 420/676] [D loss: -0.010262] [G loss: -0.066115] [d1 loss: 0.071551] [d2 loss: 0.075143]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 440/676] [D loss: -0.016146] [G loss: -0.059656] [d1 loss: 0.035184] [d2 loss: 0.035241]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 311/500] [Batch 460/676] [D loss: -0.004618] [G loss: -0.076338] [d1 loss: 0.034661] [d2 loss: 0.032501]  [sq d1 d2: 0.000005]  [num0: 23.000000] [num1 41.000000]
[Epoch 311/500] [Batch 480/676] [D loss: -0.000824] [G loss: -0.027077] [d1 loss: 0.032414] [d2 loss: 0.021367]  [sq d1 d2: 0.000122]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 500/676] [D loss: 0.008238] [G loss: -0.032494] [d1 loss: 0.054683] [d2 loss: 0.045887]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 311/500] [Batch 520/676] [D loss: -0.003717] [G loss: -0.028240] [d1 loss: 0.027853] [d2 loss: 0.029165]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 311/500] [Batch 540/676] [D loss: -0.012503] [G loss: 0.018995] [d1 loss: 0.092114] [d2 loss: 0.079162]  [sq d1 d2: 0.000168]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 560/676] [D loss: -0.008999] [G loss: 0.066757] [d1 loss: 0.083124] [d2 loss: 0.100907]  [sq d1 d2: 0.000316]  [num0: 13.000000] [num1 51.000000]
[Epoch 311/500] [Batch 580/676] [D loss: -0.007750] [G loss: 0.092441] [d1 loss: 0.127600] [d2 loss: 0.125572]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 311/500] [Batch 600/676] [D loss: -0.015595] [G loss: 0.123767] [d1 loss: 0.052759] [d2 loss: 0.063911]  [sq d1 d2: 0.000124]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 620/676] [D loss: -0.027948] [G loss: 0.151889] [d1 loss: 0.081920] [d2 loss: 0.079589]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 311/500] [Batch 640/676] [D loss: -0.015975] [G loss: 0.143155] [d1 loss: 0.033317] [d2 loss: 0.036017]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 311/500] [Batch 660/676] [D loss: -0.008816] [G loss: 0.140982] [d1 loss: 0.032362] [d2 loss: 0.028670]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 0/676] [D loss: -0.018319] [G loss: 0.144118] [d1 loss: 0.061097] [d2 loss: 0.056619]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 312/500] [Batch 20/676] [D loss: 0.004195] [G loss: 0.105274] [d1 loss: 0.064454] [d2 loss: 0.068279]  [sq d1 d2: 0.000015]  [num0: 21.000000] [num1 43.000000]
[Epoch 312/500] [Batch 40/676] [D loss: -0.000722] [G loss: 0.070514] [d1 loss: 0.147159] [d2 loss: 0.126673]  [sq d1 d2: 0.000420]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 60/676] [D loss: 0.001164] [G loss: 0.074922] [d1 loss: 0.087232] [d2 loss: 0.103193]  [sq d1 d2: 0.000255]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 80/676] [D loss: -0.004922] [G loss: 0.044024] [d1 loss: 0.049533] [d2 loss: 0.046190]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 100/676] [D loss: -0.007748] [G loss: 0.014159] [d1 loss: 0.051960] [d2 loss: 0.044203]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 312/500] [Batch 120/676] [D loss: -0.013626] [G loss: -0.030034] [d1 loss: 0.036014] [d2 loss: 0.044071]  [sq d1 d2: 0.000065]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 140/676] [D loss: -0.020119] [G loss: -0.044452] [d1 loss: 0.064842] [d2 loss: 0.060849]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 160/676] [D loss: -0.017678] [G loss: -0.088381] [d1 loss: 0.125324] [d2 loss: 0.131182]  [sq d1 d2: 0.000034]  [num0: 21.000000] [num1 43.000000]
[Epoch 312/500] [Batch 180/676] [D loss: -0.026795] [G loss: -0.101744] [d1 loss: 0.047851] [d2 loss: 0.041598]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 312/500] [Batch 200/676] [D loss: 0.014866] [G loss: -0.128996] [d1 loss: 0.044072] [d2 loss: 0.040158]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 220/676] [D loss: -0.021595] [G loss: -0.139895] [d1 loss: 0.036770] [d2 loss: 0.043265]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 240/676] [D loss: -0.003388] [G loss: -0.196785] [d1 loss: 0.047642] [d2 loss: 0.082306]  [sq d1 d2: 0.001202]  [num0: 14.000000] [num1 50.000000]
[Epoch 312/500] [Batch 260/676] [D loss: -0.003144] [G loss: -0.167120] [d1 loss: 0.099909] [d2 loss: 0.099376]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 312/500] [Batch 280/676] [D loss: 0.008723] [G loss: -0.146414] [d1 loss: 0.056759] [d2 loss: 0.068915]  [sq d1 d2: 0.000148]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 300/676] [D loss: -0.008924] [G loss: -0.146058] [d1 loss: 0.039997] [d2 loss: 0.041233]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 312/500] [Batch 320/676] [D loss: -0.005521] [G loss: -0.117154] [d1 loss: 0.035243] [d2 loss: 0.036235]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 312/500] [Batch 340/676] [D loss: -0.010636] [G loss: -0.104403] [d1 loss: 0.094116] [d2 loss: 0.101054]  [sq d1 d2: 0.000048]  [num0: 18.000000] [num1 46.000000]
[Epoch 312/500] [Batch 360/676] [D loss: -0.002416] [G loss: -0.093030] [d1 loss: 0.104159] [d2 loss: 0.095994]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 380/676] [D loss: -0.020561] [G loss: -0.120661] [d1 loss: 0.092423] [d2 loss: 0.097879]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 312/500] [Batch 400/676] [D loss: -0.013205] [G loss: -0.093540] [d1 loss: 0.030288] [d2 loss: 0.029168]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 420/676] [D loss: -0.000434] [G loss: -0.110788] [d1 loss: 0.048193] [d2 loss: 0.048106]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 440/676] [D loss: -0.004992] [G loss: -0.089348] [d1 loss: 0.123089] [d2 loss: 0.116917]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 312/500] [Batch 460/676] [D loss: -0.005930] [G loss: -0.102795] [d1 loss: 0.090658] [d2 loss: 0.102931]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 480/676] [D loss: -0.007966] [G loss: -0.076343] [d1 loss: 0.069080] [d2 loss: 0.083215]  [sq d1 d2: 0.000200]  [num0: 17.000000] [num1 47.000000]
[Epoch 312/500] [Batch 500/676] [D loss: -0.004853] [G loss: -0.091383] [d1 loss: 0.134433] [d2 loss: 0.146071]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 520/676] [D loss: 0.002390] [G loss: -0.107136] [d1 loss: 0.139570] [d2 loss: 0.136340]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 312/500] [Batch 540/676] [D loss: 0.011474] [G loss: -0.077853] [d1 loss: 0.092453] [d2 loss: 0.053735]  [sq d1 d2: 0.001499]  [num0: 12.000000] [num1 52.000000]
[Epoch 312/500] [Batch 560/676] [D loss: 0.005785] [G loss: -0.069585] [d1 loss: 0.074731] [d2 loss: 0.077496]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 580/676] [D loss: -0.000952] [G loss: -0.117555] [d1 loss: 0.054214] [d2 loss: 0.047547]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 600/676] [D loss: -0.017872] [G loss: -0.138918] [d1 loss: 0.094012] [d2 loss: 0.098184]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 312/500] [Batch 620/676] [D loss: -0.015310] [G loss: -0.133731] [d1 loss: 0.094737] [d2 loss: 0.093481]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 312/500] [Batch 640/676] [D loss: -0.010742] [G loss: -0.189360] [d1 loss: 0.042558] [d2 loss: 0.033269]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 312/500] [Batch 660/676] [D loss: -0.028806] [G loss: -0.200546] [d1 loss: 0.068857] [d2 loss: 0.076834]  [sq d1 d2: 0.000064]  [num0: 12.000000] [num1 52.000000]
[Epoch 313/500] [Batch 0/676] [D loss: -0.024555] [G loss: -0.197443] [d1 loss: 0.136653] [d2 loss: 0.116288]  [sq d1 d2: 0.000415]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 20/676] [D loss: -0.004819] [G loss: -0.237617] [d1 loss: 0.132359] [d2 loss: 0.144997]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 40/676] [D loss: -0.010551] [G loss: -0.263014] [d1 loss: 0.084873] [d2 loss: 0.082648]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]

[Epoch 313/500] [Batch 60/676] [D loss: -0.009058] [G loss: -0.191537] [d1 loss: 0.069054] [d2 loss: 0.069201]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 313/500] [Batch 80/676] [D loss: 0.001314] [G loss: -0.162629] [d1 loss: 0.052751] [d2 loss: 0.050042]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 100/676] [D loss: 0.014330] [G loss: -0.130124] [d1 loss: 0.097350] [d2 loss: 0.092644]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 313/500] [Batch 120/676] [D loss: 0.005930] [G loss: -0.111518] [d1 loss: 0.260309] [d2 loss: 0.151252]  [sq d1 d2: 0.011893]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 140/676] [D loss: -0.000048] [G loss: -0.103796] [d1 loss: 0.129130] [d2 loss: 0.135490]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 160/676] [D loss: 0.000072] [G loss: -0.066321] [d1 loss: 0.089985] [d2 loss: 0.082240]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 180/676] [D loss: -0.006677] [G loss: -0.049283] [d1 loss: 0.039693] [d2 loss: 0.041354]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 200/676] [D loss: -0.014600] [G loss: -0.048706] [d1 loss: 0.032115] [d2 loss: 0.034098]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 313/500] [Batch 220/676] [D loss: -0.028499] [G loss: -0.055272] [d1 loss: 0.106855] [d2 loss: 0.100993]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 313/500] [Batch 240/676] [D loss: -0.014986] [G loss: -0.006357] [d1 loss: 0.070366] [d2 loss: 0.055050]  [sq d1 d2: 0.000235]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 260/676] [D loss: -0.025529] [G loss: -0.002013] [d1 loss: 0.024648] [d2 loss: 0.023912]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 313/500] [Batch 280/676] [D loss: -0.021662] [G loss: -0.021432] [d1 loss: 0.091046] [d2 loss: 0.091297]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 300/676] [D loss: -0.013525] [G loss: -0.014390] [d1 loss: 0.030859] [d2 loss: 0.032802]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 320/676] [D loss: 0.012221] [G loss: 0.012568] [d1 loss: 0.071798] [d2 loss: 0.090726]  [sq d1 d2: 0.000358]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 340/676] [D loss: -0.003590] [G loss: 0.006661] [d1 loss: 0.072012] [d2 loss: 0.072867]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 313/500] [Batch 360/676] [D loss: -0.013239] [G loss: -0.003218] [d1 loss: 0.070630] [d2 loss: 0.065354]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 380/676] [D loss: -0.002670] [G loss: -0.032040] [d1 loss: 0.086723] [d2 loss: 0.091504]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 400/676] [D loss: -0.004765] [G loss: -0.053090] [d1 loss: 0.049702] [d2 loss: 0.050608]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 313/500] [Batch 420/676] [D loss: -0.005012] [G loss: -0.039593] [d1 loss: 0.028479] [d2 loss: 0.026031]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 440/676] [D loss: -0.007163] [G loss: -0.065053] [d1 loss: 0.097837] [d2 loss: 0.085113]  [sq d1 d2: 0.000162]  [num0: 13.000000] [num1 51.000000]
[Epoch 313/500] [Batch 460/676] [D loss: -0.009045] [G loss: -0.071694] [d1 loss: 0.071923] [d2 loss: 0.073391]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 313/500] [Batch 480/676] [D loss: -0.017904] [G loss: -0.082815] [d1 loss: 0.042242] [d2 loss: 0.049327]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 500/676] [D loss: -0.032934] [G loss: -0.114053] [d1 loss: 0.026419] [d2 loss: 0.028191]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 313/500] [Batch 520/676] [D loss: -0.018531] [G loss: -0.127103] [d1 loss: 0.046375] [d2 loss: 0.040981]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 313/500] [Batch 540/676] [D loss: -0.023532] [G loss: -0.115309] [d1 loss: 0.073131] [d2 loss: 0.066817]  [sq d1 d2: 0.000040]  [num0: 10.000000] [num1 54.000000]
[Epoch 313/500] [Batch 560/676] [D loss: 0.009071] [G loss: -0.135620] [d1 loss: 0.051584] [d2 loss: 0.048399]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 580/676] [D loss: -0.003143] [G loss: -0.085748] [d1 loss: 0.042375] [d2 loss: 0.040852]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 313/500] [Batch 600/676] [D loss: -0.016204] [G loss: -0.061056] [d1 loss: 0.031898] [d2 loss: 0.036828]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 313/500] [Batch 620/676] [D loss: 0.001219] [G loss: -0.043659] [d1 loss: 0.065652] [d2 loss: 0.071785]  [sq d1 d2: 0.000038]  [num0: 15.000000] [num1 49.000000]
[Epoch 313/500] [Batch 640/676] [D loss: 0.003022] [G loss: -0.052038] [d1 loss: 0.047664] [d2 loss: 0.050729]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 313/500] [Batch 660/676] [D loss: -0.009252] [G loss: -0.043556] [d1 loss: 0.100867] [d2 loss: 0.103683]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 314/500] [Batch 0/676] [D loss: 0.005728] [G loss: -0.068909] [d1 loss: 0.070186] [d2 loss: 0.052006]  [sq d1 d2: 0.000331]  [num0: 17.000000] [num1 47.000000]
[Epoch 314/500] [Batch 20/676] [D loss: -0.013237] [G loss: -0.046474] [d1 loss: 0.031102] [d2 loss: 0.040217]  [sq d1 d2: 0.000083]  [num0: 19.000000] [num1 45.000000]
[Epoch 314/500] [Batch 40/676] [D loss: -0.016044] [G loss: -0.006687] [d1 loss: 0.090990] [d2 loss: 0.081636]  [sq d1 d2: 0.000088]  [num0: 13.000000] [num1 51.000000]
[Epoch 314/500] [Batch 60/676] [D loss: 0.000289] [G loss: -0.012881] [d1 loss: 0.061402] [d2 loss: 0.068459]  [sq d1 d2: 0.000050]  [num0: 12.000000] [num1 52.000000]
[Epoch 314/500] [Batch 80/676] [D loss: -0.006589] [G loss: -0.008371] [d1 loss: 0.094452] [d2 loss: 0.109661]  [sq d1 d2: 0.000231]  [num0: 19.000000] [num1 45.000000]
[Epoch 314/500] [Batch 100/676] [D loss: -0.016991] [G loss: -0.000169] [d1 loss: 0.074146] [d2 loss: 0.078959]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 120/676] [D loss: -0.011817] [G loss: -0.006537] [d1 loss: 0.058747] [d2 loss: 0.057496]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 314/500] [Batch 140/676] [D loss: -0.005763] [G loss: -0.004548] [d1 loss: 0.066400] [d2 loss: 0.054356]  [sq d1 d2: 0.000145]  [num0: 13.000000] [num1 51.000000]
[Epoch 314/500] [Batch 160/676] [D loss: -0.007402] [G loss: 0.018728] [d1 loss: 0.080740] [d2 loss: 0.070725]  [sq d1 d2: 0.000100]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 180/676] [D loss: -0.000380] [G loss: -0.007163] [d1 loss: 0.025649] [d2 loss: 0.030187]  [sq d1 d2: 0.000021]  [num0: 19.000000] [num1 45.000000]
[Epoch 314/500] [Batch 200/676] [D loss: -0.010197] [G loss: -0.018907] [d1 loss: 0.057877] [d2 loss: 0.058601]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 314/500] [Batch 220/676] [D loss: -0.005130] [G loss: -0.018144] [d1 loss: 0.090944] [d2 loss: 0.106001]  [sq d1 d2: 0.000227]  [num0: 19.000000] [num1 45.000000]
[Epoch 314/500] [Batch 240/676] [D loss: -0.024301] [G loss: -0.019202] [d1 loss: 0.053367] [d2 loss: 0.050402]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 314/500] [Batch 260/676] [D loss: -0.004503] [G loss: -0.050233] [d1 loss: 0.089363] [d2 loss: 0.086628]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 314/500] [Batch 280/676] [D loss: -0.009444] [G loss: -0.075710] [d1 loss: 0.049301] [d2 loss: 0.061856]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 300/676] [D loss: -0.012863] [G loss: -0.044968] [d1 loss: 0.072147] [d2 loss: 0.060976]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 314/500] [Batch 320/676] [D loss: -0.012985] [G loss: -0.042248] [d1 loss: 0.063465] [d2 loss: 0.070578]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 314/500] [Batch 340/676] [D loss: -0.014258] [G loss: -0.063457] [d1 loss: 0.182199] [d2 loss: 0.167644]  [sq d1 d2: 0.000212]  [num0: 17.000000] [num1 47.000000]
[Epoch 314/500] [Batch 360/676] [D loss: 0.007452] [G loss: -0.097989] [d1 loss: 0.083310] [d2 loss: 0.081434]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 314/500] [Batch 380/676] [D loss: -0.012148] [G loss: -0.070966] [d1 loss: 0.063645] [d2 loss: 0.062563]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 314/500] [Batch 400/676] [D loss: 0.001318] [G loss: -0.070720] [d1 loss: 0.058299] [d2 loss: 0.074292]  [sq d1 d2: 0.000256]  [num0: 14.000000] [num1 50.000000]

[Epoch 314/500] [Batch 420/676] [D loss: 0.000606] [G loss: -0.095733] [d1 loss: 0.085840] [d2 loss: 0.086623]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 440/676] [D loss: 0.008210] [G loss: -0.086751] [d1 loss: 0.014815] [d2 loss: 0.018126]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 460/676] [D loss: -0.009358] [G loss: -0.086825] [d1 loss: 0.039385] [d2 loss: 0.045427]  [sq d1 d2: 0.000037]  [num0: 18.000000] [num1 46.000000]
[Epoch 314/500] [Batch 480/676] [D loss: -0.013033] [G loss: -0.117772] [d1 loss: 0.025458] [d2 loss: 0.025215]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 314/500] [Batch 500/676] [D loss: -0.023320] [G loss: -0.116635] [d1 loss: 0.115818] [d2 loss: 0.115762]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 314/500] [Batch 520/676] [D loss: -0.019555] [G loss: -0.081625] [d1 loss: 0.191322] [d2 loss: 0.153285]  [sq d1 d2: 0.001447]  [num0: 14.000000] [num1 50.000000]
[Epoch 314/500] [Batch 540/676] [D loss: -0.033510] [G loss: -0.086045] [d1 loss: 0.059862] [d2 loss: 0.068087]  [sq d1 d2: 0.000068]  [num0: 17.000000] [num1 47.000000]
[Epoch 314/500] [Batch 560/676] [D loss: -0.015170] [G loss: -0.132723] [d1 loss: 0.116403] [d2 loss: 0.117945]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 314/500] [Batch 580/676] [D loss: -0.012146] [G loss: -0.100925] [d1 loss: 0.116113] [d2 loss: 0.135091]  [sq d1 d2: 0.000360]  [num0: 16.000000] [num1 48.000000]
[Epoch 314/500] [Batch 600/676] [D loss: -0.009919] [G loss: -0.127810] [d1 loss: 0.064326] [d2 loss: 0.088913]  [sq d1 d2: 0.000605]  [num0: 20.000000] [num1 44.000000]
[Epoch 314/500] [Batch 620/676] [D loss: 0.002587] [G loss: -0.141198] [d1 loss: 0.075648] [d2 loss: 0.071097]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 314/500] [Batch 640/676] [D loss: 0.019239] [G loss: -0.131463] [d1 loss: 0.077570] [d2 loss: 0.075065]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 314/500] [Batch 660/676] [D loss: -0.008578] [G loss: -0.134287] [d1 loss: 0.049257] [d2 loss: 0.049144]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 0/676] [D loss: 0.000669] [G loss: -0.130382] [d1 loss: 0.110712] [d2 loss: 0.103154]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 20/676] [D loss: -0.018998] [G loss: -0.172661] [d1 loss: 0.084388] [d2 loss: 0.075002]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]
[Epoch 315/500] [Batch 40/676] [D loss: -0.004688] [G loss: -0.201973] [d1 loss: 0.053805] [d2 loss: 0.047469]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 60/676] [D loss: 0.005527] [G loss: -0.193317] [d1 loss: 0.121039] [d2 loss: 0.135094]  [sq d1 d2: 0.000198]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 80/676] [D loss: -0.037403] [G loss: -0.197207] [d1 loss: 0.048577] [d2 loss: 0.039253]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 100/676] [D loss: -0.000704] [G loss: -0.250082] [d1 loss: 0.028394] [d2 loss: 0.038267]  [sq d1 d2: 0.000097]  [num0: 14.000000] [num1 50.000000]
[Epoch 315/500] [Batch 120/676] [D loss: -0.046899] [G loss: -0.236607] [d1 loss: 0.079487] [d2 loss: 0.071480]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 315/500] [Batch 140/676] [D loss: 0.008195] [G loss: -0.237912] [d1 loss: 0.031189] [d2 loss: 0.037708]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 160/676] [D loss: -0.013159] [G loss: -0.207269] [d1 loss: 0.063540] [d2 loss: 0.059865]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 315/500] [Batch 180/676] [D loss: 0.014500] [G loss: -0.139557] [d1 loss: 0.042830] [d2 loss: 0.042505]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 200/676] [D loss: 0.006314] [G loss: -0.132967] [d1 loss: 0.093238] [d2 loss: 0.082836]  [sq d1 d2: 0.000108]  [num0: 18.000000] [num1 46.000000]
[Epoch 315/500] [Batch 220/676] [D loss: 0.013468] [G loss: -0.112688] [d1 loss: 0.069120] [d2 loss: 0.083137]  [sq d1 d2: 0.000196]  [num0: 14.000000] [num1 50.000000]
[Epoch 315/500] [Batch 240/676] [D loss: -0.011088] [G loss: -0.068568] [d1 loss: 0.099482] [d2 loss: 0.109065]  [sq d1 d2: 0.000092]  [num0: 15.000000] [num1 49.000000]
[Epoch 315/500] [Batch 260/676] [D loss: -0.013695] [G loss: -0.040419] [d1 loss: 0.199097] [d2 loss: 0.197225]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 280/676] [D loss: -0.016293] [G loss: -0.016047] [d1 loss: 0.079172] [d2 loss: 0.077235]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 300/676] [D loss: 0.003512] [G loss: -0.011160] [d1 loss: 0.094677] [d2 loss: 0.100566]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 320/676] [D loss: -0.015450] [G loss: 0.001107] [d1 loss: 0.063483] [d2 loss: 0.080759]  [sq d1 d2: 0.000298]  [num0: 14.000000] [num1 50.000000]
[Epoch 315/500] [Batch 340/676] [D loss: -0.010615] [G loss: -0.004896] [d1 loss: 0.055686] [d2 loss: 0.052563]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 360/676] [D loss: -0.014805] [G loss: -0.000366] [d1 loss: 0.054554] [d2 loss: 0.045911]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 380/676] [D loss: 0.005132] [G loss: 0.004777] [d1 loss: 0.048767] [d2 loss: 0.045791]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 400/676] [D loss: -0.033907] [G loss: -0.000303] [d1 loss: 0.090690] [d2 loss: 0.114746]  [sq d1 d2: 0.000579]  [num0: 12.000000] [num1 52.000000]
[Epoch 315/500] [Batch 420/676] [D loss: -0.005326] [G loss: 0.018735] [d1 loss: 0.062774] [d2 loss: 0.061961]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 440/676] [D loss: -0.004267] [G loss: 0.021870] [d1 loss: 0.078272] [d2 loss: 0.092258]  [sq d1 d2: 0.000196]  [num0: 16.000000] [num1 48.000000]
[Epoch 315/500] [Batch 460/676] [D loss: 0.011490] [G loss: 0.016266] [d1 loss: 0.101876] [d2 loss: 0.110938]  [sq d1 d2: 0.000082]  [num0: 18.000000] [num1 46.000000]
[Epoch 315/500] [Batch 480/676] [D loss: -0.011955] [G loss: 0.016726] [d1 loss: 0.073041] [d2 loss: 0.073699]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 315/500] [Batch 500/676] [D loss: 0.004025] [G loss: 0.022876] [d1 loss: 0.076105] [d2 loss: 0.081398]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 315/500] [Batch 520/676] [D loss: 0.000879] [G loss: 0.019639] [d1 loss: 0.042105] [d2 loss: 0.038176]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 540/676] [D loss: -0.011040] [G loss: -0.009986] [d1 loss: 0.054587] [d2 loss: 0.055535]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 315/500] [Batch 560/676] [D loss: -0.016822] [G loss: -0.046514] [d1 loss: 0.115226] [d2 loss: 0.122228]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 315/500] [Batch 580/676] [D loss: -0.028768] [G loss: -0.056046] [d1 loss: 0.068316] [d2 loss: 0.062720]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 315/500] [Batch 600/676] [D loss: -0.019522] [G loss: -0.116426] [d1 loss: 0.123887] [d2 loss: 0.102276]  [sq d1 d2: 0.000467]  [num0: 15.000000] [num1 49.000000]
[Epoch 315/500] [Batch 620/676] [D loss: -0.028630] [G loss: -0.094907] [d1 loss: 0.060852] [d2 loss: 0.050360]  [sq d1 d2: 0.000110]  [num0: 20.000000] [num1 44.000000]
[Epoch 315/500] [Batch 640/676] [D loss: -0.007235] [G loss: -0.126763] [d1 loss: 0.068897] [d2 loss: 0.072265]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 315/500] [Batch 660/676] [D loss: -0.004001] [G loss: -0.151568] [d1 loss: 0.029062] [d2 loss: 0.032112]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 0/676] [D loss: 0.015336] [G loss: -0.173622] [d1 loss: 0.085946] [d2 loss: 0.089941]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 20/676] [D loss: 0.002356] [G loss: -0.164975] [d1 loss: 0.044756] [d2 loss: 0.048759]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 40/676] [D loss: -0.006195] [G loss: -0.164957] [d1 loss: 0.050389] [d2 loss: 0.060319]  [sq d1 d2: 0.000099]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 60/676] [D loss: -0.012598] [G loss: -0.171193] [d1 loss: 0.070673] [d2 loss: 0.069744]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]

[Epoch 316/500] [Batch 80/676] [D loss: -0.010774] [G loss: -0.161585] [d1 loss: 0.125764] [d2 loss: 0.111884]  [sq d1 d2: 0.000193]  [num0: 17.000000] [num1 47.000000]
[Epoch 316/500] [Batch 100/676] [D loss: -0.017027] [G loss: -0.172027] [d1 loss: 0.151797] [d2 loss: 0.123122]  [sq d1 d2: 0.000822]  [num0: 15.000000] [num1 49.000000]
[Epoch 316/500] [Batch 120/676] [D loss: -0.026498] [G loss: -0.160356] [d1 loss: 0.080382] [d2 loss: 0.082656]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 140/676] [D loss: -0.007979] [G loss: -0.151593] [d1 loss: 0.065178] [d2 loss: 0.060235]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 316/500] [Batch 160/676] [D loss: -0.011570] [G loss: -0.133477] [d1 loss: 0.085568] [d2 loss: 0.099974]  [sq d1 d2: 0.000208]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 180/676] [D loss: -0.007936] [G loss: -0.133033] [d1 loss: 0.100622] [d2 loss: 0.118763]  [sq d1 d2: 0.000329]  [num0: 13.000000] [num1 51.000000]
[Epoch 316/500] [Batch 200/676] [D loss: -0.006922] [G loss: -0.118452] [d1 loss: 0.144882] [d2 loss: 0.141314]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 220/676] [D loss: -0.005181] [G loss: -0.079055] [d1 loss: 0.095976] [d2 loss: 0.086354]  [sq d1 d2: 0.000093]  [num0: 17.000000] [num1 47.000000]
[Epoch 316/500] [Batch 240/676] [D loss: -0.007078] [G loss: -0.044809] [d1 loss: 0.140996] [d2 loss: 0.181818]  [sq d1 d2: 0.001666]  [num0: 20.000000] [num1 44.000000]
[Epoch 316/500] [Batch 260/676] [D loss: -0.015213] [G loss: 0.000534] [d1 loss: 0.077048] [d2 loss: 0.072877]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 280/676] [D loss: -0.009748] [G loss: 0.039819] [d1 loss: 0.109093] [d2 loss: 0.114894]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 300/676] [D loss: -0.007266] [G loss: 0.048535] [d1 loss: 0.087991] [d2 loss: 0.085261]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 320/676] [D loss: -0.004835] [G loss: 0.077912] [d1 loss: 0.125256] [d2 loss: 0.139797]  [sq d1 d2: 0.000211]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 340/676] [D loss: -0.001736] [G loss: 0.081824] [d1 loss: 0.159056] [d2 loss: 0.161853]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 360/676] [D loss: -0.024089] [G loss: 0.055931] [d1 loss: 0.048921] [d2 loss: 0.054415]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 380/676] [D loss: -0.021407] [G loss: 0.058251] [d1 loss: 0.030363] [d2 loss: 0.042291]  [sq d1 d2: 0.000142]  [num0: 13.000000] [num1 51.000000]
[Epoch 316/500] [Batch 400/676] [D loss: -0.013640] [G loss: 0.033866] [d1 loss: 0.030624] [d2 loss: 0.037037]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 420/676] [D loss: 0.001779] [G loss: 0.016758] [d1 loss: 0.047252] [d2 loss: 0.048212]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 316/500] [Batch 440/676] [D loss: 0.011637] [G loss: -0.024446] [d1 loss: 0.054070] [d2 loss: 0.061562]  [sq d1 d2: 0.000056]  [num0: 13.000000] [num1 51.000000]
[Epoch 316/500] [Batch 460/676] [D loss: -0.007188] [G loss: -0.062767] [d1 loss: 0.070814] [d2 loss: 0.086779]  [sq d1 d2: 0.000255]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 480/676] [D loss: -0.010709] [G loss: -0.108183] [d1 loss: 0.075824] [d2 loss: 0.066946]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 500/676] [D loss: -0.000762] [G loss: -0.124065] [d1 loss: 0.053282] [d2 loss: 0.053231]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 316/500] [Batch 520/676] [D loss: 0.016827] [G loss: -0.157389] [d1 loss: 0.099554] [d2 loss: 0.091270]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 316/500] [Batch 540/676] [D loss: -0.004081] [G loss: -0.163686] [d1 loss: 0.093347] [d2 loss: 0.101621]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 316/500] [Batch 560/676] [D loss: -0.008630] [G loss: -0.206199] [d1 loss: 0.031628] [d2 loss: 0.029076]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 316/500] [Batch 580/676] [D loss: -0.020581] [G loss: -0.221683] [d1 loss: 0.051275] [d2 loss: 0.061599]  [sq d1 d2: 0.000107]  [num0: 15.000000] [num1 49.000000]
[Epoch 316/500] [Batch 600/676] [D loss: -0.024513] [G loss: -0.247642] [d1 loss: 0.106787] [d2 loss: 0.087738]  [sq d1 d2: 0.000363]  [num0: 16.000000] [num1 48.000000]
[Epoch 316/500] [Batch 620/676] [D loss: -0.001136] [G loss: -0.245206] [d1 loss: 0.066976] [d2 loss: 0.047792]  [sq d1 d2: 0.000368]  [num0: 13.000000] [num1 51.000000]
[Epoch 316/500] [Batch 640/676] [D loss: -0.003165] [G loss: -0.249122] [d1 loss: 0.122534] [d2 loss: 0.136494]  [sq d1 d2: 0.000195]  [num0: 13.000000] [num1 51.000000]
[Epoch 316/500] [Batch 660/676] [D loss: -0.016218] [G loss: -0.249504] [d1 loss: 0.067418] [d2 loss: 0.083810]  [sq d1 d2: 0.000269]  [num0: 18.000000] [num1 46.000000]
[Epoch 317/500] [Batch 0/676] [D loss: -0.010341] [G loss: -0.280250] [d1 loss: 0.110113] [d2 loss: 0.110239]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 317/500] [Batch 20/676] [D loss: -0.001345] [G loss: -0.226568] [d1 loss: 0.100943] [d2 loss: 0.111388]  [sq d1 d2: 0.000109]  [num0: 16.000000] [num1 48.000000]
[Epoch 317/500] [Batch 40/676] [D loss: -0.005749] [G loss: -0.212450] [d1 loss: 0.069680] [d2 loss: 0.073283]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 317/500] [Batch 60/676] [D loss: 0.002834] [G loss: -0.179469] [d1 loss: 0.056629] [d2 loss: 0.043902]  [sq d1 d2: 0.000162]  [num0: 13.000000] [num1 51.000000]
[Epoch 317/500] [Batch 80/676] [D loss: 0.005131] [G loss: -0.126018] [d1 loss: 0.166088] [d2 loss: 0.158231]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 317/500] [Batch 100/676] [D loss: -0.007779] [G loss: -0.104006] [d1 loss: 0.052093] [d2 loss: 0.047198]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 317/500] [Batch 120/676] [D loss: -0.009114] [G loss: -0.098828] [d1 loss: 0.158929] [d2 loss: 0.145620]  [sq d1 d2: 0.000177]  [num0: 13.000000] [num1 51.000000]
[Epoch 317/500] [Batch 140/676] [D loss: -0.007722] [G loss: -0.091801] [d1 loss: 0.038052] [d2 loss: 0.037677]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 160/676] [D loss: -0.018156] [G loss: -0.079869] [d1 loss: 0.079002] [d2 loss: 0.059482]  [sq d1 d2: 0.000381]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 180/676] [D loss: -0.024131] [G loss: -0.071037] [d1 loss: 0.149377] [d2 loss: 0.157048]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 317/500] [Batch 200/676] [D loss: -0.013130] [G loss: -0.037639] [d1 loss: 0.094864] [d2 loss: 0.104675]  [sq d1 d2: 0.000096]  [num0: 14.000000] [num1 50.000000]
[Epoch 317/500] [Batch 220/676] [D loss: -0.023898] [G loss: -0.051066] [d1 loss: 0.056804] [d2 loss: 0.066149]  [sq d1 d2: 0.000087]  [num0: 17.000000] [num1 47.000000]
[Epoch 317/500] [Batch 240/676] [D loss: -0.013027] [G loss: -0.041549] [d1 loss: 0.110009] [d2 loss: 0.117093]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 260/676] [D loss: -0.010616] [G loss: -0.049329] [d1 loss: 0.046998] [d2 loss: 0.047872]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 317/500] [Batch 280/676] [D loss: -0.001346] [G loss: -0.055986] [d1 loss: 0.107857] [d2 loss: 0.151901]  [sq d1 d2: 0.001940]  [num0: 17.000000] [num1 47.000000]
[Epoch 317/500] [Batch 300/676] [D loss: -0.012325] [G loss: -0.103349] [d1 loss: 0.061085] [d2 loss: 0.056316]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 317/500] [Batch 320/676] [D loss: -0.012707] [G loss: -0.114632] [d1 loss: 0.105298] [d2 loss: 0.107120]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 340/676] [D loss: -0.000315] [G loss: -0.074563] [d1 loss: 0.052060] [d2 loss: 0.052924]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 317/500] [Batch 360/676] [D loss: -0.011930] [G loss: -0.077189] [d1 loss: 0.080600] [d2 loss: 0.077400]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 317/500] [Batch 380/676] [D loss: -0.005671] [G loss: -0.131352] [d1 loss: 0.077589] [d2 loss: 0.078252]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 317/500] [Batch 400/676] [D loss: -0.009164] [G loss: -0.115370] [d1 loss: 0.055602] [d2 loss: 0.074528]  [sq d1 d2: 0.000358]  [num0: 13.000000] [num1 51.000000]
[Epoch 317/500] [Batch 420/676] [D loss: -0.003866] [G loss: -0.104711] [d1 loss: 0.051076] [d2 loss: 0.075359]  [sq d1 d2: 0.000590]  [num0: 14.000000] [num1 50.000000]

[Epoch 317/500] [Batch 440/676] [D loss: -0.010543] [G loss: -0.115379] [d1 loss: 0.074606] [d2 loss: 0.084006]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 317/500] [Batch 460/676] [D loss: -0.008980] [G loss: -0.103296] [d1 loss: 0.042020] [d2 loss: 0.036490]  [sq d1 d2: 0.000031]  [num0: 19.000000] [num1 45.000000]
[Epoch 317/500] [Batch 480/676] [D loss: -0.007671] [G loss: -0.116282] [d1 loss: 0.079872] [d2 loss: 0.066811]  [sq d1 d2: 0.000171]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 500/676] [D loss: -0.023608] [G loss: -0.095961] [d1 loss: 0.091971] [d2 loss: 0.046570]  [sq d1 d2: 0.002061]  [num0: 13.000000] [num1 51.000000]
[Epoch 317/500] [Batch 520/676] [D loss: -0.006016] [G loss: -0.115217] [d1 loss: 0.072769] [d2 loss: 0.060971]  [sq d1 d2: 0.000139]  [num0: 14.000000] [num1 50.000000]
[Epoch 317/500] [Batch 540/676] [D loss: -0.013881] [G loss: -0.127697] [d1 loss: 0.160256] [d2 loss: 0.200616]  [sq d1 d2: 0.001629]  [num0: 12.000000] [num1 52.000000]
[Epoch 317/500] [Batch 560/676] [D loss: -0.010332] [G loss: -0.104413] [d1 loss: 0.076194] [d2 loss: 0.075686]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 317/500] [Batch 580/676] [D loss: 0.006944] [G loss: -0.090134] [d1 loss: 0.037667] [d2 loss: 0.036849]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 317/500] [Batch 600/676] [D loss: 0.001176] [G loss: -0.077918] [d1 loss: 0.073579] [d2 loss: 0.070568]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 317/500] [Batch 620/676] [D loss: 0.005166] [G loss: -0.059723] [d1 loss: 0.087808] [d2 loss: 0.081396]  [sq d1 d2: 0.000041]  [num0: 19.000000] [num1 45.000000]
[Epoch 317/500] [Batch 640/676] [D loss: -0.013328] [G loss: -0.062768] [d1 loss: 0.083279] [d2 loss: 0.080729]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 317/500] [Batch 660/676] [D loss: 0.003209] [G loss: -0.037394] [d1 loss: 0.094311] [d2 loss: 0.090964]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 0/676] [D loss: -0.011176] [G loss: -0.041492] [d1 loss: 0.092565] [d2 loss: 0.131770]  [sq d1 d2: 0.001537]  [num0: 11.000000] [num1 53.000000]
[Epoch 318/500] [Batch 20/676] [D loss: -0.019472] [G loss: -0.049271] [d1 loss: 0.060987] [d2 loss: 0.074834]  [sq d1 d2: 0.000192]  [num0: 12.000000] [num1 52.000000]
[Epoch 318/500] [Batch 40/676] [D loss: -0.012586] [G loss: -0.035470] [d1 loss: 0.068230] [d2 loss: 0.079257]  [sq d1 d2: 0.000122]  [num0: 16.000000] [num1 48.000000]
[Epoch 318/500] [Batch 60/676] [D loss: -0.008648] [G loss: -0.029357] [d1 loss: 0.045478] [d2 loss: 0.046737]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 318/500] [Batch 80/676] [D loss: -0.022904] [G loss: -0.016100] [d1 loss: 0.049819] [d2 loss: 0.053916]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 318/500] [Batch 100/676] [D loss: -0.018477] [G loss: -0.029621] [d1 loss: 0.037237] [d2 loss: 0.038493]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 318/500] [Batch 120/676] [D loss: 0.002381] [G loss: -0.046483] [d1 loss: 0.161035] [d2 loss: 0.168595]  [sq d1 d2: 0.000057]  [num0: 16.000000] [num1 48.000000]
[Epoch 318/500] [Batch 140/676] [D loss: -0.005102] [G loss: -0.038551] [d1 loss: 0.077180] [d2 loss: 0.064405]  [sq d1 d2: 0.000163]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 160/676] [D loss: -0.000967] [G loss: -0.087809] [d1 loss: 0.041606] [d2 loss: 0.041311]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 180/676] [D loss: -0.006013] [G loss: -0.041769] [d1 loss: 0.100195] [d2 loss: 0.108848]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 318/500] [Batch 200/676] [D loss: -0.002360] [G loss: -0.066593] [d1 loss: 0.144305] [d2 loss: 0.135058]  [sq d1 d2: 0.000086]  [num0: 13.000000] [num1 51.000000]
[Epoch 318/500] [Batch 220/676] [D loss: -0.010097] [G loss: -0.051454] [d1 loss: 0.132068] [d2 loss: 0.123443]  [sq d1 d2: 0.000074]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 240/676] [D loss: -0.008984] [G loss: -0.049969] [d1 loss: 0.079671] [d2 loss: 0.070907]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 318/500] [Batch 260/676] [D loss: -0.015606] [G loss: -0.037352] [d1 loss: 0.051976] [d2 loss: 0.054323]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 318/500] [Batch 280/676] [D loss: -0.013827] [G loss: -0.051218] [d1 loss: 0.070528] [d2 loss: 0.087849]  [sq d1 d2: 0.000300]  [num0: 14.000000] [num1 50.000000]
[Epoch 318/500] [Batch 300/676] [D loss: 0.001539] [G loss: -0.056299] [d1 loss: 0.140643] [d2 loss: 0.157985]  [sq d1 d2: 0.000301]  [num0: 14.000000] [num1 50.000000]
[Epoch 318/500] [Batch 320/676] [D loss: 0.001689] [G loss: -0.054841] [d1 loss: 0.093338] [d2 loss: 0.094789]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 318/500] [Batch 340/676] [D loss: -0.028727] [G loss: -0.065917] [d1 loss: 0.028667] [d2 loss: 0.027050]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 360/676] [D loss: -0.028321] [G loss: -0.065235] [d1 loss: 0.176705] [d2 loss: 0.155714]  [sq d1 d2: 0.000441]  [num0: 18.000000] [num1 46.000000]
[Epoch 318/500] [Batch 380/676] [D loss: -0.045697] [G loss: -0.080409] [d1 loss: 0.094352] [d2 loss: 0.113335]  [sq d1 d2: 0.000360]  [num0: 20.000000] [num1 44.000000]
[Epoch 318/500] [Batch 400/676] [D loss: -0.018273] [G loss: -0.087600] [d1 loss: 0.127727] [d2 loss: 0.138617]  [sq d1 d2: 0.000119]  [num0: 20.000000] [num1 44.000000]
[Epoch 318/500] [Batch 420/676] [D loss: 0.013949] [G loss: -0.069766] [d1 loss: 0.090179] [d2 loss: 0.097326]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 440/676] [D loss: 0.016401] [G loss: -0.102967] [d1 loss: 0.059231] [d2 loss: 0.054784]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 318/500] [Batch 460/676] [D loss: -0.014225] [G loss: -0.099168] [d1 loss: 0.142000] [d2 loss: 0.151776]  [sq d1 d2: 0.000096]  [num0: 21.000000] [num1 43.000000]
[Epoch 318/500] [Batch 480/676] [D loss: -0.005653] [G loss: -0.137388] [d1 loss: 0.089822] [d2 loss: 0.078544]  [sq d1 d2: 0.000127]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 500/676] [D loss: -0.005365] [G loss: -0.112520] [d1 loss: 0.052758] [d2 loss: 0.052043]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 520/676] [D loss: -0.021096] [G loss: -0.147340] [d1 loss: 0.109060] [d2 loss: 0.103492]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 318/500] [Batch 540/676] [D loss: -0.015395] [G loss: -0.165191] [d1 loss: 0.131144] [d2 loss: 0.133301]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 318/500] [Batch 560/676] [D loss: -0.035892] [G loss: -0.203079] [d1 loss: 0.092470] [d2 loss: 0.097054]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 318/500] [Batch 580/676] [D loss: -0.018253] [G loss: -0.210321] [d1 loss: 0.062123] [d2 loss: 0.071137]  [sq d1 d2: 0.000081]  [num0: 18.000000] [num1 46.000000]
[Epoch 318/500] [Batch 600/676] [D loss: -0.014021] [G loss: -0.247523] [d1 loss: 0.074216] [d2 loss: 0.072991]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 318/500] [Batch 620/676] [D loss: -0.000791] [G loss: -0.216096] [d1 loss: 0.091722] [d2 loss: 0.099951]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 318/500] [Batch 640/676] [D loss: 0.007143] [G loss: -0.178452] [d1 loss: 0.071392] [d2 loss: 0.097372]  [sq d1 d2: 0.000675]  [num0: 17.000000] [num1 47.000000]
[Epoch 318/500] [Batch 660/676] [D loss: -0.011019] [G loss: -0.192799] [d1 loss: 0.064505] [d2 loss: 0.059240]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 319/500] [Batch 0/676] [D loss: 0.009246] [G loss: -0.167320] [d1 loss: 0.098991] [d2 loss: 0.128726]  [sq d1 d2: 0.000884]  [num0: 15.000000] [num1 49.000000]
[Epoch 319/500] [Batch 20/676] [D loss: -0.008938] [G loss: -0.133505] [d1 loss: 0.095599] [d2 loss: 0.101687]  [sq d1 d2: 0.000037]  [num0: 13.000000] [num1 51.000000]
[Epoch 319/500] [Batch 40/676] [D loss: 0.005898] [G loss: -0.141350] [d1 loss: 0.052867] [d2 loss: 0.041662]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 60/676] [D loss: -0.001675] [G loss: -0.132685] [d1 loss: 0.054023] [d2 loss: 0.049413]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 319/500] [Batch 80/676] [D loss: -0.016613] [G loss: -0.103294] [d1 loss: 0.043679] [d2 loss: 0.047994]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 319/500] [Batch 100/676] [D loss: -0.006436] [G loss: -0.108996] [d1 loss: 0.154328] [d2 loss: 0.125303]  [sq d1 d2: 0.000842]  [num0: 15.000000] [num1 49.000000]

[Epoch 319/500] [Batch 120/676] [D loss: -0.002254] [G loss: -0.114703] [d1 loss: 0.062216] [d2 loss: 0.074929]  [sq d1 d2: 0.000162]  [num0: 17.000000] [num1 47.000000]
[Epoch 319/500] [Batch 140/676] [D loss: -0.012996] [G loss: -0.100286] [d1 loss: 0.121152] [d2 loss: 0.104744]  [sq d1 d2: 0.000269]  [num0: 14.000000] [num1 50.000000]
[Epoch 319/500] [Batch 160/676] [D loss: -0.020534] [G loss: -0.105409] [d1 loss: 0.104703] [d2 loss: 0.111331]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 319/500] [Batch 180/676] [D loss: -0.019174] [G loss: -0.100452] [d1 loss: 0.114698] [d2 loss: 0.105794]  [sq d1 d2: 0.000079]  [num0: 13.000000] [num1 51.000000]
[Epoch 319/500] [Batch 200/676] [D loss: -0.024297] [G loss: -0.118456] [d1 loss: 0.108220] [d2 loss: 0.098168]  [sq d1 d2: 0.000101]  [num0: 12.000000] [num1 52.000000]
[Epoch 319/500] [Batch 220/676] [D loss: -0.016114] [G loss: -0.128149] [d1 loss: 0.077870] [d2 loss: 0.074150]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 319/500] [Batch 240/676] [D loss: 0.009319] [G loss: -0.094289] [d1 loss: 0.044636] [d2 loss: 0.028840]  [sq d1 d2: 0.000250]  [num0: 14.000000] [num1 50.000000]
[Epoch 319/500] [Batch 260/676] [D loss: 0.003265] [G loss: -0.092988] [d1 loss: 0.110049] [d2 loss: 0.122598]  [sq d1 d2: 0.000157]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 280/676] [D loss: -0.000841] [G loss: -0.047155] [d1 loss: 0.082043] [d2 loss: 0.097917]  [sq d1 d2: 0.000252]  [num0: 19.000000] [num1 45.000000]
[Epoch 319/500] [Batch 300/676] [D loss: -0.011786] [G loss: -0.061274] [d1 loss: 0.167391] [d2 loss: 0.143618]  [sq d1 d2: 0.000565]  [num0: 21.000000] [num1 43.000000]
[Epoch 319/500] [Batch 320/676] [D loss: 0.003204] [G loss: -0.059973] [d1 loss: 0.081596] [d2 loss: 0.096546]  [sq d1 d2: 0.000224]  [num0: 14.000000] [num1 50.000000]
[Epoch 319/500] [Batch 340/676] [D loss: -0.000159] [G loss: -0.047311] [d1 loss: 0.079935] [d2 loss: 0.083918]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 319/500] [Batch 360/676] [D loss: -0.007316] [G loss: -0.030641] [d1 loss: 0.068077] [d2 loss: 0.075001]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 380/676] [D loss: -0.021243] [G loss: -0.023097] [d1 loss: 0.191006] [d2 loss: 0.180048]  [sq d1 d2: 0.000120]  [num0: 15.000000] [num1 49.000000]
[Epoch 319/500] [Batch 400/676] [D loss: -0.029201] [G loss: -0.022557] [d1 loss: 0.087604] [d2 loss: 0.104654]  [sq d1 d2: 0.000291]  [num0: 18.000000] [num1 46.000000]
[Epoch 319/500] [Batch 420/676] [D loss: -0.022200] [G loss: -0.019317] [d1 loss: 0.101168] [d2 loss: 0.091309]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 440/676] [D loss: -0.013965] [G loss: -0.026124] [d1 loss: 0.245232] [d2 loss: 0.274642]  [sq d1 d2: 0.000865]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 460/676] [D loss: -0.004420] [G loss: -0.057400] [d1 loss: 0.090641] [d2 loss: 0.091357]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 319/500] [Batch 480/676] [D loss: -0.011850] [G loss: -0.011388] [d1 loss: 0.070868] [d2 loss: 0.066014]  [sq d1 d2: 0.000024]  [num0: 20.000000] [num1 44.000000]
[Epoch 319/500] [Batch 500/676] [D loss: -0.000528] [G loss: -0.035864] [d1 loss: 0.098896] [d2 loss: 0.131854]  [sq d1 d2: 0.001086]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 520/676] [D loss: -0.011322] [G loss: -0.078259] [d1 loss: 0.051784] [d2 loss: 0.072225]  [sq d1 d2: 0.000418]  [num0: 12.000000] [num1 52.000000]
[Epoch 319/500] [Batch 540/676] [D loss: 0.001273] [G loss: -0.063567] [d1 loss: 0.017280] [d2 loss: 0.030024]  [sq d1 d2: 0.000162]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 560/676] [D loss: -0.004127] [G loss: -0.079202] [d1 loss: 0.041440] [d2 loss: 0.049741]  [sq d1 d2: 0.000069]  [num0: 18.000000] [num1 46.000000]
[Epoch 319/500] [Batch 580/676] [D loss: -0.007899] [G loss: -0.104245] [d1 loss: 0.100967] [d2 loss: 0.102827]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 319/500] [Batch 600/676] [D loss: -0.018439] [G loss: -0.114625] [d1 loss: 0.171412] [d2 loss: 0.162515]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 620/676] [D loss: -0.017252] [G loss: -0.189250] [d1 loss: 0.056603] [d2 loss: 0.051075]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 319/500] [Batch 640/676] [D loss: -0.015539] [G loss: -0.187322] [d1 loss: 0.054772] [d2 loss: 0.053276]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 319/500] [Batch 660/676] [D loss: 0.000532] [G loss: -0.210693] [d1 loss: 0.070218] [d2 loss: 0.076957]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 0/676] [D loss: -0.004399] [G loss: -0.181049] [d1 loss: 0.098304] [d2 loss: 0.110611]  [sq d1 d2: 0.000151]  [num0: 18.000000] [num1 46.000000]
[Epoch 320/500] [Batch 20/676] [D loss: -0.012778] [G loss: -0.175105] [d1 loss: 0.104232] [d2 loss: 0.133122]  [sq d1 d2: 0.000835]  [num0: 18.000000] [num1 46.000000]
[Epoch 320/500] [Batch 40/676] [D loss: -0.017528] [G loss: -0.196594] [d1 loss: 0.081310] [d2 loss: 0.061191]  [sq d1 d2: 0.000405]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 60/676] [D loss: -0.013060] [G loss: -0.184058] [d1 loss: 0.109299] [d2 loss: 0.090770]  [sq d1 d2: 0.000343]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 80/676] [D loss: -0.002331] [G loss: -0.165088] [d1 loss: 0.026204] [d2 loss: 0.024210]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 100/676] [D loss: -0.000744] [G loss: -0.164008] [d1 loss: 0.028868] [d2 loss: 0.051660]  [sq d1 d2: 0.000519]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 120/676] [D loss: -0.004470] [G loss: -0.177269] [d1 loss: 0.054868] [d2 loss: 0.045009]  [sq d1 d2: 0.000097]  [num0: 20.000000] [num1 44.000000]
[Epoch 320/500] [Batch 140/676] [D loss: -0.000515] [G loss: -0.153984] [d1 loss: 0.068182] [d2 loss: 0.077097]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 320/500] [Batch 160/676] [D loss: -0.013326] [G loss: -0.151864] [d1 loss: 0.045549] [d2 loss: 0.040020]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 320/500] [Batch 180/676] [D loss: -0.012661] [G loss: -0.165912] [d1 loss: 0.129103] [d2 loss: 0.144900]  [sq d1 d2: 0.000250]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 200/676] [D loss: -0.014896] [G loss: -0.146646] [d1 loss: 0.091468] [d2 loss: 0.100441]  [sq d1 d2: 0.000081]  [num0: 13.000000] [num1 51.000000]
[Epoch 320/500] [Batch 220/676] [D loss: -0.018027] [G loss: -0.137745] [d1 loss: 0.083375] [d2 loss: 0.109940]  [sq d1 d2: 0.000706]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 240/676] [D loss: -0.008485] [G loss: -0.122352] [d1 loss: 0.041014] [d2 loss: 0.050368]  [sq d1 d2: 0.000088]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 260/676] [D loss: -0.013186] [G loss: -0.122254] [d1 loss: 0.184517] [d2 loss: 0.170961]  [sq d1 d2: 0.000184]  [num0: 19.000000] [num1 45.000000]
[Epoch 320/500] [Batch 280/676] [D loss: -0.011911] [G loss: -0.124557] [d1 loss: 0.057238] [d2 loss: 0.060445]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 300/676] [D loss: -0.005879] [G loss: -0.107666] [d1 loss: 0.078238] [d2 loss: 0.071630]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 320/676] [D loss: -0.014930] [G loss: -0.104866] [d1 loss: 0.082683] [d2 loss: 0.096414]  [sq d1 d2: 0.000189]  [num0: 12.000000] [num1 52.000000]
[Epoch 320/500] [Batch 340/676] [D loss: 0.000467] [G loss: -0.109728] [d1 loss: 0.139643] [d2 loss: 0.141260]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 320/500] [Batch 360/676] [D loss: -0.013899] [G loss: -0.095104] [d1 loss: 0.053998] [d2 loss: 0.054854]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 380/676] [D loss: 0.000381] [G loss: -0.092257] [d1 loss: 0.052626] [d2 loss: 0.061535]  [sq d1 d2: 0.000079]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 400/676] [D loss: -0.015143] [G loss: -0.081846] [d1 loss: 0.034616] [d2 loss: 0.038104]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 420/676] [D loss: -0.006213] [G loss: -0.052557] [d1 loss: 0.078172] [d2 loss: 0.068626]  [sq d1 d2: 0.000091]  [num0: 18.000000] [num1 46.000000]
[Epoch 320/500] [Batch 440/676] [D loss: -0.002198] [G loss: -0.059104] [d1 loss: 0.040762] [d2 loss: 0.048283]  [sq d1 d2: 0.000057]  [num0: 12.000000] [num1 52.000000]
[Epoch 320/500] [Batch 460/676] [D loss: -0.018341] [G loss: -0.040528] [d1 loss: 0.077981] [d2 loss: 0.095611]  [sq d1 d2: 0.000311]  [num0: 16.000000] [num1 48.000000]

[Epoch 320/500] [Batch 480/676] [D loss: -0.017868] [G loss: -0.018804] [d1 loss: 0.087282] [d2 loss: 0.093022]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 320/500] [Batch 500/676] [D loss: -0.008871] [G loss: -0.006067] [d1 loss: 0.140700] [d2 loss: 0.199583]  [sq d1 d2: 0.003467]  [num0: 18.000000] [num1 46.000000]
[Epoch 320/500] [Batch 520/676] [D loss: -0.013463] [G loss: -0.022024] [d1 loss: 0.046170] [d2 loss: 0.052965]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 320/500] [Batch 540/676] [D loss: -0.007566] [G loss: -0.038235] [d1 loss: 0.068920] [d2 loss: 0.099816]  [sq d1 d2: 0.000955]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 560/676] [D loss: -0.012835] [G loss: -0.023500] [d1 loss: 0.107727] [d2 loss: 0.131575]  [sq d1 d2: 0.000569]  [num0: 13.000000] [num1 51.000000]
[Epoch 320/500] [Batch 580/676] [D loss: -0.014658] [G loss: -0.023790] [d1 loss: 0.041743] [d2 loss: 0.044067]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 320/500] [Batch 600/676] [D loss: -0.011734] [G loss: -0.043011] [d1 loss: 0.074404] [d2 loss: 0.103103]  [sq d1 d2: 0.000824]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 620/676] [D loss: -0.006923] [G loss: -0.065943] [d1 loss: 0.050683] [d2 loss: 0.081087]  [sq d1 d2: 0.000924]  [num0: 15.000000] [num1 49.000000]
[Epoch 320/500] [Batch 640/676] [D loss: -0.000015] [G loss: -0.026276] [d1 loss: 0.077579] [d2 loss: 0.081396]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 320/500] [Batch 660/676] [D loss: 0.000115] [G loss: -0.047179] [d1 loss: 0.075468] [d2 loss: 0.177866]  [sq d1 d2: 0.010485]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 0/676] [D loss: -0.006944] [G loss: -0.043694] [d1 loss: 0.051809] [d2 loss: 0.043761]  [sq d1 d2: 0.000065]  [num0: 20.000000] [num1 44.000000]
[Epoch 321/500] [Batch 20/676] [D loss: -0.014445] [G loss: -0.035349] [d1 loss: 0.054029] [d2 loss: 0.049937]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 321/500] [Batch 40/676] [D loss: 0.010006] [G loss: 0.000122] [d1 loss: 0.040056] [d2 loss: 0.058370]  [sq d1 d2: 0.000335]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 60/676] [D loss: 0.010462] [G loss: -0.033001] [d1 loss: 0.084272] [d2 loss: 0.090518]  [sq d1 d2: 0.000039]  [num0: 10.000000] [num1 54.000000]
[Epoch 321/500] [Batch 80/676] [D loss: -0.011338] [G loss: -0.017577] [d1 loss: 0.078616] [d2 loss: 0.082064]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 321/500] [Batch 100/676] [D loss: -0.006533] [G loss: -0.025801] [d1 loss: 0.056379] [d2 loss: 0.060403]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 321/500] [Batch 120/676] [D loss: -0.004678] [G loss: -0.009398] [d1 loss: 0.040119] [d2 loss: 0.048064]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 321/500] [Batch 140/676] [D loss: -0.009018] [G loss: -0.017973] [d1 loss: 0.103751] [d2 loss: 0.100348]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 160/676] [D loss: -0.007100] [G loss: -0.055121] [d1 loss: 0.045273] [d2 loss: 0.043738]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 180/676] [D loss: -0.023806] [G loss: -0.035883] [d1 loss: 0.087814] [d2 loss: 0.082448]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 321/500] [Batch 200/676] [D loss: -0.009025] [G loss: -0.065923] [d1 loss: 0.085420] [d2 loss: 0.080309]  [sq d1 d2: 0.000026]  [num0: 12.000000] [num1 52.000000]
[Epoch 321/500] [Batch 220/676] [D loss: -0.013928] [G loss: -0.076652] [d1 loss: 0.070538] [d2 loss: 0.098828]  [sq d1 d2: 0.000800]  [num0: 19.000000] [num1 45.000000]
[Epoch 321/500] [Batch 240/676] [D loss: -0.004621] [G loss: -0.102517] [d1 loss: 0.068730] [d2 loss: 0.075017]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 260/676] [D loss: -0.007853] [G loss: -0.086426] [d1 loss: 0.083002] [d2 loss: 0.083971]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 321/500] [Batch 280/676] [D loss: -0.001632] [G loss: -0.132229] [d1 loss: 0.041909] [d2 loss: 0.057324]  [sq d1 d2: 0.000238]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 300/676] [D loss: -0.000876] [G loss: -0.116798] [d1 loss: 0.107121] [d2 loss: 0.124823]  [sq d1 d2: 0.000313]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 320/676] [D loss: -0.013296] [G loss: -0.099975] [d1 loss: 0.058853] [d2 loss: 0.076957]  [sq d1 d2: 0.000328]  [num0: 19.000000] [num1 45.000000]
[Epoch 321/500] [Batch 340/676] [D loss: -0.014479] [G loss: -0.089571] [d1 loss: 0.051092] [d2 loss: 0.050240]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 321/500] [Batch 360/676] [D loss: -0.017519] [G loss: -0.115745] [d1 loss: 0.050377] [d2 loss: 0.040678]  [sq d1 d2: 0.000094]  [num0: 17.000000] [num1 47.000000]
[Epoch 321/500] [Batch 380/676] [D loss: -0.011378] [G loss: -0.136869] [d1 loss: 0.029908] [d2 loss: 0.050232]  [sq d1 d2: 0.000413]  [num0: 16.000000] [num1 48.000000]
[Epoch 321/500] [Batch 400/676] [D loss: -0.029865] [G loss: -0.137005] [d1 loss: 0.098300] [d2 loss: 0.119803]  [sq d1 d2: 0.000462]  [num0: 19.000000] [num1 45.000000]
[Epoch 321/500] [Batch 420/676] [D loss: -0.006517] [G loss: -0.137213] [d1 loss: 0.025694] [d2 loss: 0.043016]  [sq d1 d2: 0.000300]  [num0: 16.000000] [num1 48.000000]
[Epoch 321/500] [Batch 440/676] [D loss: -0.005297] [G loss: -0.137767] [d1 loss: 0.044590] [d2 loss: 0.057622]  [sq d1 d2: 0.000170]  [num0: 16.000000] [num1 48.000000]
[Epoch 321/500] [Batch 460/676] [D loss: -0.015455] [G loss: -0.156815] [d1 loss: 0.041865] [d2 loss: 0.070487]  [sq d1 d2: 0.000819]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 480/676] [D loss: -0.023770] [G loss: -0.146434] [d1 loss: 0.139005] [d2 loss: 0.143739]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 500/676] [D loss: -0.021168] [G loss: -0.119056] [d1 loss: 0.046704] [d2 loss: 0.052822]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 520/676] [D loss: -0.007700] [G loss: -0.142103] [d1 loss: 0.113752] [d2 loss: 0.110112]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 321/500] [Batch 540/676] [D loss: -0.017928] [G loss: -0.134060] [d1 loss: 0.087998] [d2 loss: 0.117407]  [sq d1 d2: 0.000865]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 560/676] [D loss: -0.006746] [G loss: -0.149096] [d1 loss: 0.067171] [d2 loss: 0.058375]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 321/500] [Batch 580/676] [D loss: 0.009459] [G loss: -0.173913] [d1 loss: 0.133978] [d2 loss: 0.120934]  [sq d1 d2: 0.000170]  [num0: 16.000000] [num1 48.000000]
[Epoch 321/500] [Batch 600/676] [D loss: -0.004343] [G loss: -0.167754] [d1 loss: 0.075530] [d2 loss: 0.097999]  [sq d1 d2: 0.000505]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 620/676] [D loss: 0.009243] [G loss: -0.174091] [d1 loss: 0.082680] [d2 loss: 0.137257]  [sq d1 d2: 0.002979]  [num0: 12.000000] [num1 52.000000]
[Epoch 321/500] [Batch 640/676] [D loss: -0.018318] [G loss: -0.178786] [d1 loss: 0.045356] [d2 loss: 0.061037]  [sq d1 d2: 0.000246]  [num0: 14.000000] [num1 50.000000]
[Epoch 321/500] [Batch 660/676] [D loss: -0.010942] [G loss: -0.180136] [d1 loss: 0.041213] [d2 loss: 0.056418]  [sq d1 d2: 0.000231]  [num0: 19.000000] [num1 45.000000]
[Epoch 322/500] [Batch 0/676] [D loss: 0.014601] [G loss: -0.200082] [d1 loss: 0.057894] [d2 loss: 0.074165]  [sq d1 d2: 0.000265]  [num0: 19.000000] [num1 45.000000]
[Epoch 322/500] [Batch 20/676] [D loss: -0.008595] [G loss: -0.181022] [d1 loss: 0.112220] [d2 loss: 0.113515]  [sq d1 d2: 0.000002]  [num0: 10.000000] [num1 54.000000]
[Epoch 322/500] [Batch 40/676] [D loss: 0.004605] [G loss: -0.208893] [d1 loss: 0.170234] [d2 loss: 0.163166]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 60/676] [D loss: 0.015663] [G loss: -0.200539] [d1 loss: 0.032893] [d2 loss: 0.080253]  [sq d1 d2: 0.002243]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 80/676] [D loss: -0.019639] [G loss: -0.186290] [d1 loss: 0.037737] [d2 loss: 0.033471]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 100/676] [D loss: -0.001156] [G loss: -0.177114] [d1 loss: 0.062793] [d2 loss: 0.051356]  [sq d1 d2: 0.000131]  [num0: 15.000000] [num1 49.000000]
[Epoch 322/500] [Batch 120/676] [D loss: -0.011591] [G loss: -0.131807] [d1 loss: 0.040186] [d2 loss: 0.043821]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 322/500] [Batch 140/676] [D loss: -0.006008] [G loss: -0.111518] [d1 loss: 0.029457] [d2 loss: 0.031544]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]

[Epoch 322/500] [Batch 160/676] [D loss: -0.006733] [G loss: -0.067323] [d1 loss: 0.037093] [d2 loss: 0.036033]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 322/500] [Batch 180/676] [D loss: -0.020394] [G loss: -0.056059] [d1 loss: 0.083780] [d2 loss: 0.047888]  [sq d1 d2: 0.001288]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 200/676] [D loss: -0.012142] [G loss: -0.041633] [d1 loss: 0.039952] [d2 loss: 0.062417]  [sq d1 d2: 0.000505]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 220/676] [D loss: -0.007757] [G loss: -0.029307] [d1 loss: 0.027551] [d2 loss: 0.040312]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 240/676] [D loss: -0.017453] [G loss: -0.024619] [d1 loss: 0.040211] [d2 loss: 0.047429]  [sq d1 d2: 0.000052]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 260/676] [D loss: -0.014022] [G loss: -0.028822] [d1 loss: 0.037186] [d2 loss: 0.037536]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 280/676] [D loss: 0.007484] [G loss: -0.066001] [d1 loss: 0.080511] [d2 loss: 0.072975]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 322/500] [Batch 300/676] [D loss: -0.001843] [G loss: -0.042102] [d1 loss: 0.032007] [d2 loss: 0.038892]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 322/500] [Batch 320/676] [D loss: 0.013766] [G loss: -0.094635] [d1 loss: 0.053750] [d2 loss: 0.055475]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 340/676] [D loss: 0.000150] [G loss: -0.081589] [d1 loss: 0.126420] [d2 loss: 0.118241]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 360/676] [D loss: -0.026109] [G loss: -0.066187] [d1 loss: 0.120566] [d2 loss: 0.161670]  [sq d1 d2: 0.001690]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 380/676] [D loss: 0.004997] [G loss: -0.088999] [d1 loss: 0.075213] [d2 loss: 0.063913]  [sq d1 d2: 0.000128]  [num0: 12.000000] [num1 52.000000]
[Epoch 322/500] [Batch 400/676] [D loss: -0.007667] [G loss: -0.097013] [d1 loss: 0.137488] [d2 loss: 0.106241]  [sq d1 d2: 0.000976]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 420/676] [D loss: -0.018618] [G loss: -0.089933] [d1 loss: 0.025937] [d2 loss: 0.039633]  [sq d1 d2: 0.000188]  [num0: 14.000000] [num1 50.000000]
[Epoch 322/500] [Batch 440/676] [D loss: -0.029829] [G loss: -0.100917] [d1 loss: 0.047620] [d2 loss: 0.042628]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 322/500] [Batch 460/676] [D loss: -0.017259] [G loss: -0.116078] [d1 loss: 0.066227] [d2 loss: 0.057364]  [sq d1 d2: 0.000079]  [num0: 14.000000] [num1 50.000000]
[Epoch 322/500] [Batch 480/676] [D loss: -0.023834] [G loss: -0.146857] [d1 loss: 0.109811] [d2 loss: 0.133185]  [sq d1 d2: 0.000546]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 500/676] [D loss: -0.021250] [G loss: -0.137445] [d1 loss: 0.157644] [d2 loss: 0.159501]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 520/676] [D loss: -0.024958] [G loss: -0.130814] [d1 loss: 0.068794] [d2 loss: 0.073909]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 322/500] [Batch 540/676] [D loss: -0.022954] [G loss: -0.094338] [d1 loss: 0.147540] [d2 loss: 0.157371]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 560/676] [D loss: -0.002226] [G loss: -0.123209] [d1 loss: 0.038003] [d2 loss: 0.045876]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 322/500] [Batch 580/676] [D loss: -0.007556] [G loss: -0.102507] [d1 loss: 0.095829] [d2 loss: 0.105239]  [sq d1 d2: 0.000089]  [num0: 19.000000] [num1 45.000000]
[Epoch 322/500] [Batch 600/676] [D loss: -0.006946] [G loss: -0.104493] [d1 loss: 0.054891] [d2 loss: 0.051207]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 322/500] [Batch 620/676] [D loss: -0.011011] [G loss: -0.099706] [d1 loss: 0.050101] [d2 loss: 0.065035]  [sq d1 d2: 0.000223]  [num0: 15.000000] [num1 49.000000]
[Epoch 322/500] [Batch 640/676] [D loss: -0.006370] [G loss: -0.077266] [d1 loss: 0.104245] [d2 loss: 0.102998]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 322/500] [Batch 660/676] [D loss: -0.014790] [G loss: -0.021109] [d1 loss: 0.061371] [d2 loss: 0.106049]  [sq d1 d2: 0.001996]  [num0: 20.000000] [num1 44.000000]
[Epoch 323/500] [Batch 0/676] [D loss: -0.002612] [G loss: -0.034313] [d1 loss: 0.024544] [d2 loss: 0.027239]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 20/676] [D loss: -0.025128] [G loss: -0.022497] [d1 loss: 0.097671] [d2 loss: 0.101750]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 40/676] [D loss: -0.003945] [G loss: -0.056056] [d1 loss: 0.077410] [d2 loss: 0.125743]  [sq d1 d2: 0.002336]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 60/676] [D loss: -0.011197] [G loss: -0.073151] [d1 loss: 0.070154] [d2 loss: 0.074047]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 323/500] [Batch 80/676] [D loss: -0.013326] [G loss: -0.088443] [d1 loss: 0.080110] [d2 loss: 0.105963]  [sq d1 d2: 0.000668]  [num0: 19.000000] [num1 45.000000]
[Epoch 323/500] [Batch 100/676] [D loss: -0.008453] [G loss: -0.109038] [d1 loss: 0.031999] [d2 loss: 0.026745]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 120/676] [D loss: 0.005994] [G loss: -0.114325] [d1 loss: 0.053791] [d2 loss: 0.052268]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 323/500] [Batch 140/676] [D loss: -0.003791] [G loss: -0.096265] [d1 loss: 0.022012] [d2 loss: 0.030374]  [sq d1 d2: 0.000070]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 160/676] [D loss: -0.001090] [G loss: -0.087567] [d1 loss: 0.082950] [d2 loss: 0.102342]  [sq d1 d2: 0.000376]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 180/676] [D loss: -0.012329] [G loss: -0.097270] [d1 loss: 0.051286] [d2 loss: 0.045295]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 200/676] [D loss: -0.003302] [G loss: -0.129936] [d1 loss: 0.113964] [d2 loss: 0.117485]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 220/676] [D loss: -0.009582] [G loss: -0.075388] [d1 loss: 0.093677] [d2 loss: 0.090508]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 240/676] [D loss: -0.011166] [G loss: -0.085606] [d1 loss: 0.117459] [d2 loss: 0.172492]  [sq d1 d2: 0.003029]  [num0: 19.000000] [num1 45.000000]
[Epoch 323/500] [Batch 260/676] [D loss: -0.015621] [G loss: -0.095485] [d1 loss: 0.019959] [d2 loss: 0.028093]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 323/500] [Batch 280/676] [D loss: -0.012247] [G loss: -0.090586] [d1 loss: 0.101406] [d2 loss: 0.102395]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 323/500] [Batch 300/676] [D loss: -0.008640] [G loss: -0.134354] [d1 loss: 0.082105] [d2 loss: 0.084607]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 323/500] [Batch 320/676] [D loss: -0.004051] [G loss: -0.126492] [d1 loss: 0.090367] [d2 loss: 0.126517]  [sq d1 d2: 0.001307]  [num0: 18.000000] [num1 46.000000]
[Epoch 323/500] [Batch 340/676] [D loss: -0.023517] [G loss: -0.133551] [d1 loss: 0.113810] [d2 loss: 0.109784]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 323/500] [Batch 360/676] [D loss: 0.007659] [G loss: -0.108543] [d1 loss: 0.080684] [d2 loss: 0.066186]  [sq d1 d2: 0.000210]  [num0: 11.000000] [num1 53.000000]
[Epoch 323/500] [Batch 380/676] [D loss: -0.010462] [G loss: -0.090956] [d1 loss: 0.066574] [d2 loss: 0.054840]  [sq d1 d2: 0.000138]  [num0: 18.000000] [num1 46.000000]
[Epoch 323/500] [Batch 400/676] [D loss: -0.004075] [G loss: -0.086911] [d1 loss: 0.084893] [d2 loss: 0.076585]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 420/676] [D loss: 0.006342] [G loss: -0.057564] [d1 loss: 0.152486] [d2 loss: 0.161185]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 440/676] [D loss: 0.001716] [G loss: -0.060020] [d1 loss: 0.075672] [d2 loss: 0.064977]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 323/500] [Batch 460/676] [D loss: -0.024046] [G loss: -0.084899] [d1 loss: 0.067329] [d2 loss: 0.063261]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 323/500] [Batch 480/676] [D loss: -0.030082] [G loss: -0.075860] [d1 loss: 0.138143] [d2 loss: 0.120580]  [sq d1 d2: 0.000308]  [num0: 19.000000] [num1 45.000000]
[Epoch 323/500] [Batch 500/676] [D loss: 0.001602] [G loss: -0.049189] [d1 loss: 0.071235] [d2 loss: 0.087891]  [sq d1 d2: 0.000277]  [num0: 14.000000] [num1 50.000000]

[Epoch 323/500] [Batch 520/676] [D loss: -0.012395] [G loss: -0.068495] [d1 loss: 0.094050] [d2 loss: 0.101626]  [sq d1 d2: 0.000057]  [num0: 18.000000] [num1 46.000000]
[Epoch 323/500] [Batch 540/676] [D loss: -0.008510] [G loss: -0.092352] [d1 loss: 0.121921] [d2 loss: 0.126980]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 560/676] [D loss: -0.017205] [G loss: -0.138431] [d1 loss: 0.075552] [d2 loss: 0.077639]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 323/500] [Batch 580/676] [D loss: -0.010644] [G loss: -0.164895] [d1 loss: 0.044329] [d2 loss: 0.042679]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 323/500] [Batch 600/676] [D loss: -0.006494] [G loss: -0.204156] [d1 loss: 0.110861] [d2 loss: 0.089057]  [sq d1 d2: 0.000475]  [num0: 16.000000] [num1 48.000000]
[Epoch 323/500] [Batch 620/676] [D loss: -0.025198] [G loss: -0.248279] [d1 loss: 0.112963] [d2 loss: 0.163744]  [sq d1 d2: 0.002579]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 640/676] [D loss: 0.000753] [G loss: -0.254193] [d1 loss: 0.155912] [d2 loss: 0.168379]  [sq d1 d2: 0.000155]  [num0: 17.000000] [num1 47.000000]
[Epoch 323/500] [Batch 660/676] [D loss: -0.017679] [G loss: -0.206001] [d1 loss: 0.063195] [d2 loss: 0.059066]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 324/500] [Batch 0/676] [D loss: -0.012307] [G loss: -0.231911] [d1 loss: 0.068263] [d2 loss: 0.067063]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 324/500] [Batch 20/676] [D loss: -0.005963] [G loss: -0.231831] [d1 loss: 0.071935] [d2 loss: 0.057205]  [sq d1 d2: 0.000217]  [num0: 13.000000] [num1 51.000000]
[Epoch 324/500] [Batch 40/676] [D loss: -0.026214] [G loss: -0.234522] [d1 loss: 0.095840] [d2 loss: 0.099297]  [sq d1 d2: 0.000012]  [num0: 10.000000] [num1 54.000000]
[Epoch 324/500] [Batch 60/676] [D loss: -0.016835] [G loss: -0.237227] [d1 loss: 0.093118] [d2 loss: 0.107238]  [sq d1 d2: 0.000199]  [num0: 17.000000] [num1 47.000000]
[Epoch 324/500] [Batch 80/676] [D loss: -0.013450] [G loss: -0.223289] [d1 loss: 0.096670] [d2 loss: 0.094206]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 324/500] [Batch 100/676] [D loss: -0.011419] [G loss: -0.207652] [d1 loss: 0.074048] [d2 loss: 0.068051]  [sq d1 d2: 0.000036]  [num0: 10.000000] [num1 54.000000]
[Epoch 324/500] [Batch 120/676] [D loss: -0.004377] [G loss: -0.198264] [d1 loss: 0.032091] [d2 loss: 0.048645]  [sq d1 d2: 0.000274]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 140/676] [D loss: -0.013787] [G loss: -0.176956] [d1 loss: 0.129130] [d2 loss: 0.088559]  [sq d1 d2: 0.001646]  [num0: 16.000000] [num1 48.000000]
[Epoch 324/500] [Batch 160/676] [D loss: 0.005760] [G loss: -0.137660] [d1 loss: 0.035628] [d2 loss: 0.013426]  [sq d1 d2: 0.000493]  [num0: 14.000000] [num1 50.000000]
[Epoch 324/500] [Batch 180/676] [D loss: 0.000194] [G loss: -0.108645] [d1 loss: 0.019701] [d2 loss: 0.016982]  [sq d1 d2: 0.000007]  [num0: 20.000000] [num1 44.000000]
[Epoch 324/500] [Batch 200/676] [D loss: -0.006884] [G loss: -0.047376] [d1 loss: 0.093277] [d2 loss: 0.085517]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 220/676] [D loss: -0.005229] [G loss: -0.000205] [d1 loss: 0.027317] [d2 loss: 0.026146]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 324/500] [Batch 240/676] [D loss: -0.002101] [G loss: 0.013824] [d1 loss: 0.041842] [d2 loss: 0.037009]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 260/676] [D loss: 0.008563] [G loss: 0.023672] [d1 loss: 0.412332] [d2 loss: 0.350898]  [sq d1 d2: 0.003774]  [num0: 12.000000] [num1 52.000000]
[Epoch 324/500] [Batch 280/676] [D loss: -0.010868] [G loss: 0.000525] [d1 loss: 0.089277] [d2 loss: 0.075982]  [sq d1 d2: 0.000177]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 300/676] [D loss: -0.027643] [G loss: -0.004923] [d1 loss: 0.035032] [d2 loss: 0.029146]  [sq d1 d2: 0.000035]  [num0: 13.000000] [num1 51.000000]
[Epoch 324/500] [Batch 320/676] [D loss: -0.037464] [G loss: 0.008813] [d1 loss: 0.075205] [d2 loss: 0.097905]  [sq d1 d2: 0.000515]  [num0: 17.000000] [num1 47.000000]
[Epoch 324/500] [Batch 340/676] [D loss: -0.018040] [G loss: -0.025659] [d1 loss: 0.041637] [d2 loss: 0.041838]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 324/500] [Batch 360/676] [D loss: 0.004066] [G loss: -0.078031] [d1 loss: 0.080613] [d2 loss: 0.092641]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 380/676] [D loss: 0.011172] [G loss: -0.107831] [d1 loss: 0.046624] [d2 loss: 0.045492]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 324/500] [Batch 400/676] [D loss: 0.009982] [G loss: -0.171888] [d1 loss: 0.100670] [d2 loss: 0.114893]  [sq d1 d2: 0.000202]  [num0: 18.000000] [num1 46.000000]
[Epoch 324/500] [Batch 420/676] [D loss: 0.004482] [G loss: -0.187943] [d1 loss: 0.027620] [d2 loss: 0.021841]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 324/500] [Batch 440/676] [D loss: -0.013645] [G loss: -0.226304] [d1 loss: 0.034920] [d2 loss: 0.030460]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 324/500] [Batch 460/676] [D loss: -0.007366] [G loss: -0.231579] [d1 loss: 0.056112] [d2 loss: 0.046393]  [sq d1 d2: 0.000094]  [num0: 18.000000] [num1 46.000000]
[Epoch 324/500] [Batch 480/676] [D loss: -0.022198] [G loss: -0.280758] [d1 loss: 0.077910] [d2 loss: 0.083064]  [sq d1 d2: 0.000027]  [num0: 19.000000] [num1 45.000000]
[Epoch 324/500] [Batch 500/676] [D loss: -0.042052] [G loss: -0.280334] [d1 loss: 0.047818] [d2 loss: 0.039366]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 324/500] [Batch 520/676] [D loss: -0.005412] [G loss: -0.291676] [d1 loss: 0.071976] [d2 loss: 0.077056]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 324/500] [Batch 540/676] [D loss: -0.024408] [G loss: -0.303768] [d1 loss: 0.147536] [d2 loss: 0.178050]  [sq d1 d2: 0.000931]  [num0: 9.000000] [num1 55.000000]
[Epoch 324/500] [Batch 560/676] [D loss: -0.010270] [G loss: -0.285948] [d1 loss: 0.077210] [d2 loss: 0.071451]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 324/500] [Batch 580/676] [D loss: 0.004983] [G loss: -0.232686] [d1 loss: 0.093351] [d2 loss: 0.137454]  [sq d1 d2: 0.001945]  [num0: 14.000000] [num1 50.000000]
[Epoch 324/500] [Batch 600/676] [D loss: 0.009172] [G loss: -0.200978] [d1 loss: 0.048708] [d2 loss: 0.058345]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 324/500] [Batch 620/676] [D loss: 0.000487] [G loss: -0.157919] [d1 loss: 0.085465] [d2 loss: 0.085743]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 324/500] [Batch 640/676] [D loss: 0.002716] [G loss: -0.069861] [d1 loss: 0.134371] [d2 loss: 0.158921]  [sq d1 d2: 0.000603]  [num0: 17.000000] [num1 47.000000]
[Epoch 324/500] [Batch 660/676] [D loss: 0.005498] [G loss: -0.013441] [d1 loss: 0.122760] [d2 loss: 0.114863]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 325/500] [Batch 0/676] [D loss: -0.018248] [G loss: 0.010164] [d1 loss: 0.060381] [d2 loss: 0.062719]  [sq d1 d2: 0.000005]  [num0: 11.000000] [num1 53.000000]
[Epoch 325/500] [Batch 20/676] [D loss: -0.012020] [G loss: 0.044665] [d1 loss: 0.070990] [d2 loss: 0.057869]  [sq d1 d2: 0.000172]  [num0: 11.000000] [num1 53.000000]
[Epoch 325/500] [Batch 40/676] [D loss: -0.026976] [G loss: 0.066355] [d1 loss: 0.034492] [d2 loss: 0.038438]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 325/500] [Batch 60/676] [D loss: -0.031904] [G loss: 0.080479] [d1 loss: 0.063976] [d2 loss: 0.062304]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 80/676] [D loss: -0.020264] [G loss: 0.095626] [d1 loss: 0.088795] [d2 loss: 0.105191]  [sq d1 d2: 0.000269]  [num0: 15.000000] [num1 49.000000]
[Epoch 325/500] [Batch 100/676] [D loss: -0.005715] [G loss: 0.106335] [d1 loss: 0.062386] [d2 loss: 0.079372]  [sq d1 d2: 0.000289]  [num0: 14.000000] [num1 50.000000]
[Epoch 325/500] [Batch 120/676] [D loss: -0.024962] [G loss: 0.041411] [d1 loss: 0.077186] [d2 loss: 0.071022]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 325/500] [Batch 140/676] [D loss: 0.021215] [G loss: 0.055248] [d1 loss: 0.091264] [d2 loss: 0.096921]  [sq d1 d2: 0.000032]  [num0: 14.000000] [num1 50.000000]
[Epoch 325/500] [Batch 160/676] [D loss: -0.019634] [G loss: 0.011582] [d1 loss: 0.091107] [d2 loss: 0.081023]  [sq d1 d2: 0.000102]  [num0: 19.000000] [num1 45.000000]
[Epoch 325/500] [Batch 180/676] [D loss: 0.009884] [G loss: -0.045930] [d1 loss: 0.040800] [d2 loss: 0.031885]  [sq d1 d2: 0.000079]  [num0: 17.000000] [num1 47.000000]

[Epoch 325/500] [Batch 200/676] [D loss: 0.012791] [G loss: -0.068821] [d1 loss: 0.100010] [d2 loss: 0.100991]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 220/676] [D loss: -0.000994] [G loss: -0.067893] [d1 loss: 0.072676] [d2 loss: 0.071264]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 325/500] [Batch 240/676] [D loss: 0.001323] [G loss: -0.088578] [d1 loss: 0.024506] [d2 loss: 0.039847]  [sq d1 d2: 0.000235]  [num0: 12.000000] [num1 52.000000]
[Epoch 325/500] [Batch 260/676] [D loss: -0.009436] [G loss: -0.113185] [d1 loss: 0.108389] [d2 loss: 0.065278]  [sq d1 d2: 0.001859]  [num0: 13.000000] [num1 51.000000]
[Epoch 325/500] [Batch 280/676] [D loss: -0.007703] [G loss: -0.160410] [d1 loss: 0.053706] [d2 loss: 0.057707]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 325/500] [Batch 300/676] [D loss: -0.015472] [G loss: -0.201462] [d1 loss: 0.041991] [d2 loss: 0.027001]  [sq d1 d2: 0.000225]  [num0: 12.000000] [num1 52.000000]
[Epoch 325/500] [Batch 320/676] [D loss: -0.021285] [G loss: -0.291625] [d1 loss: 0.086368] [d2 loss: 0.131098]  [sq d1 d2: 0.002001]  [num0: 10.000000] [num1 54.000000]
[Epoch 325/500] [Batch 340/676] [D loss: -0.025732] [G loss: -0.321508] [d1 loss: 0.063832] [d2 loss: 0.062717]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 325/500] [Batch 360/676] [D loss: -0.032801] [G loss: -0.326346] [d1 loss: 0.036256] [d2 loss: 0.095036]  [sq d1 d2: 0.003455]  [num0: 20.000000] [num1 44.000000]
[Epoch 325/500] [Batch 380/676] [D loss: -0.000819] [G loss: -0.304619] [d1 loss: 0.097738] [d2 loss: 0.091372]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 325/500] [Batch 400/676] [D loss: -0.003867] [G loss: -0.310344] [d1 loss: 0.052898] [d2 loss: 0.061582]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 325/500] [Batch 420/676] [D loss: 0.014192] [G loss: -0.232972] [d1 loss: 0.064022] [d2 loss: 0.052302]  [sq d1 d2: 0.000137]  [num0: 18.000000] [num1 46.000000]
[Epoch 325/500] [Batch 440/676] [D loss: 0.006070] [G loss: -0.154047] [d1 loss: 0.028275] [d2 loss: 0.027698]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 325/500] [Batch 460/676] [D loss: 0.009782] [G loss: -0.082586] [d1 loss: 0.111554] [d2 loss: 0.114294]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 480/676] [D loss: -0.000622] [G loss: -0.047064] [d1 loss: 0.165624] [d2 loss: 0.154385]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 500/676] [D loss: -0.011170] [G loss: 0.002783] [d1 loss: 0.057199] [d2 loss: 0.049548]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 325/500] [Batch 520/676] [D loss: -0.023453] [G loss: 0.038256] [d1 loss: 0.041221] [d2 loss: 0.063945]  [sq d1 d2: 0.000516]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 540/676] [D loss: -0.024906] [G loss: 0.059995] [d1 loss: 0.109726] [d2 loss: 0.112142]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 325/500] [Batch 560/676] [D loss: -0.034226] [G loss: 0.086748] [d1 loss: 0.076436] [d2 loss: 0.081963]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 325/500] [Batch 580/676] [D loss: -0.035675] [G loss: 0.098086] [d1 loss: 0.081766] [d2 loss: 0.087846]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 325/500] [Batch 600/676] [D loss: -0.029772] [G loss: 0.123863] [d1 loss: 0.038015] [d2 loss: 0.039287]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 325/500] [Batch 620/676] [D loss: 0.004390] [G loss: 0.112984] [d1 loss: 0.054739] [d2 loss: 0.059830]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 325/500] [Batch 640/676] [D loss: -0.003894] [G loss: 0.103473] [d1 loss: 0.033090] [d2 loss: 0.039559]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 325/500] [Batch 660/676] [D loss: -0.000906] [G loss: 0.084628] [d1 loss: 0.061659] [d2 loss: 0.071231]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 326/500] [Batch 0/676] [D loss: 0.000291] [G loss: 0.071512] [d1 loss: 0.107060] [d2 loss: 0.104762]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 326/500] [Batch 20/676] [D loss: 0.008012] [G loss: 0.034266] [d1 loss: 0.108678] [d2 loss: 0.121312]  [sq d1 d2: 0.000160]  [num0: 18.000000] [num1 46.000000]
[Epoch 326/500] [Batch 40/676] [D loss: 0.007212] [G loss: 0.012428] [d1 loss: 0.059112] [d2 loss: 0.056733]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 326/500] [Batch 60/676] [D loss: -0.003096] [G loss: -0.006607] [d1 loss: 0.060974] [d2 loss: 0.061899]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 80/676] [D loss: -0.015421] [G loss: -0.013651] [d1 loss: 0.030940] [d2 loss: 0.045173]  [sq d1 d2: 0.000203]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 100/676] [D loss: -0.011176] [G loss: -0.055557] [d1 loss: 0.065523] [d2 loss: 0.067954]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 326/500] [Batch 120/676] [D loss: -0.021713] [G loss: -0.065403] [d1 loss: 0.081604] [d2 loss: 0.058936]  [sq d1 d2: 0.000514]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 140/676] [D loss: -0.032714] [G loss: -0.093328] [d1 loss: 0.156537] [d2 loss: 0.100690]  [sq d1 d2: 0.003119]  [num0: 14.000000] [num1 50.000000]
[Epoch 326/500] [Batch 160/676] [D loss: -0.048199] [G loss: -0.108698] [d1 loss: 0.059930] [d2 loss: 0.093557]  [sq d1 d2: 0.001131]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 180/676] [D loss: -0.008974] [G loss: -0.150547] [d1 loss: 0.056985] [d2 loss: 0.075182]  [sq d1 d2: 0.000331]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 200/676] [D loss: 0.024971] [G loss: -0.177716] [d1 loss: 0.101456] [d2 loss: 0.177065]  [sq d1 d2: 0.005717]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 220/676] [D loss: 0.014952] [G loss: -0.156952] [d1 loss: 0.050784] [d2 loss: 0.039298]  [sq d1 d2: 0.000132]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 240/676] [D loss: 0.024686] [G loss: -0.109771] [d1 loss: 0.111537] [d2 loss: 0.100334]  [sq d1 d2: 0.000126]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 260/676] [D loss: 0.008998] [G loss: -0.070828] [d1 loss: 0.060174] [d2 loss: 0.046079]  [sq d1 d2: 0.000199]  [num0: 14.000000] [num1 50.000000]
[Epoch 326/500] [Batch 280/676] [D loss: 0.003601] [G loss: -0.042006] [d1 loss: 0.151574] [d2 loss: 0.112099]  [sq d1 d2: 0.001558]  [num0: 12.000000] [num1 52.000000]
[Epoch 326/500] [Batch 300/676] [D loss: -0.000828] [G loss: -0.017291] [d1 loss: 0.137070] [d2 loss: 0.151722]  [sq d1 d2: 0.000215]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 320/676] [D loss: -0.014451] [G loss: 0.014567] [d1 loss: 0.022516] [d2 loss: 0.023377]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 326/500] [Batch 340/676] [D loss: -0.022278] [G loss: 0.041788] [d1 loss: 0.061941] [d2 loss: 0.025610]  [sq d1 d2: 0.001320]  [num0: 13.000000] [num1 51.000000]
[Epoch 326/500] [Batch 360/676] [D loss: -0.028282] [G loss: 0.056825] [d1 loss: 0.097035] [d2 loss: 0.073563]  [sq d1 d2: 0.000551]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 380/676] [D loss: -0.028119] [G loss: 0.036984] [d1 loss: 0.037076] [d2 loss: 0.045620]  [sq d1 d2: 0.000073]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 400/676] [D loss: -0.019901] [G loss: 0.059398] [d1 loss: 0.079098] [d2 loss: 0.068947]  [sq d1 d2: 0.000103]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 420/676] [D loss: 0.000091] [G loss: 0.095689] [d1 loss: 0.048016] [d2 loss: 0.048966]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 326/500] [Batch 440/676] [D loss: 0.008273] [G loss: 0.076786] [d1 loss: 0.031777] [d2 loss: 0.029108]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 460/676] [D loss: 0.000396] [G loss: 0.015604] [d1 loss: 0.035245] [d2 loss: 0.036713]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 480/676] [D loss: 0.009743] [G loss: -0.029122] [d1 loss: 0.050434] [d2 loss: 0.059103]  [sq d1 d2: 0.000075]  [num0: 19.000000] [num1 45.000000]
[Epoch 326/500] [Batch 500/676] [D loss: 0.010556] [G loss: -0.059580] [d1 loss: 0.089123] [d2 loss: 0.109972]  [sq d1 d2: 0.000435]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 520/676] [D loss: -0.000834] [G loss: -0.051075] [d1 loss: 0.127779] [d2 loss: 0.136506]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 326/500] [Batch 540/676] [D loss: -0.002939] [G loss: -0.049100] [d1 loss: 0.083876] [d2 loss: 0.114411]  [sq d1 d2: 0.000932]  [num0: 13.000000] [num1 51.000000]

[Epoch 326/500] [Batch 560/676] [D loss: -0.007081] [G loss: -0.034355] [d1 loss: 0.025638] [d2 loss: 0.027168]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 326/500] [Batch 580/676] [D loss: -0.011408] [G loss: -0.029397] [d1 loss: 0.064822] [d2 loss: 0.060782]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 326/500] [Batch 600/676] [D loss: -0.013575] [G loss: -0.020057] [d1 loss: 0.055563] [d2 loss: 0.059568]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 620/676] [D loss: -0.016677] [G loss: -0.031921] [d1 loss: 0.095733] [d2 loss: 0.072074]  [sq d1 d2: 0.000560]  [num0: 16.000000] [num1 48.000000]
[Epoch 326/500] [Batch 640/676] [D loss: -0.030728] [G loss: -0.059262] [d1 loss: 0.183199] [d2 loss: 0.142073]  [sq d1 d2: 0.001691]  [num0: 15.000000] [num1 49.000000]
[Epoch 326/500] [Batch 660/676] [D loss: -0.034837] [G loss: -0.066481] [d1 loss: 0.039195] [d2 loss: 0.048870]  [sq d1 d2: 0.000094]  [num0: 18.000000] [num1 46.000000]
[Epoch 327/500] [Batch 0/676] [D loss: -0.040655] [G loss: -0.097272] [d1 loss: 0.038989] [d2 loss: 0.046654]  [sq d1 d2: 0.000059]  [num0: 19.000000] [num1 45.000000]
[Epoch 327/500] [Batch 20/676] [D loss: -0.001459] [G loss: -0.102751] [d1 loss: 0.045397] [d2 loss: 0.038093]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 40/676] [D loss: 0.012579] [G loss: -0.098799] [d1 loss: 0.045919] [d2 loss: 0.053230]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 60/676] [D loss: 0.016190] [G loss: -0.072059] [d1 loss: 0.096775] [d2 loss: 0.125043]  [sq d1 d2: 0.000799]  [num0: 18.000000] [num1 46.000000]
[Epoch 327/500] [Batch 80/676] [D loss: 0.023274] [G loss: -0.036453] [d1 loss: 0.020155] [d2 loss: 0.023327]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 100/676] [D loss: -0.002062] [G loss: -0.043280] [d1 loss: 0.066390] [d2 loss: 0.052572]  [sq d1 d2: 0.000191]  [num0: 16.000000] [num1 48.000000]
[Epoch 327/500] [Batch 120/676] [D loss: 0.000368] [G loss: -0.037717] [d1 loss: 0.093435] [d2 loss: 0.094665]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 140/676] [D loss: -0.010930] [G loss: -0.006282] [d1 loss: 0.087654] [d2 loss: 0.088898]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 327/500] [Batch 160/676] [D loss: -0.032368] [G loss: -0.000848] [d1 loss: 0.033363] [d2 loss: 0.031441]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 180/676] [D loss: -0.028707] [G loss: 0.032239] [d1 loss: 0.020704] [d2 loss: 0.024033]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 327/500] [Batch 200/676] [D loss: -0.043635] [G loss: 0.040402] [d1 loss: 0.049875] [d2 loss: 0.031016]  [sq d1 d2: 0.000356]  [num0: 18.000000] [num1 46.000000]
[Epoch 327/500] [Batch 220/676] [D loss: -0.019712] [G loss: 0.052005] [d1 loss: 0.087045] [d2 loss: 0.123209]  [sq d1 d2: 0.001308]  [num0: 12.000000] [num1 52.000000]
[Epoch 327/500] [Batch 240/676] [D loss: -0.002146] [G loss: 0.025615] [d1 loss: 0.052091] [d2 loss: 0.054874]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 260/676] [D loss: -0.009647] [G loss: 0.008833] [d1 loss: 0.082889] [d2 loss: 0.091719]  [sq d1 d2: 0.000078]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 280/676] [D loss: 0.023178] [G loss: -0.030109] [d1 loss: 0.063112] [d2 loss: 0.068219]  [sq d1 d2: 0.000026]  [num0: 21.000000] [num1 43.000000]
[Epoch 327/500] [Batch 300/676] [D loss: 0.009252] [G loss: -0.049990] [d1 loss: 0.066223] [d2 loss: 0.070770]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 327/500] [Batch 320/676] [D loss: 0.015309] [G loss: -0.043237] [d1 loss: 0.027088] [d2 loss: 0.027908]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 327/500] [Batch 340/676] [D loss: 0.000935] [G loss: -0.064765] [d1 loss: 0.037980] [d2 loss: 0.038439]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 360/676] [D loss: -0.002422] [G loss: -0.067708] [d1 loss: 0.049336] [d2 loss: 0.038266]  [sq d1 d2: 0.000123]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 380/676] [D loss: -0.013243] [G loss: -0.075493] [d1 loss: 0.031816] [d2 loss: 0.034973]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 327/500] [Batch 400/676] [D loss: -0.032606] [G loss: -0.090366] [d1 loss: 0.058107] [d2 loss: 0.047728]  [sq d1 d2: 0.000108]  [num0: 19.000000] [num1 45.000000]
[Epoch 327/500] [Batch 420/676] [D loss: -0.029539] [G loss: -0.103530] [d1 loss: 0.019071] [d2 loss: 0.022634]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 327/500] [Batch 440/676] [D loss: -0.044719] [G loss: -0.100689] [d1 loss: 0.039866] [d2 loss: 0.041595]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 460/676] [D loss: -0.015093] [G loss: -0.135024] [d1 loss: 0.057885] [d2 loss: 0.061714]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 327/500] [Batch 480/676] [D loss: -0.030554] [G loss: -0.173021] [d1 loss: 0.027989] [d2 loss: 0.027728]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 500/676] [D loss: -0.003690] [G loss: -0.199629] [d1 loss: 0.013977] [d2 loss: 0.012181]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 520/676] [D loss: 0.018337] [G loss: -0.202713] [d1 loss: 0.123811] [d2 loss: 0.107589]  [sq d1 d2: 0.000263]  [num0: 15.000000] [num1 49.000000]
[Epoch 327/500] [Batch 540/676] [D loss: 0.008444] [G loss: -0.173241] [d1 loss: 0.072068] [d2 loss: 0.068861]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 327/500] [Batch 560/676] [D loss: 0.008714] [G loss: -0.134573] [d1 loss: 0.055348] [d2 loss: 0.059368]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 327/500] [Batch 580/676] [D loss: -0.000583] [G loss: -0.100981] [d1 loss: 0.085615] [d2 loss: 0.101406]  [sq d1 d2: 0.000249]  [num0: 12.000000] [num1 52.000000]
[Epoch 327/500] [Batch 600/676] [D loss: -0.007563] [G loss: -0.107602] [d1 loss: 0.081710] [d2 loss: 0.085728]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 327/500] [Batch 620/676] [D loss: -0.007400] [G loss: -0.079492] [d1 loss: 0.031840] [d2 loss: 0.030883]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 327/500] [Batch 640/676] [D loss: -0.022936] [G loss: -0.097933] [d1 loss: 0.095768] [d2 loss: 0.125698]  [sq d1 d2: 0.000896]  [num0: 14.000000] [num1 50.000000]
[Epoch 327/500] [Batch 660/676] [D loss: -0.049506] [G loss: -0.082271] [d1 loss: 0.066409] [d2 loss: 0.071202]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 328/500] [Batch 0/676] [D loss: -0.033807] [G loss: -0.091655] [d1 loss: 0.092376] [d2 loss: 0.031838]  [sq d1 d2: 0.003665]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 20/676] [D loss: -0.006288] [G loss: -0.092378] [d1 loss: 0.073100] [d2 loss: 0.070445]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 328/500] [Batch 40/676] [D loss: -0.004271] [G loss: -0.035365] [d1 loss: 0.060310] [d2 loss: 0.052237]  [sq d1 d2: 0.000065]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 60/676] [D loss: -0.009375] [G loss: -0.075311] [d1 loss: 0.105209] [d2 loss: 0.104050]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 328/500] [Batch 80/676] [D loss: -0.001520] [G loss: -0.099680] [d1 loss: 0.089900] [d2 loss: 0.095425]  [sq d1 d2: 0.000031]  [num0: 9.000000] [num1 55.000000]
[Epoch 328/500] [Batch 100/676] [D loss: 0.021904] [G loss: -0.123618] [d1 loss: 0.062017] [d2 loss: 0.066156]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 328/500] [Batch 120/676] [D loss: 0.014211] [G loss: -0.117483] [d1 loss: 0.028444] [d2 loss: 0.026711]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 328/500] [Batch 140/676] [D loss: 0.022643] [G loss: -0.095389] [d1 loss: 0.124612] [d2 loss: 0.170629]  [sq d1 d2: 0.002118]  [num0: 11.000000] [num1 53.000000]
[Epoch 328/500] [Batch 160/676] [D loss: -0.000118] [G loss: -0.077411] [d1 loss: 0.173085] [d2 loss: 0.149768]  [sq d1 d2: 0.000544]  [num0: 15.000000] [num1 49.000000]
[Epoch 328/500] [Batch 180/676] [D loss: -0.009026] [G loss: -0.095805] [d1 loss: 0.036981] [d2 loss: 0.038929]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 200/676] [D loss: -0.020048] [G loss: -0.115699] [d1 loss: 0.031720] [d2 loss: 0.035643]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 220/676] [D loss: -0.029521] [G loss: -0.135779] [d1 loss: 0.060157] [d2 loss: 0.046309]  [sq d1 d2: 0.000192]  [num0: 15.000000] [num1 49.000000]

[Epoch 328/500] [Batch 240/676] [D loss: -0.045124] [G loss: -0.169763] [d1 loss: 0.083746] [d2 loss: 0.073591]  [sq d1 d2: 0.000103]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 260/676] [D loss: -0.001332] [G loss: -0.192416] [d1 loss: 0.076083] [d2 loss: 0.104288]  [sq d1 d2: 0.000795]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 280/676] [D loss: -0.024641] [G loss: -0.166556] [d1 loss: 0.134341] [d2 loss: 0.084865]  [sq d1 d2: 0.002448]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 300/676] [D loss: -0.011312] [G loss: -0.132525] [d1 loss: 0.065125] [d2 loss: 0.053715]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 328/500] [Batch 320/676] [D loss: 0.027450] [G loss: -0.157714] [d1 loss: 0.087379] [d2 loss: 0.077163]  [sq d1 d2: 0.000104]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 340/676] [D loss: 0.004761] [G loss: -0.116426] [d1 loss: 0.060133] [d2 loss: 0.074153]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 328/500] [Batch 360/676] [D loss: 0.016055] [G loss: -0.067618] [d1 loss: 0.076306] [d2 loss: 0.045466]  [sq d1 d2: 0.000951]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 380/676] [D loss: 0.006846] [G loss: -0.008871] [d1 loss: 0.040131] [d2 loss: 0.055611]  [sq d1 d2: 0.000240]  [num0: 15.000000] [num1 49.000000]
[Epoch 328/500] [Batch 400/676] [D loss: 0.002611] [G loss: 0.017822] [d1 loss: 0.089171] [d2 loss: 0.074589]  [sq d1 d2: 0.000213]  [num0: 15.000000] [num1 49.000000]
[Epoch 328/500] [Batch 420/676] [D loss: -0.005757] [G loss: 0.048467] [d1 loss: 0.046519] [d2 loss: 0.089780]  [sq d1 d2: 0.001872]  [num0: 13.000000] [num1 51.000000]
[Epoch 328/500] [Batch 440/676] [D loss: -0.013613] [G loss: 0.062699] [d1 loss: 0.042327] [d2 loss: 0.046767]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 328/500] [Batch 460/676] [D loss: -0.019928] [G loss: 0.103759] [d1 loss: 0.065713] [d2 loss: 0.068740]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 328/500] [Batch 480/676] [D loss: -0.039245] [G loss: 0.152039] [d1 loss: 0.068977] [d2 loss: 0.084092]  [sq d1 d2: 0.000228]  [num0: 17.000000] [num1 47.000000]
[Epoch 328/500] [Batch 500/676] [D loss: -0.062336] [G loss: 0.164362] [d1 loss: 0.112118] [d2 loss: 0.120217]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 328/500] [Batch 520/676] [D loss: -0.063601] [G loss: 0.204909] [d1 loss: 0.123292] [d2 loss: 0.101645]  [sq d1 d2: 0.000469]  [num0: 19.000000] [num1 45.000000]
[Epoch 328/500] [Batch 540/676] [D loss: -0.036828] [G loss: 0.214532] [d1 loss: 0.056362] [d2 loss: 0.072686]  [sq d1 d2: 0.000267]  [num0: 12.000000] [num1 52.000000]
[Epoch 328/500] [Batch 560/676] [D loss: -0.013430] [G loss: 0.205882] [d1 loss: 0.050918] [d2 loss: 0.068956]  [sq d1 d2: 0.000325]  [num0: 17.000000] [num1 47.000000]
[Epoch 328/500] [Batch 580/676] [D loss: -0.003449] [G loss: 0.156969] [d1 loss: 0.036990] [d2 loss: 0.030954]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 328/500] [Batch 600/676] [D loss: 0.031899] [G loss: 0.091679] [d1 loss: 0.096778] [d2 loss: 0.088023]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 328/500] [Batch 620/676] [D loss: 0.023291] [G loss: 0.036447] [d1 loss: 0.136848] [d2 loss: 0.122681]  [sq d1 d2: 0.000201]  [num0: 18.000000] [num1 46.000000]
[Epoch 328/500] [Batch 640/676] [D loss: 0.004076] [G loss: 0.018912] [d1 loss: 0.096148] [d2 loss: 0.075978]  [sq d1 d2: 0.000407]  [num0: 12.000000] [num1 52.000000]
[Epoch 328/500] [Batch 660/676] [D loss: -0.007174] [G loss: 0.019774] [d1 loss: 0.121951] [d2 loss: 0.116068]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 0/676] [D loss: -0.009960] [G loss: 0.026545] [d1 loss: 0.053583] [d2 loss: 0.046427]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 20/676] [D loss: -0.014501] [G loss: 0.012023] [d1 loss: 0.061884] [d2 loss: 0.064733]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 329/500] [Batch 40/676] [D loss: -0.024668] [G loss: 0.011524] [d1 loss: 0.152954] [d2 loss: 0.146604]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 329/500] [Batch 60/676] [D loss: -0.033469] [G loss: 0.007320] [d1 loss: 0.045237] [d2 loss: 0.050806]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 80/676] [D loss: -0.060352] [G loss: -0.008384] [d1 loss: 0.057407] [d2 loss: 0.063406]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 329/500] [Batch 100/676] [D loss: -0.020866] [G loss: 0.025924] [d1 loss: 0.133411] [d2 loss: 0.144271]  [sq d1 d2: 0.000118]  [num0: 19.000000] [num1 45.000000]
[Epoch 329/500] [Batch 120/676] [D loss: 0.003799] [G loss: -0.028355] [d1 loss: 0.085827] [d2 loss: 0.086381]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 329/500] [Batch 140/676] [D loss: -0.002487] [G loss: -0.054747] [d1 loss: 0.045211] [d2 loss: 0.042487]  [sq d1 d2: 0.000007]  [num0: 20.000000] [num1 44.000000]
[Epoch 329/500] [Batch 160/676] [D loss: 0.020937] [G loss: -0.076916] [d1 loss: 0.031737] [d2 loss: 0.033083]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 180/676] [D loss: 0.005486] [G loss: -0.081193] [d1 loss: 0.029886] [d2 loss: 0.029127]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 200/676] [D loss: 0.012962] [G loss: -0.071107] [d1 loss: 0.073085] [d2 loss: 0.067703]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 220/676] [D loss: 0.009854] [G loss: -0.045208] [d1 loss: 0.117030] [d2 loss: 0.107371]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 240/676] [D loss: -0.001225] [G loss: -0.066808] [d1 loss: 0.113162] [d2 loss: 0.133940]  [sq d1 d2: 0.000432]  [num0: 14.000000] [num1 50.000000]
[Epoch 329/500] [Batch 260/676] [D loss: -0.004099] [G loss: -0.073171] [d1 loss: 0.057850] [d2 loss: 0.040530]  [sq d1 d2: 0.000300]  [num0: 14.000000] [num1 50.000000]
[Epoch 329/500] [Batch 280/676] [D loss: -0.005071] [G loss: -0.066362] [d1 loss: 0.088683] [d2 loss: 0.111153]  [sq d1 d2: 0.000505]  [num0: 15.000000] [num1 49.000000]
[Epoch 329/500] [Batch 300/676] [D loss: -0.028636] [G loss: -0.061743] [d1 loss: 0.110050] [d2 loss: 0.118191]  [sq d1 d2: 0.000066]  [num0: 20.000000] [num1 44.000000]
[Epoch 329/500] [Batch 320/676] [D loss: -0.015541] [G loss: -0.025822] [d1 loss: 0.076790] [d2 loss: 0.076479]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 340/676] [D loss: -0.013913] [G loss: 0.007676] [d1 loss: 0.128727] [d2 loss: 0.117475]  [sq d1 d2: 0.000127]  [num0: 14.000000] [num1 50.000000]
[Epoch 329/500] [Batch 360/676] [D loss: -0.015872] [G loss: 0.012918] [d1 loss: 0.087898] [d2 loss: 0.058032]  [sq d1 d2: 0.000892]  [num0: 14.000000] [num1 50.000000]
[Epoch 329/500] [Batch 380/676] [D loss: 0.013747] [G loss: 0.016623] [d1 loss: 0.072600] [d2 loss: 0.092025]  [sq d1 d2: 0.000377]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 400/676] [D loss: -0.011225] [G loss: 0.003249] [d1 loss: 0.075795] [d2 loss: 0.091861]  [sq d1 d2: 0.000258]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 420/676] [D loss: 0.028624] [G loss: -0.005311] [d1 loss: 0.090343] [d2 loss: 0.088681]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 440/676] [D loss: 0.003812] [G loss: -0.043667] [d1 loss: 0.040443] [d2 loss: 0.035992]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 460/676] [D loss: 0.009121] [G loss: -0.056624] [d1 loss: 0.102679] [d2 loss: 0.080133]  [sq d1 d2: 0.000508]  [num0: 15.000000] [num1 49.000000]
[Epoch 329/500] [Batch 480/676] [D loss: 0.002740] [G loss: -0.043455] [d1 loss: 0.068757] [d2 loss: 0.061006]  [sq d1 d2: 0.000060]  [num0: 11.000000] [num1 53.000000]
[Epoch 329/500] [Batch 500/676] [D loss: -0.003100] [G loss: -0.038301] [d1 loss: 0.069613] [d2 loss: 0.069198]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 329/500] [Batch 520/676] [D loss: -0.018933] [G loss: -0.008550] [d1 loss: 0.071853] [d2 loss: 0.074692]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 540/676] [D loss: -0.022468] [G loss: -0.015817] [d1 loss: 0.056032] [d2 loss: 0.061533]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 560/676] [D loss: -0.036870] [G loss: -0.043407] [d1 loss: 0.124452] [d2 loss: 0.122024]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 329/500] [Batch 580/676] [D loss: -0.040223] [G loss: -0.049933] [d1 loss: 0.065723] [d2 loss: 0.076022]  [sq d1 d2: 0.000106]  [num0: 16.000000] [num1 48.000000]

[Epoch 329/500] [Batch 600/676] [D loss: -0.026655] [G loss: -0.069677] [d1 loss: 0.058795] [d2 loss: 0.047490]  [sq d1 d2: 0.000128]  [num0: 16.000000] [num1 48.000000]
[Epoch 329/500] [Batch 620/676] [D loss: -0.030660] [G loss: -0.097051] [d1 loss: 0.062132] [d2 loss: 0.078868]  [sq d1 d2: 0.000280]  [num0: 15.000000] [num1 49.000000]
[Epoch 329/500] [Batch 640/676] [D loss: -0.009697] [G loss: -0.121943] [d1 loss: 0.086083] [d2 loss: 0.086358]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 329/500] [Batch 660/676] [D loss: 0.012018] [G loss: -0.080592] [d1 loss: 0.073892] [d2 loss: 0.063267]  [sq d1 d2: 0.000113]  [num0: 11.000000] [num1 53.000000]
[Epoch 330/500] [Batch 0/676] [D loss: 0.020526] [G loss: -0.063097] [d1 loss: 0.212815] [d2 loss: 0.247383]  [sq d1 d2: 0.001195]  [num0: 22.000000] [num1 42.000000]
[Epoch 330/500] [Batch 20/676] [D loss: 0.004860] [G loss: -0.040857] [d1 loss: 0.040908] [d2 loss: 0.038425]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 330/500] [Batch 40/676] [D loss: 0.005762] [G loss: -0.018250] [d1 loss: 0.092270] [d2 loss: 0.112981]  [sq d1 d2: 0.000429]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 60/676] [D loss: -0.008922] [G loss: -0.002848] [d1 loss: 0.086806] [d2 loss: 0.074783]  [sq d1 d2: 0.000145]  [num0: 18.000000] [num1 46.000000]
[Epoch 330/500] [Batch 80/676] [D loss: -0.024493] [G loss: 0.025074] [d1 loss: 0.058883] [d2 loss: 0.063745]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 330/500] [Batch 100/676] [D loss: -0.047864] [G loss: 0.063816] [d1 loss: 0.036753] [d2 loss: 0.051240]  [sq d1 d2: 0.000210]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 120/676] [D loss: -0.064568] [G loss: 0.132939] [d1 loss: 0.055118] [d2 loss: 0.052746]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 330/500] [Batch 140/676] [D loss: -0.043214] [G loss: 0.149464] [d1 loss: 0.065481] [d2 loss: 0.068864]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 160/676] [D loss: -0.042505] [G loss: 0.170052] [d1 loss: 0.027645] [d2 loss: 0.030328]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 330/500] [Batch 180/676] [D loss: -0.001158] [G loss: 0.148776] [d1 loss: 0.058559] [d2 loss: 0.055978]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 200/676] [D loss: 0.026784] [G loss: 0.126582] [d1 loss: 0.182149] [d2 loss: 0.188519]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 330/500] [Batch 220/676] [D loss: 0.036786] [G loss: 0.049247] [d1 loss: 0.061053] [d2 loss: 0.065412]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 240/676] [D loss: 0.010639] [G loss: 0.001869] [d1 loss: 0.141809] [d2 loss: 0.114205]  [sq d1 d2: 0.000762]  [num0: 16.000000] [num1 48.000000]
[Epoch 330/500] [Batch 260/676] [D loss: 0.009777] [G loss: -0.021971] [d1 loss: 0.078591] [d2 loss: 0.065088]  [sq d1 d2: 0.000182]  [num0: 15.000000] [num1 49.000000]
[Epoch 330/500] [Batch 280/676] [D loss: -0.001715] [G loss: -0.047202] [d1 loss: 0.055449] [d2 loss: 0.058315]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 330/500] [Batch 300/676] [D loss: -0.010069] [G loss: -0.065660] [d1 loss: 0.110548] [d2 loss: 0.076815]  [sq d1 d2: 0.001138]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 320/676] [D loss: -0.048595] [G loss: -0.066909] [d1 loss: 0.046259] [d2 loss: 0.053941]  [sq d1 d2: 0.000059]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 340/676] [D loss: -0.067682] [G loss: -0.081250] [d1 loss: 0.051072] [d2 loss: 0.057419]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 360/676] [D loss: -0.069574] [G loss: -0.110931] [d1 loss: 0.067986] [d2 loss: 0.103056]  [sq d1 d2: 0.001230]  [num0: 16.000000] [num1 48.000000]
[Epoch 330/500] [Batch 380/676] [D loss: -0.041838] [G loss: -0.099613] [d1 loss: 0.066497] [d2 loss: 0.069314]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 330/500] [Batch 400/676] [D loss: -0.073473] [G loss: -0.179097] [d1 loss: 0.089096] [d2 loss: 0.094914]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 420/676] [D loss: 0.043585] [G loss: -0.157231] [d1 loss: 0.035473] [d2 loss: 0.053209]  [sq d1 d2: 0.000315]  [num0: 15.000000] [num1 49.000000]
[Epoch 330/500] [Batch 440/676] [D loss: 0.006515] [G loss: -0.112492] [d1 loss: 0.088004] [d2 loss: 0.059280]  [sq d1 d2: 0.000825]  [num0: 18.000000] [num1 46.000000]
[Epoch 330/500] [Batch 460/676] [D loss: 0.010608] [G loss: -0.048606] [d1 loss: 0.068738] [d2 loss: 0.067548]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 480/676] [D loss: 0.004492] [G loss: 0.010763] [d1 loss: 0.089535] [d2 loss: 0.091376]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 500/676] [D loss: 0.004817] [G loss: 0.031700] [d1 loss: 0.090209] [d2 loss: 0.111307]  [sq d1 d2: 0.000445]  [num0: 16.000000] [num1 48.000000]
[Epoch 330/500] [Batch 520/676] [D loss: -0.009410] [G loss: 0.035259] [d1 loss: 0.081505] [d2 loss: 0.083317]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 330/500] [Batch 540/676] [D loss: -0.032074] [G loss: 0.034444] [d1 loss: 0.031796] [d2 loss: 0.035651]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 330/500] [Batch 560/676] [D loss: -0.053285] [G loss: 0.069176] [d1 loss: 0.107792] [d2 loss: 0.084378]  [sq d1 d2: 0.000548]  [num0: 11.000000] [num1 53.000000]
[Epoch 330/500] [Batch 580/676] [D loss: -0.044091] [G loss: 0.092749] [d1 loss: 0.071862] [d2 loss: 0.078367]  [sq d1 d2: 0.000042]  [num0: 20.000000] [num1 44.000000]
[Epoch 330/500] [Batch 600/676] [D loss: -0.099614] [G loss: 0.121815] [d1 loss: 0.153592] [d2 loss: 0.160480]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 330/500] [Batch 620/676] [D loss: -0.050321] [G loss: 0.096761] [d1 loss: 0.129539] [d2 loss: 0.092198]  [sq d1 d2: 0.001394]  [num0: 18.000000] [num1 46.000000]
[Epoch 330/500] [Batch 640/676] [D loss: 0.015327] [G loss: 0.070102] [d1 loss: 0.027041] [d2 loss: 0.041395]  [sq d1 d2: 0.000206]  [num0: 15.000000] [num1 49.000000]
[Epoch 330/500] [Batch 660/676] [D loss: -0.040506] [G loss: -0.045175] [d1 loss: 0.108366] [d2 loss: 0.117348]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 331/500] [Batch 0/676] [D loss: 0.042830] [G loss: -0.119031] [d1 loss: 0.160029] [d2 loss: 0.175626]  [sq d1 d2: 0.000243]  [num0: 18.000000] [num1 46.000000]
[Epoch 331/500] [Batch 20/676] [D loss: 0.016522] [G loss: -0.168324] [d1 loss: 0.071567] [d2 loss: 0.063688]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 331/500] [Batch 40/676] [D loss: 0.015732] [G loss: -0.149178] [d1 loss: 0.095414] [d2 loss: 0.088233]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 60/676] [D loss: 0.007156] [G loss: -0.120540] [d1 loss: 0.103299] [d2 loss: 0.087912]  [sq d1 d2: 0.000237]  [num0: 16.000000] [num1 48.000000]
[Epoch 331/500] [Batch 80/676] [D loss: -0.000803] [G loss: -0.082346] [d1 loss: 0.031496] [d2 loss: 0.032013]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 331/500] [Batch 100/676] [D loss: -0.009511] [G loss: -0.043241] [d1 loss: 0.121193] [d2 loss: 0.109253]  [sq d1 d2: 0.000143]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 120/676] [D loss: -0.033864] [G loss: 0.013603] [d1 loss: 0.189180] [d2 loss: 0.210380]  [sq d1 d2: 0.000449]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 140/676] [D loss: -0.049593] [G loss: 0.047433] [d1 loss: 0.066559] [d2 loss: 0.053209]  [sq d1 d2: 0.000178]  [num0: 16.000000] [num1 48.000000]
[Epoch 331/500] [Batch 160/676] [D loss: -0.019352] [G loss: 0.052838] [d1 loss: 0.148458] [d2 loss: 0.136589]  [sq d1 d2: 0.000141]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 180/676] [D loss: -0.052096] [G loss: 0.051356] [d1 loss: 0.141102] [d2 loss: 0.156343]  [sq d1 d2: 0.000232]  [num0: 14.000000] [num1 50.000000]
[Epoch 331/500] [Batch 200/676] [D loss: -0.007007] [G loss: 0.052858] [d1 loss: 0.081642] [d2 loss: 0.103692]  [sq d1 d2: 0.000486]  [num0: 13.000000] [num1 51.000000]
[Epoch 331/500] [Batch 220/676] [D loss: -0.032712] [G loss: 0.043648] [d1 loss: 0.061108] [d2 loss: 0.065750]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 331/500] [Batch 240/676] [D loss: -0.023509] [G loss: -0.000790] [d1 loss: 0.034714] [d2 loss: 0.029882]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]

[Epoch 331/500] [Batch 260/676] [D loss: 0.000672] [G loss: 0.014117] [d1 loss: 0.067119] [d2 loss: 0.056923]  [sq d1 d2: 0.000104]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 280/676] [D loss: 0.008372] [G loss: 0.019559] [d1 loss: 0.211448] [d2 loss: 0.155302]  [sq d1 d2: 0.003152]  [num0: 13.000000] [num1 51.000000]
[Epoch 331/500] [Batch 300/676] [D loss: 0.015604] [G loss: 0.029992] [d1 loss: 0.064524] [d2 loss: 0.068598]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 331/500] [Batch 320/676] [D loss: 0.008815] [G loss: 0.034766] [d1 loss: 0.105984] [d2 loss: 0.144030]  [sq d1 d2: 0.001447]  [num0: 13.000000] [num1 51.000000]
[Epoch 331/500] [Batch 340/676] [D loss: 0.008027] [G loss: 0.035003] [d1 loss: 0.128289] [d2 loss: 0.139584]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 331/500] [Batch 360/676] [D loss: -0.002373] [G loss: 0.023913] [d1 loss: 0.050991] [d2 loss: 0.037672]  [sq d1 d2: 0.000177]  [num0: 16.000000] [num1 48.000000]
[Epoch 331/500] [Batch 380/676] [D loss: -0.003782] [G loss: -0.006577] [d1 loss: 0.116976] [d2 loss: 0.106893]  [sq d1 d2: 0.000102]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 400/676] [D loss: -0.010128] [G loss: -0.038703] [d1 loss: 0.199850] [d2 loss: 0.157752]  [sq d1 d2: 0.001772]  [num0: 18.000000] [num1 46.000000]
[Epoch 331/500] [Batch 420/676] [D loss: -0.040431] [G loss: -0.055012] [d1 loss: 0.069670] [d2 loss: 0.084201]  [sq d1 d2: 0.000211]  [num0: 19.000000] [num1 45.000000]
[Epoch 331/500] [Batch 440/676] [D loss: -0.020653] [G loss: -0.061240] [d1 loss: 0.058563] [d2 loss: 0.049771]  [sq d1 d2: 0.000077]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 460/676] [D loss: -0.033991] [G loss: -0.049501] [d1 loss: 0.119142] [d2 loss: 0.103330]  [sq d1 d2: 0.000250]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 480/676] [D loss: -0.000144] [G loss: -0.055935] [d1 loss: 0.059457] [d2 loss: 0.050563]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 331/500] [Batch 500/676] [D loss: -0.014112] [G loss: -0.027018] [d1 loss: 0.082815] [d2 loss: 0.084181]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 520/676] [D loss: -0.004938] [G loss: -0.033573] [d1 loss: 0.076910] [d2 loss: 0.060779]  [sq d1 d2: 0.000260]  [num0: 16.000000] [num1 48.000000]
[Epoch 331/500] [Batch 540/676] [D loss: -0.016880] [G loss: -0.089369] [d1 loss: 0.087917] [d2 loss: 0.070287]  [sq d1 d2: 0.000311]  [num0: 20.000000] [num1 44.000000]
[Epoch 331/500] [Batch 560/676] [D loss: 0.001116] [G loss: -0.134292] [d1 loss: 0.087337] [d2 loss: 0.086168]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 331/500] [Batch 580/676] [D loss: 0.036749] [G loss: -0.087495] [d1 loss: 0.076075] [d2 loss: 0.070824]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 331/500] [Batch 600/676] [D loss: 0.015524] [G loss: -0.082140] [d1 loss: 0.117171] [d2 loss: 0.106295]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 620/676] [D loss: 0.008113] [G loss: -0.059434] [d1 loss: 0.139260] [d2 loss: 0.081209]  [sq d1 d2: 0.003370]  [num0: 15.000000] [num1 49.000000]
[Epoch 331/500] [Batch 640/676] [D loss: -0.003321] [G loss: -0.070936] [d1 loss: 0.094880] [d2 loss: 0.125035]  [sq d1 d2: 0.000909]  [num0: 17.000000] [num1 47.000000]
[Epoch 331/500] [Batch 660/676] [D loss: -0.009036] [G loss: -0.068110] [d1 loss: 0.027607] [d2 loss: 0.031906]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 332/500] [Batch 0/676] [D loss: -0.016640] [G loss: -0.052974] [d1 loss: 0.204230] [d2 loss: 0.190766]  [sq d1 d2: 0.000181]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 20/676] [D loss: -0.022859] [G loss: -0.055944] [d1 loss: 0.111150] [d2 loss: 0.123780]  [sq d1 d2: 0.000159]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 40/676] [D loss: -0.021249] [G loss: -0.066897] [d1 loss: 0.048595] [d2 loss: 0.050899]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 332/500] [Batch 60/676] [D loss: -0.045458] [G loss: -0.040751] [d1 loss: 0.048992] [d2 loss: 0.039196]  [sq d1 d2: 0.000096]  [num0: 9.000000] [num1 55.000000]
[Epoch 332/500] [Batch 80/676] [D loss: -0.024496] [G loss: -0.041134] [d1 loss: 0.079758] [d2 loss: 0.071901]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 100/676] [D loss: -0.009946] [G loss: -0.042431] [d1 loss: 0.074711] [d2 loss: 0.084917]  [sq d1 d2: 0.000104]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 120/676] [D loss: -0.019782] [G loss: -0.069659] [d1 loss: 0.042860] [d2 loss: 0.041853]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 140/676] [D loss: 0.004464] [G loss: -0.045944] [d1 loss: 0.038661] [d2 loss: 0.035959]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 160/676] [D loss: 0.002754] [G loss: -0.050182] [d1 loss: 0.081613] [d2 loss: 0.105039]  [sq d1 d2: 0.000549]  [num0: 20.000000] [num1 44.000000]
[Epoch 332/500] [Batch 180/676] [D loss: -0.003557] [G loss: -0.039080] [d1 loss: 0.053033] [d2 loss: 0.063916]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 200/676] [D loss: 0.012530] [G loss: 0.009169] [d1 loss: 0.059742] [d2 loss: 0.072633]  [sq d1 d2: 0.000166]  [num0: 20.000000] [num1 44.000000]
[Epoch 332/500] [Batch 220/676] [D loss: 0.012218] [G loss: 0.031778] [d1 loss: 0.048636] [d2 loss: 0.050760]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 240/676] [D loss: 0.004958] [G loss: 0.016253] [d1 loss: 0.026497] [d2 loss: 0.026546]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 260/676] [D loss: -0.003859] [G loss: 0.006533] [d1 loss: 0.071757] [d2 loss: 0.085531]  [sq d1 d2: 0.000190]  [num0: 17.000000] [num1 47.000000]
[Epoch 332/500] [Batch 280/676] [D loss: -0.007956] [G loss: 0.018837] [d1 loss: 0.034246] [d2 loss: 0.035531]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 332/500] [Batch 300/676] [D loss: -0.015615] [G loss: 0.024262] [d1 loss: 0.123257] [d2 loss: 0.103384]  [sq d1 d2: 0.000395]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 320/676] [D loss: -0.027816] [G loss: 0.034788] [d1 loss: 0.108024] [d2 loss: 0.112954]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 340/676] [D loss: -0.032340] [G loss: 0.034912] [d1 loss: 0.097496] [d2 loss: 0.088119]  [sq d1 d2: 0.000088]  [num0: 19.000000] [num1 45.000000]
[Epoch 332/500] [Batch 360/676] [D loss: -0.047028] [G loss: 0.016190] [d1 loss: 0.058549] [d2 loss: 0.101927]  [sq d1 d2: 0.001882]  [num0: 21.000000] [num1 43.000000]
[Epoch 332/500] [Batch 380/676] [D loss: -0.007329] [G loss: 0.038539] [d1 loss: 0.020784] [d2 loss: 0.032973]  [sq d1 d2: 0.000149]  [num0: 18.000000] [num1 46.000000]
[Epoch 332/500] [Batch 400/676] [D loss: -0.050819] [G loss: 0.061039] [d1 loss: 0.020207] [d2 loss: 0.023145]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 332/500] [Batch 420/676] [D loss: -0.039676] [G loss: 0.025757] [d1 loss: 0.109526] [d2 loss: 0.120182]  [sq d1 d2: 0.000114]  [num0: 17.000000] [num1 47.000000]
[Epoch 332/500] [Batch 440/676] [D loss: -0.012543] [G loss: -0.005779] [d1 loss: 0.052547] [d2 loss: 0.068022]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 332/500] [Batch 460/676] [D loss: 0.023529] [G loss: 0.027161] [d1 loss: 0.065362] [d2 loss: 0.075550]  [sq d1 d2: 0.000104]  [num0: 12.000000] [num1 52.000000]
[Epoch 332/500] [Batch 480/676] [D loss: 0.014372] [G loss: 0.020507] [d1 loss: 0.041215] [d2 loss: 0.048517]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 500/676] [D loss: 0.007256] [G loss: 0.005095] [d1 loss: 0.128412] [d2 loss: 0.131985]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 520/676] [D loss: 0.003627] [G loss: -0.005223] [d1 loss: 0.110892] [d2 loss: 0.077304]  [sq d1 d2: 0.001128]  [num0: 13.000000] [num1 51.000000]
[Epoch 332/500] [Batch 540/676] [D loss: 0.001611] [G loss: -0.013918] [d1 loss: 0.118058] [d2 loss: 0.130863]  [sq d1 d2: 0.000164]  [num0: 14.000000] [num1 50.000000]
[Epoch 332/500] [Batch 560/676] [D loss: -0.003957] [G loss: -0.023973] [d1 loss: 0.028875] [d2 loss: 0.026062]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 332/500] [Batch 580/676] [D loss: -0.016499] [G loss: -0.033346] [d1 loss: 0.075917] [d2 loss: 0.077345]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 332/500] [Batch 600/676] [D loss: -0.022497] [G loss: -0.027100] [d1 loss: 0.129993] [d2 loss: 0.175823]  [sq d1 d2: 0.002100]  [num0: 20.000000] [num1 44.000000]

[Epoch 332/500] [Batch 620/676] [D loss: -0.020931] [G loss: -0.010994] [d1 loss: 0.036218] [d2 loss: 0.039182]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 332/500] [Batch 640/676] [D loss: -0.012149] [G loss: 0.011862] [d1 loss: 0.074372] [d2 loss: 0.072820]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 332/500] [Batch 660/676] [D loss: -0.004908] [G loss: 0.025052] [d1 loss: 0.102809] [d2 loss: 0.095832]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 0/676] [D loss: -0.011236] [G loss: -0.000225] [d1 loss: 0.082682] [d2 loss: 0.094554]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 20/676] [D loss: -0.015837] [G loss: -0.025402] [d1 loss: 0.072902] [d2 loss: 0.079600]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 333/500] [Batch 40/676] [D loss: 0.015731] [G loss: -0.042575] [d1 loss: 0.098317] [d2 loss: 0.107014]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 60/676] [D loss: 0.037362] [G loss: -0.034752] [d1 loss: 0.030972] [d2 loss: 0.037883]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 80/676] [D loss: 0.013087] [G loss: 0.024549] [d1 loss: 0.063292] [d2 loss: 0.073185]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]
[Epoch 333/500] [Batch 100/676] [D loss: 0.005747] [G loss: 0.055206] [d1 loss: 0.048713] [d2 loss: 0.042361]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 333/500] [Batch 120/676] [D loss: 0.006642] [G loss: 0.072575] [d1 loss: 0.127285] [d2 loss: 0.136512]  [sq d1 d2: 0.000085]  [num0: 14.000000] [num1 50.000000]
[Epoch 333/500] [Batch 140/676] [D loss: 0.001320] [G loss: 0.081184] [d1 loss: 0.137027] [d2 loss: 0.082246]  [sq d1 d2: 0.003001]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 160/676] [D loss: -0.009659] [G loss: 0.090495] [d1 loss: 0.118951] [d2 loss: 0.156369]  [sq d1 d2: 0.001400]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 180/676] [D loss: -0.025377] [G loss: 0.096958] [d1 loss: 0.034679] [d2 loss: 0.029475]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 200/676] [D loss: -0.018728] [G loss: 0.130806] [d1 loss: 0.029564] [d2 loss: 0.032332]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 220/676] [D loss: -0.011008] [G loss: 0.166270] [d1 loss: 0.078478] [d2 loss: 0.075902]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 333/500] [Batch 240/676] [D loss: -0.026148] [G loss: 0.129435] [d1 loss: 0.089354] [d2 loss: 0.098718]  [sq d1 d2: 0.000088]  [num0: 19.000000] [num1 45.000000]
[Epoch 333/500] [Batch 260/676] [D loss: -0.031305] [G loss: 0.101943] [d1 loss: 0.053482] [d2 loss: 0.060414]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 280/676] [D loss: -0.015299] [G loss: 0.053295] [d1 loss: 0.067178] [d2 loss: 0.070997]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 300/676] [D loss: -0.017767] [G loss: 0.050228] [d1 loss: 0.068581] [d2 loss: 0.096501]  [sq d1 d2: 0.000780]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 320/676] [D loss: -0.012636] [G loss: -0.009446] [d1 loss: 0.141038] [d2 loss: 0.178088]  [sq d1 d2: 0.001373]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 340/676] [D loss: 0.006428] [G loss: -0.053632] [d1 loss: 0.074925] [d2 loss: 0.054034]  [sq d1 d2: 0.000436]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 360/676] [D loss: 0.014845] [G loss: -0.100360] [d1 loss: 0.069278] [d2 loss: 0.088547]  [sq d1 d2: 0.000371]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 380/676] [D loss: 0.009274] [G loss: -0.105350] [d1 loss: 0.078339] [d2 loss: 0.074115]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 400/676] [D loss: 0.002981] [G loss: -0.091181] [d1 loss: 0.055105] [d2 loss: 0.041119]  [sq d1 d2: 0.000196]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 420/676] [D loss: 0.001127] [G loss: -0.087574] [d1 loss: 0.037412] [d2 loss: 0.029649]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 440/676] [D loss: -0.009138] [G loss: -0.068967] [d1 loss: 0.116207] [d2 loss: 0.108509]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 460/676] [D loss: -0.011085] [G loss: -0.063125] [d1 loss: 0.038258] [d2 loss: 0.031972]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 480/676] [D loss: -0.009946] [G loss: -0.063134] [d1 loss: 0.139579] [d2 loss: 0.119452]  [sq d1 d2: 0.000405]  [num0: 20.000000] [num1 44.000000]
[Epoch 333/500] [Batch 500/676] [D loss: -0.035613] [G loss: -0.023959] [d1 loss: 0.093467] [d2 loss: 0.071567]  [sq d1 d2: 0.000480]  [num0: 12.000000] [num1 52.000000]
[Epoch 333/500] [Batch 520/676] [D loss: -0.026583] [G loss: -0.017318] [d1 loss: 0.034363] [d2 loss: 0.031756]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 333/500] [Batch 540/676] [D loss: -0.007190] [G loss: -0.005054] [d1 loss: 0.110342] [d2 loss: 0.130546]  [sq d1 d2: 0.000408]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 560/676] [D loss: -0.016352] [G loss: 0.011876] [d1 loss: 0.093426] [d2 loss: 0.094535]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 333/500] [Batch 580/676] [D loss: 0.000278] [G loss: 0.008783] [d1 loss: 0.065673] [d2 loss: 0.069363]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 600/676] [D loss: -0.020439] [G loss: 0.008924] [d1 loss: 0.057053] [d2 loss: 0.061693]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 333/500] [Batch 620/676] [D loss: -0.002671] [G loss: -0.001639] [d1 loss: 0.064634] [d2 loss: 0.076473]  [sq d1 d2: 0.000140]  [num0: 16.000000] [num1 48.000000]
[Epoch 333/500] [Batch 640/676] [D loss: 0.011774] [G loss: -0.041028] [d1 loss: 0.101343] [d2 loss: 0.104135]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 333/500] [Batch 660/676] [D loss: 0.017401] [G loss: -0.020449] [d1 loss: 0.105458] [d2 loss: 0.094058]  [sq d1 d2: 0.000130]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 0/676] [D loss: 0.003123] [G loss: -0.011931] [d1 loss: 0.070038] [d2 loss: 0.072632]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 334/500] [Batch 20/676] [D loss: 0.001223] [G loss: -0.030041] [d1 loss: 0.073261] [d2 loss: 0.075372]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 334/500] [Batch 40/676] [D loss: 0.002088] [G loss: -0.027983] [d1 loss: 0.016539] [d2 loss: 0.024498]  [sq d1 d2: 0.000063]  [num0: 13.000000] [num1 51.000000]
[Epoch 334/500] [Batch 60/676] [D loss: 0.001660] [G loss: -0.030131] [d1 loss: 0.046160] [d2 loss: 0.050444]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 334/500] [Batch 80/676] [D loss: -0.000961] [G loss: -0.036599] [d1 loss: 0.021294] [d2 loss: 0.019893]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 334/500] [Batch 100/676] [D loss: -0.006919] [G loss: -0.063000] [d1 loss: 0.083288] [d2 loss: 0.120482]  [sq d1 d2: 0.001383]  [num0: 12.000000] [num1 52.000000]
[Epoch 334/500] [Batch 120/676] [D loss: -0.011694] [G loss: -0.093837] [d1 loss: 0.069698] [d2 loss: 0.066224]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 140/676] [D loss: -0.005517] [G loss: -0.115460] [d1 loss: 0.062555] [d2 loss: 0.058448]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 334/500] [Batch 160/676] [D loss: -0.031863] [G loss: -0.123690] [d1 loss: 0.014344] [d2 loss: 0.013632]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 334/500] [Batch 180/676] [D loss: -0.024851] [G loss: -0.146743] [d1 loss: 0.056013] [d2 loss: 0.064217]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 334/500] [Batch 200/676] [D loss: -0.001225] [G loss: -0.144729] [d1 loss: 0.062984] [d2 loss: 0.048554]  [sq d1 d2: 0.000208]  [num0: 14.000000] [num1 50.000000]
[Epoch 334/500] [Batch 220/676] [D loss: -0.019622] [G loss: -0.123634] [d1 loss: 0.061081] [d2 loss: 0.065545]  [sq d1 d2: 0.000020]  [num0: 21.000000] [num1 43.000000]
[Epoch 334/500] [Batch 240/676] [D loss: 0.005632] [G loss: -0.095900] [d1 loss: 0.106745] [d2 loss: 0.089912]  [sq d1 d2: 0.000283]  [num0: 17.000000] [num1 47.000000]
[Epoch 334/500] [Batch 260/676] [D loss: -0.020327] [G loss: -0.098127] [d1 loss: 0.084688] [d2 loss: 0.092753]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 280/676] [D loss: 0.025562] [G loss: -0.115225] [d1 loss: 0.108751] [d2 loss: 0.115251]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]

[Epoch 334/500] [Batch 300/676] [D loss: 0.011076] [G loss: -0.097831] [d1 loss: 0.050582] [d2 loss: 0.041383]  [sq d1 d2: 0.000085]  [num0: 12.000000] [num1 52.000000]
[Epoch 334/500] [Batch 320/676] [D loss: 0.003261] [G loss: -0.097754] [d1 loss: 0.081195] [d2 loss: 0.070272]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 334/500] [Batch 340/676] [D loss: 0.009322] [G loss: -0.069714] [d1 loss: 0.070815] [d2 loss: 0.076855]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 334/500] [Batch 360/676] [D loss: 0.001456] [G loss: -0.048457] [d1 loss: 0.104185] [d2 loss: 0.120696]  [sq d1 d2: 0.000273]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 380/676] [D loss: 0.001457] [G loss: -0.036955] [d1 loss: 0.130408] [d2 loss: 0.106805]  [sq d1 d2: 0.000557]  [num0: 17.000000] [num1 47.000000]
[Epoch 334/500] [Batch 400/676] [D loss: -0.002347] [G loss: -0.031260] [d1 loss: 0.067375] [d2 loss: 0.073107]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 334/500] [Batch 420/676] [D loss: -0.007081] [G loss: -0.034474] [d1 loss: 0.117347] [d2 loss: 0.138990]  [sq d1 d2: 0.000468]  [num0: 18.000000] [num1 46.000000]
[Epoch 334/500] [Batch 440/676] [D loss: -0.010342] [G loss: -0.018433] [d1 loss: 0.096693] [d2 loss: 0.109685]  [sq d1 d2: 0.000169]  [num0: 18.000000] [num1 46.000000]
[Epoch 334/500] [Batch 460/676] [D loss: -0.003808] [G loss: 0.005693] [d1 loss: 0.035010] [d2 loss: 0.035989]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 334/500] [Batch 480/676] [D loss: -0.021741] [G loss: 0.032864] [d1 loss: 0.128747] [d2 loss: 0.099958]  [sq d1 d2: 0.000829]  [num0: 15.000000] [num1 49.000000]
[Epoch 334/500] [Batch 500/676] [D loss: -0.021182] [G loss: 0.050147] [d1 loss: 0.238437] [d2 loss: 0.236006]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 334/500] [Batch 520/676] [D loss: -0.016105] [G loss: 0.043344] [d1 loss: 0.047414] [d2 loss: 0.042221]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 540/676] [D loss: -0.005184] [G loss: 0.054060] [d1 loss: 0.042306] [d2 loss: 0.043524]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 334/500] [Batch 560/676] [D loss: 0.001808] [G loss: 0.057199] [d1 loss: 0.073612] [d2 loss: 0.057919]  [sq d1 d2: 0.000246]  [num0: 18.000000] [num1 46.000000]
[Epoch 334/500] [Batch 580/676] [D loss: 0.009795] [G loss: 0.065757] [d1 loss: 0.066438] [d2 loss: 0.064534]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 334/500] [Batch 600/676] [D loss: 0.008773] [G loss: 0.076437] [d1 loss: 0.115560] [d2 loss: 0.138351]  [sq d1 d2: 0.000519]  [num0: 14.000000] [num1 50.000000]
[Epoch 334/500] [Batch 620/676] [D loss: 0.003324] [G loss: 0.074185] [d1 loss: 0.074188] [d2 loss: 0.086659]  [sq d1 d2: 0.000156]  [num0: 17.000000] [num1 47.000000]
[Epoch 334/500] [Batch 640/676] [D loss: 0.014518] [G loss: 0.070866] [d1 loss: 0.059929] [d2 loss: 0.056501]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 334/500] [Batch 660/676] [D loss: -0.001776] [G loss: 0.055344] [d1 loss: 0.075755] [d2 loss: 0.036788]  [sq d1 d2: 0.001518]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 0/676] [D loss: -0.002403] [G loss: 0.043109] [d1 loss: 0.122613] [d2 loss: 0.110120]  [sq d1 d2: 0.000156]  [num0: 18.000000] [num1 46.000000]
[Epoch 335/500] [Batch 20/676] [D loss: -0.006377] [G loss: 0.021817] [d1 loss: 0.038799] [d2 loss: 0.053124]  [sq d1 d2: 0.000205]  [num0: 11.000000] [num1 53.000000]
[Epoch 335/500] [Batch 40/676] [D loss: -0.005695] [G loss: 0.017772] [d1 loss: 0.110959] [d2 loss: 0.089490]  [sq d1 d2: 0.000461]  [num0: 19.000000] [num1 45.000000]
[Epoch 335/500] [Batch 60/676] [D loss: -0.009928] [G loss: -0.002260] [d1 loss: 0.068678] [d2 loss: 0.052293]  [sq d1 d2: 0.000268]  [num0: 17.000000] [num1 47.000000]
[Epoch 335/500] [Batch 80/676] [D loss: -0.004768] [G loss: -0.004456] [d1 loss: 0.063533] [d2 loss: 0.064377]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 335/500] [Batch 100/676] [D loss: -0.027345] [G loss: 0.002339] [d1 loss: 0.063879] [d2 loss: 0.066286]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 120/676] [D loss: -0.009996] [G loss: -0.026828] [d1 loss: 0.143974] [d2 loss: 0.133369]  [sq d1 d2: 0.000112]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 140/676] [D loss: -0.012774] [G loss: 0.008046] [d1 loss: 0.047096] [d2 loss: 0.043433]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 335/500] [Batch 160/676] [D loss: -0.002272] [G loss: -0.040692] [d1 loss: 0.141417] [d2 loss: 0.126842]  [sq d1 d2: 0.000212]  [num0: 17.000000] [num1 47.000000]
[Epoch 335/500] [Batch 180/676] [D loss: 0.006845] [G loss: -0.053621] [d1 loss: 0.082339] [d2 loss: 0.066796]  [sq d1 d2: 0.000242]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 200/676] [D loss: -0.005870] [G loss: -0.071195] [d1 loss: 0.053471] [d2 loss: 0.062186]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 220/676] [D loss: 0.020747] [G loss: -0.103012] [d1 loss: 0.038252] [d2 loss: 0.037478]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 240/676] [D loss: 0.011030] [G loss: -0.115571] [d1 loss: 0.113408] [d2 loss: 0.108352]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 260/676] [D loss: -0.001862] [G loss: -0.089881] [d1 loss: 0.031875] [d2 loss: 0.031033]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 335/500] [Batch 280/676] [D loss: -0.000399] [G loss: -0.072022] [d1 loss: 0.106543] [d2 loss: 0.095160]  [sq d1 d2: 0.000130]  [num0: 17.000000] [num1 47.000000]
[Epoch 335/500] [Batch 300/676] [D loss: -0.000869] [G loss: -0.062745] [d1 loss: 0.113284] [d2 loss: 0.097129]  [sq d1 d2: 0.000261]  [num0: 13.000000] [num1 51.000000]
[Epoch 335/500] [Batch 320/676] [D loss: -0.003922] [G loss: -0.033989] [d1 loss: 0.041760] [d2 loss: 0.043374]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 335/500] [Batch 340/676] [D loss: -0.008577] [G loss: -0.012329] [d1 loss: 0.024072] [d2 loss: 0.021331]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 335/500] [Batch 360/676] [D loss: -0.011914] [G loss: -0.002193] [d1 loss: 0.100409] [d2 loss: 0.060720]  [sq d1 d2: 0.001575]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 380/676] [D loss: -0.016770] [G loss: 0.004052] [d1 loss: 0.043595] [d2 loss: 0.042050]  [sq d1 d2: 0.000002]  [num0: 11.000000] [num1 53.000000]
[Epoch 335/500] [Batch 400/676] [D loss: -0.009813] [G loss: 0.047690] [d1 loss: 0.124189] [d2 loss: 0.121525]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 335/500] [Batch 420/676] [D loss: 0.004300] [G loss: 0.035431] [d1 loss: 0.061876] [d2 loss: 0.057813]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 335/500] [Batch 440/676] [D loss: -0.006040] [G loss: 0.028722] [d1 loss: 0.029048] [d2 loss: 0.026714]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 460/676] [D loss: -0.012911] [G loss: 0.019514] [d1 loss: 0.072876] [d2 loss: 0.059116]  [sq d1 d2: 0.000189]  [num0: 17.000000] [num1 47.000000]
[Epoch 335/500] [Batch 480/676] [D loss: 0.002850] [G loss: 0.036365] [d1 loss: 0.107290] [d2 loss: 0.101983]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 500/676] [D loss: 0.001417] [G loss: 0.020074] [d1 loss: 0.071321] [d2 loss: 0.082313]  [sq d1 d2: 0.000121]  [num0: 15.000000] [num1 49.000000]
[Epoch 335/500] [Batch 520/676] [D loss: 0.006039] [G loss: 0.020513] [d1 loss: 0.047365] [d2 loss: 0.036269]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 540/676] [D loss: 0.004625] [G loss: 0.005833] [d1 loss: 0.066763] [d2 loss: 0.063055]  [sq d1 d2: 0.000014]  [num0: 20.000000] [num1 44.000000]
[Epoch 335/500] [Batch 560/676] [D loss: -0.000328] [G loss: 0.008682] [d1 loss: 0.117821] [d2 loss: 0.117122]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 335/500] [Batch 580/676] [D loss: -0.003259] [G loss: -0.004940] [d1 loss: 0.081068] [d2 loss: 0.072178]  [sq d1 d2: 0.000079]  [num0: 19.000000] [num1 45.000000]
[Epoch 335/500] [Batch 600/676] [D loss: -0.004809] [G loss: 0.005811] [d1 loss: 0.023101] [d2 loss: 0.031931]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 335/500] [Batch 620/676] [D loss: -0.011332] [G loss: -0.013445] [d1 loss: 0.044544] [d2 loss: 0.040395]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 335/500] [Batch 640/676] [D loss: -0.006570] [G loss: -0.043036] [d1 loss: 0.079171] [d2 loss: 0.068174]  [sq d1 d2: 0.000121]  [num0: 17.000000] [num1 47.000000]

[Epoch 335/500] [Batch 660/676] [D loss: -0.011964] [G loss: -0.072565] [d1 loss: 0.014325] [d2 loss: 0.016966]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 336/500] [Batch 0/676] [D loss: -0.035779] [G loss: -0.084522] [d1 loss: 0.146756] [d2 loss: 0.182051]  [sq d1 d2: 0.001246]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 20/676] [D loss: -0.030050] [G loss: -0.123305] [d1 loss: 0.053317] [d2 loss: 0.056584]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 336/500] [Batch 40/676] [D loss: -0.003085] [G loss: -0.125607] [d1 loss: 0.072011] [d2 loss: 0.073995]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 336/500] [Batch 60/676] [D loss: 0.018709] [G loss: -0.075330] [d1 loss: 0.145580] [d2 loss: 0.096116]  [sq d1 d2: 0.002447]  [num0: 18.000000] [num1 46.000000]
[Epoch 336/500] [Batch 80/676] [D loss: 0.010322] [G loss: -0.066821] [d1 loss: 0.051799] [d2 loss: 0.051581]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 100/676] [D loss: -0.000339] [G loss: -0.067717] [d1 loss: 0.025600] [d2 loss: 0.030353]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 120/676] [D loss: 0.006670] [G loss: -0.061911] [d1 loss: 0.323925] [d2 loss: 0.290015]  [sq d1 d2: 0.001150]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 140/676] [D loss: 0.000399] [G loss: -0.062949] [d1 loss: 0.015561] [d2 loss: 0.017846]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 160/676] [D loss: -0.000814] [G loss: -0.041280] [d1 loss: 0.055632] [d2 loss: 0.060730]  [sq d1 d2: 0.000026]  [num0: 8.000000] [num1 56.000000]
[Epoch 336/500] [Batch 180/676] [D loss: -0.001901] [G loss: -0.010408] [d1 loss: 0.113202] [d2 loss: 0.111940]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 336/500] [Batch 200/676] [D loss: -0.008454] [G loss: -0.005836] [d1 loss: 0.023322] [d2 loss: 0.023979]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 220/676] [D loss: -0.003049] [G loss: -0.010538] [d1 loss: 0.034236] [d2 loss: 0.029236]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 240/676] [D loss: -0.009725] [G loss: 0.005520] [d1 loss: 0.129481] [d2 loss: 0.100962]  [sq d1 d2: 0.000813]  [num0: 12.000000] [num1 52.000000]
[Epoch 336/500] [Batch 260/676] [D loss: 0.008875] [G loss: 0.033329] [d1 loss: 0.117475] [d2 loss: 0.191977]  [sq d1 d2: 0.005551]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 280/676] [D loss: 0.000500] [G loss: -0.002948] [d1 loss: 0.070911] [d2 loss: 0.059996]  [sq d1 d2: 0.000119]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 300/676] [D loss: 0.006179] [G loss: 0.010002] [d1 loss: 0.035313] [d2 loss: 0.028787]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 320/676] [D loss: -0.000591] [G loss: 0.005550] [d1 loss: 0.054251] [d2 loss: 0.057594]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 336/500] [Batch 340/676] [D loss: 0.008247] [G loss: 0.041850] [d1 loss: 0.070750] [d2 loss: 0.077943]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 360/676] [D loss: 0.011800] [G loss: 0.079597] [d1 loss: 0.069179] [d2 loss: 0.087943]  [sq d1 d2: 0.000352]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 380/676] [D loss: -0.010984] [G loss: 0.073945] [d1 loss: 0.054020] [d2 loss: 0.054863]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 336/500] [Batch 400/676] [D loss: 0.010296] [G loss: 0.061095] [d1 loss: 0.876764] [d2 loss: 0.552551]  [sq d1 d2: 0.105114]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 420/676] [D loss: 0.009145] [G loss: 0.066222] [d1 loss: 0.049243] [d2 loss: 0.028645]  [sq d1 d2: 0.000424]  [num0: 16.000000] [num1 48.000000]
[Epoch 336/500] [Batch 440/676] [D loss: -0.003841] [G loss: 0.054226] [d1 loss: 0.045819] [d2 loss: 0.052926]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 336/500] [Batch 460/676] [D loss: -0.005888] [G loss: 0.045007] [d1 loss: 0.092063] [d2 loss: 0.092580]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 480/676] [D loss: -0.008866] [G loss: 0.037982] [d1 loss: 0.097962] [d2 loss: 0.098732]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 336/500] [Batch 500/676] [D loss: -0.010891] [G loss: 0.046225] [d1 loss: 0.056340] [d2 loss: 0.080284]  [sq d1 d2: 0.000573]  [num0: 14.000000] [num1 50.000000]
[Epoch 336/500] [Batch 520/676] [D loss: -0.016540] [G loss: 0.052053] [d1 loss: 0.024014] [d2 loss: 0.016523]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 540/676] [D loss: -0.026267] [G loss: 0.058207] [d1 loss: 0.015152] [d2 loss: 0.020125]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 560/676] [D loss: -0.035400] [G loss: 0.044243] [d1 loss: 0.116141] [d2 loss: 0.129070]  [sq d1 d2: 0.000167]  [num0: 14.000000] [num1 50.000000]
[Epoch 336/500] [Batch 580/676] [D loss: -0.013710] [G loss: 0.008888] [d1 loss: 0.018958] [d2 loss: 0.014998]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 336/500] [Batch 600/676] [D loss: 0.007606] [G loss: -0.033149] [d1 loss: 0.084967] [d2 loss: 0.070043]  [sq d1 d2: 0.000223]  [num0: 13.000000] [num1 51.000000]
[Epoch 336/500] [Batch 620/676] [D loss: -0.024175] [G loss: -0.082243] [d1 loss: 0.023666] [d2 loss: 0.018589]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 336/500] [Batch 640/676] [D loss: 0.017399] [G loss: -0.157903] [d1 loss: 0.033832] [d2 loss: 0.035792]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 336/500] [Batch 660/676] [D loss: 0.035592] [G loss: -0.165625] [d1 loss: 0.074655] [d2 loss: 0.066839]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 337/500] [Batch 0/676] [D loss: 0.013276] [G loss: -0.190638] [d1 loss: 0.058875] [d2 loss: 0.053373]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 20/676] [D loss: -0.001210] [G loss: -0.187869] [d1 loss: 0.108180] [d2 loss: 0.082538]  [sq d1 d2: 0.000658]  [num0: 17.000000] [num1 47.000000]
[Epoch 337/500] [Batch 40/676] [D loss: -0.005111] [G loss: -0.189465] [d1 loss: 0.142841] [d2 loss: 0.166086]  [sq d1 d2: 0.000540]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 60/676] [D loss: -0.005521] [G loss: -0.195007] [d1 loss: 0.043453] [d2 loss: 0.045265]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 337/500] [Batch 80/676] [D loss: -0.009932] [G loss: -0.230727] [d1 loss: 0.072607] [d2 loss: 0.172965]  [sq d1 d2: 0.010072]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 100/676] [D loss: -0.013548] [G loss: -0.259240] [d1 loss: 0.080654] [d2 loss: 0.075421]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 337/500] [Batch 120/676] [D loss: -0.026020] [G loss: -0.252201] [d1 loss: 0.065369] [d2 loss: 0.058568]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 337/500] [Batch 140/676] [D loss: -0.008766] [G loss: -0.251729] [d1 loss: 0.145248] [d2 loss: 0.122077]  [sq d1 d2: 0.000537]  [num0: 18.000000] [num1 46.000000]
[Epoch 337/500] [Batch 160/676] [D loss: -0.013602] [G loss: -0.249662] [d1 loss: 0.060578] [d2 loss: 0.067771]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 180/676] [D loss: -0.005351] [G loss: -0.213461] [d1 loss: 0.115979] [d2 loss: 0.108829]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 200/676] [D loss: -0.012098] [G loss: -0.218331] [d1 loss: 0.095936] [d2 loss: 0.096071]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 337/500] [Batch 220/676] [D loss: -0.013908] [G loss: -0.164319] [d1 loss: 0.307488] [d2 loss: 0.422722]  [sq d1 d2: 0.013279]  [num0: 11.000000] [num1 53.000000]
[Epoch 337/500] [Batch 240/676] [D loss: 0.022931] [G loss: -0.093652] [d1 loss: 1.107505] [d2 loss: 0.895233]  [sq d1 d2: 0.045059]  [num0: 18.000000] [num1 46.000000]
[Epoch 337/500] [Batch 260/676] [D loss: 0.002445] [G loss: -0.004997] [d1 loss: 0.064475] [d2 loss: 0.046344]  [sq d1 d2: 0.000329]  [num0: 16.000000] [num1 48.000000]
[Epoch 337/500] [Batch 280/676] [D loss: 0.005946] [G loss: 0.084114] [d1 loss: 0.153344] [d2 loss: 0.134284]  [sq d1 d2: 0.000363]  [num0: 19.000000] [num1 45.000000]
[Epoch 337/500] [Batch 300/676] [D loss: 0.001617] [G loss: 0.128825] [d1 loss: 0.039230] [d2 loss: 0.047064]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 337/500] [Batch 320/676] [D loss: -0.011846] [G loss: 0.163224] [d1 loss: 0.802774] [d2 loss: 0.828553]  [sq d1 d2: 0.000665]  [num0: 16.000000] [num1 48.000000]

[Epoch 337/500] [Batch 340/676] [D loss: -0.015624] [G loss: 0.204952] [d1 loss: 0.057814] [d2 loss: 0.051606]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 337/500] [Batch 360/676] [D loss: -0.007424] [G loss: 0.218924] [d1 loss: 0.249567] [d2 loss: 0.259224]  [sq d1 d2: 0.000093]  [num0: 12.000000] [num1 52.000000]
[Epoch 337/500] [Batch 380/676] [D loss: -0.001856] [G loss: 0.217955] [d1 loss: 0.092350] [d2 loss: 0.109141]  [sq d1 d2: 0.000282]  [num0: 13.000000] [num1 51.000000]
[Epoch 337/500] [Batch 400/676] [D loss: -0.011148] [G loss: 0.228144] [d1 loss: 0.025199] [d2 loss: 0.024220]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 337/500] [Batch 420/676] [D loss: -0.021972] [G loss: 0.232472] [d1 loss: 0.095080] [d2 loss: 0.098486]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 337/500] [Batch 440/676] [D loss: -0.021003] [G loss: 0.241775] [d1 loss: 0.059950] [d2 loss: 0.081658]  [sq d1 d2: 0.000471]  [num0: 17.000000] [num1 47.000000]
[Epoch 337/500] [Batch 460/676] [D loss: -0.003557] [G loss: 0.207153] [d1 loss: 0.074055] [d2 loss: 0.063483]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 337/500] [Batch 480/676] [D loss: -0.013593] [G loss: 0.181466] [d1 loss: 0.131865] [d2 loss: 0.099319]  [sq d1 d2: 0.001059]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 500/676] [D loss: -0.002407] [G loss: 0.132578] [d1 loss: 0.123852] [d2 loss: 0.141522]  [sq d1 d2: 0.000312]  [num0: 18.000000] [num1 46.000000]
[Epoch 337/500] [Batch 520/676] [D loss: -0.006980] [G loss: 0.067017] [d1 loss: 0.079678] [d2 loss: 0.065698]  [sq d1 d2: 0.000195]  [num0: 14.000000] [num1 50.000000]
[Epoch 337/500] [Batch 540/676] [D loss: -0.001137] [G loss: 0.002578] [d1 loss: 0.087622] [d2 loss: 0.094314]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 337/500] [Batch 560/676] [D loss: -0.012601] [G loss: -0.041306] [d1 loss: 1.650106] [d2 loss: 1.667266]  [sq d1 d2: 0.000294]  [num0: 17.000000] [num1 47.000000]
[Epoch 337/500] [Batch 580/676] [D loss: -0.000708] [G loss: -0.129387] [d1 loss: 0.098184] [d2 loss: 0.088266]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]
[Epoch 337/500] [Batch 600/676] [D loss: 0.008736] [G loss: -0.150588] [d1 loss: 0.081756] [d2 loss: 0.076903]  [sq d1 d2: 0.000024]  [num0: 10.000000] [num1 54.000000]
[Epoch 337/500] [Batch 620/676] [D loss: -0.007684] [G loss: -0.175501] [d1 loss: 0.056128] [d2 loss: 0.057119]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 337/500] [Batch 640/676] [D loss: -0.013344] [G loss: -0.182820] [d1 loss: 0.104161] [d2 loss: 0.110448]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 337/500] [Batch 660/676] [D loss: -0.001695] [G loss: -0.193052] [d1 loss: 0.173521] [d2 loss: 0.117628]  [sq d1 d2: 0.003124]  [num0: 11.000000] [num1 53.000000]
[Epoch 338/500] [Batch 0/676] [D loss: -0.009914] [G loss: -0.199431] [d1 loss: 0.087526] [d2 loss: 0.101875]  [sq d1 d2: 0.000206]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 20/676] [D loss: 0.005060] [G loss: -0.192122] [d1 loss: 0.102285] [d2 loss: 0.116087]  [sq d1 d2: 0.000190]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 40/676] [D loss: -0.024378] [G loss: -0.209515] [d1 loss: 0.051808] [d2 loss: 0.043840]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 60/676] [D loss: -0.020964] [G loss: -0.190189] [d1 loss: 0.187750] [d2 loss: 0.107370]  [sq d1 d2: 0.006461]  [num0: 19.000000] [num1 45.000000]
[Epoch 338/500] [Batch 80/676] [D loss: -0.007237] [G loss: -0.181928] [d1 loss: 0.072188] [d2 loss: 0.068217]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 100/676] [D loss: -0.000252] [G loss: -0.173515] [d1 loss: 0.107527] [d2 loss: 0.086565]  [sq d1 d2: 0.000439]  [num0: 18.000000] [num1 46.000000]
[Epoch 338/500] [Batch 120/676] [D loss: -0.014024] [G loss: -0.154936] [d1 loss: 0.082628] [d2 loss: 0.071199]  [sq d1 d2: 0.000131]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 140/676] [D loss: 0.004266] [G loss: -0.123250] [d1 loss: 0.134433] [d2 loss: 0.110653]  [sq d1 d2: 0.000565]  [num0: 12.000000] [num1 52.000000]
[Epoch 338/500] [Batch 160/676] [D loss: -0.002664] [G loss: -0.082882] [d1 loss: 0.059217] [d2 loss: 0.059717]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 338/500] [Batch 180/676] [D loss: -0.011794] [G loss: -0.071478] [d1 loss: 0.063621] [d2 loss: 0.053089]  [sq d1 d2: 0.000111]  [num0: 12.000000] [num1 52.000000]
[Epoch 338/500] [Batch 200/676] [D loss: -0.004096] [G loss: -0.025152] [d1 loss: 0.164826] [d2 loss: 0.175014]  [sq d1 d2: 0.000104]  [num0: 18.000000] [num1 46.000000]
[Epoch 338/500] [Batch 220/676] [D loss: -0.012188] [G loss: -0.003970] [d1 loss: 0.022674] [d2 loss: 0.026154]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 240/676] [D loss: -0.001914] [G loss: 0.012607] [d1 loss: 0.058879] [d2 loss: 0.069661]  [sq d1 d2: 0.000116]  [num0: 18.000000] [num1 46.000000]
[Epoch 338/500] [Batch 260/676] [D loss: -0.010648] [G loss: 0.024045] [d1 loss: 0.098933] [d2 loss: 0.121632]  [sq d1 d2: 0.000515]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 280/676] [D loss: -0.006288] [G loss: 0.019962] [d1 loss: 0.141079] [d2 loss: 0.166679]  [sq d1 d2: 0.000655]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 300/676] [D loss: -0.012987] [G loss: 0.030153] [d1 loss: 0.062106] [d2 loss: 0.065260]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 320/676] [D loss: -0.012608] [G loss: 0.030567] [d1 loss: 0.138025] [d2 loss: 0.124700]  [sq d1 d2: 0.000178]  [num0: 13.000000] [num1 51.000000]
[Epoch 338/500] [Batch 340/676] [D loss: -0.009350] [G loss: 0.049470] [d1 loss: 0.158685] [d2 loss: 0.178312]  [sq d1 d2: 0.000385]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 360/676] [D loss: -0.008194] [G loss: 0.066789] [d1 loss: 0.051783] [d2 loss: 0.058992]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 380/676] [D loss: -0.012871] [G loss: 0.082094] [d1 loss: 0.119270] [d2 loss: 0.115618]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 400/676] [D loss: 0.006306] [G loss: 0.077770] [d1 loss: 0.353375] [d2 loss: 0.355114]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 338/500] [Batch 420/676] [D loss: -0.005928] [G loss: 0.080086] [d1 loss: 0.066753] [d2 loss: 0.062079]  [sq d1 d2: 0.000022]  [num0: 10.000000] [num1 54.000000]
[Epoch 338/500] [Batch 440/676] [D loss: 0.009370] [G loss: 0.051056] [d1 loss: 0.129970] [d2 loss: 0.139747]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 460/676] [D loss: -0.018878] [G loss: 0.045214] [d1 loss: 0.037964] [d2 loss: 0.033937]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 338/500] [Batch 480/676] [D loss: 0.003850] [G loss: 0.000138] [d1 loss: 0.093573] [d2 loss: 0.102490]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 500/676] [D loss: -0.010462] [G loss: -0.026177] [d1 loss: 0.087323] [d2 loss: 0.114336]  [sq d1 d2: 0.000730]  [num0: 18.000000] [num1 46.000000]
[Epoch 338/500] [Batch 520/676] [D loss: -0.012021] [G loss: -0.062061] [d1 loss: 0.067143] [d2 loss: 0.071766]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 540/676] [D loss: -0.005212] [G loss: -0.053631] [d1 loss: 0.036453] [d2 loss: 0.050393]  [sq d1 d2: 0.000194]  [num0: 11.000000] [num1 53.000000]
[Epoch 338/500] [Batch 560/676] [D loss: -0.006328] [G loss: -0.086337] [d1 loss: 0.237673] [d2 loss: 0.292762]  [sq d1 d2: 0.003035]  [num0: 16.000000] [num1 48.000000]
[Epoch 338/500] [Batch 580/676] [D loss: -0.010235] [G loss: -0.080283] [d1 loss: 0.073992] [d2 loss: 0.071146]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 338/500] [Batch 600/676] [D loss: 0.005487] [G loss: -0.056489] [d1 loss: 0.086010] [d2 loss: 0.132908]  [sq d1 d2: 0.002199]  [num0: 15.000000] [num1 49.000000]
[Epoch 338/500] [Batch 620/676] [D loss: -0.007153] [G loss: -0.054324] [d1 loss: 0.039368] [d2 loss: 0.040681]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 338/500] [Batch 640/676] [D loss: -0.006753] [G loss: -0.047152] [d1 loss: 0.043013] [d2 loss: 0.041409]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 338/500] [Batch 660/676] [D loss: -0.016481] [G loss: -0.053446] [d1 loss: 0.064658] [d2 loss: 0.069231]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 339/500] [Batch 0/676] [D loss: 0.002315] [G loss: -0.064321] [d1 loss: 0.139354] [d2 loss: 0.155035]  [sq d1 d2: 0.000246]  [num0: 20.000000] [num1 44.000000]

[Epoch 339/500] [Batch 20/676] [D loss: -0.000831] [G loss: -0.036525] [d1 loss: 0.161736] [d2 loss: 0.187472]  [sq d1 d2: 0.000662]  [num0: 16.000000] [num1 48.000000]
[Epoch 339/500] [Batch 40/676] [D loss: -0.018550] [G loss: -0.048710] [d1 loss: 0.015447] [d2 loss: 0.017203]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 339/500] [Batch 60/676] [D loss: -0.019664] [G loss: -0.025299] [d1 loss: 0.099364] [d2 loss: 0.098397]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 339/500] [Batch 80/676] [D loss: -0.002544] [G loss: -0.004438] [d1 loss: 0.048826] [d2 loss: 0.068037]  [sq d1 d2: 0.000369]  [num0: 18.000000] [num1 46.000000]
[Epoch 339/500] [Batch 100/676] [D loss: 0.000884] [G loss: -0.008904] [d1 loss: 0.081525] [d2 loss: 0.081251]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 339/500] [Batch 120/676] [D loss: -0.007284] [G loss: 0.004660] [d1 loss: 0.099718] [d2 loss: 0.085318]  [sq d1 d2: 0.000207]  [num0: 20.000000] [num1 44.000000]
[Epoch 339/500] [Batch 140/676] [D loss: -0.014067] [G loss: 0.002204] [d1 loss: 0.095986] [d2 loss: 0.084222]  [sq d1 d2: 0.000138]  [num0: 18.000000] [num1 46.000000]
[Epoch 339/500] [Batch 160/676] [D loss: -0.013334] [G loss: 0.007385] [d1 loss: 0.042410] [d2 loss: 0.036172]  [sq d1 d2: 0.000039]  [num0: 19.000000] [num1 45.000000]
[Epoch 339/500] [Batch 180/676] [D loss: -0.002930] [G loss: 0.027942] [d1 loss: 0.139132] [d2 loss: 0.122847]  [sq d1 d2: 0.000265]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 200/676] [D loss: -0.003538] [G loss: 0.027035] [d1 loss: 0.050918] [d2 loss: 0.044274]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 220/676] [D loss: -0.011211] [G loss: 0.028499] [d1 loss: 0.078911] [d2 loss: 0.083532]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 339/500] [Batch 240/676] [D loss: -0.015388] [G loss: 0.052593] [d1 loss: 0.186960] [d2 loss: 0.225720]  [sq d1 d2: 0.001502]  [num0: 19.000000] [num1 45.000000]
[Epoch 339/500] [Batch 260/676] [D loss: -0.012496] [G loss: 0.035039] [d1 loss: 0.049431] [d2 loss: 0.047959]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 339/500] [Batch 280/676] [D loss: -0.009556] [G loss: 0.030784] [d1 loss: 0.084567] [d2 loss: 0.114494]  [sq d1 d2: 0.000896]  [num0: 13.000000] [num1 51.000000]
[Epoch 339/500] [Batch 300/676] [D loss: 0.006714] [G loss: 0.025716] [d1 loss: 0.144131] [d2 loss: 0.159537]  [sq d1 d2: 0.000237]  [num0: 16.000000] [num1 48.000000]
[Epoch 339/500] [Batch 320/676] [D loss: -0.004977] [G loss: 0.014804] [d1 loss: 0.125372] [d2 loss: 0.110544]  [sq d1 d2: 0.000220]  [num0: 13.000000] [num1 51.000000]
[Epoch 339/500] [Batch 340/676] [D loss: -0.014921] [G loss: 0.004223] [d1 loss: 0.231829] [d2 loss: 0.233505]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 360/676] [D loss: -0.007561] [G loss: -0.035991] [d1 loss: 0.071451] [d2 loss: 0.059859]  [sq d1 d2: 0.000134]  [num0: 19.000000] [num1 45.000000]
[Epoch 339/500] [Batch 380/676] [D loss: -0.008388] [G loss: -0.045594] [d1 loss: 0.061112] [d2 loss: 0.064520]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 400/676] [D loss: -0.009944] [G loss: -0.043444] [d1 loss: 0.062552] [d2 loss: 0.056183]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 420/676] [D loss: 0.005230] [G loss: -0.063579] [d1 loss: 0.066424] [d2 loss: 0.064485]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 339/500] [Batch 440/676] [D loss: -0.007437] [G loss: -0.058166] [d1 loss: 0.123189] [d2 loss: 0.123664]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 339/500] [Batch 460/676] [D loss: 0.001540] [G loss: -0.076641] [d1 loss: 0.031794] [d2 loss: 0.025558]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 339/500] [Batch 480/676] [D loss: -0.001862] [G loss: -0.105131] [d1 loss: 0.030807] [d2 loss: 0.029897]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 339/500] [Batch 500/676] [D loss: -0.000106] [G loss: -0.099748] [d1 loss: 0.067135] [d2 loss: 0.080856]  [sq d1 d2: 0.000188]  [num0: 14.000000] [num1 50.000000]
[Epoch 339/500] [Batch 520/676] [D loss: -0.008883] [G loss: -0.088865] [d1 loss: 0.057810] [d2 loss: 0.062712]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 339/500] [Batch 540/676] [D loss: -0.004847] [G loss: -0.091081] [d1 loss: 0.123055] [d2 loss: 0.109914]  [sq d1 d2: 0.000173]  [num0: 21.000000] [num1 43.000000]
[Epoch 339/500] [Batch 560/676] [D loss: -0.000609] [G loss: -0.116655] [d1 loss: 0.097523] [d2 loss: 0.100763]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 339/500] [Batch 580/676] [D loss: -0.008619] [G loss: -0.128840] [d1 loss: 0.038978] [d2 loss: 0.040801]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 339/500] [Batch 600/676] [D loss: 0.000108] [G loss: -0.121962] [d1 loss: 0.073314] [d2 loss: 0.081278]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 339/500] [Batch 620/676] [D loss: -0.003024] [G loss: -0.131166] [d1 loss: 0.083589] [d2 loss: 0.087035]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 339/500] [Batch 640/676] [D loss: 0.003191] [G loss: -0.119773] [d1 loss: 0.035287] [d2 loss: 0.039470]  [sq d1 d2: 0.000017]  [num0: 11.000000] [num1 53.000000]
[Epoch 339/500] [Batch 660/676] [D loss: -0.005488] [G loss: -0.116262] [d1 loss: 0.053720] [d2 loss: 0.100788]  [sq d1 d2: 0.002215]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 0/676] [D loss: -0.001476] [G loss: -0.122906] [d1 loss: 0.077472] [d2 loss: 0.091393]  [sq d1 d2: 0.000194]  [num0: 12.000000] [num1 52.000000]
[Epoch 340/500] [Batch 20/676] [D loss: -0.000236] [G loss: -0.118650] [d1 loss: 0.086697] [d2 loss: 0.089407]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 40/676] [D loss: -0.000997] [G loss: -0.099664] [d1 loss: 0.261311] [d2 loss: 0.150169]  [sq d1 d2: 0.012352]  [num0: 18.000000] [num1 46.000000]
[Epoch 340/500] [Batch 60/676] [D loss: -0.000795] [G loss: -0.143193] [d1 loss: 0.105844] [d2 loss: 0.113090]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 340/500] [Batch 80/676] [D loss: -0.008827] [G loss: -0.145047] [d1 loss: 0.117022] [d2 loss: 0.130295]  [sq d1 d2: 0.000176]  [num0: 18.000000] [num1 46.000000]
[Epoch 340/500] [Batch 100/676] [D loss: -0.020991] [G loss: -0.106861] [d1 loss: 0.044142] [d2 loss: 0.036971]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 340/500] [Batch 120/676] [D loss: -0.018595] [G loss: -0.125489] [d1 loss: 0.050167] [d2 loss: 0.048692]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 340/500] [Batch 140/676] [D loss: -0.004770] [G loss: -0.105471] [d1 loss: 0.089701] [d2 loss: 0.097415]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 160/676] [D loss: -0.002143] [G loss: -0.077474] [d1 loss: 0.034353] [d2 loss: 0.036609]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 340/500] [Batch 180/676] [D loss: 0.000401] [G loss: -0.072133] [d1 loss: 0.069142] [d2 loss: 0.049113]  [sq d1 d2: 0.000401]  [num0: 18.000000] [num1 46.000000]
[Epoch 340/500] [Batch 200/676] [D loss: -0.001906] [G loss: -0.073874] [d1 loss: 0.155220] [d2 loss: 0.144015]  [sq d1 d2: 0.000126]  [num0: 11.000000] [num1 53.000000]
[Epoch 340/500] [Batch 220/676] [D loss: -0.006591] [G loss: -0.053873] [d1 loss: 0.129978] [d2 loss: 0.102666]  [sq d1 d2: 0.000746]  [num0: 17.000000] [num1 47.000000]
[Epoch 340/500] [Batch 240/676] [D loss: -0.001296] [G loss: -0.054154] [d1 loss: 0.086861] [d2 loss: 0.046587]  [sq d1 d2: 0.001622]  [num0: 16.000000] [num1 48.000000]
[Epoch 340/500] [Batch 260/676] [D loss: -0.009999] [G loss: -0.035664] [d1 loss: 0.088274] [d2 loss: 0.102943]  [sq d1 d2: 0.000215]  [num0: 17.000000] [num1 47.000000]
[Epoch 340/500] [Batch 280/676] [D loss: -0.008403] [G loss: -0.054813] [d1 loss: 0.187385] [d2 loss: 0.193587]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 340/500] [Batch 300/676] [D loss: -0.010571] [G loss: -0.055167] [d1 loss: 0.140515] [d2 loss: 0.184824]  [sq d1 d2: 0.001963]  [num0: 13.000000] [num1 51.000000]
[Epoch 340/500] [Batch 320/676] [D loss: -0.011543] [G loss: -0.065278] [d1 loss: 0.078854] [d2 loss: 0.078134]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 340/676] [D loss: 0.000112] [G loss: -0.036642] [d1 loss: 0.073569] [d2 loss: 0.107609]  [sq d1 d2: 0.001159]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 360/676] [D loss: -0.004536] [G loss: -0.061722] [d1 loss: 0.097665] [d2 loss: 0.097204]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]

[Epoch 340/500] [Batch 380/676] [D loss: -0.007947] [G loss: -0.051168] [d1 loss: 0.105779] [d2 loss: 0.117553]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 340/500] [Batch 400/676] [D loss: -0.007577] [G loss: -0.027353] [d1 loss: 0.177477] [d2 loss: 0.179405]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 340/500] [Batch 420/676] [D loss: -0.007471] [G loss: -0.063158] [d1 loss: 0.163657] [d2 loss: 0.128088]  [sq d1 d2: 0.001265]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 440/676] [D loss: 0.003504] [G loss: -0.043528] [d1 loss: 0.063341] [d2 loss: 0.059983]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 340/500] [Batch 460/676] [D loss: -0.008152] [G loss: -0.061947] [d1 loss: 0.058333] [d2 loss: 0.059886]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 340/500] [Batch 480/676] [D loss: -0.002143] [G loss: -0.024762] [d1 loss: 0.067323] [d2 loss: 0.091655]  [sq d1 d2: 0.000592]  [num0: 15.000000] [num1 49.000000]
[Epoch 340/500] [Batch 500/676] [D loss: -0.002366] [G loss: -0.025434] [d1 loss: 0.074297] [d2 loss: 0.077529]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 340/500] [Batch 520/676] [D loss: -0.012046] [G loss: -0.051552] [d1 loss: 0.068130] [d2 loss: 0.050205]  [sq d1 d2: 0.000321]  [num0: 12.000000] [num1 52.000000]
[Epoch 340/500] [Batch 540/676] [D loss: -0.023665] [G loss: -0.050055] [d1 loss: 0.082543] [d2 loss: 0.079282]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 340/500] [Batch 560/676] [D loss: -0.002860] [G loss: -0.031000] [d1 loss: 0.054088] [d2 loss: 0.050374]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 340/500] [Batch 580/676] [D loss: -0.013022] [G loss: -0.047789] [d1 loss: 0.047583] [d2 loss: 0.056683]  [sq d1 d2: 0.000083]  [num0: 12.000000] [num1 52.000000]
[Epoch 340/500] [Batch 600/676] [D loss: -0.014364] [G loss: -0.049623] [d1 loss: 0.041239] [d2 loss: 0.046776]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 340/500] [Batch 620/676] [D loss: -0.004983] [G loss: -0.060684] [d1 loss: 0.061475] [d2 loss: 0.064931]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 340/500] [Batch 640/676] [D loss: -0.020728] [G loss: -0.073608] [d1 loss: 0.090185] [d2 loss: 0.087022]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 340/500] [Batch 660/676] [D loss: -0.001919] [G loss: -0.100857] [d1 loss: 0.060782] [d2 loss: 0.064715]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 0/676] [D loss: 0.001569] [G loss: -0.086060] [d1 loss: 0.035934] [d2 loss: 0.046139]  [sq d1 d2: 0.000104]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 20/676] [D loss: -0.000918] [G loss: -0.066214] [d1 loss: 0.021809] [d2 loss: 0.026467]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 341/500] [Batch 40/676] [D loss: -0.007403] [G loss: -0.046385] [d1 loss: 0.254387] [d2 loss: 0.158886]  [sq d1 d2: 0.009120]  [num0: 18.000000] [num1 46.000000]
[Epoch 341/500] [Batch 60/676] [D loss: -0.005343] [G loss: -0.058800] [d1 loss: 0.136152] [d2 loss: 0.160166]  [sq d1 d2: 0.000577]  [num0: 18.000000] [num1 46.000000]
[Epoch 341/500] [Batch 80/676] [D loss: -0.009138] [G loss: -0.046730] [d1 loss: 0.097673] [d2 loss: 0.106077]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 100/676] [D loss: -0.013589] [G loss: -0.054371] [d1 loss: 0.122460] [d2 loss: 0.071983]  [sq d1 d2: 0.002548]  [num0: 17.000000] [num1 47.000000]
[Epoch 341/500] [Batch 120/676] [D loss: -0.005003] [G loss: -0.051329] [d1 loss: 0.108417] [d2 loss: 0.121517]  [sq d1 d2: 0.000172]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 140/676] [D loss: -0.011630] [G loss: -0.049901] [d1 loss: 0.048695] [d2 loss: 0.056657]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 160/676] [D loss: 0.001606] [G loss: -0.054876] [d1 loss: 0.040429] [d2 loss: 0.045924]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 180/676] [D loss: -0.011502] [G loss: -0.065209] [d1 loss: 0.043233] [d2 loss: 0.048311]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 341/500] [Batch 200/676] [D loss: -0.010964] [G loss: -0.067548] [d1 loss: 0.078616] [d2 loss: 0.095716]  [sq d1 d2: 0.000292]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 220/676] [D loss: -0.004616] [G loss: -0.053042] [d1 loss: 0.795248] [d2 loss: 0.479197]  [sq d1 d2: 0.099888]  [num0: 20.000000] [num1 44.000000]
[Epoch 341/500] [Batch 240/676] [D loss: -0.020351] [G loss: -0.028100] [d1 loss: 0.103229] [d2 loss: 0.114046]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 260/676] [D loss: -0.008840] [G loss: -0.044167] [d1 loss: 0.059348] [d2 loss: 0.052192]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 280/676] [D loss: -0.012968] [G loss: -0.048099] [d1 loss: 0.052567] [d2 loss: 0.054758]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 300/676] [D loss: -0.011240] [G loss: -0.041186] [d1 loss: 0.051689] [d2 loss: 0.053553]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 341/500] [Batch 320/676] [D loss: -0.000603] [G loss: -0.062795] [d1 loss: 0.080798] [d2 loss: 0.087260]  [sq d1 d2: 0.000042]  [num0: 21.000000] [num1 43.000000]
[Epoch 341/500] [Batch 340/676] [D loss: -0.014122] [G loss: -0.042503] [d1 loss: 0.429730] [d2 loss: 0.226541]  [sq d1 d2: 0.041286]  [num0: 14.000000] [num1 50.000000]
[Epoch 341/500] [Batch 360/676] [D loss: -0.014984] [G loss: -0.065430] [d1 loss: 0.193953] [d2 loss: 0.148121]  [sq d1 d2: 0.002101]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 380/676] [D loss: -0.007118] [G loss: -0.088081] [d1 loss: 0.019065] [d2 loss: 0.019859]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 400/676] [D loss: -0.000470] [G loss: -0.080810] [d1 loss: 0.046520] [d2 loss: 0.042432]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 420/676] [D loss: -0.002526] [G loss: -0.065784] [d1 loss: 0.090947] [d2 loss: 0.084455]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 440/676] [D loss: -0.006794] [G loss: -0.051822] [d1 loss: 0.100029] [d2 loss: 0.133465]  [sq d1 d2: 0.001118]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 460/676] [D loss: -0.005286] [G loss: -0.039185] [d1 loss: 0.060385] [d2 loss: 0.055198]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 480/676] [D loss: -0.005869] [G loss: -0.048075] [d1 loss: 0.047798] [d2 loss: 0.043595]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 500/676] [D loss: -0.006349] [G loss: -0.064710] [d1 loss: 0.135862] [d2 loss: 0.102421]  [sq d1 d2: 0.001118]  [num0: 17.000000] [num1 47.000000]
[Epoch 341/500] [Batch 520/676] [D loss: 0.004847] [G loss: -0.043703] [d1 loss: 0.120464] [d2 loss: 0.114419]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 540/676] [D loss: -0.006967] [G loss: -0.063587] [d1 loss: 0.093378] [d2 loss: 0.084134]  [sq d1 d2: 0.000085]  [num0: 19.000000] [num1 45.000000]
[Epoch 341/500] [Batch 560/676] [D loss: -0.008594] [G loss: -0.064264] [d1 loss: 0.095362] [d2 loss: 0.109503]  [sq d1 d2: 0.000200]  [num0: 16.000000] [num1 48.000000]
[Epoch 341/500] [Batch 580/676] [D loss: -0.008563] [G loss: -0.059590] [d1 loss: 0.058527] [d2 loss: 0.059700]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 341/500] [Batch 600/676] [D loss: -0.009131] [G loss: -0.070234] [d1 loss: 0.139908] [d2 loss: 0.104247]  [sq d1 d2: 0.001272]  [num0: 19.000000] [num1 45.000000]
[Epoch 341/500] [Batch 620/676] [D loss: -0.005187] [G loss: -0.106944] [d1 loss: 0.096118] [d2 loss: 0.083742]  [sq d1 d2: 0.000153]  [num0: 14.000000] [num1 50.000000]
[Epoch 341/500] [Batch 640/676] [D loss: -0.017246] [G loss: -0.120139] [d1 loss: 0.149395] [d2 loss: 0.130008]  [sq d1 d2: 0.000376]  [num0: 15.000000] [num1 49.000000]
[Epoch 341/500] [Batch 660/676] [D loss: -0.012213] [G loss: -0.150669] [d1 loss: 0.063119] [d2 loss: 0.034216]  [sq d1 d2: 0.000835]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 0/676] [D loss: -0.019397] [G loss: -0.130507] [d1 loss: 0.119369] [d2 loss: 0.128672]  [sq d1 d2: 0.000087]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 20/676] [D loss: -0.028676] [G loss: -0.154035] [d1 loss: 0.092722] [d2 loss: 0.095590]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 342/500] [Batch 40/676] [D loss: -0.010573] [G loss: -0.171372] [d1 loss: 0.102833] [d2 loss: 0.110934]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]

[Epoch 342/500] [Batch 60/676] [D loss: 0.008032] [G loss: -0.166115] [d1 loss: 0.033311] [d2 loss: 0.042955]  [sq d1 d2: 0.000093]  [num0: 18.000000] [num1 46.000000]
[Epoch 342/500] [Batch 80/676] [D loss: 0.008023] [G loss: -0.190628] [d1 loss: 0.057803] [d2 loss: 0.061663]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 100/676] [D loss: 0.000199] [G loss: -0.142411] [d1 loss: 0.073757] [d2 loss: 0.070308]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 342/500] [Batch 120/676] [D loss: 0.004073] [G loss: -0.121413] [d1 loss: 0.092321] [d2 loss: 0.068949]  [sq d1 d2: 0.000546]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 140/676] [D loss: -0.009154] [G loss: -0.105899] [d1 loss: 0.130999] [d2 loss: 0.146869]  [sq d1 d2: 0.000252]  [num0: 15.000000] [num1 49.000000]
[Epoch 342/500] [Batch 160/676] [D loss: -0.004752] [G loss: -0.133132] [d1 loss: 0.100784] [d2 loss: 0.086666]  [sq d1 d2: 0.000199]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 180/676] [D loss: -0.009638] [G loss: -0.142044] [d1 loss: 0.091822] [d2 loss: 0.111034]  [sq d1 d2: 0.000369]  [num0: 15.000000] [num1 49.000000]
[Epoch 342/500] [Batch 200/676] [D loss: -0.020466] [G loss: -0.137870] [d1 loss: 0.067301] [d2 loss: 0.074559]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 220/676] [D loss: -0.031745] [G loss: -0.135527] [d1 loss: 0.055677] [d2 loss: 0.050842]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 342/500] [Batch 240/676] [D loss: -0.002519] [G loss: -0.114749] [d1 loss: 0.091221] [d2 loss: 0.128305]  [sq d1 d2: 0.001375]  [num0: 15.000000] [num1 49.000000]
[Epoch 342/500] [Batch 260/676] [D loss: -0.019718] [G loss: -0.139059] [d1 loss: 0.053296] [d2 loss: 0.040347]  [sq d1 d2: 0.000168]  [num0: 13.000000] [num1 51.000000]
[Epoch 342/500] [Batch 280/676] [D loss: 0.002877] [G loss: -0.098787] [d1 loss: 0.036068] [d2 loss: 0.037247]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 300/676] [D loss: -0.006753] [G loss: -0.103210] [d1 loss: 0.110929] [d2 loss: 0.170248]  [sq d1 d2: 0.003519]  [num0: 19.000000] [num1 45.000000]
[Epoch 342/500] [Batch 320/676] [D loss: 0.002449] [G loss: -0.081416] [d1 loss: 0.125244] [d2 loss: 0.102724]  [sq d1 d2: 0.000507]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 340/676] [D loss: -0.001868] [G loss: -0.052632] [d1 loss: 0.213695] [d2 loss: 0.209264]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 360/676] [D loss: -0.006233] [G loss: -0.037211] [d1 loss: 0.060419] [d2 loss: 0.046009]  [sq d1 d2: 0.000208]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 380/676] [D loss: -0.012023] [G loss: -0.038575] [d1 loss: 0.038622] [d2 loss: 0.045161]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 400/676] [D loss: -0.011298] [G loss: -0.026269] [d1 loss: 0.144491] [d2 loss: 0.178861]  [sq d1 d2: 0.001181]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 420/676] [D loss: -0.003987] [G loss: -0.032433] [d1 loss: 0.102865] [d2 loss: 0.098528]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 440/676] [D loss: -0.015723] [G loss: -0.041572] [d1 loss: 0.070579] [d2 loss: 0.068935]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 460/676] [D loss: -0.003019] [G loss: -0.053548] [d1 loss: 0.059748] [d2 loss: 0.063326]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 480/676] [D loss: -0.011841] [G loss: -0.048228] [d1 loss: 0.099967] [d2 loss: 0.189041]  [sq d1 d2: 0.007934]  [num0: 16.000000] [num1 48.000000]
[Epoch 342/500] [Batch 500/676] [D loss: -0.004032] [G loss: -0.039242] [d1 loss: 0.103413] [d2 loss: 0.071641]  [sq d1 d2: 0.001009]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 520/676] [D loss: -0.009547] [G loss: -0.058909] [d1 loss: 0.128535] [d2 loss: 0.081024]  [sq d1 d2: 0.002257]  [num0: 18.000000] [num1 46.000000]
[Epoch 342/500] [Batch 540/676] [D loss: -0.001487] [G loss: -0.048564] [d1 loss: 0.043310] [d2 loss: 0.064612]  [sq d1 d2: 0.000454]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 560/676] [D loss: -0.006524] [G loss: -0.059523] [d1 loss: 0.061131] [d2 loss: 0.054084]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 342/500] [Batch 580/676] [D loss: -0.013577] [G loss: -0.032795] [d1 loss: 0.043711] [d2 loss: 0.032071]  [sq d1 d2: 0.000135]  [num0: 12.000000] [num1 52.000000]
[Epoch 342/500] [Batch 600/676] [D loss: -0.011295] [G loss: -0.059846] [d1 loss: 0.134546] [d2 loss: 0.096489]  [sq d1 d2: 0.001448]  [num0: 14.000000] [num1 50.000000]
[Epoch 342/500] [Batch 620/676] [D loss: -0.003341] [G loss: -0.064273] [d1 loss: 0.122200] [d2 loss: 0.138465]  [sq d1 d2: 0.000265]  [num0: 18.000000] [num1 46.000000]
[Epoch 342/500] [Batch 640/676] [D loss: -0.009732] [G loss: -0.068650] [d1 loss: 0.106146] [d2 loss: 0.113405]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 342/500] [Batch 660/676] [D loss: -0.002087] [G loss: -0.078103] [d1 loss: 0.112176] [d2 loss: 0.114011]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 0/676] [D loss: -0.002427] [G loss: -0.085401] [d1 loss: 0.153232] [d2 loss: 0.144187]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 20/676] [D loss: -0.012532] [G loss: -0.091033] [d1 loss: 0.071253] [d2 loss: 0.063300]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 40/676] [D loss: -0.001917] [G loss: -0.091835] [d1 loss: 0.051857] [d2 loss: 0.056549]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 343/500] [Batch 60/676] [D loss: -0.008707] [G loss: -0.089749] [d1 loss: 0.127307] [d2 loss: 0.148436]  [sq d1 d2: 0.000446]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 80/676] [D loss: -0.011801] [G loss: -0.082833] [d1 loss: 0.102043] [d2 loss: 0.108226]  [sq d1 d2: 0.000038]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 100/676] [D loss: -0.012611] [G loss: -0.084091] [d1 loss: 0.045695] [d2 loss: 0.047864]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 120/676] [D loss: -0.003317] [G loss: -0.106641] [d1 loss: 0.079745] [d2 loss: 0.090430]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 140/676] [D loss: -0.008793] [G loss: -0.118781] [d1 loss: 0.223393] [d2 loss: 0.314321]  [sq d1 d2: 0.008268]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 160/676] [D loss: -0.014248] [G loss: -0.087698] [d1 loss: 0.152658] [d2 loss: 0.231723]  [sq d1 d2: 0.006251]  [num0: 19.000000] [num1 45.000000]
[Epoch 343/500] [Batch 180/676] [D loss: -0.007127] [G loss: -0.109951] [d1 loss: 0.120536] [d2 loss: 0.098999]  [sq d1 d2: 0.000464]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 200/676] [D loss: 0.001702] [G loss: -0.089897] [d1 loss: 0.053025] [d2 loss: 0.071836]  [sq d1 d2: 0.000354]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 220/676] [D loss: 0.003375] [G loss: -0.088518] [d1 loss: 0.197974] [d2 loss: 0.218422]  [sq d1 d2: 0.000418]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 240/676] [D loss: -0.012961] [G loss: -0.111212] [d1 loss: 0.157271] [d2 loss: 0.154929]  [sq d1 d2: 0.000005]  [num0: 21.000000] [num1 43.000000]
[Epoch 343/500] [Batch 260/676] [D loss: -0.010175] [G loss: -0.102882] [d1 loss: 0.058189] [d2 loss: 0.059499]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 280/676] [D loss: -0.022166] [G loss: -0.120091] [d1 loss: 0.072438] [d2 loss: 0.063257]  [sq d1 d2: 0.000084]  [num0: 14.000000] [num1 50.000000]
[Epoch 343/500] [Batch 300/676] [D loss: 0.008577] [G loss: -0.132686] [d1 loss: 0.410398] [d2 loss: 0.345307]  [sq d1 d2: 0.004237]  [num0: 12.000000] [num1 52.000000]
[Epoch 343/500] [Batch 320/676] [D loss: -0.016834] [G loss: -0.147603] [d1 loss: 0.129685] [d2 loss: 0.137093]  [sq d1 d2: 0.000055]  [num0: 18.000000] [num1 46.000000]
[Epoch 343/500] [Batch 340/676] [D loss: -0.029383] [G loss: -0.140085] [d1 loss: 0.046119] [d2 loss: 0.049429]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 360/676] [D loss: 0.013109] [G loss: -0.139662] [d1 loss: 0.147410] [d2 loss: 0.140505]  [sq d1 d2: 0.000048]  [num0: 18.000000] [num1 46.000000]
[Epoch 343/500] [Batch 380/676] [D loss: -0.003561] [G loss: -0.174863] [d1 loss: 0.778025] [d2 loss: 0.613690]  [sq d1 d2: 0.027006]  [num0: 15.000000] [num1 49.000000]
[Epoch 343/500] [Batch 400/676] [D loss: -0.015707] [G loss: -0.154174] [d1 loss: 0.031469] [d2 loss: 0.058409]  [sq d1 d2: 0.000726]  [num0: 18.000000] [num1 46.000000]

[Epoch 343/500] [Batch 420/676] [D loss: -0.001028] [G loss: -0.140863] [d1 loss: 0.094339] [d2 loss: 0.104348]  [sq d1 d2: 0.000100]  [num0: 18.000000] [num1 46.000000]
[Epoch 343/500] [Batch 440/676] [D loss: -0.014599] [G loss: -0.124813] [d1 loss: 0.214100] [d2 loss: 0.217863]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 460/676] [D loss: -0.019465] [G loss: -0.141434] [d1 loss: 0.048929] [d2 loss: 0.048964]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 480/676] [D loss: -0.015504] [G loss: -0.143645] [d1 loss: 0.048516] [d2 loss: 0.049652]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 500/676] [D loss: -0.014238] [G loss: -0.151208] [d1 loss: 0.540964] [d2 loss: 0.403052]  [sq d1 d2: 0.019020]  [num0: 18.000000] [num1 46.000000]
[Epoch 343/500] [Batch 520/676] [D loss: -0.017460] [G loss: -0.158461] [d1 loss: 0.070680] [d2 loss: 0.070070]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 540/676] [D loss: -0.018472] [G loss: -0.173919] [d1 loss: 0.072904] [d2 loss: 0.065161]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 560/676] [D loss: -0.017802] [G loss: -0.168406] [d1 loss: 0.123068] [d2 loss: 0.133266]  [sq d1 d2: 0.000104]  [num0: 16.000000] [num1 48.000000]
[Epoch 343/500] [Batch 580/676] [D loss: -0.000852] [G loss: -0.170669] [d1 loss: 0.119958] [d2 loss: 0.121992]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 343/500] [Batch 600/676] [D loss: -0.015221] [G loss: -0.167174] [d1 loss: 0.044969] [d2 loss: 0.043354]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 343/500] [Batch 620/676] [D loss: 0.008749] [G loss: -0.175396] [d1 loss: 0.072814] [d2 loss: 0.070061]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 640/676] [D loss: -0.013219] [G loss: -0.174453] [d1 loss: 0.070598] [d2 loss: 0.073896]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 343/500] [Batch 660/676] [D loss: -0.007646] [G loss: -0.150242] [d1 loss: 0.048548] [d2 loss: 0.044079]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 344/500] [Batch 0/676] [D loss: 0.001721] [G loss: -0.134519] [d1 loss: 0.084288] [d2 loss: 0.080404]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 20/676] [D loss: -0.010843] [G loss: -0.124543] [d1 loss: 0.127281] [d2 loss: 0.124528]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 40/676] [D loss: -0.010206] [G loss: -0.092675] [d1 loss: 0.050732] [d2 loss: 0.056469]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 60/676] [D loss: -0.011328] [G loss: -0.069888] [d1 loss: 0.084055] [d2 loss: 0.140576]  [sq d1 d2: 0.003195]  [num0: 18.000000] [num1 46.000000]
[Epoch 344/500] [Batch 80/676] [D loss: -0.011294] [G loss: -0.063995] [d1 loss: 0.066410] [d2 loss: 0.086270]  [sq d1 d2: 0.000394]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 100/676] [D loss: -0.011055] [G loss: -0.061694] [d1 loss: 0.095653] [d2 loss: 0.104796]  [sq d1 d2: 0.000084]  [num0: 13.000000] [num1 51.000000]
[Epoch 344/500] [Batch 120/676] [D loss: -0.009790] [G loss: -0.030433] [d1 loss: 0.038787] [d2 loss: 0.043391]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 140/676] [D loss: -0.020664] [G loss: -0.058601] [d1 loss: 0.096116] [d2 loss: 0.078850]  [sq d1 d2: 0.000298]  [num0: 18.000000] [num1 46.000000]
[Epoch 344/500] [Batch 160/676] [D loss: 0.012879] [G loss: -0.070818] [d1 loss: 0.104190] [d2 loss: 0.116040]  [sq d1 d2: 0.000140]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 180/676] [D loss: -0.003853] [G loss: -0.047676] [d1 loss: 0.118285] [d2 loss: 0.095357]  [sq d1 d2: 0.000526]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 200/676] [D loss: -0.004198] [G loss: -0.069891] [d1 loss: 0.038638] [d2 loss: 0.048878]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 220/676] [D loss: 0.002985] [G loss: -0.066090] [d1 loss: 0.036431] [d2 loss: 0.046496]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 344/500] [Batch 240/676] [D loss: -0.003175] [G loss: -0.054109] [d1 loss: 0.126584] [d2 loss: 0.104354]  [sq d1 d2: 0.000494]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 260/676] [D loss: -0.001606] [G loss: -0.053965] [d1 loss: 0.045539] [d2 loss: 0.052085]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 280/676] [D loss: -0.014385] [G loss: -0.068776] [d1 loss: 0.205446] [d2 loss: 0.260869]  [sq d1 d2: 0.003072]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 300/676] [D loss: -0.014034] [G loss: -0.051314] [d1 loss: 0.079661] [d2 loss: 0.066682]  [sq d1 d2: 0.000168]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 320/676] [D loss: -0.014511] [G loss: -0.040984] [d1 loss: 0.167828] [d2 loss: 0.242179]  [sq d1 d2: 0.005528]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 340/676] [D loss: 0.000580] [G loss: -0.053638] [d1 loss: 0.089760] [d2 loss: 0.098806]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 360/676] [D loss: -0.002691] [G loss: -0.054374] [d1 loss: 0.053937] [d2 loss: 0.059399]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 344/500] [Batch 380/676] [D loss: -0.003224] [G loss: -0.058138] [d1 loss: 0.099395] [d2 loss: 0.100001]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 400/676] [D loss: -0.018470] [G loss: -0.080930] [d1 loss: 0.091076] [d2 loss: 0.105114]  [sq d1 d2: 0.000197]  [num0: 17.000000] [num1 47.000000]
[Epoch 344/500] [Batch 420/676] [D loss: -0.004649] [G loss: -0.080379] [d1 loss: 0.115979] [d2 loss: 0.140764]  [sq d1 d2: 0.000614]  [num0: 17.000000] [num1 47.000000]
[Epoch 344/500] [Batch 440/676] [D loss: -0.012617] [G loss: -0.077715] [d1 loss: 0.044970] [d2 loss: 0.050074]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 344/500] [Batch 460/676] [D loss: -0.000551] [G loss: -0.063949] [d1 loss: 0.051684] [d2 loss: 0.064855]  [sq d1 d2: 0.000173]  [num0: 15.000000] [num1 49.000000]
[Epoch 344/500] [Batch 480/676] [D loss: 0.001778] [G loss: -0.037472] [d1 loss: 0.077150] [d2 loss: 0.115387]  [sq d1 d2: 0.001462]  [num0: 13.000000] [num1 51.000000]
[Epoch 344/500] [Batch 500/676] [D loss: -0.011015] [G loss: -0.038044] [d1 loss: 0.033062] [d2 loss: 0.031804]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 520/676] [D loss: 0.003781] [G loss: -0.056154] [d1 loss: 0.047250] [d2 loss: 0.052173]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 540/676] [D loss: -0.015938] [G loss: -0.072938] [d1 loss: 0.101164] [d2 loss: 0.108476]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 560/676] [D loss: -0.003287] [G loss: -0.109296] [d1 loss: 0.144723] [d2 loss: 0.129055]  [sq d1 d2: 0.000245]  [num0: 18.000000] [num1 46.000000]
[Epoch 344/500] [Batch 580/676] [D loss: -0.010920] [G loss: -0.084439] [d1 loss: 0.076127] [d2 loss: 0.065797]  [sq d1 d2: 0.000107]  [num0: 17.000000] [num1 47.000000]
[Epoch 344/500] [Batch 600/676] [D loss: 0.000778] [G loss: -0.160697] [d1 loss: 0.103006] [d2 loss: 0.110404]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 344/500] [Batch 620/676] [D loss: -0.025745] [G loss: -0.198751] [d1 loss: 0.155628] [d2 loss: 0.114441]  [sq d1 d2: 0.001696]  [num0: 14.000000] [num1 50.000000]
[Epoch 344/500] [Batch 640/676] [D loss: -0.008452] [G loss: -0.222573] [d1 loss: 0.047640] [d2 loss: 0.050333]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 344/500] [Batch 660/676] [D loss: -0.011367] [G loss: -0.231154] [d1 loss: 0.107901] [d2 loss: 0.096733]  [sq d1 d2: 0.000125]  [num0: 18.000000] [num1 46.000000]
[Epoch 345/500] [Batch 0/676] [D loss: -0.018452] [G loss: -0.220655] [d1 loss: 0.088763] [d2 loss: 0.084820]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 20/676] [D loss: 0.003899] [G loss: -0.220719] [d1 loss: 0.062944] [d2 loss: 0.099455]  [sq d1 d2: 0.001333]  [num0: 14.000000] [num1 50.000000]
[Epoch 345/500] [Batch 40/676] [D loss: 0.003958] [G loss: -0.229726] [d1 loss: 0.146687] [d2 loss: 0.176711]  [sq d1 d2: 0.000901]  [num0: 15.000000] [num1 49.000000]

[Epoch 345/500] [Batch 60/676] [D loss: -0.012386] [G loss: -0.255727] [d1 loss: 0.042946] [d2 loss: 0.047513]  [sq d1 d2: 0.000021]  [num0: 12.000000] [num1 52.000000]
[Epoch 345/500] [Batch 80/676] [D loss: -0.016004] [G loss: -0.258425] [d1 loss: 0.082434] [d2 loss: 0.097871]  [sq d1 d2: 0.000238]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 100/676] [D loss: -0.009084] [G loss: -0.228902] [d1 loss: 0.095039] [d2 loss: 0.093418]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 120/676] [D loss: -0.001483] [G loss: -0.241501] [d1 loss: 0.093175] [d2 loss: 0.089631]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 140/676] [D loss: 0.006233] [G loss: -0.214069] [d1 loss: 0.122944] [d2 loss: 0.109655]  [sq d1 d2: 0.000177]  [num0: 14.000000] [num1 50.000000]
[Epoch 345/500] [Batch 160/676] [D loss: -0.008031] [G loss: -0.215294] [d1 loss: 0.166639] [d2 loss: 0.140577]  [sq d1 d2: 0.000679]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 180/676] [D loss: 0.009780] [G loss: -0.230288] [d1 loss: 0.163632] [d2 loss: 0.156016]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 345/500] [Batch 200/676] [D loss: 0.004537] [G loss: -0.192457] [d1 loss: 0.236425] [d2 loss: 0.245215]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 220/676] [D loss: 0.007539] [G loss: -0.150218] [d1 loss: 0.070645] [d2 loss: 0.081667]  [sq d1 d2: 0.000121]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 240/676] [D loss: -0.001975] [G loss: -0.107610] [d1 loss: 0.095725] [d2 loss: 0.103260]  [sq d1 d2: 0.000057]  [num0: 13.000000] [num1 51.000000]
[Epoch 345/500] [Batch 260/676] [D loss: -0.007969] [G loss: -0.075234] [d1 loss: 0.094280] [d2 loss: 0.100182]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 280/676] [D loss: -0.001203] [G loss: -0.069398] [d1 loss: 0.122301] [d2 loss: 0.114072]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 345/500] [Batch 300/676] [D loss: -0.003380] [G loss: -0.068139] [d1 loss: 0.142258] [d2 loss: 0.123317]  [sq d1 d2: 0.000359]  [num0: 18.000000] [num1 46.000000]
[Epoch 345/500] [Batch 320/676] [D loss: -0.026570] [G loss: -0.013906] [d1 loss: 0.119544] [d2 loss: 0.143666]  [sq d1 d2: 0.000582]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 340/676] [D loss: -0.006797] [G loss: -0.013188] [d1 loss: 0.231403] [d2 loss: 0.237371]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 345/500] [Batch 360/676] [D loss: -0.011777] [G loss: -0.039862] [d1 loss: 0.122645] [d2 loss: 0.135146]  [sq d1 d2: 0.000156]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 380/676] [D loss: 0.002480] [G loss: -0.044377] [d1 loss: 0.026608] [d2 loss: 0.025674]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 345/500] [Batch 400/676] [D loss: -0.006313] [G loss: -0.045811] [d1 loss: 0.056284] [d2 loss: 0.050171]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 345/500] [Batch 420/676] [D loss: 0.004171] [G loss: -0.037351] [d1 loss: 0.073586] [d2 loss: 0.071970]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 345/500] [Batch 440/676] [D loss: -0.001802] [G loss: -0.047852] [d1 loss: 0.120302] [d2 loss: 0.055718]  [sq d1 d2: 0.004171]  [num0: 15.000000] [num1 49.000000]
[Epoch 345/500] [Batch 460/676] [D loss: -0.003068] [G loss: -0.056137] [d1 loss: 0.037326] [d2 loss: 0.038566]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 480/676] [D loss: 0.002916] [G loss: -0.063693] [d1 loss: 0.117069] [d2 loss: 0.122822]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 345/500] [Batch 500/676] [D loss: 0.006726] [G loss: -0.101870] [d1 loss: 0.040600] [d2 loss: 0.035482]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 345/500] [Batch 520/676] [D loss: -0.033189] [G loss: -0.091928] [d1 loss: 0.144345] [d2 loss: 0.169389]  [sq d1 d2: 0.000627]  [num0: 15.000000] [num1 49.000000]
[Epoch 345/500] [Batch 540/676] [D loss: -0.011725] [G loss: -0.112961] [d1 loss: 0.056784] [d2 loss: 0.055016]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 345/500] [Batch 560/676] [D loss: -0.032331] [G loss: -0.136386] [d1 loss: 0.057311] [d2 loss: 0.050400]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 345/500] [Batch 580/676] [D loss: -0.008521] [G loss: -0.126532] [d1 loss: 0.099802] [d2 loss: 0.117830]  [sq d1 d2: 0.000325]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 600/676] [D loss: -0.021071] [G loss: -0.105760] [d1 loss: 0.076977] [d2 loss: 0.079565]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 345/500] [Batch 620/676] [D loss: -0.010060] [G loss: -0.104241] [d1 loss: 0.268074] [d2 loss: 0.232224]  [sq d1 d2: 0.001285]  [num0: 16.000000] [num1 48.000000]
[Epoch 345/500] [Batch 640/676] [D loss: -0.009323] [G loss: -0.062173] [d1 loss: 0.122534] [d2 loss: 0.116879]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 345/500] [Batch 660/676] [D loss: -0.007218] [G loss: -0.025260] [d1 loss: 0.056191] [d2 loss: 0.064646]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 0/676] [D loss: 0.009361] [G loss: -0.010725] [d1 loss: 0.090736] [d2 loss: 0.091381]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 346/500] [Batch 20/676] [D loss: -0.003559] [G loss: 0.042323] [d1 loss: 0.090046] [d2 loss: 0.074207]  [sq d1 d2: 0.000251]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 40/676] [D loss: -0.019822] [G loss: 0.083423] [d1 loss: 0.198774] [d2 loss: 0.226638]  [sq d1 d2: 0.000776]  [num0: 17.000000] [num1 47.000000]
[Epoch 346/500] [Batch 60/676] [D loss: 0.005231] [G loss: 0.073692] [d1 loss: 0.084907] [d2 loss: 0.080868]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 346/500] [Batch 80/676] [D loss: -0.020749] [G loss: 0.060225] [d1 loss: 0.148562] [d2 loss: 0.133610]  [sq d1 d2: 0.000224]  [num0: 13.000000] [num1 51.000000]
[Epoch 346/500] [Batch 100/676] [D loss: -0.011175] [G loss: 0.066206] [d1 loss: 0.045835] [d2 loss: 0.047723]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 120/676] [D loss: -0.032989] [G loss: 0.054659] [d1 loss: 0.066455] [d2 loss: 0.073350]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 140/676] [D loss: -0.017903] [G loss: 0.045661] [d1 loss: 0.078126] [d2 loss: 0.105804]  [sq d1 d2: 0.000766]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 160/676] [D loss: -0.003387] [G loss: -0.004202] [d1 loss: 0.065619] [d2 loss: 0.069648]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 346/500] [Batch 180/676] [D loss: -0.016035] [G loss: -0.011088] [d1 loss: 0.043990] [d2 loss: 0.048254]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 200/676] [D loss: 0.007764] [G loss: -0.020916] [d1 loss: 0.115851] [d2 loss: 0.105061]  [sq d1 d2: 0.000116]  [num0: 17.000000] [num1 47.000000]
[Epoch 346/500] [Batch 220/676] [D loss: 0.004269] [G loss: -0.062222] [d1 loss: 0.076373] [d2 loss: 0.071288]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 240/676] [D loss: 0.003080] [G loss: -0.092453] [d1 loss: 0.130085] [d2 loss: 0.134108]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 346/500] [Batch 260/676] [D loss: -0.015003] [G loss: -0.109847] [d1 loss: 0.030389] [d2 loss: 0.039557]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 280/676] [D loss: -0.007950] [G loss: -0.144313] [d1 loss: 0.167594] [d2 loss: 0.167517]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 300/676] [D loss: -0.026250] [G loss: -0.184171] [d1 loss: 0.037468] [d2 loss: 0.034667]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 320/676] [D loss: -0.031096] [G loss: -0.232990] [d1 loss: 0.462396] [d2 loss: 0.334492]  [sq d1 d2: 0.016360]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 340/676] [D loss: 0.000121] [G loss: -0.309562] [d1 loss: 0.092957] [d2 loss: 0.074330]  [sq d1 d2: 0.000347]  [num0: 16.000000] [num1 48.000000]
[Epoch 346/500] [Batch 360/676] [D loss: 0.003911] [G loss: -0.344283] [d1 loss: 0.080217] [d2 loss: 0.071262]  [sq d1 d2: 0.000080]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 380/676] [D loss: 0.003552] [G loss: -0.347306] [d1 loss: 0.095226] [d2 loss: 0.096969]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 346/500] [Batch 400/676] [D loss: -0.001601] [G loss: -0.357839] [d1 loss: 0.133230] [d2 loss: 0.157586]  [sq d1 d2: 0.000593]  [num0: 21.000000] [num1 43.000000]

[Epoch 346/500] [Batch 420/676] [D loss: 0.004363] [G loss: -0.323715] [d1 loss: 0.139820] [d2 loss: 0.116175]  [sq d1 d2: 0.000559]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 440/676] [D loss: -0.007520] [G loss: -0.287381] [d1 loss: 0.060041] [d2 loss: 0.075079]  [sq d1 d2: 0.000226]  [num0: 17.000000] [num1 47.000000]
[Epoch 346/500] [Batch 460/676] [D loss: -0.012354] [G loss: -0.224370] [d1 loss: 0.087305] [d2 loss: 0.090762]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 346/500] [Batch 480/676] [D loss: 0.000693] [G loss: -0.203634] [d1 loss: 0.081879] [d2 loss: 0.085022]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 346/500] [Batch 500/676] [D loss: -0.002932] [G loss: -0.152328] [d1 loss: 0.101770] [d2 loss: 0.092057]  [sq d1 d2: 0.000094]  [num0: 17.000000] [num1 47.000000]
[Epoch 346/500] [Batch 520/676] [D loss: 0.000888] [G loss: -0.129889] [d1 loss: 0.119612] [d2 loss: 0.116140]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 346/500] [Batch 540/676] [D loss: -0.015170] [G loss: -0.086879] [d1 loss: 0.127276] [d2 loss: 0.139865]  [sq d1 d2: 0.000158]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 560/676] [D loss: -0.022574] [G loss: -0.084150] [d1 loss: 0.102979] [d2 loss: 0.141444]  [sq d1 d2: 0.001480]  [num0: 14.000000] [num1 50.000000]
[Epoch 346/500] [Batch 580/676] [D loss: -0.005900] [G loss: -0.104656] [d1 loss: 0.085904] [d2 loss: 0.111260]  [sq d1 d2: 0.000643]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 600/676] [D loss: -0.023293] [G loss: -0.088250] [d1 loss: 0.080103] [d2 loss: 0.065573]  [sq d1 d2: 0.000211]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 620/676] [D loss: -0.000641] [G loss: -0.085315] [d1 loss: 0.094987] [d2 loss: 0.091179]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 346/500] [Batch 640/676] [D loss: -0.019574] [G loss: -0.054759] [d1 loss: 0.075002] [d2 loss: 0.075425]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 346/500] [Batch 660/676] [D loss: 0.015254] [G loss: -0.073149] [d1 loss: 0.099411] [d2 loss: 0.096265]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 0/676] [D loss: -0.003273] [G loss: -0.067709] [d1 loss: 0.099741] [d2 loss: 0.103293]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 347/500] [Batch 20/676] [D loss: -0.004012] [G loss: -0.107249] [d1 loss: 0.124098] [d2 loss: 0.159132]  [sq d1 d2: 0.001227]  [num0: 14.000000] [num1 50.000000]
[Epoch 347/500] [Batch 40/676] [D loss: -0.009158] [G loss: -0.090088] [d1 loss: 0.115558] [d2 loss: 0.101000]  [sq d1 d2: 0.000212]  [num0: 17.000000] [num1 47.000000]
[Epoch 347/500] [Batch 60/676] [D loss: -0.005128] [G loss: -0.075451] [d1 loss: 0.078663] [d2 loss: 0.081657]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 347/500] [Batch 80/676] [D loss: -0.013077] [G loss: -0.074817] [d1 loss: 0.073192] [d2 loss: 0.096356]  [sq d1 d2: 0.000537]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 100/676] [D loss: -0.010101] [G loss: -0.131788] [d1 loss: 0.106727] [d2 loss: 0.136341]  [sq d1 d2: 0.000877]  [num0: 17.000000] [num1 47.000000]
[Epoch 347/500] [Batch 120/676] [D loss: -0.018413] [G loss: -0.159789] [d1 loss: 0.042513] [d2 loss: 0.048237]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 140/676] [D loss: -0.007423] [G loss: -0.180033] [d1 loss: 0.115009] [d2 loss: 0.102006]  [sq d1 d2: 0.000169]  [num0: 14.000000] [num1 50.000000]
[Epoch 347/500] [Batch 160/676] [D loss: -0.004361] [G loss: -0.219414] [d1 loss: 0.045133] [d2 loss: 0.051429]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 347/500] [Batch 180/676] [D loss: -0.019802] [G loss: -0.237194] [d1 loss: 0.047879] [d2 loss: 0.102519]  [sq d1 d2: 0.002986]  [num0: 14.000000] [num1 50.000000]
[Epoch 347/500] [Batch 200/676] [D loss: -0.010121] [G loss: -0.280531] [d1 loss: 0.106092] [d2 loss: 0.113329]  [sq d1 d2: 0.000052]  [num0: 20.000000] [num1 44.000000]
[Epoch 347/500] [Batch 220/676] [D loss: 0.015480] [G loss: -0.222823] [d1 loss: 0.073409] [d2 loss: 0.069401]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 347/500] [Batch 240/676] [D loss: 0.030521] [G loss: -0.158340] [d1 loss: 0.059074] [d2 loss: 0.066016]  [sq d1 d2: 0.000048]  [num0: 11.000000] [num1 53.000000]
[Epoch 347/500] [Batch 260/676] [D loss: 0.002206] [G loss: -0.136378] [d1 loss: 0.128400] [d2 loss: 0.134382]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 347/500] [Batch 280/676] [D loss: -0.004928] [G loss: -0.079595] [d1 loss: 0.075978] [d2 loss: 0.074595]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 300/676] [D loss: -0.014131] [G loss: -0.040869] [d1 loss: 0.068383] [d2 loss: 0.058739]  [sq d1 d2: 0.000093]  [num0: 14.000000] [num1 50.000000]
[Epoch 347/500] [Batch 320/676] [D loss: -0.023211] [G loss: -0.003441] [d1 loss: 0.035345] [d2 loss: 0.024237]  [sq d1 d2: 0.000123]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 340/676] [D loss: 0.007679] [G loss: 0.048390] [d1 loss: 0.098621] [d2 loss: 0.099295]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 347/500] [Batch 360/676] [D loss: -0.046107] [G loss: 0.101888] [d1 loss: 0.092687] [d2 loss: 0.085468]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 380/676] [D loss: -0.036678] [G loss: 0.112732] [d1 loss: 0.104586] [d2 loss: 0.093919]  [sq d1 d2: 0.000114]  [num0: 13.000000] [num1 51.000000]
[Epoch 347/500] [Batch 400/676] [D loss: 0.002443] [G loss: 0.135430] [d1 loss: 0.050444] [d2 loss: 0.047033]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 420/676] [D loss: 0.001996] [G loss: 0.130656] [d1 loss: 0.198825] [d2 loss: 0.134752]  [sq d1 d2: 0.004105]  [num0: 18.000000] [num1 46.000000]
[Epoch 347/500] [Batch 440/676] [D loss: 0.000139] [G loss: 0.120990] [d1 loss: 0.073722] [d2 loss: 0.077412]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 460/676] [D loss: 0.011554] [G loss: 0.115915] [d1 loss: 0.060457] [d2 loss: 0.046901]  [sq d1 d2: 0.000184]  [num0: 18.000000] [num1 46.000000]
[Epoch 347/500] [Batch 480/676] [D loss: -0.000661] [G loss: 0.078597] [d1 loss: 0.040484] [d2 loss: 0.038670]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 500/676] [D loss: 0.001047] [G loss: 0.067870] [d1 loss: 0.084283] [d2 loss: 0.066113]  [sq d1 d2: 0.000330]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 520/676] [D loss: -0.003576] [G loss: 0.054964] [d1 loss: 0.082816] [d2 loss: 0.078103]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 347/500] [Batch 540/676] [D loss: -0.020754] [G loss: 0.063360] [d1 loss: 0.163406] [d2 loss: 0.080580]  [sq d1 d2: 0.006860]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 560/676] [D loss: -0.013151] [G loss: 0.038668] [d1 loss: 0.065568] [d2 loss: 0.082724]  [sq d1 d2: 0.000294]  [num0: 18.000000] [num1 46.000000]
[Epoch 347/500] [Batch 580/676] [D loss: -0.022033] [G loss: 0.019668] [d1 loss: 0.055199] [d2 loss: 0.075355]  [sq d1 d2: 0.000406]  [num0: 12.000000] [num1 52.000000]
[Epoch 347/500] [Batch 600/676] [D loss: -0.023322] [G loss: -0.006083] [d1 loss: 0.043533] [d2 loss: 0.055401]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 347/500] [Batch 620/676] [D loss: -0.004478] [G loss: -0.039446] [d1 loss: 0.048477] [d2 loss: 0.064653]  [sq d1 d2: 0.000262]  [num0: 18.000000] [num1 46.000000]
[Epoch 347/500] [Batch 640/676] [D loss: -0.027094] [G loss: -0.066893] [d1 loss: 0.077549] [d2 loss: 0.071969]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 347/500] [Batch 660/676] [D loss: -0.004058] [G loss: -0.134231] [d1 loss: 0.066323] [d2 loss: 0.062343]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 0/676] [D loss: 0.001272] [G loss: -0.153242] [d1 loss: 0.029911] [d2 loss: 0.025532]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 348/500] [Batch 20/676] [D loss: 0.004827] [G loss: -0.150139] [d1 loss: 0.121887] [d2 loss: 0.148710]  [sq d1 d2: 0.000719]  [num0: 13.000000] [num1 51.000000]
[Epoch 348/500] [Batch 40/676] [D loss: 0.002301] [G loss: -0.160954] [d1 loss: 0.056427] [d2 loss: 0.067148]  [sq d1 d2: 0.000115]  [num0: 17.000000] [num1 47.000000]
[Epoch 348/500] [Batch 60/676] [D loss: 0.004162] [G loss: -0.163482] [d1 loss: 0.120652] [d2 loss: 0.137725]  [sq d1 d2: 0.000291]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 80/676] [D loss: -0.008149] [G loss: -0.162890] [d1 loss: 0.152127] [d2 loss: 0.171035]  [sq d1 d2: 0.000358]  [num0: 16.000000] [num1 48.000000]

[Epoch 348/500] [Batch 100/676] [D loss: -0.019202] [G loss: -0.162430] [d1 loss: 0.027013] [d2 loss: 0.022554]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 348/500] [Batch 120/676] [D loss: -0.030807] [G loss: -0.180955] [d1 loss: 0.067978] [d2 loss: 0.088069]  [sq d1 d2: 0.000404]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 140/676] [D loss: -0.028505] [G loss: -0.150122] [d1 loss: 0.035260] [d2 loss: 0.051322]  [sq d1 d2: 0.000258]  [num0: 17.000000] [num1 47.000000]
[Epoch 348/500] [Batch 160/676] [D loss: -0.012009] [G loss: -0.149538] [d1 loss: 0.127382] [d2 loss: 0.140389]  [sq d1 d2: 0.000169]  [num0: 18.000000] [num1 46.000000]
[Epoch 348/500] [Batch 180/676] [D loss: 0.022118] [G loss: -0.145365] [d1 loss: 0.087046] [d2 loss: 0.092984]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 348/500] [Batch 200/676] [D loss: -0.017981] [G loss: -0.174654] [d1 loss: 0.050908] [d2 loss: 0.052278]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 220/676] [D loss: 0.014318] [G loss: -0.106784] [d1 loss: 0.091662] [d2 loss: 0.115017]  [sq d1 d2: 0.000545]  [num0: 12.000000] [num1 52.000000]
[Epoch 348/500] [Batch 240/676] [D loss: -0.006510] [G loss: -0.056924] [d1 loss: 0.082490] [d2 loss: 0.091261]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 348/500] [Batch 260/676] [D loss: 0.012443] [G loss: -0.032163] [d1 loss: 0.105110] [d2 loss: 0.097174]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 280/676] [D loss: -0.003377] [G loss: -0.051739] [d1 loss: 0.379298] [d2 loss: 0.262453]  [sq d1 d2: 0.013653]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 300/676] [D loss: -0.005292] [G loss: -0.043362] [d1 loss: 0.062531] [d2 loss: 0.066482]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 320/676] [D loss: -0.007882] [G loss: -0.038999] [d1 loss: 0.135393] [d2 loss: 0.171769]  [sq d1 d2: 0.001323]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 340/676] [D loss: -0.031250] [G loss: -0.038635] [d1 loss: 0.084303] [d2 loss: 0.067679]  [sq d1 d2: 0.000276]  [num0: 15.000000] [num1 49.000000]
[Epoch 348/500] [Batch 360/676] [D loss: -0.007452] [G loss: -0.066461] [d1 loss: 0.084773] [d2 loss: 0.075525]  [sq d1 d2: 0.000086]  [num0: 18.000000] [num1 46.000000]
[Epoch 348/500] [Batch 380/676] [D loss: -0.013446] [G loss: -0.091881] [d1 loss: 0.076319] [d2 loss: 0.062133]  [sq d1 d2: 0.000201]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 400/676] [D loss: -0.008543] [G loss: -0.125253] [d1 loss: 0.037146] [d2 loss: 0.047997]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 348/500] [Batch 420/676] [D loss: -0.008753] [G loss: -0.130405] [d1 loss: 0.079393] [d2 loss: 0.082764]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 440/676] [D loss: 0.001575] [G loss: -0.130466] [d1 loss: 0.025341] [d2 loss: 0.023629]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 348/500] [Batch 460/676] [D loss: -0.000727] [G loss: -0.134084] [d1 loss: 0.154871] [d2 loss: 0.152540]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 348/500] [Batch 480/676] [D loss: -0.014577] [G loss: -0.136265] [d1 loss: 0.075927] [d2 loss: 0.065787]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 500/676] [D loss: 0.017279] [G loss: -0.080058] [d1 loss: 0.120473] [d2 loss: 0.123204]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 348/500] [Batch 520/676] [D loss: -0.007166] [G loss: -0.070692] [d1 loss: 0.152070] [d2 loss: 0.150853]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 540/676] [D loss: -0.014073] [G loss: -0.044916] [d1 loss: 0.066439] [d2 loss: 0.053697]  [sq d1 d2: 0.000162]  [num0: 14.000000] [num1 50.000000]
[Epoch 348/500] [Batch 560/676] [D loss: -0.034634] [G loss: -0.023786] [d1 loss: 0.028092] [d2 loss: 0.029868]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 348/500] [Batch 580/676] [D loss: -0.009279] [G loss: -0.043127] [d1 loss: 0.086046] [d2 loss: 0.078293]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 348/500] [Batch 600/676] [D loss: -0.039676] [G loss: -0.022007] [d1 loss: 0.082102] [d2 loss: 0.098719]  [sq d1 d2: 0.000276]  [num0: 17.000000] [num1 47.000000]
[Epoch 348/500] [Batch 620/676] [D loss: -0.006062] [G loss: -0.042365] [d1 loss: 0.078156] [d2 loss: 0.131249]  [sq d1 d2: 0.002819]  [num0: 19.000000] [num1 45.000000]
[Epoch 348/500] [Batch 640/676] [D loss: -0.020510] [G loss: -0.060848] [d1 loss: 0.047012] [d2 loss: 0.042633]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 348/500] [Batch 660/676] [D loss: 0.008282] [G loss: -0.068531] [d1 loss: 0.060824] [d2 loss: 0.041401]  [sq d1 d2: 0.000377]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 0/676] [D loss: 0.000560] [G loss: -0.075962] [d1 loss: 0.030295] [d2 loss: 0.028207]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 349/500] [Batch 20/676] [D loss: 0.012168] [G loss: -0.038032] [d1 loss: 0.025444] [d2 loss: 0.038333]  [sq d1 d2: 0.000166]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 40/676] [D loss: -0.000555] [G loss: -0.029012] [d1 loss: 0.067377] [d2 loss: 0.078999]  [sq d1 d2: 0.000135]  [num0: 14.000000] [num1 50.000000]
[Epoch 349/500] [Batch 60/676] [D loss: -0.001148] [G loss: -0.007373] [d1 loss: 0.074933] [d2 loss: 0.073464]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 349/500] [Batch 80/676] [D loss: -0.002283] [G loss: -0.045627] [d1 loss: 0.098648] [d2 loss: 0.099650]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 100/676] [D loss: -0.016726] [G loss: -0.064966] [d1 loss: 0.102137] [d2 loss: 0.110955]  [sq d1 d2: 0.000078]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 120/676] [D loss: -0.025112] [G loss: -0.089337] [d1 loss: 0.024621] [d2 loss: 0.021756]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 349/500] [Batch 140/676] [D loss: -0.011078] [G loss: -0.087938] [d1 loss: 0.165014] [d2 loss: 0.179674]  [sq d1 d2: 0.000215]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 160/676] [D loss: -0.032598] [G loss: -0.130331] [d1 loss: 0.098938] [d2 loss: 0.074645]  [sq d1 d2: 0.000590]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 180/676] [D loss: -0.036917] [G loss: -0.145808] [d1 loss: 0.112012] [d2 loss: 0.120996]  [sq d1 d2: 0.000081]  [num0: 18.000000] [num1 46.000000]
[Epoch 349/500] [Batch 200/676] [D loss: -0.008335] [G loss: -0.170630] [d1 loss: 0.065833] [d2 loss: 0.072492]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 220/676] [D loss: 0.021706] [G loss: -0.177125] [d1 loss: 0.096372] [d2 loss: 0.129592]  [sq d1 d2: 0.001104]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 240/676] [D loss: -0.020872] [G loss: -0.179912] [d1 loss: 0.121437] [d2 loss: 0.120300]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 349/500] [Batch 260/676] [D loss: 0.012915] [G loss: -0.152192] [d1 loss: 0.129000] [d2 loss: 0.101250]  [sq d1 d2: 0.000770]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 280/676] [D loss: 0.017100] [G loss: -0.129463] [d1 loss: 0.053674] [d2 loss: 0.048678]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 300/676] [D loss: 0.000981] [G loss: -0.117293] [d1 loss: 0.101503] [d2 loss: 0.090966]  [sq d1 d2: 0.000111]  [num0: 15.000000] [num1 49.000000]
[Epoch 349/500] [Batch 320/676] [D loss: -0.001267] [G loss: -0.092953] [d1 loss: 0.033729] [d2 loss: 0.046572]  [sq d1 d2: 0.000165]  [num0: 15.000000] [num1 49.000000]
[Epoch 349/500] [Batch 340/676] [D loss: -0.008584] [G loss: -0.077490] [d1 loss: 0.094426] [d2 loss: 0.093429]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 349/500] [Batch 360/676] [D loss: -0.009981] [G loss: -0.068704] [d1 loss: 0.034951] [d2 loss: 0.032156]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 349/500] [Batch 380/676] [D loss: -0.005195] [G loss: -0.065571] [d1 loss: 0.076471] [d2 loss: 0.106038]  [sq d1 d2: 0.000874]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 400/676] [D loss: -0.021522] [G loss: -0.067636] [d1 loss: 0.090989] [d2 loss: 0.093155]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 349/500] [Batch 420/676] [D loss: -0.017244] [G loss: -0.029925] [d1 loss: 0.130123] [d2 loss: 0.138117]  [sq d1 d2: 0.000064]  [num0: 12.000000] [num1 52.000000]
[Epoch 349/500] [Batch 440/676] [D loss: -0.013721] [G loss: -0.011735] [d1 loss: 0.071189] [d2 loss: 0.073460]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]

[Epoch 349/500] [Batch 460/676] [D loss: -0.006204] [G loss: 0.007351] [d1 loss: 0.047117] [d2 loss: 0.052991]  [sq d1 d2: 0.000034]  [num0: 9.000000] [num1 55.000000]
[Epoch 349/500] [Batch 480/676] [D loss: -0.009465] [G loss: 0.006286] [d1 loss: 0.184459] [d2 loss: 0.174694]  [sq d1 d2: 0.000095]  [num0: 16.000000] [num1 48.000000]
[Epoch 349/500] [Batch 500/676] [D loss: 0.002459] [G loss: 0.031749] [d1 loss: 0.079085] [d2 loss: 0.080032]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 349/500] [Batch 520/676] [D loss: 0.001742] [G loss: 0.023807] [d1 loss: 0.064403] [d2 loss: 0.077593]  [sq d1 d2: 0.000174]  [num0: 18.000000] [num1 46.000000]
[Epoch 349/500] [Batch 540/676] [D loss: 0.005895] [G loss: 0.031363] [d1 loss: 0.067081] [d2 loss: 0.070338]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 560/676] [D loss: 0.008795] [G loss: 0.028103] [d1 loss: 0.033074] [d2 loss: 0.025042]  [sq d1 d2: 0.000065]  [num0: 13.000000] [num1 51.000000]
[Epoch 349/500] [Batch 580/676] [D loss: -0.002150] [G loss: 0.018371] [d1 loss: 0.050462] [d2 loss: 0.043978]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 349/500] [Batch 600/676] [D loss: -0.017342] [G loss: 0.018958] [d1 loss: 0.109839] [d2 loss: 0.114382]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 620/676] [D loss: -0.024125] [G loss: -0.002869] [d1 loss: 0.058925] [d2 loss: 0.062579]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 349/500] [Batch 640/676] [D loss: -0.002178] [G loss: -0.000369] [d1 loss: 0.045320] [d2 loss: 0.062558]  [sq d1 d2: 0.000297]  [num0: 11.000000] [num1 53.000000]
[Epoch 349/500] [Batch 660/676] [D loss: -0.033714] [G loss: 0.007184] [d1 loss: 0.053514] [d2 loss: 0.041537]  [sq d1 d2: 0.000143]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 0/676] [D loss: -0.028448] [G loss: 0.013580] [d1 loss: 0.128604] [d2 loss: 0.114399]  [sq d1 d2: 0.000202]  [num0: 14.000000] [num1 50.000000]
[Epoch 350/500] [Batch 20/676] [D loss: -0.024935] [G loss: -0.009384] [d1 loss: 0.084328] [d2 loss: 0.064960]  [sq d1 d2: 0.000375]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 40/676] [D loss: -0.023895] [G loss: -0.034183] [d1 loss: 0.101057] [d2 loss: 0.078114]  [sq d1 d2: 0.000526]  [num0: 19.000000] [num1 45.000000]
[Epoch 350/500] [Batch 60/676] [D loss: 0.003923] [G loss: -0.037737] [d1 loss: 0.112914] [d2 loss: 0.132329]  [sq d1 d2: 0.000377]  [num0: 19.000000] [num1 45.000000]
[Epoch 350/500] [Batch 80/676] [D loss: 0.028839] [G loss: -0.064604] [d1 loss: 0.069611] [d2 loss: 0.072515]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 350/500] [Batch 100/676] [D loss: 0.014715] [G loss: -0.074485] [d1 loss: 0.099571] [d2 loss: 0.109387]  [sq d1 d2: 0.000096]  [num0: 20.000000] [num1 44.000000]
[Epoch 350/500] [Batch 120/676] [D loss: -0.000460] [G loss: -0.064899] [d1 loss: 0.099529] [d2 loss: 0.087897]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 140/676] [D loss: -0.000456] [G loss: -0.077707] [d1 loss: 0.087502] [d2 loss: 0.102792]  [sq d1 d2: 0.000234]  [num0: 17.000000] [num1 47.000000]
[Epoch 350/500] [Batch 160/676] [D loss: -0.008455] [G loss: -0.063775] [d1 loss: 0.082514] [d2 loss: 0.089402]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 180/676] [D loss: -0.018609] [G loss: -0.068683] [d1 loss: 0.096733] [d2 loss: 0.093622]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 350/500] [Batch 200/676] [D loss: -0.040024] [G loss: -0.056589] [d1 loss: 0.077518] [d2 loss: 0.080397]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 350/500] [Batch 220/676] [D loss: -0.038932] [G loss: -0.038094] [d1 loss: 0.078433] [d2 loss: 0.089853]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 240/676] [D loss: -0.022028] [G loss: -0.017923] [d1 loss: 0.191941] [d2 loss: 0.128979]  [sq d1 d2: 0.003964]  [num0: 12.000000] [num1 52.000000]
[Epoch 350/500] [Batch 260/676] [D loss: -0.008604] [G loss: -0.028452] [d1 loss: 0.110816] [d2 loss: 0.118957]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 350/500] [Batch 280/676] [D loss: -0.017555] [G loss: -0.026399] [d1 loss: 0.038374] [d2 loss: 0.035072]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 350/500] [Batch 300/676] [D loss: -0.012522] [G loss: -0.023271] [d1 loss: 0.068446] [d2 loss: 0.098796]  [sq d1 d2: 0.000921]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 320/676] [D loss: 0.003065] [G loss: -0.018017] [d1 loss: 0.088426] [d2 loss: 0.114192]  [sq d1 d2: 0.000664]  [num0: 11.000000] [num1 53.000000]
[Epoch 350/500] [Batch 340/676] [D loss: 0.002658] [G loss: -0.012599] [d1 loss: 0.092710] [d2 loss: 0.098110]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 360/676] [D loss: 0.006585] [G loss: -0.003441] [d1 loss: 0.121685] [d2 loss: 0.133369]  [sq d1 d2: 0.000137]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 380/676] [D loss: 0.003472] [G loss: -0.016420] [d1 loss: 0.080129] [d2 loss: 0.095702]  [sq d1 d2: 0.000243]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 400/676] [D loss: -0.000170] [G loss: -0.037493] [d1 loss: 0.084554] [d2 loss: 0.072405]  [sq d1 d2: 0.000148]  [num0: 13.000000] [num1 51.000000]
[Epoch 350/500] [Batch 420/676] [D loss: -0.004859] [G loss: -0.052924] [d1 loss: 0.285478] [d2 loss: 0.209332]  [sq d1 d2: 0.005798]  [num0: 20.000000] [num1 44.000000]
[Epoch 350/500] [Batch 440/676] [D loss: -0.011417] [G loss: -0.067227] [d1 loss: 0.120042] [d2 loss: 0.096305]  [sq d1 d2: 0.000563]  [num0: 17.000000] [num1 47.000000]
[Epoch 350/500] [Batch 460/676] [D loss: -0.016246] [G loss: -0.071946] [d1 loss: 0.091053] [d2 loss: 0.088287]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 350/500] [Batch 480/676] [D loss: -0.050518] [G loss: -0.091396] [d1 loss: 0.043500] [d2 loss: 0.034205]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 500/676] [D loss: -0.053907] [G loss: -0.138955] [d1 loss: 0.088972] [d2 loss: 0.055934]  [sq d1 d2: 0.001091]  [num0: 14.000000] [num1 50.000000]
[Epoch 350/500] [Batch 520/676] [D loss: -0.021633] [G loss: -0.162681] [d1 loss: 0.121724] [d2 loss: 0.098859]  [sq d1 d2: 0.000523]  [num0: 16.000000] [num1 48.000000]
[Epoch 350/500] [Batch 540/676] [D loss: -0.001285] [G loss: -0.172939] [d1 loss: 0.137682] [d2 loss: 0.112615]  [sq d1 d2: 0.000628]  [num0: 17.000000] [num1 47.000000]
[Epoch 350/500] [Batch 560/676] [D loss: 0.012310] [G loss: -0.182658] [d1 loss: 0.057118] [d2 loss: 0.067888]  [sq d1 d2: 0.000116]  [num0: 18.000000] [num1 46.000000]
[Epoch 350/500] [Batch 580/676] [D loss: 0.000798] [G loss: -0.167889] [d1 loss: 0.060015] [d2 loss: 0.068722]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 600/676] [D loss: -0.002738] [G loss: -0.142997] [d1 loss: 0.107124] [d2 loss: 0.106526]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 350/500] [Batch 620/676] [D loss: 0.002187] [G loss: -0.084535] [d1 loss: 0.060075] [d2 loss: 0.057269]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 350/500] [Batch 640/676] [D loss: -0.000050] [G loss: -0.063707] [d1 loss: 0.128667] [d2 loss: 0.139503]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 350/500] [Batch 660/676] [D loss: -0.010061] [G loss: -0.058592] [d1 loss: 0.115672] [d2 loss: 0.099624]  [sq d1 d2: 0.000258]  [num0: 13.000000] [num1 51.000000]
[Epoch 351/500] [Batch 0/676] [D loss: -0.013023] [G loss: -0.035340] [d1 loss: 0.034254] [d2 loss: 0.027418]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 351/500] [Batch 20/676] [D loss: -0.019960] [G loss: -0.007938] [d1 loss: 0.045500] [d2 loss: 0.044313]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 40/676] [D loss: -0.036451] [G loss: 0.010303] [d1 loss: 0.074140] [d2 loss: 0.095486]  [sq d1 d2: 0.000456]  [num0: 11.000000] [num1 53.000000]
[Epoch 351/500] [Batch 60/676] [D loss: -0.050043] [G loss: 0.057207] [d1 loss: 0.037676] [d2 loss: 0.061968]  [sq d1 d2: 0.000590]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 80/676] [D loss: -0.008596] [G loss: 0.098234] [d1 loss: 0.049545] [d2 loss: 0.043883]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 100/676] [D loss: -0.019015] [G loss: 0.074645] [d1 loss: 0.081176] [d2 loss: 0.095083]  [sq d1 d2: 0.000193]  [num0: 17.000000] [num1 47.000000]
[Epoch 351/500] [Batch 120/676] [D loss: 0.020124] [G loss: 0.111127] [d1 loss: 0.037605] [d2 loss: 0.044186]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]

[Epoch 351/500] [Batch 140/676] [D loss: 0.002657] [G loss: 0.083657] [d1 loss: 0.117745] [d2 loss: 0.129676]  [sq d1 d2: 0.000142]  [num0: 17.000000] [num1 47.000000]
[Epoch 351/500] [Batch 160/676] [D loss: 0.014448] [G loss: 0.057698] [d1 loss: 0.121640] [d2 loss: 0.116357]  [sq d1 d2: 0.000028]  [num0: 12.000000] [num1 52.000000]
[Epoch 351/500] [Batch 180/676] [D loss: 0.009623] [G loss: 0.036099] [d1 loss: 0.058632] [d2 loss: 0.055090]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 351/500] [Batch 200/676] [D loss: 0.015506] [G loss: -0.009911] [d1 loss: 0.060461] [d2 loss: 0.063634]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 351/500] [Batch 220/676] [D loss: 0.005042] [G loss: -0.030468] [d1 loss: 0.084810] [d2 loss: 0.099805]  [sq d1 d2: 0.000225]  [num0: 10.000000] [num1 54.000000]
[Epoch 351/500] [Batch 240/676] [D loss: -0.002465] [G loss: -0.041362] [d1 loss: 0.062866] [d2 loss: 0.067223]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 260/676] [D loss: -0.015453] [G loss: -0.057468] [d1 loss: 0.041427] [d2 loss: 0.040330]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 351/500] [Batch 280/676] [D loss: -0.024893] [G loss: -0.069667] [d1 loss: 0.075601] [d2 loss: 0.066626]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 300/676] [D loss: -0.026588] [G loss: -0.069997] [d1 loss: 0.054049] [d2 loss: 0.055656]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 351/500] [Batch 320/676] [D loss: -0.024889] [G loss: -0.070235] [d1 loss: 0.114611] [d2 loss: 0.112590]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 340/676] [D loss: -0.027103] [G loss: -0.039910] [d1 loss: 0.038903] [d2 loss: 0.054551]  [sq d1 d2: 0.000245]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 360/676] [D loss: 0.002500] [G loss: -0.044708] [d1 loss: 0.079362] [d2 loss: 0.087186]  [sq d1 d2: 0.000061]  [num0: 19.000000] [num1 45.000000]
[Epoch 351/500] [Batch 380/676] [D loss: -0.000570] [G loss: -0.030540] [d1 loss: 0.103466] [d2 loss: 0.099466]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 351/500] [Batch 400/676] [D loss: 0.018649] [G loss: -0.066322] [d1 loss: 0.037175] [d2 loss: 0.058048]  [sq d1 d2: 0.000436]  [num0: 10.000000] [num1 54.000000]
[Epoch 351/500] [Batch 420/676] [D loss: 0.011348] [G loss: -0.031891] [d1 loss: 0.106032] [d2 loss: 0.092352]  [sq d1 d2: 0.000187]  [num0: 13.000000] [num1 51.000000]
[Epoch 351/500] [Batch 440/676] [D loss: 0.002762] [G loss: -0.011552] [d1 loss: 0.038351] [d2 loss: 0.043509]  [sq d1 d2: 0.000027]  [num0: 11.000000] [num1 53.000000]
[Epoch 351/500] [Batch 460/676] [D loss: -0.002980] [G loss: -0.000844] [d1 loss: 0.056337] [d2 loss: 0.085513]  [sq d1 d2: 0.000851]  [num0: 13.000000] [num1 51.000000]
[Epoch 351/500] [Batch 480/676] [D loss: -0.013949] [G loss: 0.001143] [d1 loss: 0.080331] [d2 loss: 0.095406]  [sq d1 d2: 0.000227]  [num0: 20.000000] [num1 44.000000]
[Epoch 351/500] [Batch 500/676] [D loss: -0.014594] [G loss: 0.022230] [d1 loss: 0.091860] [d2 loss: 0.079539]  [sq d1 d2: 0.000152]  [num0: 18.000000] [num1 46.000000]
[Epoch 351/500] [Batch 520/676] [D loss: -0.043219] [G loss: 0.055778] [d1 loss: 0.080746] [d2 loss: 0.091147]  [sq d1 d2: 0.000108]  [num0: 17.000000] [num1 47.000000]
[Epoch 351/500] [Batch 540/676] [D loss: -0.035891] [G loss: 0.056932] [d1 loss: 0.129183] [d2 loss: 0.125797]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 351/500] [Batch 560/676] [D loss: -0.024274] [G loss: 0.060432] [d1 loss: 0.065961] [d2 loss: 0.078748]  [sq d1 d2: 0.000164]  [num0: 18.000000] [num1 46.000000]
[Epoch 351/500] [Batch 580/676] [D loss: -0.019060] [G loss: 0.037615] [d1 loss: 0.102205] [d2 loss: 0.085397]  [sq d1 d2: 0.000283]  [num0: 12.000000] [num1 52.000000]
[Epoch 351/500] [Batch 600/676] [D loss: -0.016072] [G loss: 0.011218] [d1 loss: 0.066792] [d2 loss: 0.075353]  [sq d1 d2: 0.000073]  [num0: 15.000000] [num1 49.000000]
[Epoch 351/500] [Batch 620/676] [D loss: 0.013034] [G loss: 0.012957] [d1 loss: 0.044182] [d2 loss: 0.048567]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 351/500] [Batch 640/676] [D loss: 0.034818] [G loss: 0.000928] [d1 loss: 0.131024] [d2 loss: 0.136302]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 351/500] [Batch 660/676] [D loss: 0.018212] [G loss: -0.008764] [d1 loss: 0.056933] [d2 loss: 0.061020]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 352/500] [Batch 0/676] [D loss: 0.008689] [G loss: 0.004659] [d1 loss: 0.034655] [d2 loss: 0.044779]  [sq d1 d2: 0.000102]  [num0: 18.000000] [num1 46.000000]
[Epoch 352/500] [Batch 20/676] [D loss: 0.000440] [G loss: 0.003692] [d1 loss: 0.110421] [d2 loss: 0.128827]  [sq d1 d2: 0.000339]  [num0: 18.000000] [num1 46.000000]
[Epoch 352/500] [Batch 40/676] [D loss: -0.016012] [G loss: 0.021312] [d1 loss: 0.229485] [d2 loss: 0.154589]  [sq d1 d2: 0.005609]  [num0: 18.000000] [num1 46.000000]
[Epoch 352/500] [Batch 60/676] [D loss: -0.041977] [G loss: 0.020799] [d1 loss: 0.056703] [d2 loss: 0.035232]  [sq d1 d2: 0.000461]  [num0: 12.000000] [num1 52.000000]
[Epoch 352/500] [Batch 80/676] [D loss: -0.078021] [G loss: 0.066926] [d1 loss: 0.058933] [d2 loss: 0.068027]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 100/676] [D loss: -0.097444] [G loss: 0.065768] [d1 loss: 0.083609] [d2 loss: 0.074293]  [sq d1 d2: 0.000087]  [num0: 13.000000] [num1 51.000000]
[Epoch 352/500] [Batch 120/676] [D loss: -0.038497] [G loss: 0.014348] [d1 loss: 0.100686] [d2 loss: 0.088182]  [sq d1 d2: 0.000156]  [num0: 20.000000] [num1 44.000000]
[Epoch 352/500] [Batch 140/676] [D loss: -0.017363] [G loss: -0.019616] [d1 loss: 0.048639] [d2 loss: 0.040771]  [sq d1 d2: 0.000062]  [num0: 13.000000] [num1 51.000000]
[Epoch 352/500] [Batch 160/676] [D loss: 0.032673] [G loss: -0.022193] [d1 loss: 0.047503] [d2 loss: 0.045367]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 180/676] [D loss: 0.053521] [G loss: -0.022744] [d1 loss: 0.262548] [d2 loss: 0.237934]  [sq d1 d2: 0.000606]  [num0: 15.000000] [num1 49.000000]
[Epoch 352/500] [Batch 200/676] [D loss: 0.024858] [G loss: 0.004481] [d1 loss: 0.087990] [d2 loss: 0.112495]  [sq d1 d2: 0.000600]  [num0: 16.000000] [num1 48.000000]
[Epoch 352/500] [Batch 220/676] [D loss: 0.014722] [G loss: 0.021595] [d1 loss: 0.157922] [d2 loss: 0.173560]  [sq d1 d2: 0.000245]  [num0: 15.000000] [num1 49.000000]
[Epoch 352/500] [Batch 240/676] [D loss: 0.002462] [G loss: 0.015689] [d1 loss: 0.044445] [d2 loss: 0.046228]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 260/676] [D loss: -0.005553] [G loss: 0.017451] [d1 loss: 0.084175] [d2 loss: 0.086704]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 280/676] [D loss: -0.026541] [G loss: 0.053707] [d1 loss: 0.028012] [d2 loss: 0.035008]  [sq d1 d2: 0.000049]  [num0: 19.000000] [num1 45.000000]
[Epoch 352/500] [Batch 300/676] [D loss: -0.031485] [G loss: 0.114564] [d1 loss: 0.033702] [d2 loss: 0.029626]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 320/676] [D loss: -0.056215] [G loss: 0.080662] [d1 loss: 0.061738] [d2 loss: 0.057052]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 352/500] [Batch 340/676] [D loss: -0.024437] [G loss: 0.059624] [d1 loss: 0.136414] [d2 loss: 0.142366]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 352/500] [Batch 360/676] [D loss: -0.078237] [G loss: 0.035770] [d1 loss: 0.053867] [d2 loss: 0.054863]  [sq d1 d2: 0.000001]  [num0: 22.000000] [num1 42.000000]
[Epoch 352/500] [Batch 380/676] [D loss: -0.010697] [G loss: 0.004861] [d1 loss: 0.035305] [d2 loss: 0.049593]  [sq d1 d2: 0.000204]  [num0: 19.000000] [num1 45.000000]
[Epoch 352/500] [Batch 400/676] [D loss: -0.000376] [G loss: -0.057268] [d1 loss: 0.086311] [d2 loss: 0.079724]  [sq d1 d2: 0.000043]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 420/676] [D loss: 0.002940] [G loss: -0.140332] [d1 loss: 0.127695] [d2 loss: 0.132322]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 352/500] [Batch 440/676] [D loss: 0.011030] [G loss: -0.141082] [d1 loss: 0.056179] [d2 loss: 0.053313]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 460/676] [D loss: 0.018376] [G loss: -0.098303] [d1 loss: 0.181094] [d2 loss: 0.132215]  [sq d1 d2: 0.002389]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 480/676] [D loss: 0.003862] [G loss: -0.058668] [d1 loss: 0.147368] [d2 loss: 0.129978]  [sq d1 d2: 0.000302]  [num0: 12.000000] [num1 52.000000]

[Epoch 352/500] [Batch 500/676] [D loss: -0.014577] [G loss: -0.029858] [d1 loss: 0.091020] [d2 loss: 0.095696]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 352/500] [Batch 520/676] [D loss: -0.038979] [G loss: -0.010636] [d1 loss: 0.108326] [d2 loss: 0.143362]  [sq d1 d2: 0.001228]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 540/676] [D loss: -0.036886] [G loss: -0.034381] [d1 loss: 0.079216] [d2 loss: 0.076132]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 352/500] [Batch 560/676] [D loss: -0.065909] [G loss: -0.041321] [d1 loss: 0.099130] [d2 loss: 0.113020]  [sq d1 d2: 0.000193]  [num0: 18.000000] [num1 46.000000]
[Epoch 352/500] [Batch 580/676] [D loss: -0.070585] [G loss: -0.030856] [d1 loss: 0.044958] [d2 loss: 0.050315]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 352/500] [Batch 600/676] [D loss: -0.051762] [G loss: -0.057458] [d1 loss: 0.064343] [d2 loss: 0.060832]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 352/500] [Batch 620/676] [D loss: -0.062484] [G loss: -0.145179] [d1 loss: 0.055506] [d2 loss: 0.059646]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 640/676] [D loss: 0.014042] [G loss: -0.097736] [d1 loss: 0.119360] [d2 loss: 0.114554]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 352/500] [Batch 660/676] [D loss: 0.066278] [G loss: -0.063697] [d1 loss: 0.084998] [d2 loss: 0.068647]  [sq d1 d2: 0.000267]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 0/676] [D loss: 0.023979] [G loss: -0.064181] [d1 loss: 0.129214] [d2 loss: 0.134012]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 20/676] [D loss: 0.016191] [G loss: -0.027775] [d1 loss: 0.094816] [d2 loss: 0.108618]  [sq d1 d2: 0.000190]  [num0: 14.000000] [num1 50.000000]
[Epoch 353/500] [Batch 40/676] [D loss: 0.004176] [G loss: -0.026753] [d1 loss: 0.042404] [d2 loss: 0.037301]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 353/500] [Batch 60/676] [D loss: -0.002901] [G loss: -0.046094] [d1 loss: 0.057430] [d2 loss: 0.052664]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 80/676] [D loss: -0.015429] [G loss: -0.044458] [d1 loss: 0.100848] [d2 loss: 0.112186]  [sq d1 d2: 0.000129]  [num0: 18.000000] [num1 46.000000]
[Epoch 353/500] [Batch 100/676] [D loss: -0.026535] [G loss: -0.030254] [d1 loss: 0.092920] [d2 loss: 0.098633]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 120/676] [D loss: -0.053526] [G loss: -0.014140] [d1 loss: 0.097030] [d2 loss: 0.095633]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 353/500] [Batch 140/676] [D loss: -0.010915] [G loss: 0.033920] [d1 loss: 0.051905] [d2 loss: 0.049245]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 353/500] [Batch 160/676] [D loss: -0.070614] [G loss: 0.012871] [d1 loss: 0.071352] [d2 loss: 0.073172]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 353/500] [Batch 180/676] [D loss: -0.026439] [G loss: -0.010366] [d1 loss: 0.260106] [d2 loss: 0.239696]  [sq d1 d2: 0.000417]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 200/676] [D loss: -0.006676] [G loss: -0.016481] [d1 loss: 0.047659] [d2 loss: 0.048209]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 353/500] [Batch 220/676] [D loss: -0.030151] [G loss: -0.054619] [d1 loss: 0.080098] [d2 loss: 0.080483]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 240/676] [D loss: 0.035215] [G loss: -0.087546] [d1 loss: 0.095431] [d2 loss: 0.105023]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 260/676] [D loss: -0.010624] [G loss: -0.124154] [d1 loss: 0.075129] [d2 loss: 0.058656]  [sq d1 d2: 0.000271]  [num0: 19.000000] [num1 45.000000]
[Epoch 353/500] [Batch 280/676] [D loss: 0.005855] [G loss: -0.124621] [d1 loss: 0.111310] [d2 loss: 0.099709]  [sq d1 d2: 0.000135]  [num0: 17.000000] [num1 47.000000]
[Epoch 353/500] [Batch 300/676] [D loss: 0.010141] [G loss: -0.089745] [d1 loss: 0.086113] [d2 loss: 0.094244]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 320/676] [D loss: 0.000714] [G loss: -0.093114] [d1 loss: 0.021720] [d2 loss: 0.023515]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 340/676] [D loss: -0.014657] [G loss: -0.079823] [d1 loss: 0.058057] [d2 loss: 0.070134]  [sq d1 d2: 0.000146]  [num0: 13.000000] [num1 51.000000]
[Epoch 353/500] [Batch 360/676] [D loss: -0.031204] [G loss: -0.070597] [d1 loss: 0.147424] [d2 loss: 0.150175]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 380/676] [D loss: -0.048298] [G loss: -0.059366] [d1 loss: 0.117312] [d2 loss: 0.050761]  [sq d1 d2: 0.004429]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 400/676] [D loss: -0.031853] [G loss: -0.069308] [d1 loss: 0.051265] [d2 loss: 0.052423]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 353/500] [Batch 420/676] [D loss: -0.028331] [G loss: -0.062168] [d1 loss: 0.171727] [d2 loss: 0.155371]  [sq d1 d2: 0.000268]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 440/676] [D loss: -0.026294] [G loss: -0.045898] [d1 loss: 0.072563] [d2 loss: 0.069834]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 460/676] [D loss: 0.003439] [G loss: -0.091411] [d1 loss: 0.089728] [d2 loss: 0.119213]  [sq d1 d2: 0.000869]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 480/676] [D loss: 0.012859] [G loss: -0.143116] [d1 loss: 0.718152] [d2 loss: 0.507643]  [sq d1 d2: 0.044314]  [num0: 17.000000] [num1 47.000000]
[Epoch 353/500] [Batch 500/676] [D loss: 0.045984] [G loss: -0.177066] [d1 loss: 0.047552] [d2 loss: 0.060278]  [sq d1 d2: 0.000162]  [num0: 17.000000] [num1 47.000000]
[Epoch 353/500] [Batch 520/676] [D loss: 0.031083] [G loss: -0.113802] [d1 loss: 0.100199] [d2 loss: 0.075126]  [sq d1 d2: 0.000629]  [num0: 15.000000] [num1 49.000000]
[Epoch 353/500] [Batch 540/676] [D loss: 0.011060] [G loss: -0.087082] [d1 loss: 0.024411] [d2 loss: 0.028442]  [sq d1 d2: 0.000016]  [num0: 22.000000] [num1 42.000000]
[Epoch 353/500] [Batch 560/676] [D loss: 0.005124] [G loss: -0.060905] [d1 loss: 0.101675] [d2 loss: 0.101205]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 580/676] [D loss: -0.005156] [G loss: -0.019615] [d1 loss: 0.039148] [d2 loss: 0.041527]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 353/500] [Batch 600/676] [D loss: -0.010929] [G loss: 0.027920] [d1 loss: 0.070186] [d2 loss: 0.082229]  [sq d1 d2: 0.000145]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 620/676] [D loss: -0.023290] [G loss: 0.106223] [d1 loss: 0.110561] [d2 loss: 0.122908]  [sq d1 d2: 0.000152]  [num0: 16.000000] [num1 48.000000]
[Epoch 353/500] [Batch 640/676] [D loss: -0.052226] [G loss: 0.161502] [d1 loss: 0.080909] [d2 loss: 0.100361]  [sq d1 d2: 0.000378]  [num0: 18.000000] [num1 46.000000]
[Epoch 353/500] [Batch 660/676] [D loss: -0.019968] [G loss: 0.221679] [d1 loss: 0.060551] [d2 loss: 0.057145]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 354/500] [Batch 0/676] [D loss: -0.133553] [G loss: 0.199903] [d1 loss: 0.140218] [d2 loss: 0.139758]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 20/676] [D loss: -0.048976] [G loss: 0.166251] [d1 loss: 0.041977] [d2 loss: 0.058683]  [sq d1 d2: 0.000279]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 40/676] [D loss: -0.062728] [G loss: 0.135220] [d1 loss: 0.059639] [d2 loss: 0.071114]  [sq d1 d2: 0.000132]  [num0: 19.000000] [num1 45.000000]
[Epoch 354/500] [Batch 60/676] [D loss: -0.017091] [G loss: 0.090784] [d1 loss: 0.079048] [d2 loss: 0.100090]  [sq d1 d2: 0.000443]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 80/676] [D loss: 0.004875] [G loss: 0.071921] [d1 loss: 0.088667] [d2 loss: 0.071922]  [sq d1 d2: 0.000280]  [num0: 14.000000] [num1 50.000000]
[Epoch 354/500] [Batch 100/676] [D loss: 0.059405] [G loss: 0.033741] [d1 loss: 0.026566] [d2 loss: 0.030686]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 120/676] [D loss: 0.017390] [G loss: 0.005756] [d1 loss: 0.146275] [d2 loss: 0.147285]  [sq d1 d2: 0.000001]  [num0: 22.000000] [num1 42.000000]
[Epoch 354/500] [Batch 140/676] [D loss: 0.004539] [G loss: 0.029947] [d1 loss: 0.093011] [d2 loss: 0.105192]  [sq d1 d2: 0.000148]  [num0: 16.000000] [num1 48.000000]
[Epoch 354/500] [Batch 160/676] [D loss: -0.002321] [G loss: 0.041261] [d1 loss: 0.113966] [d2 loss: 0.090223]  [sq d1 d2: 0.000564]  [num0: 18.000000] [num1 46.000000]

[Epoch 354/500] [Batch 180/676] [D loss: -0.021565] [G loss: 0.015357] [d1 loss: 0.134566] [d2 loss: 0.119107]  [sq d1 d2: 0.000239]  [num0: 12.000000] [num1 52.000000]
[Epoch 354/500] [Batch 200/676] [D loss: -0.036265] [G loss: -0.001741] [d1 loss: 0.077898] [d2 loss: 0.077846]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 220/676] [D loss: -0.040380] [G loss: -0.002332] [d1 loss: 0.141331] [d2 loss: 0.104366]  [sq d1 d2: 0.001366]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 240/676] [D loss: -0.067634] [G loss: 0.014283] [d1 loss: 0.076125] [d2 loss: 0.076832]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 354/500] [Batch 260/676] [D loss: -0.069830] [G loss: 0.000830] [d1 loss: 0.069218] [d2 loss: 0.080252]  [sq d1 d2: 0.000122]  [num0: 16.000000] [num1 48.000000]
[Epoch 354/500] [Batch 280/676] [D loss: 0.001646] [G loss: -0.054994] [d1 loss: 0.055680] [d2 loss: 0.052836]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 354/500] [Batch 300/676] [D loss: 0.014681] [G loss: -0.033400] [d1 loss: 0.049511] [d2 loss: 0.042504]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 354/500] [Batch 320/676] [D loss: 0.027911] [G loss: -0.094895] [d1 loss: 0.082398] [d2 loss: 0.098883]  [sq d1 d2: 0.000272]  [num0: 19.000000] [num1 45.000000]
[Epoch 354/500] [Batch 340/676] [D loss: 0.063722] [G loss: -0.053937] [d1 loss: 0.110994] [d2 loss: 0.102508]  [sq d1 d2: 0.000072]  [num0: 13.000000] [num1 51.000000]
[Epoch 354/500] [Batch 360/676] [D loss: 0.020667] [G loss: -0.027252] [d1 loss: 0.128581] [d2 loss: 0.157142]  [sq d1 d2: 0.000816]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 380/676] [D loss: 0.007574] [G loss: -0.019124] [d1 loss: 0.036747] [d2 loss: 0.034679]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 354/500] [Batch 400/676] [D loss: -0.004721] [G loss: -0.041378] [d1 loss: 0.057101] [d2 loss: 0.087883]  [sq d1 d2: 0.000948]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 420/676] [D loss: -0.027421] [G loss: -0.065411] [d1 loss: 0.065957] [d2 loss: 0.066327]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 440/676] [D loss: -0.060862] [G loss: -0.060645] [d1 loss: 0.068541] [d2 loss: 0.062337]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 354/500] [Batch 460/676] [D loss: -0.057917] [G loss: -0.010364] [d1 loss: 0.089081] [d2 loss: 0.085552]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 354/500] [Batch 480/676] [D loss: -0.011661] [G loss: 0.013087] [d1 loss: 0.167812] [d2 loss: 0.179670]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 500/676] [D loss: -0.074994] [G loss: -0.004509] [d1 loss: 0.078614] [d2 loss: 0.066467]  [sq d1 d2: 0.000148]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 520/676] [D loss: -0.037903] [G loss: -0.025805] [d1 loss: 0.050051] [d2 loss: 0.042697]  [sq d1 d2: 0.000054]  [num0: 13.000000] [num1 51.000000]
[Epoch 354/500] [Batch 540/676] [D loss: -0.014132] [G loss: -0.013899] [d1 loss: 0.125574] [d2 loss: 0.116794]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 354/500] [Batch 560/676] [D loss: 0.020221] [G loss: -0.042231] [d1 loss: 0.175173] [d2 loss: 0.158968]  [sq d1 d2: 0.000263]  [num0: 19.000000] [num1 45.000000]
[Epoch 354/500] [Batch 580/676] [D loss: 0.052332] [G loss: -0.043055] [d1 loss: 0.112276] [d2 loss: 0.113749]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 600/676] [D loss: 0.052223] [G loss: -0.031523] [d1 loss: 0.087402] [d2 loss: 0.110214]  [sq d1 d2: 0.000520]  [num0: 17.000000] [num1 47.000000]
[Epoch 354/500] [Batch 620/676] [D loss: 0.020304] [G loss: -0.031333] [d1 loss: 0.143592] [d2 loss: 0.136535]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 354/500] [Batch 640/676] [D loss: 0.000580] [G loss: 0.010342] [d1 loss: 0.101992] [d2 loss: 0.104733]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 354/500] [Batch 660/676] [D loss: -0.011251] [G loss: 0.056076] [d1 loss: 0.171571] [d2 loss: 0.184140]  [sq d1 d2: 0.000158]  [num0: 14.000000] [num1 50.000000]
[Epoch 355/500] [Batch 0/676] [D loss: -0.031886] [G loss: 0.069591] [d1 loss: 0.111057] [d2 loss: 0.105684]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 355/500] [Batch 20/676] [D loss: -0.057761] [G loss: 0.077799] [d1 loss: 0.080960] [d2 loss: 0.086092]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 355/500] [Batch 40/676] [D loss: -0.047817] [G loss: 0.109248] [d1 loss: 0.119810] [d2 loss: 0.150785]  [sq d1 d2: 0.000959]  [num0: 14.000000] [num1 50.000000]
[Epoch 355/500] [Batch 60/676] [D loss: -0.109960] [G loss: 0.061604] [d1 loss: 0.068860] [d2 loss: 0.109873]  [sq d1 d2: 0.001682]  [num0: 18.000000] [num1 46.000000]
[Epoch 355/500] [Batch 80/676] [D loss: -0.044024] [G loss: 0.002847] [d1 loss: 0.113784] [d2 loss: 0.138497]  [sq d1 d2: 0.000611]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 100/676] [D loss: 0.000055] [G loss: -0.049960] [d1 loss: 0.065307] [d2 loss: 0.050890]  [sq d1 d2: 0.000208]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 120/676] [D loss: 0.050267] [G loss: 0.000238] [d1 loss: 0.125488] [d2 loss: 0.123927]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 355/500] [Batch 140/676] [D loss: 0.049974] [G loss: -0.033128] [d1 loss: 0.274081] [d2 loss: 0.101016]  [sq d1 d2: 0.029951]  [num0: 21.000000] [num1 43.000000]
[Epoch 355/500] [Batch 160/676] [D loss: 0.049954] [G loss: 0.016134] [d1 loss: 0.079148] [d2 loss: 0.075120]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 355/500] [Batch 180/676] [D loss: 0.014918] [G loss: 0.015798] [d1 loss: 0.050803] [d2 loss: 0.038513]  [sq d1 d2: 0.000151]  [num0: 15.000000] [num1 49.000000]
[Epoch 355/500] [Batch 200/676] [D loss: 0.007122] [G loss: 0.008683] [d1 loss: 0.180227] [d2 loss: 0.094032]  [sq d1 d2: 0.007430]  [num0: 18.000000] [num1 46.000000]
[Epoch 355/500] [Batch 220/676] [D loss: -0.001981] [G loss: -0.028280] [d1 loss: 0.073010] [d2 loss: 0.060748]  [sq d1 d2: 0.000150]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 240/676] [D loss: -0.012043] [G loss: -0.048642] [d1 loss: 0.188972] [d2 loss: 0.187231]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 355/500] [Batch 260/676] [D loss: -0.025817] [G loss: -0.077117] [d1 loss: 0.148839] [d2 loss: 0.144534]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 355/500] [Batch 280/676] [D loss: -0.036226] [G loss: -0.079570] [d1 loss: 0.042735] [d2 loss: 0.044254]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 355/500] [Batch 300/676] [D loss: -0.025745] [G loss: -0.056924] [d1 loss: 0.065459] [d2 loss: 0.061856]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 355/500] [Batch 320/676] [D loss: -0.073766] [G loss: -0.059742] [d1 loss: 0.079371] [d2 loss: 0.087540]  [sq d1 d2: 0.000067]  [num0: 15.000000] [num1 49.000000]
[Epoch 355/500] [Batch 340/676] [D loss: -0.106081] [G loss: -0.081451] [d1 loss: 0.140341] [d2 loss: 0.161095]  [sq d1 d2: 0.000431]  [num0: 20.000000] [num1 44.000000]
[Epoch 355/500] [Batch 360/676] [D loss: -0.061140] [G loss: -0.074347] [d1 loss: 0.065096] [d2 loss: 0.062718]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 355/500] [Batch 380/676] [D loss: -0.011657] [G loss: -0.072846] [d1 loss: 0.039996] [d2 loss: 0.065008]  [sq d1 d2: 0.000626]  [num0: 12.000000] [num1 52.000000]
[Epoch 355/500] [Batch 400/676] [D loss: 0.022532] [G loss: -0.089188] [d1 loss: 0.122637] [d2 loss: 0.113065]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 420/676] [D loss: 0.002428] [G loss: -0.093345] [d1 loss: 0.210795] [d2 loss: 0.124133]  [sq d1 d2: 0.007510]  [num0: 22.000000] [num1 42.000000]
[Epoch 355/500] [Batch 440/676] [D loss: 0.067384] [G loss: -0.087533] [d1 loss: 0.017307] [d2 loss: 0.017135]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 355/500] [Batch 460/676] [D loss: 0.032991] [G loss: -0.047367] [d1 loss: 0.150673] [d2 loss: 0.195499]  [sq d1 d2: 0.002009]  [num0: 12.000000] [num1 52.000000]
[Epoch 355/500] [Batch 480/676] [D loss: 0.005586] [G loss: -0.006134] [d1 loss: 0.055522] [d2 loss: 0.064183]  [sq d1 d2: 0.000075]  [num0: 13.000000] [num1 51.000000]
[Epoch 355/500] [Batch 500/676] [D loss: 0.002156] [G loss: 0.001774] [d1 loss: 0.052427] [d2 loss: 0.059263]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 355/500] [Batch 520/676] [D loss: -0.018155] [G loss: 0.001286] [d1 loss: 0.097723] [d2 loss: 0.112634]  [sq d1 d2: 0.000222]  [num0: 15.000000] [num1 49.000000]

[Epoch 355/500] [Batch 540/676] [D loss: -0.040403] [G loss: 0.008019] [d1 loss: 0.126415] [d2 loss: 0.073575]  [sq d1 d2: 0.002792]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 560/676] [D loss: -0.046903] [G loss: -0.016579] [d1 loss: 0.088101] [d2 loss: 0.096469]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 355/500] [Batch 580/676] [D loss: -0.034518] [G loss: -0.034691] [d1 loss: 0.104541] [d2 loss: 0.098188]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 355/500] [Batch 600/676] [D loss: -0.070391] [G loss: -0.033661] [d1 loss: 0.067981] [d2 loss: 0.068443]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 355/500] [Batch 620/676] [D loss: 0.000340] [G loss: -0.053647] [d1 loss: 0.091258] [d2 loss: 0.078979]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 355/500] [Batch 640/676] [D loss: -0.041272] [G loss: -0.110014] [d1 loss: 0.057507] [d2 loss: 0.058827]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 355/500] [Batch 660/676] [D loss: -0.009481] [G loss: -0.153590] [d1 loss: 0.205068] [d2 loss: 0.164525]  [sq d1 d2: 0.001644]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 0/676] [D loss: -0.011269] [G loss: -0.094108] [d1 loss: 0.080276] [d2 loss: 0.083376]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 356/500] [Batch 20/676] [D loss: 0.043204] [G loss: -0.053151] [d1 loss: 0.206149] [d2 loss: 0.208847]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 356/500] [Batch 40/676] [D loss: 0.034663] [G loss: 0.043560] [d1 loss: 0.043697] [d2 loss: 0.048159]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 60/676] [D loss: 0.021922] [G loss: 0.076484] [d1 loss: 0.105825] [d2 loss: 0.117355]  [sq d1 d2: 0.000133]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 80/676] [D loss: 0.018761] [G loss: 0.071184] [d1 loss: 0.099089] [d2 loss: 0.107393]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 100/676] [D loss: -0.006105] [G loss: 0.061650] [d1 loss: 0.083941] [d2 loss: 0.090700]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 120/676] [D loss: -0.015313] [G loss: 0.058367] [d1 loss: 0.058138] [d2 loss: 0.041625]  [sq d1 d2: 0.000273]  [num0: 13.000000] [num1 51.000000]
[Epoch 356/500] [Batch 140/676] [D loss: -0.043582] [G loss: 0.086243] [d1 loss: 0.044133] [d2 loss: 0.048672]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 160/676] [D loss: -0.021275] [G loss: 0.137621] [d1 loss: 0.063590] [d2 loss: 0.051998]  [sq d1 d2: 0.000134]  [num0: 16.000000] [num1 48.000000]
[Epoch 356/500] [Batch 180/676] [D loss: -0.048930] [G loss: 0.173282] [d1 loss: 0.131996] [d2 loss: 0.121508]  [sq d1 d2: 0.000110]  [num0: 16.000000] [num1 48.000000]
[Epoch 356/500] [Batch 200/676] [D loss: -0.114759] [G loss: 0.125936] [d1 loss: 0.078039] [d2 loss: 0.095511]  [sq d1 d2: 0.000305]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 220/676] [D loss: -0.073850] [G loss: 0.064913] [d1 loss: 0.061586] [d2 loss: 0.070937]  [sq d1 d2: 0.000087]  [num0: 18.000000] [num1 46.000000]
[Epoch 356/500] [Batch 240/676] [D loss: -0.095600] [G loss: 0.025203] [d1 loss: 0.093069] [d2 loss: 0.090495]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 356/500] [Batch 260/676] [D loss: -0.010103] [G loss: -0.078228] [d1 loss: 0.175900] [d2 loss: 0.091818]  [sq d1 d2: 0.007070]  [num0: 18.000000] [num1 46.000000]
[Epoch 356/500] [Batch 280/676] [D loss: 0.002050] [G loss: -0.132999] [d1 loss: 0.065722] [d2 loss: 0.101264]  [sq d1 d2: 0.001263]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 300/676] [D loss: -0.023777] [G loss: -0.158297] [d1 loss: 0.059214] [d2 loss: 0.063280]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 356/500] [Batch 320/676] [D loss: 0.028658] [G loss: -0.079184] [d1 loss: 0.107770] [d2 loss: 0.092957]  [sq d1 d2: 0.000219]  [num0: 16.000000] [num1 48.000000]
[Epoch 356/500] [Batch 340/676] [D loss: 0.023078] [G loss: -0.058751] [d1 loss: 0.115316] [d2 loss: 0.111807]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 360/676] [D loss: 0.003175] [G loss: -0.043948] [d1 loss: 0.046035] [d2 loss: 0.041178]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 356/500] [Batch 380/676] [D loss: -0.011761] [G loss: -0.004257] [d1 loss: 0.066512] [d2 loss: 0.066467]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 356/500] [Batch 400/676] [D loss: -0.010845] [G loss: 0.005770] [d1 loss: 0.058932] [d2 loss: 0.060509]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 420/676] [D loss: -0.034219] [G loss: 0.038796] [d1 loss: 0.247139] [d2 loss: 0.207401]  [sq d1 d2: 0.001579]  [num0: 13.000000] [num1 51.000000]
[Epoch 356/500] [Batch 440/676] [D loss: -0.035706] [G loss: 0.026547] [d1 loss: 0.069793] [d2 loss: 0.081855]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 460/676] [D loss: -0.070779] [G loss: -0.006845] [d1 loss: 0.027505] [d2 loss: 0.030873]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 356/500] [Batch 480/676] [D loss: -0.009393] [G loss: 0.001350] [d1 loss: 0.102142] [d2 loss: 0.128160]  [sq d1 d2: 0.000677]  [num0: 19.000000] [num1 45.000000]
[Epoch 356/500] [Batch 500/676] [D loss: 0.000697] [G loss: -0.093800] [d1 loss: 0.070407] [d2 loss: 0.071281]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 520/676] [D loss: -0.031909] [G loss: -0.141354] [d1 loss: 0.085918] [d2 loss: 0.090129]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 356/500] [Batch 540/676] [D loss: -0.005280] [G loss: -0.089176] [d1 loss: 0.137354] [d2 loss: 0.075083]  [sq d1 d2: 0.003878]  [num0: 15.000000] [num1 49.000000]
[Epoch 356/500] [Batch 560/676] [D loss: 0.047050] [G loss: -0.075948] [d1 loss: 0.115965] [d2 loss: 0.093846]  [sq d1 d2: 0.000489]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 580/676] [D loss: 0.018450] [G loss: -0.021346] [d1 loss: 0.214222] [d2 loss: 0.188797]  [sq d1 d2: 0.000646]  [num0: 18.000000] [num1 46.000000]
[Epoch 356/500] [Batch 600/676] [D loss: 0.017788] [G loss: 0.034750] [d1 loss: 0.163576] [d2 loss: 0.161345]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 620/676] [D loss: 0.026894] [G loss: 0.047766] [d1 loss: 0.052454] [d2 loss: 0.061791]  [sq d1 d2: 0.000087]  [num0: 20.000000] [num1 44.000000]
[Epoch 356/500] [Batch 640/676] [D loss: 0.007799] [G loss: 0.031395] [d1 loss: 0.098740] [d2 loss: 0.115795]  [sq d1 d2: 0.000291]  [num0: 17.000000] [num1 47.000000]
[Epoch 356/500] [Batch 660/676] [D loss: -0.007244] [G loss: 0.040624] [d1 loss: 0.066119] [d2 loss: 0.078539]  [sq d1 d2: 0.000154]  [num0: 17.000000] [num1 47.000000]
[Epoch 357/500] [Batch 0/676] [D loss: -0.016444] [G loss: 0.039071] [d1 loss: 0.068478] [d2 loss: 0.045199]  [sq d1 d2: 0.000542]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 20/676] [D loss: -0.047830] [G loss: 0.041315] [d1 loss: 0.105741] [d2 loss: 0.106587]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 357/500] [Batch 40/676] [D loss: -0.055528] [G loss: 0.068462] [d1 loss: 0.057900] [d2 loss: 0.062471]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 357/500] [Batch 60/676] [D loss: -0.033616] [G loss: 0.107606] [d1 loss: 0.120589] [d2 loss: 0.124553]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 80/676] [D loss: -0.091920] [G loss: 0.132608] [d1 loss: 0.051411] [d2 loss: 0.047517]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 357/500] [Batch 100/676] [D loss: -0.056798] [G loss: 0.102236] [d1 loss: 0.084450] [d2 loss: 0.083091]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 357/500] [Batch 120/676] [D loss: 0.005263] [G loss: 0.170280] [d1 loss: 0.012167] [d2 loss: 0.029045]  [sq d1 d2: 0.000285]  [num0: 19.000000] [num1 45.000000]
[Epoch 357/500] [Batch 140/676] [D loss: -0.008853] [G loss: 0.045116] [d1 loss: 0.088940] [d2 loss: 0.100986]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 357/500] [Batch 160/676] [D loss: -0.014829] [G loss: 0.034345] [d1 loss: 0.095323] [d2 loss: 0.088983]  [sq d1 d2: 0.000040]  [num0: 13.000000] [num1 51.000000]
[Epoch 357/500] [Batch 180/676] [D loss: 0.018375] [G loss: 0.001594] [d1 loss: 0.192118] [d2 loss: 0.206320]  [sq d1 d2: 0.000202]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 200/676] [D loss: 0.027932] [G loss: 0.028552] [d1 loss: 0.076264] [d2 loss: 0.070178]  [sq d1 d2: 0.000037]  [num0: 12.000000] [num1 52.000000]

[Epoch 357/500] [Batch 220/676] [D loss: 0.016331] [G loss: 0.014876] [d1 loss: 0.079103] [d2 loss: 0.167196]  [sq d1 d2: 0.007760]  [num0: 15.000000] [num1 49.000000]
[Epoch 357/500] [Batch 240/676] [D loss: -0.000759] [G loss: 0.002805] [d1 loss: 0.071726] [d2 loss: 0.083501]  [sq d1 d2: 0.000139]  [num0: 12.000000] [num1 52.000000]
[Epoch 357/500] [Batch 260/676] [D loss: -0.004579] [G loss: -0.037978] [d1 loss: 0.086981] [d2 loss: 0.088069]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 357/500] [Batch 280/676] [D loss: -0.036545] [G loss: -0.098880] [d1 loss: 0.154846] [d2 loss: 0.159525]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 357/500] [Batch 300/676] [D loss: -0.025487] [G loss: -0.125736] [d1 loss: 0.083015] [d2 loss: 0.074451]  [sq d1 d2: 0.000073]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 320/676] [D loss: -0.035182] [G loss: -0.142914] [d1 loss: 0.129110] [d2 loss: 0.119775]  [sq d1 d2: 0.000087]  [num0: 11.000000] [num1 53.000000]
[Epoch 357/500] [Batch 340/676] [D loss: -0.028929] [G loss: -0.176757] [d1 loss: 0.063321] [d2 loss: 0.068777]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 357/500] [Batch 360/676] [D loss: -0.054434] [G loss: -0.153763] [d1 loss: 0.081824] [d2 loss: 0.089561]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 357/500] [Batch 380/676] [D loss: -0.032487] [G loss: -0.208724] [d1 loss: 0.096102] [d2 loss: 0.107412]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 357/500] [Batch 400/676] [D loss: -0.028646] [G loss: -0.234581] [d1 loss: 0.087615] [d2 loss: 0.073641]  [sq d1 d2: 0.000195]  [num0: 17.000000] [num1 47.000000]
[Epoch 357/500] [Batch 420/676] [D loss: -0.010180] [G loss: -0.280441] [d1 loss: 0.072340] [d2 loss: 0.092160]  [sq d1 d2: 0.000393]  [num0: 13.000000] [num1 51.000000]
[Epoch 357/500] [Batch 440/676] [D loss: -0.014731] [G loss: -0.177093] [d1 loss: 0.227017] [d2 loss: 0.112109]  [sq d1 d2: 0.013204]  [num0: 18.000000] [num1 46.000000]
[Epoch 357/500] [Batch 460/676] [D loss: 0.011295] [G loss: -0.096566] [d1 loss: 0.086736] [d2 loss: 0.090516]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 480/676] [D loss: 0.007077] [G loss: 0.038090] [d1 loss: 0.137822] [d2 loss: 0.141975]  [sq d1 d2: 0.000017]  [num0: 11.000000] [num1 53.000000]
[Epoch 357/500] [Batch 500/676] [D loss: 0.001849] [G loss: 0.064318] [d1 loss: 0.165278] [d2 loss: 0.153952]  [sq d1 d2: 0.000128]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 520/676] [D loss: 0.004256] [G loss: 0.065241] [d1 loss: 0.092998] [d2 loss: 0.085222]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 357/500] [Batch 540/676] [D loss: -0.005620] [G loss: 0.060571] [d1 loss: 0.033473] [d2 loss: 0.037861]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 357/500] [Batch 560/676] [D loss: -0.011950] [G loss: 0.094689] [d1 loss: 0.084536] [d2 loss: 0.084815]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 357/500] [Batch 580/676] [D loss: -0.022357] [G loss: 0.160964] [d1 loss: 0.027017] [d2 loss: 0.023998]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 357/500] [Batch 600/676] [D loss: -0.026278] [G loss: 0.209540] [d1 loss: 0.040156] [d2 loss: 0.051581]  [sq d1 d2: 0.000131]  [num0: 18.000000] [num1 46.000000]
[Epoch 357/500] [Batch 620/676] [D loss: -0.037017] [G loss: 0.224052] [d1 loss: 0.168450] [d2 loss: 0.182046]  [sq d1 d2: 0.000185]  [num0: 14.000000] [num1 50.000000]
[Epoch 357/500] [Batch 640/676] [D loss: -0.035796] [G loss: 0.220962] [d1 loss: 0.057885] [d2 loss: 0.034966]  [sq d1 d2: 0.000525]  [num0: 21.000000] [num1 43.000000]
[Epoch 357/500] [Batch 660/676] [D loss: -0.057144] [G loss: 0.217798] [d1 loss: 0.064080] [d2 loss: 0.078191]  [sq d1 d2: 0.000199]  [num0: 20.000000] [num1 44.000000]
[Epoch 358/500] [Batch 0/676] [D loss: -0.048792] [G loss: 0.191957] [d1 loss: 0.043113] [d2 loss: 0.052074]  [sq d1 d2: 0.000080]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 20/676] [D loss: -0.011157] [G loss: 0.137747] [d1 loss: 0.063941] [d2 loss: 0.063289]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 358/500] [Batch 40/676] [D loss: -0.000314] [G loss: 0.113385] [d1 loss: 0.076745] [d2 loss: 0.098290]  [sq d1 d2: 0.000464]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 60/676] [D loss: -0.011235] [G loss: 0.071173] [d1 loss: 0.087628] [d2 loss: 0.099593]  [sq d1 d2: 0.000143]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 80/676] [D loss: 0.009284] [G loss: 0.016829] [d1 loss: 0.154203] [d2 loss: 0.164648]  [sq d1 d2: 0.000109]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 100/676] [D loss: 0.025491] [G loss: -0.065330] [d1 loss: 0.468349] [d2 loss: 0.388075]  [sq d1 d2: 0.006444]  [num0: 14.000000] [num1 50.000000]
[Epoch 358/500] [Batch 120/676] [D loss: 0.006822] [G loss: -0.103201] [d1 loss: 0.065842] [d2 loss: 0.068341]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 140/676] [D loss: 0.009281] [G loss: -0.095729] [d1 loss: 0.052085] [d2 loss: 0.053635]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 358/500] [Batch 160/676] [D loss: -0.015809] [G loss: -0.095346] [d1 loss: 0.115380] [d2 loss: 0.127184]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 358/500] [Batch 180/676] [D loss: -0.022713] [G loss: -0.135644] [d1 loss: 0.095101] [d2 loss: 0.092640]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 200/676] [D loss: -0.028304] [G loss: -0.127841] [d1 loss: 0.109025] [d2 loss: 0.143809]  [sq d1 d2: 0.001210]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 220/676] [D loss: -0.011504] [G loss: -0.178593] [d1 loss: 0.146131] [d2 loss: 0.142316]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 358/500] [Batch 240/676] [D loss: -0.042437] [G loss: -0.172873] [d1 loss: 0.086422] [d2 loss: 0.072510]  [sq d1 d2: 0.000194]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 260/676] [D loss: -0.056916] [G loss: -0.189872] [d1 loss: 0.141226] [d2 loss: 0.139712]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 358/500] [Batch 280/676] [D loss: -0.038540] [G loss: -0.208761] [d1 loss: 0.125478] [d2 loss: 0.132208]  [sq d1 d2: 0.000045]  [num0: 12.000000] [num1 52.000000]
[Epoch 358/500] [Batch 300/676] [D loss: 0.015462] [G loss: -0.137501] [d1 loss: 0.104935] [d2 loss: 0.142530]  [sq d1 d2: 0.001413]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 320/676] [D loss: -0.011225] [G loss: -0.107367] [d1 loss: 0.131427] [d2 loss: 0.165767]  [sq d1 d2: 0.001179]  [num0: 18.000000] [num1 46.000000]
[Epoch 358/500] [Batch 340/676] [D loss: -0.000025] [G loss: -0.130619] [d1 loss: 0.170466] [d2 loss: 0.180214]  [sq d1 d2: 0.000095]  [num0: 19.000000] [num1 45.000000]
[Epoch 358/500] [Batch 360/676] [D loss: 0.034566] [G loss: -0.082664] [d1 loss: 0.179022] [d2 loss: 0.176059]  [sq d1 d2: 0.000009]  [num0: 20.000000] [num1 44.000000]
[Epoch 358/500] [Batch 380/676] [D loss: 0.009178] [G loss: -0.061315] [d1 loss: 0.313681] [d2 loss: 0.196358]  [sq d1 d2: 0.013765]  [num0: 19.000000] [num1 45.000000]
[Epoch 358/500] [Batch 400/676] [D loss: 0.026482] [G loss: -0.083074] [d1 loss: 0.121879] [d2 loss: 0.170022]  [sq d1 d2: 0.002318]  [num0: 18.000000] [num1 46.000000]
[Epoch 358/500] [Batch 420/676] [D loss: -0.013232] [G loss: -0.092193] [d1 loss: 0.140996] [d2 loss: 0.119010]  [sq d1 d2: 0.000483]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 440/676] [D loss: -0.020145] [G loss: -0.115408] [d1 loss: 0.190277] [d2 loss: 0.198568]  [sq d1 d2: 0.000069]  [num0: 19.000000] [num1 45.000000]
[Epoch 358/500] [Batch 460/676] [D loss: -0.022193] [G loss: -0.116357] [d1 loss: 0.096192] [d2 loss: 0.095990]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 358/500] [Batch 480/676] [D loss: -0.020205] [G loss: -0.136998] [d1 loss: 0.101191] [d2 loss: 0.111487]  [sq d1 d2: 0.000106]  [num0: 14.000000] [num1 50.000000]
[Epoch 358/500] [Batch 500/676] [D loss: -0.050607] [G loss: -0.187923] [d1 loss: 0.136559] [d2 loss: 0.160239]  [sq d1 d2: 0.000561]  [num0: 13.000000] [num1 51.000000]
[Epoch 358/500] [Batch 520/676] [D loss: -0.004919] [G loss: -0.221738] [d1 loss: 0.068338] [d2 loss: 0.081037]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]
[Epoch 358/500] [Batch 540/676] [D loss: -0.045717] [G loss: -0.255602] [d1 loss: 0.109329] [d2 loss: 0.123126]  [sq d1 d2: 0.000190]  [num0: 16.000000] [num1 48.000000]

[Epoch 358/500] [Batch 560/676] [D loss: 0.002498] [G loss: -0.289784] [d1 loss: 0.384316] [d2 loss: 0.174425]  [sq d1 d2: 0.044054]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 580/676] [D loss: -0.015791] [G loss: -0.314897] [d1 loss: 0.154137] [d2 loss: 0.187027]  [sq d1 d2: 0.001082]  [num0: 16.000000] [num1 48.000000]
[Epoch 358/500] [Batch 600/676] [D loss: -0.012517] [G loss: -0.299896] [d1 loss: 0.085281] [d2 loss: 0.102344]  [sq d1 d2: 0.000291]  [num0: 15.000000] [num1 49.000000]
[Epoch 358/500] [Batch 620/676] [D loss: -0.017795] [G loss: -0.279460] [d1 loss: 0.123392] [d2 loss: 0.170851]  [sq d1 d2: 0.002252]  [num0: 13.000000] [num1 51.000000]
[Epoch 358/500] [Batch 640/676] [D loss: -0.003504] [G loss: -0.275868] [d1 loss: 0.066441] [d2 loss: 0.055106]  [sq d1 d2: 0.000128]  [num0: 13.000000] [num1 51.000000]
[Epoch 358/500] [Batch 660/676] [D loss: 0.016390] [G loss: -0.283016] [d1 loss: 0.047429] [d2 loss: 0.058892]  [sq d1 d2: 0.000131]  [num0: 16.000000] [num1 48.000000]
[Epoch 359/500] [Batch 0/676] [D loss: -0.002305] [G loss: -0.240442] [d1 loss: 0.138386] [d2 loss: 0.178788]  [sq d1 d2: 0.001632]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 20/676] [D loss: 0.006843] [G loss: -0.234015] [d1 loss: 0.045328] [d2 loss: 0.056958]  [sq d1 d2: 0.000135]  [num0: 18.000000] [num1 46.000000]
[Epoch 359/500] [Batch 40/676] [D loss: -0.007347] [G loss: -0.132007] [d1 loss: 0.038390] [d2 loss: 0.044198]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 359/500] [Batch 60/676] [D loss: -0.012662] [G loss: -0.103166] [d1 loss: 0.112370] [d2 loss: 0.101237]  [sq d1 d2: 0.000124]  [num0: 13.000000] [num1 51.000000]
[Epoch 359/500] [Batch 80/676] [D loss: -0.038338] [G loss: -0.095923] [d1 loss: 0.048553] [d2 loss: 0.054859]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 100/676] [D loss: 0.014323] [G loss: -0.030557] [d1 loss: 0.063024] [d2 loss: 0.065745]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 120/676] [D loss: -0.004368] [G loss: 0.009212] [d1 loss: 0.078534] [d2 loss: 0.073702]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 359/500] [Batch 140/676] [D loss: 0.009368] [G loss: 0.082259] [d1 loss: 0.091977] [d2 loss: 0.101523]  [sq d1 d2: 0.000091]  [num0: 18.000000] [num1 46.000000]
[Epoch 359/500] [Batch 160/676] [D loss: -0.015462] [G loss: 0.066582] [d1 loss: 0.127966] [d2 loss: 0.128672]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 359/500] [Batch 180/676] [D loss: -0.007556] [G loss: 0.118812] [d1 loss: 0.042533] [d2 loss: 0.063422]  [sq d1 d2: 0.000436]  [num0: 14.000000] [num1 50.000000]
[Epoch 359/500] [Batch 200/676] [D loss: -0.009537] [G loss: 0.136585] [d1 loss: 0.085791] [d2 loss: 0.085546]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 359/500] [Batch 220/676] [D loss: -0.043560] [G loss: 0.155740] [d1 loss: 0.041211] [d2 loss: 0.051651]  [sq d1 d2: 0.000109]  [num0: 14.000000] [num1 50.000000]
[Epoch 359/500] [Batch 240/676] [D loss: -0.032713] [G loss: 0.178073] [d1 loss: 0.132739] [d2 loss: 0.115497]  [sq d1 d2: 0.000297]  [num0: 14.000000] [num1 50.000000]
[Epoch 359/500] [Batch 260/676] [D loss: -0.003905] [G loss: 0.200925] [d1 loss: 0.160796] [d2 loss: 0.171697]  [sq d1 d2: 0.000119]  [num0: 16.000000] [num1 48.000000]
[Epoch 359/500] [Batch 280/676] [D loss: -0.022264] [G loss: 0.162065] [d1 loss: 0.151811] [d2 loss: 0.158836]  [sq d1 d2: 0.000049]  [num0: 21.000000] [num1 43.000000]
[Epoch 359/500] [Batch 300/676] [D loss: -0.044629] [G loss: 0.183959] [d1 loss: 0.076383] [d2 loss: 0.071865]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 320/676] [D loss: 0.008085] [G loss: 0.189594] [d1 loss: 0.139729] [d2 loss: 0.137193]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 359/500] [Batch 340/676] [D loss: -0.003344] [G loss: 0.193792] [d1 loss: 0.070578] [d2 loss: 0.066595]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 359/500] [Batch 360/676] [D loss: 0.026267] [G loss: 0.206820] [d1 loss: 0.061063] [d2 loss: 0.068929]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 359/500] [Batch 380/676] [D loss: 0.003890] [G loss: 0.231462] [d1 loss: 0.209797] [d2 loss: 0.205397]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 400/676] [D loss: 0.020367] [G loss: 0.244937] [d1 loss: 0.139818] [d2 loss: 0.153479]  [sq d1 d2: 0.000187]  [num0: 13.000000] [num1 51.000000]
[Epoch 359/500] [Batch 420/676] [D loss: -0.011790] [G loss: 0.248484] [d1 loss: 0.087836] [d2 loss: 0.092672]  [sq d1 d2: 0.000023]  [num0: 20.000000] [num1 44.000000]
[Epoch 359/500] [Batch 440/676] [D loss: 0.008120] [G loss: 0.332238] [d1 loss: 0.374278] [d2 loss: 0.376664]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 359/500] [Batch 460/676] [D loss: -0.029249] [G loss: 0.336950] [d1 loss: 0.110762] [d2 loss: 0.090472]  [sq d1 d2: 0.000412]  [num0: 22.000000] [num1 42.000000]
[Epoch 359/500] [Batch 480/676] [D loss: -0.053542] [G loss: 0.369442] [d1 loss: 0.079291] [d2 loss: 0.070146]  [sq d1 d2: 0.000084]  [num0: 19.000000] [num1 45.000000]
[Epoch 359/500] [Batch 500/676] [D loss: -0.062952] [G loss: 0.377430] [d1 loss: 0.044397] [d2 loss: 0.042290]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 359/500] [Batch 520/676] [D loss: -0.071700] [G loss: 0.401280] [d1 loss: 0.093125] [d2 loss: 0.133952]  [sq d1 d2: 0.001667]  [num0: 18.000000] [num1 46.000000]
[Epoch 359/500] [Batch 540/676] [D loss: 0.024938] [G loss: 0.425180] [d1 loss: 0.070720] [d2 loss: 0.072324]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 560/676] [D loss: -0.032080] [G loss: 0.310036] [d1 loss: 0.084194] [d2 loss: 0.054352]  [sq d1 d2: 0.000891]  [num0: 17.000000] [num1 47.000000]
[Epoch 359/500] [Batch 580/676] [D loss: 0.015906] [G loss: 0.240618] [d1 loss: 0.142178] [d2 loss: 0.193601]  [sq d1 d2: 0.002644]  [num0: 13.000000] [num1 51.000000]
[Epoch 359/500] [Batch 600/676] [D loss: 0.000707] [G loss: 0.174106] [d1 loss: 0.105925] [d2 loss: 0.113204]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 359/500] [Batch 620/676] [D loss: 0.005154] [G loss: 0.118226] [d1 loss: 0.092889] [d2 loss: 0.074953]  [sq d1 d2: 0.000322]  [num0: 17.000000] [num1 47.000000]
[Epoch 359/500] [Batch 640/676] [D loss: -0.009370] [G loss: 0.067053] [d1 loss: 0.166541] [d2 loss: 0.140281]  [sq d1 d2: 0.000690]  [num0: 15.000000] [num1 49.000000]
[Epoch 359/500] [Batch 660/676] [D loss: -0.015434] [G loss: 0.038101] [d1 loss: 0.122412] [d2 loss: 0.115618]  [sq d1 d2: 0.000046]  [num0: 19.000000] [num1 45.000000]
[Epoch 360/500] [Batch 0/676] [D loss: -0.034404] [G loss: -0.002207] [d1 loss: 0.062565] [d2 loss: 0.081807]  [sq d1 d2: 0.000370]  [num0: 17.000000] [num1 47.000000]
[Epoch 360/500] [Batch 20/676] [D loss: -0.051003] [G loss: -0.049324] [d1 loss: 0.091282] [d2 loss: 0.097354]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 360/500] [Batch 40/676] [D loss: -0.037918] [G loss: -0.100399] [d1 loss: 0.088957] [d2 loss: 0.084351]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 60/676] [D loss: -0.044424] [G loss: -0.152232] [d1 loss: 0.105769] [d2 loss: 0.099465]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 360/500] [Batch 80/676] [D loss: -0.000895] [G loss: -0.234347] [d1 loss: 0.054705] [d2 loss: 0.058049]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 360/500] [Batch 100/676] [D loss: -0.025926] [G loss: -0.265698] [d1 loss: 0.094358] [d2 loss: 0.087151]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 360/500] [Batch 120/676] [D loss: -0.000333] [G loss: -0.236091] [d1 loss: 0.077728] [d2 loss: 0.095182]  [sq d1 d2: 0.000305]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 140/676] [D loss: -0.007986] [G loss: -0.288985] [d1 loss: 0.102901] [d2 loss: 0.120607]  [sq d1 d2: 0.000314]  [num0: 13.000000] [num1 51.000000]
[Epoch 360/500] [Batch 160/676] [D loss: 0.025322] [G loss: -0.286279] [d1 loss: 0.133966] [d2 loss: 0.166182]  [sq d1 d2: 0.001038]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 180/676] [D loss: -0.011362] [G loss: -0.257298] [d1 loss: 0.087772] [d2 loss: 0.091701]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 200/676] [D loss: 0.003333] [G loss: -0.242035] [d1 loss: 0.059648] [d2 loss: 0.063024]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 360/500] [Batch 220/676] [D loss: 0.006178] [G loss: -0.216567] [d1 loss: 0.076692] [d2 loss: 0.087851]  [sq d1 d2: 0.000125]  [num0: 14.000000] [num1 50.000000]

[Epoch 360/500] [Batch 240/676] [D loss: 0.010586] [G loss: -0.202253] [d1 loss: 0.050990] [d2 loss: 0.060625]  [sq d1 d2: 0.000093]  [num0: 20.000000] [num1 44.000000]
[Epoch 360/500] [Batch 260/676] [D loss: -0.026475] [G loss: -0.194916] [d1 loss: 0.186738] [d2 loss: 0.180320]  [sq d1 d2: 0.000041]  [num0: 19.000000] [num1 45.000000]
[Epoch 360/500] [Batch 280/676] [D loss: -0.036104] [G loss: -0.233838] [d1 loss: 0.103945] [d2 loss: 0.101504]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 300/676] [D loss: -0.061243] [G loss: -0.238603] [d1 loss: 0.093971] [d2 loss: 0.092558]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 360/500] [Batch 320/676] [D loss: -0.031446] [G loss: -0.257006] [d1 loss: 0.129329] [d2 loss: 0.139905]  [sq d1 d2: 0.000112]  [num0: 15.000000] [num1 49.000000]
[Epoch 360/500] [Batch 340/676] [D loss: -0.013143] [G loss: -0.277556] [d1 loss: 0.027535] [d2 loss: 0.032915]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 360/676] [D loss: -0.012464] [G loss: -0.235914] [d1 loss: 0.079870] [d2 loss: 0.099409]  [sq d1 d2: 0.000382]  [num0: 17.000000] [num1 47.000000]
[Epoch 360/500] [Batch 380/676] [D loss: -0.018585] [G loss: -0.261073] [d1 loss: 0.104977] [d2 loss: 0.120799]  [sq d1 d2: 0.000250]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 400/676] [D loss: 0.008086] [G loss: -0.256359] [d1 loss: 0.043964] [d2 loss: 0.047581]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 360/500] [Batch 420/676] [D loss: 0.024757] [G loss: -0.240466] [d1 loss: 0.080511] [d2 loss: 0.085104]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 440/676] [D loss: 0.011607] [G loss: -0.225826] [d1 loss: 0.061577] [d2 loss: 0.070265]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 460/676] [D loss: 0.012220] [G loss: -0.141390] [d1 loss: 0.108670] [d2 loss: 0.158450]  [sq d1 d2: 0.002478]  [num0: 14.000000] [num1 50.000000]
[Epoch 360/500] [Batch 480/676] [D loss: -0.012999] [G loss: -0.126652] [d1 loss: 0.034748] [d2 loss: 0.038699]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 360/500] [Batch 500/676] [D loss: -0.005656] [G loss: -0.046440] [d1 loss: 0.030605] [d2 loss: 0.022328]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 360/500] [Batch 520/676] [D loss: -0.008035] [G loss: -0.013996] [d1 loss: 0.075056] [d2 loss: 0.081679]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 540/676] [D loss: -0.015251] [G loss: 0.008814] [d1 loss: 0.159927] [d2 loss: 0.185630]  [sq d1 d2: 0.000661]  [num0: 19.000000] [num1 45.000000]
[Epoch 360/500] [Batch 560/676] [D loss: -0.021918] [G loss: 0.004053] [d1 loss: 0.035018] [d2 loss: 0.035907]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 360/500] [Batch 580/676] [D loss: -0.047010] [G loss: 0.033810] [d1 loss: 0.044947] [d2 loss: 0.045152]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 360/500] [Batch 600/676] [D loss: -0.054389] [G loss: 0.067792] [d1 loss: 0.064548] [d2 loss: 0.049055]  [sq d1 d2: 0.000240]  [num0: 14.000000] [num1 50.000000]
[Epoch 360/500] [Batch 620/676] [D loss: -0.024517] [G loss: 0.105142] [d1 loss: 0.151910] [d2 loss: 0.141224]  [sq d1 d2: 0.000114]  [num0: 20.000000] [num1 44.000000]
[Epoch 360/500] [Batch 640/676] [D loss: -0.025871] [G loss: 0.119640] [d1 loss: 0.083684] [d2 loss: 0.105795]  [sq d1 d2: 0.000489]  [num0: 18.000000] [num1 46.000000]
[Epoch 360/500] [Batch 660/676] [D loss: -0.010193] [G loss: 0.159143] [d1 loss: 0.076524] [d2 loss: 0.108154]  [sq d1 d2: 0.001000]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 0/676] [D loss: 0.029696] [G loss: 0.184842] [d1 loss: 0.159843] [d2 loss: 0.108262]  [sq d1 d2: 0.002661]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 20/676] [D loss: 0.010276] [G loss: 0.172873] [d1 loss: 0.027969] [d2 loss: 0.036563]  [sq d1 d2: 0.000074]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 40/676] [D loss: -0.006074] [G loss: 0.178267] [d1 loss: 0.109943] [d2 loss: 0.130603]  [sq d1 d2: 0.000427]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 60/676] [D loss: -0.008748] [G loss: 0.214504] [d1 loss: 0.063339] [d2 loss: 0.066385]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 361/500] [Batch 80/676] [D loss: -0.001330] [G loss: 0.239325] [d1 loss: 0.063459] [d2 loss: 0.070193]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 100/676] [D loss: -0.016533] [G loss: 0.272971] [d1 loss: 0.085065] [d2 loss: 0.087896]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 361/500] [Batch 120/676] [D loss: -0.028717] [G loss: 0.330867] [d1 loss: 0.044315] [d2 loss: 0.048782]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 361/500] [Batch 140/676] [D loss: -0.056412] [G loss: 0.443767] [d1 loss: 0.061104] [d2 loss: 0.074665]  [sq d1 d2: 0.000184]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 160/676] [D loss: -0.037880] [G loss: 0.461516] [d1 loss: 0.052169] [d2 loss: 0.042488]  [sq d1 d2: 0.000094]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 180/676] [D loss: -0.022518] [G loss: 0.476118] [d1 loss: 0.072205] [d2 loss: 0.090660]  [sq d1 d2: 0.000341]  [num0: 20.000000] [num1 44.000000]
[Epoch 361/500] [Batch 200/676] [D loss: -0.028646] [G loss: 0.423296] [d1 loss: 0.056762] [d2 loss: 0.065466]  [sq d1 d2: 0.000076]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 220/676] [D loss: -0.009920] [G loss: 0.364337] [d1 loss: 0.130960] [d2 loss: 0.126034]  [sq d1 d2: 0.000024]  [num0: 9.000000] [num1 55.000000]
[Epoch 361/500] [Batch 240/676] [D loss: -0.019557] [G loss: 0.224864] [d1 loss: 0.081185] [d2 loss: 0.077370]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 260/676] [D loss: 0.034941] [G loss: 0.131440] [d1 loss: 0.066205] [d2 loss: 0.097693]  [sq d1 d2: 0.000992]  [num0: 15.000000] [num1 49.000000]
[Epoch 361/500] [Batch 280/676] [D loss: -0.013099] [G loss: 0.010334] [d1 loss: 0.037781] [d2 loss: 0.050284]  [sq d1 d2: 0.000156]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 300/676] [D loss: 0.004528] [G loss: -0.095994] [d1 loss: 0.077623] [d2 loss: 0.096687]  [sq d1 d2: 0.000363]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 320/676] [D loss: 0.000095] [G loss: -0.183044] [d1 loss: 0.050133] [d2 loss: 0.044943]  [sq d1 d2: 0.000027]  [num0: 12.000000] [num1 52.000000]
[Epoch 361/500] [Batch 340/676] [D loss: -0.015998] [G loss: -0.270021] [d1 loss: 0.101817] [d2 loss: 0.094442]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 360/676] [D loss: -0.025158] [G loss: -0.343749] [d1 loss: 0.111029] [d2 loss: 0.089607]  [sq d1 d2: 0.000459]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 380/676] [D loss: -0.004212] [G loss: -0.354173] [d1 loss: 0.106262] [d2 loss: 0.097528]  [sq d1 d2: 0.000076]  [num0: 13.000000] [num1 51.000000]
[Epoch 361/500] [Batch 400/676] [D loss: -0.035509] [G loss: -0.421647] [d1 loss: 0.112535] [d2 loss: 0.130526]  [sq d1 d2: 0.000324]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 420/676] [D loss: -0.059871] [G loss: -0.453697] [d1 loss: 0.058917] [d2 loss: 0.072651]  [sq d1 d2: 0.000189]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 440/676] [D loss: -0.047690] [G loss: -0.522897] [d1 loss: 0.080048] [d2 loss: 0.092255]  [sq d1 d2: 0.000149]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 460/676] [D loss: -0.033874] [G loss: -0.556340] [d1 loss: 0.046961] [d2 loss: 0.042516]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 480/676] [D loss: 0.006488] [G loss: -0.438854] [d1 loss: 0.153894] [d2 loss: 0.191136]  [sq d1 d2: 0.001387]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 500/676] [D loss: 0.010790] [G loss: -0.352038] [d1 loss: 0.054555] [d2 loss: 0.068816]  [sq d1 d2: 0.000203]  [num0: 13.000000] [num1 51.000000]
[Epoch 361/500] [Batch 520/676] [D loss: 0.009793] [G loss: -0.248964] [d1 loss: 0.091631] [d2 loss: 0.098469]  [sq d1 d2: 0.000047]  [num0: 19.000000] [num1 45.000000]
[Epoch 361/500] [Batch 540/676] [D loss: 0.009603] [G loss: -0.132968] [d1 loss: 0.072004] [d2 loss: 0.085280]  [sq d1 d2: 0.000176]  [num0: 19.000000] [num1 45.000000]
[Epoch 361/500] [Batch 560/676] [D loss: 0.008119] [G loss: -0.089911] [d1 loss: 0.079946] [d2 loss: 0.093419]  [sq d1 d2: 0.000182]  [num0: 18.000000] [num1 46.000000]
[Epoch 361/500] [Batch 580/676] [D loss: -0.000399] [G loss: -0.033946] [d1 loss: 0.042883] [d2 loss: 0.047542]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]

[Epoch 361/500] [Batch 600/676] [D loss: -0.002012] [G loss: 0.013046] [d1 loss: 0.029631] [d2 loss: 0.027751]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 361/500] [Batch 620/676] [D loss: -0.015869] [G loss: 0.083973] [d1 loss: 0.054490] [d2 loss: 0.086232]  [sq d1 d2: 0.001008]  [num0: 14.000000] [num1 50.000000]
[Epoch 361/500] [Batch 640/676] [D loss: -0.010208] [G loss: 0.119394] [d1 loss: 0.045151] [d2 loss: 0.042676]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 361/500] [Batch 660/676] [D loss: -0.018326] [G loss: 0.160920] [d1 loss: 0.052667] [d2 loss: 0.056030]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 0/676] [D loss: -0.042889] [G loss: 0.179231] [d1 loss: 0.050702] [d2 loss: 0.047919]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 362/500] [Batch 20/676] [D loss: -0.028101] [G loss: 0.173747] [d1 loss: 0.086791] [d2 loss: 0.070875]  [sq d1 d2: 0.000253]  [num0: 16.000000] [num1 48.000000]
[Epoch 362/500] [Batch 40/676] [D loss: -0.027669] [G loss: 0.182334] [d1 loss: 0.058186] [d2 loss: 0.062514]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 362/500] [Batch 60/676] [D loss: -0.023310] [G loss: 0.202058] [d1 loss: 0.581885] [d2 loss: 0.410079]  [sq d1 d2: 0.029517]  [num0: 13.000000] [num1 51.000000]
[Epoch 362/500] [Batch 80/676] [D loss: 0.003238] [G loss: 0.181805] [d1 loss: 0.128581] [d2 loss: 0.122399]  [sq d1 d2: 0.000038]  [num0: 19.000000] [num1 45.000000]
[Epoch 362/500] [Batch 100/676] [D loss: 0.003308] [G loss: 0.153503] [d1 loss: 0.087329] [d2 loss: 0.085745]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 120/676] [D loss: 0.001046] [G loss: 0.129526] [d1 loss: 0.074943] [d2 loss: 0.080603]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 362/500] [Batch 140/676] [D loss: 0.013082] [G loss: 0.092514] [d1 loss: 0.025185] [d2 loss: 0.023013]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 160/676] [D loss: 0.008216] [G loss: 0.034481] [d1 loss: 0.185872] [d2 loss: 0.100180]  [sq d1 d2: 0.007343]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 180/676] [D loss: 0.005739] [G loss: 0.014750] [d1 loss: 0.133921] [d2 loss: 0.135207]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 200/676] [D loss: 0.003357] [G loss: -0.008934] [d1 loss: 0.107505] [d2 loss: 0.083789]  [sq d1 d2: 0.000562]  [num0: 15.000000] [num1 49.000000]
[Epoch 362/500] [Batch 220/676] [D loss: -0.004194] [G loss: -0.025974] [d1 loss: 0.125528] [d2 loss: 0.143384]  [sq d1 d2: 0.000319]  [num0: 17.000000] [num1 47.000000]
[Epoch 362/500] [Batch 240/676] [D loss: -0.002734] [G loss: -0.064432] [d1 loss: 0.086078] [d2 loss: 0.084777]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 260/676] [D loss: -0.026024] [G loss: -0.093037] [d1 loss: 0.065143] [d2 loss: 0.057837]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 362/500] [Batch 280/676] [D loss: -0.020623] [G loss: -0.130367] [d1 loss: 0.057989] [d2 loss: 0.047758]  [sq d1 d2: 0.000105]  [num0: 17.000000] [num1 47.000000]
[Epoch 362/500] [Batch 300/676] [D loss: -0.032634] [G loss: -0.127566] [d1 loss: 0.048940] [d2 loss: 0.056090]  [sq d1 d2: 0.000051]  [num0: 13.000000] [num1 51.000000]
[Epoch 362/500] [Batch 320/676] [D loss: -0.042130] [G loss: -0.115644] [d1 loss: 0.134972] [d2 loss: 0.128232]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 340/676] [D loss: -0.019923] [G loss: -0.118854] [d1 loss: 0.109390] [d2 loss: 0.092873]  [sq d1 d2: 0.000273]  [num0: 15.000000] [num1 49.000000]
[Epoch 362/500] [Batch 360/676] [D loss: 0.018197] [G loss: -0.124959] [d1 loss: 0.070337] [d2 loss: 0.058788]  [sq d1 d2: 0.000133]  [num0: 12.000000] [num1 52.000000]
[Epoch 362/500] [Batch 380/676] [D loss: 0.005381] [G loss: -0.122050] [d1 loss: 0.060930] [d2 loss: 0.057279]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 362/500] [Batch 400/676] [D loss: 0.005283] [G loss: -0.090730] [d1 loss: 0.060961] [d2 loss: 0.067397]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 420/676] [D loss: 0.022599] [G loss: -0.024817] [d1 loss: 0.092299] [d2 loss: 0.097034]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 440/676] [D loss: 0.007310] [G loss: 0.016476] [d1 loss: 0.033017] [d2 loss: 0.034415]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 362/500] [Batch 460/676] [D loss: -0.001388] [G loss: 0.061530] [d1 loss: 0.073695] [d2 loss: 0.084508]  [sq d1 d2: 0.000117]  [num0: 15.000000] [num1 49.000000]
[Epoch 362/500] [Batch 480/676] [D loss: -0.011574] [G loss: 0.105441] [d1 loss: 0.064825] [d2 loss: 0.073357]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 362/500] [Batch 500/676] [D loss: -0.005856] [G loss: 0.160452] [d1 loss: 0.094657] [d2 loss: 0.087955]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 362/500] [Batch 520/676] [D loss: -0.012276] [G loss: 0.192755] [d1 loss: 0.136297] [d2 loss: 0.143788]  [sq d1 d2: 0.000056]  [num0: 13.000000] [num1 51.000000]
[Epoch 362/500] [Batch 540/676] [D loss: -0.033558] [G loss: 0.275328] [d1 loss: 0.083401] [d2 loss: 0.054024]  [sq d1 d2: 0.000863]  [num0: 16.000000] [num1 48.000000]
[Epoch 362/500] [Batch 560/676] [D loss: -0.051389] [G loss: 0.297505] [d1 loss: 0.188497] [d2 loss: 0.183897]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 362/500] [Batch 580/676] [D loss: -0.029617] [G loss: 0.302076] [d1 loss: 0.129183] [d2 loss: 0.121340]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 600/676] [D loss: -0.027768] [G loss: 0.322341] [d1 loss: 0.125134] [d2 loss: 0.124451]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 362/500] [Batch 620/676] [D loss: -0.003147] [G loss: 0.318059] [d1 loss: 0.136061] [d2 loss: 0.125328]  [sq d1 d2: 0.000115]  [num0: 18.000000] [num1 46.000000]
[Epoch 362/500] [Batch 640/676] [D loss: -0.006053] [G loss: 0.285816] [d1 loss: 0.035509] [d2 loss: 0.043050]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 362/500] [Batch 660/676] [D loss: 0.008162] [G loss: 0.188706] [d1 loss: 0.073599] [d2 loss: 0.077142]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 363/500] [Batch 0/676] [D loss: 0.006045] [G loss: 0.118256] [d1 loss: 0.087993] [d2 loss: 0.064591]  [sq d1 d2: 0.000548]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 20/676] [D loss: 0.019736] [G loss: 0.041513] [d1 loss: 0.040364] [d2 loss: 0.040020]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 363/500] [Batch 40/676] [D loss: 0.011055] [G loss: -0.029844] [d1 loss: 0.072880] [d2 loss: 0.076831]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 363/500] [Batch 60/676] [D loss: -0.004769] [G loss: -0.132613] [d1 loss: 0.079515] [d2 loss: 0.080084]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 363/500] [Batch 80/676] [D loss: -0.020832] [G loss: -0.195440] [d1 loss: 0.167436] [d2 loss: 0.162919]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 363/500] [Batch 100/676] [D loss: -0.026218] [G loss: -0.234390] [d1 loss: 0.124079] [d2 loss: 0.123474]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 363/500] [Batch 120/676] [D loss: -0.016459] [G loss: -0.298772] [d1 loss: 0.118722] [d2 loss: 0.131767]  [sq d1 d2: 0.000170]  [num0: 15.000000] [num1 49.000000]
[Epoch 363/500] [Batch 140/676] [D loss: -0.024247] [G loss: -0.381103] [d1 loss: 0.070629] [d2 loss: 0.086853]  [sq d1 d2: 0.000263]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 160/676] [D loss: 0.006721] [G loss: -0.438801] [d1 loss: 0.123675] [d2 loss: 0.100233]  [sq d1 d2: 0.000550]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 180/676] [D loss: -0.017220] [G loss: -0.475659] [d1 loss: 0.117032] [d2 loss: 0.118952]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 200/676] [D loss: -0.028141] [G loss: -0.508327] [d1 loss: 0.162009] [d2 loss: 0.155527]  [sq d1 d2: 0.000042]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 220/676] [D loss: -0.008440] [G loss: -0.428305] [d1 loss: 0.077832] [d2 loss: 0.087871]  [sq d1 d2: 0.000101]  [num0: 14.000000] [num1 50.000000]
[Epoch 363/500] [Batch 240/676] [D loss: 0.001408] [G loss: -0.372542] [d1 loss: 0.063191] [d2 loss: 0.075550]  [sq d1 d2: 0.000153]  [num0: 18.000000] [num1 46.000000]

[Epoch 363/500] [Batch 260/676] [D loss: 0.006555] [G loss: -0.256727] [d1 loss: 0.056186] [d2 loss: 0.053405]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 363/500] [Batch 280/676] [D loss: 0.009523] [G loss: -0.165631] [d1 loss: 0.035760] [d2 loss: 0.041907]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 363/500] [Batch 300/676] [D loss: -0.005797] [G loss: -0.078909] [d1 loss: 0.040775] [d2 loss: 0.042440]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 320/676] [D loss: -0.009789] [G loss: -0.011503] [d1 loss: 0.112177] [d2 loss: 0.102048]  [sq d1 d2: 0.000103]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 340/676] [D loss: -0.019110] [G loss: 0.047359] [d1 loss: 0.081926] [d2 loss: 0.083843]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 360/676] [D loss: -0.020963] [G loss: 0.157502] [d1 loss: 0.060291] [d2 loss: 0.052363]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 380/676] [D loss: -0.015385] [G loss: 0.263202] [d1 loss: 0.052397] [d2 loss: 0.066611]  [sq d1 d2: 0.000202]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 400/676] [D loss: -0.034922] [G loss: 0.360230] [d1 loss: 0.101351] [d2 loss: 0.142585]  [sq d1 d2: 0.001700]  [num0: 16.000000] [num1 48.000000]
[Epoch 363/500] [Batch 420/676] [D loss: -0.025631] [G loss: 0.367581] [d1 loss: 0.124206] [d2 loss: 0.118725]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 363/500] [Batch 440/676] [D loss: 0.014686] [G loss: 0.386727] [d1 loss: 0.041272] [d2 loss: 0.041322]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 363/500] [Batch 460/676] [D loss: 0.008001] [G loss: 0.312985] [d1 loss: 0.112547] [d2 loss: 0.112116]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 480/676] [D loss: 0.011034] [G loss: 0.196349] [d1 loss: 0.105957] [d2 loss: 0.131643]  [sq d1 d2: 0.000660]  [num0: 18.000000] [num1 46.000000]
[Epoch 363/500] [Batch 500/676] [D loss: 0.016102] [G loss: 0.132110] [d1 loss: 0.067300] [d2 loss: 0.060820]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 363/500] [Batch 520/676] [D loss: 0.012544] [G loss: 0.038111] [d1 loss: 0.071189] [d2 loss: 0.070536]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 363/500] [Batch 540/676] [D loss: -0.001214] [G loss: -0.035113] [d1 loss: 0.134711] [d2 loss: 0.156628]  [sq d1 d2: 0.000480]  [num0: 12.000000] [num1 52.000000]
[Epoch 363/500] [Batch 560/676] [D loss: -0.010353] [G loss: -0.106505] [d1 loss: 0.032899] [d2 loss: 0.038523]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 363/500] [Batch 580/676] [D loss: -0.037143] [G loss: -0.188030] [d1 loss: 0.048574] [d2 loss: 0.061361]  [sq d1 d2: 0.000164]  [num0: 19.000000] [num1 45.000000]
[Epoch 363/500] [Batch 600/676] [D loss: -0.040058] [G loss: -0.297259] [d1 loss: 0.092466] [d2 loss: 0.117122]  [sq d1 d2: 0.000608]  [num0: 16.000000] [num1 48.000000]
[Epoch 363/500] [Batch 620/676] [D loss: -0.060322] [G loss: -0.358713] [d1 loss: 0.157770] [d2 loss: 0.136376]  [sq d1 d2: 0.000458]  [num0: 15.000000] [num1 49.000000]
[Epoch 363/500] [Batch 640/676] [D loss: -0.015253] [G loss: -0.382552] [d1 loss: 0.041592] [d2 loss: 0.064573]  [sq d1 d2: 0.000528]  [num0: 17.000000] [num1 47.000000]
[Epoch 363/500] [Batch 660/676] [D loss: 0.027099] [G loss: -0.396725] [d1 loss: 0.101562] [d2 loss: 0.084026]  [sq d1 d2: 0.000307]  [num0: 17.000000] [num1 47.000000]
[Epoch 364/500] [Batch 0/676] [D loss: 0.084443] [G loss: -0.442401] [d1 loss: 0.080616] [d2 loss: 0.109974]  [sq d1 d2: 0.000862]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 20/676] [D loss: 0.008011] [G loss: -0.349487] [d1 loss: 0.095711] [d2 loss: 0.116240]  [sq d1 d2: 0.000421]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 40/676] [D loss: 0.015220] [G loss: -0.214050] [d1 loss: 0.046994] [d2 loss: 0.047551]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 60/676] [D loss: 0.019252] [G loss: -0.144800] [d1 loss: 0.073489] [d2 loss: 0.085014]  [sq d1 d2: 0.000133]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 80/676] [D loss: 0.006727] [G loss: -0.058140] [d1 loss: 0.102866] [d2 loss: 0.084245]  [sq d1 d2: 0.000347]  [num0: 13.000000] [num1 51.000000]
[Epoch 364/500] [Batch 100/676] [D loss: -0.002396] [G loss: 0.015111] [d1 loss: 0.041376] [d2 loss: 0.040233]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 364/500] [Batch 120/676] [D loss: -0.014722] [G loss: 0.099097] [d1 loss: 0.050866] [d2 loss: 0.063556]  [sq d1 d2: 0.000161]  [num0: 13.000000] [num1 51.000000]
[Epoch 364/500] [Batch 140/676] [D loss: -0.029194] [G loss: 0.265641] [d1 loss: 0.119455] [d2 loss: 0.091978]  [sq d1 d2: 0.000755]  [num0: 13.000000] [num1 51.000000]
[Epoch 364/500] [Batch 160/676] [D loss: -0.036525] [G loss: 0.419483] [d1 loss: 0.159523] [d2 loss: 0.176165]  [sq d1 d2: 0.000277]  [num0: 19.000000] [num1 45.000000]
[Epoch 364/500] [Batch 180/676] [D loss: -0.012017] [G loss: 0.505841] [d1 loss: 0.067488] [d2 loss: 0.133585]  [sq d1 d2: 0.004369]  [num0: 17.000000] [num1 47.000000]
[Epoch 364/500] [Batch 200/676] [D loss: -0.030029] [G loss: 0.533258] [d1 loss: 0.094681] [d2 loss: 0.103465]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 220/676] [D loss: 0.037746] [G loss: 0.558357] [d1 loss: 0.041905] [d2 loss: 0.050062]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 240/676] [D loss: -0.011958] [G loss: 0.524224] [d1 loss: 0.043115] [d2 loss: 0.047854]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 260/676] [D loss: 0.008838] [G loss: 0.399197] [d1 loss: 0.119071] [d2 loss: 0.126427]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 364/500] [Batch 280/676] [D loss: 0.008662] [G loss: 0.252698] [d1 loss: 0.037031] [d2 loss: 0.041188]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 364/500] [Batch 300/676] [D loss: 0.011225] [G loss: 0.131240] [d1 loss: 0.053794] [d2 loss: 0.038606]  [sq d1 d2: 0.000231]  [num0: 16.000000] [num1 48.000000]
[Epoch 364/500] [Batch 320/676] [D loss: 0.003323] [G loss: 0.036558] [d1 loss: 0.066212] [d2 loss: 0.074514]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 340/676] [D loss: -0.007749] [G loss: -0.038672] [d1 loss: 0.074036] [d2 loss: 0.114912]  [sq d1 d2: 0.001671]  [num0: 12.000000] [num1 52.000000]
[Epoch 364/500] [Batch 360/676] [D loss: -0.020317] [G loss: -0.138164] [d1 loss: 0.033296] [d2 loss: 0.056048]  [sq d1 d2: 0.000518]  [num0: 19.000000] [num1 45.000000]
[Epoch 364/500] [Batch 380/676] [D loss: -0.050566] [G loss: -0.171491] [d1 loss: 0.091721] [d2 loss: 0.100242]  [sq d1 d2: 0.000073]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 400/676] [D loss: -0.025407] [G loss: -0.302076] [d1 loss: 0.070028] [d2 loss: 0.072193]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 364/500] [Batch 420/676] [D loss: -0.046753] [G loss: -0.422602] [d1 loss: 0.052207] [d2 loss: 0.047204]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 364/500] [Batch 440/676] [D loss: -0.000197] [G loss: -0.484088] [d1 loss: 0.074477] [d2 loss: 0.076420]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 460/676] [D loss: 0.013309] [G loss: -0.508895] [d1 loss: 0.091425] [d2 loss: 0.098919]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 364/500] [Batch 480/676] [D loss: 0.037180] [G loss: -0.460869] [d1 loss: 0.152454] [d2 loss: 0.122826]  [sq d1 d2: 0.000878]  [num0: 20.000000] [num1 44.000000]
[Epoch 364/500] [Batch 500/676] [D loss: 0.037088] [G loss: -0.368995] [d1 loss: 0.064362] [d2 loss: 0.065122]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 364/500] [Batch 520/676] [D loss: 0.023147] [G loss: -0.244881] [d1 loss: 0.080993] [d2 loss: 0.086907]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 364/500] [Batch 540/676] [D loss: 0.016751] [G loss: -0.107864] [d1 loss: 0.067417] [d2 loss: 0.070077]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 364/500] [Batch 560/676] [D loss: 0.001212] [G loss: 0.013563] [d1 loss: 0.144284] [d2 loss: 0.119075]  [sq d1 d2: 0.000636]  [num0: 20.000000] [num1 44.000000]
[Epoch 364/500] [Batch 580/676] [D loss: -0.015417] [G loss: 0.130687] [d1 loss: 0.084208] [d2 loss: 0.100723]  [sq d1 d2: 0.000273]  [num0: 16.000000] [num1 48.000000]
[Epoch 364/500] [Batch 600/676] [D loss: -0.030179] [G loss: 0.264238] [d1 loss: 0.053117] [d2 loss: 0.037042]  [sq d1 d2: 0.000258]  [num0: 18.000000] [num1 46.000000]

[Epoch 364/500] [Batch 620/676] [D loss: -0.055448] [G loss: 0.433540] [d1 loss: 0.079110] [d2 loss: 0.081503]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 364/500] [Batch 640/676] [D loss: -0.063945] [G loss: 0.579579] [d1 loss: 0.050278] [d2 loss: 0.053304]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 364/500] [Batch 660/676] [D loss: -0.069551] [G loss: 0.604152] [d1 loss: 0.120152] [d2 loss: 0.098082]  [sq d1 d2: 0.000487]  [num0: 15.000000] [num1 49.000000]
[Epoch 365/500] [Batch 0/676] [D loss: -0.062418] [G loss: 0.545559] [d1 loss: 0.069326] [d2 loss: 0.069440]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 365/500] [Batch 20/676] [D loss: -0.056938] [G loss: 0.537181] [d1 loss: 0.074525] [d2 loss: 0.088897]  [sq d1 d2: 0.000207]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 40/676] [D loss: 0.051434] [G loss: 0.454983] [d1 loss: 0.083878] [d2 loss: 0.074057]  [sq d1 d2: 0.000096]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 60/676] [D loss: 0.026545] [G loss: 0.301890] [d1 loss: 0.055511] [d2 loss: 0.050184]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 365/500] [Batch 80/676] [D loss: 0.021302] [G loss: 0.163084] [d1 loss: 0.079647] [d2 loss: 0.109088]  [sq d1 d2: 0.000867]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 100/676] [D loss: 0.014335] [G loss: 0.058874] [d1 loss: 0.070933] [d2 loss: 0.077020]  [sq d1 d2: 0.000037]  [num0: 18.000000] [num1 46.000000]
[Epoch 365/500] [Batch 120/676] [D loss: 0.009521] [G loss: -0.008336] [d1 loss: 0.152683] [d2 loss: 0.181010]  [sq d1 d2: 0.000802]  [num0: 12.000000] [num1 52.000000]
[Epoch 365/500] [Batch 140/676] [D loss: -0.010328] [G loss: -0.045769] [d1 loss: 0.138923] [d2 loss: 0.137044]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 365/500] [Batch 160/676] [D loss: -0.017229] [G loss: -0.100976] [d1 loss: 0.159526] [d2 loss: 0.149052]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 180/676] [D loss: -0.057063] [G loss: -0.202779] [d1 loss: 0.055911] [d2 loss: 0.060984]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 200/676] [D loss: -0.002355] [G loss: -0.322457] [d1 loss: 0.127521] [d2 loss: 0.132109]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 220/676] [D loss: -0.083707] [G loss: -0.446638] [d1 loss: 0.100803] [d2 loss: 0.080289]  [sq d1 d2: 0.000421]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 240/676] [D loss: -0.036669] [G loss: -0.454667] [d1 loss: 0.058438] [d2 loss: 0.046088]  [sq d1 d2: 0.000153]  [num0: 12.000000] [num1 52.000000]
[Epoch 365/500] [Batch 260/676] [D loss: -0.085938] [G loss: -0.445403] [d1 loss: 0.032960] [d2 loss: 0.040878]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 280/676] [D loss: 0.027809] [G loss: -0.468028] [d1 loss: 0.078415] [d2 loss: 0.086377]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 300/676] [D loss: 0.116709] [G loss: -0.504666] [d1 loss: 0.540748] [d2 loss: 0.418652]  [sq d1 d2: 0.014907]  [num0: 11.000000] [num1 53.000000]
[Epoch 365/500] [Batch 320/676] [D loss: 0.027200] [G loss: -0.362587] [d1 loss: 0.071014] [d2 loss: 0.106867]  [sq d1 d2: 0.001285]  [num0: 16.000000] [num1 48.000000]
[Epoch 365/500] [Batch 340/676] [D loss: 0.014522] [G loss: -0.257750] [d1 loss: 0.068703] [d2 loss: 0.067804]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 360/676] [D loss: 0.012796] [G loss: -0.156255] [d1 loss: 0.070545] [d2 loss: 0.122086]  [sq d1 d2: 0.002656]  [num0: 19.000000] [num1 45.000000]
[Epoch 365/500] [Batch 380/676] [D loss: -0.003588] [G loss: -0.071302] [d1 loss: 0.041344] [d2 loss: 0.040491]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 400/676] [D loss: -0.011321] [G loss: 0.023424] [d1 loss: 0.073301] [d2 loss: 0.085946]  [sq d1 d2: 0.000160]  [num0: 18.000000] [num1 46.000000]
[Epoch 365/500] [Batch 420/676] [D loss: -0.048182] [G loss: 0.135941] [d1 loss: 0.034573] [d2 loss: 0.034177]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 440/676] [D loss: -0.036678] [G loss: 0.322784] [d1 loss: 0.060906] [d2 loss: 0.056708]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 365/500] [Batch 460/676] [D loss: -0.088544] [G loss: 0.460291] [d1 loss: 0.091774] [d2 loss: 0.094020]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 480/676] [D loss: -0.050255] [G loss: 0.566819] [d1 loss: 0.099604] [d2 loss: 0.095682]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 500/676] [D loss: -0.030655] [G loss: 0.561716] [d1 loss: 0.064679] [d2 loss: 0.069684]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 520/676] [D loss: -0.037626] [G loss: 0.497926] [d1 loss: 0.125441] [d2 loss: 0.147966]  [sq d1 d2: 0.000507]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 540/676] [D loss: 0.033849] [G loss: 0.347569] [d1 loss: 0.140032] [d2 loss: 0.153856]  [sq d1 d2: 0.000191]  [num0: 19.000000] [num1 45.000000]
[Epoch 365/500] [Batch 560/676] [D loss: 0.018599] [G loss: 0.260590] [d1 loss: 0.056894] [d2 loss: 0.067996]  [sq d1 d2: 0.000123]  [num0: 14.000000] [num1 50.000000]
[Epoch 365/500] [Batch 580/676] [D loss: 0.026955] [G loss: 0.119800] [d1 loss: 0.174206] [d2 loss: 0.195356]  [sq d1 d2: 0.000447]  [num0: 17.000000] [num1 47.000000]
[Epoch 365/500] [Batch 600/676] [D loss: 0.010370] [G loss: 0.040309] [d1 loss: 0.195467] [d2 loss: 0.136001]  [sq d1 d2: 0.003536]  [num0: 13.000000] [num1 51.000000]
[Epoch 365/500] [Batch 620/676] [D loss: 0.004403] [G loss: -0.013036] [d1 loss: 0.079253] [d2 loss: 0.090396]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 365/500] [Batch 640/676] [D loss: -0.011187] [G loss: -0.023677] [d1 loss: 0.156481] [d2 loss: 0.161133]  [sq d1 d2: 0.000022]  [num0: 11.000000] [num1 53.000000]
[Epoch 365/500] [Batch 660/676] [D loss: -0.020778] [G loss: -0.032443] [d1 loss: 0.095247] [d2 loss: 0.145474]  [sq d1 d2: 0.002523]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 0/676] [D loss: -0.023069] [G loss: -0.028025] [d1 loss: 0.105439] [d2 loss: 0.113880]  [sq d1 d2: 0.000071]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 20/676] [D loss: -0.047138] [G loss: -0.040253] [d1 loss: 0.066076] [d2 loss: 0.061017]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 366/500] [Batch 40/676] [D loss: -0.087061] [G loss: -0.063717] [d1 loss: 0.046224] [d2 loss: 0.050056]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 366/500] [Batch 60/676] [D loss: -0.060417] [G loss: -0.167236] [d1 loss: 0.132291] [d2 loss: 0.134092]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 366/500] [Batch 80/676] [D loss: -0.069382] [G loss: -0.128019] [d1 loss: 0.071105] [d2 loss: 0.079186]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 100/676] [D loss: -0.001449] [G loss: -0.167172] [d1 loss: 0.114727] [d2 loss: 0.140876]  [sq d1 d2: 0.000684]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 120/676] [D loss: -0.026533] [G loss: -0.179150] [d1 loss: 0.121396] [d2 loss: 0.137977]  [sq d1 d2: 0.000275]  [num0: 14.000000] [num1 50.000000]
[Epoch 366/500] [Batch 140/676] [D loss: -0.035841] [G loss: -0.198316] [d1 loss: 0.161138] [d2 loss: 0.126651]  [sq d1 d2: 0.001189]  [num0: 17.000000] [num1 47.000000]
[Epoch 366/500] [Batch 160/676] [D loss: -0.029585] [G loss: -0.235362] [d1 loss: 0.136634] [d2 loss: 0.141261]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 366/500] [Batch 180/676] [D loss: 0.041650] [G loss: -0.200591] [d1 loss: 0.078735] [d2 loss: 0.078744]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 366/500] [Batch 200/676] [D loss: 0.032390] [G loss: -0.156456] [d1 loss: 0.077869] [d2 loss: 0.088493]  [sq d1 d2: 0.000113]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 220/676] [D loss: 0.002565] [G loss: -0.094823] [d1 loss: 0.101954] [d2 loss: 0.098072]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 366/500] [Batch 240/676] [D loss: 0.000608] [G loss: -0.076634] [d1 loss: 0.071508] [d2 loss: 0.064905]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 260/676] [D loss: -0.002286] [G loss: -0.055011] [d1 loss: 0.124800] [d2 loss: 0.135519]  [sq d1 d2: 0.000115]  [num0: 15.000000] [num1 49.000000]
[Epoch 366/500] [Batch 280/676] [D loss: -0.004456] [G loss: -0.038813] [d1 loss: 0.162996] [d2 loss: 0.086092]  [sq d1 d2: 0.005914]  [num0: 15.000000] [num1 49.000000]

[Epoch 366/500] [Batch 300/676] [D loss: -0.012896] [G loss: -0.014450] [d1 loss: 0.076457] [d2 loss: 0.057273]  [sq d1 d2: 0.000368]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 320/676] [D loss: -0.008469] [G loss: 0.046930] [d1 loss: 0.072230] [d2 loss: 0.071511]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 366/500] [Batch 340/676] [D loss: -0.021902] [G loss: 0.075222] [d1 loss: 0.085323] [d2 loss: 0.099925]  [sq d1 d2: 0.000213]  [num0: 13.000000] [num1 51.000000]
[Epoch 366/500] [Batch 360/676] [D loss: -0.034165] [G loss: 0.115250] [d1 loss: 0.119291] [d2 loss: 0.177332]  [sq d1 d2: 0.003369]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 380/676] [D loss: -0.033747] [G loss: 0.126108] [d1 loss: 0.074922] [d2 loss: 0.088044]  [sq d1 d2: 0.000172]  [num0: 14.000000] [num1 50.000000]
[Epoch 366/500] [Batch 400/676] [D loss: -0.005382] [G loss: 0.139246] [d1 loss: 0.131271] [d2 loss: 0.137393]  [sq d1 d2: 0.000037]  [num0: 12.000000] [num1 52.000000]
[Epoch 366/500] [Batch 420/676] [D loss: -0.049851] [G loss: 0.105156] [d1 loss: 0.116702] [d2 loss: 0.106055]  [sq d1 d2: 0.000113]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 440/676] [D loss: -0.024853] [G loss: 0.102725] [d1 loss: 0.058894] [d2 loss: 0.063345]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 366/500] [Batch 460/676] [D loss: -0.029437] [G loss: 0.130284] [d1 loss: 0.183899] [d2 loss: 0.196802]  [sq d1 d2: 0.000166]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 480/676] [D loss: -0.000045] [G loss: 0.117227] [d1 loss: 0.101753] [d2 loss: 0.132701]  [sq d1 d2: 0.000958]  [num0: 15.000000] [num1 49.000000]
[Epoch 366/500] [Batch 500/676] [D loss: -0.002575] [G loss: 0.121199] [d1 loss: 0.160965] [d2 loss: 0.138253]  [sq d1 d2: 0.000516]  [num0: 13.000000] [num1 51.000000]
[Epoch 366/500] [Batch 520/676] [D loss: -0.004087] [G loss: 0.084628] [d1 loss: 0.113983] [d2 loss: 0.089357]  [sq d1 d2: 0.000606]  [num0: 17.000000] [num1 47.000000]
[Epoch 366/500] [Batch 540/676] [D loss: 0.000807] [G loss: 0.057342] [d1 loss: 0.083384] [d2 loss: 0.075380]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 366/500] [Batch 560/676] [D loss: 0.008538] [G loss: 0.023906] [d1 loss: 0.142877] [d2 loss: 0.116120]  [sq d1 d2: 0.000716]  [num0: 17.000000] [num1 47.000000]
[Epoch 366/500] [Batch 580/676] [D loss: 0.000205] [G loss: -0.000441] [d1 loss: 0.074029] [d2 loss: 0.083471]  [sq d1 d2: 0.000089]  [num0: 16.000000] [num1 48.000000]
[Epoch 366/500] [Batch 600/676] [D loss: 0.000283] [G loss: -0.034581] [d1 loss: 0.098383] [d2 loss: 0.080449]  [sq d1 d2: 0.000322]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 620/676] [D loss: -0.002328] [G loss: -0.092272] [d1 loss: 0.129428] [d2 loss: 0.133129]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 366/500] [Batch 640/676] [D loss: -0.007382] [G loss: -0.130904] [d1 loss: 0.110124] [d2 loss: 0.125147]  [sq d1 d2: 0.000226]  [num0: 15.000000] [num1 49.000000]
[Epoch 366/500] [Batch 660/676] [D loss: -0.010677] [G loss: -0.158269] [d1 loss: 0.106227] [d2 loss: 0.094565]  [sq d1 d2: 0.000136]  [num0: 14.000000] [num1 50.000000]
[Epoch 367/500] [Batch 0/676] [D loss: -0.010928] [G loss: -0.155626] [d1 loss: 0.126214] [d2 loss: 0.119793]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 367/500] [Batch 20/676] [D loss: -0.021545] [G loss: -0.175883] [d1 loss: 0.108004] [d2 loss: 0.113229]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 367/500] [Batch 40/676] [D loss: 0.004461] [G loss: -0.209858] [d1 loss: 0.069091] [d2 loss: 0.057520]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 60/676] [D loss: -0.015862] [G loss: -0.226606] [d1 loss: 0.088676] [d2 loss: 0.091913]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 367/500] [Batch 80/676] [D loss: -0.029669] [G loss: -0.245399] [d1 loss: 0.069225] [d2 loss: 0.068227]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 100/676] [D loss: -0.021612] [G loss: -0.267751] [d1 loss: 0.182941] [d2 loss: 0.196317]  [sq d1 d2: 0.000179]  [num0: 18.000000] [num1 46.000000]
[Epoch 367/500] [Batch 120/676] [D loss: -0.029629] [G loss: -0.240173] [d1 loss: 0.067535] [d2 loss: 0.056769]  [sq d1 d2: 0.000116]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 140/676] [D loss: 0.021600] [G loss: -0.242098] [d1 loss: 0.093722] [d2 loss: 0.091246]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 367/500] [Batch 160/676] [D loss: -0.015705] [G loss: -0.210453] [d1 loss: 0.075243] [d2 loss: 0.092856]  [sq d1 d2: 0.000310]  [num0: 14.000000] [num1 50.000000]
[Epoch 367/500] [Batch 180/676] [D loss: 0.021167] [G loss: -0.153162] [d1 loss: 0.139482] [d2 loss: 0.166933]  [sq d1 d2: 0.000754]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 200/676] [D loss: 0.009872] [G loss: -0.109587] [d1 loss: 0.076096] [d2 loss: 0.073974]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 367/500] [Batch 220/676] [D loss: -0.004652] [G loss: -0.070456] [d1 loss: 0.066381] [d2 loss: 0.095650]  [sq d1 d2: 0.000857]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 240/676] [D loss: 0.001192] [G loss: -0.070015] [d1 loss: 0.085195] [d2 loss: 0.088017]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 367/500] [Batch 260/676] [D loss: -0.001304] [G loss: -0.077541] [d1 loss: 0.079041] [d2 loss: 0.083784]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 367/500] [Batch 280/676] [D loss: -0.007161] [G loss: -0.078385] [d1 loss: 0.074823] [d2 loss: 0.059707]  [sq d1 d2: 0.000229]  [num0: 18.000000] [num1 46.000000]
[Epoch 367/500] [Batch 300/676] [D loss: -0.004468] [G loss: -0.088994] [d1 loss: 0.044877] [d2 loss: 0.043664]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 367/500] [Batch 320/676] [D loss: 0.009914] [G loss: -0.085429] [d1 loss: 0.021820] [d2 loss: 0.052249]  [sq d1 d2: 0.000926]  [num0: 13.000000] [num1 51.000000]
[Epoch 367/500] [Batch 340/676] [D loss: -0.014141] [G loss: -0.072121] [d1 loss: 0.066185] [d2 loss: 0.069538]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 360/676] [D loss: -0.001667] [G loss: -0.103455] [d1 loss: 0.033370] [d2 loss: 0.027574]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 367/500] [Batch 380/676] [D loss: 0.001726] [G loss: -0.102182] [d1 loss: 0.099798] [d2 loss: 0.103030]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 367/500] [Batch 400/676] [D loss: -0.020126] [G loss: -0.102828] [d1 loss: 0.046573] [d2 loss: 0.044150]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 367/500] [Batch 420/676] [D loss: -0.036521] [G loss: -0.098361] [d1 loss: 0.183221] [d2 loss: 0.188994]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 367/500] [Batch 440/676] [D loss: -0.020345] [G loss: -0.090192] [d1 loss: 0.245552] [d2 loss: 0.196844]  [sq d1 d2: 0.002372]  [num0: 11.000000] [num1 53.000000]
[Epoch 367/500] [Batch 460/676] [D loss: 0.000703] [G loss: -0.076293] [d1 loss: 0.091596] [d2 loss: 0.112363]  [sq d1 d2: 0.000431]  [num0: 16.000000] [num1 48.000000]
[Epoch 367/500] [Batch 480/676] [D loss: -0.001037] [G loss: -0.060479] [d1 loss: 0.054841] [d2 loss: 0.054645]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 367/500] [Batch 500/676] [D loss: -0.002467] [G loss: -0.080738] [d1 loss: 0.060174] [d2 loss: 0.062125]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 367/500] [Batch 520/676] [D loss: 0.003274] [G loss: -0.087287] [d1 loss: 0.056802] [d2 loss: 0.068237]  [sq d1 d2: 0.000131]  [num0: 20.000000] [num1 44.000000]
[Epoch 367/500] [Batch 540/676] [D loss: -0.006481] [G loss: -0.091475] [d1 loss: 0.046514] [d2 loss: 0.045571]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 367/500] [Batch 560/676] [D loss: 0.004419] [G loss: -0.094580] [d1 loss: 0.058891] [d2 loss: 0.051795]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 367/500] [Batch 580/676] [D loss: -0.011599] [G loss: -0.141649] [d1 loss: 0.084814] [d2 loss: 0.063090]  [sq d1 d2: 0.000472]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 600/676] [D loss: -0.012899] [G loss: -0.130222] [d1 loss: 0.087504] [d2 loss: 0.095295]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 367/500] [Batch 620/676] [D loss: -0.025461] [G loss: -0.137768] [d1 loss: 0.095056] [d2 loss: 0.084973]  [sq d1 d2: 0.000102]  [num0: 16.000000] [num1 48.000000]
[Epoch 367/500] [Batch 640/676] [D loss: 0.008752] [G loss: -0.157657] [d1 loss: 0.089253] [d2 loss: 0.100623]  [sq d1 d2: 0.000129]  [num0: 17.000000] [num1 47.000000]

[Epoch 367/500] [Batch 660/676] [D loss: -0.007754] [G loss: -0.150080] [d1 loss: 0.043687] [d2 loss: 0.048964]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 0/676] [D loss: 0.010190] [G loss: -0.147235] [d1 loss: 0.055061] [d2 loss: 0.055074]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 368/500] [Batch 20/676] [D loss: 0.012191] [G loss: -0.121738] [d1 loss: 0.016996] [d2 loss: 0.023456]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 40/676] [D loss: 0.007869] [G loss: -0.120414] [d1 loss: 0.018992] [d2 loss: 0.031274]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 60/676] [D loss: -0.000364] [G loss: -0.110902] [d1 loss: 0.095369] [d2 loss: 0.073237]  [sq d1 d2: 0.000490]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 80/676] [D loss: 0.000709] [G loss: -0.076432] [d1 loss: 0.099726] [d2 loss: 0.084911]  [sq d1 d2: 0.000219]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 100/676] [D loss: 0.003745] [G loss: -0.059969] [d1 loss: 0.056520] [d2 loss: 0.059527]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 120/676] [D loss: 0.002535] [G loss: -0.047007] [d1 loss: 0.128836] [d2 loss: 0.096561]  [sq d1 d2: 0.001042]  [num0: 17.000000] [num1 47.000000]
[Epoch 368/500] [Batch 140/676] [D loss: 0.001812] [G loss: -0.029105] [d1 loss: 0.083869] [d2 loss: 0.060152]  [sq d1 d2: 0.000563]  [num0: 19.000000] [num1 45.000000]
[Epoch 368/500] [Batch 160/676] [D loss: -0.004524] [G loss: -0.019630] [d1 loss: 0.085242] [d2 loss: 0.071732]  [sq d1 d2: 0.000183]  [num0: 17.000000] [num1 47.000000]
[Epoch 368/500] [Batch 180/676] [D loss: -0.004011] [G loss: -0.030014] [d1 loss: 0.042842] [d2 loss: 0.037111]  [sq d1 d2: 0.000033]  [num0: 19.000000] [num1 45.000000]
[Epoch 368/500] [Batch 200/676] [D loss: -0.006486] [G loss: -0.031412] [d1 loss: 0.079271] [d2 loss: 0.047618]  [sq d1 d2: 0.001002]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 220/676] [D loss: 0.004710] [G loss: -0.042917] [d1 loss: 0.091397] [d2 loss: 0.110073]  [sq d1 d2: 0.000349]  [num0: 13.000000] [num1 51.000000]
[Epoch 368/500] [Batch 240/676] [D loss: -0.012702] [G loss: -0.032032] [d1 loss: 0.106780] [d2 loss: 0.116804]  [sq d1 d2: 0.000100]  [num0: 13.000000] [num1 51.000000]
[Epoch 368/500] [Batch 260/676] [D loss: 0.001034] [G loss: -0.054705] [d1 loss: 0.084590] [d2 loss: 0.089466]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 368/500] [Batch 280/676] [D loss: -0.019491] [G loss: -0.033027] [d1 loss: 0.061227] [d2 loss: 0.055202]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 300/676] [D loss: 0.015497] [G loss: -0.023915] [d1 loss: 0.042264] [d2 loss: 0.050577]  [sq d1 d2: 0.000069]  [num0: 12.000000] [num1 52.000000]
[Epoch 368/500] [Batch 320/676] [D loss: 0.001688] [G loss: -0.018097] [d1 loss: 0.070759] [d2 loss: 0.081244]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 340/676] [D loss: 0.003680] [G loss: -0.017938] [d1 loss: 0.153831] [d2 loss: 0.101258]  [sq d1 d2: 0.002764]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 360/676] [D loss: -0.000690] [G loss: -0.005630] [d1 loss: 0.089180] [d2 loss: 0.074536]  [sq d1 d2: 0.000214]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 380/676] [D loss: -0.003595] [G loss: -0.003827] [d1 loss: 0.088236] [d2 loss: 0.090308]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 368/500] [Batch 400/676] [D loss: -0.003314] [G loss: -0.037825] [d1 loss: 0.082118] [d2 loss: 0.096533]  [sq d1 d2: 0.000208]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 420/676] [D loss: 0.003183] [G loss: -0.078982] [d1 loss: 0.146810] [d2 loss: 0.142726]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 440/676] [D loss: -0.021886] [G loss: -0.104557] [d1 loss: 0.109811] [d2 loss: 0.120492]  [sq d1 d2: 0.000114]  [num0: 17.000000] [num1 47.000000]
[Epoch 368/500] [Batch 460/676] [D loss: -0.016458] [G loss: -0.109368] [d1 loss: 0.107276] [d2 loss: 0.107567]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 480/676] [D loss: -0.015791] [G loss: -0.122672] [d1 loss: 0.149840] [d2 loss: 0.129869]  [sq d1 d2: 0.000399]  [num0: 18.000000] [num1 46.000000]
[Epoch 368/500] [Batch 500/676] [D loss: 0.014187] [G loss: -0.122846] [d1 loss: 0.072118] [d2 loss: 0.069712]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 368/500] [Batch 520/676] [D loss: -0.011994] [G loss: -0.109544] [d1 loss: 0.049618] [d2 loss: 0.060213]  [sq d1 d2: 0.000112]  [num0: 16.000000] [num1 48.000000]
[Epoch 368/500] [Batch 540/676] [D loss: -0.007145] [G loss: -0.109541] [d1 loss: 0.070976] [d2 loss: 0.065539]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 560/676] [D loss: 0.000488] [G loss: -0.099965] [d1 loss: 0.079064] [d2 loss: 0.080783]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 368/500] [Batch 580/676] [D loss: 0.002321] [G loss: -0.087780] [d1 loss: 0.078996] [d2 loss: 0.079677]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 368/500] [Batch 600/676] [D loss: 0.008060] [G loss: -0.067865] [d1 loss: 0.040022] [d2 loss: 0.051703]  [sq d1 d2: 0.000136]  [num0: 15.000000] [num1 49.000000]
[Epoch 368/500] [Batch 620/676] [D loss: -0.001240] [G loss: -0.018352] [d1 loss: 0.105359] [d2 loss: 0.143871]  [sq d1 d2: 0.001483]  [num0: 13.000000] [num1 51.000000]
[Epoch 368/500] [Batch 640/676] [D loss: -0.005962] [G loss: 0.006724] [d1 loss: 0.100240] [d2 loss: 0.108556]  [sq d1 d2: 0.000069]  [num0: 12.000000] [num1 52.000000]
[Epoch 368/500] [Batch 660/676] [D loss: 0.000618] [G loss: 0.020671] [d1 loss: 0.084564] [d2 loss: 0.058437]  [sq d1 d2: 0.000683]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 0/676] [D loss: -0.005422] [G loss: 0.042294] [d1 loss: 0.094060] [d2 loss: 0.088895]  [sq d1 d2: 0.000027]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 20/676] [D loss: -0.014511] [G loss: 0.068543] [d1 loss: 0.078472] [d2 loss: 0.070368]  [sq d1 d2: 0.000066]  [num0: 19.000000] [num1 45.000000]
[Epoch 369/500] [Batch 40/676] [D loss: -0.010949] [G loss: 0.127505] [d1 loss: 0.087886] [d2 loss: 0.089359]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 60/676] [D loss: -0.008008] [G loss: 0.166798] [d1 loss: 0.053129] [d2 loss: 0.052492]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 369/500] [Batch 80/676] [D loss: -0.013985] [G loss: 0.186125] [d1 loss: 0.124996] [d2 loss: 0.129343]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 100/676] [D loss: 0.002088] [G loss: 0.250648] [d1 loss: 0.056944] [d2 loss: 0.077841]  [sq d1 d2: 0.000437]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 120/676] [D loss: 0.010699] [G loss: 0.252565] [d1 loss: 0.077276] [d2 loss: 0.059057]  [sq d1 d2: 0.000332]  [num0: 19.000000] [num1 45.000000]
[Epoch 369/500] [Batch 140/676] [D loss: 0.005118] [G loss: 0.160554] [d1 loss: 0.036468] [d2 loss: 0.034170]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 160/676] [D loss: -0.003278] [G loss: 0.175854] [d1 loss: 0.022942] [d2 loss: 0.020335]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 369/500] [Batch 180/676] [D loss: -0.010903] [G loss: 0.166074] [d1 loss: 0.041524] [d2 loss: 0.038068]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 200/676] [D loss: 0.017863] [G loss: 0.158563] [d1 loss: 0.103774] [d2 loss: 0.124567]  [sq d1 d2: 0.000432]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 220/676] [D loss: -0.001652] [G loss: 0.084475] [d1 loss: 0.209288] [d2 loss: 0.229869]  [sq d1 d2: 0.000424]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 240/676] [D loss: 0.000311] [G loss: 0.046142] [d1 loss: 0.065147] [d2 loss: 0.066769]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 369/500] [Batch 260/676] [D loss: -0.005502] [G loss: 0.029931] [d1 loss: 0.097273] [d2 loss: 0.119235]  [sq d1 d2: 0.000482]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 280/676] [D loss: -0.009768] [G loss: -0.003728] [d1 loss: 0.037605] [d2 loss: 0.031654]  [sq d1 d2: 0.000035]  [num0: 12.000000] [num1 52.000000]
[Epoch 369/500] [Batch 300/676] [D loss: -0.005081] [G loss: -0.016141] [d1 loss: 0.042369] [d2 loss: 0.048526]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 320/676] [D loss: 0.004603] [G loss: -0.059832] [d1 loss: 0.055289] [d2 loss: 0.048155]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]

[Epoch 369/500] [Batch 340/676] [D loss: -0.006287] [G loss: -0.103019] [d1 loss: 0.133780] [d2 loss: 0.135856]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 369/500] [Batch 360/676] [D loss: 0.010345] [G loss: -0.106528] [d1 loss: 0.044281] [d2 loss: 0.039118]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 380/676] [D loss: -0.014831] [G loss: -0.166986] [d1 loss: 0.079159] [d2 loss: 0.074846]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 369/500] [Batch 400/676] [D loss: 0.005725] [G loss: -0.155797] [d1 loss: 0.103114] [d2 loss: 0.132324]  [sq d1 d2: 0.000853]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 420/676] [D loss: -0.028685] [G loss: -0.173058] [d1 loss: 0.146124] [d2 loss: 0.165564]  [sq d1 d2: 0.000378]  [num0: 14.000000] [num1 50.000000]
[Epoch 369/500] [Batch 440/676] [D loss: -0.016028] [G loss: -0.165217] [d1 loss: 0.034506] [d2 loss: 0.035507]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 369/500] [Batch 460/676] [D loss: -0.004245] [G loss: -0.124316] [d1 loss: 0.118996] [d2 loss: 0.120036]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 369/500] [Batch 480/676] [D loss: -0.005036] [G loss: -0.104227] [d1 loss: 0.047445] [d2 loss: 0.063516]  [sq d1 d2: 0.000258]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 500/676] [D loss: 0.003645] [G loss: -0.049289] [d1 loss: 0.159432] [d2 loss: 0.163189]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 520/676] [D loss: -0.009889] [G loss: -0.050336] [d1 loss: 0.197240] [d2 loss: 0.216986]  [sq d1 d2: 0.000390]  [num0: 21.000000] [num1 43.000000]
[Epoch 369/500] [Batch 540/676] [D loss: -0.015577] [G loss: 0.001920] [d1 loss: 0.094594] [d2 loss: 0.061870]  [sq d1 d2: 0.001071]  [num0: 17.000000] [num1 47.000000]
[Epoch 369/500] [Batch 560/676] [D loss: -0.012582] [G loss: 0.033697] [d1 loss: 0.050422] [d2 loss: 0.049940]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 369/500] [Batch 580/676] [D loss: -0.029737] [G loss: 0.062760] [d1 loss: 0.080691] [d2 loss: 0.105867]  [sq d1 d2: 0.000634]  [num0: 16.000000] [num1 48.000000]
[Epoch 369/500] [Batch 600/676] [D loss: -0.004531] [G loss: 0.089135] [d1 loss: 0.075473] [d2 loss: 0.051950]  [sq d1 d2: 0.000553]  [num0: 15.000000] [num1 49.000000]
[Epoch 369/500] [Batch 620/676] [D loss: 0.017770] [G loss: 0.075566] [d1 loss: 0.180195] [d2 loss: 0.135432]  [sq d1 d2: 0.002004]  [num0: 18.000000] [num1 46.000000]
[Epoch 369/500] [Batch 640/676] [D loss: -0.025878] [G loss: 0.104227] [d1 loss: 0.052879] [d2 loss: 0.052314]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 369/500] [Batch 660/676] [D loss: 0.007317] [G loss: 0.049606] [d1 loss: 0.144715] [d2 loss: 0.131484]  [sq d1 d2: 0.000175]  [num0: 16.000000] [num1 48.000000]
[Epoch 370/500] [Batch 0/676] [D loss: -0.017878] [G loss: 0.014290] [d1 loss: 0.143712] [d2 loss: 0.107964]  [sq d1 d2: 0.001278]  [num0: 18.000000] [num1 46.000000]
[Epoch 370/500] [Batch 20/676] [D loss: 0.004539] [G loss: 0.021608] [d1 loss: 0.062659] [d2 loss: 0.055775]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 40/676] [D loss: 0.000658] [G loss: -0.073803] [d1 loss: 0.056649] [d2 loss: 0.062690]  [sq d1 d2: 0.000037]  [num0: 18.000000] [num1 46.000000]
[Epoch 370/500] [Batch 60/676] [D loss: 0.004314] [G loss: -0.088829] [d1 loss: 0.052355] [d2 loss: 0.048409]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 80/676] [D loss: -0.015452] [G loss: -0.129663] [d1 loss: 0.091802] [d2 loss: 0.081159]  [sq d1 d2: 0.000113]  [num0: 13.000000] [num1 51.000000]
[Epoch 370/500] [Batch 100/676] [D loss: -0.013527] [G loss: -0.167021] [d1 loss: 0.052034] [d2 loss: 0.058573]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 370/500] [Batch 120/676] [D loss: -0.005165] [G loss: -0.181886] [d1 loss: 0.044756] [d2 loss: 0.028283]  [sq d1 d2: 0.000271]  [num0: 13.000000] [num1 51.000000]
[Epoch 370/500] [Batch 140/676] [D loss: -0.035325] [G loss: -0.260157] [d1 loss: 0.048147] [d2 loss: 0.071460]  [sq d1 d2: 0.000544]  [num0: 19.000000] [num1 45.000000]
[Epoch 370/500] [Batch 160/676] [D loss: -0.013647] [G loss: -0.315997] [d1 loss: 0.086358] [d2 loss: 0.086773]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 370/500] [Batch 180/676] [D loss: -0.023787] [G loss: -0.359908] [d1 loss: 0.101308] [d2 loss: 0.104083]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 370/500] [Batch 200/676] [D loss: 0.009412] [G loss: -0.345587] [d1 loss: 0.038879] [d2 loss: 0.048812]  [sq d1 d2: 0.000099]  [num0: 19.000000] [num1 45.000000]
[Epoch 370/500] [Batch 220/676] [D loss: -0.027409] [G loss: -0.243538] [d1 loss: 0.061994] [d2 loss: 0.063381]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 370/500] [Batch 240/676] [D loss: -0.013437] [G loss: -0.183281] [d1 loss: 0.077004] [d2 loss: 0.067611]  [sq d1 d2: 0.000088]  [num0: 13.000000] [num1 51.000000]
[Epoch 370/500] [Batch 260/676] [D loss: 0.007848] [G loss: -0.125467] [d1 loss: 0.063906] [d2 loss: 0.056998]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 370/500] [Batch 280/676] [D loss: 0.010270] [G loss: -0.091261] [d1 loss: 0.027662] [d2 loss: 0.029211]  [sq d1 d2: 0.000002]  [num0: 21.000000] [num1 43.000000]
[Epoch 370/500] [Batch 300/676] [D loss: -0.004283] [G loss: -0.046476] [d1 loss: 0.054307] [d2 loss: 0.065436]  [sq d1 d2: 0.000124]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 320/676] [D loss: -0.005501] [G loss: -0.038074] [d1 loss: 0.028824] [d2 loss: 0.023796]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 370/500] [Batch 340/676] [D loss: -0.013218] [G loss: -0.043308] [d1 loss: 0.076113] [d2 loss: 0.062090]  [sq d1 d2: 0.000197]  [num0: 20.000000] [num1 44.000000]
[Epoch 370/500] [Batch 360/676] [D loss: -0.012713] [G loss: -0.045531] [d1 loss: 0.185523] [d2 loss: 0.170456]  [sq d1 d2: 0.000227]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 380/676] [D loss: -0.015895] [G loss: -0.014099] [d1 loss: 0.089430] [d2 loss: 0.092728]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 400/676] [D loss: 0.002308] [G loss: 0.027713] [d1 loss: 0.049770] [d2 loss: 0.066255]  [sq d1 d2: 0.000272]  [num0: 16.000000] [num1 48.000000]
[Epoch 370/500] [Batch 420/676] [D loss: -0.008022] [G loss: 0.066839] [d1 loss: 0.041924] [d2 loss: 0.039092]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 370/500] [Batch 440/676] [D loss: -0.003613] [G loss: 0.092167] [d1 loss: 0.053502] [d2 loss: 0.056388]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 460/676] [D loss: -0.028099] [G loss: 0.072852] [d1 loss: 0.029832] [d2 loss: 0.024841]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 370/500] [Batch 480/676] [D loss: 0.022474] [G loss: 0.077436] [d1 loss: 0.031251] [d2 loss: 0.033719]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 500/676] [D loss: 0.006728] [G loss: 0.025011] [d1 loss: 0.069249] [d2 loss: 0.065420]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 370/500] [Batch 520/676] [D loss: -0.016539] [G loss: -0.000213] [d1 loss: 0.083428] [d2 loss: 0.092548]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 540/676] [D loss: -0.007021] [G loss: -0.012238] [d1 loss: 0.132291] [d2 loss: 0.135828]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 560/676] [D loss: -0.000765] [G loss: -0.052529] [d1 loss: 0.054379] [d2 loss: 0.041786]  [sq d1 d2: 0.000159]  [num0: 14.000000] [num1 50.000000]
[Epoch 370/500] [Batch 580/676] [D loss: -0.005591] [G loss: -0.103209] [d1 loss: 0.060787] [d2 loss: 0.072583]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 370/500] [Batch 600/676] [D loss: -0.017962] [G loss: -0.131818] [d1 loss: 0.042851] [d2 loss: 0.036378]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 620/676] [D loss: -0.048525] [G loss: -0.166098] [d1 loss: 0.090382] [d2 loss: 0.062619]  [sq d1 d2: 0.000771]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 640/676] [D loss: -0.029543] [G loss: -0.187294] [d1 loss: 0.092401] [d2 loss: 0.092437]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 370/500] [Batch 660/676] [D loss: 0.006948] [G loss: -0.206727] [d1 loss: 0.153241] [d2 loss: 0.170431]  [sq d1 d2: 0.000295]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 0/676] [D loss: 0.003411] [G loss: -0.204249] [d1 loss: 0.054016] [d2 loss: 0.052557]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]

[Epoch 371/500] [Batch 20/676] [D loss: 0.020262] [G loss: -0.217287] [d1 loss: 0.052426] [d2 loss: 0.046842]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 40/676] [D loss: 0.013262] [G loss: -0.213767] [d1 loss: 0.057785] [d2 loss: 0.053003]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 60/676] [D loss: 0.018145] [G loss: -0.124397] [d1 loss: 0.050952] [d2 loss: 0.057863]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 80/676] [D loss: 0.010213] [G loss: -0.012270] [d1 loss: 0.101660] [d2 loss: 0.096212]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 371/500] [Batch 100/676] [D loss: 0.003075] [G loss: 0.035670] [d1 loss: 0.038545] [d2 loss: 0.032282]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 371/500] [Batch 120/676] [D loss: -0.009255] [G loss: 0.095432] [d1 loss: 0.053659] [d2 loss: 0.057861]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 371/500] [Batch 140/676] [D loss: -0.016861] [G loss: 0.147751] [d1 loss: 0.082493] [d2 loss: 0.075319]  [sq d1 d2: 0.000051]  [num0: 19.000000] [num1 45.000000]
[Epoch 371/500] [Batch 160/676] [D loss: -0.046603] [G loss: 0.179880] [d1 loss: 0.068687] [d2 loss: 0.076778]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 180/676] [D loss: -0.063644] [G loss: 0.242748] [d1 loss: 0.107706] [d2 loss: 0.161218]  [sq d1 d2: 0.002864]  [num0: 15.000000] [num1 49.000000]
[Epoch 371/500] [Batch 200/676] [D loss: -0.071793] [G loss: 0.288272] [d1 loss: 0.031301] [d2 loss: 0.032340]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 220/676] [D loss: -0.055170] [G loss: 0.300669] [d1 loss: 0.049967] [d2 loss: 0.056085]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 240/676] [D loss: 0.040948] [G loss: 0.244162] [d1 loss: 0.044258] [d2 loss: 0.042278]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 260/676] [D loss: -0.005119] [G loss: 0.229280] [d1 loss: 0.059312] [d2 loss: 0.050503]  [sq d1 d2: 0.000078]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 280/676] [D loss: -0.024779] [G loss: 0.136784] [d1 loss: 0.144656] [d2 loss: 0.119540]  [sq d1 d2: 0.000631]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 300/676] [D loss: 0.009528] [G loss: 0.036703] [d1 loss: 0.069006] [d2 loss: 0.071564]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 320/676] [D loss: -0.002580] [G loss: -0.031953] [d1 loss: 0.086791] [d2 loss: 0.095292]  [sq d1 d2: 0.000072]  [num0: 12.000000] [num1 52.000000]
[Epoch 371/500] [Batch 340/676] [D loss: -0.002599] [G loss: -0.058546] [d1 loss: 0.094224] [d2 loss: 0.087304]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 360/676] [D loss: -0.001546] [G loss: -0.108098] [d1 loss: 0.103009] [d2 loss: 0.098848]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 380/676] [D loss: -0.013520] [G loss: -0.166994] [d1 loss: 0.071407] [d2 loss: 0.061971]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 400/676] [D loss: -0.042450] [G loss: -0.271310] [d1 loss: 0.085166] [d2 loss: 0.070535]  [sq d1 d2: 0.000214]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 420/676] [D loss: 0.002864] [G loss: -0.346326] [d1 loss: 0.097972] [d2 loss: 0.094070]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 371/500] [Batch 440/676] [D loss: -0.001177] [G loss: -0.379100] [d1 loss: 0.070451] [d2 loss: 0.057246]  [sq d1 d2: 0.000174]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 460/676] [D loss: -0.003749] [G loss: -0.411881] [d1 loss: 0.091577] [d2 loss: 0.098126]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 371/500] [Batch 480/676] [D loss: -0.023038] [G loss: -0.451688] [d1 loss: 0.220106] [d2 loss: 0.229367]  [sq d1 d2: 0.000086]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 500/676] [D loss: 0.004506] [G loss: -0.398021] [d1 loss: 0.054306] [d2 loss: 0.045590]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 371/500] [Batch 520/676] [D loss: 0.026963] [G loss: -0.265546] [d1 loss: 0.026959] [d2 loss: 0.023341]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 371/500] [Batch 540/676] [D loss: -0.006268] [G loss: -0.134977] [d1 loss: 0.118775] [d2 loss: 0.135690]  [sq d1 d2: 0.000286]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 560/676] [D loss: 0.007031] [G loss: -0.078523] [d1 loss: 0.091288] [d2 loss: 0.077779]  [sq d1 d2: 0.000182]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 580/676] [D loss: -0.005456] [G loss: -0.049287] [d1 loss: 0.065947] [d2 loss: 0.064449]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 371/500] [Batch 600/676] [D loss: -0.009943] [G loss: -0.006624] [d1 loss: 0.088191] [d2 loss: 0.078871]  [sq d1 d2: 0.000087]  [num0: 18.000000] [num1 46.000000]
[Epoch 371/500] [Batch 620/676] [D loss: -0.014615] [G loss: 0.038207] [d1 loss: 0.057243] [d2 loss: 0.062200]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 371/500] [Batch 640/676] [D loss: -0.018912] [G loss: 0.110968] [d1 loss: 0.031575] [d2 loss: 0.030974]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 371/500] [Batch 660/676] [D loss: 0.000801] [G loss: 0.169855] [d1 loss: 0.045670] [d2 loss: 0.046769]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 0/676] [D loss: 0.019830] [G loss: 0.228649] [d1 loss: 0.086639] [d2 loss: 0.092409]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 372/500] [Batch 20/676] [D loss: -0.029145] [G loss: 0.264517] [d1 loss: 0.046713] [d2 loss: 0.042848]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 40/676] [D loss: -0.038856] [G loss: 0.275785] [d1 loss: 0.134024] [d2 loss: 0.134912]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 372/500] [Batch 60/676] [D loss: 0.008506] [G loss: 0.310365] [d1 loss: 0.046665] [d2 loss: 0.053761]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 80/676] [D loss: 0.002463] [G loss: 0.245126] [d1 loss: 0.088157] [d2 loss: 0.091863]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 100/676] [D loss: -0.007027] [G loss: 0.159880] [d1 loss: 0.067120] [d2 loss: 0.062588]  [sq d1 d2: 0.000021]  [num0: 19.000000] [num1 45.000000]
[Epoch 372/500] [Batch 120/676] [D loss: 0.005083] [G loss: 0.098237] [d1 loss: 0.076376] [d2 loss: 0.051924]  [sq d1 d2: 0.000598]  [num0: 13.000000] [num1 51.000000]
[Epoch 372/500] [Batch 140/676] [D loss: 0.002970] [G loss: 0.032849] [d1 loss: 0.211065] [d2 loss: 0.210563]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 372/500] [Batch 160/676] [D loss: -0.002271] [G loss: -0.037585] [d1 loss: 0.105779] [d2 loss: 0.096617]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 180/676] [D loss: -0.016042] [G loss: -0.116085] [d1 loss: 0.107005] [d2 loss: 0.122808]  [sq d1 d2: 0.000250]  [num0: 16.000000] [num1 48.000000]
[Epoch 372/500] [Batch 200/676] [D loss: -0.057402] [G loss: -0.220921] [d1 loss: 0.092687] [d2 loss: 0.090896]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 220/676] [D loss: -0.038391] [G loss: -0.270391] [d1 loss: 0.078168] [d2 loss: 0.078533]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 240/676] [D loss: -0.024335] [G loss: -0.394021] [d1 loss: 0.046464] [d2 loss: 0.051139]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 260/676] [D loss: -0.082799] [G loss: -0.431525] [d1 loss: 0.037610] [d2 loss: 0.026632]  [sq d1 d2: 0.000121]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 280/676] [D loss: 0.024384] [G loss: -0.473194] [d1 loss: 0.075442] [d2 loss: 0.082018]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 300/676] [D loss: -0.008217] [G loss: -0.452499] [d1 loss: 0.059109] [d2 loss: 0.051427]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 320/676] [D loss: 0.008056] [G loss: -0.353494] [d1 loss: 0.039147] [d2 loss: 0.036664]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 340/676] [D loss: 0.017925] [G loss: -0.234485] [d1 loss: 0.062602] [d2 loss: 0.063683]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 360/676] [D loss: 0.002601] [G loss: -0.145655] [d1 loss: 0.028595] [d2 loss: 0.025346]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]

[Epoch 372/500] [Batch 380/676] [D loss: -0.000387] [G loss: -0.064762] [d1 loss: 0.053855] [d2 loss: 0.068697]  [sq d1 d2: 0.000220]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 400/676] [D loss: 0.000669] [G loss: -0.002329] [d1 loss: 0.043855] [d2 loss: 0.044064]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 372/500] [Batch 420/676] [D loss: -0.011122] [G loss: 0.059353] [d1 loss: 0.032152] [d2 loss: 0.040839]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 440/676] [D loss: -0.075287] [G loss: 0.196175] [d1 loss: 0.079994] [d2 loss: 0.073517]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 372/500] [Batch 460/676] [D loss: -0.047626] [G loss: 0.292575] [d1 loss: 0.065114] [d2 loss: 0.045977]  [sq d1 d2: 0.000366]  [num0: 18.000000] [num1 46.000000]
[Epoch 372/500] [Batch 480/676] [D loss: -0.018935] [G loss: 0.363745] [d1 loss: 0.050823] [d2 loss: 0.063138]  [sq d1 d2: 0.000152]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 500/676] [D loss: -0.057847] [G loss: 0.377472] [d1 loss: 0.052874] [d2 loss: 0.047048]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 520/676] [D loss: -0.036484] [G loss: 0.362084] [d1 loss: 0.091094] [d2 loss: 0.085961]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 372/500] [Batch 540/676] [D loss: 0.015992] [G loss: 0.306012] [d1 loss: 0.110241] [d2 loss: 0.118806]  [sq d1 d2: 0.000073]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 560/676] [D loss: 0.020457] [G loss: 0.179683] [d1 loss: 0.054854] [d2 loss: 0.055203]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 372/500] [Batch 580/676] [D loss: -0.000950] [G loss: 0.134688] [d1 loss: 0.089559] [d2 loss: 0.080698]  [sq d1 d2: 0.000079]  [num0: 14.000000] [num1 50.000000]
[Epoch 372/500] [Batch 600/676] [D loss: 0.020624] [G loss: 0.030434] [d1 loss: 0.100505] [d2 loss: 0.082286]  [sq d1 d2: 0.000332]  [num0: 17.000000] [num1 47.000000]
[Epoch 372/500] [Batch 620/676] [D loss: 0.002655] [G loss: -0.025725] [d1 loss: 0.059925] [d2 loss: 0.054834]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 640/676] [D loss: -0.000981] [G loss: -0.064834] [d1 loss: 0.058087] [d2 loss: 0.050484]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 372/500] [Batch 660/676] [D loss: -0.000094] [G loss: -0.096071] [d1 loss: 0.067717] [d2 loss: 0.057132]  [sq d1 d2: 0.000112]  [num0: 19.000000] [num1 45.000000]
[Epoch 373/500] [Batch 0/676] [D loss: -0.031089] [G loss: -0.103133] [d1 loss: 0.109359] [d2 loss: 0.093513]  [sq d1 d2: 0.000251]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 20/676] [D loss: -0.040238] [G loss: -0.182633] [d1 loss: 0.104295] [d2 loss: 0.120359]  [sq d1 d2: 0.000258]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 40/676] [D loss: -0.058829] [G loss: -0.266522] [d1 loss: 0.046787] [d2 loss: 0.042900]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 60/676] [D loss: -0.119950] [G loss: -0.302289] [d1 loss: 0.082590] [d2 loss: 0.072774]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 80/676] [D loss: -0.035010] [G loss: -0.307060] [d1 loss: 0.058095] [d2 loss: 0.049761]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 100/676] [D loss: -0.039239] [G loss: -0.322399] [d1 loss: 0.054948] [d2 loss: 0.057212]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 120/676] [D loss: 0.046024] [G loss: -0.256070] [d1 loss: 0.071386] [d2 loss: 0.080148]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 140/676] [D loss: 0.018974] [G loss: -0.118544] [d1 loss: 0.073756] [d2 loss: 0.074702]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 160/676] [D loss: 0.010205] [G loss: -0.024859] [d1 loss: 0.029552] [d2 loss: 0.031148]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 373/500] [Batch 180/676] [D loss: -0.000902] [G loss: 0.005919] [d1 loss: 0.051415] [d2 loss: 0.043646]  [sq d1 d2: 0.000060]  [num0: 18.000000] [num1 46.000000]
[Epoch 373/500] [Batch 200/676] [D loss: -0.006767] [G loss: 0.006937] [d1 loss: 0.095612] [d2 loss: 0.090024]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 220/676] [D loss: -0.011127] [G loss: 0.028668] [d1 loss: 0.052504] [d2 loss: 0.048601]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 373/500] [Batch 240/676] [D loss: -0.066551] [G loss: 0.096403] [d1 loss: 0.044770] [d2 loss: 0.058834]  [sq d1 d2: 0.000198]  [num0: 22.000000] [num1 42.000000]
[Epoch 373/500] [Batch 260/676] [D loss: -0.041823] [G loss: 0.152659] [d1 loss: 0.031168] [d2 loss: 0.031632]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 280/676] [D loss: -0.062321] [G loss: 0.196109] [d1 loss: 0.130841] [d2 loss: 0.107355]  [sq d1 d2: 0.000552]  [num0: 14.000000] [num1 50.000000]
[Epoch 373/500] [Batch 300/676] [D loss: -0.016053] [G loss: 0.152892] [d1 loss: 0.261105] [d2 loss: 0.134481]  [sq d1 d2: 0.016034]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 320/676] [D loss: -0.035286] [G loss: 0.206362] [d1 loss: 0.101153] [d2 loss: 0.093970]  [sq d1 d2: 0.000052]  [num0: 17.000000] [num1 47.000000]
[Epoch 373/500] [Batch 340/676] [D loss: -0.006702] [G loss: 0.151177] [d1 loss: 0.133129] [d2 loss: 0.080337]  [sq d1 d2: 0.002787]  [num0: 18.000000] [num1 46.000000]
[Epoch 373/500] [Batch 360/676] [D loss: -0.032643] [G loss: 0.126627] [d1 loss: 0.078700] [d2 loss: 0.087977]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 380/676] [D loss: 0.018830] [G loss: 0.064312] [d1 loss: 0.048097] [d2 loss: 0.059608]  [sq d1 d2: 0.000133]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 400/676] [D loss: 0.029168] [G loss: 0.003771] [d1 loss: 0.119571] [d2 loss: 0.124649]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 420/676] [D loss: 0.017117] [G loss: -0.058339] [d1 loss: 0.076896] [d2 loss: 0.075058]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 373/500] [Batch 440/676] [D loss: 0.001122] [G loss: -0.087676] [d1 loss: 0.089865] [d2 loss: 0.092518]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 373/500] [Batch 460/676] [D loss: -0.001636] [G loss: -0.113602] [d1 loss: 0.109251] [d2 loss: 0.101849]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 480/676] [D loss: -0.011308] [G loss: -0.191157] [d1 loss: 0.042785] [d2 loss: 0.049141]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 500/676] [D loss: -0.040699] [G loss: -0.291510] [d1 loss: 0.077726] [d2 loss: 0.076596]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 520/676] [D loss: -0.057124] [G loss: -0.358853] [d1 loss: 0.078641] [d2 loss: 0.074767]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 373/500] [Batch 540/676] [D loss: -0.063689] [G loss: -0.437372] [d1 loss: 0.073584] [d2 loss: 0.080336]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 560/676] [D loss: -0.031390] [G loss: -0.399063] [d1 loss: 0.088587] [d2 loss: 0.067188]  [sq d1 d2: 0.000458]  [num0: 18.000000] [num1 46.000000]
[Epoch 373/500] [Batch 580/676] [D loss: -0.043870] [G loss: -0.488419] [d1 loss: 0.043161] [d2 loss: 0.059302]  [sq d1 d2: 0.000261]  [num0: 17.000000] [num1 47.000000]
[Epoch 373/500] [Batch 600/676] [D loss: -0.008308] [G loss: -0.394491] [d1 loss: 0.082044] [d2 loss: 0.091353]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 620/676] [D loss: -0.014472] [G loss: -0.301301] [d1 loss: 0.092153] [d2 loss: 0.065914]  [sq d1 d2: 0.000688]  [num0: 15.000000] [num1 49.000000]
[Epoch 373/500] [Batch 640/676] [D loss: 0.019184] [G loss: -0.227544] [d1 loss: 0.076207] [d2 loss: 0.073494]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 373/500] [Batch 660/676] [D loss: 0.018761] [G loss: -0.136636] [d1 loss: 0.074480] [d2 loss: 0.085779]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 0/676] [D loss: 0.008035] [G loss: -0.100007] [d1 loss: 0.067365] [d2 loss: 0.053470]  [sq d1 d2: 0.000193]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 20/676] [D loss: 0.000710] [G loss: -0.047692] [d1 loss: 0.022330] [d2 loss: 0.026875]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 40/676] [D loss: 0.001804] [G loss: -0.019338] [d1 loss: 0.106074] [d2 loss: 0.108368]  [sq d1 d2: 0.000005]  [num0: 12.000000] [num1 52.000000]

[Epoch 374/500] [Batch 60/676] [D loss: -0.001859] [G loss: 0.037714] [d1 loss: 0.064467] [d2 loss: 0.088796]  [sq d1 d2: 0.000592]  [num0: 15.000000] [num1 49.000000]
[Epoch 374/500] [Batch 80/676] [D loss: -0.020688] [G loss: 0.133154] [d1 loss: 0.069306] [d2 loss: 0.071970]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 374/500] [Batch 100/676] [D loss: -0.067939] [G loss: 0.235744] [d1 loss: 0.045060] [d2 loss: 0.044787]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 120/676] [D loss: -0.040286] [G loss: 0.284414] [d1 loss: 0.056269] [d2 loss: 0.073717]  [sq d1 d2: 0.000304]  [num0: 14.000000] [num1 50.000000]
[Epoch 374/500] [Batch 140/676] [D loss: 0.013363] [G loss: 0.334236] [d1 loss: 0.153452] [d2 loss: 0.136767]  [sq d1 d2: 0.000278]  [num0: 17.000000] [num1 47.000000]
[Epoch 374/500] [Batch 160/676] [D loss: -0.047767] [G loss: 0.335117] [d1 loss: 0.082291] [d2 loss: 0.091003]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 180/676] [D loss: -0.000695] [G loss: 0.318098] [d1 loss: 0.055295] [d2 loss: 0.054087]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 200/676] [D loss: 0.034894] [G loss: 0.226488] [d1 loss: 0.054937] [d2 loss: 0.054496]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 374/500] [Batch 220/676] [D loss: 0.017451] [G loss: 0.158541] [d1 loss: 0.066812] [d2 loss: 0.061443]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 374/500] [Batch 240/676] [D loss: 0.013631] [G loss: 0.090366] [d1 loss: 0.071759] [d2 loss: 0.068969]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 374/500] [Batch 260/676] [D loss: 0.006285] [G loss: 0.025437] [d1 loss: 0.030710] [d2 loss: 0.038573]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 374/500] [Batch 280/676] [D loss: -0.003548] [G loss: -0.012911] [d1 loss: 0.126943] [d2 loss: 0.143788]  [sq d1 d2: 0.000284]  [num0: 12.000000] [num1 52.000000]
[Epoch 374/500] [Batch 300/676] [D loss: -0.037171] [G loss: -0.078227] [d1 loss: 0.075439] [d2 loss: 0.076569]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 374/500] [Batch 320/676] [D loss: -0.026253] [G loss: -0.154198] [d1 loss: 0.059208] [d2 loss: 0.070580]  [sq d1 d2: 0.000129]  [num0: 15.000000] [num1 49.000000]
[Epoch 374/500] [Batch 340/676] [D loss: -0.091738] [G loss: -0.284031] [d1 loss: 0.059731] [d2 loss: 0.055654]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 374/500] [Batch 360/676] [D loss: -0.035231] [G loss: -0.351769] [d1 loss: 0.089866] [d2 loss: 0.098559]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 374/500] [Batch 380/676] [D loss: -0.021586] [G loss: -0.402242] [d1 loss: 0.072857] [d2 loss: 0.067018]  [sq d1 d2: 0.000034]  [num0: 12.000000] [num1 52.000000]
[Epoch 374/500] [Batch 400/676] [D loss: 0.007287] [G loss: -0.502894] [d1 loss: 0.119844] [d2 loss: 0.110183]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 420/676] [D loss: 0.038451] [G loss: -0.525649] [d1 loss: 0.073390] [d2 loss: 0.079305]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 440/676] [D loss: 0.003564] [G loss: -0.458634] [d1 loss: 0.065282] [d2 loss: 0.077501]  [sq d1 d2: 0.000149]  [num0: 17.000000] [num1 47.000000]
[Epoch 374/500] [Batch 460/676] [D loss: 0.050393] [G loss: -0.276647] [d1 loss: 0.115077] [d2 loss: 0.112566]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 480/676] [D loss: 0.001841] [G loss: -0.097481] [d1 loss: 0.066804] [d2 loss: 0.066442]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 374/500] [Batch 500/676] [D loss: -0.002796] [G loss: -0.008581] [d1 loss: 0.047648] [d2 loss: 0.073303]  [sq d1 d2: 0.000658]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 520/676] [D loss: -0.013938] [G loss: 0.093476] [d1 loss: 0.101827] [d2 loss: 0.082826]  [sq d1 d2: 0.000361]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 540/676] [D loss: -0.029185] [G loss: 0.263600] [d1 loss: 0.112293] [d2 loss: 0.119097]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 374/500] [Batch 560/676] [D loss: -0.077779] [G loss: 0.544080] [d1 loss: 0.053270] [d2 loss: 0.050344]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 580/676] [D loss: 0.021128] [G loss: 0.673323] [d1 loss: 0.050129] [d2 loss: 0.040567]  [sq d1 d2: 0.000091]  [num0: 12.000000] [num1 52.000000]
[Epoch 374/500] [Batch 600/676] [D loss: -0.001970] [G loss: 0.729221] [d1 loss: 0.033408] [d2 loss: 0.040432]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 374/500] [Batch 620/676] [D loss: 0.016260] [G loss: 0.749410] [d1 loss: 0.115864] [d2 loss: 0.112688]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 374/500] [Batch 640/676] [D loss: -0.071923] [G loss: 0.674884] [d1 loss: 0.137288] [d2 loss: 0.140907]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 374/500] [Batch 660/676] [D loss: -0.021487] [G loss: 0.541346] [d1 loss: 0.033848] [d2 loss: 0.033840]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 0/676] [D loss: 0.030503] [G loss: 0.355913] [d1 loss: 0.061476] [d2 loss: 0.060282]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 20/676] [D loss: 0.012545] [G loss: 0.172554] [d1 loss: 0.129665] [d2 loss: 0.154269]  [sq d1 d2: 0.000605]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 40/676] [D loss: 0.004649] [G loss: 0.051196] [d1 loss: 0.039048] [d2 loss: 0.045957]  [sq d1 d2: 0.000048]  [num0: 11.000000] [num1 53.000000]
[Epoch 375/500] [Batch 60/676] [D loss: -0.012561] [G loss: -0.052468] [d1 loss: 0.061518] [d2 loss: 0.063327]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 375/500] [Batch 80/676] [D loss: -0.017005] [G loss: -0.183550] [d1 loss: 0.057342] [d2 loss: 0.043753]  [sq d1 d2: 0.000185]  [num0: 20.000000] [num1 44.000000]
[Epoch 375/500] [Batch 100/676] [D loss: -0.027500] [G loss: -0.322771] [d1 loss: 0.062524] [d2 loss: 0.066860]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 375/500] [Batch 120/676] [D loss: -0.119486] [G loss: -0.483248] [d1 loss: 0.160117] [d2 loss: 0.164971]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 375/500] [Batch 140/676] [D loss: -0.048257] [G loss: -0.580016] [d1 loss: 0.036914] [d2 loss: 0.031789]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 375/500] [Batch 160/676] [D loss: 0.014413] [G loss: -0.636760] [d1 loss: 0.064939] [d2 loss: 0.058459]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 375/500] [Batch 180/676] [D loss: -0.024138] [G loss: -0.760181] [d1 loss: 0.124417] [d2 loss: 0.128592]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 375/500] [Batch 200/676] [D loss: -0.005673] [G loss: -0.733907] [d1 loss: 0.064480] [d2 loss: 0.063472]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 375/500] [Batch 220/676] [D loss: -0.001534] [G loss: -0.540599] [d1 loss: 0.104073] [d2 loss: 0.097016]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 375/500] [Batch 240/676] [D loss: 0.011041] [G loss: -0.383134] [d1 loss: 0.058386] [d2 loss: 0.049305]  [sq d1 d2: 0.000082]  [num0: 17.000000] [num1 47.000000]
[Epoch 375/500] [Batch 260/676] [D loss: 0.018930] [G loss: -0.227962] [d1 loss: 0.078704] [d2 loss: 0.057608]  [sq d1 d2: 0.000445]  [num0: 19.000000] [num1 45.000000]
[Epoch 375/500] [Batch 280/676] [D loss: 0.003423] [G loss: -0.095402] [d1 loss: 0.066461] [d2 loss: 0.063197]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 375/500] [Batch 300/676] [D loss: -0.005695] [G loss: 0.039589] [d1 loss: 0.040359] [d2 loss: 0.052470]  [sq d1 d2: 0.000147]  [num0: 12.000000] [num1 52.000000]
[Epoch 375/500] [Batch 320/676] [D loss: -0.024390] [G loss: 0.218845] [d1 loss: 0.028087] [d2 loss: 0.025267]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 375/500] [Batch 340/676] [D loss: -0.086570] [G loss: 0.467772] [d1 loss: 0.042185] [d2 loss: 0.029766]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 360/676] [D loss: -0.111205] [G loss: 0.729540] [d1 loss: 0.039226] [d2 loss: 0.035730]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 375/500] [Batch 380/676] [D loss: -0.021747] [G loss: 0.792469] [d1 loss: 0.139830] [d2 loss: 0.157932]  [sq d1 d2: 0.000328]  [num0: 16.000000] [num1 48.000000]
[Epoch 375/500] [Batch 400/676] [D loss: -0.028695] [G loss: 0.795696] [d1 loss: 0.112573] [d2 loss: 0.106835]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]

[Epoch 375/500] [Batch 420/676] [D loss: 0.010210] [G loss: 0.829541] [d1 loss: 0.046002] [d2 loss: 0.046742]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 375/500] [Batch 440/676] [D loss: -0.048659] [G loss: 0.740878] [d1 loss: 0.092380] [d2 loss: 0.161308]  [sq d1 d2: 0.004751]  [num0: 14.000000] [num1 50.000000]
[Epoch 375/500] [Batch 460/676] [D loss: 0.030502] [G loss: 0.630172] [d1 loss: 0.049718] [d2 loss: 0.048225]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 375/500] [Batch 480/676] [D loss: 0.026170] [G loss: 0.435528] [d1 loss: 0.103456] [d2 loss: 0.110910]  [sq d1 d2: 0.000056]  [num0: 12.000000] [num1 52.000000]
[Epoch 375/500] [Batch 500/676] [D loss: 0.018571] [G loss: 0.273737] [d1 loss: 0.137583] [d2 loss: 0.125465]  [sq d1 d2: 0.000147]  [num0: 16.000000] [num1 48.000000]
[Epoch 375/500] [Batch 520/676] [D loss: 0.008400] [G loss: 0.131567] [d1 loss: 0.084016] [d2 loss: 0.143582]  [sq d1 d2: 0.003548]  [num0: 19.000000] [num1 45.000000]
[Epoch 375/500] [Batch 540/676] [D loss: -0.004219] [G loss: 0.001387] [d1 loss: 0.122316] [d2 loss: 0.105139]  [sq d1 d2: 0.000295]  [num0: 17.000000] [num1 47.000000]
[Epoch 375/500] [Batch 560/676] [D loss: -0.032737] [G loss: -0.108938] [d1 loss: 0.058813] [d2 loss: 0.071246]  [sq d1 d2: 0.000155]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 580/676] [D loss: -0.075600] [G loss: -0.236382] [d1 loss: 0.326454] [d2 loss: 0.209303]  [sq d1 d2: 0.013724]  [num0: 18.000000] [num1 46.000000]
[Epoch 375/500] [Batch 600/676] [D loss: -0.079224] [G loss: -0.385530] [d1 loss: 0.116599] [d2 loss: 0.113389]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 375/500] [Batch 620/676] [D loss: -0.058393] [G loss: -0.471654] [d1 loss: 0.074834] [d2 loss: 0.074778]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 375/500] [Batch 640/676] [D loss: -0.016721] [G loss: -0.527344] [d1 loss: 0.146623] [d2 loss: 0.138139]  [sq d1 d2: 0.000072]  [num0: 19.000000] [num1 45.000000]
[Epoch 375/500] [Batch 660/676] [D loss: -0.054773] [G loss: -0.608000] [d1 loss: 0.040339] [d2 loss: 0.043954]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 0/676] [D loss: 0.047357] [G loss: -0.681329] [d1 loss: 0.095029] [d2 loss: 0.083437]  [sq d1 d2: 0.000134]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 20/676] [D loss: 0.012482] [G loss: -0.658235] [d1 loss: 0.046714] [d2 loss: 0.038953]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 40/676] [D loss: 0.015975] [G loss: -0.625194] [d1 loss: 0.061662] [d2 loss: 0.052107]  [sq d1 d2: 0.000091]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 60/676] [D loss: 0.038413] [G loss: -0.448836] [d1 loss: 0.049281] [d2 loss: 0.047206]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 80/676] [D loss: 0.001336] [G loss: -0.288617] [d1 loss: 0.068235] [d2 loss: 0.085738]  [sq d1 d2: 0.000306]  [num0: 15.000000] [num1 49.000000]
[Epoch 376/500] [Batch 100/676] [D loss: 0.009674] [G loss: -0.147593] [d1 loss: 0.032230] [d2 loss: 0.035719]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 120/676] [D loss: -0.002422] [G loss: 0.007957] [d1 loss: 0.033776] [d2 loss: 0.033335]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 140/676] [D loss: -0.013593] [G loss: 0.151355] [d1 loss: 0.043029] [d2 loss: 0.036286]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 160/676] [D loss: -0.066355] [G loss: 0.369805] [d1 loss: 0.010874] [d2 loss: 0.008414]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 376/500] [Batch 180/676] [D loss: -0.047921] [G loss: 0.609312] [d1 loss: 0.114242] [d2 loss: 0.118495]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 200/676] [D loss: -0.045001] [G loss: 0.781424] [d1 loss: 0.029988] [d2 loss: 0.041912]  [sq d1 d2: 0.000142]  [num0: 14.000000] [num1 50.000000]
[Epoch 376/500] [Batch 220/676] [D loss: -0.086321] [G loss: 0.899720] [d1 loss: 0.074025] [d2 loss: 0.075166]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 240/676] [D loss: -0.146649] [G loss: 0.919992] [d1 loss: 0.066898] [d2 loss: 0.083416]  [sq d1 d2: 0.000273]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 260/676] [D loss: -0.060528] [G loss: 0.933150] [d1 loss: 0.021923] [d2 loss: 0.040106]  [sq d1 d2: 0.000331]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 280/676] [D loss: -0.071754] [G loss: 0.892549] [d1 loss: 0.086857] [d2 loss: 0.117605]  [sq d1 d2: 0.000945]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 300/676] [D loss: 0.053353] [G loss: 0.691200] [d1 loss: 0.138300] [d2 loss: 0.092388]  [sq d1 d2: 0.002108]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 320/676] [D loss: 0.042314] [G loss: 0.508146] [d1 loss: 0.095895] [d2 loss: 0.081378]  [sq d1 d2: 0.000211]  [num0: 20.000000] [num1 44.000000]
[Epoch 376/500] [Batch 340/676] [D loss: 0.037715] [G loss: 0.254012] [d1 loss: 0.148767] [d2 loss: 0.158155]  [sq d1 d2: 0.000088]  [num0: 14.000000] [num1 50.000000]
[Epoch 376/500] [Batch 360/676] [D loss: 0.017089] [G loss: 0.104740] [d1 loss: 0.112215] [d2 loss: 0.137702]  [sq d1 d2: 0.000650]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 380/676] [D loss: -0.002444] [G loss: -0.004214] [d1 loss: 0.096538] [d2 loss: 0.102874]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 376/500] [Batch 400/676] [D loss: -0.008596] [G loss: -0.110645] [d1 loss: 0.070387] [d2 loss: 0.063578]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 376/500] [Batch 420/676] [D loss: -0.033130] [G loss: -0.213607] [d1 loss: 0.097340] [d2 loss: 0.112289]  [sq d1 d2: 0.000223]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 440/676] [D loss: -0.061068] [G loss: -0.370532] [d1 loss: 0.089708] [d2 loss: 0.102289]  [sq d1 d2: 0.000158]  [num0: 12.000000] [num1 52.000000]
[Epoch 376/500] [Batch 460/676] [D loss: -0.098539] [G loss: -0.497930] [d1 loss: 0.098314] [d2 loss: 0.104271]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 480/676] [D loss: -0.109663] [G loss: -0.647683] [d1 loss: 0.085276] [d2 loss: 0.124157]  [sq d1 d2: 0.001512]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 500/676] [D loss: -0.101010] [G loss: -0.737253] [d1 loss: 0.090333] [d2 loss: 0.098230]  [sq d1 d2: 0.000062]  [num0: 19.000000] [num1 45.000000]
[Epoch 376/500] [Batch 520/676] [D loss: -0.145948] [G loss: -0.723303] [d1 loss: 0.045983] [d2 loss: 0.040727]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 540/676] [D loss: -0.062828] [G loss: -0.786215] [d1 loss: 0.157982] [d2 loss: 0.151386]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 560/676] [D loss: -0.022682] [G loss: -0.744312] [d1 loss: 0.107406] [d2 loss: 0.103659]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 580/676] [D loss: 0.041801] [G loss: -0.579570] [d1 loss: 0.095157] [d2 loss: 0.072279]  [sq d1 d2: 0.000523]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 600/676] [D loss: 0.038138] [G loss: -0.406806] [d1 loss: 0.048810] [d2 loss: 0.062053]  [sq d1 d2: 0.000175]  [num0: 16.000000] [num1 48.000000]
[Epoch 376/500] [Batch 620/676] [D loss: 0.008573] [G loss: -0.241889] [d1 loss: 0.115373] [d2 loss: 0.109815]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 376/500] [Batch 640/676] [D loss: 0.004008] [G loss: -0.136408] [d1 loss: 0.120449] [d2 loss: 0.168539]  [sq d1 d2: 0.002313]  [num0: 17.000000] [num1 47.000000]
[Epoch 376/500] [Batch 660/676] [D loss: -0.003846] [G loss: -0.044028] [d1 loss: 0.068656] [d2 loss: 0.055891]  [sq d1 d2: 0.000163]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 0/676] [D loss: -0.024506] [G loss: 0.061948] [d1 loss: 0.045913] [d2 loss: 0.054863]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 377/500] [Batch 20/676] [D loss: -0.034477] [G loss: 0.209692] [d1 loss: 0.064216] [d2 loss: 0.064704]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 377/500] [Batch 40/676] [D loss: -0.040847] [G loss: 0.445598] [d1 loss: 0.036050] [d2 loss: 0.026653]  [sq d1 d2: 0.000088]  [num0: 15.000000] [num1 49.000000]
[Epoch 377/500] [Batch 60/676] [D loss: -0.114830] [G loss: 0.578480] [d1 loss: 0.072228] [d2 loss: 0.055544]  [sq d1 d2: 0.000278]  [num0: 17.000000] [num1 47.000000]
[Epoch 377/500] [Batch 80/676] [D loss: -0.061508] [G loss: 0.608664] [d1 loss: 0.075271] [d2 loss: 0.064732]  [sq d1 d2: 0.000111]  [num0: 17.000000] [num1 47.000000]

[Epoch 377/500] [Batch 100/676] [D loss: -0.106941] [G loss: 0.642685] [d1 loss: 0.060090] [d2 loss: 0.074481]  [sq d1 d2: 0.000207]  [num0: 15.000000] [num1 49.000000]
[Epoch 377/500] [Batch 120/676] [D loss: -0.021767] [G loss: 0.621924] [d1 loss: 0.072312] [d2 loss: 0.064869]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 377/500] [Batch 140/676] [D loss: -0.009538] [G loss: 0.614699] [d1 loss: 0.074579] [d2 loss: 0.067682]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 160/676] [D loss: -0.022915] [G loss: 0.602254] [d1 loss: 0.062965] [d2 loss: 0.062488]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 377/500] [Batch 180/676] [D loss: 0.028763] [G loss: 0.450193] [d1 loss: 0.081945] [d2 loss: 0.083358]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 200/676] [D loss: 0.044602] [G loss: 0.303458] [d1 loss: 0.108472] [d2 loss: 0.116123]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 220/676] [D loss: 0.040348] [G loss: 0.211872] [d1 loss: 0.121995] [d2 loss: 0.115108]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 377/500] [Batch 240/676] [D loss: 0.017896] [G loss: 0.104845] [d1 loss: 0.092355] [d2 loss: 0.089506]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 377/500] [Batch 260/676] [D loss: 0.005711] [G loss: 0.011865] [d1 loss: 0.090073] [d2 loss: 0.107288]  [sq d1 d2: 0.000296]  [num0: 12.000000] [num1 52.000000]
[Epoch 377/500] [Batch 280/676] [D loss: -0.011013] [G loss: -0.053154] [d1 loss: 0.099218] [d2 loss: 0.121652]  [sq d1 d2: 0.000503]  [num0: 19.000000] [num1 45.000000]
[Epoch 377/500] [Batch 300/676] [D loss: -0.025357] [G loss: -0.129313] [d1 loss: 0.045936] [d2 loss: 0.046711]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 320/676] [D loss: -0.034654] [G loss: -0.222243] [d1 loss: 0.116601] [d2 loss: 0.118078]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 377/500] [Batch 340/676] [D loss: -0.075664] [G loss: -0.320697] [d1 loss: 0.118356] [d2 loss: 0.120539]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 377/500] [Batch 360/676] [D loss: -0.074435] [G loss: -0.459812] [d1 loss: 0.049638] [d2 loss: 0.052300]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 380/676] [D loss: -0.102232] [G loss: -0.627927] [d1 loss: 0.082654] [d2 loss: 0.077455]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 377/500] [Batch 400/676] [D loss: -0.092086] [G loss: -0.640165] [d1 loss: 0.076248] [d2 loss: 0.083939]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 377/500] [Batch 420/676] [D loss: -0.003775] [G loss: -0.686519] [d1 loss: 0.069418] [d2 loss: 0.078929]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 377/500] [Batch 440/676] [D loss: 0.022127] [G loss: -0.749592] [d1 loss: 0.063662] [d2 loss: 0.087635]  [sq d1 d2: 0.000575]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 460/676] [D loss: 0.106545] [G loss: -0.668606] [d1 loss: 0.174888] [d2 loss: 0.155084]  [sq d1 d2: 0.000392]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 480/676] [D loss: 0.031746] [G loss: -0.601131] [d1 loss: 0.058960] [d2 loss: 0.103566]  [sq d1 d2: 0.001990]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 500/676] [D loss: 0.026357] [G loss: -0.381576] [d1 loss: 0.065034] [d2 loss: 0.077466]  [sq d1 d2: 0.000155]  [num0: 19.000000] [num1 45.000000]
[Epoch 377/500] [Batch 520/676] [D loss: 0.010589] [G loss: -0.239031] [d1 loss: 0.081453] [d2 loss: 0.137836]  [sq d1 d2: 0.003179]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 540/676] [D loss: 0.008462] [G loss: -0.132165] [d1 loss: 0.043698] [d2 loss: 0.050004]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 377/500] [Batch 560/676] [D loss: -0.005049] [G loss: -0.041092] [d1 loss: 0.058384] [d2 loss: 0.074456]  [sq d1 d2: 0.000258]  [num0: 20.000000] [num1 44.000000]
[Epoch 377/500] [Batch 580/676] [D loss: -0.016733] [G loss: 0.066394] [d1 loss: 0.060741] [d2 loss: 0.041612]  [sq d1 d2: 0.000366]  [num0: 20.000000] [num1 44.000000]
[Epoch 377/500] [Batch 600/676] [D loss: -0.037303] [G loss: 0.180307] [d1 loss: 0.100943] [d2 loss: 0.075950]  [sq d1 d2: 0.000625]  [num0: 16.000000] [num1 48.000000]
[Epoch 377/500] [Batch 620/676] [D loss: -0.042060] [G loss: 0.321280] [d1 loss: 0.036961] [d2 loss: 0.049007]  [sq d1 d2: 0.000145]  [num0: 11.000000] [num1 53.000000]
[Epoch 377/500] [Batch 640/676] [D loss: -0.049916] [G loss: 0.460506] [d1 loss: 0.042750] [d2 loss: 0.037804]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 377/500] [Batch 660/676] [D loss: -0.109349] [G loss: 0.572292] [d1 loss: 0.041385] [d2 loss: 0.046048]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 0/676] [D loss: -0.015738] [G loss: 0.564703] [d1 loss: 0.126056] [d2 loss: 0.175723]  [sq d1 d2: 0.002467]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 20/676] [D loss: -0.069628] [G loss: 0.544813] [d1 loss: 0.073721] [d2 loss: 0.061912]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 378/500] [Batch 40/676] [D loss: 0.011292] [G loss: 0.489452] [d1 loss: 0.057110] [d2 loss: 0.045935]  [sq d1 d2: 0.000125]  [num0: 21.000000] [num1 43.000000]
[Epoch 378/500] [Batch 60/676] [D loss: -0.061991] [G loss: 0.511855] [d1 loss: 0.073221] [d2 loss: 0.072653]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 80/676] [D loss: 0.055192] [G loss: 0.438112] [d1 loss: 0.139717] [d2 loss: 0.176064]  [sq d1 d2: 0.001321]  [num0: 15.000000] [num1 49.000000]
[Epoch 378/500] [Batch 100/676] [D loss: 0.066394] [G loss: 0.347979] [d1 loss: 0.052520] [d2 loss: 0.059092]  [sq d1 d2: 0.000043]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 120/676] [D loss: 0.075573] [G loss: 0.233459] [d1 loss: 0.087867] [d2 loss: 0.118758]  [sq d1 d2: 0.000954]  [num0: 16.000000] [num1 48.000000]
[Epoch 378/500] [Batch 140/676] [D loss: 0.025081] [G loss: 0.080626] [d1 loss: 0.123773] [d2 loss: 0.146962]  [sq d1 d2: 0.000538]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 160/676] [D loss: -0.000318] [G loss: 0.032779] [d1 loss: 0.073154] [d2 loss: 0.095794]  [sq d1 d2: 0.000513]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 180/676] [D loss: 0.001969] [G loss: -0.077303] [d1 loss: 0.187352] [d2 loss: 0.221191]  [sq d1 d2: 0.001145]  [num0: 15.000000] [num1 49.000000]
[Epoch 378/500] [Batch 200/676] [D loss: -0.009708] [G loss: -0.139112] [d1 loss: 0.142596] [d2 loss: 0.157409]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 378/500] [Batch 220/676] [D loss: -0.014256] [G loss: -0.224851] [d1 loss: 0.081305] [d2 loss: 0.128986]  [sq d1 d2: 0.002274]  [num0: 13.000000] [num1 51.000000]
[Epoch 378/500] [Batch 240/676] [D loss: -0.042484] [G loss: -0.282450] [d1 loss: 0.042015] [d2 loss: 0.037652]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 378/500] [Batch 260/676] [D loss: -0.027439] [G loss: -0.381348] [d1 loss: 0.087411] [d2 loss: 0.109636]  [sq d1 d2: 0.000494]  [num0: 13.000000] [num1 51.000000]
[Epoch 378/500] [Batch 280/676] [D loss: -0.032284] [G loss: -0.449227] [d1 loss: 0.103982] [d2 loss: 0.106318]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 300/676] [D loss: -0.052983] [G loss: -0.547419] [d1 loss: 0.071800] [d2 loss: 0.075185]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 378/500] [Batch 320/676] [D loss: -0.034698] [G loss: -0.647812] [d1 loss: 0.083926] [d2 loss: 0.099104]  [sq d1 d2: 0.000230]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 340/676] [D loss: -0.063787] [G loss: -0.705395] [d1 loss: 0.055903] [d2 loss: 0.057843]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 378/500] [Batch 360/676] [D loss: -0.055198] [G loss: -0.688626] [d1 loss: 0.064429] [d2 loss: 0.078580]  [sq d1 d2: 0.000200]  [num0: 14.000000] [num1 50.000000]
[Epoch 378/500] [Batch 380/676] [D loss: 0.021679] [G loss: -0.623214] [d1 loss: 0.117096] [d2 loss: 0.094393]  [sq d1 d2: 0.000515]  [num0: 12.000000] [num1 52.000000]
[Epoch 378/500] [Batch 400/676] [D loss: 0.005430] [G loss: -0.456274] [d1 loss: 0.041119] [d2 loss: 0.044227]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 378/500] [Batch 420/676] [D loss: 0.024446] [G loss: -0.266962] [d1 loss: 0.025638] [d2 loss: 0.028454]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 378/500] [Batch 440/676] [D loss: 0.017826] [G loss: -0.177929] [d1 loss: 0.154321] [d2 loss: 0.154183]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]

[Epoch 378/500] [Batch 460/676] [D loss: 0.008272] [G loss: -0.117679] [d1 loss: 0.045307] [d2 loss: 0.053415]  [sq d1 d2: 0.000066]  [num0: 13.000000] [num1 51.000000]
[Epoch 378/500] [Batch 480/676] [D loss: 0.003776] [G loss: -0.070844] [d1 loss: 0.029549] [d2 loss: 0.024731]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 378/500] [Batch 500/676] [D loss: -0.003265] [G loss: -0.058865] [d1 loss: 0.024065] [d2 loss: 0.026887]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 378/500] [Batch 520/676] [D loss: -0.004893] [G loss: -0.036149] [d1 loss: 0.047043] [d2 loss: 0.046565]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 378/500] [Batch 540/676] [D loss: -0.006070] [G loss: -0.012461] [d1 loss: 0.114563] [d2 loss: 0.110691]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 378/500] [Batch 560/676] [D loss: -0.018935] [G loss: 0.043172] [d1 loss: 0.086454] [d2 loss: 0.175658]  [sq d1 d2: 0.007957]  [num0: 14.000000] [num1 50.000000]
[Epoch 378/500] [Batch 580/676] [D loss: -0.034744] [G loss: 0.109504] [d1 loss: 0.041339] [d2 loss: 0.045504]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 378/500] [Batch 600/676] [D loss: -0.009981] [G loss: 0.133992] [d1 loss: 0.049918] [d2 loss: 0.059590]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 378/500] [Batch 620/676] [D loss: -0.022278] [G loss: 0.147142] [d1 loss: 0.051930] [d2 loss: 0.064103]  [sq d1 d2: 0.000148]  [num0: 16.000000] [num1 48.000000]
[Epoch 378/500] [Batch 640/676] [D loss: -0.045005] [G loss: 0.159475] [d1 loss: 0.052994] [d2 loss: 0.046339]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 378/500] [Batch 660/676] [D loss: -0.040956] [G loss: 0.185929] [d1 loss: 0.053948] [d2 loss: 0.048273]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 379/500] [Batch 0/676] [D loss: -0.013171] [G loss: 0.167237] [d1 loss: 0.071476] [d2 loss: 0.075864]  [sq d1 d2: 0.000019]  [num0: 13.000000] [num1 51.000000]
[Epoch 379/500] [Batch 20/676] [D loss: -0.026686] [G loss: 0.132059] [d1 loss: 0.053477] [d2 loss: 0.050513]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 40/676] [D loss: 0.011930] [G loss: 0.101627] [d1 loss: 0.102838] [d2 loss: 0.101324]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 379/500] [Batch 60/676] [D loss: -0.035169] [G loss: 0.096127] [d1 loss: 0.066513] [d2 loss: 0.074802]  [sq d1 d2: 0.000069]  [num0: 20.000000] [num1 44.000000]
[Epoch 379/500] [Batch 80/676] [D loss: -0.010481] [G loss: 0.097355] [d1 loss: 0.032402] [d2 loss: 0.043399]  [sq d1 d2: 0.000121]  [num0: 17.000000] [num1 47.000000]
[Epoch 379/500] [Batch 100/676] [D loss: 0.015382] [G loss: 0.083856] [d1 loss: 0.067767] [d2 loss: 0.059055]  [sq d1 d2: 0.000076]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 120/676] [D loss: 0.013877] [G loss: 0.041684] [d1 loss: 0.211952] [d2 loss: 0.152419]  [sq d1 d2: 0.003544]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 140/676] [D loss: 0.003270] [G loss: 0.024819] [d1 loss: 0.052687] [d2 loss: 0.065045]  [sq d1 d2: 0.000153]  [num0: 15.000000] [num1 49.000000]
[Epoch 379/500] [Batch 160/676] [D loss: 0.001061] [G loss: -0.022377] [d1 loss: 0.083009] [d2 loss: 0.085046]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 180/676] [D loss: -0.002700] [G loss: -0.090311] [d1 loss: 0.088896] [d2 loss: 0.101245]  [sq d1 d2: 0.000153]  [num0: 15.000000] [num1 49.000000]
[Epoch 379/500] [Batch 200/676] [D loss: -0.016100] [G loss: -0.171678] [d1 loss: 0.044071] [d2 loss: 0.048161]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 220/676] [D loss: 0.002777] [G loss: -0.264584] [d1 loss: 0.076841] [d2 loss: 0.069338]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 379/500] [Batch 240/676] [D loss: -0.021468] [G loss: -0.321990] [d1 loss: 0.039291] [d2 loss: 0.047677]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 260/676] [D loss: -0.014745] [G loss: -0.346136] [d1 loss: 0.067412] [d2 loss: 0.075860]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 280/676] [D loss: -0.001196] [G loss: -0.378562] [d1 loss: 0.055223] [d2 loss: 0.095339]  [sq d1 d2: 0.001609]  [num0: 18.000000] [num1 46.000000]
[Epoch 379/500] [Batch 300/676] [D loss: 0.009176] [G loss: -0.382925] [d1 loss: 0.064284] [d2 loss: 0.054767]  [sq d1 d2: 0.000091]  [num0: 20.000000] [num1 44.000000]
[Epoch 379/500] [Batch 320/676] [D loss: 0.011825] [G loss: -0.306806] [d1 loss: 0.032461] [d2 loss: 0.029897]  [sq d1 d2: 0.000007]  [num0: 19.000000] [num1 45.000000]
[Epoch 379/500] [Batch 340/676] [D loss: 0.023797] [G loss: -0.253720] [d1 loss: 0.124113] [d2 loss: 0.120518]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 360/676] [D loss: 0.011728] [G loss: -0.200314] [d1 loss: 0.053670] [d2 loss: 0.038101]  [sq d1 d2: 0.000242]  [num0: 18.000000] [num1 46.000000]
[Epoch 379/500] [Batch 380/676] [D loss: 0.008109] [G loss: -0.112790] [d1 loss: 0.034327] [d2 loss: 0.040276]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 400/676] [D loss: 0.005886] [G loss: -0.065427] [d1 loss: 0.055718] [d2 loss: 0.057950]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 420/676] [D loss: 0.003603] [G loss: -0.025010] [d1 loss: 0.076689] [d2 loss: 0.086063]  [sq d1 d2: 0.000088]  [num0: 18.000000] [num1 46.000000]
[Epoch 379/500] [Batch 440/676] [D loss: 0.000685] [G loss: -0.005701] [d1 loss: 0.082511] [d2 loss: 0.087751]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 460/676] [D loss: -0.009393] [G loss: 0.020662] [d1 loss: 0.110250] [d2 loss: 0.111237]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 480/676] [D loss: -0.009634] [G loss: 0.064087] [d1 loss: 0.037660] [d2 loss: 0.043928]  [sq d1 d2: 0.000039]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 500/676] [D loss: -0.053963] [G loss: 0.094691] [d1 loss: 0.035850] [d2 loss: 0.045536]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 520/676] [D loss: 0.009569] [G loss: 0.161399] [d1 loss: 0.050962] [d2 loss: 0.050072]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 379/500] [Batch 540/676] [D loss: 0.005375] [G loss: 0.166697] [d1 loss: 0.075881] [d2 loss: 0.104420]  [sq d1 d2: 0.000815]  [num0: 15.000000] [num1 49.000000]
[Epoch 379/500] [Batch 560/676] [D loss: 0.003917] [G loss: 0.153173] [d1 loss: 0.078330] [d2 loss: 0.100969]  [sq d1 d2: 0.000513]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 580/676] [D loss: 0.026245] [G loss: 0.146538] [d1 loss: 0.046858] [d2 loss: 0.046707]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 379/500] [Batch 600/676] [D loss: 0.003279] [G loss: 0.130811] [d1 loss: 0.047590] [d2 loss: 0.049275]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 620/676] [D loss: 0.007838] [G loss: 0.077919] [d1 loss: 0.059791] [d2 loss: 0.067257]  [sq d1 d2: 0.000056]  [num0: 14.000000] [num1 50.000000]
[Epoch 379/500] [Batch 640/676] [D loss: 0.013193] [G loss: 0.009269] [d1 loss: 0.077040] [d2 loss: 0.066383]  [sq d1 d2: 0.000114]  [num0: 19.000000] [num1 45.000000]
[Epoch 379/500] [Batch 660/676] [D loss: -0.008916] [G loss: -0.017909] [d1 loss: 0.070220] [d2 loss: 0.072362]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 0/676] [D loss: -0.000497] [G loss: -0.065176] [d1 loss: 0.049292] [d2 loss: 0.066416]  [sq d1 d2: 0.000293]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 20/676] [D loss: -0.005205] [G loss: -0.123131] [d1 loss: 0.149178] [d2 loss: 0.147829]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 40/676] [D loss: -0.000740] [G loss: -0.149028] [d1 loss: 0.057332] [d2 loss: 0.062012]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 60/676] [D loss: -0.018457] [G loss: -0.206341] [d1 loss: 0.065866] [d2 loss: 0.072129]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 80/676] [D loss: -0.022153] [G loss: -0.279566] [d1 loss: 0.153346] [d2 loss: 0.131243]  [sq d1 d2: 0.000489]  [num0: 17.000000] [num1 47.000000]
[Epoch 380/500] [Batch 100/676] [D loss: -0.017925] [G loss: -0.328680] [d1 loss: 0.101961] [d2 loss: 0.148005]  [sq d1 d2: 0.002120]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 120/676] [D loss: -0.048559] [G loss: -0.347834] [d1 loss: 0.081238] [d2 loss: 0.081111]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]

[Epoch 380/500] [Batch 140/676] [D loss: -0.000920] [G loss: -0.408098] [d1 loss: 0.050420] [d2 loss: 0.044989]  [sq d1 d2: 0.000029]  [num0: 14.000000] [num1 50.000000]
[Epoch 380/500] [Batch 160/676] [D loss: -0.008943] [G loss: -0.408884] [d1 loss: 0.098774] [d2 loss: 0.127619]  [sq d1 d2: 0.000832]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 180/676] [D loss: -0.005343] [G loss: -0.389544] [d1 loss: 0.132545] [d2 loss: 0.160965]  [sq d1 d2: 0.000808]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 200/676] [D loss: 0.025296] [G loss: -0.278428] [d1 loss: 0.098696] [d2 loss: 0.105975]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 220/676] [D loss: 0.006725] [G loss: -0.201529] [d1 loss: 0.056020] [d2 loss: 0.068444]  [sq d1 d2: 0.000154]  [num0: 17.000000] [num1 47.000000]
[Epoch 380/500] [Batch 240/676] [D loss: 0.001470] [G loss: -0.121915] [d1 loss: 0.081732] [d2 loss: 0.090514]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 260/676] [D loss: 0.001390] [G loss: -0.088725] [d1 loss: 0.089272] [d2 loss: 0.074544]  [sq d1 d2: 0.000217]  [num0: 17.000000] [num1 47.000000]
[Epoch 380/500] [Batch 280/676] [D loss: 0.001360] [G loss: -0.071646] [d1 loss: 0.049562] [d2 loss: 0.043219]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 300/676] [D loss: -0.001839] [G loss: -0.015821] [d1 loss: 0.106563] [d2 loss: 0.100166]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 320/676] [D loss: -0.026543] [G loss: 0.015707] [d1 loss: 0.032692] [d2 loss: 0.030276]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 380/500] [Batch 340/676] [D loss: -0.022231] [G loss: 0.062331] [d1 loss: 0.081054] [d2 loss: 0.076107]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 360/676] [D loss: -0.019559] [G loss: 0.088993] [d1 loss: 0.052576] [d2 loss: 0.042741]  [sq d1 d2: 0.000097]  [num0: 12.000000] [num1 52.000000]
[Epoch 380/500] [Batch 380/676] [D loss: -0.010376] [G loss: 0.128196] [d1 loss: 0.098677] [d2 loss: 0.112983]  [sq d1 d2: 0.000205]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 400/676] [D loss: -0.043579] [G loss: 0.189293] [d1 loss: 0.059171] [d2 loss: 0.051226]  [sq d1 d2: 0.000063]  [num0: 13.000000] [num1 51.000000]
[Epoch 380/500] [Batch 420/676] [D loss: -0.039749] [G loss: 0.183114] [d1 loss: 0.067536] [d2 loss: 0.075497]  [sq d1 d2: 0.000063]  [num0: 19.000000] [num1 45.000000]
[Epoch 380/500] [Batch 440/676] [D loss: 0.013143] [G loss: 0.151819] [d1 loss: 0.066794] [d2 loss: 0.057014]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 460/676] [D loss: -0.011370] [G loss: 0.120684] [d1 loss: 0.080782] [d2 loss: 0.087050]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 480/676] [D loss: -0.011048] [G loss: 0.107655] [d1 loss: 0.062665] [d2 loss: 0.070825]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 500/676] [D loss: 0.001776] [G loss: 0.053994] [d1 loss: 0.107573] [d2 loss: 0.105535]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 380/500] [Batch 520/676] [D loss: -0.002777] [G loss: 0.044562] [d1 loss: 0.071906] [d2 loss: 0.087927]  [sq d1 d2: 0.000257]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 540/676] [D loss: 0.003297] [G loss: 0.008452] [d1 loss: 0.148003] [d2 loss: 0.177760]  [sq d1 d2: 0.000885]  [num0: 9.000000] [num1 55.000000]
[Epoch 380/500] [Batch 560/676] [D loss: -0.011624] [G loss: -0.029138] [d1 loss: 0.096086] [d2 loss: 0.055365]  [sq d1 d2: 0.001658]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 580/676] [D loss: -0.014017] [G loss: -0.098466] [d1 loss: 0.038762] [d2 loss: 0.033951]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 380/500] [Batch 600/676] [D loss: 0.008069] [G loss: -0.138704] [d1 loss: 0.111535] [d2 loss: 0.113045]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 380/500] [Batch 620/676] [D loss: 0.000235] [G loss: -0.205887] [d1 loss: 0.085089] [d2 loss: 0.087740]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 380/500] [Batch 640/676] [D loss: -0.004887] [G loss: -0.252729] [d1 loss: 0.073389] [d2 loss: 0.076801]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 380/500] [Batch 660/676] [D loss: 0.017908] [G loss: -0.329997] [d1 loss: 0.072180] [d2 loss: 0.077030]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 0/676] [D loss: -0.014643] [G loss: -0.373963] [d1 loss: 0.138899] [d2 loss: 0.124084]  [sq d1 d2: 0.000220]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 20/676] [D loss: -0.012917] [G loss: -0.408768] [d1 loss: 0.084016] [d2 loss: 0.109153]  [sq d1 d2: 0.000632]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 40/676] [D loss: -0.026170] [G loss: -0.433761] [d1 loss: 0.058155] [d2 loss: 0.105675]  [sq d1 d2: 0.002258]  [num0: 14.000000] [num1 50.000000]
[Epoch 381/500] [Batch 60/676] [D loss: 0.012527] [G loss: -0.469398] [d1 loss: 0.062449] [d2 loss: 0.049363]  [sq d1 d2: 0.000171]  [num0: 14.000000] [num1 50.000000]
[Epoch 381/500] [Batch 80/676] [D loss: -0.008435] [G loss: -0.386954] [d1 loss: 0.061490] [d2 loss: 0.063447]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 100/676] [D loss: 0.017209] [G loss: -0.355927] [d1 loss: 0.165137] [d2 loss: 0.160433]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 381/500] [Batch 120/676] [D loss: 0.009604] [G loss: -0.254799] [d1 loss: 0.017095] [d2 loss: 0.017554]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 140/676] [D loss: 0.001566] [G loss: -0.144769] [d1 loss: 0.066467] [d2 loss: 0.082320]  [sq d1 d2: 0.000251]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 160/676] [D loss: -0.008677] [G loss: -0.101614] [d1 loss: 0.020087] [d2 loss: 0.033326]  [sq d1 d2: 0.000175]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 180/676] [D loss: -0.022353] [G loss: -0.042589] [d1 loss: 0.164114] [d2 loss: 0.191578]  [sq d1 d2: 0.000754]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 200/676] [D loss: -0.009150] [G loss: 0.009111] [d1 loss: 0.071322] [d2 loss: 0.068177]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 220/676] [D loss: -0.013118] [G loss: 0.031068] [d1 loss: 0.028830] [d2 loss: 0.027624]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 240/676] [D loss: -0.022417] [G loss: 0.085498] [d1 loss: 0.071363] [d2 loss: 0.059371]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 381/500] [Batch 260/676] [D loss: -0.021743] [G loss: 0.098675] [d1 loss: 0.046674] [d2 loss: 0.049089]  [sq d1 d2: 0.000006]  [num0: 10.000000] [num1 54.000000]
[Epoch 381/500] [Batch 280/676] [D loss: -0.027273] [G loss: 0.129844] [d1 loss: 0.060713] [d2 loss: 0.062236]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 381/500] [Batch 300/676] [D loss: -0.028295] [G loss: 0.123020] [d1 loss: 0.115388] [d2 loss: 0.070417]  [sq d1 d2: 0.002022]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 320/676] [D loss: -0.001074] [G loss: 0.083064] [d1 loss: 0.034679] [d2 loss: 0.044016]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 340/676] [D loss: 0.009142] [G loss: 0.052711] [d1 loss: 0.112525] [d2 loss: 0.114091]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 381/500] [Batch 360/676] [D loss: -0.001040] [G loss: 0.035556] [d1 loss: 0.081274] [d2 loss: 0.087319]  [sq d1 d2: 0.000037]  [num0: 13.000000] [num1 51.000000]
[Epoch 381/500] [Batch 380/676] [D loss: -0.001002] [G loss: -0.017897] [d1 loss: 0.082245] [d2 loss: 0.061180]  [sq d1 d2: 0.000444]  [num0: 12.000000] [num1 52.000000]
[Epoch 381/500] [Batch 400/676] [D loss: 0.004802] [G loss: -0.068933] [d1 loss: 0.030234] [d2 loss: 0.038270]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 381/500] [Batch 420/676] [D loss: -0.010720] [G loss: -0.083195] [d1 loss: 0.122333] [d2 loss: 0.122063]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 381/500] [Batch 440/676] [D loss: -0.005586] [G loss: -0.084275] [d1 loss: 0.108332] [d2 loss: 0.096984]  [sq d1 d2: 0.000129]  [num0: 16.000000] [num1 48.000000]
[Epoch 381/500] [Batch 460/676] [D loss: -0.009648] [G loss: -0.125008] [d1 loss: 0.065665] [d2 loss: 0.060088]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 480/676] [D loss: -0.006005] [G loss: -0.168741] [d1 loss: 0.042823] [d2 loss: 0.041311]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]

[Epoch 381/500] [Batch 500/676] [D loss: -0.026446] [G loss: -0.206361] [d1 loss: 0.050844] [d2 loss: 0.053098]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 520/676] [D loss: -0.018317] [G loss: -0.193701] [d1 loss: 0.086931] [d2 loss: 0.074372]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 540/676] [D loss: -0.041070] [G loss: -0.191798] [d1 loss: 0.057613] [d2 loss: 0.066271]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 381/500] [Batch 560/676] [D loss: -0.016385] [G loss: -0.259232] [d1 loss: 0.150025] [d2 loss: 0.178226]  [sq d1 d2: 0.000795]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 580/676] [D loss: -0.011613] [G loss: -0.290352] [d1 loss: 0.081271] [d2 loss: 0.089987]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 600/676] [D loss: -0.019744] [G loss: -0.265005] [d1 loss: 0.075689] [d2 loss: 0.054359]  [sq d1 d2: 0.000455]  [num0: 14.000000] [num1 50.000000]
[Epoch 381/500] [Batch 620/676] [D loss: 0.001996] [G loss: -0.187142] [d1 loss: 0.062773] [d2 loss: 0.066474]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 381/500] [Batch 640/676] [D loss: 0.011676] [G loss: -0.103884] [d1 loss: 0.157967] [d2 loss: 0.130089]  [sq d1 d2: 0.000777]  [num0: 15.000000] [num1 49.000000]
[Epoch 381/500] [Batch 660/676] [D loss: 0.005584] [G loss: -0.032014] [d1 loss: 0.098313] [d2 loss: 0.119272]  [sq d1 d2: 0.000439]  [num0: 18.000000] [num1 46.000000]
[Epoch 382/500] [Batch 0/676] [D loss: -0.000377] [G loss: -0.024205] [d1 loss: 0.021208] [d2 loss: 0.020410]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 20/676] [D loss: -0.008158] [G loss: 0.031820] [d1 loss: 0.088893] [d2 loss: 0.090871]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 40/676] [D loss: -0.010958] [G loss: 0.057809] [d1 loss: 0.093709] [d2 loss: 0.087261]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 60/676] [D loss: -0.024638] [G loss: 0.088312] [d1 loss: 0.106542] [d2 loss: 0.092223]  [sq d1 d2: 0.000205]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 80/676] [D loss: -0.008607] [G loss: 0.125712] [d1 loss: 0.032843] [d2 loss: 0.032797]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 100/676] [D loss: -0.014620] [G loss: 0.178833] [d1 loss: 0.050778] [d2 loss: 0.057162]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 120/676] [D loss: -0.011950] [G loss: 0.207102] [d1 loss: 0.058189] [d2 loss: 0.068994]  [sq d1 d2: 0.000117]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 140/676] [D loss: -0.032751] [G loss: 0.224833] [d1 loss: 0.051932] [d2 loss: 0.061651]  [sq d1 d2: 0.000094]  [num0: 20.000000] [num1 44.000000]
[Epoch 382/500] [Batch 160/676] [D loss: -0.003000] [G loss: 0.249058] [d1 loss: 0.041910] [d2 loss: 0.034498]  [sq d1 d2: 0.000055]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 180/676] [D loss: -0.012547] [G loss: 0.247713] [d1 loss: 0.056588] [d2 loss: 0.048531]  [sq d1 d2: 0.000065]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 200/676] [D loss: 0.013780] [G loss: 0.240687] [d1 loss: 0.044111] [d2 loss: 0.052580]  [sq d1 d2: 0.000072]  [num0: 18.000000] [num1 46.000000]
[Epoch 382/500] [Batch 220/676] [D loss: -0.008569] [G loss: 0.173563] [d1 loss: 0.052424] [d2 loss: 0.041763]  [sq d1 d2: 0.000114]  [num0: 19.000000] [num1 45.000000]
[Epoch 382/500] [Batch 240/676] [D loss: 0.008837] [G loss: 0.112718] [d1 loss: 0.069022] [d2 loss: 0.076335]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 260/676] [D loss: -0.006545] [G loss: 0.061659] [d1 loss: 0.075417] [d2 loss: 0.072510]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 280/676] [D loss: -0.001474] [G loss: 0.027071] [d1 loss: 0.042152] [d2 loss: 0.036394]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 300/676] [D loss: -0.005086] [G loss: -0.000083] [d1 loss: 0.029252] [d2 loss: 0.029207]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 382/500] [Batch 320/676] [D loss: 0.001942] [G loss: -0.039287] [d1 loss: 0.046046] [d2 loss: 0.026683]  [sq d1 d2: 0.000375]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 340/676] [D loss: -0.006526] [G loss: -0.081167] [d1 loss: 0.096471] [d2 loss: 0.070814]  [sq d1 d2: 0.000658]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 360/676] [D loss: -0.013289] [G loss: -0.146218] [d1 loss: 0.112078] [d2 loss: 0.093484]  [sq d1 d2: 0.000346]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 380/676] [D loss: -0.033239] [G loss: -0.196243] [d1 loss: 0.044733] [d2 loss: 0.040684]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 382/500] [Batch 400/676] [D loss: 0.002408] [G loss: -0.248533] [d1 loss: 0.100972] [d2 loss: 0.112937]  [sq d1 d2: 0.000143]  [num0: 19.000000] [num1 45.000000]
[Epoch 382/500] [Batch 420/676] [D loss: -0.011128] [G loss: -0.244385] [d1 loss: 0.058648] [d2 loss: 0.052878]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 440/676] [D loss: -0.007949] [G loss: -0.286197] [d1 loss: 0.056550] [d2 loss: 0.062100]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 460/676] [D loss: -0.002828] [G loss: -0.287700] [d1 loss: 0.040259] [d2 loss: 0.036697]  [sq d1 d2: 0.000013]  [num0: 20.000000] [num1 44.000000]
[Epoch 382/500] [Batch 480/676] [D loss: -0.011849] [G loss: -0.291327] [d1 loss: 0.148700] [d2 loss: 0.146517]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 500/676] [D loss: 0.020557] [G loss: -0.239519] [d1 loss: 0.051254] [d2 loss: 0.050834]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 520/676] [D loss: 0.023064] [G loss: -0.182392] [d1 loss: 0.028573] [d2 loss: 0.028221]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 382/500] [Batch 540/676] [D loss: 0.006501] [G loss: -0.138658] [d1 loss: 0.043177] [d2 loss: 0.037892]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 560/676] [D loss: -0.002144] [G loss: -0.099665] [d1 loss: 0.018354] [d2 loss: 0.023535]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 382/500] [Batch 580/676] [D loss: -0.003895] [G loss: -0.063941] [d1 loss: 0.104656] [d2 loss: 0.119983]  [sq d1 d2: 0.000235]  [num0: 14.000000] [num1 50.000000]
[Epoch 382/500] [Batch 600/676] [D loss: -0.010746] [G loss: -0.004840] [d1 loss: 0.037776] [d2 loss: 0.043508]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 620/676] [D loss: -0.012850] [G loss: 0.016054] [d1 loss: 0.042733] [d2 loss: 0.046441]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 382/500] [Batch 640/676] [D loss: -0.009642] [G loss: 0.080888] [d1 loss: 0.088498] [d2 loss: 0.088801]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 382/500] [Batch 660/676] [D loss: 0.000137] [G loss: 0.135473] [d1 loss: 0.106207] [d2 loss: 0.071830]  [sq d1 d2: 0.001182]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 0/676] [D loss: -0.001947] [G loss: 0.139300] [d1 loss: 0.123580] [d2 loss: 0.158666]  [sq d1 d2: 0.001231]  [num0: 20.000000] [num1 44.000000]
[Epoch 383/500] [Batch 20/676] [D loss: -0.029275] [G loss: 0.211119] [d1 loss: 0.090596] [d2 loss: 0.082075]  [sq d1 d2: 0.000073]  [num0: 17.000000] [num1 47.000000]
[Epoch 383/500] [Batch 40/676] [D loss: 0.018507] [G loss: 0.246322] [d1 loss: 0.060259] [d2 loss: 0.058724]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 383/500] [Batch 60/676] [D loss: 0.023586] [G loss: 0.221854] [d1 loss: 0.033007] [d2 loss: 0.026562]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 383/500] [Batch 80/676] [D loss: -0.014427] [G loss: 0.186112] [d1 loss: 0.033452] [d2 loss: 0.034266]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 383/500] [Batch 100/676] [D loss: 0.016591] [G loss: 0.194365] [d1 loss: 0.072996] [d2 loss: 0.064384]  [sq d1 d2: 0.000074]  [num0: 11.000000] [num1 53.000000]
[Epoch 383/500] [Batch 120/676] [D loss: 0.002376] [G loss: 0.136000] [d1 loss: 0.031360] [d2 loss: 0.030791]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 383/500] [Batch 140/676] [D loss: -0.002954] [G loss: 0.108274] [d1 loss: 0.060000] [d2 loss: 0.071183]  [sq d1 d2: 0.000125]  [num0: 13.000000] [num1 51.000000]
[Epoch 383/500] [Batch 160/676] [D loss: 0.016611] [G loss: 0.055244] [d1 loss: 0.059803] [d2 loss: 0.057417]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]

[Epoch 383/500] [Batch 180/676] [D loss: -0.002381] [G loss: 0.001897] [d1 loss: 0.053774] [d2 loss: 0.085936]  [sq d1 d2: 0.001034]  [num0: 14.000000] [num1 50.000000]
[Epoch 383/500] [Batch 200/676] [D loss: -0.008810] [G loss: -0.068944] [d1 loss: 0.022647] [d2 loss: 0.020732]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 383/500] [Batch 220/676] [D loss: -0.014786] [G loss: -0.130846] [d1 loss: 0.052389] [d2 loss: 0.051113]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 240/676] [D loss: 0.002219] [G loss: -0.171777] [d1 loss: 0.057175] [d2 loss: 0.057952]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 383/500] [Batch 260/676] [D loss: -0.018706] [G loss: -0.227834] [d1 loss: 0.081334] [d2 loss: 0.092399]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 280/676] [D loss: 0.003232] [G loss: -0.274845] [d1 loss: 0.037681] [d2 loss: 0.042708]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 383/500] [Batch 300/676] [D loss: -0.015312] [G loss: -0.286667] [d1 loss: 0.172965] [d2 loss: 0.113648]  [sq d1 d2: 0.003519]  [num0: 16.000000] [num1 48.000000]
[Epoch 383/500] [Batch 320/676] [D loss: 0.005623] [G loss: -0.330881] [d1 loss: 0.027151] [d2 loss: 0.030980]  [sq d1 d2: 0.000015]  [num0: 11.000000] [num1 53.000000]
[Epoch 383/500] [Batch 340/676] [D loss: -0.002800] [G loss: -0.320772] [d1 loss: 0.049560] [d2 loss: 0.065590]  [sq d1 d2: 0.000257]  [num0: 14.000000] [num1 50.000000]
[Epoch 383/500] [Batch 360/676] [D loss: 0.003930] [G loss: -0.341200] [d1 loss: 0.097810] [d2 loss: 0.087999]  [sq d1 d2: 0.000096]  [num0: 19.000000] [num1 45.000000]
[Epoch 383/500] [Batch 380/676] [D loss: 0.021454] [G loss: -0.215426] [d1 loss: 0.020561] [d2 loss: 0.019230]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 383/500] [Batch 400/676] [D loss: 0.011714] [G loss: -0.144851] [d1 loss: 0.060343] [d2 loss: 0.052092]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 420/676] [D loss: 0.000088] [G loss: -0.099060] [d1 loss: 0.076067] [d2 loss: 0.088334]  [sq d1 d2: 0.000150]  [num0: 19.000000] [num1 45.000000]
[Epoch 383/500] [Batch 440/676] [D loss: -0.002448] [G loss: -0.056420] [d1 loss: 0.068454] [d2 loss: 0.067806]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 383/500] [Batch 460/676] [D loss: -0.002765] [G loss: -0.021176] [d1 loss: 0.025456] [d2 loss: 0.026254]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 383/500] [Batch 480/676] [D loss: -0.005340] [G loss: -0.003607] [d1 loss: 0.051322] [d2 loss: 0.064402]  [sq d1 d2: 0.000171]  [num0: 18.000000] [num1 46.000000]
[Epoch 383/500] [Batch 500/676] [D loss: 0.001319] [G loss: 0.032336] [d1 loss: 0.018246] [d2 loss: 0.022270]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 383/500] [Batch 520/676] [D loss: -0.013214] [G loss: 0.116929] [d1 loss: 0.063263] [d2 loss: 0.065001]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 383/500] [Batch 540/676] [D loss: -0.023294] [G loss: 0.165266] [d1 loss: 0.058664] [d2 loss: 0.072445]  [sq d1 d2: 0.000190]  [num0: 9.000000] [num1 55.000000]
[Epoch 383/500] [Batch 560/676] [D loss: -0.004034] [G loss: 0.202406] [d1 loss: 0.117911] [d2 loss: 0.072992]  [sq d1 d2: 0.002018]  [num0: 13.000000] [num1 51.000000]
[Epoch 383/500] [Batch 580/676] [D loss: -0.008389] [G loss: 0.224797] [d1 loss: 0.054516] [d2 loss: 0.052806]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 383/500] [Batch 600/676] [D loss: 0.009965] [G loss: 0.264408] [d1 loss: 0.076791] [d2 loss: 0.098059]  [sq d1 d2: 0.000452]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 620/676] [D loss: -0.000502] [G loss: 0.198958] [d1 loss: 0.070257] [d2 loss: 0.036658]  [sq d1 d2: 0.001129]  [num0: 15.000000] [num1 49.000000]
[Epoch 383/500] [Batch 640/676] [D loss: 0.002426] [G loss: 0.233654] [d1 loss: 0.020154] [d2 loss: 0.021411]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 383/500] [Batch 660/676] [D loss: 0.002189] [G loss: 0.205309] [d1 loss: 0.080940] [d2 loss: 0.061949]  [sq d1 d2: 0.000361]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 0/676] [D loss: 0.007114] [G loss: 0.206142] [d1 loss: 0.043073] [d2 loss: 0.041648]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 20/676] [D loss: 0.017262] [G loss: 0.177754] [d1 loss: 0.013738] [d2 loss: 0.017194]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 40/676] [D loss: -0.000504] [G loss: 0.163038] [d1 loss: 0.107954] [d2 loss: 0.112379]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 60/676] [D loss: 0.011099] [G loss: 0.120353] [d1 loss: 0.053040] [d2 loss: 0.051668]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 384/500] [Batch 80/676] [D loss: -0.000980] [G loss: 0.094355] [d1 loss: 0.083384] [d2 loss: 0.078089]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 384/500] [Batch 100/676] [D loss: -0.001770] [G loss: 0.038255] [d1 loss: 0.068685] [d2 loss: 0.059052]  [sq d1 d2: 0.000093]  [num0: 19.000000] [num1 45.000000]
[Epoch 384/500] [Batch 120/676] [D loss: -0.012208] [G loss: -0.001901] [d1 loss: 0.048807] [d2 loss: 0.048581]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 384/500] [Batch 140/676] [D loss: -0.015011] [G loss: -0.017215] [d1 loss: 0.011058] [d2 loss: 0.012880]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 160/676] [D loss: -0.012959] [G loss: -0.040839] [d1 loss: 0.021124] [d2 loss: 0.030616]  [sq d1 d2: 0.000090]  [num0: 18.000000] [num1 46.000000]
[Epoch 384/500] [Batch 180/676] [D loss: -0.000974] [G loss: -0.061383] [d1 loss: 0.028941] [d2 loss: 0.024155]  [sq d1 d2: 0.000023]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 200/676] [D loss: -0.013930] [G loss: -0.116844] [d1 loss: 0.037946] [d2 loss: 0.034663]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 384/500] [Batch 220/676] [D loss: -0.011131] [G loss: -0.132915] [d1 loss: 0.043801] [d2 loss: 0.046905]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 240/676] [D loss: -0.019734] [G loss: -0.097238] [d1 loss: 0.128166] [d2 loss: 0.125462]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 260/676] [D loss: -0.004687] [G loss: -0.126232] [d1 loss: 0.105072] [d2 loss: 0.104345]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 384/500] [Batch 280/676] [D loss: 0.010064] [G loss: -0.125031] [d1 loss: 0.098329] [d2 loss: 0.099946]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 300/676] [D loss: -0.004382] [G loss: -0.101638] [d1 loss: 0.088508] [d2 loss: 0.120003]  [sq d1 d2: 0.000992]  [num0: 16.000000] [num1 48.000000]
[Epoch 384/500] [Batch 320/676] [D loss: -0.008744] [G loss: -0.110638] [d1 loss: 0.044253] [d2 loss: 0.037658]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 340/676] [D loss: -0.003027] [G loss: -0.104081] [d1 loss: 0.044481] [d2 loss: 0.044689]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 360/676] [D loss: -0.007516] [G loss: -0.077518] [d1 loss: 0.082502] [d2 loss: 0.085259]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 380/676] [D loss: -0.009878] [G loss: -0.118550] [d1 loss: 0.033858] [d2 loss: 0.040339]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 384/500] [Batch 400/676] [D loss: -0.016899] [G loss: -0.122653] [d1 loss: 0.053396] [d2 loss: 0.059676]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 420/676] [D loss: -0.032248] [G loss: -0.138073] [d1 loss: 0.054805] [d2 loss: 0.046785]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 384/500] [Batch 440/676] [D loss: -0.015412] [G loss: -0.183616] [d1 loss: 0.116006] [d2 loss: 0.109884]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 460/676] [D loss: -0.010978] [G loss: -0.197494] [d1 loss: 0.088510] [d2 loss: 0.042591]  [sq d1 d2: 0.002109]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 480/676] [D loss: -0.025583] [G loss: -0.183687] [d1 loss: 0.040458] [d2 loss: 0.040540]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 384/500] [Batch 500/676] [D loss: -0.019536] [G loss: -0.259730] [d1 loss: 0.071607] [d2 loss: 0.091970]  [sq d1 d2: 0.000415]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 520/676] [D loss: 0.010692] [G loss: -0.236316] [d1 loss: 0.065569] [d2 loss: 0.079626]  [sq d1 d2: 0.000198]  [num0: 14.000000] [num1 50.000000]

[Epoch 384/500] [Batch 540/676] [D loss: 0.024245] [G loss: -0.216384] [d1 loss: 0.089648] [d2 loss: 0.059756]  [sq d1 d2: 0.000894]  [num0: 10.000000] [num1 54.000000]
[Epoch 384/500] [Batch 560/676] [D loss: -0.011240] [G loss: -0.195342] [d1 loss: 0.077407] [d2 loss: 0.071339]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 384/500] [Batch 580/676] [D loss: -0.004019] [G loss: -0.165151] [d1 loss: 0.109478] [d2 loss: 0.110086]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 384/500] [Batch 600/676] [D loss: -0.002887] [G loss: -0.202875] [d1 loss: 0.064884] [d2 loss: 0.057024]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 620/676] [D loss: -0.008161] [G loss: -0.208501] [d1 loss: 0.040534] [d2 loss: 0.032824]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 384/500] [Batch 640/676] [D loss: -0.014671] [G loss: -0.210775] [d1 loss: 0.097419] [d2 loss: 0.110202]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 384/500] [Batch 660/676] [D loss: -0.019050] [G loss: -0.226436] [d1 loss: 0.043163] [d2 loss: 0.039958]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 0/676] [D loss: -0.015976] [G loss: -0.254394] [d1 loss: 0.037994] [d2 loss: 0.038845]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 385/500] [Batch 20/676] [D loss: -0.018609] [G loss: -0.244177] [d1 loss: 0.020680] [d2 loss: 0.030592]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]
[Epoch 385/500] [Batch 40/676] [D loss: -0.029768] [G loss: -0.222550] [d1 loss: 0.012621] [d2 loss: 0.016663]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 385/500] [Batch 60/676] [D loss: -0.013894] [G loss: -0.198924] [d1 loss: 0.064464] [d2 loss: 0.078794]  [sq d1 d2: 0.000205]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 80/676] [D loss: -0.007585] [G loss: -0.168870] [d1 loss: 0.051878] [d2 loss: 0.058073]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 385/500] [Batch 100/676] [D loss: 0.001893] [G loss: -0.119150] [d1 loss: 0.053815] [d2 loss: 0.071597]  [sq d1 d2: 0.000316]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 120/676] [D loss: 0.000194] [G loss: -0.065425] [d1 loss: 0.029464] [d2 loss: 0.082181]  [sq d1 d2: 0.002779]  [num0: 12.000000] [num1 52.000000]
[Epoch 385/500] [Batch 140/676] [D loss: -0.006880] [G loss: -0.019964] [d1 loss: 0.055344] [d2 loss: 0.061573]  [sq d1 d2: 0.000039]  [num0: 11.000000] [num1 53.000000]
[Epoch 385/500] [Batch 160/676] [D loss: -0.005795] [G loss: 0.023262] [d1 loss: 0.037031] [d2 loss: 0.061345]  [sq d1 d2: 0.000591]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 180/676] [D loss: 0.001916] [G loss: 0.070068] [d1 loss: 0.021233] [d2 loss: 0.027192]  [sq d1 d2: 0.000036]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 200/676] [D loss: -0.004368] [G loss: 0.123098] [d1 loss: 0.021768] [d2 loss: 0.039047]  [sq d1 d2: 0.000299]  [num0: 13.000000] [num1 51.000000]
[Epoch 385/500] [Batch 220/676] [D loss: -0.015783] [G loss: 0.112132] [d1 loss: 0.065936] [d2 loss: 0.073110]  [sq d1 d2: 0.000051]  [num0: 19.000000] [num1 45.000000]
[Epoch 385/500] [Batch 240/676] [D loss: -0.003628] [G loss: 0.125114] [d1 loss: 0.029463] [d2 loss: 0.040416]  [sq d1 d2: 0.000120]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 260/676] [D loss: -0.003860] [G loss: 0.138933] [d1 loss: 0.042079] [d2 loss: 0.032154]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 385/500] [Batch 280/676] [D loss: -0.003093] [G loss: 0.186362] [d1 loss: 0.057098] [d2 loss: 0.089595]  [sq d1 d2: 0.001056]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 300/676] [D loss: -0.002318] [G loss: 0.187611] [d1 loss: 0.082733] [d2 loss: 0.077592]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 320/676] [D loss: 0.004243] [G loss: 0.238589] [d1 loss: 0.065445] [d2 loss: 0.054283]  [sq d1 d2: 0.000125]  [num0: 13.000000] [num1 51.000000]
[Epoch 385/500] [Batch 340/676] [D loss: 0.002157] [G loss: 0.255924] [d1 loss: 0.021916] [d2 loss: 0.024769]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 360/676] [D loss: -0.004310] [G loss: 0.254898] [d1 loss: 0.099058] [d2 loss: 0.098758]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 380/676] [D loss: -0.019025] [G loss: 0.255974] [d1 loss: 0.044658] [d2 loss: 0.044357]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 385/500] [Batch 400/676] [D loss: 0.001169] [G loss: 0.248208] [d1 loss: 0.209316] [d2 loss: 0.163937]  [sq d1 d2: 0.002059]  [num0: 12.000000] [num1 52.000000]
[Epoch 385/500] [Batch 420/676] [D loss: -0.019953] [G loss: 0.206516] [d1 loss: 0.093417] [d2 loss: 0.065764]  [sq d1 d2: 0.000765]  [num0: 14.000000] [num1 50.000000]
[Epoch 385/500] [Batch 440/676] [D loss: 0.000825] [G loss: 0.188386] [d1 loss: 0.051707] [d2 loss: 0.062376]  [sq d1 d2: 0.000114]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 460/676] [D loss: -0.024440] [G loss: 0.238134] [d1 loss: 0.034988] [d2 loss: 0.038328]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 480/676] [D loss: 0.000892] [G loss: 0.231598] [d1 loss: 0.055000] [d2 loss: 0.055897]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 500/676] [D loss: -0.010814] [G loss: 0.189508] [d1 loss: 0.054473] [d2 loss: 0.054068]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 520/676] [D loss: -0.017387] [G loss: 0.191280] [d1 loss: 0.067768] [d2 loss: 0.072872]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 385/500] [Batch 540/676] [D loss: -0.007878] [G loss: 0.197304] [d1 loss: 0.116332] [d2 loss: 0.120197]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 385/500] [Batch 560/676] [D loss: -0.009510] [G loss: 0.122653] [d1 loss: 0.079254] [d2 loss: 0.060037]  [sq d1 d2: 0.000369]  [num0: 19.000000] [num1 45.000000]
[Epoch 385/500] [Batch 580/676] [D loss: -0.004504] [G loss: 0.110492] [d1 loss: 0.029679] [d2 loss: 0.031980]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 385/500] [Batch 600/676] [D loss: -0.012617] [G loss: 0.042914] [d1 loss: 0.034238] [d2 loss: 0.044763]  [sq d1 d2: 0.000111]  [num0: 12.000000] [num1 52.000000]
[Epoch 385/500] [Batch 620/676] [D loss: 0.008908] [G loss: 0.041015] [d1 loss: 0.044059] [d2 loss: 0.036645]  [sq d1 d2: 0.000055]  [num0: 15.000000] [num1 49.000000]
[Epoch 385/500] [Batch 640/676] [D loss: 0.001413] [G loss: 0.006823] [d1 loss: 0.070693] [d2 loss: 0.098606]  [sq d1 d2: 0.000779]  [num0: 17.000000] [num1 47.000000]
[Epoch 385/500] [Batch 660/676] [D loss: -0.008683] [G loss: -0.023522] [d1 loss: 0.053483] [d2 loss: 0.062286]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 0/676] [D loss: -0.003120] [G loss: -0.011959] [d1 loss: 0.041976] [d2 loss: 0.039599]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 386/500] [Batch 20/676] [D loss: -0.015544] [G loss: -0.050927] [d1 loss: 0.085093] [d2 loss: 0.073414]  [sq d1 d2: 0.000136]  [num0: 17.000000] [num1 47.000000]
[Epoch 386/500] [Batch 40/676] [D loss: -0.011297] [G loss: -0.082840] [d1 loss: 0.058467] [d2 loss: 0.043893]  [sq d1 d2: 0.000212]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 60/676] [D loss: -0.018489] [G loss: -0.108656] [d1 loss: 0.065404] [d2 loss: 0.057370]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 386/500] [Batch 80/676] [D loss: -0.008687] [G loss: -0.117122] [d1 loss: 0.020635] [d2 loss: 0.017828]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 100/676] [D loss: -0.022469] [G loss: -0.138190] [d1 loss: 0.110793] [d2 loss: 0.095867]  [sq d1 d2: 0.000223]  [num0: 18.000000] [num1 46.000000]
[Epoch 386/500] [Batch 120/676] [D loss: -0.001563] [G loss: -0.137733] [d1 loss: 0.058925] [d2 loss: 0.059458]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 386/500] [Batch 140/676] [D loss: -0.007838] [G loss: -0.108494] [d1 loss: 0.062466] [d2 loss: 0.109855]  [sq d1 d2: 0.002246]  [num0: 11.000000] [num1 53.000000]
[Epoch 386/500] [Batch 160/676] [D loss: -0.012518] [G loss: -0.114962] [d1 loss: 0.025295] [d2 loss: 0.028813]  [sq d1 d2: 0.000012]  [num0: 19.000000] [num1 45.000000]
[Epoch 386/500] [Batch 180/676] [D loss: -0.018429] [G loss: -0.092569] [d1 loss: 0.049230] [d2 loss: 0.049820]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 386/500] [Batch 200/676] [D loss: 0.006060] [G loss: -0.072499] [d1 loss: 0.050383] [d2 loss: 0.051806]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]

[Epoch 386/500] [Batch 220/676] [D loss: -0.002479] [G loss: -0.069998] [d1 loss: 0.039827] [d2 loss: 0.037080]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 386/500] [Batch 240/676] [D loss: -0.005236] [G loss: -0.072405] [d1 loss: 0.099582] [d2 loss: 0.087456]  [sq d1 d2: 0.000147]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 260/676] [D loss: -0.005470] [G loss: -0.040113] [d1 loss: 0.023559] [d2 loss: 0.020525]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 386/500] [Batch 280/676] [D loss: -0.016078] [G loss: -0.037437] [d1 loss: 0.025283] [d2 loss: 0.025615]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 300/676] [D loss: -0.009752] [G loss: -0.029856] [d1 loss: 0.130624] [d2 loss: 0.095918]  [sq d1 d2: 0.001204]  [num0: 15.000000] [num1 49.000000]
[Epoch 386/500] [Batch 320/676] [D loss: -0.010902] [G loss: -0.053622] [d1 loss: 0.093184] [d2 loss: 0.088693]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 386/500] [Batch 340/676] [D loss: -0.028737] [G loss: -0.051638] [d1 loss: 0.019680] [d2 loss: 0.020499]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 386/500] [Batch 360/676] [D loss: -0.015426] [G loss: 0.024469] [d1 loss: 0.128344] [d2 loss: 0.096438]  [sq d1 d2: 0.001018]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 380/676] [D loss: -0.014052] [G loss: 0.026511] [d1 loss: 0.060975] [d2 loss: 0.075001]  [sq d1 d2: 0.000197]  [num0: 12.000000] [num1 52.000000]
[Epoch 386/500] [Batch 400/676] [D loss: -0.009071] [G loss: 0.042812] [d1 loss: 0.049710] [d2 loss: 0.048873]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 386/500] [Batch 420/676] [D loss: 0.003121] [G loss: 0.052100] [d1 loss: 0.111296] [d2 loss: 0.118823]  [sq d1 d2: 0.000057]  [num0: 19.000000] [num1 45.000000]
[Epoch 386/500] [Batch 440/676] [D loss: 0.001743] [G loss: 0.047728] [d1 loss: 0.057305] [d2 loss: 0.060602]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 386/500] [Batch 460/676] [D loss: -0.007935] [G loss: 0.017089] [d1 loss: 0.187653] [d2 loss: 0.157888]  [sq d1 d2: 0.000886]  [num0: 17.000000] [num1 47.000000]
[Epoch 386/500] [Batch 480/676] [D loss: -0.011906] [G loss: 0.045807] [d1 loss: 0.042521] [d2 loss: 0.055652]  [sq d1 d2: 0.000172]  [num0: 13.000000] [num1 51.000000]
[Epoch 386/500] [Batch 500/676] [D loss: 0.002769] [G loss: 0.063116] [d1 loss: 0.071977] [d2 loss: 0.044491]  [sq d1 d2: 0.000756]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 520/676] [D loss: -0.001763] [G loss: 0.061952] [d1 loss: 0.084705] [d2 loss: 0.087908]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 386/500] [Batch 540/676] [D loss: -0.002121] [G loss: 0.051020] [d1 loss: 0.017710] [d2 loss: 0.023215]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 386/500] [Batch 560/676] [D loss: -0.006491] [G loss: 0.060804] [d1 loss: 0.043905] [d2 loss: 0.035822]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 580/676] [D loss: -0.009631] [G loss: 0.063411] [d1 loss: 0.073262] [d2 loss: 0.120930]  [sq d1 d2: 0.002272]  [num0: 12.000000] [num1 52.000000]
[Epoch 386/500] [Batch 600/676] [D loss: -0.019557] [G loss: 0.034534] [d1 loss: 0.008033] [d2 loss: 0.008279]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 386/500] [Batch 620/676] [D loss: -0.013682] [G loss: 0.003736] [d1 loss: 0.031811] [d2 loss: 0.034002]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 386/500] [Batch 640/676] [D loss: -0.012129] [G loss: -0.006655] [d1 loss: 0.044291] [d2 loss: 0.043500]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 386/500] [Batch 660/676] [D loss: -0.025054] [G loss: -0.038200] [d1 loss: 0.040821] [d2 loss: 0.032640]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 0/676] [D loss: -0.019853] [G loss: -0.059779] [d1 loss: 0.062540] [d2 loss: 0.055574]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 20/676] [D loss: 0.002114] [G loss: -0.084108] [d1 loss: 0.087360] [d2 loss: 0.086762]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 40/676] [D loss: 0.010913] [G loss: -0.129599] [d1 loss: 0.124802] [d2 loss: 0.126071]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 60/676] [D loss: 0.012414] [G loss: -0.125023] [d1 loss: 0.067657] [d2 loss: 0.057796]  [sq d1 d2: 0.000097]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 80/676] [D loss: -0.004298] [G loss: -0.118707] [d1 loss: 0.061069] [d2 loss: 0.059585]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 387/500] [Batch 100/676] [D loss: -0.011244] [G loss: -0.085686] [d1 loss: 0.099197] [d2 loss: 0.115613]  [sq d1 d2: 0.000269]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 120/676] [D loss: 0.000682] [G loss: -0.126375] [d1 loss: 0.070511] [d2 loss: 0.066227]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 387/500] [Batch 140/676] [D loss: 0.005765] [G loss: -0.103042] [d1 loss: 0.100010] [d2 loss: 0.094875]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 160/676] [D loss: -0.003144] [G loss: -0.131152] [d1 loss: 0.028612] [d2 loss: 0.022500]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 180/676] [D loss: -0.022345] [G loss: -0.133786] [d1 loss: 0.060069] [d2 loss: 0.071244]  [sq d1 d2: 0.000125]  [num0: 16.000000] [num1 48.000000]
[Epoch 387/500] [Batch 200/676] [D loss: -0.007399] [G loss: -0.109596] [d1 loss: 0.038224] [d2 loss: 0.059035]  [sq d1 d2: 0.000433]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 220/676] [D loss: -0.015014] [G loss: -0.115863] [d1 loss: 0.136096] [d2 loss: 0.159418]  [sq d1 d2: 0.000544]  [num0: 12.000000] [num1 52.000000]
[Epoch 387/500] [Batch 240/676] [D loss: -0.007455] [G loss: -0.092924] [d1 loss: 0.044676] [d2 loss: 0.038425]  [sq d1 d2: 0.000039]  [num0: 15.000000] [num1 49.000000]
[Epoch 387/500] [Batch 260/676] [D loss: 0.000873] [G loss: -0.099467] [d1 loss: 0.164095] [d2 loss: 0.203699]  [sq d1 d2: 0.001568]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 280/676] [D loss: -0.018090] [G loss: -0.106183] [d1 loss: 0.073011] [d2 loss: 0.055154]  [sq d1 d2: 0.000319]  [num0: 16.000000] [num1 48.000000]
[Epoch 387/500] [Batch 300/676] [D loss: -0.000957] [G loss: -0.101081] [d1 loss: 0.049284] [d2 loss: 0.085536]  [sq d1 d2: 0.001314]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 320/676] [D loss: -0.020349] [G loss: -0.092050] [d1 loss: 0.058078] [d2 loss: 0.050215]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 340/676] [D loss: -0.001743] [G loss: -0.055313] [d1 loss: 0.104529] [d2 loss: 0.091770]  [sq d1 d2: 0.000163]  [num0: 16.000000] [num1 48.000000]
[Epoch 387/500] [Batch 360/676] [D loss: 0.002799] [G loss: -0.049554] [d1 loss: 0.066606] [d2 loss: 0.079980]  [sq d1 d2: 0.000179]  [num0: 16.000000] [num1 48.000000]
[Epoch 387/500] [Batch 380/676] [D loss: -0.003438] [G loss: -0.024968] [d1 loss: 0.031277] [d2 loss: 0.040239]  [sq d1 d2: 0.000080]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 400/676] [D loss: -0.007228] [G loss: -0.037395] [d1 loss: 0.027013] [d2 loss: 0.031579]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 387/500] [Batch 420/676] [D loss: -0.013894] [G loss: -0.012238] [d1 loss: 0.034965] [d2 loss: 0.031266]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 440/676] [D loss: -0.004193] [G loss: 0.014787] [d1 loss: 0.016636] [d2 loss: 0.015879]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 460/676] [D loss: -0.021838] [G loss: 0.034434] [d1 loss: 0.013008] [d2 loss: 0.015952]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 480/676] [D loss: -0.026663] [G loss: 0.025977] [d1 loss: 0.077442] [d2 loss: 0.067722]  [sq d1 d2: 0.000094]  [num0: 19.000000] [num1 45.000000]
[Epoch 387/500] [Batch 500/676] [D loss: -0.009110] [G loss: 0.051874] [d1 loss: 0.069029] [d2 loss: 0.079813]  [sq d1 d2: 0.000116]  [num0: 13.000000] [num1 51.000000]
[Epoch 387/500] [Batch 520/676] [D loss: -0.002316] [G loss: 0.070450] [d1 loss: 0.086923] [d2 loss: 0.057882]  [sq d1 d2: 0.000843]  [num0: 17.000000] [num1 47.000000]

[Epoch 387/500] [Batch 540/676] [D loss: -0.003514] [G loss: 0.065774] [d1 loss: 0.049988] [d2 loss: 0.059955]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 560/676] [D loss: -0.012257] [G loss: 0.070351] [d1 loss: 0.032922] [d2 loss: 0.027335]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 387/500] [Batch 580/676] [D loss: -0.014949] [G loss: 0.075911] [d1 loss: 0.089230] [d2 loss: 0.091327]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 600/676] [D loss: 0.004128] [G loss: 0.092359] [d1 loss: 0.081631] [d2 loss: 0.097520]  [sq d1 d2: 0.000252]  [num0: 15.000000] [num1 49.000000]
[Epoch 387/500] [Batch 620/676] [D loss: -0.026152] [G loss: 0.079721] [d1 loss: 0.042555] [d2 loss: 0.043914]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 387/500] [Batch 640/676] [D loss: -0.008389] [G loss: 0.064846] [d1 loss: 0.116196] [d2 loss: 0.083451]  [sq d1 d2: 0.001072]  [num0: 14.000000] [num1 50.000000]
[Epoch 387/500] [Batch 660/676] [D loss: -0.006561] [G loss: 0.050981] [d1 loss: 0.042886] [d2 loss: 0.034301]  [sq d1 d2: 0.000074]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 0/676] [D loss: -0.011499] [G loss: 0.096691] [d1 loss: 0.062301] [d2 loss: 0.067290]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]
[Epoch 388/500] [Batch 20/676] [D loss: -0.016039] [G loss: 0.111405] [d1 loss: 0.012285] [d2 loss: 0.018031]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 40/676] [D loss: -0.008642] [G loss: 0.100746] [d1 loss: 0.034259] [d2 loss: 0.049049]  [sq d1 d2: 0.000219]  [num0: 17.000000] [num1 47.000000]
[Epoch 388/500] [Batch 60/676] [D loss: -0.003303] [G loss: 0.090744] [d1 loss: 0.069309] [d2 loss: 0.069681]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 388/500] [Batch 80/676] [D loss: 0.001986] [G loss: 0.116046] [d1 loss: 0.075069] [d2 loss: 0.119841]  [sq d1 d2: 0.002005]  [num0: 15.000000] [num1 49.000000]
[Epoch 388/500] [Batch 100/676] [D loss: -0.019318] [G loss: 0.099895] [d1 loss: 0.092187] [d2 loss: 0.075748]  [sq d1 d2: 0.000270]  [num0: 15.000000] [num1 49.000000]
[Epoch 388/500] [Batch 120/676] [D loss: -0.008764] [G loss: 0.075816] [d1 loss: 0.125038] [d2 loss: 0.125164]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 388/500] [Batch 140/676] [D loss: -0.019898] [G loss: 0.093147] [d1 loss: 0.036403] [d2 loss: 0.041387]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 160/676] [D loss: 0.005314] [G loss: 0.096964] [d1 loss: 0.100533] [d2 loss: 0.090157]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 180/676] [D loss: -0.025787] [G loss: 0.103749] [d1 loss: 0.032335] [d2 loss: 0.037783]  [sq d1 d2: 0.000030]  [num0: 19.000000] [num1 45.000000]
[Epoch 388/500] [Batch 200/676] [D loss: -0.011034] [G loss: 0.081743] [d1 loss: 0.009493] [d2 loss: 0.013972]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 220/676] [D loss: -0.013428] [G loss: 0.083848] [d1 loss: 0.051902] [d2 loss: 0.055499]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 388/500] [Batch 240/676] [D loss: -0.007677] [G loss: 0.064601] [d1 loss: 0.063282] [d2 loss: 0.089986]  [sq d1 d2: 0.000713]  [num0: 20.000000] [num1 44.000000]
[Epoch 388/500] [Batch 260/676] [D loss: 0.013722] [G loss: 0.076028] [d1 loss: 0.085358] [d2 loss: 0.058998]  [sq d1 d2: 0.000695]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 280/676] [D loss: -0.006739] [G loss: 0.065551] [d1 loss: 0.053811] [d2 loss: 0.079213]  [sq d1 d2: 0.000645]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 300/676] [D loss: -0.000782] [G loss: 0.050897] [d1 loss: 0.024258] [d2 loss: 0.027907]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 388/500] [Batch 320/676] [D loss: -0.010875] [G loss: 0.028522] [d1 loss: 0.096493] [d2 loss: 0.099834]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 388/500] [Batch 340/676] [D loss: -0.011593] [G loss: -0.003027] [d1 loss: 0.077847] [d2 loss: 0.076668]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 388/500] [Batch 360/676] [D loss: -0.006592] [G loss: -0.025723] [d1 loss: 0.131545] [d2 loss: 0.143028]  [sq d1 d2: 0.000132]  [num0: 20.000000] [num1 44.000000]
[Epoch 388/500] [Batch 380/676] [D loss: -0.000006] [G loss: -0.029065] [d1 loss: 0.101425] [d2 loss: 0.099129]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 388/500] [Batch 400/676] [D loss: -0.013921] [G loss: -0.005129] [d1 loss: 0.091446] [d2 loss: 0.127371]  [sq d1 d2: 0.001291]  [num0: 13.000000] [num1 51.000000]
[Epoch 388/500] [Batch 420/676] [D loss: -0.014522] [G loss: -0.019915] [d1 loss: 0.045640] [d2 loss: 0.043176]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 440/676] [D loss: -0.005817] [G loss: -0.087283] [d1 loss: 0.066190] [d2 loss: 0.071825]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 388/500] [Batch 460/676] [D loss: -0.028655] [G loss: -0.079609] [d1 loss: 0.050773] [d2 loss: 0.050489]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 388/500] [Batch 480/676] [D loss: -0.001376] [G loss: -0.106944] [d1 loss: 0.055072] [d2 loss: 0.045985]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 388/500] [Batch 500/676] [D loss: -0.015273] [G loss: -0.132534] [d1 loss: 0.055998] [d2 loss: 0.073457]  [sq d1 d2: 0.000305]  [num0: 17.000000] [num1 47.000000]
[Epoch 388/500] [Batch 520/676] [D loss: -0.004332] [G loss: -0.151310] [d1 loss: 0.114647] [d2 loss: 0.126568]  [sq d1 d2: 0.000142]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 540/676] [D loss: -0.020443] [G loss: -0.153518] [d1 loss: 0.086187] [d2 loss: 0.091740]  [sq d1 d2: 0.000031]  [num0: 20.000000] [num1 44.000000]
[Epoch 388/500] [Batch 560/676] [D loss: -0.005681] [G loss: -0.181996] [d1 loss: 0.043100] [d2 loss: 0.048052]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 388/500] [Batch 580/676] [D loss: -0.021061] [G loss: -0.137622] [d1 loss: 0.118741] [d2 loss: 0.143460]  [sq d1 d2: 0.000611]  [num0: 14.000000] [num1 50.000000]
[Epoch 388/500] [Batch 600/676] [D loss: -0.016628] [G loss: -0.164774] [d1 loss: 0.148261] [d2 loss: 0.171368]  [sq d1 d2: 0.000534]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 620/676] [D loss: -0.004320] [G loss: -0.170447] [d1 loss: 0.114449] [d2 loss: 0.104440]  [sq d1 d2: 0.000100]  [num0: 16.000000] [num1 48.000000]
[Epoch 388/500] [Batch 640/676] [D loss: -0.009228] [G loss: -0.170021] [d1 loss: 0.050062] [d2 loss: 0.049150]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 388/500] [Batch 660/676] [D loss: -0.010970] [G loss: -0.159439] [d1 loss: 0.049051] [d2 loss: 0.057690]  [sq d1 d2: 0.000075]  [num0: 19.000000] [num1 45.000000]
[Epoch 389/500] [Batch 0/676] [D loss: 0.005045] [G loss: -0.168085] [d1 loss: 0.052868] [d2 loss: 0.056256]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 20/676] [D loss: -0.001349] [G loss: -0.146693] [d1 loss: 0.074712] [d2 loss: 0.078662]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 389/500] [Batch 40/676] [D loss: -0.002681] [G loss: -0.132235] [d1 loss: 0.042143] [d2 loss: 0.027539]  [sq d1 d2: 0.000213]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 60/676] [D loss: -0.011443] [G loss: -0.137433] [d1 loss: 0.110252] [d2 loss: 0.133158]  [sq d1 d2: 0.000525]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 80/676] [D loss: -0.008774] [G loss: -0.144643] [d1 loss: 0.167240] [d2 loss: 0.182952]  [sq d1 d2: 0.000247]  [num0: 17.000000] [num1 47.000000]
[Epoch 389/500] [Batch 100/676] [D loss: -0.002983] [G loss: -0.120442] [d1 loss: 0.208525] [d2 loss: 0.148754]  [sq d1 d2: 0.003573]  [num0: 18.000000] [num1 46.000000]
[Epoch 389/500] [Batch 120/676] [D loss: -0.000095] [G loss: -0.125623] [d1 loss: 0.031308] [d2 loss: 0.046198]  [sq d1 d2: 0.000222]  [num0: 11.000000] [num1 53.000000]
[Epoch 389/500] [Batch 140/676] [D loss: -0.008241] [G loss: -0.105689] [d1 loss: 0.031661] [d2 loss: 0.034684]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 160/676] [D loss: -0.010312] [G loss: -0.123233] [d1 loss: 0.045947] [d2 loss: 0.064805]  [sq d1 d2: 0.000356]  [num0: 20.000000] [num1 44.000000]
[Epoch 389/500] [Batch 180/676] [D loss: -0.014491] [G loss: -0.119876] [d1 loss: 0.090037] [d2 loss: 0.090146]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 389/500] [Batch 200/676] [D loss: -0.011602] [G loss: -0.128774] [d1 loss: 0.082068] [d2 loss: 0.082481]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]

[Epoch 389/500] [Batch 220/676] [D loss: -0.007375] [G loss: -0.112332] [d1 loss: 0.028602] [d2 loss: 0.029681]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 240/676] [D loss: -0.016908] [G loss: -0.122025] [d1 loss: 0.094720] [d2 loss: 0.105642]  [sq d1 d2: 0.000119]  [num0: 14.000000] [num1 50.000000]
[Epoch 389/500] [Batch 260/676] [D loss: -0.003532] [G loss: -0.115272] [d1 loss: 0.033090] [d2 loss: 0.033244]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 280/676] [D loss: -0.023199] [G loss: -0.114776] [d1 loss: 0.038645] [d2 loss: 0.028601]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 300/676] [D loss: -0.009137] [G loss: -0.120965] [d1 loss: 0.067266] [d2 loss: 0.084441]  [sq d1 d2: 0.000295]  [num0: 20.000000] [num1 44.000000]
[Epoch 389/500] [Batch 320/676] [D loss: -0.004081] [G loss: -0.122295] [d1 loss: 0.060634] [d2 loss: 0.092728]  [sq d1 d2: 0.001030]  [num0: 17.000000] [num1 47.000000]
[Epoch 389/500] [Batch 340/676] [D loss: -0.009827] [G loss: -0.128596] [d1 loss: 0.050445] [d2 loss: 0.051968]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 389/500] [Batch 360/676] [D loss: -0.009911] [G loss: -0.086232] [d1 loss: 0.031089] [d2 loss: 0.052212]  [sq d1 d2: 0.000446]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 380/676] [D loss: -0.014646] [G loss: -0.083542] [d1 loss: 0.065392] [d2 loss: 0.050662]  [sq d1 d2: 0.000217]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 400/676] [D loss: -0.001743] [G loss: -0.076001] [d1 loss: 0.114053] [d2 loss: 0.098967]  [sq d1 d2: 0.000228]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 420/676] [D loss: -0.007655] [G loss: -0.081299] [d1 loss: 0.011479] [d2 loss: 0.012605]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 440/676] [D loss: 0.000361] [G loss: -0.034525] [d1 loss: 0.018131] [d2 loss: 0.027288]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 460/676] [D loss: -0.021618] [G loss: -0.028256] [d1 loss: 0.045589] [d2 loss: 0.037836]  [sq d1 d2: 0.000060]  [num0: 12.000000] [num1 52.000000]
[Epoch 389/500] [Batch 480/676] [D loss: -0.010723] [G loss: -0.015423] [d1 loss: 0.138410] [d2 loss: 0.122432]  [sq d1 d2: 0.000255]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 500/676] [D loss: -0.009743] [G loss: -0.033859] [d1 loss: 0.043782] [d2 loss: 0.057722]  [sq d1 d2: 0.000194]  [num0: 18.000000] [num1 46.000000]
[Epoch 389/500] [Batch 520/676] [D loss: -0.013193] [G loss: -0.009297] [d1 loss: 0.134798] [d2 loss: 0.160485]  [sq d1 d2: 0.000660]  [num0: 14.000000] [num1 50.000000]
[Epoch 389/500] [Batch 540/676] [D loss: -0.002554] [G loss: 0.012029] [d1 loss: 0.046934] [d2 loss: 0.042228]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 560/676] [D loss: -0.004835] [G loss: 0.031995] [d1 loss: 0.057140] [d2 loss: 0.060680]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 389/500] [Batch 580/676] [D loss: -0.003751] [G loss: 0.063327] [d1 loss: 0.050446] [d2 loss: 0.067715]  [sq d1 d2: 0.000298]  [num0: 18.000000] [num1 46.000000]
[Epoch 389/500] [Batch 600/676] [D loss: -0.000548] [G loss: 0.074445] [d1 loss: 0.098828] [d2 loss: 0.104392]  [sq d1 d2: 0.000031]  [num0: 20.000000] [num1 44.000000]
[Epoch 389/500] [Batch 620/676] [D loss: -0.009149] [G loss: 0.053423] [d1 loss: 0.109500] [d2 loss: 0.124036]  [sq d1 d2: 0.000211]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 640/676] [D loss: -0.013456] [G loss: 0.069814] [d1 loss: 0.059069] [d2 loss: 0.055873]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 389/500] [Batch 660/676] [D loss: -0.006230] [G loss: 0.087123] [d1 loss: 0.019824] [d2 loss: 0.027210]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 390/500] [Batch 0/676] [D loss: -0.004548] [G loss: 0.065161] [d1 loss: 0.017557] [d2 loss: 0.017680]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 390/500] [Batch 20/676] [D loss: -0.007048] [G loss: 0.067302] [d1 loss: 0.063084] [d2 loss: 0.072962]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 390/500] [Batch 40/676] [D loss: -0.012533] [G loss: 0.098298] [d1 loss: 0.079233] [d2 loss: 0.080746]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 390/500] [Batch 60/676] [D loss: -0.007356] [G loss: 0.052956] [d1 loss: 0.075189] [d2 loss: 0.066989]  [sq d1 d2: 0.000067]  [num0: 14.000000] [num1 50.000000]
[Epoch 390/500] [Batch 80/676] [D loss: -0.001649] [G loss: 0.038026] [d1 loss: 0.073666] [d2 loss: 0.078087]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 390/500] [Batch 100/676] [D loss: -0.009014] [G loss: 0.025285] [d1 loss: 0.022908] [d2 loss: 0.027420]  [sq d1 d2: 0.000020]  [num0: 14.000000] [num1 50.000000]
[Epoch 390/500] [Batch 120/676] [D loss: -0.007495] [G loss: -0.000167] [d1 loss: 0.129227] [d2 loss: 0.127246]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 140/676] [D loss: -0.013176] [G loss: -0.059551] [d1 loss: 0.101245] [d2 loss: 0.144962]  [sq d1 d2: 0.001911]  [num0: 20.000000] [num1 44.000000]
[Epoch 390/500] [Batch 160/676] [D loss: -0.031435] [G loss: -0.078460] [d1 loss: 0.101597] [d2 loss: 0.114939]  [sq d1 d2: 0.000178]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 180/676] [D loss: -0.000338] [G loss: -0.072967] [d1 loss: 0.015111] [d2 loss: 0.027595]  [sq d1 d2: 0.000156]  [num0: 14.000000] [num1 50.000000]
[Epoch 390/500] [Batch 200/676] [D loss: 0.001670] [G loss: -0.082767] [d1 loss: 0.053352] [d2 loss: 0.055718]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 390/500] [Batch 220/676] [D loss: -0.012695] [G loss: -0.089143] [d1 loss: 0.036568] [d2 loss: 0.029803]  [sq d1 d2: 0.000046]  [num0: 21.000000] [num1 43.000000]
[Epoch 390/500] [Batch 240/676] [D loss: -0.019758] [G loss: -0.113550] [d1 loss: 0.044095] [d2 loss: 0.074172]  [sq d1 d2: 0.000905]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 260/676] [D loss: -0.020788] [G loss: -0.090541] [d1 loss: 0.038120] [d2 loss: 0.049236]  [sq d1 d2: 0.000124]  [num0: 13.000000] [num1 51.000000]
[Epoch 390/500] [Batch 280/676] [D loss: -0.004960] [G loss: -0.088734] [d1 loss: 0.108335] [d2 loss: 0.102492]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 300/676] [D loss: -0.004044] [G loss: -0.048877] [d1 loss: 0.114643] [d2 loss: 0.110570]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 390/500] [Batch 320/676] [D loss: -0.011264] [G loss: -0.056974] [d1 loss: 0.102453] [d2 loss: 0.101578]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 390/500] [Batch 340/676] [D loss: -0.009694] [G loss: -0.051578] [d1 loss: 0.126188] [d2 loss: 0.119256]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 360/676] [D loss: -0.020671] [G loss: -0.047553] [d1 loss: 0.080918] [d2 loss: 0.106550]  [sq d1 d2: 0.000657]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 380/676] [D loss: -0.024179] [G loss: -0.058136] [d1 loss: 0.074960] [d2 loss: 0.070302]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 390/500] [Batch 400/676] [D loss: -0.013085] [G loss: -0.025377] [d1 loss: 0.070665] [d2 loss: 0.096470]  [sq d1 d2: 0.000666]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 420/676] [D loss: -0.017762] [G loss: -0.037536] [d1 loss: 0.068584] [d2 loss: 0.082041]  [sq d1 d2: 0.000181]  [num0: 16.000000] [num1 48.000000]
[Epoch 390/500] [Batch 440/676] [D loss: 0.002651] [G loss: -0.026573] [d1 loss: 0.070906] [d2 loss: 0.105926]  [sq d1 d2: 0.001226]  [num0: 18.000000] [num1 46.000000]
[Epoch 390/500] [Batch 460/676] [D loss: -0.011541] [G loss: -0.021000] [d1 loss: 0.097574] [d2 loss: 0.093651]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 390/500] [Batch 480/676] [D loss: 0.006728] [G loss: -0.041274] [d1 loss: 0.044658] [d2 loss: 0.045548]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 390/500] [Batch 500/676] [D loss: -0.010865] [G loss: -0.035131] [d1 loss: 0.098115] [d2 loss: 0.071902]  [sq d1 d2: 0.000687]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 520/676] [D loss: -0.017523] [G loss: 0.018906] [d1 loss: 0.121287] [d2 loss: 0.132347]  [sq d1 d2: 0.000122]  [num0: 17.000000] [num1 47.000000]
[Epoch 390/500] [Batch 540/676] [D loss: -0.015701] [G loss: 0.002678] [d1 loss: 0.048055] [d2 loss: 0.080245]  [sq d1 d2: 0.001036]  [num0: 19.000000] [num1 45.000000]
[Epoch 390/500] [Batch 560/676] [D loss: -0.004254] [G loss: -0.029734] [d1 loss: 0.027919] [d2 loss: 0.021999]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]

[Epoch 390/500] [Batch 580/676] [D loss: -0.019643] [G loss: -0.038774] [d1 loss: 0.070388] [d2 loss: 0.087328]  [sq d1 d2: 0.000287]  [num0: 14.000000] [num1 50.000000]
[Epoch 390/500] [Batch 600/676] [D loss: -0.025971] [G loss: -0.001817] [d1 loss: 0.051888] [d2 loss: 0.038438]  [sq d1 d2: 0.000181]  [num0: 16.000000] [num1 48.000000]
[Epoch 390/500] [Batch 620/676] [D loss: -0.037686] [G loss: -0.009369] [d1 loss: 0.063074] [d2 loss: 0.054070]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 390/500] [Batch 640/676] [D loss: -0.004374] [G loss: 0.002977] [d1 loss: 0.045607] [d2 loss: 0.060999]  [sq d1 d2: 0.000237]  [num0: 13.000000] [num1 51.000000]
[Epoch 390/500] [Batch 660/676] [D loss: -0.004940] [G loss: 0.004179] [d1 loss: 0.111104] [d2 loss: 0.116632]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 391/500] [Batch 0/676] [D loss: -0.016293] [G loss: -0.021552] [d1 loss: 0.060845] [d2 loss: 0.061123]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 20/676] [D loss: -0.027716] [G loss: -0.052752] [d1 loss: 0.066642] [d2 loss: 0.031210]  [sq d1 d2: 0.001255]  [num0: 14.000000] [num1 50.000000]
[Epoch 391/500] [Batch 40/676] [D loss: -0.016686] [G loss: -0.065888] [d1 loss: 0.078228] [d2 loss: 0.083606]  [sq d1 d2: 0.000029]  [num0: 19.000000] [num1 45.000000]
[Epoch 391/500] [Batch 60/676] [D loss: -0.019349] [G loss: -0.037977] [d1 loss: 0.070047] [d2 loss: 0.057403]  [sq d1 d2: 0.000160]  [num0: 19.000000] [num1 45.000000]
[Epoch 391/500] [Batch 80/676] [D loss: -0.018343] [G loss: -0.026855] [d1 loss: 0.042477] [d2 loss: 0.038931]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 391/500] [Batch 100/676] [D loss: -0.031303] [G loss: -0.030721] [d1 loss: 0.097395] [d2 loss: 0.075730]  [sq d1 d2: 0.000469]  [num0: 15.000000] [num1 49.000000]
[Epoch 391/500] [Batch 120/676] [D loss: 0.005701] [G loss: -0.032402] [d1 loss: 0.082964] [d2 loss: 0.084619]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 391/500] [Batch 140/676] [D loss: -0.013471] [G loss: -0.016132] [d1 loss: 0.080602] [d2 loss: 0.083222]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 391/500] [Batch 160/676] [D loss: -0.004403] [G loss: 0.020978] [d1 loss: 0.021037] [d2 loss: 0.014173]  [sq d1 d2: 0.000047]  [num0: 11.000000] [num1 53.000000]
[Epoch 391/500] [Batch 180/676] [D loss: 0.014114] [G loss: 0.009148] [d1 loss: 0.047285] [d2 loss: 0.050798]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 391/500] [Batch 200/676] [D loss: -0.007896] [G loss: 0.005916] [d1 loss: 0.033855] [d2 loss: 0.036823]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 391/500] [Batch 220/676] [D loss: 0.002214] [G loss: 0.022157] [d1 loss: 0.084951] [d2 loss: 0.099926]  [sq d1 d2: 0.000224]  [num0: 16.000000] [num1 48.000000]
[Epoch 391/500] [Batch 240/676] [D loss: -0.002366] [G loss: 0.010612] [d1 loss: 0.079661] [d2 loss: 0.082066]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 260/676] [D loss: -0.006456] [G loss: 0.003713] [d1 loss: 0.151368] [d2 loss: 0.177717]  [sq d1 d2: 0.000694]  [num0: 17.000000] [num1 47.000000]
[Epoch 391/500] [Batch 280/676] [D loss: -0.010296] [G loss: 0.009609] [d1 loss: 0.055930] [d2 loss: 0.059551]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 391/500] [Batch 300/676] [D loss: -0.003703] [G loss: 0.028113] [d1 loss: 0.033192] [d2 loss: 0.033739]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 320/676] [D loss: -0.010076] [G loss: 0.026103] [d1 loss: 0.069842] [d2 loss: 0.062986]  [sq d1 d2: 0.000047]  [num0: 12.000000] [num1 52.000000]
[Epoch 391/500] [Batch 340/676] [D loss: 0.012629] [G loss: -0.038568] [d1 loss: 0.073858] [d2 loss: 0.095390]  [sq d1 d2: 0.000464]  [num0: 15.000000] [num1 49.000000]
[Epoch 391/500] [Batch 360/676] [D loss: -0.022426] [G loss: -0.044213] [d1 loss: 0.116489] [d2 loss: 0.096974]  [sq d1 d2: 0.000381]  [num0: 14.000000] [num1 50.000000]
[Epoch 391/500] [Batch 380/676] [D loss: 0.000580] [G loss: -0.061394] [d1 loss: 0.050152] [d2 loss: 0.062944]  [sq d1 d2: 0.000164]  [num0: 15.000000] [num1 49.000000]
[Epoch 391/500] [Batch 400/676] [D loss: -0.025620] [G loss: -0.080694] [d1 loss: 0.132204] [d2 loss: 0.124685]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 391/500] [Batch 420/676] [D loss: -0.001989] [G loss: -0.124900] [d1 loss: 0.170972] [d2 loss: 0.175349]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 391/500] [Batch 440/676] [D loss: -0.001184] [G loss: -0.114829] [d1 loss: 0.051310] [d2 loss: 0.045303]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 460/676] [D loss: -0.021479] [G loss: -0.145478] [d1 loss: 0.051367] [d2 loss: 0.047641]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 391/500] [Batch 480/676] [D loss: -0.031837] [G loss: -0.152385] [d1 loss: 0.054104] [d2 loss: 0.062610]  [sq d1 d2: 0.000072]  [num0: 15.000000] [num1 49.000000]
[Epoch 391/500] [Batch 500/676] [D loss: -0.008644] [G loss: -0.167277] [d1 loss: 0.057039] [d2 loss: 0.054665]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 520/676] [D loss: -0.000187] [G loss: -0.167600] [d1 loss: 0.013686] [d2 loss: 0.013568]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 391/500] [Batch 540/676] [D loss: -0.032162] [G loss: -0.141159] [d1 loss: 0.096156] [d2 loss: 0.080506]  [sq d1 d2: 0.000245]  [num0: 19.000000] [num1 45.000000]
[Epoch 391/500] [Batch 560/676] [D loss: -0.021673] [G loss: -0.142395] [d1 loss: 0.013777] [d2 loss: 0.017158]  [sq d1 d2: 0.000011]  [num0: 12.000000] [num1 52.000000]
[Epoch 391/500] [Batch 580/676] [D loss: -0.005363] [G loss: -0.144536] [d1 loss: 0.154128] [d2 loss: 0.169316]  [sq d1 d2: 0.000231]  [num0: 17.000000] [num1 47.000000]
[Epoch 391/500] [Batch 600/676] [D loss: 0.018140] [G loss: -0.144722] [d1 loss: 0.090745] [d2 loss: 0.113090]  [sq d1 d2: 0.000499]  [num0: 18.000000] [num1 46.000000]
[Epoch 391/500] [Batch 620/676] [D loss: -0.011286] [G loss: -0.153915] [d1 loss: 0.119797] [d2 loss: 0.128374]  [sq d1 d2: 0.000074]  [num0: 17.000000] [num1 47.000000]
[Epoch 391/500] [Batch 640/676] [D loss: -0.009054] [G loss: -0.147273] [d1 loss: 0.038587] [d2 loss: 0.041572]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 391/500] [Batch 660/676] [D loss: -0.021967] [G loss: -0.119633] [d1 loss: 0.082148] [d2 loss: 0.088160]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 392/500] [Batch 0/676] [D loss: 0.000951] [G loss: -0.120522] [d1 loss: 0.077576] [d2 loss: 0.070262]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 392/500] [Batch 20/676] [D loss: -0.023788] [G loss: -0.129551] [d1 loss: 0.024733] [d2 loss: 0.028660]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 392/500] [Batch 40/676] [D loss: -0.009268] [G loss: -0.127780] [d1 loss: 0.050032] [d2 loss: 0.052958]  [sq d1 d2: 0.000009]  [num0: 20.000000] [num1 44.000000]
[Epoch 392/500] [Batch 60/676] [D loss: -0.014900] [G loss: -0.098024] [d1 loss: 0.082604] [d2 loss: 0.104055]  [sq d1 d2: 0.000460]  [num0: 11.000000] [num1 53.000000]
[Epoch 392/500] [Batch 80/676] [D loss: -0.012914] [G loss: -0.097860] [d1 loss: 0.107361] [d2 loss: 0.110966]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 392/500] [Batch 100/676] [D loss: -0.009009] [G loss: -0.069503] [d1 loss: 0.055339] [d2 loss: 0.059030]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 120/676] [D loss: -0.018440] [G loss: -0.059544] [d1 loss: 0.044326] [d2 loss: 0.045163]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 140/676] [D loss: -0.024349] [G loss: -0.065759] [d1 loss: 0.080154] [d2 loss: 0.115664]  [sq d1 d2: 0.001261]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 160/676] [D loss: -0.019291] [G loss: -0.060175] [d1 loss: 0.035098] [d2 loss: 0.053986]  [sq d1 d2: 0.000357]  [num0: 13.000000] [num1 51.000000]
[Epoch 392/500] [Batch 180/676] [D loss: 0.001495] [G loss: -0.079020] [d1 loss: 0.021416] [d2 loss: 0.018490]  [sq d1 d2: 0.000009]  [num0: 11.000000] [num1 53.000000]
[Epoch 392/500] [Batch 200/676] [D loss: -0.010146] [G loss: -0.066204] [d1 loss: 0.070974] [d2 loss: 0.090187]  [sq d1 d2: 0.000369]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 220/676] [D loss: -0.001605] [G loss: -0.095485] [d1 loss: 0.030064] [d2 loss: 0.035968]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 240/676] [D loss: 0.003217] [G loss: -0.089416] [d1 loss: 0.057567] [d2 loss: 0.069182]  [sq d1 d2: 0.000135]  [num0: 22.000000] [num1 42.000000]

[Epoch 392/500] [Batch 260/676] [D loss: -0.003808] [G loss: -0.086016] [d1 loss: 0.061239] [d2 loss: 0.062322]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 280/676] [D loss: -0.016659] [G loss: -0.115535] [d1 loss: 0.033381] [d2 loss: 0.052083]  [sq d1 d2: 0.000350]  [num0: 15.000000] [num1 49.000000]
[Epoch 392/500] [Batch 300/676] [D loss: -0.015955] [G loss: -0.093859] [d1 loss: 0.110960] [d2 loss: 0.134968]  [sq d1 d2: 0.000576]  [num0: 13.000000] [num1 51.000000]
[Epoch 392/500] [Batch 320/676] [D loss: -0.024342] [G loss: -0.098621] [d1 loss: 0.052949] [d2 loss: 0.041700]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 340/676] [D loss: -0.028726] [G loss: -0.122554] [d1 loss: 0.104792] [d2 loss: 0.081398]  [sq d1 d2: 0.000547]  [num0: 13.000000] [num1 51.000000]
[Epoch 392/500] [Batch 360/676] [D loss: -0.013080] [G loss: -0.134866] [d1 loss: 0.047136] [d2 loss: 0.046621]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 380/676] [D loss: -0.011570] [G loss: -0.142439] [d1 loss: 0.026178] [d2 loss: 0.022701]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 392/500] [Batch 400/676] [D loss: -0.018377] [G loss: -0.149276] [d1 loss: 0.165156] [d2 loss: 0.173317]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 420/676] [D loss: -0.015975] [G loss: -0.142864] [d1 loss: 0.094530] [d2 loss: 0.136435]  [sq d1 d2: 0.001756]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 440/676] [D loss: -0.004695] [G loss: -0.164449] [d1 loss: 0.047159] [d2 loss: 0.054461]  [sq d1 d2: 0.000053]  [num0: 21.000000] [num1 43.000000]
[Epoch 392/500] [Batch 460/676] [D loss: -0.002298] [G loss: -0.151550] [d1 loss: 0.096003] [d2 loss: 0.085527]  [sq d1 d2: 0.000110]  [num0: 18.000000] [num1 46.000000]
[Epoch 392/500] [Batch 480/676] [D loss: -0.004426] [G loss: -0.142467] [d1 loss: 0.073018] [d2 loss: 0.060941]  [sq d1 d2: 0.000146]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 500/676] [D loss: -0.006967] [G loss: -0.143963] [d1 loss: 0.071078] [d2 loss: 0.068912]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 392/500] [Batch 520/676] [D loss: -0.000879] [G loss: -0.138582] [d1 loss: 0.100505] [d2 loss: 0.110666]  [sq d1 d2: 0.000103]  [num0: 13.000000] [num1 51.000000]
[Epoch 392/500] [Batch 540/676] [D loss: -0.011788] [G loss: -0.136218] [d1 loss: 0.085259] [d2 loss: 0.086592]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 392/500] [Batch 560/676] [D loss: -0.012977] [G loss: -0.132042] [d1 loss: 0.045004] [d2 loss: 0.056551]  [sq d1 d2: 0.000133]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 580/676] [D loss: -0.011358] [G loss: -0.095663] [d1 loss: 0.068224] [d2 loss: 0.093017]  [sq d1 d2: 0.000615]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 600/676] [D loss: 0.003622] [G loss: -0.089370] [d1 loss: 0.051582] [d2 loss: 0.052031]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 392/500] [Batch 620/676] [D loss: -0.026097] [G loss: -0.099793] [d1 loss: 0.026609] [d2 loss: 0.033710]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 392/500] [Batch 640/676] [D loss: -0.008685] [G loss: -0.111129] [d1 loss: 0.055683] [d2 loss: 0.056441]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 392/500] [Batch 660/676] [D loss: -0.004192] [G loss: -0.127233] [d1 loss: 0.024120] [d2 loss: 0.028613]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 393/500] [Batch 0/676] [D loss: -0.019712] [G loss: -0.118123] [d1 loss: 0.087591] [d2 loss: 0.096280]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 393/500] [Batch 20/676] [D loss: -0.018678] [G loss: -0.099109] [d1 loss: 0.033473] [d2 loss: 0.034858]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 393/500] [Batch 40/676] [D loss: -0.000225] [G loss: -0.096389] [d1 loss: 0.015001] [d2 loss: 0.018337]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 60/676] [D loss: -0.001033] [G loss: -0.099549] [d1 loss: 0.034531] [d2 loss: 0.056613]  [sq d1 d2: 0.000488]  [num0: 17.000000] [num1 47.000000]
[Epoch 393/500] [Batch 80/676] [D loss: 0.009037] [G loss: -0.093601] [d1 loss: 0.063801] [d2 loss: 0.111447]  [sq d1 d2: 0.002270]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 100/676] [D loss: -0.004542] [G loss: -0.112189] [d1 loss: 0.034985] [d2 loss: 0.047057]  [sq d1 d2: 0.000146]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 120/676] [D loss: 0.001919] [G loss: -0.124446] [d1 loss: 0.037071] [d2 loss: 0.032392]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 140/676] [D loss: -0.011614] [G loss: -0.111689] [d1 loss: 0.041863] [d2 loss: 0.035543]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 393/500] [Batch 160/676] [D loss: 0.006210] [G loss: -0.107149] [d1 loss: 0.011675] [d2 loss: 0.006281]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 393/500] [Batch 180/676] [D loss: -0.026501] [G loss: -0.096604] [d1 loss: 0.051203] [d2 loss: 0.049553]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 393/500] [Batch 200/676] [D loss: -0.012763] [G loss: -0.111070] [d1 loss: 0.088435] [d2 loss: 0.087146]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 220/676] [D loss: -0.013963] [G loss: -0.124023] [d1 loss: 0.161026] [d2 loss: 0.173014]  [sq d1 d2: 0.000144]  [num0: 17.000000] [num1 47.000000]
[Epoch 393/500] [Batch 240/676] [D loss: -0.026331] [G loss: -0.145708] [d1 loss: 0.071707] [d2 loss: 0.070338]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 260/676] [D loss: -0.007328] [G loss: -0.145641] [d1 loss: 0.058199] [d2 loss: 0.060455]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 280/676] [D loss: -0.011438] [G loss: -0.129284] [d1 loss: 0.024742] [d2 loss: 0.025714]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 300/676] [D loss: -0.006930] [G loss: -0.159351] [d1 loss: 0.032269] [d2 loss: 0.037093]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 393/500] [Batch 320/676] [D loss: -0.012622] [G loss: -0.092642] [d1 loss: 0.100595] [d2 loss: 0.097566]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 393/500] [Batch 340/676] [D loss: -0.005655] [G loss: -0.083183] [d1 loss: 0.036049] [d2 loss: 0.033572]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 360/676] [D loss: -0.019604] [G loss: -0.064383] [d1 loss: 0.057762] [d2 loss: 0.064246]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 380/676] [D loss: -0.012388] [G loss: -0.069520] [d1 loss: 0.079730] [d2 loss: 0.082217]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 393/500] [Batch 400/676] [D loss: -0.003328] [G loss: -0.044440] [d1 loss: 0.073459] [d2 loss: 0.062889]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 393/500] [Batch 420/676] [D loss: -0.004748] [G loss: -0.035672] [d1 loss: 0.066963] [d2 loss: 0.046468]  [sq d1 d2: 0.000420]  [num0: 19.000000] [num1 45.000000]
[Epoch 393/500] [Batch 440/676] [D loss: -0.011952] [G loss: -0.016456] [d1 loss: 0.070423] [d2 loss: 0.057993]  [sq d1 d2: 0.000154]  [num0: 18.000000] [num1 46.000000]
[Epoch 393/500] [Batch 460/676] [D loss: -0.021155] [G loss: -0.019634] [d1 loss: 0.048253] [d2 loss: 0.058886]  [sq d1 d2: 0.000113]  [num0: 18.000000] [num1 46.000000]
[Epoch 393/500] [Batch 480/676] [D loss: -0.016253] [G loss: -0.029375] [d1 loss: 0.030473] [d2 loss: 0.032225]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 500/676] [D loss: -0.019967] [G loss: -0.027027] [d1 loss: 0.051036] [d2 loss: 0.058166]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 520/676] [D loss: -0.013781] [G loss: -0.052318] [d1 loss: 0.064221] [d2 loss: 0.074155]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 393/500] [Batch 540/676] [D loss: -0.024532] [G loss: -0.073779] [d1 loss: 0.018351] [d2 loss: 0.020210]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 560/676] [D loss: -0.015225] [G loss: -0.086551] [d1 loss: 0.019123] [d2 loss: 0.019780]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 393/500] [Batch 580/676] [D loss: 0.012151] [G loss: -0.074946] [d1 loss: 0.020729] [d2 loss: 0.018677]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 600/676] [D loss: -0.006540] [G loss: -0.110215] [d1 loss: 0.077803] [d2 loss: 0.080617]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]

[Epoch 393/500] [Batch 620/676] [D loss: -0.005482] [G loss: -0.110755] [d1 loss: 0.073865] [d2 loss: 0.071566]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 393/500] [Batch 640/676] [D loss: -0.007871] [G loss: -0.119330] [d1 loss: 0.036471] [d2 loss: 0.044064]  [sq d1 d2: 0.000058]  [num0: 21.000000] [num1 43.000000]
[Epoch 393/500] [Batch 660/676] [D loss: -0.006698] [G loss: -0.125393] [d1 loss: 0.070473] [d2 loss: 0.058145]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 0/676] [D loss: -0.001912] [G loss: -0.145967] [d1 loss: 0.024793] [d2 loss: 0.033174]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 394/500] [Batch 20/676] [D loss: -0.012199] [G loss: -0.158586] [d1 loss: 0.141219] [d2 loss: 0.129572]  [sq d1 d2: 0.000136]  [num0: 18.000000] [num1 46.000000]
[Epoch 394/500] [Batch 40/676] [D loss: -0.012424] [G loss: -0.207326] [d1 loss: 0.071662] [d2 loss: 0.067147]  [sq d1 d2: 0.000020]  [num0: 20.000000] [num1 44.000000]
[Epoch 394/500] [Batch 60/676] [D loss: -0.025344] [G loss: -0.222563] [d1 loss: 0.069700] [d2 loss: 0.092849]  [sq d1 d2: 0.000536]  [num0: 17.000000] [num1 47.000000]
[Epoch 394/500] [Batch 80/676] [D loss: -0.020879] [G loss: -0.235808] [d1 loss: 0.061938] [d2 loss: 0.090813]  [sq d1 d2: 0.000834]  [num0: 19.000000] [num1 45.000000]
[Epoch 394/500] [Batch 100/676] [D loss: -0.036063] [G loss: -0.234013] [d1 loss: 0.318110] [d2 loss: 0.224781]  [sq d1 d2: 0.008710]  [num0: 19.000000] [num1 45.000000]
[Epoch 394/500] [Batch 120/676] [D loss: -0.009921] [G loss: -0.251843] [d1 loss: 0.020506] [d2 loss: 0.018926]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 394/500] [Batch 140/676] [D loss: -0.009616] [G loss: -0.223311] [d1 loss: 0.070091] [d2 loss: 0.061660]  [sq d1 d2: 0.000071]  [num0: 12.000000] [num1 52.000000]
[Epoch 394/500] [Batch 160/676] [D loss: 0.000624] [G loss: -0.216325] [d1 loss: 0.031685] [d2 loss: 0.054532]  [sq d1 d2: 0.000522]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 180/676] [D loss: -0.015434] [G loss: -0.172585] [d1 loss: 0.061829] [d2 loss: 0.063446]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 394/500] [Batch 200/676] [D loss: -0.012552] [G loss: -0.117752] [d1 loss: 0.064511] [d2 loss: 0.081029]  [sq d1 d2: 0.000273]  [num0: 16.000000] [num1 48.000000]
[Epoch 394/500] [Batch 220/676] [D loss: -0.001828] [G loss: -0.092375] [d1 loss: 0.078476] [d2 loss: 0.082914]  [sq d1 d2: 0.000020]  [num0: 22.000000] [num1 42.000000]
[Epoch 394/500] [Batch 240/676] [D loss: 0.008003] [G loss: -0.076264] [d1 loss: 0.041744] [d2 loss: 0.041367]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 394/500] [Batch 260/676] [D loss: -0.013036] [G loss: -0.054336] [d1 loss: 0.136242] [d2 loss: 0.112570]  [sq d1 d2: 0.000560]  [num0: 16.000000] [num1 48.000000]
[Epoch 394/500] [Batch 280/676] [D loss: -0.022414] [G loss: -0.066593] [d1 loss: 0.065615] [d2 loss: 0.077161]  [sq d1 d2: 0.000133]  [num0: 19.000000] [num1 45.000000]
[Epoch 394/500] [Batch 300/676] [D loss: -0.031059] [G loss: -0.043172] [d1 loss: 0.072152] [d2 loss: 0.065860]  [sq d1 d2: 0.000040]  [num0: 17.000000] [num1 47.000000]
[Epoch 394/500] [Batch 320/676] [D loss: -0.012138] [G loss: -0.018227] [d1 loss: 0.025216] [d2 loss: 0.031490]  [sq d1 d2: 0.000039]  [num0: 18.000000] [num1 46.000000]
[Epoch 394/500] [Batch 340/676] [D loss: -0.027620] [G loss: -0.032315] [d1 loss: 0.071328] [d2 loss: 0.076418]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 394/500] [Batch 360/676] [D loss: -0.030805] [G loss: -0.047884] [d1 loss: 0.025622] [d2 loss: 0.026780]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 394/500] [Batch 380/676] [D loss: -0.010064] [G loss: -0.017651] [d1 loss: 0.074950] [d2 loss: 0.085534]  [sq d1 d2: 0.000112]  [num0: 13.000000] [num1 51.000000]
[Epoch 394/500] [Batch 400/676] [D loss: -0.014950] [G loss: -0.058933] [d1 loss: 0.076506] [d2 loss: 0.079572]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 394/500] [Batch 420/676] [D loss: -0.005809] [G loss: -0.087305] [d1 loss: 0.022591] [d2 loss: 0.031895]  [sq d1 d2: 0.000087]  [num0: 14.000000] [num1 50.000000]
[Epoch 394/500] [Batch 440/676] [D loss: -0.012715] [G loss: -0.080928] [d1 loss: 0.115047] [d2 loss: 0.094211]  [sq d1 d2: 0.000434]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 460/676] [D loss: -0.002227] [G loss: -0.096840] [d1 loss: 0.071685] [d2 loss: 0.075225]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 480/676] [D loss: -0.016848] [G loss: -0.110070] [d1 loss: 0.032207] [d2 loss: 0.032690]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 500/676] [D loss: -0.009485] [G loss: -0.119101] [d1 loss: 0.032051] [d2 loss: 0.037485]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 394/500] [Batch 520/676] [D loss: -0.015923] [G loss: -0.153518] [d1 loss: 0.061841] [d2 loss: 0.085848]  [sq d1 d2: 0.000576]  [num0: 17.000000] [num1 47.000000]
[Epoch 394/500] [Batch 540/676] [D loss: -0.008434] [G loss: -0.137820] [d1 loss: 0.195552] [d2 loss: 0.238685]  [sq d1 d2: 0.001860]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 560/676] [D loss: -0.032824] [G loss: -0.163472] [d1 loss: 0.063805] [d2 loss: 0.065489]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 394/500] [Batch 580/676] [D loss: -0.022375] [G loss: -0.216615] [d1 loss: 0.133327] [d2 loss: 0.135425]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 394/500] [Batch 600/676] [D loss: -0.013807] [G loss: -0.265201] [d1 loss: 0.081945] [d2 loss: 0.075023]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 394/500] [Batch 620/676] [D loss: -0.042545] [G loss: -0.327991] [d1 loss: 0.042115] [d2 loss: 0.038079]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 394/500] [Batch 640/676] [D loss: -0.021338] [G loss: -0.302691] [d1 loss: 0.199649] [d2 loss: 0.156075]  [sq d1 d2: 0.001899]  [num0: 14.000000] [num1 50.000000]
[Epoch 394/500] [Batch 660/676] [D loss: -0.034085] [G loss: -0.306152] [d1 loss: 0.062405] [d2 loss: 0.063267]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 395/500] [Batch 0/676] [D loss: 0.002364] [G loss: -0.252782] [d1 loss: 0.049008] [d2 loss: 0.034198]  [sq d1 d2: 0.000219]  [num0: 18.000000] [num1 46.000000]
[Epoch 395/500] [Batch 20/676] [D loss: -0.003819] [G loss: -0.192279] [d1 loss: 0.041098] [d2 loss: 0.052683]  [sq d1 d2: 0.000134]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 40/676] [D loss: 0.000242] [G loss: -0.155619] [d1 loss: 0.051030] [d2 loss: 0.046306]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 60/676] [D loss: 0.005201] [G loss: -0.098260] [d1 loss: 0.048460] [d2 loss: 0.043688]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 80/676] [D loss: 0.002339] [G loss: -0.062101] [d1 loss: 0.031426] [d2 loss: 0.029352]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 100/676] [D loss: -0.016973] [G loss: -0.075239] [d1 loss: 0.118024] [d2 loss: 0.092057]  [sq d1 d2: 0.000674]  [num0: 21.000000] [num1 43.000000]
[Epoch 395/500] [Batch 120/676] [D loss: -0.013556] [G loss: -0.072742] [d1 loss: 0.045829] [d2 loss: 0.050207]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 140/676] [D loss: -0.027140] [G loss: -0.061602] [d1 loss: 0.084622] [d2 loss: 0.108894]  [sq d1 d2: 0.000589]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 160/676] [D loss: -0.016014] [G loss: -0.089685] [d1 loss: 0.104407] [d2 loss: 0.078447]  [sq d1 d2: 0.000674]  [num0: 18.000000] [num1 46.000000]
[Epoch 395/500] [Batch 180/676] [D loss: -0.015672] [G loss: -0.084026] [d1 loss: 0.069834] [d2 loss: 0.121717]  [sq d1 d2: 0.002692]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 200/676] [D loss: -0.030600] [G loss: -0.115473] [d1 loss: 0.094293] [d2 loss: 0.082589]  [sq d1 d2: 0.000137]  [num0: 15.000000] [num1 49.000000]
[Epoch 395/500] [Batch 220/676] [D loss: -0.026284] [G loss: -0.093308] [d1 loss: 0.042182] [d2 loss: 0.024316]  [sq d1 d2: 0.000319]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 240/676] [D loss: -0.016470] [G loss: -0.088515] [d1 loss: 0.053589] [d2 loss: 0.052031]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 395/500] [Batch 260/676] [D loss: -0.003584] [G loss: -0.070053] [d1 loss: 0.062168] [d2 loss: 0.064676]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 395/500] [Batch 280/676] [D loss: -0.027619] [G loss: -0.065003] [d1 loss: 0.042424] [d2 loss: 0.044447]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]

[Epoch 395/500] [Batch 300/676] [D loss: -0.002369] [G loss: -0.077734] [d1 loss: 0.083466] [d2 loss: 0.081792]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 320/676] [D loss: 0.005849] [G loss: -0.051613] [d1 loss: 0.061699] [d2 loss: 0.052718]  [sq d1 d2: 0.000081]  [num0: 19.000000] [num1 45.000000]
[Epoch 395/500] [Batch 340/676] [D loss: -0.002864] [G loss: -0.046819] [d1 loss: 0.058567] [d2 loss: 0.072956]  [sq d1 d2: 0.000207]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 360/676] [D loss: 0.004714] [G loss: -0.055563] [d1 loss: 0.105543] [d2 loss: 0.111916]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 395/500] [Batch 380/676] [D loss: -0.003625] [G loss: -0.056491] [d1 loss: 0.049720] [d2 loss: 0.072564]  [sq d1 d2: 0.000522]  [num0: 18.000000] [num1 46.000000]
[Epoch 395/500] [Batch 400/676] [D loss: -0.013767] [G loss: -0.068878] [d1 loss: 0.076013] [d2 loss: 0.078290]  [sq d1 d2: 0.000005]  [num0: 11.000000] [num1 53.000000]
[Epoch 395/500] [Batch 420/676] [D loss: -0.018179] [G loss: -0.116212] [d1 loss: 0.036075] [d2 loss: 0.028797]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 395/500] [Batch 440/676] [D loss: -0.007006] [G loss: -0.128978] [d1 loss: 0.044751] [d2 loss: 0.056530]  [sq d1 d2: 0.000139]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 460/676] [D loss: -0.027841] [G loss: -0.133760] [d1 loss: 0.038790] [d2 loss: 0.046227]  [sq d1 d2: 0.000055]  [num0: 15.000000] [num1 49.000000]
[Epoch 395/500] [Batch 480/676] [D loss: -0.008660] [G loss: -0.159320] [d1 loss: 0.011100] [d2 loss: 0.016217]  [sq d1 d2: 0.000026]  [num0: 12.000000] [num1 52.000000]
[Epoch 395/500] [Batch 500/676] [D loss: -0.045123] [G loss: -0.163121] [d1 loss: 0.099642] [d2 loss: 0.102186]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 395/500] [Batch 520/676] [D loss: -0.001725] [G loss: -0.190639] [d1 loss: 0.067539] [d2 loss: 0.074949]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 540/676] [D loss: -0.016528] [G loss: -0.178918] [d1 loss: 0.020276] [d2 loss: 0.020076]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 560/676] [D loss: 0.000633] [G loss: -0.149532] [d1 loss: 0.044891] [d2 loss: 0.041256]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 395/500] [Batch 580/676] [D loss: -0.002819] [G loss: -0.118331] [d1 loss: 0.023483] [d2 loss: 0.017458]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 600/676] [D loss: -0.005391] [G loss: -0.101379] [d1 loss: 0.014782] [d2 loss: 0.010232]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 395/500] [Batch 620/676] [D loss: 0.009621] [G loss: -0.061090] [d1 loss: 0.066170] [d2 loss: 0.055839]  [sq d1 d2: 0.000107]  [num0: 16.000000] [num1 48.000000]
[Epoch 395/500] [Batch 640/676] [D loss: -0.005682] [G loss: -0.061104] [d1 loss: 0.092889] [d2 loss: 0.085923]  [sq d1 d2: 0.000049]  [num0: 19.000000] [num1 45.000000]
[Epoch 395/500] [Batch 660/676] [D loss: -0.009288] [G loss: -0.032987] [d1 loss: 0.135659] [d2 loss: 0.133211]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 396/500] [Batch 0/676] [D loss: -0.020510] [G loss: -0.042431] [d1 loss: 0.081070] [d2 loss: 0.094993]  [sq d1 d2: 0.000194]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 20/676] [D loss: -0.027720] [G loss: -0.039497] [d1 loss: 0.056713] [d2 loss: 0.051143]  [sq d1 d2: 0.000031]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 40/676] [D loss: -0.005349] [G loss: -0.026838] [d1 loss: 0.068659] [d2 loss: 0.068645]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 60/676] [D loss: -0.031967] [G loss: -0.022144] [d1 loss: 0.073892] [d2 loss: 0.037963]  [sq d1 d2: 0.001291]  [num0: 20.000000] [num1 44.000000]
[Epoch 396/500] [Batch 80/676] [D loss: -0.020431] [G loss: -0.056206] [d1 loss: 0.065410] [d2 loss: 0.066238]  [sq d1 d2: 0.000001]  [num0: 21.000000] [num1 43.000000]
[Epoch 396/500] [Batch 100/676] [D loss: -0.002383] [G loss: -0.060625] [d1 loss: 0.133587] [d2 loss: 0.167887]  [sq d1 d2: 0.001177]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 120/676] [D loss: -0.024877] [G loss: -0.080314] [d1 loss: 0.054151] [d2 loss: 0.081445]  [sq d1 d2: 0.000745]  [num0: 16.000000] [num1 48.000000]
[Epoch 396/500] [Batch 140/676] [D loss: -0.014856] [G loss: -0.066595] [d1 loss: 0.046633] [d2 loss: 0.059003]  [sq d1 d2: 0.000153]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 160/676] [D loss: 0.005441] [G loss: -0.104333] [d1 loss: 0.053002] [d2 loss: 0.041966]  [sq d1 d2: 0.000122]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 180/676] [D loss: -0.016147] [G loss: -0.148375] [d1 loss: 0.050919] [d2 loss: 0.050273]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 200/676] [D loss: 0.001254] [G loss: -0.151116] [d1 loss: 0.087880] [d2 loss: 0.096185]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 220/676] [D loss: -0.003400] [G loss: -0.152349] [d1 loss: 0.030696] [d2 loss: 0.029415]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 240/676] [D loss: -0.012127] [G loss: -0.146820] [d1 loss: 0.058057] [d2 loss: 0.076876]  [sq d1 d2: 0.000354]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 260/676] [D loss: -0.014794] [G loss: -0.186614] [d1 loss: 0.079986] [d2 loss: 0.084929]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 280/676] [D loss: -0.035862] [G loss: -0.223880] [d1 loss: 0.047691] [d2 loss: 0.044457]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 300/676] [D loss: -0.054764] [G loss: -0.267239] [d1 loss: 0.096681] [d2 loss: 0.101333]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 320/676] [D loss: -0.048062] [G loss: -0.310163] [d1 loss: 0.037268] [d2 loss: 0.039916]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 340/676] [D loss: -0.022902] [G loss: -0.310952] [d1 loss: 0.077600] [d2 loss: 0.121295]  [sq d1 d2: 0.001909]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 360/676] [D loss: -0.006447] [G loss: -0.330425] [d1 loss: 0.080490] [d2 loss: 0.078234]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 380/676] [D loss: -0.013078] [G loss: -0.298731] [d1 loss: 0.061995] [d2 loss: 0.051732]  [sq d1 d2: 0.000105]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 400/676] [D loss: 0.005918] [G loss: -0.235309] [d1 loss: 0.037024] [d2 loss: 0.031182]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 396/500] [Batch 420/676] [D loss: 0.016872] [G loss: -0.189623] [d1 loss: 0.067379] [d2 loss: 0.062410]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 396/500] [Batch 440/676] [D loss: 0.006551] [G loss: -0.133556] [d1 loss: 0.048202] [d2 loss: 0.059572]  [sq d1 d2: 0.000129]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 460/676] [D loss: -0.003326] [G loss: -0.083011] [d1 loss: 0.034448] [d2 loss: 0.042386]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 396/500] [Batch 480/676] [D loss: -0.012887] [G loss: -0.059335] [d1 loss: 0.043449] [d2 loss: 0.041427]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 500/676] [D loss: -0.011307] [G loss: -0.052096] [d1 loss: 0.090513] [d2 loss: 0.113782]  [sq d1 d2: 0.000541]  [num0: 19.000000] [num1 45.000000]
[Epoch 396/500] [Batch 520/676] [D loss: -0.011192] [G loss: -0.016203] [d1 loss: 0.081742] [d2 loss: 0.077306]  [sq d1 d2: 0.000020]  [num0: 10.000000] [num1 54.000000]
[Epoch 396/500] [Batch 540/676] [D loss: -0.019564] [G loss: -0.012336] [d1 loss: 0.058921] [d2 loss: 0.051278]  [sq d1 d2: 0.000058]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 560/676] [D loss: -0.030035] [G loss: -0.008617] [d1 loss: 0.077861] [d2 loss: 0.082249]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 580/676] [D loss: -0.023195] [G loss: -0.009926] [d1 loss: 0.021728] [d2 loss: 0.022890]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 396/500] [Batch 600/676] [D loss: -0.010865] [G loss: -0.033227] [d1 loss: 0.010834] [d2 loss: 0.010498]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 396/500] [Batch 620/676] [D loss: -0.008301] [G loss: -0.069383] [d1 loss: 0.097631] [d2 loss: 0.093475]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 396/500] [Batch 640/676] [D loss: -0.000452] [G loss: -0.077448] [d1 loss: 0.039081] [d2 loss: 0.043998]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]

[Epoch 396/500] [Batch 660/676] [D loss: 0.014053] [G loss: -0.093833] [d1 loss: 0.054513] [d2 loss: 0.036301]  [sq d1 d2: 0.000332]  [num0: 20.000000] [num1 44.000000]
[Epoch 397/500] [Batch 0/676] [D loss: -0.023990] [G loss: -0.111760] [d1 loss: 0.027132] [d2 loss: 0.028423]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 20/676] [D loss: 0.000683] [G loss: -0.136563] [d1 loss: 0.099515] [d2 loss: 0.104483]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 397/500] [Batch 40/676] [D loss: 0.006298] [G loss: -0.110293] [d1 loss: 0.030480] [d2 loss: 0.026533]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 60/676] [D loss: 0.002984] [G loss: -0.124869] [d1 loss: 0.156270] [d2 loss: 0.101929]  [sq d1 d2: 0.002953]  [num0: 19.000000] [num1 45.000000]
[Epoch 397/500] [Batch 80/676] [D loss: -0.007092] [G loss: -0.128393] [d1 loss: 0.036275] [d2 loss: 0.032880]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 100/676] [D loss: -0.021559] [G loss: -0.162916] [d1 loss: 0.044587] [d2 loss: 0.044791]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 120/676] [D loss: -0.015972] [G loss: -0.187094] [d1 loss: 0.040378] [d2 loss: 0.044416]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 397/500] [Batch 140/676] [D loss: -0.029015] [G loss: -0.192026] [d1 loss: 0.088345] [d2 loss: 0.088390]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 160/676] [D loss: -0.013002] [G loss: -0.242116] [d1 loss: 0.063153] [d2 loss: 0.075047]  [sq d1 d2: 0.000141]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 180/676] [D loss: -0.036811] [G loss: -0.250189] [d1 loss: 0.080762] [d2 loss: 0.100368]  [sq d1 d2: 0.000384]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 200/676] [D loss: -0.006477] [G loss: -0.274673] [d1 loss: 0.047764] [d2 loss: 0.051613]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 220/676] [D loss: -0.025308] [G loss: -0.240306] [d1 loss: 0.092376] [d2 loss: 0.102615]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 240/676] [D loss: 0.023442] [G loss: -0.253421] [d1 loss: 0.070672] [d2 loss: 0.074019]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 260/676] [D loss: 0.024100] [G loss: -0.214769] [d1 loss: 0.084844] [d2 loss: 0.091158]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 397/500] [Batch 280/676] [D loss: 0.003590] [G loss: -0.137348] [d1 loss: 0.033397] [d2 loss: 0.040553]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 300/676] [D loss: -0.009133] [G loss: -0.096753] [d1 loss: 0.044774] [d2 loss: 0.041735]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 320/676] [D loss: -0.009355] [G loss: -0.063053] [d1 loss: 0.043591] [d2 loss: 0.050564]  [sq d1 d2: 0.000049]  [num0: 20.000000] [num1 44.000000]
[Epoch 397/500] [Batch 340/676] [D loss: -0.009568] [G loss: -0.035335] [d1 loss: 0.038624] [d2 loss: 0.038353]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 397/500] [Batch 360/676] [D loss: -0.008996] [G loss: -0.010126] [d1 loss: 0.119336] [d2 loss: 0.165834]  [sq d1 d2: 0.002162]  [num0: 13.000000] [num1 51.000000]
[Epoch 397/500] [Batch 380/676] [D loss: -0.014961] [G loss: 0.014460] [d1 loss: 0.042631] [d2 loss: 0.064259]  [sq d1 d2: 0.000468]  [num0: 14.000000] [num1 50.000000]
[Epoch 397/500] [Batch 400/676] [D loss: -0.019495] [G loss: 0.020852] [d1 loss: 0.107947] [d2 loss: 0.137898]  [sq d1 d2: 0.000897]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 420/676] [D loss: -0.018507] [G loss: 0.009068] [d1 loss: 0.046435] [d2 loss: 0.046067]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 397/500] [Batch 440/676] [D loss: -0.006895] [G loss: 0.022747] [d1 loss: 0.081083] [d2 loss: 0.055236]  [sq d1 d2: 0.000668]  [num0: 13.000000] [num1 51.000000]
[Epoch 397/500] [Batch 460/676] [D loss: -0.006326] [G loss: 0.026057] [d1 loss: 0.090663] [d2 loss: 0.113309]  [sq d1 d2: 0.000513]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 480/676] [D loss: -0.017922] [G loss: 0.006256] [d1 loss: 0.110010] [d2 loss: 0.124923]  [sq d1 d2: 0.000222]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 500/676] [D loss: 0.015833] [G loss: 0.013637] [d1 loss: 0.021839] [d2 loss: 0.029157]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 520/676] [D loss: 0.000696] [G loss: -0.016357] [d1 loss: 0.097988] [d2 loss: 0.102868]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 540/676] [D loss: -0.016693] [G loss: -0.036591] [d1 loss: 0.072789] [d2 loss: 0.061534]  [sq d1 d2: 0.000127]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 560/676] [D loss: -0.002044] [G loss: -0.036051] [d1 loss: 0.050498] [d2 loss: 0.059476]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 397/500] [Batch 580/676] [D loss: 0.008894] [G loss: -0.056106] [d1 loss: 0.045347] [d2 loss: 0.041385]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 397/500] [Batch 600/676] [D loss: -0.004126] [G loss: -0.074587] [d1 loss: 0.085335] [d2 loss: 0.085845]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 397/500] [Batch 620/676] [D loss: -0.011871] [G loss: -0.116824] [d1 loss: 0.105733] [d2 loss: 0.063055]  [sq d1 d2: 0.001821]  [num0: 17.000000] [num1 47.000000]
[Epoch 397/500] [Batch 640/676] [D loss: -0.000391] [G loss: -0.133677] [d1 loss: 0.169120] [d2 loss: 0.201281]  [sq d1 d2: 0.001034]  [num0: 15.000000] [num1 49.000000]
[Epoch 397/500] [Batch 660/676] [D loss: -0.007785] [G loss: -0.161018] [d1 loss: 0.045788] [d2 loss: 0.055420]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 398/500] [Batch 0/676] [D loss: -0.025755] [G loss: -0.195644] [d1 loss: 0.038791] [d2 loss: 0.026009]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 20/676] [D loss: -0.020986] [G loss: -0.229255] [d1 loss: 0.026988] [d2 loss: 0.035246]  [sq d1 d2: 0.000068]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 40/676] [D loss: -0.008143] [G loss: -0.242417] [d1 loss: 0.078813] [d2 loss: 0.077648]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 398/500] [Batch 60/676] [D loss: -0.006819] [G loss: -0.243054] [d1 loss: 0.053316] [d2 loss: 0.048410]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 398/500] [Batch 80/676] [D loss: 0.004788] [G loss: -0.264466] [d1 loss: 0.077344] [d2 loss: 0.076446]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 398/500] [Batch 100/676] [D loss: 0.005976] [G loss: -0.279765] [d1 loss: 0.057545] [d2 loss: 0.050840]  [sq d1 d2: 0.000045]  [num0: 16.000000] [num1 48.000000]
[Epoch 398/500] [Batch 120/676] [D loss: -0.010149] [G loss: -0.240368] [d1 loss: 0.014200] [d2 loss: 0.018400]  [sq d1 d2: 0.000018]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 140/676] [D loss: -0.000189] [G loss: -0.205326] [d1 loss: 0.043584] [d2 loss: 0.045846]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 398/500] [Batch 160/676] [D loss: 0.002523] [G loss: -0.192821] [d1 loss: 0.042899] [d2 loss: 0.056285]  [sq d1 d2: 0.000179]  [num0: 13.000000] [num1 51.000000]
[Epoch 398/500] [Batch 180/676] [D loss: -0.002003] [G loss: -0.158618] [d1 loss: 0.074115] [d2 loss: 0.090291]  [sq d1 d2: 0.000262]  [num0: 14.000000] [num1 50.000000]
[Epoch 398/500] [Batch 200/676] [D loss: -0.007364] [G loss: -0.094885] [d1 loss: 0.037314] [d2 loss: 0.049220]  [sq d1 d2: 0.000142]  [num0: 15.000000] [num1 49.000000]
[Epoch 398/500] [Batch 220/676] [D loss: -0.023895] [G loss: -0.071020] [d1 loss: 0.093388] [d2 loss: 0.090863]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 398/500] [Batch 240/676] [D loss: -0.024349] [G loss: -0.046387] [d1 loss: 0.094689] [d2 loss: 0.105464]  [sq d1 d2: 0.000116]  [num0: 16.000000] [num1 48.000000]
[Epoch 398/500] [Batch 260/676] [D loss: -0.019368] [G loss: -0.046356] [d1 loss: 0.068360] [d2 loss: 0.074843]  [sq d1 d2: 0.000042]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 280/676] [D loss: -0.005239] [G loss: -0.025269] [d1 loss: 0.044291] [d2 loss: 0.038134]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 300/676] [D loss: -0.001386] [G loss: -0.032184] [d1 loss: 0.069057] [d2 loss: 0.099823]  [sq d1 d2: 0.000946]  [num0: 16.000000] [num1 48.000000]
[Epoch 398/500] [Batch 320/676] [D loss: 0.000761] [G loss: -0.053359] [d1 loss: 0.062859] [d2 loss: 0.075283]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]

[Epoch 398/500] [Batch 340/676] [D loss: -0.027939] [G loss: -0.053950] [d1 loss: 0.025829] [d2 loss: 0.026340]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 360/676] [D loss: 0.002821] [G loss: -0.067529] [d1 loss: 0.117167] [d2 loss: 0.077304]  [sq d1 d2: 0.001589]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 380/676] [D loss: -0.006881] [G loss: -0.087887] [d1 loss: 0.069705] [d2 loss: 0.070228]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 400/676] [D loss: -0.012736] [G loss: -0.074383] [d1 loss: 0.023906] [d2 loss: 0.016252]  [sq d1 d2: 0.000059]  [num0: 12.000000] [num1 52.000000]
[Epoch 398/500] [Batch 420/676] [D loss: -0.009367] [G loss: -0.080268] [d1 loss: 0.112720] [d2 loss: 0.091974]  [sq d1 d2: 0.000430]  [num0: 13.000000] [num1 51.000000]
[Epoch 398/500] [Batch 440/676] [D loss: -0.013275] [G loss: -0.118331] [d1 loss: 0.055855] [d2 loss: 0.055021]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 460/676] [D loss: -0.005779] [G loss: -0.161104] [d1 loss: 0.017929] [d2 loss: 0.018817]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 398/500] [Batch 480/676] [D loss: -0.013486] [G loss: -0.171031] [d1 loss: 0.033122] [d2 loss: 0.033051]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 398/500] [Batch 500/676] [D loss: 0.005511] [G loss: -0.205077] [d1 loss: 0.051532] [d2 loss: 0.090305]  [sq d1 d2: 0.001503]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 520/676] [D loss: -0.014658] [G loss: -0.221787] [d1 loss: 0.366050] [d2 loss: 0.348607]  [sq d1 d2: 0.000304]  [num0: 14.000000] [num1 50.000000]
[Epoch 398/500] [Batch 540/676] [D loss: -0.025984] [G loss: -0.210236] [d1 loss: 0.063382] [d2 loss: 0.061193]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 398/500] [Batch 560/676] [D loss: -0.005085] [G loss: -0.198370] [d1 loss: 0.026321] [d2 loss: 0.038668]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 398/500] [Batch 580/676] [D loss: 0.003527] [G loss: -0.173381] [d1 loss: 0.097619] [d2 loss: 0.119528]  [sq d1 d2: 0.000480]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 600/676] [D loss: -0.011327] [G loss: -0.139149] [d1 loss: 0.102691] [d2 loss: 0.125471]  [sq d1 d2: 0.000519]  [num0: 18.000000] [num1 46.000000]
[Epoch 398/500] [Batch 620/676] [D loss: -0.010620] [G loss: -0.130460] [d1 loss: 0.129180] [d2 loss: 0.137734]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 398/500] [Batch 640/676] [D loss: 0.002368] [G loss: -0.105900] [d1 loss: 0.076874] [d2 loss: 0.058849]  [sq d1 d2: 0.000325]  [num0: 17.000000] [num1 47.000000]
[Epoch 398/500] [Batch 660/676] [D loss: 0.002536] [G loss: -0.084459] [d1 loss: 0.081469] [d2 loss: 0.092423]  [sq d1 d2: 0.000120]  [num0: 16.000000] [num1 48.000000]
[Epoch 399/500] [Batch 0/676] [D loss: -0.008890] [G loss: -0.060872] [d1 loss: 0.080027] [d2 loss: 0.080472]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 20/676] [D loss: -0.007971] [G loss: -0.036257] [d1 loss: 0.070180] [d2 loss: 0.068089]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 399/500] [Batch 40/676] [D loss: 0.000515] [G loss: -0.008412] [d1 loss: 0.044385] [d2 loss: 0.042168]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 399/500] [Batch 60/676] [D loss: -0.004885] [G loss: 0.032186] [d1 loss: 0.061841] [d2 loss: 0.067572]  [sq d1 d2: 0.000033]  [num0: 12.000000] [num1 52.000000]
[Epoch 399/500] [Batch 80/676] [D loss: -0.012920] [G loss: 0.072778] [d1 loss: 0.026567] [d2 loss: 0.030977]  [sq d1 d2: 0.000019]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 100/676] [D loss: 0.022261] [G loss: 0.113850] [d1 loss: 0.092737] [d2 loss: 0.075762]  [sq d1 d2: 0.000288]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 120/676] [D loss: 0.006859] [G loss: 0.142501] [d1 loss: 0.037664] [d2 loss: 0.030618]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 140/676] [D loss: -0.008245] [G loss: 0.152605] [d1 loss: 0.107388] [d2 loss: 0.126078]  [sq d1 d2: 0.000349]  [num0: 17.000000] [num1 47.000000]
[Epoch 399/500] [Batch 160/676] [D loss: -0.007086] [G loss: 0.161301] [d1 loss: 0.053920] [d2 loss: 0.047148]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 399/500] [Batch 180/676] [D loss: -0.001688] [G loss: 0.127068] [d1 loss: 0.069575] [d2 loss: 0.057970]  [sq d1 d2: 0.000135]  [num0: 16.000000] [num1 48.000000]
[Epoch 399/500] [Batch 200/676] [D loss: -0.003323] [G loss: 0.065795] [d1 loss: 0.072904] [d2 loss: 0.072198]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 399/500] [Batch 220/676] [D loss: -0.014444] [G loss: 0.023917] [d1 loss: 0.073294] [d2 loss: 0.057574]  [sq d1 d2: 0.000247]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 240/676] [D loss: -0.013120] [G loss: -0.011634] [d1 loss: 0.041649] [d2 loss: 0.044855]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 399/500] [Batch 260/676] [D loss: -0.012082] [G loss: -0.077229] [d1 loss: 0.069044] [d2 loss: 0.056048]  [sq d1 d2: 0.000169]  [num0: 17.000000] [num1 47.000000]
[Epoch 399/500] [Batch 280/676] [D loss: -0.015988] [G loss: -0.100276] [d1 loss: 0.105659] [d2 loss: 0.121476]  [sq d1 d2: 0.000250]  [num0: 19.000000] [num1 45.000000]
[Epoch 399/500] [Batch 300/676] [D loss: 0.000899] [G loss: -0.138907] [d1 loss: 0.045638] [d2 loss: 0.040681]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 399/500] [Batch 320/676] [D loss: -0.030571] [G loss: -0.190770] [d1 loss: 0.082528] [d2 loss: 0.117776]  [sq d1 d2: 0.001242]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 340/676] [D loss: 0.001926] [G loss: -0.177236] [d1 loss: 0.047984] [d2 loss: 0.046903]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 360/676] [D loss: -0.014150] [G loss: -0.161247] [d1 loss: 0.031852] [d2 loss: 0.029846]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 399/500] [Batch 380/676] [D loss: -0.024155] [G loss: -0.210418] [d1 loss: 0.065493] [d2 loss: 0.069154]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 399/500] [Batch 400/676] [D loss: -0.010656] [G loss: -0.231212] [d1 loss: 0.045983] [d2 loss: 0.043433]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 399/500] [Batch 420/676] [D loss: -0.000245] [G loss: -0.238519] [d1 loss: 0.031740] [d2 loss: 0.035244]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 399/500] [Batch 440/676] [D loss: 0.021118] [G loss: -0.218830] [d1 loss: 0.058393] [d2 loss: 0.052624]  [sq d1 d2: 0.000033]  [num0: 11.000000] [num1 53.000000]
[Epoch 399/500] [Batch 460/676] [D loss: -0.000079] [G loss: -0.161005] [d1 loss: 0.081907] [d2 loss: 0.076232]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 480/676] [D loss: -0.003728] [G loss: -0.124129] [d1 loss: 0.078240] [d2 loss: 0.083208]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 399/500] [Batch 500/676] [D loss: -0.007132] [G loss: -0.107266] [d1 loss: 0.038210] [d2 loss: 0.025454]  [sq d1 d2: 0.000163]  [num0: 14.000000] [num1 50.000000]
[Epoch 399/500] [Batch 520/676] [D loss: -0.002781] [G loss: -0.112182] [d1 loss: 0.090737] [d2 loss: 0.058321]  [sq d1 d2: 0.001051]  [num0: 18.000000] [num1 46.000000]
[Epoch 399/500] [Batch 540/676] [D loss: -0.000106] [G loss: -0.097353] [d1 loss: 0.043985] [d2 loss: 0.048295]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 560/676] [D loss: -0.012024] [G loss: -0.090375] [d1 loss: 0.052376] [d2 loss: 0.043021]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 580/676] [D loss: -0.014062] [G loss: -0.064958] [d1 loss: 0.145332] [d2 loss: 0.134690]  [sq d1 d2: 0.000113]  [num0: 18.000000] [num1 46.000000]
[Epoch 399/500] [Batch 600/676] [D loss: -0.002749] [G loss: -0.064789] [d1 loss: 0.062210] [d2 loss: 0.080032]  [sq d1 d2: 0.000318]  [num0: 15.000000] [num1 49.000000]
[Epoch 399/500] [Batch 620/676] [D loss: -0.007331] [G loss: -0.039472] [d1 loss: 0.082164] [d2 loss: 0.081763]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 399/500] [Batch 640/676] [D loss: -0.022615] [G loss: -0.053100] [d1 loss: 0.066071] [d2 loss: 0.056126]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 399/500] [Batch 660/676] [D loss: -0.016328] [G loss: -0.069404] [d1 loss: 0.052469] [d2 loss: 0.067845]  [sq d1 d2: 0.000236]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 0/676] [D loss: -0.015052] [G loss: -0.083545] [d1 loss: 0.049864] [d2 loss: 0.044371]  [sq d1 d2: 0.000030]  [num0: 19.000000] [num1 45.000000]

[Epoch 400/500] [Batch 20/676] [D loss: -0.002402] [G loss: -0.060963] [d1 loss: 0.080104] [d2 loss: 0.077715]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 400/500] [Batch 40/676] [D loss: 0.004098] [G loss: -0.075586] [d1 loss: 0.081675] [d2 loss: 0.074514]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 400/500] [Batch 60/676] [D loss: -0.008884] [G loss: -0.102497] [d1 loss: 0.046000] [d2 loss: 0.064465]  [sq d1 d2: 0.000341]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 80/676] [D loss: -0.003459] [G loss: -0.108430] [d1 loss: 0.039302] [d2 loss: 0.035709]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 400/500] [Batch 100/676] [D loss: -0.000431] [G loss: -0.097517] [d1 loss: 0.043653] [d2 loss: 0.079153]  [sq d1 d2: 0.001260]  [num0: 10.000000] [num1 54.000000]
[Epoch 400/500] [Batch 120/676] [D loss: -0.006043] [G loss: -0.098199] [d1 loss: 0.051636] [d2 loss: 0.046086]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 400/500] [Batch 140/676] [D loss: -0.017231] [G loss: -0.099744] [d1 loss: 0.051046] [d2 loss: 0.030187]  [sq d1 d2: 0.000435]  [num0: 13.000000] [num1 51.000000]
[Epoch 400/500] [Batch 160/676] [D loss: -0.005283] [G loss: -0.123275] [d1 loss: 0.046067] [d2 loss: 0.055360]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 180/676] [D loss: -0.013399] [G loss: -0.146490] [d1 loss: 0.062355] [d2 loss: 0.050249]  [sq d1 d2: 0.000147]  [num0: 12.000000] [num1 52.000000]
[Epoch 400/500] [Batch 200/676] [D loss: -0.031268] [G loss: -0.164662] [d1 loss: 0.030758] [d2 loss: 0.030988]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 400/500] [Batch 220/676] [D loss: -0.015296] [G loss: -0.188699] [d1 loss: 0.064024] [d2 loss: 0.068884]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 240/676] [D loss: -0.007081] [G loss: -0.245487] [d1 loss: 0.048518] [d2 loss: 0.054360]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 400/500] [Batch 260/676] [D loss: -0.008138] [G loss: -0.238183] [d1 loss: 0.036726] [d2 loss: 0.036080]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 280/676] [D loss: 0.026393] [G loss: -0.213014] [d1 loss: 0.044855] [d2 loss: 0.048084]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 400/500] [Batch 300/676] [D loss: -0.004203] [G loss: -0.170756] [d1 loss: 0.140426] [d2 loss: 0.066083]  [sq d1 d2: 0.005527]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 320/676] [D loss: -0.006305] [G loss: -0.161421] [d1 loss: 0.024341] [d2 loss: 0.026408]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 400/500] [Batch 340/676] [D loss: -0.004595] [G loss: -0.132014] [d1 loss: 0.043867] [d2 loss: 0.054032]  [sq d1 d2: 0.000103]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 360/676] [D loss: -0.012293] [G loss: -0.115279] [d1 loss: 0.086772] [d2 loss: 0.068757]  [sq d1 d2: 0.000325]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 380/676] [D loss: -0.000581] [G loss: -0.089110] [d1 loss: 0.044271] [d2 loss: 0.080303]  [sq d1 d2: 0.001298]  [num0: 18.000000] [num1 46.000000]
[Epoch 400/500] [Batch 400/676] [D loss: -0.015004] [G loss: -0.074311] [d1 loss: 0.094643] [d2 loss: 0.101041]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 420/676] [D loss: -0.001341] [G loss: -0.075236] [d1 loss: 0.033171] [d2 loss: 0.038957]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 400/500] [Batch 440/676] [D loss: -0.004046] [G loss: -0.077258] [d1 loss: 0.049952] [d2 loss: 0.040351]  [sq d1 d2: 0.000092]  [num0: 18.000000] [num1 46.000000]
[Epoch 400/500] [Batch 460/676] [D loss: -0.010162] [G loss: -0.061196] [d1 loss: 0.015011] [d2 loss: 0.024147]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 400/500] [Batch 480/676] [D loss: -0.022873] [G loss: -0.102557] [d1 loss: 0.022523] [d2 loss: 0.027365]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 500/676] [D loss: -0.015652] [G loss: -0.069608] [d1 loss: 0.049167] [d2 loss: 0.078365]  [sq d1 d2: 0.000853]  [num0: 17.000000] [num1 47.000000]
[Epoch 400/500] [Batch 520/676] [D loss: 0.000192] [G loss: -0.085043] [d1 loss: 0.122344] [d2 loss: 0.131335]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 540/676] [D loss: -0.024308] [G loss: -0.088682] [d1 loss: 0.104601] [d2 loss: 0.082765]  [sq d1 d2: 0.000477]  [num0: 15.000000] [num1 49.000000]
[Epoch 400/500] [Batch 560/676] [D loss: -0.003319] [G loss: -0.091119] [d1 loss: 0.034684] [d2 loss: 0.025069]  [sq d1 d2: 0.000092]  [num0: 19.000000] [num1 45.000000]
[Epoch 400/500] [Batch 580/676] [D loss: 0.010505] [G loss: -0.094698] [d1 loss: 0.086789] [d2 loss: 0.047767]  [sq d1 d2: 0.001523]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 600/676] [D loss: 0.006232] [G loss: -0.091035] [d1 loss: 0.045832] [d2 loss: 0.046480]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 400/500] [Batch 620/676] [D loss: -0.004327] [G loss: -0.083271] [d1 loss: 0.036990] [d2 loss: 0.041356]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 400/500] [Batch 640/676] [D loss: -0.002288] [G loss: -0.106944] [d1 loss: 0.080506] [d2 loss: 0.072882]  [sq d1 d2: 0.000058]  [num0: 17.000000] [num1 47.000000]
[Epoch 400/500] [Batch 660/676] [D loss: 0.003710] [G loss: -0.105307] [d1 loss: 0.100750] [d2 loss: 0.099008]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 0/676] [D loss: -0.002926] [G loss: -0.134407] [d1 loss: 0.058851] [d2 loss: 0.063487]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 401/500] [Batch 20/676] [D loss: -0.007251] [G loss: -0.134201] [d1 loss: 0.076063] [d2 loss: 0.092657]  [sq d1 d2: 0.000275]  [num0: 17.000000] [num1 47.000000]
[Epoch 401/500] [Batch 40/676] [D loss: -0.007996] [G loss: -0.155194] [d1 loss: 0.024202] [d2 loss: 0.021143]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 401/500] [Batch 60/676] [D loss: -0.020725] [G loss: -0.152416] [d1 loss: 0.024574] [d2 loss: 0.037692]  [sq d1 d2: 0.000172]  [num0: 18.000000] [num1 46.000000]
[Epoch 401/500] [Batch 80/676] [D loss: -0.014270] [G loss: -0.185011] [d1 loss: 0.079910] [d2 loss: 0.084781]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 401/500] [Batch 100/676] [D loss: -0.019695] [G loss: -0.191188] [d1 loss: 0.087727] [d2 loss: 0.077848]  [sq d1 d2: 0.000098]  [num0: 19.000000] [num1 45.000000]
[Epoch 401/500] [Batch 120/676] [D loss: -0.011467] [G loss: -0.183904] [d1 loss: 0.097153] [d2 loss: 0.087968]  [sq d1 d2: 0.000084]  [num0: 18.000000] [num1 46.000000]
[Epoch 401/500] [Batch 140/676] [D loss: -0.017751] [G loss: -0.214788] [d1 loss: 0.057056] [d2 loss: 0.095848]  [sq d1 d2: 0.001505]  [num0: 11.000000] [num1 53.000000]
[Epoch 401/500] [Batch 160/676] [D loss: -0.022627] [G loss: -0.191040] [d1 loss: 0.073912] [d2 loss: 0.061024]  [sq d1 d2: 0.000166]  [num0: 18.000000] [num1 46.000000]
[Epoch 401/500] [Batch 180/676] [D loss: -0.021121] [G loss: -0.192143] [d1 loss: 0.092103] [d2 loss: 0.082143]  [sq d1 d2: 0.000099]  [num0: 19.000000] [num1 45.000000]
[Epoch 401/500] [Batch 200/676] [D loss: -0.007240] [G loss: -0.118488] [d1 loss: 0.074035] [d2 loss: 0.075592]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 220/676] [D loss: -0.003451] [G loss: -0.092301] [d1 loss: 0.029507] [d2 loss: 0.036779]  [sq d1 d2: 0.000053]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 240/676] [D loss: -0.007840] [G loss: -0.110853] [d1 loss: 0.102576] [d2 loss: 0.113250]  [sq d1 d2: 0.000114]  [num0: 12.000000] [num1 52.000000]
[Epoch 401/500] [Batch 260/676] [D loss: -0.002419] [G loss: -0.090066] [d1 loss: 0.065138] [d2 loss: 0.061369]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 401/500] [Batch 280/676] [D loss: -0.000809] [G loss: -0.072806] [d1 loss: 0.077471] [d2 loss: 0.061588]  [sq d1 d2: 0.000252]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 300/676] [D loss: -0.007488] [G loss: -0.070651] [d1 loss: 0.094380] [d2 loss: 0.063792]  [sq d1 d2: 0.000936]  [num0: 14.000000] [num1 50.000000]
[Epoch 401/500] [Batch 320/676] [D loss: 0.004091] [G loss: -0.079568] [d1 loss: 0.096785] [d2 loss: 0.066092]  [sq d1 d2: 0.000942]  [num0: 11.000000] [num1 53.000000]
[Epoch 401/500] [Batch 340/676] [D loss: -0.015535] [G loss: -0.089296] [d1 loss: 0.050764] [d2 loss: 0.039771]  [sq d1 d2: 0.000121]  [num0: 14.000000] [num1 50.000000]

[Epoch 401/500] [Batch 360/676] [D loss: -0.019517] [G loss: -0.064234] [d1 loss: 0.064351] [d2 loss: 0.061189]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 401/500] [Batch 380/676] [D loss: 0.000326] [G loss: -0.077013] [d1 loss: 0.051240] [d2 loss: 0.050849]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 401/500] [Batch 400/676] [D loss: -0.007024] [G loss: -0.113732] [d1 loss: 0.024368] [d2 loss: 0.031309]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 420/676] [D loss: -0.014764] [G loss: -0.131786] [d1 loss: 0.127285] [d2 loss: 0.124057]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 401/500] [Batch 440/676] [D loss: -0.035906] [G loss: -0.152891] [d1 loss: 0.057930] [d2 loss: 0.038439]  [sq d1 d2: 0.000380]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 460/676] [D loss: 0.003835] [G loss: -0.152800] [d1 loss: 0.063564] [d2 loss: 0.091106]  [sq d1 d2: 0.000759]  [num0: 13.000000] [num1 51.000000]
[Epoch 401/500] [Batch 480/676] [D loss: 0.002346] [G loss: -0.148517] [d1 loss: 0.055350] [d2 loss: 0.096033]  [sq d1 d2: 0.001655]  [num0: 18.000000] [num1 46.000000]
[Epoch 401/500] [Batch 500/676] [D loss: 0.015875] [G loss: -0.148509] [d1 loss: 0.056930] [d2 loss: 0.046015]  [sq d1 d2: 0.000119]  [num0: 12.000000] [num1 52.000000]
[Epoch 401/500] [Batch 520/676] [D loss: 0.000825] [G loss: -0.121683] [d1 loss: 0.077551] [d2 loss: 0.052581]  [sq d1 d2: 0.000624]  [num0: 19.000000] [num1 45.000000]
[Epoch 401/500] [Batch 540/676] [D loss: 0.003879] [G loss: -0.095800] [d1 loss: 0.067194] [d2 loss: 0.078308]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 401/500] [Batch 560/676] [D loss: -0.000726] [G loss: -0.083181] [d1 loss: 0.081937] [d2 loss: 0.086061]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 401/500] [Batch 580/676] [D loss: -0.007943] [G loss: -0.095091] [d1 loss: 0.066096] [d2 loss: 0.073071]  [sq d1 d2: 0.000049]  [num0: 14.000000] [num1 50.000000]
[Epoch 401/500] [Batch 600/676] [D loss: -0.005607] [G loss: -0.116177] [d1 loss: 0.133260] [d2 loss: 0.113172]  [sq d1 d2: 0.000404]  [num0: 16.000000] [num1 48.000000]
[Epoch 401/500] [Batch 620/676] [D loss: -0.009409] [G loss: -0.116691] [d1 loss: 0.050327] [d2 loss: 0.056373]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 401/500] [Batch 640/676] [D loss: -0.008518] [G loss: -0.147092] [d1 loss: 0.066880] [d2 loss: 0.105017]  [sq d1 d2: 0.001454]  [num0: 13.000000] [num1 51.000000]
[Epoch 401/500] [Batch 660/676] [D loss: -0.013602] [G loss: -0.186524] [d1 loss: 0.062936] [d2 loss: 0.056105]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 402/500] [Batch 0/676] [D loss: -0.011102] [G loss: -0.195890] [d1 loss: 0.058303] [d2 loss: 0.060964]  [sq d1 d2: 0.000007]  [num0: 20.000000] [num1 44.000000]
[Epoch 402/500] [Batch 20/676] [D loss: -0.024922] [G loss: -0.203661] [d1 loss: 0.071430] [d2 loss: 0.071541]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 402/500] [Batch 40/676] [D loss: -0.008216] [G loss: -0.222944] [d1 loss: 0.026704] [d2 loss: 0.029255]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 60/676] [D loss: 0.013051] [G loss: -0.179303] [d1 loss: 0.082256] [d2 loss: 0.061843]  [sq d1 d2: 0.000417]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 80/676] [D loss: -0.004350] [G loss: -0.183729] [d1 loss: 0.030559] [d2 loss: 0.034541]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 100/676] [D loss: 0.000532] [G loss: -0.169336] [d1 loss: 0.064465] [d2 loss: 0.063416]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 402/500] [Batch 120/676] [D loss: -0.004978] [G loss: -0.141644] [d1 loss: 0.079465] [d2 loss: 0.057656]  [sq d1 d2: 0.000476]  [num0: 14.000000] [num1 50.000000]
[Epoch 402/500] [Batch 140/676] [D loss: -0.005088] [G loss: -0.114066] [d1 loss: 0.084073] [d2 loss: 0.102221]  [sq d1 d2: 0.000329]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 160/676] [D loss: -0.008833] [G loss: -0.095455] [d1 loss: 0.042424] [d2 loss: 0.040696]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 402/500] [Batch 180/676] [D loss: -0.003822] [G loss: -0.074610] [d1 loss: 0.023783] [d2 loss: 0.025420]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 402/500] [Batch 200/676] [D loss: -0.013693] [G loss: -0.068874] [d1 loss: 0.041848] [d2 loss: 0.038489]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 402/500] [Batch 220/676] [D loss: -0.013951] [G loss: -0.089056] [d1 loss: 0.080542] [d2 loss: 0.087515]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 402/500] [Batch 240/676] [D loss: -0.012719] [G loss: -0.087299] [d1 loss: 0.043978] [d2 loss: 0.043446]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 402/500] [Batch 260/676] [D loss: -0.031985] [G loss: -0.069857] [d1 loss: 0.063497] [d2 loss: 0.066373]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 402/500] [Batch 280/676] [D loss: -0.036510] [G loss: -0.085581] [d1 loss: 0.073871] [d2 loss: 0.072981]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 300/676] [D loss: -0.005497] [G loss: -0.036577] [d1 loss: 0.116795] [d2 loss: 0.029333]  [sq d1 d2: 0.007650]  [num0: 17.000000] [num1 47.000000]
[Epoch 402/500] [Batch 320/676] [D loss: -0.005071] [G loss: -0.034849] [d1 loss: 0.111924] [d2 loss: 0.146112]  [sq d1 d2: 0.001169]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 340/676] [D loss: -0.008393] [G loss: -0.018386] [d1 loss: 0.024745] [d2 loss: 0.017028]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 402/500] [Batch 360/676] [D loss: -0.027998] [G loss: -0.005499] [d1 loss: 0.036318] [d2 loss: 0.054319]  [sq d1 d2: 0.000324]  [num0: 16.000000] [num1 48.000000]
[Epoch 402/500] [Batch 380/676] [D loss: -0.018544] [G loss: 0.004649] [d1 loss: 0.059188] [d2 loss: 0.065876]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 402/500] [Batch 400/676] [D loss: 0.005643] [G loss: 0.023444] [d1 loss: 0.862629] [d2 loss: 0.706212]  [sq d1 d2: 0.024466]  [num0: 14.000000] [num1 50.000000]
[Epoch 402/500] [Batch 420/676] [D loss: 0.010033] [G loss: 0.017796] [d1 loss: 0.044439] [d2 loss: 0.051231]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 402/500] [Batch 440/676] [D loss: -0.000342] [G loss: 0.002333] [d1 loss: 0.092591] [d2 loss: 0.084970]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 402/500] [Batch 460/676] [D loss: -0.010712] [G loss: 0.019040] [d1 loss: 0.085887] [d2 loss: 0.107601]  [sq d1 d2: 0.000471]  [num0: 13.000000] [num1 51.000000]
[Epoch 402/500] [Batch 480/676] [D loss: -0.016575] [G loss: -0.011684] [d1 loss: 0.054407] [d2 loss: 0.054642]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 402/500] [Batch 500/676] [D loss: -0.031168] [G loss: -0.018120] [d1 loss: 0.048088] [d2 loss: 0.048446]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 402/500] [Batch 520/676] [D loss: -0.024719] [G loss: -0.059335] [d1 loss: 0.023206] [d2 loss: 0.027152]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 402/500] [Batch 540/676] [D loss: -0.017376] [G loss: -0.101970] [d1 loss: 0.049962] [d2 loss: 0.052784]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 402/500] [Batch 560/676] [D loss: -0.029594] [G loss: -0.109809] [d1 loss: 0.084998] [d2 loss: 0.082967]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 402/500] [Batch 580/676] [D loss: -0.012478] [G loss: -0.134982] [d1 loss: 0.051832] [d2 loss: 0.061993]  [sq d1 d2: 0.000103]  [num0: 10.000000] [num1 54.000000]
[Epoch 402/500] [Batch 600/676] [D loss: -0.015169] [G loss: -0.159121] [d1 loss: 0.019373] [d2 loss: 0.046547]  [sq d1 d2: 0.000738]  [num0: 19.000000] [num1 45.000000]
[Epoch 402/500] [Batch 620/676] [D loss: 0.012244] [G loss: -0.162004] [d1 loss: 0.126395] [d2 loss: 0.115352]  [sq d1 d2: 0.000122]  [num0: 12.000000] [num1 52.000000]
[Epoch 402/500] [Batch 640/676] [D loss: 0.003415] [G loss: -0.146783] [d1 loss: 0.058979] [d2 loss: 0.052620]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 402/500] [Batch 660/676] [D loss: -0.005819] [G loss: -0.161201] [d1 loss: 0.056423] [d2 loss: 0.033503]  [sq d1 d2: 0.000525]  [num0: 18.000000] [num1 46.000000]
[Epoch 403/500] [Batch 0/676] [D loss: -0.001898] [G loss: -0.166577] [d1 loss: 0.029336] [d2 loss: 0.041198]  [sq d1 d2: 0.000141]  [num0: 18.000000] [num1 46.000000]
[Epoch 403/500] [Batch 20/676] [D loss: -0.006871] [G loss: -0.166508] [d1 loss: 0.046131] [d2 loss: 0.049145]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]

[Epoch 403/500] [Batch 40/676] [D loss: -0.025675] [G loss: -0.185358] [d1 loss: 0.071947] [d2 loss: 0.088554]  [sq d1 d2: 0.000276]  [num0: 20.000000] [num1 44.000000]
[Epoch 403/500] [Batch 60/676] [D loss: -0.010401] [G loss: -0.201260] [d1 loss: 0.027793] [d2 loss: 0.036063]  [sq d1 d2: 0.000068]  [num0: 17.000000] [num1 47.000000]
[Epoch 403/500] [Batch 80/676] [D loss: -0.016382] [G loss: -0.202983] [d1 loss: 0.153859] [d2 loss: 0.156170]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 403/500] [Batch 100/676] [D loss: -0.027962] [G loss: -0.214115] [d1 loss: 0.052196] [d2 loss: 0.049379]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 403/500] [Batch 120/676] [D loss: -0.013788] [G loss: -0.210638] [d1 loss: 0.053209] [d2 loss: 0.057771]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 403/500] [Batch 140/676] [D loss: -0.008177] [G loss: -0.174790] [d1 loss: 0.024999] [d2 loss: 0.029526]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 403/500] [Batch 160/676] [D loss: -0.026591] [G loss: -0.178576] [d1 loss: 0.027237] [d2 loss: 0.039578]  [sq d1 d2: 0.000152]  [num0: 18.000000] [num1 46.000000]
[Epoch 403/500] [Batch 180/676] [D loss: 0.001075] [G loss: -0.153413] [d1 loss: 0.092183] [d2 loss: 0.091368]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 403/500] [Batch 200/676] [D loss: -0.006202] [G loss: -0.124040] [d1 loss: 0.041242] [d2 loss: 0.066714]  [sq d1 d2: 0.000649]  [num0: 17.000000] [num1 47.000000]
[Epoch 403/500] [Batch 220/676] [D loss: -0.002979] [G loss: -0.115700] [d1 loss: 0.037180] [d2 loss: 0.037538]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 240/676] [D loss: -0.016102] [G loss: -0.121354] [d1 loss: 0.021706] [d2 loss: 0.016651]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 260/676] [D loss: -0.027803] [G loss: -0.114861] [d1 loss: 0.116114] [d2 loss: 0.133547]  [sq d1 d2: 0.000304]  [num0: 16.000000] [num1 48.000000]
[Epoch 403/500] [Batch 280/676] [D loss: -0.012510] [G loss: -0.123068] [d1 loss: 0.063894] [d2 loss: 0.031987]  [sq d1 d2: 0.001018]  [num0: 15.000000] [num1 49.000000]
[Epoch 403/500] [Batch 300/676] [D loss: -0.009055] [G loss: -0.121508] [d1 loss: 0.026481] [d2 loss: 0.023944]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 403/500] [Batch 320/676] [D loss: -0.025745] [G loss: -0.146139] [d1 loss: 0.059111] [d2 loss: 0.045608]  [sq d1 d2: 0.000182]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 340/676] [D loss: -0.025332] [G loss: -0.133475] [d1 loss: 0.066708] [d2 loss: 0.063595]  [sq d1 d2: 0.000010]  [num0: 11.000000] [num1 53.000000]
[Epoch 403/500] [Batch 360/676] [D loss: -0.012404] [G loss: -0.132245] [d1 loss: 0.087207] [d2 loss: 0.096352]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 403/500] [Batch 380/676] [D loss: -0.016944] [G loss: -0.158662] [d1 loss: 0.116648] [d2 loss: 0.118201]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 403/500] [Batch 400/676] [D loss: 0.010205] [G loss: -0.193588] [d1 loss: 0.031545] [d2 loss: 0.029131]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 403/500] [Batch 420/676] [D loss: -0.004489] [G loss: -0.209486] [d1 loss: 0.099218] [d2 loss: 0.146576]  [sq d1 d2: 0.002243]  [num0: 10.000000] [num1 54.000000]
[Epoch 403/500] [Batch 440/676] [D loss: 0.011976] [G loss: -0.215119] [d1 loss: 0.036805] [d2 loss: 0.038281]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 403/500] [Batch 460/676] [D loss: 0.000757] [G loss: -0.188108] [d1 loss: 0.154332] [d2 loss: 0.119767]  [sq d1 d2: 0.001195]  [num0: 15.000000] [num1 49.000000]
[Epoch 403/500] [Batch 480/676] [D loss: -0.014637] [G loss: -0.219449] [d1 loss: 0.086080] [d2 loss: 0.059315]  [sq d1 d2: 0.000716]  [num0: 11.000000] [num1 53.000000]
[Epoch 403/500] [Batch 500/676] [D loss: -0.017214] [G loss: -0.182857] [d1 loss: 0.093292] [d2 loss: 0.056010]  [sq d1 d2: 0.001390]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 520/676] [D loss: -0.024520] [G loss: -0.138871] [d1 loss: 0.035528] [d2 loss: 0.033417]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 540/676] [D loss: -0.020042] [G loss: -0.155919] [d1 loss: 0.037083] [d2 loss: 0.039215]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 403/500] [Batch 560/676] [D loss: -0.025186] [G loss: -0.146134] [d1 loss: 0.071257] [d2 loss: 0.049659]  [sq d1 d2: 0.000466]  [num0: 14.000000] [num1 50.000000]
[Epoch 403/500] [Batch 580/676] [D loss: -0.030665] [G loss: -0.164915] [d1 loss: 0.083225] [d2 loss: 0.075083]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 403/500] [Batch 600/676] [D loss: 0.016029] [G loss: -0.129069] [d1 loss: 0.048990] [d2 loss: 0.050242]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 403/500] [Batch 620/676] [D loss: -0.026671] [G loss: -0.070364] [d1 loss: 0.061505] [d2 loss: 0.046387]  [sq d1 d2: 0.000229]  [num0: 15.000000] [num1 49.000000]
[Epoch 403/500] [Batch 640/676] [D loss: 0.003282] [G loss: -0.022897] [d1 loss: 0.100045] [d2 loss: 0.118727]  [sq d1 d2: 0.000349]  [num0: 19.000000] [num1 45.000000]
[Epoch 403/500] [Batch 660/676] [D loss: 0.007995] [G loss: -0.002653] [d1 loss: 0.056801] [d2 loss: 0.058770]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 0/676] [D loss: 0.005327] [G loss: -0.010419] [d1 loss: 0.132653] [d2 loss: 0.139929]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 20/676] [D loss: 0.008664] [G loss: -0.000497] [d1 loss: 0.039879] [d2 loss: 0.043892]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 40/676] [D loss: -0.001253] [G loss: 0.026471] [d1 loss: 0.084875] [d2 loss: 0.045676]  [sq d1 d2: 0.001537]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 60/676] [D loss: -0.003793] [G loss: 0.050221] [d1 loss: 0.165681] [d2 loss: 0.108948]  [sq d1 d2: 0.003219]  [num0: 12.000000] [num1 52.000000]
[Epoch 404/500] [Batch 80/676] [D loss: -0.010326] [G loss: 0.055070] [d1 loss: 0.033102] [d2 loss: 0.029865]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 100/676] [D loss: -0.028318] [G loss: 0.046967] [d1 loss: 0.121306] [d2 loss: 0.111502]  [sq d1 d2: 0.000096]  [num0: 19.000000] [num1 45.000000]
[Epoch 404/500] [Batch 120/676] [D loss: -0.006709] [G loss: 0.025972] [d1 loss: 0.059251] [d2 loss: 0.066003]  [sq d1 d2: 0.000046]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 140/676] [D loss: -0.021460] [G loss: 0.022261] [d1 loss: 0.032819] [d2 loss: 0.033809]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 160/676] [D loss: 0.002366] [G loss: 0.016394] [d1 loss: 0.049105] [d2 loss: 0.051073]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 404/500] [Batch 180/676] [D loss: -0.023395] [G loss: -0.007709] [d1 loss: 0.149248] [d2 loss: 0.169056]  [sq d1 d2: 0.000392]  [num0: 19.000000] [num1 45.000000]
[Epoch 404/500] [Batch 200/676] [D loss: -0.000887] [G loss: -0.070061] [d1 loss: 0.082110] [d2 loss: 0.103661]  [sq d1 d2: 0.000464]  [num0: 11.000000] [num1 53.000000]
[Epoch 404/500] [Batch 220/676] [D loss: -0.015697] [G loss: -0.083413] [d1 loss: 0.052213] [d2 loss: 0.049927]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 240/676] [D loss: 0.014683] [G loss: -0.104720] [d1 loss: 0.025759] [d2 loss: 0.025239]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 404/500] [Batch 260/676] [D loss: -0.014848] [G loss: -0.079489] [d1 loss: 0.024626] [d2 loss: 0.024301]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 280/676] [D loss: -0.012604] [G loss: -0.098914] [d1 loss: 0.071518] [d2 loss: 0.078372]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 300/676] [D loss: -0.008889] [G loss: -0.100789] [d1 loss: 0.046839] [d2 loss: 0.042960]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 320/676] [D loss: 0.001561] [G loss: -0.107036] [d1 loss: 0.090567] [d2 loss: 0.081064]  [sq d1 d2: 0.000090]  [num0: 19.000000] [num1 45.000000]
[Epoch 404/500] [Batch 340/676] [D loss: -0.006832] [G loss: -0.093429] [d1 loss: 0.094046] [d2 loss: 0.081300]  [sq d1 d2: 0.000162]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 360/676] [D loss: -0.023309] [G loss: -0.090739] [d1 loss: 0.030038] [d2 loss: 0.038529]  [sq d1 d2: 0.000072]  [num0: 19.000000] [num1 45.000000]
[Epoch 404/500] [Batch 380/676] [D loss: -0.017867] [G loss: -0.102176] [d1 loss: 0.093788] [d2 loss: 0.103217]  [sq d1 d2: 0.000089]  [num0: 12.000000] [num1 52.000000]

[Epoch 404/500] [Batch 400/676] [D loss: -0.014149] [G loss: -0.100546] [d1 loss: 0.045751] [d2 loss: 0.042912]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 404/500] [Batch 420/676] [D loss: -0.028212] [G loss: -0.056841] [d1 loss: 0.157563] [d2 loss: 0.162006]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 440/676] [D loss: -0.020618] [G loss: -0.044546] [d1 loss: 0.068873] [d2 loss: 0.087368]  [sq d1 d2: 0.000342]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 460/676] [D loss: -0.002218] [G loss: -0.072442] [d1 loss: 0.062791] [d2 loss: 0.050364]  [sq d1 d2: 0.000154]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 480/676] [D loss: -0.012462] [G loss: -0.075371] [d1 loss: 0.123366] [d2 loss: 0.102517]  [sq d1 d2: 0.000435]  [num0: 14.000000] [num1 50.000000]
[Epoch 404/500] [Batch 500/676] [D loss: -0.016441] [G loss: -0.062095] [d1 loss: 0.061646] [d2 loss: 0.052996]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 520/676] [D loss: -0.003605] [G loss: -0.051072] [d1 loss: 0.086655] [d2 loss: 0.079202]  [sq d1 d2: 0.000056]  [num0: 13.000000] [num1 51.000000]
[Epoch 404/500] [Batch 540/676] [D loss: 0.000075] [G loss: -0.063427] [d1 loss: 0.058036] [d2 loss: 0.071947]  [sq d1 d2: 0.000194]  [num0: 18.000000] [num1 46.000000]
[Epoch 404/500] [Batch 560/676] [D loss: 0.000331] [G loss: -0.095280] [d1 loss: 0.068400] [d2 loss: 0.043749]  [sq d1 d2: 0.000608]  [num0: 17.000000] [num1 47.000000]
[Epoch 404/500] [Batch 580/676] [D loss: -0.016145] [G loss: -0.077305] [d1 loss: 0.122255] [d2 loss: 0.087679]  [sq d1 d2: 0.001195]  [num0: 14.000000] [num1 50.000000]
[Epoch 404/500] [Batch 600/676] [D loss: -0.006867] [G loss: -0.112679] [d1 loss: 0.085102] [d2 loss: 0.092490]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 620/676] [D loss: -0.002960] [G loss: -0.153115] [d1 loss: 0.060375] [d2 loss: 0.067445]  [sq d1 d2: 0.000050]  [num0: 15.000000] [num1 49.000000]
[Epoch 404/500] [Batch 640/676] [D loss: -0.020497] [G loss: -0.168018] [d1 loss: 0.103314] [d2 loss: 0.102405]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 404/500] [Batch 660/676] [D loss: -0.035578] [G loss: -0.200216] [d1 loss: 0.130894] [d2 loss: 0.089600]  [sq d1 d2: 0.001705]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 0/676] [D loss: -0.044153] [G loss: -0.242461] [d1 loss: 0.112496] [d2 loss: 0.108951]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 20/676] [D loss: -0.001765] [G loss: -0.244210] [d1 loss: 0.061916] [d2 loss: 0.062964]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 40/676] [D loss: -0.015666] [G loss: -0.279572] [d1 loss: 0.084731] [d2 loss: 0.070544]  [sq d1 d2: 0.000201]  [num0: 18.000000] [num1 46.000000]
[Epoch 405/500] [Batch 60/676] [D loss: 0.010487] [G loss: -0.295911] [d1 loss: 0.048857] [d2 loss: 0.049851]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 80/676] [D loss: 0.011169] [G loss: -0.282706] [d1 loss: 0.072551] [d2 loss: 0.073114]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 405/500] [Batch 100/676] [D loss: 0.019961] [G loss: -0.267862] [d1 loss: 0.107867] [d2 loss: 0.115865]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 405/500] [Batch 120/676] [D loss: 0.006731] [G loss: -0.220271] [d1 loss: 0.097731] [d2 loss: 0.105802]  [sq d1 d2: 0.000065]  [num0: 12.000000] [num1 52.000000]
[Epoch 405/500] [Batch 140/676] [D loss: -0.015934] [G loss: -0.220838] [d1 loss: 0.026198] [d2 loss: 0.028096]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 160/676] [D loss: -0.006972] [G loss: -0.228441] [d1 loss: 0.089349] [d2 loss: 0.094241]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 405/500] [Batch 180/676] [D loss: -0.020181] [G loss: -0.218298] [d1 loss: 0.076928] [d2 loss: 0.069616]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 200/676] [D loss: -0.020426] [G loss: -0.195359] [d1 loss: 0.023162] [d2 loss: 0.018186]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 220/676] [D loss: -0.006876] [G loss: -0.194192] [d1 loss: 0.066289] [d2 loss: 0.060998]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 405/500] [Batch 240/676] [D loss: -0.012838] [G loss: -0.187188] [d1 loss: 0.086511] [d2 loss: 0.072074]  [sq d1 d2: 0.000208]  [num0: 17.000000] [num1 47.000000]
[Epoch 405/500] [Batch 260/676] [D loss: -0.032512] [G loss: -0.161343] [d1 loss: 0.041660] [d2 loss: 0.031964]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 280/676] [D loss: -0.025676] [G loss: -0.153861] [d1 loss: 0.069672] [d2 loss: 0.066577]  [sq d1 d2: 0.000010]  [num0: 19.000000] [num1 45.000000]
[Epoch 405/500] [Batch 300/676] [D loss: -0.015339] [G loss: -0.117136] [d1 loss: 0.108173] [d2 loss: 0.129614]  [sq d1 d2: 0.000460]  [num0: 17.000000] [num1 47.000000]
[Epoch 405/500] [Batch 320/676] [D loss: 0.004202] [G loss: -0.078479] [d1 loss: 0.047200] [d2 loss: 0.047476]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 340/676] [D loss: 0.020088] [G loss: -0.032699] [d1 loss: 0.065256] [d2 loss: 0.061331]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 360/676] [D loss: 0.006815] [G loss: -0.033400] [d1 loss: 0.064127] [d2 loss: 0.062695]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 380/676] [D loss: 0.022290] [G loss: 0.025723] [d1 loss: 0.088110] [d2 loss: 0.071298]  [sq d1 d2: 0.000283]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 400/676] [D loss: 0.000948] [G loss: 0.048073] [d1 loss: 0.078372] [d2 loss: 0.059336]  [sq d1 d2: 0.000362]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 420/676] [D loss: -0.006892] [G loss: 0.063781] [d1 loss: 0.054418] [d2 loss: 0.046691]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 440/676] [D loss: -0.005780] [G loss: 0.079931] [d1 loss: 0.049116] [d2 loss: 0.042625]  [sq d1 d2: 0.000042]  [num0: 11.000000] [num1 53.000000]
[Epoch 405/500] [Batch 460/676] [D loss: -0.011335] [G loss: 0.050980] [d1 loss: 0.052776] [d2 loss: 0.053492]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 405/500] [Batch 480/676] [D loss: -0.005739] [G loss: 0.034582] [d1 loss: 0.075386] [d2 loss: 0.076924]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 500/676] [D loss: -0.007114] [G loss: 0.000548] [d1 loss: 0.033994] [d2 loss: 0.030230]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 520/676] [D loss: -0.041217] [G loss: 0.014689] [d1 loss: 0.039145] [d2 loss: 0.031400]  [sq d1 d2: 0.000060]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 540/676] [D loss: 0.012030] [G loss: -0.002832] [d1 loss: 0.030250] [d2 loss: 0.031979]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 560/676] [D loss: -0.018940] [G loss: -0.010182] [d1 loss: 0.043017] [d2 loss: 0.046559]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 405/500] [Batch 580/676] [D loss: -0.010085] [G loss: -0.032543] [d1 loss: 0.058284] [d2 loss: 0.054555]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 600/676] [D loss: -0.019281] [G loss: -0.054586] [d1 loss: 0.029188] [d2 loss: 0.037739]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 620/676] [D loss: -0.008114] [G loss: -0.101428] [d1 loss: 0.059634] [d2 loss: 0.061107]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 405/500] [Batch 640/676] [D loss: -0.013134] [G loss: -0.121698] [d1 loss: 0.046834] [d2 loss: 0.045258]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 405/500] [Batch 660/676] [D loss: -0.006778] [G loss: -0.116991] [d1 loss: 0.065434] [d2 loss: 0.062832]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 406/500] [Batch 0/676] [D loss: -0.015208] [G loss: -0.104242] [d1 loss: 0.087214] [d2 loss: 0.097460]  [sq d1 d2: 0.000105]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 20/676] [D loss: -0.004820] [G loss: -0.124167] [d1 loss: 0.114818] [d2 loss: 0.104199]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 40/676] [D loss: 0.003202] [G loss: -0.117801] [d1 loss: 0.077319] [d2 loss: 0.076813]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 406/500] [Batch 60/676] [D loss: -0.002945] [G loss: -0.117627] [d1 loss: 0.030219] [d2 loss: 0.029441]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]

[Epoch 406/500] [Batch 80/676] [D loss: -0.014050] [G loss: -0.108672] [d1 loss: 0.065677] [d2 loss: 0.065602]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 406/500] [Batch 100/676] [D loss: -0.007258] [G loss: -0.109686] [d1 loss: 0.059932] [d2 loss: 0.048532]  [sq d1 d2: 0.000130]  [num0: 18.000000] [num1 46.000000]
[Epoch 406/500] [Batch 120/676] [D loss: -0.026567] [G loss: -0.120393] [d1 loss: 0.036393] [d2 loss: 0.042678]  [sq d1 d2: 0.000040]  [num0: 19.000000] [num1 45.000000]
[Epoch 406/500] [Batch 140/676] [D loss: -0.009917] [G loss: -0.084038] [d1 loss: 0.056741] [d2 loss: 0.048319]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 406/500] [Batch 160/676] [D loss: 0.003261] [G loss: -0.079838] [d1 loss: 0.121704] [d2 loss: 0.132594]  [sq d1 d2: 0.000119]  [num0: 18.000000] [num1 46.000000]
[Epoch 406/500] [Batch 180/676] [D loss: -0.003549] [G loss: -0.079330] [d1 loss: 0.053847] [d2 loss: 0.055229]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 200/676] [D loss: -0.015366] [G loss: -0.052450] [d1 loss: 0.057495] [d2 loss: 0.059081]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 406/500] [Batch 220/676] [D loss: 0.006570] [G loss: -0.029621] [d1 loss: 0.091714] [d2 loss: 0.109344]  [sq d1 d2: 0.000311]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 240/676] [D loss: -0.009900] [G loss: -0.046891] [d1 loss: 0.057593] [d2 loss: 0.075164]  [sq d1 d2: 0.000309]  [num0: 16.000000] [num1 48.000000]
[Epoch 406/500] [Batch 260/676] [D loss: -0.015930] [G loss: -0.020196] [d1 loss: 0.061690] [d2 loss: 0.068663]  [sq d1 d2: 0.000049]  [num0: 13.000000] [num1 51.000000]
[Epoch 406/500] [Batch 280/676] [D loss: -0.015098] [G loss: -0.034668] [d1 loss: 0.045264] [d2 loss: 0.049588]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 406/500] [Batch 300/676] [D loss: -0.009437] [G loss: -0.060006] [d1 loss: 0.054583] [d2 loss: 0.041196]  [sq d1 d2: 0.000179]  [num0: 14.000000] [num1 50.000000]
[Epoch 406/500] [Batch 320/676] [D loss: -0.011199] [G loss: -0.065510] [d1 loss: 0.020281] [d2 loss: 0.026794]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 406/500] [Batch 340/676] [D loss: -0.032494] [G loss: -0.098906] [d1 loss: 0.144942] [d2 loss: 0.130112]  [sq d1 d2: 0.000220]  [num0: 20.000000] [num1 44.000000]
[Epoch 406/500] [Batch 360/676] [D loss: -0.014365] [G loss: -0.122094] [d1 loss: 0.083914] [d2 loss: 0.087109]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 380/676] [D loss: -0.022726] [G loss: -0.129929] [d1 loss: 0.116630] [d2 loss: 0.126360]  [sq d1 d2: 0.000095]  [num0: 16.000000] [num1 48.000000]
[Epoch 406/500] [Batch 400/676] [D loss: -0.024655] [G loss: -0.144496] [d1 loss: 0.070097] [d2 loss: 0.064194]  [sq d1 d2: 0.000035]  [num0: 19.000000] [num1 45.000000]
[Epoch 406/500] [Batch 420/676] [D loss: -0.007472] [G loss: -0.157940] [d1 loss: 0.108295] [d2 loss: 0.109328]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 406/500] [Batch 440/676] [D loss: -0.002272] [G loss: -0.186324] [d1 loss: 0.096141] [d2 loss: 0.133118]  [sq d1 d2: 0.001367]  [num0: 14.000000] [num1 50.000000]
[Epoch 406/500] [Batch 460/676] [D loss: -0.008894] [G loss: -0.190229] [d1 loss: 0.030067] [d2 loss: 0.028783]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 406/500] [Batch 480/676] [D loss: 0.003424] [G loss: -0.158958] [d1 loss: 0.059677] [d2 loss: 0.065223]  [sq d1 d2: 0.000031]  [num0: 12.000000] [num1 52.000000]
[Epoch 406/500] [Batch 500/676] [D loss: -0.007106] [G loss: -0.149568] [d1 loss: 0.047608] [d2 loss: 0.055118]  [sq d1 d2: 0.000056]  [num0: 18.000000] [num1 46.000000]
[Epoch 406/500] [Batch 520/676] [D loss: -0.007108] [G loss: -0.113039] [d1 loss: 0.060332] [d2 loss: 0.050483]  [sq d1 d2: 0.000097]  [num0: 19.000000] [num1 45.000000]
[Epoch 406/500] [Batch 540/676] [D loss: -0.009095] [G loss: -0.121029] [d1 loss: 0.100628] [d2 loss: 0.087219]  [sq d1 d2: 0.000180]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 560/676] [D loss: -0.024324] [G loss: -0.098363] [d1 loss: 0.089879] [d2 loss: 0.094890]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 406/500] [Batch 580/676] [D loss: -0.013338] [G loss: -0.054858] [d1 loss: 0.043229] [d2 loss: 0.042509]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 406/500] [Batch 600/676] [D loss: -0.013519] [G loss: -0.033198] [d1 loss: 0.067244] [d2 loss: 0.047387]  [sq d1 d2: 0.000394]  [num0: 17.000000] [num1 47.000000]
[Epoch 406/500] [Batch 620/676] [D loss: -0.006293] [G loss: -0.017011] [d1 loss: 0.037478] [d2 loss: 0.048773]  [sq d1 d2: 0.000128]  [num0: 20.000000] [num1 44.000000]
[Epoch 406/500] [Batch 640/676] [D loss: 0.004457] [G loss: -0.024146] [d1 loss: 0.039887] [d2 loss: 0.043170]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 406/500] [Batch 660/676] [D loss: -0.014404] [G loss: -0.013550] [d1 loss: 0.056151] [d2 loss: 0.075194]  [sq d1 d2: 0.000363]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 0/676] [D loss: -0.007650] [G loss: -0.042088] [d1 loss: 0.064343] [d2 loss: 0.074374]  [sq d1 d2: 0.000101]  [num0: 19.000000] [num1 45.000000]
[Epoch 407/500] [Batch 20/676] [D loss: 0.015578] [G loss: -0.020530] [d1 loss: 0.040376] [d2 loss: 0.063626]  [sq d1 d2: 0.000541]  [num0: 12.000000] [num1 52.000000]
[Epoch 407/500] [Batch 40/676] [D loss: 0.010128] [G loss: -0.034233] [d1 loss: 0.078037] [d2 loss: 0.068418]  [sq d1 d2: 0.000093]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 60/676] [D loss: 0.000590] [G loss: 0.003815] [d1 loss: 0.048844] [d2 loss: 0.035054]  [sq d1 d2: 0.000190]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 80/676] [D loss: -0.001839] [G loss: -0.013709] [d1 loss: 0.055863] [d2 loss: 0.073039]  [sq d1 d2: 0.000295]  [num0: 15.000000] [num1 49.000000]
[Epoch 407/500] [Batch 100/676] [D loss: -0.008271] [G loss: -0.002267] [d1 loss: 0.079219] [d2 loss: 0.080628]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 407/500] [Batch 120/676] [D loss: -0.011587] [G loss: -0.014559] [d1 loss: 0.066662] [d2 loss: 0.070285]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 407/500] [Batch 140/676] [D loss: -0.012405] [G loss: -0.003363] [d1 loss: 0.080359] [d2 loss: 0.084062]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 407/500] [Batch 160/676] [D loss: -0.008060] [G loss: -0.024396] [d1 loss: 0.049153] [d2 loss: 0.060823]  [sq d1 d2: 0.000136]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 180/676] [D loss: -0.026173] [G loss: -0.044012] [d1 loss: 0.041697] [d2 loss: 0.041406]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 200/676] [D loss: -0.005472] [G loss: -0.056494] [d1 loss: 0.107792] [d2 loss: 0.089905]  [sq d1 d2: 0.000320]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 220/676] [D loss: -0.001914] [G loss: -0.081418] [d1 loss: 0.045623] [d2 loss: 0.050388]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 407/500] [Batch 240/676] [D loss: -0.009413] [G loss: -0.082406] [d1 loss: 0.033838] [d2 loss: 0.033690]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 260/676] [D loss: -0.011265] [G loss: -0.127169] [d1 loss: 0.084843] [d2 loss: 0.093692]  [sq d1 d2: 0.000078]  [num0: 15.000000] [num1 49.000000]
[Epoch 407/500] [Batch 280/676] [D loss: 0.000023] [G loss: -0.128826] [d1 loss: 0.060967] [d2 loss: 0.050337]  [sq d1 d2: 0.000113]  [num0: 14.000000] [num1 50.000000]
[Epoch 407/500] [Batch 300/676] [D loss: 0.001100] [G loss: -0.148120] [d1 loss: 0.081506] [d2 loss: 0.088830]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 320/676] [D loss: 0.004697] [G loss: -0.154523] [d1 loss: 0.051524] [d2 loss: 0.047715]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 340/676] [D loss: -0.009471] [G loss: -0.181834] [d1 loss: 0.106571] [d2 loss: 0.091187]  [sq d1 d2: 0.000237]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 360/676] [D loss: -0.001965] [G loss: -0.166799] [d1 loss: 0.060547] [d2 loss: 0.081650]  [sq d1 d2: 0.000445]  [num0: 15.000000] [num1 49.000000]
[Epoch 407/500] [Batch 380/676] [D loss: -0.005193] [G loss: -0.159964] [d1 loss: 0.078494] [d2 loss: 0.069937]  [sq d1 d2: 0.000073]  [num0: 13.000000] [num1 51.000000]
[Epoch 407/500] [Batch 400/676] [D loss: -0.008099] [G loss: -0.147074] [d1 loss: 0.120515] [d2 loss: 0.105219]  [sq d1 d2: 0.000234]  [num0: 20.000000] [num1 44.000000]
[Epoch 407/500] [Batch 420/676] [D loss: -0.008738] [G loss: -0.155152] [d1 loss: 0.080051] [d2 loss: 0.045739]  [sq d1 d2: 0.001177]  [num0: 14.000000] [num1 50.000000]

[Epoch 407/500] [Batch 440/676] [D loss: -0.012172] [G loss: -0.143268] [d1 loss: 0.046518] [d2 loss: 0.040852]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 460/676] [D loss: 0.006409] [G loss: -0.177258] [d1 loss: 0.058604] [d2 loss: 0.062674]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 407/500] [Batch 480/676] [D loss: -0.003325] [G loss: -0.184580] [d1 loss: 0.080688] [d2 loss: 0.084526]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 407/500] [Batch 500/676] [D loss: -0.006602] [G loss: -0.169983] [d1 loss: 0.050349] [d2 loss: 0.059413]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 520/676] [D loss: -0.001077] [G loss: -0.143334] [d1 loss: 0.129179] [d2 loss: 0.129935]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 407/500] [Batch 540/676] [D loss: -0.001304] [G loss: -0.119529] [d1 loss: 0.048067] [d2 loss: 0.054266]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 407/500] [Batch 560/676] [D loss: -0.003897] [G loss: -0.073105] [d1 loss: 0.076265] [d2 loss: 0.073499]  [sq d1 d2: 0.000008]  [num0: 11.000000] [num1 53.000000]
[Epoch 407/500] [Batch 580/676] [D loss: 0.001548] [G loss: -0.031342] [d1 loss: 0.083566] [d2 loss: 0.088692]  [sq d1 d2: 0.000026]  [num0: 12.000000] [num1 52.000000]
[Epoch 407/500] [Batch 600/676] [D loss: 0.001827] [G loss: -0.011518] [d1 loss: 0.068918] [d2 loss: 0.064874]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 407/500] [Batch 620/676] [D loss: 0.001195] [G loss: 0.009289] [d1 loss: 0.065344] [d2 loss: 0.083755]  [sq d1 d2: 0.000339]  [num0: 16.000000] [num1 48.000000]
[Epoch 407/500] [Batch 640/676] [D loss: 0.001588] [G loss: 0.032248] [d1 loss: 0.084968] [d2 loss: 0.075020]  [sq d1 d2: 0.000099]  [num0: 15.000000] [num1 49.000000]
[Epoch 407/500] [Batch 660/676] [D loss: -0.006795] [G loss: 0.073209] [d1 loss: 0.092753] [d2 loss: 0.093557]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 0/676] [D loss: -0.009247] [G loss: 0.092875] [d1 loss: 0.052757] [d2 loss: 0.051138]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 20/676] [D loss: 0.008436] [G loss: 0.086521] [d1 loss: 0.119301] [d2 loss: 0.096359]  [sq d1 d2: 0.000526]  [num0: 21.000000] [num1 43.000000]
[Epoch 408/500] [Batch 40/676] [D loss: -0.016990] [G loss: 0.111865] [d1 loss: 0.061877] [d2 loss: 0.077129]  [sq d1 d2: 0.000233]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 60/676] [D loss: -0.018559] [G loss: 0.113902] [d1 loss: 0.115106] [d2 loss: 0.129132]  [sq d1 d2: 0.000197]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 80/676] [D loss: -0.017616] [G loss: 0.136569] [d1 loss: 0.079759] [d2 loss: 0.087714]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 408/500] [Batch 100/676] [D loss: -0.000846] [G loss: 0.071984] [d1 loss: 0.090187] [d2 loss: 0.090043]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 408/500] [Batch 120/676] [D loss: -0.008925] [G loss: 0.069933] [d1 loss: 0.060401] [d2 loss: 0.052876]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 408/500] [Batch 140/676] [D loss: -0.031213] [G loss: 0.050862] [d1 loss: 0.055155] [d2 loss: 0.063739]  [sq d1 d2: 0.000074]  [num0: 19.000000] [num1 45.000000]
[Epoch 408/500] [Batch 160/676] [D loss: 0.011718] [G loss: 0.012054] [d1 loss: 0.134774] [d2 loss: 0.130256]  [sq d1 d2: 0.000020]  [num0: 20.000000] [num1 44.000000]
[Epoch 408/500] [Batch 180/676] [D loss: 0.002568] [G loss: -0.032576] [d1 loss: 0.043597] [d2 loss: 0.040863]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 408/500] [Batch 200/676] [D loss: -0.004597] [G loss: -0.032703] [d1 loss: 0.068289] [d2 loss: 0.080206]  [sq d1 d2: 0.000142]  [num0: 18.000000] [num1 46.000000]
[Epoch 408/500] [Batch 220/676] [D loss: -0.007644] [G loss: -0.058786] [d1 loss: 0.040864] [d2 loss: 0.042237]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 408/500] [Batch 240/676] [D loss: -0.010600] [G loss: -0.090733] [d1 loss: 0.061053] [d2 loss: 0.056270]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 260/676] [D loss: -0.016048] [G loss: -0.114673] [d1 loss: 0.163311] [d2 loss: 0.116423]  [sq d1 d2: 0.002198]  [num0: 14.000000] [num1 50.000000]
[Epoch 408/500] [Batch 280/676] [D loss: -0.018643] [G loss: -0.112495] [d1 loss: 0.111615] [d2 loss: 0.115925]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 300/676] [D loss: -0.018589] [G loss: -0.124534] [d1 loss: 0.066377] [d2 loss: 0.075120]  [sq d1 d2: 0.000076]  [num0: 17.000000] [num1 47.000000]
[Epoch 408/500] [Batch 320/676] [D loss: 0.005163] [G loss: -0.133921] [d1 loss: 0.054042] [d2 loss: 0.048952]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 408/500] [Batch 340/676] [D loss: 0.000099] [G loss: -0.151488] [d1 loss: 0.027373] [d2 loss: 0.031285]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 360/676] [D loss: -0.012403] [G loss: -0.140138] [d1 loss: 0.042339] [d2 loss: 0.050030]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 380/676] [D loss: 0.000901] [G loss: -0.127428] [d1 loss: 0.050591] [d2 loss: 0.054592]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 400/676] [D loss: 0.004989] [G loss: -0.164913] [d1 loss: 0.050767] [d2 loss: 0.044217]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 408/500] [Batch 420/676] [D loss: -0.005026] [G loss: -0.123898] [d1 loss: 0.061452] [d2 loss: 0.050825]  [sq d1 d2: 0.000113]  [num0: 12.000000] [num1 52.000000]
[Epoch 408/500] [Batch 440/676] [D loss: 0.001344] [G loss: -0.098866] [d1 loss: 0.035411] [d2 loss: 0.031340]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 408/500] [Batch 460/676] [D loss: -0.004299] [G loss: -0.078126] [d1 loss: 0.039804] [d2 loss: 0.039281]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 408/500] [Batch 480/676] [D loss: -0.007605] [G loss: -0.067428] [d1 loss: 0.070236] [d2 loss: 0.086536]  [sq d1 d2: 0.000266]  [num0: 17.000000] [num1 47.000000]
[Epoch 408/500] [Batch 500/676] [D loss: -0.009224] [G loss: -0.052046] [d1 loss: 0.058139] [d2 loss: 0.048644]  [sq d1 d2: 0.000090]  [num0: 15.000000] [num1 49.000000]
[Epoch 408/500] [Batch 520/676] [D loss: -0.016381] [G loss: -0.027067] [d1 loss: 0.043929] [d2 loss: 0.035338]  [sq d1 d2: 0.000074]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 540/676] [D loss: -0.007072] [G loss: -0.018504] [d1 loss: 0.099843] [d2 loss: 0.121045]  [sq d1 d2: 0.000450]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 560/676] [D loss: -0.008800] [G loss: -0.011647] [d1 loss: 0.028219] [d2 loss: 0.023591]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 580/676] [D loss: -0.006808] [G loss: -0.027374] [d1 loss: 0.071044] [d2 loss: 0.062798]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 408/500] [Batch 600/676] [D loss: 0.005675] [G loss: -0.028547] [d1 loss: 0.025596] [d2 loss: 0.027209]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 408/500] [Batch 620/676] [D loss: -0.014243] [G loss: -0.039439] [d1 loss: 0.089042] [d2 loss: 0.088531]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 408/500] [Batch 640/676] [D loss: 0.000568] [G loss: -0.022467] [d1 loss: 0.045442] [d2 loss: 0.046304]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 408/500] [Batch 660/676] [D loss: -0.005648] [G loss: -0.038152] [d1 loss: 0.017173] [d2 loss: 0.018781]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 409/500] [Batch 0/676] [D loss: -0.011372] [G loss: -0.049642] [d1 loss: 0.015700] [d2 loss: 0.012103]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 20/676] [D loss: -0.004870] [G loss: -0.054486] [d1 loss: 0.037695] [d2 loss: 0.038971]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 40/676] [D loss: -0.006498] [G loss: -0.058971] [d1 loss: 0.072417] [d2 loss: 0.072332]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 409/500] [Batch 60/676] [D loss: -0.004044] [G loss: -0.096392] [d1 loss: 0.077314] [d2 loss: 0.103363]  [sq d1 d2: 0.000679]  [num0: 17.000000] [num1 47.000000]
[Epoch 409/500] [Batch 80/676] [D loss: -0.009138] [G loss: -0.130553] [d1 loss: 0.118497] [d2 loss: 0.123018]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 100/676] [D loss: -0.023794] [G loss: -0.172358] [d1 loss: 0.130063] [d2 loss: 0.139046]  [sq d1 d2: 0.000081]  [num0: 18.000000] [num1 46.000000]

[Epoch 409/500] [Batch 120/676] [D loss: -0.023144] [G loss: -0.203950] [d1 loss: 0.116702] [d2 loss: 0.086422]  [sq d1 d2: 0.000917]  [num0: 19.000000] [num1 45.000000]
[Epoch 409/500] [Batch 140/676] [D loss: 0.009582] [G loss: -0.203947] [d1 loss: 0.032992] [d2 loss: 0.037589]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 160/676] [D loss: -0.021551] [G loss: -0.207562] [d1 loss: 0.129712] [d2 loss: 0.137449]  [sq d1 d2: 0.000060]  [num0: 19.000000] [num1 45.000000]
[Epoch 409/500] [Batch 180/676] [D loss: -0.015734] [G loss: -0.157055] [d1 loss: 0.087175] [d2 loss: 0.073101]  [sq d1 d2: 0.000198]  [num0: 17.000000] [num1 47.000000]
[Epoch 409/500] [Batch 200/676] [D loss: 0.000829] [G loss: -0.119536] [d1 loss: 0.088868] [d2 loss: 0.082115]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 409/500] [Batch 220/676] [D loss: -0.005162] [G loss: -0.110086] [d1 loss: 0.075726] [d2 loss: 0.070023]  [sq d1 d2: 0.000033]  [num0: 11.000000] [num1 53.000000]
[Epoch 409/500] [Batch 240/676] [D loss: -0.002931] [G loss: -0.095410] [d1 loss: 0.115030] [d2 loss: 0.117639]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 409/500] [Batch 260/676] [D loss: -0.008323] [G loss: -0.088060] [d1 loss: 0.047404] [d2 loss: 0.063400]  [sq d1 d2: 0.000256]  [num0: 13.000000] [num1 51.000000]
[Epoch 409/500] [Batch 280/676] [D loss: -0.016678] [G loss: -0.068877] [d1 loss: 0.038409] [d2 loss: 0.035774]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 409/500] [Batch 300/676] [D loss: -0.015965] [G loss: -0.092825] [d1 loss: 0.048933] [d2 loss: 0.057383]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 409/500] [Batch 320/676] [D loss: -0.018110] [G loss: -0.082444] [d1 loss: 0.069002] [d2 loss: 0.073573]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 340/676] [D loss: -0.002180] [G loss: -0.082909] [d1 loss: 0.062755] [d2 loss: 0.049335]  [sq d1 d2: 0.000180]  [num0: 19.000000] [num1 45.000000]
[Epoch 409/500] [Batch 360/676] [D loss: -0.025242] [G loss: -0.081388] [d1 loss: 0.086987] [d2 loss: 0.059800]  [sq d1 d2: 0.000739]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 380/676] [D loss: -0.004398] [G loss: -0.067872] [d1 loss: 0.187118] [d2 loss: 0.165943]  [sq d1 d2: 0.000448]  [num0: 17.000000] [num1 47.000000]
[Epoch 409/500] [Batch 400/676] [D loss: -0.001221] [G loss: -0.056491] [d1 loss: 0.039792] [d2 loss: 0.037582]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 409/500] [Batch 420/676] [D loss: 0.004238] [G loss: -0.069972] [d1 loss: 0.060880] [d2 loss: 0.055594]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 440/676] [D loss: -0.006142] [G loss: -0.077697] [d1 loss: 0.069683] [d2 loss: 0.054457]  [sq d1 d2: 0.000232]  [num0: 15.000000] [num1 49.000000]
[Epoch 409/500] [Batch 460/676] [D loss: -0.000692] [G loss: -0.071269] [d1 loss: 0.053636] [d2 loss: 0.062068]  [sq d1 d2: 0.000071]  [num0: 16.000000] [num1 48.000000]
[Epoch 409/500] [Batch 480/676] [D loss: -0.003181] [G loss: -0.071819] [d1 loss: 0.067583] [d2 loss: 0.065038]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 409/500] [Batch 500/676] [D loss: -0.011773] [G loss: -0.094328] [d1 loss: 0.018257] [d2 loss: 0.020065]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 409/500] [Batch 520/676] [D loss: -0.016796] [G loss: -0.098219] [d1 loss: 0.086260] [d2 loss: 0.091246]  [sq d1 d2: 0.000025]  [num0: 11.000000] [num1 53.000000]
[Epoch 409/500] [Batch 540/676] [D loss: -0.024285] [G loss: -0.087419] [d1 loss: 0.032788] [d2 loss: 0.032208]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 409/500] [Batch 560/676] [D loss: -0.011207] [G loss: -0.100763] [d1 loss: 0.093986] [d2 loss: 0.110521]  [sq d1 d2: 0.000273]  [num0: 18.000000] [num1 46.000000]
[Epoch 409/500] [Batch 580/676] [D loss: -0.012653] [G loss: -0.114868] [d1 loss: 0.157289] [d2 loss: 0.097259]  [sq d1 d2: 0.003604]  [num0: 20.000000] [num1 44.000000]
[Epoch 409/500] [Batch 600/676] [D loss: -0.031125] [G loss: -0.105834] [d1 loss: 0.056862] [d2 loss: 0.062549]  [sq d1 d2: 0.000032]  [num0: 12.000000] [num1 52.000000]
[Epoch 409/500] [Batch 620/676] [D loss: -0.019512] [G loss: -0.100347] [d1 loss: 0.068890] [d2 loss: 0.087959]  [sq d1 d2: 0.000364]  [num0: 17.000000] [num1 47.000000]
[Epoch 409/500] [Batch 640/676] [D loss: -0.031200] [G loss: -0.109464] [d1 loss: 0.070845] [d2 loss: 0.084389]  [sq d1 d2: 0.000183]  [num0: 19.000000] [num1 45.000000]
[Epoch 409/500] [Batch 660/676] [D loss: -0.010032] [G loss: -0.089393] [d1 loss: 0.080863] [d2 loss: 0.084180]  [sq d1 d2: 0.000011]  [num0: 22.000000] [num1 42.000000]
[Epoch 410/500] [Batch 0/676] [D loss: -0.002602] [G loss: -0.083887] [d1 loss: 0.023445] [d2 loss: 0.022852]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 20/676] [D loss: 0.013348] [G loss: -0.038484] [d1 loss: 0.058877] [d2 loss: 0.056883]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 410/500] [Batch 40/676] [D loss: -0.000161] [G loss: -0.022197] [d1 loss: 0.028640] [d2 loss: 0.032296]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 60/676] [D loss: 0.006109] [G loss: -0.041765] [d1 loss: 0.063456] [d2 loss: 0.079636]  [sq d1 d2: 0.000262]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 80/676] [D loss: -0.005389] [G loss: -0.039079] [d1 loss: 0.052653] [d2 loss: 0.070606]  [sq d1 d2: 0.000322]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 100/676] [D loss: -0.006758] [G loss: -0.050166] [d1 loss: 0.074120] [d2 loss: 0.062529]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 120/676] [D loss: -0.015379] [G loss: -0.066922] [d1 loss: 0.043853] [d2 loss: 0.049256]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 140/676] [D loss: -0.012623] [G loss: -0.057517] [d1 loss: 0.047495] [d2 loss: 0.032261]  [sq d1 d2: 0.000232]  [num0: 19.000000] [num1 45.000000]
[Epoch 410/500] [Batch 160/676] [D loss: -0.031899] [G loss: -0.087609] [d1 loss: 0.020085] [d2 loss: 0.021771]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 180/676] [D loss: -0.016252] [G loss: -0.104662] [d1 loss: 0.076107] [d2 loss: 0.079656]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 200/676] [D loss: -0.009551] [G loss: -0.149217] [d1 loss: 0.076747] [d2 loss: 0.092198]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 220/676] [D loss: -0.012384] [G loss: -0.163083] [d1 loss: 0.031919] [d2 loss: 0.024222]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 240/676] [D loss: -0.001867] [G loss: -0.156403] [d1 loss: 0.051823] [d2 loss: 0.053872]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 410/500] [Batch 260/676] [D loss: 0.000790] [G loss: -0.132005] [d1 loss: 0.058214] [d2 loss: 0.061930]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 410/500] [Batch 280/676] [D loss: -0.008215] [G loss: -0.140334] [d1 loss: 0.125927] [d2 loss: 0.104735]  [sq d1 d2: 0.000449]  [num0: 20.000000] [num1 44.000000]
[Epoch 410/500] [Batch 300/676] [D loss: -0.006943] [G loss: -0.132329] [d1 loss: 0.050670] [d2 loss: 0.053332]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 320/676] [D loss: -0.005709] [G loss: -0.108807] [d1 loss: 0.045075] [d2 loss: 0.037353]  [sq d1 d2: 0.000060]  [num0: 19.000000] [num1 45.000000]
[Epoch 410/500] [Batch 340/676] [D loss: -0.007778] [G loss: -0.097744] [d1 loss: 0.065602] [d2 loss: 0.065251]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 360/676] [D loss: -0.005584] [G loss: -0.085504] [d1 loss: 0.131700] [d2 loss: 0.161787]  [sq d1 d2: 0.000905]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 380/676] [D loss: -0.006065] [G loss: -0.050629] [d1 loss: 0.048668] [d2 loss: 0.044031]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 410/500] [Batch 400/676] [D loss: -0.018866] [G loss: -0.007369] [d1 loss: 0.068878] [d2 loss: 0.064012]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 420/676] [D loss: -0.010035] [G loss: -0.025033] [d1 loss: 0.060420] [d2 loss: 0.060603]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 410/500] [Batch 440/676] [D loss: -0.008930] [G loss: 0.000811] [d1 loss: 0.054922] [d2 loss: 0.046456]  [sq d1 d2: 0.000072]  [num0: 18.000000] [num1 46.000000]
[Epoch 410/500] [Batch 460/676] [D loss: -0.030685] [G loss: 0.062816] [d1 loss: 0.076779] [d2 loss: 0.044219]  [sq d1 d2: 0.001060]  [num0: 15.000000] [num1 49.000000]

[Epoch 410/500] [Batch 480/676] [D loss: 0.002827] [G loss: 0.060450] [d1 loss: 0.075553] [d2 loss: 0.077638]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 500/676] [D loss: 0.004695] [G loss: 0.088906] [d1 loss: 0.060784] [d2 loss: 0.059082]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 520/676] [D loss: -0.001990] [G loss: 0.090548] [d1 loss: 0.091873] [d2 loss: 0.091494]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 410/500] [Batch 540/676] [D loss: -0.000263] [G loss: 0.052781] [d1 loss: 0.028274] [d2 loss: 0.025603]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 410/500] [Batch 560/676] [D loss: -0.012133] [G loss: 0.051792] [d1 loss: 0.030198] [d2 loss: 0.031633]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 580/676] [D loss: -0.015229] [G loss: 0.056119] [d1 loss: 0.104908] [d2 loss: 0.075780]  [sq d1 d2: 0.000848]  [num0: 15.000000] [num1 49.000000]
[Epoch 410/500] [Batch 600/676] [D loss: -0.010402] [G loss: 0.016379] [d1 loss: 0.058520] [d2 loss: 0.057462]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 410/500] [Batch 620/676] [D loss: -0.017867] [G loss: 0.006558] [d1 loss: 0.026000] [d2 loss: 0.024157]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 410/500] [Batch 640/676] [D loss: -0.021232] [G loss: 0.012246] [d1 loss: 0.123316] [d2 loss: 0.108836]  [sq d1 d2: 0.000210]  [num0: 18.000000] [num1 46.000000]
[Epoch 410/500] [Batch 660/676] [D loss: -0.006636] [G loss: -0.003405] [d1 loss: 0.027310] [d2 loss: 0.028839]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 0/676] [D loss: 0.002661] [G loss: -0.033419] [d1 loss: 0.101592] [d2 loss: 0.099182]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 411/500] [Batch 20/676] [D loss: -0.005378] [G loss: -0.051157] [d1 loss: 0.071454] [d2 loss: 0.072336]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 411/500] [Batch 40/676] [D loss: 0.004600] [G loss: -0.066083] [d1 loss: 0.030840] [d2 loss: 0.043889]  [sq d1 d2: 0.000170]  [num0: 15.000000] [num1 49.000000]
[Epoch 411/500] [Batch 60/676] [D loss: -0.000722] [G loss: -0.090730] [d1 loss: 0.099891] [d2 loss: 0.094334]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 411/500] [Batch 80/676] [D loss: -0.003900] [G loss: -0.091856] [d1 loss: 0.062277] [d2 loss: 0.069242]  [sq d1 d2: 0.000049]  [num0: 11.000000] [num1 53.000000]
[Epoch 411/500] [Batch 100/676] [D loss: -0.016336] [G loss: -0.110844] [d1 loss: 0.032682] [d2 loss: 0.030144]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 411/500] [Batch 120/676] [D loss: -0.009902] [G loss: -0.128885] [d1 loss: 0.058015] [d2 loss: 0.075234]  [sq d1 d2: 0.000296]  [num0: 20.000000] [num1 44.000000]
[Epoch 411/500] [Batch 140/676] [D loss: -0.014336] [G loss: -0.132897] [d1 loss: 0.059451] [d2 loss: 0.064986]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 160/676] [D loss: -0.005793] [G loss: -0.146938] [d1 loss: 0.023713] [d2 loss: 0.028599]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 180/676] [D loss: 0.000277] [G loss: -0.146076] [d1 loss: 0.016430] [d2 loss: 0.021098]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 411/500] [Batch 200/676] [D loss: 0.000419] [G loss: -0.144338] [d1 loss: 0.062875] [d2 loss: 0.054689]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 220/676] [D loss: -0.004975] [G loss: -0.129513] [d1 loss: 0.078272] [d2 loss: 0.081997]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 411/500] [Batch 240/676] [D loss: -0.009845] [G loss: -0.105954] [d1 loss: 0.053445] [d2 loss: 0.015669]  [sq d1 d2: 0.001427]  [num0: 17.000000] [num1 47.000000]
[Epoch 411/500] [Batch 260/676] [D loss: -0.003539] [G loss: -0.124337] [d1 loss: 0.078208] [d2 loss: 0.085039]  [sq d1 d2: 0.000047]  [num0: 14.000000] [num1 50.000000]
[Epoch 411/500] [Batch 280/676] [D loss: -0.028230] [G loss: -0.089728] [d1 loss: 0.084119] [d2 loss: 0.080371]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 411/500] [Batch 300/676] [D loss: -0.009832] [G loss: -0.086377] [d1 loss: 0.134089] [d2 loss: 0.123294]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 320/676] [D loss: -0.008005] [G loss: -0.098111] [d1 loss: 0.057555] [d2 loss: 0.057105]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 340/676] [D loss: -0.004356] [G loss: -0.057325] [d1 loss: 0.040839] [d2 loss: 0.032545]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 360/676] [D loss: -0.006314] [G loss: -0.065564] [d1 loss: 0.019991] [d2 loss: 0.034899]  [sq d1 d2: 0.000222]  [num0: 22.000000] [num1 42.000000]
[Epoch 411/500] [Batch 380/676] [D loss: -0.007970] [G loss: -0.063412] [d1 loss: 0.068736] [d2 loss: 0.076108]  [sq d1 d2: 0.000054]  [num0: 13.000000] [num1 51.000000]
[Epoch 411/500] [Batch 400/676] [D loss: -0.000903] [G loss: -0.046221] [d1 loss: 0.052533] [d2 loss: 0.049699]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 420/676] [D loss: -0.017861] [G loss: -0.044335] [d1 loss: 0.054927] [d2 loss: 0.037913]  [sq d1 d2: 0.000289]  [num0: 15.000000] [num1 49.000000]
[Epoch 411/500] [Batch 440/676] [D loss: -0.019384] [G loss: -0.046254] [d1 loss: 0.069754] [d2 loss: 0.058003]  [sq d1 d2: 0.000138]  [num0: 12.000000] [num1 52.000000]
[Epoch 411/500] [Batch 460/676] [D loss: -0.014418] [G loss: -0.055064] [d1 loss: 0.121094] [d2 loss: 0.110000]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 480/676] [D loss: -0.000692] [G loss: -0.100928] [d1 loss: 0.035502] [d2 loss: 0.041763]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 411/500] [Batch 500/676] [D loss: -0.002700] [G loss: -0.076445] [d1 loss: 0.089941] [d2 loss: 0.085080]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 411/500] [Batch 520/676] [D loss: 0.001443] [G loss: -0.074339] [d1 loss: 0.018559] [d2 loss: 0.019896]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 540/676] [D loss: -0.001035] [G loss: -0.074718] [d1 loss: 0.073765] [d2 loss: 0.079332]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 560/676] [D loss: -0.003217] [G loss: -0.079845] [d1 loss: 0.050155] [d2 loss: 0.041180]  [sq d1 d2: 0.000081]  [num0: 15.000000] [num1 49.000000]
[Epoch 411/500] [Batch 580/676] [D loss: -0.008132] [G loss: -0.087986] [d1 loss: 0.042565] [d2 loss: 0.042769]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 411/500] [Batch 600/676] [D loss: -0.002639] [G loss: -0.092995] [d1 loss: 0.063565] [d2 loss: 0.058075]  [sq d1 d2: 0.000030]  [num0: 18.000000] [num1 46.000000]
[Epoch 411/500] [Batch 620/676] [D loss: -0.003454] [G loss: -0.102909] [d1 loss: 0.105515] [d2 loss: 0.102918]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 411/500] [Batch 640/676] [D loss: -0.008168] [G loss: -0.116772] [d1 loss: 0.053560] [d2 loss: 0.061575]  [sq d1 d2: 0.000064]  [num0: 17.000000] [num1 47.000000]
[Epoch 411/500] [Batch 660/676] [D loss: -0.007309] [G loss: -0.104231] [d1 loss: 0.084763] [d2 loss: 0.089873]  [sq d1 d2: 0.000026]  [num0: 15.000000] [num1 49.000000]
[Epoch 412/500] [Batch 0/676] [D loss: -0.010545] [G loss: -0.105988] [d1 loss: 0.106127] [d2 loss: 0.105193]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 20/676] [D loss: -0.020545] [G loss: -0.139901] [d1 loss: 0.077653] [d2 loss: 0.075347]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 40/676] [D loss: -0.008337] [G loss: -0.135983] [d1 loss: 0.104554] [d2 loss: 0.068967]  [sq d1 d2: 0.001266]  [num0: 18.000000] [num1 46.000000]
[Epoch 412/500] [Batch 60/676] [D loss: 0.009161] [G loss: -0.133272] [d1 loss: 0.081339] [d2 loss: 0.063218]  [sq d1 d2: 0.000328]  [num0: 18.000000] [num1 46.000000]
[Epoch 412/500] [Batch 80/676] [D loss: 0.002903] [G loss: -0.108206] [d1 loss: 0.070672] [d2 loss: 0.041077]  [sq d1 d2: 0.000876]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 100/676] [D loss: -0.002579] [G loss: -0.077360] [d1 loss: 0.070444] [d2 loss: 0.067148]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 412/500] [Batch 120/676] [D loss: -0.000105] [G loss: -0.075602] [d1 loss: 0.032260] [d2 loss: 0.028043]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 140/676] [D loss: -0.004818] [G loss: -0.068148] [d1 loss: 0.061781] [d2 loss: 0.072771]  [sq d1 d2: 0.000121]  [num0: 14.000000] [num1 50.000000]

[Epoch 412/500] [Batch 160/676] [D loss: -0.009663] [G loss: -0.077138] [d1 loss: 0.073519] [d2 loss: 0.087221]  [sq d1 d2: 0.000188]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 180/676] [D loss: -0.004213] [G loss: -0.080858] [d1 loss: 0.076398] [d2 loss: 0.081530]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 412/500] [Batch 200/676] [D loss: -0.011108] [G loss: -0.094181] [d1 loss: 0.065517] [d2 loss: 0.066970]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 220/676] [D loss: -0.025072] [G loss: -0.078768] [d1 loss: 0.076360] [d2 loss: 0.057702]  [sq d1 d2: 0.000348]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 240/676] [D loss: -0.018040] [G loss: -0.073442] [d1 loss: 0.051400] [d2 loss: 0.055263]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 260/676] [D loss: -0.000562] [G loss: -0.077935] [d1 loss: 0.104444] [d2 loss: 0.087601]  [sq d1 d2: 0.000284]  [num0: 19.000000] [num1 45.000000]
[Epoch 412/500] [Batch 280/676] [D loss: -0.022065] [G loss: -0.066507] [d1 loss: 0.048068] [d2 loss: 0.062540]  [sq d1 d2: 0.000209]  [num0: 15.000000] [num1 49.000000]
[Epoch 412/500] [Batch 300/676] [D loss: -0.004778] [G loss: -0.053975] [d1 loss: 0.047410] [d2 loss: 0.033471]  [sq d1 d2: 0.000194]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 320/676] [D loss: 0.000579] [G loss: -0.041219] [d1 loss: 0.130786] [d2 loss: 0.125069]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 412/500] [Batch 340/676] [D loss: 0.002763] [G loss: -0.051400] [d1 loss: 0.057917] [d2 loss: 0.051488]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 412/500] [Batch 360/676] [D loss: -0.001177] [G loss: -0.048963] [d1 loss: 0.102187] [d2 loss: 0.107937]  [sq d1 d2: 0.000033]  [num0: 19.000000] [num1 45.000000]
[Epoch 412/500] [Batch 380/676] [D loss: -0.001915] [G loss: -0.066961] [d1 loss: 0.088333] [d2 loss: 0.097685]  [sq d1 d2: 0.000087]  [num0: 9.000000] [num1 55.000000]
[Epoch 412/500] [Batch 400/676] [D loss: -0.004524] [G loss: -0.090519] [d1 loss: 0.082558] [d2 loss: 0.079548]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 412/500] [Batch 420/676] [D loss: -0.009653] [G loss: -0.080103] [d1 loss: 0.089616] [d2 loss: 0.078071]  [sq d1 d2: 0.000133]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 440/676] [D loss: -0.009471] [G loss: -0.093778] [d1 loss: 0.073244] [d2 loss: 0.063946]  [sq d1 d2: 0.000086]  [num0: 16.000000] [num1 48.000000]
[Epoch 412/500] [Batch 460/676] [D loss: -0.006942] [G loss: -0.092757] [d1 loss: 0.150895] [d2 loss: 0.147211]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 480/676] [D loss: -0.009487] [G loss: -0.106114] [d1 loss: 0.029617] [d2 loss: 0.028736]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 412/500] [Batch 500/676] [D loss: -0.012448] [G loss: -0.103917] [d1 loss: 0.065322] [d2 loss: 0.071507]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 520/676] [D loss: -0.021189] [G loss: -0.090189] [d1 loss: 0.083345] [d2 loss: 0.073513]  [sq d1 d2: 0.000097]  [num0: 19.000000] [num1 45.000000]
[Epoch 412/500] [Batch 540/676] [D loss: 0.013897] [G loss: -0.104354] [d1 loss: 0.058252] [d2 loss: 0.040309]  [sq d1 d2: 0.000322]  [num0: 13.000000] [num1 51.000000]
[Epoch 412/500] [Batch 560/676] [D loss: -0.000037] [G loss: -0.096391] [d1 loss: 0.062061] [d2 loss: 0.071747]  [sq d1 d2: 0.000094]  [num0: 15.000000] [num1 49.000000]
[Epoch 412/500] [Batch 580/676] [D loss: -0.019397] [G loss: -0.080818] [d1 loss: 0.079839] [d2 loss: 0.047204]  [sq d1 d2: 0.001065]  [num0: 18.000000] [num1 46.000000]
[Epoch 412/500] [Batch 600/676] [D loss: 0.008675] [G loss: -0.095084] [d1 loss: 0.024883] [d2 loss: 0.019818]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 412/500] [Batch 620/676] [D loss: 0.002118] [G loss: -0.083353] [d1 loss: 0.043326] [d2 loss: 0.055023]  [sq d1 d2: 0.000137]  [num0: 17.000000] [num1 47.000000]
[Epoch 412/500] [Batch 640/676] [D loss: -0.001643] [G loss: -0.062317] [d1 loss: 0.078842] [d2 loss: 0.076618]  [sq d1 d2: 0.000005]  [num0: 11.000000] [num1 53.000000]
[Epoch 412/500] [Batch 660/676] [D loss: -0.004063] [G loss: -0.050924] [d1 loss: 0.066797] [d2 loss: 0.032582]  [sq d1 d2: 0.001171]  [num0: 15.000000] [num1 49.000000]
[Epoch 413/500] [Batch 0/676] [D loss: -0.009995] [G loss: -0.053645] [d1 loss: 0.047637] [d2 loss: 0.052432]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 20/676] [D loss: -0.007344] [G loss: -0.039089] [d1 loss: 0.050322] [d2 loss: 0.056892]  [sq d1 d2: 0.000043]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 40/676] [D loss: -0.008829] [G loss: -0.054203] [d1 loss: 0.062616] [d2 loss: 0.074964]  [sq d1 d2: 0.000152]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 60/676] [D loss: -0.006142] [G loss: -0.047150] [d1 loss: 0.080839] [d2 loss: 0.066247]  [sq d1 d2: 0.000213]  [num0: 16.000000] [num1 48.000000]
[Epoch 413/500] [Batch 80/676] [D loss: -0.019422] [G loss: -0.038370] [d1 loss: 0.085165] [d2 loss: 0.098300]  [sq d1 d2: 0.000173]  [num0: 12.000000] [num1 52.000000]
[Epoch 413/500] [Batch 100/676] [D loss: -0.003237] [G loss: -0.022047] [d1 loss: 0.170062] [d2 loss: 0.140383]  [sq d1 d2: 0.000881]  [num0: 20.000000] [num1 44.000000]
[Epoch 413/500] [Batch 120/676] [D loss: 0.002276] [G loss: -0.006749] [d1 loss: 0.095445] [d2 loss: 0.096631]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 413/500] [Batch 140/676] [D loss: -0.003428] [G loss: -0.043202] [d1 loss: 0.092805] [d2 loss: 0.098891]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 160/676] [D loss: -0.019618] [G loss: -0.038512] [d1 loss: 0.063485] [d2 loss: 0.073806]  [sq d1 d2: 0.000107]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 180/676] [D loss: 0.004927] [G loss: -0.052036] [d1 loss: 0.067299] [d2 loss: 0.060145]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 200/676] [D loss: 0.007836] [G loss: -0.037611] [d1 loss: 0.015761] [d2 loss: 0.017099]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 220/676] [D loss: 0.016207] [G loss: -0.044139] [d1 loss: 0.101649] [d2 loss: 0.098656]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 413/500] [Batch 240/676] [D loss: -0.000276] [G loss: -0.059909] [d1 loss: 0.050698] [d2 loss: 0.041335]  [sq d1 d2: 0.000088]  [num0: 16.000000] [num1 48.000000]
[Epoch 413/500] [Batch 260/676] [D loss: -0.013907] [G loss: -0.084391] [d1 loss: 0.100104] [d2 loss: 0.093932]  [sq d1 d2: 0.000038]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 280/676] [D loss: -0.010001] [G loss: -0.088804] [d1 loss: 0.083191] [d2 loss: 0.079109]  [sq d1 d2: 0.000017]  [num0: 21.000000] [num1 43.000000]
[Epoch 413/500] [Batch 300/676] [D loss: -0.009646] [G loss: -0.099931] [d1 loss: 0.038656] [d2 loss: 0.047035]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 413/500] [Batch 320/676] [D loss: -0.020563] [G loss: -0.097195] [d1 loss: 0.012927] [d2 loss: 0.015461]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 413/500] [Batch 340/676] [D loss: -0.032661] [G loss: -0.130606] [d1 loss: 0.137364] [d2 loss: 0.133738]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 413/500] [Batch 360/676] [D loss: -0.015630] [G loss: -0.135543] [d1 loss: 0.073486] [d2 loss: 0.080594]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 413/500] [Batch 380/676] [D loss: 0.002529] [G loss: -0.197200] [d1 loss: 0.030994] [d2 loss: 0.028153]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 400/676] [D loss: -0.019832] [G loss: -0.190980] [d1 loss: 0.128134] [d2 loss: 0.108770]  [sq d1 d2: 0.000375]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 420/676] [D loss: 0.024848] [G loss: -0.197479] [d1 loss: 0.031749] [d2 loss: 0.034316]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 413/500] [Batch 440/676] [D loss: -0.005182] [G loss: -0.165624] [d1 loss: 0.055729] [d2 loss: 0.046991]  [sq d1 d2: 0.000076]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 460/676] [D loss: 0.008990] [G loss: -0.125261] [d1 loss: 0.079171] [d2 loss: 0.066421]  [sq d1 d2: 0.000163]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 480/676] [D loss: -0.002738] [G loss: -0.115765] [d1 loss: 0.110164] [d2 loss: 0.111549]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 413/500] [Batch 500/676] [D loss: 0.001637] [G loss: -0.124419] [d1 loss: 0.043740] [d2 loss: 0.045838]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]

[Epoch 413/500] [Batch 520/676] [D loss: 0.002570] [G loss: -0.112944] [d1 loss: 0.167539] [d2 loss: 0.133561]  [sq d1 d2: 0.001154]  [num0: 13.000000] [num1 51.000000]
[Epoch 413/500] [Batch 540/676] [D loss: -0.013301] [G loss: -0.077987] [d1 loss: 0.067357] [d2 loss: 0.053287]  [sq d1 d2: 0.000198]  [num0: 12.000000] [num1 52.000000]
[Epoch 413/500] [Batch 560/676] [D loss: -0.011197] [G loss: -0.067153] [d1 loss: 0.041751] [d2 loss: 0.030190]  [sq d1 d2: 0.000134]  [num0: 11.000000] [num1 53.000000]
[Epoch 413/500] [Batch 580/676] [D loss: -0.019142] [G loss: -0.075847] [d1 loss: 0.062696] [d2 loss: 0.060528]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 413/500] [Batch 600/676] [D loss: -0.031618] [G loss: -0.072761] [d1 loss: 0.062981] [d2 loss: 0.059556]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 413/500] [Batch 620/676] [D loss: -0.022015] [G loss: -0.079969] [d1 loss: 0.048321] [d2 loss: 0.053045]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 413/500] [Batch 640/676] [D loss: -0.018821] [G loss: -0.063817] [d1 loss: 0.070516] [d2 loss: 0.065902]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 413/500] [Batch 660/676] [D loss: -0.017574] [G loss: -0.034455] [d1 loss: 0.063090] [d2 loss: 0.065936]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 0/676] [D loss: -0.032394] [G loss: -0.049998] [d1 loss: 0.057868] [d2 loss: 0.066685]  [sq d1 d2: 0.000078]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 20/676] [D loss: 0.003272] [G loss: -0.078551] [d1 loss: 0.127496] [d2 loss: 0.139123]  [sq d1 d2: 0.000135]  [num0: 19.000000] [num1 45.000000]
[Epoch 414/500] [Batch 40/676] [D loss: 0.006615] [G loss: -0.080194] [d1 loss: 0.073720] [d2 loss: 0.063591]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 60/676] [D loss: 0.006596] [G loss: -0.083037] [d1 loss: 0.028746] [d2 loss: 0.028137]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 414/500] [Batch 80/676] [D loss: 0.009291] [G loss: -0.087278] [d1 loss: 0.078127] [d2 loss: 0.076456]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 414/500] [Batch 100/676] [D loss: -0.008676] [G loss: -0.097861] [d1 loss: 0.075733] [d2 loss: 0.068720]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 414/500] [Batch 120/676] [D loss: -0.023154] [G loss: -0.089895] [d1 loss: 0.049806] [d2 loss: 0.048149]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 140/676] [D loss: -0.011640] [G loss: -0.102008] [d1 loss: 0.051747] [d2 loss: 0.050312]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 414/500] [Batch 160/676] [D loss: -0.010280] [G loss: -0.143867] [d1 loss: 0.066459] [d2 loss: 0.058572]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 414/500] [Batch 180/676] [D loss: 0.007782] [G loss: -0.158713] [d1 loss: 0.073720] [d2 loss: 0.073201]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 200/676] [D loss: -0.041428] [G loss: -0.200172] [d1 loss: 0.034258] [d2 loss: 0.036166]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 414/500] [Batch 220/676] [D loss: -0.013387] [G loss: -0.182071] [d1 loss: 0.051356] [d2 loss: 0.055259]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 240/676] [D loss: -0.010415] [G loss: -0.201925] [d1 loss: 0.058738] [d2 loss: 0.059879]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 260/676] [D loss: -0.008383] [G loss: -0.193807] [d1 loss: 0.033075] [d2 loss: 0.033460]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 414/500] [Batch 280/676] [D loss: 0.005845] [G loss: -0.141531] [d1 loss: 0.017480] [d2 loss: 0.011299]  [sq d1 d2: 0.000038]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 300/676] [D loss: -0.003071] [G loss: -0.131239] [d1 loss: 0.074848] [d2 loss: 0.072685]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 320/676] [D loss: -0.016757] [G loss: -0.111968] [d1 loss: 0.016990] [d2 loss: 0.016500]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 340/676] [D loss: 0.002009] [G loss: -0.081332] [d1 loss: 0.086078] [d2 loss: 0.067356]  [sq d1 d2: 0.000351]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 360/676] [D loss: -0.004821] [G loss: -0.091845] [d1 loss: 0.066301] [d2 loss: 0.074133]  [sq d1 d2: 0.000061]  [num0: 19.000000] [num1 45.000000]
[Epoch 414/500] [Batch 380/676] [D loss: -0.001261] [G loss: -0.099471] [d1 loss: 0.089095] [d2 loss: 0.088298]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 414/500] [Batch 400/676] [D loss: -0.008133] [G loss: -0.070625] [d1 loss: 0.032958] [d2 loss: 0.030747]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 420/676] [D loss: -0.010853] [G loss: -0.088079] [d1 loss: 0.033851] [d2 loss: 0.026766]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 414/500] [Batch 440/676] [D loss: -0.006496] [G loss: -0.072514] [d1 loss: 0.021564] [d2 loss: 0.025055]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 460/676] [D loss: -0.015328] [G loss: -0.076019] [d1 loss: 0.104899] [d2 loss: 0.102521]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 480/676] [D loss: -0.016530] [G loss: -0.032828] [d1 loss: 0.082997] [d2 loss: 0.095553]  [sq d1 d2: 0.000158]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 500/676] [D loss: 0.001966] [G loss: -0.057724] [d1 loss: 0.040188] [d2 loss: 0.032960]  [sq d1 d2: 0.000052]  [num0: 12.000000] [num1 52.000000]
[Epoch 414/500] [Batch 520/676] [D loss: -0.009598] [G loss: -0.045311] [d1 loss: 0.042533] [d2 loss: 0.049701]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 414/500] [Batch 540/676] [D loss: 0.015694] [G loss: -0.037158] [d1 loss: 0.101671] [d2 loss: 0.092728]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 414/500] [Batch 560/676] [D loss: -0.010983] [G loss: -0.005592] [d1 loss: 0.103981] [d2 loss: 0.108425]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 580/676] [D loss: 0.010447] [G loss: -0.036352] [d1 loss: 0.058918] [d2 loss: 0.052082]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 600/676] [D loss: -0.007302] [G loss: -0.055293] [d1 loss: 0.054974] [d2 loss: 0.049537]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 414/500] [Batch 620/676] [D loss: -0.007693] [G loss: -0.042461] [d1 loss: 0.091241] [d2 loss: 0.090878]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 640/676] [D loss: 0.003609] [G loss: -0.037142] [d1 loss: 0.057724] [d2 loss: 0.046718]  [sq d1 d2: 0.000121]  [num0: 16.000000] [num1 48.000000]
[Epoch 414/500] [Batch 660/676] [D loss: -0.004616] [G loss: -0.055523] [d1 loss: 0.055591] [d2 loss: 0.050801]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 415/500] [Batch 0/676] [D loss: -0.008432] [G loss: -0.080856] [d1 loss: 0.086805] [d2 loss: 0.084091]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 20/676] [D loss: -0.028327] [G loss: -0.120543] [d1 loss: 0.075711] [d2 loss: 0.069861]  [sq d1 d2: 0.000034]  [num0: 11.000000] [num1 53.000000]
[Epoch 415/500] [Batch 40/676] [D loss: -0.014195] [G loss: -0.167097] [d1 loss: 0.047841] [d2 loss: 0.048404]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 415/500] [Batch 60/676] [D loss: -0.004457] [G loss: -0.151809] [d1 loss: 0.055612] [d2 loss: 0.056754]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 415/500] [Batch 80/676] [D loss: -0.031046] [G loss: -0.149583] [d1 loss: 0.042165] [d2 loss: 0.056801]  [sq d1 d2: 0.000214]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 100/676] [D loss: -0.002713] [G loss: -0.148704] [d1 loss: 0.072463] [d2 loss: 0.066688]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 415/500] [Batch 120/676] [D loss: 0.018866] [G loss: -0.115903] [d1 loss: 0.020341] [d2 loss: 0.019664]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 415/500] [Batch 140/676] [D loss: 0.003330] [G loss: -0.116247] [d1 loss: 0.034890] [d2 loss: 0.034624]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 415/500] [Batch 160/676] [D loss: 0.003709] [G loss: -0.082991] [d1 loss: 0.048189] [d2 loss: 0.042098]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 415/500] [Batch 180/676] [D loss: -0.000130] [G loss: -0.081456] [d1 loss: 0.065056] [d2 loss: 0.065012]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]

[Epoch 415/500] [Batch 200/676] [D loss: -0.008893] [G loss: -0.053339] [d1 loss: 0.086415] [d2 loss: 0.077873]  [sq d1 d2: 0.000073]  [num0: 20.000000] [num1 44.000000]
[Epoch 415/500] [Batch 220/676] [D loss: -0.008660] [G loss: -0.034222] [d1 loss: 0.015462] [d2 loss: 0.018181]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 240/676] [D loss: -0.023555] [G loss: -0.035775] [d1 loss: 0.066402] [d2 loss: 0.059844]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 415/500] [Batch 260/676] [D loss: -0.017529] [G loss: -0.020374] [d1 loss: 0.098927] [d2 loss: 0.097102]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 280/676] [D loss: -0.021296] [G loss: -0.036849] [d1 loss: 0.082413] [d2 loss: 0.071099]  [sq d1 d2: 0.000128]  [num0: 18.000000] [num1 46.000000]
[Epoch 415/500] [Batch 300/676] [D loss: 0.005443] [G loss: -0.025139] [d1 loss: 0.019003] [d2 loss: 0.020755]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 415/500] [Batch 320/676] [D loss: 0.012581] [G loss: -0.041222] [d1 loss: 0.283729] [d2 loss: 0.227927]  [sq d1 d2: 0.003114]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 340/676] [D loss: -0.007652] [G loss: -0.026837] [d1 loss: 0.058883] [d2 loss: 0.058574]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 415/500] [Batch 360/676] [D loss: 0.010978] [G loss: -0.077994] [d1 loss: 0.073881] [d2 loss: 0.071965]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 415/500] [Batch 380/676] [D loss: 0.005595] [G loss: -0.109730] [d1 loss: 0.066608] [d2 loss: 0.064694]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 415/500] [Batch 400/676] [D loss: 0.001852] [G loss: -0.141284] [d1 loss: 0.033205] [d2 loss: 0.028419]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 415/500] [Batch 420/676] [D loss: 0.004247] [G loss: -0.169197] [d1 loss: 0.094039] [d2 loss: 0.087273]  [sq d1 d2: 0.000046]  [num0: 12.000000] [num1 52.000000]
[Epoch 415/500] [Batch 440/676] [D loss: -0.002133] [G loss: -0.147005] [d1 loss: 0.071723] [d2 loss: 0.064590]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 415/500] [Batch 460/676] [D loss: -0.011363] [G loss: -0.155669] [d1 loss: 0.112806] [d2 loss: 0.097034]  [sq d1 d2: 0.000249]  [num0: 17.000000] [num1 47.000000]
[Epoch 415/500] [Batch 480/676] [D loss: -0.020732] [G loss: -0.193289] [d1 loss: 0.072720] [d2 loss: 0.077537]  [sq d1 d2: 0.000023]  [num0: 15.000000] [num1 49.000000]
[Epoch 415/500] [Batch 500/676] [D loss: -0.022308] [G loss: -0.191302] [d1 loss: 0.065927] [d2 loss: 0.049033]  [sq d1 d2: 0.000285]  [num0: 18.000000] [num1 46.000000]
[Epoch 415/500] [Batch 520/676] [D loss: -0.006897] [G loss: -0.178821] [d1 loss: 0.058654] [d2 loss: 0.054808]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 415/500] [Batch 540/676] [D loss: -0.025782] [G loss: -0.183345] [d1 loss: 0.035431] [d2 loss: 0.026400]  [sq d1 d2: 0.000082]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 560/676] [D loss: 0.004734] [G loss: -0.157874] [d1 loss: 0.040279] [d2 loss: 0.039994]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 415/500] [Batch 580/676] [D loss: -0.012379] [G loss: -0.158547] [d1 loss: 0.040510] [d2 loss: 0.035380]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 415/500] [Batch 600/676] [D loss: -0.008827] [G loss: -0.150913] [d1 loss: 0.051184] [d2 loss: 0.068512]  [sq d1 d2: 0.000300]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 620/676] [D loss: -0.014176] [G loss: -0.090339] [d1 loss: 0.084520] [d2 loss: 0.079408]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 415/500] [Batch 640/676] [D loss: 0.005516] [G loss: -0.079592] [d1 loss: 0.022120] [d2 loss: 0.022136]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 415/500] [Batch 660/676] [D loss: 0.008632] [G loss: -0.049234] [d1 loss: 0.060708] [d2 loss: 0.047351]  [sq d1 d2: 0.000178]  [num0: 13.000000] [num1 51.000000]
[Epoch 416/500] [Batch 0/676] [D loss: 0.000057] [G loss: -0.031857] [d1 loss: 0.039160] [d2 loss: 0.034355]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 416/500] [Batch 20/676] [D loss: -0.006150] [G loss: -0.004549] [d1 loss: 0.067171] [d2 loss: 0.070039]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 416/500] [Batch 40/676] [D loss: -0.010355] [G loss: 0.011072] [d1 loss: 0.047312] [d2 loss: 0.056452]  [sq d1 d2: 0.000084]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 60/676] [D loss: -0.008774] [G loss: 0.009836] [d1 loss: 0.036111] [d2 loss: 0.023484]  [sq d1 d2: 0.000159]  [num0: 16.000000] [num1 48.000000]
[Epoch 416/500] [Batch 80/676] [D loss: -0.009480] [G loss: 0.003208] [d1 loss: 0.158593] [d2 loss: 0.138465]  [sq d1 d2: 0.000405]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 100/676] [D loss: -0.015558] [G loss: -0.023811] [d1 loss: 0.030929] [d2 loss: 0.034708]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 416/500] [Batch 120/676] [D loss: -0.023929] [G loss: -0.044330] [d1 loss: 0.027615] [d2 loss: 0.034822]  [sq d1 d2: 0.000052]  [num0: 19.000000] [num1 45.000000]
[Epoch 416/500] [Batch 140/676] [D loss: -0.014921] [G loss: -0.046860] [d1 loss: 0.053690] [d2 loss: 0.057310]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 416/500] [Batch 160/676] [D loss: -0.003358] [G loss: -0.061373] [d1 loss: 0.111176] [d2 loss: 0.115671]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 180/676] [D loss: -0.018478] [G loss: -0.018341] [d1 loss: 0.062026] [d2 loss: 0.056425]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 200/676] [D loss: -0.014068] [G loss: -0.023254] [d1 loss: 0.081876] [d2 loss: 0.069542]  [sq d1 d2: 0.000152]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 220/676] [D loss: -0.007719] [G loss: -0.007420] [d1 loss: 0.013969] [d2 loss: 0.016098]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 240/676] [D loss: -0.004190] [G loss: 0.006162] [d1 loss: 0.117022] [d2 loss: 0.106795]  [sq d1 d2: 0.000105]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 260/676] [D loss: 0.002471] [G loss: 0.004499] [d1 loss: 0.043307] [d2 loss: 0.055631]  [sq d1 d2: 0.000152]  [num0: 12.000000] [num1 52.000000]
[Epoch 416/500] [Batch 280/676] [D loss: 0.004528] [G loss: -0.007430] [d1 loss: 0.151252] [d2 loss: 0.127079]  [sq d1 d2: 0.000584]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 300/676] [D loss: -0.006761] [G loss: -0.040929] [d1 loss: 0.167133] [d2 loss: 0.188053]  [sq d1 d2: 0.000438]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 320/676] [D loss: -0.004169] [G loss: -0.052249] [d1 loss: 0.087473] [d2 loss: 0.121409]  [sq d1 d2: 0.001152]  [num0: 16.000000] [num1 48.000000]
[Epoch 416/500] [Batch 340/676] [D loss: -0.021574] [G loss: -0.074849] [d1 loss: 0.038791] [d2 loss: 0.032612]  [sq d1 d2: 0.000038]  [num0: 10.000000] [num1 54.000000]
[Epoch 416/500] [Batch 360/676] [D loss: -0.025838] [G loss: -0.101660] [d1 loss: 0.213081] [d2 loss: 0.220851]  [sq d1 d2: 0.000060]  [num0: 20.000000] [num1 44.000000]
[Epoch 416/500] [Batch 380/676] [D loss: -0.009018] [G loss: -0.118131] [d1 loss: 0.060178] [d2 loss: 0.050366]  [sq d1 d2: 0.000096]  [num0: 15.000000] [num1 49.000000]
[Epoch 416/500] [Batch 400/676] [D loss: -0.019047] [G loss: -0.134499] [d1 loss: 0.054208] [d2 loss: 0.045662]  [sq d1 d2: 0.000073]  [num0: 14.000000] [num1 50.000000]
[Epoch 416/500] [Batch 420/676] [D loss: 0.003141] [G loss: -0.182568] [d1 loss: 0.008983] [d2 loss: 0.010241]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 416/500] [Batch 440/676] [D loss: 0.011349] [G loss: -0.180040] [d1 loss: 0.022273] [d2 loss: 0.019433]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 416/500] [Batch 460/676] [D loss: 0.013173] [G loss: -0.179916] [d1 loss: 0.112496] [d2 loss: 0.105173]  [sq d1 d2: 0.000054]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 480/676] [D loss: 0.001838] [G loss: -0.130559] [d1 loss: 0.118857] [d2 loss: 0.144205]  [sq d1 d2: 0.000643]  [num0: 15.000000] [num1 49.000000]
[Epoch 416/500] [Batch 500/676] [D loss: 0.002584] [G loss: -0.100355] [d1 loss: 0.051171] [d2 loss: 0.052875]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 416/500] [Batch 520/676] [D loss: -0.002887] [G loss: -0.090398] [d1 loss: 0.093357] [d2 loss: 0.105110]  [sq d1 d2: 0.000138]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 540/676] [D loss: -0.009174] [G loss: -0.084940] [d1 loss: 0.019680] [d2 loss: 0.024429]  [sq d1 d2: 0.000023]  [num0: 19.000000] [num1 45.000000]

[Epoch 416/500] [Batch 560/676] [D loss: -0.018859] [G loss: -0.099643] [d1 loss: 0.087865] [d2 loss: 0.097761]  [sq d1 d2: 0.000098]  [num0: 13.000000] [num1 51.000000]
[Epoch 416/500] [Batch 580/676] [D loss: -0.033791] [G loss: -0.126229] [d1 loss: 0.036100] [d2 loss: 0.041277]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 416/500] [Batch 600/676] [D loss: -0.034289] [G loss: -0.131340] [d1 loss: 0.039887] [d2 loss: 0.036922]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 620/676] [D loss: -0.027007] [G loss: -0.150004] [d1 loss: 0.055251] [d2 loss: 0.057266]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 416/500] [Batch 640/676] [D loss: 0.001087] [G loss: -0.176469] [d1 loss: 0.053772] [d2 loss: 0.041395]  [sq d1 d2: 0.000153]  [num0: 18.000000] [num1 46.000000]
[Epoch 416/500] [Batch 660/676] [D loss: -0.015681] [G loss: -0.187549] [d1 loss: 0.073793] [d2 loss: 0.051391]  [sq d1 d2: 0.000502]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 0/676] [D loss: 0.026153] [G loss: -0.181641] [d1 loss: 0.050088] [d2 loss: 0.041111]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 417/500] [Batch 20/676] [D loss: 0.009235] [G loss: -0.161705] [d1 loss: 0.103334] [d2 loss: 0.137207]  [sq d1 d2: 0.001147]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 40/676] [D loss: 0.010158] [G loss: -0.099687] [d1 loss: 0.082920] [d2 loss: 0.068905]  [sq d1 d2: 0.000196]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 60/676] [D loss: 0.013445] [G loss: -0.094839] [d1 loss: 0.072906] [d2 loss: 0.087393]  [sq d1 d2: 0.000210]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 80/676] [D loss: 0.001129] [G loss: -0.106320] [d1 loss: 0.062019] [d2 loss: 0.062017]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 417/500] [Batch 100/676] [D loss: -0.007628] [G loss: -0.094251] [d1 loss: 0.141543] [d2 loss: 0.159333]  [sq d1 d2: 0.000316]  [num0: 17.000000] [num1 47.000000]
[Epoch 417/500] [Batch 120/676] [D loss: -0.009220] [G loss: -0.079820] [d1 loss: 0.075756] [d2 loss: 0.072609]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 417/500] [Batch 140/676] [D loss: -0.029111] [G loss: -0.071064] [d1 loss: 0.060572] [d2 loss: 0.050548]  [sq d1 d2: 0.000100]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 160/676] [D loss: -0.017163] [G loss: -0.086905] [d1 loss: 0.037649] [d2 loss: 0.054353]  [sq d1 d2: 0.000279]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 180/676] [D loss: -0.014014] [G loss: -0.104988] [d1 loss: 0.056909] [d2 loss: 0.051183]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 200/676] [D loss: 0.004333] [G loss: -0.121681] [d1 loss: 0.052621] [d2 loss: 0.064938]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 220/676] [D loss: -0.025449] [G loss: -0.160815] [d1 loss: 0.149846] [d2 loss: 0.141931]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 240/676] [D loss: -0.040617] [G loss: -0.146836] [d1 loss: 0.102395] [d2 loss: 0.103108]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 417/500] [Batch 260/676] [D loss: 0.007136] [G loss: -0.127584] [d1 loss: 0.030244] [d2 loss: 0.037729]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 280/676] [D loss: 0.002119] [G loss: -0.114317] [d1 loss: 0.082465] [d2 loss: 0.081926]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 417/500] [Batch 300/676] [D loss: 0.001078] [G loss: -0.080394] [d1 loss: 0.040206] [d2 loss: 0.044934]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 417/500] [Batch 320/676] [D loss: -0.000432] [G loss: -0.053314] [d1 loss: 0.114222] [d2 loss: 0.145312]  [sq d1 d2: 0.000967]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 340/676] [D loss: -0.002549] [G loss: -0.031955] [d1 loss: 0.079823] [d2 loss: 0.074778]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 417/500] [Batch 360/676] [D loss: -0.010479] [G loss: -0.036278] [d1 loss: 0.110672] [d2 loss: 0.051416]  [sq d1 d2: 0.003511]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 380/676] [D loss: -0.023018] [G loss: 0.013871] [d1 loss: 0.083778] [d2 loss: 0.090207]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 400/676] [D loss: -0.023348] [G loss: 0.002648] [d1 loss: 0.032870] [d2 loss: 0.052309]  [sq d1 d2: 0.000378]  [num0: 18.000000] [num1 46.000000]
[Epoch 417/500] [Batch 420/676] [D loss: -0.014147] [G loss: 0.020743] [d1 loss: 0.092181] [d2 loss: 0.075994]  [sq d1 d2: 0.000262]  [num0: 18.000000] [num1 46.000000]
[Epoch 417/500] [Batch 440/676] [D loss: -0.030627] [G loss: 0.038733] [d1 loss: 0.053540] [d2 loss: 0.037666]  [sq d1 d2: 0.000252]  [num0: 17.000000] [num1 47.000000]
[Epoch 417/500] [Batch 460/676] [D loss: 0.002682] [G loss: 0.030533] [d1 loss: 0.037439] [d2 loss: 0.030849]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 417/500] [Batch 480/676] [D loss: -0.013047] [G loss: 0.032178] [d1 loss: 0.047914] [d2 loss: 0.029855]  [sq d1 d2: 0.000326]  [num0: 12.000000] [num1 52.000000]
[Epoch 417/500] [Batch 500/676] [D loss: 0.016192] [G loss: 0.066579] [d1 loss: 0.087627] [d2 loss: 0.089634]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 520/676] [D loss: 0.012573] [G loss: 0.061189] [d1 loss: 0.037549] [d2 loss: 0.040287]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 417/500] [Batch 540/676] [D loss: 0.001545] [G loss: 0.038727] [d1 loss: 0.039595] [d2 loss: 0.057518]  [sq d1 d2: 0.000321]  [num0: 12.000000] [num1 52.000000]
[Epoch 417/500] [Batch 560/676] [D loss: 0.001218] [G loss: 0.028752] [d1 loss: 0.030953] [d2 loss: 0.028848]  [sq d1 d2: 0.000004]  [num0: 13.000000] [num1 51.000000]
[Epoch 417/500] [Batch 580/676] [D loss: -0.005338] [G loss: 0.024301] [d1 loss: 0.151540] [d2 loss: 0.161134]  [sq d1 d2: 0.000092]  [num0: 18.000000] [num1 46.000000]
[Epoch 417/500] [Batch 600/676] [D loss: -0.000885] [G loss: 0.036289] [d1 loss: 0.020153] [d2 loss: 0.018966]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 620/676] [D loss: -0.006683] [G loss: 0.062397] [d1 loss: 0.118379] [d2 loss: 0.116853]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 417/500] [Batch 640/676] [D loss: -0.027275] [G loss: 0.099076] [d1 loss: 0.047647] [d2 loss: 0.045361]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 417/500] [Batch 660/676] [D loss: -0.025840] [G loss: 0.072090] [d1 loss: 0.042331] [d2 loss: 0.050414]  [sq d1 d2: 0.000065]  [num0: 14.000000] [num1 50.000000]
[Epoch 418/500] [Batch 0/676] [D loss: -0.024509] [G loss: 0.075205] [d1 loss: 0.052611] [d2 loss: 0.061225]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 418/500] [Batch 20/676] [D loss: -0.013076] [G loss: 0.059674] [d1 loss: 0.039134] [d2 loss: 0.039244]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 418/500] [Batch 40/676] [D loss: -0.017654] [G loss: 0.005538] [d1 loss: 0.068689] [d2 loss: 0.049713]  [sq d1 d2: 0.000360]  [num0: 18.000000] [num1 46.000000]
[Epoch 418/500] [Batch 60/676] [D loss: 0.004046] [G loss: -0.052674] [d1 loss: 0.027082] [d2 loss: 0.027475]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 80/676] [D loss: 0.025821] [G loss: -0.139446] [d1 loss: 0.040735] [d2 loss: 0.030524]  [sq d1 d2: 0.000104]  [num0: 14.000000] [num1 50.000000]
[Epoch 418/500] [Batch 100/676] [D loss: 0.012786] [G loss: -0.130431] [d1 loss: 0.082789] [d2 loss: 0.096743]  [sq d1 d2: 0.000195]  [num0: 20.000000] [num1 44.000000]
[Epoch 418/500] [Batch 120/676] [D loss: 0.002793] [G loss: -0.139961] [d1 loss: 0.059285] [d2 loss: 0.063135]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 140/676] [D loss: -0.001700] [G loss: -0.118410] [d1 loss: 0.033348] [d2 loss: 0.033196]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 418/500] [Batch 160/676] [D loss: -0.011177] [G loss: -0.094050] [d1 loss: 0.137686] [d2 loss: 0.137360]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 418/500] [Batch 180/676] [D loss: -0.014614] [G loss: -0.098233] [d1 loss: 0.030624] [d2 loss: 0.031862]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 200/676] [D loss: -0.016613] [G loss: -0.118837] [d1 loss: 0.075487] [d2 loss: 0.062016]  [sq d1 d2: 0.000181]  [num0: 14.000000] [num1 50.000000]
[Epoch 418/500] [Batch 220/676] [D loss: -0.032241] [G loss: -0.131102] [d1 loss: 0.056909] [d2 loss: 0.063731]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]

[Epoch 418/500] [Batch 240/676] [D loss: -0.011990] [G loss: -0.113244] [d1 loss: 0.114003] [d2 loss: 0.104671]  [sq d1 d2: 0.000087]  [num0: 19.000000] [num1 45.000000]
[Epoch 418/500] [Batch 260/676] [D loss: -0.015989] [G loss: -0.109236] [d1 loss: 0.034070] [d2 loss: 0.036051]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 280/676] [D loss: -0.035066] [G loss: -0.133392] [d1 loss: 0.046189] [d2 loss: 0.065438]  [sq d1 d2: 0.000371]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 300/676] [D loss: -0.029289] [G loss: -0.129848] [d1 loss: 0.042147] [d2 loss: 0.037461]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 320/676] [D loss: -0.020560] [G loss: -0.128382] [d1 loss: 0.030872] [d2 loss: 0.038366]  [sq d1 d2: 0.000056]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 340/676] [D loss: 0.013415] [G loss: -0.077417] [d1 loss: 0.036532] [d2 loss: 0.037659]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 360/676] [D loss: 0.004165] [G loss: -0.074448] [d1 loss: 0.098958] [d2 loss: 0.084938]  [sq d1 d2: 0.000197]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 380/676] [D loss: 0.003386] [G loss: -0.049680] [d1 loss: 0.034392] [d2 loss: 0.043853]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 400/676] [D loss: 0.009838] [G loss: -0.031116] [d1 loss: 0.059295] [d2 loss: 0.059948]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 418/500] [Batch 420/676] [D loss: -0.014009] [G loss: -0.021633] [d1 loss: 0.148007] [d2 loss: 0.082752]  [sq d1 d2: 0.004258]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 440/676] [D loss: -0.017587] [G loss: -0.011943] [d1 loss: 0.064024] [d2 loss: 0.064544]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 460/676] [D loss: -0.034849] [G loss: -0.000131] [d1 loss: 0.063447] [d2 loss: 0.058892]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 480/676] [D loss: -0.025904] [G loss: 0.003820] [d1 loss: 0.081256] [d2 loss: 0.079318]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 500/676] [D loss: 0.006604] [G loss: 0.010311] [d1 loss: 0.093252] [d2 loss: 0.095312]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 520/676] [D loss: -0.008310] [G loss: -0.011513] [d1 loss: 0.059599] [d2 loss: 0.056858]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 418/500] [Batch 540/676] [D loss: -0.010735] [G loss: -0.022466] [d1 loss: 0.064019] [d2 loss: 0.074003]  [sq d1 d2: 0.000100]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 560/676] [D loss: -0.019796] [G loss: -0.031186] [d1 loss: 0.022308] [d2 loss: 0.023723]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 580/676] [D loss: 0.006664] [G loss: -0.087922] [d1 loss: 0.059680] [d2 loss: 0.069394]  [sq d1 d2: 0.000094]  [num0: 13.000000] [num1 51.000000]
[Epoch 418/500] [Batch 600/676] [D loss: 0.008302] [G loss: -0.082078] [d1 loss: 0.060673] [d2 loss: 0.056868]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 620/676] [D loss: 0.013482] [G loss: -0.089419] [d1 loss: 0.010790] [d2 loss: 0.008941]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 418/500] [Batch 640/676] [D loss: -0.004986] [G loss: -0.079704] [d1 loss: 0.085017] [d2 loss: 0.092747]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 418/500] [Batch 660/676] [D loss: -0.013009] [G loss: -0.074850] [d1 loss: 0.073949] [d2 loss: 0.090174]  [sq d1 d2: 0.000263]  [num0: 14.000000] [num1 50.000000]
[Epoch 419/500] [Batch 0/676] [D loss: -0.011886] [G loss: -0.072745] [d1 loss: 0.061884] [d2 loss: 0.078910]  [sq d1 d2: 0.000290]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 20/676] [D loss: -0.027506] [G loss: -0.040294] [d1 loss: 0.105386] [d2 loss: 0.130740]  [sq d1 d2: 0.000643]  [num0: 18.000000] [num1 46.000000]
[Epoch 419/500] [Batch 40/676] [D loss: -0.034458] [G loss: -0.025443] [d1 loss: 0.079959] [d2 loss: 0.067040]  [sq d1 d2: 0.000167]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 60/676] [D loss: -0.025350] [G loss: -0.002748] [d1 loss: 0.058883] [d2 loss: 0.039547]  [sq d1 d2: 0.000374]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 80/676] [D loss: -0.033990] [G loss: -0.041756] [d1 loss: 0.095748] [d2 loss: 0.086306]  [sq d1 d2: 0.000089]  [num0: 20.000000] [num1 44.000000]
[Epoch 419/500] [Batch 100/676] [D loss: -0.010487] [G loss: -0.057948] [d1 loss: 0.108466] [d2 loss: 0.092171]  [sq d1 d2: 0.000266]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 120/676] [D loss: 0.020281] [G loss: -0.047865] [d1 loss: 0.070513] [d2 loss: 0.062767]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 140/676] [D loss: 0.017145] [G loss: -0.046030] [d1 loss: 0.073586] [d2 loss: 0.118527]  [sq d1 d2: 0.002020]  [num0: 20.000000] [num1 44.000000]
[Epoch 419/500] [Batch 160/676] [D loss: 0.020297] [G loss: -0.054956] [d1 loss: 0.103300] [d2 loss: 0.093349]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 180/676] [D loss: 0.000911] [G loss: -0.054601] [d1 loss: 0.065014] [d2 loss: 0.058760]  [sq d1 d2: 0.000039]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 200/676] [D loss: -0.001635] [G loss: -0.037943] [d1 loss: 0.057193] [d2 loss: 0.056515]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 220/676] [D loss: -0.002035] [G loss: -0.011305] [d1 loss: 0.077412] [d2 loss: 0.096571]  [sq d1 d2: 0.000367]  [num0: 13.000000] [num1 51.000000]
[Epoch 419/500] [Batch 240/676] [D loss: -0.006501] [G loss: -0.010140] [d1 loss: 0.081761] [d2 loss: 0.065073]  [sq d1 d2: 0.000278]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 260/676] [D loss: -0.007211] [G loss: -0.002729] [d1 loss: 0.050066] [d2 loss: 0.045022]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 280/676] [D loss: -0.014968] [G loss: 0.000877] [d1 loss: 0.069417] [d2 loss: 0.064440]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 300/676] [D loss: -0.029689] [G loss: 0.019181] [d1 loss: 0.074633] [d2 loss: 0.089709]  [sq d1 d2: 0.000227]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 320/676] [D loss: -0.013446] [G loss: 0.024752] [d1 loss: 0.052026] [d2 loss: 0.056691]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 340/676] [D loss: -0.010238] [G loss: 0.039462] [d1 loss: 0.037617] [d2 loss: 0.048785]  [sq d1 d2: 0.000125]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 360/676] [D loss: -0.001146] [G loss: 0.020973] [d1 loss: 0.081629] [d2 loss: 0.075541]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 380/676] [D loss: -0.000994] [G loss: -0.008351] [d1 loss: 0.083210] [d2 loss: 0.070157]  [sq d1 d2: 0.000170]  [num0: 12.000000] [num1 52.000000]
[Epoch 419/500] [Batch 400/676] [D loss: 0.000593] [G loss: -0.041980] [d1 loss: 0.024243] [d2 loss: 0.021860]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 420/676] [D loss: 0.001364] [G loss: -0.061857] [d1 loss: 0.083330] [d2 loss: 0.089076]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 440/676] [D loss: -0.002484] [G loss: -0.067978] [d1 loss: 0.094140] [d2 loss: 0.081160]  [sq d1 d2: 0.000168]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 460/676] [D loss: -0.007462] [G loss: -0.089175] [d1 loss: 0.086486] [d2 loss: 0.093821]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 419/500] [Batch 480/676] [D loss: -0.007407] [G loss: -0.117844] [d1 loss: 0.022122] [d2 loss: 0.020786]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 419/500] [Batch 500/676] [D loss: -0.017283] [G loss: -0.115565] [d1 loss: 0.074763] [d2 loss: 0.053264]  [sq d1 d2: 0.000462]  [num0: 13.000000] [num1 51.000000]
[Epoch 419/500] [Batch 520/676] [D loss: -0.031047] [G loss: -0.152475] [d1 loss: 0.040040] [d2 loss: 0.039371]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 419/500] [Batch 540/676] [D loss: -0.049359] [G loss: -0.185630] [d1 loss: 0.031241] [d2 loss: 0.032805]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 419/500] [Batch 560/676] [D loss: -0.004283] [G loss: -0.196623] [d1 loss: 0.029097] [d2 loss: 0.027579]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 419/500] [Batch 580/676] [D loss: -0.032070] [G loss: -0.250076] [d1 loss: 0.066364] [d2 loss: 0.071872]  [sq d1 d2: 0.000030]  [num0: 18.000000] [num1 46.000000]

[Epoch 419/500] [Batch 600/676] [D loss: -0.006749] [G loss: -0.253061] [d1 loss: 0.053923] [d2 loss: 0.055586]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 419/500] [Batch 620/676] [D loss: 0.019590] [G loss: -0.191322] [d1 loss: 0.050814] [d2 loss: 0.052741]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 419/500] [Batch 640/676] [D loss: 0.002496] [G loss: -0.164522] [d1 loss: 0.048427] [d2 loss: 0.044969]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 419/500] [Batch 660/676] [D loss: -0.003438] [G loss: -0.137245] [d1 loss: 0.080806] [d2 loss: 0.066408]  [sq d1 d2: 0.000207]  [num0: 11.000000] [num1 53.000000]
[Epoch 420/500] [Batch 0/676] [D loss: 0.002623] [G loss: -0.107298] [d1 loss: 0.047767] [d2 loss: 0.050511]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 420/500] [Batch 20/676] [D loss: -0.003355] [G loss: -0.075667] [d1 loss: 0.084235] [d2 loss: 0.063883]  [sq d1 d2: 0.000414]  [num0: 17.000000] [num1 47.000000]
[Epoch 420/500] [Batch 40/676] [D loss: -0.005840] [G loss: -0.020435] [d1 loss: 0.143557] [d2 loss: 0.135142]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 420/500] [Batch 60/676] [D loss: -0.031710] [G loss: -0.023713] [d1 loss: 0.060290] [d2 loss: 0.067301]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 420/500] [Batch 80/676] [D loss: -0.036565] [G loss: -0.012628] [d1 loss: 0.094565] [d2 loss: 0.094801]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 100/676] [D loss: -0.004517] [G loss: 0.003934] [d1 loss: 0.058329] [d2 loss: 0.067133]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 120/676] [D loss: -0.028558] [G loss: 0.001043] [d1 loss: 0.043703] [d2 loss: 0.040091]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 420/500] [Batch 140/676] [D loss: 0.012457] [G loss: 0.071997] [d1 loss: 0.061285] [d2 loss: 0.056959]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 420/500] [Batch 160/676] [D loss: 0.020714] [G loss: 0.135323] [d1 loss: 0.081172] [d2 loss: 0.074037]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 420/500] [Batch 180/676] [D loss: 0.010037] [G loss: 0.143436] [d1 loss: 0.073057] [d2 loss: 0.070396]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 420/500] [Batch 200/676] [D loss: 0.020838] [G loss: 0.098915] [d1 loss: 0.091623] [d2 loss: 0.109054]  [sq d1 d2: 0.000304]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 220/676] [D loss: 0.004533] [G loss: 0.051152] [d1 loss: 0.050683] [d2 loss: 0.064074]  [sq d1 d2: 0.000179]  [num0: 19.000000] [num1 45.000000]
[Epoch 420/500] [Batch 240/676] [D loss: -0.014844] [G loss: 0.012420] [d1 loss: 0.067885] [d2 loss: 0.077768]  [sq d1 d2: 0.000098]  [num0: 15.000000] [num1 49.000000]
[Epoch 420/500] [Batch 260/676] [D loss: -0.031295] [G loss: -0.008990] [d1 loss: 0.056747] [d2 loss: 0.048637]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 280/676] [D loss: -0.017072] [G loss: -0.052827] [d1 loss: 0.026332] [d2 loss: 0.021613]  [sq d1 d2: 0.000022]  [num0: 19.000000] [num1 45.000000]
[Epoch 420/500] [Batch 300/676] [D loss: -0.024958] [G loss: -0.098627] [d1 loss: 0.047245] [d2 loss: 0.045449]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 320/676] [D loss: -0.024644] [G loss: -0.154278] [d1 loss: 0.024207] [d2 loss: 0.031162]  [sq d1 d2: 0.000048]  [num0: 12.000000] [num1 52.000000]
[Epoch 420/500] [Batch 340/676] [D loss: -0.026129] [G loss: -0.169095] [d1 loss: 0.030229] [d2 loss: 0.024713]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 420/500] [Batch 360/676] [D loss: -0.036503] [G loss: -0.251477] [d1 loss: 0.117304] [d2 loss: 0.106074]  [sq d1 d2: 0.000126]  [num0: 17.000000] [num1 47.000000]
[Epoch 420/500] [Batch 380/676] [D loss: 0.035363] [G loss: -0.242522] [d1 loss: 0.059322] [d2 loss: 0.054085]  [sq d1 d2: 0.000027]  [num0: 13.000000] [num1 51.000000]
[Epoch 420/500] [Batch 400/676] [D loss: 0.037717] [G loss: -0.264102] [d1 loss: 0.020439] [d2 loss: 0.015411]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 420/676] [D loss: 0.002646] [G loss: -0.177642] [d1 loss: 0.120954] [d2 loss: 0.105357]  [sq d1 d2: 0.000243]  [num0: 17.000000] [num1 47.000000]
[Epoch 420/500] [Batch 440/676] [D loss: 0.006026] [G loss: -0.113669] [d1 loss: 0.121286] [d2 loss: 0.131807]  [sq d1 d2: 0.000111]  [num0: 12.000000] [num1 52.000000]
[Epoch 420/500] [Batch 460/676] [D loss: -0.001613] [G loss: -0.064951] [d1 loss: 0.087966] [d2 loss: 0.087331]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 420/500] [Batch 480/676] [D loss: -0.010198] [G loss: -0.034227] [d1 loss: 0.063708] [d2 loss: 0.067062]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 420/500] [Batch 500/676] [D loss: -0.009017] [G loss: -0.001199] [d1 loss: 0.061005] [d2 loss: 0.052508]  [sq d1 d2: 0.000072]  [num0: 14.000000] [num1 50.000000]
[Epoch 420/500] [Batch 520/676] [D loss: -0.032432] [G loss: 0.086630] [d1 loss: 0.050221] [d2 loss: 0.056080]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 420/500] [Batch 540/676] [D loss: -0.031237] [G loss: 0.112281] [d1 loss: 0.017135] [d2 loss: 0.014870]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 420/500] [Batch 560/676] [D loss: -0.012116] [G loss: 0.075652] [d1 loss: 0.065446] [d2 loss: 0.067714]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 420/500] [Batch 580/676] [D loss: -0.060770] [G loss: 0.083941] [d1 loss: 0.035027] [d2 loss: 0.035588]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 420/500] [Batch 600/676] [D loss: -0.014958] [G loss: 0.104040] [d1 loss: 0.092465] [d2 loss: 0.092066]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 420/500] [Batch 620/676] [D loss: 0.036327] [G loss: 0.074791] [d1 loss: 0.133988] [d2 loss: 0.083812]  [sq d1 d2: 0.002518]  [num0: 18.000000] [num1 46.000000]
[Epoch 420/500] [Batch 640/676] [D loss: -0.014970] [G loss: 0.015485] [d1 loss: 0.057236] [d2 loss: 0.056879]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 420/500] [Batch 660/676] [D loss: 0.008686] [G loss: -0.022743] [d1 loss: 0.058941] [d2 loss: 0.061744]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 421/500] [Batch 0/676] [D loss: 0.007600] [G loss: -0.037500] [d1 loss: 0.043394] [d2 loss: 0.040509]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 20/676] [D loss: 0.000214] [G loss: -0.051792] [d1 loss: 0.054743] [d2 loss: 0.050473]  [sq d1 d2: 0.000018]  [num0: 13.000000] [num1 51.000000]
[Epoch 421/500] [Batch 40/676] [D loss: -0.005053] [G loss: -0.051608] [d1 loss: 0.096589] [d2 loss: 0.102089]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 421/500] [Batch 60/676] [D loss: -0.015902] [G loss: -0.034293] [d1 loss: 0.078713] [d2 loss: 0.074789]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 80/676] [D loss: -0.024909] [G loss: -0.039637] [d1 loss: 0.054351] [d2 loss: 0.043859]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 100/676] [D loss: -0.050914] [G loss: -0.079858] [d1 loss: 0.040206] [d2 loss: 0.029185]  [sq d1 d2: 0.000121]  [num0: 13.000000] [num1 51.000000]
[Epoch 421/500] [Batch 120/676] [D loss: -0.042658] [G loss: -0.073994] [d1 loss: 0.034712] [d2 loss: 0.035201]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 140/676] [D loss: -0.001537] [G loss: -0.167784] [d1 loss: 0.062993] [d2 loss: 0.060726]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 160/676] [D loss: -0.039945] [G loss: -0.209073] [d1 loss: 0.051071] [d2 loss: 0.055781]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 421/500] [Batch 180/676] [D loss: 0.008872] [G loss: -0.208345] [d1 loss: 0.035198] [d2 loss: 0.044526]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 421/500] [Batch 200/676] [D loss: 0.019758] [G loss: -0.225040] [d1 loss: 0.051262] [d2 loss: 0.051030]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 421/500] [Batch 220/676] [D loss: 0.000755] [G loss: -0.170792] [d1 loss: 0.067968] [d2 loss: 0.067476]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 240/676] [D loss: 0.007399] [G loss: -0.127455] [d1 loss: 0.080877] [d2 loss: 0.084232]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 421/500] [Batch 260/676] [D loss: -0.001210] [G loss: -0.095729] [d1 loss: 0.024665] [d2 loss: 0.019544]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]

[Epoch 421/500] [Batch 280/676] [D loss: -0.009998] [G loss: -0.070258] [d1 loss: 0.107549] [d2 loss: 0.115019]  [sq d1 d2: 0.000056]  [num0: 17.000000] [num1 47.000000]
[Epoch 421/500] [Batch 300/676] [D loss: -0.025714] [G loss: -0.018812] [d1 loss: 0.060948] [d2 loss: 0.048916]  [sq d1 d2: 0.000145]  [num0: 17.000000] [num1 47.000000]
[Epoch 421/500] [Batch 320/676] [D loss: -0.037615] [G loss: 0.033242] [d1 loss: 0.048687] [d2 loss: 0.039029]  [sq d1 d2: 0.000093]  [num0: 12.000000] [num1 52.000000]
[Epoch 421/500] [Batch 340/676] [D loss: -0.044420] [G loss: 0.114400] [d1 loss: 0.087369] [d2 loss: 0.105319]  [sq d1 d2: 0.000322]  [num0: 18.000000] [num1 46.000000]
[Epoch 421/500] [Batch 360/676] [D loss: -0.046801] [G loss: 0.128193] [d1 loss: 0.029829] [d2 loss: 0.030351]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 421/500] [Batch 380/676] [D loss: -0.042064] [G loss: 0.112271] [d1 loss: 0.169372] [d2 loss: 0.150396]  [sq d1 d2: 0.000360]  [num0: 13.000000] [num1 51.000000]
[Epoch 421/500] [Batch 400/676] [D loss: -0.033129] [G loss: 0.101345] [d1 loss: 0.115622] [d2 loss: 0.107549]  [sq d1 d2: 0.000065]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 420/676] [D loss: -0.007159] [G loss: 0.176720] [d1 loss: 0.144024] [d2 loss: 0.197781]  [sq d1 d2: 0.002890]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 440/676] [D loss: 0.021456] [G loss: 0.129606] [d1 loss: 0.013657] [d2 loss: 0.013400]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 460/676] [D loss: 0.028444] [G loss: 0.091995] [d1 loss: 0.106152] [d2 loss: 0.106468]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 421/500] [Batch 480/676] [D loss: 0.017272] [G loss: 0.046514] [d1 loss: 0.026025] [d2 loss: 0.030098]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 421/500] [Batch 500/676] [D loss: -0.006196] [G loss: 0.001057] [d1 loss: 0.054194] [d2 loss: 0.070007]  [sq d1 d2: 0.000250]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 520/676] [D loss: -0.013068] [G loss: 0.003114] [d1 loss: 0.045918] [d2 loss: 0.057519]  [sq d1 d2: 0.000135]  [num0: 12.000000] [num1 52.000000]
[Epoch 421/500] [Batch 540/676] [D loss: -0.031279] [G loss: -0.008600] [d1 loss: 0.055538] [d2 loss: 0.062559]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 560/676] [D loss: -0.058196] [G loss: 0.021811] [d1 loss: 0.087274] [d2 loss: 0.082203]  [sq d1 d2: 0.000026]  [num0: 21.000000] [num1 43.000000]
[Epoch 421/500] [Batch 580/676] [D loss: -0.050881] [G loss: 0.025497] [d1 loss: 0.054320] [d2 loss: 0.051320]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 421/500] [Batch 600/676] [D loss: -0.032539] [G loss: 0.043399] [d1 loss: 0.054359] [d2 loss: 0.058301]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 620/676] [D loss: 0.028572] [G loss: 0.020416] [d1 loss: 0.070868] [d2 loss: 0.088238]  [sq d1 d2: 0.000302]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 640/676] [D loss: -0.000701] [G loss: -0.000403] [d1 loss: 0.043193] [d2 loss: 0.049273]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 421/500] [Batch 660/676] [D loss: 0.001040] [G loss: -0.038688] [d1 loss: 0.072238] [d2 loss: 0.071329]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 0/676] [D loss: 0.029962] [G loss: -0.058654] [d1 loss: 0.095645] [d2 loss: 0.091659]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 20/676] [D loss: 0.008723] [G loss: -0.030324] [d1 loss: 0.067918] [d2 loss: 0.085237]  [sq d1 d2: 0.000300]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 40/676] [D loss: 0.000479] [G loss: -0.008021] [d1 loss: 0.053515] [d2 loss: 0.055431]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 422/500] [Batch 60/676] [D loss: -0.005240] [G loss: 0.007255] [d1 loss: 0.059877] [d2 loss: 0.064499]  [sq d1 d2: 0.000021]  [num0: 19.000000] [num1 45.000000]
[Epoch 422/500] [Batch 80/676] [D loss: -0.029507] [G loss: 0.037038] [d1 loss: 0.127332] [d2 loss: 0.126517]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 100/676] [D loss: -0.044522] [G loss: 0.056629] [d1 loss: 0.077585] [d2 loss: 0.092167]  [sq d1 d2: 0.000213]  [num0: 10.000000] [num1 54.000000]
[Epoch 422/500] [Batch 120/676] [D loss: -0.053512] [G loss: 0.109117] [d1 loss: 0.200639] [d2 loss: 0.207982]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 422/500] [Batch 140/676] [D loss: -0.051355] [G loss: 0.047284] [d1 loss: 0.116745] [d2 loss: 0.096670]  [sq d1 d2: 0.000403]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 160/676] [D loss: -0.074495] [G loss: 0.008949] [d1 loss: 0.089137] [d2 loss: 0.089314]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 422/500] [Batch 180/676] [D loss: -0.007910] [G loss: -0.028538] [d1 loss: 0.060739] [d2 loss: 0.049423]  [sq d1 d2: 0.000128]  [num0: 12.000000] [num1 52.000000]
[Epoch 422/500] [Batch 200/676] [D loss: 0.028031] [G loss: -0.072037] [d1 loss: 0.082612] [d2 loss: 0.092635]  [sq d1 d2: 0.000100]  [num0: 18.000000] [num1 46.000000]
[Epoch 422/500] [Batch 220/676] [D loss: 0.018927] [G loss: -0.088097] [d1 loss: 0.064205] [d2 loss: 0.068176]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 422/500] [Batch 240/676] [D loss: -0.000264] [G loss: -0.092062] [d1 loss: 0.076903] [d2 loss: 0.080905]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 422/500] [Batch 260/676] [D loss: 0.011229] [G loss: -0.104532] [d1 loss: 0.079741] [d2 loss: 0.088800]  [sq d1 d2: 0.000082]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 280/676] [D loss: 0.005302] [G loss: -0.065402] [d1 loss: 0.057414] [d2 loss: 0.063420]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 300/676] [D loss: -0.012347] [G loss: -0.027341] [d1 loss: 0.073424] [d2 loss: 0.084879]  [sq d1 d2: 0.000131]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 320/676] [D loss: -0.015525] [G loss: -0.020361] [d1 loss: 0.089533] [d2 loss: 0.099571]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 340/676] [D loss: -0.052803] [G loss: 0.052553] [d1 loss: 0.098016] [d2 loss: 0.128270]  [sq d1 d2: 0.000915]  [num0: 19.000000] [num1 45.000000]
[Epoch 422/500] [Batch 360/676] [D loss: -0.051238] [G loss: 0.121898] [d1 loss: 0.048194] [d2 loss: 0.046368]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 422/500] [Batch 380/676] [D loss: -0.042342] [G loss: 0.150562] [d1 loss: 0.046217] [d2 loss: 0.049211]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 422/500] [Batch 400/676] [D loss: -0.067056] [G loss: 0.134118] [d1 loss: 0.110584] [d2 loss: 0.089938]  [sq d1 d2: 0.000426]  [num0: 19.000000] [num1 45.000000]
[Epoch 422/500] [Batch 420/676] [D loss: -0.035343] [G loss: 0.122197] [d1 loss: 0.036755] [d2 loss: 0.042923]  [sq d1 d2: 0.000038]  [num0: 17.000000] [num1 47.000000]
[Epoch 422/500] [Batch 440/676] [D loss: -0.014587] [G loss: 0.075389] [d1 loss: 0.073640] [d2 loss: 0.069244]  [sq d1 d2: 0.000019]  [num0: 12.000000] [num1 52.000000]
[Epoch 422/500] [Batch 460/676] [D loss: 0.014812] [G loss: 0.002124] [d1 loss: 0.035062] [d2 loss: 0.042716]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 422/500] [Batch 480/676] [D loss: 0.000959] [G loss: -0.045893] [d1 loss: 0.080192] [d2 loss: 0.084946]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 500/676] [D loss: 0.006137] [G loss: -0.079604] [d1 loss: 0.048042] [d2 loss: 0.046287]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 520/676] [D loss: 0.010601] [G loss: -0.078872] [d1 loss: 0.125442] [d2 loss: 0.117178]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 422/500] [Batch 540/676] [D loss: 0.001615] [G loss: -0.083560] [d1 loss: 0.073258] [d2 loss: 0.082025]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 560/676] [D loss: -0.008226] [G loss: -0.091976] [d1 loss: 0.185450] [d2 loss: 0.122819]  [sq d1 d2: 0.003923]  [num0: 15.000000] [num1 49.000000]

[Epoch 422/500] [Batch 580/676] [D loss: -0.028894] [G loss: -0.089096] [d1 loss: 0.089553] [d2 loss: 0.103094]  [sq d1 d2: 0.000183]  [num0: 14.000000] [num1 50.000000]
[Epoch 422/500] [Batch 600/676] [D loss: -0.048504] [G loss: -0.107043] [d1 loss: 0.116291] [d2 loss: 0.130054]  [sq d1 d2: 0.000189]  [num0: 19.000000] [num1 45.000000]
[Epoch 422/500] [Batch 620/676] [D loss: -0.065730] [G loss: -0.079751] [d1 loss: 0.105060] [d2 loss: 0.097927]  [sq d1 d2: 0.000051]  [num0: 18.000000] [num1 46.000000]
[Epoch 422/500] [Batch 640/676] [D loss: -0.067636] [G loss: 0.009030] [d1 loss: 0.077199] [d2 loss: 0.081248]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 422/500] [Batch 660/676] [D loss: -0.040865] [G loss: 0.019775] [d1 loss: 0.128718] [d2 loss: 0.129634]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 423/500] [Batch 0/676] [D loss: -0.068376] [G loss: -0.006599] [d1 loss: 0.073329] [d2 loss: 0.079854]  [sq d1 d2: 0.000043]  [num0: 14.000000] [num1 50.000000]
[Epoch 423/500] [Batch 20/676] [D loss: 0.039950] [G loss: -0.046712] [d1 loss: 0.076748] [d2 loss: 0.057755]  [sq d1 d2: 0.000361]  [num0: 11.000000] [num1 53.000000]
[Epoch 423/500] [Batch 40/676] [D loss: 0.022589] [G loss: -0.104159] [d1 loss: 0.183880] [d2 loss: 0.162430]  [sq d1 d2: 0.000460]  [num0: 17.000000] [num1 47.000000]
[Epoch 423/500] [Batch 60/676] [D loss: -0.001421] [G loss: -0.088470] [d1 loss: 0.117040] [d2 loss: 0.121286]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 80/676] [D loss: 0.011008] [G loss: -0.068426] [d1 loss: 0.023457] [d2 loss: 0.022180]  [sq d1 d2: 0.000002]  [num0: 21.000000] [num1 43.000000]
[Epoch 423/500] [Batch 100/676] [D loss: -0.002161] [G loss: -0.076225] [d1 loss: 0.076773] [d2 loss: 0.077384]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 423/500] [Batch 120/676] [D loss: -0.018430] [G loss: -0.025619] [d1 loss: 0.083990] [d2 loss: 0.116547]  [sq d1 d2: 0.001060]  [num0: 16.000000] [num1 48.000000]
[Epoch 423/500] [Batch 140/676] [D loss: -0.056538] [G loss: -0.046783] [d1 loss: 0.033048] [d2 loss: 0.031320]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 423/500] [Batch 160/676] [D loss: -0.063557] [G loss: 0.027891] [d1 loss: 0.031608] [d2 loss: 0.031103]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 180/676] [D loss: -0.115702] [G loss: 0.057420] [d1 loss: 0.115353] [d2 loss: 0.130129]  [sq d1 d2: 0.000218]  [num0: 20.000000] [num1 44.000000]
[Epoch 423/500] [Batch 200/676] [D loss: -0.101170] [G loss: 0.069315] [d1 loss: 0.027509] [d2 loss: 0.023931]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 423/500] [Batch 220/676] [D loss: -0.068703] [G loss: 0.033902] [d1 loss: 0.048465] [d2 loss: 0.054277]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 423/500] [Batch 240/676] [D loss: 0.020219] [G loss: 0.009563] [d1 loss: 0.057494] [d2 loss: 0.074096]  [sq d1 d2: 0.000276]  [num0: 18.000000] [num1 46.000000]
[Epoch 423/500] [Batch 260/676] [D loss: 0.020262] [G loss: -0.020672] [d1 loss: 0.124662] [d2 loss: 0.110720]  [sq d1 d2: 0.000194]  [num0: 13.000000] [num1 51.000000]
[Epoch 423/500] [Batch 280/676] [D loss: 0.025892] [G loss: -0.014345] [d1 loss: 0.078606] [d2 loss: 0.063185]  [sq d1 d2: 0.000238]  [num0: 19.000000] [num1 45.000000]
[Epoch 423/500] [Batch 300/676] [D loss: 0.019501] [G loss: -0.019793] [d1 loss: 0.068230] [d2 loss: 0.080053]  [sq d1 d2: 0.000140]  [num0: 19.000000] [num1 45.000000]
[Epoch 423/500] [Batch 320/676] [D loss: 0.005278] [G loss: -0.025502] [d1 loss: 0.077710] [d2 loss: 0.065106]  [sq d1 d2: 0.000159]  [num0: 19.000000] [num1 45.000000]
[Epoch 423/500] [Batch 340/676] [D loss: -0.000844] [G loss: -0.029034] [d1 loss: 0.042575] [d2 loss: 0.043121]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 360/676] [D loss: -0.009373] [G loss: -0.038654] [d1 loss: 0.052436] [d2 loss: 0.056455]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 423/500] [Batch 380/676] [D loss: -0.024263] [G loss: -0.046991] [d1 loss: 0.180969] [d2 loss: 0.182122]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 423/500] [Batch 400/676] [D loss: -0.080012] [G loss: 0.006808] [d1 loss: 0.073579] [d2 loss: 0.076320]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 420/676] [D loss: -0.093548] [G loss: 0.026639] [d1 loss: 0.096412] [d2 loss: 0.070689]  [sq d1 d2: 0.000662]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 440/676] [D loss: -0.072608] [G loss: 0.015402] [d1 loss: 0.101542] [d2 loss: 0.107256]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 460/676] [D loss: -0.019441] [G loss: 0.025284] [d1 loss: 0.100806] [d2 loss: 0.112069]  [sq d1 d2: 0.000127]  [num0: 19.000000] [num1 45.000000]
[Epoch 423/500] [Batch 480/676] [D loss: -0.069977] [G loss: -0.016132] [d1 loss: 0.112064] [d2 loss: 0.100778]  [sq d1 d2: 0.000127]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 500/676] [D loss: 0.000088] [G loss: -0.094195] [d1 loss: 0.047265] [d2 loss: 0.048005]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 423/500] [Batch 520/676] [D loss: 0.033114] [G loss: -0.131399] [d1 loss: 0.093326] [d2 loss: 0.093681]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 540/676] [D loss: 0.021422] [G loss: -0.137697] [d1 loss: 0.044073] [d2 loss: 0.057997]  [sq d1 d2: 0.000194]  [num0: 16.000000] [num1 48.000000]
[Epoch 423/500] [Batch 560/676] [D loss: 0.015600] [G loss: -0.096284] [d1 loss: 0.046866] [d2 loss: 0.043140]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 423/500] [Batch 580/676] [D loss: 0.006719] [G loss: -0.071567] [d1 loss: 0.048524] [d2 loss: 0.042005]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 423/500] [Batch 600/676] [D loss: -0.001670] [G loss: -0.031466] [d1 loss: 0.023612] [d2 loss: 0.014729]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 423/500] [Batch 620/676] [D loss: -0.013677] [G loss: -0.016741] [d1 loss: 0.072267] [d2 loss: 0.087345]  [sq d1 d2: 0.000227]  [num0: 16.000000] [num1 48.000000]
[Epoch 423/500] [Batch 640/676] [D loss: -0.028399] [G loss: -0.002516] [d1 loss: 0.051131] [d2 loss: 0.051091]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 423/500] [Batch 660/676] [D loss: -0.024624] [G loss: -0.013165] [d1 loss: 0.038571] [d2 loss: 0.038903]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 0/676] [D loss: -0.070377] [G loss: 0.019054] [d1 loss: 0.040112] [d2 loss: 0.058341]  [sq d1 d2: 0.000332]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 20/676] [D loss: -0.034782] [G loss: 0.104594] [d1 loss: 0.065375] [d2 loss: 0.060458]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 40/676] [D loss: -0.038145] [G loss: 0.089705] [d1 loss: 0.041806] [d2 loss: 0.045104]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 424/500] [Batch 60/676] [D loss: 0.047352] [G loss: 0.059747] [d1 loss: 0.030306] [d2 loss: 0.030948]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 424/500] [Batch 80/676] [D loss: 0.005967] [G loss: -0.007452] [d1 loss: 0.057529] [d2 loss: 0.053107]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 424/500] [Batch 100/676] [D loss: 0.046908] [G loss: -0.001919] [d1 loss: 0.092717] [d2 loss: 0.088306]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 424/500] [Batch 120/676] [D loss: 0.019088] [G loss: -0.011835] [d1 loss: 0.120812] [d2 loss: 0.111794]  [sq d1 d2: 0.000081]  [num0: 19.000000] [num1 45.000000]
[Epoch 424/500] [Batch 140/676] [D loss: 0.017499] [G loss: -0.015115] [d1 loss: 0.126431] [d2 loss: 0.121019]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 160/676] [D loss: 0.005889] [G loss: -0.042244] [d1 loss: 0.164585] [d2 loss: 0.202605]  [sq d1 d2: 0.001445]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 180/676] [D loss: -0.009231] [G loss: -0.087752] [d1 loss: 0.152775] [d2 loss: 0.135092]  [sq d1 d2: 0.000313]  [num0: 14.000000] [num1 50.000000]
[Epoch 424/500] [Batch 200/676] [D loss: -0.020021] [G loss: -0.124844] [d1 loss: 0.051472] [d2 loss: 0.057549]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 220/676] [D loss: -0.028977] [G loss: -0.126393] [d1 loss: 0.155080] [d2 loss: 0.173753]  [sq d1 d2: 0.000349]  [num0: 20.000000] [num1 44.000000]

[Epoch 424/500] [Batch 240/676] [D loss: -0.051383] [G loss: -0.112209] [d1 loss: 0.214722] [d2 loss: 0.175914]  [sq d1 d2: 0.001506]  [num0: 18.000000] [num1 46.000000]
[Epoch 424/500] [Batch 260/676] [D loss: -0.075437] [G loss: -0.139070] [d1 loss: 0.101923] [d2 loss: 0.084704]  [sq d1 d2: 0.000297]  [num0: 17.000000] [num1 47.000000]
[Epoch 424/500] [Batch 280/676] [D loss: -0.059356] [G loss: -0.100634] [d1 loss: 0.047287] [d2 loss: 0.048080]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 300/676] [D loss: -0.000497] [G loss: -0.083871] [d1 loss: 0.055233] [d2 loss: 0.055572]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 320/676] [D loss: -0.007394] [G loss: -0.158015] [d1 loss: 0.063831] [d2 loss: 0.071204]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 340/676] [D loss: 0.079900] [G loss: -0.182287] [d1 loss: 0.046068] [d2 loss: 0.046577]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 424/500] [Batch 360/676] [D loss: 0.051007] [G loss: -0.124562] [d1 loss: 0.061219] [d2 loss: 0.060435]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 380/676] [D loss: 0.019631] [G loss: -0.074377] [d1 loss: 0.074727] [d2 loss: 0.064346]  [sq d1 d2: 0.000108]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 400/676] [D loss: 0.004104] [G loss: -0.018099] [d1 loss: 0.137497] [d2 loss: 0.158081]  [sq d1 d2: 0.000424]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 420/676] [D loss: -0.019732] [G loss: 0.038298] [d1 loss: 0.056165] [d2 loss: 0.071257]  [sq d1 d2: 0.000228]  [num0: 13.000000] [num1 51.000000]
[Epoch 424/500] [Batch 440/676] [D loss: -0.036994] [G loss: 0.132405] [d1 loss: 0.079249] [d2 loss: 0.067511]  [sq d1 d2: 0.000138]  [num0: 18.000000] [num1 46.000000]
[Epoch 424/500] [Batch 460/676] [D loss: -0.109330] [G loss: 0.215857] [d1 loss: 0.140677] [d2 loss: 0.111078]  [sq d1 d2: 0.000876]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 480/676] [D loss: -0.055975] [G loss: 0.261146] [d1 loss: 0.036930] [d2 loss: 0.034534]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 424/500] [Batch 500/676] [D loss: -0.097576] [G loss: 0.313691] [d1 loss: 0.051725] [d2 loss: 0.063330]  [sq d1 d2: 0.000135]  [num0: 19.000000] [num1 45.000000]
[Epoch 424/500] [Batch 520/676] [D loss: -0.070795] [G loss: 0.266397] [d1 loss: 0.058316] [d2 loss: 0.052313]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 540/676] [D loss: 0.024847] [G loss: 0.190586] [d1 loss: 0.076525] [d2 loss: 0.071478]  [sq d1 d2: 0.000025]  [num0: 16.000000] [num1 48.000000]
[Epoch 424/500] [Batch 560/676] [D loss: 0.003538] [G loss: 0.061650] [d1 loss: 0.086590] [d2 loss: 0.101208]  [sq d1 d2: 0.000214]  [num0: 21.000000] [num1 43.000000]
[Epoch 424/500] [Batch 580/676] [D loss: 0.050369] [G loss: -0.092868] [d1 loss: 0.165013] [d2 loss: 0.153715]  [sq d1 d2: 0.000128]  [num0: 17.000000] [num1 47.000000]
[Epoch 424/500] [Batch 600/676] [D loss: 0.010189] [G loss: -0.092067] [d1 loss: 0.056702] [d2 loss: 0.055815]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 620/676] [D loss: 0.012090] [G loss: -0.047893] [d1 loss: 0.095133] [d2 loss: 0.098861]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 640/676] [D loss: -0.003463] [G loss: 0.016719] [d1 loss: 0.047452] [d2 loss: 0.048221]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 424/500] [Batch 660/676] [D loss: -0.023724] [G loss: 0.128675] [d1 loss: 0.076698] [d2 loss: 0.069920]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 425/500] [Batch 0/676] [D loss: -0.036960] [G loss: 0.210361] [d1 loss: 0.123517] [d2 loss: 0.125549]  [sq d1 d2: 0.000004]  [num0: 10.000000] [num1 54.000000]
[Epoch 425/500] [Batch 20/676] [D loss: -0.106799] [G loss: 0.319356] [d1 loss: 0.100752] [d2 loss: 0.108663]  [sq d1 d2: 0.000063]  [num0: 13.000000] [num1 51.000000]
[Epoch 425/500] [Batch 40/676] [D loss: -0.069453] [G loss: 0.331617] [d1 loss: 0.088593] [d2 loss: 0.089083]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 425/500] [Batch 60/676] [D loss: -0.073992] [G loss: 0.339303] [d1 loss: 0.222676] [d2 loss: 0.190805]  [sq d1 d2: 0.001016]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 80/676] [D loss: -0.057279] [G loss: 0.335014] [d1 loss: 0.109452] [d2 loss: 0.109850]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 425/500] [Batch 100/676] [D loss: -0.053979] [G loss: 0.294788] [d1 loss: 0.126052] [d2 loss: 0.113717]  [sq d1 d2: 0.000152]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 120/676] [D loss: 0.018804] [G loss: 0.269918] [d1 loss: 0.119873] [d2 loss: 0.120329]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 425/500] [Batch 140/676] [D loss: -0.012420] [G loss: 0.288900] [d1 loss: 0.025029] [d2 loss: 0.027608]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 160/676] [D loss: 0.059072] [G loss: 0.288641] [d1 loss: 0.112414] [d2 loss: 0.152199]  [sq d1 d2: 0.001583]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 180/676] [D loss: -0.013479] [G loss: 0.230175] [d1 loss: 0.132248] [d2 loss: 0.128434]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 425/500] [Batch 200/676] [D loss: 0.042747] [G loss: 0.183685] [d1 loss: 0.055978] [d2 loss: 0.059216]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 425/500] [Batch 220/676] [D loss: -0.005030] [G loss: 0.096810] [d1 loss: 0.026935] [d2 loss: 0.028031]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 425/500] [Batch 240/676] [D loss: 0.008897] [G loss: 0.025474] [d1 loss: 0.156213] [d2 loss: 0.158245]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 425/500] [Batch 260/676] [D loss: -0.002857] [G loss: -0.052741] [d1 loss: 0.021451] [d2 loss: 0.023003]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 425/500] [Batch 280/676] [D loss: -0.009425] [G loss: -0.122141] [d1 loss: 0.076203] [d2 loss: 0.084226]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 425/500] [Batch 300/676] [D loss: -0.021215] [G loss: -0.193595] [d1 loss: 0.041050] [d2 loss: 0.040489]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 425/500] [Batch 320/676] [D loss: -0.019852] [G loss: -0.300324] [d1 loss: 0.048434] [d2 loss: 0.044088]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 340/676] [D loss: -0.042908] [G loss: -0.348213] [d1 loss: 0.062930] [d2 loss: 0.041641]  [sq d1 d2: 0.000453]  [num0: 13.000000] [num1 51.000000]
[Epoch 425/500] [Batch 360/676] [D loss: -0.050053] [G loss: -0.405761] [d1 loss: 0.042504] [d2 loss: 0.045705]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 425/500] [Batch 380/676] [D loss: -0.057730] [G loss: -0.454435] [d1 loss: 0.024711] [d2 loss: 0.018480]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 425/500] [Batch 400/676] [D loss: -0.026681] [G loss: -0.443102] [d1 loss: 0.052094] [d2 loss: 0.048267]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 425/500] [Batch 420/676] [D loss: 0.058972] [G loss: -0.460631] [d1 loss: 0.037222] [d2 loss: 0.037960]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 425/500] [Batch 440/676] [D loss: -0.003974] [G loss: -0.393120] [d1 loss: 0.099989] [d2 loss: 0.097846]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 425/500] [Batch 460/676] [D loss: 0.046588] [G loss: -0.401136] [d1 loss: 0.107482] [d2 loss: 0.105004]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 425/500] [Batch 480/676] [D loss: 0.006267] [G loss: -0.314667] [d1 loss: 0.051311] [d2 loss: 0.063853]  [sq d1 d2: 0.000157]  [num0: 8.000000] [num1 56.000000]
[Epoch 425/500] [Batch 500/676] [D loss: 0.005913] [G loss: -0.212796] [d1 loss: 0.134584] [d2 loss: 0.114115]  [sq d1 d2: 0.000419]  [num0: 16.000000] [num1 48.000000]
[Epoch 425/500] [Batch 520/676] [D loss: 0.015584] [G loss: -0.128076] [d1 loss: 0.072104] [d2 loss: 0.095277]  [sq d1 d2: 0.000537]  [num0: 12.000000] [num1 52.000000]
[Epoch 425/500] [Batch 540/676] [D loss: -0.002175] [G loss: -0.114339] [d1 loss: 0.370906] [d2 loss: 0.419229]  [sq d1 d2: 0.002335]  [num0: 17.000000] [num1 47.000000]
[Epoch 425/500] [Batch 560/676] [D loss: -0.011054] [G loss: -0.111921] [d1 loss: 0.127142] [d2 loss: 0.100764]  [sq d1 d2: 0.000696]  [num0: 10.000000] [num1 54.000000]

[Epoch 425/500] [Batch 580/676] [D loss: -0.018498] [G loss: -0.109931] [d1 loss: 0.103308] [d2 loss: 0.089229]  [sq d1 d2: 0.000198]  [num0: 18.000000] [num1 46.000000]
[Epoch 425/500] [Batch 600/676] [D loss: 0.002244] [G loss: -0.101032] [d1 loss: 0.084156] [d2 loss: 0.074052]  [sq d1 d2: 0.000102]  [num0: 18.000000] [num1 46.000000]
[Epoch 425/500] [Batch 620/676] [D loss: -0.016312] [G loss: -0.104700] [d1 loss: 0.165244] [d2 loss: 0.196916]  [sq d1 d2: 0.001003]  [num0: 15.000000] [num1 49.000000]
[Epoch 425/500] [Batch 640/676] [D loss: -0.024158] [G loss: -0.085924] [d1 loss: 0.079098] [d2 loss: 0.070409]  [sq d1 d2: 0.000076]  [num0: 13.000000] [num1 51.000000]
[Epoch 425/500] [Batch 660/676] [D loss: -0.024189] [G loss: -0.079721] [d1 loss: 0.096879] [d2 loss: 0.074774]  [sq d1 d2: 0.000489]  [num0: 15.000000] [num1 49.000000]
[Epoch 426/500] [Batch 0/676] [D loss: -0.046514] [G loss: -0.046867] [d1 loss: 0.056014] [d2 loss: 0.055064]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 426/500] [Batch 20/676] [D loss: -0.021193] [G loss: -0.056512] [d1 loss: 0.156857] [d2 loss: 0.134041]  [sq d1 d2: 0.000521]  [num0: 16.000000] [num1 48.000000]
[Epoch 426/500] [Batch 40/676] [D loss: -0.010751] [G loss: -0.032337] [d1 loss: 0.136548] [d2 loss: 0.129645]  [sq d1 d2: 0.000048]  [num0: 12.000000] [num1 52.000000]
[Epoch 426/500] [Batch 60/676] [D loss: -0.002053] [G loss: -0.043638] [d1 loss: 0.413990] [d2 loss: 0.270209]  [sq d1 d2: 0.020673]  [num0: 16.000000] [num1 48.000000]
[Epoch 426/500] [Batch 80/676] [D loss: -0.030360] [G loss: -0.045982] [d1 loss: 0.500608] [d2 loss: 0.362401]  [sq d1 d2: 0.019101]  [num0: 13.000000] [num1 51.000000]
[Epoch 426/500] [Batch 100/676] [D loss: 0.004390] [G loss: -0.049922] [d1 loss: 0.134403] [d2 loss: 0.102450]  [sq d1 d2: 0.001021]  [num0: 19.000000] [num1 45.000000]
[Epoch 426/500] [Batch 120/676] [D loss: -0.016310] [G loss: -0.040809] [d1 loss: 0.079815] [d2 loss: 0.090883]  [sq d1 d2: 0.000122]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 140/676] [D loss: 0.027846] [G loss: -0.014965] [d1 loss: 0.616778] [d2 loss: 0.410225]  [sq d1 d2: 0.042664]  [num0: 13.000000] [num1 51.000000]
[Epoch 426/500] [Batch 160/676] [D loss: 0.011013] [G loss: -0.006300] [d1 loss: 0.354729] [d2 loss: 0.325761]  [sq d1 d2: 0.000839]  [num0: 15.000000] [num1 49.000000]
[Epoch 426/500] [Batch 180/676] [D loss: 0.010212] [G loss: 0.003183] [d1 loss: 0.125315] [d2 loss: 0.123986]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 200/676] [D loss: 0.012225] [G loss: 0.013184] [d1 loss: 0.135338] [d2 loss: 0.162851]  [sq d1 d2: 0.000757]  [num0: 15.000000] [num1 49.000000]
[Epoch 426/500] [Batch 220/676] [D loss: 0.000871] [G loss: 0.009651] [d1 loss: 0.042903] [d2 loss: 0.048945]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 426/500] [Batch 240/676] [D loss: 0.001235] [G loss: 0.004439] [d1 loss: 0.053958] [d2 loss: 0.053812]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 260/676] [D loss: -0.000336] [G loss: -0.009636] [d1 loss: 0.036423] [d2 loss: 0.037189]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 426/500] [Batch 280/676] [D loss: -0.000415] [G loss: -0.026593] [d1 loss: 0.078380] [d2 loss: 0.058498]  [sq d1 d2: 0.000395]  [num0: 14.000000] [num1 50.000000]
[Epoch 426/500] [Batch 300/676] [D loss: -0.008315] [G loss: -0.057938] [d1 loss: 0.082898] [d2 loss: 0.083445]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 320/676] [D loss: -0.015035] [G loss: -0.087824] [d1 loss: 0.047006] [d2 loss: 0.044383]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 340/676] [D loss: -0.013464] [G loss: -0.110528] [d1 loss: 0.023437] [d2 loss: 0.030509]  [sq d1 d2: 0.000050]  [num0: 14.000000] [num1 50.000000]
[Epoch 426/500] [Batch 360/676] [D loss: -0.023581] [G loss: -0.138948] [d1 loss: 0.118542] [d2 loss: 0.101483]  [sq d1 d2: 0.000291]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 380/676] [D loss: -0.011654] [G loss: -0.145365] [d1 loss: 0.050308] [d2 loss: 0.045983]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 426/500] [Batch 400/676] [D loss: -0.013640] [G loss: -0.138930] [d1 loss: 0.125184] [d2 loss: 0.122879]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 426/500] [Batch 420/676] [D loss: 0.012526] [G loss: -0.160977] [d1 loss: 0.041800] [d2 loss: 0.042526]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 440/676] [D loss: -0.022601] [G loss: -0.177160] [d1 loss: 0.037300] [d2 loss: 0.031009]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 426/500] [Batch 460/676] [D loss: -0.000325] [G loss: -0.186891] [d1 loss: 0.074171] [d2 loss: 0.063073]  [sq d1 d2: 0.000123]  [num0: 9.000000] [num1 55.000000]
[Epoch 426/500] [Batch 480/676] [D loss: -0.011180] [G loss: -0.168551] [d1 loss: 0.061326] [d2 loss: 0.074262]  [sq d1 d2: 0.000167]  [num0: 15.000000] [num1 49.000000]
[Epoch 426/500] [Batch 500/676] [D loss: -0.008397] [G loss: -0.162433] [d1 loss: 0.061111] [d2 loss: 0.069188]  [sq d1 d2: 0.000065]  [num0: 18.000000] [num1 46.000000]
[Epoch 426/500] [Batch 520/676] [D loss: 0.006013] [G loss: -0.132901] [d1 loss: 0.039129] [d2 loss: 0.046776]  [sq d1 d2: 0.000058]  [num0: 19.000000] [num1 45.000000]
[Epoch 426/500] [Batch 540/676] [D loss: 0.002505] [G loss: -0.105186] [d1 loss: 0.109724] [d2 loss: 0.111185]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 426/500] [Batch 560/676] [D loss: -0.000466] [G loss: -0.074601] [d1 loss: 0.063914] [d2 loss: 0.075495]  [sq d1 d2: 0.000134]  [num0: 13.000000] [num1 51.000000]
[Epoch 426/500] [Batch 580/676] [D loss: -0.007209] [G loss: -0.057769] [d1 loss: 0.085052] [d2 loss: 0.088032]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 426/500] [Batch 600/676] [D loss: -0.007700] [G loss: -0.054867] [d1 loss: 0.064493] [d2 loss: 0.063855]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 426/500] [Batch 620/676] [D loss: -0.011817] [G loss: -0.040650] [d1 loss: 0.077577] [d2 loss: 0.076595]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 426/500] [Batch 640/676] [D loss: -0.012376] [G loss: -0.018045] [d1 loss: 0.072358] [d2 loss: 0.072430]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 426/500] [Batch 660/676] [D loss: -0.013112] [G loss: 0.013323] [d1 loss: 0.052535] [d2 loss: 0.052371]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 0/676] [D loss: -0.016898] [G loss: 0.016007] [d1 loss: 0.044103] [d2 loss: 0.048928]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 427/500] [Batch 20/676] [D loss: -0.010636] [G loss: 0.035728] [d1 loss: 0.094959] [d2 loss: 0.094249]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 40/676] [D loss: -0.019943] [G loss: 0.058082] [d1 loss: 0.077434] [d2 loss: 0.084786]  [sq d1 d2: 0.000054]  [num0: 16.000000] [num1 48.000000]
[Epoch 427/500] [Batch 60/676] [D loss: 0.010093] [G loss: 0.056283] [d1 loss: 0.065070] [d2 loss: 0.071615]  [sq d1 d2: 0.000043]  [num0: 18.000000] [num1 46.000000]
[Epoch 427/500] [Batch 80/676] [D loss: -0.009186] [G loss: 0.062212] [d1 loss: 0.089647] [d2 loss: 0.090978]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 100/676] [D loss: -0.001978] [G loss: 0.096603] [d1 loss: 0.055360] [d2 loss: 0.058289]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 427/500] [Batch 120/676] [D loss: -0.005878] [G loss: 0.100153] [d1 loss: 1.069217] [d2 loss: 0.773978]  [sq d1 d2: 0.087166]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 140/676] [D loss: 0.000959] [G loss: 0.084866] [d1 loss: 0.043695] [d2 loss: 0.044295]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 160/676] [D loss: 0.009575] [G loss: 0.094447] [d1 loss: 0.081050] [d2 loss: 0.063137]  [sq d1 d2: 0.000321]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 180/676] [D loss: 0.000629] [G loss: 0.084770] [d1 loss: 0.100711] [d2 loss: 0.113042]  [sq d1 d2: 0.000152]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 200/676] [D loss: -0.002125] [G loss: 0.061957] [d1 loss: 0.106095] [d2 loss: 0.068813]  [sq d1 d2: 0.001390]  [num0: 16.000000] [num1 48.000000]
[Epoch 427/500] [Batch 220/676] [D loss: -0.001844] [G loss: 0.023269] [d1 loss: 0.044243] [d2 loss: 0.049135]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]

[Epoch 427/500] [Batch 240/676] [D loss: -0.003624] [G loss: 0.026173] [d1 loss: 0.043245] [d2 loss: 0.065870]  [sq d1 d2: 0.000512]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 260/676] [D loss: -0.015177] [G loss: -0.025539] [d1 loss: 0.151532] [d2 loss: 0.158473]  [sq d1 d2: 0.000048]  [num0: 19.000000] [num1 45.000000]
[Epoch 427/500] [Batch 280/676] [D loss: -0.024815] [G loss: -0.101181] [d1 loss: 0.094931] [d2 loss: 0.081621]  [sq d1 d2: 0.000177]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 300/676] [D loss: -0.004958] [G loss: -0.136348] [d1 loss: 0.034437] [d2 loss: 0.044151]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 320/676] [D loss: -0.003306] [G loss: -0.122473] [d1 loss: 0.093278] [d2 loss: 0.120330]  [sq d1 d2: 0.000732]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 340/676] [D loss: -0.005463] [G loss: -0.149744] [d1 loss: 0.073752] [d2 loss: 0.084420]  [sq d1 d2: 0.000114]  [num0: 19.000000] [num1 45.000000]
[Epoch 427/500] [Batch 360/676] [D loss: -0.002344] [G loss: -0.139954] [d1 loss: 0.064328] [d2 loss: 0.072730]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 380/676] [D loss: 0.014555] [G loss: -0.150802] [d1 loss: 0.057921] [d2 loss: 0.054769]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 400/676] [D loss: -0.006812] [G loss: -0.100812] [d1 loss: 0.010617] [d2 loss: 0.017972]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 420/676] [D loss: -0.008467] [G loss: -0.086241] [d1 loss: 0.094897] [d2 loss: 0.101641]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 440/676] [D loss: -0.000828] [G loss: -0.041331] [d1 loss: 0.027449] [d2 loss: 0.041843]  [sq d1 d2: 0.000207]  [num0: 16.000000] [num1 48.000000]
[Epoch 427/500] [Batch 460/676] [D loss: -0.002163] [G loss: -0.007881] [d1 loss: 0.073720] [d2 loss: 0.072400]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 427/500] [Batch 480/676] [D loss: -0.004807] [G loss: 0.025690] [d1 loss: 0.104845] [d2 loss: 0.108884]  [sq d1 d2: 0.000016]  [num0: 13.000000] [num1 51.000000]
[Epoch 427/500] [Batch 500/676] [D loss: -0.000577] [G loss: 0.037114] [d1 loss: 0.093767] [d2 loss: 0.086225]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 520/676] [D loss: -0.014008] [G loss: 0.051914] [d1 loss: 0.057120] [d2 loss: 0.046294]  [sq d1 d2: 0.000117]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 540/676] [D loss: -0.024709] [G loss: 0.074928] [d1 loss: 0.127610] [d2 loss: 0.097519]  [sq d1 d2: 0.000906]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 560/676] [D loss: -0.005777] [G loss: 0.036683] [d1 loss: 0.039889] [d2 loss: 0.035012]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 427/500] [Batch 580/676] [D loss: -0.042099] [G loss: 0.067710] [d1 loss: 0.067149] [d2 loss: 0.073959]  [sq d1 d2: 0.000046]  [num0: 15.000000] [num1 49.000000]
[Epoch 427/500] [Batch 600/676] [D loss: -0.002498] [G loss: 0.099167] [d1 loss: 0.057944] [d2 loss: 0.055862]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 427/500] [Batch 620/676] [D loss: 0.024783] [G loss: 0.071752] [d1 loss: 0.131932] [d2 loss: 0.125884]  [sq d1 d2: 0.000037]  [num0: 19.000000] [num1 45.000000]
[Epoch 427/500] [Batch 640/676] [D loss: 0.005954] [G loss: 0.070912] [d1 loss: 0.029145] [d2 loss: 0.031766]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 427/500] [Batch 660/676] [D loss: 0.019085] [G loss: 0.082459] [d1 loss: 0.087281] [d2 loss: 0.080595]  [sq d1 d2: 0.000045]  [num0: 13.000000] [num1 51.000000]
[Epoch 428/500] [Batch 0/676] [D loss: 0.019412] [G loss: 0.066799] [d1 loss: 0.057557] [d2 loss: 0.058319]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 428/500] [Batch 20/676] [D loss: 0.007502] [G loss: 0.040294] [d1 loss: 0.093259] [d2 loss: 0.098394]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 428/500] [Batch 40/676] [D loss: -0.002040] [G loss: 0.019002] [d1 loss: 0.058687] [d2 loss: 0.069245]  [sq d1 d2: 0.000111]  [num0: 15.000000] [num1 49.000000]
[Epoch 428/500] [Batch 60/676] [D loss: -0.008473] [G loss: 0.014225] [d1 loss: 0.080302] [d2 loss: 0.068084]  [sq d1 d2: 0.000149]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 80/676] [D loss: -0.009353] [G loss: -0.008948] [d1 loss: 0.117023] [d2 loss: 0.107016]  [sq d1 d2: 0.000100]  [num0: 13.000000] [num1 51.000000]
[Epoch 428/500] [Batch 100/676] [D loss: -0.012240] [G loss: -0.034648] [d1 loss: 0.075676] [d2 loss: 0.075547]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 120/676] [D loss: -0.015956] [G loss: -0.061330] [d1 loss: 0.049229] [d2 loss: 0.056324]  [sq d1 d2: 0.000050]  [num0: 18.000000] [num1 46.000000]
[Epoch 428/500] [Batch 140/676] [D loss: -0.009848] [G loss: -0.095566] [d1 loss: 0.033168] [d2 loss: 0.056381]  [sq d1 d2: 0.000539]  [num0: 18.000000] [num1 46.000000]
[Epoch 428/500] [Batch 160/676] [D loss: -0.010215] [G loss: -0.084023] [d1 loss: 0.126043] [d2 loss: 0.087653]  [sq d1 d2: 0.001474]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 180/676] [D loss: -0.058685] [G loss: -0.155243] [d1 loss: 0.146746] [d2 loss: 0.234956]  [sq d1 d2: 0.007781]  [num0: 17.000000] [num1 47.000000]
[Epoch 428/500] [Batch 200/676] [D loss: -0.012319] [G loss: -0.111644] [d1 loss: 0.067323] [d2 loss: 0.109865]  [sq d1 d2: 0.001810]  [num0: 19.000000] [num1 45.000000]
[Epoch 428/500] [Batch 220/676] [D loss: -0.002019] [G loss: -0.124685] [d1 loss: 0.074944] [d2 loss: 0.118047]  [sq d1 d2: 0.001858]  [num0: 17.000000] [num1 47.000000]
[Epoch 428/500] [Batch 240/676] [D loss: 0.002047] [G loss: -0.120482] [d1 loss: 0.031572] [d2 loss: 0.033767]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 260/676] [D loss: -0.011951] [G loss: -0.113369] [d1 loss: 0.057933] [d2 loss: 0.083862]  [sq d1 d2: 0.000672]  [num0: 13.000000] [num1 51.000000]
[Epoch 428/500] [Batch 280/676] [D loss: -0.001744] [G loss: -0.108862] [d1 loss: 0.087696] [d2 loss: 0.062484]  [sq d1 d2: 0.000636]  [num0: 18.000000] [num1 46.000000]
[Epoch 428/500] [Batch 300/676] [D loss: 0.014113] [G loss: -0.084404] [d1 loss: 0.071744] [d2 loss: 0.065494]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 320/676] [D loss: -0.009189] [G loss: -0.043024] [d1 loss: 0.127356] [d2 loss: 0.087241]  [sq d1 d2: 0.001609]  [num0: 17.000000] [num1 47.000000]
[Epoch 428/500] [Batch 340/676] [D loss: -0.001674] [G loss: -0.021823] [d1 loss: 0.070775] [d2 loss: 0.077973]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 428/500] [Batch 360/676] [D loss: -0.008367] [G loss: 0.008208] [d1 loss: 0.057299] [d2 loss: 0.055399]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 380/676] [D loss: -0.021336] [G loss: 0.045598] [d1 loss: 0.056272] [d2 loss: 0.062320]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 400/676] [D loss: -0.018944] [G loss: 0.061794] [d1 loss: 0.133769] [d2 loss: 0.114110]  [sq d1 d2: 0.000387]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 420/676] [D loss: -0.017664] [G loss: 0.081827] [d1 loss: 0.043094] [d2 loss: 0.046814]  [sq d1 d2: 0.000014]  [num0: 11.000000] [num1 53.000000]
[Epoch 428/500] [Batch 440/676] [D loss: 0.000690] [G loss: 0.089242] [d1 loss: 0.100549] [d2 loss: 0.098423]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 428/500] [Batch 460/676] [D loss: -0.017350] [G loss: 0.084367] [d1 loss: 0.128667] [d2 loss: 0.136242]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 428/500] [Batch 480/676] [D loss: -0.001043] [G loss: 0.065193] [d1 loss: 0.102329] [d2 loss: 0.104157]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 428/500] [Batch 500/676] [D loss: 0.005516] [G loss: 0.065109] [d1 loss: 0.238380] [d2 loss: 0.082013]  [sq d1 d2: 0.024450]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 520/676] [D loss: 0.005903] [G loss: 0.059694] [d1 loss: 0.090522] [d2 loss: 0.101748]  [sq d1 d2: 0.000126]  [num0: 14.000000] [num1 50.000000]
[Epoch 428/500] [Batch 540/676] [D loss: -0.007816] [G loss: 0.010496] [d1 loss: 0.033286] [d2 loss: 0.025621]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 560/676] [D loss: 0.017882] [G loss: -0.008421] [d1 loss: 0.035987] [d2 loss: 0.028267]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 428/500] [Batch 580/676] [D loss: -0.007002] [G loss: -0.029035] [d1 loss: 0.033198] [d2 loss: 0.036084]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]

[Epoch 428/500] [Batch 600/676] [D loss: 0.003835] [G loss: -0.055928] [d1 loss: 0.144305] [d2 loss: 0.193137]  [sq d1 d2: 0.002385]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 620/676] [D loss: -0.006135] [G loss: -0.065849] [d1 loss: 0.043514] [d2 loss: 0.047222]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 640/676] [D loss: -0.003594] [G loss: -0.096630] [d1 loss: 0.088645] [d2 loss: 0.121568]  [sq d1 d2: 0.001084]  [num0: 16.000000] [num1 48.000000]
[Epoch 428/500] [Batch 660/676] [D loss: -0.004750] [G loss: -0.115611] [d1 loss: 0.040276] [d2 loss: 0.051782]  [sq d1 d2: 0.000132]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 0/676] [D loss: 0.002892] [G loss: -0.163545] [d1 loss: 0.034961] [d2 loss: 0.033805]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 20/676] [D loss: -0.010133] [G loss: -0.180883] [d1 loss: 0.070186] [d2 loss: 0.035417]  [sq d1 d2: 0.001209]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 40/676] [D loss: 0.000961] [G loss: -0.215300] [d1 loss: 0.050203] [d2 loss: 0.038173]  [sq d1 d2: 0.000145]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 60/676] [D loss: -0.044273] [G loss: -0.276034] [d1 loss: 0.086398] [d2 loss: 0.080181]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 429/500] [Batch 80/676] [D loss: -0.035100] [G loss: -0.273268] [d1 loss: 0.106153] [d2 loss: 0.100738]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 429/500] [Batch 100/676] [D loss: -0.034161] [G loss: -0.315849] [d1 loss: 0.045873] [d2 loss: 0.062618]  [sq d1 d2: 0.000280]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 120/676] [D loss: -0.006061] [G loss: -0.344740] [d1 loss: 0.041498] [d2 loss: 0.062827]  [sq d1 d2: 0.000455]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 140/676] [D loss: -0.032984] [G loss: -0.253499] [d1 loss: 0.075908] [d2 loss: 0.075275]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 429/500] [Batch 160/676] [D loss: 0.008043] [G loss: -0.201804] [d1 loss: 0.147967] [d2 loss: 0.153378]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 429/500] [Batch 180/676] [D loss: -0.005295] [G loss: -0.189976] [d1 loss: 0.062313] [d2 loss: 0.083565]  [sq d1 d2: 0.000452]  [num0: 11.000000] [num1 53.000000]
[Epoch 429/500] [Batch 200/676] [D loss: 0.019452] [G loss: -0.140969] [d1 loss: 0.029208] [d2 loss: 0.037916]  [sq d1 d2: 0.000076]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 220/676] [D loss: 0.006826] [G loss: -0.086063] [d1 loss: 0.070833] [d2 loss: 0.057623]  [sq d1 d2: 0.000175]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 240/676] [D loss: 0.001462] [G loss: -0.062449] [d1 loss: 0.038747] [d2 loss: 0.048994]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 429/500] [Batch 260/676] [D loss: -0.010357] [G loss: -0.049755] [d1 loss: 0.090521] [d2 loss: 0.086986]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 280/676] [D loss: -0.015825] [G loss: -0.028988] [d1 loss: 0.083015] [d2 loss: 0.090872]  [sq d1 d2: 0.000062]  [num0: 11.000000] [num1 53.000000]
[Epoch 429/500] [Batch 300/676] [D loss: -0.015392] [G loss: -0.031525] [d1 loss: 0.086556] [d2 loss: 0.076620]  [sq d1 d2: 0.000099]  [num0: 13.000000] [num1 51.000000]
[Epoch 429/500] [Batch 320/676] [D loss: -0.010195] [G loss: -0.037836] [d1 loss: 0.049024] [d2 loss: 0.046106]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 429/500] [Batch 340/676] [D loss: -0.015997] [G loss: -0.018363] [d1 loss: 0.122250] [d2 loss: 0.155403]  [sq d1 d2: 0.001099]  [num0: 17.000000] [num1 47.000000]
[Epoch 429/500] [Batch 360/676] [D loss: -0.006286] [G loss: -0.070124] [d1 loss: 0.042323] [d2 loss: 0.042011]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 380/676] [D loss: -0.022049] [G loss: -0.064807] [d1 loss: 0.083743] [d2 loss: 0.068331]  [sq d1 d2: 0.000238]  [num0: 15.000000] [num1 49.000000]
[Epoch 429/500] [Batch 400/676] [D loss: -0.009058] [G loss: -0.039589] [d1 loss: 0.073494] [d2 loss: 0.075465]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 429/500] [Batch 420/676] [D loss: 0.003851] [G loss: -0.055882] [d1 loss: 0.122713] [d2 loss: 0.090625]  [sq d1 d2: 0.001030]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 440/676] [D loss: -0.011735] [G loss: -0.058820] [d1 loss: 0.083379] [d2 loss: 0.065306]  [sq d1 d2: 0.000327]  [num0: 16.000000] [num1 48.000000]
[Epoch 429/500] [Batch 460/676] [D loss: -0.016288] [G loss: -0.057618] [d1 loss: 0.088224] [d2 loss: 0.108755]  [sq d1 d2: 0.000422]  [num0: 17.000000] [num1 47.000000]
[Epoch 429/500] [Batch 480/676] [D loss: 0.017781] [G loss: -0.154978] [d1 loss: 0.121677] [d2 loss: 0.127564]  [sq d1 d2: 0.000035]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 500/676] [D loss: -0.012721] [G loss: -0.126358] [d1 loss: 0.014700] [d2 loss: 0.014161]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 520/676] [D loss: 0.023663] [G loss: -0.115347] [d1 loss: 0.093292] [d2 loss: 0.079561]  [sq d1 d2: 0.000189]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 540/676] [D loss: -0.007405] [G loss: -0.113309] [d1 loss: 0.159491] [d2 loss: 0.185224]  [sq d1 d2: 0.000662]  [num0: 18.000000] [num1 46.000000]
[Epoch 429/500] [Batch 560/676] [D loss: 0.001467] [G loss: -0.105437] [d1 loss: 0.069780] [d2 loss: 0.070477]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 429/500] [Batch 580/676] [D loss: -0.008606] [G loss: -0.091037] [d1 loss: 0.059801] [d2 loss: 0.055821]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 600/676] [D loss: -0.012348] [G loss: -0.078540] [d1 loss: 0.041683] [d2 loss: 0.082632]  [sq d1 d2: 0.001677]  [num0: 13.000000] [num1 51.000000]
[Epoch 429/500] [Batch 620/676] [D loss: 0.000223] [G loss: -0.139974] [d1 loss: 0.062601] [d2 loss: 0.069842]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 429/500] [Batch 640/676] [D loss: -0.011103] [G loss: -0.105490] [d1 loss: 0.042496] [d2 loss: 0.040205]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 429/500] [Batch 660/676] [D loss: -0.006831] [G loss: -0.093484] [d1 loss: 0.120613] [d2 loss: 0.105751]  [sq d1 d2: 0.000221]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 0/676] [D loss: -0.019525] [G loss: -0.123108] [d1 loss: 0.088260] [d2 loss: 0.098046]  [sq d1 d2: 0.000096]  [num0: 14.000000] [num1 50.000000]
[Epoch 430/500] [Batch 20/676] [D loss: -0.027273] [G loss: -0.103530] [d1 loss: 0.159174] [d2 loss: 0.170762]  [sq d1 d2: 0.000134]  [num0: 20.000000] [num1 44.000000]
[Epoch 430/500] [Batch 40/676] [D loss: -0.002857] [G loss: -0.118761] [d1 loss: 0.040439] [d2 loss: 0.034125]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 430/500] [Batch 60/676] [D loss: -0.011793] [G loss: -0.145662] [d1 loss: 0.134718] [d2 loss: 0.133342]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 430/500] [Batch 80/676] [D loss: -0.011794] [G loss: -0.132811] [d1 loss: 0.043379] [d2 loss: 0.045502]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 430/500] [Batch 100/676] [D loss: -0.006342] [G loss: -0.083601] [d1 loss: 0.057199] [d2 loss: 0.051177]  [sq d1 d2: 0.000036]  [num0: 14.000000] [num1 50.000000]
[Epoch 430/500] [Batch 120/676] [D loss: -0.012980] [G loss: -0.085202] [d1 loss: 0.040962] [d2 loss: 0.040212]  [sq d1 d2: 0.000001]  [num0: 10.000000] [num1 54.000000]
[Epoch 430/500] [Batch 140/676] [D loss: -0.016515] [G loss: -0.126315] [d1 loss: 0.098570] [d2 loss: 0.123588]  [sq d1 d2: 0.000626]  [num0: 15.000000] [num1 49.000000]
[Epoch 430/500] [Batch 160/676] [D loss: 0.001738] [G loss: -0.110612] [d1 loss: 0.049996] [d2 loss: 0.061145]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 430/500] [Batch 180/676] [D loss: 0.004243] [G loss: -0.119267] [d1 loss: 0.048619] [d2 loss: 0.079206]  [sq d1 d2: 0.000936]  [num0: 15.000000] [num1 49.000000]
[Epoch 430/500] [Batch 200/676] [D loss: 0.008424] [G loss: -0.109759] [d1 loss: 0.034164] [d2 loss: 0.041315]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 430/500] [Batch 220/676] [D loss: -0.017974] [G loss: -0.104685] [d1 loss: 0.046927] [d2 loss: 0.045730]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 430/500] [Batch 240/676] [D loss: -0.010350] [G loss: -0.087813] [d1 loss: 0.085220] [d2 loss: 0.086190]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 430/500] [Batch 260/676] [D loss: -0.029313] [G loss: -0.084184] [d1 loss: 0.094335] [d2 loss: 0.099298]  [sq d1 d2: 0.000025]  [num0: 12.000000] [num1 52.000000]

[Epoch 430/500] [Batch 280/676] [D loss: -0.017859] [G loss: -0.106903] [d1 loss: 0.041530] [d2 loss: 0.040339]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 430/500] [Batch 300/676] [D loss: -0.002918] [G loss: -0.102947] [d1 loss: 0.119187] [d2 loss: 0.118436]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 430/500] [Batch 320/676] [D loss: -0.018199] [G loss: -0.064799] [d1 loss: 0.023001] [d2 loss: 0.031763]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 430/500] [Batch 340/676] [D loss: -0.002020] [G loss: -0.021110] [d1 loss: 0.050628] [d2 loss: 0.058839]  [sq d1 d2: 0.000067]  [num0: 12.000000] [num1 52.000000]
[Epoch 430/500] [Batch 360/676] [D loss: -0.023824] [G loss: 0.023842] [d1 loss: 0.128998] [d2 loss: 0.142372]  [sq d1 d2: 0.000179]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 380/676] [D loss: 0.007379] [G loss: 0.047991] [d1 loss: 0.105083] [d2 loss: 0.073795]  [sq d1 d2: 0.000979]  [num0: 14.000000] [num1 50.000000]
[Epoch 430/500] [Batch 400/676] [D loss: -0.026262] [G loss: 0.079317] [d1 loss: 0.026534] [d2 loss: 0.043041]  [sq d1 d2: 0.000272]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 420/676] [D loss: -0.014927] [G loss: 0.127861] [d1 loss: 0.065758] [d2 loss: 0.070380]  [sq d1 d2: 0.000021]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 440/676] [D loss: -0.021246] [G loss: 0.188297] [d1 loss: 0.338571] [d2 loss: 0.174643]  [sq d1 d2: 0.026872]  [num0: 18.000000] [num1 46.000000]
[Epoch 430/500] [Batch 460/676] [D loss: -0.007787] [G loss: 0.174734] [d1 loss: 0.055253] [d2 loss: 0.036648]  [sq d1 d2: 0.000346]  [num0: 18.000000] [num1 46.000000]
[Epoch 430/500] [Batch 480/676] [D loss: 0.016719] [G loss: 0.202793] [d1 loss: 0.077479] [d2 loss: 0.063003]  [sq d1 d2: 0.000210]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 500/676] [D loss: -0.035515] [G loss: 0.213347] [d1 loss: 0.054550] [d2 loss: 0.055670]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 430/500] [Batch 520/676] [D loss: -0.029713] [G loss: 0.217239] [d1 loss: 0.114258] [d2 loss: 0.124674]  [sq d1 d2: 0.000108]  [num0: 17.000000] [num1 47.000000]
[Epoch 430/500] [Batch 540/676] [D loss: -0.012966] [G loss: 0.173477] [d1 loss: 0.019413] [d2 loss: 0.013691]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 430/500] [Batch 560/676] [D loss: 0.014609] [G loss: 0.138301] [d1 loss: 0.048506] [d2 loss: 0.053199]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 580/676] [D loss: -0.040215] [G loss: 0.138541] [d1 loss: 0.078432] [d2 loss: 0.065315]  [sq d1 d2: 0.000172]  [num0: 13.000000] [num1 51.000000]
[Epoch 430/500] [Batch 600/676] [D loss: 0.001246] [G loss: 0.135829] [d1 loss: 0.032403] [d2 loss: 0.027454]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 430/500] [Batch 620/676] [D loss: 0.002565] [G loss: 0.061062] [d1 loss: 0.015789] [d2 loss: 0.025090]  [sq d1 d2: 0.000087]  [num0: 20.000000] [num1 44.000000]
[Epoch 430/500] [Batch 640/676] [D loss: -0.010372] [G loss: -0.021059] [d1 loss: 0.121585] [d2 loss: 0.180491]  [sq d1 d2: 0.003470]  [num0: 17.000000] [num1 47.000000]
[Epoch 430/500] [Batch 660/676] [D loss: -0.035925] [G loss: -0.083665] [d1 loss: 0.026160] [d2 loss: 0.029774]  [sq d1 d2: 0.000013]  [num0: 19.000000] [num1 45.000000]
[Epoch 431/500] [Batch 0/676] [D loss: 0.000675] [G loss: -0.119714] [d1 loss: 0.033646] [d2 loss: 0.023379]  [sq d1 d2: 0.000105]  [num0: 13.000000] [num1 51.000000]
[Epoch 431/500] [Batch 20/676] [D loss: -0.025775] [G loss: -0.160565] [d1 loss: 0.088128] [d2 loss: 0.090834]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 431/500] [Batch 40/676] [D loss: 0.016386] [G loss: -0.234677] [d1 loss: 0.121481] [d2 loss: 0.107186]  [sq d1 d2: 0.000204]  [num0: 13.000000] [num1 51.000000]
[Epoch 431/500] [Batch 60/676] [D loss: 0.001899] [G loss: -0.270225] [d1 loss: 0.024894] [d2 loss: 0.014277]  [sq d1 d2: 0.000113]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 80/676] [D loss: 0.007044] [G loss: -0.306046] [d1 loss: 0.067211] [d2 loss: 0.086486]  [sq d1 d2: 0.000372]  [num0: 13.000000] [num1 51.000000]
[Epoch 431/500] [Batch 100/676] [D loss: -0.009931] [G loss: -0.363172] [d1 loss: 0.069917] [d2 loss: 0.088148]  [sq d1 d2: 0.000332]  [num0: 13.000000] [num1 51.000000]
[Epoch 431/500] [Batch 120/676] [D loss: 0.001924] [G loss: -0.352504] [d1 loss: 0.034571] [d2 loss: 0.027051]  [sq d1 d2: 0.000057]  [num0: 10.000000] [num1 54.000000]
[Epoch 431/500] [Batch 140/676] [D loss: 0.003724] [G loss: -0.336557] [d1 loss: 0.061059] [d2 loss: 0.050682]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 160/676] [D loss: -0.034591] [G loss: -0.303089] [d1 loss: 0.109413] [d2 loss: 0.101565]  [sq d1 d2: 0.000062]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 180/676] [D loss: 0.001745] [G loss: -0.272450] [d1 loss: 0.041000] [d2 loss: 0.031998]  [sq d1 d2: 0.000081]  [num0: 11.000000] [num1 53.000000]
[Epoch 431/500] [Batch 200/676] [D loss: -0.029770] [G loss: -0.254653] [d1 loss: 0.037931] [d2 loss: 0.088606]  [sq d1 d2: 0.002568]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 220/676] [D loss: -0.022310] [G loss: -0.210213] [d1 loss: 0.018732] [d2 loss: 0.019416]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 431/500] [Batch 240/676] [D loss: -0.037578] [G loss: -0.140052] [d1 loss: 0.110797] [d2 loss: 0.127050]  [sq d1 d2: 0.000264]  [num0: 20.000000] [num1 44.000000]
[Epoch 431/500] [Batch 260/676] [D loss: -0.002745] [G loss: -0.100607] [d1 loss: 0.038743] [d2 loss: 0.038007]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 431/500] [Batch 280/676] [D loss: -0.019947] [G loss: -0.050944] [d1 loss: 0.091153] [d2 loss: 0.081250]  [sq d1 d2: 0.000098]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 300/676] [D loss: -0.032695] [G loss: -0.017063] [d1 loss: 0.111528] [d2 loss: 0.120651]  [sq d1 d2: 0.000083]  [num0: 11.000000] [num1 53.000000]
[Epoch 431/500] [Batch 320/676] [D loss: -0.010864] [G loss: 0.003937] [d1 loss: 0.061372] [d2 loss: 0.054691]  [sq d1 d2: 0.000045]  [num0: 18.000000] [num1 46.000000]
[Epoch 431/500] [Batch 340/676] [D loss: -0.001056] [G loss: 0.021399] [d1 loss: 0.060242] [d2 loss: 0.044820]  [sq d1 d2: 0.000238]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 360/676] [D loss: 0.011807] [G loss: 0.042809] [d1 loss: 0.074720] [d2 loss: 0.064351]  [sq d1 d2: 0.000108]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 380/676] [D loss: -0.004607] [G loss: 0.005249] [d1 loss: 0.024275] [d2 loss: 0.050534]  [sq d1 d2: 0.000690]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 400/676] [D loss: 0.008473] [G loss: 0.018087] [d1 loss: 0.073741] [d2 loss: 0.066680]  [sq d1 d2: 0.000050]  [num0: 12.000000] [num1 52.000000]
[Epoch 431/500] [Batch 420/676] [D loss: -0.006193] [G loss: 0.000327] [d1 loss: 0.116810] [d2 loss: 0.113767]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 431/500] [Batch 440/676] [D loss: -0.012712] [G loss: -0.035697] [d1 loss: 0.061093] [d2 loss: 0.047481]  [sq d1 d2: 0.000185]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 460/676] [D loss: 0.012579] [G loss: -0.051362] [d1 loss: 0.060399] [d2 loss: 0.034814]  [sq d1 d2: 0.000655]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 480/676] [D loss: -0.014214] [G loss: -0.059305] [d1 loss: 0.045238] [d2 loss: 0.049176]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 431/500] [Batch 500/676] [D loss: -0.026992] [G loss: -0.064473] [d1 loss: 0.014618] [d2 loss: 0.014113]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 431/500] [Batch 520/676] [D loss: 0.011860] [G loss: -0.111334] [d1 loss: 0.077526] [d2 loss: 0.061343]  [sq d1 d2: 0.000262]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 540/676] [D loss: -0.016080] [G loss: -0.113433] [d1 loss: 0.060998] [d2 loss: 0.083746]  [sq d1 d2: 0.000517]  [num0: 16.000000] [num1 48.000000]
[Epoch 431/500] [Batch 560/676] [D loss: -0.003126] [G loss: -0.148259] [d1 loss: 0.047093] [d2 loss: 0.082444]  [sq d1 d2: 0.001250]  [num0: 15.000000] [num1 49.000000]
[Epoch 431/500] [Batch 580/676] [D loss: 0.001424] [G loss: -0.168091] [d1 loss: 0.026349] [d2 loss: 0.013388]  [sq d1 d2: 0.000168]  [num0: 18.000000] [num1 46.000000]
[Epoch 431/500] [Batch 600/676] [D loss: -0.008770] [G loss: -0.167709] [d1 loss: 0.154654] [d2 loss: 0.063629]  [sq d1 d2: 0.008286]  [num0: 19.000000] [num1 45.000000]
[Epoch 431/500] [Batch 620/676] [D loss: -0.005830] [G loss: -0.150267] [d1 loss: 0.025956] [d2 loss: 0.027440]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]

[Epoch 431/500] [Batch 640/676] [D loss: -0.002780] [G loss: -0.184823] [d1 loss: 0.063780] [d2 loss: 0.062529]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 431/500] [Batch 660/676] [D loss: 0.001244] [G loss: -0.195634] [d1 loss: 0.068909] [d2 loss: 0.062375]  [sq d1 d2: 0.000043]  [num0: 19.000000] [num1 45.000000]
[Epoch 432/500] [Batch 0/676] [D loss: -0.004475] [G loss: -0.160117] [d1 loss: 0.090397] [d2 loss: 0.095503]  [sq d1 d2: 0.000026]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 20/676] [D loss: -0.028839] [G loss: -0.154689] [d1 loss: 0.079689] [d2 loss: 0.091490]  [sq d1 d2: 0.000139]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 40/676] [D loss: -0.017706] [G loss: -0.124758] [d1 loss: 0.021593] [d2 loss: 0.020017]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 60/676] [D loss: -0.017622] [G loss: -0.084553] [d1 loss: 0.082082] [d2 loss: 0.084640]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 80/676] [D loss: -0.038977] [G loss: -0.043543] [d1 loss: 0.062194] [d2 loss: 0.066898]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 432/500] [Batch 100/676] [D loss: -0.029624] [G loss: -0.064297] [d1 loss: 0.078388] [d2 loss: 0.075240]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 432/500] [Batch 120/676] [D loss: 0.003619] [G loss: -0.050219] [d1 loss: 0.036489] [d2 loss: 0.049048]  [sq d1 d2: 0.000158]  [num0: 14.000000] [num1 50.000000]
[Epoch 432/500] [Batch 140/676] [D loss: -0.005427] [G loss: -0.019766] [d1 loss: 0.044762] [d2 loss: 0.039167]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 160/676] [D loss: -0.010273] [G loss: -0.002717] [d1 loss: 0.055619] [d2 loss: 0.051155]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 180/676] [D loss: 0.002218] [G loss: 0.045037] [d1 loss: 0.049760] [d2 loss: 0.053021]  [sq d1 d2: 0.000011]  [num0: 21.000000] [num1 43.000000]
[Epoch 432/500] [Batch 200/676] [D loss: -0.003302] [G loss: 0.078704] [d1 loss: 0.041025] [d2 loss: 0.041914]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 220/676] [D loss: 0.008042] [G loss: 0.092440] [d1 loss: 0.044690] [d2 loss: 0.043165]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 432/500] [Batch 240/676] [D loss: -0.000848] [G loss: 0.085283] [d1 loss: 0.075702] [d2 loss: 0.067620]  [sq d1 d2: 0.000065]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 260/676] [D loss: -0.000316] [G loss: 0.094408] [d1 loss: 0.039269] [d2 loss: 0.067360]  [sq d1 d2: 0.000789]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 280/676] [D loss: -0.001847] [G loss: 0.082171] [d1 loss: 0.078978] [d2 loss: 0.124335]  [sq d1 d2: 0.002057]  [num0: 13.000000] [num1 51.000000]
[Epoch 432/500] [Batch 300/676] [D loss: 0.000857] [G loss: 0.079844] [d1 loss: 0.052009] [d2 loss: 0.054509]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 320/676] [D loss: -0.036648] [G loss: 0.052175] [d1 loss: 0.029567] [d2 loss: 0.038239]  [sq d1 d2: 0.000075]  [num0: 16.000000] [num1 48.000000]
[Epoch 432/500] [Batch 340/676] [D loss: -0.026359] [G loss: 0.044257] [d1 loss: 0.098945] [d2 loss: 0.081515]  [sq d1 d2: 0.000304]  [num0: 14.000000] [num1 50.000000]
[Epoch 432/500] [Batch 360/676] [D loss: -0.010954] [G loss: 0.021558] [d1 loss: 0.036118] [d2 loss: 0.033935]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 380/676] [D loss: -0.007171] [G loss: -0.032782] [d1 loss: 0.099771] [d2 loss: 0.091577]  [sq d1 d2: 0.000067]  [num0: 16.000000] [num1 48.000000]
[Epoch 432/500] [Batch 400/676] [D loss: -0.042906] [G loss: -0.061210] [d1 loss: 0.016352] [d2 loss: 0.022595]  [sq d1 d2: 0.000039]  [num0: 21.000000] [num1 43.000000]
[Epoch 432/500] [Batch 420/676] [D loss: -0.017872] [G loss: -0.064573] [d1 loss: 0.028339] [d2 loss: 0.028619]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 432/500] [Batch 440/676] [D loss: -0.005874] [G loss: -0.085759] [d1 loss: 0.153076] [d2 loss: 0.167023]  [sq d1 d2: 0.000195]  [num0: 14.000000] [num1 50.000000]
[Epoch 432/500] [Batch 460/676] [D loss: -0.018341] [G loss: -0.081120] [d1 loss: 0.057160] [d2 loss: 0.090624]  [sq d1 d2: 0.001120]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 480/676] [D loss: 0.019645] [G loss: -0.079594] [d1 loss: 0.056252] [d2 loss: 0.039214]  [sq d1 d2: 0.000290]  [num0: 13.000000] [num1 51.000000]
[Epoch 432/500] [Batch 500/676] [D loss: 0.021065] [G loss: -0.091165] [d1 loss: 0.050592] [d2 loss: 0.056494]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 432/500] [Batch 520/676] [D loss: -0.027348] [G loss: -0.062786] [d1 loss: 0.008390] [d2 loss: 0.017584]  [sq d1 d2: 0.000085]  [num0: 15.000000] [num1 49.000000]
[Epoch 432/500] [Batch 540/676] [D loss: 0.029857] [G loss: -0.082245] [d1 loss: 0.064460] [d2 loss: 0.068319]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 432/500] [Batch 560/676] [D loss: -0.011202] [G loss: -0.082123] [d1 loss: 0.115593] [d2 loss: 0.074392]  [sq d1 d2: 0.001698]  [num0: 15.000000] [num1 49.000000]
[Epoch 432/500] [Batch 580/676] [D loss: 0.002929] [G loss: -0.079374] [d1 loss: 0.063079] [d2 loss: 0.065811]  [sq d1 d2: 0.000007]  [num0: 20.000000] [num1 44.000000]
[Epoch 432/500] [Batch 600/676] [D loss: -0.004887] [G loss: -0.085554] [d1 loss: 0.059535] [d2 loss: 0.104336]  [sq d1 d2: 0.002007]  [num0: 15.000000] [num1 49.000000]
[Epoch 432/500] [Batch 620/676] [D loss: -0.009569] [G loss: -0.117161] [d1 loss: 0.048252] [d2 loss: 0.070256]  [sq d1 d2: 0.000484]  [num0: 13.000000] [num1 51.000000]
[Epoch 432/500] [Batch 640/676] [D loss: -0.001368] [G loss: -0.112510] [d1 loss: 0.018874] [d2 loss: 0.024173]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 432/500] [Batch 660/676] [D loss: 0.000004] [G loss: -0.096374] [d1 loss: 0.047367] [d2 loss: 0.033315]  [sq d1 d2: 0.000197]  [num0: 17.000000] [num1 47.000000]
[Epoch 433/500] [Batch 0/676] [D loss: -0.008963] [G loss: -0.084604] [d1 loss: 0.046050] [d2 loss: 0.060763]  [sq d1 d2: 0.000216]  [num0: 19.000000] [num1 45.000000]
[Epoch 433/500] [Batch 20/676] [D loss: -0.008279] [G loss: -0.045389] [d1 loss: 0.057791] [d2 loss: 0.057546]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 433/500] [Batch 40/676] [D loss: -0.005599] [G loss: -0.004228] [d1 loss: 0.162493] [d2 loss: 0.145863]  [sq d1 d2: 0.000277]  [num0: 19.000000] [num1 45.000000]
[Epoch 433/500] [Batch 60/676] [D loss: -0.025366] [G loss: 0.019113] [d1 loss: 0.066718] [d2 loss: 0.055890]  [sq d1 d2: 0.000117]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 80/676] [D loss: -0.012913] [G loss: 0.005641] [d1 loss: 0.069244] [d2 loss: 0.064731]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]
[Epoch 433/500] [Batch 100/676] [D loss: 0.017564] [G loss: 0.020825] [d1 loss: 0.010191] [d2 loss: 0.008779]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 433/500] [Batch 120/676] [D loss: -0.004190] [G loss: 0.015954] [d1 loss: 0.068036] [d2 loss: 0.061784]  [sq d1 d2: 0.000039]  [num0: 17.000000] [num1 47.000000]
[Epoch 433/500] [Batch 140/676] [D loss: -0.020598] [G loss: 0.018005] [d1 loss: 0.071612] [d2 loss: 0.104349]  [sq d1 d2: 0.001072]  [num0: 14.000000] [num1 50.000000]
[Epoch 433/500] [Batch 160/676] [D loss: 0.019683] [G loss: 0.039556] [d1 loss: 0.051086] [d2 loss: 0.036383]  [sq d1 d2: 0.000216]  [num0: 15.000000] [num1 49.000000]
[Epoch 433/500] [Batch 180/676] [D loss: 0.015088] [G loss: 0.011837] [d1 loss: 0.038322] [d2 loss: 0.045916]  [sq d1 d2: 0.000058]  [num0: 20.000000] [num1 44.000000]
[Epoch 433/500] [Batch 200/676] [D loss: -0.005953] [G loss: 0.011448] [d1 loss: 0.074590] [d2 loss: 0.079309]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 433/500] [Batch 220/676] [D loss: 0.011207] [G loss: -0.004653] [d1 loss: 0.014173] [d2 loss: 0.011195]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 433/500] [Batch 240/676] [D loss: -0.014965] [G loss: -0.040428] [d1 loss: 0.034716] [d2 loss: 0.037896]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 433/500] [Batch 260/676] [D loss: -0.020507] [G loss: -0.138180] [d1 loss: 0.031249] [d2 loss: 0.033524]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 280/676] [D loss: -0.004089] [G loss: -0.146510] [d1 loss: 0.117418] [d2 loss: 0.101886]  [sq d1 d2: 0.000241]  [num0: 13.000000] [num1 51.000000]
[Epoch 433/500] [Batch 300/676] [D loss: -0.005010] [G loss: -0.188272] [d1 loss: 0.038097] [d2 loss: 0.026211]  [sq d1 d2: 0.000141]  [num0: 18.000000] [num1 46.000000]

[Epoch 433/500] [Batch 320/676] [D loss: -0.003104] [G loss: -0.205886] [d1 loss: 0.099066] [d2 loss: 0.142861]  [sq d1 d2: 0.001918]  [num0: 21.000000] [num1 43.000000]
[Epoch 433/500] [Batch 340/676] [D loss: -0.001517] [G loss: -0.239815] [d1 loss: 0.083044] [d2 loss: 0.114205]  [sq d1 d2: 0.000971]  [num0: 15.000000] [num1 49.000000]
[Epoch 433/500] [Batch 360/676] [D loss: 0.009518] [G loss: -0.255010] [d1 loss: 0.010973] [d2 loss: 0.008063]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 433/500] [Batch 380/676] [D loss: -0.006694] [G loss: -0.262241] [d1 loss: 0.033782] [d2 loss: 0.031163]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 400/676] [D loss: -0.040687] [G loss: -0.269497] [d1 loss: 0.492707] [d2 loss: 0.433770]  [sq d1 d2: 0.003474]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 420/676] [D loss: 0.005470] [G loss: -0.246097] [d1 loss: 0.015501] [d2 loss: 0.017280]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 440/676] [D loss: -0.004252] [G loss: -0.211947] [d1 loss: 0.052979] [d2 loss: 0.059470]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 433/500] [Batch 460/676] [D loss: -0.019246] [G loss: -0.180682] [d1 loss: 0.040436] [d2 loss: 0.039170]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 433/500] [Batch 480/676] [D loss: -0.018622] [G loss: -0.155057] [d1 loss: 0.083279] [d2 loss: 0.092947]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 433/500] [Batch 500/676] [D loss: 0.005042] [G loss: -0.141743] [d1 loss: 0.110443] [d2 loss: 0.058193]  [sq d1 d2: 0.002730]  [num0: 15.000000] [num1 49.000000]
[Epoch 433/500] [Batch 520/676] [D loss: -0.001406] [G loss: -0.109331] [d1 loss: 0.047482] [d2 loss: 0.039967]  [sq d1 d2: 0.000056]  [num0: 12.000000] [num1 52.000000]
[Epoch 433/500] [Batch 540/676] [D loss: 0.008144] [G loss: -0.067512] [d1 loss: 0.043349] [d2 loss: 0.039527]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 433/500] [Batch 560/676] [D loss: -0.000922] [G loss: -0.054248] [d1 loss: 0.125019] [d2 loss: 0.097313]  [sq d1 d2: 0.000768]  [num0: 13.000000] [num1 51.000000]
[Epoch 433/500] [Batch 580/676] [D loss: -0.026498] [G loss: -0.029742] [d1 loss: 0.100546] [d2 loss: 0.023245]  [sq d1 d2: 0.005975]  [num0: 18.000000] [num1 46.000000]
[Epoch 433/500] [Batch 600/676] [D loss: -0.018079] [G loss: -0.020170] [d1 loss: 0.071685] [d2 loss: 0.067984]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 433/500] [Batch 620/676] [D loss: -0.001899] [G loss: 0.030579] [d1 loss: 0.664499] [d2 loss: 0.349126]  [sq d1 d2: 0.099460]  [num0: 16.000000] [num1 48.000000]
[Epoch 433/500] [Batch 640/676] [D loss: -0.008394] [G loss: 0.012241] [d1 loss: 0.096377] [d2 loss: 0.105956]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 433/500] [Batch 660/676] [D loss: -0.010948] [G loss: 0.021639] [d1 loss: 0.075838] [d2 loss: 0.087257]  [sq d1 d2: 0.000130]  [num0: 17.000000] [num1 47.000000]
[Epoch 434/500] [Batch 0/676] [D loss: -0.015292] [G loss: 0.012103] [d1 loss: 0.099187] [d2 loss: 0.114466]  [sq d1 d2: 0.000233]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 20/676] [D loss: -0.025069] [G loss: 0.000340] [d1 loss: 0.102557] [d2 loss: 0.106599]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 40/676] [D loss: -0.013934] [G loss: 0.051743] [d1 loss: 0.080111] [d2 loss: 0.074847]  [sq d1 d2: 0.000028]  [num0: 18.000000] [num1 46.000000]
[Epoch 434/500] [Batch 60/676] [D loss: -0.019718] [G loss: 0.026064] [d1 loss: 0.080856] [d2 loss: 0.110717]  [sq d1 d2: 0.000892]  [num0: 21.000000] [num1 43.000000]
[Epoch 434/500] [Batch 80/676] [D loss: 0.005606] [G loss: -0.002972] [d1 loss: 0.074097] [d2 loss: 0.084438]  [sq d1 d2: 0.000107]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 100/676] [D loss: -0.009576] [G loss: 0.001489] [d1 loss: 0.064468] [d2 loss: 0.067284]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 120/676] [D loss: 0.002350] [G loss: 0.002678] [d1 loss: 0.040500] [d2 loss: 0.032562]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 140/676] [D loss: -0.002522] [G loss: 0.006147] [d1 loss: 0.095140] [d2 loss: 0.079887]  [sq d1 d2: 0.000233]  [num0: 15.000000] [num1 49.000000]
[Epoch 434/500] [Batch 160/676] [D loss: -0.001310] [G loss: 0.042399] [d1 loss: 0.064792] [d2 loss: 0.067708]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 434/500] [Batch 180/676] [D loss: -0.010992] [G loss: 0.024922] [d1 loss: 0.024900] [d2 loss: 0.021932]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 434/500] [Batch 200/676] [D loss: -0.009268] [G loss: 0.010528] [d1 loss: 0.090482] [d2 loss: 0.104246]  [sq d1 d2: 0.000189]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 220/676] [D loss: -0.019679] [G loss: 0.009401] [d1 loss: 0.063806] [d2 loss: 0.065010]  [sq d1 d2: 0.000001]  [num0: 9.000000] [num1 55.000000]
[Epoch 434/500] [Batch 240/676] [D loss: -0.009445] [G loss: 0.017707] [d1 loss: 0.070429] [d2 loss: 0.079347]  [sq d1 d2: 0.000080]  [num0: 15.000000] [num1 49.000000]
[Epoch 434/500] [Batch 260/676] [D loss: 0.002935] [G loss: -0.008673] [d1 loss: 0.078071] [d2 loss: 0.087298]  [sq d1 d2: 0.000085]  [num0: 17.000000] [num1 47.000000]
[Epoch 434/500] [Batch 280/676] [D loss: -0.003916] [G loss: -0.007817] [d1 loss: 0.080199] [d2 loss: 0.071534]  [sq d1 d2: 0.000075]  [num0: 18.000000] [num1 46.000000]
[Epoch 434/500] [Batch 300/676] [D loss: -0.031110] [G loss: -0.017891] [d1 loss: 0.046521] [d2 loss: 0.059554]  [sq d1 d2: 0.000170]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 320/676] [D loss: -0.006393] [G loss: -0.025807] [d1 loss: 0.031059] [d2 loss: 0.032942]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 340/676] [D loss: 0.022769] [G loss: -0.044239] [d1 loss: 0.045178] [d2 loss: 0.077862]  [sq d1 d2: 0.001068]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 360/676] [D loss: 0.002581] [G loss: -0.031853] [d1 loss: 0.011436] [d2 loss: 0.010937]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 380/676] [D loss: 0.003014] [G loss: -0.044611] [d1 loss: 0.025071] [d2 loss: 0.030011]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 400/676] [D loss: -0.013032] [G loss: 0.000148] [d1 loss: 0.210520] [d2 loss: 0.170130]  [sq d1 d2: 0.001631]  [num0: 15.000000] [num1 49.000000]
[Epoch 434/500] [Batch 420/676] [D loss: -0.010941] [G loss: -0.005970] [d1 loss: 0.105605] [d2 loss: 0.065608]  [sq d1 d2: 0.001600]  [num0: 12.000000] [num1 52.000000]
[Epoch 434/500] [Batch 440/676] [D loss: -0.006665] [G loss: -0.035755] [d1 loss: 0.053781] [d2 loss: 0.054295]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 460/676] [D loss: -0.011590] [G loss: -0.014644] [d1 loss: 0.072263] [d2 loss: 0.084917]  [sq d1 d2: 0.000160]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 480/676] [D loss: -0.027330] [G loss: 0.000959] [d1 loss: 0.026097] [d2 loss: 0.026667]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 434/500] [Batch 500/676] [D loss: -0.018167] [G loss: 0.029523] [d1 loss: 0.669027] [d2 loss: 0.476695]  [sq d1 d2: 0.036992]  [num0: 18.000000] [num1 46.000000]
[Epoch 434/500] [Batch 520/676] [D loss: -0.031326] [G loss: 0.045481] [d1 loss: 0.040924] [d2 loss: 0.016587]  [sq d1 d2: 0.000592]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 540/676] [D loss: 0.024907] [G loss: 0.043322] [d1 loss: 0.026207] [d2 loss: 0.022792]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 560/676] [D loss: -0.024216] [G loss: 0.075676] [d1 loss: 0.045161] [d2 loss: 0.060671]  [sq d1 d2: 0.000241]  [num0: 13.000000] [num1 51.000000]
[Epoch 434/500] [Batch 580/676] [D loss: -0.018377] [G loss: 0.072602] [d1 loss: 0.125161] [d2 loss: 0.143648]  [sq d1 d2: 0.000342]  [num0: 14.000000] [num1 50.000000]
[Epoch 434/500] [Batch 600/676] [D loss: 0.000420] [G loss: 0.046421] [d1 loss: 0.009626] [d2 loss: 0.011239]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 434/500] [Batch 620/676] [D loss: -0.011366] [G loss: 0.030248] [d1 loss: 0.047412] [d2 loss: 0.042745]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 434/500] [Batch 640/676] [D loss: -0.005538] [G loss: 0.026935] [d1 loss: 0.068988] [d2 loss: 0.063945]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 434/500] [Batch 660/676] [D loss: -0.003470] [G loss: -0.022541] [d1 loss: 0.046585] [d2 loss: 0.055962]  [sq d1 d2: 0.000088]  [num0: 12.000000] [num1 52.000000]

[Epoch 435/500] [Batch 0/676] [D loss: -0.005636] [G loss: -0.061499] [d1 loss: 0.123533] [d2 loss: 0.128223]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 20/676] [D loss: -0.013022] [G loss: -0.116842] [d1 loss: 0.233775] [d2 loss: 0.190936]  [sq d1 d2: 0.001835]  [num0: 16.000000] [num1 48.000000]
[Epoch 435/500] [Batch 40/676] [D loss: -0.013095] [G loss: -0.105672] [d1 loss: 0.047578] [d2 loss: 0.062187]  [sq d1 d2: 0.000213]  [num0: 11.000000] [num1 53.000000]
[Epoch 435/500] [Batch 60/676] [D loss: -0.015112] [G loss: -0.170556] [d1 loss: 0.066878] [d2 loss: 0.060107]  [sq d1 d2: 0.000046]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 80/676] [D loss: -0.017518] [G loss: -0.216394] [d1 loss: 0.027871] [d2 loss: 0.024189]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 435/500] [Batch 100/676] [D loss: -0.026278] [G loss: -0.254380] [d1 loss: 0.032148] [d2 loss: 0.039165]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 435/500] [Batch 120/676] [D loss: 0.003073] [G loss: -0.276440] [d1 loss: 0.069771] [d2 loss: 0.075303]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 140/676] [D loss: 0.009138] [G loss: -0.287735] [d1 loss: 0.041022] [d2 loss: 0.045723]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 160/676] [D loss: -0.014869] [G loss: -0.277460] [d1 loss: 0.145823] [d2 loss: 0.100573]  [sq d1 d2: 0.002048]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 180/676] [D loss: 0.000771] [G loss: -0.291378] [d1 loss: 0.019958] [d2 loss: 0.023176]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 200/676] [D loss: -0.002370] [G loss: -0.240574] [d1 loss: 0.162373] [d2 loss: 0.148883]  [sq d1 d2: 0.000182]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 220/676] [D loss: 0.011288] [G loss: -0.195208] [d1 loss: 0.107444] [d2 loss: 0.182699]  [sq d1 d2: 0.005663]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 240/676] [D loss: -0.001321] [G loss: -0.150002] [d1 loss: 0.042962] [d2 loss: 0.042034]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 260/676] [D loss: -0.016318] [G loss: -0.081450] [d1 loss: 0.064040] [d2 loss: 0.071277]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 280/676] [D loss: -0.002798] [G loss: -0.027681] [d1 loss: 0.066006] [d2 loss: 0.086979]  [sq d1 d2: 0.000440]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 300/676] [D loss: -0.020127] [G loss: 0.022696] [d1 loss: 0.139864] [d2 loss: 0.128766]  [sq d1 d2: 0.000123]  [num0: 16.000000] [num1 48.000000]
[Epoch 435/500] [Batch 320/676] [D loss: -0.026364] [G loss: 0.068767] [d1 loss: 0.074520] [d2 loss: 0.074763]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 340/676] [D loss: -0.022415] [G loss: 0.137642] [d1 loss: 0.031862] [d2 loss: 0.031100]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 435/500] [Batch 360/676] [D loss: -0.034273] [G loss: 0.147645] [d1 loss: 0.094800] [d2 loss: 0.086013]  [sq d1 d2: 0.000077]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 380/676] [D loss: 0.012149] [G loss: 0.209173] [d1 loss: 0.073505] [d2 loss: 0.094957]  [sq d1 d2: 0.000460]  [num0: 19.000000] [num1 45.000000]
[Epoch 435/500] [Batch 400/676] [D loss: -0.014097] [G loss: 0.268368] [d1 loss: 0.026728] [d2 loss: 0.039334]  [sq d1 d2: 0.000159]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 420/676] [D loss: -0.016269] [G loss: 0.253306] [d1 loss: 0.057773] [d2 loss: 0.050823]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 440/676] [D loss: 0.001517] [G loss: 0.220348] [d1 loss: 0.030815] [d2 loss: 0.090458]  [sq d1 d2: 0.003557]  [num0: 13.000000] [num1 51.000000]
[Epoch 435/500] [Batch 460/676] [D loss: -0.009756] [G loss: 0.126450] [d1 loss: 0.071427] [d2 loss: 0.083896]  [sq d1 d2: 0.000155]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 480/676] [D loss: -0.004275] [G loss: 0.090585] [d1 loss: 0.047533] [d2 loss: 0.044945]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 500/676] [D loss: -0.003695] [G loss: 0.042869] [d1 loss: 0.015059] [d2 loss: 0.014641]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 435/500] [Batch 520/676] [D loss: -0.004430] [G loss: 0.031840] [d1 loss: 0.084805] [d2 loss: 0.087190]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 435/500] [Batch 540/676] [D loss: -0.006688] [G loss: -0.033850] [d1 loss: 0.084966] [d2 loss: 0.094160]  [sq d1 d2: 0.000085]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 560/676] [D loss: -0.013179] [G loss: -0.084116] [d1 loss: 0.112295] [d2 loss: 0.097024]  [sq d1 d2: 0.000233]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 580/676] [D loss: -0.027203] [G loss: -0.132994] [d1 loss: 0.087289] [d2 loss: 0.086628]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 435/500] [Batch 600/676] [D loss: -0.007086] [G loss: -0.232270] [d1 loss: 0.025688] [d2 loss: 0.040459]  [sq d1 d2: 0.000218]  [num0: 18.000000] [num1 46.000000]
[Epoch 435/500] [Batch 620/676] [D loss: -0.000118] [G loss: -0.257591] [d1 loss: 0.036082] [d2 loss: 0.050629]  [sq d1 d2: 0.000212]  [num0: 14.000000] [num1 50.000000]
[Epoch 435/500] [Batch 640/676] [D loss: 0.005830] [G loss: -0.321535] [d1 loss: 0.025775] [d2 loss: 0.029759]  [sq d1 d2: 0.000016]  [num0: 15.000000] [num1 49.000000]
[Epoch 435/500] [Batch 660/676] [D loss: -0.004873] [G loss: -0.324674] [d1 loss: 0.132626] [d2 loss: 0.137232]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 436/500] [Batch 0/676] [D loss: -0.012233] [G loss: -0.323708] [d1 loss: 0.074970] [d2 loss: 0.062382]  [sq d1 d2: 0.000158]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 20/676] [D loss: -0.014373] [G loss: -0.314418] [d1 loss: 0.035275] [d2 loss: 0.045839]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 40/676] [D loss: 0.021584] [G loss: -0.244458] [d1 loss: 0.242872] [d2 loss: 0.265874]  [sq d1 d2: 0.000529]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 60/676] [D loss: 0.002449] [G loss: -0.222303] [d1 loss: 0.055238] [d2 loss: 0.121140]  [sq d1 d2: 0.004343]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 80/676] [D loss: 0.010177] [G loss: -0.144279] [d1 loss: 0.044867] [d2 loss: 0.050354]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 436/500] [Batch 100/676] [D loss: -0.004728] [G loss: -0.049522] [d1 loss: 0.116131] [d2 loss: 0.101712]  [sq d1 d2: 0.000208]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 120/676] [D loss: -0.001490] [G loss: -0.007927] [d1 loss: 0.073355] [d2 loss: 0.109330]  [sq d1 d2: 0.001294]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 140/676] [D loss: -0.007593] [G loss: 0.056346] [d1 loss: 0.100425] [d2 loss: 0.149352]  [sq d1 d2: 0.002394]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 160/676] [D loss: -0.030498] [G loss: 0.150552] [d1 loss: 0.139857] [d2 loss: 0.123350]  [sq d1 d2: 0.000272]  [num0: 18.000000] [num1 46.000000]
[Epoch 436/500] [Batch 180/676] [D loss: -0.038903] [G loss: 0.220357] [d1 loss: 0.032702] [d2 loss: 0.048020]  [sq d1 d2: 0.000235]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 200/676] [D loss: -0.025676] [G loss: 0.232054] [d1 loss: 0.020933] [d2 loss: 0.018959]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 220/676] [D loss: -0.035578] [G loss: 0.232092] [d1 loss: 0.078591] [d2 loss: 0.082886]  [sq d1 d2: 0.000018]  [num0: 19.000000] [num1 45.000000]
[Epoch 436/500] [Batch 240/676] [D loss: -0.007215] [G loss: 0.259055] [d1 loss: 0.144452] [d2 loss: 0.127746]  [sq d1 d2: 0.000279]  [num0: 17.000000] [num1 47.000000]
[Epoch 436/500] [Batch 260/676] [D loss: -0.010292] [G loss: 0.204636] [d1 loss: 0.042995] [d2 loss: 0.043722]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 436/500] [Batch 280/676] [D loss: 0.008762] [G loss: 0.156141] [d1 loss: 0.042780] [d2 loss: 0.047464]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 436/500] [Batch 300/676] [D loss: 0.025942] [G loss: 0.178923] [d1 loss: 0.044528] [d2 loss: 0.045192]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 436/500] [Batch 320/676] [D loss: 0.000140] [G loss: 0.086355] [d1 loss: 0.048294] [d2 loss: 0.053154]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 436/500] [Batch 340/676] [D loss: 0.006130] [G loss: 0.047371] [d1 loss: 0.013499] [d2 loss: 0.013451]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]

[Epoch 436/500] [Batch 360/676] [D loss: 0.000345] [G loss: -0.044489] [d1 loss: 0.107281] [d2 loss: 0.141553]  [sq d1 d2: 0.001175]  [num0: 17.000000] [num1 47.000000]
[Epoch 436/500] [Batch 380/676] [D loss: -0.006797] [G loss: -0.098232] [d1 loss: 0.047732] [d2 loss: 0.058615]  [sq d1 d2: 0.000118]  [num0: 20.000000] [num1 44.000000]
[Epoch 436/500] [Batch 400/676] [D loss: -0.009040] [G loss: -0.164699] [d1 loss: 0.059613] [d2 loss: 0.084717]  [sq d1 d2: 0.000630]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 420/676] [D loss: -0.008591] [G loss: -0.272688] [d1 loss: 0.078955] [d2 loss: 0.126217]  [sq d1 d2: 0.002234]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 440/676] [D loss: -0.035547] [G loss: -0.384728] [d1 loss: 0.042384] [d2 loss: 0.050406]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 436/500] [Batch 460/676] [D loss: -0.025777] [G loss: -0.458777] [d1 loss: 0.046544] [d2 loss: 0.024946]  [sq d1 d2: 0.000466]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 480/676] [D loss: -0.014563] [G loss: -0.508198] [d1 loss: 0.073395] [d2 loss: 0.070877]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 500/676] [D loss: -0.019681] [G loss: -0.551376] [d1 loss: 0.049175] [d2 loss: 0.048198]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 436/500] [Batch 520/676] [D loss: 0.002017] [G loss: -0.510672] [d1 loss: 0.054452] [d2 loss: 0.033701]  [sq d1 d2: 0.000431]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 540/676] [D loss: -0.018490] [G loss: -0.462244] [d1 loss: 0.044743] [d2 loss: 0.047505]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 436/500] [Batch 560/676] [D loss: 0.003675] [G loss: -0.386774] [d1 loss: 0.030178] [d2 loss: 0.045519]  [sq d1 d2: 0.000235]  [num0: 17.000000] [num1 47.000000]
[Epoch 436/500] [Batch 580/676] [D loss: 0.008314] [G loss: -0.288175] [d1 loss: 0.036986] [d2 loss: 0.040865]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 600/676] [D loss: -0.002404] [G loss: -0.227085] [d1 loss: 0.093316] [d2 loss: 0.062604]  [sq d1 d2: 0.000943]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 620/676] [D loss: -0.000877] [G loss: -0.151531] [d1 loss: 0.089342] [d2 loss: 0.083042]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 436/500] [Batch 640/676] [D loss: -0.000922] [G loss: -0.074926] [d1 loss: 0.087098] [d2 loss: 0.098712]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 436/500] [Batch 660/676] [D loss: -0.003237] [G loss: -0.004292] [d1 loss: 0.067481] [d2 loss: 0.092871]  [sq d1 d2: 0.000645]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 0/676] [D loss: -0.013714] [G loss: 0.051994] [d1 loss: 0.129008] [d2 loss: 0.149128]  [sq d1 d2: 0.000405]  [num0: 12.000000] [num1 52.000000]
[Epoch 437/500] [Batch 20/676] [D loss: -0.018371] [G loss: 0.134539] [d1 loss: 0.060741] [d2 loss: 0.058159]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 437/500] [Batch 40/676] [D loss: -0.020282] [G loss: 0.149322] [d1 loss: 0.078714] [d2 loss: 0.067119]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 60/676] [D loss: -0.037539] [G loss: 0.166503] [d1 loss: 0.031843] [d2 loss: 0.040482]  [sq d1 d2: 0.000075]  [num0: 12.000000] [num1 52.000000]
[Epoch 437/500] [Batch 80/676] [D loss: -0.034761] [G loss: 0.204434] [d1 loss: 0.081509] [d2 loss: 0.091509]  [sq d1 d2: 0.000100]  [num0: 19.000000] [num1 45.000000]
[Epoch 437/500] [Batch 100/676] [D loss: 0.010075] [G loss: 0.214238] [d1 loss: 0.152650] [d2 loss: 0.139814]  [sq d1 d2: 0.000165]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 120/676] [D loss: -0.011113] [G loss: 0.194160] [d1 loss: 0.098967] [d2 loss: 0.093207]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 437/500] [Batch 140/676] [D loss: -0.011406] [G loss: 0.143745] [d1 loss: 0.075683] [d2 loss: 0.082750]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 160/676] [D loss: 0.007944] [G loss: 0.133830] [d1 loss: 0.036601] [d2 loss: 0.059940]  [sq d1 d2: 0.000545]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 180/676] [D loss: 0.001323] [G loss: 0.077313] [d1 loss: 0.114422] [d2 loss: 0.113104]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 200/676] [D loss: -0.004796] [G loss: 0.066804] [d1 loss: 0.080184] [d2 loss: 0.078654]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 220/676] [D loss: -0.008030] [G loss: 0.034124] [d1 loss: 0.063412] [d2 loss: 0.065977]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 437/500] [Batch 240/676] [D loss: -0.009054] [G loss: 0.010924] [d1 loss: 0.022101] [d2 loss: 0.026648]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 260/676] [D loss: -0.016005] [G loss: 0.000732] [d1 loss: 0.117122] [d2 loss: 0.069203]  [sq d1 d2: 0.002296]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 280/676] [D loss: -0.013924] [G loss: -0.050743] [d1 loss: 0.008334] [d2 loss: 0.009161]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 300/676] [D loss: -0.021743] [G loss: -0.103413] [d1 loss: 0.038749] [d2 loss: 0.035597]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 320/676] [D loss: -0.018816] [G loss: -0.135745] [d1 loss: 0.036973] [d2 loss: 0.038408]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 437/500] [Batch 340/676] [D loss: -0.012496] [G loss: -0.198082] [d1 loss: 0.015977] [d2 loss: 0.019727]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 360/676] [D loss: 0.000632] [G loss: -0.200274] [d1 loss: 0.016616] [d2 loss: 0.008278]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 380/676] [D loss: 0.008199] [G loss: -0.232313] [d1 loss: 0.129822] [d2 loss: 0.100028]  [sq d1 d2: 0.000888]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 400/676] [D loss: -0.004357] [G loss: -0.235611] [d1 loss: 0.033920] [d2 loss: 0.030976]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 437/500] [Batch 420/676] [D loss: 0.008060] [G loss: -0.177384] [d1 loss: 0.044565] [d2 loss: 0.067712]  [sq d1 d2: 0.000536]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 440/676] [D loss: 0.011609] [G loss: -0.074987] [d1 loss: 0.040081] [d2 loss: 0.041363]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 460/676] [D loss: 0.004861] [G loss: -0.017904] [d1 loss: 0.103709] [d2 loss: 0.094582]  [sq d1 d2: 0.000083]  [num0: 15.000000] [num1 49.000000]
[Epoch 437/500] [Batch 480/676] [D loss: -0.002173] [G loss: 0.042999] [d1 loss: 0.062116] [d2 loss: 0.055109]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 500/676] [D loss: -0.010650] [G loss: 0.073528] [d1 loss: 0.031516] [d2 loss: 0.027915]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 437/500] [Batch 520/676] [D loss: -0.009014] [G loss: 0.143726] [d1 loss: 0.059295] [d2 loss: 0.061658]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 540/676] [D loss: -0.040896] [G loss: 0.223806] [d1 loss: 0.033408] [d2 loss: 0.036045]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 437/500] [Batch 560/676] [D loss: -0.022822] [G loss: 0.296191] [d1 loss: 0.008546] [d2 loss: 0.007933]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 580/676] [D loss: -0.022170] [G loss: 0.406167] [d1 loss: 0.039117] [d2 loss: 0.065899]  [sq d1 d2: 0.000717]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 600/676] [D loss: -0.009049] [G loss: 0.386448] [d1 loss: 0.030318] [d2 loss: 0.030783]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 437/500] [Batch 620/676] [D loss: -0.003163] [G loss: 0.379074] [d1 loss: 0.045203] [d2 loss: 0.056928]  [sq d1 d2: 0.000137]  [num0: 16.000000] [num1 48.000000]
[Epoch 437/500] [Batch 640/676] [D loss: 0.019608] [G loss: 0.329979] [d1 loss: 0.024008] [d2 loss: 0.021813]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 437/500] [Batch 660/676] [D loss: 0.008236] [G loss: 0.264605] [d1 loss: 0.075668] [d2 loss: 0.085297]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 0/676] [D loss: 0.030129] [G loss: 0.210938] [d1 loss: 0.147631] [d2 loss: 0.173461]  [sq d1 d2: 0.000667]  [num0: 15.000000] [num1 49.000000]

[Epoch 438/500] [Batch 20/676] [D loss: -0.000844] [G loss: 0.117345] [d1 loss: 0.050859] [d2 loss: 0.055771]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 40/676] [D loss: -0.007471] [G loss: 0.021023] [d1 loss: 0.034260] [d2 loss: 0.041858]  [sq d1 d2: 0.000058]  [num0: 19.000000] [num1 45.000000]
[Epoch 438/500] [Batch 60/676] [D loss: -0.008672] [G loss: -0.037582] [d1 loss: 0.034188] [d2 loss: 0.037484]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 80/676] [D loss: -0.025265] [G loss: -0.066133] [d1 loss: 0.652407] [d2 loss: 0.352290]  [sq d1 d2: 0.090070]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 100/676] [D loss: -0.015184] [G loss: -0.153057] [d1 loss: 0.197490] [d2 loss: 0.166003]  [sq d1 d2: 0.000991]  [num0: 12.000000] [num1 52.000000]
[Epoch 438/500] [Batch 120/676] [D loss: -0.022635] [G loss: -0.238895] [d1 loss: 0.057589] [d2 loss: 0.065962]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 140/676] [D loss: -0.006262] [G loss: -0.271920] [d1 loss: 0.140693] [d2 loss: 0.133423]  [sq d1 d2: 0.000053]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 160/676] [D loss: -0.005796] [G loss: -0.285261] [d1 loss: 0.032420] [d2 loss: 0.033143]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 438/500] [Batch 180/676] [D loss: 0.007778] [G loss: -0.247159] [d1 loss: 0.055905] [d2 loss: 0.069679]  [sq d1 d2: 0.000190]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 200/676] [D loss: 0.043587] [G loss: -0.247105] [d1 loss: 0.026662] [d2 loss: 0.030460]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 438/500] [Batch 220/676] [D loss: 0.005155] [G loss: -0.236956] [d1 loss: 0.135265] [d2 loss: 0.129871]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 240/676] [D loss: 0.008352] [G loss: -0.104565] [d1 loss: 0.063221] [d2 loss: 0.067057]  [sq d1 d2: 0.000015]  [num0: 18.000000] [num1 46.000000]
[Epoch 438/500] [Batch 260/676] [D loss: 0.004028] [G loss: -0.042687] [d1 loss: 0.128343] [d2 loss: 0.141859]  [sq d1 d2: 0.000183]  [num0: 13.000000] [num1 51.000000]
[Epoch 438/500] [Batch 280/676] [D loss: -0.007454] [G loss: -0.023365] [d1 loss: 0.076102] [d2 loss: 0.062609]  [sq d1 d2: 0.000182]  [num0: 14.000000] [num1 50.000000]
[Epoch 438/500] [Batch 300/676] [D loss: -0.018398] [G loss: 0.050083] [d1 loss: 0.054297] [d2 loss: 0.057498]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 320/676] [D loss: -0.028590] [G loss: 0.110497] [d1 loss: 0.056658] [d2 loss: 0.060137]  [sq d1 d2: 0.000012]  [num0: 19.000000] [num1 45.000000]
[Epoch 438/500] [Batch 340/676] [D loss: -0.016727] [G loss: 0.212248] [d1 loss: 0.083028] [d2 loss: 0.094400]  [sq d1 d2: 0.000129]  [num0: 19.000000] [num1 45.000000]
[Epoch 438/500] [Batch 360/676] [D loss: -0.049837] [G loss: 0.232665] [d1 loss: 0.062048] [d2 loss: 0.068406]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 438/500] [Batch 380/676] [D loss: -0.019273] [G loss: 0.268313] [d1 loss: 0.062322] [d2 loss: 0.072703]  [sq d1 d2: 0.000108]  [num0: 15.000000] [num1 49.000000]
[Epoch 438/500] [Batch 400/676] [D loss: 0.020737] [G loss: 0.289674] [d1 loss: 0.032949] [d2 loss: 0.020326]  [sq d1 d2: 0.000159]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 420/676] [D loss: -0.023073] [G loss: 0.193856] [d1 loss: 0.146736] [d2 loss: 0.156670]  [sq d1 d2: 0.000099]  [num0: 19.000000] [num1 45.000000]
[Epoch 438/500] [Batch 440/676] [D loss: -0.002132] [G loss: 0.191795] [d1 loss: 0.077698] [d2 loss: 0.084700]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 438/500] [Batch 460/676] [D loss: 0.010138] [G loss: 0.062154] [d1 loss: 0.059472] [d2 loss: 0.055809]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 438/500] [Batch 480/676] [D loss: 0.010488] [G loss: 0.006219] [d1 loss: 0.092767] [d2 loss: 0.079999]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 500/676] [D loss: -0.001493] [G loss: -0.028790] [d1 loss: 0.087695] [d2 loss: 0.091726]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 438/500] [Batch 520/676] [D loss: -0.006430] [G loss: -0.094249] [d1 loss: 0.040091] [d2 loss: 0.038993]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 540/676] [D loss: -0.019075] [G loss: -0.176873] [d1 loss: 0.120170] [d2 loss: 0.122271]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 438/500] [Batch 560/676] [D loss: -0.052776] [G loss: -0.295268] [d1 loss: 0.062644] [d2 loss: 0.105327]  [sq d1 d2: 0.001822]  [num0: 15.000000] [num1 49.000000]
[Epoch 438/500] [Batch 580/676] [D loss: -0.025620] [G loss: -0.385521] [d1 loss: 0.052108] [d2 loss: 0.041196]  [sq d1 d2: 0.000119]  [num0: 15.000000] [num1 49.000000]
[Epoch 438/500] [Batch 600/676] [D loss: -0.024085] [G loss: -0.408252] [d1 loss: 0.036399] [d2 loss: 0.028044]  [sq d1 d2: 0.000070]  [num0: 11.000000] [num1 53.000000]
[Epoch 438/500] [Batch 620/676] [D loss: -0.063529] [G loss: -0.415167] [d1 loss: 0.066279] [d2 loss: 0.062941]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 438/500] [Batch 640/676] [D loss: 0.015466] [G loss: -0.399227] [d1 loss: 0.123093] [d2 loss: 0.120340]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 438/500] [Batch 660/676] [D loss: 0.036887] [G loss: -0.371964] [d1 loss: 0.110093] [d2 loss: 0.063898]  [sq d1 d2: 0.002134]  [num0: 21.000000] [num1 43.000000]
[Epoch 439/500] [Batch 0/676] [D loss: 0.029329] [G loss: -0.320082] [d1 loss: 0.052810] [d2 loss: 0.048691]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 20/676] [D loss: -0.009430] [G loss: -0.239215] [d1 loss: 0.034511] [d2 loss: 0.036808]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 40/676] [D loss: 0.011102] [G loss: -0.158285] [d1 loss: 0.056324] [d2 loss: 0.056958]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 439/500] [Batch 60/676] [D loss: 0.001614] [G loss: -0.079633] [d1 loss: 0.033073] [d2 loss: 0.038838]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 439/500] [Batch 80/676] [D loss: -0.006241] [G loss: -0.019975] [d1 loss: 0.074542] [d2 loss: 0.065073]  [sq d1 d2: 0.000090]  [num0: 18.000000] [num1 46.000000]
[Epoch 439/500] [Batch 100/676] [D loss: -0.010117] [G loss: 0.048720] [d1 loss: 0.055214] [d2 loss: 0.073623]  [sq d1 d2: 0.000339]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 120/676] [D loss: -0.025498] [G loss: 0.134520] [d1 loss: 0.045761] [d2 loss: 0.035344]  [sq d1 d2: 0.000109]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 140/676] [D loss: -0.041533] [G loss: 0.247586] [d1 loss: 0.008856] [d2 loss: 0.007758]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 160/676] [D loss: -0.049619] [G loss: 0.314559] [d1 loss: 0.047749] [d2 loss: 0.047077]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 180/676] [D loss: -0.012224] [G loss: 0.370602] [d1 loss: 0.060206] [d2 loss: 0.055733]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 200/676] [D loss: -0.054597] [G loss: 0.369444] [d1 loss: 0.217646] [d2 loss: 0.220852]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 220/676] [D loss: -0.029531] [G loss: 0.416945] [d1 loss: 0.060044] [d2 loss: 0.060930]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 240/676] [D loss: 0.014338] [G loss: 0.316425] [d1 loss: 0.081385] [d2 loss: 0.104439]  [sq d1 d2: 0.000531]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 260/676] [D loss: 0.070530] [G loss: 0.289795] [d1 loss: 0.086685] [d2 loss: 0.081876]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 439/500] [Batch 280/676] [D loss: 0.015523] [G loss: 0.191485] [d1 loss: 0.128084] [d2 loss: 0.122497]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 439/500] [Batch 300/676] [D loss: 0.013601] [G loss: 0.111291] [d1 loss: 0.086093] [d2 loss: 0.073575]  [sq d1 d2: 0.000157]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 320/676] [D loss: 0.001806] [G loss: 0.053497] [d1 loss: 0.041137] [d2 loss: 0.041135]  [sq d1 d2: 0.000000]  [num0: 11.000000] [num1 53.000000]
[Epoch 439/500] [Batch 340/676] [D loss: -0.002916] [G loss: -0.004973] [d1 loss: 0.078766] [d2 loss: 0.068026]  [sq d1 d2: 0.000115]  [num0: 18.000000] [num1 46.000000]
[Epoch 439/500] [Batch 360/676] [D loss: -0.021979] [G loss: -0.070745] [d1 loss: 0.038714] [d2 loss: 0.060981]  [sq d1 d2: 0.000496]  [num0: 20.000000] [num1 44.000000]

[Epoch 439/500] [Batch 380/676] [D loss: -0.055985] [G loss: -0.164808] [d1 loss: 0.053753] [d2 loss: 0.069552]  [sq d1 d2: 0.000250]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 400/676] [D loss: -0.035614] [G loss: -0.216052] [d1 loss: 0.043612] [d2 loss: 0.038304]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 420/676] [D loss: -0.038742] [G loss: -0.282044] [d1 loss: 0.050613] [d2 loss: 0.047128]  [sq d1 d2: 0.000012]  [num0: 13.000000] [num1 51.000000]
[Epoch 439/500] [Batch 440/676] [D loss: 0.001727] [G loss: -0.336864] [d1 loss: 0.014190] [d2 loss: 0.012890]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 460/676] [D loss: -0.091574] [G loss: -0.404763] [d1 loss: 0.099630] [d2 loss: 0.126158]  [sq d1 d2: 0.000704]  [num0: 13.000000] [num1 51.000000]
[Epoch 439/500] [Batch 480/676] [D loss: -0.029877] [G loss: -0.342413] [d1 loss: 0.038385] [d2 loss: 0.046271]  [sq d1 d2: 0.000062]  [num0: 18.000000] [num1 46.000000]
[Epoch 439/500] [Batch 500/676] [D loss: 0.023011] [G loss: -0.275685] [d1 loss: 0.126132] [d2 loss: 0.127364]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 520/676] [D loss: 0.026400] [G loss: -0.212260] [d1 loss: 0.043187] [d2 loss: 0.066187]  [sq d1 d2: 0.000529]  [num0: 17.000000] [num1 47.000000]
[Epoch 439/500] [Batch 540/676] [D loss: 0.017235] [G loss: -0.125583] [d1 loss: 0.107822] [d2 loss: 0.154749]  [sq d1 d2: 0.002202]  [num0: 16.000000] [num1 48.000000]
[Epoch 439/500] [Batch 560/676] [D loss: 0.008320] [G loss: -0.055818] [d1 loss: 0.110313] [d2 loss: 0.111906]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 439/500] [Batch 580/676] [D loss: -0.003857] [G loss: -0.007660] [d1 loss: 0.151784] [d2 loss: 0.162872]  [sq d1 d2: 0.000123]  [num0: 20.000000] [num1 44.000000]
[Epoch 439/500] [Batch 600/676] [D loss: -0.008433] [G loss: 0.042092] [d1 loss: 0.046259] [d2 loss: 0.050225]  [sq d1 d2: 0.000016]  [num0: 21.000000] [num1 43.000000]
[Epoch 439/500] [Batch 620/676] [D loss: -0.048364] [G loss: 0.092411] [d1 loss: 0.042500] [d2 loss: 0.027759]  [sq d1 d2: 0.000217]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 640/676] [D loss: -0.037645] [G loss: 0.157933] [d1 loss: 0.013735] [d2 loss: 0.013742]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 439/500] [Batch 660/676] [D loss: -0.062906] [G loss: 0.269194] [d1 loss: 0.075773] [d2 loss: 0.083590]  [sq d1 d2: 0.000061]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 0/676] [D loss: -0.050891] [G loss: 0.317459] [d1 loss: 0.063318] [d2 loss: 0.051060]  [sq d1 d2: 0.000150]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 20/676] [D loss: -0.013175] [G loss: 0.413276] [d1 loss: 0.026049] [d2 loss: 0.046173]  [sq d1 d2: 0.000405]  [num0: 14.000000] [num1 50.000000]
[Epoch 440/500] [Batch 40/676] [D loss: 0.001620] [G loss: 0.316910] [d1 loss: 0.039118] [d2 loss: 0.049017]  [sq d1 d2: 0.000098]  [num0: 20.000000] [num1 44.000000]
[Epoch 440/500] [Batch 60/676] [D loss: 0.028729] [G loss: 0.286073] [d1 loss: 0.126589] [d2 loss: 0.136681]  [sq d1 d2: 0.000102]  [num0: 18.000000] [num1 46.000000]
[Epoch 440/500] [Batch 80/676] [D loss: 0.031235] [G loss: 0.207874] [d1 loss: 0.067662] [d2 loss: 0.071057]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 440/500] [Batch 100/676] [D loss: 0.029973] [G loss: 0.119653] [d1 loss: 0.109493] [d2 loss: 0.104771]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 440/500] [Batch 120/676] [D loss: 0.012061] [G loss: 0.047526] [d1 loss: 0.104577] [d2 loss: 0.136298]  [sq d1 d2: 0.001006]  [num0: 14.000000] [num1 50.000000]
[Epoch 440/500] [Batch 140/676] [D loss: 0.003987] [G loss: -0.041857] [d1 loss: 0.034295] [d2 loss: 0.057889]  [sq d1 d2: 0.000557]  [num0: 16.000000] [num1 48.000000]
[Epoch 440/500] [Batch 160/676] [D loss: -0.016817] [G loss: -0.109025] [d1 loss: 0.053413] [d2 loss: 0.058453]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 180/676] [D loss: -0.036924] [G loss: -0.226676] [d1 loss: 0.096656] [d2 loss: 0.082663]  [sq d1 d2: 0.000196]  [num0: 18.000000] [num1 46.000000]
[Epoch 440/500] [Batch 200/676] [D loss: -0.039381] [G loss: -0.307599] [d1 loss: 0.095953] [d2 loss: 0.080318]  [sq d1 d2: 0.000244]  [num0: 15.000000] [num1 49.000000]
[Epoch 440/500] [Batch 220/676] [D loss: -0.029192] [G loss: -0.434261] [d1 loss: 0.133046] [d2 loss: 0.117299]  [sq d1 d2: 0.000248]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 240/676] [D loss: -0.035461] [G loss: -0.518849] [d1 loss: 0.036031] [d2 loss: 0.035031]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 260/676] [D loss: -0.002136] [G loss: -0.620744] [d1 loss: 0.094292] [d2 loss: 0.087393]  [sq d1 d2: 0.000048]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 280/676] [D loss: -0.021178] [G loss: -0.666308] [d1 loss: 0.045356] [d2 loss: 0.034814]  [sq d1 d2: 0.000111]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 300/676] [D loss: -0.017726] [G loss: -0.609177] [d1 loss: 0.061873] [d2 loss: 0.068283]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 320/676] [D loss: 0.026859] [G loss: -0.487177] [d1 loss: 0.098781] [d2 loss: 0.119746]  [sq d1 d2: 0.000440]  [num0: 15.000000] [num1 49.000000]
[Epoch 440/500] [Batch 340/676] [D loss: -0.011572] [G loss: -0.324472] [d1 loss: 0.054171] [d2 loss: 0.059593]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 440/500] [Batch 360/676] [D loss: 0.024949] [G loss: -0.205239] [d1 loss: 0.058726] [d2 loss: 0.046082]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 440/500] [Batch 380/676] [D loss: 0.011127] [G loss: -0.118903] [d1 loss: 0.036125] [d2 loss: 0.032908]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 440/500] [Batch 400/676] [D loss: -0.004972] [G loss: -0.024836] [d1 loss: 0.039492] [d2 loss: 0.055647]  [sq d1 d2: 0.000261]  [num0: 11.000000] [num1 53.000000]
[Epoch 440/500] [Batch 420/676] [D loss: -0.008834] [G loss: 0.065818] [d1 loss: 0.073077] [d2 loss: 0.085935]  [sq d1 d2: 0.000165]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 440/676] [D loss: -0.019828] [G loss: 0.149285] [d1 loss: 0.025046] [d2 loss: 0.026537]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 440/500] [Batch 460/676] [D loss: -0.054794] [G loss: 0.275685] [d1 loss: 0.152646] [d2 loss: 0.099144]  [sq d1 d2: 0.002862]  [num0: 14.000000] [num1 50.000000]
[Epoch 440/500] [Batch 480/676] [D loss: -0.034981] [G loss: 0.409208] [d1 loss: 0.019687] [d2 loss: 0.020202]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 440/500] [Batch 500/676] [D loss: -0.062235] [G loss: 0.487348] [d1 loss: 0.081304] [d2 loss: 0.100793]  [sq d1 d2: 0.000380]  [num0: 13.000000] [num1 51.000000]
[Epoch 440/500] [Batch 520/676] [D loss: -0.064951] [G loss: 0.537739] [d1 loss: 0.065382] [d2 loss: 0.063173]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 540/676] [D loss: -0.002457] [G loss: 0.555741] [d1 loss: 0.035477] [d2 loss: 0.028645]  [sq d1 d2: 0.000047]  [num0: 20.000000] [num1 44.000000]
[Epoch 440/500] [Batch 560/676] [D loss: -0.001351] [G loss: 0.544128] [d1 loss: 0.067814] [d2 loss: 0.064789]  [sq d1 d2: 0.000009]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 580/676] [D loss: -0.006572] [G loss: 0.482886] [d1 loss: 0.086161] [d2 loss: 0.073406]  [sq d1 d2: 0.000163]  [num0: 17.000000] [num1 47.000000]
[Epoch 440/500] [Batch 600/676] [D loss: 0.057714] [G loss: 0.329920] [d1 loss: 0.103343] [d2 loss: 0.105082]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 440/500] [Batch 620/676] [D loss: 0.035833] [G loss: 0.203039] [d1 loss: 0.091542] [d2 loss: 0.072741]  [sq d1 d2: 0.000353]  [num0: 19.000000] [num1 45.000000]
[Epoch 440/500] [Batch 640/676] [D loss: 0.010728] [G loss: 0.129854] [d1 loss: 0.042736] [d2 loss: 0.061260]  [sq d1 d2: 0.000343]  [num0: 16.000000] [num1 48.000000]
[Epoch 440/500] [Batch 660/676] [D loss: 0.000086] [G loss: 0.064713] [d1 loss: 0.045046] [d2 loss: 0.043101]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 0/676] [D loss: 0.000559] [G loss: 0.040832] [d1 loss: 0.056920] [d2 loss: 0.067192]  [sq d1 d2: 0.000106]  [num0: 14.000000] [num1 50.000000]
[Epoch 441/500] [Batch 20/676] [D loss: -0.013011] [G loss: -0.000822] [d1 loss: 0.054062] [d2 loss: 0.048087]  [sq d1 d2: 0.000036]  [num0: 11.000000] [num1 53.000000]
[Epoch 441/500] [Batch 40/676] [D loss: -0.022795] [G loss: -0.066728] [d1 loss: 0.081755] [d2 loss: 0.066889]  [sq d1 d2: 0.000221]  [num0: 17.000000] [num1 47.000000]

[Epoch 441/500] [Batch 60/676] [D loss: -0.020489] [G loss: -0.103622] [d1 loss: 0.028877] [d2 loss: 0.029609]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 80/676] [D loss: -0.055664] [G loss: -0.204722] [d1 loss: 0.041665] [d2 loss: 0.036316]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 441/500] [Batch 100/676] [D loss: -0.042846] [G loss: -0.245332] [d1 loss: 0.084556] [d2 loss: 0.036144]  [sq d1 d2: 0.002344]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 120/676] [D loss: -0.075985] [G loss: -0.271599] [d1 loss: 0.025289] [d2 loss: 0.024777]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 140/676] [D loss: -0.071758] [G loss: -0.341238] [d1 loss: 0.075832] [d2 loss: 0.098235]  [sq d1 d2: 0.000502]  [num0: 13.000000] [num1 51.000000]
[Epoch 441/500] [Batch 160/676] [D loss: -0.018696] [G loss: -0.378651] [d1 loss: 0.012712] [d2 loss: 0.014079]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 441/500] [Batch 180/676] [D loss: 0.026504] [G loss: -0.422893] [d1 loss: 0.045797] [d2 loss: 0.048386]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 200/676] [D loss: 0.064448] [G loss: -0.410629] [d1 loss: 0.095279] [d2 loss: 0.071436]  [sq d1 d2: 0.000568]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 220/676] [D loss: 0.007160] [G loss: -0.349805] [d1 loss: 0.069594] [d2 loss: 0.070470]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 240/676] [D loss: 0.005041] [G loss: -0.246079] [d1 loss: 0.185848] [d2 loss: 0.164412]  [sq d1 d2: 0.000460]  [num0: 18.000000] [num1 46.000000]
[Epoch 441/500] [Batch 260/676] [D loss: 0.002734] [G loss: -0.111732] [d1 loss: 0.088968] [d2 loss: 0.064359]  [sq d1 d2: 0.000606]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 280/676] [D loss: -0.002266] [G loss: -0.037735] [d1 loss: 0.035437] [d2 loss: 0.043427]  [sq d1 d2: 0.000064]  [num0: 21.000000] [num1 43.000000]
[Epoch 441/500] [Batch 300/676] [D loss: -0.014173] [G loss: 0.037548] [d1 loss: 0.219816] [d2 loss: 0.130329]  [sq d1 d2: 0.008008]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 320/676] [D loss: -0.012935] [G loss: 0.135497] [d1 loss: 0.061489] [d2 loss: 0.103266]  [sq d1 d2: 0.001745]  [num0: 18.000000] [num1 46.000000]
[Epoch 441/500] [Batch 340/676] [D loss: -0.025506] [G loss: 0.282036] [d1 loss: 0.041205] [d2 loss: 0.040977]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 441/500] [Batch 360/676] [D loss: -0.027693] [G loss: 0.333771] [d1 loss: 0.059620] [d2 loss: 0.059475]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 441/500] [Batch 380/676] [D loss: -0.031215] [G loss: 0.448265] [d1 loss: 0.014812] [d2 loss: 0.020348]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 400/676] [D loss: -0.049589] [G loss: 0.484614] [d1 loss: 0.124110] [d2 loss: 0.111500]  [sq d1 d2: 0.000159]  [num0: 14.000000] [num1 50.000000]
[Epoch 441/500] [Batch 420/676] [D loss: -0.043635] [G loss: 0.487793] [d1 loss: 0.016108] [d2 loss: 0.018506]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 441/500] [Batch 440/676] [D loss: 0.001627] [G loss: 0.439560] [d1 loss: 0.016925] [d2 loss: 0.021588]  [sq d1 d2: 0.000022]  [num0: 17.000000] [num1 47.000000]
[Epoch 441/500] [Batch 460/676] [D loss: 0.035421] [G loss: 0.386693] [d1 loss: 0.058422] [d2 loss: 0.034618]  [sq d1 d2: 0.000567]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 480/676] [D loss: -0.004615] [G loss: 0.306294] [d1 loss: 0.036408] [d2 loss: 0.039879]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 441/500] [Batch 500/676] [D loss: 0.012625] [G loss: 0.251443] [d1 loss: 0.071273] [d2 loss: 0.068251]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 520/676] [D loss: 0.015623] [G loss: 0.169614] [d1 loss: 0.006592] [d2 loss: 0.009135]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 540/676] [D loss: 0.005338] [G loss: 0.062769] [d1 loss: 0.059493] [d2 loss: 0.054105]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 441/500] [Batch 560/676] [D loss: -0.004671] [G loss: -0.006628] [d1 loss: 0.041408] [d2 loss: 0.052777]  [sq d1 d2: 0.000129]  [num0: 13.000000] [num1 51.000000]
[Epoch 441/500] [Batch 580/676] [D loss: -0.021839] [G loss: -0.064634] [d1 loss: 0.078921] [d2 loss: 0.079411]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 441/500] [Batch 600/676] [D loss: -0.037241] [G loss: -0.174458] [d1 loss: 0.024905] [d2 loss: 0.025536]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 441/500] [Batch 620/676] [D loss: -0.026680] [G loss: -0.266758] [d1 loss: 0.100342] [d2 loss: 0.101009]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 441/500] [Batch 640/676] [D loss: -0.021371] [G loss: -0.401541] [d1 loss: 0.064947] [d2 loss: 0.068565]  [sq d1 d2: 0.000013]  [num0: 21.000000] [num1 43.000000]
[Epoch 441/500] [Batch 660/676] [D loss: -0.058831] [G loss: -0.543133] [d1 loss: 0.115074] [d2 loss: 0.111936]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 0/676] [D loss: -0.048778] [G loss: -0.564414] [d1 loss: 0.048827] [d2 loss: 0.048034]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 20/676] [D loss: 0.030305] [G loss: -0.597763] [d1 loss: 0.022874] [d2 loss: 0.037024]  [sq d1 d2: 0.000200]  [num0: 13.000000] [num1 51.000000]
[Epoch 442/500] [Batch 40/676] [D loss: 0.020233] [G loss: -0.610412] [d1 loss: 0.012015] [d2 loss: 0.009228]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 442/500] [Batch 60/676] [D loss: 0.000246] [G loss: -0.502262] [d1 loss: 0.119168] [d2 loss: 0.066606]  [sq d1 d2: 0.002763]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 80/676] [D loss: 0.037964] [G loss: -0.360803] [d1 loss: 0.110516] [d2 loss: 0.109053]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 100/676] [D loss: 0.007276] [G loss: -0.252918] [d1 loss: 0.106271] [d2 loss: 0.098121]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 442/500] [Batch 120/676] [D loss: -0.001992] [G loss: -0.145306] [d1 loss: 0.077313] [d2 loss: 0.124346]  [sq d1 d2: 0.002212]  [num0: 21.000000] [num1 43.000000]
[Epoch 442/500] [Batch 140/676] [D loss: 0.000551] [G loss: -0.069215] [d1 loss: 0.047962] [d2 loss: 0.047640]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 442/500] [Batch 160/676] [D loss: -0.006830] [G loss: -0.025360] [d1 loss: 0.022161] [d2 loss: 0.025522]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 180/676] [D loss: -0.015042] [G loss: 0.030159] [d1 loss: 0.020436] [d2 loss: 0.025329]  [sq d1 d2: 0.000024]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 200/676] [D loss: -0.028471] [G loss: 0.084093] [d1 loss: 0.032180] [d2 loss: 0.047559]  [sq d1 d2: 0.000236]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 220/676] [D loss: -0.050370] [G loss: 0.170982] [d1 loss: 0.023238] [d2 loss: 0.023205]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 240/676] [D loss: -0.043191] [G loss: 0.313766] [d1 loss: 0.033092] [d2 loss: 0.036783]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 442/500] [Batch 260/676] [D loss: -0.040687] [G loss: 0.368921] [d1 loss: 0.030154] [d2 loss: 0.024178]  [sq d1 d2: 0.000036]  [num0: 12.000000] [num1 52.000000]
[Epoch 442/500] [Batch 280/676] [D loss: -0.046533] [G loss: 0.419702] [d1 loss: 0.764288] [d2 loss: 0.513047]  [sq d1 d2: 0.063122]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 300/676] [D loss: 0.000914] [G loss: 0.397955] [d1 loss: 0.023680] [d2 loss: 0.014796]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 320/676] [D loss: -0.022947] [G loss: 0.318544] [d1 loss: 0.048807] [d2 loss: 0.030306]  [sq d1 d2: 0.000342]  [num0: 14.000000] [num1 50.000000]
[Epoch 442/500] [Batch 340/676] [D loss: 0.037425] [G loss: 0.237644] [d1 loss: 0.032804] [d2 loss: 0.031598]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 442/500] [Batch 360/676] [D loss: 0.001329] [G loss: 0.200165] [d1 loss: 0.120693] [d2 loss: 0.128158]  [sq d1 d2: 0.000056]  [num0: 18.000000] [num1 46.000000]
[Epoch 442/500] [Batch 380/676] [D loss: 0.019173] [G loss: 0.122611] [d1 loss: 0.039423] [d2 loss: 0.041971]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]

[Epoch 442/500] [Batch 400/676] [D loss: 0.005733] [G loss: 0.053568] [d1 loss: 0.055399] [d2 loss: 0.040042]  [sq d1 d2: 0.000236]  [num0: 16.000000] [num1 48.000000]
[Epoch 442/500] [Batch 420/676] [D loss: 0.001189] [G loss: -0.026210] [d1 loss: 0.044006] [d2 loss: 0.031042]  [sq d1 d2: 0.000168]  [num0: 11.000000] [num1 53.000000]
[Epoch 442/500] [Batch 440/676] [D loss: -0.009843] [G loss: -0.113213] [d1 loss: 0.070993] [d2 loss: 0.073509]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 460/676] [D loss: -0.017670] [G loss: -0.168400] [d1 loss: 0.051815] [d2 loss: 0.046868]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 442/500] [Batch 480/676] [D loss: -0.045225] [G loss: -0.247010] [d1 loss: 0.039050] [d2 loss: 0.033142]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 442/500] [Batch 500/676] [D loss: -0.065125] [G loss: -0.379323] [d1 loss: 0.092724] [d2 loss: 0.082033]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 520/676] [D loss: -0.040873] [G loss: -0.467331] [d1 loss: 0.164140] [d2 loss: 0.186202]  [sq d1 d2: 0.000487]  [num0: 13.000000] [num1 51.000000]
[Epoch 442/500] [Batch 540/676] [D loss: -0.038447] [G loss: -0.522302] [d1 loss: 0.054542] [d2 loss: 0.058547]  [sq d1 d2: 0.000016]  [num0: 17.000000] [num1 47.000000]
[Epoch 442/500] [Batch 560/676] [D loss: -0.007422] [G loss: -0.598898] [d1 loss: 0.013267] [d2 loss: 0.014646]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 442/500] [Batch 580/676] [D loss: -0.006715] [G loss: -0.642365] [d1 loss: 0.104732] [d2 loss: 0.141502]  [sq d1 d2: 0.001352]  [num0: 17.000000] [num1 47.000000]
[Epoch 442/500] [Batch 600/676] [D loss: 0.009772] [G loss: -0.585912] [d1 loss: 0.008165] [d2 loss: 0.012586]  [sq d1 d2: 0.000020]  [num0: 10.000000] [num1 54.000000]
[Epoch 442/500] [Batch 620/676] [D loss: 0.000036] [G loss: -0.569796] [d1 loss: 0.089150] [d2 loss: 0.084520]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 442/500] [Batch 640/676] [D loss: 0.015051] [G loss: -0.452640] [d1 loss: 0.033791] [d2 loss: 0.026140]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 442/500] [Batch 660/676] [D loss: 0.016718] [G loss: -0.366840] [d1 loss: 0.029767] [d2 loss: 0.049143]  [sq d1 d2: 0.000375]  [num0: 19.000000] [num1 45.000000]
[Epoch 443/500] [Batch 0/676] [D loss: 0.006138] [G loss: -0.259132] [d1 loss: 0.035496] [d2 loss: 0.045462]  [sq d1 d2: 0.000099]  [num0: 16.000000] [num1 48.000000]
[Epoch 443/500] [Batch 20/676] [D loss: 0.008388] [G loss: -0.137063] [d1 loss: 0.037219] [d2 loss: 0.034787]  [sq d1 d2: 0.000006]  [num0: 12.000000] [num1 52.000000]
[Epoch 443/500] [Batch 40/676] [D loss: -0.002098] [G loss: -0.042045] [d1 loss: 0.077572] [d2 loss: 0.064754]  [sq d1 d2: 0.000164]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 60/676] [D loss: -0.010659] [G loss: 0.067059] [d1 loss: 0.009125] [d2 loss: 0.005777]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 443/500] [Batch 80/676] [D loss: -0.027478] [G loss: 0.197089] [d1 loss: 0.031854] [d2 loss: 0.034901]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 443/500] [Batch 100/676] [D loss: -0.008800] [G loss: 0.376080] [d1 loss: 0.066656] [d2 loss: 0.040195]  [sq d1 d2: 0.000700]  [num0: 18.000000] [num1 46.000000]
[Epoch 443/500] [Batch 120/676] [D loss: -0.063324] [G loss: 0.591448] [d1 loss: 0.075581] [d2 loss: 0.094277]  [sq d1 d2: 0.000350]  [num0: 14.000000] [num1 50.000000]
[Epoch 443/500] [Batch 140/676] [D loss: -0.066360] [G loss: 0.700658] [d1 loss: 0.151937] [d2 loss: 0.187202]  [sq d1 d2: 0.001244]  [num0: 16.000000] [num1 48.000000]
[Epoch 443/500] [Batch 160/676] [D loss: -0.035992] [G loss: 0.704319] [d1 loss: 0.031955] [d2 loss: 0.053890]  [sq d1 d2: 0.000481]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 180/676] [D loss: -0.024432] [G loss: 0.695171] [d1 loss: 0.032180] [d2 loss: 0.039658]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 200/676] [D loss: -0.037074] [G loss: 0.695407] [d1 loss: 0.043291] [d2 loss: 0.034031]  [sq d1 d2: 0.000086]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 220/676] [D loss: 0.008301] [G loss: 0.605982] [d1 loss: 0.037528] [d2 loss: 0.043261]  [sq d1 d2: 0.000033]  [num0: 11.000000] [num1 53.000000]
[Epoch 443/500] [Batch 240/676] [D loss: 0.001119] [G loss: 0.490787] [d1 loss: 0.026720] [d2 loss: 0.039091]  [sq d1 d2: 0.000153]  [num0: 11.000000] [num1 53.000000]
[Epoch 443/500] [Batch 260/676] [D loss: 0.032115] [G loss: 0.362479] [d1 loss: 0.018211] [d2 loss: 0.017159]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 443/500] [Batch 280/676] [D loss: 0.000034] [G loss: 0.256250] [d1 loss: 0.083800] [d2 loss: 0.082115]  [sq d1 d2: 0.000003]  [num0: 19.000000] [num1 45.000000]
[Epoch 443/500] [Batch 300/676] [D loss: -0.003192] [G loss: 0.228052] [d1 loss: 0.050166] [d2 loss: 0.065563]  [sq d1 d2: 0.000237]  [num0: 16.000000] [num1 48.000000]
[Epoch 443/500] [Batch 320/676] [D loss: -0.017595] [G loss: 0.190791] [d1 loss: 0.012808] [d2 loss: 0.013750]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 443/500] [Batch 340/676] [D loss: -0.021338] [G loss: 0.117239] [d1 loss: 0.058018] [d2 loss: 0.073904]  [sq d1 d2: 0.000252]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 360/676] [D loss: 0.000458] [G loss: 0.063046] [d1 loss: 0.087309] [d2 loss: 0.074446]  [sq d1 d2: 0.000165]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 380/676] [D loss: -0.018111] [G loss: -0.007613] [d1 loss: 0.018856] [d2 loss: 0.013129]  [sq d1 d2: 0.000033]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 400/676] [D loss: -0.035411] [G loss: -0.070024] [d1 loss: 0.095068] [d2 loss: 0.119789]  [sq d1 d2: 0.000611]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 420/676] [D loss: -0.014927] [G loss: -0.101014] [d1 loss: 0.078045] [d2 loss: 0.088266]  [sq d1 d2: 0.000104]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 440/676] [D loss: -0.023004] [G loss: -0.198733] [d1 loss: 0.170166] [d2 loss: 0.163002]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 460/676] [D loss: -0.041972] [G loss: -0.250559] [d1 loss: 0.081205] [d2 loss: 0.069154]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 480/676] [D loss: -0.053542] [G loss: -0.358813] [d1 loss: 0.048809] [d2 loss: 0.069202]  [sq d1 d2: 0.000416]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 500/676] [D loss: 0.013826] [G loss: -0.412928] [d1 loss: 0.080404] [d2 loss: 0.075621]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 443/500] [Batch 520/676] [D loss: -0.038248] [G loss: -0.359280] [d1 loss: 0.078298] [d2 loss: 0.071104]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 540/676] [D loss: 0.023805] [G loss: -0.331105] [d1 loss: 0.052063] [d2 loss: 0.058110]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 443/500] [Batch 560/676] [D loss: 0.045331] [G loss: -0.308415] [d1 loss: 0.034130] [d2 loss: 0.040173]  [sq d1 d2: 0.000037]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 580/676] [D loss: 0.002204] [G loss: -0.245155] [d1 loss: 0.034062] [d2 loss: 0.033419]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 600/676] [D loss: 0.016404] [G loss: -0.216194] [d1 loss: 0.133683] [d2 loss: 0.110983]  [sq d1 d2: 0.000515]  [num0: 11.000000] [num1 53.000000]
[Epoch 443/500] [Batch 620/676] [D loss: 0.012513] [G loss: -0.163160] [d1 loss: 0.038490] [d2 loss: 0.032273]  [sq d1 d2: 0.000039]  [num0: 13.000000] [num1 51.000000]
[Epoch 443/500] [Batch 640/676] [D loss: 0.000488] [G loss: -0.127219] [d1 loss: 0.008050] [d2 loss: 0.012456]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 443/500] [Batch 660/676] [D loss: -0.003147] [G loss: -0.151768] [d1 loss: 0.065138] [d2 loss: 0.067732]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 444/500] [Batch 0/676] [D loss: -0.009116] [G loss: -0.110712] [d1 loss: 0.055505] [d2 loss: 0.028213]  [sq d1 d2: 0.000745]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 20/676] [D loss: -0.032950] [G loss: -0.088836] [d1 loss: 0.081684] [d2 loss: 0.053914]  [sq d1 d2: 0.000771]  [num0: 17.000000] [num1 47.000000]
[Epoch 444/500] [Batch 40/676] [D loss: -0.016985] [G loss: -0.079667] [d1 loss: 0.030602] [d2 loss: 0.017516]  [sq d1 d2: 0.000171]  [num0: 18.000000] [num1 46.000000]

[Epoch 444/500] [Batch 60/676] [D loss: -0.036206] [G loss: -0.044115] [d1 loss: 0.092873] [d2 loss: 0.100760]  [sq d1 d2: 0.000062]  [num0: 16.000000] [num1 48.000000]
[Epoch 444/500] [Batch 80/676] [D loss: -0.021522] [G loss: 0.000356] [d1 loss: 0.051161] [d2 loss: 0.037582]  [sq d1 d2: 0.000184]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 100/676] [D loss: -0.018795] [G loss: 0.036383] [d1 loss: 0.074160] [d2 loss: 0.064570]  [sq d1 d2: 0.000092]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 120/676] [D loss: -0.035956] [G loss: 0.052913] [d1 loss: 0.104627] [d2 loss: 0.121587]  [sq d1 d2: 0.000288]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 140/676] [D loss: -0.010493] [G loss: 0.043412] [d1 loss: 0.095945] [d2 loss: 0.073673]  [sq d1 d2: 0.000496]  [num0: 18.000000] [num1 46.000000]
[Epoch 444/500] [Batch 160/676] [D loss: -0.029358] [G loss: 0.049389] [d1 loss: 0.012816] [d2 loss: 0.011910]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 180/676] [D loss: 0.022551] [G loss: 0.036216] [d1 loss: 0.040946] [d2 loss: 0.053559]  [sq d1 d2: 0.000159]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 200/676] [D loss: 0.024148] [G loss: 0.050977] [d1 loss: 0.063866] [d2 loss: 0.057310]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 220/676] [D loss: 0.003205] [G loss: 0.093808] [d1 loss: 0.144459] [d2 loss: 0.144060]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 240/676] [D loss: -0.005891] [G loss: 0.090267] [d1 loss: 0.108788] [d2 loss: 0.103009]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 444/500] [Batch 260/676] [D loss: 0.005374] [G loss: 0.044563] [d1 loss: 0.020585] [d2 loss: 0.024414]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 444/500] [Batch 280/676] [D loss: -0.002110] [G loss: 0.025179] [d1 loss: 0.034938] [d2 loss: 0.031052]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 444/500] [Batch 300/676] [D loss: -0.009327] [G loss: -0.005893] [d1 loss: 0.091924] [d2 loss: 0.095449]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 444/500] [Batch 320/676] [D loss: -0.010514] [G loss: -0.008609] [d1 loss: 0.080887] [d2 loss: 0.085403]  [sq d1 d2: 0.000020]  [num0: 13.000000] [num1 51.000000]
[Epoch 444/500] [Batch 340/676] [D loss: -0.023923] [G loss: -0.019810] [d1 loss: 0.055310] [d2 loss: 0.068105]  [sq d1 d2: 0.000164]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 360/676] [D loss: -0.031643] [G loss: -0.023430] [d1 loss: 0.035885] [d2 loss: 0.022009]  [sq d1 d2: 0.000193]  [num0: 13.000000] [num1 51.000000]
[Epoch 444/500] [Batch 380/676] [D loss: -0.021632] [G loss: -0.043788] [d1 loss: 0.074637] [d2 loss: 0.082353]  [sq d1 d2: 0.000060]  [num0: 17.000000] [num1 47.000000]
[Epoch 444/500] [Batch 400/676] [D loss: -0.029792] [G loss: -0.018809] [d1 loss: 0.046693] [d2 loss: 0.042244]  [sq d1 d2: 0.000020]  [num0: 17.000000] [num1 47.000000]
[Epoch 444/500] [Batch 420/676] [D loss: -0.005849] [G loss: 0.023974] [d1 loss: 0.030890] [d2 loss: 0.027278]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 444/500] [Batch 440/676] [D loss: -0.034140] [G loss: 0.047080] [d1 loss: 0.029698] [d2 loss: 0.037205]  [sq d1 d2: 0.000056]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 460/676] [D loss: 0.007991] [G loss: -0.039421] [d1 loss: 0.081175] [d2 loss: 0.084610]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 444/500] [Batch 480/676] [D loss: 0.010526] [G loss: -0.035958] [d1 loss: 0.044621] [d2 loss: 0.048269]  [sq d1 d2: 0.000013]  [num0: 13.000000] [num1 51.000000]
[Epoch 444/500] [Batch 500/676] [D loss: 0.002654] [G loss: -0.024223] [d1 loss: 0.028667] [d2 loss: 0.027496]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 444/500] [Batch 520/676] [D loss: 0.002229] [G loss: 0.010915] [d1 loss: 0.029129] [d2 loss: 0.026238]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 444/500] [Batch 540/676] [D loss: 0.015873] [G loss: 0.025011] [d1 loss: 0.036459] [d2 loss: 0.036287]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 444/500] [Batch 560/676] [D loss: 0.005395] [G loss: 0.044498] [d1 loss: 0.059363] [d2 loss: 0.033609]  [sq d1 d2: 0.000663]  [num0: 20.000000] [num1 44.000000]
[Epoch 444/500] [Batch 580/676] [D loss: -0.001994] [G loss: 0.028777] [d1 loss: 0.024620] [d2 loss: 0.044035]  [sq d1 d2: 0.000377]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 600/676] [D loss: -0.012206] [G loss: 0.018180] [d1 loss: 0.062774] [d2 loss: 0.059124]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 444/500] [Batch 620/676] [D loss: -0.011819] [G loss: 0.013390] [d1 loss: 0.064322] [d2 loss: 0.068809]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 444/500] [Batch 640/676] [D loss: -0.017868] [G loss: 0.011494] [d1 loss: 0.029963] [d2 loss: 0.056505]  [sq d1 d2: 0.000704]  [num0: 17.000000] [num1 47.000000]
[Epoch 444/500] [Batch 660/676] [D loss: -0.014417] [G loss: -0.048509] [d1 loss: 0.030487] [d2 loss: 0.078834]  [sq d1 d2: 0.002337]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 0/676] [D loss: -0.029268] [G loss: -0.013104] [d1 loss: 0.019552] [d2 loss: 0.020647]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 445/500] [Batch 20/676] [D loss: 0.001709] [G loss: 0.026445] [d1 loss: 0.016832] [d2 loss: 0.014293]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 445/500] [Batch 40/676] [D loss: -0.001075] [G loss: 0.050341] [d1 loss: 0.036093] [d2 loss: 0.030691]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 60/676] [D loss: 0.034424] [G loss: 0.043195] [d1 loss: 0.055131] [d2 loss: 0.047166]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 80/676] [D loss: -0.004038] [G loss: 0.031913] [d1 loss: 0.043337] [d2 loss: 0.046906]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 100/676] [D loss: -0.006009] [G loss: 0.021550] [d1 loss: 0.081435] [d2 loss: 0.084475]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 120/676] [D loss: 0.008282] [G loss: -0.004449] [d1 loss: 0.031814] [d2 loss: 0.029084]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 140/676] [D loss: 0.015911] [G loss: -0.012162] [d1 loss: 0.038033] [d2 loss: 0.041374]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 160/676] [D loss: 0.004234] [G loss: -0.028258] [d1 loss: 0.070452] [d2 loss: 0.060606]  [sq d1 d2: 0.000097]  [num0: 20.000000] [num1 44.000000]
[Epoch 445/500] [Batch 180/676] [D loss: -0.007041] [G loss: -0.023722] [d1 loss: 0.052606] [d2 loss: 0.062409]  [sq d1 d2: 0.000096]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 200/676] [D loss: -0.020848] [G loss: -0.090242] [d1 loss: 0.233564] [d2 loss: 0.109113]  [sq d1 d2: 0.015488]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 220/676] [D loss: -0.020039] [G loss: -0.158442] [d1 loss: 0.133851] [d2 loss: 0.128784]  [sq d1 d2: 0.000026]  [num0: 20.000000] [num1 44.000000]
[Epoch 445/500] [Batch 240/676] [D loss: -0.001048] [G loss: -0.175034] [d1 loss: 0.113851] [d2 loss: 0.151572]  [sq d1 d2: 0.001423]  [num0: 14.000000] [num1 50.000000]
[Epoch 445/500] [Batch 260/676] [D loss: -0.004097] [G loss: -0.214524] [d1 loss: 0.029547] [d2 loss: 0.030301]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 280/676] [D loss: -0.015749] [G loss: -0.237786] [d1 loss: 0.035873] [d2 loss: 0.034307]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 300/676] [D loss: -0.001998] [G loss: -0.298346] [d1 loss: 0.040271] [d2 loss: 0.049602]  [sq d1 d2: 0.000087]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 320/676] [D loss: -0.025151] [G loss: -0.391474] [d1 loss: 0.030505] [d2 loss: 0.037938]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 340/676] [D loss: -0.022140] [G loss: -0.423254] [d1 loss: 0.024322] [d2 loss: 0.028010]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 445/500] [Batch 360/676] [D loss: -0.008603] [G loss: -0.397771] [d1 loss: 0.043819] [d2 loss: 0.044041]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]

[Epoch 445/500] [Batch 380/676] [D loss: 0.033863] [G loss: -0.245210] [d1 loss: 0.086335] [d2 loss: 0.087839]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 445/500] [Batch 400/676] [D loss: 0.007583] [G loss: -0.181316] [d1 loss: 0.083296] [d2 loss: 0.102147]  [sq d1 d2: 0.000355]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 420/676] [D loss: 0.012869] [G loss: -0.094126] [d1 loss: 0.045978] [d2 loss: 0.051733]  [sq d1 d2: 0.000033]  [num0: 14.000000] [num1 50.000000]
[Epoch 445/500] [Batch 440/676] [D loss: -0.005530] [G loss: -0.009038] [d1 loss: 0.031260] [d2 loss: 0.022765]  [sq d1 d2: 0.000072]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 460/676] [D loss: -0.005742] [G loss: 0.144697] [d1 loss: 0.024421] [d2 loss: 0.035731]  [sq d1 d2: 0.000128]  [num0: 12.000000] [num1 52.000000]
[Epoch 445/500] [Batch 480/676] [D loss: -0.003724] [G loss: 0.263988] [d1 loss: 0.055249] [d2 loss: 0.061242]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 445/500] [Batch 500/676] [D loss: -0.016337] [G loss: 0.390379] [d1 loss: 0.031005] [d2 loss: 0.040175]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 520/676] [D loss: -0.025936] [G loss: 0.527680] [d1 loss: 0.157465] [d2 loss: 0.123407]  [sq d1 d2: 0.001160]  [num0: 14.000000] [num1 50.000000]
[Epoch 445/500] [Batch 540/676] [D loss: -0.023605] [G loss: 0.592839] [d1 loss: 0.064347] [d2 loss: 0.064729]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 560/676] [D loss: -0.034070] [G loss: 0.654684] [d1 loss: 0.065035] [d2 loss: 0.075719]  [sq d1 d2: 0.000114]  [num0: 12.000000] [num1 52.000000]
[Epoch 445/500] [Batch 580/676] [D loss: 0.014565] [G loss: 0.650845] [d1 loss: 0.039636] [d2 loss: 0.042639]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 600/676] [D loss: -0.010509] [G loss: 0.632276] [d1 loss: 0.074448] [d2 loss: 0.094095]  [sq d1 d2: 0.000386]  [num0: 16.000000] [num1 48.000000]
[Epoch 445/500] [Batch 620/676] [D loss: 0.027591] [G loss: 0.578792] [d1 loss: 0.096915] [d2 loss: 0.052253]  [sq d1 d2: 0.001995]  [num0: 17.000000] [num1 47.000000]
[Epoch 445/500] [Batch 640/676] [D loss: 0.010955] [G loss: 0.487087] [d1 loss: 0.041544] [d2 loss: 0.036689]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 445/500] [Batch 660/676] [D loss: -0.021029] [G loss: 0.337729] [d1 loss: 0.017517] [d2 loss: 0.021737]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 446/500] [Batch 0/676] [D loss: -0.021062] [G loss: 0.303059] [d1 loss: 0.071875] [d2 loss: 0.060451]  [sq d1 d2: 0.000131]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 20/676] [D loss: 0.006428] [G loss: 0.166876] [d1 loss: 0.047785] [d2 loss: 0.056056]  [sq d1 d2: 0.000068]  [num0: 19.000000] [num1 45.000000]
[Epoch 446/500] [Batch 40/676] [D loss: -0.041321] [G loss: 0.026385] [d1 loss: 0.069029] [d2 loss: 0.100967]  [sq d1 d2: 0.001020]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 60/676] [D loss: -0.015237] [G loss: -0.053443] [d1 loss: 0.038218] [d2 loss: 0.030041]  [sq d1 d2: 0.000067]  [num0: 18.000000] [num1 46.000000]
[Epoch 446/500] [Batch 80/676] [D loss: 0.007975] [G loss: -0.147289] [d1 loss: 0.449642] [d2 loss: 0.319383]  [sq d1 d2: 0.016968]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 100/676] [D loss: -0.012129] [G loss: -0.232321] [d1 loss: 0.064902] [d2 loss: 0.076044]  [sq d1 d2: 0.000124]  [num0: 17.000000] [num1 47.000000]
[Epoch 446/500] [Batch 120/676] [D loss: -0.004945] [G loss: -0.277665] [d1 loss: 0.063660] [d2 loss: 0.069046]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 140/676] [D loss: 0.004246] [G loss: -0.369348] [d1 loss: 0.112215] [d2 loss: 0.093211]  [sq d1 d2: 0.000361]  [num0: 14.000000] [num1 50.000000]
[Epoch 446/500] [Batch 160/676] [D loss: -0.000902] [G loss: -0.430308] [d1 loss: 0.122418] [d2 loss: 0.147832]  [sq d1 d2: 0.000646]  [num0: 17.000000] [num1 47.000000]
[Epoch 446/500] [Batch 180/676] [D loss: -0.003548] [G loss: -0.399278] [d1 loss: 0.049923] [d2 loss: 0.065168]  [sq d1 d2: 0.000232]  [num0: 18.000000] [num1 46.000000]
[Epoch 446/500] [Batch 200/676] [D loss: 0.012533] [G loss: -0.362525] [d1 loss: 0.079853] [d2 loss: 0.058855]  [sq d1 d2: 0.000441]  [num0: 12.000000] [num1 52.000000]
[Epoch 446/500] [Batch 220/676] [D loss: -0.002116] [G loss: -0.269593] [d1 loss: 0.109394] [d2 loss: 0.119251]  [sq d1 d2: 0.000097]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 240/676] [D loss: -0.000798] [G loss: -0.230049] [d1 loss: 0.024391] [d2 loss: 0.017652]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 260/676] [D loss: 0.008030] [G loss: -0.130492] [d1 loss: 0.097054] [d2 loss: 0.093677]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 280/676] [D loss: -0.008276] [G loss: -0.043633] [d1 loss: 0.046024] [d2 loss: 0.043892]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 300/676] [D loss: -0.003970] [G loss: 0.016894] [d1 loss: 0.074419] [d2 loss: 0.094484]  [sq d1 d2: 0.000403]  [num0: 12.000000] [num1 52.000000]
[Epoch 446/500] [Batch 320/676] [D loss: -0.021930] [G loss: 0.064565] [d1 loss: 0.016627] [d2 loss: 0.022535]  [sq d1 d2: 0.000035]  [num0: 17.000000] [num1 47.000000]
[Epoch 446/500] [Batch 340/676] [D loss: -0.012945] [G loss: 0.126767] [d1 loss: 0.032661] [d2 loss: 0.050114]  [sq d1 d2: 0.000305]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 360/676] [D loss: -0.016952] [G loss: 0.226526] [d1 loss: 0.205672] [d2 loss: 0.225855]  [sq d1 d2: 0.000407]  [num0: 13.000000] [num1 51.000000]
[Epoch 446/500] [Batch 380/676] [D loss: -0.018667] [G loss: 0.294157] [d1 loss: 0.115353] [d2 loss: 0.117696]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 400/676] [D loss: -0.008061] [G loss: 0.293150] [d1 loss: 0.084287] [d2 loss: 0.071750]  [sq d1 d2: 0.000157]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 420/676] [D loss: -0.006274] [G loss: 0.351138] [d1 loss: 0.074439] [d2 loss: 0.046719]  [sq d1 d2: 0.000768]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 440/676] [D loss: -0.007175] [G loss: 0.411102] [d1 loss: 0.031810] [d2 loss: 0.023499]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 460/676] [D loss: 0.000294] [G loss: 0.351272] [d1 loss: 0.036799] [d2 loss: 0.022482]  [sq d1 d2: 0.000205]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 480/676] [D loss: -0.006475] [G loss: 0.365686] [d1 loss: 0.055788] [d2 loss: 0.067826]  [sq d1 d2: 0.000145]  [num0: 18.000000] [num1 46.000000]
[Epoch 446/500] [Batch 500/676] [D loss: -0.000334] [G loss: 0.288332] [d1 loss: 0.061529] [d2 loss: 0.060197]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 446/500] [Batch 520/676] [D loss: 0.001042] [G loss: 0.204686] [d1 loss: 0.058951] [d2 loss: 0.061765]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 446/500] [Batch 540/676] [D loss: 0.007622] [G loss: 0.138882] [d1 loss: 0.138576] [d2 loss: 0.147805]  [sq d1 d2: 0.000085]  [num0: 19.000000] [num1 45.000000]
[Epoch 446/500] [Batch 560/676] [D loss: -0.009759] [G loss: 0.100837] [d1 loss: 0.025186] [d2 loss: 0.025694]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 580/676] [D loss: -0.002122] [G loss: 0.049330] [d1 loss: 0.064802] [d2 loss: 0.061511]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 446/500] [Batch 600/676] [D loss: 0.011972] [G loss: -0.009576] [d1 loss: 0.116144] [d2 loss: 0.114395]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 446/500] [Batch 620/676] [D loss: -0.018262] [G loss: -0.071793] [d1 loss: 0.069173] [d2 loss: 0.064406]  [sq d1 d2: 0.000023]  [num0: 13.000000] [num1 51.000000]
[Epoch 446/500] [Batch 640/676] [D loss: -0.016481] [G loss: -0.085874] [d1 loss: 0.044087] [d2 loss: 0.072705]  [sq d1 d2: 0.000819]  [num0: 15.000000] [num1 49.000000]
[Epoch 446/500] [Batch 660/676] [D loss: 0.006906] [G loss: -0.144265] [d1 loss: 0.029972] [d2 loss: 0.033210]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 447/500] [Batch 0/676] [D loss: -0.011377] [G loss: -0.217259] [d1 loss: 0.060239] [d2 loss: 0.060493]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 20/676] [D loss: 0.008372] [G loss: -0.267888] [d1 loss: 0.110252] [d2 loss: 0.107299]  [sq d1 d2: 0.000009]  [num0: 10.000000] [num1 54.000000]

[Epoch 447/500] [Batch 40/676] [D loss: -0.010843] [G loss: -0.285899] [d1 loss: 0.009563] [d2 loss: 0.015386]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 60/676] [D loss: -0.027885] [G loss: -0.277290] [d1 loss: 0.045773] [d2 loss: 0.104681]  [sq d1 d2: 0.003470]  [num0: 13.000000] [num1 51.000000]
[Epoch 447/500] [Batch 80/676] [D loss: -0.012998] [G loss: -0.276125] [d1 loss: 0.075752] [d2 loss: 0.121118]  [sq d1 d2: 0.002058]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 100/676] [D loss: -0.009652] [G loss: -0.254800] [d1 loss: 0.050464] [d2 loss: 0.049728]  [sq d1 d2: 0.000001]  [num0: 9.000000] [num1 55.000000]
[Epoch 447/500] [Batch 120/676] [D loss: 0.028663] [G loss: -0.235294] [d1 loss: 0.045171] [d2 loss: 0.038032]  [sq d1 d2: 0.000051]  [num0: 9.000000] [num1 55.000000]
[Epoch 447/500] [Batch 140/676] [D loss: 0.002930] [G loss: -0.190813] [d1 loss: 0.054432] [d2 loss: 0.084077]  [sq d1 d2: 0.000879]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 160/676] [D loss: -0.008054] [G loss: -0.164088] [d1 loss: 0.038659] [d2 loss: 0.042679]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 180/676] [D loss: -0.011607] [G loss: -0.070183] [d1 loss: 0.120742] [d2 loss: 0.091862]  [sq d1 d2: 0.000834]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 200/676] [D loss: -0.002602] [G loss: -0.034276] [d1 loss: 0.150634] [d2 loss: 0.184229]  [sq d1 d2: 0.001129]  [num0: 12.000000] [num1 52.000000]
[Epoch 447/500] [Batch 220/676] [D loss: -0.022305] [G loss: -0.016451] [d1 loss: 0.048291] [d2 loss: 0.061141]  [sq d1 d2: 0.000165]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 240/676] [D loss: 0.002341] [G loss: -0.000139] [d1 loss: 0.117778] [d2 loss: 0.109206]  [sq d1 d2: 0.000073]  [num0: 15.000000] [num1 49.000000]
[Epoch 447/500] [Batch 260/676] [D loss: -0.014331] [G loss: 0.074746] [d1 loss: 0.070035] [d2 loss: 0.067917]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 280/676] [D loss: -0.018819] [G loss: 0.073280] [d1 loss: 0.080703] [d2 loss: 0.130605]  [sq d1 d2: 0.002490]  [num0: 18.000000] [num1 46.000000]
[Epoch 447/500] [Batch 300/676] [D loss: -0.007567] [G loss: 0.070345] [d1 loss: 0.179466] [d2 loss: 0.186164]  [sq d1 d2: 0.000045]  [num0: 15.000000] [num1 49.000000]
[Epoch 447/500] [Batch 320/676] [D loss: 0.012191] [G loss: 0.063136] [d1 loss: 0.069055] [d2 loss: 0.075139]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 447/500] [Batch 340/676] [D loss: -0.004993] [G loss: 0.073188] [d1 loss: 0.064703] [d2 loss: 0.087891]  [sq d1 d2: 0.000538]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 360/676] [D loss: -0.017145] [G loss: 0.037098] [d1 loss: 0.029307] [d2 loss: 0.030347]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 447/500] [Batch 380/676] [D loss: 0.002705] [G loss: 0.007351] [d1 loss: 0.068177] [d2 loss: 0.128900]  [sq d1 d2: 0.003687]  [num0: 14.000000] [num1 50.000000]
[Epoch 447/500] [Batch 400/676] [D loss: -0.005304] [G loss: -0.020827] [d1 loss: 0.084294] [d2 loss: 0.075452]  [sq d1 d2: 0.000078]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 420/676] [D loss: -0.001790] [G loss: -0.067681] [d1 loss: 0.068740] [d2 loss: 0.071867]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 447/500] [Batch 440/676] [D loss: -0.010173] [G loss: -0.063371] [d1 loss: 0.113024] [d2 loss: 0.111865]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 447/500] [Batch 460/676] [D loss: -0.000372] [G loss: -0.079748] [d1 loss: 0.033866] [d2 loss: 0.032053]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 447/500] [Batch 480/676] [D loss: -0.004611] [G loss: -0.115037] [d1 loss: 0.053103] [d2 loss: 0.051708]  [sq d1 d2: 0.000002]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 500/676] [D loss: -0.008004] [G loss: -0.127031] [d1 loss: 0.033916] [d2 loss: 0.080090]  [sq d1 d2: 0.002132]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 520/676] [D loss: -0.014292] [G loss: -0.192827] [d1 loss: 0.027632] [d2 loss: 0.021707]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 540/676] [D loss: -0.004659] [G loss: -0.216950] [d1 loss: 0.018972] [d2 loss: 0.026988]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 560/676] [D loss: -0.023729] [G loss: -0.238977] [d1 loss: 0.049996] [d2 loss: 0.057257]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 447/500] [Batch 580/676] [D loss: -0.004259] [G loss: -0.225250] [d1 loss: 0.041390] [d2 loss: 0.038289]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 447/500] [Batch 600/676] [D loss: -0.012854] [G loss: -0.241012] [d1 loss: 0.053054] [d2 loss: 0.054310]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 620/676] [D loss: 0.007421] [G loss: -0.269487] [d1 loss: 0.025044] [d2 loss: 0.014841]  [sq d1 d2: 0.000104]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 640/676] [D loss: 0.013890] [G loss: -0.259437] [d1 loss: 0.124724] [d2 loss: 0.174549]  [sq d1 d2: 0.002482]  [num0: 17.000000] [num1 47.000000]
[Epoch 447/500] [Batch 660/676] [D loss: -0.004743] [G loss: -0.250961] [d1 loss: 0.058558] [d2 loss: 0.041981]  [sq d1 d2: 0.000275]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 0/676] [D loss: 0.003938] [G loss: -0.254185] [d1 loss: 0.076253] [d2 loss: 0.096885]  [sq d1 d2: 0.000426]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 20/676] [D loss: -0.005896] [G loss: -0.213742] [d1 loss: 0.118930] [d2 loss: 0.049335]  [sq d1 d2: 0.004843]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 40/676] [D loss: -0.005532] [G loss: -0.155297] [d1 loss: 0.022241] [d2 loss: 0.028149]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 60/676] [D loss: 0.006626] [G loss: -0.113264] [d1 loss: 0.052376] [d2 loss: 0.044414]  [sq d1 d2: 0.000063]  [num0: 11.000000] [num1 53.000000]
[Epoch 448/500] [Batch 80/676] [D loss: -0.005709] [G loss: -0.063293] [d1 loss: 0.050783] [d2 loss: 0.056208]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 448/500] [Batch 100/676] [D loss: -0.008138] [G loss: -0.019397] [d1 loss: 0.029502] [d2 loss: 0.034785]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 120/676] [D loss: -0.017302] [G loss: 0.038847] [d1 loss: 0.048874] [d2 loss: 0.039266]  [sq d1 d2: 0.000092]  [num0: 13.000000] [num1 51.000000]
[Epoch 448/500] [Batch 140/676] [D loss: -0.001280] [G loss: 0.044366] [d1 loss: 0.041178] [d2 loss: 0.137068]  [sq d1 d2: 0.009195]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 160/676] [D loss: -0.002591] [G loss: 0.083262] [d1 loss: 0.010246] [d2 loss: 0.011357]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 448/500] [Batch 180/676] [D loss: -0.041855] [G loss: 0.169736] [d1 loss: 0.020321] [d2 loss: 0.019067]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 200/676] [D loss: -0.016995] [G loss: 0.214356] [d1 loss: 0.021694] [d2 loss: 0.026112]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 448/500] [Batch 220/676] [D loss: -0.011034] [G loss: 0.224539] [d1 loss: 0.119024] [d2 loss: 0.102217]  [sq d1 d2: 0.000282]  [num0: 18.000000] [num1 46.000000]
[Epoch 448/500] [Batch 240/676] [D loss: 0.037036] [G loss: 0.229881] [d1 loss: 0.042082] [d2 loss: 0.034887]  [sq d1 d2: 0.000052]  [num0: 19.000000] [num1 45.000000]
[Epoch 448/500] [Batch 260/676] [D loss: -0.015093] [G loss: 0.255470] [d1 loss: 0.037942] [d2 loss: 0.035594]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 280/676] [D loss: -0.023850] [G loss: 0.226885] [d1 loss: 0.067267] [d2 loss: 0.073171]  [sq d1 d2: 0.000035]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 300/676] [D loss: -0.022020] [G loss: 0.267441] [d1 loss: 0.008498] [d2 loss: 0.010704]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 320/676] [D loss: 0.012230] [G loss: 0.272520] [d1 loss: 0.033048] [d2 loss: 0.090817]  [sq d1 d2: 0.003337]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 340/676] [D loss: 0.000826] [G loss: 0.224535] [d1 loss: 0.023709] [d2 loss: 0.029044]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]

[Epoch 448/500] [Batch 360/676] [D loss: -0.005443] [G loss: 0.224095] [d1 loss: 0.052651] [d2 loss: 0.042326]  [sq d1 d2: 0.000107]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 380/676] [D loss: -0.010410] [G loss: 0.175626] [d1 loss: 0.098725] [d2 loss: 0.088336]  [sq d1 d2: 0.000108]  [num0: 18.000000] [num1 46.000000]
[Epoch 448/500] [Batch 400/676] [D loss: -0.009698] [G loss: 0.150732] [d1 loss: 0.024628] [d2 loss: 0.040527]  [sq d1 d2: 0.000253]  [num0: 17.000000] [num1 47.000000]
[Epoch 448/500] [Batch 420/676] [D loss: -0.025887] [G loss: 0.115113] [d1 loss: 0.041743] [d2 loss: 0.043477]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 448/500] [Batch 440/676] [D loss: -0.010170] [G loss: 0.116586] [d1 loss: 0.033226] [d2 loss: 0.046194]  [sq d1 d2: 0.000168]  [num0: 17.000000] [num1 47.000000]
[Epoch 448/500] [Batch 460/676] [D loss: -0.030389] [G loss: 0.125406] [d1 loss: 0.071722] [d2 loss: 0.058259]  [sq d1 d2: 0.000181]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 480/676] [D loss: 0.010591] [G loss: 0.106883] [d1 loss: 0.021568] [d2 loss: 0.029103]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 448/500] [Batch 500/676] [D loss: -0.029130] [G loss: 0.006323] [d1 loss: 0.138434] [d2 loss: 0.166169]  [sq d1 d2: 0.000769]  [num0: 14.000000] [num1 50.000000]
[Epoch 448/500] [Batch 520/676] [D loss: -0.018172] [G loss: -0.063942] [d1 loss: 0.031067] [d2 loss: 0.022859]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 448/500] [Batch 540/676] [D loss: -0.006972] [G loss: -0.093272] [d1 loss: 0.034350] [d2 loss: 0.041891]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 448/500] [Batch 560/676] [D loss: 0.001299] [G loss: -0.117653] [d1 loss: 0.044244] [d2 loss: 0.062888]  [sq d1 d2: 0.000348]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 580/676] [D loss: -0.017504] [G loss: -0.127126] [d1 loss: 0.108808] [d2 loss: 0.127766]  [sq d1 d2: 0.000359]  [num0: 12.000000] [num1 52.000000]
[Epoch 448/500] [Batch 600/676] [D loss: -0.010130] [G loss: -0.139255] [d1 loss: 0.045022] [d2 loss: 0.095168]  [sq d1 d2: 0.002515]  [num0: 14.000000] [num1 50.000000]
[Epoch 448/500] [Batch 620/676] [D loss: -0.015547] [G loss: -0.169650] [d1 loss: 0.039917] [d2 loss: 0.025528]  [sq d1 d2: 0.000207]  [num0: 19.000000] [num1 45.000000]
[Epoch 448/500] [Batch 640/676] [D loss: -0.010392] [G loss: -0.154528] [d1 loss: 0.104729] [d2 loss: 0.119954]  [sq d1 d2: 0.000232]  [num0: 16.000000] [num1 48.000000]
[Epoch 448/500] [Batch 660/676] [D loss: -0.006853] [G loss: -0.150899] [d1 loss: 0.135334] [d2 loss: 0.167801]  [sq d1 d2: 0.001054]  [num0: 18.000000] [num1 46.000000]
[Epoch 449/500] [Batch 0/676] [D loss: -0.017618] [G loss: -0.160703] [d1 loss: 0.041026] [d2 loss: 0.044424]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 449/500] [Batch 20/676] [D loss: -0.006493] [G loss: -0.144404] [d1 loss: 0.021455] [d2 loss: 0.047132]  [sq d1 d2: 0.000659]  [num0: 19.000000] [num1 45.000000]
[Epoch 449/500] [Batch 40/676] [D loss: -0.007192] [G loss: -0.127841] [d1 loss: 0.055828] [d2 loss: 0.061797]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 449/500] [Batch 60/676] [D loss: -0.004925] [G loss: -0.182391] [d1 loss: 0.115350] [d2 loss: 0.155955]  [sq d1 d2: 0.001649]  [num0: 14.000000] [num1 50.000000]
[Epoch 449/500] [Batch 80/676] [D loss: -0.012511] [G loss: -0.173285] [d1 loss: 0.094583] [d2 loss: 0.083885]  [sq d1 d2: 0.000114]  [num0: 15.000000] [num1 49.000000]
[Epoch 449/500] [Batch 100/676] [D loss: -0.006733] [G loss: -0.190737] [d1 loss: 0.111606] [d2 loss: 0.079289]  [sq d1 d2: 0.001044]  [num0: 19.000000] [num1 45.000000]
[Epoch 449/500] [Batch 120/676] [D loss: -0.010479] [G loss: -0.194516] [d1 loss: 0.057013] [d2 loss: 0.057293]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 449/500] [Batch 140/676] [D loss: -0.014690] [G loss: -0.181831] [d1 loss: 0.074274] [d2 loss: 0.068477]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 449/500] [Batch 160/676] [D loss: 0.009195] [G loss: -0.199092] [d1 loss: 0.198535] [d2 loss: 0.089074]  [sq d1 d2: 0.011982]  [num0: 17.000000] [num1 47.000000]
[Epoch 449/500] [Batch 180/676] [D loss: 0.017766] [G loss: -0.164905] [d1 loss: 0.036428] [d2 loss: 0.047726]  [sq d1 d2: 0.000128]  [num0: 13.000000] [num1 51.000000]
[Epoch 449/500] [Batch 200/676] [D loss: -0.003214] [G loss: -0.138291] [d1 loss: 0.054494] [d2 loss: 0.067793]  [sq d1 d2: 0.000177]  [num0: 16.000000] [num1 48.000000]
[Epoch 449/500] [Batch 220/676] [D loss: -0.000421] [G loss: -0.105083] [d1 loss: 0.101193] [d2 loss: 0.056037]  [sq d1 d2: 0.002039]  [num0: 17.000000] [num1 47.000000]
[Epoch 449/500] [Batch 240/676] [D loss: -0.005595] [G loss: -0.092767] [d1 loss: 0.063539] [d2 loss: 0.069292]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 449/500] [Batch 260/676] [D loss: -0.008472] [G loss: -0.050229] [d1 loss: 0.093502] [d2 loss: 0.127249]  [sq d1 d2: 0.001139]  [num0: 16.000000] [num1 48.000000]
[Epoch 449/500] [Batch 280/676] [D loss: -0.009262] [G loss: -0.034593] [d1 loss: 0.041370] [d2 loss: 0.081666]  [sq d1 d2: 0.001624]  [num0: 14.000000] [num1 50.000000]
[Epoch 449/500] [Batch 300/676] [D loss: -0.010302] [G loss: -0.047197] [d1 loss: 0.068284] [d2 loss: 0.073082]  [sq d1 d2: 0.000023]  [num0: 21.000000] [num1 43.000000]
[Epoch 449/500] [Batch 320/676] [D loss: -0.021391] [G loss: -0.040899] [d1 loss: 0.078177] [d2 loss: 0.085540]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 449/500] [Batch 340/676] [D loss: -0.003717] [G loss: -0.034560] [d1 loss: 0.103502] [d2 loss: 0.073866]  [sq d1 d2: 0.000878]  [num0: 13.000000] [num1 51.000000]
[Epoch 449/500] [Batch 360/676] [D loss: -0.017889] [G loss: -0.025016] [d1 loss: 0.063735] [d2 loss: 0.065946]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 449/500] [Batch 380/676] [D loss: -0.024791] [G loss: -0.060044] [d1 loss: 0.012601] [d2 loss: 0.021264]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 449/500] [Batch 400/676] [D loss: -0.005304] [G loss: -0.032906] [d1 loss: 0.068220] [d2 loss: 0.042650]  [sq d1 d2: 0.000654]  [num0: 17.000000] [num1 47.000000]
[Epoch 449/500] [Batch 420/676] [D loss: -0.015815] [G loss: -0.016146] [d1 loss: 0.048387] [d2 loss: 0.034965]  [sq d1 d2: 0.000180]  [num0: 13.000000] [num1 51.000000]
[Epoch 449/500] [Batch 440/676] [D loss: -0.010913] [G loss: -0.006577] [d1 loss: 0.048351] [d2 loss: 0.048606]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 449/500] [Batch 460/676] [D loss: 0.005246] [G loss: -0.031938] [d1 loss: 0.103698] [d2 loss: 0.116360]  [sq d1 d2: 0.000160]  [num0: 16.000000] [num1 48.000000]
[Epoch 449/500] [Batch 480/676] [D loss: 0.003107] [G loss: -0.026615] [d1 loss: 0.135239] [d2 loss: 0.080341]  [sq d1 d2: 0.003014]  [num0: 14.000000] [num1 50.000000]
[Epoch 449/500] [Batch 500/676] [D loss: 0.003185] [G loss: -0.066372] [d1 loss: 0.084475] [d2 loss: 0.082132]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 449/500] [Batch 520/676] [D loss: -0.000293] [G loss: -0.072376] [d1 loss: 0.050959] [d2 loss: 0.042824]  [sq d1 d2: 0.000066]  [num0: 14.000000] [num1 50.000000]
[Epoch 449/500] [Batch 540/676] [D loss: -0.020586] [G loss: -0.063987] [d1 loss: 0.093103] [d2 loss: 0.113026]  [sq d1 d2: 0.000397]  [num0: 15.000000] [num1 49.000000]
[Epoch 449/500] [Batch 560/676] [D loss: 0.002147] [G loss: -0.067769] [d1 loss: 0.021088] [d2 loss: 0.013477]  [sq d1 d2: 0.000058]  [num0: 18.000000] [num1 46.000000]
[Epoch 449/500] [Batch 580/676] [D loss: -0.002096] [G loss: -0.037733] [d1 loss: 0.067839] [d2 loss: 0.086178]  [sq d1 d2: 0.000336]  [num0: 13.000000] [num1 51.000000]
[Epoch 449/500] [Batch 600/676] [D loss: -0.019433] [G loss: -0.040999] [d1 loss: 0.107898] [d2 loss: 0.107474]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 449/500] [Batch 620/676] [D loss: -0.004837] [G loss: -0.023868] [d1 loss: 0.114032] [d2 loss: 0.143181]  [sq d1 d2: 0.000850]  [num0: 12.000000] [num1 52.000000]
[Epoch 449/500] [Batch 640/676] [D loss: -0.005134] [G loss: -0.031549] [d1 loss: 0.143590] [d2 loss: 0.111058]  [sq d1 d2: 0.001058]  [num0: 17.000000] [num1 47.000000]

[Epoch 449/500] [Batch 660/676] [D loss: -0.003585] [G loss: -0.043948] [d1 loss: 0.047845] [d2 loss: 0.040254]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 450/500] [Batch 0/676] [D loss: -0.007421] [G loss: -0.022043] [d1 loss: 0.060688] [d2 loss: 0.067094]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 450/500] [Batch 20/676] [D loss: -0.001753] [G loss: -0.019334] [d1 loss: 0.039499] [d2 loss: 0.044522]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 40/676] [D loss: 0.000646] [G loss: 0.005878] [d1 loss: 0.037667] [d2 loss: 0.043519]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 450/500] [Batch 60/676] [D loss: 0.000184] [G loss: 0.009908] [d1 loss: 0.064565] [d2 loss: 0.072538]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 450/500] [Batch 80/676] [D loss: 0.002695] [G loss: 0.017795] [d1 loss: 0.052613] [d2 loss: 0.067456]  [sq d1 d2: 0.000220]  [num0: 15.000000] [num1 49.000000]
[Epoch 450/500] [Batch 100/676] [D loss: -0.016631] [G loss: 0.041431] [d1 loss: 0.171273] [d2 loss: 0.189739]  [sq d1 d2: 0.000341]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 120/676] [D loss: -0.009150] [G loss: 0.021652] [d1 loss: 0.153661] [d2 loss: 0.101252]  [sq d1 d2: 0.002747]  [num0: 15.000000] [num1 49.000000]
[Epoch 450/500] [Batch 140/676] [D loss: -0.013271] [G loss: 0.038909] [d1 loss: 0.062728] [d2 loss: 0.059432]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 450/500] [Batch 160/676] [D loss: -0.012393] [G loss: 0.048090] [d1 loss: 0.042963] [d2 loss: 0.013584]  [sq d1 d2: 0.000863]  [num0: 18.000000] [num1 46.000000]
[Epoch 450/500] [Batch 180/676] [D loss: -0.005577] [G loss: 0.044929] [d1 loss: 0.147986] [d2 loss: 0.157609]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]
[Epoch 450/500] [Batch 200/676] [D loss: -0.010438] [G loss: 0.018385] [d1 loss: 0.094014] [d2 loss: 0.045994]  [sq d1 d2: 0.002306]  [num0: 19.000000] [num1 45.000000]
[Epoch 450/500] [Batch 220/676] [D loss: -0.010189] [G loss: 0.017669] [d1 loss: 0.039434] [d2 loss: 0.047402]  [sq d1 d2: 0.000063]  [num0: 18.000000] [num1 46.000000]
[Epoch 450/500] [Batch 240/676] [D loss: -0.010312] [G loss: 0.023455] [d1 loss: 0.060798] [d2 loss: 0.069114]  [sq d1 d2: 0.000069]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 260/676] [D loss: -0.019121] [G loss: 0.050484] [d1 loss: 0.055029] [d2 loss: 0.086034]  [sq d1 d2: 0.000961]  [num0: 18.000000] [num1 46.000000]
[Epoch 450/500] [Batch 280/676] [D loss: -0.009917] [G loss: 0.054906] [d1 loss: 0.126030] [d2 loss: 0.108634]  [sq d1 d2: 0.000303]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 300/676] [D loss: 0.001985] [G loss: 0.027747] [d1 loss: 0.050846] [d2 loss: 0.042529]  [sq d1 d2: 0.000069]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 320/676] [D loss: -0.007994] [G loss: -0.005068] [d1 loss: 0.117141] [d2 loss: 0.169358]  [sq d1 d2: 0.002727]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 340/676] [D loss: -0.004816] [G loss: -0.000829] [d1 loss: 0.062143] [d2 loss: 0.063264]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 450/500] [Batch 360/676] [D loss: -0.001988] [G loss: -0.032807] [d1 loss: 0.051026] [d2 loss: 0.046711]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 380/676] [D loss: 0.005150] [G loss: -0.033910] [d1 loss: 0.091691] [d2 loss: 0.076151]  [sq d1 d2: 0.000241]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 400/676] [D loss: -0.010127] [G loss: -0.045258] [d1 loss: 0.145825] [d2 loss: 0.122821]  [sq d1 d2: 0.000529]  [num0: 19.000000] [num1 45.000000]
[Epoch 450/500] [Batch 420/676] [D loss: -0.007047] [G loss: -0.032050] [d1 loss: 0.058563] [d2 loss: 0.058685]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 440/676] [D loss: -0.008730] [G loss: -0.031501] [d1 loss: 0.050968] [d2 loss: 0.048630]  [sq d1 d2: 0.000005]  [num0: 20.000000] [num1 44.000000]
[Epoch 450/500] [Batch 460/676] [D loss: -0.011143] [G loss: -0.043340] [d1 loss: 0.116335] [d2 loss: 0.152643]  [sq d1 d2: 0.001318]  [num0: 15.000000] [num1 49.000000]
[Epoch 450/500] [Batch 480/676] [D loss: -0.003949] [G loss: -0.042325] [d1 loss: 0.037724] [d2 loss: 0.034641]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 450/500] [Batch 500/676] [D loss: -0.004637] [G loss: -0.054202] [d1 loss: 0.146659] [d2 loss: 0.152415]  [sq d1 d2: 0.000033]  [num0: 13.000000] [num1 51.000000]
[Epoch 450/500] [Batch 520/676] [D loss: -0.009844] [G loss: -0.032999] [d1 loss: 0.145048] [d2 loss: 0.205494]  [sq d1 d2: 0.003654]  [num0: 17.000000] [num1 47.000000]
[Epoch 450/500] [Batch 540/676] [D loss: 0.000067] [G loss: -0.022872] [d1 loss: 0.080240] [d2 loss: 0.073031]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 450/500] [Batch 560/676] [D loss: -0.012656] [G loss: -0.038236] [d1 loss: 0.067776] [d2 loss: 0.072967]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 580/676] [D loss: -0.008910] [G loss: -0.042460] [d1 loss: 0.029775] [d2 loss: 0.047337]  [sq d1 d2: 0.000308]  [num0: 19.000000] [num1 45.000000]
[Epoch 450/500] [Batch 600/676] [D loss: -0.008385] [G loss: -0.047355] [d1 loss: 0.271957] [d2 loss: 0.198857]  [sq d1 d2: 0.005344]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 620/676] [D loss: -0.010159] [G loss: -0.043089] [d1 loss: 0.191125] [d2 loss: 0.280276]  [sq d1 d2: 0.007948]  [num0: 19.000000] [num1 45.000000]
[Epoch 450/500] [Batch 640/676] [D loss: -0.001144] [G loss: 0.000310] [d1 loss: 0.056405] [d2 loss: 0.045180]  [sq d1 d2: 0.000126]  [num0: 14.000000] [num1 50.000000]
[Epoch 450/500] [Batch 660/676] [D loss: -0.014318] [G loss: -0.027607] [d1 loss: 0.096353] [d2 loss: 0.104780]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 0/676] [D loss: -0.011930] [G loss: -0.027135] [d1 loss: 0.136416] [d2 loss: 0.117085]  [sq d1 d2: 0.000374]  [num0: 19.000000] [num1 45.000000]
[Epoch 451/500] [Batch 20/676] [D loss: -0.009150] [G loss: -0.033196] [d1 loss: 0.010981] [d2 loss: 0.009202]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 451/500] [Batch 40/676] [D loss: -0.011818] [G loss: -0.035979] [d1 loss: 0.042098] [d2 loss: 0.040104]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 451/500] [Batch 60/676] [D loss: -0.007290] [G loss: -0.035243] [d1 loss: 0.018553] [d2 loss: 0.018682]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 451/500] [Batch 80/676] [D loss: -0.006603] [G loss: -0.052568] [d1 loss: 0.150188] [d2 loss: 0.137813]  [sq d1 d2: 0.000153]  [num0: 17.000000] [num1 47.000000]
[Epoch 451/500] [Batch 100/676] [D loss: -0.006783] [G loss: -0.055998] [d1 loss: 0.063382] [d2 loss: 0.073288]  [sq d1 d2: 0.000098]  [num0: 13.000000] [num1 51.000000]
[Epoch 451/500] [Batch 120/676] [D loss: -0.010819] [G loss: -0.058618] [d1 loss: 0.036345] [d2 loss: 0.040746]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 451/500] [Batch 140/676] [D loss: -0.014139] [G loss: -0.042585] [d1 loss: 0.173291] [d2 loss: 0.199025]  [sq d1 d2: 0.000662]  [num0: 19.000000] [num1 45.000000]
[Epoch 451/500] [Batch 160/676] [D loss: -0.015263] [G loss: -0.042702] [d1 loss: 0.048649] [d2 loss: 0.063941]  [sq d1 d2: 0.000234]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 180/676] [D loss: -0.010670] [G loss: -0.043095] [d1 loss: 0.077120] [d2 loss: 0.074964]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 200/676] [D loss: -0.011136] [G loss: -0.072628] [d1 loss: 0.135264] [d2 loss: 0.110156]  [sq d1 d2: 0.000630]  [num0: 18.000000] [num1 46.000000]
[Epoch 451/500] [Batch 220/676] [D loss: -0.014249] [G loss: -0.060521] [d1 loss: 0.018650] [d2 loss: 0.022100]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 240/676] [D loss: -0.003314] [G loss: -0.097095] [d1 loss: 0.107675] [d2 loss: 0.096098]  [sq d1 d2: 0.000134]  [num0: 17.000000] [num1 47.000000]
[Epoch 451/500] [Batch 260/676] [D loss: -0.007291] [G loss: -0.080642] [d1 loss: 0.047564] [d2 loss: 0.060999]  [sq d1 d2: 0.000181]  [num0: 12.000000] [num1 52.000000]
[Epoch 451/500] [Batch 280/676] [D loss: -0.013432] [G loss: -0.071257] [d1 loss: 0.056699] [d2 loss: 0.083409]  [sq d1 d2: 0.000713]  [num0: 12.000000] [num1 52.000000]

[Epoch 451/500] [Batch 300/676] [D loss: -0.008812] [G loss: -0.068140] [d1 loss: 0.080997] [d2 loss: 0.064621]  [sq d1 d2: 0.000268]  [num0: 13.000000] [num1 51.000000]
[Epoch 451/500] [Batch 320/676] [D loss: -0.006560] [G loss: -0.064133] [d1 loss: 0.137368] [d2 loss: 0.135692]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 451/500] [Batch 340/676] [D loss: -0.005094] [G loss: -0.062389] [d1 loss: 0.046873] [d2 loss: 0.053753]  [sq d1 d2: 0.000047]  [num0: 19.000000] [num1 45.000000]
[Epoch 451/500] [Batch 360/676] [D loss: -0.008806] [G loss: -0.074962] [d1 loss: 0.050225] [d2 loss: 0.048654]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 451/500] [Batch 380/676] [D loss: -0.014184] [G loss: -0.073667] [d1 loss: 0.063693] [d2 loss: 0.062238]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 451/500] [Batch 400/676] [D loss: -0.007023] [G loss: -0.076049] [d1 loss: 0.076258] [d2 loss: 0.078906]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 451/500] [Batch 420/676] [D loss: 0.000043] [G loss: -0.075256] [d1 loss: 0.155449] [d2 loss: 0.116278]  [sq d1 d2: 0.001534]  [num0: 17.000000] [num1 47.000000]
[Epoch 451/500] [Batch 440/676] [D loss: -0.009021] [G loss: -0.058753] [d1 loss: 0.098846] [d2 loss: 0.105152]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 451/500] [Batch 460/676] [D loss: -0.014663] [G loss: -0.065189] [d1 loss: 0.069624] [d2 loss: 0.070531]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 480/676] [D loss: -0.017848] [G loss: -0.067364] [d1 loss: 0.085750] [d2 loss: 0.122536]  [sq d1 d2: 0.001353]  [num0: 19.000000] [num1 45.000000]
[Epoch 451/500] [Batch 500/676] [D loss: -0.008456] [G loss: -0.079008] [d1 loss: 0.035006] [d2 loss: 0.034122]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 451/500] [Batch 520/676] [D loss: -0.018520] [G loss: -0.080577] [d1 loss: 0.016550] [d2 loss: 0.019128]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 451/500] [Batch 540/676] [D loss: -0.022319] [G loss: -0.085099] [d1 loss: 0.044533] [d2 loss: 0.071951]  [sq d1 d2: 0.000752]  [num0: 16.000000] [num1 48.000000]
[Epoch 451/500] [Batch 560/676] [D loss: -0.007790] [G loss: -0.079469] [d1 loss: 0.087423] [d2 loss: 0.111055]  [sq d1 d2: 0.000558]  [num0: 17.000000] [num1 47.000000]
[Epoch 451/500] [Batch 580/676] [D loss: 0.001966] [G loss: -0.073395] [d1 loss: 0.043429] [d2 loss: 0.040572]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 451/500] [Batch 600/676] [D loss: -0.008290] [G loss: -0.071728] [d1 loss: 0.065313] [d2 loss: 0.075835]  [sq d1 d2: 0.000111]  [num0: 18.000000] [num1 46.000000]
[Epoch 451/500] [Batch 620/676] [D loss: 0.000754] [G loss: -0.052706] [d1 loss: 0.108081] [d2 loss: 0.068804]  [sq d1 d2: 0.001543]  [num0: 16.000000] [num1 48.000000]
[Epoch 451/500] [Batch 640/676] [D loss: -0.008496] [G loss: -0.060218] [d1 loss: 0.156263] [d2 loss: 0.122325]  [sq d1 d2: 0.001152]  [num0: 15.000000] [num1 49.000000]
[Epoch 451/500] [Batch 660/676] [D loss: 0.004755] [G loss: -0.048221] [d1 loss: 0.099202] [d2 loss: 0.100795]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 452/500] [Batch 0/676] [D loss: -0.003252] [G loss: -0.067844] [d1 loss: 0.171126] [d2 loss: 0.135602]  [sq d1 d2: 0.001262]  [num0: 18.000000] [num1 46.000000]
[Epoch 452/500] [Batch 20/676] [D loss: -0.016053] [G loss: -0.048051] [d1 loss: 0.063581] [d2 loss: 0.058521]  [sq d1 d2: 0.000026]  [num0: 13.000000] [num1 51.000000]
[Epoch 452/500] [Batch 40/676] [D loss: -0.007828] [G loss: -0.041112] [d1 loss: 0.028859] [d2 loss: 0.102284]  [sq d1 d2: 0.005391]  [num0: 13.000000] [num1 51.000000]
[Epoch 452/500] [Batch 60/676] [D loss: -0.007210] [G loss: -0.064096] [d1 loss: 0.085677] [d2 loss: 0.084383]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 452/500] [Batch 80/676] [D loss: -0.019200] [G loss: -0.062062] [d1 loss: 0.021644] [d2 loss: 0.021337]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 100/676] [D loss: -0.006784] [G loss: -0.050971] [d1 loss: 0.048069] [d2 loss: 0.072607]  [sq d1 d2: 0.000602]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 120/676] [D loss: -0.020860] [G loss: -0.044083] [d1 loss: 0.067105] [d2 loss: 0.082117]  [sq d1 d2: 0.000225]  [num0: 21.000000] [num1 43.000000]
[Epoch 452/500] [Batch 140/676] [D loss: 0.002848] [G loss: -0.056784] [d1 loss: 0.097973] [d2 loss: 0.105876]  [sq d1 d2: 0.000062]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 160/676] [D loss: -0.000735] [G loss: -0.064160] [d1 loss: 0.097197] [d2 loss: 0.094226]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 452/500] [Batch 180/676] [D loss: -0.011143] [G loss: -0.079361] [d1 loss: 0.019076] [d2 loss: 0.015685]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 452/500] [Batch 200/676] [D loss: -0.006864] [G loss: -0.087425] [d1 loss: 0.137683] [d2 loss: 0.082134]  [sq d1 d2: 0.003086]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 220/676] [D loss: -0.013939] [G loss: -0.097641] [d1 loss: 0.110870] [d2 loss: 0.117017]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 452/500] [Batch 240/676] [D loss: 0.006065] [G loss: -0.075520] [d1 loss: 0.109491] [d2 loss: 0.113852]  [sq d1 d2: 0.000019]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 260/676] [D loss: -0.008486] [G loss: -0.077462] [d1 loss: 0.059204] [d2 loss: 0.058496]  [sq d1 d2: 0.000001]  [num0: 12.000000] [num1 52.000000]
[Epoch 452/500] [Batch 280/676] [D loss: 0.002599] [G loss: -0.087903] [d1 loss: 0.105867] [d2 loss: 0.071887]  [sq d1 d2: 0.001155]  [num0: 20.000000] [num1 44.000000]
[Epoch 452/500] [Batch 300/676] [D loss: -0.010699] [G loss: -0.076067] [d1 loss: 0.045439] [d2 loss: 0.050430]  [sq d1 d2: 0.000025]  [num0: 18.000000] [num1 46.000000]
[Epoch 452/500] [Batch 320/676] [D loss: -0.003569] [G loss: -0.069650] [d1 loss: 0.066742] [d2 loss: 0.080037]  [sq d1 d2: 0.000177]  [num0: 18.000000] [num1 46.000000]
[Epoch 452/500] [Batch 340/676] [D loss: -0.034234] [G loss: -0.075489] [d1 loss: 0.026224] [d2 loss: 0.026147]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 360/676] [D loss: 0.003006] [G loss: -0.076410] [d1 loss: 0.093020] [d2 loss: 0.103583]  [sq d1 d2: 0.000112]  [num0: 13.000000] [num1 51.000000]
[Epoch 452/500] [Batch 380/676] [D loss: -0.010419] [G loss: -0.065725] [d1 loss: 0.105044] [d2 loss: 0.097709]  [sq d1 d2: 0.000054]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 400/676] [D loss: -0.009378] [G loss: -0.055518] [d1 loss: 0.088272] [d2 loss: 0.078103]  [sq d1 d2: 0.000103]  [num0: 21.000000] [num1 43.000000]
[Epoch 452/500] [Batch 420/676] [D loss: 0.008891] [G loss: -0.060522] [d1 loss: 0.038021] [d2 loss: 0.047545]  [sq d1 d2: 0.000091]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 440/676] [D loss: -0.011691] [G loss: -0.032050] [d1 loss: 0.059419] [d2 loss: 0.032400]  [sq d1 d2: 0.000730]  [num0: 18.000000] [num1 46.000000]
[Epoch 452/500] [Batch 460/676] [D loss: -0.004834] [G loss: -0.025478] [d1 loss: 0.038841] [d2 loss: 0.019180]  [sq d1 d2: 0.000387]  [num0: 14.000000] [num1 50.000000]
[Epoch 452/500] [Batch 480/676] [D loss: -0.002821] [G loss: -0.022877] [d1 loss: 0.063132] [d2 loss: 0.066132]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 452/500] [Batch 500/676] [D loss: -0.005848] [G loss: -0.011182] [d1 loss: 0.209007] [d2 loss: 0.225627]  [sq d1 d2: 0.000276]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 520/676] [D loss: -0.014910] [G loss: -0.012305] [d1 loss: 0.185739] [d2 loss: 0.095886]  [sq d1 d2: 0.008073]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 540/676] [D loss: -0.017355] [G loss: -0.044804] [d1 loss: 0.038190] [d2 loss: 0.036103]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 452/500] [Batch 560/676] [D loss: -0.006499] [G loss: -0.047547] [d1 loss: 0.141804] [d2 loss: 0.153093]  [sq d1 d2: 0.000127]  [num0: 16.000000] [num1 48.000000]
[Epoch 452/500] [Batch 580/676] [D loss: -0.011368] [G loss: -0.022358] [d1 loss: 0.065316] [d2 loss: 0.077339]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 600/676] [D loss: -0.002716] [G loss: -0.019687] [d1 loss: 0.065364] [d2 loss: 0.089310]  [sq d1 d2: 0.000573]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 620/676] [D loss: -0.004575] [G loss: -0.013885] [d1 loss: 0.223280] [d2 loss: 0.121209]  [sq d1 d2: 0.010419]  [num0: 15.000000] [num1 49.000000]

[Epoch 452/500] [Batch 640/676] [D loss: -0.016999] [G loss: -0.007108] [d1 loss: 0.062916] [d2 loss: 0.059313]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 452/500] [Batch 660/676] [D loss: -0.002136] [G loss: 0.010335] [d1 loss: 0.030700] [d2 loss: 0.036546]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 453/500] [Batch 0/676] [D loss: -0.023907] [G loss: -0.005776] [d1 loss: 0.055277] [d2 loss: 0.055659]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 453/500] [Batch 20/676] [D loss: -0.010689] [G loss: 0.002861] [d1 loss: 0.076615] [d2 loss: 0.080691]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 453/500] [Batch 40/676] [D loss: -0.022578] [G loss: 0.009541] [d1 loss: 0.102614] [d2 loss: 0.093999]  [sq d1 d2: 0.000074]  [num0: 21.000000] [num1 43.000000]
[Epoch 453/500] [Batch 60/676] [D loss: -0.003485] [G loss: 0.013145] [d1 loss: 0.087498] [d2 loss: 0.084213]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 453/500] [Batch 80/676] [D loss: -0.002425] [G loss: 0.020005] [d1 loss: 0.061487] [d2 loss: 0.077384]  [sq d1 d2: 0.000253]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 100/676] [D loss: -0.010987] [G loss: 0.023445] [d1 loss: 0.106058] [d2 loss: 0.137153]  [sq d1 d2: 0.000967]  [num0: 20.000000] [num1 44.000000]
[Epoch 453/500] [Batch 120/676] [D loss: -0.000730] [G loss: -0.005189] [d1 loss: 0.082936] [d2 loss: 0.073846]  [sq d1 d2: 0.000083]  [num0: 17.000000] [num1 47.000000]
[Epoch 453/500] [Batch 140/676] [D loss: -0.009568] [G loss: 0.015412] [d1 loss: 0.129940] [d2 loss: 0.117587]  [sq d1 d2: 0.000153]  [num0: 17.000000] [num1 47.000000]
[Epoch 453/500] [Batch 160/676] [D loss: -0.003659] [G loss: 0.017133] [d1 loss: 0.045735] [d2 loss: 0.074412]  [sq d1 d2: 0.000822]  [num0: 18.000000] [num1 46.000000]
[Epoch 453/500] [Batch 180/676] [D loss: -0.006982] [G loss: 0.018507] [d1 loss: 0.077682] [d2 loss: 0.084143]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 453/500] [Batch 200/676] [D loss: -0.009700] [G loss: 0.010095] [d1 loss: 0.177762] [d2 loss: 0.087559]  [sq d1 d2: 0.008136]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 220/676] [D loss: -0.004150] [G loss: 0.034690] [d1 loss: 0.143929] [d2 loss: 0.104528]  [sq d1 d2: 0.001552]  [num0: 19.000000] [num1 45.000000]
[Epoch 453/500] [Batch 240/676] [D loss: -0.009931] [G loss: 0.028568] [d1 loss: 0.026562] [d2 loss: 0.031575]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 453/500] [Batch 260/676] [D loss: -0.005980] [G loss: 0.017592] [d1 loss: 0.059963] [d2 loss: 0.066541]  [sq d1 d2: 0.000043]  [num0: 18.000000] [num1 46.000000]
[Epoch 453/500] [Batch 280/676] [D loss: -0.018584] [G loss: 0.033246] [d1 loss: 0.100230] [d2 loss: 0.134189]  [sq d1 d2: 0.001153]  [num0: 12.000000] [num1 52.000000]
[Epoch 453/500] [Batch 300/676] [D loss: -0.006585] [G loss: 0.033757] [d1 loss: 0.039970] [d2 loss: 0.042800]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 453/500] [Batch 320/676] [D loss: -0.019919] [G loss: 0.055266] [d1 loss: 0.072900] [d2 loss: 0.076880]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 453/500] [Batch 340/676] [D loss: -0.013927] [G loss: 0.027021] [d1 loss: 0.035375] [d2 loss: 0.038537]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 360/676] [D loss: -0.003630] [G loss: 0.027263] [d1 loss: 0.038436] [d2 loss: 0.045077]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 453/500] [Batch 380/676] [D loss: -0.024032] [G loss: 0.029139] [d1 loss: 0.059370] [d2 loss: 0.066794]  [sq d1 d2: 0.000055]  [num0: 14.000000] [num1 50.000000]
[Epoch 453/500] [Batch 400/676] [D loss: -0.013742] [G loss: 0.023372] [d1 loss: 0.063533] [d2 loss: 0.085416]  [sq d1 d2: 0.000479]  [num0: 10.000000] [num1 54.000000]
[Epoch 453/500] [Batch 420/676] [D loss: 0.000080] [G loss: 0.004131] [d1 loss: 0.045297] [d2 loss: 0.057345]  [sq d1 d2: 0.000145]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 440/676] [D loss: -0.004924] [G loss: -0.016549] [d1 loss: 0.056090] [d2 loss: 0.064986]  [sq d1 d2: 0.000079]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 460/676] [D loss: -0.007109] [G loss: -0.002237] [d1 loss: 0.041416] [d2 loss: 0.054161]  [sq d1 d2: 0.000162]  [num0: 19.000000] [num1 45.000000]
[Epoch 453/500] [Batch 480/676] [D loss: -0.010397] [G loss: -0.017542] [d1 loss: 0.047909] [d2 loss: 0.122737]  [sq d1 d2: 0.005599]  [num0: 16.000000] [num1 48.000000]
[Epoch 453/500] [Batch 500/676] [D loss: -0.011157] [G loss: -0.045839] [d1 loss: 0.059062] [d2 loss: 0.053301]  [sq d1 d2: 0.000033]  [num0: 19.000000] [num1 45.000000]
[Epoch 453/500] [Batch 520/676] [D loss: -0.022866] [G loss: -0.016109] [d1 loss: 0.033901] [d2 loss: 0.037175]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 453/500] [Batch 540/676] [D loss: -0.006804] [G loss: -0.035686] [d1 loss: 0.073681] [d2 loss: 0.062806]  [sq d1 d2: 0.000118]  [num0: 16.000000] [num1 48.000000]
[Epoch 453/500] [Batch 560/676] [D loss: -0.014800] [G loss: -0.041229] [d1 loss: 0.031571] [d2 loss: 0.031540]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 453/500] [Batch 580/676] [D loss: 0.004641] [G loss: -0.054402] [d1 loss: 0.042860] [d2 loss: 0.048848]  [sq d1 d2: 0.000036]  [num0: 13.000000] [num1 51.000000]
[Epoch 453/500] [Batch 600/676] [D loss: -0.021180] [G loss: -0.054180] [d1 loss: 0.056841] [d2 loss: 0.055918]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 453/500] [Batch 620/676] [D loss: -0.003228] [G loss: -0.077789] [d1 loss: 0.048462] [d2 loss: 0.073189]  [sq d1 d2: 0.000611]  [num0: 19.000000] [num1 45.000000]
[Epoch 453/500] [Batch 640/676] [D loss: -0.003905] [G loss: -0.070482] [d1 loss: 0.118170] [d2 loss: 0.116500]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 453/500] [Batch 660/676] [D loss: 0.000661] [G loss: -0.085043] [d1 loss: 0.036964] [d2 loss: 0.024268]  [sq d1 d2: 0.000161]  [num0: 14.000000] [num1 50.000000]
[Epoch 454/500] [Batch 0/676] [D loss: -0.017288] [G loss: -0.085653] [d1 loss: 0.047954] [d2 loss: 0.049391]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 454/500] [Batch 20/676] [D loss: -0.006438] [G loss: -0.072727] [d1 loss: 0.057261] [d2 loss: 0.063891]  [sq d1 d2: 0.000044]  [num0: 19.000000] [num1 45.000000]
[Epoch 454/500] [Batch 40/676] [D loss: -0.008744] [G loss: -0.071602] [d1 loss: 0.083745] [d2 loss: 0.111226]  [sq d1 d2: 0.000755]  [num0: 21.000000] [num1 43.000000]
[Epoch 454/500] [Batch 60/676] [D loss: -0.016227] [G loss: -0.056935] [d1 loss: 0.037394] [d2 loss: 0.047915]  [sq d1 d2: 0.000111]  [num0: 14.000000] [num1 50.000000]
[Epoch 454/500] [Batch 80/676] [D loss: -0.014276] [G loss: -0.045260] [d1 loss: 0.059494] [d2 loss: 0.045857]  [sq d1 d2: 0.000186]  [num0: 18.000000] [num1 46.000000]
[Epoch 454/500] [Batch 100/676] [D loss: -0.008049] [G loss: -0.075355] [d1 loss: 0.113191] [d2 loss: 0.092792]  [sq d1 d2: 0.000416]  [num0: 11.000000] [num1 53.000000]
[Epoch 454/500] [Batch 120/676] [D loss: -0.007278] [G loss: -0.059350] [d1 loss: 0.020452] [d2 loss: 0.021508]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 140/676] [D loss: -0.005350] [G loss: -0.046955] [d1 loss: 0.102667] [d2 loss: 0.100914]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 454/500] [Batch 160/676] [D loss: -0.010078] [G loss: -0.043207] [d1 loss: 0.023310] [d2 loss: 0.018115]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 454/500] [Batch 180/676] [D loss: -0.007002] [G loss: -0.025442] [d1 loss: 0.122257] [d2 loss: 0.083812]  [sq d1 d2: 0.001478]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 200/676] [D loss: -0.008211] [G loss: -0.022565] [d1 loss: 0.046157] [d2 loss: 0.040877]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 220/676] [D loss: -0.007476] [G loss: -0.009906] [d1 loss: 0.046787] [d2 loss: 0.050970]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 240/676] [D loss: -0.003346] [G loss: -0.011282] [d1 loss: 0.093330] [d2 loss: 0.078248]  [sq d1 d2: 0.000227]  [num0: 18.000000] [num1 46.000000]
[Epoch 454/500] [Batch 260/676] [D loss: -0.006172] [G loss: -0.003582] [d1 loss: 0.085831] [d2 loss: 0.097224]  [sq d1 d2: 0.000130]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 280/676] [D loss: -0.012344] [G loss: -0.018411] [d1 loss: 0.046304] [d2 loss: 0.050643]  [sq d1 d2: 0.000019]  [num0: 19.000000] [num1 45.000000]

[Epoch 454/500] [Batch 300/676] [D loss: 0.000678] [G loss: -0.001714] [d1 loss: 0.074283] [d2 loss: 0.064383]  [sq d1 d2: 0.000098]  [num0: 16.000000] [num1 48.000000]
[Epoch 454/500] [Batch 320/676] [D loss: -0.009581] [G loss: 0.006523] [d1 loss: 0.046176] [d2 loss: 0.050061]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]
[Epoch 454/500] [Batch 340/676] [D loss: -0.011986] [G loss: -0.007129] [d1 loss: 0.031957] [d2 loss: 0.030029]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 360/676] [D loss: -0.009003] [G loss: 0.008270] [d1 loss: 0.093827] [d2 loss: 0.069030]  [sq d1 d2: 0.000615]  [num0: 17.000000] [num1 47.000000]
[Epoch 454/500] [Batch 380/676] [D loss: -0.006071] [G loss: 0.014121] [d1 loss: 0.082398] [d2 loss: 0.076527]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 454/500] [Batch 400/676] [D loss: -0.010213] [G loss: 0.013823] [d1 loss: 0.074198] [d2 loss: 0.064889]  [sq d1 d2: 0.000087]  [num0: 13.000000] [num1 51.000000]
[Epoch 454/500] [Batch 420/676] [D loss: -0.008787] [G loss: 0.015260] [d1 loss: 0.039368] [d2 loss: 0.035183]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]
[Epoch 454/500] [Batch 440/676] [D loss: -0.004683] [G loss: 0.003331] [d1 loss: 0.042965] [d2 loss: 0.046241]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 454/500] [Batch 460/676] [D loss: -0.003166] [G loss: -0.015858] [d1 loss: 0.089251] [d2 loss: 0.045519]  [sq d1 d2: 0.001913]  [num0: 12.000000] [num1 52.000000]
[Epoch 454/500] [Batch 480/676] [D loss: -0.000671] [G loss: -0.000421] [d1 loss: 0.031809] [d2 loss: 0.037671]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 454/500] [Batch 500/676] [D loss: 0.000075] [G loss: -0.034303] [d1 loss: 0.035400] [d2 loss: 0.037479]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 454/500] [Batch 520/676] [D loss: -0.000577] [G loss: -0.022745] [d1 loss: 0.082471] [d2 loss: 0.088871]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 454/500] [Batch 540/676] [D loss: -0.001335] [G loss: -0.013541] [d1 loss: 0.060650] [d2 loss: 0.072738]  [sq d1 d2: 0.000146]  [num0: 14.000000] [num1 50.000000]
[Epoch 454/500] [Batch 560/676] [D loss: 0.000790] [G loss: -0.029902] [d1 loss: 0.013061] [d2 loss: 0.012809]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 454/500] [Batch 580/676] [D loss: -0.007574] [G loss: -0.029619] [d1 loss: 0.021568] [d2 loss: 0.019801]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 454/500] [Batch 600/676] [D loss: -0.003192] [G loss: -0.047070] [d1 loss: 0.022428] [d2 loss: 0.026666]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 454/500] [Batch 620/676] [D loss: -0.007044] [G loss: -0.034548] [d1 loss: 0.062320] [d2 loss: 0.042985]  [sq d1 d2: 0.000374]  [num0: 17.000000] [num1 47.000000]
[Epoch 454/500] [Batch 640/676] [D loss: -0.006834] [G loss: -0.050831] [d1 loss: 0.104332] [d2 loss: 0.136734]  [sq d1 d2: 0.001050]  [num0: 16.000000] [num1 48.000000]
[Epoch 454/500] [Batch 660/676] [D loss: -0.009512] [G loss: -0.033677] [d1 loss: 0.066408] [d2 loss: 0.091985]  [sq d1 d2: 0.000654]  [num0: 13.000000] [num1 51.000000]
[Epoch 455/500] [Batch 0/676] [D loss: -0.006815] [G loss: -0.037893] [d1 loss: 0.040422] [d2 loss: 0.046257]  [sq d1 d2: 0.000034]  [num0: 14.000000] [num1 50.000000]
[Epoch 455/500] [Batch 20/676] [D loss: -0.007292] [G loss: -0.053424] [d1 loss: 0.028727] [d2 loss: 0.035375]  [sq d1 d2: 0.000044]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 40/676] [D loss: -0.011126] [G loss: -0.038861] [d1 loss: 0.008161] [d2 loss: 0.009152]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 455/500] [Batch 60/676] [D loss: -0.010539] [G loss: -0.041845] [d1 loss: 0.080566] [d2 loss: 0.072739]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 80/676] [D loss: -0.009555] [G loss: -0.048229] [d1 loss: 0.089264] [d2 loss: 0.084581]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 455/500] [Batch 100/676] [D loss: -0.007332] [G loss: -0.019137] [d1 loss: 0.024202] [d2 loss: 0.036311]  [sq d1 d2: 0.000147]  [num0: 11.000000] [num1 53.000000]
[Epoch 455/500] [Batch 120/676] [D loss: -0.009274] [G loss: -0.018940] [d1 loss: 0.068903] [d2 loss: 0.101663]  [sq d1 d2: 0.001073]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 140/676] [D loss: -0.008405] [G loss: -0.035619] [d1 loss: 0.028309] [d2 loss: 0.021020]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 160/676] [D loss: -0.010858] [G loss: -0.035582] [d1 loss: 0.063927] [d2 loss: 0.047624]  [sq d1 d2: 0.000266]  [num0: 17.000000] [num1 47.000000]
[Epoch 455/500] [Batch 180/676] [D loss: -0.005541] [G loss: -0.035124] [d1 loss: 0.021989] [d2 loss: 0.019152]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 455/500] [Batch 200/676] [D loss: 0.002282] [G loss: 0.000303] [d1 loss: 0.093196] [d2 loss: 0.090989]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 455/500] [Batch 220/676] [D loss: -0.003903] [G loss: -0.021569] [d1 loss: 0.075291] [d2 loss: 0.094399]  [sq d1 d2: 0.000365]  [num0: 14.000000] [num1 50.000000]
[Epoch 455/500] [Batch 240/676] [D loss: -0.014102] [G loss: -0.014726] [d1 loss: 0.035503] [d2 loss: 0.006360]  [sq d1 d2: 0.000849]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 260/676] [D loss: -0.010622] [G loss: -0.000422] [d1 loss: 0.052238] [d2 loss: 0.046852]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 455/500] [Batch 280/676] [D loss: -0.008427] [G loss: -0.004033] [d1 loss: 0.046370] [d2 loss: 0.039150]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 300/676] [D loss: -0.015423] [G loss: 0.012897] [d1 loss: 0.083360] [d2 loss: 0.098827]  [sq d1 d2: 0.000239]  [num0: 13.000000] [num1 51.000000]
[Epoch 455/500] [Batch 320/676] [D loss: -0.004126] [G loss: -0.028475] [d1 loss: 0.031614] [d2 loss: 0.033278]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 340/676] [D loss: -0.006893] [G loss: -0.018034] [d1 loss: 0.053086] [d2 loss: 0.076230]  [sq d1 d2: 0.000536]  [num0: 12.000000] [num1 52.000000]
[Epoch 455/500] [Batch 360/676] [D loss: -0.007867] [G loss: 0.016260] [d1 loss: 0.052305] [d2 loss: 0.057001]  [sq d1 d2: 0.000022]  [num0: 12.000000] [num1 52.000000]
[Epoch 455/500] [Batch 380/676] [D loss: -0.020917] [G loss: 0.009869] [d1 loss: 0.092919] [d2 loss: 0.095349]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 455/500] [Batch 400/676] [D loss: -0.002568] [G loss: 0.012721] [d1 loss: 0.045040] [d2 loss: 0.041237]  [sq d1 d2: 0.000014]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 420/676] [D loss: -0.016156] [G loss: 0.002854] [d1 loss: 0.043963] [d2 loss: 0.044544]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 455/500] [Batch 440/676] [D loss: -0.004180] [G loss: 0.016259] [d1 loss: 0.029606] [d2 loss: 0.024974]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 460/676] [D loss: -0.004430] [G loss: 0.022899] [d1 loss: 0.053552] [d2 loss: 0.056175]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 480/676] [D loss: 0.004289] [G loss: 0.013914] [d1 loss: 0.077252] [d2 loss: 0.073970]  [sq d1 d2: 0.000011]  [num0: 20.000000] [num1 44.000000]
[Epoch 455/500] [Batch 500/676] [D loss: -0.014783] [G loss: 0.002809] [d1 loss: 0.094392] [d2 loss: 0.098497]  [sq d1 d2: 0.000017]  [num0: 20.000000] [num1 44.000000]
[Epoch 455/500] [Batch 520/676] [D loss: -0.019142] [G loss: 0.010952] [d1 loss: 0.084117] [d2 loss: 0.116429]  [sq d1 d2: 0.001044]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 540/676] [D loss: 0.001223] [G loss: 0.000353] [d1 loss: 0.056422] [d2 loss: 0.043672]  [sq d1 d2: 0.000163]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 560/676] [D loss: -0.007613] [G loss: 0.012498] [d1 loss: 0.064214] [d2 loss: 0.060028]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 580/676] [D loss: -0.008260] [G loss: 0.015466] [d1 loss: 0.144197] [d2 loss: 0.107911]  [sq d1 d2: 0.001317]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 600/676] [D loss: -0.008168] [G loss: 0.011545] [d1 loss: 0.034739] [d2 loss: 0.023183]  [sq d1 d2: 0.000134]  [num0: 15.000000] [num1 49.000000]
[Epoch 455/500] [Batch 620/676] [D loss: -0.012941] [G loss: 0.012658] [d1 loss: 0.039540] [d2 loss: 0.034046]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]

[Epoch 455/500] [Batch 640/676] [D loss: -0.006167] [G loss: 0.022617] [d1 loss: 0.079116] [d2 loss: 0.055425]  [sq d1 d2: 0.000561]  [num0: 16.000000] [num1 48.000000]
[Epoch 455/500] [Batch 660/676] [D loss: -0.005644] [G loss: 0.015457] [d1 loss: 0.032375] [d2 loss: 0.034573]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 456/500] [Batch 0/676] [D loss: -0.017297] [G loss: 0.002487] [d1 loss: 0.037201] [d2 loss: 0.045822]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 456/500] [Batch 20/676] [D loss: 0.001384] [G loss: -0.014870] [d1 loss: 0.039591] [d2 loss: 0.039994]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 456/500] [Batch 40/676] [D loss: -0.011032] [G loss: -0.044658] [d1 loss: 0.034965] [d2 loss: 0.041937]  [sq d1 d2: 0.000049]  [num0: 17.000000] [num1 47.000000]
[Epoch 456/500] [Batch 60/676] [D loss: -0.014280] [G loss: -0.024542] [d1 loss: 0.059363] [d2 loss: 0.064845]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 80/676] [D loss: -0.010544] [G loss: -0.037355] [d1 loss: 0.022676] [d2 loss: 0.016475]  [sq d1 d2: 0.000038]  [num0: 17.000000] [num1 47.000000]
[Epoch 456/500] [Batch 100/676] [D loss: -0.011511] [G loss: -0.024228] [d1 loss: 0.023033] [d2 loss: 0.024563]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 120/676] [D loss: -0.009989] [G loss: -0.005319] [d1 loss: 0.071568] [d2 loss: 0.079915]  [sq d1 d2: 0.000070]  [num0: 12.000000] [num1 52.000000]
[Epoch 456/500] [Batch 140/676] [D loss: -0.006015] [G loss: -0.017009] [d1 loss: 0.018169] [d2 loss: 0.024592]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 160/676] [D loss: -0.003742] [G loss: 0.003007] [d1 loss: 0.066590] [d2 loss: 0.098320]  [sq d1 d2: 0.001007]  [num0: 12.000000] [num1 52.000000]
[Epoch 456/500] [Batch 180/676] [D loss: -0.000652] [G loss: -0.018303] [d1 loss: 0.028415] [d2 loss: 0.030379]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 200/676] [D loss: 0.000676] [G loss: 0.006268] [d1 loss: 0.053190] [d2 loss: 0.056154]  [sq d1 d2: 0.000009]  [num0: 11.000000] [num1 53.000000]
[Epoch 456/500] [Batch 220/676] [D loss: -0.006568] [G loss: 0.015505] [d1 loss: 0.021653] [d2 loss: 0.024948]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 456/500] [Batch 240/676] [D loss: -0.005224] [G loss: 0.028183] [d1 loss: 0.038178] [d2 loss: 0.035049]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 260/676] [D loss: -0.013413] [G loss: 0.073221] [d1 loss: 0.069129] [d2 loss: 0.068388]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 456/500] [Batch 280/676] [D loss: -0.012958] [G loss: 0.092617] [d1 loss: 0.082465] [d2 loss: 0.102162]  [sq d1 d2: 0.000388]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 300/676] [D loss: 0.001689] [G loss: 0.101967] [d1 loss: 0.021078] [d2 loss: 0.028845]  [sq d1 d2: 0.000060]  [num0: 14.000000] [num1 50.000000]
[Epoch 456/500] [Batch 320/676] [D loss: -0.018466] [G loss: 0.100581] [d1 loss: 0.071522] [d2 loss: 0.046601]  [sq d1 d2: 0.000621]  [num0: 22.000000] [num1 42.000000]
[Epoch 456/500] [Batch 340/676] [D loss: -0.010148] [G loss: 0.112177] [d1 loss: 0.038402] [d2 loss: 0.026768]  [sq d1 d2: 0.000135]  [num0: 19.000000] [num1 45.000000]
[Epoch 456/500] [Batch 360/676] [D loss: -0.012150] [G loss: 0.066391] [d1 loss: 0.042694] [d2 loss: 0.033091]  [sq d1 d2: 0.000092]  [num0: 17.000000] [num1 47.000000]
[Epoch 456/500] [Batch 380/676] [D loss: -0.015611] [G loss: 0.082140] [d1 loss: 0.032327] [d2 loss: 0.028696]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 456/500] [Batch 400/676] [D loss: -0.008607] [G loss: 0.036991] [d1 loss: 0.053186] [d2 loss: 0.062416]  [sq d1 d2: 0.000085]  [num0: 13.000000] [num1 51.000000]
[Epoch 456/500] [Batch 420/676] [D loss: -0.017109] [G loss: 0.007384] [d1 loss: 0.039892] [d2 loss: 0.042991]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 456/500] [Batch 440/676] [D loss: -0.007155] [G loss: 0.022984] [d1 loss: 0.031474] [d2 loss: 0.019931]  [sq d1 d2: 0.000133]  [num0: 14.000000] [num1 50.000000]
[Epoch 456/500] [Batch 460/676] [D loss: -0.009095] [G loss: 0.012389] [d1 loss: 0.119002] [d2 loss: 0.103651]  [sq d1 d2: 0.000236]  [num0: 18.000000] [num1 46.000000]
[Epoch 456/500] [Batch 480/676] [D loss: -0.010295] [G loss: 0.009805] [d1 loss: 0.033060] [d2 loss: 0.032701]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 456/500] [Batch 500/676] [D loss: -0.004077] [G loss: 0.008344] [d1 loss: 0.036644] [d2 loss: 0.035626]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 456/500] [Batch 520/676] [D loss: 0.005070] [G loss: 0.001269] [d1 loss: 0.035630] [d2 loss: 0.032254]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 456/500] [Batch 540/676] [D loss: -0.009650] [G loss: 0.004792] [d1 loss: 0.074000] [d2 loss: 0.050444]  [sq d1 d2: 0.000555]  [num0: 13.000000] [num1 51.000000]
[Epoch 456/500] [Batch 560/676] [D loss: -0.017668] [G loss: -0.043440] [d1 loss: 0.022833] [d2 loss: 0.026883]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 456/500] [Batch 580/676] [D loss: -0.017972] [G loss: -0.060047] [d1 loss: 0.024879] [d2 loss: 0.024062]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 600/676] [D loss: -0.017444] [G loss: -0.057082] [d1 loss: 0.145515] [d2 loss: 0.138257]  [sq d1 d2: 0.000053]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 620/676] [D loss: -0.009024] [G loss: -0.077572] [d1 loss: 0.079089] [d2 loss: 0.050456]  [sq d1 d2: 0.000820]  [num0: 18.000000] [num1 46.000000]
[Epoch 456/500] [Batch 640/676] [D loss: -0.007231] [G loss: -0.084541] [d1 loss: 0.019185] [d2 loss: 0.019222]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 456/500] [Batch 660/676] [D loss: -0.021714] [G loss: -0.081010] [d1 loss: 0.038607] [d2 loss: 0.036211]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 457/500] [Batch 0/676] [D loss: 0.003541] [G loss: -0.032292] [d1 loss: 0.068742] [d2 loss: 0.061170]  [sq d1 d2: 0.000057]  [num0: 17.000000] [num1 47.000000]
[Epoch 457/500] [Batch 20/676] [D loss: -0.022030] [G loss: -0.052522] [d1 loss: 0.060700] [d2 loss: 0.054103]  [sq d1 d2: 0.000044]  [num0: 15.000000] [num1 49.000000]
[Epoch 457/500] [Batch 40/676] [D loss: -0.015079] [G loss: -0.064056] [d1 loss: 0.103736] [d2 loss: 0.091090]  [sq d1 d2: 0.000160]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 60/676] [D loss: -0.001691] [G loss: -0.068720] [d1 loss: 0.049666] [d2 loss: 0.077920]  [sq d1 d2: 0.000798]  [num0: 17.000000] [num1 47.000000]
[Epoch 457/500] [Batch 80/676] [D loss: -0.014175] [G loss: -0.041853] [d1 loss: 0.043758] [d2 loss: 0.050111]  [sq d1 d2: 0.000040]  [num0: 18.000000] [num1 46.000000]
[Epoch 457/500] [Batch 100/676] [D loss: 0.007424] [G loss: -0.036673] [d1 loss: 0.039214] [d2 loss: 0.034570]  [sq d1 d2: 0.000022]  [num0: 13.000000] [num1 51.000000]
[Epoch 457/500] [Batch 120/676] [D loss: -0.006043] [G loss: -0.037099] [d1 loss: 0.050495] [d2 loss: 0.053598]  [sq d1 d2: 0.000010]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 140/676] [D loss: 0.000427] [G loss: -0.039989] [d1 loss: 0.100094] [d2 loss: 0.099955]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 457/500] [Batch 160/676] [D loss: -0.008373] [G loss: -0.046366] [d1 loss: 0.026367] [d2 loss: 0.046382]  [sq d1 d2: 0.000401]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 180/676] [D loss: -0.015846] [G loss: -0.039230] [d1 loss: 0.044241] [d2 loss: 0.057996]  [sq d1 d2: 0.000189]  [num0: 10.000000] [num1 54.000000]
[Epoch 457/500] [Batch 200/676] [D loss: -0.015751] [G loss: -0.040701] [d1 loss: 0.017943] [d2 loss: 0.019741]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 457/500] [Batch 220/676] [D loss: -0.012876] [G loss: -0.049138] [d1 loss: 0.025243] [d2 loss: 0.029157]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 240/676] [D loss: -0.002234] [G loss: -0.015713] [d1 loss: 0.083452] [d2 loss: 0.073153]  [sq d1 d2: 0.000106]  [num0: 12.000000] [num1 52.000000]
[Epoch 457/500] [Batch 260/676] [D loss: -0.015346] [G loss: -0.031307] [d1 loss: 0.253384] [d2 loss: 0.131656]  [sq d1 d2: 0.014818]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 280/676] [D loss: -0.008913] [G loss: -0.011423] [d1 loss: 0.034709] [d2 loss: 0.034994]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]

[Epoch 457/500] [Batch 300/676] [D loss: -0.001801] [G loss: -0.005779] [d1 loss: 0.037692] [d2 loss: 0.025675]  [sq d1 d2: 0.000144]  [num0: 13.000000] [num1 51.000000]
[Epoch 457/500] [Batch 320/676] [D loss: 0.001147] [G loss: -0.003410] [d1 loss: 0.032266] [d2 loss: 0.029714]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 340/676] [D loss: -0.019034] [G loss: -0.015947] [d1 loss: 0.064806] [d2 loss: 0.069798]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 360/676] [D loss: -0.012118] [G loss: 0.009731] [d1 loss: 0.027312] [d2 loss: 0.028397]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 457/500] [Batch 380/676] [D loss: -0.004232] [G loss: -0.021506] [d1 loss: 0.060286] [d2 loss: 0.036171]  [sq d1 d2: 0.000582]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 400/676] [D loss: -0.011619] [G loss: -0.043672] [d1 loss: 0.046095] [d2 loss: 0.061887]  [sq d1 d2: 0.000249]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 420/676] [D loss: -0.009937] [G loss: -0.022166] [d1 loss: 0.093123] [d2 loss: 0.070438]  [sq d1 d2: 0.000515]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 440/676] [D loss: -0.011632] [G loss: -0.020254] [d1 loss: 0.060992] [d2 loss: 0.075606]  [sq d1 d2: 0.000214]  [num0: 19.000000] [num1 45.000000]
[Epoch 457/500] [Batch 460/676] [D loss: -0.009090] [G loss: -0.032645] [d1 loss: 0.082171] [d2 loss: 0.073045]  [sq d1 d2: 0.000083]  [num0: 13.000000] [num1 51.000000]
[Epoch 457/500] [Batch 480/676] [D loss: -0.013882] [G loss: -0.043855] [d1 loss: 0.029669] [d2 loss: 0.029982]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 457/500] [Batch 500/676] [D loss: -0.005006] [G loss: -0.054618] [d1 loss: 0.073658] [d2 loss: 0.091032]  [sq d1 d2: 0.000302]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 520/676] [D loss: -0.004297] [G loss: -0.048478] [d1 loss: 0.042161] [d2 loss: 0.029923]  [sq d1 d2: 0.000150]  [num0: 17.000000] [num1 47.000000]
[Epoch 457/500] [Batch 540/676] [D loss: -0.006699] [G loss: -0.046332] [d1 loss: 0.043474] [d2 loss: 0.097070]  [sq d1 d2: 0.002872]  [num0: 15.000000] [num1 49.000000]
[Epoch 457/500] [Batch 560/676] [D loss: -0.000308] [G loss: -0.048205] [d1 loss: 0.094445] [d2 loss: 0.104181]  [sq d1 d2: 0.000095]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 580/676] [D loss: -0.002192] [G loss: -0.046867] [d1 loss: 0.091395] [d2 loss: 0.073565]  [sq d1 d2: 0.000318]  [num0: 16.000000] [num1 48.000000]
[Epoch 457/500] [Batch 600/676] [D loss: -0.009043] [G loss: -0.032628] [d1 loss: 0.046369] [d2 loss: 0.019527]  [sq d1 d2: 0.000720]  [num0: 15.000000] [num1 49.000000]
[Epoch 457/500] [Batch 620/676] [D loss: -0.002958] [G loss: -0.040495] [d1 loss: 0.086037] [d2 loss: 0.039163]  [sq d1 d2: 0.002197]  [num0: 20.000000] [num1 44.000000]
[Epoch 457/500] [Batch 640/676] [D loss: -0.002255] [G loss: -0.036062] [d1 loss: 0.050760] [d2 loss: 0.045900]  [sq d1 d2: 0.000024]  [num0: 14.000000] [num1 50.000000]
[Epoch 457/500] [Batch 660/676] [D loss: -0.006261] [G loss: -0.042583] [d1 loss: 0.021005] [d2 loss: 0.026477]  [sq d1 d2: 0.000030]  [num0: 14.000000] [num1 50.000000]
[Epoch 458/500] [Batch 0/676] [D loss: -0.006836] [G loss: -0.031135] [d1 loss: 0.061310] [d2 loss: 0.050308]  [sq d1 d2: 0.000121]  [num0: 12.000000] [num1 52.000000]
[Epoch 458/500] [Batch 20/676] [D loss: -0.010850] [G loss: -0.027397] [d1 loss: 0.027307] [d2 loss: 0.050012]  [sq d1 d2: 0.000515]  [num0: 18.000000] [num1 46.000000]
[Epoch 458/500] [Batch 40/676] [D loss: -0.003877] [G loss: -0.023963] [d1 loss: 0.023421] [d2 loss: 0.021831]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 458/500] [Batch 60/676] [D loss: -0.011780] [G loss: -0.015724] [d1 loss: 0.062001] [d2 loss: 0.063128]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 458/500] [Batch 80/676] [D loss: -0.004641] [G loss: -0.022612] [d1 loss: 0.077437] [d2 loss: 0.076648]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 458/500] [Batch 100/676] [D loss: -0.012586] [G loss: -0.009783] [d1 loss: 0.072684] [d2 loss: 0.063357]  [sq d1 d2: 0.000087]  [num0: 20.000000] [num1 44.000000]
[Epoch 458/500] [Batch 120/676] [D loss: -0.021964] [G loss: -0.024725] [d1 loss: 0.090776] [d2 loss: 0.093458]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 458/500] [Batch 140/676] [D loss: -0.004381] [G loss: -0.008976] [d1 loss: 0.085587] [d2 loss: 0.075151]  [sq d1 d2: 0.000109]  [num0: 18.000000] [num1 46.000000]
[Epoch 458/500] [Batch 160/676] [D loss: 0.007048] [G loss: -0.022434] [d1 loss: 0.039045] [d2 loss: 0.045981]  [sq d1 d2: 0.000048]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 180/676] [D loss: -0.010374] [G loss: 0.009603] [d1 loss: 0.051233] [d2 loss: 0.046205]  [sq d1 d2: 0.000025]  [num0: 21.000000] [num1 43.000000]
[Epoch 458/500] [Batch 200/676] [D loss: 0.000711] [G loss: 0.003525] [d1 loss: 0.026380] [d2 loss: 0.036776]  [sq d1 d2: 0.000108]  [num0: 12.000000] [num1 52.000000]
[Epoch 458/500] [Batch 220/676] [D loss: -0.001995] [G loss: 0.009770] [d1 loss: 0.016356] [d2 loss: 0.023065]  [sq d1 d2: 0.000045]  [num0: 14.000000] [num1 50.000000]
[Epoch 458/500] [Batch 240/676] [D loss: -0.005761] [G loss: 0.005848] [d1 loss: 0.050483] [d2 loss: 0.051982]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 458/500] [Batch 260/676] [D loss: -0.015196] [G loss: -0.002947] [d1 loss: 0.043317] [d2 loss: 0.032299]  [sq d1 d2: 0.000121]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 280/676] [D loss: -0.001778] [G loss: 0.000460] [d1 loss: 0.060222] [d2 loss: 0.062282]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 458/500] [Batch 300/676] [D loss: -0.011612] [G loss: 0.003587] [d1 loss: 0.035191] [d2 loss: 0.033235]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 458/500] [Batch 320/676] [D loss: -0.000842] [G loss: 0.001876] [d1 loss: 0.084247] [d2 loss: 0.082978]  [sq d1 d2: 0.000002]  [num0: 20.000000] [num1 44.000000]
[Epoch 458/500] [Batch 340/676] [D loss: -0.021830] [G loss: 0.016828] [d1 loss: 0.063748] [d2 loss: 0.071648]  [sq d1 d2: 0.000062]  [num0: 20.000000] [num1 44.000000]
[Epoch 458/500] [Batch 360/676] [D loss: -0.022303] [G loss: 0.017636] [d1 loss: 0.021041] [d2 loss: 0.015506]  [sq d1 d2: 0.000031]  [num0: 13.000000] [num1 51.000000]
[Epoch 458/500] [Batch 380/676] [D loss: -0.018920] [G loss: 0.018881] [d1 loss: 0.072294] [d2 loss: 0.092760]  [sq d1 d2: 0.000419]  [num0: 13.000000] [num1 51.000000]
[Epoch 458/500] [Batch 400/676] [D loss: -0.014394] [G loss: 0.009984] [d1 loss: 0.031522] [d2 loss: 0.040505]  [sq d1 d2: 0.000081]  [num0: 18.000000] [num1 46.000000]
[Epoch 458/500] [Batch 420/676] [D loss: -0.017638] [G loss: 0.012800] [d1 loss: 0.038127] [d2 loss: 0.041089]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 458/500] [Batch 440/676] [D loss: -0.004536] [G loss: 0.020703] [d1 loss: 0.070489] [d2 loss: 0.061345]  [sq d1 d2: 0.000084]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 460/676] [D loss: -0.009758] [G loss: 0.029094] [d1 loss: 0.106118] [d2 loss: 0.113544]  [sq d1 d2: 0.000055]  [num0: 17.000000] [num1 47.000000]
[Epoch 458/500] [Batch 480/676] [D loss: -0.002933] [G loss: 0.032942] [d1 loss: 0.084847] [d2 loss: 0.093628]  [sq d1 d2: 0.000077]  [num0: 16.000000] [num1 48.000000]
[Epoch 458/500] [Batch 500/676] [D loss: -0.002848] [G loss: 0.030129] [d1 loss: 0.120026] [d2 loss: 0.072170]  [sq d1 d2: 0.002290]  [num0: 17.000000] [num1 47.000000]
[Epoch 458/500] [Batch 520/676] [D loss: -0.014233] [G loss: 0.006377] [d1 loss: 0.058127] [d2 loss: 0.052593]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 540/676] [D loss: 0.013837] [G loss: 0.031380] [d1 loss: 0.059880] [d2 loss: 0.047869]  [sq d1 d2: 0.000144]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 560/676] [D loss: -0.009799] [G loss: 0.024284] [d1 loss: 0.063107] [d2 loss: 0.043938]  [sq d1 d2: 0.000367]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 580/676] [D loss: -0.003499] [G loss: -0.004981] [d1 loss: 0.044282] [d2 loss: 0.046405]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 458/500] [Batch 600/676] [D loss: -0.007090] [G loss: 0.003900] [d1 loss: 0.075442] [d2 loss: 0.070539]  [sq d1 d2: 0.000024]  [num0: 19.000000] [num1 45.000000]
[Epoch 458/500] [Batch 620/676] [D loss: -0.018050] [G loss: -0.016812] [d1 loss: 0.062030] [d2 loss: 0.079229]  [sq d1 d2: 0.000296]  [num0: 18.000000] [num1 46.000000]

[Epoch 458/500] [Batch 640/676] [D loss: -0.005190] [G loss: 0.006565] [d1 loss: 0.054073] [d2 loss: 0.056653]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 458/500] [Batch 660/676] [D loss: -0.001143] [G loss: 0.005079] [d1 loss: 0.026583] [d2 loss: 0.032410]  [sq d1 d2: 0.000034]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 0/676] [D loss: -0.005838] [G loss: -0.022700] [d1 loss: 0.157881] [d2 loss: 0.121150]  [sq d1 d2: 0.001349]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 20/676] [D loss: 0.009167] [G loss: -0.017099] [d1 loss: 0.067973] [d2 loss: 0.075277]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 459/500] [Batch 40/676] [D loss: -0.018875] [G loss: -0.013149] [d1 loss: 0.053249] [d2 loss: 0.075396]  [sq d1 d2: 0.000490]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 60/676] [D loss: -0.009304] [G loss: 0.009737] [d1 loss: 0.075209] [d2 loss: 0.048160]  [sq d1 d2: 0.000732]  [num0: 19.000000] [num1 45.000000]
[Epoch 459/500] [Batch 80/676] [D loss: -0.007283] [G loss: -0.005456] [d1 loss: 0.079727] [d2 loss: 0.074034]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 459/500] [Batch 100/676] [D loss: -0.016815] [G loss: 0.001744] [d1 loss: 0.038012] [d2 loss: 0.028408]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 120/676] [D loss: -0.013543] [G loss: 0.001482] [d1 loss: 0.022807] [d2 loss: 0.023573]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 459/500] [Batch 140/676] [D loss: -0.014136] [G loss: 0.008140] [d1 loss: 0.087593] [d2 loss: 0.100716]  [sq d1 d2: 0.000172]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 160/676] [D loss: -0.007018] [G loss: -0.011120] [d1 loss: 0.130730] [d2 loss: 0.125857]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 180/676] [D loss: -0.012734] [G loss: -0.001169] [d1 loss: 0.043831] [d2 loss: 0.038311]  [sq d1 d2: 0.000030]  [num0: 20.000000] [num1 44.000000]
[Epoch 459/500] [Batch 200/676] [D loss: -0.018588] [G loss: -0.001393] [d1 loss: 0.015128] [d2 loss: 0.018035]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 220/676] [D loss: -0.023088] [G loss: -0.005138] [d1 loss: 0.039830] [d2 loss: 0.038436]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 240/676] [D loss: -0.014180] [G loss: 0.007663] [d1 loss: 0.050623] [d2 loss: 0.056251]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 260/676] [D loss: -0.021005] [G loss: -0.001837] [d1 loss: 0.030676] [d2 loss: 0.031037]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 459/500] [Batch 280/676] [D loss: -0.015781] [G loss: -0.022275] [d1 loss: 0.091610] [d2 loss: 0.090459]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 459/500] [Batch 300/676] [D loss: -0.017468] [G loss: -0.014113] [d1 loss: 0.036818] [d2 loss: 0.044474]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 320/676] [D loss: -0.000754] [G loss: -0.027668] [d1 loss: 0.096638] [d2 loss: 0.086653]  [sq d1 d2: 0.000100]  [num0: 14.000000] [num1 50.000000]
[Epoch 459/500] [Batch 340/676] [D loss: -0.005407] [G loss: -0.032606] [d1 loss: 0.058609] [d2 loss: 0.059259]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 360/676] [D loss: -0.004117] [G loss: -0.052946] [d1 loss: 0.098607] [d2 loss: 0.062663]  [sq d1 d2: 0.001292]  [num0: 15.000000] [num1 49.000000]
[Epoch 459/500] [Batch 380/676] [D loss: -0.015101] [G loss: -0.025690] [d1 loss: 0.021012] [d2 loss: 0.018198]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 400/676] [D loss: -0.014654] [G loss: -0.050799] [d1 loss: 0.054691] [d2 loss: 0.061579]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 459/500] [Batch 420/676] [D loss: -0.009271] [G loss: -0.061843] [d1 loss: 0.067433] [d2 loss: 0.070340]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 440/676] [D loss: -0.025407] [G loss: -0.033909] [d1 loss: 0.030761] [d2 loss: 0.016184]  [sq d1 d2: 0.000212]  [num0: 14.000000] [num1 50.000000]
[Epoch 459/500] [Batch 460/676] [D loss: -0.018950] [G loss: -0.002878] [d1 loss: 0.111088] [d2 loss: 0.125703]  [sq d1 d2: 0.000214]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 480/676] [D loss: -0.024819] [G loss: 0.004240] [d1 loss: 0.083576] [d2 loss: 0.092475]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 459/500] [Batch 500/676] [D loss: -0.009109] [G loss: -0.036649] [d1 loss: 0.110838] [d2 loss: 0.095874]  [sq d1 d2: 0.000224]  [num0: 13.000000] [num1 51.000000]
[Epoch 459/500] [Batch 520/676] [D loss: -0.002284] [G loss: -0.011548] [d1 loss: 0.104575] [d2 loss: 0.099565]  [sq d1 d2: 0.000025]  [num0: 14.000000] [num1 50.000000]
[Epoch 459/500] [Batch 540/676] [D loss: 0.002318] [G loss: -0.028808] [d1 loss: 0.144663] [d2 loss: 0.079096]  [sq d1 d2: 0.004299]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 560/676] [D loss: -0.009666] [G loss: -0.034402] [d1 loss: 0.062759] [d2 loss: 0.061301]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 459/500] [Batch 580/676] [D loss: -0.005384] [G loss: -0.008670] [d1 loss: 0.009003] [d2 loss: 0.011064]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 459/500] [Batch 600/676] [D loss: -0.002504] [G loss: -0.033580] [d1 loss: 0.072910] [d2 loss: 0.063358]  [sq d1 d2: 0.000091]  [num0: 17.000000] [num1 47.000000]
[Epoch 459/500] [Batch 620/676] [D loss: 0.005844] [G loss: -0.016899] [d1 loss: 0.114456] [d2 loss: 0.110596]  [sq d1 d2: 0.000015]  [num0: 19.000000] [num1 45.000000]
[Epoch 459/500] [Batch 640/676] [D loss: -0.008301] [G loss: -0.007183] [d1 loss: 0.045010] [d2 loss: 0.049002]  [sq d1 d2: 0.000016]  [num0: 20.000000] [num1 44.000000]
[Epoch 459/500] [Batch 660/676] [D loss: -0.010791] [G loss: 0.007480] [d1 loss: 0.074119] [d2 loss: 0.045572]  [sq d1 d2: 0.000815]  [num0: 17.000000] [num1 47.000000]
[Epoch 460/500] [Batch 0/676] [D loss: -0.010533] [G loss: -0.023543] [d1 loss: 0.043669] [d2 loss: 0.056209]  [sq d1 d2: 0.000157]  [num0: 14.000000] [num1 50.000000]
[Epoch 460/500] [Batch 20/676] [D loss: -0.006148] [G loss: -0.030459] [d1 loss: 0.082326] [d2 loss: 0.150605]  [sq d1 d2: 0.004662]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 40/676] [D loss: -0.004587] [G loss: -0.035095] [d1 loss: 0.063436] [d2 loss: 0.068626]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 60/676] [D loss: -0.000474] [G loss: -0.026713] [d1 loss: 0.053826] [d2 loss: 0.063040]  [sq d1 d2: 0.000085]  [num0: 21.000000] [num1 43.000000]
[Epoch 460/500] [Batch 80/676] [D loss: -0.018764] [G loss: -0.037437] [d1 loss: 0.085247] [d2 loss: 0.100349]  [sq d1 d2: 0.000228]  [num0: 18.000000] [num1 46.000000]
[Epoch 460/500] [Batch 100/676] [D loss: -0.025493] [G loss: -0.056493] [d1 loss: 0.132786] [d2 loss: 0.117323]  [sq d1 d2: 0.000239]  [num0: 17.000000] [num1 47.000000]
[Epoch 460/500] [Batch 120/676] [D loss: -0.016627] [G loss: -0.055092] [d1 loss: 0.015807] [d2 loss: 0.016266]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 460/500] [Batch 140/676] [D loss: -0.015617] [G loss: -0.043290] [d1 loss: 0.012858] [d2 loss: 0.020015]  [sq d1 d2: 0.000051]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 160/676] [D loss: -0.010750] [G loss: -0.064205] [d1 loss: 0.096967] [d2 loss: 0.093245]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 460/500] [Batch 180/676] [D loss: 0.003346] [G loss: -0.042289] [d1 loss: 0.041152] [d2 loss: 0.045296]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 200/676] [D loss: -0.013714] [G loss: -0.056503] [d1 loss: 0.053712] [d2 loss: 0.047047]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 460/500] [Batch 220/676] [D loss: 0.003378] [G loss: -0.055018] [d1 loss: 0.109673] [d2 loss: 0.086145]  [sq d1 d2: 0.000554]  [num0: 21.000000] [num1 43.000000]
[Epoch 460/500] [Batch 240/676] [D loss: -0.004024] [G loss: -0.065790] [d1 loss: 0.083093] [d2 loss: 0.074489]  [sq d1 d2: 0.000074]  [num0: 14.000000] [num1 50.000000]
[Epoch 460/500] [Batch 260/676] [D loss: -0.003225] [G loss: -0.057623] [d1 loss: 0.072832] [d2 loss: 0.080941]  [sq d1 d2: 0.000066]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 280/676] [D loss: -0.014901] [G loss: -0.060879] [d1 loss: 0.087851] [d2 loss: 0.066774]  [sq d1 d2: 0.000444]  [num0: 16.000000] [num1 48.000000]

[Epoch 460/500] [Batch 300/676] [D loss: -0.010037] [G loss: -0.047086] [d1 loss: 0.034051] [d2 loss: 0.038193]  [sq d1 d2: 0.000017]  [num0: 18.000000] [num1 46.000000]
[Epoch 460/500] [Batch 320/676] [D loss: -0.004207] [G loss: -0.067457] [d1 loss: 0.030029] [d2 loss: 0.021202]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 340/676] [D loss: -0.023793] [G loss: -0.069166] [d1 loss: 0.048538] [d2 loss: 0.035477]  [sq d1 d2: 0.000171]  [num0: 14.000000] [num1 50.000000]
[Epoch 460/500] [Batch 360/676] [D loss: -0.018507] [G loss: -0.050338] [d1 loss: 0.043389] [d2 loss: 0.050613]  [sq d1 d2: 0.000052]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 380/676] [D loss: 0.010304] [G loss: -0.026894] [d1 loss: 0.064335] [d2 loss: 0.086050]  [sq d1 d2: 0.000472]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 400/676] [D loss: -0.021486] [G loss: -0.033572] [d1 loss: 0.056878] [d2 loss: 0.051360]  [sq d1 d2: 0.000030]  [num0: 12.000000] [num1 52.000000]
[Epoch 460/500] [Batch 420/676] [D loss: -0.002309] [G loss: -0.014075] [d1 loss: 0.098138] [d2 loss: 0.081764]  [sq d1 d2: 0.000268]  [num0: 17.000000] [num1 47.000000]
[Epoch 460/500] [Batch 440/676] [D loss: -0.004338] [G loss: -0.001354] [d1 loss: 0.032187] [d2 loss: 0.029845]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 460/676] [D loss: -0.014206] [G loss: 0.022756] [d1 loss: 0.037420] [d2 loss: 0.037333]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 460/500] [Batch 480/676] [D loss: 0.001579] [G loss: -0.004959] [d1 loss: 0.043090] [d2 loss: 0.025990]  [sq d1 d2: 0.000292]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 500/676] [D loss: -0.007802] [G loss: 0.033249] [d1 loss: 0.050052] [d2 loss: 0.062366]  [sq d1 d2: 0.000152]  [num0: 13.000000] [num1 51.000000]
[Epoch 460/500] [Batch 520/676] [D loss: -0.000876] [G loss: 0.023063] [d1 loss: 0.087119] [d2 loss: 0.071316]  [sq d1 d2: 0.000250]  [num0: 19.000000] [num1 45.000000]
[Epoch 460/500] [Batch 540/676] [D loss: -0.004855] [G loss: 0.010987] [d1 loss: 0.102746] [d2 loss: 0.105318]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 560/676] [D loss: -0.007065] [G loss: 0.004033] [d1 loss: 0.073215] [d2 loss: 0.069939]  [sq d1 d2: 0.000011]  [num0: 11.000000] [num1 53.000000]
[Epoch 460/500] [Batch 580/676] [D loss: -0.010979] [G loss: 0.006509] [d1 loss: 0.207420] [d2 loss: 0.205067]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 600/676] [D loss: -0.019413] [G loss: -0.012023] [d1 loss: 0.042063] [d2 loss: 0.047036]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 460/500] [Batch 620/676] [D loss: -0.011437] [G loss: -0.019495] [d1 loss: 0.044146] [d2 loss: 0.049918]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 460/500] [Batch 640/676] [D loss: -0.020370] [G loss: -0.048757] [d1 loss: 0.040057] [d2 loss: 0.038386]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 460/500] [Batch 660/676] [D loss: -0.015356] [G loss: -0.065044] [d1 loss: 0.045378] [d2 loss: 0.062006]  [sq d1 d2: 0.000277]  [num0: 15.000000] [num1 49.000000]
[Epoch 461/500] [Batch 0/676] [D loss: -0.020565] [G loss: -0.049741] [d1 loss: 0.047408] [d2 loss: 0.041499]  [sq d1 d2: 0.000035]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 20/676] [D loss: 0.002919] [G loss: -0.063876] [d1 loss: 0.097937] [d2 loss: 0.112459]  [sq d1 d2: 0.000211]  [num0: 11.000000] [num1 53.000000]
[Epoch 461/500] [Batch 40/676] [D loss: -0.007856] [G loss: -0.085896] [d1 loss: 0.046729] [d2 loss: 0.038780]  [sq d1 d2: 0.000063]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 60/676] [D loss: -0.008968] [G loss: -0.093792] [d1 loss: 0.047228] [d2 loss: 0.047109]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 461/500] [Batch 80/676] [D loss: -0.000210] [G loss: -0.106514] [d1 loss: 0.050369] [d2 loss: 0.046677]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 461/500] [Batch 100/676] [D loss: -0.003861] [G loss: -0.101442] [d1 loss: 0.067482] [d2 loss: 0.073308]  [sq d1 d2: 0.000034]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 120/676] [D loss: -0.009767] [G loss: -0.098370] [d1 loss: 0.135618] [d2 loss: 0.102651]  [sq d1 d2: 0.001087]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 140/676] [D loss: -0.013680] [G loss: -0.125042] [d1 loss: 0.082400] [d2 loss: 0.074165]  [sq d1 d2: 0.000068]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 160/676] [D loss: -0.011474] [G loss: -0.117643] [d1 loss: 0.065478] [d2 loss: 0.062540]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 461/500] [Batch 180/676] [D loss: -0.009256] [G loss: -0.108535] [d1 loss: 0.072535] [d2 loss: 0.072104]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 461/500] [Batch 200/676] [D loss: -0.011166] [G loss: -0.116452] [d1 loss: 0.086752] [d2 loss: 0.068480]  [sq d1 d2: 0.000334]  [num0: 17.000000] [num1 47.000000]
[Epoch 461/500] [Batch 220/676] [D loss: -0.011778] [G loss: -0.088277] [d1 loss: 0.077778] [d2 loss: 0.086972]  [sq d1 d2: 0.000085]  [num0: 18.000000] [num1 46.000000]
[Epoch 461/500] [Batch 240/676] [D loss: 0.007284] [G loss: -0.108241] [d1 loss: 0.128354] [d2 loss: 0.124295]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 260/676] [D loss: 0.000337] [G loss: -0.099770] [d1 loss: 0.023235] [d2 loss: 0.026974]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 461/500] [Batch 280/676] [D loss: -0.005094] [G loss: -0.107319] [d1 loss: 0.059495] [d2 loss: 0.045178]  [sq d1 d2: 0.000205]  [num0: 14.000000] [num1 50.000000]
[Epoch 461/500] [Batch 300/676] [D loss: -0.003303] [G loss: -0.075450] [d1 loss: 0.022891] [d2 loss: 0.027433]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 461/500] [Batch 320/676] [D loss: 0.000743] [G loss: -0.035849] [d1 loss: 0.032845] [d2 loss: 0.034039]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 340/676] [D loss: -0.004112] [G loss: -0.029391] [d1 loss: 0.021990] [d2 loss: 0.016666]  [sq d1 d2: 0.000028]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 360/676] [D loss: -0.008538] [G loss: -0.035627] [d1 loss: 0.127878] [d2 loss: 0.117030]  [sq d1 d2: 0.000118]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 380/676] [D loss: -0.013030] [G loss: -0.014029] [d1 loss: 0.139038] [d2 loss: 0.112543]  [sq d1 d2: 0.000702]  [num0: 20.000000] [num1 44.000000]
[Epoch 461/500] [Batch 400/676] [D loss: -0.012589] [G loss: -0.000362] [d1 loss: 0.051041] [d2 loss: 0.040796]  [sq d1 d2: 0.000105]  [num0: 13.000000] [num1 51.000000]
[Epoch 461/500] [Batch 420/676] [D loss: -0.009834] [G loss: -0.004243] [d1 loss: 0.069512] [d2 loss: 0.084814]  [sq d1 d2: 0.000234]  [num0: 14.000000] [num1 50.000000]
[Epoch 461/500] [Batch 440/676] [D loss: -0.019584] [G loss: 0.010240] [d1 loss: 0.062067] [d2 loss: 0.054387]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 461/500] [Batch 460/676] [D loss: -0.019408] [G loss: -0.018332] [d1 loss: 0.221961] [d2 loss: 0.105353]  [sq d1 d2: 0.013597]  [num0: 20.000000] [num1 44.000000]
[Epoch 461/500] [Batch 480/676] [D loss: -0.026714] [G loss: -0.003104] [d1 loss: 0.062686] [d2 loss: 0.064744]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 500/676] [D loss: -0.012146] [G loss: -0.032998] [d1 loss: 0.044369] [d2 loss: 0.024853]  [sq d1 d2: 0.000381]  [num0: 19.000000] [num1 45.000000]
[Epoch 461/500] [Batch 520/676] [D loss: -0.013101] [G loss: -0.031816] [d1 loss: 0.075669] [d2 loss: 0.072565]  [sq d1 d2: 0.000010]  [num0: 20.000000] [num1 44.000000]
[Epoch 461/500] [Batch 540/676] [D loss: -0.007736] [G loss: -0.015684] [d1 loss: 0.029391] [d2 loss: 0.023902]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 461/500] [Batch 560/676] [D loss: -0.005602] [G loss: -0.036037] [d1 loss: 0.010081] [d2 loss: 0.012511]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 461/500] [Batch 580/676] [D loss: 0.001844] [G loss: -0.038189] [d1 loss: 0.020540] [d2 loss: 0.023122]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 461/500] [Batch 600/676] [D loss: 0.004797] [G loss: -0.066988] [d1 loss: 0.058733] [d2 loss: 0.058962]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 461/500] [Batch 620/676] [D loss: -0.000328] [G loss: -0.059128] [d1 loss: 0.055873] [d2 loss: 0.051270]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]

[Epoch 461/500] [Batch 640/676] [D loss: -0.013178] [G loss: -0.066813] [d1 loss: 0.040786] [d2 loss: 0.033638]  [sq d1 d2: 0.000051]  [num0: 14.000000] [num1 50.000000]
[Epoch 461/500] [Batch 660/676] [D loss: -0.005873] [G loss: -0.082428] [d1 loss: 0.075916] [d2 loss: 0.078833]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 0/676] [D loss: -0.009449] [G loss: -0.072359] [d1 loss: 0.047210] [d2 loss: 0.063418]  [sq d1 d2: 0.000263]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 20/676] [D loss: -0.014545] [G loss: -0.095497] [d1 loss: 0.116579] [d2 loss: 0.114234]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 40/676] [D loss: -0.020054] [G loss: -0.061009] [d1 loss: 0.068881] [d2 loss: 0.065290]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 60/676] [D loss: -0.013463] [G loss: -0.057201] [d1 loss: 0.139540] [d2 loss: 0.092138]  [sq d1 d2: 0.002247]  [num0: 18.000000] [num1 46.000000]
[Epoch 462/500] [Batch 80/676] [D loss: -0.024175] [G loss: -0.050154] [d1 loss: 0.047017] [d2 loss: 0.054258]  [sq d1 d2: 0.000052]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 100/676] [D loss: -0.009086] [G loss: -0.032664] [d1 loss: 0.069419] [d2 loss: 0.040231]  [sq d1 d2: 0.000852]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 120/676] [D loss: -0.014112] [G loss: -0.008093] [d1 loss: 0.107947] [d2 loss: 0.124711]  [sq d1 d2: 0.000281]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 140/676] [D loss: -0.004223] [G loss: -0.016684] [d1 loss: 0.053379] [d2 loss: 0.053234]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 160/676] [D loss: 0.005534] [G loss: -0.004634] [d1 loss: 0.068771] [d2 loss: 0.075530]  [sq d1 d2: 0.000046]  [num0: 11.000000] [num1 53.000000]
[Epoch 462/500] [Batch 180/676] [D loss: 0.013167] [G loss: 0.016097] [d1 loss: 0.083478] [d2 loss: 0.078123]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 462/500] [Batch 200/676] [D loss: -0.006115] [G loss: -0.013158] [d1 loss: 0.031295] [d2 loss: 0.017844]  [sq d1 d2: 0.000181]  [num0: 13.000000] [num1 51.000000]
[Epoch 462/500] [Batch 220/676] [D loss: -0.012177] [G loss: -0.005170] [d1 loss: 1.639592] [d2 loss: 0.198022]  [sq d1 d2: 2.078126]  [num0: 16.000000] [num1 48.000000]
[Epoch 462/500] [Batch 240/676] [D loss: -0.010009] [G loss: 0.002923] [d1 loss: 0.077410] [d2 loss: 0.094336]  [sq d1 d2: 0.000287]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 260/676] [D loss: -0.017205] [G loss: 0.013267] [d1 loss: 0.022874] [d2 loss: 0.023543]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 462/500] [Batch 280/676] [D loss: -0.016845] [G loss: 0.007949] [d1 loss: 0.065817] [d2 loss: 0.049302]  [sq d1 d2: 0.000273]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 300/676] [D loss: -0.016127] [G loss: 0.012887] [d1 loss: 0.138121] [d2 loss: 0.120601]  [sq d1 d2: 0.000307]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 320/676] [D loss: -0.009000] [G loss: 0.014033] [d1 loss: 0.037453] [d2 loss: 0.044018]  [sq d1 d2: 0.000043]  [num0: 22.000000] [num1 42.000000]
[Epoch 462/500] [Batch 340/676] [D loss: -0.004741] [G loss: 0.002450] [d1 loss: 0.058197] [d2 loss: 0.065201]  [sq d1 d2: 0.000049]  [num0: 18.000000] [num1 46.000000]
[Epoch 462/500] [Batch 360/676] [D loss: -0.007688] [G loss: 0.022369] [d1 loss: 0.040840] [d2 loss: 0.038262]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 462/500] [Batch 380/676] [D loss: -0.007706] [G loss: 0.015669] [d1 loss: 0.045098] [d2 loss: 0.045350]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 462/500] [Batch 400/676] [D loss: -0.008311] [G loss: 0.020992] [d1 loss: 0.025908] [d2 loss: 0.034962]  [sq d1 d2: 0.000082]  [num0: 18.000000] [num1 46.000000]
[Epoch 462/500] [Batch 420/676] [D loss: 0.014374] [G loss: 0.016086] [d1 loss: 0.055264] [d2 loss: 0.057275]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 440/676] [D loss: 0.005758] [G loss: 0.001968] [d1 loss: 0.106119] [d2 loss: 0.057864]  [sq d1 d2: 0.002329]  [num0: 12.000000] [num1 52.000000]
[Epoch 462/500] [Batch 460/676] [D loss: 0.000107] [G loss: -0.029479] [d1 loss: 0.034389] [d2 loss: 0.049675]  [sq d1 d2: 0.000234]  [num0: 18.000000] [num1 46.000000]
[Epoch 462/500] [Batch 480/676] [D loss: -0.012760] [G loss: -0.045218] [d1 loss: 0.124944] [d2 loss: 0.108586]  [sq d1 d2: 0.000268]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 500/676] [D loss: -0.014299] [G loss: -0.047311] [d1 loss: 0.057740] [d2 loss: 0.044364]  [sq d1 d2: 0.000179]  [num0: 13.000000] [num1 51.000000]
[Epoch 462/500] [Batch 520/676] [D loss: -0.011216] [G loss: -0.029265] [d1 loss: 0.048786] [d2 loss: 0.029791]  [sq d1 d2: 0.000361]  [num0: 16.000000] [num1 48.000000]
[Epoch 462/500] [Batch 540/676] [D loss: -0.011388] [G loss: -0.038523] [d1 loss: 0.082774] [d2 loss: 0.093352]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 560/676] [D loss: -0.023467] [G loss: -0.043767] [d1 loss: 0.046535] [d2 loss: 0.047917]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 580/676] [D loss: -0.001125] [G loss: -0.077749] [d1 loss: 0.025699] [d2 loss: 0.023592]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 600/676] [D loss: -0.009347] [G loss: -0.094760] [d1 loss: 0.021552] [d2 loss: 0.036112]  [sq d1 d2: 0.000212]  [num0: 15.000000] [num1 49.000000]
[Epoch 462/500] [Batch 620/676] [D loss: 0.004469] [G loss: -0.075464] [d1 loss: 0.048478] [d2 loss: 0.033015]  [sq d1 d2: 0.000239]  [num0: 14.000000] [num1 50.000000]
[Epoch 462/500] [Batch 640/676] [D loss: -0.007792] [G loss: -0.065407] [d1 loss: 0.053637] [d2 loss: 0.047249]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 462/500] [Batch 660/676] [D loss: 0.008207] [G loss: -0.058504] [d1 loss: 0.118636] [d2 loss: 0.122340]  [sq d1 d2: 0.000014]  [num0: 19.000000] [num1 45.000000]
[Epoch 463/500] [Batch 0/676] [D loss: -0.005612] [G loss: -0.054476] [d1 loss: 0.044573] [d2 loss: 0.049106]  [sq d1 d2: 0.000021]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 20/676] [D loss: -0.002370] [G loss: -0.042619] [d1 loss: 0.058364] [d2 loss: 0.068004]  [sq d1 d2: 0.000093]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 40/676] [D loss: 0.002826] [G loss: -0.025853] [d1 loss: 0.020822] [d2 loss: 0.018596]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 463/500] [Batch 60/676] [D loss: -0.000247] [G loss: -0.042341] [d1 loss: 0.073790] [d2 loss: 0.086476]  [sq d1 d2: 0.000161]  [num0: 17.000000] [num1 47.000000]
[Epoch 463/500] [Batch 80/676] [D loss: -0.009567] [G loss: -0.052666] [d1 loss: 0.016940] [d2 loss: 0.007306]  [sq d1 d2: 0.000093]  [num0: 14.000000] [num1 50.000000]
[Epoch 463/500] [Batch 100/676] [D loss: -0.013105] [G loss: -0.076813] [d1 loss: 0.042622] [d2 loss: 0.031747]  [sq d1 d2: 0.000118]  [num0: 17.000000] [num1 47.000000]
[Epoch 463/500] [Batch 120/676] [D loss: -0.013906] [G loss: -0.048185] [d1 loss: 0.066246] [d2 loss: 0.040482]  [sq d1 d2: 0.000664]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 140/676] [D loss: -0.012569] [G loss: -0.042641] [d1 loss: 0.032399] [d2 loss: 0.023299]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 160/676] [D loss: -0.019890] [G loss: -0.052489] [d1 loss: 0.084334] [d2 loss: 0.074204]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 180/676] [D loss: -0.024041] [G loss: -0.021165] [d1 loss: 0.050482] [d2 loss: 0.050277]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 200/676] [D loss: -0.022033] [G loss: -0.027797] [d1 loss: 0.044534] [d2 loss: 0.045825]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 220/676] [D loss: 0.001675] [G loss: -0.037600] [d1 loss: 0.058931] [d2 loss: 0.059041]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 463/500] [Batch 240/676] [D loss: 0.007968] [G loss: -0.057357] [d1 loss: 0.066728] [d2 loss: 0.049057]  [sq d1 d2: 0.000312]  [num0: 15.000000] [num1 49.000000]

[Epoch 463/500] [Batch 260/676] [D loss: 0.001521] [G loss: -0.055520] [d1 loss: 0.110672] [d2 loss: 0.078856]  [sq d1 d2: 0.001012]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 280/676] [D loss: 0.005415] [G loss: -0.065073] [d1 loss: 0.052503] [d2 loss: 0.056438]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 300/676] [D loss: -0.012992] [G loss: -0.053700] [d1 loss: 0.013036] [d2 loss: 0.015965]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 320/676] [D loss: -0.002171] [G loss: -0.053436] [d1 loss: 0.047694] [d2 loss: 0.042579]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 340/676] [D loss: 0.002981] [G loss: -0.066997] [d1 loss: 0.058289] [d2 loss: 0.058780]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 360/676] [D loss: -0.012753] [G loss: -0.068707] [d1 loss: 0.104374] [d2 loss: 0.104403]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 380/676] [D loss: 0.001962] [G loss: -0.079975] [d1 loss: 0.058057] [d2 loss: 0.062164]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 400/676] [D loss: -0.016823] [G loss: -0.078770] [d1 loss: 0.057683] [d2 loss: 0.055009]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 463/500] [Batch 420/676] [D loss: -0.027460] [G loss: -0.081856] [d1 loss: 0.040657] [d2 loss: 0.056287]  [sq d1 d2: 0.000244]  [num0: 18.000000] [num1 46.000000]
[Epoch 463/500] [Batch 440/676] [D loss: -0.015959] [G loss: -0.112471] [d1 loss: 0.031412] [d2 loss: 0.033010]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 463/500] [Batch 460/676] [D loss: -0.017324] [G loss: -0.106506] [d1 loss: 0.132053] [d2 loss: 0.122080]  [sq d1 d2: 0.000099]  [num0: 20.000000] [num1 44.000000]
[Epoch 463/500] [Batch 480/676] [D loss: -0.013195] [G loss: -0.086566] [d1 loss: 0.037138] [d2 loss: 0.035952]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 463/500] [Batch 500/676] [D loss: -0.000653] [G loss: -0.117354] [d1 loss: 0.033590] [d2 loss: 0.028321]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]
[Epoch 463/500] [Batch 520/676] [D loss: -0.007815] [G loss: -0.064293] [d1 loss: 0.064855] [d2 loss: 0.055645]  [sq d1 d2: 0.000085]  [num0: 14.000000] [num1 50.000000]
[Epoch 463/500] [Batch 540/676] [D loss: 0.016537] [G loss: -0.036667] [d1 loss: 0.104065] [d2 loss: 0.098385]  [sq d1 d2: 0.000032]  [num0: 16.000000] [num1 48.000000]
[Epoch 463/500] [Batch 560/676] [D loss: -0.009481] [G loss: -0.048662] [d1 loss: 0.088848] [d2 loss: 0.079750]  [sq d1 d2: 0.000083]  [num0: 17.000000] [num1 47.000000]
[Epoch 463/500] [Batch 580/676] [D loss: 0.006985] [G loss: -0.018023] [d1 loss: 0.030980] [d2 loss: 0.042591]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 463/500] [Batch 600/676] [D loss: -0.001725] [G loss: -0.030906] [d1 loss: 0.022628] [d2 loss: 0.017169]  [sq d1 d2: 0.000030]  [num0: 13.000000] [num1 51.000000]
[Epoch 463/500] [Batch 620/676] [D loss: -0.008367] [G loss: -0.038221] [d1 loss: 0.050915] [d2 loss: 0.062359]  [sq d1 d2: 0.000131]  [num0: 14.000000] [num1 50.000000]
[Epoch 463/500] [Batch 640/676] [D loss: 0.012580] [G loss: -0.028241] [d1 loss: 0.013851] [d2 loss: 0.014869]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 463/500] [Batch 660/676] [D loss: -0.011087] [G loss: -0.013707] [d1 loss: 0.098966] [d2 loss: 0.100594]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 0/676] [D loss: -0.011490] [G loss: -0.022004] [d1 loss: 0.099471] [d2 loss: 0.114073]  [sq d1 d2: 0.000213]  [num0: 18.000000] [num1 46.000000]
[Epoch 464/500] [Batch 20/676] [D loss: -0.013793] [G loss: -0.048366] [d1 loss: 0.063449] [d2 loss: 0.067114]  [sq d1 d2: 0.000013]  [num0: 12.000000] [num1 52.000000]
[Epoch 464/500] [Batch 40/676] [D loss: -0.015802] [G loss: -0.053964] [d1 loss: 0.096462] [d2 loss: 0.127957]  [sq d1 d2: 0.000992]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 60/676] [D loss: -0.007604] [G loss: -0.033366] [d1 loss: 0.076837] [d2 loss: 0.075646]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 80/676] [D loss: -0.015067] [G loss: -0.043402] [d1 loss: 0.029120] [d2 loss: 0.027866]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 464/500] [Batch 100/676] [D loss: -0.003814] [G loss: -0.056032] [d1 loss: 0.128412] [d2 loss: 0.112787]  [sq d1 d2: 0.000244]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 120/676] [D loss: 0.000774] [G loss: -0.068379] [d1 loss: 0.087734] [d2 loss: 0.079255]  [sq d1 d2: 0.000072]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 140/676] [D loss: 0.002049] [G loss: -0.052938] [d1 loss: 0.070771] [d2 loss: 0.076309]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 160/676] [D loss: -0.004569] [G loss: -0.044372] [d1 loss: 0.084370] [d2 loss: 0.083683]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 180/676] [D loss: -0.012362] [G loss: -0.025446] [d1 loss: 0.067716] [d2 loss: 0.057334]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 200/676] [D loss: -0.003499] [G loss: -0.025708] [d1 loss: 0.084564] [d2 loss: 0.065737]  [sq d1 d2: 0.000354]  [num0: 11.000000] [num1 53.000000]
[Epoch 464/500] [Batch 220/676] [D loss: -0.005569] [G loss: -0.059439] [d1 loss: 0.109166] [d2 loss: 0.101700]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 240/676] [D loss: -0.011928] [G loss: -0.093825] [d1 loss: 0.083474] [d2 loss: 0.102450]  [sq d1 d2: 0.000360]  [num0: 19.000000] [num1 45.000000]
[Epoch 464/500] [Batch 260/676] [D loss: -0.013184] [G loss: -0.133884] [d1 loss: 0.062597] [d2 loss: 0.058956]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 464/500] [Batch 280/676] [D loss: -0.002483] [G loss: -0.166135] [d1 loss: 0.151376] [d2 loss: 0.116609]  [sq d1 d2: 0.001209]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 300/676] [D loss: -0.006314] [G loss: -0.151912] [d1 loss: 0.031201] [d2 loss: 0.027923]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 464/500] [Batch 320/676] [D loss: 0.010566] [G loss: -0.141372] [d1 loss: 0.050106] [d2 loss: 0.067410]  [sq d1 d2: 0.000299]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 340/676] [D loss: 0.008882] [G loss: -0.126704] [d1 loss: 0.058092] [d2 loss: 0.063578]  [sq d1 d2: 0.000030]  [num0: 17.000000] [num1 47.000000]
[Epoch 464/500] [Batch 360/676] [D loss: -0.009118] [G loss: -0.100541] [d1 loss: 0.121594] [d2 loss: 0.110365]  [sq d1 d2: 0.000126]  [num0: 19.000000] [num1 45.000000]
[Epoch 464/500] [Batch 380/676] [D loss: -0.002034] [G loss: -0.094135] [d1 loss: 0.032174] [d2 loss: 0.029299]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 464/500] [Batch 400/676] [D loss: -0.008737] [G loss: -0.100896] [d1 loss: 0.019177] [d2 loss: 0.022985]  [sq d1 d2: 0.000014]  [num0: 18.000000] [num1 46.000000]
[Epoch 464/500] [Batch 420/676] [D loss: -0.003144] [G loss: -0.084036] [d1 loss: 0.180371] [d2 loss: 0.181740]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 440/676] [D loss: -0.004132] [G loss: -0.085278] [d1 loss: 0.034453] [d2 loss: 0.033711]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 464/500] [Batch 460/676] [D loss: -0.008297] [G loss: -0.115377] [d1 loss: 0.069526] [d2 loss: 0.043940]  [sq d1 d2: 0.000655]  [num0: 12.000000] [num1 52.000000]
[Epoch 464/500] [Batch 480/676] [D loss: -0.011107] [G loss: -0.092627] [d1 loss: 0.059376] [d2 loss: 0.062486]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 464/500] [Batch 500/676] [D loss: -0.014432] [G loss: -0.089558] [d1 loss: 0.066250] [d2 loss: 0.062585]  [sq d1 d2: 0.000013]  [num0: 18.000000] [num1 46.000000]
[Epoch 464/500] [Batch 520/676] [D loss: -0.007561] [G loss: -0.083999] [d1 loss: 0.087107] [d2 loss: 0.072377]  [sq d1 d2: 0.000217]  [num0: 19.000000] [num1 45.000000]
[Epoch 464/500] [Batch 540/676] [D loss: -0.013197] [G loss: -0.082982] [d1 loss: 0.096730] [d2 loss: 0.092510]  [sq d1 d2: 0.000018]  [num0: 17.000000] [num1 47.000000]

[Epoch 464/500] [Batch 560/676] [D loss: 0.003884] [G loss: -0.056191] [d1 loss: 0.082120] [d2 loss: 0.070115]  [sq d1 d2: 0.000144]  [num0: 18.000000] [num1 46.000000]
[Epoch 464/500] [Batch 580/676] [D loss: -0.011132] [G loss: -0.085336] [d1 loss: 0.038186] [d2 loss: 0.047492]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 464/500] [Batch 600/676] [D loss: 0.002510] [G loss: -0.086180] [d1 loss: 0.077904] [d2 loss: 0.050901]  [sq d1 d2: 0.000729]  [num0: 20.000000] [num1 44.000000]
[Epoch 464/500] [Batch 620/676] [D loss: -0.008727] [G loss: -0.065102] [d1 loss: 0.085104] [d2 loss: 0.067554]  [sq d1 d2: 0.000308]  [num0: 14.000000] [num1 50.000000]
[Epoch 464/500] [Batch 640/676] [D loss: -0.008046] [G loss: -0.074852] [d1 loss: 0.093315] [d2 loss: 0.060581]  [sq d1 d2: 0.001072]  [num0: 14.000000] [num1 50.000000]
[Epoch 464/500] [Batch 660/676] [D loss: 0.003667] [G loss: -0.063668] [d1 loss: 0.026502] [d2 loss: 0.024190]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 0/676] [D loss: 0.001922] [G loss: -0.058260] [d1 loss: 0.052125] [d2 loss: 0.050747]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 465/500] [Batch 20/676] [D loss: -0.001982] [G loss: -0.035163] [d1 loss: 0.108388] [d2 loss: 0.105983]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 40/676] [D loss: -0.004537] [G loss: -0.048542] [d1 loss: 0.017334] [d2 loss: 0.015416]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 465/500] [Batch 60/676] [D loss: -0.008669] [G loss: -0.053486] [d1 loss: 0.079366] [d2 loss: 0.068815]  [sq d1 d2: 0.000111]  [num0: 14.000000] [num1 50.000000]
[Epoch 465/500] [Batch 80/676] [D loss: -0.002692] [G loss: -0.038519] [d1 loss: 0.043696] [d2 loss: 0.038842]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 100/676] [D loss: -0.001194] [G loss: -0.060356] [d1 loss: 0.073757] [d2 loss: 0.044768]  [sq d1 d2: 0.000840]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 120/676] [D loss: -0.008328] [G loss: -0.053182] [d1 loss: 0.058092] [d2 loss: 0.051129]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 465/500] [Batch 140/676] [D loss: -0.017366] [G loss: -0.032211] [d1 loss: 0.025689] [d2 loss: 0.026126]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 160/676] [D loss: 0.001470] [G loss: -0.041919] [d1 loss: 0.017872] [d2 loss: 0.014012]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 180/676] [D loss: -0.015286] [G loss: -0.042779] [d1 loss: 0.032860] [d2 loss: 0.040946]  [sq d1 d2: 0.000065]  [num0: 19.000000] [num1 45.000000]
[Epoch 465/500] [Batch 200/676] [D loss: 0.007344] [G loss: -0.073910] [d1 loss: 0.151093] [d2 loss: 0.169820]  [sq d1 d2: 0.000351]  [num0: 17.000000] [num1 47.000000]
[Epoch 465/500] [Batch 220/676] [D loss: -0.003180] [G loss: -0.059489] [d1 loss: 0.006656] [d2 loss: 0.005652]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 240/676] [D loss: -0.004478] [G loss: -0.061508] [d1 loss: 0.024277] [d2 loss: 0.026051]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 260/676] [D loss: -0.001373] [G loss: -0.030155] [d1 loss: 0.033785] [d2 loss: 0.045162]  [sq d1 d2: 0.000129]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 280/676] [D loss: -0.008246] [G loss: -0.021672] [d1 loss: 0.067679] [d2 loss: 0.071374]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 465/500] [Batch 300/676] [D loss: -0.010176] [G loss: -0.044709] [d1 loss: 0.006230] [d2 loss: 0.008670]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 320/676] [D loss: -0.010361] [G loss: -0.049132] [d1 loss: 0.073204] [d2 loss: 0.074824]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 340/676] [D loss: -0.026658] [G loss: -0.087428] [d1 loss: 0.079417] [d2 loss: 0.075587]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 465/500] [Batch 360/676] [D loss: -0.032671] [G loss: -0.097030] [d1 loss: 0.034977] [d2 loss: 0.037844]  [sq d1 d2: 0.000008]  [num0: 12.000000] [num1 52.000000]
[Epoch 465/500] [Batch 380/676] [D loss: -0.034210] [G loss: -0.102227] [d1 loss: 0.095949] [d2 loss: 0.123811]  [sq d1 d2: 0.000776]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 400/676] [D loss: 0.000239] [G loss: -0.101562] [d1 loss: 0.050635] [d2 loss: 0.060118]  [sq d1 d2: 0.000090]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 420/676] [D loss: 0.001963] [G loss: -0.100267] [d1 loss: 0.033994] [d2 loss: 0.033096]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 440/676] [D loss: -0.006011] [G loss: -0.129306] [d1 loss: 0.044783] [d2 loss: 0.046221]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 460/676] [D loss: 0.000949] [G loss: -0.119852] [d1 loss: 0.022169] [d2 loss: 0.016903]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 480/676] [D loss: 0.003500] [G loss: -0.118517] [d1 loss: 0.053473] [d2 loss: 0.047491]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 465/500] [Batch 500/676] [D loss: 0.003189] [G loss: -0.098771] [d1 loss: 0.030600] [d2 loss: 0.031868]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 520/676] [D loss: -0.001455] [G loss: -0.084829] [d1 loss: 0.022921] [d2 loss: 0.023649]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 540/676] [D loss: -0.006665] [G loss: -0.060565] [d1 loss: 0.083863] [d2 loss: 0.087471]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 465/500] [Batch 560/676] [D loss: -0.013049] [G loss: -0.069776] [d1 loss: 0.025711] [d2 loss: 0.021746]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 465/500] [Batch 580/676] [D loss: -0.016278] [G loss: -0.070676] [d1 loss: 0.063936] [d2 loss: 0.086258]  [sq d1 d2: 0.000498]  [num0: 11.000000] [num1 53.000000]
[Epoch 465/500] [Batch 600/676] [D loss: -0.013331] [G loss: -0.066901] [d1 loss: 0.082981] [d2 loss: 0.084231]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 465/500] [Batch 620/676] [D loss: -0.017374] [G loss: -0.067746] [d1 loss: 0.016400] [d2 loss: 0.032816]  [sq d1 d2: 0.000269]  [num0: 17.000000] [num1 47.000000]
[Epoch 465/500] [Batch 640/676] [D loss: -0.011287] [G loss: -0.085537] [d1 loss: 0.093898] [d2 loss: 0.051699]  [sq d1 d2: 0.001781]  [num0: 16.000000] [num1 48.000000]
[Epoch 465/500] [Batch 660/676] [D loss: -0.017436] [G loss: -0.103889] [d1 loss: 0.043174] [d2 loss: 0.048831]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 0/676] [D loss: -0.009978] [G loss: -0.062610] [d1 loss: 0.063890] [d2 loss: 0.066826]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 20/676] [D loss: -0.004610] [G loss: -0.084436] [d1 loss: 0.020068] [d2 loss: 0.020377]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 40/676] [D loss: 0.012196] [G loss: -0.062840] [d1 loss: 0.067371] [d2 loss: 0.051016]  [sq d1 d2: 0.000267]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 60/676] [D loss: 0.006202] [G loss: -0.054761] [d1 loss: 0.082921] [d2 loss: 0.071872]  [sq d1 d2: 0.000122]  [num0: 18.000000] [num1 46.000000]
[Epoch 466/500] [Batch 80/676] [D loss: -0.002063] [G loss: -0.051117] [d1 loss: 0.095108] [d2 loss: 0.119482]  [sq d1 d2: 0.000594]  [num0: 19.000000] [num1 45.000000]
[Epoch 466/500] [Batch 100/676] [D loss: -0.005665] [G loss: -0.070159] [d1 loss: 0.053672] [d2 loss: 0.049328]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 120/676] [D loss: -0.012432] [G loss: -0.066415] [d1 loss: 0.036496] [d2 loss: 0.046889]  [sq d1 d2: 0.000108]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 140/676] [D loss: -0.018653] [G loss: -0.058471] [d1 loss: 0.109556] [d2 loss: 0.092745]  [sq d1 d2: 0.000283]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 160/676] [D loss: -0.014785] [G loss: -0.060517] [d1 loss: 0.063840] [d2 loss: 0.073487]  [sq d1 d2: 0.000093]  [num0: 21.000000] [num1 43.000000]

[Epoch 466/500] [Batch 180/676] [D loss: -0.015262] [G loss: -0.086819] [d1 loss: 0.030654] [d2 loss: 0.023460]  [sq d1 d2: 0.000052]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 200/676] [D loss: -0.019390] [G loss: -0.099196] [d1 loss: 0.154082] [d2 loss: 0.141189]  [sq d1 d2: 0.000166]  [num0: 9.000000] [num1 55.000000]
[Epoch 466/500] [Batch 220/676] [D loss: -0.001309] [G loss: -0.102378] [d1 loss: 0.028899] [d2 loss: 0.025230]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 240/676] [D loss: -0.007560] [G loss: -0.070403] [d1 loss: 0.107809] [d2 loss: 0.100108]  [sq d1 d2: 0.000059]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 260/676] [D loss: -0.002529] [G loss: -0.072305] [d1 loss: 0.048433] [d2 loss: 0.049841]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 280/676] [D loss: -0.003596] [G loss: -0.036149] [d1 loss: 0.055268] [d2 loss: 0.054729]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 300/676] [D loss: 0.001579] [G loss: -0.027375] [d1 loss: 0.057373] [d2 loss: 0.055221]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 466/500] [Batch 320/676] [D loss: -0.004423] [G loss: 0.003036] [d1 loss: 0.057195] [d2 loss: 0.061477]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 340/676] [D loss: -0.004759] [G loss: -0.004067] [d1 loss: 0.058287] [d2 loss: 0.064840]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 360/676] [D loss: -0.011514] [G loss: -0.024534] [d1 loss: 0.108878] [d2 loss: 0.082964]  [sq d1 d2: 0.000672]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 380/676] [D loss: -0.003711] [G loss: -0.012278] [d1 loss: 0.047063] [d2 loss: 0.042458]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 466/500] [Batch 400/676] [D loss: -0.013121] [G loss: 0.003033] [d1 loss: 0.084752] [d2 loss: 0.088110]  [sq d1 d2: 0.000011]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 420/676] [D loss: -0.022907] [G loss: -0.006349] [d1 loss: 0.127268] [d2 loss: 0.142053]  [sq d1 d2: 0.000219]  [num0: 14.000000] [num1 50.000000]
[Epoch 466/500] [Batch 440/676] [D loss: -0.021482] [G loss: -0.031917] [d1 loss: 0.052630] [d2 loss: 0.055021]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 460/676] [D loss: -0.012600] [G loss: -0.036349] [d1 loss: 0.037661] [d2 loss: 0.037058]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 466/500] [Batch 480/676] [D loss: -0.004227] [G loss: -0.042438] [d1 loss: 0.014424] [d2 loss: 0.016327]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 466/500] [Batch 500/676] [D loss: -0.003531] [G loss: -0.056657] [d1 loss: 0.064334] [d2 loss: 0.072428]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 520/676] [D loss: -0.011093] [G loss: -0.032122] [d1 loss: 0.047354] [d2 loss: 0.037270]  [sq d1 d2: 0.000102]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 540/676] [D loss: -0.000890] [G loss: -0.005744] [d1 loss: 0.024417] [d2 loss: 0.030246]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 560/676] [D loss: 0.002100] [G loss: -0.019912] [d1 loss: 0.012230] [d2 loss: 0.012638]  [sq d1 d2: 0.000000]  [num0: 22.000000] [num1 42.000000]
[Epoch 466/500] [Batch 580/676] [D loss: 0.002713] [G loss: -0.052157] [d1 loss: 0.005694] [d2 loss: 0.005523]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 466/500] [Batch 600/676] [D loss: 0.000472] [G loss: -0.049731] [d1 loss: 0.081776] [d2 loss: 0.076204]  [sq d1 d2: 0.000031]  [num0: 17.000000] [num1 47.000000]
[Epoch 466/500] [Batch 620/676] [D loss: -0.010211] [G loss: -0.055989] [d1 loss: 0.038157] [d2 loss: 0.031763]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 466/500] [Batch 640/676] [D loss: -0.012371] [G loss: -0.065050] [d1 loss: 0.119518] [d2 loss: 0.078266]  [sq d1 d2: 0.001702]  [num0: 16.000000] [num1 48.000000]
[Epoch 466/500] [Batch 660/676] [D loss: -0.015192] [G loss: -0.071677] [d1 loss: 0.094643] [d2 loss: 0.109817]  [sq d1 d2: 0.000230]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 0/676] [D loss: -0.012078] [G loss: -0.095564] [d1 loss: 0.092700] [d2 loss: 0.089905]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 467/500] [Batch 20/676] [D loss: -0.015539] [G loss: -0.090061] [d1 loss: 0.081892] [d2 loss: 0.084288]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 467/500] [Batch 40/676] [D loss: -0.002650] [G loss: -0.098092] [d1 loss: 0.077646] [d2 loss: 0.085625]  [sq d1 d2: 0.000064]  [num0: 12.000000] [num1 52.000000]
[Epoch 467/500] [Batch 60/676] [D loss: 0.002437] [G loss: -0.125173] [d1 loss: 0.117861] [d2 loss: 0.114491]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 467/500] [Batch 80/676] [D loss: 0.005530] [G loss: -0.153961] [d1 loss: 0.171394] [d2 loss: 0.170108]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 467/500] [Batch 100/676] [D loss: -0.004193] [G loss: -0.136018] [d1 loss: 0.103132] [d2 loss: 0.021769]  [sq d1 d2: 0.006620]  [num0: 14.000000] [num1 50.000000]
[Epoch 467/500] [Batch 120/676] [D loss: -0.000889] [G loss: -0.109741] [d1 loss: 0.041440] [d2 loss: 0.040974]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 467/500] [Batch 140/676] [D loss: -0.000563] [G loss: -0.095710] [d1 loss: 0.098925] [d2 loss: 0.086879]  [sq d1 d2: 0.000145]  [num0: 14.000000] [num1 50.000000]
[Epoch 467/500] [Batch 160/676] [D loss: -0.006040] [G loss: -0.076282] [d1 loss: 0.070168] [d2 loss: 0.089183]  [sq d1 d2: 0.000362]  [num0: 15.000000] [num1 49.000000]
[Epoch 467/500] [Batch 180/676] [D loss: -0.014800] [G loss: -0.067065] [d1 loss: 0.072985] [d2 loss: 0.072294]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 467/500] [Batch 200/676] [D loss: -0.005755] [G loss: -0.062119] [d1 loss: 0.071302] [d2 loss: 0.087872]  [sq d1 d2: 0.000275]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 220/676] [D loss: -0.016708] [G loss: -0.065958] [d1 loss: 0.051046] [d2 loss: 0.044561]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 467/500] [Batch 240/676] [D loss: -0.013887] [G loss: -0.050438] [d1 loss: 0.206867] [d2 loss: 0.085704]  [sq d1 d2: 0.014681]  [num0: 18.000000] [num1 46.000000]
[Epoch 467/500] [Batch 260/676] [D loss: -0.003694] [G loss: -0.040199] [d1 loss: 0.055203] [d2 loss: 0.073221]  [sq d1 d2: 0.000325]  [num0: 20.000000] [num1 44.000000]
[Epoch 467/500] [Batch 280/676] [D loss: -0.018915] [G loss: -0.050980] [d1 loss: 0.040472] [d2 loss: 0.032416]  [sq d1 d2: 0.000065]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 300/676] [D loss: -0.016065] [G loss: -0.014425] [d1 loss: 0.068264] [d2 loss: 0.062219]  [sq d1 d2: 0.000037]  [num0: 15.000000] [num1 49.000000]
[Epoch 467/500] [Batch 320/676] [D loss: -0.000631] [G loss: -0.019833] [d1 loss: 0.070987] [d2 loss: 0.097871]  [sq d1 d2: 0.000723]  [num0: 12.000000] [num1 52.000000]
[Epoch 467/500] [Batch 340/676] [D loss: 0.002181] [G loss: -0.053786] [d1 loss: 0.031809] [d2 loss: 0.020371]  [sq d1 d2: 0.000131]  [num0: 11.000000] [num1 53.000000]
[Epoch 467/500] [Batch 360/676] [D loss: -0.003877] [G loss: -0.064728] [d1 loss: 0.025158] [d2 loss: 0.018139]  [sq d1 d2: 0.000049]  [num0: 21.000000] [num1 43.000000]
[Epoch 467/500] [Batch 380/676] [D loss: -0.000056] [G loss: -0.067334] [d1 loss: 0.071827] [d2 loss: 0.069990]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 467/500] [Batch 400/676] [D loss: -0.000464] [G loss: -0.081444] [d1 loss: 0.085389] [d2 loss: 0.076124]  [sq d1 d2: 0.000086]  [num0: 13.000000] [num1 51.000000]
[Epoch 467/500] [Batch 420/676] [D loss: -0.008420] [G loss: -0.065661] [d1 loss: 0.047851] [d2 loss: 0.061020]  [sq d1 d2: 0.000173]  [num0: 13.000000] [num1 51.000000]
[Epoch 467/500] [Batch 440/676] [D loss: -0.017279] [G loss: -0.064882] [d1 loss: 0.062981] [d2 loss: 0.054596]  [sq d1 d2: 0.000070]  [num0: 14.000000] [num1 50.000000]
[Epoch 467/500] [Batch 460/676] [D loss: -0.022964] [G loss: -0.083906] [d1 loss: 0.063455] [d2 loss: 0.068055]  [sq d1 d2: 0.000021]  [num0: 21.000000] [num1 43.000000]
[Epoch 467/500] [Batch 480/676] [D loss: -0.009149] [G loss: -0.113775] [d1 loss: 0.068773] [d2 loss: 0.067303]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 500/676] [D loss: -0.018163] [G loss: -0.116158] [d1 loss: 0.059899] [d2 loss: 0.065202]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]

[Epoch 467/500] [Batch 520/676] [D loss: -0.018410] [G loss: -0.129570] [d1 loss: 0.102950] [d2 loss: 0.087573]  [sq d1 d2: 0.000236]  [num0: 15.000000] [num1 49.000000]
[Epoch 467/500] [Batch 540/676] [D loss: -0.002451] [G loss: -0.112617] [d1 loss: 0.029775] [d2 loss: 0.029794]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 560/676] [D loss: 0.006661] [G loss: -0.129150] [d1 loss: 0.046877] [d2 loss: 0.049979]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 467/500] [Batch 580/676] [D loss: -0.019611] [G loss: -0.142363] [d1 loss: 0.042094] [d2 loss: 0.043999]  [sq d1 d2: 0.000004]  [num0: 19.000000] [num1 45.000000]
[Epoch 467/500] [Batch 600/676] [D loss: 0.000213] [G loss: -0.126207] [d1 loss: 0.070210] [d2 loss: 0.072973]  [sq d1 d2: 0.000008]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 620/676] [D loss: -0.001719] [G loss: -0.089366] [d1 loss: 0.037162] [d2 loss: 0.040789]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 640/676] [D loss: -0.010605] [G loss: -0.081090] [d1 loss: 0.129335] [d2 loss: 0.128293]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 467/500] [Batch 660/676] [D loss: -0.015218] [G loss: -0.077561] [d1 loss: 0.018206] [d2 loss: 0.016593]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 0/676] [D loss: -0.015622] [G loss: -0.072923] [d1 loss: 0.053785] [d2 loss: 0.062643]  [sq d1 d2: 0.000078]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 20/676] [D loss: -0.014068] [G loss: -0.061160] [d1 loss: 0.044994] [d2 loss: 0.048564]  [sq d1 d2: 0.000013]  [num0: 11.000000] [num1 53.000000]
[Epoch 468/500] [Batch 40/676] [D loss: -0.016724] [G loss: -0.060696] [d1 loss: 0.052683] [d2 loss: 0.049636]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 468/500] [Batch 60/676] [D loss: 0.011195] [G loss: -0.033316] [d1 loss: 0.025758] [d2 loss: 0.034185]  [sq d1 d2: 0.000071]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 80/676] [D loss: -0.019459] [G loss: -0.035623] [d1 loss: 0.054036] [d2 loss: 0.029021]  [sq d1 d2: 0.000626]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 100/676] [D loss: -0.008754] [G loss: -0.054530] [d1 loss: 0.021986] [d2 loss: 0.021560]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 120/676] [D loss: 0.000425] [G loss: -0.040915] [d1 loss: 0.054507] [d2 loss: 0.058584]  [sq d1 d2: 0.000017]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 140/676] [D loss: -0.005455] [G loss: -0.056973] [d1 loss: 0.092559] [d2 loss: 0.076694]  [sq d1 d2: 0.000252]  [num0: 13.000000] [num1 51.000000]
[Epoch 468/500] [Batch 160/676] [D loss: 0.004466] [G loss: -0.063277] [d1 loss: 0.041843] [d2 loss: 0.043885]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 468/500] [Batch 180/676] [D loss: -0.005684] [G loss: -0.056756] [d1 loss: 0.096100] [d2 loss: 0.073683]  [sq d1 d2: 0.000503]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 200/676] [D loss: -0.007568] [G loss: -0.059936] [d1 loss: 0.083159] [d2 loss: 0.067169]  [sq d1 d2: 0.000256]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 220/676] [D loss: -0.007114] [G loss: -0.053119] [d1 loss: 0.025596] [d2 loss: 0.026433]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 240/676] [D loss: -0.026792] [G loss: -0.050740] [d1 loss: 0.028369] [d2 loss: 0.037101]  [sq d1 d2: 0.000076]  [num0: 13.000000] [num1 51.000000]
[Epoch 468/500] [Batch 260/676] [D loss: -0.018631] [G loss: -0.051109] [d1 loss: 0.053809] [d2 loss: 0.074142]  [sq d1 d2: 0.000413]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 280/676] [D loss: -0.047596] [G loss: -0.093350] [d1 loss: 0.034160] [d2 loss: 0.036950]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 300/676] [D loss: -0.021460] [G loss: -0.067320] [d1 loss: 0.041212] [d2 loss: 0.063277]  [sq d1 d2: 0.000487]  [num0: 17.000000] [num1 47.000000]
[Epoch 468/500] [Batch 320/676] [D loss: 0.000829] [G loss: -0.055864] [d1 loss: 0.186698] [d2 loss: 0.157582]  [sq d1 d2: 0.000848]  [num0: 17.000000] [num1 47.000000]
[Epoch 468/500] [Batch 340/676] [D loss: 0.003130] [G loss: -0.058734] [d1 loss: 0.036029] [d2 loss: 0.036737]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 360/676] [D loss: 0.025679] [G loss: -0.080334] [d1 loss: 0.023809] [d2 loss: 0.029184]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 380/676] [D loss: 0.004013] [G loss: -0.099533] [d1 loss: 0.071060] [d2 loss: 0.079369]  [sq d1 d2: 0.000069]  [num0: 10.000000] [num1 54.000000]
[Epoch 468/500] [Batch 400/676] [D loss: -0.000013] [G loss: -0.085790] [d1 loss: 0.052015] [d2 loss: 0.049941]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 468/500] [Batch 420/676] [D loss: -0.005518] [G loss: -0.074048] [d1 loss: 0.052314] [d2 loss: 0.064204]  [sq d1 d2: 0.000141]  [num0: 13.000000] [num1 51.000000]
[Epoch 468/500] [Batch 440/676] [D loss: -0.006275] [G loss: -0.049750] [d1 loss: 0.097618] [d2 loss: 0.085514]  [sq d1 d2: 0.000147]  [num0: 13.000000] [num1 51.000000]
[Epoch 468/500] [Batch 460/676] [D loss: 0.000663] [G loss: -0.043570] [d1 loss: 0.041325] [d2 loss: 0.033494]  [sq d1 d2: 0.000061]  [num0: 14.000000] [num1 50.000000]
[Epoch 468/500] [Batch 480/676] [D loss: -0.014349] [G loss: -0.021258] [d1 loss: 0.054226] [d2 loss: 0.050512]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 500/676] [D loss: -0.010429] [G loss: -0.009612] [d1 loss: 0.043622] [d2 loss: 0.039767]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 520/676] [D loss: -0.018574] [G loss: -0.027474] [d1 loss: 0.036680] [d2 loss: 0.042815]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 540/676] [D loss: -0.023063] [G loss: -0.021135] [d1 loss: 0.028641] [d2 loss: 0.036679]  [sq d1 d2: 0.000065]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 560/676] [D loss: 0.000477] [G loss: -0.020541] [d1 loss: 0.047854] [d2 loss: 0.055471]  [sq d1 d2: 0.000058]  [num0: 17.000000] [num1 47.000000]
[Epoch 468/500] [Batch 580/676] [D loss: -0.025252] [G loss: 0.000361] [d1 loss: 0.027155] [d2 loss: 0.024830]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 468/500] [Batch 600/676] [D loss: 0.006822] [G loss: -0.030295] [d1 loss: 0.033699] [d2 loss: 0.033548]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 468/500] [Batch 620/676] [D loss: 0.017353] [G loss: 0.000888] [d1 loss: 0.122560] [d2 loss: 0.090979]  [sq d1 d2: 0.000997]  [num0: 15.000000] [num1 49.000000]
[Epoch 468/500] [Batch 640/676] [D loss: -0.007683] [G loss: -0.007666] [d1 loss: 0.048592] [d2 loss: 0.054966]  [sq d1 d2: 0.000041]  [num0: 19.000000] [num1 45.000000]
[Epoch 468/500] [Batch 660/676] [D loss: 0.003484] [G loss: -0.035971] [d1 loss: 0.028448] [d2 loss: 0.027561]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 469/500] [Batch 0/676] [D loss: -0.004314] [G loss: -0.035472] [d1 loss: 0.076547] [d2 loss: 0.086785]  [sq d1 d2: 0.000105]  [num0: 15.000000] [num1 49.000000]
[Epoch 469/500] [Batch 20/676] [D loss: -0.008855] [G loss: -0.067998] [d1 loss: 0.026849] [d2 loss: 0.027524]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 469/500] [Batch 40/676] [D loss: -0.008072] [G loss: -0.085825] [d1 loss: 0.073814] [d2 loss: 0.063776]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 469/500] [Batch 60/676] [D loss: -0.022159] [G loss: -0.122964] [d1 loss: 0.026605] [d2 loss: 0.027958]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 80/676] [D loss: -0.003395] [G loss: -0.146590] [d1 loss: 0.050683] [d2 loss: 0.038545]  [sq d1 d2: 0.000147]  [num0: 12.000000] [num1 52.000000]
[Epoch 469/500] [Batch 100/676] [D loss: -0.016085] [G loss: -0.173483] [d1 loss: 0.166643] [d2 loss: 0.163203]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 120/676] [D loss: -0.023666] [G loss: -0.180821] [d1 loss: 0.047026] [d2 loss: 0.047694]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 469/500] [Batch 140/676] [D loss: -0.008754] [G loss: -0.186291] [d1 loss: 0.117516] [d2 loss: 0.121398]  [sq d1 d2: 0.000015]  [num0: 17.000000] [num1 47.000000]

[Epoch 469/500] [Batch 160/676] [D loss: 0.001988] [G loss: -0.176391] [d1 loss: 0.101296] [d2 loss: 0.090162]  [sq d1 d2: 0.000124]  [num0: 18.000000] [num1 46.000000]
[Epoch 469/500] [Batch 180/676] [D loss: 0.006892] [G loss: -0.132080] [d1 loss: 0.057865] [d2 loss: 0.055128]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 469/500] [Batch 200/676] [D loss: 0.011272] [G loss: -0.133449] [d1 loss: 0.090558] [d2 loss: 0.084106]  [sq d1 d2: 0.000042]  [num0: 13.000000] [num1 51.000000]
[Epoch 469/500] [Batch 220/676] [D loss: 0.007506] [G loss: -0.107470] [d1 loss: 0.024233] [d2 loss: 0.025305]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 469/500] [Batch 240/676] [D loss: -0.000264] [G loss: -0.074841] [d1 loss: 0.062256] [d2 loss: 0.058117]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 260/676] [D loss: -0.012055] [G loss: -0.044891] [d1 loss: 0.044358] [d2 loss: 0.040899]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 469/500] [Batch 280/676] [D loss: -0.013143] [G loss: -0.037599] [d1 loss: 0.063123] [d2 loss: 0.064096]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 300/676] [D loss: -0.021660] [G loss: -0.015945] [d1 loss: 0.067043] [d2 loss: 0.059375]  [sq d1 d2: 0.000059]  [num0: 16.000000] [num1 48.000000]
[Epoch 469/500] [Batch 320/676] [D loss: -0.029542] [G loss: -0.016432] [d1 loss: 0.094357] [d2 loss: 0.086987]  [sq d1 d2: 0.000054]  [num0: 20.000000] [num1 44.000000]
[Epoch 469/500] [Batch 340/676] [D loss: -0.036103] [G loss: -0.024077] [d1 loss: 0.029993] [d2 loss: 0.029856]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 360/676] [D loss: -0.012127] [G loss: -0.024063] [d1 loss: 0.041675] [d2 loss: 0.039286]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 469/500] [Batch 380/676] [D loss: -0.001823] [G loss: -0.040566] [d1 loss: 0.052446] [d2 loss: 0.049288]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 469/500] [Batch 400/676] [D loss: 0.018686] [G loss: -0.085432] [d1 loss: 0.069219] [d2 loss: 0.064669]  [sq d1 d2: 0.000021]  [num0: 17.000000] [num1 47.000000]
[Epoch 469/500] [Batch 420/676] [D loss: 0.010130] [G loss: -0.110818] [d1 loss: 0.106972] [d2 loss: 0.085210]  [sq d1 d2: 0.000474]  [num0: 16.000000] [num1 48.000000]
[Epoch 469/500] [Batch 440/676] [D loss: -0.007084] [G loss: -0.107136] [d1 loss: 0.054997] [d2 loss: 0.053269]  [sq d1 d2: 0.000003]  [num0: 11.000000] [num1 53.000000]
[Epoch 469/500] [Batch 460/676] [D loss: 0.006688] [G loss: -0.118924] [d1 loss: 0.060150] [d2 loss: 0.050924]  [sq d1 d2: 0.000085]  [num0: 12.000000] [num1 52.000000]
[Epoch 469/500] [Batch 480/676] [D loss: 0.009978] [G loss: -0.115042] [d1 loss: 0.090907] [d2 loss: 0.103186]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 469/500] [Batch 500/676] [D loss: 0.003912] [G loss: -0.099579] [d1 loss: 0.046947] [d2 loss: 0.059628]  [sq d1 d2: 0.000161]  [num0: 17.000000] [num1 47.000000]
[Epoch 469/500] [Batch 520/676] [D loss: -0.008250] [G loss: -0.083738] [d1 loss: 0.059205] [d2 loss: 0.063395]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 540/676] [D loss: -0.006395] [G loss: -0.077844] [d1 loss: 0.073910] [d2 loss: 0.050184]  [sq d1 d2: 0.000563]  [num0: 20.000000] [num1 44.000000]
[Epoch 469/500] [Batch 560/676] [D loss: -0.021375] [G loss: -0.053367] [d1 loss: 0.058584] [d2 loss: 0.068527]  [sq d1 d2: 0.000099]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 580/676] [D loss: -0.017742] [G loss: -0.050515] [d1 loss: 0.052790] [d2 loss: 0.051955]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 469/500] [Batch 600/676] [D loss: -0.049062] [G loss: 0.021166] [d1 loss: 0.046919] [d2 loss: 0.058542]  [sq d1 d2: 0.000135]  [num0: 15.000000] [num1 49.000000]
[Epoch 469/500] [Batch 620/676] [D loss: -0.030724] [G loss: 0.017599] [d1 loss: 0.010428] [d2 loss: 0.011495]  [sq d1 d2: 0.000001]  [num0: 20.000000] [num1 44.000000]
[Epoch 469/500] [Batch 640/676] [D loss: 0.001282] [G loss: -0.008580] [d1 loss: 0.069423] [d2 loss: 0.059827]  [sq d1 d2: 0.000092]  [num0: 13.000000] [num1 51.000000]
[Epoch 469/500] [Batch 660/676] [D loss: 0.000435] [G loss: 0.047507] [d1 loss: 0.035080] [d2 loss: 0.048170]  [sq d1 d2: 0.000171]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 0/676] [D loss: 0.005080] [G loss: 0.069159] [d1 loss: 0.028602] [d2 loss: 0.031042]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 470/500] [Batch 20/676] [D loss: 0.005831] [G loss: 0.061088] [d1 loss: 0.034944] [d2 loss: 0.039835]  [sq d1 d2: 0.000024]  [num0: 17.000000] [num1 47.000000]
[Epoch 470/500] [Batch 40/676] [D loss: -0.001358] [G loss: 0.032814] [d1 loss: 0.028339] [d2 loss: 0.052356]  [sq d1 d2: 0.000577]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 60/676] [D loss: 0.000941] [G loss: -0.013463] [d1 loss: 0.027116] [d2 loss: 0.033393]  [sq d1 d2: 0.000039]  [num0: 14.000000] [num1 50.000000]
[Epoch 470/500] [Batch 80/676] [D loss: -0.012637] [G loss: -0.044795] [d1 loss: 0.135738] [d2 loss: 0.141353]  [sq d1 d2: 0.000032]  [num0: 20.000000] [num1 44.000000]
[Epoch 470/500] [Batch 100/676] [D loss: -0.020243] [G loss: -0.038122] [d1 loss: 0.058432] [d2 loss: 0.057537]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 470/500] [Batch 120/676] [D loss: -0.021033] [G loss: -0.041775] [d1 loss: 0.034064] [d2 loss: 0.030409]  [sq d1 d2: 0.000013]  [num0: 21.000000] [num1 43.000000]
[Epoch 470/500] [Batch 140/676] [D loss: -0.027855] [G loss: -0.035049] [d1 loss: 0.070935] [d2 loss: 0.078007]  [sq d1 d2: 0.000050]  [num0: 16.000000] [num1 48.000000]
[Epoch 470/500] [Batch 160/676] [D loss: -0.026335] [G loss: -0.038442] [d1 loss: 0.036910] [d2 loss: 0.044382]  [sq d1 d2: 0.000056]  [num0: 14.000000] [num1 50.000000]
[Epoch 470/500] [Batch 180/676] [D loss: -0.018423] [G loss: -0.033711] [d1 loss: 0.073328] [d2 loss: 0.059893]  [sq d1 d2: 0.000181]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 200/676] [D loss: -0.025448] [G loss: -0.027874] [d1 loss: 0.094593] [d2 loss: 0.091376]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 220/676] [D loss: 0.003630] [G loss: -0.026618] [d1 loss: 0.062242] [d2 loss: 0.074533]  [sq d1 d2: 0.000151]  [num0: 16.000000] [num1 48.000000]
[Epoch 470/500] [Batch 240/676] [D loss: 0.010835] [G loss: -0.059339] [d1 loss: 0.048140] [d2 loss: 0.053695]  [sq d1 d2: 0.000031]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 260/676] [D loss: 0.012315] [G loss: -0.060750] [d1 loss: 0.034072] [d2 loss: 0.036110]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 470/500] [Batch 280/676] [D loss: -0.003694] [G loss: -0.057850] [d1 loss: 0.048566] [d2 loss: 0.033584]  [sq d1 d2: 0.000224]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 300/676] [D loss: -0.008081] [G loss: -0.031240] [d1 loss: 0.036514] [d2 loss: 0.034742]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 470/500] [Batch 320/676] [D loss: -0.017625] [G loss: -0.024324] [d1 loss: 0.042532] [d2 loss: 0.036048]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 470/500] [Batch 340/676] [D loss: -0.028128] [G loss: -0.029472] [d1 loss: 0.021175] [d2 loss: 0.024675]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 360/676] [D loss: -0.000361] [G loss: -0.043925] [d1 loss: 0.018841] [d2 loss: 0.018299]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 470/500] [Batch 380/676] [D loss: -0.040285] [G loss: -0.060056] [d1 loss: 0.116148] [d2 loss: 0.118696]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 400/676] [D loss: -0.015111] [G loss: -0.048965] [d1 loss: 0.032716] [d2 loss: 0.042638]  [sq d1 d2: 0.000098]  [num0: 19.000000] [num1 45.000000]
[Epoch 470/500] [Batch 420/676] [D loss: 0.044492] [G loss: -0.033459] [d1 loss: 0.114382] [d2 loss: 0.120993]  [sq d1 d2: 0.000044]  [num0: 13.000000] [num1 51.000000]
[Epoch 470/500] [Batch 440/676] [D loss: 0.025303] [G loss: -0.051785] [d1 loss: 0.100097] [d2 loss: 0.074149]  [sq d1 d2: 0.000673]  [num0: 16.000000] [num1 48.000000]

[Epoch 470/500] [Batch 460/676] [D loss: 0.023133] [G loss: -0.070910] [d1 loss: 0.072575] [d2 loss: 0.069721]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 480/676] [D loss: 0.029402] [G loss: -0.108993] [d1 loss: 0.066867] [d2 loss: 0.063207]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 500/676] [D loss: 0.006227] [G loss: -0.082983] [d1 loss: 0.051647] [d2 loss: 0.042898]  [sq d1 d2: 0.000077]  [num0: 12.000000] [num1 52.000000]
[Epoch 470/500] [Batch 520/676] [D loss: -0.002326] [G loss: -0.062342] [d1 loss: 0.145026] [d2 loss: 0.091154]  [sq d1 d2: 0.002902]  [num0: 18.000000] [num1 46.000000]
[Epoch 470/500] [Batch 540/676] [D loss: -0.007566] [G loss: -0.072301] [d1 loss: 0.029814] [d2 loss: 0.034628]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 470/500] [Batch 560/676] [D loss: -0.005031] [G loss: -0.089949] [d1 loss: 0.027489] [d2 loss: 0.022888]  [sq d1 d2: 0.000021]  [num0: 19.000000] [num1 45.000000]
[Epoch 470/500] [Batch 580/676] [D loss: -0.020716] [G loss: -0.099130] [d1 loss: 0.124149] [d2 loss: 0.078834]  [sq d1 d2: 0.002053]  [num0: 14.000000] [num1 50.000000]
[Epoch 470/500] [Batch 600/676] [D loss: -0.021040] [G loss: -0.123681] [d1 loss: 0.084928] [d2 loss: 0.091757]  [sq d1 d2: 0.000047]  [num0: 13.000000] [num1 51.000000]
[Epoch 470/500] [Batch 620/676] [D loss: -0.070273] [G loss: -0.160905] [d1 loss: 0.028281] [d2 loss: 0.029791]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 470/500] [Batch 640/676] [D loss: 0.000515] [G loss: -0.189030] [d1 loss: 0.050222] [d2 loss: 0.066361]  [sq d1 d2: 0.000260]  [num0: 11.000000] [num1 53.000000]
[Epoch 470/500] [Batch 660/676] [D loss: -0.004808] [G loss: -0.172939] [d1 loss: 0.048900] [d2 loss: 0.032395]  [sq d1 d2: 0.000272]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 0/676] [D loss: -0.014363] [G loss: -0.192805] [d1 loss: 0.075721] [d2 loss: 0.080471]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 20/676] [D loss: -0.005122] [G loss: -0.193223] [d1 loss: 0.045274] [d2 loss: 0.043911]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 471/500] [Batch 40/676] [D loss: 0.022079] [G loss: -0.187066] [d1 loss: 0.033279] [d2 loss: 0.029225]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 471/500] [Batch 60/676] [D loss: 0.003004] [G loss: -0.151630] [d1 loss: 0.052657] [d2 loss: 0.044757]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 80/676] [D loss: -0.003326] [G loss: -0.121285] [d1 loss: 0.050571] [d2 loss: 0.055269]  [sq d1 d2: 0.000022]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 100/676] [D loss: -0.014354] [G loss: -0.106873] [d1 loss: 0.053439] [d2 loss: 0.052944]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 471/500] [Batch 120/676] [D loss: -0.050663] [G loss: -0.103537] [d1 loss: 0.071802] [d2 loss: 0.068509]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 140/676] [D loss: -0.039130] [G loss: -0.036657] [d1 loss: 0.077798] [d2 loss: 0.065475]  [sq d1 d2: 0.000152]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 160/676] [D loss: -0.036291] [G loss: -0.065300] [d1 loss: 0.048086] [d2 loss: 0.040408]  [sq d1 d2: 0.000059]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 180/676] [D loss: -0.027081] [G loss: 0.014657] [d1 loss: 0.054502] [d2 loss: 0.049526]  [sq d1 d2: 0.000025]  [num0: 13.000000] [num1 51.000000]
[Epoch 471/500] [Batch 200/676] [D loss: -0.041557] [G loss: 0.012305] [d1 loss: 0.091804] [d2 loss: 0.088776]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 220/676] [D loss: -0.001673] [G loss: -0.019127] [d1 loss: 0.080800] [d2 loss: 0.071381]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 240/676] [D loss: 0.038468] [G loss: 0.009957] [d1 loss: 0.039863] [d2 loss: 0.033557]  [sq d1 d2: 0.000040]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 260/676] [D loss: 0.025072] [G loss: 0.016895] [d1 loss: 0.045875] [d2 loss: 0.047931]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 471/500] [Batch 280/676] [D loss: 0.005698] [G loss: 0.033311] [d1 loss: 0.059590] [d2 loss: 0.051980]  [sq d1 d2: 0.000058]  [num0: 12.000000] [num1 52.000000]
[Epoch 471/500] [Batch 300/676] [D loss: -0.006665] [G loss: -0.015338] [d1 loss: 0.040492] [d2 loss: 0.046815]  [sq d1 d2: 0.000040]  [num0: 12.000000] [num1 52.000000]
[Epoch 471/500] [Batch 320/676] [D loss: -0.019777] [G loss: -0.001470] [d1 loss: 0.037961] [d2 loss: 0.051812]  [sq d1 d2: 0.000192]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 340/676] [D loss: -0.023615] [G loss: -0.004228] [d1 loss: 0.070597] [d2 loss: 0.059224]  [sq d1 d2: 0.000129]  [num0: 14.000000] [num1 50.000000]
[Epoch 471/500] [Batch 360/676] [D loss: -0.052781] [G loss: 0.035819] [d1 loss: 0.025804] [d2 loss: 0.026645]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 380/676] [D loss: -0.044604] [G loss: -0.004002] [d1 loss: 0.060427] [d2 loss: 0.065234]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 400/676] [D loss: -0.000091] [G loss: -0.014105] [d1 loss: 0.010963] [d2 loss: 0.014792]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 420/676] [D loss: 0.010226] [G loss: -0.020673] [d1 loss: 0.074887] [d2 loss: 0.067918]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 471/500] [Batch 440/676] [D loss: -0.023999] [G loss: -0.062921] [d1 loss: 0.152991] [d2 loss: 0.139564]  [sq d1 d2: 0.000180]  [num0: 19.000000] [num1 45.000000]
[Epoch 471/500] [Batch 460/676] [D loss: 0.019913] [G loss: -0.078245] [d1 loss: 0.048514] [d2 loss: 0.062888]  [sq d1 d2: 0.000207]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 480/676] [D loss: 0.028625] [G loss: -0.085719] [d1 loss: 0.064108] [d2 loss: 0.067526]  [sq d1 d2: 0.000012]  [num0: 11.000000] [num1 53.000000]
[Epoch 471/500] [Batch 500/676] [D loss: 0.017261] [G loss: -0.039881] [d1 loss: 0.101143] [d2 loss: 0.081445]  [sq d1 d2: 0.000388]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 520/676] [D loss: 0.002631] [G loss: -0.051162] [d1 loss: 0.036464] [d2 loss: 0.039217]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 471/500] [Batch 540/676] [D loss: -0.001670] [G loss: -0.044840] [d1 loss: 0.159297] [d2 loss: 0.145311]  [sq d1 d2: 0.000196]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 560/676] [D loss: -0.013188] [G loss: -0.023629] [d1 loss: 0.017423] [d2 loss: 0.032502]  [sq d1 d2: 0.000227]  [num0: 15.000000] [num1 49.000000]
[Epoch 471/500] [Batch 580/676] [D loss: -0.016138] [G loss: -0.019804] [d1 loss: 0.138486] [d2 loss: 0.138074]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 471/500] [Batch 600/676] [D loss: -0.055813] [G loss: -0.012344] [d1 loss: 0.155558] [d2 loss: 0.134823]  [sq d1 d2: 0.000430]  [num0: 19.000000] [num1 45.000000]
[Epoch 471/500] [Batch 620/676] [D loss: -0.058945] [G loss: -0.007704] [d1 loss: 0.036155] [d2 loss: 0.053688]  [sq d1 d2: 0.000307]  [num0: 17.000000] [num1 47.000000]
[Epoch 471/500] [Batch 640/676] [D loss: -0.049338] [G loss: -0.038935] [d1 loss: 0.019475] [d2 loss: 0.020811]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 471/500] [Batch 660/676] [D loss: -0.065253] [G loss: 0.010023] [d1 loss: 0.123892] [d2 loss: 0.111219]  [sq d1 d2: 0.000161]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 0/676] [D loss: 0.003468] [G loss: -0.011346] [d1 loss: 0.021620] [d2 loss: 0.028615]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 20/676] [D loss: -0.005070] [G loss: 0.010809] [d1 loss: 0.072872] [d2 loss: 0.074952]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 472/500] [Batch 40/676] [D loss: 0.037484] [G loss: -0.039437] [d1 loss: 0.038078] [d2 loss: 0.035232]  [sq d1 d2: 0.000008]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 60/676] [D loss: 0.014705] [G loss: -0.046274] [d1 loss: 0.048328] [d2 loss: 0.035927]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]

[Epoch 472/500] [Batch 80/676] [D loss: 0.002075] [G loss: -0.016976] [d1 loss: 0.052259] [d2 loss: 0.064536]  [sq d1 d2: 0.000151]  [num0: 13.000000] [num1 51.000000]
[Epoch 472/500] [Batch 100/676] [D loss: 0.002445] [G loss: -0.003121] [d1 loss: 0.099196] [d2 loss: 0.107381]  [sq d1 d2: 0.000067]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 120/676] [D loss: -0.006906] [G loss: 0.023821] [d1 loss: 0.054323] [d2 loss: 0.048627]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 140/676] [D loss: -0.036631] [G loss: 0.053073] [d1 loss: 0.093433] [d2 loss: 0.055568]  [sq d1 d2: 0.001434]  [num0: 13.000000] [num1 51.000000]
[Epoch 472/500] [Batch 160/676] [D loss: -0.047542] [G loss: 0.057542] [d1 loss: 0.039934] [d2 loss: 0.042933]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 472/500] [Batch 180/676] [D loss: -0.016883] [G loss: 0.077190] [d1 loss: 0.090831] [d2 loss: 0.062143]  [sq d1 d2: 0.000823]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 200/676] [D loss: -0.084108] [G loss: 0.083138] [d1 loss: 0.028065] [d2 loss: 0.025623]  [sq d1 d2: 0.000006]  [num0: 19.000000] [num1 45.000000]
[Epoch 472/500] [Batch 220/676] [D loss: -0.033585] [G loss: 0.087129] [d1 loss: 0.015856] [d2 loss: 0.014076]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 240/676] [D loss: -0.002753] [G loss: 0.082742] [d1 loss: 0.026963] [d2 loss: 0.032071]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 472/500] [Batch 260/676] [D loss: -0.006405] [G loss: 0.022890] [d1 loss: 0.066298] [d2 loss: 0.056815]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 472/500] [Batch 280/676] [D loss: 0.026349] [G loss: 0.042872] [d1 loss: 0.089699] [d2 loss: 0.080160]  [sq d1 d2: 0.000091]  [num0: 19.000000] [num1 45.000000]
[Epoch 472/500] [Batch 300/676] [D loss: 0.008398] [G loss: 0.047830] [d1 loss: 0.041004] [d2 loss: 0.043728]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 320/676] [D loss: -0.003660] [G loss: 0.040326] [d1 loss: 0.088717] [d2 loss: 0.086873]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 340/676] [D loss: -0.006030] [G loss: 0.043981] [d1 loss: 0.128065] [d2 loss: 0.131648]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 360/676] [D loss: -0.018117] [G loss: 0.043336] [d1 loss: 0.042690] [d2 loss: 0.057600]  [sq d1 d2: 0.000222]  [num0: 17.000000] [num1 47.000000]
[Epoch 472/500] [Batch 380/676] [D loss: -0.060081] [G loss: 0.064087] [d1 loss: 0.055584] [d2 loss: 0.070163]  [sq d1 d2: 0.000213]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 400/676] [D loss: -0.074592] [G loss: 0.046188] [d1 loss: 0.076792] [d2 loss: 0.062837]  [sq d1 d2: 0.000195]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 420/676] [D loss: -0.063902] [G loss: 0.065221] [d1 loss: 0.023396] [d2 loss: 0.022313]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 472/500] [Batch 440/676] [D loss: -0.023189] [G loss: 0.029986] [d1 loss: 0.049986] [d2 loss: 0.039845]  [sq d1 d2: 0.000103]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 460/676] [D loss: -0.056814] [G loss: -0.025678] [d1 loss: 0.023683] [d2 loss: 0.032774]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 480/676] [D loss: 0.052145] [G loss: -0.099313] [d1 loss: 0.080492] [d2 loss: 0.071809]  [sq d1 d2: 0.000075]  [num0: 14.000000] [num1 50.000000]
[Epoch 472/500] [Batch 500/676] [D loss: 0.038014] [G loss: -0.133699] [d1 loss: 0.127314] [d2 loss: 0.141554]  [sq d1 d2: 0.000203]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 520/676] [D loss: 0.014965] [G loss: -0.111779] [d1 loss: 0.062755] [d2 loss: 0.054741]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 540/676] [D loss: 0.001913] [G loss: -0.064072] [d1 loss: 0.056314] [d2 loss: 0.051724]  [sq d1 d2: 0.000021]  [num0: 18.000000] [num1 46.000000]
[Epoch 472/500] [Batch 560/676] [D loss: -0.006858] [G loss: -0.008753] [d1 loss: 0.029489] [d2 loss: 0.029643]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 472/500] [Batch 580/676] [D loss: -0.027117] [G loss: 0.038855] [d1 loss: 0.051066] [d2 loss: 0.064501]  [sq d1 d2: 0.000181]  [num0: 14.000000] [num1 50.000000]
[Epoch 472/500] [Batch 600/676] [D loss: 0.002634] [G loss: 0.127012] [d1 loss: 0.057085] [d2 loss: 0.050601]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 472/500] [Batch 620/676] [D loss: -0.058747] [G loss: 0.195132] [d1 loss: 0.126814] [d2 loss: 0.146891]  [sq d1 d2: 0.000403]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 640/676] [D loss: -0.061030] [G loss: 0.246714] [d1 loss: 0.053123] [d2 loss: 0.035888]  [sq d1 d2: 0.000297]  [num0: 16.000000] [num1 48.000000]
[Epoch 472/500] [Batch 660/676] [D loss: -0.071451] [G loss: 0.270637] [d1 loss: 0.059090] [d2 loss: 0.066612]  [sq d1 d2: 0.000057]  [num0: 15.000000] [num1 49.000000]
[Epoch 473/500] [Batch 0/676] [D loss: -0.018000] [G loss: 0.229007] [d1 loss: 0.127129] [d2 loss: 0.104048]  [sq d1 d2: 0.000533]  [num0: 20.000000] [num1 44.000000]
[Epoch 473/500] [Batch 20/676] [D loss: -0.047651] [G loss: 0.161388] [d1 loss: 0.061040] [d2 loss: 0.060576]  [sq d1 d2: 0.000000]  [num0: 20.000000] [num1 44.000000]
[Epoch 473/500] [Batch 40/676] [D loss: 0.024364] [G loss: 0.099713] [d1 loss: 0.015643] [d2 loss: 0.016918]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 473/500] [Batch 60/676] [D loss: 0.021769] [G loss: 0.088056] [d1 loss: 0.034611] [d2 loss: 0.031589]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 473/500] [Batch 80/676] [D loss: 0.013878] [G loss: 0.023407] [d1 loss: 0.067687] [d2 loss: 0.074297]  [sq d1 d2: 0.000044]  [num0: 18.000000] [num1 46.000000]
[Epoch 473/500] [Batch 100/676] [D loss: 0.001944] [G loss: 0.002538] [d1 loss: 0.044209] [d2 loss: 0.028674]  [sq d1 d2: 0.000241]  [num0: 12.000000] [num1 52.000000]
[Epoch 473/500] [Batch 120/676] [D loss: -0.002261] [G loss: -0.043714] [d1 loss: 0.031024] [d2 loss: 0.029281]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 140/676] [D loss: -0.026655] [G loss: -0.077066] [d1 loss: 0.083979] [d2 loss: 0.099278]  [sq d1 d2: 0.000234]  [num0: 17.000000] [num1 47.000000]
[Epoch 473/500] [Batch 160/676] [D loss: -0.034376] [G loss: -0.047673] [d1 loss: 0.047409] [d2 loss: 0.043214]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 473/500] [Batch 180/676] [D loss: -0.032307] [G loss: -0.032029] [d1 loss: 0.044530] [d2 loss: 0.063649]  [sq d1 d2: 0.000366]  [num0: 18.000000] [num1 46.000000]
[Epoch 473/500] [Batch 200/676] [D loss: -0.059122] [G loss: -0.066661] [d1 loss: 0.058410] [d2 loss: 0.065329]  [sq d1 d2: 0.000048]  [num0: 18.000000] [num1 46.000000]
[Epoch 473/500] [Batch 220/676] [D loss: -0.023969] [G loss: -0.065084] [d1 loss: 0.071716] [d2 loss: 0.083576]  [sq d1 d2: 0.000141]  [num0: 15.000000] [num1 49.000000]
[Epoch 473/500] [Batch 240/676] [D loss: -0.013222] [G loss: -0.109534] [d1 loss: 0.056816] [d2 loss: 0.045225]  [sq d1 d2: 0.000134]  [num0: 20.000000] [num1 44.000000]
[Epoch 473/500] [Batch 260/676] [D loss: 0.027023] [G loss: -0.131502] [d1 loss: 0.060140] [d2 loss: 0.055552]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 280/676] [D loss: 0.019466] [G loss: -0.191964] [d1 loss: 0.079861] [d2 loss: 0.066014]  [sq d1 d2: 0.000192]  [num0: 13.000000] [num1 51.000000]
[Epoch 473/500] [Batch 300/676] [D loss: 0.022081] [G loss: -0.179895] [d1 loss: 0.182565] [d2 loss: 0.157053]  [sq d1 d2: 0.000651]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 320/676] [D loss: 0.011550] [G loss: -0.144090] [d1 loss: 0.097935] [d2 loss: 0.097812]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 340/676] [D loss: 0.006930] [G loss: -0.090550] [d1 loss: 0.133281] [d2 loss: 0.141631]  [sq d1 d2: 0.000070]  [num0: 17.000000] [num1 47.000000]
[Epoch 473/500] [Batch 360/676] [D loss: -0.001360] [G loss: -0.049220] [d1 loss: 0.101344] [d2 loss: 0.106591]  [sq d1 d2: 0.000028]  [num0: 19.000000] [num1 45.000000]
[Epoch 473/500] [Batch 380/676] [D loss: -0.024117] [G loss: -0.012775] [d1 loss: 0.125010] [d2 loss: 0.132008]  [sq d1 d2: 0.000049]  [num0: 19.000000] [num1 45.000000]
[Epoch 473/500] [Batch 400/676] [D loss: -0.056005] [G loss: 0.028070] [d1 loss: 0.092170] [d2 loss: 0.086537]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]

[Epoch 473/500] [Batch 420/676] [D loss: -0.090758] [G loss: 0.102548] [d1 loss: 0.065540] [d2 loss: 0.061224]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 440/676] [D loss: -0.079916] [G loss: 0.168358] [d1 loss: 0.050963] [d2 loss: 0.053973]  [sq d1 d2: 0.000009]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 460/676] [D loss: -0.051600] [G loss: 0.171195] [d1 loss: 0.074997] [d2 loss: 0.068916]  [sq d1 d2: 0.000037]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 480/676] [D loss: -0.048431] [G loss: 0.153189] [d1 loss: 0.093807] [d2 loss: 0.065966]  [sq d1 d2: 0.000775]  [num0: 11.000000] [num1 53.000000]
[Epoch 473/500] [Batch 500/676] [D loss: 0.040875] [G loss: 0.151463] [d1 loss: 0.097478] [d2 loss: 0.074041]  [sq d1 d2: 0.000549]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 520/676] [D loss: -0.030743] [G loss: 0.114735] [d1 loss: 0.063841] [d2 loss: 0.066350]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 540/676] [D loss: -0.011425] [G loss: 0.060100] [d1 loss: 0.059073] [d2 loss: 0.050935]  [sq d1 d2: 0.000066]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 560/676] [D loss: 0.026920] [G loss: 0.012329] [d1 loss: 0.046523] [d2 loss: 0.032665]  [sq d1 d2: 0.000192]  [num0: 15.000000] [num1 49.000000]
[Epoch 473/500] [Batch 580/676] [D loss: 0.008794] [G loss: -0.025709] [d1 loss: 0.036193] [d2 loss: 0.026926]  [sq d1 d2: 0.000086]  [num0: 14.000000] [num1 50.000000]
[Epoch 473/500] [Batch 600/676] [D loss: 0.001968] [G loss: -0.040962] [d1 loss: 0.031282] [d2 loss: 0.050138]  [sq d1 d2: 0.000356]  [num0: 18.000000] [num1 46.000000]
[Epoch 473/500] [Batch 620/676] [D loss: -0.014001] [G loss: -0.073742] [d1 loss: 0.063870] [d2 loss: 0.071873]  [sq d1 d2: 0.000064]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 640/676] [D loss: -0.039810] [G loss: -0.087794] [d1 loss: 0.051605] [d2 loss: 0.041890]  [sq d1 d2: 0.000094]  [num0: 16.000000] [num1 48.000000]
[Epoch 473/500] [Batch 660/676] [D loss: -0.044753] [G loss: -0.042208] [d1 loss: 0.020049] [d2 loss: 0.026445]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 474/500] [Batch 0/676] [D loss: -0.004462] [G loss: -0.054035] [d1 loss: 0.129420] [d2 loss: 0.137675]  [sq d1 d2: 0.000068]  [num0: 12.000000] [num1 52.000000]
[Epoch 474/500] [Batch 20/676] [D loss: -0.014359] [G loss: -0.039341] [d1 loss: 0.102469] [d2 loss: 0.084458]  [sq d1 d2: 0.000324]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 40/676] [D loss: -0.088756] [G loss: -0.024987] [d1 loss: 0.028331] [d2 loss: 0.033286]  [sq d1 d2: 0.000025]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 60/676] [D loss: -0.006969] [G loss: -0.092263] [d1 loss: 0.103213] [d2 loss: 0.102265]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 474/500] [Batch 80/676] [D loss: 0.017290] [G loss: -0.077644] [d1 loss: 0.111774] [d2 loss: 0.115911]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 100/676] [D loss: 0.030672] [G loss: -0.073204] [d1 loss: 0.069181] [d2 loss: 0.059268]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 120/676] [D loss: 0.015319] [G loss: -0.065859] [d1 loss: 0.065780] [d2 loss: 0.080599]  [sq d1 d2: 0.000220]  [num0: 18.000000] [num1 46.000000]
[Epoch 474/500] [Batch 140/676] [D loss: 0.010696] [G loss: -0.065429] [d1 loss: 0.135381] [d2 loss: 0.123728]  [sq d1 d2: 0.000136]  [num0: 18.000000] [num1 46.000000]
[Epoch 474/500] [Batch 160/676] [D loss: -0.006790] [G loss: -0.067726] [d1 loss: 0.097553] [d2 loss: 0.117723]  [sq d1 d2: 0.000407]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 180/676] [D loss: -0.021109] [G loss: -0.083903] [d1 loss: 0.122625] [d2 loss: 0.125803]  [sq d1 d2: 0.000010]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 200/676] [D loss: -0.047658] [G loss: -0.072709] [d1 loss: 0.062420] [d2 loss: 0.057104]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 474/500] [Batch 220/676] [D loss: -0.104618] [G loss: -0.018755] [d1 loss: 0.127740] [d2 loss: 0.127400]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 240/676] [D loss: -0.130048] [G loss: 0.001861] [d1 loss: 0.045867] [d2 loss: 0.034019]  [sq d1 d2: 0.000140]  [num0: 12.000000] [num1 52.000000]
[Epoch 474/500] [Batch 260/676] [D loss: -0.027993] [G loss: -0.028680] [d1 loss: 0.074827] [d2 loss: 0.069693]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 474/500] [Batch 280/676] [D loss: -0.053513] [G loss: -0.054665] [d1 loss: 0.076108] [d2 loss: 0.091367]  [sq d1 d2: 0.000233]  [num0: 19.000000] [num1 45.000000]
[Epoch 474/500] [Batch 300/676] [D loss: 0.042059] [G loss: -0.156508] [d1 loss: 0.026897] [d2 loss: 0.031290]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 320/676] [D loss: 0.003142] [G loss: -0.192507] [d1 loss: 0.067808] [d2 loss: 0.081881]  [sq d1 d2: 0.000198]  [num0: 15.000000] [num1 49.000000]
[Epoch 474/500] [Batch 340/676] [D loss: 0.032725] [G loss: -0.138214] [d1 loss: 0.102566] [d2 loss: 0.104491]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 360/676] [D loss: 0.023955] [G loss: -0.112644] [d1 loss: 0.065664] [d2 loss: 0.055628]  [sq d1 d2: 0.000101]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 380/676] [D loss: 0.007635] [G loss: -0.081711] [d1 loss: 0.101307] [d2 loss: 0.128427]  [sq d1 d2: 0.000736]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 400/676] [D loss: 0.002107] [G loss: -0.025990] [d1 loss: 0.042514] [d2 loss: 0.034512]  [sq d1 d2: 0.000064]  [num0: 14.000000] [num1 50.000000]
[Epoch 474/500] [Batch 420/676] [D loss: -0.021302] [G loss: 0.068403] [d1 loss: 0.024944] [d2 loss: 0.023022]  [sq d1 d2: 0.000004]  [num0: 20.000000] [num1 44.000000]
[Epoch 474/500] [Batch 440/676] [D loss: -0.020865] [G loss: 0.152557] [d1 loss: 0.108760] [d2 loss: 0.123131]  [sq d1 d2: 0.000207]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 460/676] [D loss: -0.067912] [G loss: 0.213200] [d1 loss: 0.043744] [d2 loss: 0.054298]  [sq d1 d2: 0.000111]  [num0: 17.000000] [num1 47.000000]
[Epoch 474/500] [Batch 480/676] [D loss: -0.082955] [G loss: 0.194877] [d1 loss: 0.149744] [d2 loss: 0.127118]  [sq d1 d2: 0.000512]  [num0: 19.000000] [num1 45.000000]
[Epoch 474/500] [Batch 500/676] [D loss: -0.097835] [G loss: 0.217556] [d1 loss: 0.069568] [d2 loss: 0.081031]  [sq d1 d2: 0.000131]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 520/676] [D loss: -0.126121] [G loss: 0.142418] [d1 loss: 0.047505] [d2 loss: 0.050895]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 474/500] [Batch 540/676] [D loss: -0.062785] [G loss: 0.132743] [d1 loss: 0.052161] [d2 loss: 0.046302]  [sq d1 d2: 0.000034]  [num0: 18.000000] [num1 46.000000]
[Epoch 474/500] [Batch 560/676] [D loss: 0.087175] [G loss: 0.067441] [d1 loss: 0.119493] [d2 loss: 0.122279]  [sq d1 d2: 0.000008]  [num0: 18.000000] [num1 46.000000]
[Epoch 474/500] [Batch 580/676] [D loss: -0.001047] [G loss: 0.013290] [d1 loss: 0.209756] [d2 loss: 0.172948]  [sq d1 d2: 0.001355]  [num0: 15.000000] [num1 49.000000]
[Epoch 474/500] [Batch 600/676] [D loss: 0.049150] [G loss: 0.022776] [d1 loss: 0.059230] [d2 loss: 0.060829]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 474/500] [Batch 620/676] [D loss: 0.015229] [G loss: 0.012621] [d1 loss: 0.083265] [d2 loss: 0.077144]  [sq d1 d2: 0.000037]  [num0: 16.000000] [num1 48.000000]
[Epoch 474/500] [Batch 640/676] [D loss: 0.009844] [G loss: -0.030668] [d1 loss: 0.045390] [d2 loss: 0.054511]  [sq d1 d2: 0.000083]  [num0: 14.000000] [num1 50.000000]
[Epoch 474/500] [Batch 660/676] [D loss: -0.016348] [G loss: -0.061343] [d1 loss: 0.074021] [d2 loss: 0.092854]  [sq d1 d2: 0.000355]  [num0: 17.000000] [num1 47.000000]
[Epoch 475/500] [Batch 0/676] [D loss: -0.028736] [G loss: -0.076754] [d1 loss: 0.055499] [d2 loss: 0.048808]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 475/500] [Batch 20/676] [D loss: -0.094725] [G loss: -0.085916] [d1 loss: 0.051026] [d2 loss: 0.057670]  [sq d1 d2: 0.000044]  [num0: 17.000000] [num1 47.000000]
[Epoch 475/500] [Batch 40/676] [D loss: -0.144322] [G loss: -0.115363] [d1 loss: 0.098187] [d2 loss: 0.108748]  [sq d1 d2: 0.000112]  [num0: 14.000000] [num1 50.000000]
[Epoch 475/500] [Batch 60/676] [D loss: -0.079434] [G loss: -0.072673] [d1 loss: 0.041452] [d2 loss: 0.040698]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]

[Epoch 475/500] [Batch 80/676] [D loss: -0.061574] [G loss: -0.090544] [d1 loss: 0.090954] [d2 loss: 0.088847]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 100/676] [D loss: -0.047535] [G loss: -0.123210] [d1 loss: 0.060954] [d2 loss: 0.073495]  [sq d1 d2: 0.000157]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 120/676] [D loss: 0.013478] [G loss: -0.207079] [d1 loss: 0.150579] [d2 loss: 0.120878]  [sq d1 d2: 0.000882]  [num0: 17.000000] [num1 47.000000]
[Epoch 475/500] [Batch 140/676] [D loss: -0.024061] [G loss: -0.266134] [d1 loss: 0.121209] [d2 loss: 0.095116]  [sq d1 d2: 0.000681]  [num0: 14.000000] [num1 50.000000]
[Epoch 475/500] [Batch 160/676] [D loss: 0.037944] [G loss: -0.289554] [d1 loss: 0.093079] [d2 loss: 0.103452]  [sq d1 d2: 0.000108]  [num0: 18.000000] [num1 46.000000]
[Epoch 475/500] [Batch 180/676] [D loss: 0.007008] [G loss: -0.268134] [d1 loss: 0.047995] [d2 loss: 0.042244]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 200/676] [D loss: 0.020108] [G loss: -0.195879] [d1 loss: 0.061176] [d2 loss: 0.066398]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 475/500] [Batch 220/676] [D loss: -0.001691] [G loss: -0.138474] [d1 loss: 0.038600] [d2 loss: 0.040144]  [sq d1 d2: 0.000002]  [num0: 12.000000] [num1 52.000000]
[Epoch 475/500] [Batch 240/676] [D loss: -0.007961] [G loss: -0.081743] [d1 loss: 0.031675] [d2 loss: 0.027424]  [sq d1 d2: 0.000018]  [num0: 12.000000] [num1 52.000000]
[Epoch 475/500] [Batch 260/676] [D loss: -0.023179] [G loss: -0.041189] [d1 loss: 0.033147] [d2 loss: 0.038812]  [sq d1 d2: 0.000032]  [num0: 18.000000] [num1 46.000000]
[Epoch 475/500] [Batch 280/676] [D loss: -0.054999] [G loss: 0.052995] [d1 loss: 0.067970] [d2 loss: 0.060201]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 475/500] [Batch 300/676] [D loss: -0.047973] [G loss: 0.099331] [d1 loss: 0.102710] [d2 loss: 0.101599]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 475/500] [Batch 320/676] [D loss: -0.103524] [G loss: 0.144983] [d1 loss: 0.090107] [d2 loss: 0.088399]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 475/500] [Batch 340/676] [D loss: -0.085945] [G loss: 0.104935] [d1 loss: 0.096395] [d2 loss: 0.074695]  [sq d1 d2: 0.000471]  [num0: 15.000000] [num1 49.000000]
[Epoch 475/500] [Batch 360/676] [D loss: -0.037042] [G loss: 0.088162] [d1 loss: 0.109764] [d2 loss: 0.080125]  [sq d1 d2: 0.000879]  [num0: 12.000000] [num1 52.000000]
[Epoch 475/500] [Batch 380/676] [D loss: -0.004142] [G loss: 0.047678] [d1 loss: 0.057744] [d2 loss: 0.063741]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 400/676] [D loss: 0.025448] [G loss: 0.076073] [d1 loss: 0.037266] [d2 loss: 0.042134]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 420/676] [D loss: 0.030869] [G loss: 0.092417] [d1 loss: 0.065928] [d2 loss: 0.056709]  [sq d1 d2: 0.000085]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 440/676] [D loss: 0.018588] [G loss: 0.118428] [d1 loss: 0.171694] [d2 loss: 0.175868]  [sq d1 d2: 0.000017]  [num0: 17.000000] [num1 47.000000]
[Epoch 475/500] [Batch 460/676] [D loss: 0.022116] [G loss: 0.077225] [d1 loss: 0.129682] [d2 loss: 0.120855]  [sq d1 d2: 0.000078]  [num0: 13.000000] [num1 51.000000]
[Epoch 475/500] [Batch 480/676] [D loss: -0.000732] [G loss: 0.061462] [d1 loss: 0.071238] [d2 loss: 0.084625]  [sq d1 d2: 0.000179]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 500/676] [D loss: -0.012032] [G loss: 0.048814] [d1 loss: 0.086096] [d2 loss: 0.071035]  [sq d1 d2: 0.000227]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 520/676] [D loss: -0.029504] [G loss: 0.057491] [d1 loss: 0.094110] [d2 loss: 0.078807]  [sq d1 d2: 0.000234]  [num0: 18.000000] [num1 46.000000]
[Epoch 475/500] [Batch 540/676] [D loss: -0.061014] [G loss: 0.088429] [d1 loss: 0.067573] [d2 loss: 0.069854]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 475/500] [Batch 560/676] [D loss: -0.082274] [G loss: 0.025263] [d1 loss: 0.034134] [d2 loss: 0.045854]  [sq d1 d2: 0.000137]  [num0: 15.000000] [num1 49.000000]
[Epoch 475/500] [Batch 580/676] [D loss: -0.091419] [G loss: -0.038043] [d1 loss: 0.121329] [d2 loss: 0.121264]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 600/676] [D loss: -0.052604] [G loss: -0.082615] [d1 loss: 0.037816] [d2 loss: 0.037662]  [sq d1 d2: 0.000000]  [num0: 21.000000] [num1 43.000000]
[Epoch 475/500] [Batch 620/676] [D loss: -0.043259] [G loss: -0.190036] [d1 loss: 0.073542] [d2 loss: 0.073680]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 475/500] [Batch 640/676] [D loss: -0.043511] [G loss: -0.182637] [d1 loss: 0.045624] [d2 loss: 0.046262]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 475/500] [Batch 660/676] [D loss: 0.022158] [G loss: -0.169210] [d1 loss: 0.082381] [d2 loss: 0.070812]  [sq d1 d2: 0.000134]  [num0: 14.000000] [num1 50.000000]
[Epoch 476/500] [Batch 0/676] [D loss: 0.005723] [G loss: -0.209758] [d1 loss: 0.100060] [d2 loss: 0.070877]  [sq d1 d2: 0.000852]  [num0: 17.000000] [num1 47.000000]
[Epoch 476/500] [Batch 20/676] [D loss: 0.024996] [G loss: -0.204885] [d1 loss: 0.045205] [d2 loss: 0.040368]  [sq d1 d2: 0.000023]  [num0: 18.000000] [num1 46.000000]
[Epoch 476/500] [Batch 40/676] [D loss: 0.016280] [G loss: -0.181294] [d1 loss: 0.068549] [d2 loss: 0.069881]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 476/500] [Batch 60/676] [D loss: 0.017876] [G loss: -0.155551] [d1 loss: 0.039125] [d2 loss: 0.053676]  [sq d1 d2: 0.000212]  [num0: 18.000000] [num1 46.000000]
[Epoch 476/500] [Batch 80/676] [D loss: 0.004078] [G loss: -0.087929] [d1 loss: 0.079731] [d2 loss: 0.076154]  [sq d1 d2: 0.000013]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 100/676] [D loss: -0.005918] [G loss: -0.016169] [d1 loss: 0.070174] [d2 loss: 0.070444]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 476/500] [Batch 120/676] [D loss: -0.031360] [G loss: -0.001574] [d1 loss: 0.142731] [d2 loss: 0.096374]  [sq d1 d2: 0.002149]  [num0: 15.000000] [num1 49.000000]
[Epoch 476/500] [Batch 140/676] [D loss: -0.057680] [G loss: 0.081085] [d1 loss: 0.012687] [d2 loss: 0.011437]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 476/500] [Batch 160/676] [D loss: -0.058514] [G loss: 0.160772] [d1 loss: 0.059113] [d2 loss: 0.059950]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 180/676] [D loss: -0.138048] [G loss: 0.166183] [d1 loss: 0.034991] [d2 loss: 0.030341]  [sq d1 d2: 0.000022]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 200/676] [D loss: -0.111392] [G loss: 0.131332] [d1 loss: 0.132447] [d2 loss: 0.132987]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 476/500] [Batch 220/676] [D loss: -0.021672] [G loss: 0.059347] [d1 loss: 0.098763] [d2 loss: 0.109680]  [sq d1 d2: 0.000119]  [num0: 13.000000] [num1 51.000000]
[Epoch 476/500] [Batch 240/676] [D loss: -0.034277] [G loss: 0.068100] [d1 loss: 0.073077] [d2 loss: 0.081168]  [sq d1 d2: 0.000065]  [num0: 12.000000] [num1 52.000000]
[Epoch 476/500] [Batch 260/676] [D loss: -0.031186] [G loss: 0.059950] [d1 loss: 0.046811] [d2 loss: 0.065183]  [sq d1 d2: 0.000338]  [num0: 18.000000] [num1 46.000000]
[Epoch 476/500] [Batch 280/676] [D loss: 0.061680] [G loss: -0.001607] [d1 loss: 0.097588] [d2 loss: 0.121372]  [sq d1 d2: 0.000566]  [num0: 15.000000] [num1 49.000000]
[Epoch 476/500] [Batch 300/676] [D loss: 0.024443] [G loss: -0.006232] [d1 loss: 0.091253] [d2 loss: 0.058611]  [sq d1 d2: 0.001066]  [num0: 15.000000] [num1 49.000000]
[Epoch 476/500] [Batch 320/676] [D loss: 0.028641] [G loss: -0.045838] [d1 loss: 0.046433] [d2 loss: 0.049258]  [sq d1 d2: 0.000008]  [num0: 14.000000] [num1 50.000000]
[Epoch 476/500] [Batch 340/676] [D loss: 0.023054] [G loss: -0.031489] [d1 loss: 0.140994] [d2 loss: 0.117823]  [sq d1 d2: 0.000537]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 360/676] [D loss: 0.012099] [G loss: -0.040632] [d1 loss: 0.124299] [d2 loss: 0.102829]  [sq d1 d2: 0.000461]  [num0: 15.000000] [num1 49.000000]
[Epoch 476/500] [Batch 380/676] [D loss: -0.000875] [G loss: -0.041723] [d1 loss: 0.134916] [d2 loss: 0.134626]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 400/676] [D loss: -0.014483] [G loss: -0.041470] [d1 loss: 0.041770] [d2 loss: 0.044254]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 476/500] [Batch 420/676] [D loss: -0.036273] [G loss: -0.029276] [d1 loss: 0.083499] [d2 loss: 0.079062]  [sq d1 d2: 0.000020]  [num0: 16.000000] [num1 48.000000]

[Epoch 476/500] [Batch 440/676] [D loss: -0.060477] [G loss: 0.046440] [d1 loss: 0.045925] [d2 loss: 0.052316]  [sq d1 d2: 0.000041]  [num0: 17.000000] [num1 47.000000]
[Epoch 476/500] [Batch 460/676] [D loss: -0.063341] [G loss: 0.043619] [d1 loss: 0.124038] [d2 loss: 0.107839]  [sq d1 d2: 0.000262]  [num0: 12.000000] [num1 52.000000]
[Epoch 476/500] [Batch 480/676] [D loss: -0.067666] [G loss: 0.080686] [d1 loss: 0.054506] [d2 loss: 0.040974]  [sq d1 d2: 0.000183]  [num0: 14.000000] [num1 50.000000]
[Epoch 476/500] [Batch 500/676] [D loss: -0.088656] [G loss: 0.059586] [d1 loss: 0.060311] [d2 loss: 0.055977]  [sq d1 d2: 0.000019]  [num0: 14.000000] [num1 50.000000]
[Epoch 476/500] [Batch 520/676] [D loss: -0.001101] [G loss: 0.033810] [d1 loss: 0.023972] [d2 loss: 0.024538]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 540/676] [D loss: 0.012749] [G loss: -0.018289] [d1 loss: 0.076290] [d2 loss: 0.058893]  [sq d1 d2: 0.000303]  [num0: 21.000000] [num1 43.000000]
[Epoch 476/500] [Batch 560/676] [D loss: 0.042131] [G loss: -0.031965] [d1 loss: 0.033884] [d2 loss: 0.036006]  [sq d1 d2: 0.000005]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 580/676] [D loss: -0.004979] [G loss: -0.091065] [d1 loss: 0.056367] [d2 loss: 0.050648]  [sq d1 d2: 0.000033]  [num0: 16.000000] [num1 48.000000]
[Epoch 476/500] [Batch 600/676] [D loss: 0.046466] [G loss: -0.104165] [d1 loss: 0.060996] [d2 loss: 0.063474]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 476/500] [Batch 620/676] [D loss: 0.038668] [G loss: -0.064619] [d1 loss: 0.077106] [d2 loss: 0.071194]  [sq d1 d2: 0.000035]  [num0: 19.000000] [num1 45.000000]
[Epoch 476/500] [Batch 640/676] [D loss: 0.026493] [G loss: -0.044828] [d1 loss: 0.140547] [d2 loss: 0.069042]  [sq d1 d2: 0.005113]  [num0: 13.000000] [num1 51.000000]
[Epoch 476/500] [Batch 660/676] [D loss: 0.010040] [G loss: -0.039132] [d1 loss: 0.088640] [d2 loss: 0.093757]  [sq d1 d2: 0.000026]  [num0: 22.000000] [num1 42.000000]
[Epoch 477/500] [Batch 0/676] [D loss: -0.000290] [G loss: -0.037405] [d1 loss: 0.069614] [d2 loss: 0.084523]  [sq d1 d2: 0.000222]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 20/676] [D loss: -0.007978] [G loss: -0.028586] [d1 loss: 0.190290] [d2 loss: 0.158796]  [sq d1 d2: 0.000992]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 40/676] [D loss: -0.019397] [G loss: -0.023701] [d1 loss: 0.088609] [d2 loss: 0.068131]  [sq d1 d2: 0.000419]  [num0: 12.000000] [num1 52.000000]
[Epoch 477/500] [Batch 60/676] [D loss: -0.014534] [G loss: -0.036130] [d1 loss: 0.032388] [d2 loss: 0.044080]  [sq d1 d2: 0.000137]  [num0: 13.000000] [num1 51.000000]
[Epoch 477/500] [Batch 80/676] [D loss: -0.043489] [G loss: -0.036881] [d1 loss: 0.098148] [d2 loss: 0.112381]  [sq d1 d2: 0.000203]  [num0: 14.000000] [num1 50.000000]
[Epoch 477/500] [Batch 100/676] [D loss: -0.027918] [G loss: -0.030654] [d1 loss: 0.159065] [d2 loss: 0.143373]  [sq d1 d2: 0.000246]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 120/676] [D loss: -0.071641] [G loss: -0.014003] [d1 loss: 0.101763] [d2 loss: 0.104782]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 140/676] [D loss: -0.026239] [G loss: -0.047537] [d1 loss: 0.085870] [d2 loss: 0.087709]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 477/500] [Batch 160/676] [D loss: -0.039896] [G loss: -0.059523] [d1 loss: 0.087115] [d2 loss: 0.059726]  [sq d1 d2: 0.000750]  [num0: 15.000000] [num1 49.000000]
[Epoch 477/500] [Batch 180/676] [D loss: 0.068074] [G loss: -0.119814] [d1 loss: 0.116823] [d2 loss: 0.119485]  [sq d1 d2: 0.000007]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 200/676] [D loss: -0.015683] [G loss: -0.184660] [d1 loss: 0.161504] [d2 loss: 0.105937]  [sq d1 d2: 0.003088]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 220/676] [D loss: 0.004675] [G loss: -0.207464] [d1 loss: 0.048602] [d2 loss: 0.043247]  [sq d1 d2: 0.000029]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 240/676] [D loss: 0.032222] [G loss: -0.250845] [d1 loss: 0.109080] [d2 loss: 0.111553]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 477/500] [Batch 260/676] [D loss: 0.027409] [G loss: -0.227570] [d1 loss: 0.096338] [d2 loss: 0.086789]  [sq d1 d2: 0.000091]  [num0: 19.000000] [num1 45.000000]
[Epoch 477/500] [Batch 280/676] [D loss: 0.009062] [G loss: -0.152045] [d1 loss: 0.057409] [d2 loss: 0.059723]  [sq d1 d2: 0.000005]  [num0: 17.000000] [num1 47.000000]
[Epoch 477/500] [Batch 300/676] [D loss: 0.019041] [G loss: -0.096207] [d1 loss: 0.066873] [d2 loss: 0.063132]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 477/500] [Batch 320/676] [D loss: 0.004284] [G loss: -0.064138] [d1 loss: 0.190934] [d2 loss: 0.176156]  [sq d1 d2: 0.000218]  [num0: 14.000000] [num1 50.000000]
[Epoch 477/500] [Batch 340/676] [D loss: -0.004342] [G loss: -0.035761] [d1 loss: 0.059933] [d2 loss: 0.054022]  [sq d1 d2: 0.000035]  [num0: 12.000000] [num1 52.000000]
[Epoch 477/500] [Batch 360/676] [D loss: -0.013088] [G loss: -0.005807] [d1 loss: 0.148471] [d2 loss: 0.162301]  [sq d1 d2: 0.000191]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 380/676] [D loss: -0.026972] [G loss: 0.060235] [d1 loss: 0.141330] [d2 loss: 0.059778]  [sq d1 d2: 0.006651]  [num0: 17.000000] [num1 47.000000]
[Epoch 477/500] [Batch 400/676] [D loss: -0.055237] [G loss: 0.126502] [d1 loss: 0.130147] [d2 loss: 0.119888]  [sq d1 d2: 0.000105]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 420/676] [D loss: -0.054676] [G loss: 0.210803] [d1 loss: 0.120596] [d2 loss: 0.099722]  [sq d1 d2: 0.000436]  [num0: 20.000000] [num1 44.000000]
[Epoch 477/500] [Batch 440/676] [D loss: -0.051837] [G loss: 0.255062] [d1 loss: 0.062903] [d2 loss: 0.056822]  [sq d1 d2: 0.000037]  [num0: 13.000000] [num1 51.000000]
[Epoch 477/500] [Batch 460/676] [D loss: -0.029908] [G loss: 0.224582] [d1 loss: 0.126690] [d2 loss: 0.118282]  [sq d1 d2: 0.000071]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 480/676] [D loss: -0.034566] [G loss: 0.193932] [d1 loss: 0.055226] [d2 loss: 0.042614]  [sq d1 d2: 0.000159]  [num0: 11.000000] [num1 53.000000]
[Epoch 477/500] [Batch 500/676] [D loss: -0.040958] [G loss: 0.182235] [d1 loss: 0.119540] [d2 loss: 0.106827]  [sq d1 d2: 0.000162]  [num0: 20.000000] [num1 44.000000]
[Epoch 477/500] [Batch 520/676] [D loss: -0.056171] [G loss: 0.184256] [d1 loss: 0.132183] [d2 loss: 0.129010]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 540/676] [D loss: -0.020390] [G loss: 0.213611] [d1 loss: 0.084938] [d2 loss: 0.069890]  [sq d1 d2: 0.000226]  [num0: 11.000000] [num1 53.000000]
[Epoch 477/500] [Batch 560/676] [D loss: 0.016616] [G loss: 0.239053] [d1 loss: 0.087088] [d2 loss: 0.107178]  [sq d1 d2: 0.000404]  [num0: 18.000000] [num1 46.000000]
[Epoch 477/500] [Batch 580/676] [D loss: 0.035820] [G loss: 0.192736] [d1 loss: 0.055748] [d2 loss: 0.059277]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 477/500] [Batch 600/676] [D loss: 0.027339] [G loss: 0.179767] [d1 loss: 0.081389] [d2 loss: 0.071897]  [sq d1 d2: 0.000090]  [num0: 14.000000] [num1 50.000000]
[Epoch 477/500] [Batch 620/676] [D loss: 0.003442] [G loss: 0.138038] [d1 loss: 0.030704] [d2 loss: 0.025889]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 477/500] [Batch 640/676] [D loss: 0.004840] [G loss: 0.105261] [d1 loss: 0.031213] [d2 loss: 0.041927]  [sq d1 d2: 0.000115]  [num0: 13.000000] [num1 51.000000]
[Epoch 477/500] [Batch 660/676] [D loss: 0.010278] [G loss: 0.074953] [d1 loss: 0.125826] [d2 loss: 0.114143]  [sq d1 d2: 0.000136]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 0/676] [D loss: 0.006049] [G loss: 0.050914] [d1 loss: 0.322535] [d2 loss: 0.336971]  [sq d1 d2: 0.000208]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 20/676] [D loss: 0.002506] [G loss: 0.020128] [d1 loss: 0.125075] [d2 loss: 0.102607]  [sq d1 d2: 0.000505]  [num0: 17.000000] [num1 47.000000]
[Epoch 478/500] [Batch 40/676] [D loss: -0.006031] [G loss: -0.012735] [d1 loss: 0.093688] [d2 loss: 0.102614]  [sq d1 d2: 0.000080]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 60/676] [D loss: -0.009610] [G loss: -0.041571] [d1 loss: 0.047484] [d2 loss: 0.055202]  [sq d1 d2: 0.000060]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 80/676] [D loss: -0.008756] [G loss: -0.074220] [d1 loss: 0.101487] [d2 loss: 0.114588]  [sq d1 d2: 0.000172]  [num0: 18.000000] [num1 46.000000]

[Epoch 478/500] [Batch 100/676] [D loss: -0.014245] [G loss: -0.119707] [d1 loss: 0.018647] [d2 loss: 0.022900]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 120/676] [D loss: -0.012942] [G loss: -0.127875] [d1 loss: 0.079200] [d2 loss: 0.064165]  [sq d1 d2: 0.000226]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 140/676] [D loss: -0.035027] [G loss: -0.142526] [d1 loss: 0.163944] [d2 loss: 0.133246]  [sq d1 d2: 0.000942]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 160/676] [D loss: -0.043813] [G loss: -0.161577] [d1 loss: 0.108620] [d2 loss: 0.117269]  [sq d1 d2: 0.000075]  [num0: 17.000000] [num1 47.000000]
[Epoch 478/500] [Batch 180/676] [D loss: -0.035074] [G loss: -0.154318] [d1 loss: 0.078330] [d2 loss: 0.080184]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 478/500] [Batch 200/676] [D loss: -0.014574] [G loss: -0.219633] [d1 loss: 0.043721] [d2 loss: 0.044747]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 220/676] [D loss: -0.041879] [G loss: -0.227612] [d1 loss: 0.047889] [d2 loss: 0.045709]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 240/676] [D loss: -0.004266] [G loss: -0.239206] [d1 loss: 0.075069] [d2 loss: 0.086320]  [sq d1 d2: 0.000127]  [num0: 19.000000] [num1 45.000000]
[Epoch 478/500] [Batch 260/676] [D loss: -0.005808] [G loss: -0.242237] [d1 loss: 0.116749] [d2 loss: 0.109243]  [sq d1 d2: 0.000056]  [num0: 19.000000] [num1 45.000000]
[Epoch 478/500] [Batch 280/676] [D loss: 0.000371] [G loss: -0.238694] [d1 loss: 0.089684] [d2 loss: 0.078537]  [sq d1 d2: 0.000124]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 300/676] [D loss: -0.010900] [G loss: -0.185549] [d1 loss: 0.094826] [d2 loss: 0.084774]  [sq d1 d2: 0.000101]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 320/676] [D loss: 0.015503] [G loss: -0.126901] [d1 loss: 0.064252] [d2 loss: 0.072061]  [sq d1 d2: 0.000061]  [num0: 13.000000] [num1 51.000000]
[Epoch 478/500] [Batch 340/676] [D loss: 0.006426] [G loss: -0.114097] [d1 loss: 0.043927] [d2 loss: 0.044569]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 478/500] [Batch 360/676] [D loss: 0.006779] [G loss: -0.092123] [d1 loss: 0.152994] [d2 loss: 0.136097]  [sq d1 d2: 0.000286]  [num0: 20.000000] [num1 44.000000]
[Epoch 478/500] [Batch 380/676] [D loss: 0.003870] [G loss: -0.073019] [d1 loss: 0.079888] [d2 loss: 0.070887]  [sq d1 d2: 0.000081]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 400/676] [D loss: -0.002563] [G loss: -0.060661] [d1 loss: 0.054399] [d2 loss: 0.058199]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 478/500] [Batch 420/676] [D loss: 0.003600] [G loss: -0.063043] [d1 loss: 0.070077] [d2 loss: 0.058841]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 440/676] [D loss: -0.001004] [G loss: -0.056171] [d1 loss: 0.046767] [d2 loss: 0.059946]  [sq d1 d2: 0.000174]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 460/676] [D loss: -0.004131] [G loss: -0.072609] [d1 loss: 0.087642] [d2 loss: 0.092462]  [sq d1 d2: 0.000023]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 480/676] [D loss: -0.004949] [G loss: -0.066734] [d1 loss: 0.065447] [d2 loss: 0.065646]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 478/500] [Batch 500/676] [D loss: -0.009900] [G loss: -0.070036] [d1 loss: 0.188868] [d2 loss: 0.179695]  [sq d1 d2: 0.000084]  [num0: 17.000000] [num1 47.000000]
[Epoch 478/500] [Batch 520/676] [D loss: -0.012382] [G loss: -0.068930] [d1 loss: 0.056360] [d2 loss: 0.059522]  [sq d1 d2: 0.000010]  [num0: 13.000000] [num1 51.000000]
[Epoch 478/500] [Batch 540/676] [D loss: -0.013646] [G loss: -0.078573] [d1 loss: 0.071184] [d2 loss: 0.059953]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 560/676] [D loss: -0.025573] [G loss: -0.057254] [d1 loss: 0.165452] [d2 loss: 0.131494]  [sq d1 d2: 0.001153]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 580/676] [D loss: -0.005578] [G loss: -0.027998] [d1 loss: 0.052134] [d2 loss: 0.076113]  [sq d1 d2: 0.000575]  [num0: 15.000000] [num1 49.000000]
[Epoch 478/500] [Batch 600/676] [D loss: -0.029923] [G loss: -0.034749] [d1 loss: 0.124082] [d2 loss: 0.148486]  [sq d1 d2: 0.000596]  [num0: 13.000000] [num1 51.000000]
[Epoch 478/500] [Batch 620/676] [D loss: -0.027298] [G loss: -0.022456] [d1 loss: 0.118546] [d2 loss: 0.145478]  [sq d1 d2: 0.000725]  [num0: 14.000000] [num1 50.000000]
[Epoch 478/500] [Batch 640/676] [D loss: 0.001480] [G loss: 0.011120] [d1 loss: 0.078541] [d2 loss: 0.087231]  [sq d1 d2: 0.000076]  [num0: 19.000000] [num1 45.000000]
[Epoch 478/500] [Batch 660/676] [D loss: -0.015519] [G loss: 0.040356] [d1 loss: 0.061189] [d2 loss: 0.074533]  [sq d1 d2: 0.000178]  [num0: 13.000000] [num1 51.000000]
[Epoch 479/500] [Batch 0/676] [D loss: -0.017075] [G loss: 0.039378] [d1 loss: 0.075429] [d2 loss: 0.083266]  [sq d1 d2: 0.000061]  [num0: 18.000000] [num1 46.000000]
[Epoch 479/500] [Batch 20/676] [D loss: -0.000703] [G loss: 0.042599] [d1 loss: 0.115480] [d2 loss: 0.132019]  [sq d1 d2: 0.000274]  [num0: 12.000000] [num1 52.000000]
[Epoch 479/500] [Batch 40/676] [D loss: -0.008711] [G loss: 0.056166] [d1 loss: 0.071413] [d2 loss: 0.085065]  [sq d1 d2: 0.000186]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 60/676] [D loss: 0.034785] [G loss: 0.061034] [d1 loss: 0.056701] [d2 loss: 0.063152]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 479/500] [Batch 80/676] [D loss: 0.019846] [G loss: 0.067058] [d1 loss: 0.097752] [d2 loss: 0.094606]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 479/500] [Batch 100/676] [D loss: -0.014217] [G loss: 0.046894] [d1 loss: 0.110198] [d2 loss: 0.098253]  [sq d1 d2: 0.000143]  [num0: 15.000000] [num1 49.000000]
[Epoch 479/500] [Batch 120/676] [D loss: 0.009531] [G loss: 0.042231] [d1 loss: 0.050117] [d2 loss: 0.057061]  [sq d1 d2: 0.000048]  [num0: 12.000000] [num1 52.000000]
[Epoch 479/500] [Batch 140/676] [D loss: 0.000802] [G loss: 0.052936] [d1 loss: 0.035166] [d2 loss: 0.037151]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 160/676] [D loss: -0.002682] [G loss: 0.062770] [d1 loss: 0.047529] [d2 loss: 0.043252]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 180/676] [D loss: -0.003806] [G loss: 0.069465] [d1 loss: 0.142629] [d2 loss: 0.163567]  [sq d1 d2: 0.000438]  [num0: 20.000000] [num1 44.000000]
[Epoch 479/500] [Batch 200/676] [D loss: -0.017520] [G loss: 0.074377] [d1 loss: 0.126374] [d2 loss: 0.101813]  [sq d1 d2: 0.000603]  [num0: 14.000000] [num1 50.000000]
[Epoch 479/500] [Batch 220/676] [D loss: -0.008872] [G loss: 0.077267] [d1 loss: 0.045434] [d2 loss: 0.057064]  [sq d1 d2: 0.000135]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 240/676] [D loss: -0.020284] [G loss: 0.085491] [d1 loss: 0.034131] [d2 loss: 0.031519]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 479/500] [Batch 260/676] [D loss: -0.006781] [G loss: 0.101808] [d1 loss: 0.072099] [d2 loss: 0.074731]  [sq d1 d2: 0.000007]  [num0: 15.000000] [num1 49.000000]
[Epoch 479/500] [Batch 280/676] [D loss: 0.003059] [G loss: 0.129416] [d1 loss: 0.022207] [d2 loss: 0.025147]  [sq d1 d2: 0.000009]  [num0: 15.000000] [num1 49.000000]
[Epoch 479/500] [Batch 300/676] [D loss: -0.005911] [G loss: 0.119833] [d1 loss: 0.112294] [d2 loss: 0.109286]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 320/676] [D loss: -0.020825] [G loss: 0.155542] [d1 loss: 0.068543] [d2 loss: 0.064215]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 340/676] [D loss: -0.026903] [G loss: 0.131502] [d1 loss: 0.055571] [d2 loss: 0.071325]  [sq d1 d2: 0.000248]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 360/676] [D loss: 0.004870] [G loss: 0.106134] [d1 loss: 0.067222] [d2 loss: 0.059808]  [sq d1 d2: 0.000055]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 380/676] [D loss: 0.011791] [G loss: 0.124438] [d1 loss: 0.084949] [d2 loss: 0.097625]  [sq d1 d2: 0.000161]  [num0: 18.000000] [num1 46.000000]

[Epoch 479/500] [Batch 400/676] [D loss: 0.030928] [G loss: 0.095031] [d1 loss: 0.116711] [d2 loss: 0.203127]  [sq d1 d2: 0.007468]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 420/676] [D loss: 0.007607] [G loss: 0.083574] [d1 loss: 0.070536] [d2 loss: 0.071344]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 479/500] [Batch 440/676] [D loss: -0.015889] [G loss: 0.089085] [d1 loss: 0.059083] [d2 loss: 0.069336]  [sq d1 d2: 0.000105]  [num0: 14.000000] [num1 50.000000]
[Epoch 479/500] [Batch 460/676] [D loss: -0.011263] [G loss: 0.078600] [d1 loss: 0.049697] [d2 loss: 0.057921]  [sq d1 d2: 0.000068]  [num0: 14.000000] [num1 50.000000]
[Epoch 479/500] [Batch 480/676] [D loss: 0.029321] [G loss: 0.061304] [d1 loss: 0.032081] [d2 loss: 0.032389]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 479/500] [Batch 500/676] [D loss: -0.002209] [G loss: 0.029635] [d1 loss: 0.161094] [d2 loss: 0.155973]  [sq d1 d2: 0.000026]  [num0: 19.000000] [num1 45.000000]
[Epoch 479/500] [Batch 520/676] [D loss: 0.007333] [G loss: 0.037098] [d1 loss: 0.155833] [d2 loss: 0.148994]  [sq d1 d2: 0.000047]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 540/676] [D loss: -0.005569] [G loss: 0.005348] [d1 loss: 0.088405] [d2 loss: 0.110165]  [sq d1 d2: 0.000473]  [num0: 20.000000] [num1 44.000000]
[Epoch 479/500] [Batch 560/676] [D loss: -0.002891] [G loss: 0.006876] [d1 loss: 0.097839] [d2 loss: 0.124705]  [sq d1 d2: 0.000722]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 580/676] [D loss: -0.009926] [G loss: -0.003710] [d1 loss: 0.029028] [d2 loss: 0.035033]  [sq d1 d2: 0.000036]  [num0: 16.000000] [num1 48.000000]
[Epoch 479/500] [Batch 600/676] [D loss: -0.008629] [G loss: 0.002178] [d1 loss: 0.066417] [d2 loss: 0.065270]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 620/676] [D loss: -0.002715] [G loss: 0.017065] [d1 loss: 0.106467] [d2 loss: 0.126926]  [sq d1 d2: 0.000419]  [num0: 15.000000] [num1 49.000000]
[Epoch 479/500] [Batch 640/676] [D loss: -0.006092] [G loss: 0.019275] [d1 loss: 0.098344] [d2 loss: 0.096256]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 479/500] [Batch 660/676] [D loss: -0.021935] [G loss: 0.014382] [d1 loss: 0.107525] [d2 loss: 0.097389]  [sq d1 d2: 0.000103]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 0/676] [D loss: -0.008575] [G loss: 0.011168] [d1 loss: 0.133162] [d2 loss: 0.128438]  [sq d1 d2: 0.000022]  [num0: 14.000000] [num1 50.000000]
[Epoch 480/500] [Batch 20/676] [D loss: -0.029286] [G loss: -0.021254] [d1 loss: 0.059876] [d2 loss: 0.059344]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 40/676] [D loss: -0.008259] [G loss: -0.034378] [d1 loss: 0.043901] [d2 loss: 0.046842]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 480/500] [Batch 60/676] [D loss: 0.009977] [G loss: -0.063685] [d1 loss: 0.056594] [d2 loss: 0.058851]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 480/500] [Batch 80/676] [D loss: 0.001951] [G loss: -0.074240] [d1 loss: 0.091593] [d2 loss: 0.063163]  [sq d1 d2: 0.000808]  [num0: 17.000000] [num1 47.000000]
[Epoch 480/500] [Batch 100/676] [D loss: -0.000953] [G loss: -0.077876] [d1 loss: 0.016657] [d2 loss: 0.022242]  [sq d1 d2: 0.000031]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 120/676] [D loss: -0.014093] [G loss: -0.093577] [d1 loss: 0.098020] [d2 loss: 0.114399]  [sq d1 d2: 0.000268]  [num0: 19.000000] [num1 45.000000]
[Epoch 480/500] [Batch 140/676] [D loss: -0.009275] [G loss: -0.110328] [d1 loss: 0.165801] [d2 loss: 0.157801]  [sq d1 d2: 0.000064]  [num0: 18.000000] [num1 46.000000]
[Epoch 480/500] [Batch 160/676] [D loss: -0.003285] [G loss: -0.110912] [d1 loss: 0.085183] [d2 loss: 0.070558]  [sq d1 d2: 0.000214]  [num0: 18.000000] [num1 46.000000]
[Epoch 480/500] [Batch 180/676] [D loss: 0.006126] [G loss: -0.118471] [d1 loss: 0.094132] [d2 loss: 0.083164]  [sq d1 d2: 0.000120]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 200/676] [D loss: 0.000190] [G loss: -0.090977] [d1 loss: 0.073852] [d2 loss: 0.054820]  [sq d1 d2: 0.000362]  [num0: 19.000000] [num1 45.000000]
[Epoch 480/500] [Batch 220/676] [D loss: -0.004493] [G loss: -0.081553] [d1 loss: 0.034422] [d2 loss: 0.042770]  [sq d1 d2: 0.000070]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 240/676] [D loss: -0.003173] [G loss: -0.077325] [d1 loss: 0.058133] [d2 loss: 0.081970]  [sq d1 d2: 0.000568]  [num0: 17.000000] [num1 47.000000]
[Epoch 480/500] [Batch 260/676] [D loss: -0.008932] [G loss: -0.125093] [d1 loss: 0.099999] [d2 loss: 0.065976]  [sq d1 d2: 0.001158]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 280/676] [D loss: 0.004134] [G loss: -0.125570] [d1 loss: 0.087488] [d2 loss: 0.088144]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 300/676] [D loss: -0.024222] [G loss: -0.147671] [d1 loss: 0.087086] [d2 loss: 0.052582]  [sq d1 d2: 0.001191]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 320/676] [D loss: -0.009855] [G loss: -0.164626] [d1 loss: 0.053449] [d2 loss: 0.052846]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 480/500] [Batch 340/676] [D loss: -0.005846] [G loss: -0.159459] [d1 loss: 0.063531] [d2 loss: 0.049179]  [sq d1 d2: 0.000206]  [num0: 19.000000] [num1 45.000000]
[Epoch 480/500] [Batch 360/676] [D loss: -0.013677] [G loss: -0.175774] [d1 loss: 0.026155] [d2 loss: 0.031371]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 380/676] [D loss: -0.019106] [G loss: -0.212354] [d1 loss: 0.093339] [d2 loss: 0.101254]  [sq d1 d2: 0.000063]  [num0: 14.000000] [num1 50.000000]
[Epoch 480/500] [Batch 400/676] [D loss: 0.016698] [G loss: -0.183305] [d1 loss: 0.051610] [d2 loss: 0.030827]  [sq d1 d2: 0.000432]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 420/676] [D loss: -0.017175] [G loss: -0.199908] [d1 loss: 0.042712] [d2 loss: 0.042047]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 440/676] [D loss: 0.034263] [G loss: -0.195836] [d1 loss: 0.182879] [d2 loss: 0.158265]  [sq d1 d2: 0.000606]  [num0: 16.000000] [num1 48.000000]
[Epoch 480/500] [Batch 460/676] [D loss: 0.009418] [G loss: -0.178253] [d1 loss: 0.048910] [d2 loss: 0.050437]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 480/500] [Batch 480/676] [D loss: 0.009308] [G loss: -0.174608] [d1 loss: 0.060582] [d2 loss: 0.070947]  [sq d1 d2: 0.000107]  [num0: 13.000000] [num1 51.000000]
[Epoch 480/500] [Batch 500/676] [D loss: 0.002313] [G loss: -0.137531] [d1 loss: 0.111040] [d2 loss: 0.090236]  [sq d1 d2: 0.000433]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 520/676] [D loss: -0.002366] [G loss: -0.132871] [d1 loss: 0.073032] [d2 loss: 0.094046]  [sq d1 d2: 0.000442]  [num0: 18.000000] [num1 46.000000]
[Epoch 480/500] [Batch 540/676] [D loss: -0.002861] [G loss: -0.123599] [d1 loss: 0.137187] [d2 loss: 0.147277]  [sq d1 d2: 0.000102]  [num0: 13.000000] [num1 51.000000]
[Epoch 480/500] [Batch 560/676] [D loss: -0.002337] [G loss: -0.073333] [d1 loss: 0.086098] [d2 loss: 0.121237]  [sq d1 d2: 0.001235]  [num0: 14.000000] [num1 50.000000]
[Epoch 480/500] [Batch 580/676] [D loss: -0.001669] [G loss: -0.053809] [d1 loss: 0.061262] [d2 loss: 0.063214]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 480/500] [Batch 600/676] [D loss: -0.011897] [G loss: -0.026939] [d1 loss: 0.054352] [d2 loss: 0.044730]  [sq d1 d2: 0.000093]  [num0: 13.000000] [num1 51.000000]
[Epoch 480/500] [Batch 620/676] [D loss: -0.005395] [G loss: -0.050672] [d1 loss: 0.156921] [d2 loss: 0.180127]  [sq d1 d2: 0.000539]  [num0: 21.000000] [num1 43.000000]
[Epoch 480/500] [Batch 640/676] [D loss: -0.009010] [G loss: -0.026467] [d1 loss: 0.076937] [d2 loss: 0.052555]  [sq d1 d2: 0.000595]  [num0: 17.000000] [num1 47.000000]
[Epoch 480/500] [Batch 660/676] [D loss: 0.000057] [G loss: -0.022805] [d1 loss: 0.048170] [d2 loss: 0.055731]  [sq d1 d2: 0.000057]  [num0: 9.000000] [num1 55.000000]
[Epoch 481/500] [Batch 0/676] [D loss: 0.001317] [G loss: -0.014352] [d1 loss: 0.029877] [d2 loss: 0.035645]  [sq d1 d2: 0.000033]  [num0: 17.000000] [num1 47.000000]
[Epoch 481/500] [Batch 20/676] [D loss: -0.009403] [G loss: 0.020039] [d1 loss: 0.096944] [d2 loss: 0.090781]  [sq d1 d2: 0.000038]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 40/676] [D loss: -0.015819] [G loss: 0.022261] [d1 loss: 0.045792] [d2 loss: 0.049374]  [sq d1 d2: 0.000013]  [num0: 15.000000] [num1 49.000000]

[Epoch 481/500] [Batch 60/676] [D loss: -0.038140] [G loss: 0.050478] [d1 loss: 0.050708] [d2 loss: 0.045489]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 80/676] [D loss: -0.026546] [G loss: 0.039266] [d1 loss: 0.046710] [d2 loss: 0.086403]  [sq d1 d2: 0.001576]  [num0: 13.000000] [num1 51.000000]
[Epoch 481/500] [Batch 100/676] [D loss: 0.001107] [G loss: 0.023327] [d1 loss: 0.070703] [d2 loss: 0.100030]  [sq d1 d2: 0.000860]  [num0: 22.000000] [num1 42.000000]
[Epoch 481/500] [Batch 120/676] [D loss: 0.016505] [G loss: 0.017194] [d1 loss: 0.052154] [d2 loss: 0.058590]  [sq d1 d2: 0.000041]  [num0: 18.000000] [num1 46.000000]
[Epoch 481/500] [Batch 140/676] [D loss: -0.010256] [G loss: 0.061142] [d1 loss: 0.018747] [d2 loss: 0.019878]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 481/500] [Batch 160/676] [D loss: 0.001758] [G loss: 0.072210] [d1 loss: 0.062948] [d2 loss: 0.079247]  [sq d1 d2: 0.000266]  [num0: 18.000000] [num1 46.000000]
[Epoch 481/500] [Batch 180/676] [D loss: 0.008118] [G loss: 0.059276] [d1 loss: 0.083246] [d2 loss: 0.075423]  [sq d1 d2: 0.000061]  [num0: 15.000000] [num1 49.000000]
[Epoch 481/500] [Batch 200/676] [D loss: 0.000013] [G loss: 0.071494] [d1 loss: 0.108991] [d2 loss: 0.129121]  [sq d1 d2: 0.000405]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 220/676] [D loss: -0.009584] [G loss: 0.076316] [d1 loss: 0.093748] [d2 loss: 0.112086]  [sq d1 d2: 0.000336]  [num0: 13.000000] [num1 51.000000]
[Epoch 481/500] [Batch 240/676] [D loss: -0.006521] [G loss: 0.096374] [d1 loss: 0.038849] [d2 loss: 0.037412]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 481/500] [Batch 260/676] [D loss: -0.010773] [G loss: 0.093040] [d1 loss: 0.034394] [d2 loss: 0.018607]  [sq d1 d2: 0.000249]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 280/676] [D loss: -0.019211] [G loss: 0.089321] [d1 loss: 0.024669] [d2 loss: 0.025321]  [sq d1 d2: 0.000000]  [num0: 19.000000] [num1 45.000000]
[Epoch 481/500] [Batch 300/676] [D loss: 0.001163] [G loss: 0.092783] [d1 loss: 0.038789] [d2 loss: 0.053512]  [sq d1 d2: 0.000217]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 320/676] [D loss: 0.007620] [G loss: 0.087854] [d1 loss: 0.063995] [d2 loss: 0.060460]  [sq d1 d2: 0.000012]  [num0: 20.000000] [num1 44.000000]
[Epoch 481/500] [Batch 340/676] [D loss: -0.000321] [G loss: 0.061476] [d1 loss: 0.089467] [d2 loss: 0.102010]  [sq d1 d2: 0.000157]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 360/676] [D loss: -0.008408] [G loss: -0.017706] [d1 loss: 0.126527] [d2 loss: 0.128314]  [sq d1 d2: 0.000003]  [num0: 12.000000] [num1 52.000000]
[Epoch 481/500] [Batch 380/676] [D loss: -0.029749] [G loss: -0.015549] [d1 loss: 0.136113] [d2 loss: 0.150764]  [sq d1 d2: 0.000215]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 400/676] [D loss: -0.006565] [G loss: -0.043801] [d1 loss: 0.054614] [d2 loss: 0.048933]  [sq d1 d2: 0.000032]  [num0: 19.000000] [num1 45.000000]
[Epoch 481/500] [Batch 420/676] [D loss: 0.020835] [G loss: -0.042692] [d1 loss: 0.122686] [d2 loss: 0.127806]  [sq d1 d2: 0.000026]  [num0: 17.000000] [num1 47.000000]
[Epoch 481/500] [Batch 440/676] [D loss: -0.015839] [G loss: -0.055161] [d1 loss: 0.036319] [d2 loss: 0.036008]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 460/676] [D loss: -0.012621] [G loss: -0.098690] [d1 loss: 0.045334] [d2 loss: 0.070739]  [sq d1 d2: 0.000645]  [num0: 15.000000] [num1 49.000000]
[Epoch 481/500] [Batch 480/676] [D loss: 0.000015] [G loss: -0.112982] [d1 loss: 0.064990] [d2 loss: 0.084622]  [sq d1 d2: 0.000385]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 500/676] [D loss: -0.002875] [G loss: -0.117033] [d1 loss: 0.142758] [d2 loss: 0.152023]  [sq d1 d2: 0.000086]  [num0: 19.000000] [num1 45.000000]
[Epoch 481/500] [Batch 520/676] [D loss: 0.010851] [G loss: -0.080088] [d1 loss: 0.112236] [d2 loss: 0.093722]  [sq d1 d2: 0.000343]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 540/676] [D loss: 0.002970] [G loss: -0.100353] [d1 loss: 0.041516] [d2 loss: 0.046693]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 560/676] [D loss: -0.006273] [G loss: -0.082967] [d1 loss: 0.106727] [d2 loss: 0.090692]  [sq d1 d2: 0.000257]  [num0: 15.000000] [num1 49.000000]
[Epoch 481/500] [Batch 580/676] [D loss: -0.001069] [G loss: -0.048224] [d1 loss: 0.182539] [d2 loss: 0.188956]  [sq d1 d2: 0.000041]  [num0: 15.000000] [num1 49.000000]
[Epoch 481/500] [Batch 600/676] [D loss: -0.005178] [G loss: -0.010057] [d1 loss: 0.042512] [d2 loss: 0.044471]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 481/500] [Batch 620/676] [D loss: -0.001353] [G loss: 0.018383] [d1 loss: 0.031217] [d2 loss: 0.027948]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 481/500] [Batch 640/676] [D loss: -0.014695] [G loss: 0.041963] [d1 loss: 0.137769] [d2 loss: 0.122311]  [sq d1 d2: 0.000239]  [num0: 16.000000] [num1 48.000000]
[Epoch 481/500] [Batch 660/676] [D loss: -0.005780] [G loss: 0.050951] [d1 loss: 0.118158] [d2 loss: 0.102606]  [sq d1 d2: 0.000242]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 0/676] [D loss: 0.018770] [G loss: 0.066845] [d1 loss: 0.052755] [d2 loss: 0.051870]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 20/676] [D loss: -0.001594] [G loss: 0.078188] [d1 loss: 0.059108] [d2 loss: 0.057349]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 482/500] [Batch 40/676] [D loss: -0.027710] [G loss: 0.116980] [d1 loss: 0.072149] [d2 loss: 0.059580]  [sq d1 d2: 0.000158]  [num0: 14.000000] [num1 50.000000]
[Epoch 482/500] [Batch 60/676] [D loss: -0.009162] [G loss: 0.162963] [d1 loss: 0.058911] [d2 loss: 0.064902]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 482/500] [Batch 80/676] [D loss: -0.008739] [G loss: 0.202549] [d1 loss: 0.076409] [d2 loss: 0.055973]  [sq d1 d2: 0.000418]  [num0: 13.000000] [num1 51.000000]
[Epoch 482/500] [Batch 100/676] [D loss: -0.018419] [G loss: 0.209290] [d1 loss: 0.050455] [d2 loss: 0.045090]  [sq d1 d2: 0.000029]  [num0: 13.000000] [num1 51.000000]
[Epoch 482/500] [Batch 120/676] [D loss: -0.008077] [G loss: 0.200979] [d1 loss: 0.086550] [d2 loss: 0.084610]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 140/676] [D loss: 0.005644] [G loss: 0.231639] [d1 loss: 0.110020] [d2 loss: 0.068704]  [sq d1 d2: 0.001707]  [num0: 18.000000] [num1 46.000000]
[Epoch 482/500] [Batch 160/676] [D loss: -0.002471] [G loss: 0.216023] [d1 loss: 0.037655] [d2 loss: 0.037410]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 482/500] [Batch 180/676] [D loss: -0.006266] [G loss: 0.214798] [d1 loss: 0.139302] [d2 loss: 0.123195]  [sq d1 d2: 0.000259]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 200/676] [D loss: 0.000894] [G loss: 0.156661] [d1 loss: 0.018858] [d2 loss: 0.023165]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 220/676] [D loss: -0.007052] [G loss: 0.122365] [d1 loss: 0.090438] [d2 loss: 0.075824]  [sq d1 d2: 0.000214]  [num0: 18.000000] [num1 46.000000]
[Epoch 482/500] [Batch 240/676] [D loss: 0.003785] [G loss: 0.089914] [d1 loss: 0.090802] [d2 loss: 0.091626]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 260/676] [D loss: 0.010802] [G loss: 0.035086] [d1 loss: 0.070434] [d2 loss: 0.076920]  [sq d1 d2: 0.000042]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 280/676] [D loss: -0.004430] [G loss: -0.005689] [d1 loss: 0.111157] [d2 loss: 0.108083]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 300/676] [D loss: -0.002647] [G loss: -0.086846] [d1 loss: 0.056118] [d2 loss: 0.051798]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 320/676] [D loss: -0.000876] [G loss: -0.101914] [d1 loss: 0.011883] [d2 loss: 0.015576]  [sq d1 d2: 0.000014]  [num0: 13.000000] [num1 51.000000]
[Epoch 482/500] [Batch 340/676] [D loss: -0.011928] [G loss: -0.135161] [d1 loss: 0.066757] [d2 loss: 0.086079]  [sq d1 d2: 0.000373]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 360/676] [D loss: -0.003554] [G loss: -0.202037] [d1 loss: 0.035507] [d2 loss: 0.040780]  [sq d1 d2: 0.000028]  [num0: 17.000000] [num1 47.000000]

[Epoch 482/500] [Batch 380/676] [D loss: -0.008869] [G loss: -0.254092] [d1 loss: 0.041500] [d2 loss: 0.054870]  [sq d1 d2: 0.000179]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 400/676] [D loss: -0.005974] [G loss: -0.252992] [d1 loss: 0.084494] [d2 loss: 0.041715]  [sq d1 d2: 0.001830]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 420/676] [D loss: -0.000911] [G loss: -0.273982] [d1 loss: 0.042684] [d2 loss: 0.044001]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 440/676] [D loss: 0.006803] [G loss: -0.263880] [d1 loss: 0.047237] [d2 loss: 0.062957]  [sq d1 d2: 0.000247]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 460/676] [D loss: -0.001869] [G loss: -0.191942] [d1 loss: 0.065418] [d2 loss: 0.052181]  [sq d1 d2: 0.000175]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 480/676] [D loss: -0.006751] [G loss: -0.158072] [d1 loss: 0.017232] [d2 loss: 0.021279]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 482/500] [Batch 500/676] [D loss: -0.005681] [G loss: -0.178831] [d1 loss: 0.053891] [d2 loss: 0.069032]  [sq d1 d2: 0.000229]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 520/676] [D loss: -0.008689] [G loss: -0.185332] [d1 loss: 0.099813] [d2 loss: 0.109693]  [sq d1 d2: 0.000098]  [num0: 17.000000] [num1 47.000000]
[Epoch 482/500] [Batch 540/676] [D loss: 0.008168] [G loss: -0.132722] [d1 loss: 0.063442] [d2 loss: 0.051306]  [sq d1 d2: 0.000147]  [num0: 13.000000] [num1 51.000000]
[Epoch 482/500] [Batch 560/676] [D loss: -0.005124] [G loss: -0.125869] [d1 loss: 0.139478] [d2 loss: 0.121944]  [sq d1 d2: 0.000307]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 580/676] [D loss: -0.002209] [G loss: -0.047018] [d1 loss: 0.013311] [d2 loss: 0.013794]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 600/676] [D loss: -0.012063] [G loss: -0.067766] [d1 loss: 0.073167] [d2 loss: 0.111846]  [sq d1 d2: 0.001496]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 620/676] [D loss: -0.014465] [G loss: -0.072389] [d1 loss: 0.084297] [d2 loss: 0.095144]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 482/500] [Batch 640/676] [D loss: -0.005088] [G loss: -0.036467] [d1 loss: 0.080859] [d2 loss: 0.083322]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 482/500] [Batch 660/676] [D loss: -0.011071] [G loss: -0.068939] [d1 loss: 0.038029] [d2 loss: 0.026650]  [sq d1 d2: 0.000129]  [num0: 16.000000] [num1 48.000000]
[Epoch 483/500] [Batch 0/676] [D loss: 0.008227] [G loss: -0.022374] [d1 loss: 0.086701] [d2 loss: 0.066310]  [sq d1 d2: 0.000416]  [num0: 13.000000] [num1 51.000000]
[Epoch 483/500] [Batch 20/676] [D loss: -0.011343] [G loss: 0.001556] [d1 loss: 0.117540] [d2 loss: 0.106294]  [sq d1 d2: 0.000126]  [num0: 12.000000] [num1 52.000000]
[Epoch 483/500] [Batch 40/676] [D loss: -0.002811] [G loss: 0.017379] [d1 loss: 0.025559] [d2 loss: 0.027112]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 483/500] [Batch 60/676] [D loss: -0.006119] [G loss: 0.009211] [d1 loss: 0.039438] [d2 loss: 0.030740]  [sq d1 d2: 0.000076]  [num0: 13.000000] [num1 51.000000]
[Epoch 483/500] [Batch 80/676] [D loss: -0.012857] [G loss: 0.000369] [d1 loss: 0.054333] [d2 loss: 0.059713]  [sq d1 d2: 0.000029]  [num0: 17.000000] [num1 47.000000]
[Epoch 483/500] [Batch 100/676] [D loss: 0.006127] [G loss: -0.007213] [d1 loss: 0.206772] [d2 loss: 0.191593]  [sq d1 d2: 0.000230]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 120/676] [D loss: -0.017810] [G loss: -0.074986] [d1 loss: 0.043841] [d2 loss: 0.034881]  [sq d1 d2: 0.000080]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 140/676] [D loss: 0.004455] [G loss: -0.047547] [d1 loss: 0.042685] [d2 loss: 0.033339]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 160/676] [D loss: -0.005436] [G loss: -0.059668] [d1 loss: 0.099365] [d2 loss: 0.092742]  [sq d1 d2: 0.000044]  [num0: 14.000000] [num1 50.000000]
[Epoch 483/500] [Batch 180/676] [D loss: -0.004801] [G loss: -0.068356] [d1 loss: 0.116654] [d2 loss: 0.088475]  [sq d1 d2: 0.000794]  [num0: 17.000000] [num1 47.000000]
[Epoch 483/500] [Batch 200/676] [D loss: -0.000519] [G loss: -0.058077] [d1 loss: 0.080703] [d2 loss: 0.074274]  [sq d1 d2: 0.000041]  [num0: 19.000000] [num1 45.000000]
[Epoch 483/500] [Batch 220/676] [D loss: 0.000549] [G loss: -0.057647] [d1 loss: 0.027952] [d2 loss: 0.027506]  [sq d1 d2: 0.000000]  [num0: 12.000000] [num1 52.000000]
[Epoch 483/500] [Batch 240/676] [D loss: -0.004970] [G loss: -0.049002] [d1 loss: 0.047627] [d2 loss: 0.059711]  [sq d1 d2: 0.000146]  [num0: 18.000000] [num1 46.000000]
[Epoch 483/500] [Batch 260/676] [D loss: -0.009400] [G loss: -0.033122] [d1 loss: 0.023929] [d2 loss: 0.020648]  [sq d1 d2: 0.000011]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 280/676] [D loss: -0.006388] [G loss: -0.048585] [d1 loss: 0.038073] [d2 loss: 0.024475]  [sq d1 d2: 0.000185]  [num0: 11.000000] [num1 53.000000]
[Epoch 483/500] [Batch 300/676] [D loss: -0.005161] [G loss: -0.015733] [d1 loss: 0.020199] [d2 loss: 0.016427]  [sq d1 d2: 0.000014]  [num0: 14.000000] [num1 50.000000]
[Epoch 483/500] [Batch 320/676] [D loss: -0.004261] [G loss: 0.005117] [d1 loss: 0.055201] [d2 loss: 0.076225]  [sq d1 d2: 0.000442]  [num0: 13.000000] [num1 51.000000]
[Epoch 483/500] [Batch 340/676] [D loss: -0.030818] [G loss: 0.012536] [d1 loss: 0.028582] [d2 loss: 0.028057]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 360/676] [D loss: -0.010734] [G loss: 0.000695] [d1 loss: 0.117333] [d2 loss: 0.101406]  [sq d1 d2: 0.000254]  [num0: 18.000000] [num1 46.000000]
[Epoch 483/500] [Batch 380/676] [D loss: 0.005389] [G loss: 0.015557] [d1 loss: 0.039541] [d2 loss: 0.039953]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 483/500] [Batch 400/676] [D loss: 0.002468] [G loss: 0.056385] [d1 loss: 0.019260] [d2 loss: 0.019076]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 483/500] [Batch 420/676] [D loss: -0.010115] [G loss: 0.097832] [d1 loss: 0.087759] [d2 loss: 0.065455]  [sq d1 d2: 0.000497]  [num0: 16.000000] [num1 48.000000]
[Epoch 483/500] [Batch 440/676] [D loss: 0.014886] [G loss: 0.121338] [d1 loss: 0.071409] [d2 loss: 0.072330]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 460/676] [D loss: 0.000175] [G loss: 0.138857] [d1 loss: 0.006025] [d2 loss: 0.008685]  [sq d1 d2: 0.000007]  [num0: 12.000000] [num1 52.000000]
[Epoch 483/500] [Batch 480/676] [D loss: 0.000531] [G loss: 0.147479] [d1 loss: 0.070854] [d2 loss: 0.057620]  [sq d1 d2: 0.000175]  [num0: 18.000000] [num1 46.000000]
[Epoch 483/500] [Batch 500/676] [D loss: -0.005006] [G loss: 0.139539] [d1 loss: 0.071414] [d2 loss: 0.064403]  [sq d1 d2: 0.000049]  [num0: 16.000000] [num1 48.000000]
[Epoch 483/500] [Batch 520/676] [D loss: -0.003903] [G loss: 0.163142] [d1 loss: 0.043520] [d2 loss: 0.045831]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 540/676] [D loss: -0.018819] [G loss: 0.192529] [d1 loss: 0.051069] [d2 loss: 0.048168]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 560/676] [D loss: -0.014192] [G loss: 0.175149] [d1 loss: 0.020558] [d2 loss: 0.023978]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 580/676] [D loss: -0.022343] [G loss: 0.207205] [d1 loss: 0.066112] [d2 loss: 0.069489]  [sq d1 d2: 0.000011]  [num0: 13.000000] [num1 51.000000]
[Epoch 483/500] [Batch 600/676] [D loss: -0.007101] [G loss: 0.190790] [d1 loss: 0.065063] [d2 loss: 0.056365]  [sq d1 d2: 0.000076]  [num0: 16.000000] [num1 48.000000]
[Epoch 483/500] [Batch 620/676] [D loss: 0.005808] [G loss: 0.153867] [d1 loss: 0.029368] [d2 loss: 0.049627]  [sq d1 d2: 0.000410]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 640/676] [D loss: -0.010908] [G loss: 0.143287] [d1 loss: 0.065233] [d2 loss: 0.053739]  [sq d1 d2: 0.000132]  [num0: 15.000000] [num1 49.000000]
[Epoch 483/500] [Batch 660/676] [D loss: 0.008536] [G loss: 0.094031] [d1 loss: 0.045952] [d2 loss: 0.047658]  [sq d1 d2: 0.000003]  [num0: 16.000000] [num1 48.000000]

[Epoch 484/500] [Batch 0/676] [D loss: -0.011071] [G loss: 0.103006] [d1 loss: 0.115384] [d2 loss: 0.119857]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 484/500] [Batch 20/676] [D loss: 0.000705] [G loss: 0.064993] [d1 loss: 0.070834] [d2 loss: 0.071600]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 484/500] [Batch 40/676] [D loss: -0.008990] [G loss: 0.010143] [d1 loss: 0.042582] [d2 loss: 0.044811]  [sq d1 d2: 0.000005]  [num0: 13.000000] [num1 51.000000]
[Epoch 484/500] [Batch 60/676] [D loss: -0.003167] [G loss: -0.027353] [d1 loss: 0.130334] [d2 loss: 0.131773]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 80/676] [D loss: -0.008413] [G loss: -0.017632] [d1 loss: 0.093959] [d2 loss: 0.068857]  [sq d1 d2: 0.000630]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 100/676] [D loss: -0.015349] [G loss: -0.032455] [d1 loss: 0.066809] [d2 loss: 0.075588]  [sq d1 d2: 0.000077]  [num0: 15.000000] [num1 49.000000]
[Epoch 484/500] [Batch 120/676] [D loss: -0.014249] [G loss: -0.042398] [d1 loss: 0.033219] [d2 loss: 0.037240]  [sq d1 d2: 0.000016]  [num0: 12.000000] [num1 52.000000]
[Epoch 484/500] [Batch 140/676] [D loss: -0.007524] [G loss: -0.062597] [d1 loss: 0.033032] [d2 loss: 0.029882]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 484/500] [Batch 160/676] [D loss: -0.020277] [G loss: -0.145723] [d1 loss: 0.124060] [d2 loss: 0.104849]  [sq d1 d2: 0.000369]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 180/676] [D loss: -0.013758] [G loss: -0.184862] [d1 loss: 0.093758] [d2 loss: 0.091136]  [sq d1 d2: 0.000007]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 200/676] [D loss: -0.008713] [G loss: -0.208751] [d1 loss: 0.136410] [d2 loss: 0.118160]  [sq d1 d2: 0.000333]  [num0: 14.000000] [num1 50.000000]
[Epoch 484/500] [Batch 220/676] [D loss: -0.021709] [G loss: -0.208274] [d1 loss: 0.038524] [d2 loss: 0.045843]  [sq d1 d2: 0.000054]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 240/676] [D loss: -0.016186] [G loss: -0.222934] [d1 loss: 0.097180] [d2 loss: 0.117043]  [sq d1 d2: 0.000395]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 260/676] [D loss: -0.009920] [G loss: -0.218193] [d1 loss: 0.010046] [d2 loss: 0.008038]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 280/676] [D loss: 0.007259] [G loss: -0.129247] [d1 loss: 0.061709] [d2 loss: 0.072280]  [sq d1 d2: 0.000112]  [num0: 15.000000] [num1 49.000000]
[Epoch 484/500] [Batch 300/676] [D loss: 0.007767] [G loss: -0.133223] [d1 loss: 0.029563] [d2 loss: 0.041046]  [sq d1 d2: 0.000132]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 320/676] [D loss: 0.001289] [G loss: -0.086562] [d1 loss: 0.066987] [d2 loss: 0.074469]  [sq d1 d2: 0.000056]  [num0: 12.000000] [num1 52.000000]
[Epoch 484/500] [Batch 340/676] [D loss: 0.005013] [G loss: -0.062173] [d1 loss: 0.114027] [d2 loss: 0.064417]  [sq d1 d2: 0.002461]  [num0: 14.000000] [num1 50.000000]
[Epoch 484/500] [Batch 360/676] [D loss: -0.001002] [G loss: -0.023547] [d1 loss: 0.089562] [d2 loss: 0.103957]  [sq d1 d2: 0.000207]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 380/676] [D loss: -0.001990] [G loss: 0.016936] [d1 loss: 0.061453] [d2 loss: 0.054655]  [sq d1 d2: 0.000046]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 400/676] [D loss: -0.000078] [G loss: 0.004483] [d1 loss: 0.049717] [d2 loss: 0.046243]  [sq d1 d2: 0.000012]  [num0: 15.000000] [num1 49.000000]
[Epoch 484/500] [Batch 420/676] [D loss: -0.010292] [G loss: 0.034984] [d1 loss: 0.072946] [d2 loss: 0.066129]  [sq d1 d2: 0.000046]  [num0: 14.000000] [num1 50.000000]
[Epoch 484/500] [Batch 440/676] [D loss: -0.022205] [G loss: 0.083471] [d1 loss: 0.040546] [d2 loss: 0.039320]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 484/500] [Batch 460/676] [D loss: -0.015326] [G loss: 0.095449] [d1 loss: 0.058681] [d2 loss: 0.063321]  [sq d1 d2: 0.000022]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 480/676] [D loss: -0.025916] [G loss: 0.112429] [d1 loss: 0.049851] [d2 loss: 0.037143]  [sq d1 d2: 0.000161]  [num0: 16.000000] [num1 48.000000]
[Epoch 484/500] [Batch 500/676] [D loss: -0.014843] [G loss: 0.127950] [d1 loss: 0.096243] [d2 loss: 0.076778]  [sq d1 d2: 0.000379]  [num0: 15.000000] [num1 49.000000]
[Epoch 484/500] [Batch 520/676] [D loss: -0.012424] [G loss: 0.084334] [d1 loss: 0.037518] [d2 loss: 0.042839]  [sq d1 d2: 0.000028]  [num0: 21.000000] [num1 43.000000]
[Epoch 484/500] [Batch 540/676] [D loss: -0.011948] [G loss: 0.042787] [d1 loss: 0.101107] [d2 loss: 0.089730]  [sq d1 d2: 0.000129]  [num0: 17.000000] [num1 47.000000]
[Epoch 484/500] [Batch 560/676] [D loss: -0.018611] [G loss: 0.081271] [d1 loss: 0.037246] [d2 loss: 0.041874]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 484/500] [Batch 580/676] [D loss: -0.018280] [G loss: 0.100685] [d1 loss: 0.043755] [d2 loss: 0.040362]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 484/500] [Batch 600/676] [D loss: -0.008365] [G loss: 0.068426] [d1 loss: 0.130554] [d2 loss: 0.130860]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 620/676] [D loss: -0.004651] [G loss: 0.077642] [d1 loss: 0.122025] [d2 loss: 0.106480]  [sq d1 d2: 0.000242]  [num0: 20.000000] [num1 44.000000]
[Epoch 484/500] [Batch 640/676] [D loss: -0.009807] [G loss: 0.071654] [d1 loss: 0.058895] [d2 loss: 0.053980]  [sq d1 d2: 0.000024]  [num0: 18.000000] [num1 46.000000]
[Epoch 484/500] [Batch 660/676] [D loss: -0.019982] [G loss: 0.096663] [d1 loss: 0.041425] [d2 loss: 0.038498]  [sq d1 d2: 0.000009]  [num0: 11.000000] [num1 53.000000]
[Epoch 485/500] [Batch 0/676] [D loss: -0.010278] [G loss: 0.101488] [d1 loss: 0.133235] [d2 loss: 0.132434]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 485/500] [Batch 20/676] [D loss: -0.004880] [G loss: 0.068541] [d1 loss: 0.041942] [d2 loss: 0.037580]  [sq d1 d2: 0.000019]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 40/676] [D loss: -0.013703] [G loss: 0.058196] [d1 loss: 0.106387] [d2 loss: 0.135935]  [sq d1 d2: 0.000873]  [num0: 12.000000] [num1 52.000000]
[Epoch 485/500] [Batch 60/676] [D loss: 0.006803] [G loss: 0.068898] [d1 loss: 0.025856] [d2 loss: 0.035035]  [sq d1 d2: 0.000084]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 80/676] [D loss: -0.006500] [G loss: 0.075719] [d1 loss: 0.023693] [d2 loss: 0.027795]  [sq d1 d2: 0.000017]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 100/676] [D loss: -0.011997] [G loss: 0.058870] [d1 loss: 0.030099] [d2 loss: 0.030854]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 485/500] [Batch 120/676] [D loss: -0.001898] [G loss: 0.036098] [d1 loss: 0.046282] [d2 loss: 0.068673]  [sq d1 d2: 0.000501]  [num0: 17.000000] [num1 47.000000]
[Epoch 485/500] [Batch 140/676] [D loss: 0.006025] [G loss: -0.021931] [d1 loss: 0.035465] [d2 loss: 0.036609]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 485/500] [Batch 160/676] [D loss: 0.011706] [G loss: -0.010405] [d1 loss: 0.037595] [d2 loss: 0.037591]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 180/676] [D loss: -0.008280] [G loss: -0.065741] [d1 loss: 0.043337] [d2 loss: 0.036799]  [sq d1 d2: 0.000043]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 200/676] [D loss: -0.019029] [G loss: -0.020051] [d1 loss: 0.072072] [d2 loss: 0.086192]  [sq d1 d2: 0.000199]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 220/676] [D loss: -0.011679] [G loss: -0.010166] [d1 loss: 0.082101] [d2 loss: 0.102798]  [sq d1 d2: 0.000428]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 240/676] [D loss: 0.001218] [G loss: -0.027388] [d1 loss: 0.118795] [d2 loss: 0.146796]  [sq d1 d2: 0.000784]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 260/676] [D loss: -0.006527] [G loss: 0.033654] [d1 loss: 0.079767] [d2 loss: 0.083642]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 280/676] [D loss: -0.013369] [G loss: 0.027373] [d1 loss: 0.013613] [d2 loss: 0.013074]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 485/500] [Batch 300/676] [D loss: -0.011513] [G loss: 0.075849] [d1 loss: 0.028080] [d2 loss: 0.041966]  [sq d1 d2: 0.000193]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 320/676] [D loss: -0.014592] [G loss: 0.044132] [d1 loss: 0.046486] [d2 loss: 0.053641]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 485/500] [Batch 340/676] [D loss: -0.004193] [G loss: 0.057208] [d1 loss: 0.033742] [d2 loss: 0.030208]  [sq d1 d2: 0.000012]  [num0: 19.000000] [num1 45.000000]

[Epoch 485/500] [Batch 360/676] [D loss: -0.010276] [G loss: 0.100999] [d1 loss: 0.022336] [d2 loss: 0.032802]  [sq d1 d2: 0.000110]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 380/676] [D loss: -0.004820] [G loss: 0.072910] [d1 loss: 0.066596] [d2 loss: 0.073471]  [sq d1 d2: 0.000047]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 400/676] [D loss: -0.023235] [G loss: 0.110502] [d1 loss: 0.054649] [d2 loss: 0.048826]  [sq d1 d2: 0.000034]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 420/676] [D loss: -0.000901] [G loss: 0.085341] [d1 loss: 0.141066] [d2 loss: 0.117234]  [sq d1 d2: 0.000568]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 440/676] [D loss: -0.014419] [G loss: 0.124019] [d1 loss: 0.026209] [d2 loss: 0.031563]  [sq d1 d2: 0.000029]  [num0: 15.000000] [num1 49.000000]
[Epoch 485/500] [Batch 460/676] [D loss: 0.004042] [G loss: 0.125947] [d1 loss: 0.076366] [d2 loss: 0.076926]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 480/676] [D loss: 0.005752] [G loss: 0.018631] [d1 loss: 0.147294] [d2 loss: 0.111880]  [sq d1 d2: 0.001254]  [num0: 18.000000] [num1 46.000000]
[Epoch 485/500] [Batch 500/676] [D loss: 0.000583] [G loss: 0.031305] [d1 loss: 0.071838] [d2 loss: 0.080189]  [sq d1 d2: 0.000070]  [num0: 13.000000] [num1 51.000000]
[Epoch 485/500] [Batch 520/676] [D loss: -0.035996] [G loss: 0.021032] [d1 loss: 0.028551] [d2 loss: 0.029600]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 540/676] [D loss: -0.007480] [G loss: -0.001112] [d1 loss: 0.061806] [d2 loss: 0.093878]  [sq d1 d2: 0.001029]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 560/676] [D loss: -0.014589] [G loss: -0.039085] [d1 loss: 0.079177] [d2 loss: 0.110065]  [sq d1 d2: 0.000954]  [num0: 19.000000] [num1 45.000000]
[Epoch 485/500] [Batch 580/676] [D loss: -0.000434] [G loss: -0.088708] [d1 loss: 0.042518] [d2 loss: 0.025292]  [sq d1 d2: 0.000297]  [num0: 17.000000] [num1 47.000000]
[Epoch 485/500] [Batch 600/676] [D loss: -0.008902] [G loss: -0.071166] [d1 loss: 0.106686] [d2 loss: 0.107830]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 485/500] [Batch 620/676] [D loss: -0.011972] [G loss: -0.054569] [d1 loss: 0.032064] [d2 loss: 0.029680]  [sq d1 d2: 0.000006]  [num0: 16.000000] [num1 48.000000]
[Epoch 485/500] [Batch 640/676] [D loss: -0.016295] [G loss: -0.030093] [d1 loss: 0.074038] [d2 loss: 0.057870]  [sq d1 d2: 0.000261]  [num0: 19.000000] [num1 45.000000]
[Epoch 485/500] [Batch 660/676] [D loss: -0.014417] [G loss: -0.058002] [d1 loss: 0.035067] [d2 loss: 0.029398]  [sq d1 d2: 0.000032]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 0/676] [D loss: -0.027697] [G loss: -0.045325] [d1 loss: 0.057748] [d2 loss: 0.047015]  [sq d1 d2: 0.000115]  [num0: 16.000000] [num1 48.000000]
[Epoch 486/500] [Batch 20/676] [D loss: -0.016704] [G loss: -0.023733] [d1 loss: 0.041416] [d2 loss: 0.055625]  [sq d1 d2: 0.000202]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 40/676] [D loss: 0.003833] [G loss: -0.019793] [d1 loss: 0.020873] [d2 loss: 0.028174]  [sq d1 d2: 0.000053]  [num0: 14.000000] [num1 50.000000]
[Epoch 486/500] [Batch 60/676] [D loss: -0.029368] [G loss: -0.011915] [d1 loss: 0.053504] [d2 loss: 0.030243]  [sq d1 d2: 0.000541]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 80/676] [D loss: -0.031078] [G loss: -0.015532] [d1 loss: 0.090057] [d2 loss: 0.123568]  [sq d1 d2: 0.001123]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 100/676] [D loss: 0.001639] [G loss: -0.010166] [d1 loss: 0.016413] [d2 loss: 0.026605]  [sq d1 d2: 0.000104]  [num0: 13.000000] [num1 51.000000]
[Epoch 486/500] [Batch 120/676] [D loss: -0.013944] [G loss: 0.053240] [d1 loss: 0.061410] [d2 loss: 0.052660]  [sq d1 d2: 0.000077]  [num0: 14.000000] [num1 50.000000]
[Epoch 486/500] [Batch 140/676] [D loss: 0.021795] [G loss: 0.089586] [d1 loss: 0.037002] [d2 loss: 0.037646]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 160/676] [D loss: -0.007074] [G loss: 0.098421] [d1 loss: 0.020106] [d2 loss: 0.015759]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 180/676] [D loss: -0.010969] [G loss: 0.101071] [d1 loss: 0.028401] [d2 loss: 0.042309]  [sq d1 d2: 0.000193]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 200/676] [D loss: -0.016771] [G loss: 0.083793] [d1 loss: 0.047963] [d2 loss: 0.063167]  [sq d1 d2: 0.000231]  [num0: 16.000000] [num1 48.000000]
[Epoch 486/500] [Batch 220/676] [D loss: -0.013345] [G loss: 0.073069] [d1 loss: 0.068144] [d2 loss: 0.062611]  [sq d1 d2: 0.000031]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 240/676] [D loss: -0.019536] [G loss: 0.063471] [d1 loss: 0.077313] [d2 loss: 0.069387]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 260/676] [D loss: -0.022836] [G loss: -0.002216] [d1 loss: 0.037764] [d2 loss: 0.032471]  [sq d1 d2: 0.000028]  [num0: 13.000000] [num1 51.000000]
[Epoch 486/500] [Batch 280/676] [D loss: -0.015018] [G loss: 0.006489] [d1 loss: 0.055480] [d2 loss: 0.056419]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 486/500] [Batch 300/676] [D loss: -0.012095] [G loss: 0.015307] [d1 loss: 0.042492] [d2 loss: 0.040027]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 320/676] [D loss: -0.002378] [G loss: -0.019845] [d1 loss: 0.063655] [d2 loss: 0.042084]  [sq d1 d2: 0.000465]  [num0: 12.000000] [num1 52.000000]
[Epoch 486/500] [Batch 340/676] [D loss: -0.029141] [G loss: 0.024580] [d1 loss: 0.102938] [d2 loss: 0.115535]  [sq d1 d2: 0.000159]  [num0: 17.000000] [num1 47.000000]
[Epoch 486/500] [Batch 360/676] [D loss: -0.003501] [G loss: -0.047936] [d1 loss: 0.082715] [d2 loss: 0.106428]  [sq d1 d2: 0.000562]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 380/676] [D loss: -0.026394] [G loss: -0.103779] [d1 loss: 0.022204] [d2 loss: 0.025100]  [sq d1 d2: 0.000008]  [num0: 19.000000] [num1 45.000000]
[Epoch 486/500] [Batch 400/676] [D loss: -0.020072] [G loss: -0.207140] [d1 loss: 0.016569] [d2 loss: 0.020475]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 486/500] [Batch 420/676] [D loss: -0.011880] [G loss: -0.262050] [d1 loss: 0.097180] [d2 loss: 0.095373]  [sq d1 d2: 0.000003]  [num0: 13.000000] [num1 51.000000]
[Epoch 486/500] [Batch 440/676] [D loss: -0.002846] [G loss: -0.280453] [d1 loss: 0.087744] [d2 loss: 0.081900]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 460/676] [D loss: -0.037658] [G loss: -0.280206] [d1 loss: 0.036674] [d2 loss: 0.037565]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 480/676] [D loss: -0.026736] [G loss: -0.280222] [d1 loss: 0.037733] [d2 loss: 0.035045]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 486/500] [Batch 500/676] [D loss: -0.014059] [G loss: -0.361472] [d1 loss: 0.024663] [d2 loss: 0.023273]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 486/500] [Batch 520/676] [D loss: -0.023981] [G loss: -0.309839] [d1 loss: 0.096235] [d2 loss: 0.092648]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 486/500] [Batch 540/676] [D loss: -0.018575] [G loss: -0.370839] [d1 loss: 0.028219] [d2 loss: 0.030590]  [sq d1 d2: 0.000006]  [num0: 17.000000] [num1 47.000000]
[Epoch 486/500] [Batch 560/676] [D loss: -0.008262] [G loss: -0.312906] [d1 loss: 0.229261] [d2 loss: 0.177425]  [sq d1 d2: 0.002687]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 580/676] [D loss: 0.016181] [G loss: -0.224317] [d1 loss: 0.087876] [d2 loss: 0.069690]  [sq d1 d2: 0.000331]  [num0: 18.000000] [num1 46.000000]
[Epoch 486/500] [Batch 600/676] [D loss: -0.007049] [G loss: -0.205933] [d1 loss: 0.033802] [d2 loss: 0.034262]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 620/676] [D loss: 0.000345] [G loss: -0.155360] [d1 loss: 0.020903] [d2 loss: 0.032143]  [sq d1 d2: 0.000126]  [num0: 14.000000] [num1 50.000000]
[Epoch 486/500] [Batch 640/676] [D loss: 0.009796] [G loss: -0.082660] [d1 loss: 0.029366] [d2 loss: 0.044903]  [sq d1 d2: 0.000241]  [num0: 15.000000] [num1 49.000000]
[Epoch 486/500] [Batch 660/676] [D loss: 0.002956] [G loss: -0.052146] [d1 loss: 0.048145] [d2 loss: 0.063106]  [sq d1 d2: 0.000224]  [num0: 12.000000] [num1 52.000000]
[Epoch 487/500] [Batch 0/676] [D loss: -0.007334] [G loss: 0.020881] [d1 loss: 0.033760] [d2 loss: 0.028260]  [sq d1 d2: 0.000030]  [num0: 11.000000] [num1 53.000000]
[Epoch 487/500] [Batch 20/676] [D loss: 0.001627] [G loss: 0.056849] [d1 loss: 0.152962] [d2 loss: 0.139763]  [sq d1 d2: 0.000174]  [num0: 15.000000] [num1 49.000000]
[Epoch 487/500] [Batch 40/676] [D loss: -0.014751] [G loss: 0.063266] [d1 loss: 0.079811] [d2 loss: 0.071510]  [sq d1 d2: 0.000069]  [num0: 16.000000] [num1 48.000000]

[Epoch 487/500] [Batch 60/676] [D loss: -0.007226] [G loss: 0.040538] [d1 loss: 0.077984] [d2 loss: 0.118669]  [sq d1 d2: 0.001655]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 80/676] [D loss: -0.009156] [G loss: 0.053111] [d1 loss: 0.045423] [d2 loss: 0.062414]  [sq d1 d2: 0.000289]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 100/676] [D loss: 0.009963] [G loss: 0.078483] [d1 loss: 0.053378] [d2 loss: 0.051716]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 120/676] [D loss: 0.026951] [G loss: 0.080951] [d1 loss: 0.126934] [d2 loss: 0.087840]  [sq d1 d2: 0.001528]  [num0: 16.000000] [num1 48.000000]
[Epoch 487/500] [Batch 140/676] [D loss: 0.021001] [G loss: 0.086212] [d1 loss: 0.081026] [d2 loss: 0.083573]  [sq d1 d2: 0.000006]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 160/676] [D loss: -0.001220] [G loss: 0.068280] [d1 loss: 0.122531] [d2 loss: 0.065417]  [sq d1 d2: 0.003262]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 180/676] [D loss: 0.003110] [G loss: 0.059560] [d1 loss: 0.071893] [d2 loss: 0.083838]  [sq d1 d2: 0.000143]  [num0: 10.000000] [num1 54.000000]
[Epoch 487/500] [Batch 200/676] [D loss: -0.011512] [G loss: 0.050911] [d1 loss: 0.099056] [d2 loss: 0.096979]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 220/676] [D loss: -0.008091] [G loss: 0.106630] [d1 loss: 0.023290] [d2 loss: 0.025328]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 487/500] [Batch 240/676] [D loss: -0.018974] [G loss: 0.099465] [d1 loss: 0.069656] [d2 loss: 0.083668]  [sq d1 d2: 0.000196]  [num0: 12.000000] [num1 52.000000]
[Epoch 487/500] [Batch 260/676] [D loss: -0.041209] [G loss: 0.120343] [d1 loss: 0.118357] [d2 loss: 0.143684]  [sq d1 d2: 0.000641]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 280/676] [D loss: -0.025842] [G loss: 0.084095] [d1 loss: 0.052780] [d2 loss: 0.050581]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 300/676] [D loss: -0.008737] [G loss: 0.094693] [d1 loss: 0.108110] [d2 loss: 0.081524]  [sq d1 d2: 0.000707]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 320/676] [D loss: -0.030427] [G loss: 0.054575] [d1 loss: 0.079267] [d2 loss: 0.082407]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 487/500] [Batch 340/676] [D loss: -0.024742] [G loss: 0.000803] [d1 loss: 0.029133] [d2 loss: 0.033458]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]
[Epoch 487/500] [Batch 360/676] [D loss: -0.003975] [G loss: -0.005849] [d1 loss: 0.036948] [d2 loss: 0.035392]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 380/676] [D loss: 0.009522] [G loss: -0.025835] [d1 loss: 0.040733] [d2 loss: 0.028696]  [sq d1 d2: 0.000145]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 400/676] [D loss: -0.008084] [G loss: -0.024313] [d1 loss: 0.067790] [d2 loss: 0.072326]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 420/676] [D loss: -0.002909] [G loss: -0.058974] [d1 loss: 0.079263] [d2 loss: 0.055026]  [sq d1 d2: 0.000587]  [num0: 13.000000] [num1 51.000000]
[Epoch 487/500] [Batch 440/676] [D loss: 0.006106] [G loss: -0.093002] [d1 loss: 0.029471] [d2 loss: 0.031445]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 460/676] [D loss: -0.008145] [G loss: -0.116628] [d1 loss: 0.049645] [d2 loss: 0.056740]  [sq d1 d2: 0.000050]  [num0: 19.000000] [num1 45.000000]
[Epoch 487/500] [Batch 480/676] [D loss: -0.019364] [G loss: -0.138687] [d1 loss: 0.024058] [d2 loss: 0.021606]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 500/676] [D loss: -0.064736] [G loss: -0.144775] [d1 loss: 0.029469] [d2 loss: 0.028669]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 487/500] [Batch 520/676] [D loss: -0.012758] [G loss: -0.182567] [d1 loss: 0.035781] [d2 loss: 0.036518]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 540/676] [D loss: -0.019724] [G loss: -0.187207] [d1 loss: 0.086911] [d2 loss: 0.117044]  [sq d1 d2: 0.000908]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 560/676] [D loss: -0.002398] [G loss: -0.199111] [d1 loss: 0.054039] [d2 loss: 0.041115]  [sq d1 d2: 0.000167]  [num0: 13.000000] [num1 51.000000]
[Epoch 487/500] [Batch 580/676] [D loss: -0.008833] [G loss: -0.194620] [d1 loss: 0.049627] [d2 loss: 0.072275]  [sq d1 d2: 0.000513]  [num0: 18.000000] [num1 46.000000]
[Epoch 487/500] [Batch 600/676] [D loss: 0.042994] [G loss: -0.181690] [d1 loss: 0.040778] [d2 loss: 0.038429]  [sq d1 d2: 0.000006]  [num0: 11.000000] [num1 53.000000]
[Epoch 487/500] [Batch 620/676] [D loss: 0.012455] [G loss: -0.224962] [d1 loss: 0.078192] [d2 loss: 0.079530]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 487/500] [Batch 640/676] [D loss: -0.004680] [G loss: -0.219668] [d1 loss: 0.093288] [d2 loss: 0.083551]  [sq d1 d2: 0.000095]  [num0: 20.000000] [num1 44.000000]
[Epoch 487/500] [Batch 660/676] [D loss: 0.005168] [G loss: -0.150979] [d1 loss: 0.067119] [d2 loss: 0.090075]  [sq d1 d2: 0.000527]  [num0: 16.000000] [num1 48.000000]
[Epoch 488/500] [Batch 0/676] [D loss: -0.001975] [G loss: -0.117569] [d1 loss: 0.036493] [d2 loss: 0.028270]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 20/676] [D loss: 0.000992] [G loss: -0.083725] [d1 loss: 0.047485] [d2 loss: 0.068259]  [sq d1 d2: 0.000432]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 40/676] [D loss: -0.010084] [G loss: -0.058010] [d1 loss: 0.039098] [d2 loss: 0.047001]  [sq d1 d2: 0.000062]  [num0: 14.000000] [num1 50.000000]
[Epoch 488/500] [Batch 60/676] [D loss: -0.022120] [G loss: -0.035621] [d1 loss: 0.194186] [d2 loss: 0.188686]  [sq d1 d2: 0.000030]  [num0: 16.000000] [num1 48.000000]
[Epoch 488/500] [Batch 80/676] [D loss: -0.027609] [G loss: -0.018821] [d1 loss: 0.074580] [d2 loss: 0.070681]  [sq d1 d2: 0.000015]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 100/676] [D loss: -0.016639] [G loss: 0.021685] [d1 loss: 0.012369] [d2 loss: 0.017703]  [sq d1 d2: 0.000028]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 120/676] [D loss: -0.029914] [G loss: 0.030137] [d1 loss: 0.058818] [d2 loss: 0.049314]  [sq d1 d2: 0.000090]  [num0: 16.000000] [num1 48.000000]
[Epoch 488/500] [Batch 140/676] [D loss: -0.019234] [G loss: 0.007161] [d1 loss: 0.052572] [d2 loss: 0.059579]  [sq d1 d2: 0.000049]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 160/676] [D loss: -0.000127] [G loss: -0.040380] [d1 loss: 0.059849] [d2 loss: 0.050233]  [sq d1 d2: 0.000092]  [num0: 16.000000] [num1 48.000000]
[Epoch 488/500] [Batch 180/676] [D loss: -0.011275] [G loss: -0.084214] [d1 loss: 0.104704] [d2 loss: 0.105643]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 488/500] [Batch 200/676] [D loss: 0.016471] [G loss: -0.148288] [d1 loss: 0.088648] [d2 loss: 0.086007]  [sq d1 d2: 0.000007]  [num0: 14.000000] [num1 50.000000]
[Epoch 488/500] [Batch 220/676] [D loss: -0.013462] [G loss: -0.156391] [d1 loss: 0.057416] [d2 loss: 0.049164]  [sq d1 d2: 0.000068]  [num0: 15.000000] [num1 49.000000]
[Epoch 488/500] [Batch 240/676] [D loss: 0.018846] [G loss: -0.145570] [d1 loss: 0.027978] [d2 loss: 0.028145]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 488/500] [Batch 260/676] [D loss: -0.000819] [G loss: -0.104175] [d1 loss: 0.054804] [d2 loss: 0.068192]  [sq d1 d2: 0.000179]  [num0: 14.000000] [num1 50.000000]
[Epoch 488/500] [Batch 280/676] [D loss: -0.000927] [G loss: -0.058782] [d1 loss: 0.027394] [d2 loss: 0.027191]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 488/500] [Batch 300/676] [D loss: -0.000676] [G loss: -0.038053] [d1 loss: 0.059775] [d2 loss: 0.048799]  [sq d1 d2: 0.000120]  [num0: 10.000000] [num1 54.000000]
[Epoch 488/500] [Batch 320/676] [D loss: -0.005542] [G loss: -0.025156] [d1 loss: 0.016694] [d2 loss: 0.029723]  [sq d1 d2: 0.000170]  [num0: 17.000000] [num1 47.000000]
[Epoch 488/500] [Batch 340/676] [D loss: -0.014807] [G loss: 0.001652] [d1 loss: 0.077187] [d2 loss: 0.055072]  [sq d1 d2: 0.000489]  [num0: 17.000000] [num1 47.000000]
[Epoch 488/500] [Batch 360/676] [D loss: -0.033952] [G loss: 0.038299] [d1 loss: 0.086535] [d2 loss: 0.081719]  [sq d1 d2: 0.000023]  [num0: 12.000000] [num1 52.000000]
[Epoch 488/500] [Batch 380/676] [D loss: -0.048277] [G loss: 0.084653] [d1 loss: 0.093630] [d2 loss: 0.128006]  [sq d1 d2: 0.001182]  [num0: 20.000000] [num1 44.000000]
[Epoch 488/500] [Batch 400/676] [D loss: -0.017952] [G loss: 0.112273] [d1 loss: 0.042095] [d2 loss: 0.032431]  [sq d1 d2: 0.000093]  [num0: 15.000000] [num1 49.000000]

[Epoch 488/500] [Batch 420/676] [D loss: -0.017849] [G loss: 0.091063] [d1 loss: 0.021055] [d2 loss: 0.030697]  [sq d1 d2: 0.000093]  [num0: 18.000000] [num1 46.000000]
[Epoch 488/500] [Batch 440/676] [D loss: -0.012357] [G loss: 0.077544] [d1 loss: 0.084343] [d2 loss: 0.078044]  [sq d1 d2: 0.000040]  [num0: 19.000000] [num1 45.000000]
[Epoch 488/500] [Batch 460/676] [D loss: 0.024249] [G loss: 0.062255] [d1 loss: 0.014383] [d2 loss: 0.017950]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 488/500] [Batch 480/676] [D loss: -0.009958] [G loss: 0.015097] [d1 loss: 0.038324] [d2 loss: 0.045530]  [sq d1 d2: 0.000052]  [num0: 13.000000] [num1 51.000000]
[Epoch 488/500] [Batch 500/676] [D loss: 0.027030] [G loss: -0.026916] [d1 loss: 0.121887] [d2 loss: 0.117878]  [sq d1 d2: 0.000016]  [num0: 19.000000] [num1 45.000000]
[Epoch 488/500] [Batch 520/676] [D loss: 0.007307] [G loss: -0.061721] [d1 loss: 0.099631] [d2 loss: 0.096568]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 488/500] [Batch 540/676] [D loss: 0.006486] [G loss: -0.058536] [d1 loss: 0.021127] [d2 loss: 0.013805]  [sq d1 d2: 0.000054]  [num0: 14.000000] [num1 50.000000]
[Epoch 488/500] [Batch 560/676] [D loss: 0.002270] [G loss: -0.038131] [d1 loss: 0.170687] [d2 loss: 0.163598]  [sq d1 d2: 0.000050]  [num0: 13.000000] [num1 51.000000]
[Epoch 488/500] [Batch 580/676] [D loss: -0.007784] [G loss: -0.022825] [d1 loss: 0.036744] [d2 loss: 0.020997]  [sq d1 d2: 0.000248]  [num0: 17.000000] [num1 47.000000]
[Epoch 488/500] [Batch 600/676] [D loss: -0.013552] [G loss: -0.017901] [d1 loss: 0.067825] [d2 loss: 0.063936]  [sq d1 d2: 0.000015]  [num0: 11.000000] [num1 53.000000]
[Epoch 488/500] [Batch 620/676] [D loss: -0.029144] [G loss: -0.005464] [d1 loss: 0.059251] [d2 loss: 0.075216]  [sq d1 d2: 0.000255]  [num0: 11.000000] [num1 53.000000]
[Epoch 488/500] [Batch 640/676] [D loss: -0.016868] [G loss: -0.002288] [d1 loss: 0.027648] [d2 loss: 0.034786]  [sq d1 d2: 0.000051]  [num0: 17.000000] [num1 47.000000]
[Epoch 488/500] [Batch 660/676] [D loss: -0.036482] [G loss: 0.014694] [d1 loss: 0.023114] [d2 loss: 0.021551]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 0/676] [D loss: -0.000715] [G loss: 0.017625] [d1 loss: 0.147724] [d2 loss: 0.149847]  [sq d1 d2: 0.000005]  [num0: 19.000000] [num1 45.000000]
[Epoch 489/500] [Batch 20/676] [D loss: -0.003132] [G loss: 0.006703] [d1 loss: 0.042304] [d2 loss: 0.046268]  [sq d1 d2: 0.000016]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 40/676] [D loss: -0.013708] [G loss: 0.060270] [d1 loss: 0.079031] [d2 loss: 0.062408]  [sq d1 d2: 0.000276]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 60/676] [D loss: 0.021482] [G loss: -0.036005] [d1 loss: 0.075879] [d2 loss: 0.113890]  [sq d1 d2: 0.001445]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 80/676] [D loss: 0.007776] [G loss: 0.006971] [d1 loss: 0.022786] [d2 loss: 0.022962]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 100/676] [D loss: -0.000784] [G loss: 0.001920] [d1 loss: 0.057310] [d2 loss: 0.057670]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 489/500] [Batch 120/676] [D loss: 0.008472] [G loss: -0.005806] [d1 loss: 0.012523] [d2 loss: 0.016573]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 140/676] [D loss: -0.001289] [G loss: 0.003616] [d1 loss: 0.025965] [d2 loss: 0.026969]  [sq d1 d2: 0.000001]  [num0: 11.000000] [num1 53.000000]
[Epoch 489/500] [Batch 160/676] [D loss: 0.002263] [G loss: -0.006997] [d1 loss: 0.256293] [d2 loss: 0.194195]  [sq d1 d2: 0.003856]  [num0: 17.000000] [num1 47.000000]
[Epoch 489/500] [Batch 180/676] [D loss: -0.035353] [G loss: -0.046592] [d1 loss: 0.036719] [d2 loss: 0.033774]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 200/676] [D loss: -0.026067] [G loss: -0.084633] [d1 loss: 0.074875] [d2 loss: 0.069522]  [sq d1 d2: 0.000029]  [num0: 12.000000] [num1 52.000000]
[Epoch 489/500] [Batch 220/676] [D loss: -0.038363] [G loss: -0.098222] [d1 loss: 0.050444] [d2 loss: 0.056962]  [sq d1 d2: 0.000042]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 240/676] [D loss: -0.018579] [G loss: -0.100257] [d1 loss: 0.016154] [d2 loss: 0.016605]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 260/676] [D loss: -0.049458] [G loss: -0.101970] [d1 loss: 0.071152] [d2 loss: 0.093320]  [sq d1 d2: 0.000491]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 280/676] [D loss: -0.023688] [G loss: -0.096195] [d1 loss: 0.124084] [d2 loss: 0.158742]  [sq d1 d2: 0.001201]  [num0: 19.000000] [num1 45.000000]
[Epoch 489/500] [Batch 300/676] [D loss: -0.031732] [G loss: -0.115253] [d1 loss: 0.066957] [d2 loss: 0.055793]  [sq d1 d2: 0.000125]  [num0: 17.000000] [num1 47.000000]
[Epoch 489/500] [Batch 320/676] [D loss: 0.011103] [G loss: -0.120578] [d1 loss: 0.078477] [d2 loss: 0.076258]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 489/500] [Batch 340/676] [D loss: 0.007786] [G loss: -0.126897] [d1 loss: 0.057004] [d2 loss: 0.077603]  [sq d1 d2: 0.000424]  [num0: 18.000000] [num1 46.000000]
[Epoch 489/500] [Batch 360/676] [D loss: 0.004304] [G loss: -0.108231] [d1 loss: 0.061954] [d2 loss: 0.072740]  [sq d1 d2: 0.000116]  [num0: 21.000000] [num1 43.000000]
[Epoch 489/500] [Batch 380/676] [D loss: 0.006380] [G loss: -0.086748] [d1 loss: 0.079380] [d2 loss: 0.071075]  [sq d1 d2: 0.000069]  [num0: 15.000000] [num1 49.000000]
[Epoch 489/500] [Batch 400/676] [D loss: -0.008410] [G loss: -0.050023] [d1 loss: 0.042001] [d2 loss: 0.046782]  [sq d1 d2: 0.000023]  [num0: 17.000000] [num1 47.000000]
[Epoch 489/500] [Batch 420/676] [D loss: -0.010315] [G loss: -0.025127] [d1 loss: 0.108648] [d2 loss: 0.095854]  [sq d1 d2: 0.000164]  [num0: 15.000000] [num1 49.000000]
[Epoch 489/500] [Batch 440/676] [D loss: -0.016144] [G loss: 0.012307] [d1 loss: 0.067959] [d2 loss: 0.065964]  [sq d1 d2: 0.000004]  [num0: 16.000000] [num1 48.000000]
[Epoch 489/500] [Batch 460/676] [D loss: -0.028945] [G loss: 0.042115] [d1 loss: 0.065569] [d2 loss: 0.066867]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 480/676] [D loss: -0.050094] [G loss: 0.062073] [d1 loss: 0.039599] [d2 loss: 0.030272]  [sq d1 d2: 0.000087]  [num0: 15.000000] [num1 49.000000]
[Epoch 489/500] [Batch 500/676] [D loss: -0.025044] [G loss: 0.068453] [d1 loss: 0.078943] [d2 loss: 0.069802]  [sq d1 d2: 0.000084]  [num0: 17.000000] [num1 47.000000]
[Epoch 489/500] [Batch 520/676] [D loss: -0.033144] [G loss: 0.040699] [d1 loss: 0.031070] [d2 loss: 0.033589]  [sq d1 d2: 0.000006]  [num0: 13.000000] [num1 51.000000]
[Epoch 489/500] [Batch 540/676] [D loss: -0.019110] [G loss: 0.076031] [d1 loss: 0.025042] [d2 loss: 0.032710]  [sq d1 d2: 0.000059]  [num0: 18.000000] [num1 46.000000]
[Epoch 489/500] [Batch 560/676] [D loss: 0.006774] [G loss: 0.049546] [d1 loss: 0.038918] [d2 loss: 0.047473]  [sq d1 d2: 0.000073]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 580/676] [D loss: 0.025620] [G loss: 0.031244] [d1 loss: 0.098262] [d2 loss: 0.114048]  [sq d1 d2: 0.000249]  [num0: 17.000000] [num1 47.000000]
[Epoch 489/500] [Batch 600/676] [D loss: 0.016381] [G loss: 0.030027] [d1 loss: 0.036648] [d2 loss: 0.047150]  [sq d1 d2: 0.000110]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 620/676] [D loss: -0.006497] [G loss: 0.039262] [d1 loss: 0.021167] [d2 loss: 0.020135]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 489/500] [Batch 640/676] [D loss: 0.004628] [G loss: 0.009545] [d1 loss: 0.086586] [d2 loss: 0.063456]  [sq d1 d2: 0.000535]  [num0: 18.000000] [num1 46.000000]
[Epoch 489/500] [Batch 660/676] [D loss: -0.002394] [G loss: -0.019876] [d1 loss: 0.034969] [d2 loss: 0.041876]  [sq d1 d2: 0.000048]  [num0: 16.000000] [num1 48.000000]
[Epoch 490/500] [Batch 0/676] [D loss: -0.005691] [G loss: -0.032548] [d1 loss: 0.035381] [d2 loss: 0.051234]  [sq d1 d2: 0.000251]  [num0: 18.000000] [num1 46.000000]
[Epoch 490/500] [Batch 20/676] [D loss: -0.023555] [G loss: -0.055955] [d1 loss: 0.071904] [d2 loss: 0.060690]  [sq d1 d2: 0.000126]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 40/676] [D loss: -0.028780] [G loss: -0.116401] [d1 loss: 0.047777] [d2 loss: 0.045177]  [sq d1 d2: 0.000007]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 60/676] [D loss: -0.014803] [G loss: -0.129218] [d1 loss: 0.035360] [d2 loss: 0.041339]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]

[Epoch 490/500] [Batch 80/676] [D loss: -0.038659] [G loss: -0.133915] [d1 loss: 0.071142] [d2 loss: 0.057090]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 100/676] [D loss: -0.077338] [G loss: -0.128398] [d1 loss: 0.201763] [d2 loss: 0.245619]  [sq d1 d2: 0.001923]  [num0: 14.000000] [num1 50.000000]
[Epoch 490/500] [Batch 120/676] [D loss: -0.028668] [G loss: -0.117836] [d1 loss: 0.119387] [d2 loss: 0.100625]  [sq d1 d2: 0.000352]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 140/676] [D loss: -0.009587] [G loss: -0.131408] [d1 loss: 0.047667] [d2 loss: 0.056757]  [sq d1 d2: 0.000083]  [num0: 16.000000] [num1 48.000000]
[Epoch 490/500] [Batch 160/676] [D loss: 0.038033] [G loss: -0.133778] [d1 loss: 0.041679] [d2 loss: 0.055155]  [sq d1 d2: 0.000182]  [num0: 16.000000] [num1 48.000000]
[Epoch 490/500] [Batch 180/676] [D loss: 0.026399] [G loss: -0.100161] [d1 loss: 0.021012] [d2 loss: 0.034768]  [sq d1 d2: 0.000189]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 200/676] [D loss: 0.017248] [G loss: -0.067234] [d1 loss: 0.045610] [d2 loss: 0.052508]  [sq d1 d2: 0.000048]  [num0: 17.000000] [num1 47.000000]
[Epoch 490/500] [Batch 220/676] [D loss: 0.003894] [G loss: -0.058848] [d1 loss: 0.031151] [d2 loss: 0.030470]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 240/676] [D loss: -0.001709] [G loss: -0.033817] [d1 loss: 0.042063] [d2 loss: 0.056576]  [sq d1 d2: 0.000211]  [num0: 12.000000] [num1 52.000000]
[Epoch 490/500] [Batch 260/676] [D loss: -0.009242] [G loss: -0.033392] [d1 loss: 0.108327] [d2 loss: 0.100698]  [sq d1 d2: 0.000058]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 280/676] [D loss: -0.020401] [G loss: -0.020353] [d1 loss: 0.063238] [d2 loss: 0.048150]  [sq d1 d2: 0.000228]  [num0: 18.000000] [num1 46.000000]
[Epoch 490/500] [Batch 300/676] [D loss: -0.025363] [G loss: -0.017143] [d1 loss: 0.011384] [d2 loss: 0.015136]  [sq d1 d2: 0.000014]  [num0: 17.000000] [num1 47.000000]
[Epoch 490/500] [Batch 320/676] [D loss: -0.050651] [G loss: 0.028845] [d1 loss: 0.093606] [d2 loss: 0.065907]  [sq d1 d2: 0.000767]  [num0: 17.000000] [num1 47.000000]
[Epoch 490/500] [Batch 340/676] [D loss: -0.023890] [G loss: 0.034976] [d1 loss: 0.098943] [d2 loss: 0.041035]  [sq d1 d2: 0.003353]  [num0: 16.000000] [num1 48.000000]
[Epoch 490/500] [Batch 360/676] [D loss: -0.034491] [G loss: 0.025512] [d1 loss: 0.022978] [d2 loss: 0.031937]  [sq d1 d2: 0.000080]  [num0: 19.000000] [num1 45.000000]
[Epoch 490/500] [Batch 380/676] [D loss: -0.014612] [G loss: 0.033322] [d1 loss: 0.047077] [d2 loss: 0.050530]  [sq d1 d2: 0.000012]  [num0: 17.000000] [num1 47.000000]
[Epoch 490/500] [Batch 400/676] [D loss: 0.013724] [G loss: 0.047829] [d1 loss: 0.113143] [d2 loss: 0.111956]  [sq d1 d2: 0.000001]  [num0: 19.000000] [num1 45.000000]
[Epoch 490/500] [Batch 420/676] [D loss: 0.048292] [G loss: 0.071851] [d1 loss: 0.061391] [d2 loss: 0.055059]  [sq d1 d2: 0.000040]  [num0: 14.000000] [num1 50.000000]
[Epoch 490/500] [Batch 440/676] [D loss: 0.015351] [G loss: 0.029803] [d1 loss: 0.012990] [d2 loss: 0.023857]  [sq d1 d2: 0.000118]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 460/676] [D loss: 0.004331] [G loss: 0.022308] [d1 loss: 0.053287] [d2 loss: 0.078881]  [sq d1 d2: 0.000655]  [num0: 14.000000] [num1 50.000000]
[Epoch 490/500] [Batch 480/676] [D loss: 0.005179] [G loss: 0.001752] [d1 loss: 0.063631] [d2 loss: 0.054881]  [sq d1 d2: 0.000077]  [num0: 18.000000] [num1 46.000000]
[Epoch 490/500] [Batch 500/676] [D loss: -0.002938] [G loss: 0.001790] [d1 loss: 0.041354] [d2 loss: 0.055406]  [sq d1 d2: 0.000197]  [num0: 15.000000] [num1 49.000000]
[Epoch 490/500] [Batch 520/676] [D loss: -0.005416] [G loss: -0.015728] [d1 loss: 0.052361] [d2 loss: 0.057302]  [sq d1 d2: 0.000024]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 540/676] [D loss: -0.027127] [G loss: 0.003524] [d1 loss: 0.050385] [d2 loss: 0.047245]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 490/500] [Batch 560/676] [D loss: -0.032324] [G loss: 0.004866] [d1 loss: 0.015682] [d2 loss: 0.018758]  [sq d1 d2: 0.000009]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 580/676] [D loss: -0.032590] [G loss: -0.035163] [d1 loss: 0.067698] [d2 loss: 0.076666]  [sq d1 d2: 0.000080]  [num0: 18.000000] [num1 46.000000]
[Epoch 490/500] [Batch 600/676] [D loss: -0.034188] [G loss: -0.025383] [d1 loss: 0.101156] [d2 loss: 0.109179]  [sq d1 d2: 0.000064]  [num0: 13.000000] [num1 51.000000]
[Epoch 490/500] [Batch 620/676] [D loss: -0.016992] [G loss: -0.082835] [d1 loss: 0.080170] [d2 loss: 0.079733]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 490/500] [Batch 640/676] [D loss: -0.017256] [G loss: -0.106417] [d1 loss: 0.028926] [d2 loss: 0.024830]  [sq d1 d2: 0.000017]  [num0: 14.000000] [num1 50.000000]
[Epoch 490/500] [Batch 660/676] [D loss: 0.016322] [G loss: -0.090163] [d1 loss: 0.024614] [d2 loss: 0.024197]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 0/676] [D loss: -0.004394] [G loss: -0.076218] [d1 loss: 0.078498] [d2 loss: 0.084358]  [sq d1 d2: 0.000034]  [num0: 16.000000] [num1 48.000000]
[Epoch 491/500] [Batch 20/676] [D loss: 0.003409] [G loss: -0.052931] [d1 loss: 0.062865] [d2 loss: 0.053805]  [sq d1 d2: 0.000082]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 40/676] [D loss: 0.012170] [G loss: -0.022044] [d1 loss: 0.066799] [d2 loss: 0.075157]  [sq d1 d2: 0.000070]  [num0: 18.000000] [num1 46.000000]
[Epoch 491/500] [Batch 60/676] [D loss: 0.005324] [G loss: -0.013660] [d1 loss: 0.045804] [d2 loss: 0.066743]  [sq d1 d2: 0.000438]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 80/676] [D loss: -0.007525] [G loss: -0.013086] [d1 loss: 0.070122] [d2 loss: 0.090206]  [sq d1 d2: 0.000403]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 100/676] [D loss: -0.008398] [G loss: -0.004750] [d1 loss: 0.025268] [d2 loss: 0.022403]  [sq d1 d2: 0.000008]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 120/676] [D loss: -0.022022] [G loss: 0.005338] [d1 loss: 0.041012] [d2 loss: 0.056461]  [sq d1 d2: 0.000239]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 140/676] [D loss: -0.042494] [G loss: 0.016942] [d1 loss: 0.013975] [d2 loss: 0.015046]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 491/500] [Batch 160/676] [D loss: -0.033901] [G loss: 0.064680] [d1 loss: 0.056300] [d2 loss: 0.042416]  [sq d1 d2: 0.000193]  [num0: 12.000000] [num1 52.000000]
[Epoch 491/500] [Batch 180/676] [D loss: -0.037679] [G loss: 0.042023] [d1 loss: 0.073130] [d2 loss: 0.076309]  [sq d1 d2: 0.000010]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 200/676] [D loss: -0.002344] [G loss: 0.054316] [d1 loss: 0.027593] [d2 loss: 0.027280]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 491/500] [Batch 220/676] [D loss: 0.010433] [G loss: 0.061451] [d1 loss: 0.017895] [d2 loss: 0.017316]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 240/676] [D loss: -0.046032] [G loss: 0.077729] [d1 loss: 0.035221] [d2 loss: 0.045646]  [sq d1 d2: 0.000109]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 260/676] [D loss: -0.000219] [G loss: 0.087831] [d1 loss: 0.070594] [d2 loss: 0.067035]  [sq d1 d2: 0.000013]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 280/676] [D loss: 0.022752] [G loss: 0.058112] [d1 loss: 0.030273] [d2 loss: 0.029145]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 300/676] [D loss: 0.019192] [G loss: 0.085069] [d1 loss: 0.068408] [d2 loss: 0.066537]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 320/676] [D loss: 0.013919] [G loss: 0.074501] [d1 loss: 0.073693] [d2 loss: 0.074490]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 340/676] [D loss: 0.003394] [G loss: 0.034895] [d1 loss: 0.320738] [d2 loss: 0.248737]  [sq d1 d2: 0.005184]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 360/676] [D loss: -0.004129] [G loss: 0.021074] [d1 loss: 0.065715] [d2 loss: 0.069985]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 380/676] [D loss: -0.009791] [G loss: 0.014863] [d1 loss: 0.067823] [d2 loss: 0.067259]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 400/676] [D loss: -0.016814] [G loss: 0.038494] [d1 loss: 0.184050] [d2 loss: 0.190727]  [sq d1 d2: 0.000045]  [num0: 19.000000] [num1 45.000000]
[Epoch 491/500] [Batch 420/676] [D loss: -0.025279] [G loss: 0.065454] [d1 loss: 0.060366] [d2 loss: 0.052105]  [sq d1 d2: 0.000068]  [num0: 12.000000] [num1 52.000000]

[Epoch 491/500] [Batch 440/676] [D loss: -0.041959] [G loss: 0.105336] [d1 loss: 0.061379] [d2 loss: 0.041908]  [sq d1 d2: 0.000379]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 460/676] [D loss: -0.017035] [G loss: 0.127417] [d1 loss: 0.080479] [d2 loss: 0.095892]  [sq d1 d2: 0.000238]  [num0: 16.000000] [num1 48.000000]
[Epoch 491/500] [Batch 480/676] [D loss: -0.043662] [G loss: 0.115603] [d1 loss: 0.065192] [d2 loss: 0.060597]  [sq d1 d2: 0.000021]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 500/676] [D loss: 0.006045] [G loss: 0.102122] [d1 loss: 0.088108] [d2 loss: 0.079347]  [sq d1 d2: 0.000077]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 520/676] [D loss: 0.046422] [G loss: 0.002832] [d1 loss: 0.093258] [d2 loss: 0.073523]  [sq d1 d2: 0.000389]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 540/676] [D loss: -0.006368] [G loss: -0.056614] [d1 loss: 0.028781] [d2 loss: 0.026327]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 560/676] [D loss: 0.037203] [G loss: -0.077748] [d1 loss: 0.079795] [d2 loss: 0.080021]  [sq d1 d2: 0.000000]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 580/676] [D loss: 0.008442] [G loss: -0.063922] [d1 loss: 0.073576] [d2 loss: 0.102530]  [sq d1 d2: 0.000838]  [num0: 15.000000] [num1 49.000000]
[Epoch 491/500] [Batch 600/676] [D loss: 0.009810] [G loss: -0.047351] [d1 loss: 0.030320] [d2 loss: 0.039764]  [sq d1 d2: 0.000089]  [num0: 17.000000] [num1 47.000000]
[Epoch 491/500] [Batch 620/676] [D loss: 0.002819] [G loss: -0.021569] [d1 loss: 0.068796] [d2 loss: 0.078349]  [sq d1 d2: 0.000091]  [num0: 14.000000] [num1 50.000000]
[Epoch 491/500] [Batch 640/676] [D loss: -0.000816] [G loss: 0.007587] [d1 loss: 0.069972] [d2 loss: 0.081278]  [sq d1 d2: 0.000128]  [num0: 19.000000] [num1 45.000000]
[Epoch 491/500] [Batch 660/676] [D loss: -0.014719] [G loss: 0.044057] [d1 loss: 0.033096] [d2 loss: 0.041502]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 0/676] [D loss: -0.031387] [G loss: 0.089546] [d1 loss: 0.018272] [d2 loss: 0.022748]  [sq d1 d2: 0.000020]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 20/676] [D loss: -0.034344] [G loss: 0.112491] [d1 loss: 0.079562] [d2 loss: 0.069909]  [sq d1 d2: 0.000093]  [num0: 9.000000] [num1 55.000000]
[Epoch 492/500] [Batch 40/676] [D loss: -0.023058] [G loss: 0.106567] [d1 loss: 0.050723] [d2 loss: 0.043254]  [sq d1 d2: 0.000056]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 60/676] [D loss: -0.052752] [G loss: 0.093198] [d1 loss: 0.016163] [d2 loss: 0.031451]  [sq d1 d2: 0.000234]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 80/676] [D loss: -0.032438] [G loss: 0.085593] [d1 loss: 0.029179] [d2 loss: 0.031581]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 100/676] [D loss: -0.031672] [G loss: 0.047657] [d1 loss: 0.098597] [d2 loss: 0.110344]  [sq d1 d2: 0.000138]  [num0: 14.000000] [num1 50.000000]
[Epoch 492/500] [Batch 120/676] [D loss: 0.007787] [G loss: 0.018688] [d1 loss: 0.064322] [d2 loss: 0.060951]  [sq d1 d2: 0.000011]  [num0: 18.000000] [num1 46.000000]
[Epoch 492/500] [Batch 140/676] [D loss: 0.022779] [G loss: -0.050954] [d1 loss: 0.138968] [d2 loss: 0.084262]  [sq d1 d2: 0.002993]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 160/676] [D loss: 0.002100] [G loss: -0.078877] [d1 loss: 0.036415] [d2 loss: 0.037366]  [sq d1 d2: 0.000001]  [num0: 14.000000] [num1 50.000000]
[Epoch 492/500] [Batch 180/676] [D loss: 0.001990] [G loss: -0.108763] [d1 loss: 0.049132] [d2 loss: 0.044031]  [sq d1 d2: 0.000026]  [num0: 16.000000] [num1 48.000000]
[Epoch 492/500] [Batch 200/676] [D loss: -0.002449] [G loss: -0.097730] [d1 loss: 0.041397] [d2 loss: 0.032947]  [sq d1 d2: 0.000071]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 220/676] [D loss: 0.006040] [G loss: -0.099768] [d1 loss: 0.101732] [d2 loss: 0.104838]  [sq d1 d2: 0.000010]  [num0: 18.000000] [num1 46.000000]
[Epoch 492/500] [Batch 240/676] [D loss: -0.000461] [G loss: -0.099880] [d1 loss: 0.054509] [d2 loss: 0.055202]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 260/676] [D loss: -0.003310] [G loss: -0.117110] [d1 loss: 0.119214] [d2 loss: 0.071578]  [sq d1 d2: 0.002269]  [num0: 20.000000] [num1 44.000000]
[Epoch 492/500] [Batch 280/676] [D loss: -0.004184] [G loss: -0.102666] [d1 loss: 0.064377] [d2 loss: 0.056531]  [sq d1 d2: 0.000062]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 300/676] [D loss: -0.027757] [G loss: -0.095303] [d1 loss: 0.143367] [d2 loss: 0.119767]  [sq d1 d2: 0.000557]  [num0: 18.000000] [num1 46.000000]
[Epoch 492/500] [Batch 320/676] [D loss: -0.021533] [G loss: -0.109977] [d1 loss: 0.038929] [d2 loss: 0.047429]  [sq d1 d2: 0.000072]  [num0: 19.000000] [num1 45.000000]
[Epoch 492/500] [Batch 340/676] [D loss: -0.034330] [G loss: -0.144489] [d1 loss: 0.056524] [d2 loss: 0.052497]  [sq d1 d2: 0.000016]  [num0: 16.000000] [num1 48.000000]
[Epoch 492/500] [Batch 360/676] [D loss: -0.034099] [G loss: -0.173009] [d1 loss: 0.037083] [d2 loss: 0.037714]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 380/676] [D loss: -0.030189] [G loss: -0.206135] [d1 loss: 0.059555] [d2 loss: 0.049770]  [sq d1 d2: 0.000096]  [num0: 18.000000] [num1 46.000000]
[Epoch 492/500] [Batch 400/676] [D loss: -0.014872] [G loss: -0.207356] [d1 loss: 0.127138] [d2 loss: 0.088495]  [sq d1 d2: 0.001493]  [num0: 14.000000] [num1 50.000000]
[Epoch 492/500] [Batch 420/676] [D loss: -0.008009] [G loss: -0.165835] [d1 loss: 0.031515] [d2 loss: 0.025723]  [sq d1 d2: 0.000034]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 440/676] [D loss: 0.003281] [G loss: -0.101959] [d1 loss: 0.138319] [d2 loss: 0.128191]  [sq d1 d2: 0.000103]  [num0: 13.000000] [num1 51.000000]
[Epoch 492/500] [Batch 460/676] [D loss: 0.013666] [G loss: -0.058859] [d1 loss: 0.123319] [d2 loss: 0.096881]  [sq d1 d2: 0.000699]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 480/676] [D loss: 0.002266] [G loss: -0.053902] [d1 loss: 0.101919] [d2 loss: 0.089210]  [sq d1 d2: 0.000162]  [num0: 16.000000] [num1 48.000000]
[Epoch 492/500] [Batch 500/676] [D loss: 0.003889] [G loss: -0.049645] [d1 loss: 0.017068] [d2 loss: 0.022301]  [sq d1 d2: 0.000027]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 520/676] [D loss: -0.001495] [G loss: -0.063317] [d1 loss: 0.055925] [d2 loss: 0.059290]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 540/676] [D loss: -0.005158] [G loss: -0.056911] [d1 loss: 0.128268] [d2 loss: 0.148153]  [sq d1 d2: 0.000395]  [num0: 18.000000] [num1 46.000000]
[Epoch 492/500] [Batch 560/676] [D loss: -0.010308] [G loss: -0.072006] [d1 loss: 0.053103] [d2 loss: 0.084949]  [sq d1 d2: 0.001014]  [num0: 16.000000] [num1 48.000000]
[Epoch 492/500] [Batch 580/676] [D loss: -0.013045] [G loss: -0.129167] [d1 loss: 0.059681] [d2 loss: 0.061498]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 600/676] [D loss: -0.017087] [G loss: -0.139639] [d1 loss: 0.052505] [d2 loss: 0.056661]  [sq d1 d2: 0.000017]  [num0: 16.000000] [num1 48.000000]
[Epoch 492/500] [Batch 620/676] [D loss: -0.024128] [G loss: -0.145790] [d1 loss: 0.092350] [d2 loss: 0.068394]  [sq d1 d2: 0.000574]  [num0: 17.000000] [num1 47.000000]
[Epoch 492/500] [Batch 640/676] [D loss: 0.001623] [G loss: -0.133970] [d1 loss: 0.049869] [d2 loss: 0.033818]  [sq d1 d2: 0.000258]  [num0: 15.000000] [num1 49.000000]
[Epoch 492/500] [Batch 660/676] [D loss: -0.018266] [G loss: -0.111791] [d1 loss: 0.205116] [d2 loss: 0.176906]  [sq d1 d2: 0.000796]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 0/676] [D loss: -0.020059] [G loss: -0.110789] [d1 loss: 0.040259] [d2 loss: 0.041704]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 20/676] [D loss: 0.015481] [G loss: -0.080721] [d1 loss: 0.039340] [d2 loss: 0.039368]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 493/500] [Batch 40/676] [D loss: 0.011774] [G loss: -0.060602] [d1 loss: 0.013518] [d2 loss: 0.012160]  [sq d1 d2: 0.000002]  [num0: 14.000000] [num1 50.000000]
[Epoch 493/500] [Batch 60/676] [D loss: 0.041120] [G loss: -0.060654] [d1 loss: 0.019760] [d2 loss: 0.023274]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 80/676] [D loss: 0.007154] [G loss: -0.036309] [d1 loss: 0.018164] [d2 loss: 0.014655]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]

[Epoch 493/500] [Batch 100/676] [D loss: 0.007655] [G loss: -0.021762] [d1 loss: 0.010397] [d2 loss: 0.009728]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 120/676] [D loss: 0.003667] [G loss: -0.001974] [d1 loss: 0.077194] [d2 loss: 0.086824]  [sq d1 d2: 0.000093]  [num0: 17.000000] [num1 47.000000]
[Epoch 493/500] [Batch 140/676] [D loss: -0.000976] [G loss: 0.015747] [d1 loss: 0.030205] [d2 loss: 0.052056]  [sq d1 d2: 0.000477]  [num0: 13.000000] [num1 51.000000]
[Epoch 493/500] [Batch 160/676] [D loss: -0.004139] [G loss: 0.026015] [d1 loss: 0.044594] [d2 loss: 0.042327]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 493/500] [Batch 180/676] [D loss: -0.010403] [G loss: 0.036163] [d1 loss: 0.026289] [d2 loss: 0.031209]  [sq d1 d2: 0.000024]  [num0: 20.000000] [num1 44.000000]
[Epoch 493/500] [Batch 200/676] [D loss: -0.025780] [G loss: 0.052738] [d1 loss: 0.066359] [d2 loss: 0.078764]  [sq d1 d2: 0.000154]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 220/676] [D loss: -0.012095] [G loss: 0.053706] [d1 loss: 0.066993] [d2 loss: 0.054357]  [sq d1 d2: 0.000160]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 240/676] [D loss: -0.012435] [G loss: 0.034046] [d1 loss: 0.047774] [d2 loss: 0.067071]  [sq d1 d2: 0.000372]  [num0: 13.000000] [num1 51.000000]
[Epoch 493/500] [Batch 260/676] [D loss: -0.011010] [G loss: 0.059291] [d1 loss: 0.124316] [d2 loss: 0.081031]  [sq d1 d2: 0.001874]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 280/676] [D loss: 0.015246] [G loss: 0.057024] [d1 loss: 0.023404] [d2 loss: 0.024390]  [sq d1 d2: 0.000001]  [num0: 13.000000] [num1 51.000000]
[Epoch 493/500] [Batch 300/676] [D loss: -0.006901] [G loss: 0.033402] [d1 loss: 0.024221] [d2 loss: 0.031139]  [sq d1 d2: 0.000048]  [num0: 14.000000] [num1 50.000000]
[Epoch 493/500] [Batch 320/676] [D loss: -0.002076] [G loss: 0.034667] [d1 loss: 0.037703] [d2 loss: 0.040879]  [sq d1 d2: 0.000010]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 340/676] [D loss: 0.007587] [G loss: 0.027572] [d1 loss: 0.118891] [d2 loss: 0.090032]  [sq d1 d2: 0.000833]  [num0: 14.000000] [num1 50.000000]
[Epoch 493/500] [Batch 360/676] [D loss: 0.014742] [G loss: -0.001349] [d1 loss: 0.019266] [d2 loss: 0.020731]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 380/676] [D loss: 0.004839] [G loss: 0.005027] [d1 loss: 0.055912] [d2 loss: 0.068108]  [sq d1 d2: 0.000149]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 400/676] [D loss: 0.005387] [G loss: 0.013295] [d1 loss: 0.075897] [d2 loss: 0.073917]  [sq d1 d2: 0.000004]  [num0: 12.000000] [num1 52.000000]
[Epoch 493/500] [Batch 420/676] [D loss: -0.001303] [G loss: 0.010349] [d1 loss: 0.100145] [d2 loss: 0.094427]  [sq d1 d2: 0.000033]  [num0: 18.000000] [num1 46.000000]
[Epoch 493/500] [Batch 440/676] [D loss: -0.000016] [G loss: 0.002164] [d1 loss: 0.033634] [d2 loss: 0.039323]  [sq d1 d2: 0.000032]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 460/676] [D loss: -0.000153] [G loss: -0.009522] [d1 loss: 0.057051] [d2 loss: 0.064002]  [sq d1 d2: 0.000048]  [num0: 18.000000] [num1 46.000000]
[Epoch 493/500] [Batch 480/676] [D loss: -0.012170] [G loss: -0.014323] [d1 loss: 0.040891] [d2 loss: 0.043908]  [sq d1 d2: 0.000009]  [num0: 18.000000] [num1 46.000000]
[Epoch 493/500] [Batch 500/676] [D loss: -0.017354] [G loss: -0.007124] [d1 loss: 0.036483] [d2 loss: 0.028389]  [sq d1 d2: 0.000066]  [num0: 17.000000] [num1 47.000000]
[Epoch 493/500] [Batch 520/676] [D loss: -0.030293] [G loss: -0.014878] [d1 loss: 0.039460] [d2 loss: 0.029216]  [sq d1 d2: 0.000105]  [num0: 18.000000] [num1 46.000000]
[Epoch 493/500] [Batch 540/676] [D loss: -0.002146] [G loss: -0.042453] [d1 loss: 0.049443] [d2 loss: 0.048092]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 560/676] [D loss: 0.016827] [G loss: -0.062881] [d1 loss: 0.047445] [d2 loss: 0.052920]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 580/676] [D loss: -0.034820] [G loss: -0.067859] [d1 loss: 0.057200] [d2 loss: 0.070417]  [sq d1 d2: 0.000175]  [num0: 13.000000] [num1 51.000000]
[Epoch 493/500] [Batch 600/676] [D loss: -0.002000] [G loss: -0.059952] [d1 loss: 0.087862] [d2 loss: 0.099351]  [sq d1 d2: 0.000132]  [num0: 19.000000] [num1 45.000000]
[Epoch 493/500] [Batch 620/676] [D loss: -0.003576] [G loss: -0.016273] [d1 loss: 0.094386] [d2 loss: 0.070219]  [sq d1 d2: 0.000584]  [num0: 16.000000] [num1 48.000000]
[Epoch 493/500] [Batch 640/676] [D loss: 0.009119] [G loss: 0.008352] [d1 loss: 0.025897] [d2 loss: 0.023773]  [sq d1 d2: 0.000005]  [num0: 15.000000] [num1 49.000000]
[Epoch 493/500] [Batch 660/676] [D loss: 0.004691] [G loss: -0.001453] [d1 loss: 0.095948] [d2 loss: 0.079198]  [sq d1 d2: 0.000281]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 0/676] [D loss: 0.009020] [G loss: 0.001438] [d1 loss: 0.034304] [d2 loss: 0.043998]  [sq d1 d2: 0.000094]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 20/676] [D loss: -0.001149] [G loss: 0.004464] [d1 loss: 0.070786] [d2 loss: 0.053888]  [sq d1 d2: 0.000286]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 40/676] [D loss: 0.001756] [G loss: 0.005670] [d1 loss: 0.059332] [d2 loss: 0.060990]  [sq d1 d2: 0.000003]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 60/676] [D loss: 0.000184] [G loss: 0.000372] [d1 loss: 0.058204] [d2 loss: 0.062637]  [sq d1 d2: 0.000020]  [num0: 18.000000] [num1 46.000000]
[Epoch 494/500] [Batch 80/676] [D loss: -0.005002] [G loss: 0.009346] [d1 loss: 0.014364] [d2 loss: 0.025188]  [sq d1 d2: 0.000117]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 100/676] [D loss: -0.014025] [G loss: 0.016438] [d1 loss: 0.064864] [d2 loss: 0.071931]  [sq d1 d2: 0.000050]  [num0: 11.000000] [num1 53.000000]
[Epoch 494/500] [Batch 120/676] [D loss: -0.003236] [G loss: -0.003756] [d1 loss: 0.015211] [d2 loss: 0.017187]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 140/676] [D loss: -0.013022] [G loss: 0.016585] [d1 loss: 0.057913] [d2 loss: 0.086968]  [sq d1 d2: 0.000844]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 160/676] [D loss: -0.028734] [G loss: 0.008414] [d1 loss: 0.194130] [d2 loss: 0.169273]  [sq d1 d2: 0.000618]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 180/676] [D loss: 0.013347] [G loss: -0.007976] [d1 loss: 0.059020] [d2 loss: 0.077284]  [sq d1 d2: 0.000334]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 200/676] [D loss: 0.005523] [G loss: 0.035735] [d1 loss: 0.063966] [d2 loss: 0.088292]  [sq d1 d2: 0.000592]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 220/676] [D loss: -0.033909] [G loss: -0.003291] [d1 loss: 0.067322] [d2 loss: 0.080177]  [sq d1 d2: 0.000165]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 240/676] [D loss: 0.018881] [G loss: -0.028097] [d1 loss: 0.043850] [d2 loss: 0.046266]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 260/676] [D loss: 0.007377] [G loss: -0.008401] [d1 loss: 0.069540] [d2 loss: 0.069067]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 280/676] [D loss: 0.019641] [G loss: -0.016456] [d1 loss: 0.053529] [d2 loss: 0.057906]  [sq d1 d2: 0.000019]  [num0: 18.000000] [num1 46.000000]
[Epoch 494/500] [Batch 300/676] [D loss: 0.006448] [G loss: -0.002099] [d1 loss: 0.029948] [d2 loss: 0.029772]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 320/676] [D loss: 0.004067] [G loss: -0.003821] [d1 loss: 0.114243] [d2 loss: 0.111200]  [sq d1 d2: 0.000009]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 340/676] [D loss: 0.000931] [G loss: -0.005989] [d1 loss: 0.099894] [d2 loss: 0.091462]  [sq d1 d2: 0.000071]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 360/676] [D loss: -0.000643] [G loss: -0.008061] [d1 loss: 0.033076] [d2 loss: 0.048559]  [sq d1 d2: 0.000240]  [num0: 18.000000] [num1 46.000000]
[Epoch 494/500] [Batch 380/676] [D loss: -0.004009] [G loss: -0.004109] [d1 loss: 0.049886] [d2 loss: 0.051134]  [sq d1 d2: 0.000002]  [num0: 13.000000] [num1 51.000000]
[Epoch 494/500] [Batch 400/676] [D loss: -0.012877] [G loss: 0.001894] [d1 loss: 0.056579] [d2 loss: 0.052693]  [sq d1 d2: 0.000015]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 420/676] [D loss: -0.000829] [G loss: 0.007173] [d1 loss: 0.036248] [d2 loss: 0.049404]  [sq d1 d2: 0.000173]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 440/676] [D loss: 0.005536] [G loss: 0.022984] [d1 loss: 0.037594] [d2 loss: 0.023614]  [sq d1 d2: 0.000195]  [num0: 16.000000] [num1 48.000000]

[Epoch 494/500] [Batch 460/676] [D loss: -0.026310] [G loss: -0.003298] [d1 loss: 0.017902] [d2 loss: 0.022890]  [sq d1 d2: 0.000025]  [num0: 19.000000] [num1 45.000000]
[Epoch 494/500] [Batch 480/676] [D loss: -0.037798] [G loss: 0.044668] [d1 loss: 0.050330] [d2 loss: 0.039751]  [sq d1 d2: 0.000112]  [num0: 18.000000] [num1 46.000000]
[Epoch 494/500] [Batch 500/676] [D loss: 0.017218] [G loss: 0.009374] [d1 loss: 0.064388] [d2 loss: 0.077799]  [sq d1 d2: 0.000180]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 520/676] [D loss: -0.002290] [G loss: -0.014214] [d1 loss: 0.026853] [d2 loss: 0.024821]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 540/676] [D loss: 0.013173] [G loss: 0.014052] [d1 loss: 0.039462] [d2 loss: 0.051860]  [sq d1 d2: 0.000154]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 560/676] [D loss: 0.002150] [G loss: 0.023873] [d1 loss: 0.096221] [d2 loss: 0.119353]  [sq d1 d2: 0.000535]  [num0: 17.000000] [num1 47.000000]
[Epoch 494/500] [Batch 580/676] [D loss: 0.001596] [G loss: 0.007615] [d1 loss: 0.079685] [d2 loss: 0.103420]  [sq d1 d2: 0.000563]  [num0: 15.000000] [num1 49.000000]
[Epoch 494/500] [Batch 600/676] [D loss: 0.011131] [G loss: -0.009816] [d1 loss: 0.082945] [d2 loss: 0.085660]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 620/676] [D loss: 0.008302] [G loss: -0.007155] [d1 loss: 0.038117] [d2 loss: 0.044525]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 494/500] [Batch 640/676] [D loss: 0.001595] [G loss: -0.035105] [d1 loss: 0.052857] [d2 loss: 0.061590]  [sq d1 d2: 0.000076]  [num0: 14.000000] [num1 50.000000]
[Epoch 494/500] [Batch 660/676] [D loss: -0.004157] [G loss: -0.045429] [d1 loss: 0.281950] [d2 loss: 0.233485]  [sq d1 d2: 0.002349]  [num0: 17.000000] [num1 47.000000]
[Epoch 495/500] [Batch 0/676] [D loss: -0.004135] [G loss: -0.049047] [d1 loss: 0.056707] [d2 loss: 0.063802]  [sq d1 d2: 0.000050]  [num0: 17.000000] [num1 47.000000]
[Epoch 495/500] [Batch 20/676] [D loss: -0.009309] [G loss: -0.066362] [d1 loss: 0.061574] [d2 loss: 0.076375]  [sq d1 d2: 0.000219]  [num0: 13.000000] [num1 51.000000]
[Epoch 495/500] [Batch 40/676] [D loss: -0.021807] [G loss: -0.071755] [d1 loss: 0.086537] [d2 loss: 0.047467]  [sq d1 d2: 0.001526]  [num0: 17.000000] [num1 47.000000]
[Epoch 495/500] [Batch 60/676] [D loss: -0.018426] [G loss: -0.059224] [d1 loss: 0.037321] [d2 loss: 0.052339]  [sq d1 d2: 0.000226]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 80/676] [D loss: 0.016145] [G loss: -0.065854] [d1 loss: 0.077805] [d2 loss: 0.060470]  [sq d1 d2: 0.000301]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 100/676] [D loss: 0.016496] [G loss: -0.073784] [d1 loss: 0.042654] [d2 loss: 0.038375]  [sq d1 d2: 0.000018]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 120/676] [D loss: -0.006729] [G loss: -0.065317] [d1 loss: 0.057779] [d2 loss: 0.061330]  [sq d1 d2: 0.000013]  [num0: 14.000000] [num1 50.000000]
[Epoch 495/500] [Batch 140/676] [D loss: 0.006960] [G loss: -0.068680] [d1 loss: 0.111044] [d2 loss: 0.124847]  [sq d1 d2: 0.000191]  [num0: 20.000000] [num1 44.000000]
[Epoch 495/500] [Batch 160/676] [D loss: -0.003042] [G loss: -0.086131] [d1 loss: 0.049341] [d2 loss: 0.045831]  [sq d1 d2: 0.000012]  [num0: 12.000000] [num1 52.000000]
[Epoch 495/500] [Batch 180/676] [D loss: -0.002871] [G loss: -0.052428] [d1 loss: 0.051261] [d2 loss: 0.066724]  [sq d1 d2: 0.000239]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 200/676] [D loss: 0.013341] [G loss: -0.049317] [d1 loss: 0.069773] [d2 loss: 0.060902]  [sq d1 d2: 0.000079]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 220/676] [D loss: -0.000063] [G loss: -0.057004] [d1 loss: 0.036758] [d2 loss: 0.034822]  [sq d1 d2: 0.000004]  [num0: 14.000000] [num1 50.000000]
[Epoch 495/500] [Batch 240/676] [D loss: 0.002259] [G loss: -0.049180] [d1 loss: 0.092085] [d2 loss: 0.069187]  [sq d1 d2: 0.000524]  [num0: 14.000000] [num1 50.000000]
[Epoch 495/500] [Batch 260/676] [D loss: -0.000863] [G loss: -0.033445] [d1 loss: 0.111072] [d2 loss: 0.109966]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 280/676] [D loss: -0.003972] [G loss: -0.027975] [d1 loss: 0.073564] [d2 loss: 0.079901]  [sq d1 d2: 0.000040]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 300/676] [D loss: -0.011498] [G loss: -0.044453] [d1 loss: 0.033357] [d2 loss: 0.040619]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 495/500] [Batch 320/676] [D loss: -0.020859] [G loss: -0.062536] [d1 loss: 0.035063] [d2 loss: 0.032515]  [sq d1 d2: 0.000006]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 340/676] [D loss: -0.024347] [G loss: -0.041525] [d1 loss: 0.028068] [d2 loss: 0.028657]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 360/676] [D loss: -0.020043] [G loss: -0.037382] [d1 loss: 0.062099] [d2 loss: 0.054156]  [sq d1 d2: 0.000063]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 380/676] [D loss: -0.035772] [G loss: -0.041313] [d1 loss: 0.062274] [d2 loss: 0.067346]  [sq d1 d2: 0.000026]  [num0: 14.000000] [num1 50.000000]
[Epoch 495/500] [Batch 400/676] [D loss: -0.025140] [G loss: -0.059876] [d1 loss: 0.123654] [d2 loss: 0.180972]  [sq d1 d2: 0.003285]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 420/676] [D loss: -0.013083] [G loss: -0.025129] [d1 loss: 0.062102] [d2 loss: 0.063285]  [sq d1 d2: 0.000001]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 440/676] [D loss: -0.000431] [G loss: -0.000530] [d1 loss: 0.086291] [d2 loss: 0.095836]  [sq d1 d2: 0.000091]  [num0: 17.000000] [num1 47.000000]
[Epoch 495/500] [Batch 460/676] [D loss: 0.010549] [G loss: 0.036830] [d1 loss: 0.007632] [d2 loss: 0.006084]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 480/676] [D loss: 0.015042] [G loss: 0.071906] [d1 loss: 0.036244] [d2 loss: 0.043083]  [sq d1 d2: 0.000047]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 500/676] [D loss: 0.005546] [G loss: 0.055598] [d1 loss: 0.045299] [d2 loss: 0.041945]  [sq d1 d2: 0.000011]  [num0: 14.000000] [num1 50.000000]
[Epoch 495/500] [Batch 520/676] [D loss: 0.005154] [G loss: 0.034726] [d1 loss: 0.050769] [d2 loss: 0.049941]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 495/500] [Batch 540/676] [D loss: -0.003351] [G loss: 0.032392] [d1 loss: 0.038856] [d2 loss: 0.035147]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 560/676] [D loss: -0.003062] [G loss: 0.019370] [d1 loss: 0.020728] [d2 loss: 0.022880]  [sq d1 d2: 0.000005]  [num0: 18.000000] [num1 46.000000]
[Epoch 495/500] [Batch 580/676] [D loss: -0.007669] [G loss: -0.014299] [d1 loss: 0.042256] [d2 loss: 0.038103]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 495/500] [Batch 600/676] [D loss: -0.009451] [G loss: -0.053726] [d1 loss: 0.102273] [d2 loss: 0.109923]  [sq d1 d2: 0.000059]  [num0: 12.000000] [num1 52.000000]
[Epoch 495/500] [Batch 620/676] [D loss: -0.008144] [G loss: -0.068700] [d1 loss: 0.074262] [d2 loss: 0.081941]  [sq d1 d2: 0.000059]  [num0: 13.000000] [num1 51.000000]
[Epoch 495/500] [Batch 640/676] [D loss: -0.011289] [G loss: -0.076587] [d1 loss: 0.091700] [d2 loss: 0.066509]  [sq d1 d2: 0.000635]  [num0: 16.000000] [num1 48.000000]
[Epoch 495/500] [Batch 660/676] [D loss: -0.055864] [G loss: -0.082009] [d1 loss: 0.075456] [d2 loss: 0.057900]  [sq d1 d2: 0.000308]  [num0: 14.000000] [num1 50.000000]
[Epoch 496/500] [Batch 0/676] [D loss: -0.013291] [G loss: -0.115414] [d1 loss: 0.037098] [d2 loss: 0.067344]  [sq d1 d2: 0.000915]  [num0: 19.000000] [num1 45.000000]
[Epoch 496/500] [Batch 20/676] [D loss: -0.024558] [G loss: -0.121250] [d1 loss: 0.074881] [d2 loss: 0.092159]  [sq d1 d2: 0.000299]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 40/676] [D loss: -0.024559] [G loss: -0.144053] [d1 loss: 0.115948] [d2 loss: 0.132107]  [sq d1 d2: 0.000261]  [num0: 9.000000] [num1 55.000000]
[Epoch 496/500] [Batch 60/676] [D loss: -0.012944] [G loss: -0.151007] [d1 loss: 0.025192] [d2 loss: 0.023530]  [sq d1 d2: 0.000003]  [num0: 14.000000] [num1 50.000000]
[Epoch 496/500] [Batch 80/676] [D loss: 0.007883] [G loss: -0.164574] [d1 loss: 0.013960] [d2 loss: 0.016448]  [sq d1 d2: 0.000006]  [num0: 14.000000] [num1 50.000000]
[Epoch 496/500] [Batch 100/676] [D loss: 0.005314] [G loss: -0.151667] [d1 loss: 0.045443] [d2 loss: 0.036479]  [sq d1 d2: 0.000080]  [num0: 13.000000] [num1 51.000000]
[Epoch 496/500] [Batch 120/676] [D loss: 0.008426] [G loss: -0.111041] [d1 loss: 0.085100] [d2 loss: 0.080765]  [sq d1 d2: 0.000019]  [num0: 17.000000] [num1 47.000000]

[Epoch 496/500] [Batch 140/676] [D loss: 0.002875] [G loss: -0.062951] [d1 loss: 0.083070] [d2 loss: 0.092054]  [sq d1 d2: 0.000081]  [num0: 14.000000] [num1 50.000000]
[Epoch 496/500] [Batch 160/676] [D loss: 0.000140] [G loss: -0.070653] [d1 loss: 0.060513] [d2 loss: 0.054526]  [sq d1 d2: 0.000036]  [num0: 18.000000] [num1 46.000000]
[Epoch 496/500] [Batch 180/676] [D loss: -0.002559] [G loss: -0.063129] [d1 loss: 0.118099] [d2 loss: 0.140021]  [sq d1 d2: 0.000481]  [num0: 15.000000] [num1 49.000000]
[Epoch 496/500] [Batch 200/676] [D loss: -0.008208] [G loss: -0.045638] [d1 loss: 0.045749] [d2 loss: 0.055729]  [sq d1 d2: 0.000100]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 220/676] [D loss: -0.006111] [G loss: -0.040218] [d1 loss: 0.085630] [d2 loss: 0.094868]  [sq d1 d2: 0.000085]  [num0: 19.000000] [num1 45.000000]
[Epoch 496/500] [Batch 240/676] [D loss: -0.028663] [G loss: -0.029925] [d1 loss: 0.128769] [d2 loss: 0.134385]  [sq d1 d2: 0.000032]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 260/676] [D loss: 0.001168] [G loss: 0.020102] [d1 loss: 0.076088] [d2 loss: 0.084998]  [sq d1 d2: 0.000079]  [num0: 18.000000] [num1 46.000000]
[Epoch 496/500] [Batch 280/676] [D loss: -0.006338] [G loss: 0.042620] [d1 loss: 0.081764] [d2 loss: 0.074347]  [sq d1 d2: 0.000055]  [num0: 15.000000] [num1 49.000000]
[Epoch 496/500] [Batch 300/676] [D loss: -0.005590] [G loss: 0.059899] [d1 loss: 0.032218] [d2 loss: 0.027319]  [sq d1 d2: 0.000024]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 320/676] [D loss: -0.008203] [G loss: 0.058512] [d1 loss: 0.034502] [d2 loss: 0.075847]  [sq d1 d2: 0.001709]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 340/676] [D loss: -0.001268] [G loss: 0.030224] [d1 loss: 0.085135] [d2 loss: 0.111793]  [sq d1 d2: 0.000711]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 360/676] [D loss: 0.006827] [G loss: 0.014732] [d1 loss: 0.042963] [d2 loss: 0.042909]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 496/500] [Batch 380/676] [D loss: 0.002323] [G loss: 0.030075] [d1 loss: 0.056251] [d2 loss: 0.053354]  [sq d1 d2: 0.000008]  [num0: 13.000000] [num1 51.000000]
[Epoch 496/500] [Batch 400/676] [D loss: 0.013046] [G loss: 0.030957] [d1 loss: 0.111921] [d2 loss: 0.093123]  [sq d1 d2: 0.000353]  [num0: 18.000000] [num1 46.000000]
[Epoch 496/500] [Batch 420/676] [D loss: 0.007631] [G loss: 0.046024] [d1 loss: 0.028835] [d2 loss: 0.032647]  [sq d1 d2: 0.000015]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 440/676] [D loss: 0.000161] [G loss: 0.041930] [d1 loss: 0.048740] [d2 loss: 0.052523]  [sq d1 d2: 0.000014]  [num0: 12.000000] [num1 52.000000]
[Epoch 496/500] [Batch 460/676] [D loss: 0.000193] [G loss: 0.024293] [d1 loss: 0.062482] [d2 loss: 0.075712]  [sq d1 d2: 0.000175]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 480/676] [D loss: -0.006336] [G loss: 0.014155] [d1 loss: 0.020837] [d2 loss: 0.019621]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 496/500] [Batch 500/676] [D loss: -0.003575] [G loss: 0.047558] [d1 loss: 0.042504] [d2 loss: 0.048996]  [sq d1 d2: 0.000042]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 520/676] [D loss: -0.007302] [G loss: 0.057794] [d1 loss: 0.024436] [d2 loss: 0.022372]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 540/676] [D loss: -0.025343] [G loss: 0.101451] [d1 loss: 0.038256] [d2 loss: 0.047182]  [sq d1 d2: 0.000080]  [num0: 17.000000] [num1 47.000000]
[Epoch 496/500] [Batch 560/676] [D loss: -0.021581] [G loss: 0.159056] [d1 loss: 0.090123] [d2 loss: 0.057715]  [sq d1 d2: 0.001050]  [num0: 18.000000] [num1 46.000000]
[Epoch 496/500] [Batch 580/676] [D loss: -0.003918] [G loss: 0.214918] [d1 loss: 0.042490] [d2 loss: 0.047639]  [sq d1 d2: 0.000027]  [num0: 14.000000] [num1 50.000000]
[Epoch 496/500] [Batch 600/676] [D loss: 0.005431] [G loss: 0.194993] [d1 loss: 0.026288] [d2 loss: 0.020411]  [sq d1 d2: 0.000035]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 620/676] [D loss: -0.018275] [G loss: 0.170463] [d1 loss: 0.068655] [d2 loss: 0.054399]  [sq d1 d2: 0.000203]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 640/676] [D loss: 0.010668] [G loss: 0.142529] [d1 loss: 0.019844] [d2 loss: 0.015283]  [sq d1 d2: 0.000021]  [num0: 16.000000] [num1 48.000000]
[Epoch 496/500] [Batch 660/676] [D loss: 0.011151] [G loss: 0.060696] [d1 loss: 0.068070] [d2 loss: 0.068623]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 0/676] [D loss: 0.010199] [G loss: 0.045606] [d1 loss: 0.050987] [d2 loss: 0.047563]  [sq d1 d2: 0.000012]  [num0: 21.000000] [num1 43.000000]
[Epoch 497/500] [Batch 20/676] [D loss: 0.000180] [G loss: 0.035874] [d1 loss: 0.079564] [d2 loss: 0.096135]  [sq d1 d2: 0.000275]  [num0: 14.000000] [num1 50.000000]
[Epoch 497/500] [Batch 40/676] [D loss: -0.001632] [G loss: 0.015456] [d1 loss: 0.021208] [d2 loss: 0.023030]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 497/500] [Batch 60/676] [D loss: -0.005903] [G loss: 0.034769] [d1 loss: 0.062240] [d2 loss: 0.053407]  [sq d1 d2: 0.000078]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 80/676] [D loss: -0.011444] [G loss: 0.058145] [d1 loss: 0.055987] [d2 loss: 0.070016]  [sq d1 d2: 0.000197]  [num0: 13.000000] [num1 51.000000]
[Epoch 497/500] [Batch 100/676] [D loss: -0.025696] [G loss: 0.076110] [d1 loss: 0.074856] [d2 loss: 0.081683]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 497/500] [Batch 120/676] [D loss: -0.026405] [G loss: 0.090506] [d1 loss: 0.085211] [d2 loss: 0.071806]  [sq d1 d2: 0.000180]  [num0: 13.000000] [num1 51.000000]
[Epoch 497/500] [Batch 140/676] [D loss: -0.015898] [G loss: 0.112093] [d1 loss: 0.048491] [d2 loss: 0.046687]  [sq d1 d2: 0.000003]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 160/676] [D loss: -0.023596] [G loss: 0.053714] [d1 loss: 0.062204] [d2 loss: 0.057971]  [sq d1 d2: 0.000018]  [num0: 14.000000] [num1 50.000000]
[Epoch 497/500] [Batch 180/676] [D loss: -0.030962] [G loss: 0.064606] [d1 loss: 0.085719] [d2 loss: 0.088971]  [sq d1 d2: 0.000011]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 200/676] [D loss: -0.001750] [G loss: -0.003141] [d1 loss: 0.010662] [d2 loss: 0.012029]  [sq d1 d2: 0.000002]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 220/676] [D loss: 0.025301] [G loss: -0.000871] [d1 loss: 0.043894] [d2 loss: 0.038674]  [sq d1 d2: 0.000027]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 240/676] [D loss: 0.000832] [G loss: 0.005032] [d1 loss: 0.042117] [d2 loss: 0.049661]  [sq d1 d2: 0.000057]  [num0: 14.000000] [num1 50.000000]
[Epoch 497/500] [Batch 260/676] [D loss: 0.006706] [G loss: -0.001599] [d1 loss: 0.067056] [d2 loss: 0.060852]  [sq d1 d2: 0.000038]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 280/676] [D loss: 0.009596] [G loss: -0.013688] [d1 loss: 0.072002] [d2 loss: 0.078148]  [sq d1 d2: 0.000038]  [num0: 11.000000] [num1 53.000000]
[Epoch 497/500] [Batch 300/676] [D loss: -0.000639] [G loss: -0.026630] [d1 loss: 0.060343] [d2 loss: 0.049799]  [sq d1 d2: 0.000111]  [num0: 14.000000] [num1 50.000000]
[Epoch 497/500] [Batch 320/676] [D loss: -0.000661] [G loss: -0.057310] [d1 loss: 0.024567] [d2 loss: 0.024614]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 497/500] [Batch 340/676] [D loss: -0.010164] [G loss: -0.107046] [d1 loss: 0.023015] [d2 loss: 0.019586]  [sq d1 d2: 0.000012]  [num0: 18.000000] [num1 46.000000]
[Epoch 497/500] [Batch 360/676] [D loss: -0.016080] [G loss: -0.148667] [d1 loss: 0.046049] [d2 loss: 0.051215]  [sq d1 d2: 0.000027]  [num0: 15.000000] [num1 49.000000]
[Epoch 497/500] [Batch 380/676] [D loss: -0.007421] [G loss: -0.126468] [d1 loss: 0.106744] [d2 loss: 0.100584]  [sq d1 d2: 0.000038]  [num0: 18.000000] [num1 46.000000]
[Epoch 497/500] [Batch 400/676] [D loss: -0.056045] [G loss: -0.090208] [d1 loss: 0.046880] [d2 loss: 0.054479]  [sq d1 d2: 0.000058]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 420/676] [D loss: -0.026666] [G loss: -0.063004] [d1 loss: 0.049000] [d2 loss: 0.049545]  [sq d1 d2: 0.000000]  [num0: 18.000000] [num1 46.000000]
[Epoch 497/500] [Batch 440/676] [D loss: -0.066495] [G loss: -0.090127] [d1 loss: 0.058115] [d2 loss: 0.066478]  [sq d1 d2: 0.000070]  [num0: 15.000000] [num1 49.000000]
[Epoch 497/500] [Batch 460/676] [D loss: -0.016974] [G loss: -0.107265] [d1 loss: 0.078283] [d2 loss: 0.067612]  [sq d1 d2: 0.000114]  [num0: 11.000000] [num1 53.000000]
[Epoch 497/500] [Batch 480/676] [D loss: 0.014184] [G loss: -0.186212] [d1 loss: 0.076338] [d2 loss: 0.088172]  [sq d1 d2: 0.000140]  [num0: 17.000000] [num1 47.000000]

[Epoch 497/500] [Batch 500/676] [D loss: 0.003439] [G loss: -0.120432] [d1 loss: 0.040383] [d2 loss: 0.041814]  [sq d1 d2: 0.000002]  [num0: 22.000000] [num1 42.000000]
[Epoch 497/500] [Batch 520/676] [D loss: 0.021710] [G loss: -0.097440] [d1 loss: 0.126607] [d2 loss: 0.129605]  [sq d1 d2: 0.000009]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 540/676] [D loss: 0.010302] [G loss: -0.080546] [d1 loss: 0.035112] [d2 loss: 0.025320]  [sq d1 d2: 0.000096]  [num0: 16.000000] [num1 48.000000]
[Epoch 497/500] [Batch 560/676] [D loss: 0.000382] [G loss: -0.079646] [d1 loss: 0.080489] [d2 loss: 0.093124]  [sq d1 d2: 0.000160]  [num0: 14.000000] [num1 50.000000]
[Epoch 497/500] [Batch 580/676] [D loss: -0.008638] [G loss: -0.080509] [d1 loss: 0.047180] [d2 loss: 0.029113]  [sq d1 d2: 0.000326]  [num0: 13.000000] [num1 51.000000]
[Epoch 497/500] [Batch 600/676] [D loss: -0.020620] [G loss: -0.064760] [d1 loss: 0.064641] [d2 loss: 0.054479]  [sq d1 d2: 0.000103]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 620/676] [D loss: -0.016615] [G loss: -0.084764] [d1 loss: 0.080579] [d2 loss: 0.069937]  [sq d1 d2: 0.000113]  [num0: 17.000000] [num1 47.000000]
[Epoch 497/500] [Batch 640/676] [D loss: -0.042032] [G loss: -0.095734] [d1 loss: 0.023136] [d2 loss: 0.017645]  [sq d1 d2: 0.000030]  [num0: 15.000000] [num1 49.000000]
[Epoch 497/500] [Batch 660/676] [D loss: -0.025381] [G loss: -0.121294] [d1 loss: 0.068734] [d2 loss: 0.097323]  [sq d1 d2: 0.000817]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 0/676] [D loss: -0.046630] [G loss: -0.103170] [d1 loss: 0.055857] [d2 loss: 0.048673]  [sq d1 d2: 0.000052]  [num0: 18.000000] [num1 46.000000]
[Epoch 498/500] [Batch 20/676] [D loss: 0.000519] [G loss: -0.074451] [d1 loss: 0.106987] [d2 loss: 0.047618]  [sq d1 d2: 0.003525]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 40/676] [D loss: -0.004039] [G loss: -0.030861] [d1 loss: 0.086091] [d2 loss: 0.083423]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 60/676] [D loss: 0.024893] [G loss: -0.014882] [d1 loss: 0.013244] [d2 loss: 0.014821]  [sq d1 d2: 0.000002]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 80/676] [D loss: 0.007590] [G loss: -0.045187] [d1 loss: 0.134404] [d2 loss: 0.038611]  [sq d1 d2: 0.009176]  [num0: 19.000000] [num1 45.000000]
[Epoch 498/500] [Batch 100/676] [D loss: 0.006445] [G loss: -0.006092] [d1 loss: 0.074201] [d2 loss: 0.059378]  [sq d1 d2: 0.000220]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 120/676] [D loss: 0.010243] [G loss: 0.029017] [d1 loss: 0.132735] [d2 loss: 0.132138]  [sq d1 d2: 0.000000]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 140/676] [D loss: 0.006599] [G loss: 0.040083] [d1 loss: 0.014197] [d2 loss: 0.015000]  [sq d1 d2: 0.000001]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 160/676] [D loss: 0.000286] [G loss: 0.021186] [d1 loss: 0.048581] [d2 loss: 0.045395]  [sq d1 d2: 0.000010]  [num0: 12.000000] [num1 52.000000]
[Epoch 498/500] [Batch 180/676] [D loss: -0.002293] [G loss: 0.000027] [d1 loss: 0.045020] [d2 loss: 0.061876]  [sq d1 d2: 0.000284]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 200/676] [D loss: -0.008987] [G loss: -0.026295] [d1 loss: 0.027004] [d2 loss: 0.022843]  [sq d1 d2: 0.000017]  [num0: 19.000000] [num1 45.000000]
[Epoch 498/500] [Batch 220/676] [D loss: -0.011640] [G loss: -0.017018] [d1 loss: 0.031858] [d2 loss: 0.019240]  [sq d1 d2: 0.000159]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 240/676] [D loss: -0.017974] [G loss: -0.034034] [d1 loss: 0.016562] [d2 loss: 0.009404]  [sq d1 d2: 0.000051]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 260/676] [D loss: -0.020321] [G loss: 0.001021] [d1 loss: 0.028169] [d2 loss: 0.042553]  [sq d1 d2: 0.000207]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 280/676] [D loss: -0.023764] [G loss: 0.031623] [d1 loss: 0.067072] [d2 loss: 0.061075]  [sq d1 d2: 0.000036]  [num0: 15.000000] [num1 49.000000]
[Epoch 498/500] [Batch 300/676] [D loss: -0.008832] [G loss: 0.092927] [d1 loss: 0.093749] [d2 loss: 0.076833]  [sq d1 d2: 0.000286]  [num0: 13.000000] [num1 51.000000]
[Epoch 498/500] [Batch 320/676] [D loss: -0.018661] [G loss: 0.059700] [d1 loss: 0.013567] [d2 loss: 0.011457]  [sq d1 d2: 0.000004]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 340/676] [D loss: 0.027615] [G loss: 0.093243] [d1 loss: 0.010211] [d2 loss: 0.009284]  [sq d1 d2: 0.000001]  [num0: 15.000000] [num1 49.000000]
[Epoch 498/500] [Batch 360/676] [D loss: 0.009985] [G loss: 0.059773] [d1 loss: 0.033654] [d2 loss: 0.029768]  [sq d1 d2: 0.000015]  [num0: 13.000000] [num1 51.000000]
[Epoch 498/500] [Batch 380/676] [D loss: 0.001513] [G loss: 0.043437] [d1 loss: 0.053902] [d2 loss: 0.039783]  [sq d1 d2: 0.000199]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 400/676] [D loss: 0.006207] [G loss: 0.032077] [d1 loss: 0.046150] [d2 loss: 0.051520]  [sq d1 d2: 0.000029]  [num0: 18.000000] [num1 46.000000]
[Epoch 498/500] [Batch 420/676] [D loss: 0.006991] [G loss: 0.016280] [d1 loss: 0.041477] [d2 loss: 0.049358]  [sq d1 d2: 0.000062]  [num0: 17.000000] [num1 47.000000]
[Epoch 498/500] [Batch 440/676] [D loss: 0.002332] [G loss: -0.008777] [d1 loss: 0.061178] [d2 loss: 0.043126]  [sq d1 d2: 0.000326]  [num0: 11.000000] [num1 53.000000]
[Epoch 498/500] [Batch 460/676] [D loss: -0.000189] [G loss: -0.019266] [d1 loss: 0.035773] [d2 loss: 0.036210]  [sq d1 d2: 0.000000]  [num0: 13.000000] [num1 51.000000]
[Epoch 498/500] [Batch 480/676] [D loss: -0.003472] [G loss: -0.034377] [d1 loss: 0.015928] [d2 loss: 0.008644]  [sq d1 d2: 0.000053]  [num0: 19.000000] [num1 45.000000]
[Epoch 498/500] [Batch 500/676] [D loss: -0.014473] [G loss: -0.058572] [d1 loss: 0.029674] [d2 loss: 0.047113]  [sq d1 d2: 0.000304]  [num0: 15.000000] [num1 49.000000]
[Epoch 498/500] [Batch 520/676] [D loss: -0.011975] [G loss: -0.084070] [d1 loss: 0.017474] [d2 loss: 0.024726]  [sq d1 d2: 0.000053]  [num0: 18.000000] [num1 46.000000]
[Epoch 498/500] [Batch 540/676] [D loss: -0.020768] [G loss: -0.098685] [d1 loss: 0.123774] [d2 loss: 0.102646]  [sq d1 d2: 0.000446]  [num0: 13.000000] [num1 51.000000]
[Epoch 498/500] [Batch 560/676] [D loss: -0.026016] [G loss: -0.097314] [d1 loss: 0.033712] [d2 loss: 0.031160]  [sq d1 d2: 0.000007]  [num0: 16.000000] [num1 48.000000]
[Epoch 498/500] [Batch 580/676] [D loss: -0.016825] [G loss: -0.131803] [d1 loss: 0.045536] [d2 loss: 0.054163]  [sq d1 d2: 0.000074]  [num0: 12.000000] [num1 52.000000]
[Epoch 498/500] [Batch 600/676] [D loss: 0.032135] [G loss: -0.106283] [d1 loss: 0.035154] [d2 loss: 0.040818]  [sq d1 d2: 0.000032]  [num0: 13.000000] [num1 51.000000]
[Epoch 498/500] [Batch 620/676] [D loss: 0.022605] [G loss: -0.073437] [d1 loss: 0.037340] [d2 loss: 0.054406]  [sq d1 d2: 0.000291]  [num0: 12.000000] [num1 52.000000]
[Epoch 498/500] [Batch 640/676] [D loss: 0.035242] [G loss: -0.070426] [d1 loss: 0.062218] [d2 loss: 0.082016]  [sq d1 d2: 0.000392]  [num0: 14.000000] [num1 50.000000]
[Epoch 498/500] [Batch 660/676] [D loss: -0.012682] [G loss: -0.081459] [d1 loss: 0.036058] [d2 loss: 0.041041]  [sq d1 d2: 0.000025]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 0/676] [D loss: -0.021065] [G loss: -0.095207] [d1 loss: 0.053180] [d2 loss: 0.046357]  [sq d1 d2: 0.000047]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 20/676] [D loss: 0.012484] [G loss: -0.050099] [d1 loss: 0.054925] [d2 loss: 0.046030]  [sq d1 d2: 0.000079]  [num0: 17.000000] [num1 47.000000]
[Epoch 499/500] [Batch 40/676] [D loss: 0.000749] [G loss: -0.013863] [d1 loss: 0.081747] [d2 loss: 0.081463]  [sq d1 d2: 0.000000]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 60/676] [D loss: -0.001871] [G loss: 0.000192] [d1 loss: 0.004944] [d2 loss: 0.007228]  [sq d1 d2: 0.000005]  [num0: 14.000000] [num1 50.000000]
[Epoch 499/500] [Batch 80/676] [D loss: -0.005989] [G loss: 0.005629] [d1 loss: 0.049046] [d2 loss: 0.056766]  [sq d1 d2: 0.000060]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 100/676] [D loss: 0.000027] [G loss: 0.026123] [d1 loss: 0.042961] [d2 loss: 0.057865]  [sq d1 d2: 0.000222]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 120/676] [D loss: -0.002699] [G loss: 0.082310] [d1 loss: 0.048261] [d2 loss: 0.055099]  [sq d1 d2: 0.000047]  [num0: 12.000000] [num1 52.000000]
[Epoch 499/500] [Batch 140/676] [D loss: -0.015007] [G loss: 0.112211] [d1 loss: 0.057636] [d2 loss: 0.042982]  [sq d1 d2: 0.000215]  [num0: 15.000000] [num1 49.000000]

[Epoch 499/500] [Batch 160/676] [D loss: -0.020882] [G loss: 0.150318] [d1 loss: 0.057749] [d2 loss: 0.056483]  [sq d1 d2: 0.000002]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 180/676] [D loss: -0.049311] [G loss: 0.137348] [d1 loss: 0.010778] [d2 loss: 0.007305]  [sq d1 d2: 0.000012]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 200/676] [D loss: 0.013969] [G loss: 0.101921] [d1 loss: 0.051689] [d2 loss: 0.052032]  [sq d1 d2: 0.000000]  [num0: 17.000000] [num1 47.000000]
[Epoch 499/500] [Batch 220/676] [D loss: -0.000090] [G loss: 0.136794] [d1 loss: 0.034458] [d2 loss: 0.043019]  [sq d1 d2: 0.000073]  [num0: 19.000000] [num1 45.000000]
[Epoch 499/500] [Batch 240/676] [D loss: 0.036218] [G loss: 0.091719] [d1 loss: 0.102958] [d2 loss: 0.096559]  [sq d1 d2: 0.000041]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 260/676] [D loss: 0.011624] [G loss: 0.079865] [d1 loss: 0.025998] [d2 loss: 0.030245]  [sq d1 d2: 0.000018]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 280/676] [D loss: 0.004666] [G loss: 0.058659] [d1 loss: 0.052743] [d2 loss: 0.046195]  [sq d1 d2: 0.000043]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 300/676] [D loss: 0.004970] [G loss: 0.061075] [d1 loss: 0.051131] [d2 loss: 0.063701]  [sq d1 d2: 0.000158]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 320/676] [D loss: -0.003731] [G loss: 0.051294] [d1 loss: 0.065090] [d2 loss: 0.047517]  [sq d1 d2: 0.000309]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 340/676] [D loss: -0.000995] [G loss: 0.025855] [d1 loss: 0.102283] [d2 loss: 0.072884]  [sq d1 d2: 0.000864]  [num0: 14.000000] [num1 50.000000]
[Epoch 499/500] [Batch 360/676] [D loss: -0.008316] [G loss: 0.019710] [d1 loss: 0.035597] [d2 loss: 0.040450]  [sq d1 d2: 0.000024]  [num0: 12.000000] [num1 52.000000]
[Epoch 499/500] [Batch 380/676] [D loss: -0.009507] [G loss: 0.000795] [d1 loss: 0.022571] [d2 loss: 0.024628]  [sq d1 d2: 0.000004]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 400/676] [D loss: -0.013358] [G loss: -0.003960] [d1 loss: 0.039877] [d2 loss: 0.030106]  [sq d1 d2: 0.000095]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 420/676] [D loss: -0.039404] [G loss: -0.037398] [d1 loss: 0.029814] [d2 loss: 0.031873]  [sq d1 d2: 0.000004]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 440/676] [D loss: -0.033337] [G loss: -0.074682] [d1 loss: 0.040255] [d2 loss: 0.046623]  [sq d1 d2: 0.000041]  [num0: 14.000000] [num1 50.000000]
[Epoch 499/500] [Batch 460/676] [D loss: -0.017265] [G loss: -0.099774] [d1 loss: 0.027072] [d2 loss: 0.028164]  [sq d1 d2: 0.000001]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 480/676] [D loss: 0.017453] [G loss: -0.070236] [d1 loss: 0.039411] [d2 loss: 0.043088]  [sq d1 d2: 0.000014]  [num0: 16.000000] [num1 48.000000]
[Epoch 499/500] [Batch 500/676] [D loss: 0.003709] [G loss: -0.046470] [d1 loss: 0.039959] [d2 loss: 0.025042]  [sq d1 d2: 0.000223]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 520/676] [D loss: 0.002988] [G loss: -0.048243] [d1 loss: 0.085161] [d2 loss: 0.081142]  [sq d1 d2: 0.000016]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 540/676] [D loss: 0.005148] [G loss: -0.015465] [d1 loss: 0.048980] [d2 loss: 0.050716]  [sq d1 d2: 0.000003]  [num0: 18.000000] [num1 46.000000]
[Epoch 499/500] [Batch 560/676] [D loss: 0.002539] [G loss: -0.014544] [d1 loss: 0.052474] [d2 loss: 0.065585]  [sq d1 d2: 0.000172]  [num0: 13.000000] [num1 51.000000]
[Epoch 499/500] [Batch 580/676] [D loss: 0.006850] [G loss: 0.020908] [d1 loss: 0.033958] [d2 loss: 0.032536]  [sq d1 d2: 0.000002]  [num0: 15.000000] [num1 49.000000]
[Epoch 499/500] [Batch 600/676] [D loss: -0.000611] [G loss: 0.026731] [d1 loss: 0.032079] [d2 loss: 0.039672]  [sq d1 d2: 0.000058]  [num0: 19.000000] [num1 45.000000]
[Epoch 499/500] [Batch 620/676] [D loss: -0.009960] [G loss: 0.042088] [d1 loss: 0.050564] [d2 loss: 0.047054]  [sq d1 d2: 0.000012]  [num0: 14.000000] [num1 50.000000]
[Epoch 499/500] [Batch 640/676] [D loss: -0.009417] [G loss: 0.032699] [d1 loss: 0.044379] [d2 loss: 0.036436]  [sq d1 d2: 0.000063]  [num0: 17.000000] [num1 47.000000]
[Epoch 499/500] [Batch 660/676] [D loss: -0.007771] [G loss: 0.047707] [d1 loss: 0.077272] [d2 loss: 0.087569]  [sq d1 d2: 0.000106]  [num0: 15.000000] [num1 49.000000]

In [22]:
import pandas as pd
q1 = pd.DataFrame(q1)
q1.columns = dataset_train.columns
q1['income'] = q1['income']>0.5
res = eval_model(q1, dataset_test)
print(res)

{'precision': 0.812200956937799, 'recall': 0.9029255319148937, 'auroc': 0.6349305078929307, 'dp': 0.11800063453606757, 'ftu': 0.014000000000000012, 'confMatrix': array([[ 182,  314],
       [ 146, 1358]])}

## Save data

In [ ]:
import pickle

In [ ]:
with open("results/data_"+str(repNum)+'.p','wb') as f:
    pickle.dump(results,f)